### ISSUE TITLE
vinyl: abort alter in alter.cc

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#1006]
It's possible to "trigger" alter by replace in a system space. Sophia should not allow this either. The check in schema.lua should be replaced with a check in the engine api

**Comment by pmwkaa** [comment]
As i understand any system space access is done via box.schema. On replace trigger will be called if one will try to access the space directly.

Could you be more specific about index API changes and the place in alter.cc it should be called.

**Comment by kostja** [comment]
I can do box.space._index:insert{}, bypassing box.schema, and crash the server or get a silly error message. 
Your fix breaks encapsulation, all interaction with engine is done via engine API. For example, each alter calls handler->onAlter, which you can just throw from. Or you can add another hook into alter_space_do(), in which you will throw.

**Comment by rtsisyk** [comment]
Fixed by #1647
