### ISSUE TITLE
Memtx mvcc poorly handles DDL

### ISSUE THREAD

**Issue by drewdzzz** [tarantool/tarantool#10146]
Creating or altering (and, potentially, dropping) an index in parallel with other requests can lead to crash (see #10096, #10097, #10147) or violate isolation (#10171). Crashes happen because mvcc does not handle index DDL at all, so right after an index is altered, some internal structures can point to the old index which is more likely to be already deleted, or when a new index is created, some old `stories` do not take it into account and have no links for it so it breaks internal invariant - we rely on the fact that tuple have stories for all indexes. Violation of isolation happens because we delete all mvcc stories related to the space when committing DDL.

It seems that handling of DDL was poorly conceived and now it needs to be completely re-designed.

**Comment by alyapunov** [comment]
Actually mvcc handles all DDL, see `memtx_tx_abort_all_for_ddl`. I bet the problem is deeper.

**Comment by drewdzzz** [comment]
Function `memtx_tx_abort_all_for_ddl` aborts all active transactions on preparing DDL, but the problem is that new transactions (that began after DDL is prepared) see outdated stories, that don't know about the new index.
