### ISSUE TITLE
Provide a method to get instance vclock after all writes in progress are finished

### ISSUE THREAD

**Issue by sergepetrenko** [tarantool/tarantool#10142]
It's common practice to implement master switch via the following steps:
1. Issue `box.cfg{read_only = true}` on the old master
2. Remember lsn of the last written transaction on that master(`box.info.lsn`)
3. Wait for replication up to that `lsn` on the new desired master
4. Issue `box.cfg{read_only = false}` on the new master

These steps are supposed to guarantee that in case both old and new masters are alive the switch happens only after the new master receives everything that was written by the old master. But there's a problem: `box.cfg{read_only = true}` only affects the transactions which aren't yet sent to WAL. IOW, setting `box.cfg{read_only = true}` doesn't guarantee that `box.info.lsn` will stop growing immediately. It might still need some time to reflect the last writes.

<details><summary>Reproducer:</summary>

```lua
-- Step 1.
-- Start a Tarantool built in debug mode
box.cfg{}
-- Step 2.
box.schema.space.create('test'):create_index('pk')
-- Step 3.
box.error.injection.set('ERRINJ_WAL_DELAY', true)
-- Step 4.
require('fiber').new(function() box.space.test:insert{1} end)
-- Step 5.
box.cfg{read_only=true}
-- Step 6.
box.info.lsn -- Will show something like 2.
-- Step 7.
box.error.injection.set('ERRINJ_WAL_DELAY', false)
-- Step 8.
box.info.lsn -- Will show a bigger value. For example, 3.
```

</details>

Let's provide a `box.ctl` method to sync WAL. For example, `box.ctl.wal_sync()`. It'll issue the C `wal_sync` method and make sure that all the ongoing writes are finished. With this implementing failover correctly will become possible: the user will have to perform `box.ctl.wal_sync()` before remembering `box.info.lsn`.

**Comment by sergepetrenko** [comment]
See also #9937.

**Comment by R-omk** [comment]
Will it be possible to use this to read committed data even if we don’t enable MVCC ?

Now we use something like this as a workround:

box.begin()
space:select()  --    read data
space:udapte( { 'non exitsts key' }, {})  
box.commit()   --   We are waiting for confirmation based on indirect evidence that the read data was committed.

**Comment by R-omk** [comment]
@sergepetrenko 

> wal_sync yields, so it won't be possible to call it inside an open transaction

I don’t need it inside the transaction, it’s enough to understand that the writes that were in the queue have been completed, this will indicate that any previous operations do not read dirty data.  .. if I'm not mistaken..

> But it seems this would be worse performance-wise than the hack you propose.

my hack assumes that there will always be a dummy write, but if there is nothing in the queue it don't have to wait for anything at all, this should immediately indicate that any previous readings were not dirty.

My issue is precisely to more effectively handle situations when it is known in advance that all writing transactions have already been completed.

For example, I could extend  my hack and make a counter of open and completed transactions, increase it at the beginning of the transaction and decrease it in the oncommit/rollback  trigger, in this case it need to make a dummy write ops only if the counter is not zero.  .. it seems like it should work, again, unless I'm missing something..

**Comment by sergepetrenko** [comment]
@R-omk 

> @sergepetrenko
> 
> > wal_sync yields, so it won't be possible to call it inside an open transaction
> 
> I don’t need it inside the transaction, it’s enough to understand that the writes that were in the queue have been completed, this will indicate that any previous operations do not read dirty data. .. if I'm not mistaken..
> 
> > But it seems this would be worse performance-wise than the hack you propose.
> 
> my hack assumes that there will always be a dummy write, but if there is nothing in the queue it don't have to wait for anything at all, this should immediately indicate that any previous readings were not dirty.
> 
> My issue is precisely to more effectively handle situations when it is known in advance that all writing transactions have already been completed.
> 
> For example, I could extend my hack and make a counter of open and completed transactions, increase it at the beginning of the transaction and decrease it in the oncommit/rollback trigger, in this case it need to make a dummy write ops only if the counter is not zero. .. it seems like it should work, again, unless I'm missing something..

Ok, I see. It seems you could do the following then:
1. Perform a bunch of reads from a single fiber without yields
2. Issue `wal_sync` from outside the transaction. If it completes successfully, everything you have read is certainly written. In case it fails, it doesn't guarantee that the reads you performed are bad, but still you can't be sure anymore.

It seems this will stay correct as long as you do `wal_sync` after any amount of reads from any amount of fibers as long as `wal_sync` gets executed in the same event loop iteration as the reads (how to achieve this? Some `fiber.wakeup()` `fiber_reschedule()` magic probably.
