### ISSUE TITLE
Tuple field aliases

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#1014]
If a space is formattted (see `space:format{}`), make field names available in Lua, i.e. make it
possible to query tuple fields via aliases (`t['alias']` rather than `t[1]`).

See also https://github.com/tarantool/tarantool/issues/1285 "Tuple field access via JSON path" for nested tuple fields (fields within a field) and https://github.com/tarantool/tarantool/issues/1309 "Speed up non-indexed tuple field access"

**Comment by rtsisyk** [comment]
#2652 is done, this ticket is not blocked anymore.

**Comment by rtsisyk** [comment]
1.7.5-144-g5f1a74c71
