### ISSUE TITLE
sophia: assertion if nine indexed fields

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#1015]
I have Ubuntu 12.04 and Tarantool 1.6, pulled from source today.

I make these requests:
"
 box.schema.create_space('t',{engine='sophia'})
 box.space.t:create_index('primary',{parts={1,'str',2,'str',3,'str',4,'str',5,'str',6,'str',7,'str',8,'str',9,'str'}})
 box.space.t:insert{'1','2','3','4','5','6','7','8','9'}
"

The result is:
"
tarantool>  box.space.t:insert{'1','2','3','4','5','6','7','8','9'}
sophia/environment/se_v.c:43: se_vsetpart: Assertion `part->pos < (int)(sizeof(v->keyv) / sizeof(sfv))' failed.
Aborted (core dumped)
"

**Comment by kostja** [comment]
Pushed.
