### ISSUE TITLE
sophia: behaviour of multi-part indexes

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#1016]
I have Ubuntu 12.04 and Tarantool 1.6, pulled from source today.

I make these requests:
"
box.schema.create_space('T',{engine='sophia'})
box.space.T:create_index('T',{parts={1,'str',2,'str',3,'str'}})
box.space.T:insert{'1','2','3'}
box.space.T:insert{'1','2','0'}
box.space.T.index.T:select({'1','2',nil},{iterator='GT'})
"

The answer I get is: one tuple.
That's clearly wrong, but I don't know what is the right answer:
zero tuples (that's what I get with memtx),
or two tuples (as if nil is less than any non-nil),
or an error (as if nil may not be compared with non-nil).

**Comment by kostja** [comment]
Pushed.
