### ISSUE TITLE
yaml: encoding-decoding transforms a string into a number

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#10164]
**System info**

Tarantool 3.1.0-entrypoint-135-gdeaa9599b

* OS: Linux
* OS Version: Gentoo
* Architecture: amd64

**Bug description**

The `yaml` built-in module encodes a string in such a way that decoding it using the same module gives a number.

I don't know whether we should adjust encoding or decoding.

**Steps to reproduce**

```lua
#!/usr/bin/env tarantool

local yaml = require('yaml')

local data = {hostname = '9e0260492063'}
local encoded = yaml.encode(data)
local decoded = yaml.decode(encoded)
print(decoded.hostname)
```

How to run:

Just type `tarantool test.lua`.

**Actual behavior**

```
$ tarantool test.lua
inf
```

**Expected behavior**

```
$ tarantool test.lua
9e0260492063
```

**Additional info**

Tarantool 1.10.15 quotes the string on encoding:

```yaml
Tarantool 1.10.15-0-ge14d0b4eab

tarantool> yaml = require('yaml')
tarantool> print(yaml.encode({hostname = '9e0260492063'}))
---
hostname: '9e0260492063'
...
```

So, this problem looks like a regression in encoding.

**Comment by georgiy-belyanin** [comment]
I'll work on this issue.
