### ISSUE TITLE
gh-8252 test tests nothing

### ISSUE THREAD

**Issue by Buristan** [tarantool/tarantool#10210]
https://github.com/tarantool/tarantool/blob/1e1bf36dbceafce625a8ce7e54951892cc8e2fa0/test/app-luatest/gh_8252_jit_off_on_macOS_by_default_test.lua#L5

This test is silently ignored by the luatest since it is not started with the `test_` prefix.

**Comment by ligurio** [comment]
Submitted a luatest issue https://github.com/tarantool/luatest/issues/385.
