### ISSUE TITLE
relay: ack to TX thread only the txns whose `on_commit` is finished

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#10252]
There is a problem right now in how the replication works. In particular, one another problem in relay. Relay reads WAL without looking at TX thread. It can happen and actually happens a lot, that a txn could be written to WAL, picked up by a relay thread, sent to a replica, committed there, ACK is delivered to relay, relay sends it to TX, but TX **still** didn't receive a notification from its own WAL thread. I.e. the txns sometimes are acked before their local `on_commit` trigger is invoked.

This is a common case which is quite hard to handle, but needs to be handled in our code anyway. For example:
```C
static void
txn_limbo_read_confirm(struct txn_limbo *limbo, int64_t lsn)
{
	rlist_foreach_entry_safe(e, &limbo->queue, in_queue, tmp) {
		if (txn_has_flag(e->txn, TXN_WAIT_ACK)) {
			if (e->lsn > lsn)
				break;
			/*
			 * Sync transaction not yet received an LSN. Happens
			 * only to local master transactions whose WAL write is
			 * in progress.
			 */
			if (e->lsn == -1)
				break;
```
A transaction here can be confirmed before getting an LSN on the original instance.

This is also making things harder than they should be in #10114. A replica is deleted from `_cluster` and acks that itself, but the master still doesn't know that for sure - what?

A possible solution could go one of the two directions:
- From tx->relay channel PoV;
- From relay->tx channel PoV.

Tx->relay option would mean that the relay must not pick the txns, which are not fully processed by TX yet. Relay could read them from disk, but only send to the replica once gets notified from TX about a next batch of txns being fully processed. The bad thing is that the TX would have to send stuff to relay more actively.

Relay->tx option means that the relays work like now. But they either don't forward ACKs to TX thread until it catches up, or they do, but TX won't process them until finishes the txns.

Once this is done, we can find all places where this weird situation was being handled, and delete that code.

**Comment by sergepetrenko** [comment]
Good idea!

I think we should go from the relay->tx pov. It should be quite easy to implement.
Simply cache the vclock that got acked by the replica, and perform `txn_limbo_ack` once local instance vclock catches up with it.
We already have this caching, by the way. replica vclock as seen by tx is stored in `relay->tx.vclock`

**Comment by Gerold103** [comment]
To clarify - I mean fix it in general, not just for the limbo. Make it literally impossible to receive an actual ACK for anything, whose on-commit trigger is not yet invoked.

**Comment by sergepetrenko** [comment]
> To clarify - I mean fix it in general, not just for the limbo. Make it literally impossible to receive an actual ACK for anything, whose on-commit trigger is not yet invoked.

Isn't limbo the only user of relay acks at the moment?

Anyway, if I got you right, you want to split `tx_status_update` into two parts:
* `tx_process_ack`, which would run `replicaset.on_ack` triggers and  perform `txn_limbo_ack`
* `tx_status_update`: update `downstream.vclock`, perform all the bookkeeping like updating `tx_last_seen` and so on, and processing raft term coming from applier, if any.

`tx_process_ack` would then run only up to instance vclock
https://github.com/tarantool/tarantool/blob/4cac1677c88a0ee13944d8dc44b10813738bb445/src/box/relay.cc#L598-L638

**Comment by sergepetrenko** [comment]
AFAIU we decided this is not needed in a verbal discussion with @Gerold103.
Feel free to close.

**Comment by Gerold103** [comment]
Lets drop it now. Reopen if needed for anything else. So far implementation complexity doesn't look worth it.
