### ISSUE TITLE
builtin/box/schema.lua:1814: attempt to index local 'tuple' (a nil value)

### ISSUE THREAD

**Issue by ligurio** [tarantool/tarantool#10262]
**Bug description**

The test got an error  `builtin/box/schema.lua:1814: attempt to index local 'tuple' (a nil value)` on calling `idx:alter(opts)`.

https://github.com/tarantool/tarantool/blob/5ce010c5e6d95713dd4344dcaded3920b6d6417d/src/box/lua/schema.lua#L1811-L1814

Probably, we should check tuple for `nil` before accessing `opts`:

```diff
--- a/src/box/lua/schema.lua
+++ b/src/box/lua/schema.lua
@@ -1811,7 +1811,7 @@ box.schema.index.alter = atomic_wrapper(function(space_id, index_id, options)
     local tuple = _index:get{space_id, index_id }
     local parts = {}
     local index_opts = {}
-    if type(tuple.opts) == 'number' then
+    if tuple and type(tuple.opts) == 'number' then
         -- old format
         index_opts.unique = tuple[5] == 1
         local part_count = tuple[6]
```

* OS: Linux
* OS Version: Ubuntu 22.04
* Architecture: amd64

Tarantool 06b87e27ea42c1f2f84b98b7156eba60db669dfb

Tarantool 3.2.0-entrypoint-112-g319357d59
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_BACKTRACE=TRUE
Compiler: GNU-13.2.0
C_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/home/ubuntu/tarantool=. -std=c11 -Wall -Wextra -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type -O2 -g -DNDEBUG -ggdb -O2 
CXX_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/home/ubuntu/tarantool=. -std=c++11 -Wall -Wextra -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type -O2 -g -DNDEBUG -ggdb -O2 

**Steps to reproduce**

Found by fuzzing test.

**Actual behavior**

The test got an error  `builtin/box/schema.lua:1814: attempt to index local 'tuple' (a nil value)` on calling `idx:alter(opts)`.

**Expected behavior**

No error.

**Comment by drewdzzz** [comment]
Reproducer is the same as [here](https://github.com/tarantool/tarantool/issues/10235#issuecomment-2238576994) - just add `memtx_use_mvcc_engine = true` to `box.cfg{}`.
