### ISSUE TITLE
Fix usages of `G(L)->gc.total` in Tarantool sources

### ISSUE THREAD

**Issue by Buristan** [tarantool/tarantool#10284]
We use `G(L)->gc.total` instead of using the Lua C API in several places:
* https://github.com/tarantool/tarantool/blob/a3ef8fb60382e747eed2cb521ebb3329dd4058f7/src/box/lua/info.c#L478
* https://github.com/tarantool/tarantool/blob/a3ef8fb60382e747eed2cb521ebb3329dd4058f7/src/box/lua/slab.cc#L262

These usages can be replaced with the corresponding calls to [the `lua_gc()` function](https://www.lua.org/manual/5.1/manual.html#lua_gc):
```c
lua_gc(L, LUA_GCCOUNT, 0) * 1024 + lua_gc(L, LUA_GCCOUNTB, 0);
```

**Comment by igormunkin** [comment]
It's about time.
