### ISSUE TITLE
config: grant access to call a global Lua function in runtime

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#10310]
The idea is to allow to grant access to call a global Lua function even if the database is read-only or has an old schema version if the configuration allows it.

In other words, if the configuration has the following snippet:

```yaml
credentials:
  users:
    alice:
      privileges:
        - permissions: [execute]
          lua_call: [my_func]
```

The `my_func` function can be called by the `alice` user via iproto disregadring the database mode/status.

Let's also support `lua_call: [all]` variant in the same way: allow to call all the global Lua functions except built-in ones disregarding the database mode/status.

> [!NOTE]
> I propose to keep writing the privileges to the database when possible (when the database is RW and schema versions is the newest[^1]) for compatibility and consistency with other privileges.

The motivation is to break cycles like the following:

* A bootstrapped database is needed to grant access to a function that assigns a bootstrap leader.
* The RW database mode is needed on some instance in a replicaset to grant access to a function that makes an instance RW.

This task depends on #10304 and #10306.

Part of TNTP-201.

[^1]: DDL is allowed only when the schema version is the newest, see #7149.

**Comment by sergepetrenko** [comment]
> The motivation is to break cycles like the following:
> 
>     * A bootstrapped database is needed to grant access to a function that assigns a bootstrap leader.
> 
>     * The RW database mode is needed on some instance in a replicaset to grant access to a function that makes an instance RW.

Maybe we can make the functions you mention always accessible? IOW, create some whitelist for a specific Tarantool version.

**Comment by Totktonada** [comment]
> Maybe we can make the functions you mention always accessible? IOW, create some whitelist for a specific Tarantool version.

It seems, it is a possible solution. However, I have some doubts regarding it:

* A user may have its own bootstrap leader assignment, RO/RW management, informational functions.
* A user may want to control these privileges from the configuration (including ones for the built-in tarantool functions).
* A user may have application functions that are not related to the database anyhow.
* It is a logical step toward runtime privileges: in my opinion, if we make all the config's privileges runtime from the scratch, it simplifies a lot of things for us and for a user.
