### ISSUE TITLE
Inconsistent visual style in documentation

### ISSUE THREAD

**Issue by mejedi** [tarantool/tarantool#1033]
Visual style is somewhat inconsistent. Common issues:
 * Breaking conventions defined in http://tarantool.org/doc/book/intro.html#conventions
 * Lua blocks lacking syntax highlighting;
 * Terminal sessions typeset in black boxes.

http://tarantool.org/doc/book/user_guide_getting_started.html#starting-tarantool-and-making-your-first-database **user types box.cfg — hence bold**
http://tarantool.org/doc/book/box/index.html#document-data-model
http://tarantool.org/doc/book/box/index.html#operations
http://tarantool.org/doc/book/box/index.html#data-persistence
http://tarantool.org/doc/book/box/box_space.html **missing hotlinks, space_object:update lua code**
http://tarantool.org/doc/book/box/box_space.html#example-showing-use-of-the-box-space-functions
http://tarantool.org/doc/book/box/box_index.html#package-box-index-with-index-type-rtree-for-spatial-searches **lua code**
http://tarantool.org/doc/book/box/box_tuple.html#example **lua code**
http://tarantool.org/doc/book/box/atomic.html#example **lua code**
http://tarantool.org/doc/book/box/limitations.html **hotlinks, please**
http://tarantool.org/doc/book/box/triggers.html#example **lua code, terminal session**
http://tarantool.org/doc/book/box/triggers.html#replace-triggers **hotlinks, please**
http://tarantool.org/doc/book/replication/index.html#hands-on-replication-tutorial **terminal content overflows the box on 15" laptop**
http://tarantool.org/doc/book/configuration/index.html#binary-logging-and-snapshots **hotlinks, please**
http://tarantool.org/doc/book/configuration/index.html#book-cfg-local-hot-standy **terminal session**
http://tarantool.org/doc/book/administration.html#requests **lua code**
http://tarantool.org/doc/book/administration.html#a-detailed-example-for-tarantoolctl **terminal session**
http://tarantool.org/doc/book/connectors/index.html#perl **terminal session**
http://tarantool.org/doc/book/connectors/index.html#c **SETUP, CONNECT etc captions **
http://tarantool.org/doc/book/app_a_errcodes.html#list-of-error-codes **hotlinks, please**
http://tarantool.org/doc/book/app_c_lua_tutorial.html#create-a-function-that-returns-a-string **Lua code, subsequent section have the same issue**
http://tarantool.org/doc/book/app_c_lua_tutorial.html#sum-a-json-field-for-all-tuples **LINE1 etc captions**

http://tarantool.org/doc/reference/digest.html#example
http://tarantool.org/doc/reference/uuid.html#example
http://tarantool.org/doc/reference/yaml.html#example
http://tarantool.org/doc/reference/msgpack.html#example
http://tarantool.org/doc/reference/fiber.html#lua-function.fiber.create
http://tarantool.org/doc/reference/fiber.html#lua-function.fiber.time
http://tarantool.org/doc/reference/fiber.html#lua-function.fiber.time64
http://tarantool.org/doc/reference/fiber.html#example
http://tarantool.org/doc/reference/socket.html#lua-function.socket.getaddrinfo
http://tarantool.org/doc/reference/socket.html#use-tcp-server-to-accept-file-contents-sent-with-socat
http://tarantool.org/doc/reference/tap.html#lua-function.taptest.ok
http://tarantool.org/doc/reference/tap.html#lua-function.taptest.skip
http://tarantool.org/doc/reference/shard.html **example section headers**
http://tarantool.org/doc/reference/tarantool.html **example session header**

**Comment by kostja** [comment]
Eugene, let's discuss this, I wonder why the errors are so numerous - is it a conversion error or something that was introduced later by Peter's changes? In any case if you can fix this it would be great.
