### ISSUE TITLE
Do not abort all yielding memtx transactions when DDL is committed

### ISSUE THREAD

**Issue by locker** [tarantool/tarantool#10377]
Currently, any DDL operation aborts **all** yielding memtx transactions, even those that are not directly affected by it:

```lua
local fiber = require('fiber')

box.cfg{
    log_level = 'warn',
    memtx_use_mvcc_engine = true,
}

local s = box.schema.space.create('test')
s:create_index('pk')

box.begin()
s:insert({1})

local f = fiber.new(box.schema.space.create, 'test2')
f:set_joinable(true)
f:join()

box.commit()

os.exit(0)
```

Output:

```
2024-08-07 12:49:27.531 [143562] main/114/lua memtx_tx.c:700 W> Transaction committing DDL (id=392) has aborted another TX (id=391)
2024-08-07 12:49:27.532 [143562] main test.lua:18 E> ER_TRANSACTION_CONFLICT: Transaction has been aborted by conflict
2024-08-07 12:49:27.532 [143562] main F> fatal error, exiting the event loop
```

This is caused by the following code:

https://github.com/tarantool/tarantool/blob/625afe418151de1015483ed24acaa57e1f85efb3/src/box/memtx_engine.cc#L623-L624

In contrast to memtx, Vinyl aborts only affected transactions when a DDL operation is committed, see commit d3e12369565151ba8c0632a84adab4bf90eff23f. We should do something similar in memtx.

**Comment by locker** [comment]
Related issues:
- #9696
- #9720
- #10375

**Comment by locker** [comment]
BTW this was suggested during review: https://github.com/tarantool/tarantool/pull/6228#discussion_r678185169.

**Comment by CuriousGeorgiy** [comment]
@locker close #6138 as duplicate?

**Comment by locker** [comment]
> @locker close #6138 as duplicate?

I'm not sure it's the same. Fixing this issue wouldn't fix the examples from the commit description:

```
-- Can't create spaces with the same name in separate transactions, meanwhile
-- drop doesn't find the space by name.
--
box.cfg{memtx_use_mvcc_engine = true}

txn_proxy = require('txn_proxy')

tx1 = txn_proxy.new()
tx2 = txn_proxy.new()

tx1:begin()
tx2:begin()

tx1("box.schema.create_space('t')")
tx2("box.schema.create_space('t')")
-- 'Space ''t'' already exists'
```

```
tx1:begin()
tx2:begin()


tx1("box.schema.create_space('t1')")
tx2("box.space.t1:drop()")
-- 'Space ''t1'' does not exist'
```

Looks like that issue is about data dictionary versioning. Not sure anybody needs it though.

I added it to the related issue list in https://github.com/tarantool/tarantool/issues/10377#issuecomment-2273077466.

**Comment by locker** [comment]
Please remove the skip condition after the fix:

https://github.com/tarantool/tarantool/blob/f5f061d051dc6268949bfcb141d211142282578d/test/engine-luatest/gh_10375_ddl_does_not_abort_unrelated_transactions_test.lua#L29
