### ISSUE TITLE
Add box.intxn()

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#1039]
Please add bindings for intxn() macro to Lua. I think that `intxn()` is bad name, please also try to find a better name. 

See also #1038

**Comment by kostja** [comment]
box_txn()

**Comment by rtsisyk** [comment]
Why this API is not public Lua?

**Comment by kostja** [comment]
Same reason fiber.wakeup() is not public. It should  not be possible to
access txn object explicity.

**Comment by rtsisyk** [comment]
Added bool box_txn() to C API.
