### ISSUE TITLE
Replication: relay ends after duplicate key

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#1041]
I have Ubuntu 12.04 and Tarantool 1.6, pulled from source today.

I get master-replica replication going (not master-master).
I insert something on the replica.
I try to insert the same thing on the master.
On the master I read "replica has closed its socket ... exiting relay relay thread".

How to repeat ...

Set up two shells. Call them Terminal#1 and Terminal#2.

On Terminal #1, say:
"
    mkdir -p ~/tarantool_test_node_1
    cd ~/tarantool_test_node_1
    rm -R ~/tarantool_test_node_1/*
    ~/tarantool/src/tarantool
    box.cfg{listen=3301}
    box.schema.user.create('replicator', {password = 'password'})
    box.schema.user.grant('replicator','read,write','universe')
"

On Terminal #2, say:
"
    mkdir -p ~/tarantool_test_node_2
    cd ~/tarantool_test_node_2
    rm -R ~/tarantool_test_node_2/*
    ~/tarantool/src/tarantool
    box.cfg{listen=3302, replication_source='replicator:password@localhost:3301'}
"

On Terminal #1, say:
"
    box.schema.space.create('T2')
    box.space.T2:create_index('primary',{})
    box.space.T2:insert{1}
"

On Terminal #2, say:
"
    # Terminal 2
    box.space.T2:insert{2}
"

On Terminal #1, say:
"
    # Terminal #1
    box.space.T2:insert{2}
"

The result on Terminal #1 now looks like this:
"
2015-09-14 14:45:07.403 [21411] relay/127.0.0.1:58450/101/main I> the replica has closed its socket, exiting
2015-09-14 14:45:07.403 [21411] relay/127.0.0.1:58450/102/main I> fiber `main' has been cancelled
2015-09-14 14:45:07.404 [21411] relay/127.0.0.1:58450/102/main I> fiber `main': exiting
2015-09-14 14:45:07.404 [21411] relay/127.0.0.1:58450/101/main C> exiting the relay loop

**Comment by kostja** [comment]
This is works as intended. Duplicate key errors stop replication. It must be restarted again after an error like that.
