### ISSUE TITLE
Function failure with _vuser, bad message 

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#1042]
I have Ubuntu 12.04 and Tarantool 1.6, pulled from source today.

I execute this request: box.space._vuser:len().

The result looks like this:
```
tarantool> box.space._vuser:len()
---
- error: TREE does not support size()
...
```
1. I don't believe it's helpful to blame TREE
and size().  It's not the fault of TREE, and
users shouldn't expect complaints to say
"size" when they typed in "len".

2. This wrecked an example in the manual,
Example showing use of the box.space functions.
I don't mind. But whenever things change,
the manual's examples can be affected.

I asked Konstantin Osipov about this, and he replied:
> This is unintentional, mandates a bug report.

**Comment by rtsisyk** [comment]
vspace.index[x]:len() wasn't implemented because it has O(N) complexity...

**Comment by kostja** [comment]
Roman, the complaint about a bad error message is valid.

**Comment by kostja** [comment]
This is ok, but the error message should be fixed.

**Comment by rtsisyk** [comment]
This fix requires copy-pasting of 100 lines of code from https://github.com/tarantool/tarantool/blob/1.6/src/box/index.cc#L160-L245
@kostja please approve

**Comment by kostja** [comment]
I disagree it's got to be a copy paste, but I agree sysengine should provide own, user friendly implementations for these functions.

**Comment by rtsisyk** [comment]
I will be a copy-paste with index_str[index->type] replaced with space name.

**Comment by rtsisyk** [comment]
1) Close with WON'T FIX (will be done by default after 14 days)
2) Copy-paste 100 lines of code from index.cc to sysview_index.cc (with replacing index_str[index->type] to "sysview")

**Comment by rtsisyk** [comment]
I don't want to copy a half of class Index just to fix the single error message.
I suggest to close this ticket as non important....

**Comment by kostja** [comment]
* Roman Tsisyk <notifications@github.com> [15/12/21 12:26]:
> I don't want to copy a half of class Index just to fix the
> single error message.  I suggest to close this ticket as non
> important.... 

Please copy for now. Being user friendly is important and if you have to
write a lot of code for it it's the problem of the design not of
the user.

-- 
Konstantin Osipov, Moscow, Russia, +7 903 626 22 32
http://tarantool.org - www.twitter.com/kostja_osipov

**Comment by rtsisyk** [comment]
OK

**Comment by rtsisyk** [comment]
I introduced some new pattern which hasn't been used before. I hope you will like it.
review => @alyapunov

**Comment by rtsisyk** [comment]
* Introduce new error codes: ER_INDEX_METHOD, ER_SPACE_METHOD, ER_ENGINE_FEATURE
* Add index type to ER_INDEX_METHOD

**Comment by rtsisyk** [comment]
Fixed.
