### ISSUE TITLE
Logger to syslog

### ISSUE THREAD

**Issue by mejedi** [tarantool/tarantool#1043]
Implement syslog support. If logger = { } (a Lua table with facility, identity, level), log directly to syslog.

**Comment by kostja** [comment]
Another request coming from another corporate deployment.

**Comment by mejedi** [comment]
The following is the summary of an internal discussion.

Logger key (string) specifies the logging destination. In order to support different destinations in a uniform way the following syntax is adopted:

 * `"file:/path/to/file"` — log to file;
 * `"pipe:/path/to/executable [param1 ...]"` — log to a helper process via a pipe;
 * `"syslog:[key=value[,key=value...]]"` — log to syslog.

The legacy logger syntax is retained for compatibility. The legacy syntax will be dropped in a future release.

### Syslog Destination

The syntax is `"syslog:"` followed by an optional comma separated key=value list. The folowing keys are defined:
 * `identity=...` — a string prepended to every syslog message (default: `tarantool`);
 * `facility=...` — syslog facility (`auth`, `authpriv`, `cron`, `daemon`, `ftp`, `kern`, `lpr`, `mail`, `news`, `security`, `syslog`, `user`, `uucp`, `local0` ... `local7`, default: `user`).

**Note:** the severy level of a message logged to syslog is set automatically.

**Note:** the proposed syntax is based on [[1](http://nginx.org/en/docs/syslog.html)] and [[2](http://tengine.taobao.org/document/http_log.html)].

**Comment by rtsisyk** [comment]
> "file:/path/to/file" — log to file;
> "pipe:/path/to/executable [param1 ...]" — log to a helper process via a pipe;
> "syslog:[key=value[,key=value...]]" — log to syslog.
> The legacy logger syntax is retained for compatibility. The legacy syntax will be dropped in a future release.

Please keep current syntax - logging to file is most common case.

> The syntax is "syslog:" followed by an optional comma separated key=value list. The folowing keys are defined:
> 
>    identity=... — a string prepended to every syslog message (default: tarantool);
>   facility=... — syslog facility (auth, authpriv, cron, daemon, ftp, kern, lpr, mail, news, security, > syslog, user, uucp, local0 ... local7, default: user).

Why not to use Lua tables instead of this microlanguage?

```
logger = "filename";
logger = "|pipe";
logger = {
    type = "syslog";
    identity =  "xxx";
    facility = "yyy";
}
logger = {
    type = "file";
    path = "/var/log/blabla";
}
logger = {
    type = "subprocess";
    path = "/usr/bin/logcat";
    pass_signals = false; -- just for example
}
```

**Comment by kostja** [comment]
Duplicate of gh-2283
