### ISSUE TITLE
Add support for automatic rollback of asynchronous transactions from an old term when synchronous replication is used

### ISSUE THREAD

**Issue by CuriousGeorgiy** [tarantool/tarantool#10459]
Using asynchronous replication with synchronous replication leads to split-brain when a new leader gets appointed without knowledge of all the async transactions of the former leader. Such cases are quite common, it's impossible to guarantee that async transactions from the old leader reach the new leader in time. For example, the old leader might be unreachable, or simply die before replication takes place.

The user has a choice here: either not to mix async replication with synchronous replication at all, or face spurious split-brain cases each time the situation above occurs.

The reason for raising a split-brain error in a situation described above is that we can't keep the async transactions from an old term - they might overwrite something written by the new leader in the new term, and we can't roll them back, because we don't have the necessary info to do so.

Fixing this error requires manual intervention and a rebootstrap of the stray node. The conflicting transactions are also lost.

In order to simplify administration, let's add support for automatic rollback of asynchronous transactions from an old term by keeping asynchronous transactions in the synchronous queue until they get confirmed on a quorum of replicas.

The feature will be controlled by a new `replication_split_brain_handling_mode` enumeration option. For now, the only available mode will be `rollback`, which automatically rolls back conflicting asynchronous transactions in the event of a split-brain situation.

This feature can lead to data loss, so in order to make it safe, we will allow the user to intervene by adding a `box.ctl.on_replication_split_brain_rollback` event in the scope of #10460.

**Comment by sergepetrenko** [comment]
Superseded by #10583
