### ISSUE TITLE
Wal_write_to_disk should stop using ftruncate

### ISSUE THREAD

**Issue by mejedi** [tarantool/tarantool#1051]
If WAL write fails it is possible that the last transaction didn't make it to the disk completely, i.e. some statements were written but not all of them. To remedy the situation ftruncate is used. This is wrong because it is possible for a replication relay to pick incorrect data before ftruncate suceeds.

**Comment by rtsisyk** [comment]
I think this problem can be fixed by adding transaction boundary markers to xrow header.

**Comment by kostja** [comment]
We added transaction boundaries, and a test case will soon follow, closing.
