### ISSUE TITLE
 Use-of-uninitialized-value in function `lj_str_new()`

### ISSUE THREAD

**Issue by skorpion98** [tarantool/tarantool#10511]
### Bug description
We found a use-of-uninitialized-value bug in function `lj_str_new()` after testing one of the harnesses provided on the OSS-Fuzz repository (luaL_loadbuffer_fuzzer).

**Valgrind output**
==206== Conditional jump or move depends on uninitialised value(s)
==206==	at 0x3DA2A9: lj_str_new (in /out/luaL_loadbuffer_fuzzer)
==206==	by 0x4A9B20: lj_ctype_initfin (in /out/luaL_loadbuffer_fuzzer)
==206==	by 0x3D90E4: cpluaopen (in /out/luaL_loadbuffer_fuzzer)
==206==	by 0x3BEBAA: lj_vm_cpcall (in /out/luaL_loadbuffer_fuzzer)
==206==	by 0x3D8F5E: lua_newstate (in /out/luaL_loadbuffer_fuzzer)
==206==	by 0x3EAFCF: luaL_newstate (in /out/luaL_loadbuffer_fuzzer)
==206==	by 0x2CE193: TestOneProtoInput(lua_grammar::Block const&) (in /out/luaL_loadbuffer_fuzzer)
==206==	by 0x2CE0AD: LLVMFuzzerTestOneInput (in /out/luaL_loadbuffer_fuzzer)
==206==	by 0x6C2A29: ExecuteFilesOnyByOne (in /out/luaL_loadbuffer_fuzzer)
==206==	by 0x6C2825: LLVMFuzzerRunDriver (in /out/luaL_loadbuffer_fuzzer)
==206==	by 0x6C23DD: main (in /out/luaL_loadbuffer_fuzzer)

### Steps to reproduce
In the [attached archive](https://github.com/user-attachments/files/16846665/tarantool_msan_bugs.zip) you will find:
  - the executable on which we performed our tests
  - the input file that caused the bug
  - the output of Valgrind confirming our finding

To reproduce the errors, a memory safety tool is required to expose the bug. 
Run the given binary with the testcase files inside Valgrind with a command like `valgrind ./luaL_loadbuffer_fuzzer /path_to_testcases/input`.

The program has been tested on the standard Docker image provided on OSS-Fuzz using Ubuntu 20.04, providing AFL++ as fuzzing engine and build flag `--sanitizer=none`.

The hash commit used to perform the tests is `218fc46`.

**Environment**
- OS: Linux
- Version/Distribution: Ubuntu 20.04
- Architecture: x86_64

**Comment by Buristan** [comment]
Thanks for the report!

I suppose you don't add the following flag to suppress false-positives produced by LuaJIT:
```
--suppressions=third_party/luajit/src/lj.supp
```

With this flag enabled, all valgrind warnings are gone.
