### ISSUE TITLE
Asynchronous transactions must bump the confirmation boundary of the synchronous queue

### ISSUE THREAD

**Issue by CuriousGeorgiy** [tarantool/tarantool#10528]
Currently, we cannot detect a split-brain situation on the old leader when a promote arrives, and the old leader has committed asynchronous transactions that are not confirmed by the promote. We can only detect this on the new leader if he sees asynchronous transactions replicated to him from the old leader.

This is because asynchronous transactions do not bump the confirmation boundary of the synchronous queue, which is used to detect such a split-brain situation. Even though asynchronous transactions can completely bypass the synchronous queue, they must still bump the confirmation boundaries as if they were instantly confirmed (since asynchronous transactions are _per se_ synchronous transactions with quorum 1).

**Comment by sergepetrenko** [comment]
Superseded by #10583
