### ISSUE TITLE
debian/tarantool-common.logrotate changes log user/group of the log file

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#1052]
If /etc/sysconfig/tarantool/default has a username != tarantool, for example, taransible, this username
is not taken into account by logrotate. 

Indeed, the username is hardcoded in the logrotate script we install:

    create 0640 tarantool adm

Logrotate should preserve the user name and group of the orignal file, if possible.

**Comment by unera** [comment]
if You change tarantool's default user, You should change user/group in /etc/logrotate.d/tarantool.d, too.

**Comment by Sulverus** [comment]
Looks like we need to add comment before username option in /etc/default/tarantool?

**Comment by rtsisyk** [comment]
Please add comments to /etc/default/tarantool and close the ticket.

**Comment by rtsisyk** [comment]
I'm touching this file right now.
