### ISSUE TITLE
Thread names (pthread_setname_np)

### ISSUE THREAD

**Issue by mejedi** [tarantool/tarantool#1053]
Assigning names to Tarantool threads will make it easier to navigate the (rather lengthy) list of threads in gdb.

**Comment by mejedi** [comment]
Done for cord_start-ed threads. TODO: eio pools, sophia threads.

**Comment by mejedi** [comment]
Done for eio pool (Linux). TODO: eio pool, sophia threads.

**Comment by kostja** [comment]
Please open issues in  respective projects for eio and sophia
