### ISSUE TITLE
'log' configuration in box.cfg{} style

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#1054]
Please implement require('log').cfg{} and move all logger properties from box.cfg{}.
box.cfg { log_level = xx } can be kept for backward compatibility.

See also #1045 and #1046.

**Comment by rtsisyk** [comment]
+ log.cfg { level = } should accept strings instead of number (e.g. level = 'verbose').

**Comment by olegrok** [comment]
After https://github.com/tarantool/tarantool/commit/a94a9b3fd629b5abbc99a23ba527cd91e5c6ebf5 we have `log.cfg` function. Is issue resolved?

**Comment by Totktonada** [comment]
@olegrok Thanks for the reminder!

Sure, it was implemented since 2.5.0-100-ga94a9b3fd.
