### ISSUE TITLE
http client: update libcurl from 8.8.0+patches to 8.10.1

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#10576]
The latest libcurl update is 7192bf66791748a4d399322378d23b1abfa477aa, it bumps libcurl to 8.8.0+patches. The update lands to `3.2.0`, `3.1.1` and `2.11.4` releases.

The most recent version of libcurl is now [8.10.1](https://curl.se/docs/releases.html). Comparing to 8.8.0 it offers a lot of [bugfixes](https://curl.se/changes.html) and four [security fixes](https://curl.se/docs/security.html).

It seems wortful to update the libcurl submodule in tarantool as a regular code health activity: to bring the fixes and improve overall stability.

The usual process is the following:

* Prepare the submodule update:
  * Update the https://github.com/tarantool/curl fork (push the `master` branch + all the new tags).
  * Prepare a patch in tarantool with the `third_party/curl` submodule update.
* Prepare changes on the tarantool side:
  * Verify all the added/deleted/changed libcurl's CMake options and set them explicitly to their defaults (or other appropriate values) in `cmake/BuildLibCURL.cmake`. (Use `cmake -LAH` or something similar to obtain the option list for the old and the new libcurl versions.)
  * Include the tarantool side changes into the submodule bump patch.
  * Don't forget to highlight all the non-trivial changes in the commit message.
* Open a pull request in tarantool.

NB: A general guide [how to update a submodule](https://github.com/tarantool/tarantool/wiki/How-to-update-a-third-party-repository-when-it-is-used-as-a-submodule).

NB 2: A more detailed guide [how to update a submodule with curl as the example](https://github.com/tarantool/tarantool/wiki/Update-a-third-party-library).

The libcurl update is supposed to land to `release/2.11` (future `2.11.5`), `release/3.2` (future `3.2.1`) and `master` (future `3.3.0`).

**Comment by ligurio** [comment]
> I'm happy to announce another curl release. Get it as always from https://curl.se/
> curl and libcurl 8.10.1

https://curl.se/docs/releases.html

**Comment by Totktonada** [comment]
@ligurio Thanks for noticing! I've updated the issue title/description.
