### ISSUE TITLE
Fix local hot standby start after extending primary key (1.5)

### ISSUE THREAD

**Issue by Mons** [tarantool/tarantool#1058]
Situation:
- Tarantool had primary key of N fields.
- There are many updates on database (by pkey), which got saved into xlogs.
- Requests could not be stopped during update process.
- Primary key extended to N+1 fields in config
- Local hot standby cannot be run, since there is updates in xlogs with key of N fields.

Expected solution:
Allow updates from xlogs to be executed by partial key, when run in local hot standby mode.

**Comment by kostja** [comment]
We fixed this on a custom branch.
