### ISSUE TITLE
php connector - 7.0 support for 1.6 (and possibly 1.5?)

### ISSUE THREAD

**Issue by anton-povarov** [tarantool/tarantool#1060]
PHP7 is RC2 already and looks like it's on track for november release.
We're using extensions connectors for 1.5/1.6 and would love to see them updated.

@kostja said - currently no plans, but do post a ticker for that.

**Comment by kostja** [comment]
Please follow https://github.com/tarantool/tarantool-php/issues/46 instead.

**Comment by Sannis** [comment]
PHP7 version for 1.5 (but with some difference with upstream version): https://github.com/tony2001/tarantool-php/tree/php7
