### ISSUE TITLE
tarantool stuck at the end of test execution

### ISSUE THREAD

**Issue by ligurio** [tarantool/tarantool#10600]
**Bug description**

* OS: Linux
* OS Version: Ubuntu 24.04
* Architecture: amd64

Tarantool 3.3.0-entrypoint-85-g2300704e8
Target: Linux-x86_64-Debug
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_BACKTRACE=TRUE
Compiler: GNU-13.2.0
C_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/home/ubuntu/tarantool=. -std=c11 -Wall -Wextra -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type -Werror -g -ggdb -O0 
CXX_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -msse2 -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/home/ubuntu/tarantool=. -std=c++11 -Wall -Wextra -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type -Werror -g -ggdb -O0 

**Steps to reproduce**

How to run:

`seed=$RANDOM; ./build/src/tarantool ./test/fuzz/lua/test_engine.lua --workers 500 --test_duration $((30)) --engine vinyl --verbose --seed $seed; echo $seed;`

Random seed is 18137.

**Actual behavior**

tarantool process finished execution of Lua script but cannot finish itself

**Expected behavior**

tarantool process has finished

tarantool binary + coredump + tarantool.log + fiber.info
https://drive.google.com/file/d/11nOo4JH69tJYCBBteIg2mKiyubem65Og/view?usp=sharing

**Comment by locker** [comment]
There's a test fiber that doesn't exit because it's waiting for `box.snapshot()` to complete:

```
  280:
    backtrace:
    - C: '#1  0x60d672cb3de0 in fiber_yield+18'
    - C: '#2  0x60d672cb404d in fiber_yield_timeout+314'
    - C: '#3  0x60d672cc0f47 in fiber_cond_wait_timeout+202'
    - C: '#4  0x60d672cc10d0 in fiber_cond_wait+40'
    - C: '#5  0x60d672ac124a in vy_scheduler_wait_checkpoint+132'
    - C: '#6  0x60d672a5b30e in vinyl_engine_wait_checkpoint+106'
    - C: '#7  0x60d672a345f5 in engine_commit_checkpoint+75'
    - C: '#8  0x60d672b3c137 in gc_do_checkpoint+466'
    - C: '#9  0x60d672b3c332 in gc_checkpoint+390'
    - C: '#10 0x60d672b34c76 in box_checkpoint+64'
    - C: '#11 0x60d672c2737c in lbox_snapshot+21'
    - L: '#12 snapshot in =[C]:-1'
    - L: '#13 (unnamed) in @./test/fuzz/lua/test_engine.lua:802'
    - C: '#14 0x60d672d22f9b in lua_pcall+969'
    - C: '#15 0x60d672c848e6 in luaT_call+45'
    - C: '#16 0x60d672c79612 in lua_fiber_run_f+189'
    - C: '#17 0x60d6729cf143 in fiber_cxx_invoke(int (*)(__va_list_tag*), __va_list_tag*)+34'
    - C: '#18 0x60d672cb5472 in fiber_loop+219'
    - C: '#19 0x60d673096658 in coro_init+120'
    csw: 9
    max_slice:
      err: 1
      warn: 0.5
    memory:
      total: 524760
      used: 520
    time: 0
    name: 'WRK #165'
    fid: 280
```

`box.snapshot` is blocked by `ERRINJ_VY_RUN_WRITE_DELAY`:

```
#3  0x000058741effd282 in vy_task_write_run (task=0x587420872230, no_compression=true) at /home/ubuntu/tarantool/src/box/vy_scheduler.c:1113
1113            ERROR_INJECT_SLEEP(ERRINJ_VY_RUN_WRITE_DELAY);
```
