### ISSUE TITLE
Move tarantool.h from ./src/trivia/tarantool.h to ./include/tarantool/tarantool.h

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#1061]
All our rockspecs tries to find `tarantool/tarantool.h` file to compile.
Since `tarantool.h` is contained in `./src/trivia/tarantool.h` (i.e. without `tarantool/` prefix), it is not possible to specify `TARANTOOL_DIR=/path/to/tarantool/sources` to LuaRocks without running `make install`.

Reported by @pgulutzan

**Comment by kostja** [comment]
Eugene, I believe you have fixed this today, if so, please close the bug.

**Comment by rtsisyk** [comment]
Fixed

**Comment by dyu** [comment]
There is no src/trivia/tarantool.h in both master and 1.6 branch.
Likewise doing a make install does't have a tarantool.h in $INSTALL_DIR/include/tarantool

I was trying to install your luarocks modules (makes me wonder if they are used at all) and the rocks install fails because of that.

**Comment by bigbes** [comment]
`src/module.h` appears when you're building Tarantool. We've renamed it in
version 1.6.6

С наилучшими пожеланиями, Евгений.

2015-12-25 12:44 GMT+03:00 David Yu <notifications@github.com>:
