### ISSUE TITLE
Buffer ownership transfer from/to IPROTO thread

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#1064]
Implement some code to transfer ownership of ibuf/obuf from IPROTO thread to another thread and vice versa. The primary reason is to fix replication request processing which are handled in separate threads.

Please understand that all our threads uses readhead and can read extra more bytes, than needed. Instead of transfer raw fd to another thread, please transfer both fd and buffers. Don't forget to stop all ev watchers for this socket after transferring.

bsync is transfer sockets from/to IPROTO and RELAY threads.

**Comment by kostja** [comment]
This is probably not necessary in the new bsync arch.

**Comment by kostja** [comment]
We don't need this any more.
