### ISSUE TITLE
Use timeouts for network code in replication

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#1065]
1. Add `box.cfg { read_timeout = x, write_timeoout = x }` (names TBD).
2. Fix `evio_setsockopt_keepalive(int fd)` to use proper values of `TCP_KEEPIDLE`, `TCP_KEEPIDLE`, `TCP_KEEPIDLE` on **Linux** and **FreeBSD** and `TCP_KEEPALIVE` on **OS X** (man 4 tcp).
3. Check that replica disconnects within `read_timeout` after one-way shutdown on the master (i.e. without sending RST). 
4. Always use coio_*_timeout() functions, especially when connecting to remote servers.
   The only problem here is  `SUBSCRIBE` command will still use `INFINITY` timeout for read. All writes can be done with timeout, but it doesn't matter if you properly fixed `TCP_KEEPALIVE` at previous step.
5. **Add test cases**

**Comment by kostja** [comment]
Roman, I believe replication acks supersedes this ticket, moving to 1.7.5 to close along.

**Comment by rtsisyk** [comment]
This ticket require new options in box.cfg(). Otherwise there is no way to make a test case.
Please move it back to 1.7.6.

**Comment by rtsisyk** [comment]
1.7.4-473-ge3c5fde4b
