### ISSUE TITLE
config: separate schema code and data validators

### ISSUE THREAD

**Issue by mandesero** [tarantool/tarantool#10691]
### Overview

Currently, validation annotations (i.e. `validate` functions) are mixed in with the configuration schema (that defines the structure and types of the data). While it can be useful to view both the schema and validation logic together, more often than not, the validation code takes up a significant amount of space and makes the schema itself difficult to read.

#### Separate Validator Functions

Create a dedicated `validators.lua` file where validation functions are defined separately:

```lua
-- validators.lua
local M = {}

M['iproto.advertise.client'] = function(data, w)
	-- <...>
end

return M
```

#### Proposal 1: Use `schema.new` to inject validators

In this proposal, the `schema.new` function will be modified to automatically inject the necessary `validate` annotations from the `validators` module into the schema nodes during the schema preprocessing step (i.e., when copying the schema nodes).

```lua
-- instance_config.lua
local validators = require('internal.config.validators')

return schema.new('instance_config', {
	-- <..schema without validate = function() end..>
}, {
	validators = validators,
})
```

#### Proposal 2: Use a wrapper to add validators

Once [#10636](https://github.com/tarantool/tarantool/issues/10636) is resolved, we can reuse the wrapper that adds descriptions to schema fields and extend it to also set validators. This approach will apply changes at the `instance_config` level without modifying the `schema` implementation:

```lua
-- instance_config.lua
local validators = require('internal.config.validators')

local function set_validator(schema_obj, ctx)
	-- <...>
	schema_obj.validate = validators[<..field_path..>]
	-- <...>
end

local function <..wrapper..>(schema, ctx)
	set_description(schema, ctx)
	set_validator(schema, ctx)
	-- <...>
end

return schema.new('instance_config', <..wrapper..>({
	-- <..schema without validate = function() end..>
}), <...>)
```

-----
Jira: [TNTP-263](https://jira.vk.team/browse/TNTP-263)

**Comment by georgiy-belyanin** [comment]
I'd like to discuss the suggested approach a bit.

Implicit relations in the code make it harder to read. One of the strongest parts of the existing schema definition is that it's easy to see what we expect in the field and how it's validated.

E.g. take a look at the way we define `iproto.advertise.client`:
```diff
             client = schema.scalar({
                 type = 'string',
                 default = box.NULL,
-                validate = validate_uri_field(false, true),		
             }),
```

With explicit validator field it's obvious we expect URI here. Without it's unclear from quite a few variables what kind of string/number we expect.

**Comment by Totktonada** [comment]
Seems like we actually have many repeating checks here that can be generalized.

OTOH, I don't mind decoupling of the `validate` annotations -- when I'm looking into the schema, it is not the primary information I'm looking for. OK to return them back here if they become one-liners.

For me it looks worthful to proceed with Maksim's proposal and then continue with your proposal about generalization of the checks. In fact, I did some work in this direction (generalized cluster scope checks) on top of Maksim's patchset. Not sent yet, waiting for #10694 to land.
