### ISSUE TITLE
Add package builds to travis 

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#1071]

**Comment by Sulverus** [comment]
Done. Now cloud builds are in `beta` and it works in parallel with buildbot. 
https://travis-ci.org/tarantool/tarantool/builds/96773594
All drivers and lua modules rpm/deb specs have been updated and their builds have been moved to the cloud. New docker-based build system available in https://github.com/tarantool/build repo.
Demo repo in packagecloud:
tarantool only https://packagecloud.io/tarantool/1_6
modules, libraries and drivers https://packagecloud.io/tarantool/master

We can switch old and new builds after ~4 weeks of beta period
