### ISSUE TITLE
travis: enable docker build

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#1072]

**Comment by rybakit** [comment]
Related tickers:

https://github.com/Sulverus/tarantool-docker/issues/4
https://github.com/Sulverus/tarantool-docker/issues/3

Would be great to fix them as well ;)

**Comment by rybakit** [comment]
And here is an example of how I use docker to test Tarantool queue:
https://github.com/tarantool-php/queue/blob/master/.travis.yml

**Comment by bigbes** [comment]
It seems to me that they're not related:
this ticket is about new infrastructure of docker - builds inside
container, not VM's.

С наилучшими пожеланиями, Евгений.

2015-11-17 15:47 GMT+03:00 Eugene Leonovich <notifications@github.com>:

**Comment by rybakit** [comment]
@kostja @bigbes could Sulverus/tarantool-docker#3 be added to 1.6.8 milestone then? Right know it's not possible to run tests against the stable 1.6 branch with Docker.

**Comment by Sulverus** [comment]
Implemented for drivers, using travis-ci+docker+packagecoud.io 
Example: https://travis-ci.org/tarantool/tarantool-php

**Comment by Sulverus** [comment]
demo repository: https://packagecloud.io/tarantool/modules

**Comment by bigbes** [comment]
So, i guess, i've lost ability to test my php driver on every available PHP
that's given in travis?

С наилучшими пожеланиями, Евгений.

2015-11-28 1:01 GMT+03:00 Andrew <notifications@github.com>:

**Comment by Sulverus** [comment]
No, it's possible to add multiple compilers and exclusion matrix in travis.yml

**Comment by Sulverus** [comment]
Implemented in https://github.com/tarantool/tarantool/issues/1071
