### ISSUE TITLE
travis: enable mac build

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#1073]

**Comment by rtsisyk** [comment]
Wow, does travis support mac?

**Comment by kostja** [comment]
http://docs.travis-ci.com/user/osx-ci-environment/

**Comment by Sulverus** [comment]
Tarantool build config updated with multi os support(linux, os x), pushed to gh-1073 branch and rebased https://github.com/tarantool/tarantool/commit/d65d30b219989f395335ae8bc403429d92f4a861

**Comment by kostja** [comment]
* Andrew <notifications@github.com> [15/10/15 18:59]:
> Tarantool build config updated with multi os support(linux, os x), pushed to gh-1073 branch and rebased https://github.com/tarantool/tarantool/commit/d65d30b219989f395335ae8bc403429d92f4a861

OK to push.

-- 
http://tarantool.org - a NoSQL database in a Lua script

**Comment by Sulverus** [comment]
merged to 1.6

**Comment by mejedi** [comment]
The crash is being investigated in gh-1107
