### ISSUE TITLE
tarantool 3.2.1 regression failures on sonoma runners

### ISSUE THREAD

**Issue by chenrui333** [tarantool/tarantool#10763]
**Bug description**

seeing some regression failures on sonoma runners (macos-14)

* OS: macOS Sonoma
* OS Version: macos-14
* Architecture: arm/x86

Place `tarantool --version` output here.

**Steps to reproduce**

Run two tarantool instances iteractively.

1. Type '...' in console 1.
1. Type '...' in console 2.

or reproducer script:

```
#!/usr/bin/env tarantool

<your code here>
```

How to run:

Just type `tarantool test.lua`.

**Actual behavior**

```
==> /opt/homebrew/Cellar/tarantool/3.2.1/bin/tarantool /private/tmp/tarantool-test-20241028-25971-ogk5ir/test.lua
  Bus error
    code: 1
    addr: 0x1030f0000
    context: 0x1380a7c18
    siginfo: 0x1380a7bb0
  Current time: 1730146339
  Please file a bug at https://github.com/tarantool/tarantool/issues
  Attempting backtrace... Note: since the server has already crashed, 
  this may fail as well
  #1  0x102bd26cc in crash_signal_cb+148
  #2  0x18247e584 in _sigtramp+[56](https://github.com/Homebrew/homebrew-core/actions/runs/11560968254/job/32180273884?pr=195851#step:3:57)
  #3  0x102c0ced4 in lj_BC_FUNCC+44
  #4  0x102bb068c in luaT_set_module_from_source+112
  #5  0x102bb0108 in tarantool_lua_init+824
  #6  0x102a5278c in main+1[61](https://github.com/Homebrew/homebrew-core/actions/runs/11560968254/job/32180273884?pr=195851#step:3:62)6
```

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/11560968254/job/32180273884?pr=195851
relates to https://github.com/Homebrew/homebrew-core/pull/195851

**Expected behavior**

**Comment by sergepetrenko** [comment]
Same issue as #10566

**Comment by chenrui333** [comment]
yeah, I totally forgot the issue I raised before, merged this into https://github.com/tarantool/tarantool/issues/10566
