### ISSUE TITLE
Support negative indices in tuple operations

### ISSUE THREAD

**Issue by ligurio** [tarantool/tarantool#10788]
**Bug description**

Imagine a tuple with key in a first field and array in the second field. It is possible to add an element to an array in a tuple and specify a position of the new element, where position is a positive number indicating the number of the element before which the number should be inserted.
However, this position can be positive only, one can't specify the position of an element from the end of the list:

```lua
tarantool> t = box.tuple.new({1, {1, 2, 3}})                         
---                                                                                                                                     
...

tarantool> t                                                                                                                            
---
- [1, [1, 2, 3]]                                                    
...

tarantool> t:update({{'!', '[2][1]', 10}})                           
---
- [1, [10, 1, 2, 3]]            -- 10 added at the beginning of the list
...
tarantool> t:update({{'!', '[2][-1]', 10}})
---
- error: 'Field ''[2][-1]'' UPDATE error: invalid JSON in position 5'
...

tarantool> 
```

However, it is possible to specify a negative number of the fields:

```lua
tarantool> t:update({{'!', -1, 10}})
---
- [1, [1, 2, 3], 10] -- 10 added as the last field
...

tarantool> 
```
 
* OS: Linux
* OS Version: Ubuntu 22.04
* Architecture: amd64

3.3.0-entrypoint-183-g6fa8c32c9a

**Comment by olegrok** [comment]
Duplicate of https://github.com/tarantool/tarantool/issues/5152

**Comment by ligurio** [comment]
Duplicate of https://github.com/tarantool/tarantool/issues/5152
