### ISSUE TITLE
say_logrotate used as a signal handler, not async-signal safe

### ISSUE THREAD

**Issue by mejedi** [tarantool/tarantool#1081]
- say_info() uses strftime and snprintf, which are not async signal safe
- the file descriptor closed in logroate can be used in a different thread. Moreover, the other thread may write to the descriptor after it's closed and opened by some other thread. We need to make sure that the file
descriptor can never be used by some other thread, best if the new log file has the sime descriptor id (use dup2)

**Comment by kostja** [comment]
* Nick Zavaritsky <notifications@github.com> [15/10/04 15:13]:
> Converting it to a libev signal watcher makes sense.
> 
> (Pro: no restrictions on the code, Cons: processing delayed if
> event loop is busy) 

What's wrong with?

No, converting it to libev is not a good idea, it should work 
even in a busy loop.


-- 
http://tarantool.org - a NoSQL database in a Lua script

**Comment by mejedi** [comment]
Fixed in the patch for gh-1043
