### ISSUE TITLE
snapshot daemon: limit the maximim disk size of maintained WALs

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#1082]
Please a limit for the maximum summary size of all existing WALs.

**Comment by rtsisyk** [comment]
See also #748

**Comment by kostja** [comment]
The size is now dependent on checkpoint count.

**Comment by sharonovd** [comment]
This may be still useful for mitigating workload bursts, when big amount of WAL is generated in short amount of time.

Proposal: 
 - introduce wal_max_count setting - combined with wal_max_size setting, this option can be used for transparent disk usage management:
 - if snapshot daemon discovers that limit is reached, it triggers snapshotting (to try and reduce amount of wals and total consumed disk space)
