### ISSUE TITLE
segfault

### ISSUE THREAD

**Issue by orangeudav** [tarantool/tarantool#1084]
version 1.6.6-199-g0e36259

Please file a bug at http://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed,
this may fail as well
#0  0x42ded0 in sig_fatal_cb(int)+112
#1  0x7f7017ae80a0 in ?
#2  0x463a3b in MemtxEngine::commitCheckpoint()+123
#3  0x43a8dc in engine_checkpoint(long)+636
#4  0x46dbd8 in lbox_snapshot(lua_State*)+24
#5  0x4eb666 in lj_BC_FUNCC+52

**Comment by alyapunov** [comment]
Hi,
Thanks for report,
Could you please provide more details about the accident:
1)how many spaces are used, what kind of indexes and number of tuples in them
2)workload at a time of crash, probable RPS, especially modifying RPS
3)log file for the time of crash

**Comment by alyapunov** [comment]
Can't reproduce
