### ISSUE TITLE
Inconsistency for a new field in the _func space

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#1090]
This is not a bug, it is an observation about Tarantool 1.6.
Due to Issue#897 - stored functions in C/C++, there is an
additional field in the _func space.

Please make three _func tuples and look at them:
box.schema.func.create('function1')
box.schema.func.create('function2',{language='LUA'})
box.schema.func.create('function3',{language='Lua'})
box.space._func:select{}
... The result of the select{} includes:
  - [2, 1, 'function1', 0]
  - [3, 1, 'function2', 0, 'LUA']
  - [4, 1, 'function3', 0, 'Lua']
... which makes searches harder. In order to find out
"is the function Lua?" I have to ask
"is the field nonexistent or is upper(field-value) = 'LUA'?".
It might become more complex if someday a sixth field is added.

If box.schema.func.create ensured that the fifth field was
always either 'LUA' or 'C', it might become less complex.

**Comment by kostja** [comment]
An inconsistency is a bug.
