### ISSUE TITLE
Suport appveyor

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#1096]
Support Windows build at appveyor.com:

https://ci.appveyor.com/project/kostja/tarantool

.appveyor.yml is already in place in the sources: https://github.com/tarantool/tarantool/blob/1.6/.appveyor.yml
but is ignored for some reason

**Comment by Totktonada** [comment]
There are no plans to support Windows. Even if we'll do (in theory), we likely will use GitHub Actions as CI. The issue becomes not actual and I guess I can close it.
