### ISSUE TITLE
search: replication support for the new snapshot implementation

### ISSUE THREAD

**Issue by pmwkaa** [tarantool/tarantool#1114]
Recently we discussed issues with tarantool-sophia snapshot integration.

The discussion ended with an idea of a new snapshot implementation in tarantool: do not take a Sophia snapshot to reduce duplicate collection. But we forgot that snapshots are also used as a view for spaces being alive at the moment of snapshot creation.

I've manage to patch Sophia to release a used transaction but still to hold a view on a created spaces:
https://github.com/tarantool/tarantool/commit/da4c530b63150cdc26417e57fe531d0003d197bb
 
JOIN implementation now feeds latest versions (under created join cursor) instead of snapshot cursor.

This ticket is about JOIN support. We need to send exact statement LSN to slave and ensure replication still works (see ref above). Ensure that sophia is in Recovery mode during JOIN, etc.

**Comment by rtsisyk** [comment]
Implemented by 1.7.0-781-g8211560
