### ISSUE TITLE
extract tarantool-common package into an own versioning

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#1120]
We should not build a new tarantool-common package on each push into tarantool tree.
tarantool-common should be norach, arechitecture=all

**Comment by rtsisyk** [comment]
> tarantool-common should be norach, arechitecture=all

I fixed  that.

>We should not build a new tarantool-common package on each push into tarantool tree.

You have to create a new source package to do that (=new spec file). 

What do you want to achieve?  It is possible to don't restart daemons on upgrade.

BTW, I think that tarantool-common is useless. It was copied from postgresql-common in Debian, but we actually don't support multiple versions of tarantool on the same system as it was done for postgres.

**Comment by rtsisyk** [comment]
Ahh, I see #1119.

**Comment by rtsisyk** [comment]
Own versioning requires  a new source package to do that (=new spec file). 
Probably we need to merge tarantool-common into tarantool.

This ticket won't fix, sorry.

**Comment by rtsisyk** [comment]
Detailed explanation:

* Own versioning requires a new source package =>
* A new source package requires a new `debian/` folder =>
* A new `debian/` folder should be be placed at the root directory of git repo for buildbots =>
* Init scripts, tarantoolctl, logrotate, systemd configuration and so on should be extracted from the main git repo into a some new git repo =>
* This change break RPM, homebrew, FreeBSD and other packages =>
* Release engineering process become so much overcomplicated
* I will have to add  [some more Conflicts](https://github.com/tarantool/tarantool/blob/32ff24d231a6c07aa39ab0ae07f29a294de46a01/debian/control#L26-L44) to the main package
* Such big change requires a new review in Debian

RPM doesn't need `tarantool-common` . I'll remove it in 1.6.8. See explanation of `tarantool-common` purpose in #1119.
