### ISSUE TITLE
Inconsistency between memtx and phia for on_replace triggers with upsert

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#1121]
I have Ubuntu 12.04 and Tarantool 1.6.7, pulled from source today.
(Pulled from 1.6, not from master.)

I execute the following requests:

box.cfg{}
box.space.S:drop()
box.schema.space.create('S',{engine='sophia'})
box.space.S:create_index('S_1',{})
box.space.S:insert{12,'A','B','C','D'}
S_counter = 0
function S_f () S_counter = S_counter + 1 end; box.space.S:on_replace(S_f)
box.space.S:upsert({12},{{'=',3,'a'},{'=',4,'b'}})
S_counter
box.space.S:drop()
box.schema.space.create('S',{engine='memtx'})
box.space.S:create_index('S_1',{})
box.space.S:insert{12,'A','B','C','D'}
S_counter = 0
function S_f () S_counter = S_counter + 1 end; box.space.S:on_replace(S_f)
box.space.S:upsert({12},{{'=',3,'a'},{'=',4,'b'}})
S_counter

The first time that I display S_counter, the result is 0.
The second time that I display S_counter, the result is 1.
The only difference is: I use engine='sophia' the first time,
I use engine='memtx' the second time.

**Comment by Gerold103** [comment]
Fixed in 1.7.2
