### ISSUE TITLE
Improve CI build times

### ISSUE THREAD

**Issue by mejedi** [tarantool/tarantool#1125]
Project build times recently increased from [2 minutes](https://travis-ci.org/tarantool/tarantool/builds/87009896) to [4-10 minutes](https://travis-ci.org/tarantool/tarantool/builds/87009896). Extra time is being spent building newly added python dependencies of the test-run.

**Comment by Sulverus** [comment]
Implemented in https://github.com/tarantool/tarantool/issues/1071
Mean build time for tarantool packaging(measurements described [there] (https://github.com/tarantool/build/blob/master/README.md) )  is less then `15 minutes` for 12 os + linux tests + mac os tests versus old builds `~1,2 hour`

Example: https://travis-ci.org/tarantool/tarantool/builds/96773594
Now it works in beta for 1.6 branch.

After beta period we can move tests into docker and cache all python dependencies in dockerhub
https://hub.docker.com/r/tarantool/build/
