### ISSUE TITLE
Keyboard echo disabled after tarantool exit

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#1128]
I have Ubuntu 12.04 and Tarantool 1.6.7, pulled from source today.

I start the tarantool server. I stop it using control-C.
Now any key that I type on my keyboard is not echoed on the screen.

This problem does not occur with Tarantool 1.6.6 instead of 1.6.7.
This problem does not occur if I exit with os.exit() instead of control-C.

**Comment by mejedi** [comment]
Fixed in 1.6 branch.

**Comment by pgulutzan** [comment]
It has happened again, with Tarantool 1.6 built from source today.
