### ISSUE TITLE
Badly formed error message

### ISSUE THREAD

**Issue by rybakit** [tarantool/tarantool#1130]
Tarantool 1.6.7-363-g838bb33:

```lua
space = box.schema.space.create('foo')
space:create_index('primary', {type = 'hash', parts = {1, 'num'}})
space:insert{1, 'foobar'}
space:update(1, {{}})
---
- error: Invalid MsgPack - expected an update operationnon empty array)
...
```
Notice `operationnon empty array)` part. 

Tarantool 1.6.7-164-g8fe7030 however returns the correct message: `Invalid MsgPack - expected an update operation (array)`.

**Comment by rybakit** [comment]
:+1:  thanks

**Comment by rybakit** [comment]
Does the fix also change the error code? It was 20 before and now it's 1.

**Comment by kostja** [comment]
Yes, it does. Is it an issue? This code is used for malformed update, we need to perhaps introduce a separate one..

**Comment by rybakit** [comment]
It's not an issue, I just wanted to make sure it was intended.
