### ISSUE TITLE
coio_wait() performance and design issues

### ISSUE THREAD

**Issue by mejedi** [tarantool/tarantool#1132]
*TL;DR:* `coio_wait()` comes with an overhead — unnecessary syscalls

```lua
-- simple Lua echo server
socket = require('socket')
socket.tcp_server('0.0.0.0', 3302, function(s)
    while true do
        request = s:read("\n");
        if request == nil or request == "" then return end
        print(request)
    end
end)
```
##### Strace (fragment)
We do `nc localhost 3302`, and we enter `1\n2\n\3\n4\n` in the terminal. This connection is fd 7 in Tarantool.

Note `epoll_ctl(EPOLL_CTL_ADD)` failing with `EEXIST` after each processed input line.
```
accept(6, {sa_family=AF_INET, sin_port=htons(40804), sin_addr=inet_addr("127.0.0.1")}, [16]) = 7
fcntl(7, F_GETFL)                       = 0x2 (flags O_RDWR)
fcntl(7, F_SETFL, O_RDWR|O_NONBLOCK)    = 0
read(7, 0x7f8a23008030, 16336)          = -1 EAGAIN (Resource temporarily unavailable)
epoll_ctl(4, EPOLL_CTL_ADD, 6, {EPOLLIN, {u32=6, u64=8589934598}}) = -1 EEXIST (File exists)
epoll_ctl(4, EPOLL_CTL_ADD, 7, {EPOLLIN, {u32=7, u64=4294967303}}) = 0
epoll_wait(4, {{EPOLLIN, {u32=7, u64=4294967303}}}, 64, 59743) = 1
read(7, "1\n", 16336)                   = 2
write(1, "1\n", 2)                      = 2
write(1, "\n", 1)                       = 1
read(7, 0x7f8a23008032, 16334)          = -1 EAGAIN (Resource temporarily unavailable)
epoll_ctl(4, EPOLL_CTL_ADD, 7, {EPOLLIN, {u32=7, u64=8589934599}}) = -1 EEXIST (File exists)
epoll_wait(4, {{EPOLLIN, {u32=7, u64=4294967303}}}, 64, 59743) = 1
read(7, "2\n", 16334)                   = 2
write(1, "2\n", 2)                      = 2
write(1, "\n", 1)                       = 1
read(7, 0x7f8a23008034, 16332)          = -1 EAGAIN (Resource temporarily unavailable)
epoll_ctl(4, EPOLL_CTL_ADD, 7, {EPOLLIN, {u32=7, u64=8589934599}}) = -1 EEXIST (File exists)
epoll_wait(4, {{EPOLLIN, {u32=7, u64=4294967303}}}, 64, 59743) = 1
read(7, "3\n", 16332)                   = 2
write(1, "3\n", 2)                      = 2
write(1, "\n", 1)                       = 1
read(7, 0x7f8a23008036, 16330)          = -1 EAGAIN (Resource temporarily unavailable)
epoll_ctl(4, EPOLL_CTL_ADD, 7, {EPOLLIN, {u32=7, u64=8589934599}}) = -1 EEXIST (File exists)
epoll_wait(4, {{EPOLLIN, {u32=7, u64=4294967303}}}, 64, 59743) = 1
read(7, "4\n", 16330)                   = 2
write(1, "4\n", 2)                      = 2
write(1, "\n", 1)                       = 1
read(7, 0x7f8a23008038, 16328)          = -1 EAGAIN (Resource temporarily unavailable)
epoll_ctl(4, EPOLL_CTL_ADD, 7, {EPOLLIN, {u32=7, u64=8589934599}}) = -1 EEXIST (File exists)
```

### Suboptimal, a bit
Quoting from libev manual [[the special problem of disappearing file descriptors](http://pod.tst.eu/http://cvs.schmorp.de/libev/ev.pod#The_special_problem_of_disappearing_)]:
> Some backends (e.g. kqueue, epoll) need to be told about closing a file descriptor (either due to calling close explicitly or any other means, such as dup2). The reason is that you register interest in some file descriptor, but when it goes away, the operating system will silently drop this interest. If another file  descriptor with the same number then is registered with libev, there is no efficient way to see that this is, in fact, a different file descriptor.

> To avoid having to explicitly tell libev about such cases, libev follows the following policy: Each time ev_io_set is being called, libev will assume that this is potentially a new file descriptor, otherwise it is assumed that the file descriptor stays the same. That means that you have to call ev_io_set (or ev_io_init) when you change the descriptor even if the file descriptor number itself did not change.

coio_wait() actually does ev_io_init on every invocation.

**Comment by mejedi** [comment]
### Design Issues

Multiple fibers could get blocked waiting for the same object (fd). An object often provides an explicit close() method. Close invalidates the file descriptor; before closing it is necessary to unblock all fibers waiting for the descriptor and to prevent more fibers from getting blocked.

This logic is already implemented in highlevel wrapper in the socket module; we are going to need it in database connectors as well and probably all over the place.

Libev is easily hackable to enumerate and kill all watchers associated with a file descriptor.

The suggestion is to wrap a fd in a C structure (structure lifetime == object lifetime) and to change `coio_wait()` interface. This structure wrapper thing will allow for:
 * associating flags with fd (to avoid ev_io_init overhead — see above);
 * preventing fibers from blocking on an object that is about to die;
 * allowing for coio_wait() generalizations: see next section.

#### coio_wait generalization

`coio_wait()` allows to wait for a fd + timeout. When it is necessary to wait for a larger set of events one has to write complex code involving libev watchers and fiber magic.

The suggestion is to implement coio_wait_N and polymorphic waitable objects (the suggested fd wrapper will be the first one).

This will provide a convenient coroutine-friendly interface and will allow to abstract from libev.

**Comment by kostja** [comment]
Please provide an example how you would be able to rewrite net.box given you have this genrealization.

**Comment by mejedi** [comment]
Doesn't feel like a good idea any more :)
