### ISSUE TITLE
Maintain dbg package archive

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#114]
Since distributions require stripped binaries, we can get a core file with no debugging information from a very old version of Tarantool. To be able to debug that core, we need to save an archive of dbg packages for all produced builds of the server.

**Comment by kostja** [comment]
The new policy is to strip and harden the binaries, we need this again.

**Comment by Totktonada** [comment]
We don't follow this policy at the moment: our binaries are not stripped.

In theory we can support external ELF with debug information in `fiber.info()` backtraces (5326), however it is not implemented now. There is nothing to do regarding *this* issue until that: we can't offer separate package with debug info. Closing so.
