### ISSUE TITLE
Add fio.chdir

### ISSUE THREAD

**Issue by mejedi** [tarantool/tarantool#1141]
We need a function in fio module to change working directory.

**Comment by kostja** [comment]
The last patch is OK to push.

**Comment by rtsisyk** [comment]
@kostja this feature should go to 1.7, otherwise we will break box.cfg {}.

**Comment by kostja** [comment]
* Roman Tsisyk <notifications@github.com> [16/01/07 15:47]:
> @kostja this feature should go to 1.7, otherwise we will break box.cfg {}.

just by having the binding we will not break anything. 
people can use it at their own risk.

-- 
Konstantin Osipov, Moscow, Russia, +7 903 626 22 32
http://tarantool.org - www.twitter.com/kostja_osipov

**Comment by kostja** [comment]
Pushed into 1.7.0 branch.
