### ISSUE TITLE
tarantool --cat in 1.6 format

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#1149]
Implement a --output-format 1.6 for tarantool --cat in 1.5, so that stuff from 1.5 snapshots/binary logs can be loaded into an 1.6 instance

The option should accept format specifiers for fields, something like "%d %s %s %s", i.e. hints for cat format, so that --cat doesn't have to guess whether a tuple field is a string or a number.

Do nothing in this ticket about parsing tarantool.cfg and converting it to .lua configuration file format of 1.6 - this can be done manually by the one who's doing the migration.

After this is done, the procedure of 1.5 -> 1.6 migration is this:

- create an 1.6 instance with no data but desired space layout, space identifiers should match those of 1.5
- run --cat for 1.5 snapshot, and load it into 1.6
- continuously run --cat for 1.5 xlogs and keep loading them into 1.6
- stop 1.5 instance, cat the last xlog, and switch over to 1.6

**Comment by bigbes** [comment]
Inherited by https://github.com/tarantool/tarantool/issues/1201
