### ISSUE TITLE
Merge concepts of out-of-memory in index and tuple arenas

### ISSUE THREAD

**Issue by alyapunov** [tarantool/tarantool#1154]
Now when memory is out in index arena, we got OutOfMemory exceptions,
when memory is out in tuple arena - ClientError.
Both situations are the same concept and should have the same error message (variant - should be subtypes of the same exception)

**Comment by kostja** [comment]
The solution is simple - throw ClientError ER_OUTOFMEMORY in both cases.

**Comment by rtsisyk** [comment]
OutOfMemory + ClientError(MEMORY_ISSUE) is a mess. Needs to be discussed.

**Comment by rtsisyk** [comment]
Fixed.
