### ISSUE TITLE
addrinfo is leaked in lua/socket.cc in case of Lua API error

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#1164]
After switching off EXTERNAL UNWIND, freeaddrinfo() may be not called in luasocket.cc in case of API error. 
Similar problem exists in lbox_socket_accept() (fd may be leaked) and recvfrom (buffer may be leaked).

In a similar vein, some region memory may be leaked in lua/pickle.c in case one of the Lua  API calls
throws an error.

**Comment by rtsisyk** [comment]
Please use pcall() inside of lbox_getaddrinfo().

**Comment by rtsisyk** [comment]
Fixed 1.6.8-367-ge04413b.
