### ISSUE TITLE
list of error codes fomatting is garbled

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#1172]
![screenshot from 2015-11-28 01 07 42](https://cloud.githubusercontent.com/assets/482910/11448601/80b77c30-956c-11e5-8913-a04b30f85e50.png)

**Comment by bigbes** [comment]
What does that means?

С наилучшими пожеланиями, Евгений.

2015-11-28 1:08 GMT+03:00 Konstantin Osipov <notifications@github.com>:

**Comment by kostja** [comment]
Sorry, I thought that some errors are formatted and others are not. Apparently it's just the table of contents which is highlighted and clickable.

**Comment by pgulutzan** [comment]
Yes, the table of contents looks bad to some people. Won't fix this year.
