### ISSUE TITLE
Segmented stacks for fibers

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#1173]
1M fibers require 62GB of memory on my machine (default stack size is 64Kb).
Please implemente `-fsplit-stacks` for fibers and decrease the default stack size to 1-2kb.

[1] https://gcc.gnu.org/wiki/SplitStacks
[2] https://blog.cloudflare.com/how-stacks-are-handled-in-go/ (part about segmented stacks)

**Comment by kostja** [comment]
This could also be a very good performance boost.

**Comment by kostja** [comment]
After a quick look this doesn't seem to be either easy to implement or maintain.
