### ISSUE TITLE
Error message for upsert

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#1181]
I have Ubuntu 12.04 and Tarantool 1.6, pulled from tarantool/1.6 today.

I make the following requests:
box.schema.space.create('tester')
box.space.tester:create_index('primary',{})
box.space.tester:insert{'a'}
box.space.tester:upsert({'a'},{{'=',3,2}})

For the insert, the error message is
- error: 'Tuple field 1 type does not match one required by operation: expected NUM'

For the upsert, the error message is
- error: 'Supplied key type of part 0 does not match index part type: expected NUM'

This gives the erroneous impresion that "part 0" means "field#0 in the tuple",
because in both cases it's the same general mistake: putting 'a' in the numeric key.
But it doesn't mean that.  So I suggest changing the error message to
- error: 'Type of first argument in the upsert request does not match index part type: expected NUM'

**Comment by alyapunov** [comment]
I really think that such an error message
- error: 'Type of first argument in the upsert request does not match index part type: expected NUM'

will certainly confuse the user, because first argument must be a tuple (i.e. table in lua)
And I think the error message in upsert must exactly be the same, as in insert:

- error: 'Tuple field 1 type does not match one required by operation: expected NUM'

**Comment by rtsisyk** [comment]
> Tuesday, December 29, 2015 11:16 AM +03:00 from Konstantin Osipov <kostja@tarantool.org>:
>
> * Alexandr Lyapunov <a.lyapunov@corp.mail.ru> [15/12/29 11:08]:
> > /* Check field count in tuple */
> > space_validate_tuple_raw(space, request->tuple);
> > + tuple_validate_raw(space->format, request->tuple);
>
> Both names are meaningless.
> How am I to tell what's the difference between the two?
>

We discussed offline that Alex will open a new ticket for removing space_validate_**():

````
static inline void
space_validate_field_count(struct space *sp, uint32_t field_count)
void
space_validate_tuple_raw(struct space *sp, const char *data)
void
space_validate_tuple(struct space *sp, struct tuple *new_tuple)

void
tuple_field_count_validate(struct tuple_format *format, const char *data). <!-- removed by this patch

+void
+tuple_validate_raw() <!-- added by this patch
```

space->def.field_count (former "arity") should be moved to tuple format.
As result all checks above except tuple_validate_raw(tuple_data) + tuple_validate(tuple) will be removed from the code.
