### ISSUE TITLE
lbox_select() may leak in case of memory failure

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#1182]
Both lbox_select() (Lua/C) and index:select() (FFI) may leak on a memory failure during re-allocating Lua table with results.

https://github.com/tarantool/tarantool/blob/056df8503f1f21a1145c1150c948a5579b2064e1/src/box/lua/schema.lua#L816-L822 (see a line with call to port_buf_destroy).

A test case hard to make, however it should be possible.

**Comment by kostja** [comment]
I'm closing this since, given the tests, we're more likely to run out of finalizers first.
