### ISSUE TITLE
net.box: soft automatic schema reload

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#1183]
Now that the iproto protocol has sc_schema_id, fix net.box as well as all other drivers to perform "soft" schema reload. I call this strategy "soft", since there are many ways to deal with schema changes, and this is only one of them.

So what net.box should do by default:
- load the current schema automatically when connection is established
- include sc_schema_id in queries
- if the response is ER_WRONG_SCHEMA_VERSION, reload the schema and re-issue the query.

**Comment by Sulverus** [comment]
Implemented soft automatic schema reload + tests. Awaiting for review: https://github.com/tarantool/tarantool/commit/082d26ceec29ea9f656a6e3cc399ba2d3cfe1cae

**Comment by Sulverus** [comment]
+ after review fixes
+ system space/index constants replaced with box.schema.VSPACE_ID/VINDEX_ID
