### ISSUE TITLE
Per-space sophia engine parameters 

### ISSUE THREAD

**Issue by kadavros** [tarantool/tarantool#1188]
Make it possible to set sophia engine parameters per-space, and not only per tarantool instance.
E.g.:
``` lua
test_space = box.schema.space.create('test', {
    if_not_exists = true,
    engine = storage_engine,
    params = "page_size = 32768; compression = 'lz4'"
})
```
or something similar.

**Comment by pmwkaa** [comment]
i suggest to switch box.cfg{ sophia = } to the same format too. From Sophia side i will handle the parsing.

**Comment by kostja** [comment]
Ugh, a raw parameter string looks ugly. No syntax checks, dynamic/static checks, every engine has to invent their own way to handle defaults. Why not use a Lua table with options.

**Comment by pmwkaa** [comment]
Syntax check will be done by Sophia. Sophia knows about configuration var types. String value is easy to serialize also (in _space). But I agree that this way may not fit 'universal configuration'.

Anyway, right now we distinct Sophia configuration from others: box.cfg{ sophia = } and probably should do also box.schema.space.create('test, { sophia = }). Can this solve the problem?

**Comment by kadavros** [comment]
>>> Ugh, a raw parameter string looks ugly.
If we map only given few params to lua table variables, then we'll need to upgrade tarantool for any new requested param, which is ugly too.

**Comment by kostja** [comment]
Upgrading to get features is what you normally have to do, yes.

**Comment by kadavros** [comment]
Ok, I just don't get this 'checks' and 'safety' issues - these are all runtime checks anyway, the difference is only in who does the check - tarantool or sophia. It seems like there is no need to duplicate those checks in tarantool, sophia will handle them. Plus you get all sophia params for free, without the need to duplicate them in tarantool too.

**Comment by kadavros** [comment]
Btw, MondoDB implements this feature the same way for WiredTiger engine tuning: just by transferring raw option string to the engine itself. The only alternative is to duplicate them all and somehow to keep up with new options, which is painful.

**Comment by kostja** [comment]
I never doubted mongo
10 дек. 2015 г. 4:10 PM пользователь "kadavros" <notifications@github.com>
написал:

**Comment by kadavros** [comment]
Ok, then whatever ) we just need to pass some options to sophia per space, the most crucial options are: page_size, compression, node_size, compression_key. And more is better.

**Comment by kostja** [comment]
In MongoDB, storage_engine= spec can be a document, here's the link: 
https://docs.mongodb.org/manual/reference/method/db.createCollection/

**Comment by rtsisyk** [comment]
Discussed with @kostja:

* Re-schedule for 1.6.8 to simplify 1.6.x to 1.7.x upgrade
* Regenerate `bootstrap.bin` to use the new format
* Wrap 1.6.x compatibility code to  `if (is_167_plus) {}` blocks
* Improve error messages ('Wrong index options (field 4): parameter ''holy'' is unexpected')
* Discuss recursive options with @pmwkaa (`memory.limit`)

**Comment by rtsisyk** [comment]
1.6.8-349-ga0dc412
