### ISSUE TITLE
debian/changelog last entry contains version 1.6.5

### ISSUE THREAD

**Issue by coldze** [tarantool/tarantool#1197]
I've cloned repo, switched to tag 1.6.8, built deb-package and was surprised to see 1.6.5 in package name :)

**Comment by bigbes** [comment]
Our build system uses `dch` to update version of package.

С наилучшими пожеланиями, Евгений.

2015-12-10 14:06 GMT+03:00 coldze <notifications@github.com>:

**Comment by coldze** [comment]
Ok, but how that correlates with outdated changelog-file in debian folder?

**Comment by rtsisyk** [comment]
Changelog has been fixed.
I plan to upload new packages to the mainstream debian repository soon.
