### ISSUE TITLE
1.5 -> 1.6 migration framework

### ISSUE THREAD

**Issue by bigbes** [tarantool/tarantool#1201]
The first part of the migration toolkit is to implement a way to read snapshots and xlog files created in Tarantool 1.5..

An example configuration  file:

``` lua
local reader = require('xlog').v15

-- get migrate object
migration_object = reader({
	dir = '.' -- or dir = {xlog = '.', snap = '.'}
	spaces = { -- simple
		[[<old_id>]] = {
			new_id = <num|str>,
			fields = {
				['NUM' | 'STR']+
			}, 
			default = ['NUM' | 'STR']
		},
		[[<old_id>]] = { -- harder, with callbacks
			'insert': <function>(<tuple>, flags),
			'delete': ...,
			'update': ...,
		}
	(...)
	}
})

-- load and convert records from all available xlogs/snaps
migrate_object:resume()
-- stop master here (downtime is going on)
--  load and convert from remaining xlogs 
migrate_object:resume()
```

Two ways:
* simple - you show what spaces to take, how to convert them to the new format a where to put the results
* advanced - you give callbacks per space, manually decode tuples with custom logic, then make something with it manually.

Goals:
- give framework to work with old tuples.

First implementation - pure Lua version, using pickle.

**Comment by rtsisyk** [comment]
1. Please implement 1.5 replication client instead of reading files from disk.
2. You can use space:format() for schema

**Comment by bigbes** [comment]
@rtsisyk 
1) 1.5 replication client may be the second part of this framework
2) `space:format()` schema is not enough for old schema

**Comment by bigbes** [comment]
It's located in repo `https://github.com/bigbes/migrate`. CR neded

**Comment by rtsisyk** [comment]
Moved to https://github.com/bigbes/migrate
