### ISSUE TITLE
madvise MADV_NOHUGEPAGE

### ISSUE THREAD

**Issue by mejedi** [tarantool/tarantool#1202]
Linux madvise has several useful flags: MADV_DONTFORK, MADV_NOHUGEPAGE, MADV_DONTDUMP.

**Comment by kostja** [comment]
MADV_DONTDUMP is too fresh;
Instead of MADV_DONTFORK, we use MMAP_SHARED.
MADV_NOHUGEPAGE is good for 1.5 only, where we should avoid huge pages for performance reasons.
Reclassifying this as an 1.5 issue.

**Comment by kostja** [comment]
Eugene, please add MADV_NOHUGEPAGES to the alloc in 1.5 to avoid performance issues in production.
Should be a one liner change here:
https://github.com/tarantool/tarantool/blob/stable/src/salloc.cc#L172

**Comment by kostja** [comment]
Nice feature, but will not happen in 1.5, and is irrelevant in 1.6+
