### ISSUE TITLE
new tuple format for phia documents

### ISSUE THREAD

**Issue by pmwkaa** [tarantool/tarantool#1214]
Remove the need for allocate and reconstruct tuples from sophia documents during read/cursor allocations

**Comment by rtsisyk** [comment]
I suggest to add `tuple_newv(struct iovec *iov, int iovcnt)` to our API in order to allow construction tuple from parts. Is it easy to do and it definitely will improve performance. I also was asked for this feature from A.Levshin for stored procedures.

**Comment by kostja** [comment]
Superseded by deploying msgpack format.
