### ISSUE TITLE
When do you plan to make the SQL?

### ISSUE THREAD

**Issue by monoflash** [tarantool/tarantool#1220]
I see you still are burning pen on habrahabr...
You did think that the popularity of your database will grow sharply as it will be convenient to work with?
I am personally waiting for SQL, because working with the database in the Lua not convenient.

**Comment by rtsisyk** [comment]
Yes, we plan to add SQL in the near future (work in progress).

**Comment by bigbes** [comment]
It's planned in the next version: https://github.com/tarantool/tarantool/issues/1209

**Comment by rtsisyk** [comment]
Please you our mail list or facebook group fro questions!
https://groups.google.com/forum/#!forum/tarantool
https://www.facebook.com/groups/tarantool/
Thanks!
