### ISSUE TITLE
iPython's like %cpaste functionality as more usable and user-friendly analogue of console.delimiter

### ISSUE THREAD

**Issue by zlobspb** [tarantool/tarantool#1223]
Can't get used to
```lua
console = require('console')
console.delimiter('!')
function f ()
  statement_1 = 'a'
  statement_2 = 'b'
end!
console.delimiter('')!
```

I think it would be much more usable and user-friendly to add iPython's like functionality of %cpaste:
```lua
cpaste
Pasting code; enter '--' alone on the line to stop or use Ctrl-D.
function f ()
  statement_1 = 'a'
  statement_2 = 'b'
end
--
```

**Comment by mejedi** [comment]
Actually in recent Tarantool versions delimiter is unnecessary (#1133).

**Comment by zlobspb** [comment]
it works even better, thank you
but it doesn't work in try.tarantool.org

**Comment by mejedi** [comment]
Confirmed that the current delimiter-less input works for the OP.

**Comment by mejedi** [comment]
Filed bug [#9](https://github.com/tarantool/try/issues/9) against `try.tarantool.org`
