### ISSUE TITLE
Avoid hardcoded IP ports in tests

### ISSUE THREAD

**Issue by anatol** [tarantool/tarantool#1227]
There are some tests that use a specific port. e.g. 

https://github.com/tarantool/tarantool/blob/8e3534cfc907435909791bf93693790408df98ad/test/box/socket.test.lua#L72
https://github.com/tarantool/tarantool/blob/8e3534cfc907435909791bf93693790408df98ad/test/replication/prune.test.lua#L6

These ports might be already used by some other process. Especially it is true for port 8080 that is used as a default by a number of tools. And it will cause tarantool test failure.

Ideally if available port in the test chosen dynamically by passing `0` to `bind()` syscall.

**Comment by rtsisyk** [comment]
+1
test-run definitely must be fixed to use a random port instead of 8080.

**Comment by rtsisyk** [comment]
test-run fixed (port 8080), prune.test.lua fixed.

@GeorgyKirichenko please try to fix socket.test.lua.
This test fails too often on Travis and locally.

**Comment by rtsisyk** [comment]
socket.test also should not try to connect to remote servers
