### ISSUE TITLE
tarantoolctl reload 

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#1229]
`tarantoolctl reload instance` should  flush package.loaded cache and reload the instance script.
This feature makes hot code reload more simple and eliminates needs for `dofile()`.
Discussed with @zlobspb

**Comment by rtsisyk** [comment]
Please file a ticket for module upgrade documentation after implementing this feature.

**Comment by kostja** [comment]
Reload was renamed to eval. I don't think this idea makes any sense after the rename. Why not flush package.loaded inside the loaded code?

**Comment by rtsisyk** [comment]
@kostja we need a consistent solution to reload startup script from tarantoolctl.

**Comment by rtsisyk** [comment]
Moved to 1.7.x

**Comment by rtsisyk** [comment]
>  Reload was renamed to eval. I don't think this idea makes any sense after the rename. Why not flush package.loaded inside the loaded code?

1.6.8:

- `tarantoolctl reload myapp` should alias to `tarantoolctl eval /etc/tarantool/instances.enabled/myapp.lua`
-  Add some examples how to reload code and flush caches to modulekit and example.lua
- Help @lenkis with documentation

**Comment by Mons** [comment]
https://github.com/Mons/tnt-package-reload

**Comment by rtsisyk** [comment]
=> customer switched to 1.7.x with vinyl

**Comment by Mons** [comment]
No future plans no tarantoolctl. Replaced by [tt](https://github.com/tarantool/tt)
