### ISSUE TITLE
better error formatting in interactive console

### ISSUE THREAD

**Issue by mejedi** [tarantool/tarantool#1237]
Multiline Lua error messages are hardly readable:
```
tarantool> require 'xxx'
---
- error: "module 'xxx' not found:\n\tno field package.preload['xxx']\n\tno file './xxx.lua'\n\tno
    file './xxx/init.lua'\n\tno file '/home/mejedi/.luarocks/share/lua/5.1/xxx.lua'\n\tno
    file '/home/mejedi/.luarocks/share/lua/5.1/xxx/init.lua'\n\tno file '/home/mejedi/.luarocks/share/lua/xxx.lua'\n\tno
    file '/home/mejedi/.luarocks/share/lua/xxx/init.lua'\n\tno file '/usr/local/share/tarantool/xxx.lua'\n\tno
    file '/usr/local/share/tarantool/xxx/init.lua'\n\tno file './xxx.lua'\n\tno file
    '/usr/local/share/luajit-2.1.0-beta1/xxx.lua'\n\tno file '/usr/local/share/lua/5.1/xxx.lua'\n\tno
    file '/usr/local/share/lua/5.1/xxx/init.lua'\n\tno file './xxx.so'\n\tno file
    '/home/mejedi/.luarocks/lib/lua/5.1/xxx.so'\n\tno file '/home/mejedi/.luarocks/lib/lua/xxx.so'\n\tno
    file '/usr/local/lib/tarantool/xxx.so'\n\tno file './xxx.so'\n\tno file '/usr/local/lib/lua/5.1/xxx.so'\n\tno
    file '/usr/local/lib/lua/5.1/loadall.so'"
...
```
YAML permits for multiline scalars with no escaping, the following is much nicer:
```
tarantool> require 'xxx'
---
- error: |-
    module 'xxx' not found:
        no field package.preload['xxx']
        no file './xxx.lua'
        no file './xxx/init.lua'
        no file '/Users/n.zavaritsky/.luarocks/share/lua/5.1/xxx.lua'
        no file '/Users/n.zavaritsky/.luarocks/share/lua/5.1/xxx/init.lua'
        no file '/Users/n.zavaritsky/.luarocks/share/lua/xxx.lua'
        no file '/Users/n.zavaritsky/.luarocks/share/lua/xxx/init.lua'
        no file '/usr/local/share/tarantool/xxx.lua'
        no file '/usr/local/share/tarantool/xxx/init.lua'
        no file './xxx.lua'
        no file '/usr/local/share/luajit-2.1.0-beta1/xxx.lua'
        no file '/usr/local/share/lua/5.1/xxx.lua'
        no file '/usr/local/share/lua/5.1/xxx/init.lua'
        no file './xxx.dylib'
        no file '/Users/n.zavaritsky/.luarocks/lib/lua/5.1/xxx.dylib'
        no file '/Users/n.zavaritsky/.luarocks/lib/lua/xxx.dylib'
        no file '/usr/local/lib/tarantool/xxx.so'
        no file './xxx.dylib'
        no file '/usr/local/lib/lua/5.1/xxx.dylib'
        no file '/usr/local/lib/lua/5.1/loadall.dylib'
...
```

**Comment by rtsisyk** [comment]
Output is pretty nice, the patch is good.

The only one problem I see in this patch is modified `libyaml` code.
Currently we use vanilla libyaml and Tarantool can even be compiled with system libyaml via `cmake . -DENABLE_BUNDLED_LIBYAML=OFF`.  I added this option to pass lint checks on Debian.

It'll be great if you can make this fix without touching libyaml. I fixed similar problem for `tutorial()` long time ago and that fix works properly both with system and embedded libyaml. 
Thanks!

**Comment by mejedi** [comment]
>It'll be great if you can make this fix without touching libyaml. I fixed similar problem for tutorial() long time ago and that fix works properly both with system and embedded libyaml.

I would love to avoid touching libyaml if it was possible. Unfortunately, it didn't work.

Basically, lua-yaml decides on the formatting style (that very part you've tweaked for `tutorial()`), and then it asks libyaml to use that particular style. However, if libyaml thinks that requested style is inappropriate for the data at hand, it will pick another one.

Libyaml is being overconservative about the `TAB` character (used in lua error messages).

### YAML 1.1
>Tabs may appear inside comments and quoted or block scalar content.
 Tabs must not appear elsewhere, such as in indentation and separation spaces.

**Comment by rtsisyk** [comment]
> I would love to avoid touching libyaml if it was possible. Unfortunately, it didn't work.

Forking libyaml for the one line just not worth it to me.  Please try to find a workaround and/or open a ticket in [libyaml](https://bitbucket.org/xi/libyaml) if you feel that library is not flexible enough. 
Thanks.

**Comment by rtsisyk** [comment]
Please send your patch to libyaml.
