### ISSUE TITLE
tarantoolctl fails to create /var/lib/tarantool/<instance> directory

### ISSUE THREAD

**Issue by rybakit** [tarantool/tarantool#1246]
Tarantool is installed from the deb `http://tarantool.org/dist/1.6/ubuntu/`.
Full log: https://s3.amazonaws.com/archive.travis-ci.org/jobs/99221583/log.txt.

**Comment by kostja** [comment]
Please push to master.

**Comment by rtsisyk** [comment]
I fixed this problem in deb/rpm packages for 1.6.8 (branch 1.6).
Please re-open ticket if you still have problems.
