### ISSUE TITLE
Remove old docs from tarantool.org

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#1250]
http://tarantool.org/doc/user_guide/sp-box-index.html is accessible to google search, and it is confusing.
The old format manual should only be available for 1.5.

**Comment by Sulverus** [comment]
Done. Old user_guide removed from 1.6 site.
1.6: http://tarantool.org/doc/
1.5: http://stable.tarantool.org/doc/mpage/

**Comment by rtsisyk** [comment]
This bug is not fixed.

**Comment by Sulverus** [comment]
Seems like this file is included in 1.6 site deploy. @bigbes ?

**Comment by Sulverus** [comment]
old cached files in build slave removed.
