### ISSUE TITLE
Multikey index support

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#1257]
To better support proxies for more advanced databases, and to serve our own community better, Tarantool needs to extend data type support in indexes:
- [ ] partial index, if a value is nil, it's not in the index
- [ ] mongo "multikey" index, where, when an indexed field is an array, every entry in the array is added to the index

**Comment by plandem** [comment]
+1 for arrays

**Comment by KlonD90** [comment]
+1 for arrays

**Comment by igorcoding** [comment]
+1 for partial index

**Comment by fsitedev** [comment]
+1 for mongo "multikey"

**Comment by jmenhome** [comment]
array

**Comment by racktear** [comment]
I would be nice if this thing also worked with functional index. e.g. I have a field with a space-separated string, and then a functional index splits it to an array of strings, and I have a string-array index on top of it

**Comment by sharonovd** [comment]
Additional question - how are the records sorted in multikey index?

Basic use-case is the following:
 - addresses are stored (e. g. 'Россия, Калужская область, Калуга, Ленина, 25')
 - multikey index is cared based on all words
 - user expects iterator output to be sorted based on full value (е. g. Калужская область should come before  Калуга)

**Comment by kshcherbatov** [comment]
Multikey indexes in memtex must be implemented over "tuple hints" code rework.
So, #3961 must be merged first

**Comment by kyukhin** [comment]
Done (64704bb3b7aeb72a468ea126063895b0719e9092).
