### ISSUE TITLE
Functional index

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#1260]
Implement functional indexes: 
- [ ] partial index, i.e. the index that only stores a subset of tuples in a space, for example, doesn't store tuples which have nil in the indexed field
- [ ] index based on a stored function
- [ ] multikey index

Implementation plan:
- [ ] store function definition in _func and automatically load/define function on bootstrap (as well as replicate it)

**Comment by kshcherbatov** [comment]
Dependency #4182
