### ISSUE TITLE
update/upsert: support JSON paths

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#1261]
Extend UPDATE syntax to support JSON paths.
- [ ] any update operation can take a field name, not just id, or a path in a field, for example:
- [ ] rename a path

**Comment by Gerold103** [comment]
Proposal:
- Implement json path parser;
- Integrate the parse into tuple_update/upsert_execute.
It allows to execute updates. Also for updates by tuple field names using space format a tuple_format can be used. For example:
```Lua
format = { {name = 'field1', type = 'unsigned'}, {name = 'field2}, {name = 'field3'} }
space = box.schema.space.create('test', {format = format})
pk = space:create_index('pk')
space:replace{1, {value = 2}, 3}
space:update({1}, { {'=', 'field2.value', 20} })
space:get{1} -- returns {1, {value = 20}, 3}
```

**Comment by Gerold103** [comment]
Blocked by #1285

**Comment by Gerold103** [comment]
Update var 1:
```
{'=', 'f.c.d', 40}
{'!', 'f', {e = 1000}}
{'#', 'f.c.e'}
{'#', 'f.c.f[2]', 2}
{'=', 'f.g[3]', 200}
{'+', 'f.c.g.l', 100}
{'!', 'f.g[4]', 300}
{'+', 'f.g[4]', 50}
```

**Comment by Khatskevich** [comment]
why not `-` for delete?

**Comment by Gerold103** [comment]
@Khatskevich because '-' is a subtraction. For deletion already `#` exists - it deletes specified field count starting from an index.

**Comment by Gerold103** [comment]
It was decided, that the current implementation should be continued. JSON trees in their current implementation are too expensive in terms of memory consumption. We should stick to my approach with 'bar's, when we do not store intermediate offsets along a JSON path in an update operation.
