### ISSUE TITLE
Support Lua CLI options

### ISSUE THREAD

**Issue by bigbes** [tarantool/tarantool#1265]
Corresponding `lua` manual:

```
OPTIONS:
       -e stat
              execute statement stat.
       -i     enter interactive mode after executing script.
       -l name
              execute the equivalent of name=require('name') before executing script.
       -v     show version information.
       -E     ignore environment variables.
       --     stop handling options.
       -      stop handling options and execute the standard input as a file.
```

To add more compatibility with Lua (e.g. to support `luarocks` Makefile)

**Comment by kostja** [comment]
LuaJIT does the same:
```
 % ./luajit --help
usage: ./luajit [options]... [script [args]...].
Available options are:
  -e chunk  Execute string 'chunk'.
  -l name   Require library 'name'.
  -b ...    Save or list bytecode.
  -j cmd    Perform LuaJIT control command.
  -O[opt]   Control LuaJIT optimizations.
  -i        Enter interactive mode after executing 'script'.
  -v        Show version information.
  -E        Ignore environment variables.
  --        Stop handling options.
  -         Execute stdin and stop handling options.
kostja@atlas ~/work/tarantool/third_party/luajit/src
```

**Comment by rtsisyk** [comment]
Needed for ZeroBraneStudio:

> Roman Kolchin
It's own lua works fine at the same time:
Debugger server started at localhost:8172.
Program starting as '"/Applications/ZeroBraneStudio.app/Contents/ZeroBraneStudio/bin/lua.app/Contents/MacOS/lua" -e "io.stdout:setvbuf('no')" "/var/folders/3r/t24hrs0x41b3q4bzc7zg8lwc0000gn/T/.chtduK"'.
Program 'lua' started in '/Applications/ZeroBraneStudio.app/Contents/ZeroBraneStudio/myprograms' (pid: 14588).
Debugging session started in '/Applications/ZeroBraneStudio.app/Contents/ZeroBraneStudio/myprograms/'.

**Comment by bigbes** [comment]
Approved by rtsisyk

**Comment by rtsisyk** [comment]
This feature is nice to have for #2067.

**Comment by rtsisyk** [comment]
1.7.4-478-g8c2cf77ea
