### ISSUE TITLE
memtx engine changes in box.cfg{}

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#1268]
Regroup all options related to memtx engine in box.cfg{}:

`box.cfg{memtx = {} }`, where `memtx` is a table of:
- arena - memory given to the engine
- slab_alloc_factor - slab alloc factor in tuple arena (unless we kill it by the time we go in production by implementing the log structured allocator, https://github.com/tarantool/tarantool/issues/1251
- snapshot_interval, snasphot_count, snapshot_period

**Comment by rtsisyk** [comment]
A breaking change, should be done ASAP.

**Comment by rtsisyk** [comment]
Moving cfg changes to 1.8

**Comment by kostja** [comment]
Done.
