### ISSUE TITLE
memtx: replication JOIN should work off a checkpoint, not a snapshot file

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#1271]
Replication JOIN in MemTX engine should create a checkpoint on the fly, and send data from the in-memory state, rather than a disk file. This is a pre-requisite task for #1270 and continuous snapshotting in memtx.

**Comment by rtsisyk** [comment]
rolling feature, moving to 1.7.3

**Comment by kyukhin** [comment]
This issue'll help to avoid creation of initial snapshots.
And thus will allow not to create any snapshot in `wal_mode=none` mode.

I'll set it as prio1.

**Comment by viciious** [comment]
So how does this feature work? Does the newly introduced RO view require additional RAM to function?

**Comment by kostja** [comment]
It uses the same technique as when taking a snapshot - so it does require a little extra ram, yes, but this is the same amount as is usually required to take a snapshot.
