### ISSUE TITLE
sphinxdoc: multiple language support

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#1277]
Extend our sphinxdoc scripts to build the manual in multiple available languages, and, more generally, support translations.

**Comment by bigbes** [comment]
Ways to implement this:
1. Make use of `.po` files for supporting of gettext (http://www.sphinx-doc.org/en/stable/intl.html)
2. Make use of `ifdef` for including files with different suffixes (http://www.sphinx-doc.org/en/stable/ext/ifconfig.html)
