### ISSUE TITLE
tostring() is buggy for numbers

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#1279]
```
---
...
 x = '824708557567779'
---
...
y = tostring(tonumber64(x))
---
...
y
---
- '8.2470855756778e+14'
...
```

https://github.com/tarantool/tarantool/blob/1.6/src/lua/utils.c#L719-L734

**Comment by rtsisyk** [comment]
tostring() is buggy for doubles:
```
tarantool> tostring(824708557567779)
---
- '8.2470855756778e+14'
...
```

**Comment by rtsisyk** [comment]
This problem also presents in the stock LuaJIT:

```
LuaJIT 2.1.0-beta1 -- Copyright (C) 2005-2015 Mike Pall. http://luajit.org/
JIT: ON SSE2 SSE3 SSE4.1 fold cse dce fwd dse narrow loop abc sink fuse
> =tostring(824708557567779)
8.2470855756778e+14
> 
```

```
LuaJIT 2.0.4 -- Copyright (C) 2005-2015 Mike Pall. http://luajit.org/
JIT: ON CMOV SSE2 SSE3 SSE4.1 fold cse dce fwd dse narrow loop abc sink fuse
> =tostring(824708557567779)
8.2470855756778e+14
> 
```

Please investigate LuaJIT sources. Probably LuaJIT should use libc functions or switch to dtoa code by David M. Gay.

**Comment by mejedi** [comment]
LuaJIT uses `sprintf("%.14g")` to format its numbers.

Standard library implementation (`tostring`, etc) is in `luajit/src/lib_base.c`.

Following the breadcrumbs it becomes apparent that `lua_number2str` defined in `luajit/arc/luaconf.h` is responsible for formatting.

**Comment by ptolomaues** [comment]
I think this is bug in tonumber(64) in tarantool and not in tostring() in lua, because

type(tonumber64("9223372036854775807"))
---
- cdata
...
type(tonumber64("824708557567779"))
---
- number

and tostring() work correctly only with cdata

**Comment by rtsisyk** [comment]
>  I think this is bug in tonumber64() in tarantool and not in tostring() in lua, because
>
> type(tonumber64("9223372036854775807"))
>
>    cdata
>
> type(tonumber64("824708557567779"))
>
>   number
>
> and tostring() work correctly only with cdata
>

This is a desired behavior. `lua_Number` is more lightweight then `cdata<uint64_t>`.


Actually, this is no a bug.
It is a desired beh

**Comment by rtsisyk** [comment]
> I think this is bug in tonumber64() in tarantool and not in tostring() in lua, because
> 
> type(tonumber64("9223372036854775807"))
> 
>     cdata
> 
> type(tonumber64("824708557567779"))
> 
>     number
> 
> and tostring() work correctly only with cdata

This is a desired behavior. The reason is that `number` is more lightweight then `cdata<uint64_t>`. 
We've narrowed the range to `[-1e14 + 1, 1e14 -1]` to make `tostring()` to be happy. 
You can always convert you numbers to uint64_t using this trick: `0ULL + lua number`.

**Comment by rtsisyk** [comment]
The workaround has been added to 1.6.8-380-g093828c
