### ISSUE TITLE
Build fail with version 1.6

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#1283]
I have Ubuntu 12.04, gcc 4.7.3.
I cloned Tarantool 1.6 today and attempted to build, thus ...
cd ~
git clone -b 1.6 https://github.com/tarantool/tarantool.git ~/tarantool-1.6
cd ~/tarantool-1.6
#The following is necessary if subdirectory third_party/lua-cjson is empty
git submodule init
git submodule update
 cd ~/tarantool-1.6
 make clean
 rm CMakeCache.txt
 cmake .
 make
The result looks like this:
"
[ 57%] Building CXX object src/box/CMakeFiles/box.dir/memtx_tree.cc.o
In file included from /home/pgulutzan/tarantool-1.6/src/box/memtx_tree.h:55:0,
                 from /home/pgulutzan/tarantool-1.6/src/box/memtx_tree.cc:31:
/home/pgulutzan/tarantool-1.6/src/lib/salad/bps_tree.h: In function ‘int bps_tree_index_debug_check_insert_into_leaf(bps_tree_index*, bool)’:
/home/pgulutzan/tarantool-1.6/src/lib/salad/bps_tree.h:4416:31: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
/home/pgulutzan/tarantool-1.6/src/lib/salad/bps_tree.h:4422:33: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
/home/pgulutzan/tarantool-1.6/src/lib/salad/bps_tree.h: In function ‘int bps_tree_index_debug_check_delete_from_leaf(bps_tree_index*, bool)’:
/home/pgulutzan/tarantool-1.6/src/lib/salad/bps_tree.h:4477:32: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
...
"
and so on.

**Comment by pgulutzan** [comment]
I can make the error disappear by editing
compiler.cmake, and adding on line 165:
"-Wno-sign-compare"
In other words, the cause is the "fix" of issue#1221.

**Comment by rtsisyk** [comment]
Yes, it is a  regression on gcc 4.7.
One liner, will fix today.

**Comment by rtsisyk** [comment]
Fixed
