### ISSUE TITLE
add to doc how to start/stop Tarantool app in different OSs

### ISSUE THREAD

**Issue by lenkis** [tarantool/tarantool#1286]
Kostya, please add details.

**Comment by rtsisyk** [comment]
https://github.com/tarantool/tarantool/blob/gh-1264-systemd/README.systemd.md
https://groups.google.com/forum/#!topic/tarantool-ru/-zz_LvxfKnw (my long post)

**Comment by lenkis** [comment]
Outstanding improvements (to do when @rtsisyk has time):
1) add instructions for debugging with 'abrt' (in notes for 'systemd' users; now we have instructions only for 'coredumpctl')
2) add example for flushing cashes after eval (during Tarantool prod update)
3) add example for configuring deb/rpm assembly (during Tarantool prod update)
