### ISSUE TITLE
Remove space:inc()/space:dec() in 1.7

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#1289]
I have Ubuntu 12.04 and tarantool 1.6, pulled from 1.6 source today.
I execute these requests:
```
box.cfg{}
box.schema.space.create('sophia',{engine='phia'})
box.space.sophia:create_index('primary',{})
box.space.sophia:replace{0,0}
box.space.sophia:inc(0)
box.space.sophia:select{}
```
When the `inc()` happens, there is an error message:

```
- error: Duplicate key exists in unique index 'primary' in space 'sophia'
```

Such an error should mean that the `inc()` failed.
But it succeeded.
When the `select()` happens, there is a correct result:
```
---
- - [0, 1]
...
```

**Comment by pgulutzan** [comment]
The following is not the same as the main example
but I believe it might have the same cause.
I execute these requests:
box.schema.space.create('X',{engine='sophia'})
box.space.X:create_index('X',{parts={1,'NUM'}})
box.space.X:insert{1,-1}
box.space.X:dec{1}
box.space.X:select{}
The dec() request returns an error, but the
select() request shows that it succeeded.

**Comment by rtsisyk** [comment]
1. Rewrite inc()/dec() using upsert()
2. Remove inc()/dec() in 1.7 and suggest to use upsert() directly

**Comment by rtsisyk** [comment]
@kostja: need feedback for this ticket

**Comment by rtsisyk** [comment]
=> Fix `:inc()` using `:get()`

**Comment by rtsisyk** [comment]
inc()/dec() is Tarantool 1.5 legacy. We decided to remove it.

- [ ] Remove implementation and tests from 1.7
- [ ] Open a ticket in tarantool/doc to deprecate this function in 1.6.9 and to remove in 1.7.x.

**Comment by bigbes** [comment]
It's used, so we better document how to implement it/

**Comment by rtsisyk** [comment]
Is it used in 1.6.x?
