### ISSUE TITLE
Runtime and lua memory limit

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#1294]
Add ab option to limit the total amount of memory whuch a single procedure can use or some other means t limit impact of a destructive stired procedure in system memory. Add a simple way to trace Lua code in procedure on to help identify killer query

**Comment by rtsisyk** [comment]
How do you plan to limit Lua memory? Moreover, there is no technology to set quotes per request for region_alloc, slab_cache and so on. This ticket is "raw idea", please consider to convert.

**Comment by igormunkin** [comment]
Well, I see two requests here:

* **Find the issues with Lua memory**: there is Lua memory profiler implemented in scope of #5442; if one has any requests for further enhancements, feel free to open the relevant ticket.
* **Limit Lua memory**: there is a ticket in scope of the centralized config epic with the ideas to implement Lua memory limit to be tweaked in the config file. For more info see #8881.

Considering everything above, I believe this ticket can be closed.
