### ISSUE TITLE
small regression

### ISSUE THREAD

**Issue by alyapunov** [tarantool/tarantool#1298]
It seems that small allocator's performance is not so good as it could be.
I am running the task: create 1M allocations of size 16-256 bytes, and then repeating delete of random allocations and create new of random size (16-256B).
In this task I got about 2.8 Mrps, worse than malloc.
I guess it could be fixes to get at least 6Mrps

**Comment by rtsisyk** [comment]
Fixed by 2df27115c683316d3b80eaf0df9a71208c1515e1
