### ISSUE TITLE
box.pack / box.unpack API changes in 1.6

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#130]
- "w" - was removed during merging MsgPack.
  Reason: pack_varint32 / pick_varint32 were removed.
- "p" - has been changed to encode MsgPack.
  Reason: backward compatibility of box.lua procedures.
  box.pack("p", x) is equivalent to msgpack.encode(x), box.pack("pp", x, y) will pack two MsgPacks in sequence and so on

I think these changes should be documented.

**Comment by Mons** [comment]
It is ok not to have V and R, because they are not standard for packing, but BER-integer (w) and string pointer (p) are extremely required.
