### ISSUE TITLE
Document nil and NULL usage in Lua tables

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#1300]
Lua doesn't handle `nil` inside tables properly. Users should use msgpack.NULL instead.
See #1123 for examples

**Comment by bigbes** [comment]
Also we need to document that `msgpack.NULL` is not equal `nil`. example:
``` lua
tarantooll> if msgpack.NULL then return 1 end
---
- 1
...
tarantooll> if nil then return 1 end
---
...
```

**Comment by kostja** [comment]
What section of the manual do you want changed and in what way?
We already document NULL in many relevant places. 

http://tarantool.org/doc/search.html?q=null&check_keywords=yes&area=default

**Comment by rtsisyk** [comment]
@kostja even @pgulutzan who has written all documentation doesn't known about this Lua pitfall (see initial report in #1123).

**Comment by pgulutzan** [comment]
What is the specific "Lua pitfall" that is relevant for Issue#1123? I suggested in the description of issue#1123 (original title = Comparing nil for select() searches) that comparisons and conversions that involve missing values or explicitly nil/null values are inconsistent. I do not think this has been solved, and I do not think that it can be solved by saying again that msgpack.NULL exists -- for issue#1123, using msgpack.NULL would only cause error messages.

**Comment by rtsisyk** [comment]
@pgulutzan Tarantool doesn't support NULLs in indexed fields.
`box.space.T.index.T:select({'1',nil,'5'},{iterator='EQ'})` is completely equivalent to `box.space.T.index.T:select({'1', '5'},{iterator='EQ'})` because Lua ignores `nil` in tables.

**Comment by pgulutzan** [comment]
@rtsisyk Could you please try your example on the T space that I used for the issue#1123 example? If you really are getting exactly the same result for both requests, then something about our environments is different.

**Comment by lenkis** [comment]
Issues transferred to tarantool/doc repository, see https://github.com/tarantool/doc/issues/64
