### ISSUE TITLE
Incorrect parameter handling in fiber.channel methods

### ISSUE THREAD

**Issue by mejedi** [tarantool/tarantool#1301]
```
tarantool> _TARANTOOL
---
- 1.6.8-400-g34f5774
...

tarantool> f = require('fiber'); a = f.channel(); b = f.channel(100)
---
...

tarantool> a:size()
---
- 0
...

tarantool> a:size(42)
---
- error: 'bad argument #3 to ''?'' (fiber.channel expected, got number)'
...

tarantool> a:size(1, 2, 3, b)
---
- 100
...
```

**Comment by rtsisyk** [comment]
Discussed. Please make a patch to replace relative stack indexes (-1, -2, etc.) to absolute (1, 2, 3) for fiber.channel() bindings.

**Comment by mejedi** [comment]
We should accept nil timeouts as well (`nil==none`, infinite timeout). Comes in handy when you write a function, accepting an optional timeout and passing it further to a channel function, eg:
``` lua
function my_get(channel, optional_timeout)
    -- do things
    -- ...
    channel:get(channel, optional_timeout)
end
```

**Comment by kostja** [comment]
* Nick Zavaritsky <notifications@github.com> [16/01/29 14:07]:
> We should accept nil timeouts as well (`nil==none`, infinite timeout). Comes in handy when you write a function, accepting an optional timeout and passing it further to a channel function, eg:
> ``` lua
> function my_get(channel, optional_timeout)
>     -- do things
>     -- ...
>     channel:get(channel, optional_timeout)
> end
> ``` 

nil != infinity!

nil is nil; nowhere in tarantool nil means infinity; it's a common
design principle


-- 
Konstantin Osipov, Moscow, Russia, +7 903 626 22 32
http://tarantool.org - www.twitter.com/kostja_osipov

**Comment by rtsisyk** [comment]
`get(channel, nil)` should be equivalent to `get(channel)` and  `get(channel)` is equivalent to `get(channel, INFINITY)`

**Comment by kostja** [comment]
ok
