### ISSUE TITLE
Snapshot daemon doesn't remove all xlog files

### ISSUE THREAD

**Issue by kadavros** [tarantool/tarantool#1303]
Snapshot daemon doesn't remove all xlog files.
Config options for snapshot daemon are as follows:
snapshot_period = 3*60*60,
snapshot_count = 5,
tarantool instances had been working for > 12 hours with no input traffic, and still there are 70+ Gb of xlog files.
Expected behavior: all unnecessary xlog files are automatically removed.

**Comment by GeorgyKirichenko** [comment]
Can you attach list of preserved snap and xlog files?

**Comment by kadavros** [comment]
Unfortunately, no. I'll provide them if this behavior happens again.

**Comment by kostja** [comment]
Please re-open when the bug manifests again.
