### ISSUE TITLE
slab_alloc_maximal maximum value

### ISSUE THREAD

**Issue by paoloach** [tarantool/tarantool#1304]
Hi,
needing to have  tuples with a lot of objects, so I try to modify the parameter slab_alloc_maximal in order to put into a single tuple 50M objects.
Unfortunately, I find out that maximum value usable for that parameter is about 63M (bytes),  so I able to create tuples of  about 10M objects.
The weird behavior is that using a more bigger value the value allocable decrease !
I get error as "Failed to allocate 4868574 bytes in slab allocator". I can't allocate 5M when it should capable to allocate almost 100M bytes.

**Comment by kostja** [comment]
Thank you for your report. We will take a look at it. You should keep in mind that every update creates a copy of tuple in Tarantool, so, even though we allow larger slab_alloc_maximal settings, this is not a good design pattern with Tarantool in general. Are you sure you your data model needs tuples so large?

**Comment by paoloach** [comment]
Unfortunately, I need to associate a key to a list of integer and so it seems to me that the more plain model is to use a tuple to contain this list.

Thank,
Paolo

**Comment by GeorgyKirichenko** [comment]
Hi Paolo,
possibly you should set bigger value to slab_alloc_arena, this worked for me.
With latest tarantool 1.6 this should be executed successfully:

box.cfg{slab_alloc_arena = 8,
    slab_alloc_maximal = 256 * 1024 * 1024}

-- a 192 Mb-long random string
print('Generate long random string')
long_str = require('digest').urandom(192 * 1024 * 1024)
print(long_str:len() .. ' bytes generated')

s1 = box.schema.space.create('long_space')
s1:create_index('pk')

print('Insert long tuple to space')
s1:insert({1, long_str})
print('Inserted')

os.exit()

Georgy
