### ISSUE TITLE
CMake fails to correctly report missing packages

### ISSUE THREAD

**Issue by gpryor** [tarantool/tarantool#1306]
On branch 1.6, CMake can't find a package on configuration and instead of reporting the missing package, prints the following,

```
CMake Error at CMakeLists.txt:426 (find_package_message):
  FIND_PACKAGE_MESSAGE Function invoked with incorrect arguments for function
  named: FIND_PACKAGE_MESSAGE
```

A little hard to fix the missing packages!

Happened on armv7h, but I suspect it is global.

**Comment by kostja** [comment]
Hi, thanks for the issue and the pull request, merged.
