### ISSUE TITLE
tuple.so

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#1314]
Create a shared library to read/write data in MsgPack format. 
The library should contain:

```
box_tuple_field();
box_tuple_bsize();
box_tuple_size();
box_tuple_format();
box_tuple_new();
box_tuple_iterator()
box_tuple_iterator_free()
box_tuple_position()
box_tuple_rewind()
box_tuple_seek()
box_tuple_next()
```

The API should take into account byte ordering issues (the data may be created on Intel, and used on ARM)

**Comment by rtsisyk** [comment]
any deadlines?

**Comment by kostja** [comment]
This is done.
