### ISSUE TITLE
Support signed integers in tuple_update

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#132]
Since we have datatypes in 1.6  I propose to patch tuple_update in order to properly support all available numeric data types.

	_(UPDATE_OP_ADD, 1)  + MP_INT, MP_FLOAT, MP_DOUBLE
	_(UPDATE_OP_AND, 2)  + MP_INT
	_(UPDATE_OP_XOR, 3)  + MP_INT
	_(UPDATE_OP_OR, 4)    + MP_INT

**Comment by kostja** [comment]
Pushed.
