### ISSUE TITLE
fio.abspath is broken

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#1321]
```
tarantool> require('fio').abspath('../../test')

---
- /home/roman/tarantool/migration/../../test
...
```

Expected: `/home/roman/test`

**Comment by mejedi** [comment]
We can probably rescue https://github.com/tarantool/tarantool/commit/a0852b53756d0e5a108f99f976eed3df82fe12cc, contains smart pathjoin removing `..` components.
