### ISSUE TITLE
Missing OpenSSL dependency

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#1322]
from `digest.lua`:

```
if ssl == nil then
    local variants = {
        'libssl.so.10',
        'libssl.so.1.0.0',
        'libssl.so.0.9.8',
        'libssl.so',
        'ssl',
    }

    for _, libname in pairs(variants) do
        pcall(function() ssl = ffi.load(libname) end)
        if ssl ~= nil then
            break
        end
    end
end
```

Nice, but `digest` is a core module, used by `net.box` and other.
=> I think we should explicitly link with `libssl` using CMake. 

OpenSSL is a core system library used by, say, sshd. In other words, a Linux/BSD servers without OpenSSL  don't even exist in the universe.

OpenSSL [license](https://www.openssl.org/source/license.html) makes some problems:

```
 * 3. All advertising materials mentioning features or use of this
 *    software must display the following acknowledgment:
 *    "This product includes software developed by the OpenSSL Project
 *    for use in the OpenSSL Toolkit. (http://www.openssl.org/)"
 *
 * 4. The names "OpenSSL Toolkit" and "OpenSSL Project" must not be used to
 *    endorse or promote products derived from this software without
 *    prior written permission. For written permission, please contact
 *    openssl-core@openssl.org.
 *
 * 5. Products derived from this software may not be called "OpenSSL"
 *    nor may "OpenSSL" appear in their names without prior written
 *    permission of the OpenSSL Project.
 *
 * 6. Redistributions of any form whatsoever must retain the following
 *    acknowledgment:
 *    "This product includes software developed by the OpenSSL Project
 *    for use in the OpenSSL Toolkit (http://www.openssl.org/)"
```

Proposed solution for the license problem:

* Add "This product includes software developed by the OpenSSL Project for use in the OpenSSL Toolkit. (http://www.openssl.org/)" clause to http://tarantool.org/doc/reference/digest.html
* Write a log message on the first usage of `digest`.

Alternative, we can try to find a better library..

**Comment by kostja** [comment]
Roman, I fail to see where we violate this licence. This is a non-issue. In any case our bug tracker is not an appropriate forum for this sort of requests since licensing is badly understood in the community and any discussion like that creates FUD (fear, uncertainty, doubt).

**Comment by mejedi** [comment]
We still need a reliable loading, the current approach with explicit listing of every version of the openssl library doesn't work well (currently broken on Debian Stretch).

**Comment by rtsisyk** [comment]
=> link with OpenSSL

**Comment by rtsisyk** [comment]
Fixed
