### ISSUE TITLE
print ucontext/registers in sig_fatal_cb

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#1325]
Print the registers in sig_fatal_cb()

**Comment by rtsisyk** [comment]
@kostja who need this feature? Why it was scheduled for 1.6.x?
I don't think that we should re-invent GDB. Please convert to "raw idea" and/or 1.8.

**Comment by kostja** [comment]
I do. There is no gdb if there is no core file.
1 апр. 2016 г. 5:41 PM пользователь "Roman Tsisyk" <notifications@github.com>
написал:

**Comment by rtsisyk** [comment]
I don't think that have enough time in this milestone to re-invent gdb.

**Comment by rtsisyk** [comment]
libbfd  can be replaced by libunwind: http://www.nongnu.org/libunwind/docs.html
libunwind can unwind stacks based on DWARF information and print function names, registers and other information, even if -fomit-frame-pointer is enabled.

**Comment by kostja** [comment]
This is done by Ivan Kosenko
