### ISSUE TITLE
Secondary Index support for phia backend

### ISSUE THREAD

**Issue by crudbug** [tarantool/tarantool#1327]
From - http://tarantool.org/doc/book/box/sophia_diff.html#sophia-diff 

Are there any plans to support secondary indexes with Sophia backend ?

**Comment by pmwkaa** [comment]
Hi, yes it is planned. I believe the secondary indexes support will be available for testing in following 1-2 month time. thanks

**Comment by pmwkaa** [comment]
related task: https://github.com/tarantool/tarantool/issues/623

**Comment by rtsisyk** [comment]
This ticket is duplicate of #623
