### ISSUE TITLE
Figure out why Tarantool is too slow on AWS

### ISSUE THREAD

**Issue by danikin** [tarantool/tarantool#1336]
I ran Tarantool on AWS micro instance with one CPU core and came across the following problem. The maximum performance is 60-70K select sync requests per second. Tarantool uses 73% CPU, test uses 27% CPU. So we can extrapolate this to 90K selects per sec per core which is still pretty slow for Tarantool.

I'm using a table with one hashed index and another integer field. Source code for the test is here: https://github.com/tarantool/tarantool/issues/1335

If it is possible to make more than 100K selects per sec in the sync mode on one CPU core then please provide me with the full access to an AWS (or whatever) instance with the Tarantool instance and the test that can prove it. If you do so and if I make sure it really works this fast then I'll close this issue.

**Comment by kostja** [comment]
Sorry, this is not an appropriate forum for general complaints. If you have a specific enhancement request, or a bug report, please don't hesitate to open a separate ticket.
