### ISSUE TITLE
fio: provide access to stdin/stdout/stderr

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#1338]
Make it possible to read stdin/stdout/stderr using fio API. Update the documentation.

**Comment by rtsisyk** [comment]
Who need this feature in 1.6.x? Please consider to move to 1.7.x

**Comment by rtsisyk** [comment]
There is no customer => wishlist

**Comment by olegrok** [comment]
quite strange way (read as workaround) to do this
```lua
fd = fio.open('/dev/null')
fd.fh = 2 -- or 1 for stdout
tarantool> fd:write('test')
test---
- true
...
```

**Comment by igormunkin** [comment]
@olegrok, it looks more like a bug than a workaround. IMHO, `fd.fh` field ought to be immutable.
@kyukhin, I think it have to be fixed.

**Comment by printercu** [comment]
@cyrillos looks like non-blocking pipe io from #4031 can be useful for this one.

**Comment by printercu** [comment]
@igormunkin I think even if `io.stdin:read` will be fixed to be non-blocking, there should be fio interface for this standard descriptors because `fio` and `io` have different api. Modules like `csv` work only with `fio`.

**Comment by olegrok** [comment]
Sorry, it was a mistake. Reopened.
