### ISSUE TITLE
Enable tests for Debian

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#1341]
https://github.com/tarantool/test-run has too many Python dependencies (gevent is most problematic).
I was unable to get all this stuff working on old Ubuntas and Debians.
Please find a way to enable tests for Debian packages.

**Comment by rtsisyk** [comment]
https://raphaelhertzog.com/2010/09/27/different-dependencies-between-debian-and-ubuntu-but-common-source-package/

**Comment by Totktonada** [comment]
The similar problem on CentOS 6, see 2d8b6cb304ff1784e0e680607e17ae35d6d39d4f.

**Comment by Totktonada** [comment]
CentOS 6 is gone, so I removed it from the issue title.
