### ISSUE TITLE
Segmentation fault with small slab_alloc_arena

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#1345]
I have Ubuntu 12.04 and Tarantool 1.6, pulled from 1.6 source today.

I start with an empty directory, I create a space with one
index, and I attempt to insert many random tuples into it,
just as in the tutorial in the manual. But I start with
"box.cfg{slab_alloc_arena=0.01, snapshot_period=1, ...".
So it would be fair to get an error message saying
"error: Failed to allocate xxx bytes ..."
Usually I do get that.
But if I call the function multiple times anyway,
I eventually see a segmentation fault.

This is minor but I report it because a bit of the output
resembles what I see in Issue#1319 Segmentation fault.

How to repeat:

box.cfg{slab_alloc_arena=0.01, snapshot_period=1, log_level=3}

box.schema.space.create('tester')
box.space.tester:create_index('primary',{})

function string_function()
  local random_number
  local random_string
  random_string = ""
  for x = 1,10,1 do
    random_number = math.random(65, 90)
    random_string = random_string .. string.char(random_number)
  end
  return random_string
end

function main_function()
  local string_value, t
  for i = 1,1000000,1 do
    string_value = string_function()
    t = box.tuple.new({i,string_value})
    box.space.tester:replace(t)
  end
end

main_function()
main_function()
main_function()

Results vary, but this is typical:
"
tarantool> main_function()
Segmentation fault
Current time: 1456076097
Please file a bug at http://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed, 
this may fail as well
#0  0x42ca41 in sig_fatal_cb(int)+129
#1  0x7f766ecbbcb0 in ?
#2  0x507327 in lj_BC_FUNCC+52
Aborted (core dumped)
"

**Comment by rtsisyk** [comment]
Confirmed.
