### ISSUE TITLE
Tarantool-PHP documentation review

### ISSUE THREAD

**Issue by bigbes** [tarantool/tarantool#1355]
Documentation located at https://github.com/tarantool/tarantool-php/blob/master/README.md

**Comment by rtsisyk** [comment]
Please track tarantool-php tickets in tarantool-php project. Thanks!

**Comment by bigbes** [comment]
I can't link @lenkis to issues in tarantool-php.
26 февр. 2016 г. 22:45 пользователь "Roman Tsisyk" <notifications@github.com>
написал:

**Comment by lenkis** [comment]
Now watching php issues, please feel free to add documentation issues to tarantool-php project.

**Comment by rtsisyk** [comment]
> I can't link @lenkis to issues in tarantool-php.
Fixed, please move ticket to tarantol-php.

**Comment by lenkis** [comment]
Please verify & review language issues in this readme.

**Comment by lenkis** [comment]
Updated README.md + README.PACK.md in this repo and PHP driver info in the main Tarantool manual.
