### ISSUE TITLE
Missing #include "config.h" in eio.c

### ISSUE THREAD

**Issue by viciious** [tarantool/tarantool#1361]
src/third_party/libeio/eio.c is missing #include "config.h" and thus renders running ./configure totally useless.
As the result of that, we're experiencing problems compiling libeio which is bundled with tarantool source code.
Please consider adding the suggested #include statement to stay consistent with the upstream: http://cvs.schmorp.de/libeio/eio.c?view=markup

**Comment by kostja** [comment]
We're not using libeio configure and you shouldn't either. What exactly are you trying to do?

**Comment by viciious** [comment]
Thanks! We'd been looking for a way to statically link Tarantool's xlog/snapshot utility functions which also brought in the dependency on libeio.
We ended up forking the functions we need and removing all libeio calls.

Marking the issue as resolved.
