### ISSUE TITLE
Tarantool C library reads more responses then the number of resuests on Google Cloud Platform and Digital Ocean

### ISSUE THREAD

**Issue by danikin** [tarantool/tarantool#1371]
1. Doing this test on Google Cloud Platform: https://gist.githubusercontent.com/danikin/a5ddc6fe0cedc6257853/raw/8d91a5610f8e4fa949a054196a3c8ea99901afd2/tar_test.c
2. Running it like this: `./tar_test 10.140.0.2:3301 read 1 10000000`
3. Got the result like this:

	```
	danikin1@tarantool-client tar_test]$ ./tar_test 10.140.0.2:3301 read 1 10000000
	Requests per second: 330965, Responses per second: 330574, Pending requests: 391, Latency in momentum: 1.182791 ms
	Requests per second: 196406, Responses per second: 822656, Pending requests: -625859, Latency in momentum: -760.778503 ms
	Requests per second: 173066, Responses per second: 854383, Pending requests: -1307176, Latency in momentum: -1529.964899 ms
	Requests per second: 191017, Responses per second: 190910, Pending requests: -1307069, Latency in momentum: -6846.519302 ms
	```
4. Which means that tarantool-c library gets more responses then the number of requests being sent. Which is a bug. Right?

I feel that there is some problem of multithreaded environment. I send requests in one thread and get responses in another one. Maybe tarantool-c has some race conditions working this way.

The funny thing is that it that I can't reproduce the bug on AWS but I easily reproduce it on Google Cloud.

**Comment by danikin** [comment]
It seems to be that tnt_stream::data is used for both forming requests and receiving responses. If that's true then the easiest way fix it is to split this buffer into two and to use each of them for read and write separately.

**Comment by danikin** [comment]
Got the same thing on a Digital Ocean instance:

Requests per second: 870239, Responses per second: 20446755, Pending requests: -19576516, Latency in momentum: -957.438772 ms
Requests per second: 704241, Responses per second: 42207688, Pending requests: -61079963, Latency in momentum: -1447.128850 ms
Requests per second: 829902, Responses per second: 37152033, Pending requests: -97402094, Latency in momentum: -2621.716394 ms
Requests per second: 719356, Responses per second: 46420286, Pending requests: -143103024, Latency in momentum: -3082.769115 ms
Requests per second: 720833, Responses per second: 47102886, Pending requests: -189485077, Latency in momentum: -4022.791236 ms
Requests per second: 717184, Responses per second: 47079204, Pending requests: -235847097, Latency in momentum: -5009.581237 ms
Requests per second: 818475, Responses per second: 38924083, Pending requests: -273952705, Latency in momentum: -7038.128682 ms
Requests per second: 1037869, Responses per second: 18598338, Pending requests: -291513174, Latency in momentum: -15674.151852 ms
Requests per second: 1393542, Responses per second: 2068727, Pending requests: -292188359, Latency in momentum: -141240.656210 ms

**Comment by danikin** [comment]
I came up with an idea how to deal with this problem.

According to this piece of code if there is nothing to read then read_reply returns immediately:

static int
tnt_net_reply(struct tnt_stream *s, struct tnt_reply *r) {
	if (s->wrcnt == 0)
		return 1;
	pm_atomic_fetch_sub(&s->wrcnt, 1);
	return tnt_reply_from(r, (tnt_reply_t)tnt_net_recv_cb, s);
}

So what I need to do is just to check read_reply on 1 return value. If it is 1 then there is nothing to read and I should just wait.

But I'm still a little bit concerned about this feature. Is it documented?

**Comment by bigbes** [comment]
Problem was in atomic loads (that weren't atomic) and in parsing code of `read_reply`.
`tnt->read_reply` needs to be documented.
