### ISSUE TITLE
Document multi-master replication configuration and box.cfg.readonly

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#1372]
In 1.6.8 it's possible to provide multiple replication sources in an array, like this:

```box.cfg{replication_source={'uri1', 'uri2', 'uri3'}}```

It is also possible to dynamically set any replica to read only mode:

`box.cfg{readonly=true}`

This needs to be reflected in the manual.

**Comment by gpryor** [comment]
I could use this ASAP! I apologize if I missed something in the manual, but could you comment on how this is done so that I can test this, now?

**Comment by kostja** [comment]
Here's a discussion of the new option: 

https://groups.google.com/d/msg/tarantool/ZtL6fI7TZ0M/735fT32nBQAJ

Please check out the tests as well: 

https://github.com/tarantool/tarantool/blob/1.6/test/replication-py/multi.test.py#L44
