### ISSUE TITLE
Support https in http rock

### ISSUE THREAD

**Issue by evgeny-sureev** [tarantool/tarantool#1377]
I encountered an error when trying to require module `socket.http`.

Steps to reproduce:
1. Create file `test.lua`

```
package.loaded['socket.http'] = nil
http = require "socket.http"
```
1. Execute command `tarantool test.lua` and get an error message:

```
test.lua: /usr/local/share/lua/5.1/socket/http.lua:89: attempt to index field 'sourcet' (a nil value)
```

Tarantool version 1.6.7-630-geab01da

**Comment by bigbes** [comment]
1) You better use http://github.com/tarantool/http for means of http server/client. It uses our socket API, that doesn't blocks Tarantool.
2) Our socket module is interfiering with LuaSocket. It's not initialized [properly](https://github.com/diegonehab/luasocket/blob/master/src/socket.lua#L73)

**Comment by evgeny-sureev** [comment]
`socket.http` not used in my code, it used in LuaSec's [https.lua](https://github.com/brunoos/luasec/blob/master/src/https.lua#L12), which in turn used by [LuaVkApi](https://github.com/last-khajiit/lua-vk-api), which I use.

**Comment by kostja** [comment]
I see that LuaVkApi uses https.lua in a single place in this file, would it be possible to use our http.client.request instead? 
https://github.com/tarantool/http/blob/master/http/client.lua#L24

**Comment by bigbes** [comment]
You may unload preloaded socket module using
```
package.loaded['socket'] = nil
```
and then you may try to `require()` what depends on custom (not embedded) socket.lua

**Comment by bigbes** [comment]
Please, let us know if it'll work for you.

**Comment by evgeny-sureev** [comment]
Rewrited luaVKApi using tarantool's http module, like @kostja said.

**Comment by kostja** [comment]
* Evgeny Sureev <notifications@github.com> [16/03/11 15:53]:
> Rewrited luaVKApi using tarantool's http module, like @kostja said.

Nice, could you fork it into our org or at least give me a link
I'll tweet it? 

We can also add it to our rocks repository at rocks.tarantool.org

-- 
Konstantin Osipov, Moscow, Russia, +7 903 626 22 32
http://tarantool.org - www.twitter.com/kostja_osipov

**Comment by evgeny-sureev** [comment]
It seems that http://github.com/tarantool/http not support https requests.

**Comment by kostja** [comment]
This is done.
