### ISSUE TITLE
Documentation for crypto module

### ISSUE THREAD

**Issue by GeorgyKirichenko** [tarantool/tarantool#1379]
For issue 1316 a new "crypto" module was added to tarantool builtin modules.
Crypto provides two interface: digest and cipher.
First interface would be used for digest calculation and contains definitions for digest algorithms:
md2, md4, md5, sha, sha1, sha224, sha256, sha384, sha512, dss, dss1, mdc2 and ripemd160. Each definition contains method new that will create a 'context' object, or can be called itself to calculate digest from passed string.
Digest context object contains methods init, update, result and free. Update can be called multiple times to add new chunk of data to hashed value. After adding last chunk of data result should be called to obtain a digest value. If we want to use context object later then we must call init method. This method will reinitialize a digest context. Free method will free all associated resources.
 
Cipher interface consists of des, aes128, aes192 and aes256 items. Each item contains subitems with cipher modes: cbc, cfb, ecb. Each mode object contains from encrypt and decrypt items.
Encrypt and decrypt items can be called itself to encrypt or decrypt data with passed key and initial vector. Encrypt and decrypt items contains method new, that will create a cipher context object.
Cipher context has similar api as digest context object: init, update, result and free. But for encrypt and decrypt context objects we must call init with key and initial vector.

Examples can be found in src/lua/digest.lua

**Comment by campbx** [comment]
Hi there, any plans to add SHA3 to the crypto module?

**Comment by kostja** [comment]
Hi, this bug is closed, could you please file a separate feature request?
