### ISSUE TITLE
small submodule depends on exeption.h

### ISSUE THREAD

**Issue by alyapunov** [tarantool/tarantool#1384]
There are a pair of functions with 'xc' postfix in small sub-module. That why "exeption.h" is included and the small depends on exceptions definition.

This dependency hinders usage of small submodule as a standalone project.

I beleive 'xc' functions must be moved to somewhere like 'small_xc.h' (and possibly 'small_xc.cc')

**Comment by rtsisyk** [comment]
=> https://github.com/tarantool/small/issues/7
