### ISSUE TITLE
Replace all (struct tuple *) pointers with a (struct tuple_id) instances

### ISSUE THREAD

**Issue by alyapunov** [tarantool/tarantool#1385]
In order to introduce new log structured allocator into tarantool we have to make an intermediate step as described in issue title.
This a long routine work that may cause a lots of mistakes and it is better to be done apart from new allocator integration.

**Comment by rtsisyk** [comment]
Reviewed today.

**Comment by rtsisyk** [comment]
Pushed to 1.8

**Comment by kostja** [comment]
Original patch: [gh-1385-tuple-id-original.txt](https://github.com/tarantool/tarantool/files/693502/gh-1385-tuple-id-original.txt)
Patch rebased to 1.7: [gh-1385-tuple-id.txt](https://github.com/tarantool/tarantool/files/693501/gh-1385-tuple-id.txt)

**Comment by rtsisyk** [comment]
OK, moved to 1.8

**Comment by kostja** [comment]
We will not do this in the near future, since we integrated sophia for which it was necessary.
