### ISSUE TITLE
tarantool-devel is necessary for rocks, but is not installed

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#1388]
To install http rock from rocks.tarantool.org, one needs tarantool-devel package. this package is not installed. 

this is a change requeset for rocks.tarantool.org page, the instructions need to be brought up to date.

**Comment by bigbes** [comment]
It's not rocks related, it's related to packages. And it's described in every package

**Comment by rtsisyk** [comment]
I updated readme.
https://github.com/tarantool/rocks/commit/f8b7fe83abd3aa6ec0727d36aad91133bbf8be86
