### ISSUE TITLE
tarantool doesn't start listening on existing socket file

### ISSUE THREAD

**Issue by hengestone** [tarantool/tarantool#1395]
Using a simple configuration with version 1.6.8-581-g15766a8:
`box.cfg {
  listen: '/var/lib/tarantool/mydb.sock'
}
`

tarantool doesn't start if the file `/var/lib/tarantool/mydb.sock` already exists:
`iproto evio.cc:347 W> binary: unix/:/var/lib/tarantool/mydb.sock is already in use, will retry binding after 0.100000 seconds.`

The socket file is not in use by any other process according to `lsof`, this was after a reboot with the configuration loaded from `/etc/tarantool/instances.enabled/mydb.lua` by `tarantoolctl start mydb`

**Comment by hengestone** [comment]
Since this is tangentially related to #1405 (tarantoolctl won't open control socket):
Would it be possible to specify the connect uri as a tarantoolctl option, then have tarantool use that as the default to box.cfg.listen?

That would make it possible for tarantoolctl to use the same logic to remove a data socket if needed at the same time as the control socket.

Thanks :)

**Comment by kostja** [comment]
We'll just try to open the file and if it's dead, remove it.

**Comment by bigbes** [comment]
@hengestone now I get it, it's not tarantoolctl related.

**Comment by hengestone** [comment]
Yes this happens in the main 'tarantool' server :)  But my thinking was that it could be something that tarantoolctl' could handle elegantly since it deals with pid files and the control socket already.

If it's simple to determine if the current data socket is dead and remove it at server startup time, that's great :+1:

**Comment by rtsisyk** [comment]
This problem should be fixed in the same way as it was done for console.listen() - try to connect to existing socket file and than remove it on fail.

**Comment by rtsisyk** [comment]
Affects me too.
