### ISSUE TITLE
fiber.join()

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#1397]
Expose joinable fibers to Lua and implement `fiber.join(<fiber>)`.
To join a fiber, it needs to be "joinable". By default, Tarantool fibers are not joinable, i.e. self destruct when a fiber function ends. We need an api call `fiber.set_joinable()` to turn "joinable" property on and off.
`fiber.create()` immediately invokes the created fiber, yielding the caller, after which "joining" it could be too late. 
It would be nice to:
- have a way to create a fiber, schedule it for execution, but not invoke yet: invocation yields, and yields are not allowed in a memtx transaction
- set properties for the fiber
- the created fiber is "ready to run" and is invoked when the caller yields.

Let's add a separate call for it. Let's use `fiber.new()`. The method signature should be the same as in fiber.create(), but behavior should be as described above. After a fiber is created, its property could be set with `fiber.set_joinable(true|false)`, where false is the default initial value.

**Comment by rtsisyk** [comment]
fiber.join() should return a Lua object from by a fiber function.

**Comment by unera** [comment]
> fiber.join() should return a Lua object from by a fiber function.

also should throw exception from by a fiber function

**Comment by kostja** [comment]
I rebased the patch. I agree we need to pass the return value from the called fiber to fiber.join. For this purpose, we need to capture child_L lua state somewhere, perhaps in a fiber key. The patch should not duplicate fiber_recycle(), and call fiber_join() instead.
