### ISSUE TITLE
tarantoolctl ignores work_dir option

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#1406]
tarantool ignores `work_dir` option in `box.cfg{}` and uses default or relative pathes for xlogs and snapshots directories

**Comment by kostja** [comment]
It doesn't ignore it, it overrides it with the setting from /etc/sysconfig/default/tarantool

**Comment by rtsisyk** [comment]
My customer has the following configuration:

```
box.cfg {
  work_dir = "/mnt/some-tarantool-data/";
  wal_dir = "wals/";
  snap_dir = "snaps/";
}
```

tarantoolctl creates `/var/lib/tarantool/instance/wals|snaps/` instead of `/mnt/some-tarantool-data/wals|snaps/`

**Comment by rtsisyk** [comment]
=> Please use absolute paths in snap_dir, wal_dir and sophia_dir.
work_dir is legacy (see #1425).

**Comment by kostja** [comment]
Roman, it's not an issue of absolute paths, it's an issue that work_dir is taken from /etc/sysconfig/default.
