### ISSUE TITLE
failed to recover sophia space

### ISSUE THREAD

**Issue by man0xff** [tarantool/tarantool#1408]
init.lua:

    box.cfg{
        listen = 3312,
        work_dir = '.',
        pid_file = 'box.pid',
        snap_dir = 'snaps',
        wal_dir = 'xlogs',
        wal_mode = 'none',
        log_level = 5,
        logger = 'logs/tarantool.log',
    }
    require('console').listen(3412)
 
    local s = box.schema.create_space('sophia_space', {
        engine = 'sophia',
        if_not_exists = true,
    })
    s:create_index('primary', {
        type = 'tree',
        parts = {1, 'num'},
        if_not_exists = true,
    })

At first start dir with name `512` was created. Then I stop tarantool, try to start again and get error:

    2016-03-25 13:01:20.772 [14490] main/101/test.lua F> sophia/index/si_recover.c:611 directory './512' already exists                                                             

With `box.snapshot()` command before stop tarantool all is fine.

**Comment by pmwkaa** [comment]
These situation happened due to **wal_mode = 'none'**, i'm not sure whether this is a bug or a feature in that case.

**Comment by rtsisyk** [comment]
Please make box.snapshot() after performing DDL requests (box.schema.space.create and so on).
