### ISSUE TITLE
Tarantool dead after start, but it doesn't say that it died

### ISSUE THREAD

**Issue by agent-0007** [tarantool/tarantool#1409]
Tarantool 1.6.8-586-g504e151

I tryed start my tarantool. It says that it has been started and everything ok!
```
[root@hack_srv lua]# /etc/init.d/tarantool start
tarantool: Starting instances
/usr/bin/tarantoolctl: Found tt.lua in /etc/tarantool/instances.enabled
/usr/bin/tarantoolctl: Starting instance...

```
My app doesn't work... i go to tailing logs:

```
2016-03-25 14:28:23.103 [11348] main/101/tarantoolctl C> version 1.6.8-586-g504e151
2016-03-25 14:28:23.103 [11348] main/101/tarantoolctl C> log level 4
2016-03-25 14:28:24.217 [11348] main/101/tarantoolctl recovery.cc:211 W> file `/var/lib/tarantool/ tt/00000000000000571359.xlog` wasn't correctly closed
2016-03-25 14:28:24.218 [11348] main/101/tarantoolctl recovery.cc:211 W> file `/var/lib/tarantool/tt/00000000000000571359.xlog` wasn't correctly closed

sp_get(0x2889470): attempt to use destroyed object

```

```
[root@hack_srv lua]# ps ax|grep tarantool
11316 pts/0    S+     0:00 tail -f /var/log/tarantool/tt.log
13048 pts/1    S+     0:00 grep tarantool
[root@hack_srv lua]# 
```

Repeate this bug:
you need change you lua ccode and make mistake.
For example:
```
function move_tuple(space_id, args, tuple)
	log.error(tupleAAAA); -- make mistake at this string ;(
	box.space[space_id]:delete{tuple[1]}
end
```

Restart tarantool and take this error in log.

I suppose, that tarantool must check lua for mistakes before start, and if an error occurred - don't start!

**Comment by bigbes** [comment]
I see a couple of bugs:
1) `sp_get(0x2889470): attempt to use destroyed object` - sophia crash
2) `log.error(tupleAAAA); -- make mistake at this string ;(` - lua is dynamic language, this error can be found only at runtime (or you may use linter).

Resolution for this issue:
1) sophia error must be investigated separately
2) add check that script syntax(!!) is OK, then restart tarantool

**Comment by agent-0007** [comment]
How i can check syntax before start ?
If error in lua scripts appears on production via puppet, and tarantool on restart say to puppet "OK" (really not started) - it will be BIG FAIL!!!

I think: it's no a feature - it's a bug!

**Comment by bigbes** [comment]
> How i can check syntax before start ?
It will be added into tarantoolctl

> If error in lua scripts appears on production via puppet, and tarantool on restart say to puppet "OK" (really not started) - it will be BIG FAIL!!!

Again, there's two types of errors:
1) syntax errors - that can be found at compile time
2) semantics errors - can be found only at runtime.

Tarantool can't fight with semantics errors, but it can check for syntax errors before restart.

**Comment by pmwkaa** [comment]
sp_get() crash related to incorrect usage from Tarantool side (create/destroy race).
ref #1416.

**Comment by bigbes** [comment]
@pmwkaa i meant Sophia related, not `tarantoolctl` related.
