### ISSUE TITLE
Check data dictionary version in 1.7

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#1414]
@kostja: on start of 2.0 read schema.version from box.space._schema and fail if version < 1.6.8
See also #1281

**Comment by rtsisyk** [comment]
There are no reasons to fail on <1.6.9 data. Please consider to move to 1.7.4.

**Comment by rtsisyk** [comment]
1.7.4 is still backward-compatible with 1.6.x. Moved to 1.7.5.

**Comment by kyukhin** [comment]
All checks are performed in `upgrade.lua` script. No need to do such checks in core.
