### ISSUE TITLE
Document console.ac

### ISSUE THREAD

**Issue by mejedi** [tarantool/tarantool#1418]
Tab completion in interactive console is enabled by default (except for remote sessions which aren't supported yet). A new function was added in console module:
```lua
require("console").ac(false) -- autocompletion off, TAB key inserts literal TAB
require("console").ac(true)  -- TAB key triggers autocompletion
```
This option is not persisted; `ac` is `true` again after a restart.

Related: #1413

**Comment by rtsisyk** [comment]
Isn't it better to name this feature `console.autocompletion()` or `console.completion()` instead of `console.ac()`?

**Comment by mejedi** [comment]
Too much typing to my taste.
