### ISSUE TITLE
bad slab_alloc_minimal causes assertion

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#1419]
I have Ubunbu 12.04 and Tarantool 1.6, pulled from source today.

I execute the following request:
box.cfg{slab_alloc_minimal=1048576}

The result is an assertion:
tarantool: /home/pgulutzan/tarantool-master/src/lib/small/small/small.c:110: small_alloc_create: Assertion `alloc->objsize_max > objsize_min + STEP_POOL_MAX * STEP_SIZE' failed.
Aborted (core dumped)

I am aware that this is not a good setting; however, It would be okay to spit out
an error message and stop the server, but assertions look bad, they resemble crashes too closely.

**Comment by rtsisyk** [comment]
Confirmed.
