### ISSUE TITLE
tarantoolctl and custom logger

### ISSUE THREAD

**Issue by bigbes** [tarantool/tarantool#1423]
Current logger option supports many options:
- `|` and `pipe:` - for piping output
- `file:` and simple - for file
- `syslog:` - for syslogd

but tarantoolctl understands only piping (`|`). We need to extend the support of loggers in it.

**Comment by rtsisyk** [comment]
I don't think that anybody need a custom value for logger when tarantoolctl is used.

**Comment by rtsisyk** [comment]
Anyway,  it is easy to fix than to document.

**Comment by bigbes** [comment]
> I don't think that anybody need a custom value for logger
Are you sure?
