### ISSUE TITLE
Deprecate work_dir option in Tarantool 1.7

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#1425]
Please use absolute paths in snap_dir, wal_dir and phia_dir.
This change already was discussed during reviewing fio.chdir() patch.

**Comment by rtsisyk** [comment]
Probably 1.8... Definitely now for 1.7.0 (alpha).

**Comment by kostja** [comment]
I don't know why we should do this at all. Let's not spend time on this.
