### ISSUE TITLE
ER_NO_SUCH_INDEX error in sql CREATE TABLE

### ISSUE THREAD

**Issue by feldsherov** [tarantool/tarantool#1429]
space.h:189 E> ER_NO_SUCH_INDEX: No index #0 is defined in space <space_name> occurs, when you execute CREATE TABLE in lldb.

For example in below script:

box.cfg{}
r = require('sql')
c = r.connect('test')
c:execute("CREATE TABLE test12 (id INT, PRIMARY KEY (id))")

**Comment by Gerold103** [comment]
Error was in get_trntl_table_from_tuple in calling box_index_len on not existing index.
