### ISSUE TITLE
Remove unix socket file at exit

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#1434]
% ./tarantool 
./tarantool: version 1.7.0-760-g7a5ac56
type 'help' for interactive help
tarantool> box.cfg{listen='/tmp/file'}
tarantool> %                                                                   
 kostja@atlas ~/work/tarantool/src
 % ls -al /tmp/file 
srwxrwxr-x 1 kostja kostja 0 апр.   8 11:22 /tmp/file

**Comment by rtsisyk** [comment]
Pushed
