### ISSUE TITLE
Document https://github.com/zloidemon/tarantool-radius

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#1444]
Add a better readme to https://github.com/zloidemon/tarantool-radius so that it can be a good rockspec.

**Comment by kostja** [comment]
Veniamin, could you please add the readme and assign this bug to @lenkis afterwards? We need to make your rock a proper citizen, there is an external demand for it.

**Comment by zloidemon** [comment]
That is related to https://github.com/tarantool/tarantool/issues/797 because UDP Api  has changed and not fully ported on 1.6.X

**Comment by rtsisyk** [comment]
======================
Simple UDP echo server
======================

Tarantool currently don't have :func:`socket.udp_server()`, but this
function can be implemented using sockets and fibers:

    #!/usr/bin/env tarantool

    local socket = require('socket')
    local errno = require('errno')
    local fiber = require('fiber')

    local function udp_server_loop(s, handler)
        fiber.name("udp_server")
        while true do
            -- try to read a datagram first
            local msg, peer = s:recvfrom()
            if msg == "" then
                -- socket was closed via s:close()
                break
            elseif msg ~= nil then
                -- got a new datagram
                handler(s, peer, msg)
            else
                if s:errno() == errno.EAGAIN or s:errno() == errno.EINTR then
                    -- socket is not ready
                    s:readable() -- yield, epoll will wake us when new data arrived
                else
                    -- socket error
                    local msg = s:error()
                    s:close() -- save resources and don't wait GC
                    error("Socket error: " .. msg)
                end
            end
        end
    end

    local function udp_server(host, port, handler)
        local s = socket('AF_INET', 'SOCK_DGRAM', 0)
        if not s then
            return nil -- check errno:strerror()
        end
        if not s:bind(host, port) then
            local e = s:errno() -- save errno
            s:close()
            errno(e) -- restore errno
            return nil -- check errno:strerror()
        end

        fiber.create(udp_server_loop, s, handler) -- start a new background fiber
        return s
    end

Usage:

.. code-block:: lua

    local function handler(s, peer, msg)
        -- You don't have to wait until socket is ready to sent UDP
        -- s:writable()
        s:sendto(peer.host, peer.port, "Pong: " .. msg)
    end

    local server = udp_server('127.0.0.1', 3548, handler)
    if not server then
        error('Failed to bind: ' .. errno.strerror())
    end

    print('Started')

    require('console').start()

The example looks a little bit complicated because it actually check
socket errors.

**Comment by kostja** [comment]
Nobody seems to be wanting this, closing as won't fix.
