### ISSUE TITLE
Re-write documentation for `tarantoolctl`

### ISSUE THREAD

**Issue by bigbes** [tarantool/tarantool#1445]
Quote:

> Copy tarantoolctl to /tarantool_test. If you made a source download to ~/tarantool-1.6, then

> ```
> $ sudo cp ~/tarantool-1.6/extra/dist/tarantoolctl /tarantool_test/tarantoolctl
> ```

> If the file was named tarantoolctl and placed on /usr/bin/tarantoolctl, then

> ```
> $ sudo cp /usr/bin/tarantoolctl /tarantool_test/tarantoolctl
> ```

**Comment by pgulutzan** [comment]
I interpret this as: it's now impossible to use tarantoolctl unless it's been installed on a subdirectory of /usr. This is regrettable, but it simplifies the description somewhat. There were a few other details that also needed editing in this area.
