### ISSUE TITLE
phia integration

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#1452]
- [x] extract rb @alyapunov 
etc) and move them, pick the unit tests from the original project @alyapunov
- [x] remove vtable from vfs @GeorgyKirichenko
- [x] extract lz4
- [x] extract zstd
- [x] extract crc
- [x] remove thread
- [x] remove unused configuration options
- [x] set memory limit to 1G by default
- [x] extract mutex
- [x] extract rlist
- [x] extract trigger
- [x] remove gc
- [x] remove non-portable defines
- [x] identify and remove dead code
- [x] remove typedefs
- [x] remove WAL
- [x] remove object pools; an extra spinlock around what already is done by malloc is useless
- [x] remove anti-cache, RAM-only modes: these are broken by design
- [x] range index snapshots - this is a broken feature as well. unfortunately i don't see an easy way to re-implement it; remove;
- [x] remove worker pool - @GeorgyKirichenko 
- [x] extract hash @GeorgyKirichenko 
- [x] replace ss_error with struct diag @GeorgyKirichenko
- [x] use tarantool error injection @GeorgyKirichenko 
- [x] replace ss_order with key_def's order @rtsisyk
- [x] rewrite PhiaEngine::join to use Tarantool data dictionary, and kill seviewdb @rtsisyk 
- [x] move cursor() method from env to index object (sedb) @rtsisyk 
- [x] remove trace
- [x] remove API lock around calls which are guaranteed to be invoked only in tx thread
- [x] remove sp_* wrappers, use native objects and their api
- [x] identify the test plan, begin adding missing unit and functional tests
- [x] remove ssalign, sshot, sslikely, ssunlikely, sscast
- [x] remove void * style polymorphism: virtual tables are ok, but passing void * around is not ok

**Comment by rtsisyk** [comment]
Splitted into separate tickets.
