### ISSUE TITLE
Implement RSA cipher in crypto built-in

### ISSUE THREAD

**Issue by Sulverus** [tarantool/tarantool#1456]
Need to expose asymmetric encryption (RSA) in package crypto (`crypto.cipher.rsa`)

**Comment by rtsisyk** [comment]
=> https://github.com/tarantool/luaossl
@Sulverus @GeorgyKirichenko can we close this ticket?

**Comment by rtsisyk** [comment]
We decided to cease development of built-in 'crypto' module and switch completely to `luaossl`.
Original patch for crypto/digest by @GeorgyKirichenko is attached below:
[gh_1456_crypto_rsa.patch.txt](https://github.com/tarantool/tarantool/files/305560/gh_1456_crypto_rsa.patch.txt)
