### ISSUE TITLE
vinyl: don't checkpoint excessively when it's set up to work together with memtx

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#1468]
In vinyl-only mode, we should automatically advance the global checkpoint state and memtx checkpoint as part of it, along with the non- quiescent vinyl checkpiont, if there were no memtx changes. This is necessary to avoid long restart time of vinyl, caused by having to play all the WALs from the last (formal) memtx checkpoint done every checkpoint_interval.

How to implement:
* implement a new centralized snapshot daemon (checkpoint manager)
* report to checkpoint manager about dumps of vinyl runs
* the checkpoint manager will automatically advance (write a message to .xctl file) the checkpoint to position x when it sees that all LSN > x are dumped.

**Comment by rtsisyk** [comment]
I don't understand this ticket

**Comment by rtsisyk** [comment]
This ticket looks like a duplicate of #1916

**Comment by kostja** [comment]
This is a raw idea. The problem is alleviated by multi-level compaction.

**Comment by kostja** [comment]
Reopening after an explicit request from a user in the mailing list.

**Comment by rtsisyk** [comment]
> the checkpoint manager will automatically advance (write a message to .xctl file) the checkpoint to position x when it sees that all LSN > x are dumped.

I don't understand  this idea. How is it supposed to work for memtx snapshots?

**Comment by kostja** [comment]
There is nothing left to do on this ticket.
