### ISSUE TITLE
Error with not unique index. If there are several equal keys then select founds only first

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#1481]

**Comment by pgulutzan** [comment]
When I try, with Tarantool 1.6 pulled from source today,
I get two tuples.

Method:
box.cfg{}
box.schema.space.create('T')
box.space.T:create_index('primary')
box.space.T:create_index('secondary',{unique=false,parts={2,'STR'}})
box.space.T:insert{1,'A'}
box.space.T:insert{2,'A'}
box.space.T.index.secondary:select('A')

Result:
tarantool> box.space.T.index.secondary:select('A')
---
- - [1, 'A']
  - [2, 'A']
...

I wonder what we're doing differently.

**Comment by Gerold103** [comment]
This is only sql problem and is already fixed
