### ISSUE TITLE
phia: functional test plan

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#1484]
This is an attempt to come up with a white-box functional test coverage for phia
Step 1: run gcov test coverage and see parts not covered by the currnet test.

**Data definition language**:

**Autocommit mode**

*Multi-statement transaction mode*

**Indexing**
- [x] single-part index @rtsisyk
- [x] multi-part index, up to MAX_KEY_PART parts  @rtsisyk
- [x] min, max value in every key type (too large string key, int max, int min)  @rtsisyk
- [x] indexing of different key part types (string, number)  @rtsisyk
- [ ] an attempt to insert a type which doesn't match index type, NIL as example  @rtsisyk

**Iteration**
- [x] key = NULL with ALL, LT,GT,GE,LE  @rtsisyk

**Features**
- [x] Filters - lz4, std
- [x] [AMQF filter](http://sophia.systems/v2.1/admin/amqf.html)
- [x] Prefix compression (`compression_key = 1` index option in tarantool)

**Errors**

- [ ] Disk I/O errors - add error injections to VFS code
- [ ] Broken data files

**GCOV TODO**
No coverage
- [ ] si_nodeopen
- [ ] ss_fileopen
- [ ] ss_filesync
- [ ] ss_fileresize
- [ ] ss_fileseek
- [ ] ss_fnv
- [ ] ss_bufiterref_close
- [ ] ss_nonefilter_*
- [ ] ss_qfrecover
- [ ] ss_qf*
- [ ] ss_rbmax
- [ ] ss_rbprev
- [ ] ss_stdaclose
- [ ] ss_stdvfs_size
- [ ] ss_stdvfs_sync
- [ ] ss_stdvfs_truncate
- [ ] ss_stdvfs_seek
- [ ] ss_stdvfs_mmap
- [ ] ss_stdvfs_m*
- [ ] sf_compareprefix
- [ ] sf_field
- [ ] sf_cmp*
- [ ] sf_schemecompare_prefix
- [ ] sr_versionstorage_check
- [ ] sr_stattx_lock
- [ ] sv_field
- [ ] sv_hash
- [ ] sv_refvisible
- [ ] sv_mergeiter_lt
- [ ] sv_writeiter_upsert
- [ ] sv_indexset
- [ ] sv_indexiter_close
- [ ] sv_indexiter_has
- [ ] sv_refiflsnset
- [ ] sv_upsertviflsnset
- [ ] sx_vfreeall
- [ ] sx_find
- [ ] sx_deadlock_in
- [ ] sx_deadlock_unmark
- [ ] sx_deadlock
- [ ] sx_viflsn
- [ ] sx_viflsnset
- [ ] sd_pagesparse_*
- [ ] sd_pageiter_chain_next
- [ ] sd_pageiter_lt
- [ ] sd_indexmax
- [ ] sd_indexamqf
- [ ] sd_sealvalidate
- [ ] sd_buildadd_sparse
- [ ] sd_indexadd_sparse
- [ ] sd_indexcopy
- [ ] sd_mergefree
- [ ] sd_recover_*
- [ ] sd_vrawifpointer
- [ ] si_nodecmp
- [ ] si_amqfhas_branch
- [ ] si_lru_add
- [ ] si_cacheseek
- [ ] si_trackinit
- [ ] si_trackfree
- [ ] si_trackmetrics
- [ ] si_tracknsn
- [ ] si_trackmatch
- [ ] si_trackset
- [ ] si_trackget
- [ ] si_trackreplace
- [ ] si_remove
- [ ] si_compact_index
- [ ] si_redistribute
- [ ] si_redistribute_set
- [ ] si_redistribute_index
- [ ] si_splitfree
- [ ] si_noderecover
- [ ] si_nodeopen
- [ ] si_plannerpeek_age
- [ ] si_plannerpeek_compact_temperature
- [ ] si_plannerpeek_lru
- [ ] si_processid
- [ ] si_process
- [ ] si_trackdir
- [ ] si_trackvalidate
- [ ] si_recover*
- [ ] phia_cursor_set_read_commited
- [ ] phia_index_close
- [ ] phia_index_bsize
- [ ] phia_document_lsn

Bad coverage
- [ ] sc_do
- [ ] si_write
- [ ] si_getbranch
- [ ] si_getresult
- [ ] si_plannerpeek_nodegc
- [ ] si_plannerpeek_gc
- [ ] si_merge
- [ ] si_execute
- [ ] si_iter_open
- [ ] si_cachevalidate
- [ ] si_lru_vlsn
- [ ] sd_read_page
- [ ] sd_pageiter_cmp
- [ ] sx_rollback
- [ ] sx_max
- [ ] sx_min
- [ ] sx_indextruncate
- [ ] sv_vset
- [ ] sv_indexiter_open
- [ ] sv_upsertpush_raw
- [ ] sv_upsertgc
- [ ] sf_schemeset
- [ ] sf_limitset
- [ ] ss_zstdfilter_next
- [ ] ss_lz4filter_next
- [ ] ss_rbremove

**Comment by rtsisyk** [comment]
Indexing, Iteration, Features are finished, disk I/O moved to #1610
