### ISSUE TITLE
Can't install tarantool in debian 7.10 from official repo

### ISSUE THREAD

**Issue by racktear** [tarantool/tarantool#1485]
When doing `apt-get update` after adding tarantool repo:

```sh
W: Failed to fetch http://download.tarantool.org/tarantool/1.6/debian/dists/wheezy/main/source/Sources  302  Moved Temporarily

W: Failed to fetch http://download.tarantool.org/tarantool/1.6/debian/dists/wheezy/main/binary-amd64/Packages  302  Moved Temporarily
```

See the original problem here:
https://groups.google.com/forum/#!topic/tarantool-ru/f0R9H4AYUdo

It is confirmed that older debian distros can't handle 30x redirects in apt repositories. It has been fixed in debian 8, but not backported.

**Comment by rtsisyk** [comment]
Please use 
```
deb http://packagecloud.io/tarantool/1_6/debian/ wheezy main
deb-src http://packagecloud.io/tarantool/1_6/debian/ wheezy main
```
instead of download.tarantool.org
