### ISSUE TITLE
Document that tarantoolctl works with ~/.config/tarantool/tarantool

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#1492]
tarantoolctl has a search order for it's 'defaults' file. First it looks for a defaults file in ~/.config/tarantool/tarantool, then in /etc/sysconfig/tarantool/ Please confirm with the source code to find out the exact order: 

https://github.com/tarantool/tarantool/blob/1.7/extra/dist/tarantoolctl.in#L18
https://github.com/tarantool/tarantool/blob/1.7/extra/dist/tarantoolctl.in#L214
https://github.com/tarantool/tarantool/blob/1.7/extra/dist/tarantoolctl.in#L198

This allows one to use it for instance management while instances are located in a home directory. This can be quite useful for development, or when there is no access to /var or other system-wide directories. 

Please document this.

**Comment by bigbes** [comment]
It's not entirely so:

1) It looks in ./.tarantoolctl
2) then it looks in ~/.config/tarantool/tarantool
3) then it looks in predefined dir (@CMAKE_INSTALL_FULL_SYSCONFDIR@
/@SYSCONFIG_DEFAULT@/tarantool, where [@CMAKE_INSTALL_FULL_SYSCONFDIR@ is,
basically, /etc], [@SYSCONFIG_DEFAULT@ is 'sysconfig'/'defaults' in
rpm'based/deb'based distros])

With best regards, Eugene.

2016-05-19 17:20 GMT+03:00 Konstantin Osipov <notifications@github.com>:
