### ISSUE TITLE
building tarantool on alpine linux 3.3 (amd64) fails

### ISSUE THREAD

**Issue by epicfilemcnulty** [tarantool/tarantool#1500]
> buildo@builder:~/tarantool/src/tarantool-1.6.8.683$ make
> [ 62%] Built target tarantool
> Scanning dependencies of target arena_mt.test
> [ 62%] Building C object src/lib/small/test/CMakeFiles/arena_mt.test.dir/arena_mt.c.o
> /home/buildo/tarantool/src/tarantool-1.6.8.683/src/lib/small/test/arena_mt.c: In function 'run':
> /home/buildo/tarantool/src/tarantool-1.6.8.683/src/lib/small/test/arena_mt.c:28:22: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
>   unsigned int seed = (unsigned int) pthread_self();
>                       ^
> cc1: all warnings being treated as errors
> src/lib/small/test/CMakeFiles/arena_mt.test.dir/build.make:62: recipe for target 'src/lib/small/test/CMakeFiles/arena_mt.test.dir/arena_mt.c.o' failed
> make[2]: *** [src/lib/small/test/CMakeFiles/arena_mt.test.dir/arena_mt.c.o] Error 1
> CMakeFiles/Makefile2:1020: recipe for target 'src/lib/small/test/CMakeFiles/arena_mt.test.dir/all' failed
> make[1]: *** [src/lib/small/test/CMakeFiles/arena_mt.test.dir/all] Error 2
> Makefile:149: recipe for target 'all' failed
> make: *** [all] Error 2
>

**Comment by epicfilemcnulty** [comment]
well, apparently it only happens for 1.6.8.683 version, tarantool 1.6.8.525 (which is supposed to be stable version, I believe -- it is not exactly clear) builds just fine...

**Comment by racktear** [comment]
@epicfilemcnulty Could you please check this patch: https://github.com/tarantool/tarantool/pull/1504

I did it in order to build official docker images based on Alpine Linux (see https://github.com/tarantool/tarantool-docker/tree/alpine-based-images)

If the patch is OK, I'll merge it to 1.6.

**Comment by racktear** [comment]
Sorry, the correct link to the patch is:  https://github.com/tarantool/small/commit/e59cf7c3e1d2c263ccd6d5aaf6d8ea3572b68c06

**Comment by epicfilemcnulty** [comment]
@racktear Successfully built versions 1.6.8.683 and 1.6.8.692 with this patch. Thanks!

**Comment by racktear** [comment]
@epicfilemcnulty Do you plan to build a docker container with tarantool? Maybe we can coordinate our efforts... What are your requirements?

**Comment by epicfilemcnulty** [comment]
@racktear Not exactly, actually I'm using alpine as a base container for lxc. Maybe it's worth to create an official tarantool apk package? I've created a draft APKBUILD file for tarantool while I was building it.

**Comment by rtsisyk** [comment]
Problem with -Wpointer-to-int-cast on musl libc was fixed in 1.7.x. 1.6.x is not affected.
Alpine Linux / Docker feature request moved to  #1502

See also #1249
