### ISSUE TITLE
Docker images must follow common guidelines

### ISSUE THREAD

**Issue by racktear** [tarantool/tarantool#1502]
Usually docker containers are not built with different guest operating system. Instead, the maintainer picks one OS and sticks with it. For databases it is usually debian:jesse at this moment.

Plus, releases are tagged by major versions as to have e.g.:

- latest _(points to 2.0)_
- 2.0
- 1.5
- 1.0

See for example how it's done for Cassandra: https://hub.docker.com/r/library/cassandra/tags/

What I propose:

- Base tarantool images off debian:jesse
- Use the following tags: latest, 1.7, 1.6
- Drop all existing tags

**Comment by saks** [comment]
Why not to use [alpine image](https://hub.docker.com/_/alpine/) as base, since [docker will use it for official images](https://www.brianchristner.io/docker-is-moving-to-alpine-linux/)?

**Comment by racktear** [comment]
@saks Yeah, I already reconsidered that. See https://github.com/tarantool/tarantool-docker/tree/alpine-based-images

I've implemented the 1.7 and 1.6 images based on Alpine. The only problem that exists so far is that I don't know how to generate C.UTF-8 locale. The locale-generating stuff is missing in the distro.

**Comment by saks** [comment]
@racktear Thanks! Will try it out soon! Another question: any plans to make an "official" docker image that will be possible to pull with `docker pull tarantool`?

**Comment by racktear** [comment]
@saks Yes. That's what I'm up to. For the time being, you can use https://hub.docker.com/r/tarantool/tarantool/

**Comment by racktear** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;EuffGtBq&#x2F;3-run-bootstrap-scripts-once-in-docker-containers"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Run bootstrap scripts once in Docker containers</a>

**Comment by racktear** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;HvzJfHGY&#x2F;16-add-batteries-to-the-docker-container"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Add &quot;batteries&quot; to the docker container</a>

**Comment by rtsisyk** [comment]
@racktear I think this ticket is finished.
