### ISSUE TITLE
console.connect doesn't understand URIs with empty passwords

### ISSUE THREAD

**Issue by racktear** [tarantool/tarantool#1512]
The `uri` library doesn't understand the URIs with empty passwords (:@). This leads to users being unable to connect with a non-guest user and an empty password. 

[This RFC](https://tools.ietf.org/html/rfc3986) says that it should be permitted. Excerpt:

> Use of the format "user:password" in the userinfo field is
> deprecated.  Applications should not render as clear text any data
> after the first colon (":") character found within a userinfo
> subcomponent unless the data after the colon is the empty string
> (indicating no password).

Actual behavior:

```
tarantool> console.connect('admin:@localhost:3301')
---
- error: 'builtin/console.lua:309: Usage: console.connect("[login:password@][host:]port")'
...
```

Passing no password information doesn't cut it either;

```
tarantool> console.connect('admin@localhost:3301')
---
- error: 'net.box: password is not defined'
...
```

**Comment by racktear** [comment]
This is a bug in uri library's BNF grammar. But the general form of <user>@<host> is supported (without colon). I believe it will be a good compromise to just treat the password as empty in this case.

**Comment by racktear** [comment]
The PRs above are just a partial solution. They don't cover the empty password in URI, just the missing one. Which should be enough for now.

**Comment by racktear** [comment]
Required for #1502

**Comment by rtsisyk** [comment]
Hi, our URI parser doesn't support such syntax:

```
 require('uri').parse('admin:@localhost:3301')
---
- null
...
tarantool>  require('uri').parse('admin@localhost:3301')
---
- host: localhost
  service: '3301'
  login: admin
...
```

You need to patch src/uri.rl + add a test case in test/unit/uri.cc to fix it.
