### ISSUE TITLE
pcall() memory corruption

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#1516]
Found by @GeorgyKirichenko 

1.7.0-1024-g5fd0a7d

```
local fiber = require('fiber')

box.cfg {
    slab_alloc_arena  = 0.1,
    rows_per_wal      = 1000000,
}

local s1 = box.schema.space.create('s1', { engine = 'phia' })
s1:create_index('pk')

local function insert(key)
    s1:insert(key)
end

--jit.off(insert)

local function t1()
    for i = 1, 100000 do
        pcall(insert, {i})
    end
end;

fiber.create(t1)
fiber.create(t1)

fiber.sleep(10)
os.exit()
```

I added "regression" tag because 1.6 doesn't crash.
We realized that our pcall_wrapper() impedes JIT compilation and, therefore, prevents crash in this test case.

**Comment by mejedi** [comment]
Patch prepared and sent to LuaJIT mailing list; awaiting response.

**Comment by mejedi** [comment]
Applied patch to Tarantool LuaJIT mirror.
