### ISSUE TITLE
Tarantool builtin HTTP server

### ISSUE THREAD

**Issue by dedok** [tarantool/tarantool#1518]
For version v0.1 full support of nginx upstream module (i.e. RPC/REST) is required.
Detail here: https://github.com/tarantool/nginx_upstream_module#tarantool-nginx-upstream-module
Depends from: https://github.com/tarantool/nginx_upstream_module/issues/39

proposal cfg:

```
box.cfg {
 http_listen = "HOST_STR"
}
```

**Comment by kostja** [comment]
We do have tarantool/http for a server.
