### ISSUE TITLE
vinyl: pagepointer assertion

### ISSUE THREAD

**Issue by GeorgyKirichenko** [tarantool/tarantool#1530]
tarantool: /home/georgy/projects/tarantool4/src/box/phia.c:6133: sd_pagepointer: Assertion `(sizeof(struct sdv) * p->h->count) + v->offset <= p->h->sizeorigin' failed.

may be caused by compression bug (it happens after compression err)

**Comment by rtsisyk** [comment]
Duplicate of #1527
