### ISSUE TITLE
net.box.connect alias for net.box.new

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#1533]
we have console.connect(), it would be handy to have net.box.connect as well

**Comment by rtsisyk** [comment]
`box.connect()` ;)

**Comment by mejedi** [comment]
Please, deprecate `box.new` as well :)

**Comment by rtsisyk** [comment]
See also #401

**Comment by rtsisyk** [comment]
Add net.box.connect() for now and close this ticket.
