### ISSUE TITLE
Document stored procedures in C/C++

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#1536]
Tarantool supports stored procedures written in C/C++ since 1.6.7.

There are some examples in our tests suite:
https://github.com/tarantool/tarantool/blob/1.7/test/box/function1.c#L16
https://github.com/tarantool/tarantool/blob/1.7/test/box/function1.test.lua#L17

See also #898

**Comment by kostja** [comment]
A decent reference was created when Eugene moved the docs to a separate repo.
