### ISSUE TITLE
net.box should convert nil passwords to empty passwords

### ISSUE THREAD

**Issue by racktear** [tarantool/tarantool#1545]
This is another attempt to unify how we log in users with an empty password. The fix will be both for 'guest' (as a special case) and for other users.

Right now there are 2 ways to authenticate after client connects to the server:
1) Send an authentication packet to the server. This will authenticate you as a specific user.
2) Don't send authentication packet, and start using the session right away. In which case the user is assumed to be "guest".

Option (1) has 2 further cases:
1.1) Password is sent like this: {'chap-sha1': 'swE0NkotFDGZBMLIBzY88sgavVs='}
1.2) An "empty" password is sent: {}

There is special logic to handle logins with "guest" user. Since the guest user has nil as password in the database, we can't successfully check any incoming password sent in the authentication packet, since the authentication packet can't contain "nil" in the password field.

### Changes:
- The guest's password will be set to an empty string in the database (it will be performed during bootstrap). It will allow clients to send an empty password 
- net.box will be patched to send empty string as a password, if it receives nil. This will enable logging in with URIs like guest@host.

### Implications:
- This change won't affect guest authentication packets that contain '{}' as password, so existing clients will not be affected.
- The box.schema.user.passwd will fail for guest user, _except when called with en empty string as password_. This is required in order to set up the guest user's password for the first time, during bootstrap.

**Comment by racktear** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;zgVa7EVL&#x2F;1-login-for-guest-user-with-empty-password"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> login for guest user with empty password</a>

**Comment by racktear** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;vPJPk93L&#x2F;2-patch-net-box-to-change-nil-password-to-empty-string"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Patch net.box to change nil password to empty string</a>

**Comment by rtsisyk** [comment]
1.7.0-1186-g076a842
