### ISSUE TITLE
Add tarantool-php/mapper to the list of drivers

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#1547]
https://github.com/tarantool-php/mapper

**Comment by rybakit** [comment]
@kostja Would it also have sense to add https://github.com/tarantool-php/queue?

**Comment by bigbes** [comment]
It's reasonable to mention https://github.com/tarantool-php/queue in queue
repository. Mapper is for general Tarantool usage, but php-queue is for
queue only.
<https://github.com/tarantool-php/queue>

With best regards, Eugene.

2016-06-15 13:01 GMT+03:00 Eugene Leonovich <notifications@github.com>:
