### ISSUE TITLE
Incorrect overflow handling for ULL/LL literals in LuaJIT

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#1555]
```
tarantool> tostring(-12345678901234567890LL)

---
- 6101065172474983726LL
...
```

**Comment by mejedi** [comment]
Please elaborate on your proposal. What should be done differently? May be a lexer error?

**Comment by rtsisyk** [comment]
lexer error is ok.

**Comment by mejedi** [comment]
Will brake tarantool-avro and maybe other code.

**Comment by rtsisyk** [comment]
> Will break tarantool-avro and maybe other code.

why?

**Comment by ruben-ayrapetyan** [comment]
@rtsisyk, what is expected behaviour in case of overflow during execution? Should it also be catched?

For example, lexer could catch overflow:
```
tarantool> 9223372036854775808LL
---
- error: '[string "9223372036854775808LL"]:1: malformed number near ''9223372036854775808LL'''
...

tarantool> 9223372036854775807LL
---
- 9223372036854775807
...
```

Then, wouldn't lua behaviour seem inconsistent, if overflow is not checked during execution?

```
tarantool> x = 9223372036854775807LL
---
...

tarantool> y = 1
---
...

tarantool> x + y
---
- -9223372036854775808
```

What do you think about this?

**Comment by igormunkin** [comment]
This is a valid LJ behaviour with the following rationale considering the [FFI semantics](http://luajit.org/ext_ffi_semantics.html).

According to the [FFI page](http://luajit.org/ext_ffi.html) on LJ wiki: "The FFI library allows using C data structures from pure Lua code". Thereby, all operations with such types should be interpreted considering its C specifics. The signess of the cdata numeric objects is defined within LuaJIT frontend and FFI tostring metamethod yields the result respecting the type signess. We will obtain the proper result after changing the suffix of the literal:
```tarantool
tarantool> tostring(12345678901234567890ULL)
---
- 12345678901234567890ULL
...

```
Closing the issue with wontfix reason.
