### ISSUE TITLE
NULL support in indexes

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#1557]
Implement support for NULL values in indexes.

NULL has special semantics in databases. 
Please read [this article](https://en.wikipedia.org/wiki/Null_%28SQL%29) carefully, especially part about [ternary logic](https://en.wikipedia.org/wiki/Null_%28SQL%29#Comparisons_with_NULL_and_the_three-valued_logic_.283VL.29).
### 1. NULL value in UNIQUE index

**Unique index can contain more than one NULL values**

```
CREATE TABLE nulltest (id INT PRIMARY KEY, val INT, UNIQUE(val)) -- unique constraint
INSERT INTO nulltest VALUES(1, null);
INSERT INTO nulltest VALUES(6, 6);
INSERT INTO nulltest VALUES(5, 5);
INSERT INTO nulltest VALUES(4, null);
INSERT INTO nulltest VALUES(3, null);
INSERT INTO nulltest VALUES(2, 2);
SELECT * FROM nulltest ORDER BY val;
 id | val 
----+-----
  2 |   2
  5 |   5
  6 |   6
  3 |    
  4 |     -- multiple rows with NULL values in UNIQUE index
  1 |    
(6 rows)  
```

`(x <OPERATOR> NULL)` is NULL, not TRUE or FALSE. Even `(NULL == NULL)` is `NULL`.

ANSI SQL 2011, part 2, section 4.18.3.2 "Unique constraints":

> Unique constraint is satisfied if and only if there do not exist two rows R1 and R2 of T (table) such that R1 and R2 have the same **non-null** values in the unique columns.

Please read [Peter's article](http://ocelot.ca/blog/blog/2013/09/11/null-and-unique/) on NULL and UNIQUE constraints in SQL for detailed explanation.

`space:create_index(name, { unique = true })` in Tarantool is semantically equivalent to `CREATE UNIQUE INDEX name ON space (key)` in SQL. Therefore, `unique = true` must also allow multiple nulls values.
### 2. Sort order for NULL values

**Sort order for NULL values is implementation defined**, like for non-unique indexes. 

Technically, you can't apply ternary logic directly to B-trees. A tree comparator function must be transitive to define strict order over the set of keys in tree. In other words, if cmp(a, NULL) is "less" then cmp(NULL, a) should be "great or equal", otherwise tree properties will not be met. 

Some SQL implementations consider NULLs values less than any other value ("nulls low"), whereas other implementations consider NULLs great than other values ("nulls high").

Example - PostgreSQL - "nulls high":

```
postgres> SELECT id, val, ctid FROM nulltest ORDER BY val;
 id | val | ctid   -- 
----+-----+-------
  2 |   2 | (0,6)
  5 |   5 | (0,3)
  6 |   6 | (0,2)
  3 |     | (0,5)  --  nulls high
  4 |     | (0,4)  --  order for records 3, 4, 1 is random, based on physical location on the disk
  1 |     | (0,1)  --
```

Example - sqlite3 - "nulls low":

```
sqlite> SELECT id, val, rowid FROM nulltest ORDER BY val ASC;
1||1    -- nulls low
4||4    -- order for records 1, 4, 3 is random, based on physical location  on the disk
3||5
2|2|6
5|5|3  
6|6|2
```

Tarantool/SQL is based on sqlite3. Therefore, let's choose "nulls low" order for compatibility with sqlite3.

`space:select({}, {iterator='GE'})` should have the same order as
`SELECT * FROM space ORDER BY val ASC NULLS FIRST`
and space:select({}, {iterator='LE'}) should have the same order as
`SELECT * FROM space ORDER BY val DESC NULLS LAST`
## 3. NOT NULL constraint

SQL has `NOT NULL` constraint:

```
CREATE TABLE table (..., val INT NOT NULL, ... )
```

By default any column without "NOT NULL" constraint can store NULLs. NOT NULL columns can't store NULL (an error is raised).

There are two options for us:
- Add `not_null = false` option per field in _space.format.
  Pros: like SQL
  Cons: `not_null = false` is inverted logic; option is not 1.6->1.7 forward-compatible.
- Add `null = true` option per field in _space.format

Let's discuss these two options. 
## 4.  PRIMARY KEY must not allow NULLs

Since there is no way to unique identify rows in an index by NULL key, primary key must not allow NULLs. `PRIMARY KEY` in SQL effectively means "UNIQUE" and "NOT NULL". 

It is possible to enable NOT NULL constraint explicitly, based on knowledge that index is "first" (primary).
## 5. Lua and nils

`nil` has special meaning in Lua - `table[x] = nil` means `delete x from table`.
`{'a', 'b', nil}` is semantically equivalent to table = {}; table[1] = 'a', table[2] = 'b', table[3] = nil, therefore `nil` is not usable in tables. See #1123 for nice examples of buggy design of Lua.

Lua's `nil` also doesn't support ternary logic:

```
tarantool> 1 < nil

---
- error: '[string "return 1 < nil"]:1: attempt to compare number with nil'
...

tarantool> 1 + nil

---
- error: '[string "return 1 + nil"]:1: attempt to perform arithmetic on a nil value'
...
```

There are also msgpack.NULL/yaml.NULL/json.NULL which can be safetly inserted to Lua table.

Probably we should add box.NULL special value which will fully support ternary NULL logic in Lua.
It is easy to implement using Lua table with __eq and __serialize meta-methods. 

Let's discuss this part. See #1300 for details.
## 6. SELECT \* FROM tab WHERE x = NULL

**`box.space.test:select({NULL}, {iterator = 'EQ'})`  is empty set:**

```
SELECT * FROM nulltest WHERE val = NULL;
 id | val 
----+-----
(0 rows)
```

SQL has a special syntax for that:

```
SELECT * FROM nulltest WHERE val is NULL;
 id | val 
----+-----
  1 |    
  4 |    
  3 |    
  7 |
```

It is possible to add a special iterator type, like "EQ_IS" in the future to implement "IS NULL" feature. This feature is not part of this ticket.

EQ/GE/GT/LE/LT iterators must work properly at least on `null = true` indexes. Support for NULL queries over not-null indexes is senseless and will introduce performance regression at least for `NUM` and `STR` indexes.

One more problem is how to handle space:select(nil) and space:select(msgpack.NULL).

Currently space:select(scalar) == space:select({scalar}).
space:select({scalar}) is like "SELECT \* FROM space WHERE key=scalar ORDER BY key ASC", so
space:select(scalar) is also like "SELECT \* FROM space WHERE key=scalar ORDER BY key ASC".

At the same time, somefunc(nil) == somefun() in Lua, so space:select(nil) == space:select() == space:select({}).

How to handle space:select(msgpack.NULL) and space:select(nil)?
a) space:select(msgpack.NULL) == space:select({msgpack.NULL})
b) space:select(msgpack.NULL) == space:select(nil) == space:select({})
c) ban space:select(msgpack.NULL)
d) ban space:select(msgpack.NULL) and space:select(nil, {...})

Let's discuss these options.
## 7. Partial indexes

It was an idea to omit NULL records from indexes to save some memory. SQLITE calls this feature "[partial index](https://www.sqlite.org/partialindex.html)", some other database use "fileterd index" terminology.

We don't implement this feature as part of this ticket. I think this behaviour can be controlled by some create_index() option, e.g. "partial = true/false/filter_function/where clause from sql".
## 8. Default values

Default values are not part of this feature.

---

I added this ticket to 1.7.0, but actually this feature is rolling and can be postponed to 1.7.1+ or even to 1.8.x.

**Comment by Gerold103** [comment]
> There are two options for us:
>
>Add 'not_null = true' option to box.schema.space_create()
>Pros: like SQL
>Cons: default value must be 'true' for 1.6 -> 1.7 forward compatibility, not_null = false is inverted logic
>
>Add null = true option tobox.schema.space_create()
>
>Let's discuss these options.

What will happen in case of creating table, where not all columns can be NULL?
Example: `CREATE TABLE test(a PRIMARY KEY, b NOT NULL, c NULL)`
If we add option `not_null` to entire space then we can't insert NULLs in column `c` but it contradict with "CREATE" statement.
I think that we must define `NULL/NOT NULL` for each column separately.

**Comment by rtsisyk** [comment]
> What will happen in case of creating table, where not all columns can be NULL?
I wanted to say `spate:create_index()`, not `create_space()`. Sorry,

**Comment by rtsisyk** [comment]
> I think that we must define NULL/NOT NULL for each column separately.

Yes, I agree that it is even better to define this option per column in _space.format field.

**Comment by Gerold103** [comment]
NULLs proposal:
0. Implement comparators, which allows NULL.
1. In select() and get() check if index allows NULL (at least one indexed field allows NULL) and if a key contains NULL then return empty sey, becuse NULL in the key would not be equal, greater or lesser than any value in its column.
2. Make an option for select(): {exact = boolean}. If exact == true, then do not check NULL in keys.
3. Make for all NULL-possible indexes new comparators: tuple_compare(NULL, NULL) == -1,
tuple_compare_with_key(NULL, NULL) == 0 (see struct key_def). In such a case select(exact = true) works automatically, because it uses tuple_compare_with_key(), and an unique NULL-possible index can store multiple NULLs, because to save a new tuple with NULL it used tuple_compare().

**Comment by rtsisyk** [comment]
1.7.5-193-g30ae14611
