### ISSUE TITLE
Parallel testing in Tarantool

### ISSUE THREAD

**Issue by bigbes** [tarantool/tarantool#156]
Prelude
-----------
Right now we have simple testing system (It can run tests in series), but we can't test parallel execution and some hea^W load on it. So we must run tests in parallel with a number of workers.

Currently we have such scheme:
```
+-------------+    +---------+    +----+
|./test-run.py+--->|TestSuite+--->|Test|
+-------------+    +----+----+    +--+-+
                        |            |
                        v            |
                   +------+          |
                   |Server|<---------+
                   +------+
```
But in parallel testing we have no need in starting/stopping server, so our new schema will look like:
```
+-----------+    +---------+    +----+
|./runner.py+--->|TestSuite+--->|Test|
+---+-------+    +---------+    +----+
    |
    v
+------+
|Server|
+------+
```
`./runner.py` simply becomes a `manager` of processes. It starts `TestSuite`'s and sponsors them with processes.

Needed Features
------------------------
1) Parallel running of TestSuites
2) Parallel running of Tests
3) Killing of long-run suites (something like watchdog)
4) Opportunity to repeat tests indefinitely (or finite number of time :) )
5) Ability to repeat bug's. Must have log such as:
```
command %time %process %suite %cmd
start/stop %time %process %suite
...
```

Difficulties
---------------
* One must refactor `lib/test_suite.py`, `lib/tarantool_server.py` and other `lib/*.py` for using queues(or other collections with multiprocessing analogue) and not write to output. To be exception-safe and other. It was great for simple test purposes, but not for parallel.
* Current ./test-run may be compatible with refactored `lib`, but what for?
* We have to perform a lot of work for porting old tests for parallel execution (Maybe we need to add our preprocessor way to append prefix into var_names and space_names)

**Comment by Sulverus** [comment]
Moved to test-run https://github.com/tarantool/test-run/issues/6
