### ISSUE TITLE
Bad checksum on 'cdata' types

### ISSUE THREAD

**Issue by fsitedev** [tarantool/tarantool#1561]
> require('digest').crc32(1086391917483899**0**);
- 1660621899

> require('digest').crc32(1086391917483899**1**);
- 1660621899

**Comment by rtsisyk** [comment]
```
 update = function(self, str)
        str = tostring(str or '')
        self.value = ffi.C.crc32_calc(self.value, str, string.len(str))
    end,
```

`tostring(str or '')` is a BUG.  "any object" to "bytearray" is a separate feature. Don't rely to tostring() for this task. This code should be removed. Since this change is not backward-compatible, I added 1.7.0 tag.
