### ISSUE TITLE
vinyl: rename structures

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#1562]
Let's discuss names. See https://github.com/tarantool/tarantool/wiki/Vinyl-Architecture#disk-layout for details.

* ssfile => vi_file
* `struct PACKED srversion` => ?
* `struct PACKED srconfdump` => ?
* `struct PACKED sv` => ?
* `struct PACKED svlogindex` => ?
* `struct PACKED svlogv` => ?
* `struct PACKED svmergesrc` => ?
* `struct PACKED svmergeiter` => ?
* `struct PACKED svreaditer` => ?
* `struct PACKED svwriteiter` => ?
* `struct PACKED sxv` => ?
* `struct PACKED sdid` => ?
* `struct PACKED sdv` => ?
* `struct PACKED sdpageheader` => ?
* `struct PACKED sdpageiter` => ?
* `struct PACKED sdbuildref` => ?
* `struct PACKED sdindexheader` => ?
* `struct PACKED sdindexamqf` => ?
* `struct PACKED sdindexpage` => ?
* `struct PACKED sdindexiter` => ?
* `struct PACKED sdseal` => ?
* `struct PACKED sdread` => ?
* `struct PACKED sdrecover` => ?
* `struct PACKED sibranch` => ?
* `struct PACKED sinode` => ?
* `struct PACKED sicachebranch` => ?
* `struct PACKED siiter` => ?

**Comment by rtsisyk** [comment]
`struct sinode` -> `struct vinyl_track`

**Comment by kostja** [comment]
We've done this.
