### ISSUE TITLE
vinyl: remove amqf

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#1563]
@alyapunov investigated that quotient filter in vinyl doesn't work algorithmically with configured parameters. I checked coverage result and figured out that "optimal" case of this filter is never triggered even by vinyl/stress.test.lua. @alyapunov proposes to replace QF with a simple bloom filter.
I believe that it is possible to enable bloomfilter for all indexes and stop confusing our users with unclear `amqf` option.

@kostja Could we remove this option? There is no free resources to maintain dead code.
One fool can write more code than four wise men can understand. 

Bloomfilter or any other alternatives can be implemented after finishing with more important tasks.

**Comment by alyapunov** [comment]
I would add that QF implemented in vinyl is correct and I can explain its every line of code, QF itself is very cool data structure and could be useful somewhere else, but not in vinyl, at least not with used settings

**Comment by kostja** [comment]
* Roman Tsisyk <notifications@github.com> [16/06/30 19:09]:
> @alyapunov investigated that quotient filter in vinyl doesn't work algorithmically with configured parameters. I checked coverage result and figured out that "optimal" case of this filter is never triggered even by vinyl/stress.test.lua. @alyapunov proposes to replace QF with a simple bloom filter.
> I believe that it is possible to enable bloomfilter for all indexes and stop confusing our users with unclear `amqf` option.
> 
> @kostja Could we remove this option? There is no free resources
> to maintain dead code.
> One fool can write more code than four wise men can understand. 

Go ahead.

-- 
Konstantin Osipov, Moscow, Russia, +7 903 626 22 32
http://tarantool.org - www.twitter.com/kostja_osipov

**Comment by kostja** [comment]
* Aleksandr Lyapunov <notifications@github.com> [16/06/30 19:09]:
> I would add that QF implemented in vinyl is correct and I can
> explain its every line of code, QF itself is very cool data
> structure and could be useful somewhere else, but not in vinyl,
> at least not with used settings

Move to salad then.

-- 
Konstantin Osipov, Moscow, Russia, +7 903 626 22 32
http://tarantool.org - www.twitter.com/kostja_osipov
