### ISSUE TITLE
Race condition is master-master replication setup

### ISSUE THREAD

**Issue by racktear** [tarantool/tarantool#1589]
Run 2 tarantool 1.7 instances like this:

``` lua
box.cfg{listen=3301, replication_source={'localhost:3301', 'localhost:3302'}}
```

and

``` lua
box.cfg{listen=3302, replication_source={'localhost:3301', 'localhost:3302'}}
```

Then observe that one of the instances exits with the following error:

```
2016-07-01 18:19:06.923 [83164] main/101/app.lua xrow.cc:263 E> ER_ACCESS_DENIED: Read access on universe is denied for user 'guest'
2016-07-01 18:19:06.923 [83164] main/101/app.lua F> can't initialize storage: Read access on universe is denied for user 'guest'
```

Instead, the instances should have retried connections to each other indefinitely.

**Comment by racktear** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;n7JBcmmp&#x2F;45-race-condition-in-master-master-replication-setup"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Race condition in master-master replication setup</a>

**Comment by rtsisyk** [comment]
=> review

**Comment by rtsisyk** [comment]
1.7.2-284-gc25e881
