### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by taroff** [tarantool/tarantool#1590]
Привет! Не знаю будет ли это полезно, но вот что оно вывело
http://pastebin.com/UUPGigMU

**Comment by bigbes** [comment]
Было-бы не плохо указать конфигурацию тарантула, получить корку, указать версию Тарантула. Очень желательно - получить тест-кейс для повторения.

**Comment by rtsisyk** [comment]
LuaJIT finalizers #562 ?

**Comment by taroff** [comment]
К сожалению не могу предоставить инфы. Повторить падение не удалось, + нашел в своем lua коде пару серьезных багов.

Код был примерно такого плана
http://pastebin.com/LKqFsJWK

Причем пока я тестировал свою логику загружал этот код несколько раз через tarantoolctl eval instance script.lua в результате чего создалась пачка файберов одинаковых.

Версия 1.6.8-701-g11be0cd под centos 6 из оф репа.

В логе появилось и сообщение о PANIC: unprotected error in call to Lua API (not enough memory), но после публикации о креше и я не стал дописывать сюда.

**Comment by kostja** [comment]
Duplicate of gh-562
