### ISSUE TITLE
Prometheus endpoint for Tarantool

### ISSUE THREAD

**Issue by racktear** [tarantool/tarantool#1591]
To make tarantool maintenance easier, it will be nice to have an implementation of Prometheus exposition protocol:
https://prometheus.io/docs/instrumenting/exposition_formats/

Right now we don't have any easy way to instrument applications and aggregate application metrics. Adding support for prometheus is one of the easiest ways to achieve this.

Basically, the exposition protocol is protobuf over HTTP.

**Comment by racktear** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;YpnV5pPd&#x2F;46-prometheus-endpoint-for-tarantool"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Prometheus endpoint for Tarantool</a>

**Comment by rtsisyk** [comment]
Implemented: https://github.com/tarantool/prometheus
