### ISSUE TITLE
vinyl: sparse indexes

### ISSUE THREAD

**Issue by Sulverus** [tarantool/tarantool#1594]
Need to implement sparse indexes in vinyl

Now i have error:
```
E> Start failed: Can't create or modify index 'primary' in space 'tail': Vinyl key parts must follow first and cannot be sparse
```

**Comment by rtsisyk** [comment]
Hi, could you please find a workaround? This feature is hard to implement on the current code base and I don't expect that we can deliver it soon. :(

**Comment by rtsisyk** [comment]
I mostly implemented this feature, only upsert is left. Blocked by #1570.
