### ISSUE TITLE
vinyl: temperature is not used by planner

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#1595]
> Anti-Cache mode makes RAM a primary storage, while disk becomes a secondary storage. Sophia implements the mode by introducing so-called index Temperature. The Temperature shows which nodes are the most frequently accessed for read (hot). These nodes are periodically elected and promoted to be put in-memory. Previously elected nodes are unloaded if they do not fit into memory limit.

Anti-Cache already has been removed, please remove temperature too.

**Comment by rtsisyk** [comment]
Discussed with @kostja , temperature may be needed for new planner, don't remove right now.

**Comment by rtsisyk** [comment]
```
    6958           0 : vy_planner_peek_compact_temperature(struct vy_planner *p, struct vy_plan *plan)
    6959             : {
    6960             :         /* try to peek a hottest node with number of
    6961             :          * branches >= watermark */
    6962             :         struct vy_range *n;
    6963           0 :         struct ssrqnode *pn = NULL;
    6964           0 :         while ((pn = ss_rqprev(&p->temp, pn))) {
    6965           0 :                 n = container_of(pn, struct vy_range, nodetemp);
    6966           0 :                 if (n->flags & SI_LOCK)
    6967           0 :                         continue;
    6968           0 :                 if (n->branch_count >= plan->a)
    6969             :                         goto match;
    6970             :                 return 0;
    6971             :         }
    6972             :         return 0;
    6973             : match:
    6974           0 :         vy_range_lock(n);
    6975           0 :         plan->explain = SI_ENONE;
    6976           0 :         plan->node = n;
    6977           0 :         return 1;
    6978             : }
```

Proposal: remove vy_planner_peek_compact_temperature(), but keep metric collection for a new planner. Otherwise @feldsherov will make useless refactoring of  `planner->temp` ssrq (#1599).

@kostja: need feedback

**Comment by rtsisyk** [comment]
The same thing with `vy_planner_peek_age()`.

**Comment by kostja** [comment]
* Roman Tsisyk <notifications@github.com> [16/07/21 10:53]:

> @kostja: need feedback
> 
We can remove whatever when we begin to re-factor the planner.
But first we need to have a new scheduler architecture in place
and secondary keys.

-- 
Konstantin Osipov, Moscow, Russia, +7 903 626 22 32
http://tarantool.org - www.twitter.com/kostja_osipov
