### ISSUE TITLE
Debian: start example.lua instance by default

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#1602]
I received negative feedback from a customer. Please start tarantool by default after apt-get install, like mysql, nginx, apache and other. 

There are two options:

* Add a configuration wizard to package to setup "admin" password (can be copypasted from somewhere)
* Grant universe permissions for guests

`example.lua` instance should listen on 127.0.0.1:3313.

**Comment by kostja** [comment]
* Roman Tsisyk <notifications@github.com> [16/07/07 16:24]:
> I received negative feedback from a customer. Please start tarantool by default after apt-get install, like mysql, nginx, apache and other. 
> 
> There are two options:
> 
> * Add a configuration wizard to package to setup "admin" password (can be copypasted from somewhere)
> * Grant universe permissions for guests
> 
> `example.lua` instance should listen on 127.0.0.1:3313.

Let's start with no listen port, only console port.

-- 
Konstantin Osipov, Moscow, Russia, +7 903 626 22 32
http://tarantool.org - www.twitter.com/kostja_osipov
