### ISSUE TITLE
On exit trigger for Lua

### ISSUE THREAD

**Issue by viciious** [tarantool/tarantool#1607]
Hi,

do you think it would be feasible to add an on_exit trigger to Tarantool's box Lua API? We would like to be able to perform some health status reports from Lua when Tarantool instance is being brought down and that kind of trigger seems like the best possible place for that.

Thanks in advance.

**Comment by kostja** [comment]
This is possible, but generally we avoid doing anything serious on exit.

**Comment by viciious** [comment]
Thanks!
This would greatly help us improve our monitoring/health-check system.

**Comment by zloidemon** [comment]
I seem that solution should involve signals handling and give opportunity to define some actions on signals.
