### ISSUE TITLE
Ubuntu 15.04 Xenial amd64 - Tarantool broken, can't load libbfd-2.26-system.so

### ISSUE THREAD

**Issue by kmansoft** [tarantool/tarantool#1614]
After today's Ubuntu update of binutils to: 2.26.1-1ubuntu1~16.04

Tarantool from official reps, also updated today, 1.6.8.736.g3c2c889-1:

Issue: tarantool can't start.

> tarantool: error while loading shared libraries: libbfd-2.26-system.so: cannot open shared object file: No such file or directory

Looks like this version of binutils renamed the .so:

> dpkg-query -S /usr/lib/x86_64-linux-gnu/libbfd-2.26.1-system.so
> binutils: /usr/lib/x86_64-linux-gnu/libbfd-2.26.1-system.so

Sure, I can make a symlink for now, but this probably should be fixed in the official reps.

**Comment by kostja** [comment]
Could you please also list your /etc/apt/sources.list.d/*tarantool*.list ?

**Comment by kmansoft** [comment]
Sure:

> deb http://download.tarantool.org/tarantool/1.6/ubuntu/ xenial main
> #deb-src http://download.tarantool.org/tarantool/1.6/ubuntu/ xenial main

binutils updated today, maybe your build server just missed the update?

И чтобы два раза не вставать:

> Linux tammy 4.4.0-28-generic #47-Ubuntu SMP Fri Jun 24 10:09:13 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

> $ lsb_release -a
> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 16.04 LTS
> Release:	16.04
> Codename:	xenial

> $ ls -lh /usr/lib/x86_64-linux-gnu/libbfd*
> -rw-r--r-- 1 root root 1.3M Jun 30 12:14 /usr/lib/x86_64-linux-gnu/libbfd-2.26.1-system.so
> lrwxrwxrwx 1 root root   23 Jul 13 17:47 /usr/lib/x86_64-linux-gnu/libbfd-2.26-system.so -> libbfd-2.26.1-system.so

The symlink is not part of binutils, was added by me, and now tarantool runs again.

**Comment by rtsisyk** [comment]
Confirmed.

**Comment by rtsisyk** [comment]
Downstream ticket: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=831361
