### ISSUE TITLE
Guess instance name in tarantoolctl

### ISSUE THREAD

**Issue by racktear** [tarantool/tarantool#1619]
If there is only one active tarantool instance, tarantoolctl should work even if the instance name is not specified. e.g.:

```sh
$ tarantoolctl enter
```

Should connect to a running instance with an admin console.

**Comment by racktear** [comment]
Implemented. Waiting for review.

**Comment by kostja** [comment]
@racktear doesn't want to pursue this anymore, when he changes his mind we'll reopen this :)
