### ISSUE TITLE
net.box documentation deficiencies

### ISSUE THREAD

**Issue by viciious** [tarantool/tarantool#1620]
https://tarantool.org/doc/reference_lua/net_box.html

This part of the documentation doesn't list upsert and possibly other commands too.

**Comment by bigbes** [comment]
It's not what you want?
```
 conn.space.<space-name>:upsert{field-value, ...}
```

**Comment by bigbes** [comment]
But it doesn't show indexes and their methods

**Comment by viciious** [comment]
> It's not what you want?
It is, thanks to https://github.com/tarantool/doc/commit/ccc2aa497f1e94c6d5c74e65502ddf426d7ca32f

You got me there for a moment :)

**Comment by kostja** [comment]
Fixed.
