### ISSUE TITLE
Crash on SIGUSR1 in console process

### ISSUE THREAD

**Issue by kmansoft** [tarantool/tarantool#1624]
Let's say I have two tarantool processes running:

```
$ ps -ef | grep tarantool
kman      4470  2270  0 15:26 pts/0    00:00:03 tarantool test.lua <running>
kman      4647  2089  0 15:28 pts/1    00:00:00 tarantool
kman      5050  4093  0 15:43 pts/2    00:00:00 grep --color=auto tarantool
```

The first is my database server, with all the good "box.space" stuff.

The second is my interactive console: console.connect(the first process).

And then I decide to flush the logs and send SIGUSR1 to the *wong* process by mistake:

```
kill -SIGUSR1 4647 <<--- wrong PID, should be 4470
```

The good part is that the database server process keeps running.

The bad part is that the console process crashes.

```
Segmentation fault
Current time: 1468845860
Please file a bug at http://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed, 
this may fail as well
#0  0x427f81 in sig_fatal_cb(int)+129
#1  0x7fef368cfc30 in ?
#2  0x4b7f60 in fiber_loop+48
#3  0x61986f in coro_init+63
#4  (nil) in ?
Aborted (core dumped)
```

Suggestion: tarantool should not crash if it receives a SIGUSR1 and it's not the process managing the database.

**Comment by kostja** [comment]
Thank you for your bug report, fixed in the latest 1.6 branch.
