### ISSUE TITLE
vinyl: si_redistribute() is not covered by tests

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#1635]
```
    6205             : static int
    6206           0 : si_redistribute(struct vinyl_index *index, struct sdc *c,
    6207             :                 struct vy_range *node, struct vy_buf *result)
    6208             : {
    6209             :         (void)index;
    6210           0 :         struct svindex *vindex = vy_range_index(node);
    6211             :         struct vy_iter ii;
    6212             :         sv_indexiter_open(&ii, vindex, VINYL_GE, NULL, 0);
    6213           0 :         while (sv_indexiter_has(&ii))
    6214             :         {
    6215           0 :                 struct sv *v = sv_indexiter_get(&ii);
    6216           0 :                 int rc = vy_buf_add(&c->b, &v->v, sizeof(struct svref **));
    6217           0 :                 if (unlikely(rc == -1))
    6218           0 :                         return vy_oom();
    6219           0 :                 sv_indexiter_next(&ii);
    6220             :         }
    6221           0 :         if (unlikely(vy_buf_used(&c->b) == 0))
    6222             :                 return 0;
    6223             :         struct vy_bufiter i, j;
    6224           0 :         vy_bufiter_open(&i, &c->b, sizeof(struct svref*));
    6225           0 :         vy_bufiter_open(&j, result, sizeof(struct vy_range*));
    6226           0 :         struct vy_range *prev = vy_bufiterref_get(&j);
    6227             :         vy_bufiter_next(&j);
    6228             :         while (1)
    6229             :         {
    6230           0 :                 struct vy_range *p = vy_bufiterref_get(&j);
    6231           0 :                 if (p == NULL) {
    6232             :                         assert(prev != NULL);
    6233           0 :                         while (vy_bufiter_has(&i)) {
    6234           0 :                                 struct svref *v = vy_bufiterref_get(&i);
    6235           0 :                                 sv_indexset(&prev->i0, *v);
    6236             :                                 vy_bufiter_next(&i);
    6237             :                         }
    6238             :                         break;
    6239             :                 }
    6240           0 :                 while (vy_bufiter_has(&i))
    6241             :                 {
    6242           0 :                         struct svref *v = vy_bufiterref_get(&i);
    6243           0 :                         struct vy_page_info *page = vy_page_index_first_page(&p->self.index);
    6244           0 :                         int rc = vy_tuple_compare(v->v->data,
    6245           0 :                                 vy_page_index_min_key(&p->self.index, page),
    6246           0 :                                 index->key_def);
    6247           0 :                         if (unlikely(rc >= 0))
    6248             :                                 break;
    6249           0 :                         sv_indexset(&prev->i0, *v);
    6250             :                         vy_bufiter_next(&i);
    6251             :                 }
    6252           0 :                 if (unlikely(! vy_bufiter_has(&i)))
    6253             :                         break;
    6254           0 :                 prev = p;
    6255             :                 vy_bufiter_next(&j);
    6256             :         }
    6257             :         assert(vy_bufiterref_get(&i) == NULL);
    6258             :         return 0;
    6259             : }
    6260             : 
    6261             : static inline void
    6262           0 : si_redistribute_set(struct vinyl_index *index, uint64_t now, struct svref *v)
    6263             : {
    6264           0 :         index->update_time = now;
    6265             :         /* match node */
    6266             :         struct vy_rangeiter ii;
    6267           0 :         vy_rangeiter_open(&ii, index, VINYL_GE, v->v->data, v->v->size);
    6268           0 :         struct vy_range *node = vy_rangeiter_get(&ii);
    6269             :         assert(node != NULL);
    6270             :         /* update node */
    6271           0 :         struct svindex *vindex = vy_range_index(node);
    6272           0 :         int rc = sv_indexset(vindex, *v);
    6273             :         assert(rc == 0); /* TODO: handle BPS tree errors properly */
    6274             :         (void) rc;
    6275           0 :         node->update_time = index->update_time;
    6276           0 :         node->used += vinyl_tuple_size(v->v);
    6277             :         /* schedule node */
    6278           0 :         vy_planner_update(&index->p, SI_BRANCH, node);
    6279           0 : }
    6280             : 
    6281             : static int
    6282           0 : si_redistribute_index(struct vinyl_index *index, struct sdc *c, struct vy_range *node)
    6283             : {
    6284           0 :         struct svindex *vindex = vy_range_index(node);
    6285             :         struct vy_iter ii;
    6286             :         sv_indexiter_open(&ii, vindex, VINYL_GE, NULL, 0);
    6287           0 :         while (sv_indexiter_has(&ii)) {
    6288           0 :                 struct sv *v = sv_indexiter_get(&ii);
    6289           0 :                 int rc = vy_buf_add(&c->b, &v->v, sizeof(struct svref**));
    6290           0 :                 if (unlikely(rc == -1))
    6291           0 :                         return vy_oom();
    6292           0 :                 sv_indexiter_next(&ii);
    6293             :         }
    6294           0 :         if (unlikely(vy_buf_used(&c->b) == 0))
    6295             :                 return 0;
    6296           0 :         uint64_t now = clock_monotonic64();
    6297             :         struct vy_bufiter i;
    6298           0 :         vy_bufiter_open(&i, &c->b, sizeof(struct svref*));
    6299           0 :         while (vy_bufiter_has(&i)) {
    6300           0 :                 struct svref *v = vy_bufiterref_get(&i);
    6301           0 :                 si_redistribute_set(index, now, v);
    6302             :                 vy_bufiter_next(&i);
    6303             :         }
    6304             :         return 0;
    6305             : }
    6306             : 
    6307             : static int
    6308           0 : si_splitfree(struct vy_buf *result, struct vinyl_env *env)
    6309             : {
    6310             :         struct vy_bufiter i;
    6311             :         vy_bufiter_open(&i, result, sizeof(struct vy_range*));
    6312           0 :         while (vy_bufiter_has(&i))
    6313             :         {
    6314           0 :                 struct vy_range *p = vy_bufiterref_get(&i);
    6315           0 :                 vy_range_free(p, env, 0);
    6316             :                 vy_bufiter_next(&i);
    6317             :         }
    6318           0 :         return 0;
    6319             : }
```

Please investigate what is `si_redistribute()` and add a test case or remove this code.

**Comment by kostja** [comment]
* Roman Tsisyk <notifications@github.com> [16/07/21 10:53]:

si_redistribute() redistributes the in-memory index of a pruned
range (e.g. when a range is split in two).

The way it's implemented, by locking the entire index (see
vy_index_lock() in the caller function), and then trying to push
tuple into related indexes one by one is utter crap.

So it's good it's not covered by tests - we need to make sure it's
never used (e.g. we never split a range before flushing its
in-memory part to disk, etc),  and delete it.

> ```
>     6205             : static int
>     6206           0 : si_redistribute(struct vinyl_index *index, struct sdc *c,
>     6207             :                 struct vy_range *node, struct vy_buf *result)
>     6208             : {
>     6209             :         (void)index;
>     6210           0 :         struct svindex *vindex = vy_range_index(node);
>     6211             :         struct vy_iter ii;
>     6212             :         sv_indexiter_open(&ii, vindex, VINYL_GE, NULL, 0);
>     6213           0 :         while (sv_indexiter_has(&ii))
>     6214             :         {
>     6215           0 :                 struct sv *v = sv_indexiter_get(&ii);
>     6216           0 :                 int rc = vy_buf_add(&c->b, &v->v, sizeof(struct svref **));
>     6217           0 :                 if (unlikely(rc == -1))
>     6218           0 :                         return vy_oom();
>     6219           0 :                 sv_indexiter_next(&ii);
>     6220             :         }
>     6221           0 :         if (unlikely(vy_buf_used(&c->b) == 0))
>     6222             :                 return 0;
>     6223             :         struct vy_bufiter i, j;
>     6224           0 :         vy_bufiter_open(&i, &c->b, sizeof(struct svref*));
>     6225           0 :         vy_bufiter_open(&j, result, sizeof(struct vy_range*));
>     6226           0 :         struct vy_range *prev = vy_bufiterref_get(&j);
>     6227             :         vy_bufiter_next(&j);
>     6228             :         while (1)
>     6229             :         {
>     6230           0 :                 struct vy_range *p = vy_bufiterref_get(&j);
>     6231           0 :                 if (p == NULL) {
>     6232             :                         assert(prev != NULL);
>     6233           0 :                         while (vy_bufiter_has(&i)) {
>     6234           0 :                                 struct svref *v = vy_bufiterref_get(&i);
>     6235           0 :                                 sv_indexset(&prev->i0, *v);
>     6236             :                                 vy_bufiter_next(&i);
>     6237             :                         }
>     6238             :                         break;
>     6239             :                 }
>     6240           0 :                 while (vy_bufiter_has(&i))
>     6241             :                 {
>     6242           0 :                         struct svref *v = vy_bufiterref_get(&i);
>     6243           0 :                         struct vy_page_info *page = vy_page_index_first_page(&p->self.index);
>     6244           0 :                         int rc = vy_tuple_compare(v->v->data,
>     6245           0 :                                 vy_page_index_min_key(&p->self.index, page),
>     6246           0 :                                 index->key_def);
>     6247           0 :                         if (unlikely(rc >= 0))
>     6248             :                                 break;
>     6249           0 :                         sv_indexset(&prev->i0, *v);
>     6250             :                         vy_bufiter_next(&i);
>     6251             :                 }
>     6252           0 :                 if (unlikely(! vy_bufiter_has(&i)))
>     6253             :                         break;
>     6254           0 :                 prev = p;
>     6255             :                 vy_bufiter_next(&j);
>     6256             :         }
>     6257             :         assert(vy_bufiterref_get(&i) == NULL);
>     6258             :         return 0;
>     6259             : }
>     6260             : 
>     6261             : static inline void
>     6262           0 : si_redistribute_set(struct vinyl_index *index, uint64_t now, struct svref *v)
>     6263             : {
>     6264           0 :         index->update_time = now;
>     6265             :         /* match node */
>     6266             :         struct vy_rangeiter ii;
>     6267           0 :         vy_rangeiter_open(&ii, index, VINYL_GE, v->v->data, v->v->size);
>     6268           0 :         struct vy_range *node = vy_rangeiter_get(&ii);
>     6269             :         assert(node != NULL);
>     6270             :         /* update node */
>     6271           0 :         struct svindex *vindex = vy_range_index(node);
>     6272           0 :         int rc = sv_indexset(vindex, *v);
>     6273             :         assert(rc == 0); /* TODO: handle BPS tree errors properly */
>     6274             :         (void) rc;
>     6275           0 :         node->update_time = index->update_time;
>     6276           0 :         node->used += vinyl_tuple_size(v->v);
>     6277             :         /* schedule node */
>     6278           0 :         vy_planner_update(&index->p, SI_BRANCH, node);
>     6279           0 : }
>     6280             : 
>     6281             : static int
>     6282           0 : si_redistribute_index(struct vinyl_index *index, struct sdc *c, struct vy_range *node)
>     6283             : {
>     6284           0 :         struct svindex *vindex = vy_range_index(node);
>     6285             :         struct vy_iter ii;
>     6286             :         sv_indexiter_open(&ii, vindex, VINYL_GE, NULL, 0);
>     6287           0 :         while (sv_indexiter_has(&ii)) {
>     6288           0 :                 struct sv *v = sv_indexiter_get(&ii);
>     6289           0 :                 int rc = vy_buf_add(&c->b, &v->v, sizeof(struct svref**));
>     6290           0 :                 if (unlikely(rc == -1))
>     6291           0 :                         return vy_oom();
>     6292           0 :                 sv_indexiter_next(&ii);
>     6293             :         }
>     6294           0 :         if (unlikely(vy_buf_used(&c->b) == 0))
>     6295             :                 return 0;
>     6296           0 :         uint64_t now = clock_monotonic64();
>     6297             :         struct vy_bufiter i;
>     6298           0 :         vy_bufiter_open(&i, &c->b, sizeof(struct svref*));
>     6299           0 :         while (vy_bufiter_has(&i)) {
>     6300           0 :                 struct svref *v = vy_bufiterref_get(&i);
>     6301           0 :                 si_redistribute_set(index, now, v);
>     6302             :                 vy_bufiter_next(&i);
>     6303             :         }
>     6304             :         return 0;
>     6305             : }
>     6306             : 
>     6307             : static int
>     6308           0 : si_splitfree(struct vy_buf *result, struct vinyl_env *env)
>     6309             : {
>     6310             :         struct vy_bufiter i;
>     6311             :         vy_bufiter_open(&i, result, sizeof(struct vy_range*));
>     6312           0 :         while (vy_bufiter_has(&i))
>     6313             :         {
>     6314           0 :                 struct vy_range *p = vy_bufiterref_get(&i);
>     6315           0 :                 vy_range_free(p, env, 0);
>     6316             :                 vy_bufiter_next(&i);
>     6317             :         }
>     6318           0 :         return 0;
>     6319             : }
> ```
> 
> Please investigate what is `si_redistribute()` and add a test case or remove this code.
> 
> 
> ---
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/tarantool/tarantool/issues/1635

-- 
Konstantin Osipov, Moscow, Russia, +7 903 626 22 32
http://tarantool.org - www.twitter.com/kostja_osipov
