### ISSUE TITLE
Implement quantile calculation in C

### ISSUE THREAD

**Issue by knazarov** [tarantool/tarantool#1636]
The quantile calculation over an infinite stream is needed for Prometheus monitoring, and may also be useful as a function over Tarantool spaces.

Here's an algorithm used by Prometheus Go client to calculate quantiles: http://www.cs.rutgers.edu/%7Emuthu/bquant.pdf

The description of difference between summary and histogram metrics and reasoning behind them can be found here:
https://prometheus.io/docs/practices/histograms/

**Comment by Mons** [comment]
Implemented in tarantool/metrics
