### ISSUE TITLE
Segfault on xpcall + box.rollback()

### ISSUE THREAD

**Issue by zaglex** [tarantool/tarantool#1638]
Tarantool crashes on box.rollback() in xpcall error handler when parallel processes are working.

**How to reproduce:**
1) Define such lua-function

```lua
function myfunc()
    local response = {}
    response.status = xpcall(function()
        box.begin()
        error('test error')
        box.commit()
    end, function(message)
        box.rollback()
    end)

    return response
end
```

2) Somehow call this function simultaneously from two processes. E.g. you can use such php-script:
```php
<?php
$tnt = new Tarantool('localhost', 3301);
for ($i = 0; $i < 100000; $i++) {
    $tnt->call('myfunc', []);
}
```
and run two instances of it simultaneously.

**Tarantool version:**
Tarantool 1.6.8-623-g932857e
Target: Linux-x86_64-Gentoo

P.S.
With pcall everything is ok, but I wanted to use xpcall for debug.traceback().

**Comment by rtsisyk** [comment]
1.6.8-631-g2e08d87
1.7.1-191-g08ed210
