### ISSUE TITLE
Index::Index: index must not be opened in constructor

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#1640]
Successor of Index class in constructor must not actually open index. Need to open index in another method.
If we open index in constructor then VinylIndex in constructor during altering space creates and opens vinyl indices even if this index already exists.
This executes on alter: `vinyl_index.cc: db = vinyl_index_new(env, key_def, space->format); `

**Comment by rtsisyk** [comment]
Needed for #623
