### ISSUE TITLE
vinyl: assertion when creating second index

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#1647]
I have Ubuntu 14.04 and Tarantool 1.7, pulled from source today.

I execute these requests:
box.cfg{}
box.schema.space.create('t',{engine='vinyl'})
box.space.t:create_index('primary')
box.space.t:insert{1,'',''}
box.space.t:create_index('a1')

The result for the final statement is:
tarantool> box.space.t:create_index('a1')
tarantool: /home/pgulutzan/tarantool-1.7/src/box/vinyl_index.cc:218: virtual tuple* VinylIndex::replace(tuple*, tuple*, dup_replace_mode): Assertion `0' failed.
Aborted (core dumped)

**Comment by rtsisyk** [comment]
Discussed => add ER_UNSSUPPORTED in ALTER for 1.7.1 (beta), implement in 1.7.2+.
