### ISSUE TITLE
ASCII plotting rock

### ISSUE THREAD

**Issue by ghost** [tarantool/tarantool#1652]
The code is sitting around in my repos and it might as well go towards something. 300 lines of lua. Good for time series and can scale to ridiculous levels. The following plot was about a gig of data plotted in about a second.

Let me know if interest!

![timestamps](https://cloud.githubusercontent.com/assets/3138149/17249743/5c14948a-556f-11e6-8e82-9714c30f6d5e.png)

**Comment by rtsisyk** [comment]
wow!
It would be nice to make a module (rock) for Lua.

**Comment by rtsisyk** [comment]
@gpryor could you please make a Lua module for ASCII plotting? It should be useful for Lua community as well as for Tarantool users. We have an example [here](https://github.com/tarantool/modulekit).

**Comment by Mons** [comment]
Looks nice, but user has gone and no code references left
