### ISSUE TITLE
0 in SYNC field of header for the "Invalid MsgPack - packet body" error

### ISSUE THREAD

**Issue by brigadier** [tarantool/tarantool#1654]
Tarantool always returns 0 in the SYNC field of header after DELETE (and may be other) requests with invalid data (for example DELETE with index as string) and closes the socket. I understand such behaviour for the cases when the head can't be parsed at all, but for the error in body it would be better to return standard error response, with the real SYNC and without closing the socket.
It is also inconsistent with the UPDATE operation, which correctly returns errors for bad operations, without closing the socket.

**Comment by rtsisyk** [comment]
Do you mean that server returns incorrect SYNC value for ERROR responses in case of DELETE/UPDATE? I just checked 1.6/1.7 code and I can't confirm that. 

Please provide an information about your Tarantool version and a test case. Thanks!

**Comment by brigadier** [comment]
Hi,
 version 1.7.1-89-g36a0cd1

Sorry, my initial description was incorrect. tarantool just closes the socket when it encounters non-integer value of index in otherwise correct packet.
Test case - send a 'delete' packed with STR value in index field instead of INT. This packet is incorrect indeed, but I think closing socket it is not necessary for such errors, when there's a header, a body with all necessary fields but just one of the fields has incorrect type. In contrary, for the 'update' packet, if I send some incorrect ops, it just returns an error packet with "Unknown UPDATE operation".

The packet which makes tarantool close the socket ("" in index):  `<<131,16,205,2,1,17,160,32,146,1,2>>`
Correct packet (1 in index): `<<131,16,205,2,1,17,1,32,146,1,2>>`

**Comment by kostja** [comment]
* Evgeny M. <notifications@github.com> [16/08/01 14:33]:
> Sorry, my initial description was incorrect. tarantool just closes the socket when it encounters non-integer value of index in otherwise correct packet.
> Test case - send a 'delete' packed with STR value in index field instead of INT. This packet is incorrect indeed, but I think closing socket it is not necessary for such errors, when there's a header, a body with all necessary fields but just one of the fields has incorrect type. In contrary, for the 'update' packet, if I send some incorrect ops, it just returns an error packet with "Unknown UPDATE operation".
> 
> The packet which makes tarantool close the socket ("" in index):  `<<131,16,205,2,1,17,160,32,146,1,2>>`
> Correct packet (1 in index): `<<131,16,205,2,1,17,1,32,146,1,2>>`

Just my curiosity, is the client a Perl one?

-- 
Konstantin Osipov, Moscow, Russia, +7 903 626 22 32
http://tarantool.org - www.twitter.com/kostja_osipov

**Comment by brigadier** [comment]
Erlang one https://github.com/brigadier/tara/
