### ISSUE TITLE
vinyl: change disk format

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#1656]
- [ ] Merge `struct sdindexheader` into `struct sdseal`
- [ ] Merge `struct sdindexpage` into `struct sdpageheader`
- [ ] Save compressor name in pageheader
- [ ] Change absolute offsets to relative

See https://github.com/tarantool/tarantool/wiki/Vinyl%20Architecture

See also:

* #1610, #1611, #1527, #1530, #1618, #1628

**Comment by alyapunov** [comment]
Reorder members in struct PACKED sdv: uint64_t, uint32_t, uint32_t, uint8_t for better align

**Comment by alyapunov** [comment]
Add key size to vy_page_info
Add number-of-deleted records to vy_page_info
Remove all DUP counts

**Comment by rtsisyk** [comment]
Superseded by #1720
