### ISSUE TITLE
auto_increment doesn't work on vinyl engine

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#1658]
Test case:
`space = box.schema.space.create('tweedledum', { engine = 'vinyl' })`
`space:create_index('primary', { type  = 'tree', parts = {1, 'num'}, unique = true })`
`space:auto_increment{'a'}`
`space:auto_increment{'b'}`
`space:auto_increment{'c'}`

Sometimes this test fails.

**Comment by Gerold103** [comment]
Duplicate of #1435

**Comment by rtsisyk** [comment]
auto_increment on vinyl is hard to fix - each operation will require disk lookup (index:max()).

**Comment by kostja** [comment]
This is done (and covered by a test, vinyl/errinj.test, vinyl/gh.test)
