### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by stepan-mitkin** [tarantool/tarantool#1660]
## Operating system
Debian Wheezy 64 bit
Linux localhost 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux

## Log after crash
Segmentation fault
Current time: 1469838361
Please file a bug at http://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed, 
this may fail as well
#0  0x426e11 in sig_fatal_cb(int)+129
#1  0x7fd030c3f8d0 in ?

## Log after restart:
2016-07-30 07:25:01.382 [10945] main/101/dewt.lua C> version 1.6.8-653-g2e4a17d
2016-07-30 07:25:01.382 [10945] main/101/dewt.lua C> log level 5
2016-07-30 07:25:01.383 [10945] main/101/dewt.lua I> mapping 536870912 bytes for tuple arena...
2016-07-30 07:25:01.384 [10945] main/101/dewt.lua I> recovery start

**Comment by rtsisyk** [comment]
Hi, could you please provide a test case, a coredump or a backtrace?

**Comment by stepan-mitkin** [comment]
Ahh... The coredump file is lost.
Sorry for not being useful.
What can I do to get more info if (when) this problem occurs again?

**Comment by rtsisyk** [comment]
You can enable coredumps (ulimit -c unlimited).
It is even better to send us a reproducible test case.
