### ISSUE TITLE
"Can't start tarantool" on restart in tests

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#1663]
Build: https://travis-ci.org/tarantool/tarantool/builds/149430449
Valgrind errors:
engine/misc.test.lua with parameter engine = 'vinyl'
==18901== Thread 5 vinyl:
==18901== Invalid read of size 4
==18901==    at 0x49C812: vy_task_execute (vinyl.c:5203)
==18901==    by 0x4A5FA3: sc_schedule (vinyl.c:7684)
==18901==    by 0x4ACC64: vinyl_worker (vinyl.c:9576)
==18901==    by 0x4F5FEA: cord_thread_func (fiber.c:816)
==18901==    by 0x58EE6F9: start_thread (pthread_create.c:333)
==18901==    by 0x66CDB5C: clone (clone.S:109)
==18901==  Address 0x6d79ac8 is 5,752 bytes inside a block of size 5,904 free'd
==18901==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==18901==    by 0x4A9B41: vinyl_index_delete (vinyl.c:8524)
==18901==    by 0x49EDA3: vy_index_drop (vinyl.c:5695)
==18901==    by 0x49C7E3: vy_task_execute (vinyl.c:5196)
==18901==    by 0x4A5FA3: sc_schedule (vinyl.c:7684)
==18901==    by 0x4ACC64: vinyl_worker (vinyl.c:9576)
==18901==    by 0x4F5FEA: cord_thread_func (fiber.c:816)
==18901==    by 0x58EE6F9: start_thread (pthread_create.c:333)
==18901==    by 0x66CDB5C: clone (clone.S:109)
==18901==  Block was alloc'd at
==18901==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==18901==    by 0x4A8FEF: vinyl_index_new (vinyl.c:8421)
==18901==    by 0x47E2BD: VinylIndex::VinylIndex(key_def*) (vinyl_index.cc:131)
==18901==    by 0x47B922: VinylEngine::createIndex(key_def*) (vinyl_engine.cc:191)
==18901==    by 0x440198: space_new(space_def*, rlist*) (space.cc:129)
==18901==    by 0x4B0E25: alter_space_do(txn*, alter_space*, space*) (alter.cc:756)
==18901==    by 0x4B291C: on_replace_dd_index(trigger*, void*) (alter.cc:1413)
==18901==    by 0x4460F3: trigger_run (trigger.h:77)
==18901==    by 0x446B50: txn_commit_stmt(txn*, request*) (txn.cc:171)
==18901==    by 0x448D68: process_rw(request*, tuple**) (box.cc:168)
==18901==    by 0x448EF3: apply_row(xstream*, xrow_header*) (box.cc:203)
==18901==    by 0x448F19: apply_wal_row(xstream*, xrow_header*) (box.cc:217)
==18901==

engine/upsert.test.lua with parameter engine = 'vinyl'
==19063== Thread 7 vinyl:
==19063== Invalid read of size 4
==19063==    at 0x49C812: vy_task_execute (vinyl.c:5203)
==19063==    by 0x4A5FA3: sc_schedule (vinyl.c:7684)
==19063==    by 0x4ACC64: vinyl_worker (vinyl.c:9576)
==19063==    by 0x4F5FEA: cord_thread_func (fiber.c:816)
==19063==    by 0x58EE6F9: start_thread (pthread_create.c:333)
==19063==    by 0x66CDB5C: clone (clone.S:109)
==19063==  Address 0x6e61c78 is 5,752 bytes inside a block of size 5,904 free'd
==19063==    at 0x4C2EDEB: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==19063==    by 0x4A9B41: vinyl_index_delete (vinyl.c:8524)
==19063==    by 0x49EDA3: vy_index_drop (vinyl.c:5695)
==19063==    by 0x49C7E3: vy_task_execute (vinyl.c:5196)
==19063==    by 0x4A5FA3: sc_schedule (vinyl.c:7684)
==19063==    by 0x4ACC64: vinyl_worker (vinyl.c:9576)
==19063==    by 0x4F5FEA: cord_thread_func (fiber.c:816)
==19063==    by 0x58EE6F9: start_thread (pthread_create.c:333)
==19063==    by 0x66CDB5C: clone (clone.S:109)
==19063==  Block was alloc'd at
==19063==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==19063==    by 0x4A8FEF: vinyl_index_new (vinyl.c:8421)
==19063==    by 0x47E2BD: VinylIndex::VinylIndex(key_def*) (vinyl_index.cc:131)
==19063==    by 0x47B922: VinylEngine::createIndex(key_def*) (vinyl_engine.cc:191)
==19063==    by 0x440198: space_new(space_def*, rlist*) (space.cc:129)
==19063==    by 0x4B0E25: alter_space_do(txn*, alter_space*, space*) (alter.cc:756)
==19063==    by 0x4B291C: on_replace_dd_index(trigger*, void*) (alter.cc:1413)
==19063==    by 0x4460F3: trigger_run (trigger.h:77)
==19063==    by 0x446B50: txn_commit_stmt(txn*, request*) (txn.cc:171)
==19063==    by 0x448D68: process_rw(request*, tuple**) (box.cc:168)
==19063==    by 0x448EF3: apply_row(xstream*, xrow_header*) (box.cc:203)
==19063==    by 0x448F19: apply_wal_row(xstream*, xrow_header*) (box.cc:217)
==19063==

**Comment by rtsisyk** [comment]
Confirmed, I can reproduce that
