### ISSUE TITLE
rb.h: more efficient iterator, is_empty()

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#1668]
The current rb iterator doesn't store the path, and rbtree nodes don't store parent links, so it takes a new log(N) lookup to advance to the right subtree. Implement an iterator that stores the current iteration path in the tree, and use it in vinyl.

Implement _is_empty() helper.

**Comment by rtsisyk** [comment]
Nobody cares => 1.7.4

**Comment by rtsisyk** [comment]
1.7.4-423-g738a6afd3
