### ISSUE TITLE
Implement libcurl based http client

### ISSUE THREAD

**Issue by Sulverus** [tarantool/tarantool#1674]
Out customers need http client with:
* keep alive support (`CURLOPT_*_KEEP*` options)
* https support (`CURLOPT_SSL_*` options)
* support custom dns server (`CURLOPT_DNS_*` options)
* All http options

Optional:
* async dns resolving (probably uDNS lib based) (do not use curl dns resolver)

**Comment by kostja** [comment]
Done.
