### ISSUE TITLE
vinyl: infinite cycle on box.snapshot

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#1684]
test case:

box.cfg{}
engine = 'vinyl'
-- Create and drop several indices
space = box.schema.space.create('test', { engine = engine })
pk = space:create_index('primary')
index2 = space:create_index('secondary', { parts = {2, 'str'} })
index3 = space:create_index('third', { parts = {3, 'str'}, unique = false })
index2:drop()
index2 = space:create_index('secondary', { parts = {4, 'str'} })
index3:drop()
index2:drop()
index2 = space:create_index('secondary', { parts = {2, 'str'} })
index3 = space:create_index('third', { parts = {3, 'str'}, unique = false })
index4 = space:create_index('fourth', { parts = {2, 'str', 3, 'str'} })
space:drop()

-- test index:bsize()

space = box.schema.space.create('test', { engine = engine })
pk = space:create_index('primary', { type = 'tree', parts = {1, 'unsigned'} })
box.snapshot()
space:drop()

**Comment by rtsisyk** [comment]
I'll check it.
