### ISSUE TITLE
vinyl: index:count() doesn't yield

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#1688]
index:count() may block TX thread for the long time if runs are cached in memory.
Please add explicit yields.

**Comment by kostja** [comment]
The suggestion look like a hack. It doesn't yield in memtx either, so what?

11 авг. 2016 г. 5:13 PM пользователь "Roman Tsisyk" <
notifications@github.com> написал:

**Comment by rtsisyk** [comment]
> The suggestion look like a hack. It doesn't yield in memtx either, so what? 

Tarantool totally stops responding on occasional index:count() call.
I think than fiber_reschedule() for every 1000 rows is good hack.

**Comment by rtsisyk** [comment]
This feature requires #1796, which is in the wishlist.
