### ISSUE TITLE
Types in system spaces

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#1690]
I have Ubuntu 14.04 and Tarantool 1.7, pulled from source today.

I execute this request:
box.space._space.index.name:select{'_space'}
## The result is:
- \- [280, 1, '_space', 'memtx', 0, {}, [{'name': 'id', 'type': 'num'}, {'name': 'owner',
      'type': 'num'}, {'name': 'name', 'type': 'str'}, {'name': 'engine', 'type': 'str'},
    {'name': 'field_count', 'type': 'num'}, {'name': 'flags', 'type': 'str'}, {
      'name': 'format', 'type': '*'}]]
  ...

The type values 'num' and 'str' are not the values that I see if
I say box.space._space, and 'num' is deprecated.
When creating a system space we should use the values that we recommend.

Additionally, please consider disallowing invalid or abnormal values
for type in the format clause for ordinary spaces.
For example disallow
box.schema.space.create('TM', {
            format = {
              [1] = {["name"] = "field#1"},
              [2] = {["type"] = "UINT"}
            }
          })

**Comment by rtsisyk** [comment]
Probably we should use avro schema for space.format()

**Comment by kostja** [comment]
This is done.
