### ISSUE TITLE
vinyl: centralized tuple cache, with range support

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#1692]
We need to create a range tree with [min, max] ranges (one-dimensional RTREE).

For invalidation, look at MARK, randomized garbage collection, or 3-zone LRU cache implementation.
Avoid mutexes, use refs/pins to pin the page in the cache. Cache pages should be block-size aligned,
use the lower bits to deal with ABA problem. 
Perhaps a ready-to-use implementation is already available online.

Page size: assume the page has to take aligned size in RAM (e.g. 4-8K), but can be of any size on disk.

Coordination of page cache expiration and pruning of runs: since it's going to be a global cache, there should be a way to prune (mark as unused) all pages of a run when the run itself is merged.

**Comment by rtsisyk** [comment]
@kostja I had to state that nobody works on this feature except @feldsherov

**Comment by rtsisyk** [comment]
1.7.3-123-g33b4f2d
