### ISSUE TITLE
Fiber storage hasn't data in first time access

### ISSUE THREAD

**Issue by zloidemon** [tarantool/tarantool#1696]
Fiber storage hasn't data in first time access. If put **fiber.sleep(1)** inside fiber before use fiber.self() it will work.

```
tarantool: version 1.6.8-371-g6a7d814
```

Simple code:
```
fiber = require 'fiber'

local function test_fiber()
    local me = fiber.self()
    print('pre while', me.storage.xxx)
    while true do
        print('in while', me.storage.xxx)
        fiber.sleep(2)
    end
end

f = fiber.create(test_fiber)
f.storage.xxx = 'lol'
```

Output:
```
> tarantool xxx.lua
pre while	nil
in while	nil
xxx.lua: entering the event loop
in while	lol
in while	lol
in while	lol
in while	lol
in while	lol
```

**Comment by mejedi** [comment]
It's a quirk of the current fiber scheduler; not a bug.

Basically, when the parent fiber spawns a child via `fiber.create`, the new fiber starts executing immediately. Once the child reaches `fiber.sleep()`, it yields allowing for the parent to resume. At this point, the next line following `fiber.create()` executes and `f.storage.xxx` is set.
