### ISSUE TITLE
Avoid reading from disk in vy_readcommited() during WAL recovery

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#1697]
When recovering from WAL we may apply records which are already applied. To avoid it, si_write() calls si_readcommitted() to check if a tuple has not been already applied. This can be avoided altogether, if we issue a checkpoint after WAL recovery and flush all vy_mem indexes to disk along with pruning of already inserted tuples.

**Comment by alyapunov** [comment]
Merge_iterator is not ready now for duplicated statements
I'd put forward another way. Every range could simply hold max_lsn value. During recovery every statement finds its range and if the statement->lsn <=  the range->max_lsn then the statement must be skipped.
