### ISSUE TITLE
vinyl: use uint64_t and off_t instead of int for offsets

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#1711]
int is 32-bit, off_t is 64-bit if large file is enabled

**Comment by Gerold103** [comment]
Test case
box.cfg{
	slab_alloc_maximal = 2 * 1024 * 1024,
	logger = 'tarantool.log'
}
space = box.schema.space.create('test', { engine = 'vinyl' })
index = space:create_index('pk')
str_val = 'a'
for i = 1, 20 do str_val = str_val..str_val end
for i = 1, 1000 do space:insert({i, str_val}) collectgarbage('collect') end
box.snapshot()
for i = 1001, 1100 do space:insert({i, str_val}) collectgarbage('collect') end
box.snapshot()
for i = 1101, 1200 do space:insert({i, str_val}) collectgarbage('collect') end
box.snapshot()
for i = 1201, 1300 do space:insert({i, str_val}) collectgarbage('collect') end
box.snapshot()
for i = 1301, 1400 do space:insert({i, str_val}) collectgarbage('collect') end
box.snapshot()
for i = 1401, 1500 do space:insert({i, str_val}) collectgarbage('collect') end
box.snapshot()
for i = 1501, 1600 do space:insert({i, str_val}) collectgarbage('collect') end
box.snapshot()
for i = 1601, 1700 do space:insert({i, str_val}) collectgarbage('collect') end
box.snapshot()
for i = 1701, 1800 do space:insert({i, str_val}) collectgarbage('collect') end
box.snapshot()
