### ISSUE TITLE
gentoo ebuild ?

### ISSUE THREAD

**Issue by xpunkt** [tarantool/tarantool#1715]
please make one :=)

**Comment by rtsisyk** [comment]
We have outdated Gentoo Overlay for Tarantool 1.5: https://github.com/tarantool/gentoo-overlay 
It would be nice if you can update this overlay to the latest Tarantool version.

**Comment by xpunkt** [comment]
i have already maked 2 pulls :=)

git-2 is also to old, should be git-r3

eapi=4 should be eapi=5 now

wiill try if i can solve it all

**Comment by xpunkt** [comment]
found that it have submodule in github, this submodules are fetched authmatic in git-r3 eclass

for this to work its imho needed to make each submodule a new ebuild ?

**Comment by rtsisyk** [comment]
> for this to work its imho needed to make each submodule a new ebuild ?

I don't think that it makes sense.

**Comment by xpunkt** [comment]
layman -a fidonet
emerge --autounmask-write =tarantool-1.5.9999
etc-update
emerge -av tarantool

here is my current problem

**Comment by cono** [comment]
I've made 1.5.5_p33 version:
https://github.com/tarantool/gentoo-overlay/pull/5

Tried via new portage repos.conf feature. Successfully installed and started tarantool server.

**Comment by xpunkt** [comment]
thanks cono, where is that ebuild just ?

note my work is based on HEAD in github, so the ebuild name should changed to tarantool-9999 with always will be HEAD in github

**Comment by cono** [comment]
@xpunkt I have provided a link to the merge request: https://github.com/tarantool/gentoo-overlay/pull/5

**Comment by Totktonada** [comment]
The issue seems to be fixed.

* Ebuilds for git live version and for several releases are available in an overlay: https://github.com/tarantool/gentoo-overlay
* The overlay was added to layman (Gentoo repositories infrastructure): https://github.com/gentoo/api-gentoo-org/commit/9c796454286c40c1ca8c6cf5fa520a4a9b2cf102
