### ISSUE TITLE
Improve update optimization for secondary keys

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#1716]
Set the last bit in a column mask as an indicator of changing tuple fields from 64 to infinity. 
Most keys are defined on fields in range 0..60, and tracking updates of fields with large ids in the last bit would allow us to skip updating secondary indexes for such updates.

**Comment by rtsisyk** [comment]
Nobody cares about indexes with 63+ parts. Please consider to close this ticket.

**Comment by rtsisyk** [comment]
Blocked by #2312

**Comment by Gerold103** [comment]
It is not blocked. Write iterator doesn't explicitly use the last bit of the column mask.

**Comment by Gerold103** [comment]
Now it is not only vinyl feature. When the column mask became the part of the key_def, we are able to use column mask in the memtx also.
See https://github.com/tarantool/tarantool/commit/f3aeb39832ea517423a578c7c6a5348c97ecf779
