### ISSUE TITLE
New format for vinyl metadata

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#1720]
# Vinyl meta format.

Store such things as `vy_page_header`, `vy_run_header`, etc as xlog file on disk.
This solves the big-endian vs. little endian problem, as well as forward/backward compatibility issues.

File name: <index_lsn>.<range_id>.<run id>.index
File format: tarantool xlog file
Xlog format type: INDEX (tuples are stored in .run files with RUN type)

A file for a run will contain one entry in _vinyl_run system space and an entry per every page of the run (space _vinyl_page).

Each run or page should have only one xlog entry in the file into its corresponding space.

## Run Information

Space name: _vinyl_run
Space id: 328 (not saved in snapshots, but reserved):

Run requests will be storead as 2-field tuple, first is the run identifier, second - map with run info. Run info map consists of min and max lsn and run page count.

Tuple fields:
* run_id: int64_t
* space_id: int32_t
* index_id: int32_t
* index_lsn: int64_t
* map:
  + VY_RUN_MIN_LSN = 1: int64_t
  + VY_RUN_MAX_LSN = 2: int64_t
  + VY_RUN_PAGE_COUNT = 3:  int64_t
  + VY_RANGE_MIN_KEY = 4: array
  + VY_RANGE_MAX_KEY = 5: array

## Page Index

Space name: _vinyl_index
Space id: 336 (not saved in snapshots, but reserved):

Page requests are stored as a 3-field tuple, first and second are the run
and page identifiers, three - map with page info. Page info map consists of
page file offset and page file size, page request count and page min key.

Tuple fields:
* run_id: int64_t
* page_offset: int64_t
* page_size: int64_t
* key/value map:
  + VY_PAGE_MIN_KEY = 1: array (tuple)
  + VY_PAGE_MAX_KEY = 2: array (tuple) - reserved for iterator optimization
  + VY_PAGE_MIN_LSN = 3: int64_t - this may speed up merges
  + VY_PAGE_MAX_LSN = 4: int64_t
  + VY_PAGE_UNPACKED_SIZE = 5: int64_t - uncompressed size of a page
  + VY_PAGE_REQUEST_COUNT = 6: uint32_t
  + VY_PAGE_BLOOMFILTER = 7: bin - RESERVED, bloom filter; technically, bloom filter is an array of bits, 3 bits per key; we can store it as MP_BIN

**Comment by rtsisyk** [comment]
- [ ] Check region_alloc() usage and add fiber_gc() to proper places
      (see e1b20ca5a60c08c47e68b8de9e86a19be5719e46 )
- [ ] Extract vy_stmt_encode()/vy_stmt_decode() functions
- [ ] Remove "series" from UPSERT and use the common format with WAL for
      upserts
- [ ] Report file names on error properly
       xlog_cursor_openfd(&itr->cursor, run->fd, "" <!-- filename);

**Comment by rtsisyk** [comment]
- [ ] Convert .index files to xlog format.

**Comment by rtsisyk** [comment]
# Vinyl meta format.

File name: <index_lsn>.<range_id>.<run id>.index
File format: tarantool xlog file
Xlog format type: INDEX (tuples are stored in .run files with RUN type)

A file for a run will contain one entry in _vinyl_run system space and an entry per every page of the run (space _vinyl_page).

Each run or page should have only one xlog entry in the file into its corresponding space.

## Run Information

Space name: _vinyl_run
Space id: 328 (not saved in snapshots, but reserved):

Run requests will be storead as 2-field tuple, first is the run identifier, second - map with run info. Run info map consists of min and max lsn and run page count.

Tuple fields:
* run_id: int64_t
* space_id: int32_t
* index_id: int32_t
* index_lsn: int64_t
* map:
  + VY_RUN_MIN_LSN = 1: int64_t
  + VY_RUN_MAX_LSN = 2: int64_t
  + VY_RUN_PAGE_COUNT = 3:  int64_t
  + VY_RANGE_MIN_KEY = 4: array
  + VY_RANGE_MAX_KEY = 5: array

## Page Index

Space name: _vinyl_index
Space id: 336 (not saved in snapshots, but reserved):

Page requests are stored as a 3-field tuple, first and second are the run
and page identifiers, three - map with page info. Page info map consists of
page file offset and page file size, page request count and page min key.

Tuple fields:
* run_id: int64_t
* page_offset: int64_t
* page_size: int64_t
* key/value map:
  + VY_PAGE_MIN_KEY = 1: array (tuple)
  + VY_PAGE_MAX_KEY = 2: array (tuple) - reserved for iterator optimization
  + VY_PAGE_MIN_LSN = 3: int64_t - this may speed up merges
  + VY_PAGE_MAX_LSN = 4: int64_t
  + VY_PAGE_UNPACKED_SIZE = 5: int64_t - uncompressed size of a page
  + VY_PAGE_REQUEST_COUNT = 6: uint32_t
  + VY_PAGE_BLOOMFILTER = 7: bin - RESERVED, bloom filter; technically, bloom filter is an array of bits, 3 bits per key; we can store it as MP_BIN

**Comment by rtsisyk** [comment]
Pushed.
