### ISSUE TITLE
CALL should leave Lua object on stack when parsing : (method invocation)

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#1721]
http://stackoverflow.com/questions/38900621/python-tarantool-call-parameters
complains that you can invoke an object method, but the object itself is not left on stack and is not passed in as the first argument.
box_lua_find should leave the object on the stack, so that 'call' is actually possible.

**Comment by bigbes** [comment]
Not a bug.
```
In [4]: connection.call('box.space.auth_user:auto_increment', [["8", 7, 7, 7]])
Out[4]:
- [1, '8', 7, 7, 7]
```
