### ISSUE TITLE
Vinyl: merge iterator can't merge more than two runs

### ISSUE THREAD

**Issue by GeorgyKirichenko** [tarantool/tarantool#1725]
Test-case:
box.cfg{}

s0 = box.schema.space.create('tweedledum', {engine = 'vinyl'})
i0 = s0:create_index('primary', {
	type = 'tree', parts = {1, 'unsigned'},
	unique = true })

-- integer keys
s0:replace{1, 'tuple'}
box.snapshot()
s0:replace{2, 'tuple 2'}
box.snapshot()

s0:insert{3, 'tuple 3'}
v1 = s0.index['primary']:get{1} or {'none'}
v2 = s0.index['primary']:get{2}
v3 = s0.index['primary']:get{3}

print(v1[1])
print(v2[1])
print(v3[1])

os.exit()

Often first `get' returns nil instead of inserted tuple.
I hope, that should be fixed by new iterator

**Comment by locker** [comment]
Temporary reopen - we need to add a test case for this issue.

**Comment by rtsisyk** [comment]
I added test case by 813d76791b7803524b3581bab12219cc16faf4b5
