### ISSUE TITLE
net.box connection index info indexes parts from 0

### ISSUE THREAD

**Issue by igorcoding** [tarantool/tarantool#1729]
Index parts in net.box connection should be numbered from 1 as in box.space[sp].index.[ind].parts.
Also index part types should be in lowercase probably.
In the following example net.box connection is established to the current node:
```
tarantool> c = require('net.box').new('127.0.0.1:3303')
tarantool> box.space.test.index.testi.parts
---
- - type: unsigned
    fieldno: 1
  - type: unsigned
    fieldno: 2
...
tarantool> c.space.test.index.testi.parts
---
- 0:
    type: UNSIGNED
    fieldno: 0
  1:
    type: UNSIGNED
    fieldno: 1
...
```

**Comment by rtsisyk** [comment]
@kostja breaking changes ought to be finished before beta. I suggest to move this task back to 1.7.2 list.
