### ISSUE TITLE
xlog size limits and xlog reopening

### ISSUE THREAD

**Issue by leksunin** [tarantool/tarantool#173]
Вводная:

а) Тарантул пишет xlog, который переоткрывает, когда количество записей в нем становится больше чем rows_per_wal.

б) Для удобства резервного копирования xlog'ов необходимо, что бы они были небольшого размер - порядка 100 мегабайт. Но т.к. размер записи в каждом инстансе тарантула свой, то что бы добиться xlog'а нужного размера надо вручную подбирать значение rows_per_wal.

Хочется:
а) что бы в тарантуле можно было задавать в конфиге размер xlog'а, после достижения которого, тарантул бы его переоткрывал

б) добавить в тарантул команду с админского порта - переоткрыть xlog

**Comment by rtsisyk** [comment]
rolling feature => 1.7.3
