### ISSUE TITLE
fiber.cond()

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#1731]
Implement new cond-like synchronization mechanism:

* `cond = fiber.cond()`
* `cond:wait(timeout)` - yields the current fiber to wait until another fiber invokes the `:signal()` or `broadcast()` method on the cond object
* `cond:signal()` - wakes up a single waiter
* `cond:broadcastl()` - wakes up all waiters

Needed for #799 #800 #1138

**Comment by mejedi** [comment]
eb1cebeb30
