### ISSUE TITLE
vinyl: re-add disk I/O statistics

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#1741]
The new read iterator vy @a_lyapunov doesn't maintain stat.read_disk. 
This needs to be fixed. Plus, the entire design of vy_stat_get() is clumsy and could be much streamlined.

**Comment by rtsisyk** [comment]
This bug is probably already fixed. @locker please re-check

**Comment by rtsisyk** [comment]
vinyl has been switch to xlog format. Please maintain I/O statistics in xlog cursor.

**Comment by rtsisyk** [comment]
Needed to test tuple-cache.

See also #31

**Comment by rtsisyk** [comment]
@alyapunov added `struct vy_iterator_stat` instead.
However, this ticket is still actual to debug vinyl on the production.

**Comment by kostja** [comment]
This is done by @locker already.
