### ISSUE TITLE
vinyl: truncate()/drop() space can crash under load

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#1742]
The following sequence of events is possible: 
- tx1 begins work with space t1
- tx1 issues a read, which yields on a disk read (this is vinyl-only today, since memtx reads don't yield)
- tx2 comes along, issuing drop of t1
- the drop succeeds before tx1 yield finishes
- index memory is gone, the read returns and corrupts the heap

How to reproduce/test: 
- add an error injection which calls fiber_sleep() into the read code (vy_index_read())
- start a test which continuously reads/drops an index in two fibers, a few hundred iterations
  should be enough.

How to fix:
- track objects used in a transaction within the transaction. On drop, simply mark
  an object as dropped. Collect the object in the engine when the last transaction
  using it commits.

**Comment by rtsisyk** [comment]
This complicated bug doesn't fit into 1.7.3 time frame, please consider to move to 1.7.4.

**Comment by rtsisyk** [comment]
1.7.4-473-ge3c5fde4b
