### ISSUE TITLE
vinyl: allow multiple shadow vy_mem indexes in vy_range 

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#1744]
```
struct PACKED vy_range {
	...
	struct vy_mem    i0, i1;
```

Currently vy_range can have only two memory indexes (i0 and i1). i0 is active and used for inserts, i1 is read-only and scheduled for dump. Please refactor code to have one active index (read-write) and multiple passive (read-only) indexes. This ticket is needed to #1735

**Comment by kostja** [comment]
This is done.
