### ISSUE TITLE
vinyl: vinyl/compact crashes

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#1758]
vinyl/compact.test.lua                                          [ fail ]

Test failed! Result content mismatch:
--- vinyl/compact.result Thu Sep  8 21:13:29 2016
+++ vinyl/compact.reject Fri Sep  9 16:50:07 2016
@@ -64,7 +64,7 @@
 ...
 vyinfo().run_count == 2
 ---
-- true
+- false
 ...
 -- wait for compaction
 while vyinfo().run_count >= 2 do fiber.sleep(0.1) end

**Comment by rtsisyk** [comment]
From #1761
```
+- error: './test_run.lua:174: Failed to seek log file: /... full path .../build/test/var/vinyl.log
+    : Invalid argument'
```

**Comment by rtsisyk** [comment]
I can't reproduce
```
vyinfo().run_count == 2

-- true
+- false
```
