### ISSUE TITLE
Duplicate key exists in unique index 'primary' in space '_index'

### ISSUE THREAD

**Issue by rybakit** [tarantool/tarantool#1760]
Running [tube:truncate()](https://github.com/tarantool/queue#driver-api) not always, but often results in a `Duplicate key exists in unique index 'primary' in space '_index'` error.

Tarantool & queue are installed with `docker build -t tarantool/tarantool github.com/tarantool/tarantool-docker#:1.7`.

**Comment by bigbes** [comment]
duplicate of https://github.com/tarantool/tarantool/issues/618
