### ISSUE TITLE
Tarantool doesn't listen to all interfaces

### ISSUE THREAD

**Issue by danikin** [tarantool/tarantool#1762]
Tarantool 1.7 listens only loopback by default. Tarantool 1.6 used to listens all the interfaces by default. I want either revert this behaviour back.

**Comment by rtsisyk** [comment]
It was changed intentionally. example.lua grants universe permissions to guest user and it is not safe to listen on external interfaces in this case.

See #1602

You can change  `listen = 'localhost:3301'` to `listen = '*:3301'`.

**Comment by kostja** [comment]
Dennis, we need to change your benchmark script. Better yet if you have your own .lua file which you use in the benchmark.
