### ISSUE TITLE
Add support for ASAN/UBSAN and friends

### ISSUE THREAD

**Issue by mejedi** [tarantool/tarantool#1765]
Address Sanitiser is a modern faster alternative to Valgrind. It's based on compiler instrumentation.

**Comment by mejedi** [comment]
Necessary changes committed to Tarantool LuaJIT mirror.

**Comment by mejedi** [comment]
ASAN comes in two parts — compiler support + a runtime library.

We need a modified runtime to properly handle Tarantool fibers. No need to build a patched compiler :)

Fiber support was introduced in https://reviews.llvm.org/D20913, successfully backported the patch to XCode 7.3.0 tree.

**Comment by racktear** [comment]
clang 3.9 release already includes support for fibers in address sanitizer

**Comment by rtsisyk** [comment]
Implemened (afd229393ecba61ce39e9c302fe3e7e7e0afa8c8)
