### ISSUE TITLE
Select statement with a composite key works incorrectly

### ISSUE THREAD

**Issue by sgnrslv** [tarantool/tarantool#1779]
Documentation [states](https://tarantool.org/doc/book/box/box_index.html?highlight=index#module-box.index) that formally the logic for TREE index searches is:

```
for i = 1 to number-of-parts-of-search-value
    if (search-value-part[i] is nil and <comparison-operator> is "=") or
       (search-value-part[i] <comparison-operator> index-key-part[i] is true) then
           comparison-result[i] is true
    endif
```

And if all comparison-results are true, then search-value "matches" index key.

But this doesn't correlate with results we get after the following steps (just a quick example):

```
box.schema.space.create('testme')
box.space.testme:create_index("primary", {unique = true, type = 'hash', parts = {1, 'unsigned'}})
box.space.testme:create_index("secondary", {unique = false, type = 'tree', parts = {2, 'unsigned', 3, 'unsigned'}})
for i = 1, 5, 1 do box.space.testme:insert{i, i, 5 - i} end

box.space.testme.index.secondary:select({4, 2}, {iterator = "LE"})

---
- - [4, 4, 1]
  - [3, 3, 2]
  - [2, 2, 3]
  - [1, 1, 4]
...
```

So, **comparison condition was not applied to the second part of the composite index**.

There are two unexpected tuples:

```
  - [2, 2, 3]
  - [1, 1, 4]
```

**Comment by bigbes** [comment]
@sgnrslv well, this rule simply applies to EQ, but not applies to LT/GT(E). If first part of key is suitable (lesser/greater respectively), than it's sufficient condition.

**Comment by sgnrslv** [comment]
@bigbes ok, got it.

**Comment by kostja** [comment]
@lenkis please move this to tarantool/doc

**Comment by lenkis** [comment]
To be tracked in doc repo.
