### ISSUE TITLE
vinyl: iterator created just after box.begin() doesn't see this transaction

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#1806]
`space = box.schema.space.create('test', { engine = 'vinyl' })`
`pk = space:create_index('primary')`
`idx2 = space:create_index('idx2', { parts = {2, 'unsigned'} })`
`idx3 = space:create_index('idx3', { parts = {3, 'integer'}, unique = false })`
`space:replace({1, 1, 1})`
`box.begin()`
`iter_obj = create_iterator(pk)`
`space:replace({2, 2, 2})`
`print_iterator(iter_obj)`
`box.commit()`
Output must be {1, 1, 1} and {2, 2, 2} but is {1, 1, 1}.

**Comment by rtsisyk** [comment]
@kostja could you please review this patch? Thanks.
