### ISSUE TITLE
1.7 regression: wrong processing schema_id in request/response

### ISSUE THREAD

**Issue by unera** [tarantool/tarantool#1808]
# 1.6

1. send ping (without `SCHEMA_ID`)
1. receive response with `SCHEMA_ID = X`
1. send ping with `SCHEMA_ID = X+1`
1. receive error response with `CODE = 0x806D` and `ERROR` contains schema error message

# 1.7

1. send ping (without `SCHEMA_ID`)
1. receive response with `SHCHEMA_ID = X`
1. send ping with `SCHEMA_ID = X+1`
1. receive response with `CODE = 0`, `SCHEMA_ID = X`, no errors

If You use `select` method instead `ping`, 1.7 returns properly error and code.

**Comment by unera** [comment]
The problem is present for methods

- ping
- call_lua

Methods works fine:

- select

The other methods are not tested.

**Comment by rtsisyk** [comment]
1.7.2-18-g38e8b2d
