### ISSUE TITLE
Automated QA with libfuzzer and ASAN from clang

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#1809]
libfuzzer uses code instrumentation to hit boundary cases in code.

**Comment by rtsisyk** [comment]
Requires ASAN support #1765

**Comment by ligurio** [comment]
v1 https://lists.tarantool.org/pipermail/tarantool-patches/2020-April/015347.html

**Comment by ligurio** [comment]
v1 https://lists.tarantool.org/pipermail/tarantool-patches/2020-April/015347.html
v2 https://lists.tarantool.org/pipermail/tarantool-patches/2020-April/016215.html

**Comment by ligurio** [comment]
https://google.github.io/oss-fuzz/getting-started/new-project-guide/
https://google.github.io/oss-fuzz/getting-started/continuous-integration/

**Comment by ligurio** [comment]
Patch to integrate with OSS Fuzz - https://github.com/google/oss-fuzz/pull/4723

**Comment by ligurio** [comment]
[Tarantool-patches] [PATCH 0/4] Add fuzzing testing
https://lists.tarantool.org/pipermail/tarantool-patches/2020-November/021003.html
