### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by vmakhaev** [tarantool/tarantool#1817]
Here are some memtx dumps:
https://www.dropbox.com/s/3ip29x8y79dt9qe/cores.tgz?dl=0

And one vinyl dump:
https://www.dropbox.com/s/n41tj7yye2iwiwi/vinyl.tgz?dl=0

I can not provide code, but issue is reproducible and likely caused by concurrent writes.
`version 1.7.2-1-g92ed6c4`

**Comment by rtsisyk** [comment]
Please try to upgrade to the latest 1.7.2
