### ISSUE TITLE
Connecting to tarantool server from mod_lua

### ISSUE THREAD

**Issue by soapdog** [tarantool/tarantool#1822]
Hi,

I am building a web application using Apache2 and mod_lua. I would love to connect to a tarantool db from it but I can't find an up to date connector for Lua. I have seen *tarantool-lua* but that is 3 years old and not working with the current dist.

Right now, I can't replace apache2/mod_lua with nginx. What can I do? Is there a connector for Lua like there is for the other languages?

Also, with mod_lua, I can't replace the interpreter being used with the tarantool bin.

Thanks in advance
andre

**Comment by bigbes** [comment]
Hello, Andre!

Right now we don't have Tarantool connector for lua language. But we have a couple of different things that may help you (but they all related to nginx and resty):

1) https://github.com/perusio/lua-resty-tarantool and https://github.com/ziontab/lua-nginx-tarantool . You may adapt one of this connectors for your application. (Any PR is much appreciated!)
2) You may use https://github.com/tarantool/nginx_upstream_module as proxy between Tarantool and you application, that will convert http queries to msgpack.
