### ISSUE TITLE
vinyl: write iterator DELETE pruning is incorrect.

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#1824]
The write iterator faithfully returns _all_ statements with lsn > oldest_vlsn. But if this is the last statement with lsn > oldest_vlsn, and it's a **DELETE**, and it's the last level, it should not be returned.

**Comment by alyapunov** [comment]
I disagree with "incorrect". It is correct but has simplified 
It should also remove DELETE that followed by another DELETE.
It also might completely replace UPSERT with REPLACE if that possible.
Each of these could be done but is not so simple - write iterator must look to future statements to decide whether the current statement must be output or not or how

**Comment by rtsisyk** [comment]
@Gerold103 @alyapunov please check that this problem still exists.

**Comment by rtsisyk** [comment]
Any news?

**Comment by Gerold103** [comment]
The ticket still is actual.

**Comment by rtsisyk** [comment]
OK

**Comment by rtsisyk** [comment]
Blocked by #2090

**Comment by rtsisyk** [comment]
Blocked by #2090

**Comment by Gerold103** [comment]
It seems to be fixed in the #1920 patch.
