### ISSUE TITLE
Allow tuple_upsert_execute() to process multiple UPSERTS at once

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#1832]
Add support for array of arrays of upsert operations in tuple_upsert_execute(). In other words, allow to pass vector of UPSERTS to process all them at once.

This change is needed to speed up UPSERT processing in Vinyl.

**Comment by rtsisyk** [comment]
This performance optimization is not critical for 1.7.3, moved to 1.7.4.

**Comment by kostja** [comment]
This change is no longer relevant, we squash upsert series into a single upsert, which then can be processed at once.
