### ISSUE TITLE
Search in https://tarantool.org/doc.html

### ISSUE THREAD

**Issue by alyapunov** [tarantool/tarantool#1836]
Again I tried to find something in our documentation and failed.
I thing there must be a search field at some highly visible place in the main doc page.
I want my usual case to be: I want revise box.update usage, I open "tarantool.org", click "Documentaion", enter text "update" to search field, press enter, click on proper search result, done.

**Comment by bigbes** [comment]
All documentation tickets are now part of `tarantool/doc` repository. And that's one is: tarantool/doc#85
