### ISSUE TITLE
Out of memory error is lost

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#1850]
How to repeat:
- run out of memory
- get "Failed to allocate X bytes" error on the next attempt to insert into space
- query box.error.last(): it returns NULL

Note: this is only repeatable from the interactive/remote console.

**Comment by rtsisyk** [comment]
I can't reporoduce this problem neither in a remote nor in a local console:

```
tarantool> for i=1,100000 do box.space.memtx:replace({i, string.rep('a', 5000)}) end
---
- error: Failed to allocate 5023 bytes in slab allocator for memtx_tuple
...

tarantool> box.error.last()
---
- Failed to allocate 5023 bytes in slab allocator for memtx_tuple
...
```

Did you have any background fibers?

**Comment by rtsisyk** [comment]
This bug doesn't have a reproducible test case. Please re-open if problem still exists.
