### ISSUE TITLE
Optimize say() macro to check log_level

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#1851]
```
#define say(level, format, ...) ({ _say(level, __FILE__, __LINE__, format, \
        ##__VA_ARGS__); })
#define say_debug(format, ...) say(S_DEBUG, NULL, format, ##__VA_ARGS__)
+               say_debug("optimize upsert fast: %s: %s", vy_range_str(range),
+                         vy_stmt_str(stmt, index->key_def));
```

say_debug() arguments are evaluated even if log_level > DEBUG.
I propose to add if (say_log_level_is_enabled(level))) to `({ _say(level, __FILE__, __LINE__, format, ##__VA_ARGS__); })`

**Comment by kostja** [comment]
* Roman Tsisyk <notifications@github.com> [16/10/18 15:05]:

I agree.

> ```
> #define say(level, format, ...) ({ _say(level, __FILE__, __LINE__, format, \
>         ##__VA_ARGS__); })
> #define say_debug(format, ...) say(S_DEBUG, NULL, format, ##__VA_ARGS__)
> +               say_debug("optimize upsert fast: %s: %s", vy_range_str(range),
> +                         vy_stmt_str(stmt, index->key_def));
> ```
> 
> say_debug() arguments are evaluated even if log_level > DEBUG.
> I propose to add if (say_log_level_is_enabled(S_DEBUG))) to `({ _say(level, __FILE__, __LINE__, format, ##__VA_ARGS__); })`

-- 
Konstantin Osipov, Moscow, Russia, +7 903 626 22 32
http://tarantool.org - www.twitter.com/kostja_osipov
