### ISSUE TITLE
Allow empty update operation in upsert

### ISSUE THREAD

**Issue by aensidhe** [tarantool/tarantool#1854]

**Comment by rtsisyk** [comment]
1.7.2-119-ga98e90b

**Comment by rtsisyk** [comment]
This problem is not fully fixed:

```
tarantool> for i=1,1000 do box.space.test:upsert({i}) end
---
- error: '[string "for i=1,1000 do box.space.test:upsert({i}) end"]:1: Usage index:upsert(tuple_key,
    ops)'
...
```

**Comment by kostja** [comment]
We need to update the docs when it's fixed, and explain why this is useful. Please open a ticket against the reference when this is closed.

**Comment by alyapunov** [comment]
The original task was to allow empty ops.
 Now I've allowed to omit ops at all in lua, but not in IPROTO.

**Comment by rtsisyk** [comment]
OK, pushed
