### ISSUE TITLE
vinyl: throttle tx thread if dump doesn't catch up

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#1862]
If transactions are committed to a vinyl database at a rate higher than the dump bandwidth, there will be long stalls, as demonstrated in #3603, because when the memory limit is hit, all transactions will have to wait until memory dump is complete, which may take seconds or even minutes. To avoid long stalls, we need to throttle transactions in advance so that the write rate never exceeds the dump bandwidth.

**Comment by locker** [comment]
todo: log whenever throttling is enabled

**Comment by rtsisyk** [comment]
Discussed yesterday. A patch is implemented, but we don't have a proper benchmark to ensure that throttling really works as expected.

**Comment by kostja** [comment]
Quota timeouts seems to cover this problem quite well for now. Moving to wish list to collect some customer stories first.

**Comment by locker** [comment]
Fixed by commit c0d8063b6a2d8141ca4064c2b76101fb28ea3479
