### ISSUE TITLE
Assign LSN in WAL and remove global struct recovery 

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#1865]
- [ ] Assign LSN in WAL thread 
- [ ] Remove global struct recovery
- [ ] Add replication_vclock for appliers to filter processed rows
- [ ] Patch wal_writer to support wal_mode == WAL_NONE
- [ ] Move txn_write_to_wal() logic to WAL writer
- [ ] Remove `wal == NULL` and `wal != NULL` checks
- [ ] Remove cluster_wait_for_id() - uneeded
- [ ] Remove cluster_clock() - unused

See cc8ac7edeefa012f3c6f234074564c021622341b

**Comment by rtsisyk** [comment]
Need review, remove-tx-vclock branch

**Comment by rtsisyk** [comment]
Complicated, but doesn't affect user visible behavior. Moved to 1.7.5

**Comment by rtsisyk** [comment]
Decided to go with the simple solution, moved back to 1.7.4

**Comment by kostja** [comment]
I pushed a series of patches which together close this bug.
