### ISSUE TITLE
Invoke function in Eval request

### ISSUE THREAD

**Issue by anton-putau** [tarantool/tarantool#1872]
I am trying to use [Eval request](https://tarantool.org/doc/dev_guide/internals_index.html?highlight=eval),

expression = "return function-name"
tuple = function params

Got exception `unsupported Lua type function` for Eval request.
I have used [this library](https://github.com/progaudi/tarantool-csharp/), and not tested with other clients.

Is it tarantool mistake or my incorrect params? Or it is client issue?
Thanks.

**Comment by rtsisyk** [comment]
Hi, 

please use CALL request to invoke Lua functions. 
`CALL("function", arg1, arg2)` is significantly more efficient than `EVAL("function(...)", arg1, arg2)`.

**Comment by anton-putau** [comment]
Thanks
