### ISSUE TITLE
Build fail with DCMAKE_BUILD_TYPE=Release

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#1874]
I have Ubuntu 14.04 with 4.7.3.
I have Tarantool 1.7, pulled from source today.
I execute these instructions:
cmake . -DCMAKE_BUILD_TYPE=Release
make

The make does not finish. It reaches the line
[ 51%] Building C object src/box/CMakeFiles/box.dir/vinyl.c.o
then cpu usage goes close to 99% according to top,
and nothing else occurs for several minutes.

With DCMAKE_BUILD_TYPE=Debug, there is no problem.

**Comment by rtsisyk** [comment]
Confirmed. I noticed this problem on Debian Wheezy on [Travis CI](https://travis-ci.org/tarantool/tarantool/jobs/170779653#L4270) couple days ago. It seems that vinyl.c is too large and buggy gcc can't process it properly.
I'll investigate possible options.

**Comment by rtsisyk** [comment]
Hi @pgulutzan, could you please re-try on the latest 1.7?
This problem has gone away for me, but I don't have good explanation for that. Probably it was fixed after gcc upgrade.

I also wonder do you have ccache enabled on your Ubuntu?

$ apt-cache policy ccache
$ whereis gcc
gcc: /usr/bin/gcc /usr/lib/gcc # original gcc

$ sudo apt-get install ccache
$ export PATH=/usr/lib/ccache/:$PATH # enable ccache
$ hash -r
$ whereis gcc
gcc: /usr/bin/gcc /usr/lib/gcc /usr/lib/ccache/gcc # gcc with enabled ccache

**Comment by pgulutzan** [comment]
The problem has gone away for me too. I have not recently upgraded gcc, it is still 4.7.3. I do not have ccache enabled on my Ubuntu machine.

**Comment by rtsisyk** [comment]
OK. We're splitting vinyl.c into multiple files to finally resolve this problem.

=> #1906
