### ISSUE TITLE
logger output changes after box.cfg{}

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#1888]
```
tarantool> log.info('hello')
tarantool: hello

---
...

tarantool> box.cfg{}
2016-11-02 09:37:11.043 [30206] main/101/interactive C> version 1.7.2-140-g8f7d929
2016-11-02 09:37:11.043 [30206] main/101/interactive C> log level 5
2016-11-02 09:37:11.043 [30206] main/101/interactive I> mapping 1073741824 bytes for tuple arena...
2016-11-02 09:37:11.091 [30206] main/101/interactive I> recovery start
2016-11-02 09:37:11.091 [30206] main/101/interactive I> recovering from `./00000000000000000000.snap'
2016-11-02 09:37:11.099 [30206] main/101/interactive I> ready to accept requests

---
...

tarantool> log.info('hello')
2016-11-02 09:37:12.380 [30206] main/101/interactive I> hello

---
...

```

logger is unusable without box.cfg({}).

**Comment by kostja** [comment]
* Roman Tsisyk <notifications@github.com> [16/11/02 10:13]:

This works as intended. 

> ```
> tarantool> log.info('hello')
> tarantool: hello
> ---
> ...
> 
> tarantool> box.cfg{}
> 2016-11-02 09:37:11.043 [30206] main/101/interactive C> version 1.7.2-140-g8f7d929
> 2016-11-02 09:37:11.043 [30206] main/101/interactive C> log level 5
> 2016-11-02 09:37:11.043 [30206] main/101/interactive I> mapping 1073741824 bytes for tuple arena...
> 2016-11-02 09:37:11.091 [30206] main/101/interactive I> recovery start
> 2016-11-02 09:37:11.091 [30206] main/101/interactive I> recovering from `./00000000000000000000.snap'
> 2016-11-02 09:37:11.099 [30206] main/101/interactive I> ready to accept requests
> ---
> ...
> 
> tarantool> log.info('hello')
> 2016-11-02 09:37:12.380 [30206] main/101/interactive I> hello
> ---
> ...
> 
> ```
> 
> logger is unusable without box.cfg({}).

-- 
Konstantin Osipov, Moscow, Russia, +7 903 626 22 32
http://tarantool.org - www.twitter.com/kostja_osipov

**Comment by rtsisyk** [comment]
I use 8-16 Tarantool instances as Lua interpreteres with "net.box" and "xlog" modules. I don't plan to store any data on these Tarantool and create data directories, but it would be nice to have working "log" module.

**Comment by kostja** [comment]
* Roman Tsisyk <notifications@github.com> [16/11/02 13:41]:
> I use 8-16 Tarantool instances as Lua interpreteres with
> "net.box" and "xlog" modules. I don't plan to store any data on
> these Tarantool and create data directories, but it would be
> nice to have working "log" module.

There is a separate ticket for this problem, about making 'logger'
separate from box.

-- 
Konstantin Osipov, Moscow, Russia, +7 903 626 22 32
http://tarantool.org - www.twitter.com/kostja_osipov

**Comment by rtsisyk** [comment]
OK, this ticket is a duplicate of #689
