### ISSUE TITLE
Getting rank for tuple in index

### ISSUE THREAD

**Issue by ivankosenko** [tarantool/tarantool#1894]
For some purposes (for example, the ratings table) it is necessary to find the number of tuples in a particular index. It would be nice to have a built-in method for this.

**Comment by rtsisyk** [comment]
> to find the number of tuples in a particular index

Do you mean index:count()?

I remember that initial request was to find the position in the tree index.

**Comment by ivankosenko** [comment]
sorry. it's my mistake. Of course, I mean the position of the element.

**Comment by mkostoevr** [comment]
Currently one can get the rank of the tuple using `count`: `index:count(tuple_key, {iterator = 'LT'})` (+1 if 1-based position required).

But this has a linear complexity, the index count will be optimized in the scope of #8204 (only for indexes with `fast_offset = true`).
