### ISSUE TITLE
WRONG behavior of index:get()

### ISSUE THREAD

**Issue by cyanide-burnout** [tarantool/tarantool#1895]
Actual behaviour:
```
arguments.slot })
---
- error: More than one tuple found by get()
...

unix/:/tmp/Registry.sock> box.space.ClusterMembers.index.Inbound:select({ arguments.destination, arguments.number, arguments.slot })
---
- []
...

```

Documentation says (https://tarantool.org/doc/book/box/box_space.html#box-space-get):
> Return:
> the tuple whose index key matches key, or null.

So expected behaviour should be nil and not error.

**Comment by rtsisyk** [comment]
index:get() only works will the full key on unique indexes. The error message is incorrect, see #1882
