### ISSUE TITLE
vinyl: no way to start tarantool with secondary indicies from snapshot

### ISSUE THREAD

**Issue by andrew-statsenko** [tarantool/tarantool#1899]
Database was created with code:

    local space = box.schema.create_space('hashdb', {engine='vinyl'})
    space:create_index('cloud', {unique = true, parts = {1, 'string'}})
    space:create_index('sha1',  {unique = true, parts = {2, 'string'}})
    space:create_index('md5',   {unique = true, parts = {3, 'string'}})

Some data was inserted. After box:snapshot() database not started with error message:

vinyl_space.cc:592 E> ER_UNSUPPORTED: Vinyl does not support altering not empty space

**Comment by funny-falcon** [comment]
What happens, if you add "if_not_exists" option to all those create_space and create_index?

**Comment by andrew-statsenko** [comment]
Code guarded via box.once()

```
local function bootstrap()

    local space = box.schema.create_space('hashdb', {engine='vinyl'})
    space:create_index('cloud', {unique = true, parts = {1, 'string'}})
    space:create_index('sha1',  {unique = true, parts = {2, 'string'}})
    space:create_index('md5',   {unique = true, parts = {3, 'string'}})
    box.schema.user.grant('guest', 'read,write,execute', 'universe')
end
-- for first run create a space and add set up grants
box.once('hashdb', bootstrap)
```

problem is deeper and @alyapunov knows the details. 

Hope, fix will be soon ;-)

**Comment by andrew-statsenko** [comment]
fixed, please merge into 1.7

**Comment by rtsisyk** [comment]
Please add good comments to VinylEngine::buildSecondaryKey() and VinylSpace::prepareAlterSpace() before closing this ticket.

**Comment by rtsisyk** [comment]
@andrew-statsenko I kept this ticket opened to add some good comments about this case to the source tree.
