### ISSUE TITLE
Inform users about status of throttling

### ISSUE THREAD

**Issue by aensidhe** [tarantool/tarantool#1905]
Tarantool can enable throttling for graceful degradation of performance. It will be very useful to operators to have:
- message in logs about start of throttling
- message in logs about end of throttling
- status in box.info.server about throttling status: enabled (how long, how much is delay if it can vary), disabled.

**Comment by rtsisyk** [comment]
Throttling is an experimental feature and it still hasn't merge into 1.7 yet (see #1862).
I definitely agree with all of you that it must be logged. We will take it into account in the new version of this patch. Please subscribe to #1862 for updates.
