### ISSUE TITLE
vinyl: optimize write iterator to squash writes of non-active transactions

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#1920]
Optimize write iterator to squash writes of non-active transactions (aka purge lsn becoming an array)

**Comment by rtsisyk** [comment]
=> 1.7.4

**Comment by Gerold103** [comment]
- It is proposed to return array of merged statements from vy_merge_iterator_squash_upsert instead of one by one. It allows to delete last_not_squashed parameter and optimize last level.
- Don't use this style:
```C
declare param = value;
if (condition)
    param = another_value;
```
Use:
```C
declare param;
if (condition)
    param = another_value;
else
    param = value;
```

**Comment by rtsisyk** [comment]
Blocked by #1920
