### ISSUE TITLE
Login/password disclosure when setting 'replication_source' option

### ISSUE THREAD

**Issue by viciious** [tarantool/tarantool#1924]
Found in tarantool log file:

> 2016-11-15 19:58:41.617 [11197] main/1253/etcd:66919ea9-913b-40c4-8d20- I> set 'replication_source' configuration option to ["loginxxxx:passxxxx@10.zzz.zzz.zzz:2641"]

When logging variables to a file, potentially sensitive bits of information should be stripped off.

**Comment by lomik** [comment]
Fix for 1.6 required

**Comment by rtsisyk** [comment]
> Fix for 1.6 required

OK

**Comment by viciious** [comment]
Yeah, forgot to mention that this bug affects Tarantool v1.6.8

**Comment by rtsisyk** [comment]
1.7.3-125-g932db5f52
