### ISSUE TITLE
Harmonize vinyl and memtx options

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#1927]
slab_alloc_arena sets memory limit for memtx; we need to move this to memtx configuration table.
memory_limit sets memory limit for vinyl; we need to use the same name for both variables
range_size in vinyl is in bytes; memory_limit is in gigabytes; we need to harmonize these

@rtsisyk's draft:

```
box.cfg{

    --
    -- Memtx
    --    
    memtx_dir  = <path>; -- box.cfg.snap_dir, keep alias until 2.0
    memtx_memory = <bytes>; -- box.cfg.slab_alloc_arena, keep alias until 2.0
    memtx_min_tuple_size = <bytes>; -- box.cfg.slab_alloc_minimal, keep alias until 2.0
    memtx_max_tuple_size = <bytes>; -- box.cfg.slab_alloc_maximal, keep alias until 2.0
    -- obsolete box.cfg.slab_alloc_factor, keep alias until 2.0

    --
    -- Vinyl
    --    
    vinyl_dir = <path>;  -- box.cfg.vinyl_dir, drop alias
    vinyl_memory = <bytes>; -- box.cfg.vinyl.memory_limit, drop alias
    vinyl_cache = <bytes>; -- box.cfg.vinyl.cache, drop alias
    vinyl_threads = <integer>; -- --box.cfg.vinyl.threads, drop alias
    vinyl_run_count_per_level = <number>;
    vinyl_run_size_ratio      = <ratio>;
    vinyl_range_size          = <bytes>;
    vinyl_page_size           = <bytes>;

    --
    -- Snapshot Daemon
    --
    checkpoint_count = <integer>; -- box.cfg.snapshot_count, keep alias until 2.0
    checkpoint_interval = <float>; -- box.cfg.snapshot_period, keep alias until 2.0

    --
    -- WAL
    --    
    wal_dir =  <path>; --  no changes
    wal_mode = "write|fsync|none"; -- no changes
    wal_max_size = <number>; -- a new option
    -- obsolete box.cfg.rows_per_wal
    wal_dir_rescan_delay = <interval>; -- no changes

    log = "syslog:identity=tarantool,facility=user"; --- box.cfg.logger, keep alias until 2.0
    log_nonblock; --- box.cfg.logger_nonblock, keep alias until 2.0
    log_level = "DEBUG|INFO|WARN|ERROR" -- keep 1|2|3|4|5|6|7 for compatibility

    --
    -- Replication
    --
    replication = {
            "uri";
            "uri";
            "uri";
    }; -- no changes
    replication = "uri"; -- no changes, keep box.cfg.replication_source alias until 2.0

    --
    -- Misc
    --
    force_recovery = <bool>; -- inverted version of box.cfg.panic_on_snap_error, keep alias until 2.0
    readahead = <bytes>; -- no changes
    read_only = <bool>; -- no changes
    hot_standby = <bool>; -- no changes
    background = <bool>; -- no changes
    coredump = <bool>; --  no changes
    pid_file = <path>; --  no changes
};

<bytes> is a non-negative integer (zero or a natural number)
```

Notes:

* panic_on_XXX_error were renamed to XXX_force_recovery.
  See https://dev.mysql.com/doc/refman/5.7/en/forcing-innodb-recovery.html 

* rows_per_wal renamed to to wal_max_size.
  See https://dev.mysql.com/doc/refman/5.7/en/replication-options-binary-log.html#sysvar_max_binlog_size

**Comment by rtsisyk** [comment]
See also #1840

**Comment by rtsisyk** [comment]
Discussed with @kostja.

1. Add box.cfg { memtx = { memory_limit = xxx } }

```
box.cfg { memtx = { memory_limit = xxx } }
```

2. Keep box.cfg { slab_alloc_arena } for compatibility.

**Comment by kostja** [comment]
* Roman Tsisyk <notifications@github.com> [16/12/09 15:30]:
> Discussed with @kostja.
> 
> 1. Add box.cfg { memtx = { memory_limit = xxx } }
> 
> ```
> box.cfg { memtx = { memory_limit = xxx } }
> ```

slab_alloc_factor, slab_alloc_minimal, slab_alloc_maximal are also
moved to memtx. 

> 2. Keep box.cfg { slab_alloc_arena } for compatibility.

-- 
Konstantin Osipov, Moscow, Russia, +7 903 626 22 32
http://tarantool.org - www.twitter.com/kostja_osipov

**Comment by rtsisyk** [comment]
An initial prototype is done. We need to collect feedback from the team and or users.

**Comment by rtsisyk** [comment]
gh-1927-memtx-memory-options:
```
box.cfg {
    memtx = {
        slab_alloc_minimal = bytes|500MB|500M|5GB|5G;
        slab_alloc_maximal = bytes|1M|1MB;
        slab_alloc_factor = 1.1;
   }
}
```

**Comment by unera** [comment]
<blockquote>

```lua
box.cfg{
    memtx = {
        dir = <path>; -- box.cfg.snap_dir
        memory = <bytes>; -- box.cfg.slab_alloc_arena
        ?? alloc_minimal = <bytes>; -- box.cfg.slab_alloc_minimal
        ?? alloc_maximal = <bytes>; -- box.cfg.slab_alloc_maximal
        snapshot_count = <integer>; -- box.cfg.snapshot_count;
        snapshot_period = <float>; -- box.cfg.snapshot_period;
        ?? panic_on_error = <bool>; -- box.cfg.panic_on_snap_error
    };
```

</blockquote>

Evil! hellish inferno!

Memtx is tarantool's mainstream, so it would be nice keep these options at root config hash.

Do not break backward compatibility!
it is a bad practice

**Comment by racktear** [comment]
Here's my raw feedback:

   - Memory specification is not clear. If memtx.slab_alloc_arena includes
     anything except actual data stored in spaces, then it needs further
     design consideration.
   - Units should be specified in configuration entry name. E.g.:
     - min_alloc_bytes
     - max_alloc_bytes
     - snapshot_period_seconds
   - It is not clear what wal.rows does. Probably better to rename to
     wal.max_row_count. The same goes about wal.size. Probably better
     to have wal.max_size_bytes
   - wal.rescan_delay is better read as wal.rescan_delay_seconds
   - dir in engine configuration will be more obvious either as data_dir
     or base_dir, depending on the behavior of wal_dir and snap_dir
     configuration variables. If they are relative to the engine's dir,
     then e.g. memtx.base_dir will be more obvious
   - logger.pipe will be more obvious if named logger.pipe_to_cmd
   - It is not clear now if options in logger are mutually exclusive. If
     it's possible to configure multiple loggers at the same time, it will
     be useful to be able to specify different logging levels for each logger.
     If not, an explicit logger.engine option is required, and other options
     should be prefixed by logging engine type. E.g. logger.pipe_cmd,
     logger.syslog_identity, logger.syslog_facility.

**Comment by rtsisyk** [comment]
Alternative proposal:

```
box.cfg{
    --
    -- Memtx
    --    
    memtx_snapshot_dir  = <path>; -- box.cfg.snap_dir, keep alias until 2.0
    memtx_snapshot_count = <integer>; -- box.cfg.snapshot_count, keep alias until 2.0
    memtx_snapshot_period = <float>; -- box.cfg.snapshot_period, keep alias until 2.0
    memtx_panic_on_snapshot_error = <bool>; -- box.cfg.panic_on_snap_error, keep alias until 2.0
    memtx_memory = <bytes>; -- box.cfg.slab_alloc_arena, keep alias until 2.0
    memtx_alloc_minimal = <bytes>; -- box.cfg.slab_alloc_minimal, keep alias until 2.0
    memtx_alloc_maximal = <bytes>; -- box.cfg.slab_alloc_maximal, keep alias until 2.0

    --
    -- Vinyl
    --    
    vinyl_dir = <path>;  -- box.cfg.vinyl_dir, drop alias
    vinyl_memory = <bytes>; -- box.cfg.vinyl.memory_limit, drop alias
    vinyl_cache = <bytes>; -- box.cfg.vinyl.cache, drop alias
    vinyl_threads = <integer>; -- --box.cfg.vinyl.threads, drop alias
    vinyl_panic_on_data_error = <bool>, a new option

    --
    -- WAL
    --    
    wal_dir =  <path>; --  no changes
    wal_mode = "write|fsync|none"; -- no changes
    rows_per_wal = <number>; -- no changes
    bytes_per_wal = <number>; -- a new option
    panic_on_wal_error = <bool>; -- no changes
   
    logger = "syslog:identity=tarantool,facility=user"; -- no changes
    logger_nonblock -- no changes
    log_level = 1|2|3|4|5|6|7; -- no changes

    --
    -- Replication
    --
    replication_source = {
            "uri";
            "uri";
            "uri";
    }; -- no changes
    replication_source = "uri"; -- no changes
    wal_dir_rescan_delay = <interval>; -- no changes

    --
    -- Misc
    --
    readahead = <bytes>; -- no changes
    read_only = <bool>; -- no changes
    hot_standby = <bool>; -- no changes
    background = <bool>; -- no changes
    coredump = <bool>; --  no changes
    pid_file = <path>; --  no changes
};

<bytes> is <number>|"500MB"|"500M"|"5GB"|"5G"
```

**Comment by rtsisyk** [comment]
>Memory specification is not clear. If memtx.slab_alloc_arena includes
anything except actual data stored in spaces, then it needs further
design consideration.

memtx.memory is overall limit both for indexes and data.

> Units should be specified in configuration entry name. E.g.:
    min_alloc_bytes
    max_alloc_bytes
    snapshot_period_seconds

> wal.rescan_delay is better read as wal.rescan_delay_seconds

Discussed => use bytes and seconds as units everywhere and don't add _suffixes.

> It is not clear what wal.rows does. Probably better to rename to
wal.max_row_count. The same goes about wal.size. Probably better
to have wal.max_size_bytes

I agree. I changed it to wal_max_size in the new version.

**Comment by rtsisyk** [comment]
> logger.pipe will be more obvious if named logger.pipe_to_cmd
It is not clear now if options in logger are mutually exclusive. If
it's possible to configure multiple loggers at the same time, it will
be useful to be able to specify different logging levels for each logger.
If not, an explicit logger.engine option is required, and other options
should be prefixed by logging engine type. E.g. logger.pipe_cmd,
logger.syslog_identity, logger.syslog_facility.

These part of initial proposal has been discarded.

**Comment by rtsisyk** [comment]
tarantool 1.7.3.351.gc386c19-1 from Debian package fails to start after this patch:

systemctl start tarantool@example:

```
tarantoolctl[19878]: Deprecated option logger, please use log instead
tarantoolctl[19878]: Configuration failed: Incorrect value for option 'logger': can not override a value for a deprecated opti
tarantoolctl[19878]: 2017-02-26 21:02:58.586 [1803] main/101/tarantoolctl I> mapping 536870912 bytes for tuple arena...
```

apt-cache policy  tarantool:
```
tarantool:
  Installed: 1.7.3.351.gc386c19-1
  Candidate: 1.7.3.351.gc386c19-1
  Version table:
 *** 1.7.3.351.gc386c19-1 990
        990 https://packagecloud.io/tarantool/1_7/debian stretch/main amd64 Packages
        100 /var/lib/dpkg/status
```

cat /etc/default/tarantool:
```
default_cfg = {
    pid_file   = "/var/run/tarantool", -- /var/run/tarantool/${INSTANCE}.pid
    wal_dir    = "/var/lib/tarantool", -- /var/lib/tarantool/${INSTANCE}/
    snap_dir   = "/var/lib/tarantool", -- /var/lib/tarantool/${INSTANCE}
    vinyl_dir = "/var/lib/tarantool", -- /var/lib/tarantool/${INSTANCE}
    logger     = "/var/log/tarantool", -- /var/log/tarantool/${INSTANCE}.log
    username   = "tarantool",
}
```

Please add a translation table to tarantoolctl.

**Comment by rtsisyk** [comment]
1.7.3-354-ge7550da
