### ISSUE TITLE
[uri]: doesn't parse urls with |

### ISSUE THREAD

**Issue by zloidemon** [tarantool/tarantool#1929]
URI module doesn't parse URL with symbol '|', although it is available in URL and work on http module.

```
tarantool> uri.parse('http://test.com/a?xxx=123&a|b')
---
- null
...
```

Example in python:
```
In [1]: from urlparse import urlparse

In [2]: urlparse('http://test.com/a?xxx=123&a|b')
Out[2]: ParseResult(scheme='http', netloc='test.com', path='/a', params='', query='xxx=123&a|b', fragment='')
```

Fixed in [commmit](https://github.com/tarantool/tarantool/commit/4b71c4dbc90b369ac48f1f7072fb2fe077fa10bai)

**Comment by rtsisyk** [comment]
Pushed via 1.6, thanks!
1.6.9-29-gddac212
1.7.2-224-g7030662
