### ISSUE TITLE
tarantool 1.6 не взлетает под нагрузкой

### ISSUE THREAD

**Issue by melyutin** [tarantool/tarantool#1932]
данные загружаются из снапшота, икслогов. коробка биндится на заданный порт (при этом индексы еще не построены) и сразу приходит нагрузка.

получаем в итоге
2016-11-18 19:02:12.178 [6222] iproto sio.cc:251 !> SystemError accept, called on fd 12, aka 0.0.0.0:10006: Too many open files
и последующее падение - кончились дискрипторы, админкую консоль поднять не получается

версия 1.6.8.580-1.el6

**Comment by rtsisyk** [comment]
Не очень понятно с чего вы взяли, что индексы еще не построены? Можно полный лог посмотреть плз?

**Comment by viciious** [comment]
Проблема, похоже, может быть в том, что сначала говорится box.cfg{listen=...}, и только потом читается схема. Тарантул биндится на порт и копит реквесты пока поднимает индексы. В качестве workaround можно попробовать отцепить box.cfg{listen=...} куда-нибудь в конец скрипта инициализации.

**Comment by viciious** [comment]
Да, вариант с отцеплением box.cfg{listen=...} от остальной части работает. По меньшей мере это контр-интуитивное поведение тарантула, а по большей - баг в полный рост.

**Comment by kostja** [comment]
* Victor Luchits <notifications@github.com> [16/12/15 12:27]:
> Да, вариант с отцеплением box.cfg{listen=...} от остальной части работает. По меньшей мере это контр-интуитивное поведение тарантула, а по большей - баг в полный рост.
> 

В 1.7 bind & listen будут разнесены, bind будет делаться до начала
recovery, а listen после окончания.

Проблема уйдёт.

В 1.6 проблема корнями уходит в режим hot standby, который
пытается делать recovery одновременно с попытками сделать bind &
listen на порт и перейти в режим мастера.

-- 
Konstantin Osipov, Moscow, Russia, +7 903 626 22 32
http://tarantool.org - www.twitter.com/kostja_osipov

**Comment by kostja** [comment]
Проблема исправлена в 1.7, мы сначала пытаемся сделать bind на порт, потом поднять снапшот и журналы, и только потом делаем listen.

**Comment by kostja** [comment]
The fix was backported to 1.6
