### ISSUE TITLE
console.lua leaks sockets 

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#1936]
Try writing a script which connects to console every second, checks status and disconnects. 
It will leak all file descriptors (Lua garbage collection?)

Reproducible in production only (garage).

Recording here for tracking purposes, as a placeholder for support incident.

**Comment by rtsisyk** [comment]
Did you try collectgarbage('collect') in Lua?

**Comment by kostja** [comment]
The whole thing happens only a few hours after restart. I guess we'll need to construct a stress test to reproduce the problem. I will also re-enable console on one of the masters  to see if the problem is still repeatable.

**Comment by kostja** [comment]
The key to reproducing this ticket is to have a lot of files in vinyl - many spaces and indexes is an easy way to achieve that. The key suspicion is Lua garbage collector, which doesn't collect file descriptors quickly enough, so vinyl starts running out of file descriptors.

**Comment by IlyaMarkovMipt** [comment]
Tried to run the described case. Mentioned bug was not reproduced.
[Scripts](https://gist.github.com/IlyaMarkovMipt/975d8e0bab7138f9e7a721e50ca45b00)

**Comment by kostja** [comment]
* Ilya Markov <notifications@github.com> [17/05/29 19:46]:
> Tried to run the described case. Mentioned bug was not reproduced.
> [Scripts](https://gist.github.com/IlyaMarkovMipt/975d8e0bab7138f9e7a721e50ca45b00)

Please try with low ulimit -n


-- 
Konstantin Osipov, Moscow, Russia, +7 903 626 22 32
http://tarantool.org - www.twitter.com/kostja_osipov

**Comment by IlyaMarkovMipt** [comment]
tried with new description of test
```
ulimit -n
255
```
[scripts](https://gist.github.com/IlyaMarkovMipt/975d8e0bab7138f9e7a721e50ca45b00)
Bug was not reproduced.

**Comment by rtsisyk** [comment]
We can't reproduce this bug.

server.lua:

```
-- ulimit -n
-- 255
console = require('console')
box.cfg{log="tarantool.log", work_dir="tnt"}
box.schema.user.grant('guest', 'read,write,execute', 'universe')

local NUMBER_SPACES = 200
local NUMBER_ELEMS = 500
for i = 1, NUMBER_SPACES do
	local space = box.schema.space.create('space' .. i, {if_not_exists=true, engine='vinyl'})
	local idx = space:create_index('primary',{parts = {1,'unsigned', 2, 'unsigned'}})
	for i = 1, NUMBER_ELEMS do
		space:replace{math.random(10000), math.random(10000)}
	end
	box.snapshot()
end
local CONSOLE_SOCKET = '/tmp/tarantool-test-console.sock'
os.remove(CONSOLE_SOCKET)
local server = console.listen(CONSOLE_SOCKET)
```

client.lua
```
local socket = require('socket')
local fiber = require('fiber')
local NUMBER_CONNS = 150

local CONSOLE_SOCKET = '/tmp/tarantool-test-console.sock'

for i = 1, NUMBER_CONNS  do
	fiber.sleep(0.01)
	local client = socket.tcp_connect("unix/", CONSOLE_SOCKET)
	local handshake = client:read{chunk = 128}
	client:write("box.info")
	client:close()
end
local client = socket.tcp_connect("unix/", CONSOLE_SOCKET)
local handshake = client:read{chunk = 128}
client:write("for i = 1, 200 do box.space[\"space\" .. i]:drop() end\n")
client:close()

os.exit(0)
```

**Comment by kostja** [comment]
Closing as can't repeat.
