### ISSUE TITLE
Please provide a package for Fedora 25

### ISSUE THREAD

**Issue by kmansoft** [tarantool/tarantool#1939]
Now that Fedora 25 is released, please provide a package at:

`http://download.tarantool.org/tarantool/1.6/fedora/$releasever/$basearch/`

where $releasever = 25

**Comment by rtsisyk** [comment]
I've just pushed a Docker Image with Fedora 25 to packpack (our build system):
https://hub.docker.com/r/packpack/packpack/builds/

**Comment by rtsisyk** [comment]
Tarantool 1.6.9 is on the way, see https://travis-ci.org/tarantool/tarantool/builds/178364889.
Tarantool 1.7.2 will be later after fixing builds of recently added Ubuntu Yakkety and Fedora 25.

**Comment by rtsisyk** [comment]
PackageCloud still doesn't support Fedora 25. I've sent a feature request.

**Comment by kmansoft** [comment]
The repo (1.6, Fedora 25, x86_64) is now available. Thank you. Looking forward to actual builds :)

**Comment by rtsisyk** [comment]
Tarantool 1.7 is already there: https://travis-ci.org/tarantool/tarantool/jobs/178566908#L3950

**Comment by rtsisyk** [comment]
- [x] https://github.com/tarantool/tarantool
- [ ] https://github.com/tarantool/queue
- [x] https://github.com/tarantool/http
- [ ] https://github.com/tarantool/expirationd
- [ ] https://github.com/tarantool/tarantool-python
- [ ] https://github.com/tarantool/small
- [ ] https://github.com/tarantool/msgpuck
- [ ] https://github.com/tarantool/memcached
- [ ] https://github.com/tarantool/connpool
- [ ] https://github.com/tarantool/shard
- [ ] https://github.com/tarantool/mqtt
- [ ] https://github.com/tarantool/migrate
- [ ] https://github.com/tarantool/curl
- [ ] https://github.com/tarantool/s3
- [ ] https://github.com/tarantool/tarantool-php
- [ ] https://github.com/tarantool/avro-schema
- [ ] https://github.com/tarantool/gis
- [ ] https://github.com/tarantool/gperftools
- [ ] https://github.com/tarantool/modulekit
- [ ] https://github.com/tarantool/luaossl
- [ ] https://github.com/tarantool/tarantool-c
- [ ] https://github.com/tarantool/pg
- [ ] https://github.com/tarantool/mysql

**Comment by rtsisyk** [comment]
Postponed

**Comment by rtsisyk** [comment]
I updated .travis.yml on all repos.
