### ISSUE TITLE
Equivalent of "show index" in 1.6

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#194]
I have Tarantool version 1.6 built from source today.
In 1.5 I can see `show index` to see number of keys and amount of memory used.
I do not see the same sort of thing in 1.6.

From emails between P. Gulutzan and K. Osipov in February 2014:
```
P. Gulutzan: For some "show" functions in 1.5 there's a vague equivalent in 1.6.
But not for "show index" (number of keys and amount of memory used).
Right?
K. Osipov:: I now see in the code that it's implemented but not bound to any
Lua call. Please file a bug.
```

**Comment by rtsisyk** [comment]
index:bsize()  (previously known as index:memsize()) is good enough for now.
Please close the ticket after adding this method to the documentation.
