### ISSUE TITLE
tarantool crashed

### ISSUE THREAD

**Issue by YarickR** [tarantool/tarantool#1942]
2016-11-24 04:47:07.153 [16651] wal/101/main I> creating `/var/lib/tarantool/paq003/00000000002125157303.xlog.inprogress'
Segmentation fault
Current time: 1479952030
Please file a bug at http://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed,
this may fail as well
#0  0x428fa1 in ?
#1  0x7f7a37e1de20 in ?

2016-10-26 18:36:02.006 [16651] main/101/tarantoolctl C> version 1.6.8-776-gd36ba27

**Comment by mejedi** [comment]
Could you please share a core dump?

**Comment by YarickR** [comment]
Nope, there wasn't one (ulimit -c 0; will provide it when it'll happen next
time)

**Comment by rtsisyk** [comment]
Hi, there is no enough information to debug this bug. Do you have a test case?
