### ISSUE TITLE
Conistently failing upsert squash can soar the cost of upsert to O(N^2) 

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#1947]
To see if we can squash two upserts together, we first parse the entire upsert statement, which is O(N upsert ops in the statement). If upsert squashing fails, we increase the number of ops in the statement, adding ops to the first upsert. This is O(N^2) from the number of upserts * number of ops in upsert. 

Find a way to see if squashing is not applicable without parsing the entire upsert (perhaps, begin by parsing the shorter upsert first, plus mark non-squashable upsert vy_stmt objects).

Also, please avoid counting upsert statements to check if squashing needs to take place: use O(logN) algorithm instead of O(N).

Without these two fixes the optimization could turn into a pessimization in some edge cases.

**Comment by rtsisyk** [comment]
The write iterator and point-lookup iterator already use the stack of UPSERT.
Only the read iterator remains, so this ticket is superseded by #1833.

**Comment by kostja** [comment]
Please read my comment in gh-1622 about this bug.
