### ISSUE TITLE
vinyl: a new chunked allocator for tuples

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#1949]
As part of #1908 we plan to use the common vy_stmt for all indexes of the space. This feature requires reference counters for vy_stmt, which are currently broken due to usage of region_alloc(). Please implement a replacement for region_alloc() which will be able to free memory by chunks based on the lsn:

```
/* Allocate @a size bytes */
void *
alloc(size_t size, int64_t lsn);

/* Free all allocated memory where lsn < min_lsn */
void *
truncate(int64_t min_lsn);
```

This allocator will be used as vy_index-wide level for all ranges and all mems. `alloc()` function will be called  from vy_range_set() as usual. `truncate()` function will be called on completion of a dump or compaction with the value of vy_index->min_mem_lsn (see #1948).

**Comment by Gerold103** [comment]
- [ ] Implement chunked allocator
- [ ] Use chunked allocator per range
- [ ] Use chunked allocator per index
