### ISSUE TITLE
make box.cfg{repilcation_source=} non-blocking when called second time

### ISSUE THREAD

**Issue by unera** [tarantool/tarantool#1956]
Thanks for closing #1511 :)

But `async replication` means that data can be received with lag.

There are no different between 0.1 second lag and 3601 second lag (server was down).

So If an instance **has initialized database** it should enter RW-mode even if `replication_source` is/are not available (or begin unavailable).

**Comment by vtolstov** [comment]
Any news ? I'm use 1.7.3.227.g870e8d7-1 and need to start tarantool with empty replication_source, and after add some nodes - restart original server.

**Comment by kostja** [comment]
You can do it. This ticket is not relevant to what you're trying to do. Let's discuss in the community channel!

**Comment by vtolstov** [comment]
thanks, my issue now: #2079 and #723

**Comment by kostja** [comment]
gh-2079 is high-prio, we'll do it in 1.7.4 as you can see. for gh-723, could you send us a patch? and anyway, this is not relevant to this ticket, please use the telegram chat :)

**Comment by kostja** [comment]
One option re this ticket is to make box.cfg{repilcation_source=} non-blocking when called second time.

**Comment by rtsisyk** [comment]
Superseded by #2958
