### ISSUE TITLE
returns incorrectly value IPROTO_SCHEMA_ID  from LUA_CALL

### ISSUE THREAD

**Issue by unera** [tarantool/tarantool#1959]
If a lua call does something with tarantool's schema, its response contains incorrect SCHEMA_ID:

```lua

#!/usr/bin/env tarantool

local test = require('tap').test()
local nbox = require 'net.box'


box.cfg{ listen = 1234, logger = '/dev/null' }

box.schema.user.create('test', { password = 'test', if_not_exists = true })
box.schema.user.grant('test',
    'read,write,execute', 'universe', nil, { if_not_exists = true })


function blah(space)
    box.schema.space.create(space)
    return true
end

function bleh()
    return true
end

if box.space.test_space then
    box.space.test_space:drop()
end

test:plan(6)

local remote = nbox.new('test:test@localhost:1234')
test:ok(remote:ping(), 'ping')
local sid = remote._schema_id
test:ok(remote:call('blah', 'test_space'), 'create space')
test:isnt(remote._schema_id, sid, 'schema id was returned actual value')

test:ok(remote:call('bleh'), 'push schema events')
test:isnt(remote._schema_id, sid, 'schema id was returned actual value')
test:ok(remote.space.test_space, 'schema was reloaded')

os.exit(test:check() == true and 0 or -1)

```

**Comment by rtsisyk** [comment]
@unera schema_id is updated only on the next request. I can confirm this problem.
Unfortunately, there is no simple fix for this problem, so we decided to move this ticket to 1.7.4. Sorry.

**Comment by rtsisyk** [comment]
@unera We've pushed a fix. Now net.box will start to load a new version of schema **just after** receiving some response with a new schema_id.  All subsequent requests will be blocked waiting for the new schema. In other words, we eliminated an extra road-trip between the client and the server for your case. 

However, conn._schema_id variable is updated only after actual schema has been loaded. It's an internal variable, please don't rely on it in your tests.
