### ISSUE TITLE
test-run: implement a check that a test case leaves the database in clean state

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#1961]
We often have test run failures because developers forget to clean up after a test.
test-run should check for it and report errors when running the test.

The check should include:
- spaces
- users,
- grants

**Comment by Totktonada** [comment]
@bigbes provided the initial example how to achieve this: [1].

[1]: https://gist.github.com/bigbes/47e9e5c5cfb9245dbda94fd0d6c3ed11

**Comment by Totktonada** [comment]
Related: https://github.com/tarantool/test-run/commit/a50b0b5376188c6bce65a84620d20b2540408a5a

**Comment by Totktonada** [comment]
I propose to perform the clean up from test-run instead of pushing a developer to doing all needed cleanup manually in the end of each test.

**Comment by sergw** [comment]
Also will be cleaned up:
- functions
- globals
- package.loaded
