### ISSUE TITLE
Inconsistent behaviour of tonumber64 and tonumber

### ISSUE THREAD

**Issue by bigbes** [tarantool/tarantool#1963]
1) BUG: on bad numbers `tonumber64` returns part of it (behaviour of `strtoull`), but `tonumber` returns `nil`
    ```
    tarantool> tonumber('100o100')
    ---
    - null
    ...

    tarantool> tonumber64('100o100')
    ---
    - 100
    ...
    ```
2) FEATURE: second argument of `tonumber` is number's base (default is 10)
3) FEATURE: `tonumber` support other bases ('0x..', '0b...')
    ```
    tarantool> tonumber('0b1100')
    ---
    - 12
    ...
    tarantool> tonumber('0x1100')
    ---
    - 4352
    ...
    ```

**Comment by rtsisyk** [comment]
1. There is a bug in a condition:

https://github.com/tarantool/tarantool/blob/566842f01a8e434362f8c89ba9ba54ff09d25571/src/lua/init.c#L170

2. strtoull also supports "base":

https://github.com/tarantool/tarantool/blob/566842f01a8e434362f8c89ba9ba54ff09d25571/src/lua/init.c#L169

3. It is easy to check for "0b" and "0x"

**Comment by rtsisyk** [comment]
Some more test cases by @pgulutzan:

```
>tarantool> tonumber(20,36)
>---
>- 72
>...
>
>tarantool> tonumber64(20,36)
>---
>- 36
>...
>"
>
>Example #2:
>"
>tarantool> tonumber('-43')
>---
>- -43
>...
>
>tarantool> tonumber64('-43')
>---
>- 18446744073709551573
>...
>"
>
>Example #3:
>"
>tarantool> tonumber("")
>---
>- null
>...
>
>tarantool> tonumber64("")
>---
>- 0
>...
```

**Comment by rtsisyk** [comment]
```
$ lua5.1
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio
> =tonumber(10, 2)
2
>
$ lua5.3
Lua 5.3.3  Copyright (C) 1994-2016 Lua.org, PUC-Rio
> tonumber(10, 2)
stdin:1: bad argument #1 to 'tonumber' (string expected, got number)
stack traceback:
        [C]: in function 'tonumber'
        stdin:1: in main chunk
        [C]: in ?
> ^C
```

I don't care about this case anymore.  Let's add "string expected, got number" to finally close this ticket.
