### ISSUE TITLE
Email notifications for commits

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#1965]
Please enable the notification daemon which sends emails to "commits@" for all our GitHub repos. Thanks.

- [x] https://github.com/tarantool/tarantool
- [x] https://github.com/tarantool/queue
- [x] https://github.com/tarantool/http
- [x] https://github.com/tarantool/expirationd
- [x] https://github.com/tarantool/tarantool-python
- [x] https://github.com/tarantool/small
- [x] https://github.com/tarantool/msgpuck
- [x] https://github.com/tarantool/memcached
- [x] https://github.com/tarantool/connpool
- [x] https://github.com/tarantool/shard
- [x] https://github.com/tarantool/mqtt
- [x] https://github.com/tarantool/migrate
- [x] https://github.com/tarantool/curl
- [x] https://github.com/tarantool/s3
- [x] https://github.com/tarantool/tarantool-php
- [x] https://github.com/tarantool/avro-schema
- [x] https://github.com/tarantool/gis
- [x] https://github.com/tarantool/gperftools
- [x] https://github.com/tarantool/modulekit
- [x] https://github.com/tarantool/luaossl
- [x] https://github.com/tarantool/tarantool-c
- [x] https://github.com/tarantool/pg
- [x] https://github.com/tarantool/mysql

**Comment by racktear** [comment]
I will do it. But going further, you can add it for new repos like this:

* Go to repo Settings -> Webhooks
* Click "Add a new webhook"
* Set payload URL to `http://farm.tarantool.org:8083/hooks`
* Set content-type to `application/json`
* Set events to `just push event`
* Leave "active" checked

That's it. There is no need to reconfigure the daemon itself.
