### ISSUE TITLE
DDL is broken if invoked from on_replace() triggers

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#1968]
Cover all DDL functions in triggers:
* create/drop space, index, function, user, role
* grant/revoke privilege, role
* alter space, index
* two DDL statements in a row

There are many reasons for DDL in on_replace triggers to be broken:
* DDL effects become permanent on_commit only
* the space cache is not versioning, so pushing anything into a space cache potentially makes things visible to other transactions during a yield; not a problem if we do cascading rollback, though, but this needs to be covered with tests.

See a test case in #588

**Comment by rtsisyk** [comment]
See also #588

**Comment by rtsisyk** [comment]
1.7.4-348-g87fb9470d
