### ISSUE TITLE
Build freezes at 100% on Alpine Edge

### ISSUE THREAD

**Issue by AlexMasterov** [tarantool/tarantool#1969]
Alpine 3.4 works fine, but 3.5 release is coming soon. Tried "edge"..

[gcc 6.2.1-r1](https://pkgs.alpinelinux.org/package/edge/main/x86_64/gcc)
[cmake 3.6.2-r0](https://pkgs.alpinelinux.org/package/edge/main/x86_64/cmake)

Git tag, jobs number, AVX support, libressl-dev/openssl-dev, doesn't matter.

[Dockerfile](https://gist.github.com/AlexMasterov/3bb15af64cd04cb33d6d67a486f77e5a#file-dockerfile)
[Build.log](https://gist.github.com/AlexMasterov/3bb15af64cd04cb33d6d67a486f77e5a#file-build-log)

**Comment by rtsisyk** [comment]
Hi, I don't see any error messages in your build.log. I'll re-test your Dockerfile soon.

**Comment by rtsisyk** [comment]
I waited a minute after 100% and cmake has successful finished:

```
docker run -t -i gh-1969 /bin/sh
/ # tarantool
tarantool: version 1.7.2-314-gedffdc00e
type 'help' for interactive help
```

This freeze is probably caused by #1968

**Comment by AlexMasterov** [comment]
@rtsisyk I'm not so lucky. I have a perma-freeze.

**Comment by AlexMasterov** [comment]
@rtsisyk how can I debug this?

**top**
```sh
  PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
 2288  2285 root     D    3221m 159%   0   1% /usr/libexec/gcc/x86_64-alpine-linux-musl/6.2.1/cc1 -quiet -I /tmp/tarantool/src -I /tmp/tarantool/src/l
 2285  2284 root     S     1692   0%   0   0% /usr/bin/cc -DCORO_ASM -DNDEBUG -DNVALGRIND -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -D__STDC_CONSTANT_MACRO
 5491     0 root     S     1540   0%   2   0% sh
    1     0 root     S     1536   0%   6   0% /bin/sh -c apk add --update --virtual .tarantool-build-dependencies     cmake     curl     g++     gcc
 5498  5491 root     R     1532   0%   2   0% top
 2284  2277 root     S     1532   0%   0   0% /bin/sh -c cd /tmp/tarantool/test/unit && /usr/bin/cc  -DCORO_ASM -DNDEBUG -DNVALGRIND -D_FILE_OFFSET_BI
 1704  1701 root     S     1496   0%   2   0% make -f CMakeFiles/Makefile2 all
 1701     1 root     S     1216   0%   0   0% make -j 8
 2277  1704 root     S     1112   0%   6   0% make -f test/unit/CMakeFiles/msgpack.test.dir/build.make test/unit/CMakeFiles/msgpack.test.dir/build
```

**Comment by rtsisyk** [comment]
> [100%] Built target tarantool
cc: internal compiler error: Killed (program cc1)
Please submit a full bug report,
with preprocessed source if appropriate.

Probably gcc was killed by OOM killer. Please try to increase the available RAM or enable swap space.

**Comment by AlexMasterov** [comment]
@rtsisyk The problem was solved. Thanks!
