### ISSUE TITLE
Email notifications for the same pull request are sent multiple times

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#1971]
Hi,

I see the following messages every time I push to 1.7 branch:

[commits] [tarantool] 01/01: Merge 9cfa351c88229e3763824fe93a51b7091ec58774 into b39c857df79e1fc297b09b97a2b1df274ef74929
[commits] [tarantool] reference refs/pull/1933/merge updated (c6d19ab -> 58daa40)

This pull request is already pushed. Please fix email daemon to handle pull requests propely.

**Comment by racktear** [comment]
Does it behave this way for all pull requests or only for this one?
Were there any problems with the old notification daemon? Because they both use the same tool/algorightm.

**Comment by bigbes** [comment]
> Were there any problems with the old notification daemon? Because they
both use the same tool/algorightm.
Yes, they were.

@rtsisyk why can't you simply ignore it?

With best regards, Eugene.

2016-12-06 0:04 GMT+03:00 Konstantin Nazarov <notifications@github.com>:

**Comment by kostja** [comment]
I don't think this should still bother us.
