### ISSUE TITLE
Retry connections to master if we have wrong cluster id

### ISSUE THREAD

**Issue by racktear** [tarantool/tarantool#1981]
In a master-slave or master-master scenarios, replicas should retry connecting to master indefinitely, when they get wrong cluster id.

Currently if slave gets wrong cluster id, the only way to make it sync is either update replication source, or restart tarantool.

I need it for convenient recovery from backups in tarantool cloud.

**Comment by rtsisyk** [comment]
We discussed this feature with @GeorgyKirichenko today and realized that it can't be implemented easily in the current replication architecture. Tarantool creates a hashmap of replicas on box.cfg() using `replica_uuid` from greeting. Received UUID is used as a primary key to identify replicas in the replicaset, so it can't be changed without reconstructing replicaset by box.cfg().
