### ISSUE TITLE
Display status of recovery in box.info

### ISSUE THREAD

**Issue by racktear** [tarantool/tarantool#1984]
It will be extremely useful for automation tools to know the status of recovery from xlog/snap.

There should either be a counter in %-s, or (better) the currently replayed lsn and the target lsn to recover to.

**Comment by rtsisyk** [comment]
How is it supposed to work? box.info.WHAT? Please elaborate your proposal.

**Comment by kostja** [comment]
Use box.info.status, it's the status of recovery exactly.
