### ISSUE TITLE
console.print()

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#1986]
Many users want to be able to print directly into the screen of a remote console. They don't realize that print() goes to server stdout. 

Implement console.print() which prints to the socket of the currently connected console.

**Comment by lenkis** [comment]
We also need this for documentation. We often use print() in examples, but these examples don't work in docker. Users get frustrated:

Andrey Oleynik, [18 Apr 2017, 18:39 (18/04/2017, 18:39)]: 
А почему print не работает в интерактивной консольке, а в документации примеры с принтом?

Konstantin Osipov, [18 Apr 2017, 18:40]: 
где в документации примеры с принтом

print печатает в stdout

Andrey Oleynik, [18 Apr 2017, 18:41]: 
https://tarantool.org/doc/1.7/book/box/box_index.html#box-index-index-pairs

После First Example of index pairs():

Konstantin Osipov, [18 Apr 2017, 18:42]: 
@lenkis открой тикет плиз на переделку

print печатает в stdout

если вы работаетете  с тарантулом в докере, как в случае с try, то stdout у него в /var/log/tarantool

**Comment by rtsisyk** [comment]
IMHO, the most users will continue to call `print()` instead of  `console.print()` and see nothing. Shall we override `print()` instead? How to keep it compatible with PUC-Rio Lua.

**Comment by kostja** [comment]
Let's make sure the manual examples can be copy-pasted, and worry about abuse of print() separately.

**Comment by bigbes** [comment]
Maybe it's better to replace prints with aggregation and return?

**Comment by kostja** [comment]
When we implement https://github.com/tarantool/tarantool/issues/2677 this will become possible.

**Comment by Mons** [comment]
I propose the following:
1. override _G.print
2. print always is written to log
3. every print **duplicate** information to every connected console

**Comment by kostja** [comment]
Use box.session.push() and it will print to the text console in all cases.
