### ISSUE TITLE
Display info about vinyl background workers

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#1987]
We need more insight into what vinyl background workers are doing:
- upsert squash fiber - it should account squashed upserts in box.stat
- the scheduler fiber should issue informational messages for dumps and compactions
- log all errors in the background fibers in the error log
- log status of vinyl snapshot - there is an illusion that snapshot is complete when memtx snapshot is complete

**Comment by rtsisyk** [comment]
Implemented.
