### ISSUE TITLE
Do not perform double look up in the mem for each upsert

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#1988]
We invoke mem tree look up twice when inserting an upsert, since we always insert it twice.
Instead, we should insert UPSERT statement, then use its insert position as a hint to search the previous lsn in the tree, and optimize it later. An upsert-heavy workload using 6% of CPU for vy_mem_older_lsn() today.

**Comment by rtsisyk** [comment]
This ticket is not actual after #1842.

**Comment by Gerold103** [comment]
The ticket is still actual.

**Comment by Gerold103** [comment]
Blocked by #2492

**Comment by Gerold103** [comment]
Ticket is 100% not actual. See https://github.com/tarantool/tarantool/blob/084163c3713f065e51a1cb54ff52f748710ab033/src/box/vinyl.c#L3926
On the moment of the ticket creation the insertion of a new statement and upserts squashing were in the one function: `vy_range_set_upsert`, which was called on commit. But now insertion in a mem is doing in `vy_prepare` and optimization in `vy_commit`, between which the log write is executed.
We could save the insert position in `prepare`, but it is invalidating after the next insert before `vy_prepare`.

**Comment by kostja** [comment]
The fact that the code is not the same as before doesn't mean the problem is solved.
It's not. 
There are two lookups in the tree for each upsert. 
If you don't know how to fix this, then perhaps find another project to contribute to?

**Comment by Gerold103** [comment]
@kostja means, that we can use n_upserts to check, if there is a sense to optimize upsert.
