### ISSUE TITLE
nils in tuple cauzes "error: Tuple/Key must be MsgPack array"

### ISSUE THREAD

**Issue by Igorjan94** [tarantool/tarantool#1990]
Tarantool 1.7.2-1-g92ed6c4 (Lua console):

Test = box.schema.space.create('Tester')
Test:create_index('primary', {type = 'tree', parts = {1, 'unsigned'}})
Test:auto_increment{1, 1}
-- [1, 1, 1]
Test:auto_increment{1, nil, 1}
-- [2, 1, 1] --<b>O_O</b><--------------------------------------------------
Test:auto_increment{1, nil, nil, 1}
-- [3, 1, null, null, 1]
Test:auto_increment{1, nil, nil, nil, nil, nil, nil, nil, 1}
...
-- [8, 1, null, null, null, null, null, null, null, 1]
Test:auto_increment{1, nil, nil, nil, nil, nil, nil, nil, nil, 1}
-- error: Tuple/Key must be MsgPack array --<b>O_O</b><--------------------------------------------------

If I use insert instead of auto_increment, count of nils changes, but error is the same.
In 1.6.8 versions count of inserted nils doesn't depend on count of nils I insert

Is it undocumented feature or I didn't find it in documentation?)

**Comment by bigbes** [comment]
http://lua-users.org/wiki/StoringNilsInTables

Use msgpack.NULL/json.NULL/yaml.NULL to store `nil` in tables.

Opened ticket for documentation: https://github.com/tarantool/doc/issues/64

**Comment by bigbes** [comment]
Also,
```
Test:auto_increment{1, nil, nil, nil, nil, nil, nil, nil, nil, 1}
-- error: Tuple/Key must be MsgPack array --O_O<--------------------------------------------------
```

it becames not an array table, but map table and Tarantool thinks that it's map `{[1] = 1, [10] = 1}`

**Comment by Igorjan94** [comment]
box.space.Test:auto_increment({[1] = 1, [10] = 1})
-- [4, 10, null, null, null, null, null, null, null, 19]
box.space.Test:auto_increment({[1] = 1, [11] = 1})
-- error: Tuple/Key must be MsgPack array

But problem is solved with msgpack.NULL
