### ISSUE TITLE
Whether to use prefixes for luarock naming

### ISSUE THREAD

**Issue by racktear** [tarantool/tarantool#1995]
There are 2 options for naming luarocks:
1. `<packagename>`
2. `tarantool-<packagename>`

I see the 2-nd as beneficial because:
1. Luarocks packages are named the same way as the OS packages
2. We don't conflict with existing packages in luarocks

Benefit 2 is especially important, since soon we will install our luarocks in the common lua dir instead of our own. Example of package we will overwrite on users' machines: https://github.com/daurnimator/lua-http

**Comment by racktear** [comment]
I need a decision to go on with working on LuaRocks. I'm bringing up this because of recent patches to mysql and curl rocks.

**Comment by kostja** [comment]
Many Lua packages are broken when used with Tarantool, since they use blocking IO, http is one such example. 

We don't have to install our packages to Lua path, we can extend package search paths with our own (and we do already, I believe).

Hence, use unprefixed names. 

PS A history lesson - we used to have prefixed names. And it was a pain.

**Comment by racktear** [comment]
@kostja if we do install luarocks to our own path, then luarocks will be unable to remove our packages. You have shown the related ticket in tarantool/curl a few days ago.

**Comment by kostja** [comment]
This can be fixed in luarocks upstream. @hishamhm is open to extending luarocks to support various Lua distributions.

**Comment by hishamhm** [comment]
It's a matter of having your own tarantool manifest in luarocks.org, and confoguring your luarocks client so that the tarantool manifest takes precedence over the root one

**Comment by racktear** [comment]
@hishamhm thanks for suggestion. I'll try it out.

**Comment by rtsisyk** [comment]
Some of our module names are already cybersquattered. See "http" or "socket" for example.

**Comment by hishamhm** [comment]
not in the `tarantool` manifest, right?
