### ISSUE TITLE
Avoid duplication of records in a history of console commands

### ISSUE THREAD

**Issue by R-omk** [tarantool/tarantool#1999]
It is necessary to make a behavior like in the bash history.

**Comment by R-omk** [comment]
Also do not save empty string (press enter key) into history

**Comment by ligurio** [comment]
Looks like it was fixed in #2938, 7906e40839ec166f1df6532f0324b488e406deb6

https://github.com/tarantool/tarantool/blob/master/src/box/lua/console.c#L392

@Totktonada, could you confirm?

**Comment by Totktonada** [comment]
Looks so. I don't remember such behaviour in any more or less recent tarantool versions.
