### ISSUE TITLE
relay: xlog wasn't correctly closed on start

### ISSUE THREAD

**Issue by lomik** [tarantool/tarantool#2011]
Тарантул (с мастер-мастер репликацией) каждый раз на рестарте пишет в лог:
2016-12-27 15:20:06.612 [29728] relay/xxx.xxx.xxx.xxx:54066/101/main recovery.cc:211 W> file /data/xlogs65/00000000000286994104.xlog wasn't correctly closed

При этом ругается он на лог, который только что создал при старте. Версия tarantool-1.6.8.653-1.el7.centos.x86_64

**Comment by kostja** [comment]
The message is coming from the relay thread trying to read an empty xlog and relay it to the master. Should be simply suppressed.

**Comment by rtsisyk** [comment]
Please re-open if you need additional help.
