### ISSUE TITLE
tuple_extract_key works in O(n^2), but can be implemented in O(n)

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#2012]
Now `tuple_extract_key` calls `tuple_extract_key_raw` that iterates over a raw MessagePack array of tuple fields via `mp_next` and builds a new MessagePack array with key fields from the specified `key_def`. Since `key_def->parts` can be unordered, the key building works in `O(n^2)`.

My and @mejedi proposal is to use in `tuple_extrace_key` the array of key field offsets from struct tuple. This allows to build the key in O(n).

**Comment by rtsisyk** [comment]
Great proposal! I'm moving this ticket to 1.7.4.
