### ISSUE TITLE
vinyl: add quota timeout

### ISSUE THREAD

**Issue by locker** [tarantool/tarantool#2014]
Currently, when we run out of available quota, we throttle all pending write requests until we reclaim enough memory by dumping data stored in there to disk. As this may take quite a while or even get stuck due to write errors, we need to introduce a timeout after which throttled requests will be cancelled.

**Comment by rtsisyk** [comment]
Pushed 70a610d1d267344f45f765e3078eb004522204e2

**Comment by rtsisyk** [comment]
```
vinyl/quota_timeout.test.lua                                    [ fail ]

Test failed! Result content mismatch:

--- vinyl/quota_timeout.result	Thu May 18 12:31:26 2017

+++ vinyl/quota_timeout.reject	Thu May 18 12:36:26 2017

@@ -40,7 +40,6 @@

 -- and dump is disabled, it should fail with ER_VY_QUOTA_TIMEOUT.

 _ = s:auto_increment{pad}

 ---

-- error: Timed out waiting for Vinyl memory quota

 ...
 box.info.vinyl().memory.used
 ---
```
