### ISSUE TITLE
Interactive transactions in IPROTO

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#2016]
A client transaction can be started with CALL("box.begin").

Vinyl doesn't abort a transaction at fiber yield. But the same fiber may serve different connections of the binary protocol. It means that queries from different connections may end up in the same transaction, or that a subsequent query which is intended for a multi-statement transaction ends up committed prematurely.

All this trouble happens because struct txn is now stored in struct fiber, not in struct session, as well as gc pool.

So it seems time has come to move struct txn, struct region, and struct diag from struct fiber to struct session. Then we will either need to create a technical session for every fiber, or make sure that the rest of the code, which uses fibers, works without struct region gc and struct diag.

How to repeat: 
- begin a transaction on the client, over the binary protocol
- create another connection
- send a batch of two queries over the same connection; the queries must use the transactrion and yield
- observe the second query execute before the first one.

# Implementation

## The binary protocol 
We will extend the binary protocol header with a new key, **IPROTO_TRANSACTION_ID**.
Each request missing this key, or with key value 0, will run in its own transaction, or, if it's CALL/EVAL, will be able to manually control the transaction flow. In other words, for old clients and drivers, the semantics will stay the same.

We will also add commands for explicit transaction control flow:
IPROTO_BEGIN
IPROTO_COMMIT
IPROTO_ROLLBACK

These transaction will pass IPROTO_TRANSACTION_ID in the header, so they will affect the transaction identified by the supplied id.

IPROTO_BEGIN may miss IPROTO_TRANSACTION_ID. In this case, as well as in case of CALL/EVAL request explicitly starting a transaction by invoking `box.begin()` and  leaving it open, the server will pass an automatically generated id back to the client.

Since, with this enhancement, the client will get an opportunity to flood the server with infinitely many open transaction, a new box dynamic configuration variable needs to be introduced: `transaction_max`, limiting the number of active transactions.
We also need to reflect the number of active transactions in a statistical variable.

## Lua concole

We need a way to store the active transaction id in a Lua console. Since the id can not be stored in the session (a single session may multiplex many transactions), we need a way to store it someplace else - perhaps in the console itself. For that purpose, we perhaps need to extend box.session package to return transaction id, so that Lua console can query it explicitly and save.

## Runtime

fiber->gc needs to become a pointer, so that setting active transaction will update it.
Disconnect trigger needs to roll back all transactions active in the connection.
There should be a way to get a list of all active transactions in Lua and explicitly roll them back (by the
system administrator).

## Binary log and replication

We may need to introduce transaction id to the binary log to implement synchronous replication. For now, though, since we never have partial transactions in the binary log, and there is a binary log transaction (physical one), we don't need to change anything.

**Comment by rtsisyk** [comment]
> A client transaction can be started with CALL("box.begin").

Yes, it can. It will be rolled back just after the CALL():

```
tarantool> space = box.schema.space.create('test', { engine = 'vinyl' } )
---
...

tarantool> pk = space:create_index('pk')
---
...

tarantool> box.schema.user.grant('guest', 'read,write,execute', 'universe')
---
...

tarantool> remote = require('net.box')
---
...

tarantool> -- Check remote two-phase transactions.
---
...

tarantool> conn = remote.connect(3313)
---
...

tarantool> function callme()
> box.begin()
> space:replace({1, 2, 3})
> end
---
...

tarantool> conn:call('callme')
2017-03-17 14:10:08.205 [62125] main/105/main box.cc:1066 W> a transaction is active at return from 'callme'
```

> Vinyl doesn't abort a transaction at fiber yield. But the same fiber may serve different connections of the binary protocol. It means that queries from different connections may end up in the same transaction, or that a subsequent query which is intended for a multi-statement transaction ends up committed prematurely.
>  It means that queries from different connections may end up in the same transaction

Yes, fiber->fls[TXN] may contain a pointer to freed memory TXN in some situations. I made multiple attempts to fix this bug, all patches were rejected by @kostja.  Here is a diff from the latest one:

```
diff --git a/src/box/iproto.cc b/src/box/iproto.cc
index bb9ab67..954750a 100644
--- a/src/box/iproto.cc
+++ b/src/box/iproto.cc
@@ -307,6 +307,21 @@ tx_process_join_subscribe(struct cmsg *msg);
 static void
 net_end_join_subscribe(struct cmsg *msg);
 
+static void
+tx_fiber_init(struct session *session, uint64_t sync)
+{
+ session->sync = sync;
+ fiber_set_session(fiber(), session);
+ fiber_set_user(fiber(), &session->credentials);
+}
+
+static void
+tx_fiber_clear(void)
+{
+ fiber_set_session(fiber(), NULL);
+ fiber_set_user(fiber(), NULL);
+}
+
 /**
  * Fire on_disconnect triggers in the tx
  * thread and destroy the session object,
@@ -317,10 +332,12 @@ tx_process_disconnect(struct cmsg *m)
 {
  struct iproto_msg *msg = (struct iproto_msg *) m;
  struct iproto_connection *con = msg->connection;
+ tx_fiber_init(con->session, 0);
  if (con->session) {
  if (! rlist_empty(&session_on_disconnect))
  session_run_on_disconnect_triggers(con->session);
  session_destroy(con->session);
+ tx_fiber_clear();
  con->session = NULL; /* safety */
  }
  /*
@@ -842,14 +859,6 @@ iproto_connection_on_output(ev_loop *loop, struct ev_io *watcher,
  }
 }
 
-static void
-tx_fiber_init(struct session *session, uint64_t sync)
-{
- session->sync = sync;
- fiber_set_session(fiber(), session);
- fiber_set_user(fiber(), &session->credentials);
-}
-
 static int
 tx_check_schema(uint32_t schema_id)
 {
@@ -881,11 +890,13 @@ tx_process1(struct cmsg *m)
  iproto_reply_select(out, &svp, msg->header.sync,
  tuple != 0);
  msg->write_end = obuf_create_svp(out);
+ tx_fiber_clear();
  return;
 error:
  iproto_reply_error(out, diag_last_error(&fiber()->diag),
  msg->header.sync);
  msg->write_end = obuf_create_svp(out);
+ tx_fiber_clear();
 }
 
 static void
@@ -915,11 +926,13 @@ tx_process_select(struct cmsg *m)
  port_dump(&port, out);
  iproto_reply_select(out, &svp, msg->header.sync, port.size);
  msg->write_end = obuf_create_svp(out);
+ tx_fiber_clear();
  return;
 error:
  iproto_reply_error(out, diag_last_error(&fiber()->diag),
  msg->header.sync);
  msg->write_end = obuf_create_svp(out);
+ tx_fiber_clear();
 }
 
 static void
@@ -959,11 +972,13 @@ tx_process_misc(struct cmsg *m)
  msg->header.sync);
  }
  msg->write_end = obuf_create_svp(out);
+ tx_fiber_clear();
  return;
 error:
  iproto_reply_error(out, diag_last_error(&fiber()->diag),
  msg->header.sync);
  msg->write_end = obuf_create_svp(out);
+ tx_fiber_clear();
 }
```

> Implementation

This part is actually a new feature specification for interactive transactions in IPROTO. I changed the type of this ticket to "feature" and moved to 1.7.5.

**Comment by Gerold103** [comment]
Blocked by #2503.

**Comment by Gerold103** [comment]
Blocked by #946.

**Comment by kyukhin** [comment]
Superceeded by #5860
