### ISSUE TITLE
Could not restore vinyl space

### ISSUE THREAD

**Issue by dmitry-sobolev** [tarantool/tarantool#2022]
Hello, 

We are trying to use tarantool with vinyl storage engine currently. Until recently we were running tarantool in official docker container. But after docker crash we could not run tarantool. There's log:

> 2017-01-09 04:53:45.488 [1] main/101/tarantool-entrypoint.lua C> version 1.7.2-287-g085f6e4
> 2017-01-09 04:53:45.488 [1] main/101/tarantool-entrypoint.lua C> log level 5
> 2017-01-09 04:53:45.488 [1] main/101/tarantool-entrypoint.lua I> mapping 3221225472 bytes for tuple arena...
> 2017-01-09 04:53:45.505 [1] main/101/tarantool-entrypoint.lua I> recovery start
> 2017-01-09 04:53:45.505 [1] main/101/tarantool-entrypoint.lua I> recovering from `/var/lib/tarantool/00000000000035173329.snap'
> 2017-01-09 04:53:45.515 [1] main/101/tarantool-entrypoint.lua vinyl.c:2525 W> found stale range 516/0/000000000000001a.0000000000000153(["800aff7e-5b3d-4b89-8c62-5c39c7893e47"]..[])
> 2017-01-09 04:53:45.516 [1] main/101/tarantool-entrypoint.lua vinyl.c:2525 W> found stale range 516/0/000000000000001a.0000000000000152([]..["800aff7e-5b3d-4b89-8c62-5c39c7893e47"])
> 2017-01-09 04:53:45.519 [1] main/101/tarantool-entrypoint.lua vinyl.c:2525 W> found stale range 516/1/000000000000001b.00000000000000d2([]..[])
> 2017-01-09 04:53:45.523 [1] main/101/tarantool-entrypoint.lua vinyl.c:2525 W> found stale range 516/2/000000000000001c.00000000000000d2([]..[])
> 2017-01-09 04:53:45.529 [1] main/101/tarantool-entrypoint.lua vinyl.c:2525 W> found stale range 516/4/000000000000001e.00000000000000d2([]..[])
> 2017-01-09 04:53:45.533 [1] main/101/tarantool-entrypoint.lua vinyl.c:2525 W> found stale range 516/5/000000000000001f.00000000000000d2([]..[])
> 2017-01-09 04:53:45.537 [1] main/101/tarantool-entrypoint.lua vinyl.c:2525 W> found stale range 516/6/0000000000000020.00000000000000d2([]..[])
> 2017-01-09 04:53:45.542 [1] main/101/tarantool-entrypoint.lua vinyl.c:2525 W> found stale range 516/7/0000000000000021.00000000000000d2([]..[])
> 2017-01-09 04:53:45.547 [1] main/101/tarantool-entrypoint.lua I> recover from `/var/lib/tarantool/00000000000035036788.xlog'
> 2017-01-09 04:53:45.618 [1] main/101/tarantool-entrypoint.lua I> done `/var/lib/tarantool/00000000000035036788.xlog'
> 2017-01-09 04:53:45.618 [1] main/102/hot_standby I> recover from `/var/lib/tarantool/00000000000035036788.xlog'
> 2017-01-09 04:53:45.681 [1] iproto/102/iproto I> binary: started
> 2017-01-09 04:53:45.681 [1] iproto/102/iproto I> binary: bound to 0.0.0.0:3301
> 2017-01-09 04:53:45.682 [1] main/101/tarantool-entrypoint.lua I> done `/var/lib/tarantool/00000000000035036788.xlog'
> 2017-01-09 04:53:45.682 [1] main/101/tarantool-entrypoint.lua I> Building secondary indexes in space '_queue'...
> 2017-01-09 04:53:45.682 [1] main/101/tarantool-entrypoint.lua I> Adding 1 keys to TREE index 'tube_id' ...
> 2017-01-09 04:53:45.682 [1] main/101/tarantool-entrypoint.lua I> Space '_queue': done
> 2017-01-09 04:53:45.687 [1] main/101/tarantool-entrypoint.lua I> ready to accept requests
> 2017-01-09 04:53:45.688 [1] main/105/snapshot_daemon I> started
> 2017-01-09 04:53:45.688 [1] main/105/snapshot_daemon I> scheduled the next snapshot at Mon Jan  9 06:44:00 2017
> 2017-01-09 04:53:45.688 [1] main/101/tarantool-entrypoint.lua I> set 'snapshot_period' configuration option to 3600
> 2017-01-09 04:53:45.688 [1] main/106/console/unix/:/var/run/tarant I> started
> 2017-01-09 04:53:45.690 [1] vinyl.worker/101/main xlog.cc:694 !> /var/lib/tarantool/516/3/000000000000001d.00000000000000d3.0.run: failed to open: File exists
> Segmentation fault
> Current time: 1483937625
> Please file a bug at http://github.com/tarantool/tarantool/issues
> Attempting backtrace... Note: since the server has already crashed, 
> this may fail as well
> #0  0x563c36c9d049 in ?
> #1  0x7f5846d5fe0c in ?
> #2  0x563c36c9d0cc in ?
> #3  0x563c36d90550 in ?
> #4  0x563c36eb0a4f in ?
> #5  0 in ?

Could it be because of we were running out of disk space or something else?

**Comment by rtsisyk** [comment]
This problem has been fix a month ago.  Vinyl is still in active development, please try to use the latest version of Tarantool from 1.7 git branch/docker tag.

**Comment by dmitry-sobolev** [comment]
In release notes of Tarantool 1.7.3 has been written that vinyl disk layout was changed, so I didn't try to run it with my data. Do it run with old vinyl data files?

**Comment by rtsisyk** [comment]
You can use replication to upgrade. Vinyl disk layout is still in flux, we're trying to stabilize it.

**Comment by dmitry-sobolev** [comment]
It seems like this issue was solved in latest versions of tarantool, so I'm closing it.
