### ISSUE TITLE
vinyl: memory limits are exceeded

### ISSUE THREAD

**Issue by IlyaMarkovMipt** [tarantool/tarantool#2032]
Using latest version of tarantool (version 1.7.3-98-gb185445), I got unexpected behaviour.

Configuration was:
``` lua
box.cfg {
 listen=3301,
 log_level=5,
 logger='tarantool.log', 
 slab_alloc_minimal=24, slab_alloc_factor=1.2, slab_alloc_arena = 5,
 vinyl = {memory_limit=2*1024*1024*1024}, 
 wal_mode='none'
}

local engine='vinyl'

links = box.schema.space.create('links', {id = 513, if_not_exists = true, engine=engine})

links:create_index('primary', {id = 0, unique = true, type = type_idx, parts={1, 'unsigned', 2, 'unsigned', 3, 'unsigned'}, if_not_exists = true})
links:create_index('id1_type_sh', {id = 1, unique = false, type='tree', parts={1, 'unsigned', 3, 'unsigned' }, if_not_exists = true})
links:create_index('id1_type_vis', {id = 2, unique = false, type='tree', parts={1, 'unsigned', 3, 'unsigned', 4, 'scalar'}, if_not_exists = true})
links:create_index('time', {id = 4, unique = false, type='tree', parts={6, 'unsigned'}, if_not_exists = true})

```
I expected, that application wouldn't use more that 2 GB of memory, but it did.
The workload was about 15 GB and all of it was in memory.
The info from collectgarbage("count")  told me, that the amount of memory currently used by the program  was about 1 MB. It means, that vinyl used more memory, than it was configured to use.

### How to reproduce.
script is [here](https://gist.github.com/IlyaMarkovMipt/248889f0e66cbecb6d00094c1ec1241f)
launch it with
```
tarantool app.lua
```

**Comment by rtsisyk** [comment]
Please check after  #1842

**Comment by rtsisyk** [comment]
I'll check it LinkBench soon.

**Comment by rtsisyk** [comment]
I don't see this problem on our LinkBench instance anymore. I have  `vinyl_memory = 512 * 1024 * 1024` and `vinyl_cache = 2 * 1024 * 1024 * 1024;` with 4G of RAM on my test host and Vinyl works fine.
