### ISSUE TITLE
PVS-Studio fixes

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#2035]
The list of problems found by [PVS Studio](http://www.viva64.com/en/pvs-studio/) by [Viva64](http://www.viva64.com/) in 1.7.3-106-gfd45494:

- [x] [src/tt_pthread.h:301](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/src/tt_pthread.h#L301)	err	V579 The snprintf function receives the pointer and its size as arguments. It is possibly a mistake. Inspect the second argument.
- [x] [src/cbus.c:74](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/src/cbus.c#L74)	warn	V559 Suspicious assignment inside the condition expression of ternary operator: f->caller->caller = & cord->sched.
- [x] [src/say.c:490](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/src/say.c#L490)	warn	V547 Expression 'option == ((void *) 0)' is always false.
- [x] [src/evio.cc:109](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/src/evio.cc#L109)	warn	V571 Recurring check. The 'family != 1' condition was already verified in line 108.
- [x] [src/coeio.c:352](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/src/coeio.c#L352)	err	V597 The compiler could delete the 'memset' function call, which is used to flush 'task' object. The memset_s() function should be used to erase the private data.
- [x] [src/backtrace.cc:338](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/src/backtrace.cc#L338)	warn	V547 Expression 'fiber_name(cord_ptr->fiber) == __null' is always false. Pointer 'fiber_name(cord_ptr->fiber)' != NULL.
- [ ] [src/lua/utils.c:83](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/src/lua/utils.c#L83)	warn	V547 Expression is always false.
- [x] [src/lib/bitset/page.h:95](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/src/lib/bitset/page.h#L95)	warn	V560 A part of conditional expression is always true: (16 % 1 == 0).
- [x] [src/lib/bitset/page.h:94](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/src/lib/bitset/page.h#L94)	warn	V560 A part of conditional expression is always true: 1 <= 1.
- [x] [src/lib/bitset/iterator.c:89](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/src/lib/bitset/iterator.c#L89)	warn	V778 Two similar code fragments were found. Perhaps, this is a typo and 'page_tmp' variable should be used instead of 'page'.
- [x] [src/lib/salad/guava.c:42](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/src/lib/salad/guava.c#L42)	warn	V707 Giving short names to global variables is considered to be bad practice. It is suggested to rename 'K' variable.
- [x] [src/lib/salad/rtree.c:306](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/src/lib/salad/rtree.c#L306)	warn	V764 Possible incorrect order of arguments passed to 'rtree_rect_in_rect' function: 'rt2' and 'rt1'.
- [x] [src/lib/salad/rtree.c:314](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/src/lib/salad/rtree.c#L314)	warn	V764 Possible incorrect order of arguments passed to 'rtree_rect_strict_in_rect' function: 'rt2' and 'rt1'.
- [x] [src/box/xlog.cc:536](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/src/box/xlog.cc#L536)	warn	V701 realloc() possible leak: when realloc() fails in allocating memory, original pointer 'signatures' is lost. Consider assigning realloc() to a temporary pointer.
- [x] [src/box/memtx_rtree.cc:182](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/src/box/memtx_rtree.cc#L182)	warn	V559 Suspicious assignment inside the condition expression of ternary operator.
- [x] [src/box/memtx_rtree.cc:182](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/src/box/memtx_rtree.cc#L182)	warn	V768 The expression is of enum type. It is odd that it is used as an expression of a Boolean-type.
- [x] [src/box/memtx_rtree.cc:255](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/src/box/memtx_rtree.cc#L255)	warn	V668 There is no sense in testing the 'it' pointer against null, as the memory was allocated using the 'new' operator. The exception will be generated in the case of memory allocation error.
- [x] [src/box/memtx_hash.cc:219](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/src/box/memtx_hash.cc#L219)	err	V568 It's odd that 'sizeof()' operator evaluates the size of a pointer to a class, but not the size of the 'hash_table' class object.
- [x] [src/lib/salad/mhash.h:77](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/src/lib/salad/mhash.h#L77)	warn	V677 Custom declaration of a standard 'uint32_t' type. The declaration from system header files should be used instead.
- [x] [src/box/engine.cc:47](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/src/box/engine.cc#L47)	err	V730 Not all members of a class are initialized inside the constructor. Consider inspecting: id, flags.
- [x] [src/lib/salad/bps_tree.h:4276](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/src/lib/salad/bps_tree.h#L4276)	warn	V711 It is dangerous to create a local variable within a loop with a same name as a variable controlling this loop.
- [x] [src/box/memtx_tree.cc:275](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/src/box/memtx_tree.cc#L275)	err	V630 The 'calloc' function is used to allocate memory for an array of objects which are classes containing constructors.
- [x] [src/box/memtx_tree.cc:370](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/src/box/memtx_tree.cc#L370)	warn	V701 realloc() possible leak: when realloc() fails in allocating memory, original pointer 'build_array' is lost. Consider assigning realloc() to a temporary pointer.
- [x] [src/box/memtx_tree.cc:387](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/src/box/memtx_tree.cc#L387)	warn	V701 realloc() possible leak: when realloc() fails in allocating memory, original pointer 'build_array' is lost. Consider assigning realloc() to a temporary pointer.
- [x] [src/box/memtx_engine.cc:158](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/src/box/memtx_engine.cc#L158)	warn	V764 Possible incorrect order of arguments passed to 'replace' function: 'new_tuple' and 'old_tuple'.
- [x] [src/box/vy_stmt.c:80](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/src/box/vy_stmt.c#L80)	err	V597 The compiler could delete the 'memset' function call, which is used to flush 'tuple' object. The memset_s() function should be used to erase the private data.
- [x] [src/box/vy_log.c:424](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/src/box/vy_log.c#L424)	err	V629 Consider inspecting the '1 << key' expression. Bit shifting of the 32-bit value with a subsequent expansion to the 64-bit type.
- [x] [src/box/vy_log.c:488](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/src/box/vy_log.c#L488)	err	V597 The compiler could delete the 'memset' function call, which is used to flush 'log' object. The memset_s() function should be used to erase the private data.
- [x] [src/box/vy_log.c:902](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/src/box/vy_log.c#L902)	err	V597 The compiler could delete the 'memset' function call, which is used to flush 'recovery' object. The memset_s() function should be used to erase the private data.
- [x] [src/box/func.cc:41](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/src/box/func.cc#L41)	err	V630 The 'malloc' function is used to allocate memory for an array of objects which are classes containing constructors.
- [ ] [src/box/alter.cc:1161](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/src/box/alter.cc#L1161)	err	V623 Consider inspecting the '?:' operator. A temporary object is being created and subsequently destroyed. Check second operand.
- [x] [src/box/recovery.cc:412](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/src/box/recovery.cc#L412)	warn	V730 Not all members of a class are initialized inside the constructor. Consider inspecting: file_path.
- [x] [src/box/wal.cc:573](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/src/box/wal.cc#L573)	err	V623 Consider inspecting the '?:' operator. A temporary object is being created and subsequently destroyed. Check third operand.
- [x] [src/box/vinyl.c:1331](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/src/box/vinyl.c#L1331)	err	V597 The compiler could delete the 'memset' function call, which is used to flush 'run' object. The memset_s() function should be used to erase the private data.
- [x] [src/box/vinyl.c:1389](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/src/box/vinyl.c#L1389)	err	V696 The 'continue' operator will terminate 'do { ... } while (FALSE)' loop because the condition is always false. Check lines: 1389, 1389.
- [x] [src/box/vinyl.c:2187](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/src/box/vinyl.c#L2187)	err	V629 Consider inspecting the '1 << key' expression. Bit shifting of the 32-bit value with a subsequent expansion to the 64-bit type.
- [x] [src/box/vinyl.c:2336](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/src/box/vinyl.c#L2336)	err	V629 Consider inspecting the '1 << key' expression. Bit shifting of the 32-bit value with a subsequent expansion to the 64-bit type.
- [x] [src/box/vinyl.c:2586](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/src/box/vinyl.c#L2586)	err	V597 The compiler could delete the 'memset' function call, which is used to flush 'range' object. The memset_s() function should be used to erase the private data.
- [x] [src/box/vinyl.c:3817](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/src/box/vinyl.c#L3817)	warn	V612 An unconditional 'return' within a loop.
- [x] [src/box/vinyl.c:3843](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/src/box/vinyl.c#L3843)	warn	V612 An unconditional 'return' within a loop.
- [x] [src/box/vinyl.c:4698](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/src/box/vinyl.c#L4698)	err	V597 The compiler could delete the 'memset' function call, which is used to flush 'index' object. The memset_s() function should be used to erase the private data.
- [x] [src/box/vinyl.c:5878](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/src/box/vinyl.c#L5878)	err	V597 The compiler could delete the 'memset' function call, which is used to flush 'tx' object. The memset_s() function should be used to erase the private data.
- [x] [src/box/vinyl.c:5949](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/src/box/vinyl.c#L5949)	err	V597 The compiler could delete the 'memset' function call, which is used to flush 'tx' object. The memset_s() function should be used to erase the private data.
- [x] [src/box/vinyl.c:6369](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/src/box/vinyl.c#L6369)	err	V597 The compiler could delete the 'memset' function call, which is used to flush 'page' object. The memset_s() function should be used to erase the private data.
- [x] [test/unit/queue.c:149](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/test/unit/queue.c#L149)	warn	V760 Two identical blocks of text were found. The second block begins from line 152.
- [x] [test/unit/guava.c:38](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/test/unit/guava.c#L38)	err	V501 There are identical sub-expressions to the left and to the right of the '!=' operator: guava(100, 20) != guava(100, 20)
- [x] [test/unit/guava.c:50](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/test/unit/guava.c#L50)	err	V706 Suspicious division: sizeof (golden100) / sizeof (int64_t). Size of every element in 'golden100' array does not equal to divisor.
- [x] [src/lib/salad/bps_tree.h:4396](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/src/lib/salad/bps_tree.h#L4396)	err	V510 The 'printf' function is not expected to receive class-type variable as second actual argument.
- [x] [src/lib/salad/bps_tree.h:4418](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/src/lib/salad/bps_tree.h#L4418)	err	V510 The 'printf' function is not expected to receive class-type variable as second actual argument.
- [x] [test/unit/bps_tree_iterator.cc:96](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/test/unit/bps_tree_iterator.cc#L96)	warn	V756 The 'j' counter is not used inside a nested loop. Consider inspecting usage of 'i' counter.
- [ ] [test/unit/bps_tree.cc:16](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/test/unit/bps_tree.cc#L16)	err	V575 The 'realloc' function processes '0' elements. Inspect the second argument.
- [ ] [test/unit/bps_tree.cc:16](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/test/unit/bps_tree.cc#L16)	warn	V701 realloc() possible leak: when realloc() fails in allocating memory, original pointer 't->members' is lost. Consider assigning realloc() to a temporary pointer.
- [ ] [test/unit/bps_tree.cc:16](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/test/unit/bps_tree.cc#L16)	warn	V701 realloc() possible leak: when realloc() fails in allocating memory, original pointer 't->lrpointers' is lost. Consider assigning realloc() to a temporary pointer.
- [x] [test/unit/bps_tree.cc:16](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/test/unit/bps_tree.cc#L16)	warn	V701 realloc() possible leak: when realloc() fails in allocating memory, original pointer 'i' is lost. Consider assigning realloc() to a temporary pointer.
- [x] [test/unit/bps_tree.cc:582](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/test/unit/bps_tree.cc#L582)	err	V576 Incorrect format. Consider checking the second actual argument of the 'printf' function. The memsize type argument is expected.
- [x] [test/unit/bps_tree.cc:586](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/test/unit/bps_tree.cc#L586)	err	V576 Incorrect format. Consider checking the second actual argument of the 'printf' function. The memsize type argument is expected.
- [x] [test/unit/bitset_iterator.c:381](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/test/unit/bitset_iterator.c#L381)	err	V593 Consider reviewing the expression of the 'A = B == C' kind. The expression is calculated as following: 'A = (B == C)'.
- [x] [test/unit/rtree_multidim.cc:83](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/test/unit/rtree_multidim.cc#L83)	err	V517 The use of 'if (A) {...} else if (A) {...}' pattern was detected. There is a probability of logical error presence. Check lines: 83, 86.
- [x] [test/unit/vclock.cc:84](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/test/unit/vclock.cc#L84)	err	V501 There are identical sub-expressions 'VCLOCK_ORDER_UNDEFINED' to the left and to the right of the '!=' operator.
- [x] [test/unit/vclock.cc:88](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/test/unit/vclock.cc#L88)	err	V501 There are identical sub-expressions 'VCLOCK_ORDER_UNDEFINED' to the left and to the right of the '!=' operator.
- [x] [test/unit/vclock.cc:89](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/test/unit/vclock.cc#L89)	err	V501 There are identical sub-expressions 'VCLOCK_ORDER_UNDEFINED' to the left and to the right of the '!=' operator.
- [x] [test/unit/vclock.cc:90](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/test/unit/vclock.cc#L90)	err	V501 There are identical sub-expressions 'VCLOCK_ORDER_UNDEFINED' to the left and to the right of the '!=' operator.
- [x] [test/unit/vclock.cc:91](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/test/unit/vclock.cc#L91)	err	V501 There are identical sub-expressions 'VCLOCK_ORDER_UNDEFINED' to the left and to the right of the '!=' operator.
- [x] [test/unit/reflection_cxx.cc:24](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/test/unit/reflection_cxx.cc#L24)	warn	V730 Not all members of a class are initialized inside the constructor. Consider inspecting: m_int, m_str.
- [x] [test/unit/reflection_cxx.cc:51](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/test/unit/reflection_cxx.cc#L51)	warn	V730 Not all members of a class are initialized inside the constructor. Consider inspecting: m_int, m_str.
- [x] [src/uri.c:1](https://github.com/tarantool/tarantool/blob/fd45494b18fbfa20a8f40286bece35ccd456df8e/src/uri.c#L1)	err	V002 Some diagnostic messages may contain incorrect line number in this file.

I validated some randomly picked items and I can confirm that this list contains some non-false positive alarms.

Please feel free to fix bulks of items and push to a branch for review. Don't forget to add "See #2035" to commit messages. 

See also https://github.com/rtsisyk/msgpuck/issues/13

**Comment by IlyaMarkovMipt** [comment]
src/coeio.c:352 err	V597 - ignored due to the fact it's used in debug mode.

**Comment by rtsisyk** [comment]
Pushed
