### ISSUE TITLE
Whats is the equivalent of the AND & OR select operators in tarantool?

### ISSUE THREAD

**Issue by suporteavancado** [tarantool/tarantool#2037]
Hi,

How to make in tarantool a select/search similar to this one in SQL (using the AND operator):

select * from quotes where date >= "2000-01-01" AND date <= "2010-01-01"

Thanks

Danilo

**Comment by kostja** [comment]
Hi, what you're looking for is BETWEEN here, really. Please check this part of the manual: 
https://tarantool.org/doc/1.7/book/box/box_index.html#example-showing-a-user-defined-iterator
or join our telegram channel to get help.
Thanks!
