### ISSUE TITLE
box.snapshot() fails to write snapshot if we are at same lsn as last saved snapshot

### ISSUE THREAD

**Issue by vicpopov** [tarantool/tarantool#2045]
Here is an example of error I get when trying to save snapshot when there is no write transactions occurring after last saved snapshots.
```
[root@test1 ~]# cat /etc/tarantool/instances.enabled/test.lua 
box.cfg {
        listen = 3300;
        logger = '/logs/tarantool/test.log';
        read_only = false;
        rows_per_wal = 50000;
        slab_alloc_arena = 0.5;
        snapshot_count = 5;
        snapshot_period = 60;
        username = 'tarantool';
        wal_mode = 'write';
}
[root@test1 ~]# > /logs/tarantool/test.log; tarantoolctl start test
/usr/bin/tarantoolctl: Starting instance...
[root@test1 ~]# tarantoolctl enter test
/usr/bin/tarantoolctl: connected to unix/:/var/run/tarantool/test.control
unix/:/var/run/tarantool/test.control> box.info
---
- server:
    lsn: 0
    ro: false
    uuid: 689dd775-17b3-41b9-8e6c-4ca4c0042b8a
    id: 1
  cluster:
    uuid: 5824ab55-077d-4260-ab64-2658a616de52
  version: 1.6.9-55-g0ff46f3
  pid: 4069
  status: running
  vclock:
  - 0
  replication:
    status: off
  uptime: 21
...

unix/:/var/run/tarantool/test.control> s = box.schema.space.create('tester')
---
...

unix/:/var/run/tarantool/test.control> s:create_index('primary', {type = 'hash', parts = {1, 'num'}})
---
- unique: true
  parts:
  - type: NUM
    fieldno: 1
  id: 0
  space_id: 512
  name: primary
  type: HASH
...

unix/:/var/run/tarantool/test.control> t = s:insert{1, 'Roxette'}
---
...

unix/:/var/run/tarantool/test.control> t = s:insert{2, 'Scorpions', 2015}
---
...

unix/:/var/run/tarantool/test.control> t = s:insert{3, 'Ace of Base', 1993}
---
...

unix/:/var/run/tarantool/test.control> s:select{3}
---
- - [3, 'Ace of Base', 1993]
...

unix/:/var/run/tarantool/test.control> box.snapshot()
---
- error: can't save snapshot, errno 17 (File exists)
...

```
Same behavior when snapshot daemon is requested to create snapshots regularly - it simply does not create them, just reschedules next snapshot creation.
Absence of fresh snapshots prevents from creating a monitoring check that ensures we always have latest snapshot.

I believe it is wrong to fail in a situation when operator's desire is to ensure creation of latest snapshot (for example before shutdown/restart/backup/destructive actions).
The correct behavior for tarantool after box.snapshot() should result in fresh snapshot no matter what snapshots exist, and what LSN we are at.
Proposed solutions if snapshot with name corresponding current LSN exists:
- write snapshot and replace existing snapshot with new one after new has been written.
- advance LSN with noop transaction and write next snapshot
- touch snapshot, ensuring its freshness. This is least desirable variant because it will make more difficult to create a robust backup solution, uploading fresh snapshots to backup storage (overwriting backup storage even with file timestamps makes backups less reliable and trustworthy).

**Comment by YarickR** [comment]
It will be great if tarantool could provide some kind of a LSN check between in-memory state and on-disk snapshot, so one could safely assume if he needs to call box.snapshot() to get fresh snapshot.

**Comment by Mons** [comment]
touch would be semantically correct

**Comment by rtsisyk** [comment]
OK, let's touch the last snapshot file.
