### ISSUE TITLE
Make tuple_extract_key template

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#2048]
Re-use templates in tuple_compare.cc to generate optimized versions of tuple_extract_key() for typical use cases. This optimization is mandatory after #2046

**Comment by rtsisyk** [comment]
This optimization for sequential keys in tuple_extract_key_slowpath_raw() is not covered by tests: https://coveralls.io/jobs/25995975/source_files/1107615913#L262

Please add some **functional** tests to get code coverage for this optimization. tuple_extract_key_raw() is used by UPSERT in MemTX and by secondary keys in Vinyl.

tuple_extract_key() is OK.

**Comment by rtsisyk** [comment]
The coverage is still missing even after 653c9b96af810914340ae6cac165f233013f487d patch:

https://coveralls.io/builds/11682499/source?filename=src%2Fbox%2Ftuple.c#L268

**Comment by rtsisyk** [comment]
rewind in tuple_extract_key_slowpath_raw() is still not tested:
https://coveralls.io/jobs/26142242/source_files/1131270764#L268

**Comment by Gerold103** [comment]
The extractor still is not template. And it is needed for #2988.
