### ISSUE TITLE
Insert and update operations list misbehaviour in protocol

### ISSUE THREAD

**Issue by igorcoding** [tarantool/tarantool#2055]
Натолкнулся на достаточно неприятную неконсистентность в индексации в протоколе (в update и upsert)
поясню на примере tarantool модуля для питона

это значит спейс:
```
s = box.schema.create_space('tester')
s:create_index('primary')
```

Идем кодом в тарантул и делаем Insert + Update:
```
server.insert('tester', (2, 'hello'))
server.update('tester', (2,), [(':', 1, 1, 3, '!!!')])
```

Согласно моим убеждениям должен сделаться сплайс строки hello от символа 'e' до второго символа 'l', что и происходит:
```
tarantool> box.space.tester:select{}
---
- - [2, 'h!!!o']
...
```

Теперь очищаем спейс и делаем upsert:
```
server.upsert('tester', [2, 'hello'], [(':', 1, 1, 3, '!!!')])
```

Спейс пустой - должен сделаться insert, что и имеем:
```
tarantool> box.space.tester:select{}
---
- - [2, 'hello']
...
```

Теперь сделаем upsert выше еще разок и в коннекторе все прошло успешно, а вот в тарантуле в логе видна ошибка:
```
2017-02-03 01:45:02.690 [11424] main/164/main tuple_update.c:1085 E> UPSERT operation failed:
2017-02-03 01:45:02.690 [11424] main/164/main tuple_update.c:307 E> ER_UPDATE_ARG_TYPE: Argument type in operation ':' on field 1 does not match field type: expected a string
```

Выходит, что он fieldno = 1 воспринял "как луа", хотя в апдейте воспринимал нормально
Тоже самое касается в общем-то остальных параметров - они все индексируются с 1.

Проблема не в коннекторе.
в версии `1.7.2-333-gaeec869` все работало праивльно, а в `1.7.3-172-g2587f6a` - уже нет

**Comment by rtsisyk** [comment]
Fixed via 9e72a15ee70e0f0f54657f1b767b5f94086fcaa1
1.7.3-195-g9e72a15
