### ISSUE TITLE
Create index with a "NUMERIC" part fails with "NUMBER field type is not supported"

### ISSUE THREAD

**Issue by agnul** [tarantool/tarantool#2056]
Maybe I'm doing something wrong here but:

```
some_space:create_index('expireDate', {
    unique = false,
    type = 'TREE',
    parts = {3, 'NUMBER'}
})
```
works on version `1.6.7-630-geab01da`. The same statement on version `1.6.9-56-gafce2a6` fails with the error message

```
Can't create or modify index 'expireDate' in space 'someSpace': 
NUMBER field type is not supported
```

Any idea what's wrong?

**Comment by kostja** [comment]
We were not checking the input in 1.6.7 and substituting all the incorrect input with a default.
We fixed this in 1.6.9, and your statement started to fail. 'NUMBER' is no a correct type alias in 1.6 (neither it is in 1.7). 
Sorry for this gotcha.
