### ISSUE TITLE
Support autoincrement in binary protocol

### ISSUE THREAD

**Issue by crackerplace** [tarantool/tarantool#2070]
Hi All,

As per the tarantool binary doc,there are codes for insert,update,select etc.But I could not find a code for [autoincrement](https://tarantool.org/doc/singlehtml.html#box-space-auto-increment).

https://tarantool.org/doc/singlehtml.html#unified-packet-structure

Value for <code> key in request can be:

**User command codes**
select= 0x01

insert= 0x02

replace= 0x03

update  = 0x04

delete  = 0x05

call_16 = 0x06

auth    = 0x07

eval    = 0x08

upsert  = 0x09

call    = 0x0a

**Admin command codes**

ping    = 0x40

**Value for code key in response can be:**

OK      = 0x00

ERROR   = 0x8XXX

Can this support be added so that client connectors can invoke autoincrement on a box space through the binary protocol.

**Comment by rtsisyk** [comment]
autoincrement is a simple Lua wrapper around index:max() + space:replace().
There is no protocol command for autoincrement.

**Comment by crackerplace** [comment]
@rtsisyk Thanks.If I have to even get an index:max() ,how can I do it from a connector end.I meant what should be the user command code for it(like insert= 0x02) at a binary protocol level.Or is this function only available in the tarantool server itself.

I was trying to see if autoincrement in some form can be done with lua-resty-tarantool or if it has to be implemented.

**Comment by kostja** [comment]
Hi, we will support this in SQL in 1.8.0.

**Comment by kostja** [comment]
This is done with the new sequences, simply pass nil for the sequence column in the binary protocol.
