### ISSUE TITLE
Increase precision for percentage ratios provoded by box.slab.info()

### ISSUE THREAD

**Issue by viciious** [tarantool/tarantool#2082]
```
tarantool> box.slab.info()
---
- items_size: 228128
  items_used_ratio: 1.8%
  quota_size: 1073741824
  quota_used_ratio: 0.8%
  arena_used_ratio: 43.2%
  items_used: 4208
  quota_used: 8388608
  arena_size: 2325176
  arena_used: 1003632
...
```

I think the *_used_ratio attributes listed by box.slab.info() might be useful it they provided at least two digits in the fractional part. From experience, the 0.1% jumps are somewhat confusing. 

It would be nice to have this in 1.6 branch too.

Thanks in advance.

**Comment by rtsisyk** [comment]
1.6.9-83-g7a0996c5a
