### ISSUE TITLE
Built-in tarantool-curl

### ISSUE THREAD

**Issue by dedok** [tarantool/tarantool#2083]
1) All development should be in separate branch (builtin-tarantool-curl)
2) tarantool-curl has own libev loop that is wrong in context of conception of tarantool.
   the built-in tarantool-curl should use tx event loop. So to make it possible - need remove curl_f (and fiber) and replace loop pointer to tx loop pointer.
3) Port auto test to test_run.
4) Integrate http test and the brand new built-in tarantool-curl.

References:
* tarantool-curl evloop - https://github.com/tarantool/curl/blob/master/curl/driver.c#L37
* tx event loop - is pointer to libev loop which executes event in tx thread.

**Comment by rtsisyk** [comment]
1.7.4-151-g7e62ac79b
