### ISSUE TITLE
vinyl: extract GE/GT and LE/LT cases from the read iterator

### ISSUE THREAD

**Issue by alyapunov** [tarantool/tarantool#2090]
DRAFT

Goals:
Simplify restore
Remove -2 return code
Optimize merge locate - make only log(N) comparisons
Do not read the same page from several fibers simultaneously
Optimize upsert squash - no tuple allocation on every upsert (if there are several sequential upserts of the same key)
Unit tests

Steps:
Create simple write iterator that handles msgpack only: no tuple_alloc, no different behaviour on different threads
Tuple refs in mem, run, range, index + invalid status of them.
Implement ITER_REQ
Unit tests
Merge iterator source flag mask: TXW of CACHE or MEM or RUN;
IS_MUTABLE, IS YIELDABLE, STOPPABLE, BELOGNS_RANGE
Merge iterator additional flags: IS_THE_LATEST
Merge iterator retuns both masks ORed

**Comment by Gerold103** [comment]
If the run and mem iterators return raw message pack, you can't talk about tuples referencing in the these iterators.

**Comment by alyapunov** [comment]
Do not search in write_set in vy_tx_track(..), just pass source info flags from read-merge iterator.
Note that read iterator must pass binary OR of all sources from merge iterator in case of UPSERT sequence

**Comment by alyapunov** [comment]
1. Make independent write iterator.
2. On order to bury restoring:
2.1. make new API of the low-level iterators:
 * get_next_key
 * get_next_lsn
 * step_to_next_key
2.2. add different keys for initial positioning and for EQ/REQ limit
3. Use light refts for run/mem (allow them to free resources but not free vy_run/vy_mem structure)
4. Use heap in merge iterator

**Comment by alyapunov** [comment]
removed "Optimize upsert squash - no tuple allocation on every upsert (if there are several sequential upserts of the same key)"
That is good in some cases but bad in another.
Current implementation is best for simple series of upserts of the same field. That's common scenario, so I suggest to leave the current implementation.

**Comment by rtsisyk** [comment]
This ticket requires range/gap locks in the tx manager.

**Comment by rtsisyk** [comment]
Moving to 1.7.6

**Comment by rtsisyk** [comment]
Refactored, the ticket is not actual anymore.
1.7.6-26-gf6ec32e8b
