### ISSUE TITLE
Tarantool stack trace is broken when run in Docker

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#2103]
![photo_2017-02-27_20-46-25](https://cloud.githubusercontent.com/assets/482910/23372729/e8322430-fd2d-11e6-97a7-7ae6bbd6659f.jpg)

Docker is using MUSL libc and there is no libbfd by default on Alpine  Linux.

Do either of these:
* make sure libbfd works
* use libunwind
* use glibc rather rather than musl

**Comment by rtsisyk** [comment]
libunwind: http://lists.nongnu.org/archive/html/libunwind-devel/2017-02/msg00013.html

**Comment by rtsisyk** [comment]
1.7.4-329-g2e4b6fddf
