### ISSUE TITLE
Build fails on Android

### ISSUE THREAD

**Issue by dedok** [tarantool/tarantool#2106]
0%] Building C object CMakeFiles/ev.dir/third_party/tarantool_ev.c.o
In file included from /data/data/com.termux/files/home/tarantool/third_party/tarantool_ev.c:31:
In file included from /data/data/com.termux/files/home/tarantool/third_party/libev/ev.c:167:
/data/data/com.termux/files/usr/include/stdlib.h:108:14: error: conflicting types for
      'arc4random'
unsigned int arc4random(void);
             ^
/data/data/com.termux/files/usr/include/stdio.h:488:20: note: previous implicit
      declaration is here
                unsigned int r = arc4random();
                                 ^
1 error generated.
make[2]: *** [CMakeFiles/ev.dir/build.make:63: CMakeFiles/ev.dir/third_party/tarantool_ev.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:139: CMakeFiles/ev.dir/all] Error 2
make: *** [Makefile:150: all] Error 2

**Comment by rtsisyk** [comment]
OMG
Do you have a real use case for Tarantool on Android? We can add support for bionic libc, but does  it make sense?

**Comment by dedok** [comment]
Our users try to use tarantool on mobile platforms.

**Comment by dedok** [comment]
I have spoken with the user and I have asked - 'can he gives any comments?'. Comments means he will give to us his explanation.

**Comment by kyukhin** [comment]
We do not support Android.
