### ISSUE TITLE
Redundant lookups into primary index

### ISSUE THREAD

**Issue by mejedi** [tarantool/tarantool#2110]
```sql
CREATE TABLE t2(rowid primary key, a,x);
CREATE INDEX t2x ON t2(x);
EXPLAIN SELECT rowid, a FROM t2 WHERE x='00ffffffffff'
```
Yields
```yaml
---
- - [0, 'Init', 0, 14, 0, '', '00', 'Start at 14']
  - [1, 'OpenRead', 0, 16448, 0, 'k(1,)', '00', 'root=16448 iDb=0; t2']
  - [2, 'OpenRead', 1, 16449, 0, 'k(2,,)', '02', 'root=16449 iDb=0; t2x']
  - [3, 'Explain', 0, 0, 0, 'SEARCH TABLE t2 USING INDEX t2x (x=?)', '00', '']
  - [4, 'String8', 0, 1, 0, '00ffffffffff', '00', 'r[1]=''00ffffffffff''']
  - [5, 'SeekGE', 1, 13, 1, '1', '00', 'key=r[1]']
  - [6, 'IdxGT', 1, 13, 1, '1', '00', 'key=r[1]']
  - [7, 'Column', 1, 0, 2, '', '00', 'r[2]=']
  - [8, 'NotFound', 0, 12, 2, '1', '00', 'key=r[2]']
  - [9, 'Column', 1, 0, 3, '', '00', 'r[3]=t2.rowid']
  - [10, 'Column', 1, 1, 4, '', '00', 'r[4]=t2.a']
  - [11, 'ResultRow', 3, 2, 0, '', '00', 'output=r[3..4]']
  - [12, 'Next', 1, 6, 1, '', '00', '']
  - [13, 'Halt', 0, 0, 0, '', '00', '']
  - [14, 'Transaction', 0, 0, 2, '0', '01', 'usesStmtJournal=0']
  - [15, 'Goto', 0, 1, 0, '', '00', '']
...
```
Opcode `[8, 'NotFound']` is redundant.

So why does SQLite emit it? In SQLite, a table+indices is implemented as several independent BTrees. When an entry is fetched from a secondary index, there's a chance for inconsistency. If the entry is found in a secondary index BTree but is missing from the main BTree, SQLite skips it. Hence the `NotFound` opcode.

This doesn't actually make sense in Tarantool, since (in `memtx`) this inconsistency couldn't really happen.

Yet its relevant for `vynil`.

Note: currently there's a hack in place to avoid lookups into the primary index, since `memtx` indices are covering. This needs to be re-evaluated when optimising for `vynil`.

**Comment by kostja** [comment]
Vinyl will work exactly in the same way as memtx. We will not push any differences up the storage engine API.

**Comment by mejedi** [comment]
>Vinyl will work exactly in the same way as memtx. We will not push any differences up the storage engine API.

In `memtx`, fetching the entire tuple is virtually free. But in `vinyl`, it's not. It would be great if it was possible to process the query using the secondary index only, without hidden lookups into the primary index for fields that aren't even going to be accessed! Other SQL products have this feature, by the way.

**Comment by kostja** [comment]
There are no SQL optimizers built from scratch for LSM trees, so it's not comparing apples to apples. Vinyl secondary key lookup may return a deleted key. You need a lookup in the primary index just to make sure the LSN of the key is actually visible to the transaction. Maybe-sometime-in-the-future we will have a different implementation, but then, as I said, it would be easier to hide all the complexity behind struct tuple, perform the primary key lookup on demand and spare VDBE from the headache.
