### ISSUE TITLE
Make all ANSI SQL keywords reserved.

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#2116]
This will block future incompatibility.

**Comment by pgulutzan** [comment]
The SQL standard document, section "token and separator", says
a "key word" is either a "reserved word" or a "non-reserved word".
It goes on to list non-reserved words (for example BEFORE), and
reserved words (for example BEGIN). I interpreted the words
"Make all ANSI SQL keywords reserved" as a reference to
both standard reserved words and non-reserved words.
I think Mr Yukhin has confirmed that he did not mean that.
