### ISSUE TITLE
Implement SQL console.

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#2117]
We need to implement SQL mode console.

**Comment by rtsisyk** [comment]
- [ ] Research on meta-control symbols used by various REPL implementations for meta-commands, e.g. "\command", ".command", "#command", "!command" and other:
  * psql
  * mysql
  * SQL*Plus
  * sqlite
  * ipython REPL
  * NodeJS REPL
  * Swift REPL
  * Ruby REPL
  * PHP REPL
  * ...
The goal is to find "the least common denominator" for meta-control characters among the most popular read-eval-print-loops and ensure that this symbol is reserved in all most popular languages we would add in future. Please post your research results to this ticket, choose any character you think is the most appropriate and then move on.
- [ ] Add preprocessor to Lua console and implement "\delimiter" command by wrapping console.delimiter() function.
- [ ] Add "\language lua" and "\language sql" preprocessor command to switch between Lua and SQL languages. We already have some state in  console, stored in box.session.storage (see box.session.delimiter() implementation). You can extend this state to store chosen language. SQL commands can be executed by invoking `box.sql.execute()`

Limitations for the first version:

* SQL language outputs results in YAML format, we will change it by the next patches.
* SQL language doesn't support auto-completion, we will decide how to add it later.

**Comment by rtsisyk** [comment]
Please note that this feature should be implemented against "sql2" branch. This branch will be rebased and renamed to 1.8 lately.

**Comment by GeorgyKirichenko** [comment]
Some language consoles (python, ruby) use internal functions such as help() for special behaviour, but this is applicable for one-language applications with defined syntax and special function names

sql plus and sqlite consoles use special instruction like SET, SHOW, that can be well-matched against sql syntax, but this is not applicable for multi-language tarantool console.

psql and mysql consoles use special escape char '\' for internal console commands such as \h \t \c and e.g.

'\' escape at first command string position can be used for entering console internal mode, if some language will use this symbol too then tarantool can support double escaping

**Comment by rtsisyk** [comment]
* **mysql** - already uses `\`  as meta-character
* **psql** - already uses `\`  as meta-character
* **sqlite** - uses `.` as meta-character
* **SQL*Plus** - uses SET XXX which can change both client and server options
* **Lua 5.3** - OK

`\` at the beginning of the line is invalid:

```
$ lua5.3
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio
> \
stdin:1: unexpected symbol near '\'
```

* **Python 3.5** - almost OK, requires some tricks

`\` is  line continuation character, but it should work for us at the beginning of the expression

```
$ python3.5
Python 3.5.3 (default, Jan 19 2017, 14:11:04)
[GCC 6.3.0 20170118] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> \
...
>>> \
...
>>>
>>> \command
  File "<stdin>", line 1
    \command
           ^
SyntaxError: unexpected character after line continuation character
>>>
```

* **ipython*** - OK

The same as Python.

```
$ ipython3 
^[[APython 3.5.3 (default, Jan 19 2017, 14:11:04)
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: \command
  File "<ipython-input-1-4505f6747bbf>", line 1
    \command
            ^
SyntaxError: unexpected character after line continuation character


In [2]: 
```

* **Ruby**

```
$ irb
irb(main):001:0> \command
SyntaxError: (irb):1: syntax error, unexpected $undefined
\command
 ^
        from /usr/bin/irb:11:in `<main>'
irb(main):002:0>
```

* **nodejs**
```
$ 
> \
SyntaxError: Unexpected token ILLEGAL
> \help
...
...
...
... <!-- WTF, how to exit from this mode?
``

**Comment by rtsisyk** [comment]
OK, let's go with `\`.

**Comment by rtsisyk** [comment]
```
   Meta-Commands
       Anything you enter in psql that begins with an unquoted backslash is a psql meta-command that is processed by psql itself. These
       commands make psql more useful for administration or scripting. Meta-commands are often called slash or backslash commands.

       The format of a psql command is the backslash, followed immediately by a command verb, then any arguments. The arguments are separated
       from the command verb and each other by any number of whitespace characters.

       To include whitespace in an argument you can quote it with single quotes. To include a single quote in an argument, write two single
       quotes within single-quoted text. Anything contained in single quotes is furthermore subject to C-like substitutions for \n (new line),
       \t (tab), \b (backspace), \r (carriage return), \f (form feed), \digits (octal), and \xdigits (hexadecimal). A backslash preceding any
       other character within single-quoted text quotes that single character, whatever it is.

       Within an argument, text that is enclosed in backquotes (`) is taken as a command line that is passed to the shell. The output of the
       command (with any trailing newline removed) replaces the backquoted text.

       If an unquoted colon (:) followed by a psql variable name appears within an argument, it is replaced by the variable's value, as
       described in SQL Interpolation.

       Some commands take an SQL identifier (such as a table name) as argument. These arguments follow the syntax rules of SQL: Unquoted
       letters are forced to lowercase, while double quotes (") protect letters from case conversion and allow incorporation of whitespace into
       the identifier. Within double quotes, paired double quotes reduce to a single double quote in the resulting name. For example,
       FOO"BAR"BAZ is interpreted as fooBARbaz, and "A weird"" name" becomes A weird" name.

       Parsing for arguments stops at the end of the line, or when another unquoted backslash is found. An unquoted backslash is taken as the
       beginning of a new meta-command. The special sequence \\ (two backslashes) marks the end of arguments and continues parsing SQL
       commands, if any. That way SQL and psql  commands can be freely mixed on a line. But in any case, the arguments of a meta-command cannot
       continue beyond the end of the line.
``

**Comment by kyukhin** [comment]
OK to me.

**Comment by kyukhin** [comment]
Could you pls mke meta commands case-insensitive as per Peter's request?
