### ISSUE TITLE
Prohibit `SELECT` w/o `FROM`

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#2124]
`SELECT` w/o subsequent `FROM` is not standard, let's prohibit it.
Probably, we'll need to introduce dummy table (like `DUAL` in Oracle)

>I am able to say
select 5;
there is no FROM clause.
This is typical of SQLite and MySQL, but
not standard and Oracle lovers would say
SELECT 5 FROM DUAL;
so should "select 5;" really be allowed?

**Comment by kostja** [comment]
We will not fix this.
