### ISSUE TITLE
Don't read the primary key when updating a non-unique secondary key

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#2129]
Implement lazy secondary index garbage collection, which is done only during compaction. 
Do not delete garbage from non-unique secondary keys on replace/insert events.

**Comment by Gerold103** [comment]
Plan: https://docs.google.com/document/d/1FCncEfAVOdqbz9x2UVN02NHVBwdsJPdFSulZxA0CaeA/edit

**Comment by locker** [comment]
Fixed by a6edd4559bca4b7df480cb54874ad517f0719591

**Comment by nekufa** [comment]
@locker, i collect schema metadata on application server bootstrap and it validates schema for all spaces (including system). is there a way to add primary key on _vinyl_deferred_delete space? or it's better to skip validation for that space?

**Comment by locker** [comment]
@nekufa Blackhole engine, which is used for _vinyl_deferred_delete space, doesn't support indexes so I guess you should skip validation for this space or, even better, for all spaces that don't have any indexes.

**Comment by nekufa** [comment]
@locker thanks, i learned that it is a way of replica broadcasting. i decide to disable that check for any system spaces
