### ISSUE TITLE
Division by zero should yield error or infinity.

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#2135]
Subj.

>I am able to say
select 7/0 from m1;
The result is NULL.
Once again this sort of thing is non-standard
but common. Should it cause an error?
Or should 7 / 0 = inf, as in Tarantool-NoSQL?

**Comment by pgulutzan** [comment]
Fixing this so it will say "error" makes for standard-SQL
compatibility, but not compatibility with Lua ("7/0 = inf"),
and not compatibility with SQLite. Incompatibility and
loose rules are behind several problems with arithmetic.
Others are
The ABS() failure (see issue#2347 Functions in SQL)
The ROUND() failure (see issue#2347 Functions in SQL)
Incompatibility with big Lua numbers (see issue#2469
SQL returns wrong data for int64 values and issue#2363
SQL select statement, with big numbers).

See also issue#1701 nan. This was closed in May 2017
with an explanation:
sNaN < qNaN < -inf < normal number < +inf;
sNaN == sNaN;
qNaN == qNaN;
aNaN != qNaN;
-inf == -inf;
+inf == +inf;
but we know that is incompatible with standard-SQL
requirements, so we should be asking: how to represent,
whether to add a BINARY_FLOAT data type, what the
order is compared to NULL, what the keywords are,
why lists like this don't include -NaN,
and what to do about what is typically regarded as
overflow such as 1E500, or arithmetic-overflow.

**Comment by kshcherbatov** [comment]
Tested on other databases:

**ms sql: Divide by zero error encountered.
pgsql: ERROR: division by zero
ORA-01476: divisor is equal to zero**
mysql, sqlite: NULLs in count of rows amount 

@kyukhin lit's disallow divide by 0?

**Comment by kyukhin** [comment]
I bet we want to be ANSI-complaint, so let's throw error.
