### ISSUE TITLE
`IS` is only applicable when dealing with NULL.

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#2136]
Issue is that `... WHERE 0 IS 0` working right now.

> There doesn't seem to be much checking for whether
an operator is appropriate for the operand, so
"0 is 0" is allowed. Probably this has some relation
to the lack of data type checking, so I expect it
will be disallowed.

**Comment by Gerold103** [comment]
https://github.com/tarantool/tarantool/commit/b3a3ddb571202c70171ac57a2f831e8bad00bf9b
