### ISSUE TITLE
`DROP TABLE` should cause discard of associated triggers.

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#2141]
Right now `DROP TABLE` didn't cause removal of its triggers. Need to fix this.

> Also, triggers are not dropped if the table is dropped.

**Comment by kyukhin** [comment]
This might be changed.
Bulat, could you pls verify if this holds and if so  - fix it?

**Comment by TheAviat0r** [comment]
Roger that

**Comment by kyukhin** [comment]
Resolved.
