### ISSUE TITLE
set up lua_atpanic to write a message to the error log

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#2142]
The stack trace may not always be available when we get an abort signal. Set up lua_atpanic function to write a message to the error log, print stack trace and then abort.

This should provide better crash diagnostics when panic is called.

Ideally to be fixed in 1.5, 1.6, and 1.7 trees.

**Comment by rtsisyk** [comment]
How do you want to print Lua stack trace from a signal handler? I don't understand the idea of this ticket.
