### ISSUE TITLE
Replica silently lost all changes in time of final join streaming

### ISSUE THREAD

**Issue by GeorgyKirichenko** [tarantool/tarantool#2152]
First, replica downloads from master initial snapshot with vclock, Seconds replica downloads final join with changes between initial join vclock and the time of end of initial join vclock streaming procedure. After final join replica recieves masters currenct vclock that may be differ from end of final join stream, but this vclock acts as last masters state.

**Comment by rtsisyk** [comment]
Fixed by a1c0d98911d96be0cce840d966de4170a3e6744c
