### ISSUE TITLE
vinyl: don't store LSN on disk if it's lower than the oldest read view LSN

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#2154]
Don't waste space trying to store LSN for a transaction wchih is older than the oldest read view. Assume it's LSN is -inf, store nothing, when reading page from disk set LSN to 0.
This should save quite a few bytes on scale.
Mostly affects the runs at lowest levels.

**Comment by rtsisyk** [comment]
Let's return to this ticket after finishing with benchmarks.

See #2400

**Comment by Gerold103** [comment]
We can not skip oldest LSNs because of recovery without vylog.

**Comment by kostja** [comment]
This breaks force-recovery mode. Won't fix.
