### ISSUE TITLE
Add pre-build config option to disable dependency from libbfd.

### ISSUE THREAD

**Issue by amdei** [tarantool/tarantool#2155]
Kind of opposite to #1179: deb-package should not have run-time dependency from `binutils`.
This is due to `binutils `include, among others, linker and assembler, what is in some cases forbidden on production machines.

More than that, https://packages.debian.org/jessie/binutils-dev states (though I do not know how to interpret that):

> building Debian packages which depend on the shared libbfd is Not Allowed.

It looks like current situation can be solved by following:

1. Add option to eliminate dependency from `libbfd` at compile-time;
1. detect presence of `libbfd` at run-time, and load and use it dynamically.

While second option looks complicated, it gives users ability to see pretty backtraces if they are able to install  `binutils`, first one looks simpler to implement.

**Comment by amdei** [comment]
Seems that dependency from libbfd can be eliminating at configure-time with:

    cmake . -DENABLE_BACKTRACE=OFF

**Comment by kostja** [comment]
We no longer depend on libbfd, we use libunwind.
