### ISSUE TITLE
vinyl: write each vinyl page as a single xlog transaction, not one transaction per run

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#2157]
Currently vinyl run is written to the file as a single xlog transaction. This means, that if the run is corrupt, we have to skip all the pages in the run. Checksum each page separately, to be able to recover data on disk corruption. This is necessary for gh-2156

**Comment by rtsisyk** [comment]
Each page is already written as a single xlog transaction. Please see https://github.com/tarantool/tarantool/blob/a8e6b7204dee5eeb0832b5fe20cf0ba6a7511d47/src/box/vinyl.c#L2126-L2171
