### ISSUE TITLE
Background `ANALYZE` fiber

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#2162]
PeterG writes:
>  Don't allow the statement. I don't see what it would do.
    Perhaps I'm asking for the equivalent of the SQLite
    compile-time option SQL_OMIT_ANALYZE.

@kostja and @kyukhin, 17/07/2017:
We will implement a background process which gathers optimizer statistics at all times. It will be possible to turn this process of. If there is no background process, we still need a statement to force one-off scan and accumulation of statistics. This is what ANALYZE is already doing in sqlite. So the decision is to actually keep this statement.

**Comment by kyukhin** [comment]
Remove `DETACH` as well.

**Comment by kyukhin** [comment]
kostja comments that this be likely won't be fixed.

**Comment by kostja** [comment]
Duplicate of https://github.com/tarantool/tarantool/issues/2853
