### ISSUE TITLE
Remove `ATTACH DATABASE`.

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#2163]
> Don't allow the statement. I don't see what it would do.
    Perhaps I'm asking for the equivalent of the SQLite
    compile-time option SQL_OMIT_ATTACH.

**Comment by kyukhin** [comment]
Remove `DETACH` as well.

**Comment by Gerold103** [comment]
Summary for a student:
1. Go to `parse.y` file.
2. Find and remove `ATTACH DATABASE ` and `DETACH DATABASE `, if these commands exists.
3. Rerun CMake with a flag: `cmake . -DSQL_MAINTAINER_MODE=1`.
4. Rebuild Tarantool: `make -j`.
5. Run existing tests to check that nothing is broken: `python test-run.py sql/ sql-tap/`.
6. Add your own test to one of existing files, or better create a new one for all of this parser things: `parser.test.lua` for example.
7. Update `.result` file of your test.

**Comment by kyukhin** [comment]
`ATTACH/DETACH` statements were removed.
