### ISSUE TITLE
Remove `BEGIN TRANSACTION`.

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#2164]
> Don't allow the statement. Allow START TRANSACTION instead.

**Comment by kyukhin** [comment]
Same for `END TRANSACTION`.
Or maybe just keep both for SQLite compatibility

**Comment by kyukhin** [comment]
Same for`ROLLBACK [TRANSACTION]`.
Maybe keep allowing of `TRANSACTION` to be SQLite compatible.

**Comment by kyukhin** [comment]
Maybe this is too aggressive to remove `BEGIN TRANSACTION`, maybe simply prohibit single worded synonym `BEGIN`. Same for `END`.

**Comment by pgulutzan** [comment]
MySQL, another DBMS group supporting BEGIN to start a transaction, got into parsing trouble when attempting to support BEGIN in the standard way to start a compound statement (bug#42597). It's fixed, but the trouble could have been avoided by not supporting BEGIN to start a transaction. MySQL and PostgreSQL support both BEGIN and START TRANSACTION for historical reasons, but we don't have historical reasons.

**Comment by Gerold103** [comment]
@alexfmsu is assigned on the ticket.
