### ISSUE TITLE
Remove `ORDER BY` and `LIMIT` from `DELETE` statement.

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#2172]
Subj.

> Okay, it's already been decided: ORDER BY + LIMIT are
    not allowed. I'm just noting this, because these clauses
    are possible in SQLite with a compile-time option.

**Comment by mejedi** [comment]
We don't set this option. The reason this feature is turned off by default is because the implementation is incomplete.

BTW, `ORDER BY` and `LIMIT` in `DELETE` statement are useful. I wonder if standard SQL offers any alternatives.

**Comment by kostja** [comment]
You can always use WHERE pk IN (subquery expr) - this is the standard alternative.
ORDER BY ... LIMIT is only useful if your optimizer is very weak, otherwise you can do it efficiently with a standard compliant SQL, in relational spirit.

**Comment by kyukhin** [comment]
Done by https://github.com/tarantool/tarantool/commit/43ed060f9539ed44a232ca81ad890b1099872cd9
