### ISSUE TITLE
Check if `INSERT/REPACE` of `OR` form are working.

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#2175]
If `INSERT/REPLACE ... OR ...` form is not working and cannot be easily fixed - let's remove it.

**Comment by iproha94** [comment]
``` INSERT OR REPLACE ``` statement is working.

```REPLACE``` works like ``` INSERT OR REPLACE ```, but that's beside the point.

**Comment by kyukhin** [comment]
Ok, closing then.
