### ISSUE TITLE
Check `with clause` in `SELECT` statement.

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#2176]
Need to verify if `with clause` is working withing `SELECT` statement or can be easily fixed.

Remove if it is not.

**Comment by iproha94** [comment]
```WITH``` clause is working withing ```SELECT``` statement. See documentation [common-table-expressions](https://tarantool.org/en/doc/1.8/tutorials/sql_tutorial.html#common-table-expressions)

**Comment by kyukhin** [comment]
Okay, closing then.
