### ISSUE TITLE
Remove `VACUUM` statement.

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#2178]
Subj.

> Don't allow the statement. I don't see what it would do.
    Perhaps I'm asking for the equivalent of the SQLite
    compile-time option SQL_OMIT_VACUUM.

**Comment by pgulutzan** [comment]
VACUUM Is worse than useless, it makes all tables disappear.
box.sql.execute("CREATE TABLE te7 (s1 INT PRIMARY KEY);")
box.sql.execute("VACUUM;")
box.sql.execute("SELECT * FROM te7;")
Result = error: 'no such table: te7'
