### ISSUE TITLE
bad argument #1 to ''pairs'' on box.cfg()

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#2191]
```
version 1.7.3-354-ge7550da08
type 'help' for interactive help
tarantool> box.cfg()
---
- error: 'builtin/box/load_cfg.lua:175: bad argument #1 to ''pairs'' (table expected,
    got nil)'
...

```

**Comment by bigbes** [comment]
`error: 'builtin/uri.lua:41: bad argument #2 to ''uri_parse'' (cannot convert ''table'' to ''const char *'')'`

on double call of `box.cfg{ replication = {} }`

**Comment by rtsisyk** [comment]
Oops, "box.cfg{ replication = {} }" must work. This is a regression  since 1.6.x, moving back to 1.7.4.
