### ISSUE TITLE
Rename log.logger_pid

### ISSUE THREAD

**Issue by lenkis** [tarantool/tarantool#2197]
Please decide whether it's worth renaming the variable `logger_pid` (in `log` module) into `log_pid` to keep the name consistent with changes under https://github.com/tarantool/tarantool/issues/1927

**Comment by rtsisyk** [comment]
This is a follow up for #1927, moving to 1.7.4 prio1.

**Comment by bigbes** [comment]
`log.log_pid` looks kind of ugly. Maybe it's better to rename `log_pid` to `pid`, to avoid unnecessary repetition?

**Comment by rtsisyk** [comment]
> log.log_pid looks kind of ugly. Maybe it's better to rename log_pid to pid, to avoid unnecessary repetition?

Already done, see 1.7.

**Comment by bigbes** [comment]
> Already done, see 1.7.

If it's done it doesn't mean it's not ugly.
