### ISSUE TITLE
Embed Lua into SQL.

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#2200]
E.g., to be able to access service variables.

> One of many possible examples is
"
tarantool> box.cfg.wal_mode
--
 write
...
"
We want something vaguely like this SQL statement
select box.cfg.wal_mode from t;
but of course we don't want periods inside identifiers.

**Comment by rtsisyk** [comment]
I don't the idea of storing Lua code in data spaces. It would be better to allow SQL's `CALL <name>` to work like IPROTO_CALL and support all global Lua functions and defined C procedures.

**Comment by Khatskevich** [comment]
it would be easy to do something like this
```
select lua('box.cfg.wal_mode');
select lua('2 + 2');
```
However, it CONTRADICTS with static types.
@kyukhin

**Comment by kostja** [comment]
This is a trivial wrapper around a Lua stored function which does eval of the passed argument, not a standalone feature request. Utterly insecure. If you want use a sandboxed lua program, then it's a different matter.
