### ISSUE TITLE
Verify that `box.space.t:upsert(...)` is used for `UPSERT`.

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#2203]
Subj.

**Comment by rtsisyk** [comment]
box_upsert() C API should be used instead of Lua's `box.space.t:upsert(...)`

**Comment by Korablev77** [comment]
There is no INSERT OT UPDATE in SQLite, but INSERT OR REPLACE statement uses vdbe opcode OP_IdxInsert, which in its turn calls box_replace(). Hence, I think it is confirmed and can be closed.

**Comment by kyukhin** [comment]
Closing then.
