### ISSUE TITLE
vinyl: implement single mem per index

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#2209]
Remove vy_mem from vy_range and create single vy_mem in entire vy_index.
Dump index mems in index runs. Index runs can be splited in ranges during compaction and splitting of ranges.

- [x] Restrict the run_iterator return statements => review by @alyapunov 
- [x] Return maximal LSN from compact_new => reword comments by by @locker
- [x] Implement deferred restore of runs and mem => review by @alyapunov 
- [x] Create 'compact_max_lsn' heap of ranges => OK, keep on branch
- [x] Save max_dump_size in vy_range instead of vy_task => OK, push to 1.7
- [x] Make coalesce as separate task => review by @locker, rework by @Gerold103  
- [x] Save max_dump_lsn for ranges in vy_log =>  implement by @locker 
- [x] Save key_def for runs in vy_log => implement by @locker 
- [x] Add a merge iterator to vy_join => implement by @locker 
- [x] Patch vy_read_iterator to support infinruns => implement by @Gerold103 
- [x] Glue all this stuff together @Gerold103, fix tests

----

- [ ] Design how to compact entire infinruns @rtsisyk @kostja 
- [ ] Find a better conceptions for holes in infiruns @rtsisyk @kostja

**Comment by kostja** [comment]
Pushed.
