### ISSUE TITLE
Fix index id generation

### ISSUE THREAD

**Issue by mejedi** [tarantool/tarantool#2216]
Currently, valid index id is [0,127]. Next index id in SQL `CREATE INDEX` statement is computed as `max(indexid) + 1`. This calculation may yield invalid index id if indices are added and dropped repeatedly.

**Comment by kostja** [comment]
Please provide a test case. You'll learn that the problem is really hard to reproduce in real life - you need to create an index, and then drop the previous one.
There is a simple fix in schema.lua (we need to fill the gaps and recycle old ids, but only when we reach max index id).

**Comment by kostja** [comment]
The problem has no known effects.
