### ISSUE TITLE
Move legacy DD structs to Tarantool

### ISSUE THREAD

**Issue by mejedi** [tarantool/tarantool#2217]
Tables and indices in SQLite are identified by a single integer representing the root page number of the corresponding BTree.

Due to SQLite legacy we encode space and index ids in a page number. Store and pass spaceid, indexid explicitly.

Rationale: the current approach restricts id range; makes comprehending the code harder.

**Comment by kyukhin** [comment]
There's no proposal here. One of main goals of integration of SQL w/ Trantool is to merge data dictionaries of SQL w/ Tarantool's one. So, we're going to merge `struct Table` and `struct Index` of SQL w/ corresponding Tnt entities (space/index) and refactoring SQL sources to adopt the change.

I think that this is a big deal and should be moved out of alpha-2 and scheduled to be implemented during alpha-2, beta-1 development slot.

**Comment by kyukhin** [comment]
At the end of the day, we'd like to use single data dictionary. Current vision is to remove most of legacy SQLite data structures, which represent data dictionary and extend backend's data structures w/ necessary fields.

Obvious mapping is (legacy -> TNT):
struct Table -> struct space;
struct Index -> struct index;

For struct Table, there're also field that have no sense to put inside struct space, unless corresponding feature is implemented inside of the server. Example: 
`FKey *pFKey;            /* Linked list of all foreign keys in this table */`, Tarantool have no FK so far.
