### ISSUE TITLE
box.schema.user.password('user') shows wrong hash

### ISSUE THREAD

**Issue by stepanbabenko** [tarantool/tarantool#2219]
```
box.schema.user.passwd('testuser','12345')
---
..
box.schema.user.password('testuser')
---
5lFNHrMfSoFWDN3yjJMIxRgejn4=
...

box.schema.user.passwd('testuser','54321')
---
...
box.schema.user.password('testuser')
---
5lFNHrMfSoFWDN3yjJMIxRgejn4=
...
box.space._user:select(5)
---
[5, 1, 'testuser', 'user', {'chap-sha1': 'JzFi4aZ0mXwPZIGwu2d+YrUGWgA='}]
...
```
It looks like that box.schema.user.password() shows incorrect hash of a user’s password

**Comment by kostja** [comment]
Has to be fixed in 1.6

**Comment by stepanbabenko** [comment]
version: 1.7.3-403-gfa14851

**Comment by GeorgyKirichenko** [comment]
input parameter for box.schema.user.password(password) is the password to hash but not the user name

**Comment by rtsisyk** [comment]
Please note that there are two functions:

* [box.schema.user.password(password)](https://tarantool.org/en/doc/1.7/book/box/box_schema.html?highlight=password#lua-function.box.schema.user.password)
  Return a hash of a user’s password.


* [box.schema.user.passwd(user-name, password)](https://tarantool.org/en/doc/1.7/book/box/box_schema.html?highlight=password#lua-function.box.schema.user.passwd)
  Associate a password with the user who is currently logged in. or with another user. Users who wish to change their own passwords should use box.schema.user.passwd(password). Administrators who wish to change passwords of other users should use box.schema.user.passwd(user-name, password).

I agree that `password()` vs `passwd()` are misleading. We will discuss possible removal or renaming of  `password()` lately.

**Comment by rtsisyk** [comment]
Documentation problem => 1.7.5

**Comment by lenkis** [comment]
Clarified usage of these two functions in 1.6/1.7/1.8 manuals
