### ISSUE TITLE
Invoke Lua functions created outside SQL.

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#2233]
Along with #2232, it'll be useful to define temporary Lua functions outside of
SQL program.

> Suppose I defined a function outside SQL
function f() return 5; end
Now I want to say "select f() from t;".
As with global variable names, there might have to be
some indication that it's a global function, for
example "select @@f() from t;".
This sort of function is temporary and the
text would not be in a _function table.

**Comment by kyukhin** [comment]
sqlite-tcl/trigger6.test.lua wasn't converted to sql-tap because of this issue.

**Comment by Khatskevich** [comment]
In my opinion, ability to call any global function is redundant.
I suppose that it is easy enough to register function you want to call with box.internal.sql_create_function.
Am I wrong?

**Comment by lenkis** [comment]
Doc ticket: https://github.com/tarantool/doc/issues/879
