### ISSUE TITLE
Support JSON in SQL.

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#2239]
Introduce new JSON type.

Not 1.8.0 feature.

> I think that MySQL and PostgreSQL didn't do JSON quite right
http://ocelot.ca/blog/blog/2015/11/26/standard-sqljson-and-mysql-5-7-json/
and I think that doing it right would require some discussion.
In the meantime I believe JSON data should not be in a new
JSON data type, it should just be in a VARCHAR.

**Comment by kyukhin** [comment]
There's also set for working with JSON documents in SQL 2016

**Comment by Gerold103** [comment]
Duplicate of #2369
