### ISSUE TITLE
Prepared statement invalidation on schema change

### ISSUE THREAD

**Issue by mejedi** [tarantool/tarantool#2245]
When the schema changes prepared statements need to be recompiled.

Current implementation maintains all prepared statements in a single list. When the schema changes all statements are purged. This is bad for a database server.

We would like to invalidate only the statements affected.

Example: an index was added to `T1`. Select statements fetching from `T1` need recompilation to have a chance of taking advantage of the added index. The majority of statements don't touch `T1` and should be retained.

This improvement requires replacing the global list with a per-object lists. There's an added complication that a statement could participate in multiple lists (Ex: `SELECT * FROM T1 UNION ALL SELECT * from T2`).

**Comment by kyukhin** [comment]
Prepared statements are not usable so far.
So, this issue is blocked by #2592 or even should be closed w/ "won't be resolved" status.

**Comment by kyukhin** [comment]
I guess this is done.
