### ISSUE TITLE
crash somewhere in bsize

### ISSUE THREAD

**Issue by alyapunov** [tarantool/tarantool#2257]
running a code
```
s = box.schema.space.create('test',{engine=engine})
_ = s:create_index('primary')
s:replace{1}
box.begin()
s:delete{1}
box.rollback()
s:delete{1}
```
got a crash with an error message in log:
```
tarantool: /home/alyapunov/Work/tarantool/src/box/space.cc:222: void space_bsize_update(space*, const tuple*, const tuple*): Assertion `space->bsize >= old_bsize' failed.
```

**Comment by rtsisyk** [comment]
It would be nice to see at least the stack trace. This crash is not caused by a bug in  space_bsize_update(). This assertion just demonstrate that we handle old/new tuples on rollback in the wrong way.
