### ISSUE TITLE
tarantoolctl cat creates invalid strings

### ISSUE THREAD

**Issue by man0xff** [tarantool/tarantool#2262]
it has created such string constant:

    '\x69\x45\xdd\xb2\xf2\x4f\x3b\xf1\xb8\x4\xe1\xf1\x8\x9d\xbb\x4e'`
                                          ^          ^

marked bytes have only one digit and that breaks parsing
tarantool-1.7.2.335-1.el7.centos.x86_64

**Comment by bigbes** [comment]
In `tarantoolctl` we need to replace `("\\x%2x")` --with--> `("\\x%02x")`.

**Comment by man0xff** [comment]
https://github.com/tarantool/tarantool/pull/2287

**Comment by bigbes** [comment]
Fixed
