### ISSUE TITLE
Rename schema_id

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#2265]
When describing packets, the manual refers to
"schema_id" because it depends on the naming
used in the source code.
<schema_id>     ::= 0x05
But this name is confusingly similar to BOX_SCHEMA_ID,
the id of the _schema space. We're not actually
talking about an identifier of the schema, we're
talking about an identifier of the schema version.
Suggestion: schema_version_in_packet.
Once the change is done, we can fix the manual.

Rationale: in dev email thread "Schema reload"
on 2017-03-27 Peter Gulutzan wrote:
Is it too late to change the name "schema_id"?
The manual refers to schema_id in the packet header
https://tarantool.org/doc/1.7/dev_guide/internals_index.html
but it gets compared to sc_version, which stands for either
"schema version" or "schema change version", I guess.

Konstantin Osipov replied:
It is SChema version. Please rename the name of the field in the
internals and file a ticket against the server to do an internal
rename in src/box/iproto_constants.h (the name is not used
anywhere but in the source code, all connectors use the number of
the key, not its name).

**Comment by rtsisyk** [comment]
I want to rename `sc_version` and `schema_id` to `schema_version`. Does it work or you?

**Comment by kostja** [comment]
OK with me

**Comment by pgulutzan** [comment]
OK with me
