### ISSUE TITLE
Allow no PK tables.

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#2284]
SQLite contains so-called `rowid` implicit column which acts as PK when no such specified.
When PK is specified to be single column integer - `rowid` is associated with such a key.

Tarantool doesn't allow to insert into spaces w/o index defined on top of it.
So, if no PK is defined for table, let's create implicit integer column (which will automatically increment upon insertions into the table) which will constitute index necessary for Tarantool.

Questions arise though when we're beginning to talk about ALTERs. If we add PK later, should we remove this implicit column?

**Comment by Korablev77** [comment]
We have no more rowid since b61ee32eff9c216e13c1819c483dedc22be9db3c
