### ISSUE TITLE
IPROTO_SQL_EXECUTE

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#2285]
Implement an IPROTO protocol command to execute an SQL statement. 
This is a minimal API necessary to enable SQL support in Tarantool client drivers.

The command is a "catch-all" for all use cases involving SQL, except cursor management.

It accepts the following parameters:

* prepared statement text,
* prepared statement parameters,
* execution options.

The client has no access to explicit prepared statement management, i.e. creation and destruction of prepared statements. These are managed by the server automatically. The client always sends SQL statement text to the server, and the server automatically finds a prepared statement for the text if there is one.

It is possible to pass parameters along with the text. 
The options include such things as opening a server side cursor, or a "dry-run" option, which only parses the query text and returns the result set metadata, but does not execute the statement.

The binary layout of the command is:

1) IPROTO_HEADER: the same as any other IPROTO header, IPROTO_TYPE = IPROTO_SQL_EXECUTE
2) IPROTO_BODY: contains at least these keys: IPROTO_SQL_TEXT, IPROTO_SQL_BIND. The driver writers are advised to put IPROTO_SQL_BIND as the last argument of the command. Additional keys are possible. IPROTO_SQL_TEXT contains a query text. IRPOTO_SQL_BIND contains an array of tuples (positioned bind, e.g. :1, :2, etc) or array of maps (named binds, eg.. :field1, :field2)

Options/flags to be added in the future:
* IPROTO_SERVER_SIDE_CURSOR - boolean
* IPROTO_DRY_RUN - boolean

These options can be possied either as a single key (IPROTO_SQL_OPTIONS) or as multiple keys (to be decided later).

The server responds with IPROTO_OK in case of success, with an optional result set. The result set contains an IPROTO_BODY response, with IPROTO_DESCRIPTION key containing a result set metadata array, and IPROTO_DATA with result set rows. In case of cursor, the body contains a cursor id in IRPOTO_CURSOR_ID field (to be added later).

IPROTO_DESCRIPTION is an array of maps, each map for each result set column in order. Each map includes at least:
IPROTO_FIELD_TYPE - a string with column type, e.g. "string", "num", the tarantool column types
IPROTO_FIELD_NAME - a string with column name, e.g. "*", "1", "address"

**Comment by Gerold103** [comment]
I think, that we need add IPROTO_LANGUAGE also for IPROTO_CALL, because SQL also has functions, like SUM, AVG, COUNT etc.

**Comment by Gerold103** [comment]
@rtsisyk said, that language for 'call' is useless, so do not pay attention to this idea.

**Comment by Gerold103** [comment]
We can cherry-pick patch about port.cc -> port.c. Do it at first.

**Comment by aensidhe** [comment]
```The server responds with IPROTO_OK in case of error```

Ok in case of error?

**Comment by rtsisyk** [comment]
> It accepts the following parameters:
>
>    prepared statement text,
>    prepared statement parameters,
>    execution options.

Why "prepared"? It should be just "statement text" and "statement parameters".

> IPROTO_FIELD_NAME - a string with column name, e.g. "*", "1", "address"

Does "*" have any special meaning here?

>  IPROTO_SQL_TEXT contains a query text. IRPOTO_SQL_BIND contains an array of tuples (positioned bind, e.g. :1, :2, etc) or array of maps (named binds, eg.. :field1, :field2)

Please specify exactly which format will be used for binding parameters:
  - position arguments: `$1` (:1, %s, :1, etc.)
  - named arguments: `$name` (:name, %(name)s, etc.)

**Comment by Gerold103** [comment]
@kostja  review:
- sql_execute -> execute
- надо дербанить sql.c уже на части либо реализацию sql_execute в execute.c класть

**Comment by Gerold103** [comment]
@kostja review:
- IPROTO_DESCRIPTION -> IPROTO_METADATA;
- DATA+METADATA только если есть result set;
- Без result set отдавать IPROTO_SQL_INFO: { IPROTO_SQL_ROW_COUNT: number};
- смержить константы xrow.c в enum в начале файла;
- body_key -> iproto_map_key;
- все константы сделать с IPROTO_;
