### ISSUE TITLE
[PROPOSAL] Use pull requests for the code review

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#2299]
## Goals

* Involve more people into the code review process.

* Reduce the average "latency" of review iterations to 1-2 business days.

* Save the history of review comments and discussions for teammates and newcomers.

* Force "two approved reviews" rule to be mandatory for 1.6/1.7/1.8+ check-in.

* Make the review process to be well-defined and more efficient.

## Problems

The current workflow looks as follows:

- Notification Daemon sends a new email for every commit in the patchset 
   => at least 1 email sent
- To assign and notify a potential reviewer you reply to this email and mention somebody in CC 
   => at least 2 emails sent
- The reviewer may want to rebase the patch to the latest trunk
   => at least 3 emails sent, the email thread is divided.
- Review comments from the reviewer
  => at least 4 emails sent
- Clarification questions from the author
  => at least 5 emails sent
- Explanation from the reviewer
  => at least 6 emails sent
- The author reworks his/her patch and push rebased version into -v2, v3, .., vN branch 
  => go to the first step, the email thread is divided.

Assume that we want to have 2 iterations for an average patchset. Some patches may require up to 10 iterations, but let's stick to the number "2. Two iterations will create at least 12 emails,
Dozens (literally) of disconnected emails just to review a simple patch? Sounds too bureaucratic, isn't?
Moreover, these emails ain't grouped in threads by the most email clients for various reason (different topics, different senders, missing headers, etc..)

* Commits@ maillist is heavy-loaded with useless emails.
* Authors and reviewers (=all team members) have to read dozens of emails every day in order to coordinate their work.
* Potential reviewers struggle to find branches for review.
* Finding an appropriate email to reply in the maillist is non-trivial too.
* Missing tasks lists of pending and active reviews.
* There is no proper way to assign reviewers.
* The progress on review tasks is hard to check.
* Authors can't track the current progress on their patches.
* Participants prefer to use instance messengers or even verbal communication for collaboration due to the current complexity of the procedure.
* Missing history of review comments.
* This system doesn't scale to the bigger number of participants.
* Reviewers and authors don't do their job on time due to a lack of information.

Briefly, the current review process is totally **flawed**.

## Solution

Proposed solution is to use GitHub [Pull Requests](https://help.github.com/articles/about-pull-requests/) for the code review process. 

This proposal doesn't imply that  you will have use the web-browser to review patches. The entire process can be performed using console tools. [Don't worry, be happy](https://youtu.be/d-diB65scQU?t=32).

## SUBMITTING PATCHES WORKFLOW

1. Write some code and push it on a branch in **tarantool/tarantool**, as usual.

To simplify the transition process we will continue to use the main repository for all development branches. External contributors continues to use their forks for branches.

Console:

```
$ git push github gh-NUMBER-SHORT-DESCRIPTION
```

2. Submit your changes as a pull request.

![pullrequests](https://cloud.githubusercontent.com/assets/1799054/24788120/6feae524-1b74-11e7-9e5f-57c73e68cfc3.png)

- Choose your branch and an appropriate release branch you want to push to (e.g. 1.7, 1.8, ...) in GitHub interface and click "New pull request".

- Add some meaningful description of your patchset and comments for potential reviewers.
  Ensure that you have a link to the original GitHub ticket in the description (e.g. "See #XXX").

- Choose at least couple people you want to get review from. GitHub is too smart and automatically suggest reviewers based on the latest `git log` for changes files. Don't forget to add somebody who has push permissions to the release branch (i.e. a gatekeeper).

- Click "Create a pull request".

![pullrequests-2](https://cloud.githubusercontent.com/assets/1799054/24788131/7bd39c96-1b74-11e7-991e-5b9fa936b0fa.png)

Console users can use [**hub**](https://hub.github.com/hub.1.html) console utility for GitHub instead:

```
$ git checkout my-branch
$ git pull-request -b 1.7
https://github.com/tarantool/tarantool/pull/NUMBER
```

3. GitHub will subscribe you to all notifications about this pull request. You can reply using a web-interface **or via email**. 

4. New versions of patches should be **force-pushed** to the same branch. GitHub will update the pull request automatically. Please be careful with force-push. I prefer to always use "git push origin from:to" syntax to avoid mistakes:

```
git push github gh-NUMBER-SHORT-DESCRIPTION:gh-NUMBER-SHORT-DESCRIPTION
```

5.  You goal is to convenience at least two people including a gatekeeper to approve your pull request (see below). The pull requests will be pushed by a gatekeeper when it meets requiring criteria.

## REVIEW WORKFLOW

1. Pull requests looks like regular tasks on GitHub. You will receive a notification email from GitHub when you is assigned to a some pull request. Fill free to review any other open pull requests according to your priorities.

2.  [Checkout the pull request](https://help.github.com/articles/checking-out-pull-requests-locally/):

```
git fetch origin pull/PULLREQUESTNUMBER/head:LOCALBRANCHNAME
```

Alternatively you can continue to use the existing workflow:

```
git fetch -a
git checkout gh-NUMBER-SHORT-DESCRIPTION
```

3. Review the branch

This part is not changing, you can continue to use your favorite CLI tools:

```
git diff origin/1.7...
vimdiff 
...
```

Alternatively you can add comments using GitHub interface.

4. Send your review comments to the author.

You can reply directly via web-interface or using email. Feel free to use instant messengers, phone, verbally or any other convenience methods to get some information from the author. Communication is so expensive and I don't want to make it even more expensive. Please remember that it is your **obligation to post the summary of your review** to the pull request on GitHub. Any discussions without written down summary are considered as time-wasting and useless.

5. Make your verdict

![github2](https://cloud.githubusercontent.com/assets/1799054/24789491/fc642b62-1b7b-11e7-921f-8c8a09c95221.png)

Choose "Approve" if the patch meets criteria. Choose "Request changes" if it doesn't.

![github2](https://cloud.githubusercontent.com/assets/1799054/24789798/1aff5370-1b7d-11e7-8676-1888d02848a6.png)

6. The patch is finally reviewed and pushed by a gatekeeper:

```
git push github gh-NAME-SHORT-DESCRIPTION:1.7
```

Pull requests is closed automatically. It is a gatekeeper obligation to close the pull request after the push.

## PROPOSAL PROCEEDING

Star this ticket on GitHub if it does work for you. Ask questions.

![github4](https://cloud.githubusercontent.com/assets/1799054/24789883/7ef12e30-1b7d-11e7-9f0c-c7115f44deee.png)

**Comment by racktear** [comment]
Do you propose that in future we will do development in forks?

**Comment by bigbes** [comment]
> Do you propose that in future we will do development in forks?

We can develop in fork and we can develop in place - that doesn't matter for creating of PR (local/remote ones)

**Comment by racktear** [comment]
@bigbes with forks you don't have to clean up branches in the main repo. It becomes developers' responsibility.

**Comment by bigbes** [comment]
Doesn't seem like much of a problem to me.
Gatekeeper can delete branches, or this can do committer..

**Comment by kostja** [comment]
OK, we tried this and changed back to email.
