### ISSUE TITLE
vinyl: implement a new write iterator

### ISSUE THREAD

**Issue by alyapunov** [tarantool/tarantool#2312]
Requirements:
1. Simple (one direction, no coio, simple page cache, immutable sources, etc)
2. Heap sort of sources
3. Avoid unnecessary allocations (return ptr to msgpack, one buffer for all pages)
4. Future possibility for collecting skipped tuples (#2129)
5. Simple and cheap range boundaries (for range split and infinirun compaction)
6. Separate file, and make unit test for it
7. Mempool and list for sources (instead of an array of them)

Needed fo #2090

**Comment by rtsisyk** [comment]
+ New write iterator should handle duplicated LSN properly (decided during meeting on 2017-04-17).
