### ISSUE TITLE
When setting snap_io_rate_limit snapshoting gets stuck

### ISSUE THREAD

**Issue by Mons** [tarantool/tarantool#2328]
1. Run a database (1.6.9-80)
2. Set snap_io_rate_limit=40 on the fly
3. Start snapshoting by any way (signal, console, daemon)

Got: snapshoting stucks with zero-size .snap.inprogress
Expected: snapshoting works

**Comment by GeorgyKirichenko** [comment]
If snap_io_rate_limit was set while snapshoting then write speed will be recalculated from begin of snapshot.
For example, if 1mb of snapshot was written, then tarantool will wait for 1mb/40 seconds after io_rate_limit was set.

**Comment by rtsisyk** [comment]
@Mons can we close this ticket?

**Comment by rtsisyk** [comment]
OK, we'll try to reproduce this problem again.

**Comment by GeorgyKirichenko** [comment]
Can't reproduce on last 1.6

**Comment by rtsisyk** [comment]
Please re-open if problem still exists.
