### ISSUE TITLE
C7: Restart seems not to work after kill. Centos 7 unit file contains unknown option.

### ISSUE THREAD

**Issue by Mons** [tarantool/tarantool#2329]
1.6.9-80

After killing tarantool with kill we got no restart by systemd

Unit file from rpm contains option, unknown by systemd:
RestartUSec

**Comment by rtsisyk** [comment]
OMG, it seems that systemd versions are not compatible with each other... I'll check this problem on CentOS 7.

**Comment by bigbes** [comment]
That seems.. unlikely.

Here is manual:
> https://www.freedesktop.org/software/systemd/man/systemd.service.html

And here is our systemd file:
>
https://github.com/tarantool/tarantool/blob/1.7/extra/dist/tarantool%40.service.in

No USec have been found.

Moreover, I've unpacked our RPM (provided from [packagecloud](
https://packagecloud.io/tarantool/1_6/packages/el/7/tarantool-1.6.9.80-1.el7.centos.x86_64.rpm))
and found nothing about  "RestartUSec";
```
2017-04-14 14:40:59 bigbes-laptop in ~/Downloads/temp
[○] → rpm2cpio.pl tarantool-1.6.9.80-1.el7.centos.x86_64.rpm | cpio -idmv
./etc/logrotate.d/tarantool
./etc/sysconfig/tarantool
./etc/tarantool
./etc/tarantool/instances.available
./etc/tarantool/instances.available/example.lua
./usr/bin/tarantool
./usr/bin/tarantoolctl
./usr/lib/systemd/system/tarantool@.service
./usr/lib/tmpfiles.d/tarantool.conf
./usr/lib64/tarantool
./usr/share/doc/tarantool-1.6.9.80
./usr/share/doc/tarantool-1.6.9.80/README.md
./usr/share/licenses/tarantool-1.6.9.80
./usr/share/licenses/tarantool-1.6.9.80/AUTHORS
./usr/share/licenses/tarantool-1.6.9.80/LICENSE
./usr/share/man/man1/tarantool.1.gz
./usr/share/man/man1/tarantoolctl.1.gz
./usr/share/tarantool
./var/lib/tarantool
./var/log/tarantool
21898 blocks
2017-04-14 14:41:02 bigbes-laptop in ~/Downloads/temp
[○] → cat ./usr/lib/systemd/system/tarantool@.service | grep Restart
# 4. Restart tarantool@example service
Restart=on-failure
RestartSec=100ms
```

**Comment by bigbes** [comment]
That seems.. unlikely.

Here is manual:
> https://www.freedesktop.org/software/systemd/man/systemd.service.html

And here is our systemd file (hint: no USec here):
> https://github.com/tarantool/tarantool/blob/1.7/extra/dist/tarantool%40.service.in

Moreover, I've unpacked our RPM (provided from [packagecloud](https://packagecloud.io/tarantool/1_6/packages/el/7/tarantool-1.6.9.80-1.el7.centos.x86_64.rpm)) and found nothing about  "RestartUSec":

```
2017-04-14 14:40:59 bigbes-laptop in ~/Downloads/temp
[○] → rpm2cpio.pl tarantool-1.6.9.80-1.el7.centos.x86_64.rpm | cpio -idmv
...
./usr/lib/systemd/system/tarantool@.service
...
2017-04-14 14:41:02 bigbes-laptop in ~/Downloads/temp
[○] → cat ./usr/lib/systemd/system/tarantool@.service | grep Restart
# 4. Restart tarantool@example service
Restart=on-failure
RestartSec=100ms
```

**Comment by fb929** [comment]
```
$ systemctl show tarantool | grep -i restart
Restart=no
RestartUSec=100ms
```

https://www.freedesktop.org/software/systemd/man/systemctl.html

> and time settings are always exposed as properties ending in the "…USec" suffix even if a matching configuration options end in "…Sec", because microseconds is the normalized time unit used by the system and service manager.


everything works as it should =)

but, if I'm kill tarantool manually "kill \<pid\>", systemd not restart daemon
It is probably worth changing the settings Restart=on-failure to Restart=always

**Comment by rtsisyk** [comment]
> It is probably worth changing the settings Restart=on-failure to Restart=always

OK, we will check the best practices for this value on RPM and Debian systems and change our .service file according to the results.

As a temporary workaround, you can override this setting by creating a "drop-in" file in `/etc/systemd/system/tarantool@example.service.d/`. Please see comments in `/usr/lib/systemd/system/tarantool.service` and systemd documentation for additional information.

**Comment by rtsisyk** [comment]
I researched this problem:

<table>
<tr><th>Package</th><th>Debian</th><th>Fedora</th></tr>
<tr><td>PostgreSQL</td><td>Restart=always</td><td>default</td></tr>
<tr><td>MySQL</td><td>Restart=on-failure, RestartPreventExitStatus=1</td><td>-</td></tr>
<tr><td>MariaDB</td><td>missing systemd files</td><td>Restart=on-abort, RestartSec=5s</td></tr>
<tr><td>Redis</td><td>Restart=always</td><td>default</td></tr>
<tr><td>MongoDB</td><td>default</td><td>default</td></tr>
<tr><td>nginx</td><td>default</td><td>default</td></tr>
<tr><td>Apache2</td><td>Restart=on-abort</td><td>default</td></tr>
<tr><td>Postfix</td><td>default</td><td>default</td></tr>
<tr><td>Sendmail</td><td>missing systemd files</td><td>default</td></tr>
<tr><td>Samba</td><td>default</td><td>default</td></tr>
</table>

The most packages have default settings for `Restart=` option both on Debian and Fedora.
Tarantool should follow the best practices of major distributions. Please use "drop-in" to override the default value.  See comments in [/usr/lib/systemd/system/tarantool.service](https://github.com/tarantool/tarantool/blob/49f67f680e8587f64b30de6cdf67628ac2bd060e/extra/dist/tarantool%40.service.in#L1-L31) and refer systemd [documentation](https://www.freedesktop.org/software/systemd/man/systemd.unit.html) for additional information. CoreOS website has a [good tutorial](https://coreos.com/os/docs/latest/using-systemd-drop-in-units.html) about drop-ins.
