### ISSUE TITLE
Need to fix warnings in SQL branch

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#2338]
Current SQL branch [1] contains thousands of warnings which must be reviewed and fixed.

[1] - https://github.com/tarantool/tarantool/tree/kyukhin/sql2-exp

**Comment by rtsisyk** [comment]
I think we can disable `-Wall -Wextra` for this third-party code for 1.8.0 alpha release.

**Comment by kyukhin** [comment]
That's it. We can't bear it anymore. Setting `prio1` and assignee.
