### ISSUE TITLE
Identifiers in SQL

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#2345]
Possible problems with identifiers in SQL statements.

Identifiers may be enclosed in 'single' quotes or in [brackets].
With single quotes this is bad because it cannot be consistent --
sometimes things in single quotes must be interpreted as string
literals rather than identifiers. With brackets this is bad
because it will make it impossible to to use []s for arrays (Issue#2237).
(Identifiers may also be enclosed inside `grave accents` which
I consider bad but I predict that others will say it is okay.)
I do not know whether this makes the identifiers truly "delimited",
so I am not saying this is a duplicate of Issue#2123 Allow ANSI SQL delimiters only.
box.sql.execute("CREATE TABLE 'te3' ('s1' INT PRIMARY KEY);")
box.sql.execute("INSERT INTO 'te3' VALUES ('1');")
box.sql.execute("SELECT * FROM te3 WHERE s1 = 's1';")
Result: []

Many non-letter characters, e.g. $ and «, are legal
in column identifiers but not in table identifiers.
This suggests that the rules for space identifiers
("expected letters, digits or an underscore") are
applicable to tables but not to columns, an inconsistency.
box.sql.execute("CREATE TABLE te4 (te4$ INT PRIMARY KEY);")
box.sql.execute("CREATE TABLE te4$ (te4$ INT PRIMARY KEY);")
Result: first statement succeeds, second statement fails.

Regular identifiers are stored the way they are typed,
they should be stored in upper case. (Delimited identifiers,
however, should be stored the way they are typed.)
This is recommended because delimited identifiers should be case sensitive.
Suppose you create table a, which becomes A.
This will not conflict with (delimited) "a", which becomes a --
when you search for a, you get A.
The standard, of course, does not tell you how to store.
But it does say that you do the comparison after folding to upper case,
which would have the same effect.
There is a lot of variation about this issue:
MySQL is confusing for historical reasons.
ttps://dev.mysql.com/doc/refman/5.6/en/identifier-case-sensitivity.html
PostgreSQL folds to lower case.
ttps://www.postgresql.org/docs/8.4/static/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS
DB2 folds to upper case:
https://www.ibm.com/support/knowledgecenter/en/SSEPGG_9.7.0/com.ibm.db2.luw.sql.ref.doc/doc/r0000719.html
Oracle folds to upper case:
https://docs.oracle.com/cd/B28359_01/server.111/b28286/sql_elements008.htm#SQLRF00223
SQL Server is case insensitive, or sensitive, depending on the database collation
https://docs.microsoft.com/en-us/sql/relational-databases/databases/database-identifiers
box.sql.execute("CREATE TABLE a (s1 INT PRIMARY KEY);")
box.space._space:select()
Result: 'a'

Delimited identifiers are case insensitive.
(Delimited identifiers are also subject to a restriction that they
cannot containing spaces or special characters which I consider bad
but it is necessary for compatibility with NoSQL restrictions.)
box.sql.execute([[CREATE TABLE "te5" ("s1" INTEGER PRIMARY KEY)]])
box.sql.execute([[SELECT "S1" FROM "TE5"]])
Result: no error

The identifier rules should be the same for all objects.
If a rule applies to table identifiers, then it should also
apply to column identifiers, index identifiers, constraint
identifiers, and trigger identifiers. Thus if maximum length
= 64 bytes, and it's stored as upper case, then those are the only
rules that the user needs to know. The user will not enjoy
learning a different set of rules for each different type of
object, unless it is necessary. I know that sometimes it is necessary.

**Comment by pgulutzan** [comment]
Right.

**Comment by pgulutzan** [comment]
See also:
Make all ANSI SQL keywords reserved. #2116
Allow ANSI SQL delimiters only #2123
Only allow identifiers which are valid in Tarantool. #2126
Increase identifier maximal length. #2127

**Comment by kyukhin** [comment]
Fixed. Tested by 56d01c8
