### ISSUE TITLE
Operators in SQL

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#2346]
Possible problems with operators in SQL statements.

If any arithmetic operator is applied to a string,
and cast(string to number) is impossible, it is treated
as 0. This is abnormal, for example MySQL would accept
the string but produce a warning, and Lua would produce
an error.
```
box.sql.execute("VALUES ('#1' - '2a');")
Result: [-2]
```
`1 IS 1` is legal. It's not standard, the original idea was that
there should be a way to show that we don't really
mean "x = NULL" when we say "x IS NULL", so there's
a special keyword that's supposed to apply only for
NULLs. I don't know whether anybody else allows "1 IS 1".
And, in this case, "IS" does not exactly mean "=".
```
box.sql.execute("VALUES (NULL IS NOT NULL, NULL = NOT NULL);");
Result: [0, null]
```
Multiplying inf times 0 yields NULL. Perhaps that's
correct, perhaps the result should be NaN, perhaps
the result should be 0 -- but nobody knows the rules.
This is the sort of confusion that occurs when one
allows non-standard results, like inf.
```
box.sql.execute("VALUES (1e333 * 0);")
Result: [null]
```
Shifting a real value by zero bits results in -1.
("<<" is a non-standard operator meaning "shift bits
left", which is not a bad thing in itself.)
```
box.sql.execute("VALUES (1e300, 1e300 << 0);")
---
- - [1e+300, -1]
```

**Comment by kyukhin** [comment]
Let's emit error if conversion of string literal to number is impossible?

**Comment by pgulutzan** [comment]
I am somewhat more fanatical -- a string is not a number.
Why would I ever want to say '1' (string) when I can say 1 (number)?
Or, to turn this into a big question:
Do you want to be compatible with NoSQL (in that case '1' is not 1)?
Do you want to be compatible with standard SQL (in that case '1' is not 1)?
Do you want to be compatible with SQLite (in that case '1' can be 1)?
For 1.8.0 I suppose the temporary answer is no,no,yes.
But for 1.8.1 I hope the final answer is yes,yes,no.

**Comment by Korablev77** [comment]
Now we've introduced strict types and strings and numbers are compatible only if string literal is really number like '34'. So we can do things like:
```
CREATE TABLE t (id INT PRIMARY KEY);
INSERT INTO t VALUES ('123');
SELECT * FROM t WHERE t 1 < '124';
```

Most DBs also allow to do such things, so we decided to follow their way. If we get many complaints from users, I guess this behaviour can be changed/updated.

**Comment by kyukhin** [comment]
So, moving to wishlist then.

**Comment by Korablev77** [comment]
I guess I can close this issue.

VALUES ('#1' - '2a'); -- not valid anymore
```
tarantool> VALUES ('#1' - '2a');
---
- null
- 'Type mismatch: can not convert 2a to numeric'
...
```
1 IS 1 -- not legal anymore
```
tarantool> VALUES (1 IS 1);
---
- null
- Syntax error near '1'
...
```
Multiplying inf times 0 yields NULL -- I guess this should be documented

VALUES (1e300, 1e300 << 0); -- not legal anymore
```
tarantool> VALUES (1e300, 1e300 << 0)
---
- null
- 'Type mismatch: can not convert 1.0e+300 to integer'
...
```
