### ISSUE TITLE
Error during a column addition with a UNIQUE constraint

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#2349]
It is not legal to add a column with a UNIQUE constraint.
```
box.sql.execute("CREATE TABLE te9 (s1 INT PRIMARY KEY);")
box.sql.execute("ALTER TABLE te9 ADD COLUMN s2 INT UNIQUE;")
````
Result = error: Cannot add a UNIQUE column

**Comment by kyukhin** [comment]
I confirm first part of the issue.

As per second part: is it correct? Should we keep this behaviour?

**Comment by pgulutzan** [comment]
Regarding the second part: I suppose it is possible to
CREATE UNIQUE INDEX separately, so it is not important.
But I can say
box.sql.execute("ALTER TABLE t377 add column s2 int check (s2 > 5)")
that is, adding a column with a constraint is usually
legal, so I don't understand why UNIQUE is different.

**Comment by kyukhin** [comment]
#2607 submitted

**Comment by kyukhin** [comment]
Looks like this is a limitation of SQLite which prohibits changing UNIQUE columns.
This restriction should be removed.

**Comment by ImeevMA** [comment]
Currently, this problem cannot be resolved, since we cannot add a column via ALTER TABLE. See #3075

**Comment by ImeevMA** [comment]
Blocked by #3075

**Comment by Totktonada** [comment]
The issue is about ability to add an UNIQUE constraint. The linked patch declares that an UNIQUE contraint 'cannot be specified yet'. How the patch resolves the issue? @romanhabibov, can you clarify, please?

BTW, instead of `Closes #xxxx, #yyyy` use the following syntax:

```
Closes #xxxx
Closes #yyyy
```

This way GitHub will automatically close both issues, not only the first one.

**Comment by romanhabibov** [comment]
> cannot be specified yet
This issue was opened when the <ALTER TABLE ADD COLUMN> statement was not yet removed from the Tarantool. My last patch returns <ALTER TABLE ADD COLUMN> and add ability to specify constraints (UNIQUE in particular) with column description in this statement simultaneously.

**Comment by Korablev77** [comment]
Closed via https://github.com/tarantool/tarantool/commit/6cff9025909529febeff2f04bf714f70bd3a79e1
