### ISSUE TITLE
SQL create table statement

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#2350]
Some problems with CREATE TABLE in SQL.

There is no error if two constraints have the same name.
Temporarily this might be okay because constraints
are not stored and it is impossible to drop constraints;
however, eventually those things will be supported, and
I believe it would not be difficult to prevent duplication
within a single CREATE TABLE statement.
box.sql.execute("CREATE TABLE te10 (s1 INT, CONSTRAINT c PRIMARY KEY (s1), CONSTRAINT c CHECK (s1 > 0));")
Result = no error.

The requirement, that column definitions must come before
table constraint definitions, is not standard. I've often
seen constraints defined immediately after the definitions
of the columns that they immediately affect.
box.sql.execute("CREATE TABLE te11 (s1 INT, CHECK (s1 > 0), s2 INT);")
Result = syntax error

Table-names that begin with 'sqlite' are still not allowed.
I think it's okay to have a prefix that's reserved for
Tarantool's use, but if it's necessary, that prefix should
be 'tarantool'.
box.sql.execute("CREATE TABLE sqlite_1 (s1 INT PRIMARY KEY);")
Result: error: 'object name reserved for internal use ...'

**Comment by kyukhin** [comment]
Okay, probably we should check for constraint name duplication (post 1.8.0)

I don't think this is critical.

Yes, agree. But I believe that we have no reserved prefixes at all. BUT for future, let's reserve `tarantool_` prefix.

Confirmed.

**Comment by kyukhin** [comment]
This issue was superseded by #3503, #3504.

We now allow any prefixes in table names.
