### ISSUE TITLE
Automatic data type conversion in SQL

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#2352]
The current description of automatic data type conversion in the SQL
manual takes a full two pages. The affinity rules are non-standard,
complex, and unnecessary.

Eventually, I expect, we will have data types and will
enforce them so that, for example, 'wombat' is not allowed
in an INTEGER column. But, recognizing that is difficult,
I suggest that in version 1.8.0 there should be only one
data type -- SCALAR. This is not a standard data type, of
course. Let it be mandatory to supply the data type, let
it be illegal to state any other data type (for example
the SQLite rule "if CHAR is buried somewhere in the word,
it is TEXT" does not apply in Tarantool).

I admit that this means most of the SQLite test suite
would have to be changed.

**Comment by kyukhin** [comment]
Won't this break compatibility w/ major DBMS? and obfuscate customers migration to Tarantool SQL?

**Comment by pgulutzan** [comment]
You're right, my suggestion is bad.
I'll close it myself.
