### ISSUE TITLE
SQL: error dropping a temporary table

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#2354]
DROP TABLE on a temporary table causes error =
" SQL logic error or missing database".
box.sql.execute("CREATE TEMPORARY TABLE te20 (s1 INT PRIMARY KEY);")
box.sql.execute("DROP TABLE te20;")
Result = error

**Comment by mikkiek** [comment]
I've similar issue using docker container.
After connetion to container:

unix/:/var/run/tarantool/tarantool.sock> \set language sql
---
- true
...

unix/:/var/run/tarantool/tarantool.sock> \set delimiter ;
---
- error: Can not install delimiter for net box sessions
...

unix/:/var/run/tarantool/tarantool.sock> CREATE TABLE table1 (column1 INTEGER PRIMARY KEY, column2 VARCHAR(100));
---
...

unix/:/var/run/tarantool/tarantool.sock> INSERT INTO table1 VALUES (1, 'A')
---
- error: SQL logic error or missing database
...
----------------
Looks like nothing work except CREATE TABLE.

**Comment by kyukhin** [comment]
This bug should be re-pharased like that: Ban TEMPORARY tables in parser for alpha-2.

**Comment by kyukhin** [comment]
Temporary tables are already banned.
