### ISSUE TITLE
SQL: DROP VIEW [RESTRICT|CASCADE]

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#2355]
Some problems with views in SQL.

A view is not dropped when its underlying table is dropped.
This is not uncommon, other DBMSs also allow out-of-date views.
But it is not helpful, either.
box.sql.execute("CREATE TABLE te22 (s1 INT PRIMARY KEY);")
box.sql.execute("CREATE VIEW te23 AS SELECT * FROM te22;")
box.sql.execute("DROP TABLE te22;")
box.sql.execute("SELECT * FROM te23;")
Result = Error: No such table: main.te22

It is not possible to insert or update or delete from a view, although sometimes
a possible substitution is to create an INSTEAD OF trigger.

**Comment by kyukhin** [comment]
Should we drop related views when table is dropped? (even if view selects from multiple tables).

**Comment by pgulutzan** [comment]
The big question is: for any type of object,
if object#1 refers to object#2, and object#2
is dropped or altered, what should happen to
object#1? The standard's usual answer is:
you should specify RESTRICT (it's illegal to
drop unless you drop object#1 first), or
CASCADE (you must drop object#2 -- and if
object#3 depends on object#2 you must also
drop object#3 and so on). But for this small
question: it's not a disaster if the view is
depending on something that doesn't exist.
So you can close -- but if so, please say "it is a
policy decision that we will not restrict or
cascade", so I can document it.

**Comment by pgulutzan** [comment]
Also: I can create a view that refers to a table column that doesn't exist.
CREATE TABLE te44 (s1 INT PRIMARY KEY);
CREATE VIEW ve44 AS SELECT s2 FROM te44;

**Comment by morrme** [comment]
sql server has an addon clause to the CREATE VIEW statement: WITH SCHEMABINDING , that prevents this behavior.

**Comment by kyukhin** [comment]
Superseded by #3491.
