### ISSUE TITLE
SQL insert statement

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#2358]
It is possible to use the same column twice.
It is possible that this is a duplicate of other cases
where Tarantool allows improper repetitions, but I'm
not sure of that.
box.sql.execute("CREATE TABLE te27 (column1 INT PRIMARY KEY);")
box.sql.execute("INSERT INTO te27 (column1, column1) VALUES (33,'a');")
box.sql.execute("SELECT * FROM te27;")
Result = [33]

**Comment by kyukhin** [comment]
is it a bug?

**Comment by pgulutzan** [comment]
It is a bug, although not important.
