### ISSUE TITLE
SQL update statement

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#2359]
Some possible problems with the SQL UPDATE statement.

It is possible to SET the same column twice,
although this may be the same sort of complaint
as I made for INSERT ("It is possible to use the same
column twice").
box.sql.execute("CREATE TABLE te28 (s1 INT PRIMARY KEY, s2 INT);")
box.sql.execute("INSERT INTO te28 VALUES (1, 2);")
box.sql.execute("UPDATE te28 SET s2 = 3, s2 = 4;")
box.sql.execute("SELECT s2 FROM te28;")
Result = [4]

It is possible to use UPDATE to change the primary-key value,
which is okay, but disallowed in NoSQL.
Since I assume that the reasons for disallowing in NoSQL
are still valid, I believe it should be disallowed in SQL too.
box.sql.execute("CREATE TABLE te29 (s1 INT PRIMARY KEY);")
box.sql.execute("INSERT INTO te29 VALUES (1);")
box.sql.execute("UPDATE te28 SET s1 = 2;")

* If column s1 is indexed and is in the WHERE clause, and column s1 is being updated,
 and  there are many rows to update, and the table is a view which is being updated
 with an INSTEAD OF trigger, failure and unexplained changes of data may occur. For example:
 box.sql.execute("CREATE TABLE te30 (s1 INT PRIMARY KEY, s2 INT);")
 box.sql.execute("CREATE VIEW te31 AS SELECT s1, s2 FROM te30 ORDER BY s1 DESC;")
 box.sql.execute("CREATE TRIGGER te32 INSTEAD OF UPDATE ON te31 BEGIN UPDATE te30 SET s1 = new.s1, s2 = new.s2; END;")
 box.sql.execute("INSERT INTO te30 VALUES (1,1),(3,2),(5,3),(7,4);")
 box.sql.execute("UPDATE te31 SET s1 = s1 + 1;")
 box.sql.execute("SELECT * FROM te30;")
Result: error = error: 'UNIQUE constraint failed: te30.s1', and SELECT returns
---
- - [3, 2]
  - [5, 3]
  - [7, 4]
  - [8, 4]
...

An optional clause OR ROLLBACK|ABORT|REPLACE|FAIL|IGNORE is legal but does nothing.

**Comment by kyukhin** [comment]
Confirmed. Changing PK's columns should be prohibited.

**Comment by pgulutzan** [comment]
The first problem (setting the same column twice) is fixed. The third problem (unique constraint failure) is not a bug. So only one problem remains: changing the primary key.

**Comment by Korablev77** [comment]
In SQL update consists from DELETE + INSERT, so I don't think that it is really problem.

**Comment by kyukhin** [comment]
@pgulutzan I agree w/ Nikita. I don't see why we should ban PK update.

**Comment by pgulutzan** [comment]
Nikita Pettik is correct. So there are no more problems. I think that this can be closed.
Regarding my statement that "An optional clause OR ROLLBACK|ABORT|REPLACE|FAIL|IGNORE is legal but does nothing." -- now the clauses cause deleting, I decided that is a separate issue, #3566

**Comment by kyukhin** [comment]
Closing then.
