### ISSUE TITLE
SQL replace statement

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#2360]
REPLACE can cause duplicates of primary keys. Example:
box.sql.execute("CREATE TABLE te34 (s1 INT PRIMARY KEY, s2 INT);");
box.sql.execute("INSERT INTO te34 VALUES (1,1);");
box.sql.execute("CREATE TABLE te35 (s1 INT PRIMARY KEY, s2 INT);");
box.sql.execute("INSERT INTO te35 VALUES (1,1);");
box.sql.execute("CREATE TRIGGER te36 BEFORE INSERT ON te34 FOR EACH ROW BEGIN DELETE FROM te35; END");
box.sql.execute("REPLACE INTO te34 VALUES (1,NULL);");
box.sql.execute("SELECT s1 FROM te34;")
Result: 2 rows, both containing [1].

**Comment by kyukhin** [comment]
Confirmed
