### ISSUE TITLE
SQL clauses related to groups and aggregates

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#2364]
Some possible problems with GROUP BY and HAVING,
and aggregations.

SELECT s1,s2 FROM t GROUP BY s1; is legal.
SELECT s1 AS q FROM t GROUP BY q; is legal.
SELECT s1 FROM t GROUP by 1; is legal.
I am aware that other DBMSs act this way,
but want everyone to be aware it is not normal.

There is no warning if NULLs are ignored.
I'm not even sure whether generating warnings
is possible, so I don't know whether this is easy.
Not all DBMSs handle this.
box.sql.execute("CREATE TABLE te39 (s1 INT PRIMARY KEY, s2 INT);")
box.sql.execute("INSERT INTO te39 VALUES (1,1);")
box.sql.execute("INSERT INTO te39 VALUES (2,NULL);")
box.sql.execute("SELECT SUM(s2) FROM te39;")
Result: [1] which is the right answer but I also hoped for:
"Warning: "null value eliminated in set function"
or something like that.

HAVING is not legal without GROUP BY.
box.sql.execute("CREATE TABLE te40 (s1 INT PRIMARY KEY);")
box.sql.execute("INSERT INTO te40 VALUES (1);")
box.sql.execute("SELECT s1 FROM te40 HAVING s1 = 1;")
Result =  error: a GROUP BY clause is required before HAVING

**Comment by kyukhin** [comment]
I think warning might significantly slow down execution time as extra checks would be injected in hot places. So, doubt it will be implemented nearest future.

So, this is a bug if HAVING requires GROUP BY?

**Comment by pgulutzan** [comment]
Yes, HAVING should still be possible.
Of course there's only one group, so
SELECT SUM(s1) FROM t HAVING SUM(s1) > 0;
would either return the sum, or nothing.

**Comment by kshcherbatov** [comment]
**1. Warning:**
MySQL - no warning
Oracle - no warning
Postgres - no warning
SQLite - no warning
MSSqlServer - no warning

**2. Having:**
Only MySQL support such syntax:
others:
Oracle: ORA-00979: not a GROUP BY expression
PostgreSQL: ERROR: column "te40.s1" must appear in the GROUP BY clause or be used in an aggregate function Position: 9
SQLite: could not prepare statement (1 a GROUP BY clause is required before HAVING)
MS SQL 2017: Column 'te40.s1' is invalid in the HAVING clause because it is not contained in either an aggregate function or the GROUP BY clause.

**Comment by kshcherbatov** [comment]
Won't fix.
Ok by @kostja

**Comment by kshcherbatov** [comment]
@pgulutzan please, give an example where "HAVING without GROUP BY" doesn't work, but should.

**Comment by pgulutzan** [comment]
Yes, HAVING should still be possible.
Of course there's only one group, so
SELECT SUM(s1) FROM t HAVING SUM(s1) > 0;
would either return the sum, or nothing.

**Comment by kshcherbatov** [comment]
@pgulutzan, hi!
Should we also support such cases?
```
CREATE TABLE te40 (s1 INT, s2 INT, PRIMARY KEY (s1,s2))
INSERT INTO te40 VALUES (1,1)
INSERT INTO te40 VALUES (2,2)
```
```
SELECT (SELECT s1 FROM te40 LIMIT 1) FROM te40 HAVING min(s1) > 0
```

```
SELECT 1 from te40 having min(s1) > 0
```

```
SELECT date() from te40 having min(s1) > 0
```

It is not so trivial to implement for SQLITE as a first part with aggregate functions only.
Decided to merge patch containing only aggregates feature and create new task if required.

**Comment by pgulutzan** [comment]
"SELECT 1 from te40 having min(s1) > 0;", where the select list has only a literal, fits the suggested requirement that the select list can contain aggregates and/or literals but nothing else. The other two examples do not fit that requirement. There are a few other things that could also be acceptable but I don't want to suggest that non-trivial implementation work would be worth the time. If you can do aggregates e.g. "SELECT MIN(s1) FROM te40  HAVING MIN(s1) > 0;", but you cannot do "SELECT 1 from te40 having min(s1) > 0;", I agree that is good enough for this year.
