### ISSUE TITLE
SQL order by clause

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#2365]
ORDER BY 1 is legal.
"ORDER BY ordinal" got deprecated in the standard long ago.
As far as I know, most (all?) DBMSs still accept it.
But, since "ORDER BY expression" is now legal, it's supposed
to mean "order by the literal value 1", which is always the same.
```
box.sql.execute("CREATE TABLE te41 (s1 INT PRIMARY KEY, s2 INT);")
box.sql.execute("INSERT INTO te41 VALUES (1, 2);")
box.sql.execute("INSERT INTO te41 VALUES (2, 1);")
box.sql.execute("SELECT * FROM te41 ORDER BY 2 DESC;")
Result = rows are in order by the second column.
```

LIMIT without ORDER BY is legal.
Since there should be no guarantee what order the
result rows will be in, this is non-standard.
```
box.sql.execute("CREATE TABLE te42 (s1 INT PRIMARY KEY, s2 INT);")
box.sql.execute("INSERT INTO te42 VALUES (1, 2);")
box.sql.execute("INSERT INTO te42 VALUES (2, 1);")
box.sql.execute("SELECT * FROM te42 LIMIT 1;")
Result: 1 row.
```

**Comment by kyukhin** [comment]
Is it a bug?

**Comment by pgulutzan** [comment]
I call it a bug, but expect you'll want to
get other opinions.

**Comment by kyukhin** [comment]
ORDER BY <ordinal> is available in multiple DBMS, so let's keep it.
LIMIT w/o ORDER BY may be needed to have a sneak peak from some table, w/o any warranties.

So, I guess this issue won't be implemented.
