### ISSUE TITLE
SQL pragma statement

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#2367]
PRAGMA encoding=utf16le; is allowed,
but Tarantool only allows UTF8 encoding.
box.sql.execute("PRAGMA encoding=utf16le;")
Result = no error

**Comment by kyukhin** [comment]
Confirmed. Let's block it.

**Comment by Gerold103** [comment]
PRAGMA do not raise error, if PRAGMA is unknown. In fact, in the original sqlite I can write:
```
sqlite> PRAGMA unexisting_pragma=ON;
sqlite>
```
and there is no an error.

**Comment by kyukhin** [comment]
I think that we need to emit warning message on any unknown PRAGMA
