### ISSUE TITLE
Support JSON objects stored in SQL tables

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#2369]
I don't get as much information about database objects
as I want, using SQL. I know that INFORMATION_SCHEMA
will come (Issue#2244), but in the meantime I have to
depend on sqlite_master (which shows only triggers),
on PRAGMA table_info (which doesn't show constraints),
and on SELECT ... FROM _space. The immediate flaw is
that the format column is binary garbage. I know that
flattening is hard (I've done it), but at least I
should get what I'd get with box.space._space:select(),
stripping spaces and newlines.
box.sql.execute("SELECT * FROM _space where id=320;")
Result = - - [320, 1, '_cluster', 'memtx', 0, !!binary gA==, !!binary koKkbmFtZaJpZKR0eXBlo251bYKkbmFtZaR1dWlkpHR5cGWjc3Ry]

**Comment by kyukhin** [comment]
Confirmed.
