### ISSUE TITLE
Returning a tuple result from SQL

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#2370]
box.space.t:insert{1} returns a tuple but
box.sql.execute("INSERT INTO t VALUES (1)") does not.
Obviously this is not a bug.
But I assume there is a good reason that
box.space.t:insert (and certain other functions)
returns a tuple, so as a feature request I'll ask:
if number of rows = 1, and statement = INSERT or
UPDATE or DELETE, return the row.

**Comment by kyukhin** [comment]
Confirmed.

**Comment by kevpie** [comment]
What are the possibilities of supporting a `RETURNING` clause from `INSERT, UPDATE, DELETE` and returning all the modified tuples?

This a most useful feature and could be a nice addition.  Also when used along with CTEs you have a good way to return the outcome of INSERTS, UPDATES or DELETES and pass them into INSERTS, UPDATES or DELETES.  Utilizing this type of SQL query can simplify many scenarios.  
Another neat thing may be even a way to directly enqueue deleted or updated tuples into a queue if they where addressable through SQL.

**Comment by kshcherbatov** [comment]
Decided to implement another way and later. With RETURNING clause. #3649
