### ISSUE TITLE
Do not force-use quota at commit

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#2379]
Currently vinyl invokes vy_quota_use() twice per statement: once at prepare, second time at commit. 
Avoid double invocation, vy_quota_use() at prepare should be sufficient.

**Comment by kostja** [comment]
We decided this problem is not imporant enough to fix it. We will return to it in scope of performance tests.

**Comment by rtsisyk** [comment]
Affects #2629

**Comment by kostja** [comment]
Won't fix.
