### ISSUE TITLE
Master and slave data differs significantly

### ISSUE THREAD

**Issue by zaglex** [tarantool/tarantool#2393]
Hello!

I have such situation:

1. I've setup master-slave replication between two tarantool instances. Replica is configured with 'read_only' option.
2. After some time of working (several days) replica and master are not in sync, i.e. data on replica significantly differs from data on master. 
Details:
- replication.lag is 0, replication status is 'follow'
- replica continues fetching fresh data from master, there are no error messages in logs.

What do I want:
I'd like to have a tool which allows to know whether replication is really ok: status variables, error messages in log etc. And, of course, I'd like to know what could break the replication.

P.S. It is not a single case, we are catching this problem again and again.   

Tarantool version details:

Tarantool 1.6.9-80-g2672373
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/opt/tarantool -DENABLE_BACKTRACE=ON
Compiler: /usr/bin/x86_64-pc-linux-gnu-gcc /usr/bin/x86_64-pc-linux-gnu-g++
C_FLAGS:-pipe -O2 -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-format-truncation -fno-gnu89-inline
CXX_FLAGS:-pipe -O2 -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-format-truncation -Wno-invalid-offsetof

**Comment by zaglex** [comment]
Please, help us with this issue. We can't switch from 1.6 to 1.7, because we have production deployment and moving to 1.7 can cause some problems (at least we've encountered this issue https://github.com/tarantool/tarantool/issues/2454 during 1.7. testing).

Does it look like replication bug in 1.6.9 or we are doing something wrong?

**Comment by kostja** [comment]
Hello guys, it is a very general description of the problem, so it's hard to help. We need steps to reproduce the problem to be able to look into it. Or we could provide support. The ticket database is not a good place for free support requests however, we try to provide support of this kind on our telegram channel. Could we continue there?

**Comment by kostja** [comment]
As discussed during support meeting: please check if your snapshot daemon works correctly and your xlog files are not deleted before they are relayed to the slave. 1.6.9 does not check for a "gap" in xlog files history created by incorrectly configured snapshot daemon. This is addressed in 1.7 with gh-748

**Comment by zaglex** [comment]
Problem is solved now.
Indeed xlogs were being removed by snapshot daemon before relaying to the slave. This happened because we were using setting snapshot_count = 1.
And actually relay was not silent: it wrote "exiting relay loop" to the log (but without any explanations).
