### ISSUE TITLE
Please upgrade to LuaJit-2.1b3 - No more garbage memory limit problems

### ISSUE THREAD

**Issue by suporteavancado** [tarantool/tarantool#2396]
It was realeased yesterday with a wonderful news:
"The major addition over beta2 is the LJ_GC64 mode JIT compiler
backend contributed by Peter Cawley. Previously, only the x64 and
ARM64 interpreters could be built in this mode. This mode removes
the 32 bit limitation for garbage collected memory on 64 bit systems."

https://www.freelists.org/post/luajit/LuaJIT210beta3

**Comment by bigbes** [comment]
Well, LJ_GC64 is still in heavy beta and is limited to x64/arm64 only.

**Comment by rtsisyk** [comment]
Yeah, we will try to upgrade our fork soon.

**Comment by rtsisyk** [comment]
I've updated LuaJIT to 2.1.0-beta3 in 1.7 branch. Please note that LJ_GC64 is still off. We don't think that this feature makes sense with the current implementation of GC in LuaJIT.

**Comment by Fedora7** [comment]
@rtsisyk could you provide more information about why the LJ_GC64 feature doesn't make  sense with the current implementation of GC ?  Thanks
