### ISSUE TITLE
Improve vinyl/recovery.test

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#2397]
Already done:
- statistics
- split
- dump

To add:
- coalesce
- data is restored fully -  for every index (so, multiple indexes)
- data from mem filies is not lost
- empty space is recovered correctly
- test that infiniruns are added correctly

All this works while:
- shutdown happens during dump
- shutdown happens during compact
- shutdown happens during split/coalesce
- the number of worker threads is > 2, so that there may be more than one compact in progress
- the number of secondary keys is large and shutdown happens at dump of any key
- memory quota is lowered after restart (Vinyl must not stall while replaying WAL in this case, it should forcefully consume quota instead)

**Comment by locker** [comment]
> Already done:
> - statistics
> - split
> - dump
> 
> To add:
> - coalesce

To test that, make vinyl/coalesce.test.lua restart the server and check the space content after recovery. Actually, we should test range splitting there as well, as this test needs to split ranges before it
can coalesce them, anyway.

> - data is restored fully -  for every index (so, multiple indexes)
> - data from mem filies is not lost
> - empty space is recovered correctly
> - test that infiniruns are added correctly
> 
> All this works while:
> - shutdown happens during dump
> - shutdown happens during compact

> - shutdown happens during split/coalesce

This doesn't make sense: split/coalesce doesn't involve a worker thread anymore - it is done instantly in tx.

> - the number of worker threads is > 2, so that there may be more than one compact in progress

Already done: vinyl/vinyl.lua sets vinyl_write_threads to 3.

> - the number of secondary keys is large and shutdown happens at dump of any key

Already tested by vinyl/partial_dump.test.lua

> - memory quota is lowered after restart (Vinyl must not stall while replaying WAL in this case, it should forcefully consume quota instead)

Extend vinyl/recovery_quota.test.lua
