### ISSUE TITLE
vinyl: remove slice reference counting

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#2398]
Remove slice reference counting, instead, pin slices in memory in run iterators, when it's necessary to fetch data with a coeio task. Wait for all pinned slices in compact task completion hook, before removing all the old slices. 

By getting rid of slice reference count, it'll be possible to get rid of run->refs as well, and leave only run->slice_count, since at no time a run will be used by a slice which is hanging around.

**Comment by locker** [comment]
Fixed by d40d611d57dd00b1a580c6df146cde9a9a8a0485
