### ISSUE TITLE
Never use Lua error() in the code, use box.raise() instead.

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#240]
Try to use Tarantool error codes for as many errors as possible.
This way error message text is file/line independent, and it's easy to catch an error based on its error code.

**Comment by rtsisyk** [comment]
This idea is controversial. box.error() is a part of box. I can't raise box.error() in src/lua/ modules.

**Comment by kostja** [comment]
This is implemented in a different spirit with removal of EXTERNAL_UNWIND.
