### ISSUE TITLE
net.box doesn't update pseudo-space objects on schema refresh

### ISSUE THREAD

**Issue by racktear** [tarantool/tarantool#2401]
Let's suppose I store a space object like this:

```lua
local test = conn.space.test
```

And then a schema update happens somewhere on the server. Then the `test` variable will point to a dangling pseudo-space object. This likely happens because on schema update, the net.box just replaces `conn.space.test`, instead of updating the existing object.

This may cause weird problems if users don't take it into account.

**Comment by rtsisyk** [comment]
OK, let's try to patch ALTER to re-use existing box.space objects, then apply the same fix to net.box.

**Comment by rtsisyk** [comment]
1.7.5-257-g300bc7dac
