### ISSUE TITLE
vinyl: add a test case for 1.7.4 vylog format

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#2407]
Add a test case which would start from 1.7.4 vinyl data and index files, as well as vylog.
This is necessary to preserve backward compatibility of format changes in 1.7.5+

**Comment by rtsisyk** [comment]
It should be prio1 instead of prio3.

**Comment by rtsisyk** [comment]
Closed by 59a6eb3cdafc810556d56d7442c2967e829c5c22
