### ISSUE TITLE
Do not use MP sort if the number of rows in the table is below a large constant (like 10k rows)

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#2431]
Starting MP threads slows down tarantool start by a significant margin.
We measured that not starting these threads speeds up test-run 1.3-1.5 times.
Hence, do not use parallel sort for small tables, OpenMP threads are started on demand.

**Comment by alyapunov** [comment]
Fixed, but I found no difference in performance neither for tests nor for a simple txt launch.

**Comment by kostja** [comment]
@alyapunov the fix is necessary to avoid starting openmp threads by a simple alter/create space with no rows.

**Comment by Totktonada** [comment]
For the sake of completeness: before it was fixed in tarantool, it was worked around in test-run [here](https://github.com/tarantool/test-run/commit/e1b6a710c91fb86e479093e3767c42b7304b8a5b).
