### ISSUE TITLE
Extend net.box to support SQL

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#2435]
This ticket supersedes box.sql.execute(). When this ticket is implemented, box.sql.execute() should be removed. net.box.self:execute() should be used instead.

### Error handling

All functions return an object on success or nil on error. Misuse of Lua API raises a Lua error.

### Execute an SQL statement

`status, res = con:execute(sql, params, options)`

This single function can be use to execute a statement with or without parameters, create a prepared statement and execute it immediately, reuse an existing prepared statement, execute a statement (prepared or not) and open a cursor for it. It always sends a single IPROTO command to the server, IPROTO_SQL_EXECUTE. IPROTO_SQL_EXECUTE accepts SQL text or prepared statement id and the list of parameters, and may either prepare or execute an existing statement.

* `sql` - is a text string with optional placeholders
* `params` is an array or map of positioned or named parameters (we will support positioned parameters only at first
* `options` - a map with execution options. For now the options may be empty, but
  in future they may include such things as opening a server side cursor, automatically preparing a statement or reusing an exising prepared statement, etc.

The status is nil on error. In this case res contains an error message, and non-nil
on success.

### Obtain execution status, affected rows.

A successful SQL statement may or may not return a result set. 
The result value of execute therefore contains the following parameters:

* `result.description` - a Lua table with a description of result set rows, or nil for a statement which returns no result set, such as CREATE/DROP or INSERT/DELETE
* `result.rowcount` - the number of result set rows. nil in case of server-side cursor associated with a result set
* `result.rows` - return a Lua table with result set rows, or nil if there was a cursor opened for the result set (see the next function)
* `result:__pairs()` - returns a Lua compatible iterator over result set rows; 
* `result:close()` - explicitly close the server side cursor, if any, not waiting for the garbage collector to kick in

### Prepared statement API

There is no separate prepared statement or cursor API. To reuse an SQL text as a prepared statement, pass an option to execute(). To use a server-side cursor pass another option to execute(), and use __pairs() meta-method to iterate over result set rows.

### Miscellaneous: transaction control, getting the list of tables, etc.

None. Use execute() for everything.

**Comment by Gerold103** [comment]
Why `__pairs()`? Why not `pairs()` or `next()`?

**Comment by kostja** [comment]
@Gerold103, I meant it's a metamethod, so it's a method of the metatable really, not the real Lua method.

**Comment by bigbes** [comment]
> result:__pairs() - returns a Lua compatible iterator over result set rows;

`__pairs`/`__ipairs` are ignored in LuaJIT without COMPAT_52 (+ it's metamethods, not methods). We are using `:pairs()` for now

> All functions return an object on success or nil on error
> The status is nil on error. In this case res contains an error message, and non-nil
> ...

`false` is better for this cases. It's standard practice in Lua community.

**Comment by kyukhin** [comment]
This issue is mostly implemented.
Not implemented parts extracted into #3082 and #2592
