### ISSUE TITLE
vinyl: secondary idx cursor with vlsn int64_max skips keys

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#2442]
Branch ultra-hack, test vinyl/errinj. During cursor lookup to the primary index by the secondary key the newer key can be added to the space between the lookuped and previous. However the cursor doesn't see it and doesn't restore iterators.

**Comment by rtsisyk** [comment]
A test case by @Gerold103:
[0001-vinyl-add-test-on-incorrect-pk-lookup.patch.txt](https://github.com/tarantool/tarantool/files/1028229/0001-vinyl-add-test-on-incorrect-pk-lookup.patch.txt)

Please apply this patch if you find a solution for this problem.

**Comment by rtsisyk** [comment]
Blocked by #2090

**Comment by alyapunov** [comment]
#2090 goes to 1.7.6, this must go too.

**Comment by rtsisyk** [comment]
Yes, this ticket should be in 1.7.6, because it requires #2060.

**Comment by Gerold103** [comment]
If a key was read from a read_iterator, then it appears in a cache. If the same key was updated during reading primary index, then in a secondary index the same key disappears from the cache. So the update can be detected by checking cache. If the key just read from the secondary index has disappeared from the secondary index cache, then it was updated and must be reread.
