### ISSUE TITLE
std::bad_alloc in case of error in new will cause panic

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#2451]
Memtx indexes are created via `new` operator. But `new` operator can throw `std::bad_alloc` and tarantool will catch it in `catch(...)` and panic.

**Comment by mkostoevr** [comment]
Indexes are created using `memtx_*_index_new` since 1187b586dc634ac1c9b757df79a8d60a6d219073, indexes don't throw exceptions since 50bf3988623dbce70f6cd54778a5e6165eefbc4a.

Closed as outdated.
