### ISSUE TITLE
Function call return serialization errors on function return values

### ISSUE THREAD

**Issue by hengestone** [tarantool/tarantool#2453]
Calling a tarantool server side function that returns a table that includes functions returns a serialization error to the client:
`"unsupported Lua type 'function', server: localhost:3301 ... etc"`

I think it would be more useful in the general case to do what e.g. `pl.pretty` does and replace function values with e.g. `function: 0x413f00a0`

**Comment by kostja** [comment]
* Conrad Steenberg <notifications@github.com> [17/05/21 08:30]:
> Calling a tarantool server side function that returns a table that includes functions returns a serialization error to the client:
> `"unsupported Lua type 'function', server: localhost:3301 ... etc"`
> 
> I think it would be more useful in the general case to do what e.g. `pl.pretty` does and replace function values with e.g. `function: 0x413f00a0`

The reason it's not done is that it may lead to subtle programming
errors when one stores a function persistently in a tuple and will
expect it to retrieved back safely.

You can set actions for serialization errors by extending the 
encoder, I will look up how.

-- 
Konstantin Osipov, Moscow, Russia, +7 903 626 22 32
http://tarantool.org - www.twitter.com/kostja_osipov

**Comment by kostja** [comment]
Roman, this seems to be not documented. Please dig up how to do it and open a documentation bug.

**Comment by lenkis** [comment]
Issue moved to doc repo.

**Comment by alyapunov** [comment]
test

  
>Суббота, 20 мая 2017, 23:38 +03:00 от Conrad Steenberg <notifications@github.com>:
> 
>Calling a tarantool server side function that returns a table that includes functions returns a serialization error to the client:
>"unsupported Lua type 'function', server: localhost:3301 ... etc"
>I think it would be more useful in the general case to do what e.g. pl.pretty does and replace function values with e.g. function: 0x413f00a0
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .
> 
--
Александр Ляпунов

**Comment by alyapunov** [comment]
gggg
 
Best Regards,
Victoria
