### ISSUE TITLE
Put several cooccurring member to vy_run

### ISSUE THREAD

**Issue by alyapunov** [tarantool/tarantool#2457]
Now the vy_run itself is unusable without several essences:
```
const struct key_def *key_def;
const struct key_def *user_key_def;
struct tuple_format *format;
struct tuple_format *upsert_format;
uint64_t column_mask;
bool is_primary;
bool is_last_level;
struct vy_run_env *run_env;
```
Adding this members will significantly simplify usage of vy_slice/vy_run.

**Comment by rtsisyk** [comment]
This approach may not work, because vy_run can be used from multiple threads, but tuple_format is not thread-safe.
