### ISSUE TITLE
Read only mode

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#246]
Make it possible to switch a node into read-only mode (only accepts updates from replication)
via an admin command.

This is necessary now when server replication is master-master.

**Comment by bigbes** [comment]
Anyone can do it with:
```lua
ffi.cdef[[
extern int is_ro;
]]
function set_ro()
    ffi.C.is_ro = true;
end
```

**Comment by rtsisyk** [comment]
`box.cfg { read_only = true | false; }`
