### ISSUE TITLE
Open files limit in default config

### ISSUE THREAD

**Issue by alyapunov** [tarantool/tarantool#2465]
Users that try to use tarantool+vinyl in production inevitably face max-open-files limit (1024 by default) and suffer from tarantool's DoS at some point. The limit is not so important for memtx since memtx uses descriptors almost only for sockets, but vinyl can open maximal possible number of files and halt forever being unable to start dump/compact processes.

As I understood, tarantool has default config for system-d and maybe other configs/examples that user usually use.

We should set/increase the limit in default config/examples to at least 64k in order to prevent users from making a mistake at the first time of usage.

**Comment by rtsisyk** [comment]
[tarantool@.service](https://github.com/tarantool/tarantool/blob/1.7/extra/dist/tarantool%40.service.in) provides an example to how to increase NoFILE limit under systemd. Anyway, I agree that we should increase the default value to 64k or something like that.
