### ISSUE TITLE
log: logging to syslog should use syslogfd

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#2466]
The default syslog API tarantool uses is blocking. This doesn't respect log_nonblock option. This leads to trash in production, when syslog logging is enabled and it is necessary to enable a higher log level. We need to use syslogfd instead, to ensure log_nonblock affects logging to syslog.

This patch may be necessary to backport 1.6.

**Comment by bigbes** [comment]
Simplier to write our own syslog client implementation (that'll support our needs) as described https://tools.ietf.org/html/rfc5424
Why? We won't have any way for syslog to behave like our "file" logging. It assumes, that we can write at most "PIPE_BUF" bytes at once in a "sync" way.
This operation can't be ported to socket IO, so it can't be ported to be a part of current syslog API.
Summing up: simple enough option is to support part of syslog API in library, that'd suit us well.

**Comment by bigbes** [comment]
BTW I suggest to implement this first, since it'll help us to design our new logging API

**Comment by kostja** [comment]
Eugene,  I don't see any problem using syslog fd yet. Let's discuss.

**Comment by rtsisyk** [comment]
1.7.4-460-ga362eff6a
