### ISSUE TITLE
log: avoid truncating log messages in case of partial write in non-blocking mode.

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#2474]
In non-blocking mode, when the socket/file descriptor is not ready to accept new data, the logger should ensure the message is never truncated - but entire messages are dropped. In other words, we should never chop messages when writing them to the log, even if log_nonblock is true.

A request by @mons, observed in production.

**Comment by rtsisyk** [comment]
prio3 ?

**Comment by locker** [comment]
Currently, the `log_nonblock` option doesn't work if logging is done via syslog (although it's going to be fixed soon - see #2466), i.e. it only makes sense for pipe- and file-based loggers. Write to a file opened with `O_APPEND` is guaranteed to be atomic - see `write(2)`. Write to a pipe of size `PIPE_BUF` or less (<= 4K, typically) is guaranteed to be atomic as well - see `pipe(7)`. That said, the issue described here doesn't seem to have ever existed.
