### ISSUE TITLE
Thread naming in tarantool

### ISSUE THREAD

**Issue by alyapunov** [tarantool/tarantool#2475]
On centos7 all tarantool threads are shown as 'tarantool' in process list and it's not convenient. One user shown me about 30 of threads with 'tarantool' names, but maybe it was a wrong tool, I'm not sure. They asked me to fix it but first of all it must be proven.

**Comment by rtsisyk** [comment]
I think you saw OpenMP threads.

**Comment by rtsisyk** [comment]
I re-checked this problem on CentOS 7 - it actually was OpenMP threads.
