### ISSUE TITLE
Broken base64 encoding

### ISSUE THREAD

**Issue by zloidemon** [tarantool/tarantool#2478]
Incorrect working base64 in tarantool, encoding usually adding extra `0A` byte (`\n`) after every 52 symbol.
I recommend to see that [screenshot](http://i.imgur.com/E3PvmzL.png)

```
Tarantool 1.7.3-771-g980d30092
Target: Darwin-x86_64-Debug
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/Users/vg/.opt -DENABLE_BACKTRACE=OFF
Compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
C_FLAGS: -Wno-unknown-pragmas -fexceptions -funwind-tables -fno-common -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Werror
CXX_FLAGS: -Wno-unknown-pragmas -fexceptions -funwind-tables -fno-common -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Werror
```

Scripts for testings:

```python
import base64

def hex_dump(src, length=16):
    FILTER = ''.join([(len(repr(chr(x))) == 3) and chr(x) or '.' for x in range(256)])
    lines = []
    for c in xrange(0, len(src), length):
        chars = src[c:c+length]
        hex = ' '.join(["%02x" % ord(x) for x in chars])
        printable = ''.join(["%s" % ((ord(x) <= 127 and FILTER[ord(x)]) or '.') for x in chars])
        lines.append("%04x  %-*s  %s\n" % (c, length*3, hex, printable))
    return ''.join(lines)

def show(st):
    print(st)
    print("len: {}".format(len(st)))
    print(hex_dump(base64.standard_b64encode(st)))

str1 = 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
show(str1)
str2 = 'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB'
show(str2)
str3 = 'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC'
show(str3)
show(str1 + str2)
```

```lua
local digest = require('digest')

function hex_dump(buf)
   for i=1,math.ceil(#buf/16) * 16 do
      if (i-1) % 16 == 0 then io.write(string.format('%08X  ', i-1)) end
      io.write( i > #buf and '   ' or string.format('%02X ', buf:byte(i)) )
      if i %  8 == 0 then io.write(' ') end
      if i % 16 == 0 then io.write( buf:sub(i-16+1, i):gsub('%c','.'), '\n' ) end
   end
end

function show(str)
    print(str)
    print("len: ", string.len(str))
    print(hex_dump(digest.base64_encode(str)))
end

str1 = 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
show(str1)
str2 = 'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB'
show(str2)
str3 = 'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC'
show(str3)

show(str1 .. str2)
```

**Comment by kostja** [comment]
This byte is harmless but makes the result look good. What is your problem with it?

**Comment by zloidemon** [comment]
Problem is implementation JWT server side on tarantool. While making signature of header and payload you will get incorrect signature. [JWT.io](https://jwt.io/#debugger) has debugger to check your signature and data in requests. For example, if you have more than one backends and pass through token to python backend which has generated by tarantool. Token will invalid in process of validation.

**Comment by bigbes** [comment]
It's not broken, it follows the specification - https://tools.ietf.org/html/rfc4648#section-3.3

**Comment by zloidemon** [comment]
@bigbes Hmmm.. I seem you are missed with task. This issue isn't related to https://github.com/tarantool/tarantool/issues/2479 where need to add support to trim paddings.

**Comment by bigbes** [comment]
It documents both (newline and pads)

**Comment by Totktonada** [comment]
There are at least two cases when user expects non-formatted base64: generating JWT tokens, passing base64 within HTTP headers.

On the other side, formatted base64 is needed for convenience in interactive usage and for prettify at writing to a file.

My guess is that formatting should be optional and disabled by default.

My http-headers case workarounded for now with `base64_str = base64_str:gsub('\n', '')`.

**Comment by rtsisyk** [comment]
1.7.5-112-gcd4e26d43
