### ISSUE TITLE
module.h is not updated automatically

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#2481]
I have Ubuntu 14.04 and gcc 4.8. I say:

git clone -b 1.8 https://github.com/tarantool/tarantool.git ~/tarantool-1.8
cd ~/tarantool-1.8
git submodule init
git submodule update --recursive
cmake . 
make

Result =
"
/home/pgulutzan/tarantool-1.8/test/app-tap/module_api.c: In function ‘test_say’:
/home/pgulutzan/tarantool-1.8/test/app-tap/module_api.c:36:2: error: implicit declaration of function ‘say_verbose’ [-Werror=implicit-function-declaration]
  say_verbose("test verbose");
  ^
/home/pgulutzan/tarantool-1.8/test/app-tap/module_api.c: At top level:
cc1: error: unrecognized command line option "-Wno-format-truncation" [-Werror]
cc1: all warnings being treated as errors
make[2]: *** [test/app-tap/CMakeFiles/module_api.dir/module_api.c.o] Error 1
make[1]: *** [test/app-tap/CMakeFiles/module_api.dir/all] Error 2
make: *** [all] Error 2
"

This did not occur in a build from source a few days ago.
This does not occur with Ubuntu 17.04 and gcc 6.3.

**Comment by Gerold103** [comment]
Please, try to remove src/module.h and then rebuild. Sometimes it helps.

**Comment by pgulutzan** [comment]
The comment by Gerold103 is correct. So, is this a duplicate of an issue that developers are already aware of?

**Comment by Gerold103** [comment]
Yes. It is well known problem, that module.h must be regenerated after changes in the module api.

**Comment by rtsisyk** [comment]
1.7.4-317-gc533975dc
