### ISSUE TITLE
replication: heartbeat messages

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#2484]
Send heartbeat messages in relay to update applier's lag and idle every second. This should also prevent replication from hanging during configuration changes, such as iptables/routing/virtual ip/whaterver. On applier side, if there are no heartbeats more than a heartbeat timeout seconds, reconnect automatically.

Lag is the primary indicator of replication health. A master sends heartbeat to the replica every replication_heartbeat_interval seconds, and the replica is programmed to reconnect automatically if it doesn’t see heartbeat messages more often than replication_reconnect_interval seconds.  Therefore, in a healthy replication setup, lag should never exceed replication_reconnect_interval: if it does, either your replication is lagging seriously behind, because master is running ahead of the slave, or the network link between replicas is down.

**Comment by rtsisyk** [comment]
To implement this feature in backward-compatible way the replication client should check remote version first and start sending pings only when server supports them.

**Comment by rtsisyk** [comment]
Our replication client is implemented in synchronous style using coio functions, so there is no easy way to send pings in background. This ticket is complicated (5+ days) and requires significant refactoring.

**Comment by kostja** [comment]
I actually disagree. You don't send pings in the "to" channel, you send pings in the "from" channel, and then you respond to them in the "to" channel.

**Comment by rtsisyk** [comment]
> I actually disagree. You don't send pings in the "to" channel, you send pings in the "from" channel, and then you respond to them in the "to" channel. So pings and acks are more or less the same.

"from" channel doesn't know remote client's version, so this approach can't be implemented in backward-compatible way.

**Comment by kostja** [comment]
As discussed on the phone:
- we patch relay's reader fiber to keep reading and decoding anything that comes from the applier
- the applier knows the relay version, it comes in the greeting. If the version is > 1.7.5, the applier creates a "heartbeat" fiber, to send acks to the relay. Alternatively, the heartbeat fiber can be created at all times, but do nothing if the version is old.

The heartbeat fiber runs an infinite loop, in which:
- it definitely sends a message back even if there are no rows from the master once in heartbeat_timeout
- it the meanwhile, it sleeps on the cond, and if there is a row from the master, applier fiber signals the cond (after applying the row).

A new configuration variable is introduced, replication_heartbeat_interval, which is 1 by default (we need to benchmark it (c) :)). 0 means that we send individual message acks, non-zero means we only send acks once in an interval. We should always send acks once in a while even if there are no messages!

What the ack contains: replicaset_vclock.

**Comment by rtsisyk** [comment]
1.7.4-444-gf672ce4e0
