### ISSUE TITLE
Make space format updates transactional

### ISSUE THREAD

**Issue by knazarov** [tarantool/tarantool#2488]
Currently the space format is stored in _space, field 7. If I update it in box.begin()..box.commit(), I get this:

```sh
2017-05-30 15:53:59.223 [39278] main/101/test3.lua F> Space _space does not support multi-statement transactions
```

Since this is a regular memtx space update, maybe we can allow it inside transactions?

**Comment by mkostoevr** [comment]
The `space:format` can be called in a transaction since 1f7b0d6577f49ae417447ddcf2a43bfd77fa6eef.

BTW all `box.schema` DDL functions are transactional since 198178101da6263f5d37d496afd1955431b09fc4.
