### ISSUE TITLE
Test vylog write error handling

### ISSUE THREAD

**Issue by locker** [tarantool/tarantool#2490]
Check that:
- A single vylog failure does not break vinyl dump/compaction permanently.
- An error to commit a run does not leave garbage in vylog.
- Unfinished runs we failed to discard due to vylog write error are removed from vylog after restart.
- Error logging index create/drop/truncate does not result in the operation failure: the operation is either logged along with the next write to vylog or after restart.

**Comment by rtsisyk** [comment]
f1862699a5802afe14ba53dd91a7cfabdbcc2e01
