### ISSUE TITLE
sql: all indexes have field type "scalar", even if it can be more specific ("number"...)

### ISSUE THREAD

**Issue by Khatskevich** [tarantool/tarantool#2494]
all indexes have field type "scalar"

For example:
```
box.sql.execute('CREATE TABLE t(a int PRIMARY KEY)')
.....
box.space._index:select{}
.....
[518, 0, 'sqlite_autoindex_t_1', 'tree', {'unique': true, 'sql': ''}, [[0, 'scalar']]]
```
in this case we get "scalar" index, while it is obvious that the index field type should be "integer".

Tarantool should use information from schema while creating indexes.

**Comment by Khatskevich** [comment]
blocked by #1557

**Comment by kyukhin** [comment]
Not blocked anymore
