### ISSUE TITLE
socket:recvfrom does not work as expected

### ISSUE THREAD

**Issue by cyanide-burnout** [tarantool/tarantool#2501]
Following code always returns nil:

```lua
local socket = require('socket')

local function getBinary(value)
    return (value:gsub('..', function (value) return string.char(tonumber(value, 16)) end))
end

function getProfile(number, address, port)
    local result = false

    local handle = socket('AF_INET', 'SOCK_DGRAM', 'udp')
    local requests = { getBinary('9000'), getBinary('f000') }

    handle:bind('0.0.0.0')
    for _, request in pairs(requests) do
        handle:sendto(address, port, request)
        local response, sender = handle:recvfrom(256)
        if response == nil or response:sub(1, 1) == string.char(tonumber('f1', 16)) then
            result = true; break
        end
    end
    handle:close()

    return result
end
```

**Comment by IlyaMarkovMipt** [comment]
You should specify port in bind function. Otherwise, it will be bound to random port.
Another way to solve your problem is get that random port from handle:name()
`handle:sendto(address, handle:name().port, request)`

**Comment by cyanide-burnout** [comment]
If you check my code, the binded port should be random. Destination port for sendto should be defined.
Ok, I will try to do next:
`
  handle:bind('0.0.0.0', handle:name().port)
  handle:setsockopt('SOL_SOCKET', 'SO_RCVTIMEO', 200000000)

  for _, request in pairs(requests) do
    handle:sendto(address, port, request)
    local response, sender = handle:recvfrom(256)
    if response == nil then
      result = handle:errno()
      break
    end
`

**Comment by GeorgyKirichenko** [comment]
You got EAGAIN because all sockets operations are nonblocking by default. And there is no data in socket on time of a recvfrom call and EAGAIN is the expected behavior. Please try to use `handle:nonblock(false)' after socket initializaion

**Comment by kostja** [comment]
No feedback -> please reopen if we still can help you with this bug.

**Comment by cyanide-burnout** [comment]
Solution:
`handle:sendto(value, 49690, data)
handle:readable(2)
data, address = handle:recvfrom(2048)`
