### ISSUE TITLE
Transaction rollback should give a warning?

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#2528]
```
#!/usr/bin/env tarantool

local fiber = require('fiber')

box.cfg{log_level=7} -- debug
box.schema.create_space('s')
box.space.s:create_index('pk')

box.begin()

box.space.s:insert({1, 2, 3})
fiber.sleep(0)

-- check tr
if pcall(box.begin) then
    box.commit()
    error('rolled back')
end

-- commit tr
box.commit()

print(box.space.s:get(1))
```

The output that may be related:

```
2017-06-19 21:09:28.088 [12957] main/101/tnt-txn-yield.lua D> LuajitError at /var/tmp/portage/dev-db/tarantool-9999/work/tarantool-9999/src/lua/utils.c:946
2017-06-19 21:09:28.088 [12957] main/101/tnt-txn-yield.lua F> /home/alex/tmp/./tnt-txn-yield.lua:17: rolled back
```

Don’t sure what is the first line, but I don’t see any warning about rolling back the transaction.

Note: Tarantool segfaults on the case avobe from time to time. I’ll file separate issues about the crash.

Tarantool 1.8.1-183-gc221e7c85
Target: Linux-x86_64-Debug
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_BACKTRACE=yes
Compiler: /usr/bin/x86_64-pc-linux-gnu-gcc /usr/bin/x86_64-pc-linux-gnu-g++
C_FLAGS:-march=native -O2 -ggdb -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -mavx -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -fno-gnu89-inline -Werror
CXX_FLAGS:-march=native -O2 -ggdb -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -mavx -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Werror

**Comment by rtsisyk** [comment]
Yes, it should, but it doesn't:

```
static void
txn_on_yield_or_stop(struct trigger * /* trigger */, void * /* event */)
{
	txn_rollback(); /* doesn't throw */
}
```

**Comment by rtsisyk** [comment]
This bug can be test via box-tap suite

**Comment by sharonovd** [comment]
Upvoting, this is disgusting
