### ISSUE TITLE
vinyl: Don't bloat tx manager with rows when doing space:pairs()

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#2534]
Since the conflict manager still keeps every row, and doesn't have gaps, don't add every row read through a consistent read view to the conflict manager, otherwise you can easily run out of memory when iterating over a medium size space.

These rows are useless in the tx manager anyway.

**Comment by alyapunov** [comment]
RO transaction were removed by 9c57ed6191cf3ebb8ad769f5aaa73d5c88a9e1ed.
My original fix was aba925a17405562a3f51f0f339c8b60b2c30940b and it worked fine with the :pairs() case but it didn't get through code review.

**Comment by alyapunov** [comment]
Blocked by #2700

**Comment by locker** [comment]
Fixed by a31c2c10347cbd131395ebdd93d64069923f5286
