### ISSUE TITLE
Can not start on Debian 8/9 if dbus package is not presented.

### ISSUE THREAD

**Issue by amdei** [tarantool/tarantool#2538]
Tarantool can not start on Debian 8/9 if package `dbus` is not presented.
In logs there is only the notorious

    got signal 15 - Terminated

Issue is in a way tarantool determines if it runs under systemd:
It is done by parsing output of `systemctl`, run by `trantool` user , but it can't start under non-root.

    # sudo -u tarantool systemctl
    Failed to get D-Bus connection: No such file or directory

Issue is in absence of dbus socket - it is not presented if dbus service is not presented:

    systemctl status --all dbus.socket

But if `dbus` package is installed - all start to work as a charm instantly.

Probably other way of determining if trantool run under systemd is required.

**Comment by rtsisyk** [comment]
Confirmed

Probably we should add an option to tarantoolctl to avoid daemonization, e.g. `tarantoolctl start example --foreground`. Actually I plan to remove /usr/bin/tarantoolctl wrapper for systemd case, but it is complicated task.

**Comment by rtsisyk** [comment]
I realized that `--foreground` will break `tarantoolctl start INSTANCE` -> `systemctl  start tarantool@INSTANCE` redirect. Any better ideas how to detect systemd? Nothing from [1] is portable between all distros...

[1]: https://unix.stackexchange.com/questions/18209/detect-init-system-using-the-shell/164092#164092

**Comment by rtsisyk** [comment]
1.7.4-319-g90a16b0e3
