### ISSUE TITLE
Duplicate key error after failure to create with too many columns

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#2549]
I have Ubuntu 14.04.
I have Tarantool 1.8 pulled from source today.
I execute these requests:

column_count = 256

box.sql.execute([[drop table t1]])

create_statement = 'CREATE TABLE t1 ('
for i = 1,column_count do
  if i > 1 then create_statement = create_statement .. ',' end
  create_statement = create_statement .. 's' .. i .. ' INT'
  if i == 1 then create_statement = create_statement .. ' PRIMARY KEY' end
  end
create_statement = create_statement .. ')'
box.sql.execute(create_statement)

box.sql.execute('CREATE TABLE t1 (s1 int primary key)')

Result: - error: 'Can''t create or modify index ''sqlite_autoindex_t1_1'' in space ''t1'':
    too many key parts'

Second result: - error: Duplicate key exists in unique index 'name' in space '_space'

This was done because we want to document the maximum number
of columns in a table. In SQLite
it is 2000. But if it is 255 in Tarantool, I doubt anyone will complain.

Nevertheless, the second CREATE TABLE statement should have succeeded.

**Comment by TheAviat0r** [comment]
@pgulutzan , can you reproduce it on latest 1.8? I executed with column_count = 1900 and everything was ok, table was successfully created.

```
box.sql.execute([[drop table t1]])

create_statement = 'CREATE TABLE t1 ('
for i = 1,column_count do
if i > 1 then create_statement = create_statement .. ',' end
create_statement = create_statement .. 's' .. i .. ' INT'
if i == 1 then create_statement = create_statement .. ' PRIMARY KEY' end
end
create_statement = create_statement .. ')'
box.sql.execute(create_statement)
```

**Comment by pgulutzan** [comment]
I cannot reproduce it on latest 1.8.
