### ISSUE TITLE
[replica]: Logs need more info

### ISSUE THREAD

**Issue by zloidemon** [tarantool/tarantool#2555]
Env: CentOS 7, tarantool 1.7.4-214-geb9066f

```
2017-06-29 11:59:44.852 [21453] main/101/tarantoolctl I> Adding 1188 keys to TREE index 'skip' ...
2017-06-29 11:59:44.854 [21453] main/101/tarantoolctl I> Space 'updates': done
```

Not possible to use tarantool console and tarantool not respond. That is issue with master server because server is not available, would like to see error messages every 3-5 sec (depends on replica reconnection timeout):

```
Master replica 127.0.0.1 not respond...
```

**Comment by kostja** [comment]
We can add additional log messages before connecting to a replica, unless we have one already. I'm not sure your analysis of the problem is correct.

**Comment by kostja** [comment]
I don't know what happened here. E.g. it could be a timeout in connect to replica, or somewhere else. @zloidemon please come up with a test case and reopen the bug.
