### ISSUE TITLE
An easy way to start the database from SQL

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#2559]
Currently, we have an SQL mode of interactive console which allows you to type SQL statements right away.

tarnatool> SELECT 1;
...

This, however, doesn't work seamlessly to user, since SQL is only available when the box (the database) is already started with ```box.cfg{}```, so a user has to switch to Lua, to turn the database on, and only then switch back to SQL to type SQL statements.

We need a simple way to start "example" database from SQL, or change the user story when SQL is in use, so that switching to and from Lua is no longer necessary. For example, we could recommend using an instance file which has the database pre-configured. A follow up of gh-2430

**Comment by rtsisyk** [comment]
Let's invoke box.cfg() with default options on the first access to box.XXX instead of raising an error().
