### ISSUE TITLE
Documentation: Python example using (pg) SQL

### ISSUE THREAD

**Issue by AlexMikhalev** [tarantool/tarantool#2563]
Hello devs,

I have tried to follow SQL tutorial and then connect to Tarantool instance using Python with aim to use python pandas.from_sql, however I didn't manage to connect using pgsql or sqlachemy.
1) Is it possible to use SQL in Tarantool without Lua?
2) It would be good to have documentation Howto connect to Tarantool using sqlalchemy. 

Regards,
Alex

**Comment by kyukhin** [comment]
Hello Alex,

1. Right now the answer is NO, you always start w/ Lua console. However in the nearest future we'll commit an extension to binary protocol (IPROTO) which will allow to execute SQL w/o Lua marks
2. AFAIK, sqlalchemy is based on ODBC, which is not yet implemented. We'll probably implement ODBC in future
