### ISSUE TITLE
sql: problem with iteration during modification

### ISSUE THREAD

**Issue by Khatskevich** [tarantool/tarantool#2564]
In case we iterate over data set and delete some elements, it is possible that iterator skip some items (or may even return some of them two times)

Example:
```
local function sql(zSql)
       box.sql.execute(zSql)
end
box.internal.sql_create_function("sql", sql)
box.sql.execute("CREATE TABLE (a PRIMARY KEY) ")
box.sql.execute("INSERT INTO t values(1),(2),(3),(4),(5),(6),(7),(8),(9),(10)")
box.sql.execute("SELECT sql('DELETE FROM t WHERE a = '||a ) FROM t WHERE a>5")
box.sql.execute(" SELECT a from t ") -- returns 1, 2, 3, 4, 5, 7, 9
```
The result of the last cmd is `1, 2, 3, 4, 5, 7, 9` instead of `1, 2, 3, 4, 5`
That means that iterator skipped some items because deletes.

blocked by #1796
(resolving #1796 should fix this issue actually)

**Comment by kyukhin** [comment]
Not blocked anymore.

**Comment by Khatskevich** [comment]
Just tested, It works (possibly after stable iterators fix)
