### ISSUE TITLE
Bulk delete

### ISSUE THREAD

**Issue by foverzar** [tarantool/tarantool#2568]
Is there a way to issue a bulk delete operation? Currently, looking through the docs, I can only think of creating a stored procedure that selects required records and iterates over them, calling `...delete(tuple[1])` for each record.

**Comment by kyukhin** [comment]
space:truncate() will clear a space:
https://tarantool.org/doc/1.7/book/box/box_space.html#box-space-truncate

**Comment by rtsisyk** [comment]
Tarantool intentionally doesn't provide special API for bulk operations. You can a) Send a batch of requests using network protocol, like HTTP pipelining b) Use Lua or C stored procedure.
