### ISSUE TITLE
Sometimes can not start on system boot (starting too early?)

### ISSUE THREAD

**Issue by amdei** [tarantool/tarantool#2581]
Tarantool 1.7.4.227
Debian 9 stretch

If I assign specific IP address as a listen (e.g. '192.168.8.8:3344'), _sometimes_ tarantool can not start on system boot:

    journalctl -xb | grep -3 'uri for bind'
> 2017-07-07 18:57:48.144 [732] main/101/tarantoolctl F> can't initialize storage: can't resolve uri for bind, called on fd -1
> systemd[1]: tarantool@example.service: Main process exited, code=exited, status=1/FAILURE

Manual start after system boot went well.

**Comment by amdei** [comment]
More logs:

> 2017-07-07 19:07:25.325 [752] main/101/tarantoolctl C> log level 6
> 2017-07-07 19:07:25.325 [752] main/101/tarantoolctl I> mapping 268435456 bytes for tuple arena...
> 2017-07-07 19:07:25.326 [752] main/101/tarantoolctl evio.cc:339 !> SystemError can't resolve uri for bind, called on fd -1: Success
> 2017-07-07 19:07:25.326 [752] main/101/tarantoolctl F> can't initialize storage: can't resolve uri for bind, called on fd -1

**Comment by amdei** [comment]
I changed in

    /lib/systemd/system/tarantool@.service

from

    After=network.target

to

    After=network-online.target

but it does not help. :(

**Comment by rtsisyk** [comment]
OK, we need to find a way to reproduce this problem.

**Comment by amdei** [comment]
Looks like easiest way to reproduce these issue is:

1. Configure host machine to get address from DHCP
1. Configure network interface with `allow-hotplug` option (default on Debian), so the corresponding `/etc/network/interfaces` would look like this:

> allow-hotplug ens33
> iface ens33 inet dhcp

In this case `networking.service` will not know when this _hotplug_ will happens, and return control immediately. So, trantool starts before DHCP obtains address.

To overcome the issue it is enough to configure interface with `auto` option.

Although this is a way to reproduce the issue, it is clear miconfiguration - no one in reality will configure server to get address with DHCP and specify specific IP in listen address.
However the same issue holds true for DNS name in listen address - in will not be resolved during tarantool startup in described scenario.

May be it is worth to mention proper interface configuration in documentation with warning about `allow-hotplug` option?

**Comment by zloidemon** [comment]
It even doesn't work with the lo device

```
ox.cfg {
    listen = '127.0.0.1:3301',
    memtx_memory = 134217728,
    checkpoint_interval = 3600,
    checkpoint_count = 3,
    force_recovery = true,
}
```

Tarantool version is 1.7.6-9-g4e960f7

```
2017-11-23 17:23:44.835 [1202] main/101/test evio.cc:339 !> SystemError can't resolve uri for bind, called on fd -1: Success
2017-11-23 17:23:44.836 [1202] main/101/test F> can't initialize storage: can't resolve uri for bind, called on fd -1
```

**Comment by zloidemon** [comment]
Works for me now
```
[Unit]
Description=Tarantool Database Server
After=network.target
Requires=network-online.target
Documentation=man:tarantool(1)
```
