### ISSUE TITLE
sql: implement prepared statements cache

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#2592]

**Comment by Gerold103** [comment]
The cache do not affect the API.
Where to implement:
- Inside `sqlite3Prepare` and `sqlite3_finalize`. Such way allows to use cache both for iproto and lua requests (`sql_prepare_and_execute` and `lua_sql_execute`);
- Inside tarantool as a special subsystem.

How to implement:
```C
enum { PREPARED_STATEMENTS_MAX = 100 };
struct prepared_stmts {
    hash_t table = new_hash(); /* To fast search by SQL. */
    heap_t heap = new_heap(); /* To fast sort by id. */
    uint32_t id_sequence = 0;
};
hash_key_t = const char *; /* sql request. */
hash_value_t = struct {
    uint32_t schema_version;
    uint32_t id;
    sqlite3_stmt *stmt;
};

heap_key_t = uint32_t; /* id. */
heap_value_t = hash_elem_t;
```
If the statement to prepare is new, then prepare it, save the prepared statement, the current schema version and the current `id_sequence` in the hash and in the heap. If the hash is full, then pop the statement with minimal `id` from the heap and from the hash. If the statement is found in the hash, then check schema version and update its id to the `++id_sequence`.
- schema version from the hash == current schema version -> use the prepared statement;
- schema version from the hash != current schema version -> reprepare the statement.

**Comment by Gerold103** [comment]
Linked with https://github.com/tarantool/tarantool/issues/3497

**Comment by jobs-git** [comment]
Hi, I have been waiting for this for so long! I have a feature request though:

**Feature: Send prepared statement and data in one network request**

Typically, mysql sends prepared statement first then followed by data. This consumes 2x network i/o.

So to keep it secure, the method should still act as prepared statement but the difference is it gets the data available right away to be digested by prepared statement logic.

It goes like this

`tnt_sql_prepared_statement("SQL Prepared statement",[data array]);`

**Comment by Totktonada** [comment]
FYI: @jobs-git moves this proposal to #4690.
