### ISSUE TITLE
ALTER makes the table disappear

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#2607]
Reproducer:

box.sql.execute("CREATE TABLE te8 (s1 INT PRIMARY KEY);")
box.sql.execute("ALTER TABLE te8 ADD COLUMN s2 INT;")
box.sql.execute("SELECT * FROM te8;")
Result = error: 'no such table: te8'

**Comment by iproha94** [comment]
I have segmentation fault ``` sqlite3StatusDown: Assertion `N >= 0' failed.``` when executing
``` box.sql.execute("ALTER TABLE te8 ADD COLUMN s2 INT;") ```

**Comment by kyukhin** [comment]
The alter statement is not going to be supported in alpha-2 and probably won't be part of 1.8 at all.
Let's ban ALTER statement so far.
@kostja, if no objections, then I'd ask @pgulutzan to reflect it in docs and @iproha94 to do actual ban in `src/box/sql/parser.y`

We'll need a follow-up issue asking to implement `ALTER` statement (wishlist).
