### ISSUE TITLE
Nils in indexes in stored procedures

### ISSUE THREAD

**Issue by foverzar** [tarantool/tarantool#2610]
Suppose I have a stored procedure that calls the following function:
```
function test(param1, param2)
    box.space.some_entity.index.some_index:select({
        param1,
        param2
    })
end
```
with some_index created with parts:
```
{ 1, "string", 2, "string"}
```

If param1 is passed as nil, I get the following error:
```
"Supplied key type of part 0 does not match index part type: expected string"
```

If  I try the same from tarantool REPL, I get no error.

Digging through github issues and tarantool 1.7 docs, I found that this may be related to lua nil vs msgpack.NULL, although assigning ```param1 = msgpack.NULL``` or adding it directly to table yields the same result.

I'm a little confused. The docs say I can use nil as part of a query, but trying to do it in a stored procedure results in errror.

**Comment by kostja** [comment]
The first  key part can not be nil. You can omit other key parts.
