### ISSUE TITLE
Return generated columns after INSERT in IPROTO

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#2618]
JDBC driver contains interface which allows to read autogenerated columns
values after INSERT is occurred [1].
If there was multi-INSERT stmt - last row's autogenerated columns are returned.

Second option might be just return whole inserted row and let driver do the job.

So, for INSERTs let's return along w/ row_count a map with generated columns.

**Comment by Gerold103** [comment]
Forget my patch. It will not work. At first, we should learn which columns odbc really needs. I know about autoincrement only (like mysql last_insert_id). We should find other values, store them and return via iproto.

**Comment by ImeevMA** [comment]
At the end it was decided to return all auto-generated in current statement ids. It will be used in JDBC driver: [getGeneratedKeys()](https://docs.oracle.com/javase/7/docs/api/java/sql/Statement.html#getGeneratedKeys())

**Comment by ImeevMA** [comment]
After some research I found out:

**ODBC**
According to [documentation](https://docs.microsoft.com/en-us/sql/relational-databases/native-client-odbc-results/processing-results-odbc?view=sql-server-2017):
Each INSERT, UPDATE, and DELETE statement returns a result set containing only the number of rows affected by the modification.

**JDBC**
According to [documentation](https://docs.oracle.com/javase/8/docs/api/java/sql/Statement.html):
Each INSERT statement returns a result set. This result set can contain:
1. Number of rows affected by the modification.
2. All auto-generated in this statement keys. Method getGeneratedKeys() is used to get these auto-generated values. This method returns ResultSet object. However, what data contains this object should be decided by vendor.

After this I read what other vendor returns. I found that in case flag RETURN_GENERATED_KEYS was used returned ResultSet contains:
**_DB2_**: [All values](https://www.ibm.com/support/knowledgecenter/SSEPEK_12.0.0/java/src/tpc/imjcc_t0057053.html) that were generated during this INSERT statement. [Does not work](https://www.ibm.com/support/knowledgecenter/SSEPEK_12.0.0/java/src/tpc/imjcc_tjvbtupd.html) with executeBatch().
**_PostgreSQL_**: [All columns](https://github.com/pgjdbc/pgjdbc/issues/99) of all inserted records. [Works](https://github.com/pgjdbc/pgjdbc/blob/b7fd9f3cef734b4c219e2f6bc6c19acf68b2990b/pgjdbc/src/test/java/org/postgresql/test/jdbc3/GeneratedKeysTest.java) with executeBatch().
**_MS SQL_**: Only one [generated value](https://docs.microsoft.com/en-gb/sql/connect/jdbc/using-auto-generated-keys?view=sql-server-2017). This is [bug](https://github.com/Microsoft/mssql-jdbc/issues/245). [Does not work](https://github.com/Microsoft/mssql-jdbc/issues/358) with executeBatch().
**_Oracle DB_**: [ROWID of inserted row](https://docs.oracle.com/database/121/JJDBC/jdbcvers.htm#JJDBC28105). This ROWID can be used to retrieve other columns. Does not work with executeBatch().

Now we have to decide what to return via IPROTO:
1) Only auto-generated IDs.
2) All rows in which ID was generated.
3) All rows.
4) Nothing (in this case getGeneratedKeys() should throw SQLFeatureNotSupportedException).
