### ISSUE TITLE
Send column meta info in iproto requests

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#2620]
JDBC driver requires along with column NAME and TYPE also NULLABLE
flag which states if column was declared as 'NOT NULL' or not.
After space_format is properly filled, need to return per each column:
- DEFAULT
- COLLATION
- UNIQUE
- NOT NULL
- IS_PK (and place of the column in PK)

Blocked by: #2652

**Comment by kyukhin** [comment]
Probably this change also should include SQL-specific (more or less) column flags like:
* AUTOINCREMENT
* DEFAULT value (if any)

**Comment by Gerold103** [comment]
I can not find, where JDBC requires COLLATION, UNIQUE, IS_PK fields.

**Comment by Gerold103** [comment]
In the patchset of the ticket IPROTO_FIELD_NAME has been changed to 0 from 0x29 - it must be documented together with new metadata keys after push into 2.0.

**Comment by Gerold103** [comment]
And IPROTO code changes must be applied in Java driver.

**Comment by kyukhin** [comment]
So, we're returning only types and generated ids. Closing this one.
