### ISSUE TITLE
Print warning if fiber or coord name is truncated

### ISSUE THREAD

**Issue by viciious** [tarantool/tarantool#2622]
fiber_set_name and cord_set_name should probably print a warning if the passed name is too long. As of now, both will silently truncate it in sprintf call.

**Comment by kostja** [comment]
This is in the context of expirationd, which uses fiber.name() to identify tasks. If a name is truncated, expirationd silently misses the fact. It should handle the situation gracefully instead: e.g. fail to set the name. We can do this by adding a check to fiber.name()

**Comment by kostja** [comment]
A test should be added to expiraitond, though

**Comment by pjao** [comment]
This breaks a function of the expirationd (https://github.com/tarantool/expirationd/issues/22)
