### ISSUE TITLE
Remove EXCLUSIVE/IMMEDIATE from BEGIN statement

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#2624]
Those specifiers are only valid for SQLite and should be removed from Tarantool's
SQL front-end.

**Comment by TheAviat0r** [comment]
https://github.com/tarantool/tarantool/commit/3b26a6327080decefeb89b4ca890d2ac6f9ddabb

**Comment by TheAviat0r** [comment]
https://github.com/tarantool/tarantool/commit/18789d6d66259e1471ac0888123abf7b20da116f
