### ISSUE TITLE
Crash on OS X with "not enough memory"

### ISSUE THREAD

**Issue by racktear** [tarantool/tarantool#2638]
If I start tarantool on latest OS X, I get errors like this:

```
E> LuajitError: not enough memory
```

It reproduces on my machine even without any extra Lua code, just with plain box.cfg {}.

It started to happen after the latest OS X security update.

UPD: It happens once every 2-3 runs.

**Comment by rtsisyk** [comment]
Please paste your `sw_vers` and `system_profiler SPSoftwareDataType` output.

**Comment by kostja** [comment]
This is fixed.
