### ISSUE TITLE
LuaRocks: support custom rocks_servers

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#2640]
Add support for .rocks/config.lua file to configure custom rocks_servers

**Comment by rtsisyk** [comment]
There are no customer for this feature => wishlist

**Comment by igorcoding** [comment]
+ Please, make `tarantoolctl rocks` look for rocks in the https://rocks.moonscript.org along with rocks.tarantool.org

**Comment by rosik** [comment]
I have two proposals:
1. support command-line options `--only-server` and `--server` from [luarocks](https://github.com/luarocks/luarocks/wiki/luarocks)
2. make `tarantoolctl rocks` a separate utility, something like `tarantoolrocks`

The result I want to achieve:
Be able to fetch rockspecs and it's dependencies from custom server

**Comment by kyukhin** [comment]
Let's pick first option.
