### ISSUE TITLE
box.session.type()

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#2642]
Implement a helper function to return session type:
- **binary**: a binary protocol connection
- **console**: an administrative console connection
- **repl**: interactive mode (repl)
- **applier**: a replication applier
- **background**: a background fiber

This is useful in triggers, which are invoked in master-master configuration, to skip trigger actions on replicas.

**Comment by rtsisyk** [comment]
s/iproto/binary/g
s/background/lua/g

**Comment by kostja** [comment]
@lenkis, please document
