### ISSUE TITLE
LuaJIT's allocator is totally broken

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#2643]
LuaJIT can only operate with 31-bit address space due to internal limitations**. For this reason LuaJIT has it own allocator, which uses mmap() on all Unix-like platforms (Linux, BSD, OS X). 

According to POSIX, mmap(NULL) can return arbitrary address depending on implementation. For example, Linux Kernel returns address somewhere from the end of virtual address space, whereas Darwin starts from the lowest 32-bit addressees. On Linux LuaJIT uses special MAP_32BIT flag in order to request lower 32-bit address space from mmap(NULL). Unfortunately, Darwin doesn't support such flag and LuaJIT just tries to probe mmap(NULL) call in a (!) loop starting from 0x0 with step 0x1000000 until suitable address is found. 

Do you any problem with the probing approach on Darwin? The problem is obvious. On OS X Tarantool call mmap(NULL) to allocate some memory for memtx_arena. Darwin Kernel returns arbitrary address, which probably can be from the lowest 32-bit address space. LuaJIT tries to find a free 32-bit address after that and fails with "out of memory". Period.

** The latest version of LuaJIT introduced a special `LJ_GC64` mode which aims to workaround this problem, but we believe that this experimental feature is inefficient, immature and not-production ready.

Here is some example:
```
<!-- LuaJIT mmap some memory from 31-bit address space on the start
ljmmap(131072) => 0x627f000
ljmmap(131072) => 0x629f000
ljmmap(131072) => 0x62bf000
ljmmap(131072) => 0x62df000
ljmmap(131072) => 0x62ff000
ljmmap(131072) => 0x631f000
ljmmap(131072) => 0x633f000
ljmmap(131072) => 0x635f000
mmap(4194304) => 0x637f000
version 1.7.3-479-g73cbb4a63
type 'help' for interactive help
tarantool> box.cfg{memtx_memory=3*1024*1024*1024}
2017-08-01 18:54:00.288 [42602] main/101/interactive C> version 1.7.3-479-g73cbb4a63
2017-08-01 18:54:00.289 [42602] main/101/interactive C> log level 5
2017-08-01 18:54:00.289 [42602] main/101/interactive I> mapping 3221225472 bytes for tuple arena...

<!-- Tarantool mmap 3GB starting from 0x6800000

mmap(3221225472) => 0x6800000
mmap(4194304) => 0xc6800000
mmap(4194304) => 0xc6c00000
mmap(4194304) => 0xc7000000
2017-08-01 18:54:00.298 [42602] main/101/interactive I> recovery start
2017-08-01 18:54:00.298 [42602] main/101/interactive I> recovering from `./00000000000000000000.snap'

<!-- OOPS, there is no more 31-bit address space
ljmmap(131072) => 0xc7520000
ljmmap(131072) => 0xc7520000
ljmmap(131072) => 0xc7520000
ljmmap(131072) => 0xc7520000
ljmmap(131072) => 0xc7520000
ljmmap(131072) => 0xc7520000
ljmmap(131072) => 0xc7520000
ljmmap(131072) => 0xc7520000
ljmmap(131072) => 0xc7520000
ljmmap(131072) => 0xc7520000
ljmmap(131072) => 0xc7520000
ljmmap(131072) => 0xc7520000
ljmmap(131072) => 0xc7520000
ljmmap(131072) => 0xc7520000
ljmmap(131072) => 0xc7520000
ljmmap(131072) => 0xc7520000
ljmmap(131072) => 0xc7520000
ljmmap(131072) => 0xc7520000
ljmmap(131072) => 0xc7520000
ljmmap(131072) => 0xc7520000
ljmmap(131072) => 0xc7520000
ljmmap(131072) => 0xc7520000
ljmmap(131072) => 0xc7520000
ljmmap(131072) => 0xc7520000
ljmmap(131072) => 0xc7520000
ljmmap(131072) => 0xc7520000
ljmmap(131072) => 0xc7520000
ljmmap(131072) => 0xc7520000
ljmmap(131072) => 0xc7520000
ljmmap(131072) => 0xc7520000
ljmmap(131072) => 0xc7520000
ljmmap(131072) => 0xc7520000
ljmmap(131072) => 0xc7520000
ljmmap(131072) => 0xc7520000
ljmmap(131072) => 0xc7520000
ljmmap(131072) => 0xc7520000
ljmmap(131072) => 0xc7520000
ljmmap(131072) => 0xc7520000
ljmmap(131072) => 0xc7520000
ljmmap(131072) => 0xc7520000
ljmmap(131072) => 0xc7520000
ljmmap(131072) => 0xc7520000
ljmmap(131072) => 0xc7520000
ljmmap(131072) => 0xc7520000
ljmmap(131072) => 0xc7520000
ljmmap(131072) => 0xc7520000
ljmmap(131072) => 0xc7520000
ljmmap(131072) => 0xc7520000
ljmmap(131072) => 0xc7520000
ljmmap(131072) => 0xc7520000
ljmmap(131072) => 0xc7520000
ljmmap(131072) => 0xc7520000
ljmmap(131072) => 0xc7520000
ljmmap(131072) => 0xc7520000
2017-08-01 19:07:40.724 [42841] main/101/interactive F> not enough memory
```

Possible solutions:

1. Enable LJ_GC64 mode for OS X - it is better, than nothing
2. Rewrite slab_arena to use upper address space
3. Rewrite lj_alloc to use matras

This ticket is 1.7.5 prio1 because we can't release Tarantool which doesn't work on the latest OS X.

**Comment by funny-falcon** [comment]
Why tarantool doesn't do `mmap(BIG_HINT_ADDRESS)` ?
`#define BIG_HINT_ADDRESS = (void*)(uintptr_t)0x432100000000` should work quite well (if OSX supports it well).
