### ISSUE TITLE
Check column type in SQL parser

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#2645]
This issue is a first step toward implementation of strict typing in Tarantool's SQL frontend.
During parsing of column right now anything is accepted in the type slot.
E.g. following DDL is totally OK:
```
tarantool> CREATE TABLE t (id INT PRIMARY KEY, a GGGGG)
---
...
```

Let's fix parse and accept only following types:
- [INT|INTEGER]
- FLOAT
- VARCHAR[(n)]
- BLOB

Anything else should lead to syntax error.

This list is subject of discussion

**Comment by pgulutzan** [comment]
See also Issue#2351 Column definition in SQL

**Comment by kyukhin** [comment]
Closing as duplicate of #2351
