### ISSUE TITLE
sql: Ability to set some sqlite debug vars is necessary

### ISSUE THREAD

**Issue by Khatskevich** [tarantool/tarantool#2646]
We  need to have api to set some sqlite debug vars from lua.
By now we need to have access to at least sqlite_current_time.
This variable is used to set face date to sqlite and to test it (see table-13.2.* tests).

Read access was given by resolving #2455.

**Comment by Khatskevich** [comment]
Oops, `sqlite_current_time` is deleted.
In case someone needs to change some other variable, please, open a ticket especially for that variable.

**Comment by kyukhin** [comment]
Done.
