### ISSUE TITLE
Remove sql options from _space and _index

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#2647]
Use tuple_format from #2652 to store parsed table definition.

**Comment by kyukhin** [comment]
AFAIU, this issue is mostly about forcing SQL engine to use column definitions from `tuple_format`.

Right now `struct Table` contains an array of structures describing columns.
Here is the struct:
```
struct Column {
        char *zName;            /* Name of this column, \000, then the type */
        Expr *pDflt;            /* Default value of this column */
        char *zColl;            /* Collating sequence.  If NULL, use the default */
        u8 notNull;             /* An OE_ code for handling a NOT NULL constraint */
        char affinity;          /* One of the SQLITE_AFF_... values */
        u8 szEst;               /* Estimated size of value in this column. sizeof(INT)==1 */
        u8 colFlags;            /* Boolean properties.  See COLFLAG_ defines below */
};
```

`zName` and `notNull` might be moved to tuple_format easily.
`zColl` might be converted to collation ID and stored in tuple_format.
`affinity` should be removed and replaced w/ field type.

`colFlags` looks useless:
```
#define COLFLAG_PRIMKEY  0x0001 /* Column is part of the primary key */
#define COLFLAG_HIDDEN   0x0002 /* A hidden column. */
#define COLFLAG_HASTYPE  0x0004 /* Type name follows column name */
```

Open question is how to store following values:
1. `szEst`: field size estimation, which might not be simple to calculate if field is of complex type
2. `pDflt`: default value for column

Let's start from removing `zName` and `notNull` fields from `struct column`

**Comment by Korablev77** [comment]
After completing DD integration, it makes no sense to hold string of 'CREATE TABLE ...' or 'CREATE INDEX ...' statement. Previously, it was used to restore initial format (i.e. column names, types etc) and add meta-data to internal DD. The only exception is VIEW, since it is parsed each time VIEW is involved to create AST of SELECT.
