### ISSUE TITLE
Case-insensitvie indexes

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#2648]
In SQL `COLLATION` property might be set for:
- table column (#2547)
- index column (this issue)

Need to add new optional field to index_opts which will mark which
collation is used in the index. Two possible values are allowed: 'CASE",
'NOCASE'

**Comment by rtsisyk** [comment]
This ticket is going to 1.7.6, because we want to implement 'collate' index option in 1.7.x, according to roadmap.

**Comment by rtsisyk** [comment]
Collation is not about case-insensitiveness, collation is about language-specific compassion rules (a.k.a locale). case-sensitiveness can be implemented via functional index (like [Postgres](https://www.postgresql.org/docs/9.6/static/sql-createindex.html)) or by a separate option(like [Mongo](
https://docs.mongodb.com/manual/core/index-case-insensitive/)).

**Comment by rtsisyk** [comment]
1.7.5-157-ge260c2e33
