### ISSUE TITLE
Incorporate libicu into Tarantool source tree

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#2649]
Put recent version of libicu [1] into Tarantool's source tree (third_party I guess),
update CMake*, make sure lib's symbols are visible to main Tarantool.

[1] -  http://site.icu-project.org/download

**Comment by rtsisyk** [comment]
This ticket is going to 1.7.6, because we want to implement 'collate' index option in 1.7.x, according to roadmap.

**Comment by alyapunov** [comment]
Comparator perf comparison https://pastebin.com/JX1B9p4N
Order of different comparators https://pastebin.com/TXSbpMFy
+nunicode https://pastebin.com/iGjLKFqU (MYSQL means mariaDB here)

**Comment by rtsisyk** [comment]
1.7.5-157-ge260c2e33
