### ISSUE TITLE
Set COLLATION type when constructing an index

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#2653]
If index under construction contains COLLATION specifier - set a flag in `index_opts`.

This will enable indexation with proper COLLATION type.

Enable/prepare tests as well.

Blocked by #2648

**Comment by kyukhin** [comment]
Not blocked anymore

**Comment by Khatskevich** [comment]
It looked strange that unicode's order of special characters is different from ascii, so I have conducted a small research. There are weights of some special characters according to unicode standard.
```
  0020  ; [*0209.0020.0002] # SPACE
: 003A  ; [*023A.0020.0002] # COLON
! 0021  ; [*0261.0020.0002] # EXCLAMATION MARK
) 0029  ; [*0319.0020.0002] # RIGHT PARENTHESIS
[ 005B  ; [*031A.0020.0002] # LEFT SQUARE BRACKET
} 007D  ; [*031D.0020.0002] # RIGHT CURLY BRACKET
@ 0040  ; [*038F.0020.0002] # COMMERCIAL AT
/ 002F  ; [*0395.0020.0002] # SOLIDUS
` 0060  ; [*0498.0020.0002] # GRAVE ACCENT
< 003C  ; [*0630.0020.0002] # LESS-THAN SIGN
```
It proves that everything is allright. See collations.test.lua for more information.
