### ISSUE TITLE
Use libicu's versions for UPPER()/LOWER() implementation

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#2654]
After #2651 is resolved, need to update UPPER/LOWER embedded functions implementation to use libicu facilities.

Need to enable/write tests to cover the functionality.

Blocked by #2651

**Comment by Khatskevich** [comment]
It is not obvious how to set locale for UPPER/LOWER and other functions
Here is some info on this issue from 2003 standard:
### Syntax
```
<string value function> ::= <character value function> | <blob value function>
<character value function> ::= <character substring function> | <regular expression substring function> 
    | <fold>| <transcoding>| <character transliteration>| <trim function>
    | <character overlay function>| <normalize function>| <specific type method>
<fold> ::= { UPPER | LOWER } <left paren> <character value expression> <right paren>
```

#### General Rules
##### If `<fold>` is specified, then:
1. Let S be the value of the <character value expression>.
2. If S is the null value, then the result of the <fold> is the null value.
3. Let FRML be the length or maximum length in characters of the declared type of <fold>.
4. Case:
    * If UPPER is specified, then let FR be a copy of S in which every lower case character that has
a corresponding upper case character or characters in the character set of S and every title case
character that has a corresponding upper case character or characters in the character set of S is
replaced by that upper case character or characters.
    * If LOWER is specified, then let FR be a copy of S in which every upper case character that has
a corresponding lower case character or characters in the character set of S and every title case
character that has a corresponding lower case character or characters in the character set of S is
replaced by that lower case character or characters.
5. If the character set of <character factor> is UTF8, UTF16, or UTF32, then FR is replaced by
Case:
    * If the <search condition> S IS NORMALIZED evaluated to True, then NORMALIZE (FR)
    * Otherwise, FR.
6. Let FRL be the length in characters of FR.
7. Case:
    * If FRL is less than or equal to FRML, then the result of the <fold> is FR. If the declared type of
FR is fixed-length character string, then the result is padded on the right with (FRML – FRL)
<space>s.
    * If FRL is greater than FRML, then the result of the <fold> is the first FRML characters of FR
with length FRML. If any of the right-most (FRL – FRML) characters of FR are not <space>
characters, then a completion condition is raised: warning — string data, right truncation.

**Comment by Khatskevich** [comment]
#### There are two approaches to implement upper/lower:

1. UPPER( string, locale_name) (e.g. UPPER('hello', 'ru_RU'))
2. UPPER(string, collation_name_in_tarantool) (e.g. UPPER('hello', "unicode_ci"))

###### First solution
Disadvantages:
- The locale name is not checked by icu. In case of invalid locale - the default locale is chosen silently.

###### Second solution
Disadvantages:
- We can not get `UCaseMap` object from our `struct coll`, so to create `UCaseMap` we need to:
  - find `struct coll` in hash
  - query tuple from `_collation` space by id
  - create `UCaseMap` based on fetched locale
- Create collation is not a public API, so it would require some patience to do UPPER with locale which is not in our `_collation` space

**Comment by Khatskevich** [comment]
Ok.
We finally decide to support only
UPPER(str)
without additional arguments to work always in the default locale.
