### ISSUE TITLE
http.client remembers only last cookie value when receives several "Set-Cookie" headers

### ISSUE THREAD

**Issue by icamys** [tarantool/tarantool#2658]
**Problem**
I'm sending a GET request to a server using embedded http.client. The server responses with two headers named `Set-Cookie`. The client remembers only the last header because Lua table can include only one key `["set-cookie"]`.
Using Tarantool 1.7

**Expected behavior**
Client should remember all headers

**Motivation**
Multiple usage of `Set-Cookie` headers is a pretty regular thing:
```
Note: In practice, the "Set-Cookie" header field ([RFC6265]) often
      appears multiple times in a response message and does not use the
      list syntax, violating the above requirements on multiple header
      fields with the same name.  Since it cannot be combined into a
      single field-value, recipients ought to handle "Set-Cookie" as a
      special case while processing header fields.  (See Appendix A.2.3
      of [Kri2001] for details.)
```
From [RFC7230](https://tools.ietf.org/html/rfc7230#section-3.2.2)

**Comment by rtsisyk** [comment]
Confirmed, easy to fix.

**Comment by Mons** [comment]
HTTP RFC states, that 2 headers are equivalent to single header with 2 values, separated with `,`.
So, common approach for hash/dict is to store such headers as comma-separated values

But!
Sadly, cookie values could contain unquoted date with comma inside, which makes parsing not so easy. So the proposal is either to store 'set-cookie' header always as array (while other headers as comma-separated values) or to store 'set-cookie' also as raw, comma-separated single value (for those, who wants to parse it by theirselves) and also provide container with decoded value of set-cookie

**Comment by icamys** [comment]
@Mons +1 for provide container with decoded values

**Comment by rtsisyk** [comment]
A fix on the branch gh-2658-http-cookie. @IlyaMarkovMipt could you please add a test case using our gevent server?

**Comment by Totktonada** [comment]
@rtsisyk How current format of headers will be changed?

**Comment by rtsisyk** [comment]
http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2

> Multiple message-header fields with the same field-name MAY be present in a message if and only if the entire field-value for that header field is defined as a comma-separated list [i.e., #(values)]. It MUST be possible to combine the multiple header fields into one "field-name: field-value" pair, without changing the semantics of the message, by appending each subsequent field-value to the first, each separated by a comma. The order in which header fields with the same field-name are received is therefore significant to the interpretation of the combined field value, and thus a proxy MUST NOT change the order of these field values when a message is forwarded.

1.7.5-146-g375c16156

**Comment by rtsisyk** [comment]
.cookie parser moved to https://github.com/tarantool/tarantool/issues/2801

**Comment by Totktonada** [comment]
It would be good to update documentation accordingly.
