### ISSUE TITLE
Multiple parallel net.box calls() livelock on schema reload

### ISSUE THREAD

**Issue by racktear** [tarantool/tarantool#2666]
When multiple stored procedures are called remotely, that change schema, it is possible that they livelock the current net.box implementation, because it retries the call() upon detecting the schema change.

**Comment by kostja** [comment]
I don't see why CALL should be retried at all.

**Comment by Gerold103** [comment]
It is not possible. Test case, that provides, that a call is not retried:
```Lua
-- Input
box.cfg{listen = 3313}
count = 0
box.schema.user.grant('guest', 'read,write,execute', 'universe')
function do_smth()
	count = count + 1
	box.schema.create_space('test')
end
n = require('net.box')
c = n:connect(3313)
c:call('do_smth')
```

```Lua
-- Output
tarantool> c:call('do_smth')
---
...

tarantool> count
---
- 1
...
```

**Comment by Gerold103** [comment]
Since the ticket is not actual, I propose to close it.

**Comment by Gerold103** [comment]
I added the test in commit https://github.com/tarantool/tarantool/commit/e0f9cdc8dd4c3f326921c5dd7d717e6864a8bade
