### ISSUE TITLE
Allow to insert to memtx tuples bigger than `memtx_max_tuple_size'

### ISSUE THREAD

**Issue by rtokarev** [tarantool/tarantool#2667]
In some tasks we have 99% tuples that are smaller than some upper size, but 1% of tuples could be bigger. May be it's possible to insert these tuples using for example some fallback allocator that isn't such an optimal as default one, but don't have upper limit for allocation unit?

**Comment by rtsisyk** [comment]
memtx done - 1.7.4-429-g1a85df725
vinyl in progress.
