### ISSUE TITLE
Travis build of 1.8 is broken

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#2670]
Due to unknown reason `sql/iproto.test.lua` test hangs on Travis [1].
We still cannot reproduce it locally. Looks like exactly the same environment
as on Travis is needed.

This should be fixed ASAP as it might hide other issues.

[1] - https://travis-ci.org/tarantool/tarantool/jobs/262209792

**Comment by TheAviat0r** [comment]
Unable to fix functional indexes in Tarantool 1.8.2 because currently there are no hidden fields in engine, it will be implemented in the future,  came to agreement to move this issue to 1.8.3

**Comment by kyukhin** [comment]
Fixed by https://github.com/tarantool/tarantool/commit/a4b2080176c20c79b2efdb7fc2ed0a5d5498b9bf
