### ISSUE TITLE
Access check is missing in space:truncate()

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#2674]
There is no access check in space:truncate() any more, since it's an independent space and independent execution branch, and we didn't copy the access check from on_replace_dd_index.
Check for write access to the table being truncated in on_replace_dd_truncate, add a test case.
We should not check for create/drop, this is a pain to the users. And we should not check access to _truncate, it's a technical table, let's treat truncate as dml.

**Comment by rtsisyk** [comment]
1.7.4-437-gca361e204
