### ISSUE TITLE
тарантул не стартует и не ругается после обновления.

### ISSUE THREAD

**Issue by alekseyxxx** [tarantool/tarantool#2679]
Обновил тарантул до version 1.7.4-339-g5b96bb4.
Луашка приложения переехала из /etc/tarantool/instances.enabled/packmon-app.lua   в  /etc/tarantool/instances.available/packmon-app.lua,  но кроме того пришлось переименовать packmon-app.lua  в packmon_app.lua, потому что с дефисом тарантул не запускался, (и даже не ругался).

**Comment by lenkis** [comment]
related doc ticket: https://github.com/tarantool/doc/issues

**Comment by vicpopov** [comment]
должно починиться после https://github.com/tarantool/tarantool/pull/2684

**Comment by rtsisyk** [comment]
Duplicate of #2684
