### ISSUE TITLE
Refactor SQL's AUTOINCREMENT to use Tarantool facilities

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#2690]
SQL is intended to generate its own byte code to implement AUTOINCREMENT
feature for PKs.
It supports dedicated sequence table (sql_sequence) which stores current max-ids
for all tables and emits dedicated bytecode to update its contents.

Should be refactored as far as core Tarantool supports autoincrement itself.

**Comment by rtsisyk** [comment]
Blocked by #389

**Comment by kyukhin** [comment]
Not blocked anymore.
