### ISSUE TITLE
fiber.top()

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#2694]
Implement fiber.top() which returns fiber list ordered by average cpu usage in the last second

Arguments:
- seconds
- number of fibers

**Comment by sergepetrenko** [comment]
Performance measurements with and without fiber.top():
Invoked with `tarantool test.lua num_fibers`
The test measures context switches per second with `num_fibers` all running in a loop `while true do fiber.yield() end`

The results are averaged between 5 runs.

num_fibers | default version | fiber.top() version
---:|---:|---:
1 | 484 266 | 429 150 *(- 11.3 %)*
10 | 2 006 201 | 1 728 187 *(- 13.9 %)*
100 | 2 950 172 | 2 467 650 *(- 16.4 %)*
1000 | 2 400 037 | 2 020 417 *(- 15.8 %)*
10000 | 8 824 | 8 910 *(+ 1.0 %)*

File used to test fiber.top() version: 
```lua
fiber = require('fiber')
num_fibers = arg[1]
delta_time = 1

fiber_func = function()
    while true do
        fiber.yield()
    end
end

-- create fibers but do not let them run yet
for i = 1, num_fibers do
    fiber.new(fiber_func)
end

fiber.top_enable()

t_start = fiber.time()
fiber.sleep(delta_time)
t_end = fiber.time()

fiber.top_disable();

tbl = fiber.info()
csw = 0
for k ,v in pairs(tbl) do
    csw = csw + v["csw"]
end

print("delta time:", t_end - t_start)
print("csw/sec:", csw / (t_end - t_start))

```
File used to test default version: 
```lua
fiber = require('fiber')
num_fibers = arg[1]
delta_time = 1

fiber_func = function()
    while true do
        fiber.yield()
    end
end

-- create fibers but do not let them run yet
for i = 1, num_fibers do
    fiber.new(fiber_func)
end


t_start = fiber.time()
fiber.sleep(delta_time)
t_end = fiber.time()


tbl = fiber.info()
csw = 0
for k ,v in pairs(tbl) do
    csw = csw + v["csw"]
end

print("delta time:", t_end - t_start)
print("csw/sec:", csw / (t_end - t_start))
```
