### ISSUE TITLE
Don't quit on SIGINT in console

### ISSUE THREAD

**Issue by ASverdlov** [tarantool/tarantool#2717]
Currently if you type Ctrl+C in tarantool console, you'll quit it.

Instead I suggest jumping to the next empty line to escape running currently typed command upon SIGINT receipt, without saving previously typed command in history.

Quitting can be done on EOF (Ctrl+D).

**Comment by sitnikovv** [comment]
It is better to do optional, so as not to break compatibility.

**Comment by Totktonada** [comment]
@sitnikovv Compatibility with what? It is how most interactive interpreters works and I want especially note that bash in interactive mode works in that way.

**Comment by sitnikovv** [comment]
@Totktonada 
For example, if you worked with the console through expect

**Comment by Totktonada** [comment]
EOF situation on stdin causes exit as well as in shell. It can be sent with Ctrl+D (as far as I know in most terminal implementations).

**Comment by printercu** [comment]
Is there any way to clear input line now? Most readline clis have convention to clear line on ^C and exit on ^D. Let's revert https://github.com/tarantool/tarantool/commit/e6e14292ef376dbc0f8895eee3daf08f74ada895

**Comment by Totktonada** [comment]
See also #1510.

**Comment by Totktonada** [comment]
NB: We should do it only in interactive mode.

**Comment by Totktonada** [comment]
I propose to do the following within this issue:

1. Don't exit on SIGINT.
2. Discard a current input, leave from the readline search mode.
3. If a command is executed currently, then either do nothing or discard current input (if any).

I propose to don't implement cancellation of a currently executed command in any way within this issue. There are #1510 and #2857, which mention this.
