### ISSUE TITLE
 if the packet was incorrect, respond with an error code  before closing connection

### ISSUE THREAD

**Issue by unera** [tarantool/tarantool#272]
Например вместо номера итератора прислать если его имя.
ща пишет в лог такое сообщение, но не отвечает клиенту ничего.
просто закрывает сокет.

```text

# 2014-04-24 14:15:54.213 [12574] main iproto_constants.cc:108 E> ER_INVALID_MSGPACK: Invalid MsgPack - packet header

```

**Comment by kostja** [comment]
Now that we put iproto into a separate thread fixing this bug is only a matter of not-so-major refactoring, so it's time has come.
