### ISSUE TITLE
Install example.lua on Mac OS X

### ISSUE THREAD

**Issue by VadimPopov** [tarantool/tarantool#2725]
As previously discussed, we need to make sure the **example.lua** file gets installed on all platforms, since it's used in Quick Start tutorials. Please pay special attention to Mac OS X, as **example.lua** is currently missing from there.

---
Explanation
-
The path to **example.lua** is set by **instance_dir** variable in tarantool config.
The problem occurs because of a conflict between the old or custom user config with the new one. 
Possible solutions are:

Variant 1
-
tarantoolctl has internal default path to **instance_dir** so the sequence is as follows:
1. check config file and try to find **instance_dir**
2. a. if not found use default OS-specific path (currently it's /etc/tarantool/instances.enabled which is wrong for OSX)
  b. if **instance_dir** is set but file not found, use default OS-specific path again.
3. If that did not help either, print error message: file not found.

Variant 2
-
Split tarantool config into two parts: user config and tarantool version-specific config.

**Comment by rtsisyk** [comment]
@bigbes can patch brewspec.

**Comment by rtsisyk** [comment]
Any progress?

**Comment by bigbes** [comment]
I was in full confidence, that example.lua is, automatically, installed.
Ok, I'll put it with the next brewspec update. But I need some help with this https://github.com/tarantool/tarantool/issues/2930

**Comment by lenkis** [comment]
We found that ``tarantoolctl start example`` works ok with clean Tarantool installations. That's enough for a beginner. Closing.
