### ISSUE TITLE
space_def_new_from_tuple() leaks memory

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#2733]
space_def_new_from_tuple() calls space_opts_create() which calls opts_create_from_field() which set space_opts->sql  using malloc(). This member leaks on exceptional case in space_def_new_from_tuple().
Please check similar places too.

**Comment by Gerold103** [comment]
It is not actual. Can I close it?

**Comment by rtsisyk** [comment]
Actually def->sql was freed by space_def_delete(). I refactored the code to make it more clear.
