### ISSUE TITLE
libev timers are inaccurate

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#2737]
Steps to reproduce:

```
#!/usr/bin/env tarantool

local json = require('json')
local fiber = require('fiber')
local http = require('http.client').new()

local url = 'https://jsonplaceholder.typicode.com/posts'
local opts = { 
    timeout = 2,
    verbose = true,
}

local response = http:post(url, '\n', opts)
print('DEBUG: RESPONSE: ' .. json.encode(response))
require('io').read() -- wait >2 seconds, then hit enter
--require('fiber').sleep(3)
local response = http:post(url, '\n', opts)
print('DEBUG: RESPONSE: ' .. json.encode(response))
```

Responses are the following:

```
DEBUG: RESPONSE: {"reason":"Ok","status":201,"body":"<…>"}}
DEBUG: RESPONSE: {"status":408,"reason":"Timeout was reached"}
```

Reproduced on Tarantool 1.7.4-175-gf728e8e and 1.7.5-12-g6b8602782.

```
$ curl --version
curl 7.53.1 (x86_64-pc-linux-gnu) libcurl/7.53.1 OpenSSL/1.0.2k zlib/1.2.11
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smtp smtps telnet tftp 
Features: IPv6 Largefile NTLM SSL libz TLS-SRP UnixSockets HTTPS-proxy 
```

**Comment by GeorgyKirichenko** [comment]
io module is a lua native module and does blocking call, so time is not evaluated correctly after this call, please don't use it

**Comment by rtsisyk** [comment]
ev_timer uses ev_now() (event loop time) instead of ev_time() (realtime clock), therefore fiber_yield_timeout() and all other functions calculate timeouts incorrectly.

**Comment by rtsisyk** [comment]
What should be done in this ticket?

**Comment by kostja** [comment]
Please use fio instead of io.

**Comment by Totktonada** [comment]
Sorry for the long silence. It seems, I missed the replies.

I agree, it is not worth to expect that timeouts will work correctly after a blocking call. And it is not worth to change, since blocking calls are generally not recommended in context of tarantool's application.

The behavior looks strange on a first glance, but it is how timeouts are work in tarantool in general.

Thank you for the answers.

----

OTOH, after PR #7160 we can update the fiber's timer once per millisecond.
