### ISSUE TITLE
Add possibility to run benchmarks

### ISSUE THREAD

**Issue by vbauer** [tarantool/tarantool#274]
It would be great to test Tarantool's performance using out-of-box script/application.

Something like this: https://github.com/antirez/redis/blob/unstable/src/redis-benchmark.c

**Comment by kostja** [comment]
Hi, 
by now we run lots of benchmarks, some of them on a daily basis. 
Check out http://tarantool.org/benchmark.html
We also have a set of micro-benchmark which we execute & measure results on every run:
https://github.com/tarantool/microb

**Comment by vbauer** [comment]
Thank you very much!
