### ISSUE TITLE
Log server_id, lsn pair in "too long" messages

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#2743]
```
2017-09-06 15:27:03.646 [11289] main/1067705/main txn.cc:208 W> too long WAL write: 0.839 sec
```

Add (server_id, lsn) to this message to simplify searching for problematic request in xlog.

Mail.Ru, via 1.6

**Comment by locker** [comment]
Fixed by 43ba81b4f68ffb3538bbe3b42848bc158ced10b1
