### ISSUE TITLE
Enhance fio.rename() to work over filesystems

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#2751]

**Comment by bigbes** [comment]
Proposal: do not touch `fio.rename` as low-level counterpart and create some analogue of [shutil](https://docs.python.org/2/library/shutil.html) python library:
* copy between file-systems
* `rmtree` - already used in tests

**Comment by Totktonada** [comment]
@bigbes Okay for me, but in the case the documentation of `fio.rename` should state explicitly it does not work over filesystems.

**Comment by Totktonada** [comment]
Ouch, I missed @bigbes proposed don’t add rename-over-fs at all. I guess it would be convenient for users to use general-purpose function working like `mv` unix command. As separate function, of course.

**Comment by rtsisyk** [comment]
This feature has already been implemented during 1.7.6 development, but I decided to push it into 1.7.7 instead of 1.7.6.

d7135403a8341e865b80519f13587ed32a73a359

**Comment by Totktonada** [comment]
Requested `mv` functionality now can be implemented using `rename || copytree + rmtree`. Good enough. I would note that into documentation.
