### ISSUE TITLE
built-in 'fio' sucks

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#2757]
Please extend the built-in fio module to provide better diagnostics: every call should return an error object as second return value when an error happens.

fio.open() default mode is 0, which is non-workable. If mode is nil, like in open() the default mode should be used - 777 & umask

**Comment by rtsisyk** [comment]
Both problems have been fixed during 1.7.6 development, but I decided to push it into upcoming 1.7.7 instead of 1.7.6.
