### ISSUE TITLE
Add PCRE library to contrib

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#2764]
Now I using [lrexlib-pcre](https://rrthomas.github.io/lrexlib/).

**Comment by rtsisyk** [comment]
Let's add this library to our rocks.

**Comment by rtsisyk** [comment]
Alternative: https://github.com/igormunkin/lua-re

**Comment by Totktonada** [comment]
lua-re seems being pretty small and works for me except arguments validation (causes segfault for now).

**Comment by Totktonada** [comment]
lrexlib-pcre and lrexlib-pcre2 are in our rocks. lua-re stalled for the year and is not ready for production use due to lack of validation.

@kyukhin, we can close the issue?

**Comment by Totktonada** [comment]
https://github.com/tarantool/lrexlib was added.
