### ISSUE TITLE
Extend the default loader to look for .rocks in the parent dir hierarchy

### ISSUE THREAD

**Issue by racktear** [tarantool/tarantool#2767]
I believe there is a pattern for installing .rocks in the project root, and adding it to .gitignore.

But since most of the project is usually located, and/or started from the subdirectory, I have to add boilerplate that extends `package.path` and `package.cpath` to be able to start it.

I suggest that the default loader be extended to add a mechanism for looking up the .rocks directory in the parent directories recursively.

**Comment by rtsisyk** [comment]
1. Remove ${pwd}/.rocks from package.path/package.cpath
2. Add a new package.loader() which will recursively search in the higher directories, like npm:

> If the node_modules directory doesn't exist in your current directory, NPM will look for it in the higher directories until it finds it. So, if the parent directory has a node_modules directory, NPM will assume that's where it is to install modules.

**Comment by rtsisyk** [comment]
1.7.5-136-gc182cf3e8
