### ISSUE TITLE
Use self-signed client certificates with http.client on Mac

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#2772]
Self-signed client certificates declined by system-wide libcurl on Mac. (DY)LD_LIBRARY_PATH, (DY)LD_PRELOAD seems banned in recent OS versions.

@ASverdlov can provide additional details re attempts performed to get it work.

The solution I see: statically link libcurl for Mac builds.

**Comment by racktear** [comment]
Correction: make it possible to link with libcurl from homebrew. Even probably do it by default.

**Comment by bigbes** [comment]
Don't you think, that it's brew spec problem?

**Comment by rtsisyk** [comment]
@Totktonada @racktear gh-2772-curl-homebrew should solve your problem, please check.

**Comment by ASverdlov** [comment]
@rtsisyk Thanks! This solves the problem.

**Comment by rtsisyk** [comment]
1.7.5-99-g947b378dd
