### ISSUE TITLE
Add base64_urlsafe_encode() to digest module

### ISSUE THREAD

**Issue by opomuc** [tarantool/tarantool#2777]
We need `base64_urlsafe_encode()` function for a safe use in URL headers. While standard allows padding, it is inconsistent with HTTP headers and causes HTTP server to fail on incorrect header format when passed a token string. Thus, encoded string must not contain whitespace characters. 

See #2478, #2479 for more information.

**Comment by rtsisyk** [comment]
а) Remove \n delimiter б) Replace + by - and / by  _.

**Comment by rtsisyk** [comment]
1.7.5-112-gcd4e26d43
