### ISSUE TITLE
Snapshot daemon don't update snapshot-file without new transactions between checkpoint_interval-s

### ISSUE THREAD

**Issue by alexeyantropov** [tarantool/tarantool#2780]
При наличии запущенного, но не активного (без продуктовой нагрузки) инстанса, Snapshot daemon не обновляет время модификации последнего снапшота (или не перезаписывает имеющийся снапшот). Важно обновлять время модификации (перезаписывать снапшот) аналогично https://github.com/tarantool/tarantool/issues/2045 для проверки корректности работы Snapshot daemon согласно конфигурации checkpoint_interval. При этом проверка, в общем случае, не должна знать о том, что инстанс принимает продуктовую нагрузку или находится в неком неактивном состоянии, или переходит из состояния используется \ не используется. Вне зависимости от этого проверка мониторинга всегда должна говорить о том, что инстанс корректно создает снапшоты.

Пример:

tarantool-1.7.5.0-1.el6.x86_64 & tarantool-queue-1.0.52-1.el6.noarch.

Интсанс запущен 22-го числа, в логе имеем информацию о запланированном снапшоте:

`...`
`2017-09-22 14:47:44.587 [24972] main/483/fifottl I> Started queue fifottl fiber`
`2017-09-22 16:29:07.917 [24972] main/105/checkpoint_daemon I> making snapshot...`
`2017-09-22 16:29:07.944 [24972] snapshot/101/main I> saving snapshot '/var/lib/tarantool/xxx/00000000000000000026.snap.inprogress'`
`2017-09-22 16:29:07.945 [24972] snapshot/101/main I> done`
`2017-09-22 16:29:07.957 [24972] main/105/checkpoint_daemon I> vinyl checkpoint done`
`2017-09-22 16:29:07.958 [24972] main/105/checkpoint_daemon I> scheduled the next snapshot at Fri Sep 22 18:29:07 2017`
`2017-09-22 18:29:07.958 [24972] main/105/checkpoint_daemon I> scheduled the next snapshot at Fri Sep 22 20:29:07 2017`
`2017-09-22 20:29:07.958 [24972] main/105/checkpoint_daemon I> scheduled the next snapshot at Fri Sep 22 22:29:07 2017`
`2017-09-22 22:29:07.959 [24972] main/105/checkpoint_daemon I> scheduled the next snapshot at Sat Sep 23 00:29:07 2017`
`2017-09-23 00:29:07.959 [24972] main/105/checkpoint_daemon I> scheduled the next snapshot at Sat Sep 23 02:29:07 2017`
`2017-09-23 02:29:07.960 [24972] main/105/checkpoint_daemon I> scheduled the next snapshot at Sat Sep 23 04:29:07 2017`
`2017-09-23 04:29:07.961 [24972] main/105/checkpoint_daemon I> scheduled the next snapshot at Sat Sep 23 06:29:07 2017`
`2017-09-23 06:29:07.962 [24972] main/105/checkpoint_daemon I> scheduled the next snapshot at Sat Sep 23 08:29:07 2017`
`2017-09-23 08:29:07.962 [24972] main/105/checkpoint_daemon I> scheduled the next snapshot at Sat Sep 23 10:29:07 2017`
`2017-09-23 10:29:07.962 [24972] main/105/checkpoint_daemon I> scheduled the next snapshot at Sat Sep 23 12:29:07 2017`
`2017-09-23 12:29:07.963 [24972] main/105/checkpoint_daemon I> scheduled the next snapshot at Sat Sep 23 14:29:07 2017`
`...`

Но никаких изменений на файловой системе нет:

`$ date; ls -la`
`Mon Sep 25 10:20:16 MSK 2017`
`total 20`
`drwxrwx--- 2 tarantool root 4096 Sep 22 16:29 .`
`drwxrwx--- 4 tarantool root 4096 Sep 22 13:38 ..`
`-rw-r--r-- 1 tarantool root 1211 Sep 22 13:47 00000000000000000000.snap`
`-rw-r--r-- 1 tarantool root 2642 Sep 22 16:29 00000000000000000000.xlog`
`-rw-r--r-- 1 tarantool root 1712 Sep 22 16:29 00000000000000000026.snap`

При этом команда box.snapshot() обновляет время модификации последнего снапшота, что правильно:

`$ tarantoolctl enter xxx`
`connected to unix/:/var/run/tarantool/xxx`
`unix/:/var/run/tarantool/xxx> box.snapshot()`
`---`
`- ok`
`...`

`...`
`2017-09-25 10:29:07.977 [24972] main/105/checkpoint_daemon I> scheduled the next snapshot at Mon Sep 25 12:29:07 2017`
`2017-09-25 12:01:39.647 [24972] main/8940809/console/unix/: I> vinyl checkpoint done`
`2017-09-25 12:29:07.977 [24972] main/105/checkpoint_daemon I> scheduled the next snapshot at Mon Sep 25 14:29:07 2017`
`...`

`$ date; ls -la`
`Mon Sep 25 12:38:22 MSK 2017`
`total 20`
`drwxrwx--- 2 tarantool root 4096 Sep 22 16:29 .`
`drwxrwx--- 4 tarantool root 4096 Sep 22 13:38 ..`
`-rw-r--r-- 1 tarantool root 1211 Sep 22 13:47 00000000000000000000.snap`
`-rw-r--r-- 1 tarantool root 2642 Sep 22 16:29 00000000000000000000.xlog`
`-rw-r--r-- 1 tarantool root 1712 Sep 25 12:01 00000000000000000026.snap`

**Comment by kostja** [comment]
Надо доделать.

**Comment by rtsisyk** [comment]
ccd451eb9652b27821dba0ff74e6443c296ae246
