### ISSUE TITLE
Make log buffer size configurable

### ISSUE THREAD

**Issue by racktear** [tarantool/tarantool#2781]
Currently the maximum length of the log entry is about 2000 chars.

I suggest to bump the default limit to 8192, and to make this limit configurable through box.cfg() up to at least a few megabytes.

**Comment by rtsisyk** [comment]
This buffer is thread-local, so configuration via box.cfg() is technically complicated. I can increase the default limit to 8192 for logger=<file>. logger=<pipe> will still be capped by 4096 bytes per message due to system limitations (PIPE_MAX).

**Comment by rtsisyk** [comment]
I increased the buffer size to 16k, but message now can be interleaved in some situation:

>   From pipe(7):
>    POSIX.1 says that write(2)s of less than PIPE_BUF bytes must be atomic:
>   the output data is written to the pipe as a contiguous sequence. Writes
>   of more than PIPE_BUF bytes may be nonatomic: the kernel may interleave
>   the data with data written by other processes. PIPE_BUF is 4k on Linux.
>
>   Nevertheless, let's ignore the fact that messages can be interleaved in
>   some situations and set SAY_BUF_LEN_MAX to 16k for now.

The proper fix for interleaving is https://github.com/tarantool/tarantool/issues/2794, but that ticket is complicated and we don't have time for it right now.
