### ISSUE TITLE
concurrent ddl bug in memtx

### ISSUE THREAD

**Issue by Khatskevich** [tarantool/tarantool#2783]
Multi-statement ddl transactions are disallowed in memtx, but this check is not triggered due to rollback in yield, caused by `lock_before_dd` in `alter.cc`.
This leads `unlock_after_dd` to not shoot (wtile `lock_before_dd` is taken).

This sample causes deadlock by now
```
fiber = require("fiber")
box.cfg{}

test1 = box.schema.space.create('test1')
test1:create_index('primary', {unique = true, parts = {1, 'unsigned'}})
c = fiber.channel(2)
fiber.create(function() --fiber1
    test1:create_index("sec", {unique = true, parts = {2, 'unsigned'}})
    print("fiber 1 exit")
    c:put(true)
end)

fiber.create(function() -- fiber 2
    local space
    box.begin()
    pcall( function() -- this request should fail, but create txn with rollback callback on yield
        space = box.schema.space.create('test2')
    end)
    pcall( function() -- this request takes ddl_lock but do not frees it
        test1:create_index("sec2", {unique = true, parts = {2, 'unsigned'}})
    end)
    box.commit()
    print("fiber 2 exit")
    c:put(true)
end)

for i = 1, 2 do c:get() end
test1:drop() -- this is where everything stops
os.exit(0)

```
1. fiber1 occupy ddl lock
2. fiber2 do begin
3. fiber 2 makes fail-request (create("test2")), fails, but adds rollback callback on fiber yied
4. fiber2 tries to occupy lock, fail, do yield, do rollback, cancell transaction,**occupy lock**, fails
5. fiber2 do not unlock because it had to be done by trigger in transaction which is canceled
6. main fiber try to drop space, but lock is not unlocked

**Comment by rtsisyk** [comment]
box.schema.space.create('test2') inside box.begin()-box.commit() block raises and exception, so c:put(true) in fiber2 never happen and c:get() blocks on the second call.

**Comment by Khatskevich** [comment]
I think that b01baad373fa3bcbbf12c7ba3d350c3b7e8f617a is the best solution, because current implementation has several disadvantages:
1. It silently rollbacks, while we expect error at least (see #2528)
2. It cancels transaction, as a side effect, and next command in sql which is COMMIT fails due to an absence of transactions (while failed statement must not cancel transaction).

**Comment by GeorgyKirichenko** [comment]
The new error message for 1.9 Debug is:
/src/box/txn.c:148: txn_begin_in_engine: Assertion `stailq_empty(&txn->stmts)' failed
