### ISSUE TITLE
Forbid user to create trigger on system spaces

### ISSUE THREAD

**Issue by TheAviat0r** [tarantool/tarantool#2787]
Now user is able to create trigger on Tarantool system spaces. For example, this query works successfully:
`CREATE TRIGGER tt1 AFTER UPDATE ON _space BEGIN SELECT 1; END;`
We should forbid user to do it, because it can harm database metadata.

**Comment by kostja** [comment]
I don't know what this is for. Please explain why it breaks and why we should forbid it at all.

**Comment by TheAviat0r** [comment]
@kostja the purpose is to save default SQLite behavior, where user is not able to create trigger on meta-data tables beginning with 'sqlite_' prefix.

**Comment by kostja** [comment]
We don't care.
