### ISSUE TITLE
Expose a function to write a plain string to log

### ISSUE THREAD

**Issue by racktear** [tarantool/tarantool#2788]
Currently I can't just write a plain string to log file, because from my client code I don't know a proper fd.

I need this to be able to implement a custom logger (say, to write logs in json format)

**Comment by zloidemon** [comment]
I need it but it might conflict with this https://github.com/tarantool/tarantool/issues/2485

**Comment by racktear** [comment]
The issue #2485 is to set different log levels for loggers.

My need is to be able to modify the log entry format and to be able to put undecorated stuff to stdout/logfile/etc...

There is no major conflict in it. We can later add `say_plain()` to individual logger objects.

**Comment by rtsisyk** [comment]
https://github.com/tarantool/tarantool/issues/2795
