### ISSUE TITLE
sql: concurrent ddl 2

### ISSUE THREAD

**Issue by Khatskevich** [tarantool/tarantool#2793]
Concurrent ddl is not working properly.
Here is example of failing test:
ec0ca83f83318df906afdf9f1c85e3d0ba83267e : test/sql-tap/gh-2723-concurrency.test.lua 

Blocked, because tarantool have to transactional ddl itself. #600 #2783 #1871

**Comment by kostja** [comment]
This is not an SQL bug.

**Comment by kyukhin** [comment]
Not reproducible anymore.
