### ISSUE TITLE
Structured logging in JSON format

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#2795]
Add a new option to box.cfg { log_format = "plain|json" } to choose between plain (current) and json formatting for log output:

`{"time": 1507026445.23232, "level": "WARN", "message": <message>, "filename": <filename>, "line": <fds>}`

Needed by @racktear

**Comment by racktear** [comment]
A prototype that demonstrates how I wish the log module to be extended:

https://github.com/tarantool/slog

**Comment by rtsisyk** [comment]
ok, I think we can incorporate slog into built-in logger.

**Comment by Totktonada** [comment]
@racktear Is a format string with json output simultaneously supported?

```
log.info('my_table: %s', {…some table here…})
```

**Comment by racktear** [comment]
@Totktonada I doubt it. The built-in formatter doesn't support Lua tables. Well, it does, but it uses tostring().

**Comment by rtsisyk** [comment]
1.7.5-183-g437e82ed6
