### ISSUE TITLE
replication: transaction boundaries in replication protocol

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#2798]
Currently multi-statement transactions can be applied non-atomically on replicas. I propose to patch replication protocol to send xrow txs as batches under the same IPROTO packet.

This ticket is complicated, because recovery API is entirely row-based instead of tx-based.

**Comment by Gerold103** [comment]
Test case.
First tarantool:
```Lua
box.cfg{listen = 3314}
box.schema.user.grant('guest', 'read,write,execute', 'universe')
s = box.schema.space.create('test')
pk = s:create_index('pk')
sk = s:create_index('sk', {parts = {2, 'unsigned'}})
errinj = box.error.injection
errinj.set("ERRINJ_RECOVER_XLOG_LIMIT", 2)
```

Second tarantool:
```Lua
box.cfg{replication = 3314}
```

First tarantool:
```Lua
box.begin() s:replace{1, 1} s:replace({2, 2}) s:replace({3, 3}) box.commit()
```

Second tarantool:
```Lua
tarantool> box.space.test:select{} -- must be 0 rows.
---
- - [1, 1]
  - [2, 2]
...
```

**Comment by rtsisyk** [comment]
2017-12-06 blocked by @kostja for unknown reason.
