### ISSUE TITLE
sql: box.sql.execute("UPDATE ...") return value

### ISSUE THREAD

**Issue by ctpo6** [tarantool/tarantool#2799]
Now it returns nothing, whether there were updated tuples or not. In some cases it would be convinient for the caller to have an info if the update really happen. Please consider returning the number of updated tuples or the latest updated tuple.

**Comment by kostja** [comment]
We will remove box.sql.execute() altogether, as well as box.sql

**Comment by ctpo6** [comment]
Replacement for box.sql.execute()?

**Comment by kostja** [comment]
net.box

**Comment by ctpo6** [comment]
Documentation already updated? If not yet, when expected?
