### ISSUE TITLE
Fix space formats checking

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#2800]
First:
```
s = box.schema.space.create('test', {engine = 'vinyl', field_count = 2
---
...

tarantool> pk = s:create_index('pk')
---
...

tarantool> s:replace{1, 2}
---
- [1, 2]
...

tarantool> t = box.space._space:select{s.id}[1]:totable()
---
...

tarantool> t[5] = 1
---
...

tarantool> box.space._space:replace(t)
---
- error: Index 'pk' (TREE) of space 'test' (vinyl) does not support size()
...
```

Second:
```
box.cfg{}
format = {}
format[1] = {name = 'id', type = 'unsigned'}
format[2] = {name = 'field2', type = 'unsigned'}
format[3] = {name = 'field3', type = 'unsigned'}
s = box.schema.space.create('test', {format = format})
pk = s:create_index('pk')
sk = s:create_index('sk', { parts = {2, 'unsigned'} })
s:replace{1, 2, 3}
format[3].type = 'string'
s:format(format)
```
Must fail, but it does not.

**Comment by Gerold103** [comment]
What to do with adding a new fields to a not empty space?
1. Forbid. Then bootstrap fails - system spaces at first are built and then formatted.
2. Allow. Then an user can add a field with a such type to a format, that an existing tuple can be invalid for a new format. Then restart fails, on bootstrap also (on select for vinyl).
3. Allow for memtx, disable for vinyl. For memtx go through all primary index tuples and check that a new field type is ok.

**Comment by rtsisyk** [comment]
1.7.5-193-g30ae14611
