### ISSUE TITLE
Bindings to consul

### ISSUE THREAD

**Issue by knazarov** [tarantool/tarantool#2804]
For most of our projects we need a way to compose a cluster, and distribute configuration.
In addition, it is now very hard to do reliable failover and leader election, as Tarantool doesn't have raft on board.

I propose to create a lua rock with consul bindings and use consul for all cluster management tasks.

An example of a decently written client library: https://github.com/cablehead/python-consul
We can copycat it

**Comment by Mons** [comment]
Completely obsoleted
