### ISSUE TITLE
Support for column names in index definition

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#2814]
Below is some real boilerplate code:

```
    local subscriber = box.schema.space.create('subscriber')
    subscriber:format({
        {name='subscriber_id', type='integer'},
        {name='customer_id', type='integer'},
        {name='customer_ext_id', type='string'},
        -- CUT
    })
    subscriber:create_index('subscriber', {
        parts = {
            {1, 'integer'},
            {3, 'string'}
        }
    })
    subscriber:create_index('customer', {
        parts = {
            {2, 'integer'},
            {3, 'string'}
        },
        unique = false
    })
```

I propose to add more shortcuts to index part definitions:

- parts = { {field = field_name1, type = field_type}, {field = field_name2, type = field_type}, ...} 
- parts = { {field_name1, field_type}, {field_name2, field_type}, ...} 
- parts = { {field_name1}, {field_name2}, ...} 
- parts = {field_name1, field_name2}

field_type should be derived from the column definition (if any) or set to 'scalar'.
Transformation should be performed in schema.lua, data dictionary format shouldn't be changed.

**Comment by alyapunov** [comment]
I also would like to see 
```
parts = {field_id1, field_id2}
```
working.

**Comment by rtsisyk** [comment]
1.7.5-173-g47c2fe45b
