### ISSUE TITLE
sql: omit creation of index only on primary key

### ISSUE THREAD

**Issue by Korablev77** [tarantool/tarantool#2817]
Index which is created only on PRIMARY KEY column is likely to be useless. Furthermore, in this case running ANALYZE leads to appearance of excess statistics in tables _sql_stat1 and _sql_stat4, which in its turn results in overhead when query planner optimizes query execution. Thus, it seems reasonable to omit creation of such indexes.

**Comment by kyukhin** [comment]
This is part of #3369
