### ISSUE TITLE
sql: remove "tcl variable" token type

### ISSUE THREAD

**Issue by Khatskevich** [tarantool/tarantool#2828]
there is legacy TK_VARIABLE token type.
It should be deleted

**Comment by iproha94** [comment]
TK_VARIABLE - important token. It is necessary to bind the variables in the preparation of statements. I deleted code for tcl, which allows you to make variable name with double colon and brackets. Examples: ```:v::ar``` or ```:v(ar)```
See commit ```sql: remove tcl legacy code``` in  branch ```iproha94/gh-2828-tcl-legacy```

**Comment by kyukhin** [comment]
TK_VARIABLE is necessary token for binding. Test suite contains no traces of this token.
So, I guess this issue is done.
