### ISSUE TITLE
Sequence cannot be used with a secondary key on index:alter()

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#2832]
box.schema.create_space('s')
box.space.s:create_index('primary', {sequence = true})
box.space.s:create_index('str', {parts={2, 'string'}})
box.space.s.index.str:alter({parts={2, 'string', 1, 'unsigned'}})

- error: 'Can''t create or modify index ''str'' in space ''s'': sequence cannot be
    used with a secondary key'

**Comment by locker** [comment]
Fixed in 1.7.5-196-g77db87ce
