### ISSUE TITLE
Http.client crashes on empty post response

### ISSUE THREAD

**Issue by sharonovd** [tarantool/tarantool#2836]
Tornado-based mock service replies with 'empty' spot response. Verbose log:

19:05:23 p2phub.1   | * Found bundle for host localhost: 0x7ff97d902fa0 [can pipeline]
19:05:23 p2phub.1   | * Re-using existing connection! (#18) with host localhost
19:05:23 p2phub.1   | * Connected to localhost (::1) port 55555 (#18)
19:05:23 p2phub.1   | > POST /no_account HTTP/1.1
19:05:23 p2phub.1   | Host: localhost:55555
19:05:23 p2phub.1   | Accept: */*
19:05:23 p2phub.1   | Content-Length: 1887
19:05:23 p2phub.1   | Content-type: application/json
19:05:23 p2phub.1   | Request-id: f26b10f19963d51ef63aa5a742da4de9889c1ce086e582d7d3f968ecd1bf9ac6
19:05:23 p2phub.1   | Connection: Keep-Alive
19:05:23 p2phub.1   | Keep-Alive: timeout=60
19:05:23 p2phub.1   | Expect: 100-continue
19:05:23 p2phub.1   | 
19:05:23 p2phub.1   | < HTTP/1.1 200 OK
19:05:23 p2phub.1   | < Server: TornadoServer/4.5.2
19:05:23 p2phub.1   | < Content-Type: text/html; charset=UTF-8
19:05:23 p2phub.1   | < Date: Mon, 16 Oct 2017 16:05:23 GMT
19:05:23 p2phub.1   | < Access-Control-Allow-Origin: *
19:05:23 p2phub.1   | < Access-Control-Allow-Headers: x-requested-with
19:05:23 p2phub.1   | < Access-Control-Allow-Methods: POST, OPTIONS
19:05:23 p2phub.1   | < Content-Length: 0
19:05:23 p2phub.1   | < 
19:05:23 p2phub.1   | * Connection #17 to host localhost left intact
19:05:23 p2phub.1   | 2017-10-16 19:05:23.903 [71343] main/122/lua I> POST https://localhost:55555/has_account; http.client raises: builtin/http.client.lua:112: bad argument #1 to 'gsub' (string expected, got nil)

**Comment by rtsisyk** [comment]
Fixed by 69e94271bcd876e439e7be05af425278265ba238
