### ISSUE TITLE
Remove/change check on unknown fields in space:format

### ISSUE THREAD

**Issue by Igorjan94** [tarantool/tarantool#2839]
I used to store some additional fields in space:format, cauze it's convenient to store space's schema in one place, which is designed for it.
Now I got this exception: "Wrong space format (field 1): unexpected option 'myCustomFieldHere'"

Possible solutions:
* remove any check;
* warning on "unexpected option";
* yet another flag to switch this behavior.

version: 1.7.5-196-g77db87ce4

**Comment by rtsisyk** [comment]
1.7.5-267-gf688ef36a
