### ISSUE TITLE
Rocksfile: a file specifying lua package dependencies

### ISSUE THREAD

**Issue by knazarov** [tarantool/tarantool#2848]
I suggest to introduce a file, called `Rocksfile` that can be placed in the root of any tarantool project and which will specify all its Lua dependencies. 

Example `Rocksfile`:
```sh
package-one==1.9.4
git+https://github.com/path/to/package-two@41b95ec#rockspec=path-to-rockspec
package-three==1.0.1
./local/path/to-package#rockspec=path-to-rockspec
```

Without additional arguments, this will install all packages from Rocksilfe to .rocks:
```sh
tarantoolctl rocks install
```

**Comment by kostja** [comment]
I like the idea, but I think it's a feature request to LuaRocks. Why not file it there?

**Comment by racktear** [comment]
@kostja because this is unlikely to happen in luarocks, for political reasons. 

Plus, it's trivially doable outside of luarocks: we need to just parse the file and delegate execution to the existing luarocks functionality.

**Comment by racktear** [comment]
@kostja Sorry, but I don't want it bad enough to negotiate the feature with luarocks authors. You can move it to general wishlist.

**Comment by Totktonada** [comment]
A rockspec has `dependencies` field. Why a separate file for dependencies is needed?

**Comment by knazarov** [comment]
No longer needed. We figured out how to do it just with rockspecs.
