### ISSUE TITLE
Error messages related to format()

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#2855]
I have Ubuntu 14.04 and Tarantool 1.7, pulled from source today.

I fear that some error messages, related to recent changes for the `format()` clause, may mislead users.

```
box.schema.space.create('T')
box.space.T:create_index('I',{parts={1,'scalar'}})
box.space.T:insert{1}

box.space.T:format({{name='field_id', type='integer'}, {name='The rain in Spain falls mainly in the Plain', type='integer'}})
```

```
tarantool> box.space.T:format({{name='field_id', type='integer'}, {name='The rain in Spain falls mainly in the Plain', type='integer'}})
---
- error: Ambiguous field type, field 1. Requested type is scalar but the field has
    previously been defined as integer
...
```

... The error message is incorrect, the request is not ambiguous, the requested type is what's in the request, so: `Requested type is integer but the field has previously been defined as scalar.`

```
tarantool> box.space.T:format({{name='field_id', type='scalar'}, {name='The rain in Spain falls mainly in the Plain', type='integer'}})
---
- error: Tuple field count 1 is less than required by a defined index (expected 2)
...
```

... The error message is incorrect, the field count is more than required by a defined index.

```
tarantool> box.space.T:create_index('I12',{parts={{{'x'}},{'y'}}})
---
- error: 'Illegal parameters, options.parts[1]: field (name or number) is expected'
...
```
... The error message is incorrect, 'x' is a valid field name. The real problem is that the number of braces is not the same for both 'x' and 'y'. (By the way, I do not understand why a user will ever want to use more braces than necessary.)

```
box.schema.space.create('T2')
box.space.T2:create_index('I',{parts={1,'scalar'}})
box.space.T2:format({{name='x'}, {name='y', type='integer'}})
```

```
box.space.T2:create_index('I9',{parts={'x'}})
---
- error: 'Can''t create or modify index ''I9'' in space ''T'': field type ''any''
    is not supported'
```

... The error message is correct, but users are not told there is a field type named 'any'. Suggestion: `"a field does not have a type defined with a format clause"`.

**Comment by kyukhin** [comment]
Closed by mistake
