### ISSUE TITLE
Raise on raw modifications of box.cfg values

### ISSUE THREAD

**Issue by Mons** [tarantool/tarantool#2867]
```sh
tarantool
> box.cfg{}
> box.cfg.read_only
false
> box.cfg.read_only = true
> box.cfg.read_only
true
```

I'd expect 3rd command should raise and cfg table at all would be readonly

Updated (25.01.2023): RFC - https://www.notion.so/Raw-modifications-of-box-cfg-values-9f440d321f984389a22bcb3f81366ea7

**Comment by rtsisyk** [comment]
Hi,
It is not possible technically in Lua :(

**Comment by Mons** [comment]
Why not?
```lua
tarantool> local actual = { read_only = false } cfg = setmetatable({}, { __index = function(self,k) return actual[k] end, __newindex = function() error("Restricted",2) end, __serialize = function() return actual end })
---
...

tarantool> cfg                                                                                                                                                                  ---
- read_only: false
...

tarantool> cfg.read_only
---
- false
...

tarantool> cfg.read_only = true
---
- error: '[string "cfg.read_only = true"]:1: Restricted'
...
```

**Comment by kostja** [comment]
This affects all newbies.

**Comment by unera** [comment]
> It is not possible technically in Lua :(

Почему?
я думаю надо шире идти:

у каждого инстанса должно быть не два, а больше статусов:

1. readonly (отвечает по протоколу клиентам, но не разрешает делать изменения на данной реплике)
2. readwrite
3. inaccessible - не отвечает клиентам (а только репликам)


и сделать функцию, которая может В ЛЮБОЙ момент переводить инстанс между стейтами.

Далее:

1. дать возможность определить свой триггер на коннект/дисконнект реплик
2. дать инфу по стейту всех реплик: приконнекчена

И далее пользователь может определить через box.cfg функцию которая по дефолту дергается из данного триггера.

Тогда:

1. Старое поведение: функция всегда переводит в rw
2. Текущее (реплики неюзабельны): функция переводит в rw только если все реплики в статистике помечены как приконнектившиеся
3. Манипуляции с кворумами: в зависимости от числа приконнекченных

## Дополнительные фичи

дополнительно получим фичу безпростойного апгрейда БД:

1. переводим в inaccessible
2. апгрейдим/перезапускаем
3. переводим в ro/rw

статус inaccessible:

1. обрабатывает запросы от реплик в обычном режиме
2. прочие запросы от iproto приостанавливают вычитку из сокета до тех пор пока реплика не станет readonly или readwrite

как-то так надо делать.

но прежде всего надо бы починить мастер-мастер репликацию. А то тикет закрыли конечно хорошо. Но репликация от этого юзабельнее не стала

**Comment by Mons** [comment]
@unera, I think your ideas are not for this ticket. They are reasonably good, but create it as another ticket

**Comment by IlyaMarkovMipt** [comment]
@Mons The approach you propose reduces the abilities of the current `box.cfg`.
Lua 5.1 does not support `__pairs`, `__ipairs`, `__next` metamethods, so we can't redefine pairs/ipairs operators.

**Comment by Totktonada** [comment]
@IlyaMarkovMipt I use the following trick:

```
local rawpairs = pairs

--- Replacement for global pairs function to call __pairs() if it exists.
function pairs(table) -- luacheck: ignore
    local mt = getmetatable(table)
    local p = mt and mt.__pairs or rawpairs
    return p(table)
end
```

**Comment by GeorgyKirichenko** [comment]
I don't like global pairs redefinition, and i'm not sure that we really need to protect box.cfg now. At least until box will be a separate library or some other global change.

**Comment by GeorgyKirichenko** [comment]
@kostja i think you should make a decision about this ticket - will we do it now or later

**Comment by Totktonada** [comment]
We'll elaborate possible ways on #4521 and will return then to this issue.
