### ISSUE TITLE
redhat6 rpm download failure

### ISSUE THREAD

**Issue by hellower** [tarantool/tarantool#2869]
[root@redhat6:/var/cache]
# cat /etc/yum.repos.d/tarantool_1_7.repo 
[tarantool_1_7]
name=EnterpriseLinux-$releasever - Tarantool
baseurl=http://download.tarantool.org/tarantool/1.7/el/$releasever/$basearch/
gpgkey=http://download.tarantool.org/tarantool/1.7/gpgkey
repo_gpgcheck=1
gpgcheck=0
enabled=1

[tarantool_1_7-source]
name=EnterpriseLinux-$releasever - Tarantool Sources
baseurl=http://download.tarantool.org/tarantool/1.7/el/$releasever/SRPMS
gpgkey=http://download.tarantool.org/tarantool/1.7/gpgkey
repo_gpgcheck=1
gpgcheck=0
[root@redhat6:/var/cache]
# uname -a
Linux redhat6 2.6.32-573.el6.x86_64 #1 SMP Wed Jul 1 18:23:37 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux
[root@redhat6:/var/cache]
# cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 6.7 (Santiago)
[root@redhat6:/var/cache]

#  yum -y install tarantool
Loaded plugins: product-id, refresh-packagekit, security, subscription-manager
Setting up Install Process
http://download.tarantool.org/tarantool/1.7/el/6Server/x86_64/repodata/repomd.xml: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"
Trying other mirror.
Error: Cannot retrieve repository metadata (repomd.xml) for repository: tarantool_1_7. Please verify its path and try again
[root@redhat6:/var/cache]
#

**Comment by rtsisyk** [comment]
Hi, please change http://download.tarantool.org/tarantool/1.7/el/$releasever/$basearch/ to http://download.tarantool.org/tarantool/1.7/el/6/$basearch/ (explicit "6" instead of $releasever).

**Comment by rtsisyk** [comment]
https://github.com/tarantool/doc/issues/327
