### ISSUE TITLE
vinyl: log selects that took too long

### ISSUE THREAD

**Issue by locker** [tarantool/tarantool#2871]
In some extreme cases a `select()` may take seconds or even minutes in vinyl even if it returns just a few tuples. To be able to debug such cases, we at least need to log problematic requests. I suggest to introduce a new configuration parameter, `vinyl_too_long_threshold`, and log arguments of `select()` and the problematic statement in case a read iteration took more time than specified by this parameter.

**Comment by rtsisyk** [comment]
I think that too_long_thresolhd option is enough for all cases.

**Comment by rtsisyk** [comment]
af63fcbe3c0511359af20da4f888c1e843209a26
