### ISSUE TITLE
vinyl: abort bootstrap if vinyl_dir is not empty

### ISSUE THREAD

**Issue by locker** [tarantool/tarantool#2872]
If tarantool is restarted from an empty snapshot directory, while the `vinyl_dir` contains data left from an old setup (which happens e.g. if the user sets a wrong `memtx_dir` by mistake), the tarantool instance will successfully bootstrap, but since there vylog files from the old and the new setup mixed in the same directory, there will be errors once the user starts using vinyl:
```
vinyl.c:835 E> 512/0: dump failed: file './512/0/00000000000000000001.run' already exists
vy_log.c:1095 E> failed to rotate metadata log: file './00000000000000000005.vylog' already exists
```
What is worse, the new instance is likely to fail to recover after restart:
```
vy_log.c:886 E> ER_MISSING_SNAPSHOT: Can't find snapshot
```
To avoid this, we should abort bootstrap if the vinyl directory contains vylog files.

**Comment by rtsisyk** [comment]
1.7.5-264-g4d796a8c3
