### ISSUE TITLE
Support bcrypt password hashing algorithm

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#2874]

**Comment by racktear** [comment]
Discussed with @IlyaMarkovMipt 

Agreed to first implement PBKDF2, because it's in openssl already, and then bcrypt.

**Comment by rtsisyk** [comment]
Awaiting check from @Totktonada

**Comment by racktear** [comment]
@rtsisyk сейчас PBKDF2_ITERATIONS захардкожен. Нужно сделать его параметром.

**Comment by Totktonada** [comment]
Да и длину хэша я бы тоже вынес в параметр.

**Comment by rtsisyk** [comment]
ok

**Comment by Totktonada** [comment]
@IlyaMarkovMipt, thanks!

I observed the behaviour unexpected for me: length of a resulting hash differs in dependence of iterations count. Consider the following example.

```
tarantool> digest.pbkdf2('text', 'salt', 1000000, 128):hex():len() / 2
---
- 8
...

tarantool> digest.pbkdf2('text', 'salt', 100000, 128):hex():len() / 2
---
- 128
...

tarantool> digest.pbkdf2('text', 'salt', 10000, 128):hex():len() / 2
---
- 60
...
```

@IlyaMarkovMipt, can you please explain that?

**Comment by Totktonada** [comment]
I performed the following tests:

1. The time needed for hashing depends of iterations count.
2. Same input+salt — same output.
3. Different output for different salt.
4. Run the following command:

```
fiber.create(function() for i = 1, 10000 do digest.pbkdf2('text', 'salt', 100000, 128) end end)
```

I can use tarantool from the console as before, while hashing performed in “background”. Looks good!

**Comment by Totktonada** [comment]
The hash for an empty string can be short too.

```
tarantool> digest.pbkdf2('', 'sadfdfdffdlt', 100000, 128):hex()
---
- b420fd
...

tarantool> digest.pbkdf2('', 'salt', 100000, 128):hex()
---
- 378a8bda976ade0a4497d2a04bd1ce352bc66c389947624ae5fab8c62074a37118a459e7ee26a8d225b5433aa06dd391daafdc9e5aaab2985b8c0e45a52b5dbd61fabd527fe65e66b7d902f66b6607358c3ed34a6b5fb812cbe334f90bcee2407d323550fc1fb4dfb4a771e1a58304644866ef779887096bd2b676f3d68837e4
```

**Comment by Totktonada** [comment]
Observed random segfaults after this patch applying (more info was provided via the chat).

**Comment by Totktonada** [comment]
The hash length now is one that expected! As the last check I’ll try it in the cofiguration where I got segfaults previously.

**Comment by Totktonada** [comment]
Checked, seems work.

**Comment by rtsisyk** [comment]
Pushed to upcoming 1.7.7 (1.7.6-47-g93980aeff)

**Comment by ElusiveSpirit** [comment]
What about supporting bcrypt?

**Comment by Totktonada** [comment]
There are no such plans ATM. Feel free to file another issue if there is a demand.
