### ISSUE TITLE
vinyl: optimize select in case primary key is updated while secondary keys are not

### ISSUE THREAD

**Issue by locker** [tarantool/tarantool#2875]
Vinyl doesn't store tuples, instead it stores statements, such as DELETE, REPLACE, and UPSERT. For instance, if there's tuple `{1, 1}` in a vinyl space with the primary key over the first field, and the user calls `space:replace{1, 2}`, the following statements will be appended to the memory level of the space's primary index: `DELETE{1}`, `REPLACE{1, 2}`. If the space has secondary indexes, they will be updated in a similar fashion. When `space:select()` is called, all statements corresponding to the requested key will be iterated until a terminal statement, i.e. REPLACE, is found. As a result, the more UPSERT and DELETE statements there are for the requested key in the index, the longer one iteration of `space:select()` will take so we should strive to discard non-terminal statements whenever we can.

We already try to squash UPSERT statements upon inserting them into the memory tree, but DELETEs are never discarded, because we need them as tombstones. However, there's a case that we've seen in production that may still be optimized. It is illustrated by the following script:
```
clock = require 'clock'

box.cfg{}

box.once('init', function()
    local s = box.schema.space.create('test', {engine = 'vinyl'})
    s:create_index('primary')
    s:create_index('secondary', {unique = false, parts = {2, 'unsigned'}})
    s:insert{1, 1}
    box.snapshot()
    for i = 1, 100000 do
        s:delete(i)
        s:replace{i + 1, 1}
    end
    box.snapshot()
end)

t1 = clock.monotonic()
box.space.test.index.secondary:select(1)
t2 = clock.monotonic()

print(string.format('select() took %.3f seconds', t2 - t1))

os.exit(0)
```
The script generates 100K pairs of `DELETE{i, 1}` + `REPLACE{i + 1, 1}` statements in the secondary index. The `box.space.test.index.secondary:select(1)` has to iterate them all before it can return the final statement, which is `{100001, 1}`, because they all match the search criteria. On my laptop the `select()` takes about half a second even though the disk isn't involved. In production the dummy statements may end up scattered among several disk runs. There also may be concurrent requests, which also increases the cost of disk accesses. We observed that a `select()` took several minutes in worst cases.

It seems that we can optimize this particular case by removing `REPLACE{i, 1}` + `DELETE{i, 1}` from the memory level upon statement insertion, because in case of secondary keys there shouldn't be two sequential REPLACE statements for the same full key ('full' means including the primary key part).

**Comment by locker** [comment]
It also make sense to discard REPLACE + DELETE pairs for primary keys, but this is more sophisticated, because in contrast to secondary keys, there may be two successive REPLACE statements for the same key in a primary index.

One way to deal with it is to introduce [SingleDelete](https://github.com/facebook/rocksdb/wiki/Single-Delete) operation, similarly to how it is done in RocksDB. SingleDelete acts like conventional Delete, but instead of appending a DELETE statement to the memory level, it removes the last REPLACE for the deleted key. SingleDelete is only safe to call if there is no REPLACE statements preceding the deleted statement. It is not a very elegant solution as it shifts responsibility to the user.

Another option is to discern INSERT from REPLACE in memory. For instance, `space:insert()` may not succeed if the last statement for the inserted key is REPLACE. This means that when the key is deleted, we can safely drop the new REPLACE from the memory level instead of appending a DELETE.

**Comment by rtsisyk** [comment]
1.7.6 is almost frozen, moving to 1.7.7

**Comment by rtsisyk** [comment]
Requires https://github.com/tarantool/tarantool/issues/2897 for testing on the production
