### ISSUE TITLE
Remove BITSET index in 1.8

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#2881]
We have no throughput to maintain it, no users.

**Comment by bofm** [comment]
So sad that you are throwing it away. The main reason nobody uses it may be the fact that it is not possible set this index on a PR tuple part. The overhead of HASH or TREE index on PK contradicts with the idea of saving space on large sets of integers with BITSET index.

**Comment by zloidemon** [comment]
Users #2974, #1728 issues. Main issue with BITSET is not enough documentation with real world use cases to understand that index.

**Comment by nekufa** [comment]
Maybe you can keep it in current implementation without any improvements?
We use bitset for entity state persistence and flexible data selection..

**Comment by kostja** [comment]
OK, thank you for your feedback. I'll see what can be done, for now I'm closing this bug.
