### ISSUE TITLE
Remove db descriptor from SQL sources

### ISSUE THREAD

**Issue by TheAviat0r** [tarantool/tarantool#2883]
Each database in SQL had its unique number called 'iDb' >= 0. But opportunity to have multiple databases was removed, after that code had been refactored. However, lots of VDBE opcodes like 'ReopenIdx', 'OpenRead', 'OpenWrite' have an iDb recorded in registers.

```
 /* 100 */ "ReopenIdx"        OpHelp("root=P2 iDb=P3")
 /* 101 */ "OpenRead"         OpHelp("root=P2 iDb=P3") 
```

It is not necessary now, because iDb is always equal to 0, so opcodes and VDBE should be refactored.

**Comment by kyukhin** [comment]
Done by f92bc1e66
