### ISSUE TITLE
Assertion with new index options

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#2885]
I have Ubuntu 14.04 and Tarantool 1.7 pulled from source today.
I execute these requests:
box.cfg{listen=3301}
box.schema.space.create('T', {engine='memtx'})
box.space.T:create_index('primary')
box.space.T:create_index('secondary', {unique=true, parts = {{2, 'boolean', is_nullable = true},{3, 'string', is_nullable = false}}})
box.space.T:insert{6,true,'c'}
box.space.T:insert{7,false,'c'}

The result looks like this:
tarantool> box.space.T:insert{7,false,'c'}
tarantool: /home/pgulutzan/tarantool-1.7/src/box/tuple_compare.cc:407: int tuple_compare_field_with_hint(const char*, mp_type, const char*, mp_type, int8_t, coll*): Assertion `0' failed.

**Comment by locker** [comment]
Fixed by ea2a11391e900609376c3bfaa1d4d929eef46782
