### ISSUE TITLE
community: add CONTRIBUTING.md

### ISSUE THREAD

**Issue by Quasilyte** [tarantool/tarantool#2889]
`CONTRIBUTING.md` is a flag for open-source project that tells: "contributions are welcome".
If it is not such a project, this issue can be closed immediately.

It can be a small file that contains references to external resources, like [contributors guide](https://tarantool.org/en/doc/1.7/dev_guide/index.html).
Good example: [golang/go/CONTRIBUTING.md](https://github.com/golang/go/blob/master/CONTRIBUTING.md).

This file reduces the time that is required to find useful tips and guidelines
to start contributing.

[Setting guidelines for repository contributors](https://help.github.com/articles/setting-guidelines-for-repository-contributors/).

Thank you.

**Comment by kostja** [comment]
Hi, care to send a pull request?

**Comment by Quasilyte** [comment]
@kostja, as soon as I get more familiarity with the project.
Maybe in a week or two.

**Comment by kostja** [comment]
ping

**Comment by Quasilyte** [comment]
I was distracted by other projects and activities, sorry.
