### ISSUE TITLE
Using 'num' in index definition leads to strange warning: "field type 'num' is deprecated since Tarantool 1.7, please use 'nil' instead"

### ISSUE THREAD

**Issue by sharonovd** [tarantool/tarantool#2892]
user_roles:create_index('user_id', {parts = {
                {field=1, type='num'}
        }})

14:02:28 rp.1       | 2017-11-03 14:02:28.151 [18689] main/102/lua schema.lua:713 W> field type 'num' is deprecated since Tarantool 1.7, please use 'nil' instead

**Comment by rtsisyk** [comment]
Fixed in 1.7.6
