### ISSUE TITLE
space format ignores field types

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#2895]
```Lua
tarantool> format = {}
---
...

tarantool> format[1] = {name = 'field1', 'unsigned'}
---
...

tarantool> format[2] = {name = 'field2', 'unsigned'}
---
...

tarantool> s = box.schema.create_space('test', {format = format})
---
...

tarantool> s:format()
---
- [{'name': 'field1', 'type': 'any'}, {'name': 'field2', 'type': 'any'}]
```

Format contains fields with unsigned type, but the result format contains 'any' type.

**Comment by Igorjan94** [comment]
Is it intended, that `format[1] = {name = 'field1', 'unsigned'}` doesn't have `type = `?

**Comment by Gerold103** [comment]
@Igorjan94 I think, that there must be either error on such format (with no 'type='), or correct processing (allow to do not write 'type=').
But here I wrote type='unsigned', and there is no error and the real type became 'any'.
