### ISSUE TITLE
Audit log

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#2902]
Implement box.cfg { audit = "file|pipe|syslog" } to log secuiry events:

- Successful user login
- Unsuccessful user login
- Logging out of the system or closing the user session
- Unsuccessful attempts to access protection objects (personal data, detail, subscriber's location, etc.)
- Creating an account in the system
- Deleting an account in the system
- Blocking an account in the system
- Unlocking an account in the system
- Assigning (changing) the access rights (roles, profiles, etc.) of the account

**Comment by IlyaMarkovMipt** [comment]
Moved to gitlab
