### ISSUE TITLE
Implement TPC-H

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#2903]
In order to measure performance of OLAP workloads, need to add benchmarking for [1].

[1] - http://www.tpc.org/tpch/default.asp

**Comment by iproha94** [comment]
• research tpch-documentation [ref](http://www.tpc.org/tpc_documents_current_versions/pdf/tpc-h_v2.17.3.pdf)
• studied percona tpch implementation (python, mysql) [ref](https://www.percona.com/blog/2008/04/10/tpc-h-run-on-mysql-51-and-60/)
• studied noname tpch implementation (shell, php, postgresql) [ref](https://github.com/tvondra/pg_tpch
) 
Conclusion: there is no simple way to implement tpch for tarantool

**Comment by tsafin** [comment]
Waiting till tsafin/tnt-tpch#1 be resolved before transferring to QA

**Comment by tsafin** [comment]
- [ ] TPC-H benchmark integration to our regular testing will be done in #5010

**Comment by kyukhin** [comment]
Done.
