### ISSUE TITLE
IPROTO: call returns wrong tuple

### ISSUE THREAD

**Issue by unera** [tarantool/tarantool#291]
Iproto call 

```lua
box.name.index.index_name:select('unexists key')
```

returns msgpack that contains **one tuple** that contains empty array

**Comment by kostja** [comment]
We added EVAL command which is tailored specifically for safe RPC. See http://tarantool.org/doc/box-protocol.html for details.

**Comment by rtsisyk** [comment]
Tarantool 1.7.x will use EVAL-style output for CALL.
However, this problem is still actual for #1296.

**Comment by rtsisyk** [comment]
One more use-case from #1167:

    function f() local res = {} res[1] = 1 res[20] = 1 return res end
