### ISSUE TITLE
New versioning scheme for pre-release packages

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#2913]
Currently pre-release packages uses git tag of the previous release + the number of commit since this tag. For example, upcoming 1.7.7 packages are versioned "tarantool-1.7.6.x", which confuses the uses and creates collisions with 1.7.6 hotfixes. We need to find another scheme for versioning pre-releases packages.

**Comment by rtsisyk** [comment]
Raw Idea 1: use 1.7.7.0+gitsha for pre-release packages and 1.7.1.x for releases and hotfixes.
See http://semver.org/

**Comment by kostja** [comment]
Until there is a clear idea what to do, it should sit on wishlist.
We're not following semver for an entirely different reason:
"
Patch version Z (x.y.Z | x > 0) MUST be incremented if only backwards compatible bug fixes are introduced. A bug fix is defined as an internal change that fixes incorrect behavior.
"

**Comment by kostja** [comment]
A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-]. Identifiers MUST NOT be empty. Numeric identifiers MUST NOT include leading zeroes. Pre-release versions have a lower precedence than the associated normal version. A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version. Examples: 1.0.0-alpha, 1.0.0-alpha.1, 1.0.0-0.3.7, 1.0.0-x.7.z.92.

**Comment by IlyaMarkovMipt** [comment]
Proposed solution:
* for pre-release: 1.7.7.0.dev-0.<number of commits>
* for releases: 1.7.7.1<hash>-1
* for release fixes: 1.7.7.X<hash>-1, where (X - 1) is number of fix

**Comment by kostja** [comment]
Won't fix - we changed the release policy.
