### ISSUE TITLE
identifier names have commin constraints (func, space, index...) Allow all printable characters

### ISSUE THREAD

**Issue by Khatskevich** [tarantool/tarantool#2914]
This snippet works, but should not.
```
box.cfg{wal_mode="none"}

sp = box.schema.space.create("sp")
sp:format({{name="$ $", type="scalar"}})
```

**Comment by Khatskevich** [comment]
As we decided to allow any identifier (#2126), we need only to check that identifier is a valid unicode (utf8) string

**Comment by Khatskevich** [comment]
Lua autocomplete possibly do not support utf8 symbols (symbols assumed to be 1 byte)

**Comment by rtsisyk** [comment]
On @kostja review
