### ISSUE TITLE
Change output format for binary data in YAML

### ISSUE THREAD

**Issue by Mons** [tarantool/tarantool#2917]
Currently binary data are formatted as

```
tarantool> "\x00\x01\x02\x03\x04\x05\x06\xff"
---
- !!binary AAECAwQFBv8=
...
```
The propose is to output ASCII as is and everything outside [0x20..0x7f] as "\x%02X"
This would be usable either in Lua or in YAML.

**Comment by bigbes** [comment]
Disagree, YAML doesn't support escaping, so we can't copy/paste yaml output, and use `yaml.decode` and expect that everything will be ok.

**Comment by Mons** [comment]
```
tarantool> yaml.decode("---\n- \"xx\\x00\\x01\\x02\\x03\\x04\\x05\\x06\\xffx\"\n")
---
- ["xx\0\x01\x02\x03\x04\x05\x06ÿx"]
```

**Comment by rtsisyk** [comment]
libyaml doesn't support this feature. We need to fork libyaml to implement it..

**Comment by bigbes** [comment]
@Mons your example contains escaped string, mostly, not raw one.

**Comment by Mons** [comment]
@bigbes, yes, after some investigation I found, that hex escaping is about unicode, not raw.
So, closing this
