### ISSUE TITLE
Package numbering is broken: 1.8 repo on packagecloud contains 1.7.6 packages

### ISSUE THREAD

**Issue by aensidhe** [tarantool/tarantool#2919]
https://packagecloud.io/tarantool/1_8?page=1

It seems that this should contain one more line: https://github.com/tarantool/tarantool/blob/e9af40c4b1235cd3197e802dd9a7c6852539f47d/.travis.yml#L86

**Comment by rtsisyk** [comment]
yeah, we forgot to push a fix.

**Comment by aensidhe** [comment]
Workaround is to use https://hub.docker.com/r/progaudi/tarantool/

**Comment by kostja** [comment]
This is fixed now.
