### ISSUE TITLE
Question lua5.2 compatiblity

### ISSUE THREAD

**Issue by hellower** [tarantool/tarantool#2921]
How can I compile tarantool with -DLUAJIT_ENABLE_LUA52COMPAT (luajit)?
or
Can you release tarantool binaries (rpm) with the -DLUAJIT_ENABLE_LUA52COMPAT option?

sorry for poor english.

**Comment by rtsisyk** [comment]
Hi, -DLUAJIT_ENABLE_LUA52COMPAT is arguble, because it doesn't implement Lua 5.2 fully. We discussed this option long time ago and decided to stay away. Why do you need it?

**Comment by hellower** [comment]
I'm testing tarantool with openresty + tarantool nginx_upstream_module

openresty (default :  luajit  2.1beta  + DLUAJIT_ENABLE_LUA52COMPAT option).
but tarantool (default: without  DLUAJIT_ENABLE_LUA52COMPAT )

I just want to write the same version luajit script.
sorry for my poor english.
