### ISSUE TITLE
Add file_exists() to fio module

### ISSUE THREAD

**Issue by racktear** [tarantool/tarantool#2924]
Checking whether a file exists is necessary in many places in Lua code. Checking for fio.stat() to not be nil is not very idiomatic. 

Thus I propose to add fio.file_exists()

**Comment by rtsisyk** [comment]
fio.path.exists()

**Comment by rtsisyk** [comment]
Status?

**Comment by rtsisyk** [comment]
Copy-cat Python's os.path:

- os.path.exists()
- os.path.lexists()
- os.path.isfile()
- os.path.islink()
- os.path.isdir()
- os.path.ismount()

**Comment by kostja** [comment]
Pushed in 1.7.7
