### ISSUE TITLE
SQL identifiers and system spaces

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#2927]
I have Ubuntu 14.04. I have Tarantool 1.8 pulled from source today.

I believe that regular and delimited identifiers of system tables
(where the underlying space begins with "_")
are not handled correctly with SQL.

Suppose I say
CREATE TABLE a (s1 INT PRIMARY KEY);
The result is: a table named A is created.
(It's easy to see this with box.space._space:select().
The space name is A.)
If I later say
SELECT * FROM a;
I see what is in table A.

Suppose I say
CREATE TABLE "a" (s1 INT PRIMARY KEY);
The result is: a table named a is created.
If I later say
SELECT * FROM "a";
I see what is in table a.

So I can see that the rule for regular identifiers is:
convert identifier to upper case before accessing the database.
And the rule for delimited identifiers is:
do not convert to upper case before accessing the database.

These rules are compatible with standard SQL requirements.
It is wonderful that the Tarantool developers made it work
properly, instead of trying to do case-insensitive comparisons.

But with _space, _cluster, etc. those rules are not followed.

SELECT * FROM _space;
I see what is in _space, the system space.
So this particular regular identifier was
not converted to upper case.

CREATE TABLE "_SPACE" (s1 INT PRIMARY KEY);
I get "error: table _SPACE already exists".
So this particular delimited identifier was
handled with a case-insensitive comparison.

I believe that this behaviour occurs for
_cluster _collation _func _index _priv _schema
_sequence _space _space_sequence _trigger _truncate
_user _vspace _vindex _vuser vpriv.
But I did not check them all.

**Comment by Khatskevich** [comment]
Already fixed.
