### ISSUE TITLE
Savepoint not found

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#2931]
I have Ubuntu 14.04. I have Tarantool 1.8, pulled from source today.
I execute these requests (all on one line):
`
box.sql.execute([[BEGIN TRANSACTION; ]]) box.sql.execute([[SAVEPOINT Q; ]]) box.sql.execute([[RELEASE SAVEPOINT Q; ]]) box.sql.execute([[COMMIT ]])
`

The result is:
`- error: 'no such savepoint: Q'`

**Comment by kyukhin** [comment]
`ROOLBACK` seems to be broken as well:
```
tarantool> box.sql.execute([[BEGIN TRANSACTION; ]]) box.sql.execute([[SAVEPOINT Q; ]]) box.sql.execute([[ROLLBACK TO SAVEPOINT Q; ]])
---
- error: 'no such savepoint: Q'
...
```

**Comment by kyukhin** [comment]
Done @ c3d5944dd3a2e21e293912d6e4e052065da1982a
