### ISSUE TITLE
Tarantoolctl cannot connect to unix binary socket using authentication

### ISSUE THREAD

**Issue by sharonovd** [tarantool/tarantool#2933]
Application code:
...
box.cfg({listen='/tmp/p2phub.sock'})
box.schema.user.passwd('admin', '1q2w3e')
...
Starts okay:
10:57:12 p2phub.1   | 2017-11-21 10:57:12.307 [18823] main C> entering the event loop

Connect without auth works ok:
d:p2phub d.sharonov$ tarantoolctl connect "unix/:/tmp/p2phub.sock"
Execute access on universe is denied for user 'guest'

Connect using auth does not work 9=probably some url parse issue):
d:p2phub d.sharonov$ tarantoolctl connect "admin:1q2w3e@unix/:/tmp/p2phub.sock"
builtin/box/console.lua:306: Usage: console.connect("[login:password@][host:]port")

---
Explanation
---
Connection works fine:

tarantool> netb = require('net.box')
tarantool> netb.connect('/tmp/p2phub.sock', {user = 'admin', password = '1q2w3e'}) // OK

Problem with our uri parser:

tarantool> uri = require('uri')
tarantool> uri.parse('unix/:/tmp/p2phub.sock')
  host: **unix/**
  **service**: /tmp/p2phub.sock
  unix: /tmp/p2phub.sock

tarantool> uri.parse('admin:1q2w3e@unix/:/tmp/p2phub.sock')
  password: 1q2w3e
  **path**: /tmp/p2phub.sock
  host: **unix**
  login: admin

quick fix/workaround proposal:

_if u ~= nil and u.host == 'unix' and u.service == nil then
    u.service = u.path
    u.host = 'unix/'
end_

Or to fix uri parser (more complex)

**Comment by kbelyavs** [comment]
Last commit with 'merge' was just to check tests, since previous two failed with unknown reason (different reason, but identical code, may be some bug with Travis CI?)
