### ISSUE TITLE
RPS - 1.7 vs. 1.6

### ISSUE THREAD

**Issue by kmansoft** [tarantool/tarantool#2939]
Follow-up to:

https://groups.google.com/d/msg/tarantool-ru/qa1LJz8eryU/_JgfOcroCAAJ

Summary:

In our app (Tarantool + Go lang), we're seeing pretty significant RPS drop from 1.6.9 to 1.7.*

A test app with a README:

https://github.com/kmansoft/tarantool_1_7_rps_perf_drop

In short:

Terminal window 1:

`rm -v 000* ; ./push_db_server.lua`

Terminal window 2:

`./run_test_db_server.sh subs ping change`

During the "subs" test (documented in the README), Tarantool 1.6 gives consistent 42K - 65K RPS.

With Tarantool 1.7, there are temporary but consistent "drops" during this test all the way down to about 12-13K RPS.

My main system is Fedora (x86_64, 32 GB RAM, NVME SSD).

Downgrading to Tarantool 1.6.9.52 from Fedora reps makes the issue go away.

Running the test in /tmp also makes it go away, which makes me think the issue is related to I/O.

I have tried running a Tarantool 1.7 branch which has a setting to disable WAL compression - performance improved a bit overall, but the "drops" did not go away.

I am also able to reproduce on Ubuntu 17.10 with Tarantool 1.7. Can't downgrade to 1.6 there for a comparison, but the "drops" with 1.7 are there.

**Comment by kostja** [comment]
@GeorgyKirichenko, please write a summary here about your findings. After that I believe the ticket can be closed.

**Comment by GeorgyKirichenko** [comment]
@kmansoft i still can't reproduce the issue with exact same tarantool versions. But i can create two tarantool stands and open tarantool ports for you.

**Comment by kostja** [comment]
Please let's continue using instant messaging, the results are not reproducible on our hardware.
