### ISSUE TITLE
box.schema.func.reload only work with a function name

### ISSUE THREAD

**Issue by tonyfreeman** [tarantool/tarantool#2946]
`box.schema.func.reload()` only work with a function name but the documentation says that it should work with a module name and also without any arguments to reload everything https://tarantool.org/en/doc/1.7/book/box/box_schema.html?highlight=reload#lua-function.box.schema.func.reload
```lua
tarantool> box.schema.func.reload()
---
- error: 'bad argument #1 to ''?'' (string expected, got no value)'
...

tarantool> box.schema.func.reload("function1_module")
---
- error: Function 'function1_module' does not exist
...
```

**Comment by rtsisyk** [comment]
There is no way to implement such behavior.

**Comment by rtsisyk** [comment]
I can't fix this bug. Tarantool operates only with functions and I can't add an option to reload entire module because there are no such entity "module" in our data dictionary.

**Comment by kostja** [comment]
To force-reload everything introduce '.so' function versioning, and bump the version to force eventual reload of all function.
