### ISSUE TITLE
source archive from releases page not build

### ISSUE THREAD

**Issue by norguhtar** [tarantool/tarantool#2947]
For example download 
https://github.com/tarantool/tarantool/archive/1.7.6.tar.gz (Source code)

tar -xvf 1.7.6.tar.gz 
cd tarantool-1.7.6
cmake .

got:
CMake Error at CMakeLists.txt:53 (message):
  Failed to find submodules

-- Configuring incomplete, errors occurred!
See also "/home/ubuntu/tarantool/tarantool-1.7.6/CMakeFiles/CMakeOutput.log".

Version 1.6
https://github.com/tarantool/tarantool/archive/1.6.9.tar.gz (Source code)

tar -xvf 1.6.9.tar.gz
cd tarantool-1.6.9
cmake .

got:
CMake Error at CMakeLists.txt:165 (message):
  Unable to retrive version from git or
  /home/ubuntu/tarantool/tarantool-1.6.9/VERSION file.

**Comment by bigbes** [comment]
It shouldn't work - VERSION file is autogenerated from `git describe` command.  Use https://github.com/tarantool/tarantool/releases/download/1.7.6/tarantool-1.7.6.0.tar.gz link, instead, or from tarantool tar.gz archive.

**Comment by norguhtar** [comment]
Ok
