### ISSUE TITLE
sql: remove unnecessary templates for binding parameters

### ISSUE THREAD

**Issue by iproha94** [tarantool/tarantool#2948]
Tarantool (SQLite): In the SQL statement literals may be replaced by a parameter that matches one of following templates:
* ?
* ?NNN
* :VVV
* @VVV
* $VVV
In the templates above, NNN represents an integer literal, and VVV represents an alphanumeric identifier.

Need to remove templates that are not used by other vendors.

**Comment by iproha94** [comment]
## MySQL 
User variables are written as @var_name, where the variable name var_name consists of alphanumeric characters, ., _, and $. A user variable name can contain other characters if you quote it as a string or identifier (for example, @'my-var', @"my-var", or @`my-var`).

[ref1](https://dev.mysql.com/doc/refman/5.7/en/sql-syntax-prepared-statements.html)
[ref2](https://dev.mysql.com/doc/refman/5.7/en/user-variables.html)
Example:
```
PREPARE stmt1 FROM 'SELECT SQRT(POW(?,2) + POW(?,2)) AS hypotenuse';
SET @a = 3;
SET @b = 4;
EXECUTE stmt1 USING @a, @b;
```
```
SET @col = "c1";
SELECT @col FROM t;
```

## PostgreSQL
When creating the prepared statement, refer to parameters by position, using $1, $2, etc. 
[ref](https://www.postgresql.org/docs/9.3/static/sql-prepare.html)
Example:
```
PREPARE fooplan (int, text, bool, numeric) AS
    INSERT INTO foo VALUES($1, $2, $3, $4);
EXECUTE fooplan(1, 'Hunter Valley', 't', 200.00);
```

## Oracle
You can use placeholders for input variables in any DELETE, INSERT, SELECT, or UPDATE statement, or PL/SQL block, in any position in the statement where you can use an expression or a literal value.
[ref](https://docs.oracle.com/cd/B10501_01/appdev.920/a96584/oci05bnd.htm)

For example, given the INSERT statement
```
INSERT INTO emp VALUES
    (:empno, :ename, :job, :sal, :deptno)
```
and the following variable declarations
```
text     *ename, *job;
sword    empno, sal, deptno;
```

## MS Server

[ref](https://docs.microsoft.com/en-us/sql/odbc/reference/develop-app/binding-parameters-by-name-named-parameters)
```
CREATE PROCEDURE test @title_id int = 1, @quote char(30) AS <blah>
```
In this procedure, the first parameter, @title_id, has a default value of 1. An application can use the following code to invoke this procedure such that it specifies only one dynamic parameter. This parameter is a named parameter with the name "@quote".
```
// Prepare the procedure invocation statement.  
SQLPrepare(hstmt, "{call test(?)}", SQL_NTS);  

// Populate record 1 of ipd.  
SQLBindParameter(hstmt, 1, SQL_PARAM_INPUT, SQL_C_CHAR, SQL_CHAR,  
                  30, 0, szQuote, 0, &cbValue);  

// Get ipd handle and set the SQL_DESC_NAMED and SQL_DESC_UNNAMED fields  
// for record #1.  
SQLGetStmtAttr(hstmt, SQL_ATTR_IMP_PARAM_DESC, &hIpd, 0, 0);  
SQLSetDescField(hIpd, 1, SQL_DESC_NAME, "@quote", SQL_NTS);  

// Assuming that szQuote has been appropriately initialized,  
// execute.  
SQLExecute(hstmt);  
```

**Comment by Gerold103** [comment]
As I can see, ?N must be removed, and $V must be converted into $N. Other things must be kept.
? - used in MySQL, :V - used in Oracle, @v - used in MySQL, MS Server.
