### ISSUE TITLE
sql: update table name in stat table after renaming

### ISSUE THREAD

**Issue by Korablev77** [tarantool/tarantool#2962]
`ANALYZE` gathers statistics in tables `_sql_stat1` and `_sql_stat4`. It is held in format: `<table_name, index_name, statistics>`. After `ALTER TABLE RENAME TO`, table name in stat tables isn't changed, and will be updated only after another run of `ANALYZE`. It is not critical, but may affect performance issues, since query planner can't use statistics for that table. So the proposal is to update table name in _sql_stat1 and _sql_stat4 tables, if ones contain it.

**Comment by kostja** [comment]
Why do you refer to table in 'stat' by name and not by id? Please use id instead.

**Comment by Korablev77** [comment]
It should be closed when #3242 hits the trunk.

**Comment by igormunkin** [comment]
Ticket looks irrelevant since there are no `_sql_stat1` and `_sql_stat4` spaces since 2.2.0-108-gec93b4a5 (ec93b4a). Closing with wontifx reason.
