### ISSUE TITLE
sql: insert or abort is not working

### ISSUE THREAD

**Issue by Khatskevich** [tarantool/tarantool#2964]
1. Possibly not only abort does not work
2. Possibly not only insert does not work

This statement produces wrong results

Statement:
```
yaml = require "yaml"

box.sql.execute([[ create table t1(a primary key) ]])
box.sql.execute([[ begin ]])
box.sql.execute([[ insert into t1 values(1) ]])
r = box.sql.execute([[ select * from t1 ]])
print(yaml.encode(r))
ok, msg = pcall( function () box.sql.execute([[ insert or abort into t1 values(2),(3),(1);]]) end)
print(msg)
r = box.sql.execute([[ select * from t1 ]])
print(yaml.encode(r))
box.sql.execute([[ rollback ]])
r = box.sql.execute([[ select * from t1 ]])
print(yaml.encode(r))
```
Result:
```
t=3.000000e-06 |  create table t1(a primary key) 
t=3.000000e-06 |  begin 
t=1.000000e-06 |  insert into t1 values(1) 
t=1.000000e-06 |  select * from t1 
---
- [1]
...

t=2.000000e-06 |  insert or abort into t1 values(2),(3),(1);
UNIQUE constraint failed: T1.A
t=1.000000e-06 |  select * from t1 
---
- [1]
- [2]  --- SHOULD NOT BE THERE
- [3]  --- SHOULD NOT BE THERE
...

t=1.000000e-06 |  rollback 
t=1.000000e-06 |  select * from t1 
--- []
```

result rows with `SHOULD NOT BE THERE` are excess.

Related to #2931

**Comment by Khatskevich** [comment]
Thesis:

Abort rollbacks the whole last statement, even if it fires in some statement in the trigger. Here is how it works in sqlite3:

```
sqlite>  create table t1(a primary key);
sqlite> create table t2(a primary key);
sqlite>  create trigger trig1 after insert on t1 begin insert or abort into t2 values(new.a); end;
sqlite> insert into t1 values(1);
sqlite> insert into t1 values(2);
sqlite> select * from t1;
1
2
sqlite> select * from t2;
1
2
sqlite> insert into t2 vAlues(3);
sqlite> insert into t1 values(3);
Error: UNIQUE constraint failed: t2.a
sqlite> select * from t2;
1
2
3
sqlite> select * from t1;
1
2
sqlite> 
```

**Comment by Khatskevich** [comment]
## Implementation overview:

### Where to store details on SQL transaction
1. Details on transaction should not be stored in VDBE, because single transaction may interact with many VDBEs
2. Decision: Put structure `sql_txn` to Tarantool txn as an attribute.
    * How to name the attribute?
    * What should the type of the attribute be? (void * or directly sql_txn?)

### How to store named savepoints?
1. SQLite's savepoints contain extra info in addition to Tarantool's ones, so it should be an additional structure with a pointer to box_txn_savepoint_t.
2. How to organize them so that it is still fast (in the case of name=Null) and searchable by name.
    * global hash key(txn_id, name)
    * local for txn hash on region key(name)
    * local list on region

**Comment by Gerold103** [comment]
My proposal:
```C
// txn.h
struct txn {
+     void *sql_txn;
};

txn_begin() {
+     txn->sql_txn = NULL;
}

// sql files
+ struct sql_savepoint {
+     struct txn_savepoint *savepoint;
+     char *name;
+};

+ struct sql_txn {
+     struct mhash sql_savepoints;
+     struct trigger on_commit;
+     struct trigger on_rollback;
};
```
- Add `void *sql_txn` to `struct txn`. Pointer to void must be used instead of explicit `struct sql_txn` because txn.h must not depend on any languages. And because `struct txn` can exists without sql;
- In sql files define `struct sql_savepoint` which contains `struct txn_savepoint *` as member and `char *name`. Store named hash of savepoints in `sql_txn` - it allows to do not store names out of sql;
- `sql_txn` must contain on_commit and on_rollback triggers, becase a transaction can be started from sql, but commited from lua. In such a case `sql_txn` must be correctly destroyed. (On a first phase of implementation `sql_txn` consists of only savepoints on region, so on_commit/on_rollback can be added later and commit from lua can be ignored by sql).

**Comment by kyukhin** [comment]
Done @ c3d5944dd3a2e21e293912d6e4e052065da1982a
