### ISSUE TITLE
Cannot create an index with same name as table

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#2984]
I have Ubuntu 14.04. I have Tarantool 1.8, pulled from source today.
I execute these requests:
CREATE TABLE A (s1 int primary key, s2 int);
CREATE INDEX A ON A (s2);
The result is an error with the message "there is already a table named A".

**Comment by pgulutzan** [comment]
Oops, I forget this is already documented behaviour so it's not a bug. Forget it.

**Comment by alyapunov** [comment]
* Peter Gulutzan <notifications@github.com> [17/12/06 20:17]:
> I have Ubuntu 14.04. I have Tarantool 1.8, pulled from source today.
> I execute these requests:
> CREATE TABLE A (s1 int primary key, s2 int);
> CREATE INDEX A ON A (s2);
> The result is an error with the message "there is already a table named A".

Looks like it should be a bug.


-- 
Konstantin Osipov, Moscow, Russia, +7 903 626 22 32
http://tarantool.org - www.twitter.com/kostja_osipov
