### ISSUE TITLE
Application error inside docker container 

### ISSUE THREAD

**Issue by skuzmitskiy** [tarantool/tarantool#2986]
Hello!
Application working inside docker container based on Alpine Linux with Tarantool 1.7, application crashes with error - "Segmentation fault", in tarantool log i see like this:
[app.log](https://github.com/tarantool/tarantool/files/1538170/app.log)
                                                                     
Segmentation fault                                                                                                                           
Current time: 1512622215                                                                                                                                
Please file a bug at http://github.com/tarantool/tarantool/issues                                                                                     
Attempting backtrace... Note: since the server has already crashed,                                                                                     
this may fail as well                                                                                                   
#0  0x7f79d1f4d579 in ?                                                                                                                                 
#1  0x7f79d1cbce07 in ?                                                                                                                               
#2  0x7f79cf164d3b in ?                                                                                                                      
#3  0x7f79cef5723a in ?                                                                                                                                 
2017-12-07 06:20:46.885 [1723] main/101/tarantoolctl C> version 1.7.4-0-g927bd9c24

/opt/tarantool # tarantool --version
Tarantool 1.7.4-0-g927bd9c24
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_BACKTRACE=ON
Compiler: /usr/bin/cc /usr/bin/c++
C_FLAGS: -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -fno-gnu89-inline
CXX_FLAGS: -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof

Docker image:
tarantool/tarantool:1.7.4

Docker version:
Docker version 17.05.0-ce, build 89658be

Could you please say, why it does?
Thanks!

**Comment by bigbes** [comment]
Try to use latest version of docker container and tell if your problem is gone

**Comment by kostja** [comment]
Please provide a more detailed test case, using a fresh version of the server (1.7.6) and then reopen this bug. Thank you!
