### ISSUE TITLE
sql: Delete op_transaction and related vdbe attributes

### ISSUE THREAD

**Issue by Khatskevich** [tarantool/tarantool#2992]
Since we disallow multistatement Sql queries, created op_ttransaction and deleted Btree, we can and should delete legacy code and attributes of vdbe and sqlite3.

**Comment by Korablev77** [comment]
I guess, this ticket is related to #3119: "Remove opcode OP_Transaction: it was superseded by Tarantool's specific OP_TTransaction"

@kyukhin should we close this as a duplicate?

**Comment by Korablev77** [comment]
Already done: https://github.com/tarantool/tarantool/commit/b080a7f09c6c679904ced120d6d8a4f39c16efdd
