### ISSUE TITLE
BEFORE trigger

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#2993]
Proposal: add space:before_replace(old, new) => result trigger in additional to space:on_replace().
The new trigger should use returned value as resulting tuple:

```
function before_replace(old, new)
   if old.yyy == new.yyy then
     return nil -- ignore this statement
  elseif old.xxx >= new.xxx then
     box.space:_conflict:insert(old)
    return old -- apply old statement
  else
    return new -- apply new statement
  end 
end
```
The idea of this trigger is that it **rewrites** the NEW value of the operation, and returns the rewritten value. If it chooses to return the OLD value for the NEW value, the operation is effectively skipped. If it does not perform a rewrite, i.e. returns the original NEW value, the operation is applied as is (but in this case you are better off using on_replace trigger, because it induces lower overhead). If it returns NULL, then it is assumed that OLD is replaced with NULL, and the operation is turned into a DELETE. If it returns nothing (return without arguments), then it's assumed that the original NEW value is left intact, and the operation also applied as is.

<table>
<tr>
<th>Request</th>
<th>OLD</th>
<th>NEW</th>
<th>return</th>
<th>return NULL</th>
<th>return OLD</th>
<th>return NEW</th>
<th>return TUPLE</th>
</tr>
<tr>
<td>REPLACE</td>
<td>old tuple</td>
<td>new tuple</td>
<td>replace NEW</td>
<td>delete OLD</td>
<td>skip</td>
<td>replace NEW</td>
<td>replace TUPLE</td>
</tr>
<tr>
<td>INSERT</td>
<td>NULL</td>
<td>new tuple</td>
<td>insert NEW</td>
<td>skip</td>
<td>skip</td>
<td>insert NEW</td>
<td>insert TUPLE*</td>
</tr>
<tr>
<td>UPDATE**</td>
<td>old tuple</td>
<td>new tuple</td>
<td>replace NEW</td>
<td>delete OLD</td>
<td>skip</td>
<td>replace NEW</td>
<td>replace TUPLE</td>
</tr>
<tr>
<td>DELETE</td>
<td>old tuple</td>
<td>NULL</td>
<td>delete OLD</td>
<td>delete OLD</td>
<td>skip</td>
<td>delete OLD</td>
<td>replace TUPLE</td>
</tr>
</table>

Notes:
`*` the trigger is not allowed to change the primary key, so INSERT continues to stay INSERT 
`**` in case of UPSERT, we apply upsert before invoking the trigger, so it is effectively treated as UPDATE.

**Comment by rtsisyk** [comment]
Needed as a workaround for conflict resolution in M-M replication.

**Comment by rtsisyk** [comment]
Approved for 1.7.7 by @kostja  2017-12-11.

**Comment by locker** [comment]
I have a few questions regarding the new trigger implementation:
- Is it true that an attempt to modify the value of the primary key from BEFORE trigger must be prohibited? For example, let the primary key index field 1, then if we replace {1, 1} with {1, 2}, the trigger callback can return {1, 3}, but an attempt to return {2, 2} should fail.
- The trigger is supposed to be called not only on REPLACE or UPDATE but also on INSERT and DELETE, in which case it is be passed nil for the old/new tuple, right?
- If UPDATE is called for a non-existent key, it is silently ignored and BEFORE trigger is not executed. Is that correct?
- Obviously, we can discard a REPLACE by returning the old tuple from the trigger. Can we discard an INSERT by returning nil? Can we discard DELETE by returning the old tuple? Can we turn a REPLACE into DELETE by returning nil or vice-versa?
- AFAIU we are going to use this trigger for conflict resolution during asynchronous replication as follows. The user is supposed to store a timestamp in each tuple and install BEFORE trigger on each space. The trigger callback should return either the old tuple or the new tuple depending on which one has a newer timestamp. This scheme is going to work only provided there's no DELETE statements. Is my understanding correct?

**Comment by kostja** [comment]
1) Don't allow to modify the value of the primary key, correct.
2) Right
3) Yes
4) The trigger takes a pair of tuples, old, new. And returns the new value of "new". If the new value of "new" is nil, then it's a delete when old is non-nil or a no-op if old is nil. Otherwise it's a replace (if old was non-nil) or an insert (if old was nil). In other words, the trigger can turn one statement into another.
5) Let's move this discussion out, it's about the application of the feature, not the feature itself.
6) I don't know how to solve this and this is a showstopper.

**Comment by rtsisyk** [comment]
1. I agree, please don't allow to modify the value of the primary key, correct.
2. Please make a table with possible result for each trigger type (see [CREATE TRIGGER](https://www.postgresql.org/docs/10/static/sql-createtrigger.html) for example) and we will discussed it.
3. Yes
4. See 2
5. Offtopic
6. It is a showstopper, please try to find a solution for this problem.

**Comment by rtsisyk** [comment]
v1:

<table>
<tr>
<th>Request</th>
<th>OLD</th>
<th>NEW</th>
<th>return NULL</th>
<th>return NOT NULL</th>
</tr>
<tr>
<td>REPLACE/INSERT</td>
<td>old tuple</td>
<td>new tuple</td>
<td>delete(OLD)</td>
<td>replace(result)</td>
</tr>
<tr>
<td>UPDATE/UPSERT</td>
<td>old tuple</td>
<td>new tuple</td>
<td>delete(OLD)</td>
<td>replace(result)</td>
</tr>
<tr>
<td>DELETE</td>
<td>old tuple</td>
<td>NULL</td>
<td>delete(OLD)</td>
<td>replace(result)</td>
</tr>
</table>

v2 (PostgresSQL-like)

<table>
<tr>
<th>Request</th>
<th>OLD</th>
<th>NEW</th>
<th>return NULL</th>
<th>return NOT NULL</th>
</tr>
<tr>
<td>REPLACE/INSERT</td>
<td>old tuple</td>
<td>new tuple</td>
<td>skip operation</td>
<td>replace(result)</td>
</tr>
<tr>
<td>UPDATE/UPSERT</td>
<td>old tuple</td>
<td>new tuple</td>
<td>skip operation</td>
<td>replace(result)</td>
</tr>
<tr>
<td>DELETE</td>
<td>old tuple</td>
<td>NULL</td>
<td>skip operation</td>
<td>delete(OLD), <br/>result must be OLD</td>
</tr>
</table>

From [PostgreSQL documentation](https://www.postgresql.org/docs/current/static/plpgsql-trigger.html):

> Row-level triggers fired BEFORE can return null to signal the trigger manager to skip the rest of the operation for this row (i.e., subsequent triggers are not fired, and the INSERT/UPDATE/DELETE does not occur for this row). If a nonnull value is returned then the operation proceeds with that row value. Returning a row value different from the original value of NEW alters the row that will be inserted or updated. Thus, if the trigger function wants the triggering action to succeed normally without altering the row value, NEW (or a value equal thereto) has to be returned. To alter the row to be stored, it is possible to replace single values directly in NEW and return the modified NEW, or to build a complete new record/row to return. In the case of a before-trigger on DELETE, the returned value has no direct effect, but it has to be nonnull to allow the trigger action to proceed. Note that NEW is null in DELETE triggers, so returning that is usually not sensible. The usual idiom in DELETE triggers is to return OLD.

**Comment by locker** [comment]
Regarding issue no. 6 (how to install the trigger before subscription), right now I see two possible ways to resolve this:
1. A new trigger called upon bootstrap completion. The trigger callback is passed to `box.cfg()` along with other server options. It is invoked right after the server configuration has been complete, but before the `is_box_configured` flag is set (see `box_cfg_xc()`) or subscription starts so that when it is being invoked the server will refuse any requests with `ER_LOADING`.
2. A new Lua function `box.bootstrap()`. If invoked, the function executes the bootstrap sequence (either remote or local) or local recovery in case the server has already been bootstrapped. The server will not start subscription, neither will it accept any user requests, before `box.cfg()` is called.

**Comment by kostja** [comment]
In scope of this fix, please ensure the user story described in https://github.com/tarantool/tarantool/issues/2897 works
