### ISSUE TITLE
Add vclock for safer hot standby switch

### ISSUE THREAD

**Issue by lenkis** [tarantool/tarantool#3002]
This is general practice to start a standby instance if the primary instance needs to be restarted *with minimal downtime*. For example, if we need to change non-dynamic params (like `memtx_memory`) on the primary instance, or if the primary instance throws ER_MEMORY_ISSUE due to memory fragmentation.

In this case, we start a standby instance on the same host and need to know when it catches up with the primary instance -- we cannot stop the primary instance earlier than that. We need to know `vclock`, but presently we can't read it. Please make it possible.

**Comment by kostja** [comment]
We don't need to know vclock any more, box.ctl.wait_rw() will handle this, no?

**Comment by GeorgyKirichenko** [comment]
The main case is an read-only master and hot-standby waiting for exchange. We don't know something about hot standby lag and can't make any decision about time to exchange with minimal downtime.
For example - maser can't do any write but still performing reads. We want to switch master and hot standby but first we should wait until hot standby has all recent datas.

**Comment by locker** [comment]
Fixed by 85299d97db4a8253fbf67bceb971f28cadae5e91
