### ISSUE TITLE
Segmentation fault with null argument to a msgpack function

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#3005]
I have Ubuntu 14.04. I have Tarantool 1.7 pulled from source today.
I execute these requests:
box.cfg{}
buffer = require('buffer')
ibuf = buffer.ibuf()
msgpack = require('msgpack')
msgpack.ibuf_decode(ibuf.rpos)
Result = segmentation fault.

I know, this function will be deprecated.
I know, I should not pass ibuf.rpos when it is null.
But I'm wondering whether an error message is possible.

**Comment by rtsisyk** [comment]
1.7.6-136-gd1c537540
