### ISSUE TITLE
Is_nullable = false does not matter for scalar type

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#3009]
```
box.cfg{}
s = box.schema.create_space('test')
pk = s:create_index('pk')
sk = s:create_index('sk', {parts = {{2, 'scalar', is_nullable = false}}})
s:replace{4, box.NULL}
```
The last replace must not work, but it does. It is because of https://github.com/tarantool/tarantool/commit/a2f574e3ca224aeaef8483222e388d018f5c2e17

MP_CLASS_NIL must be NULL in mp_class_comparators.
mp_compare_nil must be removed. To maintain NULLs only is_nullable option can be used.

**Comment by TheAviat0r** [comment]
Now in SQL NOT NULL constraint is checked by bytecode. If we remove it and rely on Tarantool, it won't work. Example:

```
tarantool> create table t1(a int primary key, b NOT NULL);
---
...

tarantool> insert into t1 values (1, 1);
---
...

tarantool> insert into t1 values (2, NULL);
---
...

tarantool> SELECT * FROM t1;
---
- - [1, 1]
  - [2, null]
```
