### ISSUE TITLE
No error if log_format=json and logging to syslog

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#3014]
box.cfg{} raises no error on wrong configuration. We can't log in json format while 

```
kostja@atlas /opt/local/work/tarantool/src
 % ./tarantool 
Tarantool 1.7.6-116-gd54d4de
type 'help' for interactive help
tarantool> box.cfg{log_format="json", log = 'syslog:identity=tarantool'}
started logging into a syslog, SIGHUP log rotation disabled
<3>Dec 22 17:45:08 tarantool[1607]: main/101/interactive C> Tarantool 1.7.6-116-gd54d4de
<3>Dec 22 17:45:08 tarantool[1607]: main/101/interactive C> log level 5
<7>Dec 22 17:45:08 tarantool[1607]: main/101/interactive I> mapping 268435456 bytes for memtx tuple arena...
<7>Dec 22 17:45:08 tarantool[1607]: main/101/interactive I> mapping 134217728 bytes for vinyl tuple arena...
<7>Dec 22 17:45:08 tarantool[1607]: main/101/interactive I> initializing an empty data directory
<7>Dec 22 17:45:08 tarantool[1607]: snapshot/101/main I> saving snapshot `./00000000000000000000.snap.inprogress'
<7>Dec 22 17:45:08 tarantool[1607]: snapshot/101/main I> done
<7>Dec 22 17:45:08 tarantool[1607]: main/101/interactive I> ready to accept requests
<7>Dec 22 17:45:08 tarantool[1607]: main/104/checkpoint_daemon I> started
<7>Dec 22 17:45:08 tarantool[1607]: main/104/checkpoint_daemon I> scheduled the next snapshot at Fri Dec 22 19:38:09 2017
<7>Dec 22 17:45:08 tarantool[1607]: main/101/interactive I> set 'log_format' configuration option to "json"
```

As you can see, it also produces no error about being unable to log to syslog.

**Comment by IlyaMarkovMipt** [comment]
We have to validate combinations of parameters' values in `box.cfg`.
E.g. it's impossible to have `log="syslog:..."` and `log_format="json"` (this issue)
or it's useless to have `log = "file:..."` and `log_nonblock = true`(#3072).

There should be the way to configure that the certain combinations are prohibited.

I see following ways of implementation:

1. Add to `box_check_config` function checking parameters' combination consistency.
Disadvantage: It is non-configurable. Only adding additional `if`s for each combination

2. Add table of parameters of prohibited combinations of config
in lua code. Raise an error in case of appearing one the mentioned
pair in `box.cfg`.
Disadvantage: Some of `cfg` parameters (e.g. `log`) are parsed in C code, so checking
their values in Lua requires either rewriting this parsing in Lua or propagating
parsing functions to lua.

**Comment by kostja** [comment]
Let's begin with a patch for Lua library cfg.lua, and see how it goes.
