### ISSUE TITLE
Allow to iterate through different orders

### ISSUE THREAD

**Issue by Korablev77** [tarantool/tarantool#3016]
In order to support basic SQL feature -- to make sorting in different orders 
(ex. `SELECT * FROM tab ORDER BY col1 DESC, col2, col3 DESC;`) it is required to iterate through key columns in different orders.

**Comment by kyukhin** [comment]
We need an API which will allow us to index fields in the ephemeral tables in different orders.

**Comment by kyukhin** [comment]
Things are even worse: we do not have native DESC indexes.
However we can mimic them.
