### ISSUE TITLE
replication lost last records in case of power failure

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#3027]
1. Setup master <-> master replication for two replicas
2. Insert some records to replica1
3. Power off replica1 to create an empty xlog file (see #3026 for a test case)
4. Remove the last empty xlog on replica1
5. Start replica1
6. Insert a new record on replica 1
7. Insert record won't be replicated to replica 2, because replica 2 already applied another record for { replica1, lsn }. 

Expected behaviour: replica 1 downloads its own lost records from replica 2

**Comment by kbelyavs** [comment]
Accidentally created a similar ticket [#3210](http://github.com/tarantool/tarantool/issues/3210).
Close, as implemented.
