### ISSUE TITLE
Sequence steps even if insertion failed 

### ISSUE THREAD

**Issue by taosx** [tarantool/tarantool#3030]
When a sequence it's attached to an index and you insert in the space of that index, the sequence steps, even if you have an error on that insert and it doesn't happen.

>  <details>
>  <summary>~/t/p/test &lambda; tarantool -v</summary>
>  
> > Tarantool 1.7.6-13-g38418dbaf
> > Target: Linux-x86_64-Release
> > Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_BACKTRACE=ON
> > Compiler: /usr/bin/cc /usr/bin/c++
> > C_FLAGS:-march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -fno-gnu89-inline
> > CXX_FLAGS:-march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof
> </details>

Reproducing case Inside tarantool cli:
```lua
SEQ_NAME = "testspace_sequence"

sp = box.schema.space.create("testspace", {if_not_exists = true})

box.schema.sequence.create(SEQ_NAME, {start = 1})

sp:create_index("primary", { parts = { 1, "unsigned" }, sequence = SEQ_NAME })

sp:create_index("secondary", {parts = { 2, "string" }, unique = true  })

sp:insert({nil, "michael"})
-- [1, 'michael']

sp:insert({nil, "michael"}) -- next happened here but didn't revert when insert failed
-- error: Duplicate key exists in unique index 'secondary' in space 'testspace'

sp:insert({nil, "elena"})
-- [3, 'elena']
```
<details>
<summary>More details about each command:</summary>
<br>

* box.schema.space.create("testspace", {if_not_exists = true})
```lua
- index: []
  on_replace: 'function: 0x41e2ce40'
  temporary: false
  id: 528
  engine: memtx
  enabled: false
  name: testspace
  field_count: 0
- created
```

* box.schema.sequence.create(SEQ_NAME, {start = 1})
```lua
- step: 1
  id: 9
  min: 1
  cache: 0
  uid: 0
  max: 9223372036854775807
  cycle: false
  name: testspace_sequence
  start: 1
```

* sp:create_index("primary", { parts = { 1, "unsigned" }, sequence = SEQ_NAME })
```lua
- unique: true
  parts:
  - type: unsigned
    is_nullable: false
    fieldno: 1
  sequence_id: 9
  id: 0
  space_id: 525
  name: primary
  type: TREE
```

* sp:create_index("secondary", {parts = { 2, "string" }, unique = true  })
```lua
- unique: true
  parts:
  - type: string
    is_nullable: false
    fieldno: 2
  id: 1
  space_id: 525
  name: secondary
  type: TREE
```

</details>

<br>
Is this desired behavior or a bug?

For someone who need the sequence to represent the number of items in an index they could use: sequence:set(box.space.${namespace}.index.${nameindex}:len())

EDIT:
After some more testing with a my project, it could as well be desired behavior, mysql does this for auto-incrementing and it's pretty easy to make it consistent with errors without affecting performance:

```lua
ok, data = pcall(model.space[space_name].insert, model.space[space_name], data)
if not ok then
    box.sequence[sequence_name]:set(box.space[space_name].index[index_name]:len())
    log.error("Couldn't insert new this.\n[Error] " .. tostring(data))
end
```
Not beautiful but it works.

**Comment by kostja** [comment]
* Tasos Soukoulis <notifications@github.com> [18/01/05 23:10]:
> Is this desired behavior or a bug?

This is not a bug.


-- 
Konstantin Osipov, Moscow, Russia, +7 903 626 22 32
http://tarantool.org - www.twitter.com/kostja_osipov

**Comment by taosx** [comment]
@kostja I understand, thank you (I found some use cases for this). This can be closed.
