### ISSUE TITLE
sql: make foreign key mismatch error more informative

### ISSUE THREAD

**Issue by Korablev77** [tarantool/tarantool#3033]
Originally, SQLite allows to create foreign keys only on primary or unique indexes. Moreover, they should feature default(binary) collation sequence. Otherwise, an error will be raised. However, it is unlikely to be informative enough: 
```
create table child(id primary key, a references parent(b));
create table parent(a primary key, b);
insert into parent values(1, 2);
insert into child values(1,2);
"foreign key mismatch - CHILD referencing PARENT"
```
So, suggestion is to put there message containing info about the fact that foreign keys can be created only on PK/unique indexes with the default collation sequence.

**Comment by Gerold103** [comment]
@SudoBobo please, use 'Closes #nnnn' instead of 'Closes: #nnnn'. The second approach does not close tickets.

**Comment by Korablev77** [comment]
Closed since we decided to allow creating FK with other collations. The only restriction remained - they must match.
