### ISSUE TITLE
New replication configuration API

### ISSUE THREAD

**Issue by locker** [tarantool/tarantool#3034]
It looks like instead of overwhelming `box.cfg` with new options, such as `replication_quorum`, we could add new functions for replication configuration with clear semantics and let users decide what to do. The functions could be:
- `box.subscribe(addr, timeout)` Subscribe to events from a master at `addr`. Try to connect for `timeout` seconds. On success, return the master id that could be used to track the subscription state via `box.info.replication`. To cancel the function before timeout, cancel the current fiber.
- `box.unsubscribe(id | uuid)` Remove the master with the given id (or uuid) from the replication configuration.

Assume the cluster has already been bootstrapped. Then a replica's workflow could look like this:
1. Call `box.cfg` without specifying `replication` for local recovery. Replication will be configured later. To prevent the instance from processing user requests before replication configuration is complete, do not set `listen` (alternatively, one could set `read_only` flag or write some code in Lua to reject client requests in case the instance hasn't been fully initialized).
2. Create a fiber per each configured master. Call `box.subscribe` in each fiber to connect to a master. In the main fiber (or a special monitoring fiber), wait until the instance is connected to a sufficient number of masters, then complete configuration either by setting `listen` or clearing `read_only` flag depending on the decision made on step 1. One could also wait until the replication lag (as reported by `box.info.replication`) to be small enough before proceeding to handling user requests (see #999).
3. After configuration has been completed, the fibers created on step 2 could be left for monitoring subscription. For instance, they could be used for removing masters by calling `box.unsubscribe` that are found to be permanently down or they could switch the instance to the read-only mode if the replication lag gets too high.

It would definitely require writing more code in Lua, but at the same time it would be more flexible, as the users could decide for themselves what they want to do in various extreme cases. This would also spare us from adding a bunch of new configuration options for each use case and then maintaining them for good. To ease the initial setup, we could probably ship a script implementing the default behavior right in the Tarantool package.

See also #999 #2958

**Comment by Mons** [comment]
Current state of bootstrapping logic is strict and consistent.
Also it seems, that proposed changes not relevant to real production environments, because it is impossible to make an assumption like "Assume the cluster has already been bootstrapped" in real apps. When cluster is bootstrapped — everything is easy. The most complex problems are in the moment of bootstrap/initial join.
To finalise: new mechanisms, like swim, raft and some new upcoming features will eliminate complexity of replication configuration.
