### ISSUE TITLE
declaring global variable from a function fails

### ISSUE THREAD

**Issue by Khatskevich** [tarantool/tarantool#3047]
This small snippet does not work in Tarantool
```
tarantool> a = function () _G["my_variable"] = 1 end
tarantool> a()
- error: '[string "a = function () _G["my_variable"] = 1 end"]:1: assign to undeclared
    variable ''my_variable'''
```
While it works in lua 5.2 and 5.1 interpreters

**Comment by kyukhin** [comment]
luajit is lua-5.1 compatible.

**Comment by rosik** [comment]
Are you using strict mode?
* https://tarantool.org/en/doc/1.7/reference/reference_lua/strict.html
* https://github.com/tarantool/tarantool/blob/1.7-next/src/lua/strict.lua

> By default strict mode is off, unless tarantool was built with the -DCMAKE_BUILD_TYPE=Debug option

Under strict mode you still can set `_G.var` from main().
If you really _really_ need to work with globals you can use rawget, rawset.

**Comment by Khatskevich** [comment]
I do not really need it, but it can be useful in some situations.
I have tested it under lua5.1 -> the same as lua5.2 (supports this feature).

**Comment by Khatskevich** [comment]
The reason was simple: strict mode by default in tarantool builded in debug mode.
Thanks to @rosik
