### ISSUE TITLE
LuaJIT: make sure yields can happen in JIT code

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#3059]
Currently, yielding from JIT optimized code breaks the interpreter state. This is why we use Lua C API and not FFI for all database API binding from interpreter (insert/update/delete operations, transactoin management, etc). This means that database operations can not ever become part of a JIT trace, removing the whole benefit of JIT.

Please make it possible to yield from JIT code.

**Comment by igormunkin** [comment]
> Please make it possible to yield from JIT code.

Unfortunately, I doubt there is a way to resolve it in terms of current JIT design: the recording of Lua coroutines switch-over is forbidden in LuaJIT. However, I found [CoCo](http://coco.luajit.org/index.html) library mentioning the following:
> Coco is also integrated into LuaJIT 1.x to allow yielding for JIT compiled functions.

I have no idea about its implementation and stability, but it's worth to take a look whether there is anything valuable to solve the issue.

**Comment by filonenko-mikhail** [comment]
Just want to copy text from one internet place to our another internet place

```
Ani A wrote:
> Is CoCo (coroutine) library integrated in LuaJIT2.0.2 ?
> (the coco page says that it is integrated in LuaJIT1.x, but
> does not mention 2.x). If it is not integrated by default, is there
> a separate patch for LuaJIT2.x ?

CoCo is LuaJIT 1.x only. LuaJIT 2.x has a fully resumable VM, so
there's little need for CoCo anymore. You can yield() across
iterators, across metamethods, across pcall() etc.

The only thing that doesn't work is yielding when the coroutine
has a C function further down in the stack. Note that pcall() and
others are builtins and not C functions, so this restriction
doesn't apply for them.

--Mike
```

**Comment by igormunkin** [comment]
@filonenko-mikhail, thanks, but there is not a word regarding yielding in a JIT compiled code. I believe that as a result of this research at least we'll have a reason why this idea can't be implemented in LuaJIT.

**Comment by igormunkin** [comment]
Well, I guess it's enough done for this issue.

Here are the inputs for "will never be done with current design" reason:
* `fiber.yield` and other interfaces calling `fiber_yield` underneath are just plain functions called via Lua C / FFI engines. They do not signal to LuaJIT VM when the current running coroutine is switched to another one (there are two hacks for unwinding purposes, but it is considered as misuse: see more info in LuaJIT/LuaJIT#740). We've also added a safe point in scope of #1700 to check whether the trace is being recorded or executed at each fiber switch.
* The trace is considered as a continuous linear flow, but `fiber.yield` never guarantees to be scheduled to the same fiber (i.e. Lua coroutine), the trace is recorded and executed later. Violating this rule leads to the failures similar to #4491 and many others investigated and fixed until the aforementioned safe point was introduced.

Hence, I suggest to close this issue now. I doubt it should be ever reopened.
