### ISSUE TITLE
LuaJIT: overflow of FFI finalizers table unconditionally leads to panic.

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#3060]
When number of FFI objects in the interpreter grows beyond a certain limit, LuaJIT simply ends with panic. This is unacceptable for 24x7 apps. 
Test case:
https://github.com/tarantool/tarantool/blob/1.7/test/long_run-py/finalizers.test.py

**Comment by Totktonada** [comment]
See also #3751 and 022a3c5026fffcecd9bc85f5484d5b5c53ae887d.
