### ISSUE TITLE
LuaJIT: make strict mode the default

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#3061]
We need to patch LuaJIT with built-in strict mode. This has to be a built-in to avoid performance implications. It's a safety issue, and yes, it changes semantics of Lua, but this seems to be mandatory for stability of our production deployments.

**Comment by sharonovd** [comment]
This can be solved by using luacheck to control production code. 
I don't see the necessity.

Probably, doc recommendation (to use luacheck) would be enough.

**Comment by Mons** [comment]
Strictly disagree
