### ISSUE TITLE
http client: is not working with large output

### ISSUE THREAD

**Issue by zloidemon** [tarantool/tarantool#3065]
I used to old version tarantool 1.8 and http.client works fine but after upgrade to latest 1.7 or 1.8.3-79-ge2c080280 http get request response me

```
tarantool> x:get('https://127.0.0.1/test')
---
- error: 'curl: Failure when receiving data from the peer'
...

tarantool> x:get('https://127.0.0.1/test')
---
- error: 'curl: Failure when receiving data from the peer'
...

tarantool> x:get('https://127.0.0.1/test')
---
- error: 'curl: Failure when receiving data from the peer'
...

tarantool> x:get('https://127.0.0.1/test')
---
- error: 'curl: Failure when receiving data from the peer'
...

tarantool> x:get('https://127.0.0.1/test')
---
- reason: Ok
  status: 200
  body: '[...a lot data...]'
```

Tested 1.7.6, 1.7.5 but **only works on 1.7.4** (more precision 1.7.4-458-g05eef5f)

Explanation
---
Brief check shows following difference between system lib curl and the one from homebrew:
> curl-config --feature
SSL
IPv6
UnixSockets
libz
AsynchDNS
+GSS-API
+SPNEGO
+Kerberos
...
/usr/local/opt/curl/bin/curl-config --feature
SSL
IPv6
UnixSockets
libz
AsynchDNS

So both supports SSL and HTTPS in general, and the difference which lacks in homebrew's version
related to HTTP but not HTTPS.

So I need test case for reproduction/investigation if problem is not with HTTPS.

Proposal
---
It looks like old homebrew curl didn't support SSL by default. Suggest to add simple compile-time check to make sure that 'HTTPS' schema is supported.
Libcurl supports SSL since version 7.10 with CURL_VERSION_SSL flag, so suggest to check library version and with SSL flag set.

**Comment by Totktonada** [comment]
Please, add `verbose` parameter to the options ( https://tarantool.org/en/doc/1.7/reference/reference_lua/http.html ) and post output here.

**Comment by zloidemon** [comment]
Main issue is using hombrew installed libs instead system. By default curl complied without openssl, issue might solved by recompile curl:

```
brew upgrade --with-openssl curl
```

I thing more better use system curl and etc libraries more as possible than homebrew or optionally defined homebrew libraries to link.

**Comment by Totktonada** [comment]
As I know we use curl from homebrew due to #2772.

**Comment by kbelyavs** [comment]
Hi, need help with reproduction. Looks like old brew's curl version doesn't support https by default. But my version does, so suggest to add simple check and prints message with solution in case https is not supported.
