### ISSUE TITLE
force_recovery should not stop on corrupted xlog file and try to recover as much as possible

### ISSUE THREAD

**Issue by kbelyavs** [tarantool/tarantool#3076]
This bug derived from #3026
It was found that force_recovery stopped on corrupted xlog file (either header or data). But based on description in documentation it should try to restore as much state as possible.
The goal of the task is to offer a solution that will be corresponded to the expected behavior, that is, to try to recover as much as possible.
As for now proposed to:
 - Do not break recovery on empty xlog
 - Try to recover as much as possible
 - remove only empty xlog on recovery_finalize (#3026)

**Comment by locker** [comment]
Fixed by be558f206cb92c3888ce30901c1ca46ca4d21215
