### ISSUE TITLE
Changes in Tarantool release policy

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#3078]
## Definitions

In this document, I will use terms according to their definitions provided at http://semver.org:

A major release may contain incompatible changes. A minor release does not contain incompatible changes, but may contain features. A patch release must contain backward-compatible bug fixes only. 

## Preamble

Tarantool today publishes a major release every 1 or 2 years. We use both first and second version digits to identify a major release. E.g. both 1.7 and 1.6 are major releases. A major release may contain incompatible changes. Each major release goes through development-maturity life cycle, as follows: 
- We release a few alpha versions, e.g. 1.7.1, 1.7.2. Alpha versions may contain incompatible changes, crashes and other bugs. An alpha version is released once in every few months.
- Once major changes necessary to introduce new flagship features are ready, we release a few beta versions, e.g. 1.7.3, 1.7.4. Beta versions may contain crashes, but do not have incompatible changes, so can be used to develop new applications.
- Once all crashes are ironed out, minor features are complete and we've done some rigorous internal testing, we release a gamma version. A gamma is a special kind of stable release. We believe it's stable, since we have fixed all the bugs in it we could find, but it has not been **proven** to be stable by the community, hence we don't call it stable. 
- Finally, after we see our gamma versions run successfully in production, usually in a few more months, during which we fix all incoming bugs and add some minor features, we declare a release stable. A stable release is supported for 3 years, during which we continue fixing bugs in it.

We do not have "patch" level releases, in definition of semver, as such. We simply publish all our nightly builds, for all our releases, beginning with their alpha state.

## The problem

- Our maturity cycle may take a long time. Some major features, such as vinyl, take 2-3 years to mature. While this happens, we have no vehicle to deliver minor features to the community on a regular fashion - e.g. every few months.
- This situation is self-aggravating. At the end of a maturity cycle, we tend to push more and more features into the release, since we know that the next vehicle may not depart in a year or two, thus destabilizing the release, and prolonging the stabilization period even more.
- Another manifestation of the same, we have no other vehicle to deliver minor features for paying customers but pushing them into a stable release, thus violating our commitment to community to keep a stable release stable.
- Community has no quick way to identify how stable and supported a release is just by looking at its version.

## The change

Like Ubuntu, we need to begin distinguishing two kinds of stable releases: LTS and a standard stable release. We should continue supporting LTS releases for 3, and, with paying customers, up to 5 years, while standard stable release will be only supported a few months after the next stable is out. We should adopt semantic versioning for our release numbers: only the first digit should stand for MAJOR release. I.e. we should not allow incompatible changes between 1.7 and 1.8. The second digit should stand for MINOR, and be used for introduction of backward-compatible features. PATCH level releases must contain only backward compatible bug fixes. We should reflect how stable a release is in MINOR digit: 0 meaning alpha, 1 meaning beta, anything between 1 and 10 meaning stable, and 10 meaning LTS. With these changes our release cycle will look as follows:

We will be adding commits simultaneously to three **major** releases, lets name them LTS, STABLE, and NEXT.
LTS is a stable release which does not receive new features, and only gets backward compatible fixes. Hence, following the rules of semver, LTS release never has its MAJOR or MINOR version increased, and only gets PATCH level releases. STABLE is our current stable release, which may receive new features. When the next STABLE version is published, MINOR version is incremented. Between MINOR releases, we may have intermediate PATCH level releases as well, which will contain only bug fixes. We will maintain PATCH level releases for two STABLE releases, the current and the previous one, to maintain support continuity. NEXT is our next major release, and it should follow the same maturity cycle as described in the preamble. While NEXT release is in alpha state, its MINOR is frozen at 0 and is only increased when the release reaches BETA status. Once the NEXT release becomes STABLE, we **switch** the vehicle for delivery of minor features, designating the previous stable release as LTS, and relasing it with MINOR set to 10. 

To sum up, once a quarter we should:
- release the next LTS release, e.g. 2.10.6, 2.10.7, 2.10.8
- release the next STABLE release, e.g. 3.6, 3.7 or 3.8
- optionally release an alpha or beta version of the NEXT release, e.g. 4.0.1 or 4.0.2 or 4.0.3

In all supported releases, we also must release a PATCH release as soon as we find and fix an outstanding CVE/vulnerability. We will also publish nightly builds, and will continue using the fourth slot in the version identifier to designate the nightly build number.

## Making the transition

According to the new policy, the current 1.7 is STABLE, and should have its MINOR increased to 1.8 with the next release of 1.7.7. We will not do that, instead, we will freeze 1.7 for new features with release of 1.10 and turn it into LTS.
According to the same policy, the current 1.8 is the NEXT major, since it has some big features we've been working for the past 3 years. We will need to transition it to STABLE ASAP, since otherwise we will have no vehicle for small features, thus it will be renumbered to 2.0. Synchronous replication and sharding will have to go to the new NEXT, i.e. Tarantool 3.0.

## Example version identifier

* 2.0.3 - third alpha of 2.0 release
* 2.1.3 - a beta of 2.0 release
* 2.2 - a stable version of 2.0 series, but perhaps not an LTS yet
* 2.10 - an LTS release

**Comment by lenkis** [comment]
Issue moved to doc repo.
