### ISSUE TITLE
Vinyl engine always inits even it will not be used

### ISSUE THREAD

**Issue by rtokarev** [tarantool/tarantool#3079]
It maps some virtual memory that will not be used if no one of vinyl space will be created. Maybe it worth having a config's variable that could turn it on/off or init it on demand, before the first vinyl space is created.

**Comment by locker** [comment]
To be honest, I don't see much point in it. AFAIK virtual memory is practically free. If one still feels uncomfortable about it, they can decrease the value of `box.cfg.vinyl_memory`. Apart from mapping some memory, initializing vinyl subsystem doesn't leave any user-visible traces. I suggest to close this issue as "Won't fix".

**Comment by kyukhin** [comment]
Just use vinyl_memory = 0
