### ISSUE TITLE
Extend ALTER to support adding a constraint to existing table

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#3097]
Oracle supports following syntax:
```
-- add a unique constraint to a column
ALTER TABLE SAMP.PROJECT 
ADD CONSTRAINT P_UC UNIQUE (PROJNAME);
```
It might be useful to:
1. be able to add constraint to existing table
2. make some (which?) of constraint types (optionally?) named

[1] - https://docs.oracle.com/javadb/10.8.3.0/ref/rrefsqlj13590.html

**Comment by Korablev77** [comment]
The only constraint currently can't be added using ALTER TABLE is CHECK constraint.
