### ISSUE TITLE
Improve SQL test suite toward static types

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#3102]
Right now, whole sql-tap test suite is Lua-projected variant of SQLite one.
SQLite uses so-called affinity attribute to deal w/ expression types.

Need to mutate the suite, so that it'll obey static typing tules:
1. each column of a table must have assigned type
2. each expression should contain non-conflicting types
3. if types cannot be implicitly converted to conform: need to
   use type conversion built-ins or update test semantics

**Comment by Totktonada** [comment]
The wording sounds like we want to have tests only with static types (or even phohibit non-typed tables at all). As I know we don’t want neither of that options. So, I think the plan should sounds like:

`1`. Assign types for tables in existing tests + your pount 2 and 3.
`4`. Create suites with non-typed tables and mixed typed/non-typed tables.

There is the interesting option to achieve 4th point: preprocess a well-typed suite with cutting down type information (entirely or partially) and run the generated suite as a separate one.

**Comment by Korablev77** [comment]
We've already introduced strict types and reworked almost all tests. The only issues remained are connected with mixing types (e.g. column was declared as DOUBLE and we insert there strings). Currently disabled tests: selectA.test.lua, types2.test.lua, e_expr.test.lua

They should be reconsidered and we should manually check that they can be resurrected.

**Comment by kyukhin** [comment]
This looks like done.
