### ISSUE TITLE
Misleading "authenticated" messages in the log when auto-bootstrapping a cluster with guest credentials

### ISSUE THREAD

**Issue by locker** [tarantool/tarantool#3113]
When I autobootstrap a new cluster without specifying credentials in the replication URI, I see the "authenticated" message printed to the log on all nodes every second until I grant the guest user the replication role on the cluster leader. This is misleading as no authentication actually occurs. This doesn't happen if I explicitly pass credentials in the URI.

**Comment by rtsisyk** [comment]
+1

**Comment by locker** [comment]
Fixed by 674c10581193dc7c5127e33cb995d0dc0ed58a68
