### ISSUE TITLE
Enable LTO/IPO optimizations 

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#3117]
There was [1] a pull request proposing to add LTO target to Tarantool.

This still looks very promising to have link-time optimizations.

For vanilla SQLite enabling LTO improves performance by 250%,
so this looks like worse doing.

Let's try to add new build type which will include most aggressive
optimizations: `-flto -Ofast`

[1] - https://github.com/tarantool/tarantool/pull/2561

**Comment by Totktonada** [comment]
In case of linker-related problems it worth to try to use gold instead of bfd: `-fuse-ld=gold`.

**Comment by Totktonada** [comment]
```
diff --git a/cmake/compiler.cmake b/cmake/compiler.cmake
index 05d33ab48..ce2458003 100644
--- a/cmake/compiler.cmake
+++ b/cmake/compiler.cmake
@@ -308,3 +308,5 @@ else()
     set(CMAKE_HOST_C_COMPILER ${CMAKE_C_COMPILER})
     set(CMAKE_HOST_CXX_COMPILER ${CMAKE_CXX_COMPILER})
 endif()
+
+SET(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -fuse-ld=gold")
```

**Comment by Khatskevich** [comment]
here is main perf research page
https://github.com/tarantool/tarantool/wiki/performance-research-(SQL)

Here you can find LTO research status

**Comment by Khatskevich** [comment]
https://github.com/tarantool/tarantool/wiki/performance-research new link
