### ISSUE TITLE
sql: SQLite backend removal follow-up: cleanups

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#3119]
- [x] Refactor `struct CursorPayload`, only two fields are used in box/sql.c: `key` and `nkey`. Maybe even remove whole struct
- [x] Refactor `struct Schema`: only 3 fields are actually used `fkey, `table` and `trigger`
- [x] Remove code under `OMIT_DEPRECATED` ifndef
- [x] Remove `struct Db`, the only field used in this struct is `Schema`
- [x] Remove code under `OMIT_AUTHORIZED` ifndef
- [x] Remove journal_mode, file `memjournal.c` and code under `OMIT_WAL` infdef
- [x] Remove opcode `OP_Transaction`: it was superseded by Tarantool's specific `OP_TTransaction `
- [x] Remove from types of 4-th argument in VDBE type `P4_TABLE`: no tables anymore
- [x] Remove code under `OMIT_AUTOINCREMENT` ifndef

**Comment by TheAviat0r** [comment]
Patch is in 2.0, so that ticket should be closed.
