### ISSUE TITLE
sql: merge BtCursor and ta_cursor structures

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#3120]
After Tarantool's ephemeral tables are used by SQL front-end and legacy backend is removed, to structures `BtCursor` and `ta_cursor` are ultimately same entity. Merge them into single structure.

**Comment by Korablev77** [comment]
Closed by:https://github.com/tarantool/tarantool/commit/a7b583842811e87919accbe28d4884434f16f23f
