### ISSUE TITLE
sql: refactor pgnoRoot field in cursor structure

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#3122]
Right now structure `BtCursor` contains field `pgnoRoot` which was originally stand for root page in btree. Right now it is used to encode space_id index_id.

Refactor this struct and code which uses it: need to make SQL understand what is space_id and index_id. `pgnoRoot` should be removed as dead code.

**Comment by Korablev77** [comment]
The suggestion is to hold `struct space *` and` struct index *` in cursors instead of ids. Moreover, we decided to pass pointer to space/index to OP_OpenWrite/OP_OpenRead opcodes instead of ids, in order to get rid of redundant id lookups.

**Comment by kyukhin** [comment]
It turns out, that it's time to split program logic for DDL and DML a bit.

Any DDL operation lead to schema change, so any reference to `space*` or
`index*` would become invalid.

Proposal is to distinguish DDL operations like this:
1. If operation is about to change schema ID (any update to _space, _index,
_truncate), then special handling is needed. Any operation of such a king
need to use space_id/index_id explicitly
2. New opcode to be introduced which will derive pointer to space/index
from its identifier
3. All DML operations should use references to space/index, not
identifiers

Schema might only be changed during DDL request.
Schema might not be changed during DML request.

However, there're mixed statements.
Consider example (opcodes are from vanilla SQLite, due to #XXX).
```
sqlite> create table t1 (id integer primary key);
sqlite> insert into t1 values (1), (2), (3);
sqlite> pragma vdbe_debug=1;
sqlite> create table t2 as select * from t1;
```

Last statement is compiled into:
```
VDBE Program Listing:
   0 Init             0   43    0               00 Start at 43
   1 ReadCookie       0    3    2               00
   2 If               3    5    0               00
   3 SetCookie        0    2    4               00
   4 SetCookie        0    5    1               00
   5 CreateBtree      0    2    1               00 r[2]=root iDb=0 flags=1
   6 OpenWrite        0    1    0 5             00 root=1 iDb=0
   7 NewRowid         0    1    0               00 r[1]=rowid
   8 Blob             6    3    0 ^F             00 r[3]=^F (len=6)
   9 Insert           0    3    1               08 intkey=r[1] data=r[3]
  10 Close            0    0    0               00
  11 Close            0    0    0               00
  12 OpenWrite        1    2    0               10 root=2 iDb=0
  13 InitCoroutine    4   21   14               00
  14 OpenRead         2    2    0 0             00 root=2 iDb=0; t1
  15 Explain          0    0    0 SCAN TABLE t1 00
  16 Rewind           2   20    0               00
  17 Rowid            2    7    0               00 r[7]=rowid
  18 Yield            4    0    0               00
  19 Next             2   17    0               01
  20 EndCoroutine     4    0    0               00
  21 Yield            4   26    0               00
  22 MakeRecord       7    1    5 D             00 r[5]=mkrec(r[7])
  23 NewRowid         1    6    0               00 r[6]=rowid
  24 Insert           1    5    6               00 intkey=r[6] data=r[5]
  25 Goto             0   21    0               00
  26 Close            1    0    0               00
  27 Null             0    8    9               00 r[8..9]=NULL
  28 OpenWrite        3    1    0 5             00 root=1 iDb=0; sqlite_master
  29 Explain          0    0    0 SEARCH TABLE sqlite_master USING INTEGER PRIMARY KEY (rowid=?) 00
  30 SeekRowid        3   32    1               00 intkey=r[1]; pk
  31 Rowid            3    9    0               00 r[9]=rowid
  32 IsNull           9   40    0               00 if r[9]==NULL goto 40
  33 String8          0   10    0 table         00 r[10]='table'
  34 String8          0   11    0 t2            00 r[11]='t2'
  35 String8          0   12    0 t2            00 r[12]='t2'
  36 Copy             2   13    0               00 r[13]=r[2]
  37 String8          0   14    0 CREATE TABLE t2(id INT) 00 r[14]='CREATE TABLE t2(id INT)'
  38 MakeRecord      10    5   15 BBBDB         00 r[15]=mkrec(r[10..14])
  39 Insert           3   15    9               00 intkey=r[9] data=r[15]
  40 SetCookie        0    1    4               00
  41 ParseSchema      0    0    0 tbl_name='t2' AND type!='trigger' 00
  42 Halt             0    0    0               00
  43 Transaction      0    1    3 0             01 usesStmtJournal=1
  44 Goto             0    1    0               00
```

So, inside single VM program both DDL (stmts 1-10) and 
DML (rest) requests are put together.

Proposal is to use identifiers in DDL, pointers in DML and
special opcode on the border, which will derive pointer from
identifier. Also separate opcode for insertion by identifier
is needed. It will be used for insertions into spaces which might
lead to schema ID change.

Here's proposed pseudocode (for same `create table as select`):
```
...
MakeRecord r1, ... ; Prepare tuple for _space insertion
InsertS <_space_id>, r1 ; Insert new tuple into _space space
...
MakeRecord r2, ... ; Prepare tuple for _index insertioon
InsertS <_index_id>, r2 ; Insert new tuple into _index space
...
SIDtoPtr <t1>, r3; t1 is a table which if donor for values to new table
SIDtoPtr <t2>, r4; t2 is newly created table. <t2> is on reg probably
...
OpenRead 1, r3 ; Open is performed by pointer
...
OpenWrite 2, r4; Open is performed by pointer
;; Loop over 1 and insert into 2
```

At the end of the day, new opcodes are to be introduced:
1. `InsertS` for insertions into tables which might change schema ID
2. `OpenRead/OpenWrite` should use pointer to space/index as argument
3. `SIDtoPtr` is new opcode which is a barrier between DDL and DML and
should convert space identifier to pointer.
4. No subsequent schema changes are allowed. This should be checked
(in debug mode) by assertions in `OpenRead/OpenWrite`

**Comment by kyukhin** [comment]
I've  extracted my comment into separate issue #3252
