### ISSUE TITLE
Assertion if before_replace and on_replace and delete

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#3127]
I have Ubuntu 17.04 and Tarantool 1.7.7 pulled from source today.
I execute these requests:
box.cfg{}
box.space.t:drop()
box.schema.space.create('t')
box.space.t:create_index('i')
function before_replace (old,new) print('before') box.space.t:delete{1} end
function on_replace (old,new) print('on') box.space.t:delete{1} end
box.space.t:on_replace(on_replace)
box.space.t:before_replace(before_replace)
box.space.t:insert{1}

The result looks like this:
before
on
before
before
before
tarantool: /home/pgulutzan/tarantool-1.7-next/src/box/space.c:470:
space_before_replace: Assertion `stmt->old_tuple == old_tuple' failed.
Aborted (core dumped)

We document that if you do exotic things with triggers, then
result may be "undefined". But I believe that an error
message, instead of an assertion, would be easier for users
to handle.

**Comment by locker** [comment]
Fixed by 6b49134d9f07cac3de6f394cce9e5f209273c739
