### ISSUE TITLE
Unexpected run_triggers effect

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#3128]
I have Ubuntu 17.04 and Tarantool 1.7.7 pulled from source today.
If I have two before_replace triggers,
and their functions both contain box.space.t:run_triggers(false),
they both are executed,
that is, run_triggers does not have immediate effect
for a before_replace trigger -- but does have immediate effect
for an on_replace trigger.

What I expect is: after run_triggers(false) is done by the
first function then no other triggers are activated;
OR after run_triggers(false) is done by the first function
then all other triggers are activated;
OR run_triggers(false) is illegal within a trigger function.
I don't get any of those alternatives.

Example:
These requests print 'before #2' and 'before #1', but do not  print 'on'
box.cfg{}
box.space.t:drop()
box.schema.space.create('t')
box.space.t:create_index('i')
box.space.t:insert{1,0}
box.space.t:create_index('i2',{parts={2,'scalar'}})
function before_replace_1 (old,new) print('before #1') box.space.t:run_triggers(false) return new end
function before_replace_2 (old,new) print('before #2') box.space.t:run_triggers(false) return new end
function on_replace (old,new) print('on')  end
box.space.t:on_replace(on_replace)
box.space.t:before_replace(before_replace_1)
box.space.t:before_replace(before_replace_2)
box.space.t:replace{1,1}

Another example:
Perhaps this is not related, and perhaps this is not a bug,
but (since "return old" has special effects in before_replace triggers)
perhaps this is a related phenomenon.
These requests print 'before #2' and 'before #1', but do not  print 'on'

box.cfg{}
box.space.t:drop()
box.schema.space.create('t')
box.space.t:create_index('i')
box.space.t:insert{1,0}
box.space.t:create_index('i2',{parts={2,'scalar'}})
function before_replace_1 (old,new) print('before #1') return old end
function before_replace_2 (old,new) print('before #2') return old end
function on_replace (old,new) print('on')  end
box.space.t:on_replace(on_replace)
box.space.t:before_replace(before_replace_1)
box.space.t:before_replace(before_replace_2)
box.space.t:replace{1,1}

**Comment by kostja** [comment]
Whatever is the behaviour, we have no documentation and no tests for it.

**Comment by kostja** [comment]
Pushed the test cases.
