### ISSUE TITLE
memory leak in http.client when using https

### ISSUE THREAD

**Issue by iskandarov-egor** [tarantool/tarantool#3130]
http.client leaks memory when using https:
```
c = require('http.client').new()
for i=1,10^3 do c:get('https://...') end -- leaks memory
for i=1,10^3 do c:get('http://...') end -- doesn't
```

tarantool version: Tarantool 1.7.7-221-g8b08ec5

**Comment by GeorgyKirichenko** [comment]
Please paste more info about the memory leak, how you has detect that, your OS version and curl package version and with which library openssl/libressl/gnutls libcurl was built

**Comment by andrew-statsenko** [comment]
`$ cat /etc/centos-release
CentOS Linux release 7.2.1511 (Core)

$ rpm -qi tarantool | grep Version
Version     : 1.7.7.221


$ rpm -qi libcurl | grep Version
Version     : 7.58.0`

**Comment by GeorgyKirichenko** [comment]
@andrew-statsenko this is possibly libcurl issue, was some leak detected after libcurl upgrade?

**Comment by andrew-statsenko** [comment]
After upgrade libcurl from 7.29.0 to latest 7.58.0 leak is slow done, but I think it still exist:

initial RSS: 33608 => 10^5 HTTPS GET requests => RSS: 34604

Look's like not critical issue, but if you investigate this issue it will be good.

**Comment by kostja** [comment]
Please reopen this bug if there is still a memory leak.
