### ISSUE TITLE
Potential negative effects when using coroutines and fibers?

### ISSUE THREAD

**Issue by aleclarson** [tarantool/tarantool#3131]
I found [this StackOverflow answer](https://stackoverflow.com/questions/36152489/when-to-use-fibers-and-when-to-use-co-routines-in-tarantool/36152870#36152870) that briefly touched on a potential problem when using coroutines instead of fibers, but I'm wondering if any other negative effects are possible.

I'd rather use fibers whenever possible, but I might be forced to use coroutines in situations where a Lua library does something I need where Tarantool is lacking.

**Comment by kostja** [comment]
I added extra info on stackoverflow.
