### ISSUE TITLE
fio.open(path):read() returning zero bytes

### ISSUE THREAD

**Issue by aleclarson** [tarantool/tarantool#3133]
The docs say that `:read()` without arguments should read the entire file, but I seem to get a zero length string back instead.

**Comment by aleclarson** [comment]
Workaround:
```lua
local fh = fio.open(path)
fh:read(fh:stat().size)
```

**Comment by Totktonada** [comment]
What revision are you using? fio.read() w/o arguments supported since 1.7.7-208-gdf2387b36. See #2925 for details.

**Comment by aleclarson** [comment]
Oh okay. I'm using 1.7.6-12-g2db448b
