### ISSUE TITLE
Nullable fields

### ISSUE THREAD

**Issue by aleclarson** [tarantool/tarantool#3135]
Does `space:format` support defining nullable fields?

```lua
space:format{
  {'id', 'uint'},
  {'email', 'string', nullable=true},
}
```

If so, the docs should be updated.

**Comment by aleclarson** [comment]
I would prefer nullable by default, with a `required=true` to declare otherwise.

**Comment by kostja** [comment]
Use is_nullable instead please. The docs will be updated soon. and it's in 1.7.7 only.

**Comment by kostja** [comment]
BTW, the ETA to respond in a ticket is a couple of weeks. If you need help, using telegram channel usually works faster.
