### ISSUE TITLE
Bus error: moonscript loader

### ISSUE THREAD

**Issue by aleclarson** [tarantool/tarantool#3143]
I found a weird `Bus error: 10` caused by using [moonscript](http://moonscript.org)'s package loader.

The .zip file below contains a Lua program that runs fine with Lua 5.1 and 5.3, but not Tarantool.

[Repro link.](https://drive.google.com/file/d/1LZH3uyVQJU0WnXxJCl_2Kd0TC-k4qFV_/view?usp=sharing)

View the `README.md` file for more details. Let me know if anything else is necessary.

I'm on OSX High Sierra v10.13

**Comment by aleclarson** [comment]
If there's any way to get a real error message, I'd love to know.

**Comment by kostja** [comment]
Sorry, we will have not time to look at this.
