### ISSUE TITLE
A gotcha when granting to universe with options

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#3146]
The name of the universe is optional, so we don't check it. If a user wants to specify extra options in the grant, such as if_not_exists, and mistakes object name argument with options argument, options are silently ignored:
```
local function bootstrap()
    box.schema.user.grant('tnt', 'read,write,execute', 'universe', {if_not_exists = true})
    print("box.once is executed on master")
end
```
Please fix the Lua code to ensure that universe name is a scalar - string or nil.

**Comment by locker** [comment]
Fixed by 7e652c220b85663c2185021d24e0c2f306754e1b
