### ISSUE TITLE
Do not check secondary index uniqueness on REPLACE if it includes all primary index parts

### ISSUE THREAD

**Issue by locker** [tarantool/tarantool#3154]
If a secondary index contains all parts of the primary index, we don't need to check uniqueness on REPLACE as it is guaranteed by the primary index. This can spare us some disk spaces.

**Comment by Gerold103** [comment]
It is possible not only for primary parts included in secondary ones. It works for any unique index parts, included in any another index parts. To do minimal count of unique checks we must detect indexes, which uniqueness check we can avoid always. These indexes can be found during vinyl space creation.
For example, for unique indexes index1 parts = {1, 2, 3}, index2 parts = {2, 3}, index3 parts = {4, 5}, index4 parts = {5, 4, 3} we can always skip unique check of index1 and index4.
**NOTE: And the same is true for memtx!!!**

**Comment by Gerold103** [comment]
// Removed vinyl, because it works for memtx too.

**Comment by locker** [comment]
> // Removed vinyl, because it works for memtx too.

For memtx the uniqueness check comes for free, because insertion of a new tuple into an index implies a lookup - see [memtx_tree_index_replace](https://github.com/tarantool/tarantool/blob/99c7a971df04d7234ee88da501b291497c4dd43f/src/box/memtx_tree.c#L383) and [replace_check_dup](https://github.com/tarantool/tarantool/blob/99c7a971df04d7234ee88da501b291497c4dd43f/src/box/index.h#L406). So no, this is purely a vinyl issue.
