### ISSUE TITLE
heartbeat messages don't send under curtain conditions

### ISSUE THREAD

**Issue by kbelyavs** [tarantool/tarantool#3160]
After we Introduced read with timeout on applier side to detect master's state, condition variable woken up on incoming ACK, so heartbeat doesn't send.
Suggest to remove this in relay_reader_f (since we read with timeout, and it's not needed anymore)

This leads to race condition and breaks connection between instances.

**Comment by locker** [comment]
Fixed by ad562340ce2978124e1162e0289306a989be3d38

**Comment by GeorgyKirichenko** [comment]
If a local wal has changes only from a remote peer (and relay has nothing to send due to filtration) then relay won't send any heartbeats.
