### ISSUE TITLE
Netbox emits error with no message

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#3163]
Netbox sometimes can emit error with code 77, but with empty message. There must be at least description of error code.

**Comment by kostja** [comment]
Please provide a test case.

**Comment by Gerold103** [comment]
I see this in vshard logs, but do not know, how to repoduce. It was exactly empty string in message, not nil. Like {code = 77, message = ""}.

**Comment by kyukhin** [comment]
@Gerold103 , w/o a testcase I guess we should close this.

**Comment by kyukhin** [comment]
Closing. There's no way to reproduce.
