### ISSUE TITLE
Tarantool hangs at exit until vinyl compaction is complete

### ISSUE THREAD

**Issue by locker** [tarantool/tarantool#3166]
If the user terminates tarantool while compaction is in progress, tarantool won't exit immediately - it will hang until compaction is complete, which may take quite a while on large data sets. Ridiculously, once compaction has been finished, vinyl will not commit the produced run in the vylog and so will delete it after restart and schedule compaction anew. We should either abort all write tasks at exit or commit the produced runs before exiting.

**Comment by kostja** [comment]
Abort please, or, even better, exit quickly and remove the garbage which is left around during garbage collection.
