### ISSUE TITLE
index:max() returns irrelevant tuple if there is no match

### ISSUE THREAD

**Issue by sharonovd** [tarantool/tarantool#3167]
If ```box.space.<my_space>.index.<my_index>:select(some_key)``` returns nothing, I expect ```:max(some_key)``` to return nothing as well. But it returns some random tuple instead!

Sample code:

```
localhost:3302> box.schema.create_space('test')
---
- index: []
  on_replace: 'function: 0x010ece3280'
  temporary: false
  id: 540
  engine: memtx
  enabled: false
  name: test
  field_count: 0
- created
...

localhost:3302> box.space.test:create_index('test', {type='tree', parts={1,'unsigned',2,'unsigned'}})
---
- unique: true
  parts:
  - type: unsigned
    is_nullable: false
    fieldno: 1
  - type: unsigned
    is_nullable: false
    fieldno: 2
  id: 0
  space_id: 540
  name: test
  type: TREE
...

localhost:3302> box.space.test:insert({1, 1})
---
- [1, 1]
...

localhost:3302> box.space.test:insert({1, 2})
---
- [1, 2]
...

localhost:3302> box.space.test:insert({2, 2})
---
- [2, 2]
...

localhost:3302> box.space.test.in
box.space.test.index    box.space.test.insert(  
localhost:3302> box.space.test.index.test:select({3})
---
- []
...

localhost:3302> box.space.test.index.test:max({3})
---
- [2, 2]
...


```

**Comment by bigbes** [comment]
It's due to `box_index_max` is implemented using `:select(key, { iterator = 'LE', limit = 1})`. Probably checking `:count(key) > 0` is OK for this case

**Comment by locker** [comment]
This is a [documented](https://tarantool.org/en/doc/1.7/book/box/box_index.html?highlight=index%20max#lua-function.index_object.max) behavior:

> Return:
> 
> the tuple for the last key in the index. If optional key-value is supplied, returns the last key which is less than or equal to key-value.

I'm afraid "fixing" it may break existing users.

**Comment by sharonovd** [comment]
IMO, this is a documented bs.

You may leave it as it is - but it renders max() rather useless.

**Comment by kostja** [comment]
I agree with Dmitry, never was the intent. Let's try to fix it.

**Comment by Gerold103** [comment]
The patch is ready long ago.
