### ISSUE TITLE
index.alter() does not work as expected for empty vinyl spaces

### ISSUE THREAD

**Issue by locker** [tarantool/tarantool#3169]
If the new index definition is compatible with the old one and so index rebuild is not necessary, index.alter() doesn't update key definition stored in vinyl, resulting in invalid behavior. For example,
```
tarantool> s = box.schema.space.create('vinyl', {engine = 'vinyl'})
---
...

tarantool> i = s:create_index('pk')
---
...

tarantool> i:alter{parts = {1, 'integer'}}
---
...

tarantool> _ = s:insert{-1}
---
...

tarantool> _ = s:insert{1}
---
...

tarantool> s:select()
---
- - [1]
  - [-1]
...
```
Expected:
```
---
- - [-1]
  - [1]
...
```

**Comment by Gerold103** [comment]
Lets forbid this alter (now it is forbidden for empty spaces, but key_def of a primary index is already in vylog even if a space is empty).
