### ISSUE TITLE
Introduce type ANY

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#3174]
Tarantool backend has a convenient way to store arbitrary values: it has dedicated type, called `ANY`.
Expose this type by SQL frontend.

**Comment by Gerold103** [comment]
I think, you must introduce types ARRAY and MAP at first, because ANY contains them.

**Comment by kostja** [comment]
I agree with Vlad, let's add Array/Map columns first, then we can add ANY. Essentially ANY is SCALAR + arrays + maps.
