### ISSUE TITLE
Do not print multiple "Connection refused" on netbox reconnection attempts

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#3175]
When `reconnect_after` option is specified, and a netbox connection broken, it logs each `reconnect_after` seconds `Connection refused` message. When `reconnect_after` is about 0.01 seconds, it turns a log file into a garbage with thousands of duplicate records. Lets log this message once, and do not write anything to a log until a state is changed to closed or connected state.

**Comment by Totktonada** [comment]
The connection state dump each 10 seconds or like so can be useful in the case.

**Comment by Gerold103** [comment]
@Totktonada good idea. This period could be configurable via `connect()` options, and could be `math.huge` to log any state change only once. The logging state only once is preferable for vshard, because its connections can be up very log. For example, Mons have vshard cluster with uptime 5 days - it is 43200 identical messages for each connection. His cluster consists of two replicasets, so each router would log 86400 log messages - log file becomes unreadable.

**Comment by Totktonada** [comment]
@Gerold103 I mean state dumps in case when something going wrong or, in other words, only for 'bad' states.

**Comment by kostja** [comment]
Please make a short, clear and easy fix and close this in any branch you want.
