### ISSUE TITLE
Failed to write to disk

### ISSUE THREAD

**Issue by zloidemon** [tarantool/tarantool#3176]
Ubuntu 16.04, version: 1.7.6-15-g033160e

```
unix/:/var/run/tarantool/test.control> box.space.test:replace({.....})
---
- error: Failed to write to disk
...

unix/:/var/run/tarantool/test.control> box.snapshot()
---
- ok
...

unix/:/var/run/tarantool/test.control> box.space.test:replace({.......})
---
- error: Failed to write to disk
...
```

Fs works fine:

```
# touch 123 && echo $?
```

logs:

```
2018-02-19 16:45:45.168 [2315] wal/101/main xlog.c:703 !> SystemError file '/var/lib/tarantool/test/00000000000000000695.xlog' already exists: File exists
2018-02-19 16:45:45.168 [2315] main/111/console/unix/: txn.c:261 E> ER_WAL_IO: Failed to write to disk
```

I don't understand what is going wrong, not enough information in logs files and returns by tarantool console.

My data is not so dangerous to lost, i solved issue after drop xlog file.

Got more info about failure in DC, that issue after power off on rack tarantools aren't auto-recovery itself after power off.

**Comment by kostja** [comment]
We discussed this and agreed @zloidemon needs to re-test it with a never version.

**Comment by zloidemon** [comment]
Yes, I updated to latest tarantool version in repository **1.7.6.19.g9f35a12-1**, but still don't understand where is package **1.7.7** with fixes.

**Comment by kostja** [comment]
Use 1.9 branch please.

**Comment by kyukhin** [comment]
No updates for 4 months. I guess issue resolved.
