### ISSUE TITLE
Finish cleanup in SQL FE struct Index

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#3179]
There pack of fields which turn to dead:
- is_covering
- is_resized

Ultimately, we need to store inside `struct Index` only those fields which are needed to store data between parse and actual DDL invocation. In all other cases, data should be gathered from Tarantool's backend.

**Comment by kyukhin** [comment]
More fields:
- nKeyCol
- nColumn
-  idxType
- aiColumn
- aSortOrder: should be commented so far. Until #3016 is implemented

**Comment by Korablev77** [comment]
@kyukhin removing of idxType rather belongs to #3181
