### ISSUE TITLE
Remove auto-generated files from source tree

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#3183]
Right now, in order to regenerate automaton of SQL grammar parser, Tarantool
should be built in special `SQL_MAINTAINER_MODE` in which case dedicated
scripts are involved to update opcode table and compile Lemon-written grammar
into C source code.

This is awful and should be refactored: grammar should be compiled always and
generated sources should be treated as build artefacts (just like object files).

Important note: do not introduce extra dependencies for Tarantool build system.
Some of scripts written in TCL, so they should be re-writeen in bash/perl/python
or something which Tarantool already using.

**Comment by Totktonada** [comment]
We don’t use bash/perl/python during build as I see. sh does not support arrays and regexps (w/o fork to run grep), so to use sh we need to rewrite mkopcodeh.tcl using several (constant number) grep invocation per needle line type and emulate tcl’s associative arrays via `declare ARRAY_${key}=value`. The way to go?
