### ISSUE TITLE
Read-only replica

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#3186]
Designate a uuid and server id for read-only subscriptions which do not require registration in _cluster table. It should be possible to join an existing cluster without polluting its _cluster table, but by simply sending your vclock and subscribing to events.

**Comment by unera** [comment]
### Example 1

Backup/reserve replica, that is used for only backups.

### Example 2

Memcache-like applications (for example: each backend has its own RO replica, so backend can be turned on/off)

PS: It would be nice if `temporary` spaces was accessible as readwrite.

**Comment by unera** [comment]
Example `box.cfg` option:

```lua
box.cfg{
    cluster = false,
}
```
The replica will not be present in `_cluster` space.

**Comment by unera** [comment]
Example `box.cfg` option:

```lua
box.cfg{
    cluster = false,
}
```
The replica will not be present in `_cluster` space.

**Comment by ddosoff** [comment]
I'd like to have this option.

**Comment by rkravchik** [comment]
This issue is connected with #2572 due to @viciious [comment](https://github.com/tarantool/tarantool/issues/2572#issuecomment-313373007):
> A read-only replica with fixed client-side fake UUID ('0000...00') would also work in our case.

And the story lasts over the year...

**Comment by maks83** [comment]
> It would be nice if `temporary` spaces was accessible as readwrite.

i need this feature for implementing map/reduce on slave replicas

**Comment by rkravchik** [comment]
It would be nice if this feature would be backported to 1.6.9.
