### ISSUE TITLE
Error when changing vinyl options

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#3193]
I have Ubuntu 17.04.
I have Tarantool 1.7, pulled from tarantool-1.7-next source a few days ago.

I execute these requests:

box.cfg{}
box.schema.space.create('v',{engine='vinyl'})
box.space.v:create_index('i')
box.space.v.index.i:alter({bloom_fpr=0.0})
for i=1,100000 do i = i + 1 box.space.v:insert{i,''} box.space.v.index.i:alter({page_size=i}) end

Result =
2018-02-22 18:53:02.733 [7300] main/102/vinyl.scheduler I> 512/0: dump
started
tarantool:
/home/pgulutzan/tarantool-1.7-next/src/lib/small/small/quota.h:137:
quota_use: Assertion `size_in_units' failed.

I am unable to restart with box.cfg,
so the database is not recoverable.

**Comment by locker** [comment]
Fixed by 632592bf21da6a1f2f666dc186f4ec4f4319e43f
