### ISSUE TITLE
sql: enable REINDEX statement

### ISSUE THREAD

**Issue by Korablev77** [tarantool/tarantool#3195]
Originally, SQLite provides an opportunity to do reindexing:
https://www.sqlite.org/lang_reindex.html
For instance, it might be useful while dealing with changed collation. However, in our SQL an attempt at calling reindex results in assertion fault:
```
box.cfg{}
\set language sql
CREATE TABLE t1(id PRIMARY KEY, a);
CREATE INDEX i1 ON t1(a);
REINDEX t1.i1;
Assertion failed: (0), function sqlite3Reindex, file tarantool/src/box/sql/build.c, line 4219.
```
So, we should decide whether it is worth to support this feature and fix it, or just remove it.

**Comment by Totktonada** [comment]
Let consider this issue as 'we need to fix support of REINDEX statement' while it will be banned in the scope of 2.1.0 in #2174.

**Comment by Gerold103** [comment]
If a collation is changed, index should be recreated automatically. REINDEX makes no sense for a user.

**Comment by Gerold103** [comment]
@Korablev77 No, I can not imagine how we can use it. To be honest, I thought that REINDEX is a way to reduce fragmentation in B-tree on disk. But even in such a way it is not applicable - the only disk storage is Vinyl and it is an LSM tree.

**Comment by Korablev77** [comment]
Ok, then I close this issue.
