### ISSUE TITLE
`default` option for `space:format`

### ISSUE THREAD

**Issue by aleclarson** [tarantool/tarantool#3206]
Has a `default` option for `space:format` been considered?

For example, writing `{'field', 'string', default = box.NULL}` would fill the field with `box.NULL` unless a string is provided to `space:insert`. Additionally, the `is_nullable` option would be implicitly set to `true`, because `box.NULL` is the default value.

**Comment by aleclarson** [comment]
The main issue this would fix is the following scenario. I have a tuple where the last five fields have no value (not even nil). I have to set the last field before I set the other four fields, but an error is thrown if I don't check the other four fields and set them to nil if no value exists.

**Comment by aleclarson** [comment]
I've managed to implement this in userland.

```moon
space_insert = space_mt.insert
space_mt.insert = (tuple) =>
  format = get_format @id

  if #format > #tuple
    for i = #tuple + 1, #format
      val = format[i].default
      tuple[i] = val if type(val) ~= 'nil'

  space_insert self, tuple
```

The `get_format` function checks a local table for the cached result of `box.space._space:get(space_id).format`.

**Comment by msiomkin** [comment]
I have one more case. Default values are even more important when you add a non nullable field to an existing not empty space. This gives an error now:

error: Tuple field count 2 is less than required by space format or defined indexes
    (expected at least 3)

This error could be eliminated if we had 'default' option in space format.

**Comment by romanhabibov** [comment]
It is needed to support <ADD COLUMN> #3075 for non empty spaces.

**Comment by pgulutzan** [comment]
There already is an undocumented default option for space:format.
This syntax is legal:
box.schema.space.create('tester')
box.space.tester:create_index('I')
box.space.tester:format({{'a',type='number'},{'b',type='number', default = '15'}})
However, it is for SQL's DEFAULT clause. So this will work:
box.execute([[INSERT INTO "tester" ("a") VALUES (1);]])
But this will fail:
box.space.tester:insert{2}

**Comment by unera** [comment]
duplicate #8157
