### ISSUE TITLE
Tarantool does not recover properly if data missing in xlog

### ISSUE THREAD

**Issue by kbelyavs** [tarantool/tarantool#3210]
Under certain conditions like last records missing in master's xlog, Tarantool does not recover properly.

```
tarantool1> box.cfg { listen = 3313 }
tarantool1> box.schema.user.grant('guest', 'read,write,execute', 'universe')
tarantool2> box.cfg { listen = 3314, replication_source = 3313 }
tarantool1> box.space._schema:insert({'1'})
tarantool2> box.space._schema:select()
```
One can see record ['1'] here ..
Ctrl+d tarantool1
delete last xlog (rm 0*2.xlog)
start tarantool1 again and check
```
tarantool1> box.cfg { listen = 3313 } 
tarantool1> box.space._schema:select()
```
No record ['1'] ..
Now let's insert some more data..
```
tarantool1> box.space._schema:insert({'2'})
tarantool1> box.space._schema:insert({'3'})
```
And check again ..
```
tarantool1> box.space._schema:select()
---
- - ['2']
  - ['3']
tarantool2> box.space._schema:select()
---
- - ['1']
  - ['3']
```
Different datasets, both incorrect.

Done for 1.9, still need to do for 1.6

**Comment by locker** [comment]
Fixed by eae84efbfbf9e504660eba26c013487c7991459b

**Comment by kbelyavs** [comment]
I think we need to reopen this bug again since still need to do same for 1.6.

**Comment by kbelyavs** [comment]
Update: no need for this in 1.6. Close.
