### ISSUE TITLE
Need documented way for detection that running under tarantoolctl

### ISSUE THREAD

**Issue by Mons** [tarantool/tarantool#3215]
Currently there are several undocumented hacks, that could be used to detect, that app was run under tarantoolctl.
Here 2 of them:
```lua
local under_tarantoolctl = fiber.name() == 'tarantoolctl'
local under_tarantoolctl = pcall(function() return require'ffi'.C.kill end)
```

Second is very ugly and unpredictable, so I want to legitimate and document first one ;)

**Comment by kostja** [comment]
+ Add to this a way to detect that it's a systemd restart

**Comment by sergepetrenko** [comment]
@Mons for me only the second hack works right now, could you please give more info on how do you make the first one work?

**Comment by Mons** [comment]
But... You created a new one...
So there will be 2 of them: that works on 1.6-1.10 and that works on 1.10.1+
