### ISSUE TITLE
Need to avoid broke twemproxy

### ISSUE THREAD

**Issue by zloidemon** [tarantool/tarantool#3221]
Please, take a time and look at [nc_tarantool.c](https://github.com/tarantool/twemproxy/blob/e2c2736dec3341a3f337952a0d18874d4918e0cc/src/proto/nc_tarantool.c#L813) new versions of tarantool won't work with old twemproxy.

**Comment by kostja** [comment]
What exactly is broken? nc_tarantool.c referenced is fine, it won't break anything.

**Comment by zloidemon** [comment]
```
    n = nc_scnprintf(mbuf->last, IPROTO_GREETING_SIZE + 1,
                     "Tarantool %-20s %-32s\n%-63s\n",
                     "1.6.0", "("PACKAGE_STRING")", base64buf);
```

**Comment by kostja** [comment]
This does not seem broken.

**Comment by kyukhin** [comment]
Closing then.
