### ISSUE TITLE
Cannot use luarocks' luacrypto (Tarantool 1.8.3)

### ISSUE THREAD

**Issue by cbalano** [tarantool/tarantool#3230]
I issued "tarantoolctl rocks install luacrypto" at the OS prompt and it completed fine. But when I tried to use it,  I get an error essentially saying that luacrypto.decrypt is a non-existing index.

Turns out that Tarantool 1.8.3 comes with its own module called luacrypto - which is nothing like the one I need to use - and that tarantool's luacrypto is actually picked up by require("luacrypto") every time.

So my question is how can I tell Lua Interpreter to pick up luarocks' luacrypto over tarantool's luacrypto?

Forking and changing the name of the luarocks library is not an option, because there are many other luarocks (example: luajwt) listing it as a dependency, and that means changing all those luarocks as well to depend on the renamed library.

**Comment by kostja** [comment]
* cbalano <notifications@github.com> [18/03/12 08:38]:
> I issued "tarantoolctl rocks install luacrypto" at the OS prompt and it completed fine. But when I tried to use it,  I get an error essentially saying that luacrypto.decrypt is a non-existing index.
> 
> Turns out that Tarantool 1.8.3 comes with its own module called luacrypto - which is nothing like the one I need to use - and that tarantool's luacrypto is actually picked up by require "luacrypto" evry time.
> 
> So my question is how can I tell Lua Interpreter to pick up luarock's luacrypto over tarantool's luacrypto?
> 
> Forking and changing the name of the luarocks library is not an
> option, because there are many other luarocks (example: luajwt)
> listing it as a dependency, and that means changing all those
> luarocks as well to depend on the renamed library.

We don't have a built-in luacrypt module. Could you attach a short
Lua script that fails?

-- 
Konstantin Osipov, Moscow, Russia, +7 903 626 22 32
http://tarantool.org - www.twitter.com/kostja_osipov

**Comment by cbalano** [comment]
`#! /usr/local/bin/tarantool

crypto = require "crypto"
for k,v in pairs(crypto) do
 print (k, v)
end
`


`
/opt/ts/lua> test_luacrypto.lua
digest  table: 0x41c42de8
hmac    table: 0x41c43bb0
cipher  table: 0x40a2c3f8


I have no crypto module installed anywhere, so it must come from tarantool. In fact I installed the md5 module specifically to perform my encryption tasks.

/opt/ts/lua> tarantoolctl rocks list

Installed rocks:
----------------

ad
   1.0.0-0 (installed) - /opt/ts/lua/.rocks/share/tarantool/rocks

authman
   scm-1 (installed) - /opt/ts/lua/.rocks/share/tarantool/rocks

cbench
   scm-1 (installed) - /opt/ts/lua/.rocks/share/tarantool/rocks

connpool
   scm-1 (installed) - /opt/ts/lua/.rocks/share/tarantool/rocks

document
   scm-1 (installed) - /opt/ts/lua/.rocks/share/tarantool/rocks

dump
   scm-1 (installed) - /opt/ts/lua/.rocks/share/tarantool/rocks

expirationd
   scm-1 (installed) - /opt/ts/lua/.rocks/share/tarantool/rocks

http
   scm-1 (installed) - /opt/ts/lua/.rocks/share/tarantool/rocks

lbase64
   20120820-1 (installed) - /opt/ts/lua/.rocks/share/tarantool/rocks

lua-cjson
   2.1devel-1 (installed) - /opt/ts/lua/.rocks/share/tarantool/rocks

luasocket
   3.0rc1-2 (installed) - /opt/ts/lua/.rocks/share/tarantool/rocks

md5
   1.2-1 (installed) - /opt/ts/lua/.rocks/share/tarantool/rocks

queue
   scm-1 (installed) - /opt/ts/lua/.rocks/share/tarantool/rocks

shard
   scm-1 (installed) - /opt/ts/lua/.rocks/share/tarantool/rocks

smtp
   scm-1 (installed) - /opt/ts/lua/.rocks/share/tarantool/rocks

watchdog
   scm-1 (installed) - /opt/ts/lua/.rocks/share/tarantool/rocks
`

**Comment by kyukhin** [comment]
I've grep-ed source of Tarantool and looks like crypto is only used by digest module.
This module is used in a single place (checkpoint_daemon), where urandom() digest's
function is invoked. This function in turn does not depend on crypto.

**Comment by kyukhin** [comment]
So, right now your method is safe.
