### ISSUE TITLE
Enable parallel test-run for whole test suites

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#3232]
test-run now works in parallel in most test suites, but not for all.

Need to enable it everywhere or carefully explain why it is not possible
in each case.

**Comment by Totktonada** [comment]
Dupe of #2436, but the description here is more clear.

**Comment by Totktonada** [comment]
Only vinyl have `is_parallel = False` now.

**Comment by ligurio** [comment]
There were many commits regarding parallel test runs. Can we consider task as done? // CC: @avtikhon, @Totktonada

**Comment by Totktonada** [comment]
Yep. Thanks for catching it.
