### ISSUE TITLE
Can not create a space starting with digit

### ISSUE THREAD

**Issue by mtrempoltsev** [tarantool/tarantool#3241]
Example of a valid name from the documentation:

```
box.space['1*A']:select{1}
```

[https://tarantool.org/en/doc/1.7/reference/lua_tips.html#app-server-names](https://tarantool.org/en/doc/1.7/reference/lua_tips.html#app-server-names)

```
tarantool> space = box.schema.space.create('1a')
---
- error: Invalid identifier '1a' (expected letters, digits or an underscore)
...
```

Branch: 1.7.6-stable

**Comment by Khatskevich** [comment]
1. We do not have `1.7.6-stable` branch in gh repository
2. This feature is not available in `1.7`
3. This snippet works on `1.9` and higher

Posibble solutions:
1. Backport to `1.7`
2. Fix the docs

**Comment by kyukhin** [comment]
I guess we should fix docs then.

**Comment by kostja** [comment]
Fix the docs.

**Comment by Khatskevich** [comment]
Docs are fixed.
