### ISSUE TITLE
Add support for lua 5.3 bignum

### ISSUE THREAD

**Issue by knazarov** [tarantool/tarantool#3265]
In order to better support applications dealing with financial data, it will be nice to make integer behavior less surprising. Lua 5.3 bignum is a good candidate for this.

**Comment by kyukhin** [comment]
I see no support for bignum in core Lua 5.3
There's a package for bignum here [1].
It should be compatible w/ Tarantool.

@racktear, what's the issue?

[1] - http://oss.digirati.com.br/luabignum/bn/index.htm

**Comment by Totktonada** [comment]
@racktear Is our number64 has enough bits for such applications? If so, are there problems with number64 that prevent using in these applications?

**Comment by kyukhin** [comment]
No feedback for two months. Closing.
