### ISSUE TITLE
replication_connect_quorum=0 is ignored

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#3278]
The spec says:

if box.cfg.read_only is false, the replica checks a new variable, box.cfg.replication_connect_quorum, which defaults to the number of entries in box.cfg.replication, and specifies the number of peers the replica should be in sync with to enter read-write mode. If the quorum is reached, the mode is read-write. Otherwise the mode is read-only. The new, forced read-only mode can be changed only by changing box.cfg.replication or box.cfg.replication_connect_quorum.
```
 % ./tarantool
Tarantool 1.10.0-34-g1c3eb95
type 'help' for interactive help
tarantool> box.cfg{replication = { '127.0.0.1:3302' },replication_connect_quorum = 0,replication_timeout = 1,read_only = false,}
...
2018-03-24 08:25:22.664 [14434] main/101/interactive I> recovery start
2018-03-24 08:25:22.664 [14434] main/101/interactive I> recovering from `./00000000000000000000.snap'
2018-03-24 08:25:22.684 [14434] main/105/applier/127.0.0.1:3302 I> can't connect to master
2018-03-24 08:25:22.684 [14434] main/105/applier/127.0.0.1:3302 coio.cc:104 !> SystemError connect, called on fd 13, aka 127.0.0.1:33314: Connection refused
2018-03-24 08:25:22.684 [14434] main/105/applier/127.0.0.1:3302 I> will retry every 1.00 second
2018-03-24 08:25:26.685 [14434] main/101/interactive I> ready to accept requests
2018-03-24 08:25:26.685 [14434] main/109/checkpoint_daemon I> started
2018-03-24 08:25:26.685 [14434] main/109/checkpoint_daemon I> scheduled the next snapshot at Sat Mar 24 10:14:06 2018
---
...
tarantool> box.info.status
---
- orphan
...
```
**What should happen**:

If replication_connect_quorum is 0, we should enter read-write mode.
Please also check that replication_connect_quorum properly accounts self: if self is present in replication list, it should be accounted, otherwise (as in the test case above, not). For example, for the test case above, the behavior exhibited should only be present when replication_connect_quorum=1

**Comment by Gerold103** [comment]
Fixing of this will help also to return to a fullmesh topology in vshard: https://github.com/tarantool/vshard/issues/83

**Comment by Gerold103** [comment]
On my computer the `box.cfg{replication = { '127.0.0.1:<not existing port>' },replication_connect_quorum = 0,replication_timeout = 1,read_only = false,}` command just blocks the console. I even can not check box.info.status.

**Comment by Gerold103** [comment]
Still not works.

**Comment by Gerold103** [comment]
I am trying this:
```Lua
box.cfg{
replication = { '127.0.0.1:33333' },
replication_connect_quorum = 0,
replication_timeout = 1,
read_only = false
}
```
This call still blocks the thread.

**Comment by Gerold103** [comment]
@kostja @kbelyavs

**Comment by Gerold103** [comment]
Moreover, this "fix" breaks master-slave. Here is the simple test case:
```Lua
-- First node, master. --
box.cfg{
	listen=3313,
	read_only = false
}
box.schema.user.grant('guest', 'read,write,execute', 'universe')
```
```Lua
-- Second node, slave. --
box.cfg{
	replication = { '127.0.0.1:3313' },
	replication_connect_quorum = 0,
	read_only = true
}
```

After start I print replication info on the slave:
```YAML
tarantool> box.info.replication
---
- 1:
    id: 1
    uuid: 37d7b710-16d8-46ac-b688-fb8a55ae1083
    lsn: 2
    upstream:
      status: ready
      idle: 3.18981299999
      peer: 127.0.0.1:3313
      lag: 0
  2:
    id: 2
    uuid: 458f614d-ede6-40a5-a7c5-5e6c422bfad3
    lsn: 0
...
```

If I remove `replication_connect_quorum` option, then the status is `follow`, but nothing is changed actually - both the master and the slave work and see each other.

**Comment by kbelyavs** [comment]
I am trying this:
```Lua
box.cfg{
replication = { '127.0.0.1:33333' }, -- port 33333 is empty
replication_connect_quorum = 0,
replication_timeout = 1,
read_only = false
}
```
This call still blocks the thread.

It's a different case. We still can't do box.cfg on replica with master absent. It's because bootstrap and leader election required same replication value across the cluster with all masters present.

**Comment by Gerold103** [comment]
It makes master-slave be unusable.

**Comment by Gerold103** [comment]
And this master-slave case: https://github.com/tarantool/tarantool/issues/3278#issuecomment-381733771 worked before the patch. Now it is not.

**Comment by kbelyavs** [comment]
Moreover, this "fix" breaks master-slave. Here is the simple test case:
@Gerold103 second is true, investigating.

**Comment by Gerold103** [comment]
See the second test case:
```Lua
box.cfg{
    listen = 33334,
    replication = { '127.0.0.1:33333', '127.0.0.1:33334' },
    replication_connect_quorum = 0,
    replication_timeout = 1,
    read_only = false
}
```

This is correct master-master configuration of one of the cluster members. And it blocks the thread too.

**Comment by kbelyavs** [comment]
@Gerold103 thank you for finding that.
It seems that replication_connect_quorum should be ignored during bootstrap. Will discuss it with @locker and @kostja.

**Comment by Gerold103** [comment]
Thanks.

**Comment by Gerold103** [comment]
The last case still does not work:
```Lua
box.cfg{
    listen = 33334,
    replication = { '127.0.0.1:33333', '127.0.0.1:33334' },
    replication_connect_quorum = 0,
    replication_timeout = 1,
    read_only = false
}
```
This call hangs forever.

**Comment by kbelyavs** [comment]
Is this a first run? I mean if you have no snapshot file, you start a cluster with some members missing, whether the replication_connect_quorum option is set or not, it will hangs forever and this is a different case. During bootstrap all cluster members should present.
'replication_connect_quorum' allows to continue work after bootstrap.
Please explain your test case more carefully.
How I check?
1. Run two master instances in a full mesh.
2. Shutdown both
3a. Run second with replication_connect_quorum = 0
It has status "running" and is read-write.
3b. Run second without replication_connect_quorum
It has status "orphan" and is read-only.
