### ISSUE TITLE
Enhance tomap() with 'names_only' option

### ISSUE THREAD

**Issue by sharonovd** [tarantool/tarantool#3281]
Please consider enhancing tuple:tomap() with option to strip source key-numbered fields from result.
That would be useful for straightforward exposing formatted spaces via REST.
Proposed interface:
```tuple:tomap({only_names=true})```

Otherwise, I have to maintain util function:

```
function utils.tomap(tuple)
    checks('cdata')
    local map = tuple:tomap()
    assert(map)
    for k, v in pairs(map) do
        if type(k) == 'number' then
            map[k] = nil
        end
    end
    return map
end```

**Comment by Gerold103** [comment]
Duplicate #3280
