### ISSUE TITLE
Use Tarantool's facilities to deal w/ OS

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#3284]
SQL folder contains legacy file called os_unix.c which is responsible for interfacing
with operating system. On the other hand, Tarantool core contains all these facilities:
working w/ files, sleeping etc.

Need to remove os_unix.c and replace all invocation w/ Tarantool core calls.

**Comment by Korablev77** [comment]
It is worth mentioning, that file routine is used mainly for SQL sorter, which relies on merge-sort algorithm. If data to be sorted can't be fitted into heap memory, sorter dumps data to files.
For details see: src/box/sql/vdbesorter.c
