### ISSUE TITLE
http.client documentation bugs

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#3286]
https://tarantool.io/en/doc/1.9/reference/reference_lua/http.html?highlight=http%20client#module-http.client doesn't contain a lot of details. the docs are very sketchy. @hypersolid has more info

**Comment by pgulutzan** [comment]
Should this be reported in https://github.com/tarantool/doc/issues rather than https://github.com/tarantool/tarantool/issues?

**Comment by kyukhin** [comment]
Moved to correct repo.
