### ISSUE TITLE
sql: dry-run for EXECUTE

### ISSUE THREAD

**Issue by alg1973** [tarantool/tarantool#3292]
This feature is connected with [sql cache #2592 ](https://github.com/tarantool/tarantool/issues/2592) but since client API  isn't affected by sql cache  API needs it.
   We need server side prepare call which should return information about sql statement. After prepare server can put the statement into sql cache. The minimum information is number of bind parameters in sql statement. Without such information client API should parse sql statement them-self  which we should avoid.
The main idea behind sql bind variables is ability to execute current statement multiple times.

**Comment by kostja** [comment]
PREPARE is an option to EXECUTE, dry-run. No separate API call for now.

**Comment by Totktonada** [comment]
Aside of dry-run, connectors need parameter count and types.

**Comment by kostja** [comment]
Well, exactly, this options returns parameter count and types, request metadata, but no result set.

**Comment by kyukhin** [comment]
That is important feature of *DBC drivers.

**Comment by Korablev77** [comment]
Now there's `PREPARE` call which returns required meta-information.
