### ISSUE TITLE
1.9.0.0 src tarball removed

### ISSUE THREAD

**Issue by commitay** [tarantool/tarantool#3295]
https://download.tarantool.org/tarantool/1.9/src/tarantool-1.9.0.0.tar.gz

The tarball used in the Homebrew [formula](https://github.com/Homebrew/homebrew-core/blob/d32802ef7c9c472a700b12937509c458ce875cf2/Formula/tarantool.rb#L4) seems to have been removed.

Should we update to the newest tarball in http://download.tarantool.org/tarantool/1.9/src/ ?

https://github.com/Homebrew/homebrew-core/pull/25825

**Comment by kostja** [comment]
Please update. This is some very strange mistake, this is an append-only folder, I will investigate what happened.

**Comment by commitay** [comment]
Thanks @kostja!
