### ISSUE TITLE
Under Mac monotonic_clock is not enabled in libev 

### ISSUE THREAD

**Issue by alg1973** [tarantool/tarantool#3299]
This bug is connected with bug [#2537](https://github.com/tarantool/tarantool/issues/2527) and [fix](https://github.com/tarantool/tarantool/commit/a6c87bf9ac99a633c578aeb3919a09293bc235e3). So under Mac original bug is still an issue.

**Comment by locker** [comment]
Fixed by 10af1cb104420d9f3148bccf0c988ca27e600ac5
