### ISSUE TITLE
sql: parse and load VIEW into in-memory structs

### ISSUE THREAD

**Issue by Korablev77** [tarantool/tarantool#3300]
Currently, views are held in Tarantool as spaces with SQL statement and nothing except that. In order to operate (e.g. fetch number of columns, their names) on view and compile 'SELECT' statement representing given view, we should fetch 'CREATE VIEW' statement from space, parse it and load into struct Select and struct View (i.e. struct Table in original SQLite).

**Comment by kyukhin** [comment]
IMHO,  you do not need `struct View`. `struct Select` is all-inclusive structure and everything else which VIEW might possess is aliases for columns in VIEW's SELECT.
Those names are contained in `space_def->fields`. So, everything you need is to put `struct Select *` field into space_def and compile (using dedicated machinery, like sql_compile_expr()) on space_def create/duplicate in alter.cc

**Comment by Korablev77** [comment]
Closed via https://github.com/tarantool/tarantool/commit/dc358cb014280f5835740b6c2b25608383b14763
