### ISSUE TITLE
cmake option to remove feedback daemon

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#3308]
It would be better to pack tarantool for distros w/o external patches (because these patches will become broken from time to time).

Pack unconditionally with 'spying' stuff is not an option at least for Gentoo (but okay to enable it under a default-disabled flag). So, should I going to maintain patchset upward of tarantool or wait for the cmake flag?

**Comment by kyukhin** [comment]
Please use a configuration time default, feedback_daemon=true/false, not a compile-time option. You can put a different config to /etc/default or /etc/tarantool/instances.available

**Comment by Totktonada** [comment]
I’m against of delivering spying code to Gentoo even when it is disabled (one cannot statically check whether it is really so). Now several sed / rm commads removes the daemon on src_prepare stage. I’ll maintain that approach externally.

**Comment by unera** [comment]
We already have a global config file `/etc/default/tarantool`.

<details> 
  <summary>/etc/default/tarantool content </summary>

```lua
--
-- System-wide settings for tarantoolctl and init scripts
--
-- This file was configured by the package maintainers and you probably
-- don't want to change it. Please complain about your custom configuration
-- directly to upstream's bug tracker rather than to your distro.
--
-- Settings below should be kept in sync with:
--
--   * logrotate configuration
--   * tarantool.service unit
--   * systemd-tmpfiles configuration
--   * directory structure and permissions
--

default_cfg = {
    pid_file   = "/var/run/tarantool", -- /var/run/tarantool/${INSTANCE}.pid
    wal_dir    = "/var/lib/tarantool", -- /var/lib/tarantool/${INSTANCE}/
    memtx_dir  = "/var/lib/tarantool", -- /var/lib/tarantool/${INSTANCE}
    vinyl_dir  = "/var/lib/tarantool", -- /var/lib/tarantool/${INSTANCE}
    log        = "/var/log/tarantool", -- /var/log/tarantool/${INSTANCE}.log
    username   = "tarantool",
    language   = "lua",
}

-- instances.available - all available instances
-- instances.enabled - instances to autostart by sysvinit
instance_dir = "/etc/tarantool/instances.enabled"
-- vim: set ft=lua :
```

</details>


The file contains for example paths, languages, etc.

So we could:
- add default options value into the config (`feedback_enabled`)
- drop cmake keys
- change the option by debconf scenario (`false` - is default for Debian)

**Comment by Totktonada** [comment]
I vote for keeping the CMake option. Sooner or later I'll use it to exclude the feedback daemon code from the executable on Gentoo instead [hacking with sed](https://github.com/tarantool/gentoo-overlay/blob/e65412a61f0850f9f7c2de0849a826787523777a/dev-db/tarantool/tarantool-9999.ebuild#L108-L128). As the maintainer of the Gentoo overlay I insist on excluding this code at all from the executable if a user don't set the `feedback-daemon` USE flag explicitly.

Anyway, it does not block the runtime option in any way. I guess we should discuss the runtime option in #6395.

In brief, the `/etc/{sysconfig,default}/tarantool` is interpreted by tarantoolctl. It is not clear how to better interpret it from a 'pure' tarantool. However it seems doable and I would appreciate reusing of the same configuration. We should discuss what exactly we'll interpret in the 'pure' tarantool (e.g. whether to follow `*_dir` options instead of current cwd default — it is the breaking change).
