### ISSUE TITLE
Remove key_def_new_with_parts from exports

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#3311]
It is follow up of #3310, that is needed for support spaces with collations and nullable fields in tarantool/shard. It is better to remove the function from exports after implementing #3276 (now on 1.10.1, maybe need to be moved to 1.9) and appropriate tarantool/shard update, to keep recent shard being compatible with recent tarantool 1.9.

**Comment by locker** [comment]
Fixed by fbd80f706ee092de7e69830c3db17f9f17bbaeac

**Comment by Totktonada** [comment]
NB: The function was added in [1.9.0-72-g7d089bbdf](https://github.com/tarantool/tarantool/commit/7d089bbdf0366f043a377a7f351da82952f6c8c5) and removed in [1.10.1-390-gfbd80f706](https://github.com/tarantool/tarantool/commit/fbd80f706ee092de7e69830c3db17f9f17bbaeac).
