### ISSUE TITLE
iproto: greetings space shortage

### ISSUE THREAD

**Issue by alg1973** [tarantool/tarantool#3312]
Greetings packet size contains 128 bytes of data with 63 bytes for first line. eg

> 'Tarantool 1.10.0 (Binary) 3ba1962e-d70a-4111-9e95-61e7b840fcd5 '

So with version 10.10.10 we'll get UUID truncated by one byte.

**Comment by kyukhin** [comment]
It's a known limitation. We will not fix until it breaks.
