### ISSUE TITLE
sql: convert to Tarantool coding style

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#3315]
See `src/box/sql/sqliteInt.h`. The new prefix can be `SQL_`, for example.

**Comment by Korablev77** [comment]
Moreover, some of them SQLite specific and can be removed (alongside with code which uses it).

**Comment by kostja** [comment]
The branch is obsolete, as is the ticket.

**Comment by kyukhin** [comment]
Done by 73e85ae
