### ISSUE TITLE
unclear docs about net_box.connect() options and observed behaviour

### ISSUE THREAD

**Issue by ctpo6** [tarantool/tarantool#3338]
Tarantool 2.0.4-291-gcd99ba3

Наблюдаемые таймауты коннекта не согласуются с текущей документацией (читаю 2.0).
На приведенных ниже примерах видно, что:
1) Опции wait_connected, connect_timeout при отсутствии опции reconnect_after не оказывают вообще никакого влияния на таймаут получения ответа от connect() при неудачной попытке.
2) При наличии опции reconnect_after время получения ответа равно сумме wait_connected + 
connect_timeout, что вообще никак не отражено в документации. 

btw, является ли такое поведение нормальным или это баг?

Помимо внесения правок в документацию, непосредственно связанных с 1) 2), хочется иметь рекомендумеые значения этих 3 параметров. В документации приведен reconnect_after=5. Можно ли сделать 1? 0.5? 0.1? Связанные с этим накладные расходы? Как должны соотноситься значения всех 3 параметров между собой?

```
tarantool> t0 = fiber.time(); cn = nb.connect("127.0.0.1:9301", {wait_connected = 1.5, connect_timeout = 1}); print(fiber.time() - t0)
1.0001184940338
---
...

tarantool> t0 = fiber.time(); cn = nb.connect("127.0.0.1:9301", {wait_connected = 1.5, connect_timeout = 2}); print(fiber.time() - t0)
1.0226445198059
---
...

tarantool> cn
---
- opts:
    wait_connected: 1.5
    connect_timeout: 2
  host: 127.0.0.1
  state: error
  error: Connection refused
  port: '9301'
...

tarantool> t0 = fiber.time(); cn = nb.connect("127.0.0.1:9301", {wait_connected = 1.5, connect_timeout = 2, reconnect_after=5}); print(fiber.time() - t0)
2.5210826396942
```

**Comment by ctpo6** [comment]
Не являются ли опции wait_connected и connect_timeout дублирующими? Если я выставлю wait_connected=false, connect_timeout=1, то ответ получу все равно через 1 секунду.

**Comment by kyukhin** [comment]
Moved to doc repo: https://github.com/tarantool/doc/issues/560
