### ISSUE TITLE
Does SQL support 'ALTER TABLE ' syntax ,I want to change my SQL table structure.

### ISSUE THREAD

**Issue by zlinwei** [tarantool/tarantool#3347]
like this:
ALTER TABLE test_table ADD COLUMN TEST_ADD VARCHAR(32);
I want to add a column of the table, but i got an error:'error: 'near "ADD": syntax error'
How could I change my table's structure?

**Comment by Korablev77** [comment]
Hello. Unfortunately, now the only ALTER you are able to do via SQL is RENAME. Someday we are going to support other features of ALTER: #3075, #3097.

**Comment by zlinwei** [comment]
Oh, Thanks for your help.

**Comment by kyukhin** [comment]
Closing.
