### ISSUE TITLE
error: Can't modify data because this instance is in read-only mode.

### ISSUE THREAD

**Issue by zlinwei** [tarantool/tarantool#3355]
My config:

box.cfg {
    listen = 3301,
    -- pid_file = "./db_server.pid",
    replication = {'replicator:replicator@192.168.20.30:3301',  -- master URI
                   'replicator:replicator@192.168.20.30:3302'}, -- replica URI
    read_only = false
}

the other one is listen in 3302;
the first instance has old data. but the another is empty;

but when I insert data, I got the error. 

How could I replica a instance when it was not empty. 
Thanks.

**Comment by Gerold103** [comment]
As far as I know, you should not write replica uri in `replication` on master. It is enough to set `replication` on a slave. @kbelyavs please comment.

**Comment by kbelyavs** [comment]
@zlinwei, could you please provide more details, if you remove replica's URI from replication as @Gerold103 suggests, will it help you?
If not, please provide more details, like type box.info in master's console
and where did you insert data, then you got this error, on mater?

**Comment by zlinwei** [comment]
Thanks for your help. I am trying.

**Comment by zlinwei** [comment]
It works. Thanks again.
