### ISSUE TITLE
Configuration option to enable/disable vinyl

### ISSUE THREAD

**Issue by zloidemon** [tarantool/tarantool#3356]
I actually not use vinyl and want to disable to all my instances. By default i see vylog on start tarantool and did a kugle to save vinyl data at tmpfs partition to resolve issue.

**Comment by kyukhin** [comment]
Could you pls explain the issue w/ more details?

**Comment by Totktonada** [comment]
I guess it was resolved by [1.7.5-103-g114f04030](https://github.com/tarantool/tarantool/commit/114f0403087fcd5e5f3d177d9a54004dad1a2a9d). Feel free to reopen with more information if your problem still exists.
