### ISSUE TITLE
base64_encode nearly always urlsafe

### ISSUE THREAD

**Issue by SWSAmor** [tarantool/tarantool#3358]
For me the base64_encode make urlsafe in these cases:
`{nopad=true}`
`{nowrap=true}`
`{nopad=true, urlsafe=false}`
`{nowrap=true, urlsafe=false}`

I use tarantool 1.9.0.71

**Comment by Gerold103** [comment]
Can you provide a concrete test case?

**Comment by SWSAmor** [comment]
Sure, here is:
> (digest.base64_encode(p)):
Jqemi+MWV/Ux+ou4z3VqOZ8uXQbysS7PMYRywIKrOPT0SH/Ss69G1vHEYAw4vREjUnxZ19j/
gO5VUpL/f8kwpkjtUEGKRCflv2N84xZMtN1pFfeHzqkgf53TncBKp3VJ

> (digest.base64_encode(p, {urlsafe=true})):
Jqemi-MWV_Ux-ou4z3VqOZ8uXQbysS7PMYRywIKrOPT0SH_Ss69G1vHEYAw4vREjUnxZ19j_gO5VUpL_f8kwpkjtUEGKRCflv2N84xZMtN1pFfeHzqkgf53TncBKp3VJ

> (digest.base64_encode(p, {nopad=true})):
Jqemi-MWV_Ux-ou4z3VqOZ8uXQbysS7PMYRywIKrOPT0SH_Ss69G1vHEYAw4vREjUnxZ19j_
gO5VUpL_f8kwpkjtUEGKRCflv2N84xZMtN1pFfeHzqkgf53TncBKp3VJ

> (digest.base64_encode(p, {nowrap=true})):
Jqemi-MWV_Ux-ou4z3VqOZ8uXQbysS7PMYRywIKrOPT0SH_Ss69G1vHEYAw4vREjUnxZ19j_gO5VUpL_f8kwpkjtUEGKRCflv2N84xZMtN1pFfeHzqkgf53TncBKp3VJ

> (digest.base64_encode(p, {nopad=true, urlsafe=false})):
Jqemi-MWV_Ux-ou4z3VqOZ8uXQbysS7PMYRywIKrOPT0SH_Ss69G1vHEYAw4vREjUnxZ19j_
gO5VUpL_f8kwpkjtUEGKRCflv2N84xZMtN1pFfeHzqkgf53TncBKp3VJ

> (digest.base64_encode(p, {nowrap=true, urlsafe=false})):
Jqemi-MWV_Ux-ou4z3VqOZ8uXQbysS7PMYRywIKrOPT0SH_Ss69G1vHEYAw4vREjUnxZ19j_gO5VUpL_f8kwpkjtUEGKRCflv2N84xZMtN1pFfeHzqkgf53TncBKp3VJ

**Comment by Gerold103** [comment]
What is 'p'?

**Comment by bigbes** [comment]
Whats wrong with this?

**Comment by Gerold103** [comment]
I found I bug in base64.c:
```C
if ((options & BASE64_URLSAFE) != 0)
		encoding = urlsafe_encoding;
	else
		encoding = default_encoding;
```
Here must be another check: `if ((options & BASE64_URLSAFE) == BASE64_URLSAFE)`, because `BASE64_URLSAFE` consists of several bits.
