### ISSUE TITLE
sql: use Tarantool's structs for metadata during query compilation

### ISSUE THREAD

**Issue by Korablev77** [tarantool/tarantool#3369]
Currently, there are several cases when struct Table/Index is used only to hold metadata (such as table's name, number of fields etc) during compilation time. Thus, there is no real corresponding struct space for it. In order to merge data dictionaries, it is required to use struct space instead of struct Table. For instance, such instances of struct Table/Index are used to represent metadata concerning views (this point will be covered with #3368), result set of nested selects, result set of joins etc (see src/box/sql/where.c and src/box/sql/select.c).

It is worth mentioning, that within #3272 issue, space_def has been moved to struct Table. So now, it is possible not to substitute struct Table, but use space_def from it.

**Comment by SudoBobo** [comment]
After verbal discussion we decided to expand ticket scope; now it includes fixing `*Table->someProperty` -> `*Table->def->someProperty` in both select.c and where.c
Also it includes the same change with `Index` and `index_def`

**Comment by SudoBobo** [comment]
In [branch](https://github.com/tarantool/tarantool/tree/gh-3272-no-sql-names)  related to #3272 usage of `Table->space_def` for metadata in select.c and where.c is implemented. Also in this branch all usages of `Table->some_property` in select.c and where.c are fixed to `Table->def->some_property`
