### ISSUE TITLE
Stored function namespaces

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#3371]
Now on each stored function a separate grant must be done to allow a user to call the function. For example, if I have 3 function and 3 users, I must do 9 grants to allow each user call each function.

I propose to introduce function namespaces, and allow to grant call rights on entire namespace. For example, I have an appilcation `my_app` with functions `get`, `put`, `delete`, and application `http_app` with functions `get`, `post`, `head`:
```Lua
-- my_app.lua
local function get()
-- ...
end
local function put()
-- ...
end
local function delete()
-- ...
end
```

```Lua
-- http_app.lua
local function get()
-- ...
end
local function post()
-- ...
end
local function head()
-- ...
end
```

I want to be able to grant rights on entire `my_app`:

```Lua
-- main.lua
my_app = require('my_app')
http_app = require('http_app')
box.schema.func.create('my_app.get')
box.schema.func.create('my_app.put')
box.schema.func.create('my_app.delete')
box.schema.func.create('http_app.get')
box.schema.func.create('http_app.post')
box.schema.func.create('http_app.head')

box.schema.user.grant('guest', 'execute', 'namespace', 'my_app')
box.schema.user.grant('guest', 'execute', 'namespace', 'http_app')
```

**Comment by kyukhin** [comment]
To me, this looks like role feature as well.

**Comment by Gerold103** [comment]
You are right, ok. The feature is redundant.
