### ISSUE TITLE
iproto: result set also needs unambiguous column name in ODBC API

### ISSUE THREAD

**Issue by alg1973** [tarantool/tarantool#3376]
Since in the result set of the select statement column names  aren't sometimes distinguishable  ("select m.a,n.a from m,n" or due to aliases)  we need here table name and original column name so please add  this fields to SQL_INFO map as a result of original  sqlite3_column_table_name() and sqlite3_column_original_name() 
This is continuation of https://github.com/tarantool/tarantool/issues/3373

This is that ODBC clients expect to get about result set https://docs.microsoft.com/ru-ru/sql/odbc/reference/syntax/sqlcolattribute-function?view=sql-server-2017

**Comment by Gerold103** [comment]
Duplicate of this #2620

**Comment by kyukhin** [comment]
Duplicate.
