### ISSUE TITLE
ctl: unknown option --local

### ISSUE THREAD

**Issue by aleclarson** [tarantool/tarantool#3377]
```
$ tarantoolctl rocks install lulpeg --local
builtin/internal.argparse.lua:142: unknown options: local
```

The workaround is adding `local_by_default = true` to `~/.luarocks/config.lua`

**Comment by bigbes** [comment]
but `tarantoolctl rocks install` installs into `./.rocks` by default

**Comment by aleclarson** [comment]
strangely, it's not doing that for me, but I'm using a local build, so that probably has something to do with it

**Comment by aleclarson** [comment]
strangely, it's not doing that for me, but I'm using a local build, so that probably has something to do with it.

can you point me to where it does that?
