### ISSUE TITLE
Explicit checking of tnt process being restarted in tarantoolctl

### ISSUE THREAD

**Issue by fsitedev** [tarantool/tarantool#3384]
Currently if tnt running long not yielding fiber code we can't normally restart it with tarantoolctl.
That is because of restart function making only 1 second sleep without explicit  process existence checking:
```
local function restart()
    local stat = check_file(instance_path)
    if stat ~= nil then
        log.error("Error while checking syntax: halting")
        return 1
    end
    stop()
    fiber.sleep(1)
    start()
    return 0
end
```

**Comment by kostja** [comment]
TARANTOOL_RESTARTED environment variable is set during restart in 1.10
