### ISSUE TITLE
Allow to get a first utf-8 character of a string in lua using built-in libicu

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#3385]
Now it is possible to do it using lua-utf8. There are two alternatives:

Implement `sub`-like method. The example on lua-utf8:

```
local utf8 = require('lua-utf8')
print(utf8.sub('абвгде', 1, 1))
```

Implement by-char iterator like the following in lua-utf8:

```
for _, char_num in utf8.next, str do
    local c = utf8.char(char_num)
    …
end
```

We can get a first char using such iterator like so: `print(utf8.char(select(2, utf8.next('абвгде'))))`.

I described my specific case above (get a first char), but it can be generalized in some appropriave way.

**Comment by Gerold103** [comment]
Blocked by #3081 and #3290.
