### ISSUE TITLE
Segmentation fault(error message requests create issue)

### ISSUE THREAD

**Issue by vvzvlad** [tarantool/tarantool#3386]
I do not know if there is a need for it, but issure has created.

> 2018-04-27 15:31:42.551 [59794] main/101/smart_sity_local.lua C> Tarantool 1.9.0-0-g14d33e3
> 2018-04-27 15:31:42.551 [59794] main/101/smart_sity_local.lua C> log level 4
> 2018-04-27 15:31:42.629 [59794] main C> entering the event loop
> Segmentation fault
>   code: SEGV_MAPERR
>   addr: 0x73655f6972a5
>   context: 0x11081fd08
>   siginfo: 0x11081fca0
> Current time: 1524832319
> Please file a bug at http://github.com/tarantool/tarantool/issues
> Attempting backtrace... Note: since the server has already crashed, 
> this may fail as well
> #0  0x10e19ad41 in print_backtrace+9
> #1  0x10e0f8603 in _ZL12sig_fatal_cbiP9__siginfoPv+158
> #2  0x7fff756f9f5a in _sigtramp+1a
> #3  0x10e1becb3 in lua_rawgeti+20
> #4  0x1105b141d in mosq_message_f+1d
> #5  0x1105bb934 in _mosquitto_handle_publish+1b8
> #6  0x1105bb46f in _mosquitto_packet_read+9a
> #7  0x1105b9b1f in mosquitto_loop_read+82
> #8  0x1105b1208 in mosq_io_run_one+98
> #9  0x10e1af665 in lj_BC_FUNCC+44
> #10 0x10e1bf663 in lua_pcall+96
> #11 0x10e18ddc8 in luaT_call+13
> #12 0x10e18a407 in lua_fiber_run_f+66
> #13 0x10e0f821c in _ZL16fiber_cxx_invokePFiP13__va_list_tagES0_+c
> #14 0x10e198efb in fiber_loop+2a
> #15 0x10e2add67 in coro_init+4b
> Abort trap: 6
>

**Comment by kyukhin** [comment]
Hello, do you have a test case?

**Comment by kyukhin** [comment]
No test case for two months. Consider resolved.
