### ISSUE TITLE
Never keep a dead replica around if running out of disk space

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#3397]
Currently garbage collection daemon will keep xlogs for a  dead replica forever. This can easily eat up entire disk space on the master, eventually crippling the master.
This is a regression compared to 1.6 behavior, and, what's more important, is completely useless.
We should keep old logs around for a dead replica, but not until it begins to harm the master.

How to fix: 
- when re-opening an xlog file, posix_fallocate() previous xlog-file size / 2 but min 10mb; 
  posix_fallocate() can be done in the thread pool
- if posix_fallocate() fails, warn in the log file, raise a status in box.info and signal the garbage collector to kill off all dead replicas

**Comment by kbelyavs** [comment]
Neither posix_fallocate() nor fallocate() exists on OSX. May be we can check available space periodically (say every 1min) or based on written data?

**Comment by locker** [comment]
Fixed by 8a1bdc8263e9ff0550e257e088f767ca3f998f0e
