### ISSUE TITLE
sql.exequte arg substitution (parameter binding)

### ISSUE THREAD

**Issue by Khatskevich** [tarantool/tarantool#3401]
While perf measuring I found out that It is impossible to bind parameters in `sql` query from `Lua` as it is implemented in `iproto`.
```
cn:execute('select ?, ?, ?, ?, ?', {'abc', -123.456, msgpack.NULL, true, false})
```
This is an important feature because `Lua` concatenates strings very slowly.

**Comment by Totktonada** [comment]
Now cherry-picked to 2.1 too (it seems it was not made before due to a mistake).
