### ISSUE TITLE
Operation space:truncate() increases schema_version

### ISSUE THREAD

**Issue by ivankosenko** [tarantool/tarantool#3414]
Old implementation of space:truncate() did space recreation with changing space.id. So increase of schema_version was necessary. Now space:truncate() does not change space.id, but schema_version is still increasing. Maybe this should be fixed.

**Comment by Gerold103** [comment]
( Kostja has allowed me to assign the milestone ).

**Comment by Gerold103** [comment]
Can be linked with https://github.com/tarantool/tarantool/issues/1157.

**Comment by Gerold103** [comment]
We have decided to create a second schema version for internal usage, that grows faster than public one.
