### ISSUE TITLE
Crash on Fedora 28, tarantool 1.9.1-6-g35db70fac

### ISSUE THREAD

**Issue by lenkis** [tarantool/tarantool#3418]
(Initially reported by mistake to tarantool/doc repo as https://github.com/tarantool/doc/issues/524, by https://github.com/kmansoft)

tarantool --version

```
Tarantool 1.9.1-6-g35db70fac
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_BACKTRACE=ON
Compiler: /usr/bin/cc /usr/bin/c++
C_FLAGS:-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -m64 -mtune=generic -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -fno-gnu89-inline
CXX_FLAGS:-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches  -m64 -mtune=generic -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof
```

No crash.

The system is Fedora 28 with testing-updates

$ uname -a
Linux fiona 4.16.9-300.fc28.x86_64 #1 SMP Thu May 17 06:39:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Running a lua file with tarantool also works.

Now:

Just running "tarantool" (with no switches or source file) crashes, core dump:

```
$ tarantool
Tarantool 1.9.1-6-g35db70fac
type 'help' for interactive help
Segmentation fault (core dumped)
```

So maybe it crashes when trying to go into an interactive loop.

Stack trace:

```
$ coredumpctl gdb
           PID: 2073 (tarantool)
           UID: 1000 (kman)
           GID: 1000 (kman)
        Signal: 11 (SEGV)
     Timestamp: Sat 2018-05-19 19:36:03 MSK (16s ago)
  Command Line: tarantool
    Executable: /usr/bin/tarantool
 Control Group: /user.slice/user-1000.slice/session-2.scope
          Unit: session-2.scope
         Slice: user-1000.slice
       Session: 2
     Owner UID: 1000 (kman)
       Boot ID: 62d6f7b3fd094206aee004e118ce300e
    Machine ID: 8c8ee2146deb4a939a0024afb69bbbf7
      Hostname: fiona
       Storage: /var/lib/systemd/coredump/core.tarantool.1000.62d6f7b3fd094206aee004e118ce300e.2073.1526747763000000.lz4
       Message: Process 2073 (tarantool) of user 1000 dumped core.
                
                Stack trace of thread 2073:
                #0  0x00007f9d43614e95 n/a (libtinfo.so.6)
                #1  0x00007f9d43615317 n/a (libtinfo.so.6)
                #2  0x00007f9d43615435 _nc_read_entry2 (libtinfo.so.6)
                #3  0x00007f9d4360e026 _nc_setup_tinfo (libtinfo.so.6)
                #4  0x00007f9d4360e393 _nc_setupterm (libtinfo.so.6)
                #5  0x00007f9d4360e897 tgetent_sp (libtinfo.so.6)
                #6  0x00007f9d43a819bc _rl_init_terminal_io (libreadline.so.7)
                #7  0x00007f9d43a68c89 rl_initialize (libreadline.so.7)
                #8  0x00007f9d43a809c9 _rl_callback_newline (libreadline.so.7)
                #9  0x00000000004b7815 lbox_console_readline (tarantool)
                #10 0x00000000004f1cb7 lj_BC_FUNCC (tarantool)
                #11 0x0000000000503574 lua_pcall (tarantool)
                #12 0x00000000004cb4e1 luaT_call (tarantool)
                #13 0x00000000004c5509 lua_main (tarantool)
                #14 0x00000000004c57df run_script_f (tarantool)
                #15 0x000000000040e46c fiber_cxx_invoke (tarantool)
                #16 0x00000000004d9880 fiber_loop (tarantool)
                #17 0x000000000060566f coro_init (tarantool)
```
libtinfo comes from:

ncurses-libs-6.1-5.20180224.fc28.x86_64

libreadline comes from:

readline-7.0-10.fc28.x86_64

```
$ ldd /usr/bin/tarantool
	linux-vdso.so.1 (0x00007ffcda517000)
	libicui18n.so.57 => /lib64/libicui18n.so.57 (0x00007f2c85dc3000)
	libicuuc.so.57 => /lib64/libicuuc.so.57 (0x00007f2c85a15000)
	libyaml-0.so.2 => /lib64/libyaml-0.so.2 (0x00007f2c857f5000)
	libreadline.so.7 => /lib64/libreadline.so.7 (0x00007f2c855a8000)
	libncurses.so.6 => /lib64/libncurses.so.6 (0x00007f2c8537f000)
	libtinfo.so.6 => /lib64/libtinfo.so.6 (0x00007f2c85152000)
...
```

**Comment by kshcherbatov** [comment]
Tarantool has been crashing when trying to go into an
interactive loop in ncurses-libs/libtinfo library via
lbox_console_readline.
Ncurses on Fedora 28 is compiled with flag
--fstack-clash-protection that use stack protection
mechanism (strictly speaking configure option --enable-widec
is also required, but it is not a part of problem we
investigated): gcc inserting code to step the stack down
one page at a time, running a logical-OR with zero
at each point, which doesn't affect any value on the stack
but forces a memory access:
```
     lea r11,[rsp-frameSize]
 label:
     sub rsp,pageSize
     or QWORD PTR [rsp],0x0
     cmp rsp,r11
     jne label
```
where frameSize=32768 b and pageSize=4096 b
(read also https://ldpreload.com/blog/stack-smashes-you)

Tarantool main interactive loop is working in fiber with
default stack size 65536 b
```
BINARY IMAGE MEMORY MAP:
_____________________________________________________

SECTION      ADDRESSES       COMMENT

DATA         0x0       ^
HEAP                   |
             0x0ec18   |  # < --fstack-clash-
                       |  #   protection check
STACK: @               |  #
       @     0x16c18   | $# < ncurses/readline
       @               | $    internals, access
       @               | $    syscall in wrapper
       @               | $
       @               | $
       @     0x1ffe0   | $  < frame0 -- LUA
             ....      |
             0xffff    |

+------+-----------------------------+-------------+
| SIGN | DESCRIPTION                 | TOTAL SIZE  |
+------+-----------------------------+-------------+
|  @   | stack area region; (fiber)  |   65536 b   |
+------+-----------------------------+-------------+
|  $   | user-space application stack|   37832 b   |
|      | memory usage                |             |
+------+-----------------------------+-------------+
|  #   | a memory that checked stack |   32768 b   |
|      | probing generated with      |             |
|      | --fstack-clash-protection   |             |
+------+-----------------------------+-------------+
_____________________________________________________
```
In other words, $ + # = 70600    >    65536 = @
and we have segfault:
```
SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_ACCERR, si_addr=}
SIGSEGV {si_signo=SIGSEGV, si_code=SI_KERNEL, si_addr=NULL}
```

**I suppose** to increase interactive console main loop fiber stack. This would fix problem reported as this bug. 
On attempt to create console fiber(with default stack size), fiber would fail; but would not crash tarantool.
```
tarantool> require('fiber').create(function() require('console').start() end)
```

We didn't have constructive discussion, and I have no constructive ideas that could resolve this problem systematically. Third-party libraries RPM compile flags are the part of distros and it could be reproduced in some other cases later.

@GeorgyKirichenko please, keep on this ticket discussion thread.

**Comment by cyrillos** [comment]
Guys, the real issue is not the page touching. But rather the fact that ncurses started to use 32K buffers since commit 1501ae2a13db0ffd2db8404c24aa5010a88ea91b (Mon Jan 22 01:39:40 2018 +0000)
```
@@ -94,7 +100,14 @@ extern "C" {
  * given implementation may exceed.
  */
 #define MAX_NAME_SIZE  512     /* maximum legal name field size (XSI:127) */
-#define MAX_ENTRY_SIZE 4096    /* maximum legal entry size */
+#define MAX_ENTRY_SIZE1        4096    /* maximum legal entry size (SVr2) */
+#define MAX_ENTRY_SIZE2        32768   /* maximum legal entry size (ncurses6.1) */
+
+#if NCURSES_EXT_COLORS && HAVE_INIT_EXTENDED_COLOR
+#define MAX_ENTRY_SIZE MAX_ENTRY_SIZE2
+#else
+#define MAX_ENTRY_SIZE MAX_ENTRY_SIZE1
+#endif
...
```

Now the callers

```
_nc_read_tic_entry
  char buffer[MAX_ENTRY_SIZE + 1];
  ...
  _nc_read_termtype
    char buf[MAX_ENTRY_SIZE + 2];
```
no wonder that it exceeds 65K stack. Page touching simply reveals the lack of stack early.

**Comment by kmansoft** [comment]
Can Tarantool make the default stack size larger if a recent readline version is detected (can it be done?) maybe with a documentation caveat that Fedora is not optimal for production.

But then all other distros will probably catch up (to newer readline) sooner or later, even the more popular for servers Debian and Ubuntu (and eventually CentOS and RHEL, in 10 years maybe...)

Looks like someone already attempted that, not sure if this change has been picked up:

https://github.com/tarantool/tarantool/commit/f2677cd964b23aa4ef09dbad660d42f206ce8ab3

PS:

I have a funny feeling :bowtie: why it was me who filed the crash originally:

https://github.com/tarantool/doc/issues/524

**Comment by locker** [comment]
> Can Tarantool make the default stack size larger if a recent readline version is detected (can it be done?) maybe with a documentation caveat that Fedora is not optimal for production.

It's not just about readline/ncurses. We have a similar issue with other third part libraries, e.g. libcurl. Increasing the stack unconditionally for all of them would bloat memory usage. We are planning to make stacks dynamically shrink and grow. In fact, we're already working in this direction.

**Comment by kmansoft** [comment]
> We are planning to make stacks dynamically shrink and grow. In fact, we're already working in this direction.

Ah OK thank you.

**Comment by locker** [comment]
> Will that be only in 2.0 / 2.1 series - or are there plans to backport to 1.10 (for example) or 1.11 whatever?

The milestone says it will be backported to 1.10.
