### ISSUE TITLE
Add test checking there is no memory leaks at shutdown

### ISSUE THREAD

**Issue by locker** [tarantool/tarantool#3419]
We need a test case to catch bugs like the one fixed by ab65724f4005821ef067709399bae72a9f23ac1b. It may be a simple unit test or we may use asan/valgrind instead. If we choose the latter, we will need to fix other memory leaks first, for which we will probably have to rework the shutdown procedure without `atexit`.

**Comment by Totktonada** [comment]
Note: lua_close() helps with curl_multi 'indirect leak' that ASAN reports even for `./src/tarantool <<< ''`. It was disabled (as part of tarantool_lua_free()) in a718d469100a2992707c16cd251a56e5e5159be2.

**Comment by locker** [comment]
This was done: we now have a CI workflow that runs tests with ASAN enabled.
