### ISSUE TITLE
Allow different nullability in indexes and format

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#3430]
Now it is allowed to declare different types on the same field in various indexes and in a format. The result format takes the strictest type for each field. Such behaviour allows to do incremental alter changing field type in each index and in a format step by step in different transaction. Actually it is a workaround for non-transactional DDL.

But it does not work when a user wants to alter `is_nullable`. Now it must be the same in all indexes and in a format for the same field. Workaround is to drop a space format and do the alter, but it is tricky.

**Comment by locker** [comment]
Fixed by 5b68c5f5b995e89cfc2e8846463c56ca80d64508
