### ISSUE TITLE
Module for dealing with dates and iso8601 format in general

### ISSUE THREAD

**Issue by knazarov** [tarantool/tarantool#3434]
We've picked up a module from community: 
https://github.com/tarantool/icu-date

It will be nice to have something like this in core, because date/time manipulations are ubiquitous

**Comment by racktear** [comment]
Also discussed in #2738

**Comment by racktear** [comment]
The only problem with icu-date is that it doesn't understand nanoseconds.

**Comment by olegrok** [comment]
After functional indexes was introduced I think we should return to discussion. Our customers want to operate with dates and times. So tarantool have libicu as dependency. I think we should adopt existing library (https://github.com/tarantool/icu-date) and get it as built-in module.

In the best case it should be drop&replace solution

**Comment by Mons** [comment]
Implemented datetime
