### ISSUE TITLE
[Question] Client library for Lua-embedding C/C++ applications?

### ISSUE THREAD

**Issue by nikki93** [tarantool/tarantool#3436]
Hi!

Tarantool looks really awesome! :) I am working with a game engine written in C/C++ that embeds Lua, hoping to write applications in Lua on top of it (the engine is love2d.org, and I've already managed to embed other C/C++ libraries like the 'ImGui' library). I was wondering if there was a straightforward way to embed Tarantool's C/C++ code along with the engine and expose it to the existing Lua runtime there so that I can connect to a remote Tarantool instance. The main usecase would be to persist user data. Interesting use cases could be to run Tarantool remotely writing some real-time application server logic in Lua and connect with that to implement something like a game server.

Not sure if this question makes sense at all given the current architecture / goals for Tarantool but figured I'd ask. :) If this place is only really for 'issues' and I should ask questions elsewhere please let me know!

Thanks!

**Comment by kyukhin** [comment]
Hello, feel free to ask all you questions in Telegram channel https://telegram.me/tarantool
