### ISSUE TITLE
Request context

### ISSUE THREAD

**Issue by knazarov** [tarantool/tarantool#3462]
It is a very typical pattern to store per-request information in `fiber.storage`, for instance, request ID. Request ID is used by code handling the request to log diagnostic messages together with the request ID. It is also typical to store in `fiber.storage` the user ID of the user who caused the request in the first place. Then the code somewhere in request handling pipeline may check for ACLs and decide to permit or reject the request.

The problem with current `fiber.storage` is that it's not cleaned after the fiber is returned to the fiber pool, thus making the cleanup a potentially dangerous place: if you forget to clean-up the context, the next request may potentially inherit the sate of previous request, thus leading to potentially strange results.

I propose to either fix the current behavior or introduce a concept of request context that will be cleaned after the request is completed and the fiber is returned to the fiber pool.

**Comment by Gerold103** [comment]
1. As far as I know, `fiber.storage` is cleaned up when the fiber is recycled. I have looked at the code of recycling - it nullifies the storage. Or do you have a test that it is wrong?
2. To get the user you can use `box.session.uid()`.
3. To get request id (sync) you can use `box.session.sync()` to store the value at the beginning of the request into a local variable. After #3450 will be fixed, you are able to use `box.session.sync()` directly with no saving its result.

**Comment by bigbes** [comment]
`fiber.storage` won't be nullified, since fibers aren't killed, but reused (https://github.com/tarantool/tarantool/issues/2901)

**Comment by sharonovd** [comment]
Regarding 2. - database user is interesting only rarely. More than often we are referring to app server user, authenticated by other means.
