### ISSUE TITLE
Corrupted representation of cyrillic symbols in logs

### ISSUE THREAD

**Issue by opomuc** [tarantool/tarantool#3470]
Tarantool HEAD 1b6cb4a (2.0)

Some examples:
`"data":{"individuals":[{"last_name":"Ð<98>Ð²Ð°Ð½Ð¾Ð²","first_name":"Ð<94>Ð¾Ð±Ñ<80>Ð¾Ð¶Ð¸Ñ<80>","individual_id":1},{"last_name":"Ð<98>Ð²Ð°Ð½Ð¾Ð²","first_name":"Ð<98>Ð²Ð°Ð½","individual_id":10},{"last_name":"Ð<98>Ð²Ð°Ð½Ñ<82>ÐµÐµÐ²","first_name":"Ð<9f>ÐµÑ<82>Ñ<80>","individual_id":11},{"last_name":"Ð<98>Ð²Ð°Ð½ÐºÐ¸Ð½","first_name":"Ð¡Ð¸Ð´Ð¾Ñ<80>","individual_id":12}]},"aux":{"hello":"hello Ð<98>Ð²Ð°Ð½Ð¾Ð²Ð<94>Ð¾Ð±Ñ<80>Ð¾Ð¶Ð¸Ñ<80>"}}`

`last_name/ВоЛоДин/first_name/ИГОРЬ/additional_name/сергеевич -> /last_name/Ð<92>Ð¾Ð<9b>Ð¾Ð<94>Ð¸Ð½/first_name/Ð<98>Ð<93>Ð<9e>Ð Ð¬/additional_name/Ñ<81>ÐµÑ<80>Ð³ÐµÐµÐ²Ð¸Ñ<87>`

**Comment by opomuc** [comment]
The problem persists if return to version 1.9. Meaning when two versions are present in system

**Comment by kyukhin** [comment]
We need a reproducer.

**Comment by kyukhin** [comment]
Two weeks w/o feedback. Consider solved.
