### ISSUE TITLE
Constraint definition errors create unwanted objects

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#3474]
If CREATE TABLE fails due to a constraint definition error,
something is still created, so the error cannot be fixed.
box.sql.execute("CREATE TABLE t99 (s1 INT,UNIQUE(s1,s1),PRIMARY KEY(s1));")
box.sql.execute("CREATE TABLE t99 (s1 INT,UNIQUE(s1),PRIMARY KEY(s1));")
Result = error in the first statement (good), error in the second statement (bad).

**Comment by kshcherbatov** [comment]
We have no transactional DDL, so let's keep this bug and make good documentation for this scenario.

**Comment by kshcherbatov** [comment]
Won't fix #3499
