### ISSUE TITLE
sql: remove tnum from struct Table and struct Index

### ISSUE THREAD

**Issue by Korablev77** [tarantool/tarantool#3482]
Since now we have `space_def` inside `struct Table` and `indef_def` inside `struct Index`, there is no need to encode/decode space and index ids into tnum.

**Comment by kyukhin** [comment]
This issue is so far blocked by review of https://github.com/tarantool/tarantool/tree/sb/gh-3369-use-index-def-in-select-and-where.
To remove `tnum` from `struct Index`, pointer to `struct index_def` should be put into `struct Index`
