### ISSUE TITLE
Configurable syslog destination

### ISSUE THREAD

**Issue by nikat** [tarantool/tarantool#3487]
Implement configuration option `server=` for syslog destination.

### Current implementation [[1]:](https://tarantool.io/en/doc/1.9/reference/configuration/#confval-log) 

The syntax is `syslog:` followed by an optional comma separated key=value list. The following keys are defined:
- `identity=...`
- `facility=...`

`/dev/log` is hardcoded as the only possible syslog destination.

https://github.com/tarantool/tarantool/blob/13f4355c5111285c7aecca30a960603eecdf298d/src/say.c#L477-L487

### Proposed implementation:

In addition to implemented options add a new one:
- `server=...` — syslog destination

For example:
- `syslog:server=unix:/var/log/tarantool.sock,identity=myinstance`
- `syslog:server=192.168.1.1:514,identity=tarantool_myinstance`

**Note:** related to #1043

**Note:** proposed configuration syntax is based on [[2](http://nginx.org/en/docs/syslog.html)]

**Comment by Mons** [comment]
+ for Mac default location should be /var/run/syslog if there is no /dev/log

**Comment by OKriw** [comment]
facility=... is not implemented too.

**Comment by locker** [comment]
Fixed by 6854ea19b0d50b741b3dad74f4cca9acd66e7c22
