### ISSUE TITLE
Coredump after connection close

### ISSUE THREAD

**Issue by rtokarev** [tarantool/tarantool#3488]
I have reproducible coredump test case.

\# /usr/local/bin/tarantool --version
Tarantool 1.9.1-29-g80d379e
Target: Linux-x86_64-Debug
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_BACKTRACE=ON
Compiler: /usr/lib64/ccache/cc /usr/bin/c++
C_FLAGS: -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -fno-gnu89-inline -Werror
CXX_FLAGS: -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Werror

backtrace:
#0  0x00007f03073f65e5 in *GI_raise (sig=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:64
#1  0x00007f03073f7dc5 in *__GI_abort () at abort.c:92
#2  0x00007f03073ef70e in __assert_fail_base (fmt=<optimized out>, assertion=0x6bf3d0 "fd >= 0", file=0x6bf298 "/home/rtokarev/repo/tarantool/src/box/iproto.cc", line=<optimized out>,
    function=<optimized out>) at assert.c:96
#3  0x00007f03073ef7d0 in *__GI___assert_fail (assertion=0x6bf3d0 "fd >= 0", file=0x6bf298 "/home/rtokarev/repo/tarantool/src/box/iproto.cc", line=659,
    function=0x6bfb00 <iproto_connection_on_input(ev_loop*, ev_io*, int)::__PRETTY_FUNCTION> "void iproto_connection_on_input(ev_loop*, ev_io*, int)") at assert.c:105
#4  0x000000000041040e in iproto_connection_on_input (loop=0x2a66ed0, watcher=0x7f02fb840ef8) at /home/rtokarev/repo/tarantool/src/box/iproto.cc:659
#5  0x00000000006b3b30 in ev_invoke_pending (loop=0x2a66ed0) at /home/rtokarev/repo/tarantool/third_party/libev/ev.c:3347
#6  0x00000000006b4a1e in ev_run (loop=0x2a66ed0, flags=0) at /home/rtokarev/repo/tarantool/third_party/libev/ev.c:3750
#7  0x00000000005012a4 in cord_costart_thread_func (arg=0x2a63550) at /home/rtokarev/repo/tarantool/src/fiber.c:1157
#8  0x00000000005005df in cord_thread_func (p=0x7f02fc81f900) at /home/rtokarev/repo/tarantool/src/fiber.c:958
#9  0x00007f0308555aa1 in start_thread (arg=0x7f02fc7ff700) at pthread_create.c:301
#10 0x00007f03074acaad in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:115

**Comment by kostja** [comment]
This was fixed in 1.10 and I cherry-picked a fix to 1.10 (gh-3400)
