### ISSUE TITLE
sql: ABORT and FAIL conflict actions inside transactions are broken

### ISSUE THREAD

**Issue by Hollow111** [tarantool/tarantool#3500]
[Description](https://github.com/tarantool/tarantool/wiki/SQL:-ON-CONFLICT-clause-for-INSERT,-UPDATE-statements) for these conflict actions:

**ABORT**. When an applicable constraint violation occurs, the ABORT resolution algorithm aborts the current SQL statement with an SQLITE_CONSTRAINT error and backs out any changes made by the current SQL statement; but changes caused by prior SQL statements within the same transaction are preserved and the transaction remains active. This is the default behavior and the behavior specified by the SQL standard.

**FAIL**. When an applicable constraint violation occurs, the FAIL resolution algorithm aborts the current SQL statement with an SQLITE_CONSTRAINT error. But the FAIL resolution does not back out prior changes of the SQL statement that failed nor does it end the transaction. Example below.

Reproduce for ABORT (The same as if the second stmt would be is 'INSERT OR ABORT'):
```
	CREATE TABLE t2(a INTEGER PRIMARY KEY, b INTEGER);
	BEGIN;
	INSERT INTO t2 VALUES (1, 1), (4, 4);
	INSERT INTO t2 VALUES (0, 0), (1, 2), (3, 3), (5, 5);  
	INSERT INTO t2 VALUES (10, 10);
	COMMIT;
	SELECT * FROM t2;
```
Expected: [1, 1], [4, 4], [10, 10]
Got: [1, 1], [4, 4]

Reproduce for FAIL:
```
	CREATE TABLE t2(a INTEGER PRIMARY KEY, b INTGER);
	BEGIN;
	INSERT INTO t2 VALUES (1, 1), (4, 4);
	INSERT OR FAIL INTO t2 VALUES (0, 0), (1, 2), (3, 3), (5, 5);  
	INSERT INTO t2 VALUES (10, 10);
	COMMIT;
	SELECT * FROM t2;
```
Expected: [0, 0], [1, 1], [4, 4], [10, 10]
Got: [0, 0], [1, 1], [4, 4]

Tarantool, Branch 2.0.

**Comment by Hollow111** [comment]
This wasn't actually an sql bug. I was testing these in sql-tester which breaks the test when it catches an exception. So it's just tester behavior thus issue isn't actual.

@kyukhin

**Comment by kyukhin** [comment]
Closing then.
