### ISSUE TITLE
Implement partial core dumps

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#3509]
Production Tarantool instance might consume huge amounts of memory,
making core dump real pain.

Consider light-weight dumping feature: do not dump memory occupied
by tuples.

GDB should handle such dumps perfectly.

**Comment by locker** [comment]
See madvise:MADV_DONTDUMP

**Comment by cyrillos** [comment]
As far as I see we shouldn't madvice each tuple but instead need to modify our "small" allocator to be madvice compatible.
