### ISSUE TITLE
string packing apparently is unreliable

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#351]
In Tarantool 1.5, I can pack a string and then unpack it,
even if the string is not the last thing that I pack. Example:
```
localhost> lua box.unpack('pi', box.pack('pi', 'String', 666))
---
 - String
 - 666
...
```
In Tarantool 1.6, as far as I can tell, the only pickle.pack|unpack
format specifier for "a sequence of bytes" is A.
But it doesn't seem to give a length-byte or a terminator:
```
tarantool> #pickle.pack('A','String')
---
- 6
...
```
This is okay if 'A' is at the end:
```
tarantool> pickle.unpack('sA',pickle.pack('sA', 666, 'String'))
---
- 666
- 'String'
...
```
But it is not okay if 'A' is not at the end:
```
tarantool> pickle.unpack('As',pickle.pack('As', 'String', 666))
---
- error: 'pickle.unpack(''s''): got 8 bytes (expected: 10+)'
...
```

**Comment by kostja** [comment]
Peter, no one seems to care - pack()/unpack() was useful only as part of the 1.5 binary protocol. The defect you've pointed out is "broken by design", and we will not redesign it in 1.5.
