### ISSUE TITLE
json: incorrect parsing of integers with exponent

### ISSUE THREAD

**Issue by opomuc** [tarantool/tarantool#3514]
From [RFC 7159](https://tools.ietf.org/html/rfc7159.html#section-6):

> The representation of numbers is similar to that used in most
   programming languages.  A number is represented in base 10 using
   decimal digits.  It contains an integer component that may be
   prefixed with an optional minus sign, which may be followed by a
   fraction part and/or an exponent part.  Leading zeros are not
   allowed.
   A fraction part is a decimal point followed by one or more digits.

From [json.org](http://www.json.org/):
![image](https://user-images.githubusercontent.com/8739816/42451222-4139c784-838f-11e8-8285-780f620e745c.png)

```
tarantool> json.decode('{"remained_amount":2.0e+3}')
---
- {'remained_amount': 2000}
...

tarantool> json.decode('{"remained_amount":2.0E+3}')
---
- {'remained_amount': 2000}
...

tarantool> json.decode('{"remained_amount":2e+3}')
---
- {'remained_amount': 2000}
...

tarantool> json.decode('{"remained_amount":2E+3}')
---
- error: Expected comma or object end but found invalid token at character 21
...
```

**Comment by kshcherbatov** [comment]
Although lua-сjson is in the third_party folder, it differs significantly from the possible upstream; has the form of a rethought and a simplified fragment. That's why we will make the required changes to our version.
