### ISSUE TITLE
Duplicate-key error with a char column containing digits

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#3515]
I have Ubuntu 14.04 and Tarantool 2.0, pulled from source today.

If I have a unique index on a column defined as CHAR,
then a certain kind of UPDATE (adding '0' before a digit)
fails (and it should not fail), saying "duplicate".
Then, if I drop the unique index, do the same update again,
and then create the unique index again, there is no error.
```
 DROP TABLE t1;
 CREATE TABLE t1(a INT PRIMARY KEY, b CHAR(5));
 CREATE UNIQUE INDEX i1 ON t1 (b);
 INSERT INTO t1 VALUES (0, '2');
 INSERT INTO t1 VALUES (1, '02');
 -- The following update will fail saying there's a duplicate in T1
 UPDATE t1 SET b =  '0' || b;
 DROP INDEX i1 ON t1;
 -- The following update will not fail
 UPDATE t1 SET b =  '0' || b;
 -- The following create will succeed
 CREATE UNIQUE INDEX i1 ON t1 (b);
```

**Comment by kyukhin** [comment]
@pgulutzan, I don't understand your concern.
Here's what I have after last update statement:
```
tarantool>  UPDATE t1 SET b =  '0' || b;
---
...
tarantool> SELECT * FROM t1;
---
- - [0, '02']
  - [1, '002']
...
tarantool>  CREATE UNIQUE INDEX i1 ON t1 (b);
---
...
```
What's wrong w/ creation of unique index here? Values are different...

**Comment by pgulutzan** [comment]
There is nothing wrong with CREATE UNIQUE INDEX, I
only added it to show that there is no duplicate.
The bug is not there, the bug is in the first UPDATE,
after the comment " -- The following update will fail
saying there's a duplicate in T1". That is wrong,
because there is no duplicate, so UPDATE should not fail.

However, I see now that my original theory is nonsense.
I thought that this is due to using numerics in a CHAR.
Wrong. It is merely a variant of this:
create table t2 (s1 int primary key);
insert into t2 values (1),(2);
update t2 set s1 = s1 + 1;
Result = duplicate-key error.
Probably there is already an old bug report about
that, although I don't see it. Perhaps you remember.

**Comment by kshcherbatov** [comment]
Technically this is equal to concept
``` 
transaction;
foreach tuple: tuple.b += 1;
commit;
```
where b is unique,
that isn't supported in tarantool. 
This problem was discussed with @kostja a month ago. I've returned to this problem today and believe this is the time to close this task.

Won't fix.
