### ISSUE TITLE
Check if transaction opened

### ISSUE THREAD

**Issue by dsamirov** [tarantool/tarantool#3518]
In Lua code I need an option to check if transaction is opened. If I have a function with `box.begin()`, `box.commit()` I can't call it inside another transaction because double `box.begin()` causes error.

**Comment by Totktonada** [comment]
```
local is_in_txn = not pcall(box.begin)
```

It surely did the work before 1.9.1-40-g131121c99 and I guess still works.

**Comment by dsamirov** [comment]
Yes. This lua code is fine for me. I close this issue.

**Comment by Gerold103** [comment]
@Totktonada such code opens a transaction if it was not opened before. I think, a check should not have any after-effects.

**Comment by Totktonada** [comment]
@Gerold103 Sure, one should close it then. But I’m agree that a ready to use function w/o side effects would be covenient.
