### ISSUE TITLE
The like() function is rejected because like is a reserved word

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#3523]
I have Ubuntu 14.04. I have Tarantool 2.0.4, pulled from source today.
If I say SELECT LIKE('a','a'); I get this error message:
error: keyword "LIKE" is reserved
If I say select "LIKE"('a','a'); I get no error message, it works.
Something similar happens with glob().

Of course, I don't see any reason to support like() or glob().
But it seems that a decision was made to support them, and
in that case they should not be rejected as regular identifiers
for functions.

**Comment by pgulutzan** [comment]
I suppose this no longer matters because issue#3572 "LIKE & GLOB operators" will remove like() and glob().

**Comment by Hollow111** [comment]
@pgulutzan will it? I can't find a word about removing function like(), only removing GLOB with related function glob().

**Comment by pgulutzan** [comment]
Oh. Then I'm sorry, I was mistaken. Anyway, I hope you solve this issue by removing support for LIKE().

**Comment by Totktonada** [comment]
LIKE is the standard operator, we are not going to remove it. GLOB was broken is some way and we decided to remove it now, but implement REGEXP instead in the future.

**Comment by Totktonada** [comment]
Ouch, I misread you message (I did read LIKE() as LIKE). Are you propose to don't fix the issue? Maybe I don't get the idea.

**Comment by Hollow111** [comment]
@Totktonada As far as I understood the suggestion is to delete built-in functions like "like()", "regexp()" as well as closing this issue.

**Comment by pgulutzan** [comment]
I am suggesting removing support for the LIKE() function, since I believe that is the easiest way to solve the problem that LIKE is a reserved word Of course, if somebody can point to a reason that users would want to use LIKE() instead of the LIKE operator, then fine, don't fix, and I'll document that they have to use quote marks.

**Comment by Korablev77** [comment]
Finally, we decided that fix doesn't worth the effort. So, let's simply consider this behaviour as a feature. @pgulutzan Could you document it?

**Comment by pgulutzan** [comment]
Okay, now the SQL manual says:
"LIKE"(string-expression-1, string-expression-2 [, string-expression-3])
           -- "LIKE"(a,b[,c]) -- notice the quote marks -- is equivalent to b LIKE a [ESCAPE c]
           Example: "LIKE('%Rain',The Rain') is 1 because it is true
