### ISSUE TITLE
Add support for "tarantoolctl rocks pack" subcommand

### ISSUE THREAD

**Issue by knazarov** [tarantool/tarantool#3525]
The "rocks pack" subcommand is available in luarocks (https://github.com/luarocks/luarocks/wiki/pack), but cannot be called via tarantoolctl CLI:

```sh
$ tarantoolctl rocks pack

Error: Unknown command: pack
```

Please add the corresponding subcommand to `tarantoolctl rocks`

**Comment by rosik** [comment]
Don't forget about `unpack`

**Comment by Totktonada** [comment]
It was closed by PR #3586 in 1.10.1-236-g0746fdb4a.
