### ISSUE TITLE
Statically link with libstdc++ by default

### ISSUE THREAD

**Issue by racktear** [tarantool/tarantool#3526]
Currently as far as I understand, we depend on libstdc++ only to support exceptions in certain places. It will be nice to remove libstdc++ as a runtime dependency, by statically linking with it by default.

**Comment by kyukhin** [comment]
@kostja AFAIK, we're going to remove exceptions completely from Tarantool sources.
If so this issue is void, if not - it is makes sense.

**Comment by kyukhin** [comment]
I've asked privately.
We're about to remove dependency on libstdc++ at all in next release.
So, superseded by #3532
