### ISSUE TITLE
Assertion if guest makes default for-each-row trigger affecting nonexistent table

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#3535]
I have Ubuntu 14.04. I have Tarantool 2.0.4, pulled from source today.
I have two shells.

On the first shell, which I start with tarantool/src/tarantool, I say:
box.cfg{listen=3301}
box.schema.user.grant('guest','read,write,execute','universe')

On the second shell, which I start with tarantoolctl connect 3301, I say:
box.sql.execute("create table t2 (s1 int primary key);")
box.sql.execute("create trigger t2 before insert on t2 begin delete from t1; end;")
box.sql.execute("insert into t2 values (0);")

Result:
/home/pgulutzan/tarantool-2.0/src/box/sql/vdbe.c:4872: sqlite3VdbeExec: Assertion `nMem>0' failed.
Aborted (core dumped)

**Comment by kshcherbatov** [comment]
Came with @kyukhin path

commit #378658a567edaf5262b1f69cf18033a7a915e700
Author: Kirill Yukhin <kyukhin@tarantool.org>
Date:   Fri May 18 16:31:24 2018 +0300

    sql: refactor SQL delete to allow Lua spaces
    
    This is a first step toward fully-featured deletion
    of spaces created in Lua by means of SQL language.
    This change to handle most simple case:
    DELETE * FROM <space_name> and will be improved in
    nearest future.
    Also, refactor (sqlite3ViewGetColumnNames()) to
    use Tarantool's code style and naming convention.
    
    Part of #3235

**Comment by kshcherbatov** [comment]
This bug is not about netbox and grants,
```
box.sql.execute("create table t2 (s1 int primary key);")
box.sql.execute("create trigger t2 before insert on t2 begin delete from t1; end;")
box.sql.execute("insert into t2 values (0);")
```
is all you need to reproduce

**Comment by kshcherbatov** [comment]
The problem is following:
trigger contains "delete from t1" part that was changed with 378658a567edaf5262b1f69cf18033a7a915e700 patch.
Previously on code generation step sqlite3LocateTable used to set Parser error on target table not exists. Now it doesn't raise error at all.

```
-- table t1 doesn't exist
 delete from t1;
---
...
```

```
sql_table_delete_from:

if (sqlite3LocateTable(parse, LOCATE_NOERR, tab_name) == NULL) {
		space_id = box_space_id_by_name(tab_name,
						strlen(tab_name));
		if (space_id == BOX_ID_NIL)
			goto delete_from_cleanup;
	} else {
		table = sql_list_lookup_table(parse, tab_list);
		if (table == NULL)
			goto delete_from_cleanup;
		space_id = SQLITE_PAGENO_TO_SPACEID(table->tnum);
		trigger_list =sqlite3TriggersExist(table, TK_DELETE,
						   NULL, NULL);
		is_complex = trigger_list != NULL ||
			     sqlite3FkRequired(table, NULL);
	}
```

It looks like it was made specially.
@kyukhin ?
