### ISSUE TITLE
Some triggers cause error messages and/or half-finished updates

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#3536]
I have Ubuntu 14.04. I have Tarantool 2.0.4, pulled from source today.

I execute these requests:
box.cfg{}
box.sql.execute("drop view v;")
box.sql.execute("drop table t;")
box.sql.execute("drop view v;")
box.sql.execute("CREATE TABLE t (s1 INT, s2 INT, s3 INT, s4 INT PRIMARY KEY);")
box.sql.execute("CREATE VIEW v AS SELECT s1, s2 FROM t;")
box.sql.execute("CREATE TRIGGER tv INSTEAD OF UPDATE ON v BEGIN UPDATE t SET s3 = new.s1 WHERE s1 = old.s1; END;")
box.sql.execute("INSERT INTO t VALUES (1,1,1,1);")
box.sql.execute("UPDATE v SET s2 = s1 + 1;")
box.sql.execute("UPDATE v SET s1 = s1 + 5;")
box.sql.execute("SELECT * FROM t;")

For both UPDATE statements, I see this error message:
* 2018-07-15 14:15:01.380 [15651] main/101/interactive space.h:250 E> ER_NO_SUCH_INDEX: No index #0 is defined in space 'V'
I don't understand the message, I believe I made the trigger correctly.

For the SELECT statement, I see this result:
"
tarantool> box.sql.execute("SELECT * FROM t;")
---
- - [1, 1, 6, 1]
...
"
I don't understand the result, it seems that the first UPDATE failed completely
and the second UPDATE didn't change the s1 column but did change the s3 column.

**Comment by kshcherbatov** [comment]
This message start being shown since @Korablev77 patch.
This is not an answer what the problem is (yet).

commit 4cbba96f32e1b1ae578ac4aefec7c5cf4dfe26a4
Author: Nikita Pettik <korablev@tarantool.org>
Date:   Thu Feb 8 02:54:47 2018 +0300

    sql: delegate SQL primary key check to Tarantool
    
    As last point of removing colflag attribute from struct Column,
    table_column_is_primkey() function is added. It checks via Tarantool
    facilities whether column belongs to PK or not (after space creation).
    However, during initializing of SQL iternals and before actual creation
    of struct space, colflag attribute (as indicator of PK) still can be used.
    Since this is the only purpose of attribute, one has been renamed.
    
    Closes #3118
