### ISSUE TITLE
yaml incorrectly escapes special characters in a string

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#354]
tarantool> box.space.Q:insert{[[a\t ]]}
     ---
     - ['a\t ']
     ...

   
    tarantool> box.space.Q:insert{'a\t '}
    ---
    - ["a\t "]
     ...

As you can see in both cases \t is printed as is, even though in the first case it's two characters ('\' and 't') and in the second case it's a single character (tab)

**Comment by rtsisyk** [comment]
Need to port this logic: https://bitbucket.org/xi/pyyaml/src/ddf211a41bb231c365fece5599b7e484e6dc33fc/lib/yaml/emitter.py?at=default#cl-645

**Comment by rtsisyk** [comment]
```
tarantool> t = box.tuple.new("\x08\x5c\xc2\x80\x12\x2f")
---
...

tarantool> t
---
- ["\b\\\x80\x12/"]
...
```

'\x5c' is missing

**Comment by mejedi** [comment]
Actually, `\xc2` is missing, this is probably because `utf8('\x80') == '\xc2\x80'`. Libyaml has a so called 'Unicode' mode which is active by default, will look into it.
