### ISSUE TITLE
sql: LIKE/LENGTH do not scan if '\0' is encountered

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#3542]
String functions LIKE(), and LENGTH() stop when
'\0' exists in the input, if data type = text.
This is not supposed to be an end-of-string signal in SQL.
```
box.sql.execute("VALUES (GLOB(CHAR(65,00,65),'A'), LENGTH(CHAR(65,00,65)));")
````
Result: [1, 1]

This is a part of #2347

**Comment by Hollow111** [comment]
I guess, we will need to implement some sort of entity that stores string length or replace end-of-string trigger-symbol from `\0` by some other.

**Comment by Totktonada** [comment]
Related (Redis way to handle strings): https://github.com/antirez/sds
