### ISSUE TITLE
Remove struct Enc

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#3545]
Now sql.c has this:
```C
struct Enc {
	char *(*encode_uint)(char *data, uint64_t num);
	char *(*encode_str)(char *data, const char *str, uint32_t len);
	char *(*encode_bool)(char *data, bool v);
	char *(*encode_array)(char *data, uint32_t len);
	char *(*encode_map)(char *data, uint32_t len);
};
```

The only purpose of this struct is to make the same API for calculation of MessagePack size and its encoding during DML via SQL. But we have already mpstream. It should be adapted for this thing and replace struct Enc.

**Comment by kyukhin** [comment]
This part of #2419.

**Comment by Gerold103** [comment]
I think, issues like #2419 has no sense. It is a huge list of non-clearly described pseudo-features/refactoring plans, that is hard to maintain and fix. My opinion, that it should be split into separate issues and closed.
