### ISSUE TITLE
Add support for multiple transports at the same time

### ISSUE THREAD

**Issue by cyanide-burnout** [tarantool/tarantool#3554]
In fact unix-socket connection is faster than locally connected tcp.
I am trying to use unix-socket but some communications require to use tcp.

It might be good for example to have this option:
box.cfg({ listen = { 3301, '/tmp/tarantool.sock' } })

**Comment by amdei** [comment]
Also, it would be wonderful it local clients were able to connect using unix-socket, while replication works over TCP.

**Comment by Gerold103** [comment]
Despite the ticket involves major refactoring of the whole iproto thread and networking, it looks promising in terms of speed up of local requests. For example, when vshard router works on the same node as one of the storages, it may send requests to the local storage via a unix socket. While other routers will use tcp to access the same storage.

**Comment by cyanide-burnout** [comment]
If you finally plan to make this and make refactoring of iproto, I would like to suggest to have a look on some capabilities maybe in the future, such as transferring data over shmem (memfd) and RDMA.
Just thought.

**Comment by knazarov** [comment]
I haven't experienced cases with real tarantool apps when TCP was a bottleneck.

**Comment by cyanide-burnout** [comment]
The problem is in CPU usage and timings. We (brandmeister) did measurements between TCP and UNIX connection types, and it seems like UNIX sockets are faster and makes less affect to CPU. Meanwhile we moved some our components from UNIX sockets and pipes to memfd and found better increase.
Anyway, I've created this ticket at the moment when we found that UNIX socket is much prefer for our real-time server system, where php driver and replicatord support TCP only.
Latency is so critical for real-time.
And finally, if you can free some CPU cycles from network processing, they could be used somewhere else )

**Comment by kostja** [comment]
This ticket has a lot of intersection with proxy module. https://github.com/tarantool/tarantool/issues/2625
When 2625 is fixed one will be able to:
- have multiple listen objects
- start listen before box.cfg.

Unofrtunately this ticket is stuck for a long time - and I don't want to speculate why, because nothing good comes to mind.
