### ISSUE TITLE
Remove redundant and erroneous error message from tarantoolctl eval

### ISSUE THREAD

**Issue by Mons** [tarantool/tarantool#3560]
This line may very confuse
https://github.com/tarantool/tarantool/blob/7c3f9ceb0124935440e711a0a4012c4fa1f2146a/extra/dist/tarantoolctl.in#L788
in case of executing arbitrary command.

I request to remove it from at least 1.10 and 2.0

```
tarantoolctl eval myinstance <<< 'error("Some error from inline command")'
Error while reloading config:
Some error from inline command
```

Since eval have correct return code there is no need in extra message

**Comment by locker** [comment]
Fixed by commit dc648b9965e419bca86762d7f7e7c0b9bc62a7f4
