### ISSUE TITLE
Table creation fails but _space is changed

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#3562]
I have Ubuntu 14.04. I have Tarantool 2.0, pulled from source today.
I execute these requests:

box.schema.user.grant('guest','read,write,execute','universe')
box.session.su('guest')
box.sql.execute([[CREATE TABLE t22(id INTEGER PRIMARY KEY AUTOINCREMENT, a,b);]])
box.session.su('admin')
box.schema.user.grant('guest','create','universe')
box.session.su('guest')
box.sql.execute([[CREATE TABLE t22(id INTEGER PRIMARY KEY AUTOINCREMENT, a,b);]])

The first box.sql.execute request causes an error
- error: Create access to sequence 'T22' is denied for user 'guest'
This does not look like a bug, I need 'create' privilege, okay.

The second box.sql.execute request causes an error
- error: Duplicate key exists in unique index 'name' in space '_space'
This does look like a bug, the first box.sql.execute request did not fail completely.

**Comment by Korablev77** [comment]
I guess ticket is quite similar to this one: https://github.com/tarantool/tarantool/issues/3499

Without transactional DDL fail during table creation doesn't result in removal of already created objects.

**Comment by pgulutzan** [comment]
The above comment seems correct. I didn't see the similarity of #3499, sorry. I'll close this issue since it is a duplicate.
