### ISSUE TITLE
Applier changes commit order of rows to apply

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#3568]
If a row to apply yielded and another row arrived from other replica, it can finish applying earlier than the former. For vinyl it leads to conflicts even when the rows arrived in the correct order. Also it affects `box.ctl.promote()` that relays on the fact that even if records in a space are from different replicas, they are applied in the order of execution.

Consider the problem in details. Applier does its work in several steps: vclock get, vclock follow, latch lock, apply row, latch unlock. Latch here blocks only if several records are from the same replica regardless of the space. If latch does not block and appliance of the row yields, during this yield we can receive another row for the same space from another replica that will by applied faster than the former.

Here the test case is.
```Lua
-- Replica 1--
----------------------------- Step 1 -----------------------------
box.cfg{
	listen = 3313,
	replication = {'localhost:3313', 'localhost:3314', 'localhost:3315'},
	vinyl_bloom_fpr = 1,
}
box.schema.user.grant('guest', 'read,write,execute', 'universe')
----------------------------- Step 4 -----------------------------
fiber = require('fiber')
s = box.schema.create_space('test', {engine = 'vinyl'})
pk = s:create_index('pk')
s:insert{1}
s:insert{0}
s:insert{4}
s:insert{5}
----------------------------- Step 6 -----------------------------
s:insert{2}
```

```Lua
-- Replica 2--
----------------------------- Step 2 -----------------------------
box.cfg{
	listen = 3314,
	replication = {'localhost:3313', 'localhost:3314', 'localhost:3315'},
	vinyl_bloom_fpr = 1,
}
box.schema.user.grant('guest', 'read,write,execute', 'universe')
----------------------------- Step 5 -----------------------------
box.snapshot()
box.error.injection.set("ERRINJ_VY_READ_PAGE_TIMEOUT", 5)
```

```Lua
-- Replica 3--

----------------------------- Step 3 -----------------------------
box.cfg{
	listen = 3315,
	replication = {'localhost:3313', 'localhost:3314', 'localhost:3315'},
	vinyl_bloom_fpr = 1,
}
box.schema.user.grant('guest', 'read,write,execute', 'universe')
fiber = require('fiber')
while not box.space.test or not box.space.test.index.pk or
      not box.space.test:get{2} do
	fiber.sleep(0.01)
end
box.space.test:replace{2, 2}
```

Expected result that on the replica 2 we will have record `{2, 2}`. But actually the replication is just broken due to conflict in 5 seconds after Step 6. `{2}` arrived earlier than `{2, 2}`, but committed later:
```
tarantool> 2018-07-25 16:41:03.047 [34271] main/105/applier/localhost:3313 vy_point_lookup.c:272 W> 512/0: get([2]) => <NULL> took too long: 5.000 sec
2018-07-25 16:41:03.047 [34271] main/105/applier/localhost:3313 box.cc:330 E> error applying row: {type: 'INSERT', lsn: 9, space_id: 512, index_id: 0, tuple: [2]}
2018-07-25 16:41:03.047 [34271] main/105/applier/localhost:3313 I> can't read row
2018-07-25 16:41:03.047 [34271] main/105/applier/localhost:3313 vy_tx.c:499 E> ER_TRANSACTION_CONFLICT: Transaction has been aborted by conflict
```
There are several possible fixes.
* The simplest fix is to lock the latch earlier. Not here: https://github.com/tarantool/tarantool/blob/2.0/src/box/applier.cc#L523, but here: https://github.com/tarantool/tarantool/blob/2.0/src/box/applier.cc#L497. It helps because actually record `{2}` is send from the Replica3 before `{2, 2}` but it is skipped since its lsn was already followed here: https://github.com/tarantool/tarantool/blob/2.0/src/box/applier.cc#L506. But it affects performance of the case when records are not linked and can be applied independently.
* Do not skip the record silently. Instead introduce a per-space latch or something to order the space updates.
* Do not mind. And introduce a special latch for promotion.

**Comment by sergepetrenko** [comment]
Seems outdated.

Feel free to reopen if I'm wrong.
