### ISSUE TITLE
Strength in the _collation space

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#3573]
I have Ubuntu 14.04. I have Tarantool 2.0, pulled from source today.

I select from the _collation system table:

tarantool> box.space._collation:select()
---
- - [1, 'unicode', 1, 'ICU', '', {}]
  - [2, 'unicode_ci', 1, 'ICU', '', {'strength': 'primary'}]

This suggests that 'unicode' collation strength is nil.
My tests suggest that in fact it is strength = 'identical'.

**Comment by ImeevMA** [comment]
Hello, @pgulutzan!
From your comment I can see two problems:
1) We cannot see value of **strength** option. We can assume that it has some *default* value.
2) We don't know what is this *default* value according to [Comparison Levels](http://userguide.icu-project.org/collation/concepts#TOC-Comparison-Levels)

Now I am going to make **strength** option visible. But before that, I'd like to ask you: what level should I use as *default* value? Personally, I think that **identical** is most appropriate one. But I am not sure about this.

**Comment by pgulutzan** [comment]
I assume everyone agrees that "unicode" has default strength, so your question is important.
I doubt that 'identical' is the most appropriate default strength.


No. I believe what I read in http://unicode.org/reports/tr10/ UTS #10 Unicode Collation Algorithm:
"The default for strength in UCA is tertiary; it can be changed for different locales in CLDR."
and what I read in ICU's concepts page http://userguide.icu-project.org/collation/concepts:
"This level should be used sparingly, as only code point values differences between two strings is an extremely rare occurrence. Using this level substantially decreases the performance for
both incremental comparison and sort key generation (as well as increasing the sort key length)."

This might be a good time to remind everyone that, although deterministic sort order
is desirable, 'identical' does not guarantee it. For example:
box.internal.collation.create('RUSSIAN_S5', 'ICU', 'ru_RU', {strength='identical'});
box.sql.execute([[DROP TABLE "k";]])
box.sql.execute([[CREATE TABLE "k" (s1 INT PRIMARY KEY, s2 CHAR(1));]])
box.space.k:insert{5,'Ё'}
-- Insert Е and Combining Diaeresis
box.space.k:insert{2,string.char(0xd0)..string.char(0x95)..string.char(0xcc)..string.char(0x88)}
box.sql.execute([[SELECT s1,s2,length(s2) FROM "k" WHERE s2 = 'Ё' COLLATE "RUSSIAN_S5";]])
The SELECT result is:
tarantool> box.sql.execute([[SELECT s1,s2,length(s2) FROM "k" WHERE s2 = 'Ё' COLLATE "RUSSIAN_S5";]])
---
- - [2, 'Ё', 2]
  - [5, 'Ё', 1]
...

So: feature request: 'deterministic' strength? Maybe it's actually not bad
if the comparison operator is '=' and there's no index, because then you'd
only need to memcmp the UTF-8 strings.

**Comment by pgulutzan** [comment]
I was only complaining that the description that I see with _collation:select() seemed unclear.
I worry that the proposed patch will change the actual collation strength of "unicode" and of new collations created with default options, and those are unnecessary changes.
Now I regret that I created this issue, and suggest it should be closed with "won't fix".
