### ISSUE TITLE
Introduce a separate schema_object_type for grants on entire entity.

### ISSUE THREAD

**Issue by sergepetrenko** [tarantool/tarantool#3574]
Currently granting privileges on an entire entity and on a single object share the same object_type, the one of the entity. This causes object id confusion, since we use id 0 to indicate granting on an entire entity, but some entities have objects with id 0.
To fix this implement a separate type to indicate grants on an entire entity.

This is needed for correct implementation of #3524.

**Comment by locker** [comment]
Fixed by ba5aec56944e0ea86e91fa670bff41b8e0cddc00
