### ISSUE TITLE
Exploring tarantool, what if dataset exceeds memory, what will happen?

### ISSUE THREAD

**Issue by streetlist** [tarantool/tarantool#3575]
Does tarantool have to have all dataset fit in memory nicely or do we have some sort of warm-cold data persistence on disk? Thanks in advance for the guidance

**Comment by kyukhin** [comment]
Feel free to ask your questions in:
- Telegram channel
    - (Russian) https://t.me/tarantoolru
    - (English) https://t.me/tarantool
- Google groups
    - (Russian) https://groups.google.com/forum/#!forum/tarantool-ru
    - (English) https://groups.google.com/forum/#!forum/tarantool
