### ISSUE TITLE
Is tarantool production ready?

### ISSUE THREAD

**Issue by unisqu** [tarantool/tarantool#3576]
I know badoo, mail.ru are using it but is it production ready for the open source version?

**Comment by kyukhin** [comment]
Feel free to ask your questions in:
- Telegram channel
    - (Russian) https://t.me/tarantoolru
    - (English) https://t.me/tarantool
- Google groups
    - (Russian) https://groups.google.com/forum/#!forum/tarantool-ru
    - (English) https://groups.google.com/forum/#!forum/tarantool
