### ISSUE TITLE
i'm trying to configure tarantool docker's vinyl_memory setting

### ISSUE THREAD

**Issue by unisqu** [tarantool/tarantool#3577]
i used the official tarantool docker and no idea how to configure (where to change the box.cfg{})?

Any help appreciated.

https://tarantool.io/en/doc/1.9/reference/configuration/#confval-vinyl_memory

**Comment by kyukhin** [comment]
Feel free to ask your questions in:
- Telegram channel
    - (Russian) https://t.me/tarantoolru
    - (English) https://t.me/tarantool
- Google groups
    - (Russian) https://groups.google.com/forum/#!forum/tarantool-ru
    - (English) https://groups.google.com/forum/#!forum/tarantool
