### ISSUE TITLE
Full text search in column values possible?

### ISSUE THREAD

**Issue by unisqu** [tarantool/tarantool#3579]
Did I missed out something? Can tarantool do full text column value search?

**Comment by kyukhin** [comment]
Feel free to ask your questions in:
- Telegram channel
    - (Russian) https://t.me/tarantoolru
    - (English) https://t.me/tarantool
- Google groups
    - (Russian) https://groups.google.com/forum/#!forum/tarantool-ru
    - (English) https://groups.google.com/forum/#!forum/tarantool
