### ISSUE TITLE
fio.pathjoin fails with non-informative error message

### ISSUE THREAD

**Issue by mtrempoltsev** [tarantool/tarantool#3580]
Tarantool 2.0.4-311-g268304e0d

```
tarantool> fio = require('fio')
tarantool> fio.pathjoin('test', nil)
---
- error: 'builtin/fio.lua:236: Undefined path part'
...
```

I can't find a problem in the code with this error message. Please print the stack.

**Comment by Totktonada** [comment]
Use xpcall + debug.traceback to print the stacktrace.

**Comment by mtrempoltsev** [comment]
I want the Tarantool to be more friendly. As example:

```
local json = require('json')

json.decode(nil)
```

Goog message:

> 1.lua:3: bad argument #1 to 'decode' (string expected, got nil)

```
local fio = require('fio')

fio.pathjoin(nil)
```

Bad message:

> builtin/fio.lua:216: Undefined path part 1

**Comment by romanhabibov** [comment]
@mtrempoltsev, did you expect to see something like "Undefined path: nil"?

**Comment by mtrempoltsev** [comment]
I want to see a place in my code where function fails.

**Comment by Totktonada** [comment]
I don't think we should set the second parameter of error(): https://www.freelists.org/post/tarantool-patches/PATCH-02-v2-fio-show-function-name-in-all-fio-errors,2
