### ISSUE TITLE
CMP0037 OLD cmake deprecation warning

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#3587]
```
CMake Deprecation Warning at test/CMakeLists.txt:21 (cmake_policy):
  The OLD behavior for policy CMP0037 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.
```

cmake version 3.11.3

Related: #742.

Can be fixed like so I guess: https://git.reviewboard.kde.org/r/123745/diff/1#index_header

Update: The link above was died. I guess the linked patch is https://phabricator.kde.org/R283:38b0eeec41de0e916dd834b849f7ddcfa06bdafc

**Comment by OKriw** [comment]
We have got cmake_policy(SET CMP0037 OLD).
Accordingly to https://cmake.org/cmake/help/v3.0/policy/CMP0037.html
starting from 2.8.12 + we need to follow some name politics when using add_library(), add_executable() and add_custom_target(). 
I guess we need to check name we are using inside add_* functions and remove setting old policy.
