### ISSUE TITLE
Collations & LIKE operator should work according to ANSI

### ISSUE THREAD

**Issue by Hollow111** [tarantool/tarantool#3589]
Today LIKE is always case-sensitive, regardless of column character set. In order to change like case sensitivity one has to use "PRAGMA case_sensitive_like" in a preceding statement. This breaks ANSI compatibility, and needs to be fixed ASAP since when/if we fix it later, we'll break semantics of existing code.

What needs to be done:

1) Remove "PRAGMA case_sensitive_like" & everything concerned with it.
2) Make LIKE operator used with TEXT types depend on column collations. 

Part of #3572.

**Comment by pgulutzan** [comment]
I guess that when LIKE depends on column collations, it will use ICU. So I suggest this test:
Compare Long S with S.
SELECT UPPER('ſ') = 'S', 'ſ' LIKE 'S', 'ſ' = 'S' COLLATE "unicode_ci";
Currently the result is: 1, 0, 1.

**Comment by romanhabibov** [comment]
How should operator 'LIKE' behave with collations, which equate ligatures (e.g. 'ss' and 'ß', 'œ' and 'oé')?
I have tried to maintain the following behaviour: 'ss' LIKE 'ß' COLLATE "unicode_de__phonebook_s1" --> true. (As I understood, this collation equate 'ss' and 'ß'.)
But, now I think, that ICU don't provide such an API for this.

**Comment by pgulutzan** [comment]
@romanhabibov: I will reply via email.
