### ISSUE TITLE
Vagrant-based regression tests

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#359]
A user needs to be able to say `make test` and get compile and test failures from all supported platforms

**Comment by Sulverus** [comment]
fedora 20 x86_64 testrunner is available:
http://master.farm.tarantool.org/builders/0_Testrunner%20%28master%29

**Comment by Sulverus** [comment]
Now buildbot farm can build docker containers with tarantool and run tests for all supported platforms. 
+docker hub repository added  
https://registry.hub.docker.com/u/tarantool/tarantool/
