### ISSUE TITLE
Allow to start tarantool with no formats via special box.cfg option

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#3605]
It is a common case that an instance is running on a version 1.6.*, then is upgraded to 1.9 with box.schema.upgrade(). But some of users has malformed space formats, and some of them got and ignored errors on `box.schema.upgrade()`. Such half-upgraded data can not be started on a new version due to format violations, and can not be rolled back because some of new system spaces managed to be created. And we can not repair raw xlogs and snapshots because we have no such tools and they are zipped.

So it would be useful to have a command line option like `--ignore-space-formats`. It would allow to start an instance on the spaces with malformed formats, fix them, create a snapshot and then start with the formats turned on.

**Comment by kostja** [comment]
Won't fix.
