### ISSUE TITLE
Segmentation fault with subquery in check clause

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#3611]
I have Ubuntu 14.04. I have Tarantool 2.0, pulled from source today.

I execute this request:
box.sql.execute([[CREATE TABLE w2 (s1 INT PRIMARY KEY, CHECK ((SELECT COUNT(*) FROM w2) = 0));]])
Result = Segmentation fault.

**Comment by kshcherbatov** [comment]
It's a bit strange, but this bug came with patch
commit 13df2b1f7a968dcb2e5e670e50749d2f749cc3f5
Merge: 0ecdb0f 0665841
Author: Kirill Yukhin <kyukhin@tarantool.org>
Date:   Tue Jul 31 09:31:34 2018 +0300

    Merge branch '1.10' into 2.0

I mean there is no sql-related changes there.
(researching)

**Comment by kshcherbatov** [comment]
There were an appropriate place to setup error in selectExpander:
```
int space_id = box_space_id_by_name(t_name, strlen(t_name));
if (space_id == BOX_ID_NIL) {
	sqlite3ErrorMsg(pParse,
			"no such table: %s",
			t_name);
	return WRC_Abort;
}
struct space *space = space_by_id(space_id);

But after 13df2b1 patch box_space_id_by_name returns not BOX_ID_NIL here like space exists, but it doesn't.

**Comment by kshcherbatov** [comment]
Yep,
this patch include 7f8a75a4353afdd1bfdf883545072cda5d257a69 
from 1.10 that escalate the problem.

**Comment by kshcherbatov** [comment]
Finally, I've investigated what's going on:
With 9a543202c93ef903b07b293463650d78002ae866 we make sql_checks_resolve_space_def_reference as a part of on_replace_dd_space on _space insertion.
Before Vova's path 0ecabde box_space_id_by_name returned BOX_ID_NIL thanks for Multi-engine transaction error(that omitted now).
In other word, box_space_id_by_name do _space lookup of space "W2" during "W2" insertion.
I believe that the appropriate solution is to get rid of assumption that space_by_id returns not NULL at the same time box_space_id_by_name returned not BOX_ID_NIL.
