### ISSUE TITLE
How to share tarantool's ev_loop in other liberary?

### ISSUE THREAD

**Issue by zw-git** [tarantool/tarantool#3614]
I get the  struct ev_loop pointer in lua, and use it in other liberary(like libwebsockets) with a lua callback function via ffi. But it crashed at sometime.
How to share tarantool's ev_loop in other liberary?

**Comment by kyukhin** [comment]
Feel free to ask your questions in:
- Telegram channel
    - (Russian) https://t.me/tarantoolru
    - (English) https://t.me/tarantool
- Google groups
    - (Russian) https://groups.google.com/forum/#!forum/tarantool-ru
    - (English) https://groups.google.com/forum/#!forum/tarantool
