### ISSUE TITLE
setting syslog logger on os without syslog crashes tarantool

### ISSUE THREAD

**Issue by OKriw** [tarantool/tarantool#3618]
If we set box.cfg{log="syslog:"} on systems with unconfigured syslog (fedora26/27, centos) crashes tarantool.

Steps to reproduce:
run tarantool on centos/fedora.
```
tarantool> box.cfg, {log = "syslog:"}
SystemError syslog logger: No such file or directory: No such file or directory
failed to initialize logging subsystem
```

**Comment by sergepetrenko** [comment]
Setting syslog logging happens in `load_cfg()`. Every other error here results in tarantool exiting. So why should this error result in some other action?

**Comment by OKriw** [comment]
Setting syslog is not an error, it is normal configuration. Problem happens
when we set syslog and there is no syslog configured. So normal
configuration leads to crash. I guess we should check if there is syslog
available? And in box_check_cfg raise exception?

ср, 15 авг. 2018 г. в 17:59, Serge Petrenko <notifications@github.com>:

**Comment by Mons** [comment]
Just don't set log: in this case.
