### ISSUE TITLE
how to install tarantool and tarantoolctl on ubuntu 18.04?

### ISSUE THREAD

**Issue by vanessasmith** [tarantool/tarantool#3620]
Hello,
I wonder if:
 is there a way to install tarantool on ubuntu 18.04

the vps has only ubuntu 18.04 bionic , no previous ubuntu versions.

1)the page of tarantool packages are for previous ubuntu versions:
 https://tarantool.io/en/download/os-installation/1.9/ubuntu/
2) then I tried to install from source:
https://tarantool.io/en/doc/1.9/dev_guide/building_from_source/
there were some errors on python:  Failed building wheel for argparse,,etc.
but the rest was correct:
git clone --recursive https://github.com/tarantool/tarantool.git -b 1.9 ~/tarantool
cd ~/tarantool
make clean         # unnecessary, added for good luck
rm CMakeCache.txt  # unnecessary, added for good luck
cmake .            # start initiating with build type=Debug
make
make install
there is tarantool, Tarantool 1.9.1-65-ge72867cb9
but when I try to run tarantoolctl, tarantoolctl is not installed.
I read that tarantoolctl is part of the distribution.

3)in apt-get install tarantool there is no tarantool.
However the following packages replace it:
  tarantool-lts:i386 tarantool-lts
I have tried also installing tarantool-lts, but there is no tarantoolctl
also I have tried with tarantool forn nginx, only to build-all.

the vps is shipped with 18.04 ubuntu only.

Is there a way to install tarantool for ubuntu 18.04?

thank you

**Comment by Totktonada** [comment]
@vanessasmith We have the repository for Ubuntu Bionic, but the documentation doesn’t reflect it for now (tracked by [1]). You can replace all words `xenial` with `bionic` in the instruction from your first link and it should work.

[1]: https://github.com/tarantool/doc/issues/536

**Comment by vanessasmith** [comment]
It works.
thank you,
