### ISSUE TITLE
Add characters to strip to string.rstrip and string.lstrip

### ISSUE THREAD

**Issue by racktear** [tarantool/tarantool#3622]
I want to be able to do roughly this:

```lua
string.rstrip('/my/path/', '/')
```

And have `/` removed from the right. This is how python or penlight do this for example. By default they remove whitespace characters, and if the second parameter is passed, they remove all characters mentioned in that parameter.

**Comment by Totktonada** [comment]
Dupe of your #2977.

**Comment by kyukhin** [comment]
Duplicate of #2977
