### ISSUE TITLE
Make configuration variables from load_cfg.lua visible

### ISSUE THREAD

**Issue by Mons** [tarantool/tarantool#3628]
For utilities, that wraps configuration it is very useful to know which params are dynamic or deprecated and so on...
Currently I'm using contents of `dynamic_cfg`, `upgrade_cfg`, `translate_cfg`.
Also would be great to access `default_cfg` for some cases

I suppose it would be ok to have it somehow like `require("internal.load_cfg").dynamic_cfg` and so on

**Comment by Totktonada** [comment]
The same idea comes into my mind too: #8141. I'll close my issue as duplicate, but I'll cite its content here.

> # box: list available box.cfg options before box configuration
>
> Parameters to pass into `box.cfg()` may be received from an external configuration file/storage. In this case we should validate them before calling `box.cfg()`.
>
> What else except the list of names is needed:
>
> * Allowed types.
> * Whether the option can be configured only once or dynamically at any time.
>
> NB: It would be nice to replace the [hardcoded box.cfg options list](https://github.com/tarantool/cartridge/blob/56fe20ab8992d4cc283eb9d25d1498ce8f39e272/cartridge/argparse.lua#L112-L208) in cartridge to don't [update it constantly](https://github.com/tarantool/cartridge/pull/1826) and to don't let users update cartridge in order to use new box.cfg options.

(And, what also comes into my head: it worth to expose default values as well.)

**Comment by Totktonada** [comment]
I've added `box.internal.template_cfg` and `box.internal.default_cfg` in f679b1e4fb33be8f707c93f9bed65e3ebcd8068f (`3.0.0-alpha1-21-gf679b1e4fb`). These are internal tables: they may be changed, renamed or disappear.

**Comment by Totktonada** [comment]
The configuration is now focused on the new declarative configuration facilities (#8724).

At the same time, some internal APIs are added, so if one really needs, she/he can access the list of box.cfg() parameters before first box.cfg() call.

I think it is a good point to close the issue as completed. If there are more requests on the topic, just file a new feature request.
