### ISSUE TITLE
Implement rocks remove --force option

### ISSUE THREAD

**Issue by mtrempoltsev** [tarantool/tarantool#3632]
```
ib-core $ tarantoolctl rocks remove logger
Checking stability of dependencies in the absence of
logger scm-1...

Will not remove logger scm-1.
Removing it would break dependencies for:
ib-core scm-1

Use --force to force removal (warning: this may break modules).

Error: Failed removing.
ib-core $ tarantoolctl rocks remove logger --force
builtin/internal.argparse.lua:142: unknown options: force
```

**Comment by Totktonada** [comment]
I think we should allow all or most of luarocks options to be passed to subcommands.

However we maybe should ban --lua-ver[sion], --lua-dir and other options that are related to choosing a Lua interpreter to configure packages against (don't sure however what exactly this 'configuration' does).

**Comment by Totktonada** [comment]
Pushed to 1.10 too in [1.10.5-48-g84dd4f57d](https://github.com/tarantool/tarantool/commit/84dd4f57d02781f36a2520de119a6d5d2a8e8901).
