### ISSUE TITLE
Make tarantoolctl self-sufficient binary

### ISSUE THREAD

**Issue by sharonovd** [tarantool/tarantool#3641]
Currently `tarantoolctl` is a lua script, executed by tarantool.
It also requires luarocks to be installed in the system.

It is not suitable for some situations - e. g. when tarantool is statically packed, and no other external dependencies are allowed (luarocks, zip, etc), or when it is launched on admin laptop - to connect to remote server.

Proposal is to make tarantoolctl a self-sufficient binary - compiling luajit, luarocks, zip and probably something else inside.

**Comment by sharonovd** [comment]
Alternative would be the following:

Provide ability to link luarocks and zip to tarantool statically.

**Comment by kyukhin** [comment]
OK.
