### ISSUE TITLE
Relay do not close connection socket because of an error

### ISSUE THREAD

**Issue by GeorgyKirichenko** [tarantool/tarantool#3642]
src/box/iproto.cc in function tx_process_join_subscribe on Socker Error tarantool rethrow the error and this break cbus message dispatching and then net_end_subscribe wont be called.

We shouldn't pass exception out from the cbus calling functions, so return should be used instead of throw

**Comment by locker** [comment]
Blocked by https://github.com/tarantool/test-run/issues/117

**Comment by locker** [comment]
Fixed by 2e87902e6aab66697ff36004b78c8f72daef9492
