### ISSUE TITLE
Foreign key circular reference prevents dropping

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#3646]
create table t16 (s1 int primary key, s2 char(5) unique);
create table t17 (s1 int primary key, s2 char(5) unique, foreign key (s2) references t16 (s2));
alter table t16 add constraint C foreign key (s2) references t17 (s2);
drop table t17;
drop table t16;
pragma foreign_keys=no;
For the first DROP statement, I get Error . Can't drop space 'T17': other objects depend on it
For the second DROP statement, I get Error . Can't drop space 'T16': other objects depend on it

**Comment by Korablev77** [comment]
Why this behaviour is supposed to be unexpected? Firstly, you should drop FK constraint with `ALTER TABLE DROP CONSTRAINT` and only then drop table. I tested this example on PostgreSQL and MySQL - both don't allow to drop table until it is referenced by another table.

**Comment by pgulutzan** [comment]
Korablev77 is 100% correct, the matter is solved easily with ALTER TABLE. I apologize for not thinking clearly, and I will cancel this non-bug.
