### ISSUE TITLE
sql: make VARBINARY accept only binary format

### ISSUE THREAD

**Issue by Korablev77** [tarantool/tarantool#3650]
Currently, \<BLOB> is really \<SCALAR> under the hood, so it actually accepts any type. For example:
```
CREATE TABLE t1(id INT PRIMARY KEY, a BLOB);
INSERT INTO t1 VALUES(1, 'x');
INSERT INTO t1 VALUES(2, 3);
INSERT INTO t1 VALUES(3, 3.0432);
```
Most of other DBs allow to store in BLOB only real binary format. Examples:

- db2
```
db2 => CREATE TABLE t1(b BLOB)
DB20000I  The SQL command completed successfully.

db2 => INSERT INTO t1 VALUES (1)
DB21034E  The command was processed as an SQL statement because it was not a 
valid Command Line Processor command.  During SQL processing it returned:
SQL0408N  A value is not compatible with the data type of its assignment 
target. Target name is "B".  SQLSTATE=42821

db2 => INSERT INTO t1 VALUES ('abc')
DB21034E  The command was processed as an SQL statement because it was not a 
valid Command Line Processor command.  During SQL processing it returned:
SQL0408N  A value is not compatible with the data type of its assignment 
target. Target name is "B".  SQLSTATE=42821

db2 => INSERT INTO t1 VALUES(CAST('99' AS BLOB))
DB20000I  The SQL command completed successfully.
```

- Oracle
```
CREATE TABLE t1(a BLOB)
INSERT INTO t1 VALUES (1)
ORA-00932: inconsistent datatypes: expected BLOB got NUMBER
```
Ordinar string is OK:
`INSERT INTO t1 VALUES('abc') `

- Postgres lacks BLOB type, but still features \<BYTEA>:
```
CREATE TABLE t1(a BYTEA);
INSERT INTO t1 VALUES (1);
42804: column "a" is of type bytea but expression is of type integer
```
Nevertheless, it accepts strings:
`INSERT INTO t1 VALUES('abc');`

Moreover, we should ban implicit conversions from BLOB to other types, including string ones.
- db2
```
CREATE TABLE t1(a CHAR(10))
INSERT INTO t1 VALUES ('9')
CREATE TABLE t2(b BLOB)
INSERT INTO t2 VALUES (CAST('9' AS BLOB))

db2 => SELECT * FROM t1, t2 WHERE a = b
SQL0401N  The data types of the operands for the operation "=" are not 
compatible or comparable.  SQLSTATE=42818
```
- Postgres

```
CREATE TABLE t1(a CHAR(10));
INSERT INTO t1 VALUES ('9');
CREATE TABLE t2(b BYTEA);
INSERT INTO t2 VALUES ('9');
SELECT * FROM t1, t2 WHERE a = b;
42883: operator does not exist: character = bytea
```

Moreover, according to ANSI:

> Binary large object strings cannot be used in:
> — Predicates other than \<comparison predicate> with an \<equals operator> or a \<not equals operator>, \<quantified comparison predicate> with an \<equals operator> or a \<not equals operator>, and \<exists predicate>.
> — \<general set function>.
> — \<group by clause>.
> — \<order by clause>.
> — \<unique constraint definition>.
> — \<referential constraint definition>.
> — \<select list> of a \<query specification> that has a \<set quantifier> of DISTINCT.
> — UNION, INTERSECT, and EXCEPT.
> — Columns used for matching when forming a \<joined table>.

**Comment by Korablev77** [comment]
Moreover, fact of using BLOB as SCALAR leads to such silly things:

```
CREATE TABLE t1 (x INT primary key, y TEXT);
INSERT INTO t1 VALUES(1,99);
CREATE TABLE t2(a  INT primary key, b BLOB);
CREATE INDEX t2b ON t2(b);
INSERT INTO t2 VALUES(2, '99');
SELECT x, a, y=b FROM t1, t2 WHERE y=b;
```

Result is:
```
---
- - [1, 2, 1]
...

```
But if we do this:
```
DELETE FROM t2;
INSERT INTO t2 VALUES(2, 99);
SELECT * FROM t2;
```
Result would be empty set `[]`. One can see that in first case we inserted ('99') in BLOB field, in second one - (99). Lest look at VDBE program:

```
tarantool> SELECT x, a, y=b FROM t1, t2 WHERE y=b; 
SQL: [SELECT x, a, y=b FROM t1, t2 WHERE y=b; ]
VDBE Program Listing:
 101>    0 Init             0    1    0               00 Start at 1
 101>    1 OpenWrite        2    0    0 space<name=T1> 00 index id = 0, space ptr = space<name=T1>; pk_unnamed_T1_1
 101>    2 OpenWrite        3    1    0 space<name=T2> 02 index id = 1, space ptr = space<name=T2>; T2B
 101>    3 Explain          0    0    0 SCAN TABLE T1 00 
 101>    4 Rewind           2   17    1 0             00 
 101>    5 Explain          0    1    1 SEARCH TABLE T2 USING COVERING INDEX T2B (B=?) 00 
 101>    6 Column           2    1    1               00 r[1]=T1.Y
 101>    7 IsNull           1   16    0               00 if r[1]==NULL goto 16
 101>    8 SeekGE           3   16    1 1             00 key=r[1]
 101>    9 IdxGT            3   16    1 1             00 key=r[1]
 101>   10 Column           2    0    2               00 r[2]=T1.X
 101>   11 Column           3    0    3               00 r[3]=T2.A
 101>   12 Column           3    1    5               00 r[5]=T2.B
 101>   13 Eq               5    4    1 (binary)      61 r[4] = (r[1]==r[5])
 101>   14 ResultRow        2    3    0               00 output=r[2..4]
 101>   15 Next             3    9    1               00 
 101>   16 Next             2    5    0               01 
 101>   17 Halt             0    0    0               00 

```
Explanation is quite simple: we extract key from table `t1` and try to search in index `t2b` by this key. In first case key is '99' and it exists in `t2b`. In second case, the value in `t2` is [2, 99]. Type of key to be found STRING ('99') and value in `t2` is of INT (99) type.

**Comment by Korablev77** [comment]
Another note concerning <BLOB>: in SQLite <BLOB> and <TEXT> are comparable, but <BLOB> is always less than <TEXT>. So, even if we allow comparisons between these two types, we *likely* should remove this restriction.

**Comment by Totktonada** [comment]
AFAIU we want to store BLOB data as bin8/bin/16/bin32 in msgpack and forbid other ones (including DML from Lua side). Then we need to introduce new tarantool format data type: it will allow bin* mp types, but disallow fixstr/str* ones. @Korablev77 Are this issue assumes this scope of work?

Now strings are inserted are fixstr/str*, but X'...' values as bin*:

```
box.cfg{}
\set language sql
create table t(id int primary key, v blob);
insert into t values(1, 'abcd');
insert into t values(2, X'61626364');
\set language lua
tuple_mp_hex = function(t) local ffi = require('ffi') local o = (ffi.cast('const uint16_t *', t) + 4)[0] local s = (ffi.cast('const uint32_t *', t) + 1)[0] local d = ffi.cast('const char *', t) + o return ffi.string(d, s):hex() end -- gh-3909
tarantool> tuple_mp_hex(box.space.T:get(1))
---
- 9201a461626364
...

tarantool> tuple_mp_hex(box.space.T:get(2))
---
- 9202c40461626364
...
```

`a461626364` is fixstr of length 4 with characters 61, 62, 63, 64 ('a', 'b', 'c', 'd'). `c40461626364` is bin8 of length 4 with the same bytes. The decoding table: https://github.com/msgpack/msgpack/blob/master/spec.md#overview

Why it even matter? It affects what we send in the binary protocol and so we have no strong representation of our SQL types for connectors. See https://github.com/tarantool/tarantool-java/issues/45

**Comment by Totktonada** [comment]
I see even more: bin8 from iproto sql_execute stored as fixstr: https://github.com/tarantool/tarantool-java/issues/45#issuecomment-457449618

**Comment by Totktonada** [comment]
@kyukhin It is a part of #4019, so should be in 2.1.2 milestone.

**Comment by Totktonada** [comment]
The example above is valid for scalar (we replaced blob with scalar and going to support blob separately in the future).

Now I have a problem with scalar: if I bind bin8 to, say, `insert into x values(2, ?)` and try to select it, I got str8. It is not a part of this issue.

**Comment by kostja** [comment]
Need to finish this in scope of varbinary supoprt

**Comment by Korablev77** [comment]
@kostja It seems to be already finished:

```
tarantool> CREATE TABLE t (v VARBINARY PRIMARY KEY)
---
- row_count: 1
...

tarantool> INSERT INTO t VALUES (1)
---
- null
- 'Type mismatch: can not convert 1 to varbinary'
...

tarantool> INSERT INTO t VALUES ('abc')
---
- null
- 'Type mismatch: can not convert abc to varbinary'
...

tarantool> INSERT INTO t VALUES (X'00')
---
- row_count: 1
...

```

**Comment by kostja** [comment]
Add a test case and close the bug please.

**Comment by Korablev77** [comment]
It already exists: `test/sql/types.test.lua`
