### ISSUE TITLE
sql: <WHERE> clause argument must be boolean

### ISSUE THREAD

**Issue by Korablev77** [tarantool/tarantool#3651]
Now it is possible to run queries like this:
```
tarantool> SELECT 1 WHERE 'abc'
---
- []
...

tarantool> SELECT 1 WHERE 12
---
- - [1]
...
tarantool> SELECT 1 WHERE 0
---
- []
...
```
In first case one can see implicit conversion from string to boolean. It definitely makes no sense: \<WHERE> clause requires its argument to be boolean (to be more precise: the \<search condition> is effectively evaluated for each row of given table (lets call it `T`); the result of the \<where clause> is a
table of those rows of `T` for which the result of the \<search condition> is True) and any conversions must be prohibited.

*Other DBs behaviour:

- db2 doesn't even allow to run this query:
```
db2 => SELECT * FROM t1 WHERE TRUE

SQL0104N  An unexpected token "END-OF-STATEMENT" was found following "* FROM 
t1 WHERE TRUE".  Expected tokens may include:  "<interval_qualifier>".  
SQLSTATE=42601

```

- Postgres
```
SELECT 1 WHERE 'abc'
22P02: invalid input syntax for type boolean: "abc"
SELECT 1 WHERE 1
42804: argument of WHERE must be type boolean, not type integer

```

- Oracle
```
SELECT 1 FROM t1 WHERE 1
ORA-00920: invalid relational operator
SELECT 1 FROM t1 WHERE TRUE
ORA-00920: invalid relational operator
```

**Comment by Gerold103** [comment]
Fixed with boolean type introduction.
