### ISSUE TITLE
Can not start after upgrade schema

### ISSUE THREAD

**Issue by zloidemon** [tarantool/tarantool#3652]
I had installed tarantool 1.7.6 and updated to latest 1.9.1. After use command to upgrade schema to last one, I got issues:

```
I> recovering from `/var/lib/tarantool/plusofon_pincall/00000000000000134478.snap'
key_def.h:403 E> ER_FIELD_TYPE: Tuple field 6 type does not match one required by operation: expected string
F> can't initialize storage: Tuple field 6 type does not match one required by operation: expected string
```

Server no more start.

Tarantool 1.9.1-76-g87f9be4
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial

**Comment by kostja** [comment]
You have been using 1.7.4 and hit a bug with broken 1.7.4 -> 1.7.5 upgrade.
Please upgrade manually with this script:
function setmap(table)                                                          
    return setmetatable(table, { __serialize = 'map' })                         
end                                                                             
function update_existing_users_to_1_7_5()                                       
    local def_ids_to_update = {}                                                
    for _, def in box.space._user:pairs() do                                    
        local new_def = def:totable()                                           
        if new_def[5] == nil then                                               
            table.insert(def_ids_to_update, new_def[1])                         
        end                                                                     
    end                                                                         
    for _, id in ipairs(def_ids_to_update) do                                   
        box.space._user:update(id, {{'=', 5, setmap({})}})                      
    end                                                                         
end                                                                             
                                                                                
box.space._user:run_triggers(false)                                             
update_existing_users_to_1_7_5();                                               
box.space._user:run_triggers(true)                                              
                                                                                
box.space._space:run_triggers(false)                                            
old_format = box.space._space:get{box.space._space.id}:totable()                
old_format[7][6].type = 'map'                                                   
box.space._space:replace(old_format)                                            
old_format = box.space._space:get{box.space._index.id}:totable()                
old_format[7][5].type = 'map'                                                   
box.space._space:replace(old_format)                                            
box.space._space:run_triggers(true)                                             
                                                                                
old_format=nil                                                                  
setmap=nil                                                                      
update_existing_users_to_1_7_5=nil                                              
box.snapshot()
