### ISSUE TITLE
sql: remove support of binding variables from trigger definition

### ISSUE THREAD

**Issue by Korablev77** [tarantool/tarantool#3653]
We don't support SQLite's binding mechanism (https://www.sqlite.org/c3ref/bind_blob.html), so it makes no sense to allow this syntax. Moreover, right now it results in assertion:

```
CREATE TABLE t1(a INT PRIMARY KEY, b INT);
CREATE TRIGGER tr1 AFTER INSERT ON t1 WHEN new.a = ? BEGIN SELECT 1; END;
INSERT INTO t1 VALUES (1, 1);
Assertion failed: (pOp->p1>0 && pOp->p1<=p->nVar), function sqlite3VdbeExec, file tarantool/src/box/sql/vdbe.c, line 1245.
```

**Comment by kshcherbatov** [comment]
First of all, "We don't support SQLite's binding mechanism" - it is not so. I've validated assigning variable and it works correctly. The problem is slightly different:
sql_trigger_begin use reduced expression tree for WHEN clause:
```
trigger->pWhen = sqlite3ExprDup(db, when, EXPRDUP_REDUCE);
```
so, iColumn that is below iTable field (```#define EXPR_REDUCEDSIZE offsetof(Expr,iTable) ```)
is an invalid memory containing zero:
```
                        u32 nSize = (u32) exprStructSize(p);
			memcpy(zAlloc, p, nSize);
			if (nSize < EXPR_FULLSIZE) {
				memset(&zAlloc[nSize], 0,
				       EXPR_FULLSIZE - nSize);
			}
```
as you see, EXPRDUP_REDUCE even doesn't save memory in this case!

**Comment by kshcherbatov** [comment]
I think that DEFAULTS/VIEWS/CHECKS and other server-integrated(compiled with temporal parser) AST Variables would work improper way.

**Comment by kshcherbatov** [comment]
Moreover, I offer this diff
```
@@ -140,11 +141,10 @@ sql_trigger_begin(struct Parse *parse, struct Token *name, int tr_tm,
 
        trigger->op = (u8) op;
        trigger->tr_tm = tr_tm;
-       trigger->pWhen = sqlite3ExprDup(db, when, EXPRDUP_REDUCE);
-       trigger->pColumns = sqlite3IdListDup(db, columns);
-       if ((when != NULL && trigger->pWhen == NULL) ||
-           (columns != NULL && trigger->pColumns == NULL))
-               goto trigger_cleanup;
+       trigger->pWhen = when;
+       when = NULL;
+       trigger->pColumns = columns;
+       columns = NULL;
```
(not a part of this bug; there is no reason to truncate structures like sqlite did now).
