### ISSUE TITLE
Assertion with passwd

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#3659]
I have Ubuntu 18.04. I have Tarantool 1.10, pulled from source today.
I execute this improper request:
box.schema.user:passwd()
The result is:
tarantool: /home/pgulutzan/tarantool-1.10/src/lua/utils.c:899: luaT_error: Assertion `e != NULL' failed.

**Comment by locker** [comment]
Fixed by ac77418fc53bccb46eb8b8f8e2853dcb079f53a0
