### ISSUE TITLE
Add gcc-7 and gcc-8 targets into CI

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#3660]
As #3658 shows we don't catch mistakes that triggers build time errors only on gcc-7 and newer. Such target should be added into CI, I think.

**Comment by ligurio** [comment]
Also: enable ` -Werror` for all tarantool sources (enabled with Release build on Travis, make sure we have it on GitLab CI.

**Comment by Totktonada** [comment]
See also c308f35d8807dd08d8c0b6e281fa2391d3c31161.

**Comment by Totktonada** [comment]
See also #4941.

**Comment by avtikhon** [comment]
We already have packages build/deploy on CentOS 7 for all release branches where gcc-8 is in use:
https://gitlab.com/tarantool/tarantool/-/jobs/778136873#L2059
```
Tarantool 2.6.0-143-g0dc7281
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_BACKTRACE=ON
Compiler: /opt/rh/devtoolset-8/root/usr/bin/cc /opt/rh/devtoolset-8/root/usr/bin/c++
C_FLAGS:-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type
CXX_FLAGS:-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type
```

**Comment by Totktonada** [comment]
Packages are built without -Werror AFAIR. It is intentional:

https://github.com/tarantool/tarantool/blob/0dc72812fb78a192945612f0e954026a0ffe4053/cmake/compiler.cmake#L372-L382

**Comment by avtikhon** [comment]
Discussed with @Totktonada and @sergos the current process of deploying packages. Found that the root cause of the disabled '-Werror' flag in packages build was that in previous packages builds were not checked in CI before deploying. Agreed that for now this flag can be set by default in packages builds with patch:
```
diff --git a/rpm/tarantool.spec b/rpm/tarantool.spec
index eedc031..04d41a4 100644
--- a/rpm/tarantool.spec
+++ b/rpm/tarantool.spec
@@ -160,6 +160,7 @@ C and Lua/C modules.
          -DSYSTEMD_UNIT_DIR:PATH=%{_unitdir} \
          -DSYSTEMD_TMPFILES_DIR:PATH=%{_tmpfilesdir} \
 %endif
+         -DENABLE_WERROR:BOOL=ON \
          -DENABLE_DIST:BOOL=ON
 make %{?_smp_mflags}
 
```
After this change these builds can be used for compilers testings like the current issue #3660 and issue on default compiler #4941

**Comment by kyukhin** [comment]
Done.

**Comment by Totktonada** [comment]
I don't see such jobs in CI. Please, clarify, where it was done or close with another reason.

**Comment by Totktonada** [comment]
`-Werror` was intentionally not enabled during packages build, so I didn't expect that we'll do it (especially without any consistency between RPM / Deb packages). But okay, gcc-8 is covered so.
