### ISSUE TITLE
Instance is not found in /usr/local/etc/tarantool/instances.available ?

### ISSUE THREAD

**Issue by vanessasmith** [tarantool/tarantool#3661]
Hi, I am having trouble running tarantool 101 tutorial, 

do you know if the tutorial works or if it is outdated?

https://dzone.com/articles/tarantool-101-guide-2-build-yourself-an-ip-logging

tarantoolctl asks for a file in and path that is not in the tutorial: 
 /usr/local/etc/tarantool/instances.available

the tutorial says: 
create  config file in /usr/share/tarantool/   , 
and the app in /etc/tarantool/instances.enabled/, 
then use tarantool check iplogger, 
and tarantool start iplogger

but this error appears:

# tarantoolctl check /usr/share/tarantool/iplogger.lua
Instance iplogger is not found in /usr/local/etc/tarantool/instances.available
# tarantoolctl check /etc/tarantool/instances.enabled/iplogger.lua
Instance iplogger is not found in /usr/local/etc/tarantool/instances.available
# tarantoolctl start iplogger
Instance iplogger is not found in /usr/local/etc/tarantool/instances.available
# tarantoolctl status iplogger
Instance iplogger is not found in /usr/local/etc/tarantool/instances.available

what file goes in  /usr/local/etc/tarantool/instances.available ?

A) if I do:
#cp  /etc/tarantool/instances.enabled/iplogger.lua  /usr/local/etc/tarantool/instances.available/ then
# tarantoolctl check /etc/tarantool/instances.enabled/iplogger.lua
File '/usr/local/etc/tarantool/instances.available/iplogger.lua' is OK
#tarantoolctl check /usr/share/tarantool/iplogger.lua
File '/usr/local/etc/tarantool/instances.available/iplogger.lua' is OK
# tarantoolctl start iplogger
Starting instance iplogger...
Forwarding to 'systemctl start tarantool@iplogger'
Job for tarantool@iplogger.service failed because the control process exited with error code.
See "systemctl status tarantool@iplogger.service" and "journalctl -xe" for details.
# systemctl status tarantool@iplogger.service
● tarantool@iplogger.service - Tarantool Database Server
   Loaded: loaded (/lib/systemd/system/tarantool@.service; indirect; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2018-09-03 18:21:52 UTC; 39s ago
     Docs: man:tarantool(1)
  Process: 4584 ExecStart=/usr/bin/tarantoolctl start iplogger (code=exited, status=1/FAILURE)
 Main PID: 4584 (code=exited, status=1/FAILURE)
   Status: "running"

 systemd[1]: tarantool@iplogger.service: Main process exited, code=exited,
systemd[1]: tarantool@iplogger.service: Failed with result 'exit-code'.
 systemd[1]: Failed to start Tarantool Database Server.
systemd[1]: tarantool@iplogger.service: Service hold-off time over, sched
systemd[1]: tarantool@iplogger.service: Scheduled restart job, restart co
systemd[1]: Stopped Tarantool Database Server.
systemd[1]: tarantool@iplogger.service: Start request repeated too quickl
systemd[1]: tarantool@iplogger.service: Failed with result 'exit-code'.
systemd[1]: Failed to start Tarantool Database Server.
systemd[1]: tarantool@iplogger.service: Start request repeated too quickl

systemd[1]: Tarantool@iplogger.service: Failed with result 'exit-code'.
systemd[1]: Failed to start Tarantool Database Server.
-- Subject: Unit tarantool@iplogger.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Unit tarantool@iplogger.service has failed.
--
-- The result is RESULT.

B) IF I do the opposite, copying the other iplogger.lua file:
#cp  /usr/share/tarantool/iplogger.lua  /usr/local/etc/tarantool/instances.available/iplogger.lua
tarantoolctl start iplogger
Starting instance iplogger...
Forwarding to 'systemctl start tarantool@iplogger'
Job for tarantool@iplogger.service failed because the control process exited with error code.
See "systemctl status tarantool@iplogger.service" and "journalctl -xe" for details.
 tarantool@iplogger.service - Tarantool Database Server
   Loaded: loaded (/lib/systemd/system/tarantool@.service; indirect; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2018-09-03 18:34:52 UTC; 50s ago
     Docs: man:tarantool(1)
  Process: 4749 ExecStart=/usr/bin/tarantoolctl start iplogger (code=exited, status=1/FAILURE)
 Main PID: 4749 (code=exited, status=1/FAILURE)
   Status: "running"

 systemd[1]: tarantool@iplogger.service: Main process exited, code=exited,
 systemd[1]: tarantool@iplogger.service: Failed with result 'exit-code'.
systemd[1]: Failed to start Tarantool Database Server.
 systemd[1]: tarantool@iplogger.service: Service hold-off time over, sched
systemd[1]: tarantool@iplogger.service: Scheduled restart job, restart co
systemd[1]: Stopped Tarantool Database Server.
systemd[1]: tarantool@iplogger.service: Start request repeated too quickl
systemd[1]: tarantool@iplogger.service: Failed with result 'exit-code'.
systemd[1]: Failed to start Tarantool Database Server.

tarantoolctl[4956]:         no file '/usr/local/lib/lua/5.1/http.so'                            <----------------?

 systemd[1]: tarantool@iplogger.service: Main process exited, code=exited,
systemd[1]: tarantool@iplogger.service: Failed with result 'exit-code'.
 systemd[1]: Failed to start Tarantool Database Server.
-- Subject: Unit tarantool@iplogger.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Unit tarantool@iplogger.service has failed.
--
-- The result is RESULT.
 systemd[1]: tarantool@iplogger.service: Service hold-off time over, sched
systemd[1]: tarantool@iplogger.service: Scheduled restart job, restart co
-- Subject: Automatic restarting of a unit has been scheduled
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Automatic restarting of the unit tarantool@iplogger.service has been scheduled, as the result for
-- the configured Restart= setting for the unit.
systemd[1]: Stopped Tarantool Database Server.
-- Subject: Unit tarantool@iplogger.service has finished shutting down
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Unit tarantool@iplogger.service has finished shutting down.
 tarantool@iplogger.service: Start request repeated too quickl
tarantool@iplogger.service: Failed with result 'exit-code'.
Failed to start Tarantool Database Server.
-- Subject: Unit tarantool@iplogger.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Unit tarantool@iplogger.service has failed.
--

thank you

**Comment by evanbates** [comment]
Hi, it was written that way to eliminate a step, i.e. the step of putting the file in "instances.available" and then creating a symlink to "instances.enabled" (similar to NGINX). In the interim, Tarantool has become more strict on the issue. So the thing to do is 
1. create the file in "instances.available," (step 1 should be "nano /etc/tarantool/instances.available/iplogger.lua")
2. Make a symlink: "ln -s /etc/tarantool/instances.available/iplogger.lua /etc/tarantool/instances.enabled"
3. After that the "tarantoolctl check" statements should pass.

p.s.  you also need to make sure to have the "http" module installed. This was part of 101 Part 1, but the easiest way to install it is with the cmake directions here: https://github.com/tarantool/http, like so: 
   git clone https://github.com/tarantool/http.git
   cd http && cmake . -DCMAKE_BUILD_TYPE=RelWithDebugInfo 
   make
   make install

Let me know if you have any additional questions!

**Comment by evanbates** [comment]
Changes also made in tutorial itself...

**Comment by vanessasmith** [comment]
it works!
thank you
