### ISSUE TITLE
yaml.encode uses multiline format for 'false' and 'true'

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#3662]
After #3476 yaml.encode() encodes 'false' and 'true' correctly, but uses multiline encoding, which just spends screen area:

```
defaultValue: |-
  false
```

Expected:

```
defaultValue: 'false'
```

**Comment by kyukhin** [comment]
@Totktonada could you pls take a look at the branch?

**Comment by olegrok** [comment]
@kyukhin 

Cherry-pick to 1.10 pls
