### ISSUE TITLE
any successful build on unikernel ?

### ISSUE THREAD

**Issue by wprayudo** [tarantool/tarantool#3663]
is there a clear guidance for building tarantool in unikernels ?

best regards

**Comment by kyukhin** [comment]
Feel free to ask your questions in:
- Telegram channel
    - (Russian) https://t.me/tarantoolru
    - (English) https://t.me/tarantool
- Google groups
    - (Russian) https://groups.google.com/forum/#!forum/tarantool-ru
    - (English) https://groups.google.com/forum/#!forum/tarantool
