### ISSUE TITLE
sql: allow to fire VDBE programs outside SQL

### ISSUE THREAD

**Issue by Korablev77** [tarantool/tarantool#3674]
To enable SQL triggers, foreign keys and value constraint checks outside SQL-land, we must allow to run VDBE programs as Tarantool native triggers. For instance:

`CREATE TRIGGER r3 INSTEAD OF UPDATE ON v1 BEGIN INSERT INTO t2 VALUES(NEW.x); END;`

This statement results in insertion to `_trigger` system space, which in its turn should lead to creation of *native* trigger on `v1` space. This *native* trigger should fire SQL trigger (i.e. VDBE program implementing trigger's logic) on each update of space `v1`. In this respect, SQL triggers will be fired always, regardless source of incoming rows (SQL or Lua).

**Comment by Korablev77** [comment]
@locker you accidentally closed wrong ticket. This one is not implemented yet.

**Comment by kostja** [comment]
A duplicate of gh-3691
