### ISSUE TITLE
socket bind error return value

### ISSUE THREAD

**Issue by rosik** [tarantool/tarantool#3676]
[Doc](https://tarantool.io/en/doc/1.9/reference/reference_lua/socket/#lua-function.socket_object.bind) says:
```
    Possible errors: Returns nil, status, errno, errstr on error.
```

Reality (Tarantool 1.10.1-350-gad6a24985) says:
```
tarantool> sock = require('socket')('AF_INET', 'SOCK_STREAM', 'tcp')
---
...

tarantool> sock:bind('0.0.0.0', 22) -- port 22 is taken by ssh
---
- false
...

```

I do not know whether it's problem of doc or tarantool itself

**Comment by Totktonada** [comment]
sock:errno() and sock:error() will give an actual error. But the doc looks like it should be returned from the function, you are right. I don't know what should be changed too.

**Comment by rosik** [comment]
This is an appropriate solution. I move the issue to https://github.com/tarantool/doc/issues/613
