### ISSUE TITLE
Error message about undeclared identifier

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#3677]
I have FreeBSD 11. I have Tarantool 2.0, pulled from source today.
To build, I use gcc and cmake and gmake. The gmake fails, saying
/home/pgulutzan/tarantool-2.0/src/say.c:501:22: error: use of undeclared identifier 'IPPROTO_UDP'
If I add this line after line 47 of say.c
#include <netinet/in.h>
then gmake succeeds, and tarantool executable seems okay as far as I can tell.

**Comment by kyukhin** [comment]
@pgulutzan still reproduces?

**Comment by pgulutzan** [comment]
yes

**Comment by locker** [comment]
Fixed by 311e8fce90011fd7aad930c02b79804d2d6050f7
