### ISSUE TITLE
Add lua_tonumberx and lua_tointegerx to exports

### ISSUE THREAD

**Issue by edam** [tarantool/tarantool#3680]
The version of luajit bundled with tarantool 1.9.2 includes the symbols:

    lua_tointegerx
    lua_tonumberx

which are not included in `extra/exports` and can not be dynamically linked against by lua libraries (such as https://github.com/starwing/lua-protobuf).

Also, FYI, a diff of exported symbols from the current luajit (3de8f28) against those in `extra/exports` shows the following discrepancies... (see also #2419)

    +lua_atpanic
    +lua_close
    -lua_copy
    +lua_dump
    +lua_error
    +lua_gethook
    +lua_gethookcount
    +lua_gethookmask
    +lua_getinfo
    +lua_getlocal
    +lua_getstack
    -lua_hash
    -lua_hashstring
    -lua_isyieldable
    +lua_load
    +lua_loadx
    +lua_newstate
    +lua_sethook
    +lua_setlocal
    -lua_tointegerx
    -lua_tonumberx
    -lua_version

**Comment by Totktonada** [comment]
Symbols we don't export from luajit:

```
-lua_copy
-lua_hash
-lua_hashstring
-lua_isyieldable
-lua_tointegerx
-lua_tonumberx
-lua_version
```

Group them by the Lua API version introduces the symbol:

Lua 5.2:
- lua_copy
- lua_tointegerx
- lua_tonumberx
- lua_version

Lua 5.3:
- lua_isyieldable

Not a Lua API:
- lua_hash / lua_hashstring (see [commit](1))

Tarantool (as well as LuaJIT) supports Lua 5.1. lua-protobuf supports lua 5.1 too, check the [code](2) (it is under `#if LUA_VERSION_NUM < 502`).

I tried to install lua-protobuf from the [rockspec](3) using `tarantoolctl rocks install` (it installs pb.so into a location where tarantool cannot find it, but it is a separate issue) and `luarocks install` (successfully). Then I successfully run the [example](4) (with replacing `require "serpent".block` with `require('yaml').encode`).

@edam So, what steps you perform and what is going wrong with lua-protobuf?

[1]: https://github.com/tarantool/luajit/commit/b8587fafa36b417194b208d747e1f2be1faf19be
[2]: https://github.com/starwing/lua-protobuf/blob/1d7625cb1efa97694509a725bd0edbdfafbbc318/pb.c#L54
[3]: https://github.com/starwing/lua-protobuf/blob/7704b82d79de3501de81027e41dc5f6ea78c80cd/rockspecs/lua-protobuf-scm-1.rockspec
[4]: https://github.com/starwing/lua-protobuf#example

**Comment by edam** [comment]
Fair enough.

I think lua-protobuf actually approximates `lua_tonumberx()` when it isn't available (i.e., `LUA_VERSION_NUM < 502`). And it isn't perfect (e.g., it won't detect that the string `"0"` has been correctly converted). And this is the same for any other library, unless they implement their own `lua_tonumberx()`, so it still might be worth adding to the exports lists.

**Comment by Totktonada** [comment]
For the reference: lua_tonumber and lua_tonumberx [code][1]; lua_tointeger and lua_tointegerx [code][2].

It seems that lua_tointegerx set `ok` to 1 when truncates double to integer, so "0" is only case in which *x functions help. Right implementations of *x functions for Lua 5.1 should check this case manually, I think. I would consider it as lua-protobuf bug (look at the code, I fixed the link in my previous message).

Second point: even if we'll export these functions we still report LUA_VERSION_NUM as 501 and lua-protobuf will not use them. Only modules that are written specifically for luajit and/or tarantool will able to use them.

@edam So, what is the problem we trying to solve here?

1. If it is lua-protobuf behaviour, so it should be an issue in lua-protobuf to fix it against Lua 5.1 compliant lua implementations.
2. If it is about other modules around lua land, they will not use *x functions when linked against luajit/tarantool, so we cannot solve it from our side.
3. If it is about tarantool-specific module we should decide anything after seeing certain cases and I don't know one.

[1]: https://github.com/tarantool/luajit/blob/3de8f282ab6c50270e6fd0db2c9f7fc9f6277f9b/src/lj_api.c#L333-L359
[2]: https://github.com/tarantool/luajit/blob/3de8f282ab6c50270e6fd0db2c9f7fc9f6277f9b/src/lj_api.c#L385-L435

**Comment by kyukhin** [comment]
No answer for years.

**Comment by peick** [comment]
I have the same problem with tarantool 2.10:

The function lua_tonumberx is not exported as a symbol in the tarantool executable (see `extra/exports`). The library `lua-protobuf` cannot be used after installation with `tarantool rocks make ...`, because there's this error:

```
echo 'require("pb")' | tarantool
LuajitError: module 'pb' not found:
	no field package.preload['pb']
	no file '/opt/product/pb.lua'
	no file '/opt/product/pb/init.lua'/opt/product/pb.so: undefined symbol: lua_tointegerx
	no file '/opt/product/.rocks/share/tarantool/pb.lua'
	no file '/opt/product/.rocks/share/tarantool/pb/init.lua'
	no file '/opt/.rocks/share/tarantool/pb.lua'
	no file '/opt/.rocks/share/tarantool/pb/init.lua'
```

**Comment by Totktonada** [comment]
> Unfortunately the function is mentioned in `/usr/include/tarantool/lua.h` although not exported.

@peick That looks as the problem or at least inconsistency. Can you verify, please, that removing them from the header allows the `lua-protobuf` module to compile and work correctly?

**Comment by peick** [comment]
> Can you verify, please, that removing them from the header allows the lua-protobuf module to compile and work correctly?
Did not work, because `lua-protobuf` does this:

```
// pb.c
#if LUA_VERSION_NUM < 502

#ifndef luaL_newlib /* not LuaJIT 2.1 */
#define luaL_newlib(L,l) (lua_newtable(L), luaL_register(L,NULL,l))

// here lua-protobuf declare their implementation of lua_tointegerx and lua_tonumberx
static lua_Integer lua_tointegerx(lua_State *L, int idx, int *isint) { ... }

static lua_Number lua_tonumberx(lua_State *L, int idx, int *isnum) { ... }

static void *luaL_testudata(lua_State *L, int idx, const char *type) { ... }
#endif
```

tarantool has `LUA_VERSION_NUM 501` and `luaL_newlib` defined in its `lua.h`.
