### ISSUE TITLE
Duplicate unique key causes deletion

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#3683]
I have Ubuntu 18.04. I have Tarantool 2.0, pulled from source today.
I execute these statements:
CREATE TABLE t (s1 CHAR(1) PRIMARY KEY, s2 INT UNIQUE);
REPLACE INTO t VALUES ('A',2),('b',2);
SELECT * FROM t;
The result is: 'b',2.

**Comment by Korablev77** [comment]
This is expected behaviour. `REPLACE` (or its alias `INSERT OR REPLACE`) causes deletion and insertion to all unique indexes.

**Comment by pgulutzan** [comment]
Korablev77 is correct. I was confused by the title of issue#2963 "sql: ban ON CONFLICT REPLACE for secondary indexes", This is not banned. So the error was in the documentation. Sorry. I'll close.
