### ISSUE TITLE
Give an error when wrong CMAKE_BUILD_TYPE was passed

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#3686]
We have the following targets:

- Debug;
- RelWithDebInfo;
- Rel (in `FreeBSD/databases/tarantool/Makefile`) or Release (in `README.MacOSX`);
- RelWithDebInfoWError (will be after #3238).

We should choose btw Rel or Release and forbid values other the above.

**Comment by Totktonada** [comment]
RelWithDebInfoWError was gone in c308f35d8807dd08d8c0b6e281fa2391d3c31161.

**Comment by Totktonada** [comment]
NB: It seems, `CMAKE_BUILD_TYPE` is considered as case insensitive:

https://github.com/llvm/llvm-project/blob/699396131f745ec8b42ae33cb0e4553a783b6674/llvm/CMakeLists.txt#L371-L376
https://lists.llvm.org/pipermail/llvm-commits/Week-of-Mon-20150810/292471.html

**Comment by mkostoevr** [comment]
Closed with #9354, the valid build configs are: `Debug`, `Release`, `RelWithDebInfo` and `MinSizeRel` (as per [CMake documentation](https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html)).

Note, the build type is case-sensitive.

The `Rel` config is used in the [FreeBSD/databases/tarantool/Makefile](https://github.com/tarantool/tarantool/blob/7828ac3b4860e9208e871d671ddc4c328d136fc8/FreeBSD/databases/tarantool/Makefile#L55), but the file is outdated and is not used anymore. This build type is either a misspelling or an old config supported by CMake in times of Tarantool 1.6.8.
