### ISSUE TITLE
Segmentation fault on SIGHUP

### ISSUE THREAD

**Issue by sorc1** [tarantool/tarantool#3690]
Tarantool always breaks with segmentation fault on SIGHUP.

bisect: 9f99bc626dcc0 ("say: Wrap logrotate signal handler with ev_signal").

**Comment by GeorgyKirichenko** [comment]
Please attach a minimal case to reproduce

**Comment by Gerold103** [comment]
Closed in https://github.com/tarantool/tarantool/commit/c9f36fb9e4589f903324e0108954c4a545588407
