### ISSUE TITLE
Make SQL Checks on server side

### ISSUE THREAD

**Issue by kshcherbatov** [tarantool/tarantool#3691]
As a part of DD integration we have to make SQL constraints checks on server sade same as SQL does.
Relative task to #3674

**Comment by kshcherbatov** [comment]
In the current architecture checks are performed before implicit type conversion on the side of the SQL.  
E.g.
```
CREATE TABLE t2(
          id  INT primary key,
          x INTEGER CONSTRAINT one CHECK( typeof(coalesce(x,0))=='integer'),
          y REAL CONSTRAINT two CHECK( typeof(coalesce(y,0.1))=='real' ),
          z TEXT CONSTRAINT three CHECK( typeof(coalesce(z,''))=='text' )
        );

 INSERT INTO t2 VALUES(3, 1.1, NULL, NULL);
```
With the movement of checks to the server side, they are made after the casting and backward compatibility cannot be provided. Perhaps, It would be not relevant with tiket:
https://github.com/tarantool/tarantool/issues/3809

**Comment by Korablev77** [comment]
@kshcherbatov

Unfortunately, mentioned issue is not related to this one: it doesn't affect order of checks.

**Comment by kshcherbatov** [comment]
@pgulutzan Hi!
Tell me please, Is the UPDATE {or IGNORE, ABORT, FAIL} ANSI-SQL an extension to the ANSI standard that we may get rid of?

**Comment by pgulutzan** [comment]
Yes.
