### ISSUE TITLE
sql: introduce conventional <DATE> and <TIME> types

### ISSUE THREAD

**Issue by Korablev77** [tarantool/tarantool#3694]
Originally, SQLite doesn't provide separate type to hold datetime data. To be more precise, in SQLite you can declare column with \<DATETIME> type and store there floats as well as strings.
To support ANSI we should introduce separate type which would accept only given format.

> DATE.
> Range: '0001-01-01' to '9999-12-31'.
> Proleptic Gregorian; invalid dates cause errors.
> Literals can have the form '0001-01-01' (the
> actual requirement is DATE '0001-01-01' but nobody
> bothers with that).
> (updated comment: nobody will mind negative dates.)
> 
> TIME.
> Range: '00:00:00' to '23:59:59'.
> No need for fractions of seconds, they're optional.
> 
> TIMESTAMP.
> Range: '0001-01-01 00:00:00' to '9999-12-31 23:59:59'.
> (updated comment: nobody will mind negative dates)

To get more information see:
SQL ANSI 2011 Part 2: Foundation (SQL/Foundation)
4.6 Datetimes and intervals

**Comment by Totktonada** [comment]
We can use ICU facilities to convert dates from / to internal format.

**Comment by Totktonada** [comment]
DATETIME is non-standard and should be removed. TIMESTAMP should be supported instead.

**Comment by Korablev77** [comment]
We've removed support of DATE/TIME from parser alongside with built-in functions as a part of #4019. List of tests from suite which are affected and ergo partially or completely disabled (so they to be re-enabled after this issue is resolved):
sql-tap/date.test.lua (completely)
sql-tap/table.test.lua (table-13.1)
sql-tap/tkt3791.test.lua (completely)
sql-tap/tkt-bd484a090c.test.lua (completely)
sql-tap/tkt2192.test.lua (tkt2192-1.1 and tkt2192-1.2)

**Comment by Totktonada** [comment]
I'm going to disable sql-tap/debug_mode_only.test.lua. See https://github.com/tarantool/test-run/pull/299#issuecomment-842679378.

**Comment by tsafin** [comment]
Closed by #6773
