### ISSUE TITLE
sql: remove opportunity to turn off integrity constraints at runtime 

### ISSUE THREAD

**Issue by Korablev77** [tarantool/tarantool#3696]
Originally, SQLite provides opportunity to disable foreign keys, triggers and value check constraints right at runtime using `pragma foreign_keys`, `pragma ignore_check_constraints` and `pragma recursive_triggers`.
We've decided to remove support of this feature for several reasons. Firstly, they are unlikely to be carefully tested (within our test suite). Secondly, when we introduce prepared statements, it will be quite complicated to synchronise this option during query compilation and at VDBE runtime. Finally, it breaks original idea of integrity constraints: if user disables them, provides data manipulations which in turn break data integrity and eventually turns them on, nothing good will happen at all.

**Comment by Khatskevich** [comment]
I do not think that we should delete recursive triggers. Those can be useful.
Though postgres and db2 allow those, the only restriction is recursion depth.

**Comment by Korablev77** [comment]
@Khatskevich 
Is it possible to turn them off/on at runtime? Or they are simply always enabled? If they are always enabled, lets make our triggers to be always recursive. Other option is to specify type of trigger (recursive/non-recursive) during its creation, like: `CREATE RECURSIVE TRIGGER ...`

**Comment by Khatskevich** [comment]
It is possible to turn them on at runtime. By default, they are turned off.

**Comment by Khatskevich** [comment]
It was decided to just leave the rec_triggers be enabled by default.
