### ISSUE TITLE
Csv example does not work

### ISSUE THREAD

**Issue by makorne** [tarantool/tarantool#3702]
https://github.com/tarantool/tarantool/wiki/Lua-interface-for-CSV-parser

```
...

tarantool> csv = require('csv')
---
...

f = require("fio").open("example.txt", { "O_WRONLY", "O_TRUNC" , "O_CREAT"}, 0x1FF)

---
...

tarantool> for i=0,14,3 do    t = {i, i + 1, i + 2} ;  s = csv.dump(t, f) ; end
---
...

tarantool> f = require("fio").open("example.txt", { "O_RDONLY"})
---
...

tarantool> for i, tup in csv.iterate(f) do   print(tup[1], tup[2], tup[3]); end
---
- error: 'builtin/csv.lua:102: attempt to index local ''readable'' (a nil value)
```

**Comment by Totktonada** [comment]
Thanks for the report!

A file handle is the third parameter of csv.dump() (the second one is table of options or nil). The wiki page was fixed.

**Comment by makorne** [comment]
Example was not changed and is still wrong :

```
    f = require("fio").open("example.txt", { "O_RDONLY"})
```

**Comment by Totktonada** [comment]
The change I made in September:

-csv.dump(multiline_header, f)
+csv.dump(multiline_header, nil, f)

Just checked and it works for me.

Reading example, which you cite now, works too. The error means that you were get `nil` intead a file handle. You can show an error like so:

```
f, err = require("fio").open("example.txt", { "O_RDONLY"})
err
```

I guess that it is mistype of a file name.
