### ISSUE TITLE
ddl changes values of sql changes and total_changes

### ISSUE THREAD

**Issue by Khatskevich** [tarantool/tarantool#3706]
do not change total_changes on ddl

**Comment by Korablev77** [comment]
Please, argue your idea. As far as I remember, it was made on purpose, in order to return rowcount as 1 on DDL requests (via IProto). See Vdbe->nChange and OPFLAG_NCHANGE.

**Comment by Gerold103** [comment]
Nikita is right. We made row_count on DDL deliberately in order to flag that DDL actually was done. Also row_count == 0 can be returned if IF NOT EXISTS was used, but a DDL object was existing.

**Comment by Korablev77** [comment]
Since there is no any explicit contradictions, I will close this ticket.
