### ISSUE TITLE
Return null in case space:get doesn't find anything

### ISSUE THREAD

**Issue by Khatskevich** [tarantool/tarantool#3716]
`space:get()` returns tuple if it is found and nothing otherwise.
This is inconsistent and affects functions which pass the result of `get` function directly to a
c written code.

E.g. console prints
```
---
```
instead of 
```
---
- null
```

**Comment by Mons** [comment]
`:get()` currently returns Lua nil in case of key absence.
This could be easily checked with `if`, or there is `or default` pattern:
```lua
local val = sp:get( ... ) or { default... }
```
Such change will break all of them, since box.NULL is true.
