### ISSUE TITLE
Assertion if update

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#3719]
I have Ubuntu 18.04. I have Tarantool 2.0, pulled from source today.
I execute these statements:
create table tj (s1 int primary key);
insert into tj values (1);
update tj set s1 = 1;
The result is:
tarantool: /home/pgulutzan/tarantool-2.0/src/box/sql/vdbe.c:4076: sqlite3VdbeExec: Assertion `pC!=0' failed.
Aborted (core dumped)
pgulutzan@pgulutzan-Virtu

**Comment by kyukhin** [comment]
Closed by cebcf21114f50141e8aa0a72f30ea47dfbfef16c
