### ISSUE TITLE
sql: crash trying to re-register a function that is running

### ISSUE THREAD

**Issue by ztarvos** [tarantool/tarantool#3724]
I was exploring the possibilities to trigger delay via SQL (for test purposes) and caught a tarantool crash.
It occurs when I attempt to re-register the SQL function while it is being run on another connection.

Steps to reproduce:

1. Open two separate console connections to tarantool (2.0)

2. In the first console do: 

```
box.internal.sql_create_function('WAITFOR', function (n) require('fiber').sleep(n) return n end)

box.sql.execute('select WAITFOR(30)')

```

3. Don't wait for the last command to complete. Instead, while 30 sec last, in the second console do:

`box.internal.sql_create_function('WAITFOR', function (n) require('fiber').sleep(n) return n end)`

4. Tarantool crashes
```
#0  0x5200fe in print_backtrace+9
#1  0x40cbd4 in _ZL12sig_fatal_cbiP9siginfo_tPv+1cb
#2  0x7f3549ba0680 in _L_unlock_13+34
#3  0x543eb6 in lj_vm_returnp+19
#4  0x565798 in lua_call+b4
#5  0x4eaf55 in execute_lua_eval+1cf
#6  0x543e1b in lj_BC_FUNCC+34
#7  0x565910 in lua_pcall+176
#8  0x5084db in luaT_call+29
#9  0x4eb2af in box_process_lua+9c
#10 0x4eb31f in box_lua_eval+28
#11 0x4e91f9 in box_process_eval+54
#12 0x412534 in _ZL15tx_process_callP4cmsg+ce
#13 0x522709 in cmsg_deliver+30
#14 0x5236b7 in fiber_pool_f+19a
#15 0x40c615 in _ZL16fiber_cxx_invokePFiP13__va_list_tagES0_+1e
#16 0x51d182 in fiber_loop+7c
#17 0x6e35ad in coro_init+4c
```

**Comment by Korablev77** [comment]
Hello. Thanks for bug reporting. Unfortunately, I can't reproduce your case. I do this:

Main console:
```
box.cfg{}
console = require('console')
console.listen('127.0.0.1:3303')
```

1 console:
```
console = require('console')
console.connect('localhost:3303')
box.internal.sql_create_function('WAITFOR', function (n) require('fiber').sleep(n) return n end)
box.sql.execute('select WAITFOR(30)')
```

2 console:
```
console = require('console')
console.connect('localhost:3303')
box.internal.sql_create_function('WAITFOR', function (n) require('fiber').sleep(n) return n end)
```

And nothing happens both on debug/release builds of fresh 2.0 (MacOS + clang). Could you, please, check if it still appears to you on very fresh 2.0. If so, could you provide information concerning your setup?

Anyway, it looks like LuaJIT issue, rather than SQL.

**Comment by Totktonada** [comment]
I have it reproduced on 2.1.0-3-g6ca97fd5a (Debug build).
