### ISSUE TITLE
Tarantool crashes on vshard startup (lj_gc_step)

### ISSUE THREAD

**Issue by sharonovd** [tarantool/tarantool#3725]
Crash appears randomly during storage start. Stack trace differs, but it always relates to lj garbadge collection. One example: 

Attempting backtrace... Note: since the server has already crashed, 
this may fail as well
#0 0x4e93d9 in print_backtrace+9
#1 0x40f427 in _ZL12sig_fatal_cbiP9siginfo_tPv+c7
#2 0x7f78198f16d0 in _L_unlock_13+34
#3 0x50175c in gc_traverse_trace.part.1+8c
#4 0x501dfc in propagatemark+5dc
#5 0x502654 in lj_gc_step+54
#6 0x4fe5fc in lj_BC_TNEW+67
#7 0x4c8048 in _ZL27box_lua_space_new_or_deleteP7triggerPv+618
#8 0x4f7a52 in trigger_run+32
#9 0x496164 in _ZL18alter_space_commitP7triggerPv+54
#10 0x4f7a52 in trigger_run+32
#11 0x4a8fa7 in txn_commit+127
#12 0x4af38f in _ZL22apply_initial_join_rowP7xstreamP11xrow_header+6f
#13 0x4bd136 in xstream_write+6
#14 0x4be520 in _ZL9applier_fP13__va_list_tag+370
#15 0x40e91c in _ZL16fiber_cxx_invokePFiP13__va_list_tagES0_+c
#16 0x4e6140 in fiber_loop+30
#17 0x6127af in coro_init+3f

Tarantool version: 1.7.7

Workaround: call gc manually prior to calling vshard.cfg

@GeorgyKirichenko has more details, if necessary.

**Comment by kyukhin** [comment]
Might be connected w/ #3751

**Comment by Totktonada** [comment]
Fixed in https://github.com/tarantool/luajit/commit/d92380ffa50098bc0a1eec3d1c0b6cd404591fcf and propagated into tarantool in be0506db66976ab85cdc05d497a19a8d4e39d2ac (2.1) and e5e259a82f8ef771818b97f5f8ca8ab601e9e2c4 (1.10).
