### ISSUE TITLE
Debug mode isn't applied to src/box/sql.c

### ISSUE THREAD

**Issue by Korablev77** [tarantool/tarantool#3727]
Subj.

```
make clean
cmake -DCMAKE_BUILD_TYPE=Debug .
make -j
lldb ./src/tarantool
br set -n tarantoolSqlite3IdxKeyCompare
run
box.cfg{}
\set language sql
CREATE TABLE t1 (id INT PRIMARY KEY);
INSERT INTO t1 VALUES (1);
SELECT * FROM t1 WHERE id < 3;
Process 61139 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = breakpoint 3.1
    frame #0: 0x000000010010d960 tarantool`tarantoolSqlite3IdxKeyCompare
tarantool`tarantoolSqlite3IdxKeyCompare:
->  0x10010d960 <+0>:      pushq  %rbp
    0x10010d961 <-126559>: movq   %rsp, %rbp
    0x10010d964 <-126556>: subq   $0xa0, %rsp
    0x10010d96b <-126549>: movq   %rdi, -0x20(%rbp)
Target 0: (tarantool) stopped.
```
Debug symbols appear only if compile with `-DSQL_MAINTAINER_MODE=1` flag.

**Comment by Totktonada** [comment]
We have no any SQL_MAINTAINER_MODE usages across sources. I tried your reproducer on fresh 2.0 (8e94f9713c89d89bda490e7c3cee95a185d04c47) on Debug build on Linux + gdb and things seems to work fine.

Are that reproduced on a fresh 2.0? Build type is Debug? Is non-sql code has debug symbols? If all that are true, so it is something Mac OS (or lldb) specific.

**Comment by Korablev77** [comment]
@Totktonada
Now I see that I really can't reproduce it again (nevertheless, when I created this issue, I definitely managed to reproduce it several times). Moreover, I've checked it on 2.0...
Well, lets close this but if I ever reproduce it again, I will reopen it.
