### ISSUE TITLE
Operation implicitly changes INTEGER to REAL

### ISSUE THREAD

**Issue by ImeevMA** [tarantool/tarantool#3735]
```bash
tarantool> box.sql.execute('SELECT (2147483647*2147483647*2147483647);')
---
- - [9.903520300448e+27]
...
```

As we can see, result of this SELECT is REAL.

Result of this SELECT from other vendors:

**_SQL Server_**:
Arithmetic overflow error converting expression to data type int.

**_MySQL_**:
BIGINT value is out of range in '((2147483647 * 2147483647) * 2147483647)'

**_PostgreSQL_**:
22003: integer out of range

**_SQLite3_**:
9.90352030044798e+27

It works the same way for INSERT and UPDATE:
```bash
tarantool> box.sql.execute('CREATE TABLE a (a INT PRIMARY KEY, b REAL);')
---
...

tarantool> box.sql.execute('INSERT INTO a VALUES (1, 2147483647*2147483647*2147483647);')
---
...

tarantool> box.sql.execute('SELECT * FROM a;')
---
- - [1, 9.903520300448e+27]
...
```

May be it is better to throw an error?

@pgulutzan, can you say what do you think about this?

**Comment by Korablev77** [comment]
Personally I think that implicit conversion from int to float (in this particular case) is not what we deserve at all. I vote for throwing an overflow error. It is sort of obvious, isn't it?

**Comment by Gerold103** [comment]
I vote for an error as well.

**Comment by pgulutzan** [comment]
I agree that is wrong, as the standard document says "If the declared type of both operands of a dyadic arithmetic operator is exact numeric, then the declared type of the result is an implementation-defined exact numeric type ..." and I am assuming nobody wants to implement an exact numeric type that could handle such a large number.

**Comment by ImeevMA** [comment]
Even though this works in a wrong way it allowed us to find another error - #3670 

It may be good idea to test mentioned there statements in patch for this issue.

**Comment by Totktonada** [comment]
I think any implicit cast with precision loss should raise an error. Don't sure whether we should forbid to implicitly cast (INTEGER 42) to (DOUBLE 42.0) and vice versa, but we definitely should forbid to implicitly cast (INTEGER 9223372036854775807) to (DOUBLE 9223372036854775808.0) and (DOUBLE 42.1) to (INTEGER 42). So I propose to treat the issue as bug about precision loss during expression evaluation.

@pgulutzan What do you this about type implicit casting from, say, (INTEGER 42) to (DOUBLE 42.0)? Don't sure about the case to consider here.

**Comment by Korablev77** [comment]
@Totktonada 
Loss during conversion is already covered by this issue: #3809
