### ISSUE TITLE
Assertion after improper index creation

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#3744]
I have Ubuntu 18.04. I have Tarantool 2.0, pulled from source today.
I execute these requests:

sp = box.schema.space.create('tester')
sp:create_index('primary', {parts = {1, 'unsigned' }})
box.space.tester:create_index('O', {unique = false, parts = {2, 'number'} })
box.space.tester:insert{1,-1}
box.space.tester:create_index('I', {unique = false, parts = {{2, 'number',is_nullable=true}}})
box.space.tester:insert{4,nil,7}

The result is:
tarantool: /home/pgulutzan/tarantool-2.0/src/box/tuple_compare.cc:252: int mp_compare_number_with_hint(const char*, mp_type, const char*, mp_type): Assertion `mp_classof(rhs_type) == MP_CLASS_NUMBER' failed.
Aborted (core dumped)

**Comment by locker** [comment]
Fixed by 52b84d2eb0bfa7dae5fba1e4d7015a683bbb65db
