### ISSUE TITLE
[1pt] Tagged releases are not uploaded (extra commit is needed)

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#3745]
https://github.com/travis-ci/travis-ci/issues/7780#issuecomment-302389370

**Comment by Totktonada** [comment]
We have the same problems with modules (say, avro-schema).

**Comment by Totktonada** [comment]
We should also enable tarball and package jobs on tagged revisions, because, say, `if: branch = "master"` does not enable them on tagged revisions.

**Comment by Totktonada** [comment]
We don't push RPM / Deb packages from master since [2.5.0-12-gba206b484](https://github.com/tarantool/tarantool/commit/ba206b484ae691e5816d81a28d38b2a385596479), but we still do this from 2.4 and 1.10 (2.3, 2.2 and 2.1 will not be tagged anymore and are not updated in fact). So the problem should be resolved for Travis CI for 2.4 and 1.10. Or finally disable deploy to packagecloud (#4947).

However the same problem also exist with our GitLab CI rules. See [jobs list](https://gitlab.com/tarantool/tarantool/-/pipelines/167938161) for 2.5.1 tag pipeline.

* Consequence 1: No Deb / RPM packages are deployed for x.y.z.0 commit, a dummy commit is necessary to deploy x.y.z.1. We possibly need a dummy commit as part of the release management process (just to don't mark a common 2.5 and 2.6 ancestor neither with 2.5.1, not with 2.6.0 tags; it would be counter-intuitive) and adding one more dummy commit looks weird. The example without extra dummy commits:

```
* X (branch: master)   * X (branch: 2.5)
|                      |   
* X                    * X 
|                      |   
* X                    * X 
|                      |   
* D (tag: 2.6.0)       * D (tag: 2.5.1)
|                     /   
* X <----------------+
|
* X

X -- regular commit
D -- technical / dummy commit
```

* Consequence 2: RPM / Deb packages are not uploaded into [release repositories](https://github.com/tarantool/doc/issues/1218).

The latter bullet looks important.

@kyukhin Please, schedule to Q3. Let's finally fix it.

**Comment by Totktonada** [comment]
NB: Can a job that is run as result of `git push` see a tag, which appears afterwards as result of `git push --tags`? I don't know whether it is possible when GitLab CI manages a workspace on a runner, but I almost sure it is possible after fca966a28de22b70080004440448e8f8dbb86d68.

See, we deploy into a release repository based of the tag presence on a current commit:

https://github.com/tarantool/tarantool/blob/6d188772309f40fb77d8922c6861fe54743863e4/.gitlab.mk#L124-L127

So it is possible that two jobs will try to deploy the same version: the latter job will fail.

Workaround: `git push`, wait for CI or cancel it, `git push --tags`.

**Comment by avtikhon** [comment]
Right, this solution is workable fine.

Also found that command
```
git name-rev --name-only --tags --no-undefined HEAD
```
after tag arrives returns not only the tag, but and the additional suffix which shows the number of commits before the tag, it means that for the commit that was tagged it will be like:
2.4.2^0
but for commits before it will became
2.4.2~1
2.4.2~2
...
so the suffix check should be added to the tag check line in gitlab-ci script.

**Comment by Totktonada** [comment]
Again (but in short), problems:

- `x.y.z.0` RPM / Deb packages are not deployed to packagecloud on 1.10 and 2.4. Not resolved (but is not important at all).
- `x.y.z.0` RPM / Deb packages are not deployed to live repositories. Should be resolved in 5aa1a1dfe58f39d9024b6e66000a71458a26f3ff by `only: [tags]`.
- `x.y.z.0` RPM / Deb packages may be tried to upload twice (from a push job and from a tag job). Looks actual after 5aa1a1dfe58f39d9024b6e66000a71458a26f3ff.
- `x.y.z.0` source tarballs are not deployed. Same as above.
- `x.y.z.0` RPM / Deb packages are not deployed to *release* repositories. Should be resolved in 5aa1a1dfe58f39d9024b6e66000a71458a26f3ff by using `CI_COMMIT_TAG`.
- `x.y.z.0` RPM / Deb packages may be tried to upload twice. Same as above (I guess that `CI_COMMIT_TAG` appears only in a tag job).

@avtikhon Am I right? Can you share what further actions you want to do within this issue?

**Comment by Totktonada** [comment]
> `x.y.z.0` source tarballs are not deployed.

I don't remember why I did guess that it is so. `only: [tags]` is present on 'sources_deploy' job (over two level of templates). Maybe I just missed it. Anyway, I'll mark it as working above. I suggest to verify that it works when we'll bump next releases.

**Comment by Totktonada** [comment]
Since we use [per-job mirror](https://github.com/tarantool/tarantool/blob/fca966a28de22b70080004440448e8f8dbb86d68/.gitlab-ci.yml#L16-L34) of a repository, it is possible to just drop a tag for a push / branch job (as opposite to tag job) to ensure correctness of git describe output and so correctness of all math based on it (see `BUCKET` variable in `.gitlab.mk` for example). I guess `CI_COMMIT_TAG` variable is only set for tag jobs, so deletion of a tag within the per-job repository mirror when the variable is not defined or empty should do the work.

Alexander (@avtikhon) has doubts about this and want to verify it thoroughly later, so he proposed to forcely deploy to a live repository when git describe says `x.y.z.0`. At least we'll not have failed CI in this case of double deployment. Downside: we can miss `x.y.(z-1).r` deployments from a push / branch job, because it'll build and deploy `x.y.z.0` packages / tarballs in fact. It is acceptable as the temporary solution, I think.

**Comment by Totktonada** [comment]
More detailed description is in the [mailing list](https://lists.tarantool.org/pipermail/tarantool-patches/2020-October/020152.html).

**Comment by Totktonada** [comment]
> - [ ] x.y.z.0 RPM / Deb packages are not deployed to packagecloud on 1.10 and 2.4. Not resolved (but is not important at all).

For the record: it is not resolved, but is not important.

> - [ ] x.y.z.0 RPM / Deb packages may be tried to upload twice (from a push job and from a tag job). Looks broken after 5aa1a1d.

It should be fixed.
