### ISSUE TITLE
Add support for "tarantoolctl rocks doc" subcommand

### ISSUE THREAD

**Issue by rosik** [tarantool/tarantool#3753]
The "rocks doc" subcommand is available in luarocks (https://github.com/luarocks/luarocks/wiki/doc), but cannot be called via tarantoolctl CLI:

```sh
$ tarantoolctl rocks doc

Error: Unknown command: doc
```

Please add the corresponding subcommand to `tarantoolctl rocks` similar to #3525

**Comment by Totktonada** [comment]
Fixed in PR #3842, pushed as 2.1.1-104-g7af4aeb8a.
