### ISSUE TITLE
Separate tarantoolctl rocks apart from tarantoolctl

### ISSUE THREAD

**Issue by rosik** [tarantool/tarantool#3754]
Tarantoolctl rocks does support only several luarocks options.
Some options were added in #2640, #3525, and there is open #3632 and #3753 

Maybe it's time to make `tarantoolctl rocks` a separate utility, say `tarantoolrocks` (name does not matter), which could understand _all_ luarocks options, not only chosen ones.

**Comment by knazarov** [comment]
You can make `tarantoolctl rocks` understand all luarocks options. I don't see any reason to move that to a separate utility, especially if it breaks the public API

**Comment by rosik** [comment]
The only problem is that tarantoolctl parses options itself.

Public API can be kept with something like `tarantoolctl rocks -> os.execute('tarantoolrocks ' .. args)`

**Comment by knazarov** [comment]
It is possible to fix this behavior without modifying any (most of) externally visible stuff.

**Comment by Totktonada** [comment]
I proposed to implement options passthrough to rocks subcommands within the scope of #3632. Are there other things that we should resolve here? If not, I think we can close this issue.
