### ISSUE TITLE
Assertion `relay->state != RELAY_FOLLOW' failed

### ISSUE THREAD

**Issue by rosik** [tarantool/tarantool#3759]
Tarantool version:
```
1.10.2-0-gc0d8063b6 (built from source)
```

OS version:
```
Ubuntu bionic 18.04
4.15.0-36-generic
```

Bug description:
```
tarantool: /opt/tntsrc/src/box/relay.cc:588: void relay_subscribe(replica*, int, uint64_t, vclock*, uint32_t): Assertion `relay->state != RELAY_FOLLOW' failed.
```

**Comment by kyukhin** [comment]
Is there a reproducer?

**Comment by rosik** [comment]
It's not too simple, but it exists. I can share it privately (and logs too).

**Comment by rosik** [comment]
If you assign it to someone, I can share a reproducer directly to that person.

**Comment by rosik** [comment]
Obsolete. I didn't meet it ever again in that 1.5 years, and I've lost the reproducer.
