### ISSUE TITLE
SQL does return either metadata or sql_info, but should both

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#3764]
```Lua
box.cfg{listen = 3313}
netbox = require('net.box')
function push_id() box.space.TEST:insert{box.NULL, 0} box.space.TEST:insert{box.NULL, 0} return true end
box.internal.sql_create_function("push_id", push_id)
box.schema.user.grant('guest','read,write,execute', 'universe')
box.sql.execute('create table test (id integer primary key autoincrement, a integer)')
c = netbox.connect(box.cfg.listen)
c:execute('select push_id()')
```
The last thing returns
```Yaml
---
- metadata:
  - name: push_id()
  rows:
  - [1]
...
```
But should return rowcount = 2 as well. There are two issues:
* SQL response dumper explicitly splits metadata and sql_info via checking 'result column_count > 0' - it should not;
* rowcount does not account Lua and C updates. So `sqlite3_changes` function should be removed, and all changes should be accounted inside box.

First one is trivial, but will not work without the fixed second one. I propose this: add a changes counter to fiber local storage. Then after each commit increment this counter on `txn->n_rows`. It allows to have multiple sequential transactions inside single request. We can rely on fiber local storage because a request (both iproto, Lua, any) can not change its fiber before finish.

**Comment by Korablev77** [comment]
JFYI: if you decide to store change counter within fiber, then this ticket https://github.com/tarantool/tarantool/issues/2181 (which unfortunately is already implemented) will become unnecessary and shouldn't be merged.

**Comment by Gerold103** [comment]
Anyway we should count changes inside box, so #2181 makes no sense in its current implementation. I think, it should be reimplemented via fiber local storage. Lets just reword 2181 issue to make it clear. And after 2181 is implemented, this issue is unblocked. In-box accounting is needed not only buy SQL calling Lua, but also by SQL calling Lua calling SQL again - it will break sqlite3.nChanges counter even now.

By the way, any relocation into box should be consulted with @kostja. The proposal above is just MHO.

**Comment by Korablev77** [comment]
Ok, I'm not against throwing away #2181. What is more, storing change counter within fiber would allow us to account changes made by triggers (and as you already mentioned Lua <-> SQL interconnections).
BTW, personally for me queries like `SELECT push_id()` looks like nightmare...On the one hand nothing criminal here: it may be simple reimplementation of max(), sum() or whatever auxiliary Lua function. On the other hand, if I modify your example a little, Tarantool will get stuck:

```
function push_id() box.space.TEST:insert{box.NULL, 0} box.space.TEST:insert{box.NULL, 0} return true end
box.internal.sql_create_function("push_id", push_id)
\set language sql
create table test (id integer primary key autoincrement, a integer)
select push_id()
select id, push_id() from test;
```

**Comment by Korablev77** [comment]
upd.: I talked today with @kostja and he suggested to separate these issues. It means that now we are pushing #2181 at its current state and later move change counter to fiber to account changes from Lua-land.

**Comment by Gerold103** [comment]
Now @kostja decided to forbid SQL_INFO from DQL. So in other words: a body has either INFO or METADATA, not both. If this decision is final, @ImeevMA, please, do not forget to update https://github.com/tarantool/tarantool/blob/2.1/doc/rfc/3328-wire_protocol.md document. Now in this document it is said that a response can have both INFO and METADATA.
