### ISSUE TITLE
engine/recover_wal.test.lua (vinyl conf) hangs in CI

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#3767]
Tarantool version: 1.10.
OS version: fedora 26, docker, travis-ci.

https://travis-ci.org/tarantool/tarantool/jobs/446308548#L5117

The test hangs on `test_run:cmd('restart server default')`. It is unclear whether test-run blocks on waiting tarantool to stop or to start. It is also unclear whether the problem root within the test or test-run.

**Comment by avtikhon** [comment]
Not reproduced, also Fedora 26 is not testing now. (Latest Fedora 28)
