### ISSUE TITLE
Dirty memory access in SQL

### ISSUE THREAD

**Issue by kshcherbatov** [tarantool/tarantool#3772]
Tarantool version: 2.1

Bug description:
tarantoolSqlite3TupleColumnFast has strange format in cursor,
take a look at:
```
 src/box/sql.c | 1 +
 1 file changed, 1 insertion(+)

diff --git a/src/box/sql.c b/src/box/sql.c
index ab4a587..2b7bc05 100644
--- a/src/box/sql.c
+++ b/src/box/sql.c
@@ -198,6 +198,7 @@ tarantoolSqlite3TupleColumnFast(BtCursor *pCur, u32 fieldno, u32 *field_size)
        struct tuple_format *format = tuple_format(pCur->last_tuple);
        assert(format->exact_field_count == 0
               || fieldno < format->exact_field_count);
+       assert(fieldno < format->field_count);
        if (format->fields[fieldno].offset_slot == TUPLE_OFFSET_SLOT_NIL)
                return NULL;
        const char *field = tuple_field(pCur->last_tuple, fieldno);
-- 
2.7.4
```
and try
```
box.sql.execute("SELECT \"name\" FROM \"_space\"")
```

**Comment by Korablev77** [comment]
I took a quick look at this issue. AFAIU from source code:

```
struct tuple_format {
	...
	/**
	 * If not set (== 0), any tuple in the space can have any number of
	 * fields. If set, each tuple must have exactly this number of fields.
	 */
	uint32_t exact_field_count;
	...
```
For _space it is set to 0:
`- - [280, 1, '_space', 'memtx', 0, ...`

Moreover, assert above supports my thoughts: 
`assert(format->exact_field_count == 0 || fieldno < format->exact_field_count);`

So this doesn't seem to be bug. @Gerold103 Am I right?

**Comment by Gerold103** [comment]
You are totally right, but the issue is about `field_count`. If `exact_field_count` is 0, then `field_count` is the only source of truth. If `exact_field_count` is not 0, then `field_count` is exactly the same.

**Comment by Gerold103** [comment]
If this things are not true, then it is a bug too.

**Comment by Gerold103** [comment]
But stop. I looked into source code and discovered, that exact_field_count can be bigger than field_count easily.

**Comment by Korablev77** [comment]
Hmm, it is kind of strange...I set breakpoint at `tuple_field_raw()`:
```
uint32_t field_count = mp_decode_array(&tuple);
(lldb) print field_count
(uint32_t) $2 = 7
(lldb) print *format
(const tuple_format) $3 = {
  vtab = {
    tuple_delete = 0x000000010002ff70 (tarantool`memtx_tuple_delete at memtx_engine.c:1183)
    tuple_new = 0x000000010002f780 (tarantool`memtx_tuple_new at memtx_engine.c:1129)
  }
  engine = 0x0000000105000000
  id = 4
  refs = 4
  is_temporary = false
  field_map_size = 0
  exact_field_count = 0
  index_field_count = 1
  min_field_count = 1
  field_count = 1
  dict = 0x0000000103d00bf0
  fields = {}
}
```

**Comment by Gerold103** [comment]
It is allowed to fetch these fields from tuple. It is not allowed to fetch struct tuple_field by such indexes from struct tuple_format, because, obviously, format.fields array is shorter.
