### ISSUE TITLE
pragma sql_compound_select_limit

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#3792]
I have Ubuntu 18.04. I have Tarantool 2.1, pulled from source today.

I execute these statements:
```
PRAGMA sql_compound_select_limit(-1);
SELECT 5 UNION ALL SELECT 6;
-- Result: PRAGMA does not say there is an error, the minus sign is ignored.
```

I execute these statements:
```
PRAGMA sql_compound_select_limit(0);
SELECT 5 UNION ALL SELECT 6;
-- Result: no error, although the limit has been exceeded.
```

I execute these statements:
```
PRAGMA sql_compound_select_limit(+1);
SELECT 5 UNION ALL SELECT 6;
-- Result: "error: Too many UNION or EXCEPT or INTERSECT operations (limit 1 is set)"
```
although the number of UNION operations is 1, which is the limit

I execute this statement:
```
PRAGMA;
```
I do not see what the current setting is for sql_compound_select_limit.

While I'm whining, I'd like to object to the name "sql_compound_select_limit".
The words "compound select" make me think of compound SELECT statements, but
obviously this has nothing to do with compound statements.
The UNION or EXCEPT or INTERSECT operations are done with operators,
often called "set operators" or "table operators", and that is what
we are supposedly counting according to the error message, we are not counting SELECTS.
Anyway, set operators can be used with VALUES statements too.
And why does the "sql_" prefix exist?

Actually I think all PRAGMA statements are bad, but for now will
only suggest that for this particular case (a) the behaviour could be improved
(b) the name could be max_set_operators.

**Comment by Korablev77** [comment]
> I execute these statements:
PRAGMA sql_compound_select_limit(-1);
SELECT 5 UNION ALL SELECT 6;
-- Result: PRAGMA does not say there is an error, the minus sign is ignored.

It seems that negative values are not taken into consideration and simply ignored, so the current value is not changed. I guess an error raise is more suitable here, isn't it? It can be easily fixed.

> PRAGMA sql_compound_select_limit(+1);
> SELECT 5 UNION ALL SELECT 6;
> -- Result: "error: Too many UNION or EXCEPT or INTERSECT operations (limit 1 is set)"
> although the number of UNION operations is 1, which is the limit

Probably, it was confused with the number of UNION/EXCEPT/INTERSECT operands (which is +1). Should be fixed.

> I execute these statements:
PRAGMA sql_compound_select_limit(0);
SELECT 5 UNION ALL SELECT 6;
-- Result: no error, although the limit has been exceeded.

0 value removes any limits at all; this behaviour is also supported by SQLite (on the other hand, there it is compile-time option). Although it was mentioned in doc request within b2afe208d12d0e02aa6ede4e3411128e30e87b1b patch:

> Setting sql_compound_select_limit at 0 disables this limit at
> all.

Is this behaviour OK? Or 0 should mean "no compound queries at all"?

> Actually I think all PRAGMA statements are bad

Could you suggest possible replacement for PRAGMA statement? As you may know, now we need it to set several quite important settings such as engine (memtx/vinyl), defer mode for foreign keys, displaying meta-information concerning indexes/tables, debug trace facilities and so on. It is unlikely that we are going to remove it soon, but we should keep in mind reasonable alternatives. For instance, we can use `SET` syntax like in PostgreSQL (e.g. `SET enable_seqscan = true`).

Finally, I agree that naming should be fixed and current value of this pragma should be displayed in simple 'PRAGMA' list.

**Comment by pgulutzan** [comment]
Re compound_select_limit(-1): yes I believe an error would be appropriate.
Re confusing "number of operations" with "number of operands": yes I believe your explanation.
Re compound_select_limit(0): I believe 0 should mean "0 set operators" not "infinite set operators".
Re SET instead of PRAGMA: yes I hope that eventually users can use SET and SELECT|VALUES for variables.
Re naming: I guess you mean at least that it won't be compound_select_limit, good.
Re display: thank you.

**Comment by ImeevMA** [comment]
@pgulutzan We removed this pragma in #4511. Should we close this issue?

**Comment by pgulutzan** [comment]
@ImeevMA: Yes, sql_compound_select_limit is not supported now, which solves the problem. However, please see also my comment today on Issue#4511.

**Comment by ImeevMA** [comment]
@pgulutzan I responded to a comment in #4511. I think there is nothing to do here, so I close this issue.
