### ISSUE TITLE
sql: allow <COLLATE> clause only for arguments of string-like types

### ISSUE THREAD

**Issue by Korablev77** [tarantool/tarantool#3804]
Currently it is possible to do things like:

```
CREATE TABLE t (id INT PRIMARY KEY);
SELECT id COLLATE BINARY FROM t;
SELECT id COLLATE "unicode_ci" FROM t;
```

Which obviously makes no sense. Since now strict typing has been already introduced we can point out real types of columns related to \<COLLATE> clause and throw an error in case type is not string-like.
Note that during format creation fields are checked to be of SCALAR/STRING type in case collation is explicitly indicated.

**Comment by Gerold103** [comment]
Please, investigate what about binding to collated arguments. We need somehow ban this: `SELECT ? COLLATE <coll>` with non-string values.
