### ISSUE TITLE
sql: implicit type cast problems during assignment

### ISSUE THREAD

**Issue by Korablev77** [tarantool/tarantool#3809]
There are still a couple of issues connected with type casting (according to dev mailing list):

- [ ] Loss during conversion: if target data type is exact numeric, source data type is exact numeric or approximate numeric and cast results in imply loss of any leading significant digits after rounding or truncating, then an error should be raised. In particular this also applies to INF constant: it can't be assigned to INT type.

- [ ] Assign to CHAR: we should require an explicit CAST for all three situations, from INT, from REAL, and from BLOB.

- [x] Assign to BLOB: should require an explicit CAST for all three types as well. 

- [ ] Assign to INT: disallow implicit conversion from CHAR, even if CHAR value can be converted to a number (e.g. int_column = '123' should be banned).

- [ ] Assign to REAL:  disallow implicit conversion from CHAR, even if CHAR value can be converted to a number (e.g. real_column = '1.23' should be banned).

- [ ] Misc: check that assign to CHAR and to BLOB from INF leads to the same result (now can observe different results: 'Inf' and 'INF' which looks quite strange).

**Comment by pgulutzan** [comment]
Please also consider CHARACTER_LENGTH(boolean-value).

**Comment by pgulutzan** [comment]
Also this happens:
CREATE TABLE t (s1 INTEGER PRIMARY KEY);
INSERT INTO t VALUES (1.1);
Result = error.
Should this be a separate bug report?

**Comment by ImeevMA** [comment]
@pgulutzan I think it would be better to create a new issue.

**Comment by pgulutzan** [comment]
@ImeevMA: It is an old issue: Issue#4216 Silent NUMBER cast to INTEGER.
I have thought about it some more, and decided: since K. Yukhin closed it, I will do nothing.
