### ISSUE TITLE
sql: support -2^63 .. 2^64-1 integer type

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#3810]
We need a SQL type to match native Tarantool's 'integer' space format / index format [type][1], which represents -2^63 .. 2^64-1 range of integral numbers. Those number are encoded as int64 or uint64 msgpack type depending of value.

Now we support the following integral number types in Tarantool/SQL: INT / INTEGER. SMALLINT and BIGINT intended to be supported after #3687.

There are the following ways to implement SQL type for the -2^63 .. 2^64-1 range:

1. Expand range for INT and INTEGER (it is now -2^63 .. 2^63-1). Expand BIGINT too. Don't sure about SMALLINT.
2. Expand BIGINT range, leave SMALLINT, INT, INTEGER as is.
3. Introduce a new SQL type, leave existing / planned integral SQL types as is.

I vote for the first way, because Tarantool/SQL type INTEGER is expected to represent the same range as native Tarantool's 'integer'.

[1]: https://tarantool.io/en/doc/2.1/book/box/data_model/#indexed-field-types

**Comment by Totktonada** [comment]
@kostja says it should be INT, so it seems we'll going with the first way.

**Comment by Korablev77** [comment]
Due to this feature we may observe strange behaviour during Lua-SQL interaction:
```
\set language sql
CREATE TABLE t (id INT PRIMARY KEY, a INT);
\set language lua
box.space.T:insert{1, 18446744073709551615ULL}
\set language sql
SELECT a + 1 FROM t;
---
  - [1.844674407371e+19]
...
```

**Comment by kyukhin** [comment]
Let's do this:
1. SQL's INTEGER should cover same range as Lua's: -2^63..2^64-1
2. In the scope of this issue we do not introduce new types in SQL
3. In case, when calculated INTEGER value become out-of-range: runtime error is emitted by VDBE
4. Output for type INTEGER should always be numeric, no conversion to FP value

**Comment by Totktonada** [comment]
Note re ODBC:

> The [C Data Types][1] part of ODBC standard explicitly states that
> `SQLINTEGER` is defined as `long int` and `SQLUINTEGER` is defined as
> `unsigned long int`. How to expose our INTEGER (-2^63..2^64-1) SQL
> type?

[1]: https://docs.microsoft.com/en-us/sql/odbc/reference/appendixes/c-data-types?view=sql-server-2017

AFAIR, there is also a document around JDBC that provide some recommendations for mapping SQL types to Java ones that recommends to map INTEGER into long or int (don't sure), but it seems it is not mandatory. (TBD: find the document.)

However ODBC wording looks as requirement rather then recommendation. There is the sense here: we have native BigInteger in Java, but have no a native (and standard) type in C broader then int64_t / uint64_t.

**Comment by Korablev77** [comment]
Another one evidence that suggested by @kostja and supported by @kyukhin implementation is inappropriate. We are going to suffer if we attempt to follow such weird (and likely to be wrong) range for INTEGER.

**Comment by Korablev77** [comment]
upd.: I've banned opportunity to operate on integers in range [INT64_MAX, UINT64_MAX] in scope of this issue: https://github.com/tarantool/tarantool/issues/3735, even if they are fetched from space entries. So examples like:
```
box.space.T:insert{1, 18446744073709551615ULL}
\set language sql
SELECT a + 1 FROM t;
---
  - [1.844674407371e+19]
...
```
now are resulting in `error: 'Failed to execute SQL statement: integer is overflowed' `

If this is enough for 2.1.1, I suggest to move this ticket to 2.2.

**Comment by pgulutzan** [comment]
I suggest changing the error message from "integer is overflowed" to "integer overflow".
