### ISSUE TITLE
sql: introduce FLOAT, DOUBLE and REAL data types

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#3812]
Currently SQL doesn't have FLOAT/DOUBLE/REAL data types, there is only NUMBER data type, which also allows integer values. Introduce FLOAT/DOUBLE/REAL data types (actually we only need DOUBLE, all other types are synonyms).

**Comment by Totktonada** [comment]
Note: FLOAT and DOUBLE is expected to be float64, REAL is expected to be float32.

https://docs.oracle.com/javase/1.5.0/docs/guide/jdbc/getstart/mapping.html

**Comment by Korablev77** [comment]
That's obviously should firstly be done in NoSQL Tarantool: now there's only `NUMBER` field type
