### ISSUE TITLE
sql: precision loss when parse a floating point number

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#3813]
Example:

```
tarantool> select 9223372036854775807.0
---
- - [9223372036854775808]
...
```

**Comment by Korablev77** [comment]
Note that the same behaviour is observed during insertion big numbers to NoSQL Tarantool:
```
box.schema.create_space('t1')
box.space.t1:format({{name = 'id', type = 'number'}})
box.space.t1:create_index('i1', {parts = {1, 'number'}})
tarantool> box.space.t1:insert({9007199254740993.0})
---
- [9007199254740992]
...

```

However, other DBs (PostgreSQL, MySQL, MS SQL) throw an error (except for Oracle - it allows to operate on VERY big numbers). So, I guess we will throw an error as well (in Tarantool/SQL).

**Comment by Totktonada** [comment]
Yep, all numbers in Lua are doubles, but Tarantool has some kind of workaround for lua land: LL and ULL suffixes to store a number as cdata<int64_t> or cdata<uint64_t>. Anyway, it is out of scope, IMHO.

**Comment by Korablev77** [comment]
upd: I've reconsider my point of view. Mentioned DBs by default use numeric types for literals, not floating point. For example, in PostgreSQL:

```
select typname from pg_type where oid = pg_typeof(9007199254740992.0)
   | typname
-- | --
1  | numeric
```
We can force DOUBLE type and observe the same loss:
```
SELECT 9007199254740992::DOUBLE PRECISION
float8
9,00719925474099E+15
```

Since literals are threatened as doubles, they obey IEEE 754 standard. And by this standard loss is expected behaviour. Hence until numeric/decimal types are introduced, we can do nothing here.

**Comment by Totktonada** [comment]
@Korablev77 So you propose to parse the literal to numeric/decimal w/o any precision loss and then raise an error only when converting to double/int?

Consider also current behaviour when parsing integer values:

```
tarantool> SELECT 9223372036854775808
---
- error: 'oversized integer: 9223372036854775808'
...
```

**Comment by Korablev77** [comment]
Literal is parsed without loss, it is simply saved as a string. String is converted to double during byte-code generation (see codeReal() function). It is out of parser's business, you get the same 'loss' in C:

```
double x = 9223372036854775807.0;
printf("%f \n", x);
9223372036854775808.000000
```

Integer features quite different nature, and this error seems to be OK. Again, if we had numeric type and literals were threatened as numeric, then no error would be raised. The same example from PosgtreSQL:
```
select typname from pg_type where oid = pg_typeof(9223372036854775808)
   | typname
-- | --
1  | numeric

select 9223372036854775808::INTEGER
22003: integer out of range
```

So, I guess this error is fine.

**Comment by Totktonada** [comment]
So, floating-point literals are numeric with any length and any precision, but integral literals are int32 and the reason is 'Integer features quite different nature' means 'no reason'. Cannot get your logic here.

> Funny thing: if you call it 'loss', then even '0.1' is not valid value, since it hasn't precise binary representation: 0.1 is really 0.100000001490116119384765625 according to IEEE 754 and error due to conversion is 1.490116119384765625E-9.

It is loss, so I call it loss. I don't say anywhere that 0.1 is valid. Implicit cast it to double should produce an error, IMHO.

**Comment by Totktonada** [comment]
> But not any precision - it is not possible I guess, there should be limit.

So parsing a number beyond this limit should give an error, I think.

> Loss of double is expected behaviour…

It is (when a value casted to / specified as double). Loss of precision of a numeric literal is not somewhat expected, I guess.

> integer literals are of type int64

Int64 is not enough to represent uint64 range, which is part of our built-in 'integer' space format type (it is uint64 + int64). Now you cannot update an integer field in a space to a value in the [2^63; 2^64] range, but able from Lua.

> They should both be numeric when we introduce that type.

Sure. And I don't see any differences in behaviour integral and fp types **should** have against precision loss. But now they have.

**Comment by Korablev77** [comment]
So blocked until https://github.com/tarantool/tarantool/issues/3672 is resolved.

**Comment by kyukhin** [comment]
Resolved.
