### ISSUE TITLE
How to create a thread and communicate with each other ?

### ISSUE THREAD

**Issue by veezhang** [tarantool/tarantool#3821]

**Comment by Totktonada** [comment]
Tarantool uses cooperative multitasking and primitive named fiber. It is quite similiar to greenlets in Python. fiber_cond and fiber_channel can be used to syncronized communications. Please, refer the [documentation][1]. We also have [queue][2] module to persist tasks in the datadase and proceed with them from multiple worker fibers.

Feel free to ask any questions in our Telegram channels [in English][3] or [in Russian][4].

[1]: https://tarantool.io/en/doc/1.10/reference/reference_lua/fiber/
[2]: https://github.com/tarantool/queue
[3]: https://t.me/tarantool
[4]: https://t.me/tarantoolru

**Comment by kyukhin** [comment]
Feel free to ask your questions in:
- Telegram channel
    - (Russian) https://t.me/tarantoolru
    - (English) https://t.me/tarantool
- Google groups
    - (Russian) https://groups.google.com/forum/#!forum/tarantool-ru
    - (English) https://groups.google.com/forum/#!forum/tarantool
