### ISSUE TITLE
In case of ENOSPC delete WALs not needed for recovery from the last checkpoint

### ISSUE THREAD

**Issue by locker** [tarantool/tarantool#3822]
Getting ENOSPC when trying to write to WAL triggers removal of WAL files pinned by old replicas (see #3397). However, we never delete WAL files that are needed for recovery from the oldest checkpoint, for the sake of data redundancy in case of a hardware failure.

In the scope of #1082 we are planning to limit max size of disk space that can be occupied by WAL files. It would be logical to add an option that would trigger checkpointing if the size of WAL files since the last checkpoint exceeds a certain threshold (like `box.cfg.checkpoint_interval`, but in bytes instead of seconds). If we always keep all WAL files needed for recovery from the oldest checkpoint, we will complicate the usage of this option, because the admin will have to take into account the value of `box.cfg.checkpoint_count` when estimating the size of the WAL partition.

That being said, let's force deletion of all WAL files except those that are needed for recovery from the last checkpoint in case of ENOSPC. Although this would hurt redundancy, it should be tolerable, because ENOSPC is a rather infrequent event.

**Comment by kostja** [comment]
Please do in scope of MF paid task.
