### ISSUE TITLE
"net_msg_max limit reached" consumes CPU

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#3825]
Tarantool version:
\>= 1.9
OS version:
any
Bug description:
Under load on each new request "net_msg_max limit reached" message is logged. It consumes CPU reducing RPS in several times, and disk wasting gigabytes to just store copies of this message.
Steps to reproduce:
Just reach net_msg_max.

**Comment by Mons** [comment]
I think it would be sufficient to limit output to max 1 message per second

**Comment by Gerold103** [comment]
Yes. But I think the main problem of this issue is how to make it reusable for any other similar log messages. For example, do not print too long wal write on each occurrence - we can have 50k fibers, first made too long wal write and all others will have it too = 50k messages.

**Comment by Gerold103** [comment]
Number of such unique log messages is not too big, so a possible solution is add a static variable in a function, making such frequent logging in which we will store last log time and number of occurrences. If more than one message appeared in a small time interval, we will log it once with saying how many times it occurred. It will work for all cases.

**Comment by locker** [comment]
See #2218
