### ISSUE TITLE
sql: bind parameters array leaks in iproto thread

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#3828]
Tarantool version:
\>= 2.0

OS version:
any

Bug description:
Memory leaks when SQL bind parameters are used. iproto_msg_decode calls xrow_decode_sql which allocates an array of sql_bind values on a region. But iproto thread never frees region. It does not use fibers at all.

Steps to reproduce:
Just use bind parameters in any SQL query.

**Comment by Gerold103** [comment]
In a discussion with @kostja we've decided that we should continue decoding of `sql_bind` array in iproto thread. But it is still unclear how to free `sql_bind` array. Now `struct iproto_msg` is actually a union of different requests and has no clear inheritance and virtual methods. If we want to create a custom destructor for a concrete request type, we should either
1) just add something like `void (*destroy)(struct iproto_msg *)` to `struct iproto_msg` and initialise it in `iproto_msg_decode`;
2) make `iproto_msg` base and inherit from it call, sql, dml and other msgs. But we still need to add a destructor to the base `iproto_msg` in the same way as in point 1;
3) add a destructor to `struct cmsg`. This will allow to push destruction logic down to the routing level. It is much more complex, but we already have some crutches about it: `struct cbus_call_msg` has `free_cb`, `struct relay_gc_msg` is allocated on `malloc` and then freed explicitly. A problem with `struct cmsg` destructor is how to call it from a specific thread, if cmsg is allocated on a specific slab cache (like `iproto_msg`). And do we really need it if most of cmsgs are now either on stack or are parts of a bigger structures? IMO, so far it makes no sense to complicate things so much.

Also it appeared that we could decode `IPROTO_UPDATE` operations in iproto thread in the same way as `sql_bind` array.

**Comment by Gerold103** [comment]
We have decided to move bindings decoding to TX thread.

**Comment by zilveer** [comment]
@Gerold103 can you please prove me an example of how you use SQL bind parameters array in Tarantool?

regards

**Comment by Gerold103** [comment]
Hi! Look at the tests: https://github.com/tarantool/tarantool/blob/master/test/sql/bind.result and at the documentation: https://www.tarantool.io/en/doc/2.1/book/box/box_sql/#lua-function.box.execute

**Comment by zilveer** [comment]
@Gerold103 i just saw this ;)
Thank you!

Regards
