### ISSUE TITLE
Please ensure maintainers run the test suite before pushing to trunk

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#3848]
Tarantool version:
All
OS version:
All
Bug description:
Some of our committers and maintainers don't run entire test suite in parallel mode before committing to trunk. Please ensure this doesn't happen.
Steps to reproduce:
Watch the maintainer do the push.

**Comment by Totktonada** [comment]
We keep this on track anyway, the issue is not necessary. Closed.
