### ISSUE TITLE
Use _DARWIN_UNLIMITED_SELECT define on MacOS 

### ISSUE THREAD

**Issue by bigbes** [tarantool/tarantool#3867]
When you're opening a lot of fd's on MacOS in Tarantool (builded the usual way) you'll, eventually, obtain `(libev) select: Invalid argument` message, which points you that you've already opened too many fd's.

Example:
```
tarantool> box.cfg{ listen = 3301 }
tarantool> rv = {}; for i = 1, 1000 do local nb = require('net.box').new('localhost:3301'); table.insert(rv, nb); nb:ping() end; return rv
(libev) select: Invalid argument
Abort trap: 6
```

For me it opens only 504 netbox connection (which make sense, since it's 2 * fd_count in select already registered).

**Comment by bigbes** [comment]
Small addition is: `kqueue` seems to be "broken" as Marc Lehmann [wrote in libev documentation](http://pod.tst.eu/http://cvs.schmorp.de/libev/ev.pod#OS_X_AND_DARWIN_BUGS), poll uses `kqueue`, and `select` has "hack" to use more than 1024 fds.

**Comment by kyukhin** [comment]
@bigbes what do you like to see?

**Comment by kyukhin** [comment]
No answer, closing.

**Comment by Totktonada** [comment]
It is already enabled in third_party/libev/ev.c.

```c
/* OS X, in its infinite idiocy, actually HARDCODES
 * a limit of 1024 into their select. Where people have brains,
 * OS X engineers apparently have a vacuum. Or maybe they were
 * ordered to have a vacuum, or they do anything for money.
 * This might help. Or not.
 */
#define _DARWIN_UNLIMITED_SELECT 1
```

**Comment by eljashm** [comment]
Unlimited select flag was in fact present in source files but it did not change much because it was defined too late, after including `<sys/time.h>`. 
The problem with such precendence is described here: 
http://lists.schmorp.de/pipermail/libev/2018q2/002788.html

So the obvious solution would be moving this line before including time.h.

**Comment by Totktonada** [comment]
It seems it worth to reopen this issue.
