### ISSUE TITLE
Segfault on upsert

### ISSUE THREAD

**Issue by YarickR** [tarantool/tarantool#3869]
Tarantool version: 1.10.2.68

OS version: Gentoo Linux

Bug description:
2018-12-11 00:55:35.705 [3392] main/1857/main tuple_update.c:394 E> ER_NO_SUCH_FIELD: Field 9 was not found in the tuple
Segmentation fault
  code: SEGV_MAPERR
  addr: 0x7fa99e0079ce
  context: 0x7fa97558f740
  siginfo: 0x7fa97558f870
  rax      0x7fa99e0079ce     140366477031886
  rbx      0x7fa834bb9fdf     140360415944671
  rcx      0x7                7
  rdx      0x7fa99e0079ce     140366477031886
  rsi      0x1                1
  rdi      0x7fa97558fd70     140365794966896
  rsp      0x7fa97558fce0     140365794966752
  rbp      0x7fa97558fce0     140365794966752
  r8       0x0                0
  r9       0x2d1887ee         756582382
  r10      0x11               17
  r11      0x0                0
  r12      0x7fa834bb9fdf     140360415944671
  r13      0x4031b9f8         1077000696
  r14      0x41d02250         1104159312
  r15      0x415e75f8         1096709624
  rip      0x7fa97acc0d55     140365886393685
  eflags   0x10202            66050
  cs       0x33               51
  gs       0x0                0
  fs       0x0                0
  cr2      0x7fa99e0079ce     140366477031886
  err      0x4                4
  oldmask  0x0                0
  trapno   0xe                14
Current time: 1544478973
Please file a bug at http://github.com/tarantool/tarantool/issues

Steps to reproduce:

Optional (but very desirable):
* coredump
* backtrace
* netstat

**Comment by kyukhin** [comment]
We\ve fixed #3902. Could you please re-check?

**Comment by kyukhin** [comment]
No answer for months, closing.
