### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by YarickR** [tarantool/tarantool#3872]
Tarantool version: 1.10.2.68

OS version: Gentoo Linux

Bug description: After doing select from external app and disconnecting before result is retrieved, memory is not freed

Steps to reproduce: Create a large dataset, do select on it to retrieve the whole dataset, terminate connecton while select is running.

Optional (but very desirable):
* coredump
* backtrace
* netstat

[leak.tar.zip](https://github.com/tarantool/tarantool/files/2666865/leak.tar.zip)

**Comment by Totktonada** [comment]
Any reproducer (script)? Are that reproduced on 1.10.2-80-g0b6e25f46 (it fixes 32B/req memleak in the built-in http_client)?

**Comment by kyukhin** [comment]
No answer, closing.
