### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by mikezsin** [tarantool/tarantool#3873]
Tarantool version:
Tarantool 1.10.2-68-g037af04

OS version:
Gentoo
Bug description:
Segfault
Steps to reproduce:
unknown
Optional (but very desirable):
Segmentation fault
  code: SEGV_MAPERR
  addr: 0x35
  context: 0x7fbd031ef7c0
  siginfo: 0x7fbd031ef8f0
  rax      0x1d               29
  rbx      0x7fbc390462cc     140446387167948
  rcx      0x418786d8         1099400920
  rdx      0x7fbd095fade0     140449882811872
  rsi      0x4                4
  rdi      0x1d               29
  rsp      0x7fbd031efd70     140449777909104
  rbp      0x7fbd031efd80     140449777909120
  r8       0x7fbd030dfe50     140449776795216
  r9       0x0                0
  r10      0x0                0
  r11      0x0                0
  r12      0x7fbc390462cc     140446387167948
  r13      0x40c2f370         1086518128
  r14      0x401              1025
  r15      0x4094d340         1083495232
  rip      0x7fbd086d4ad3     140449866926803
  eflags   0x10202            66050
  cs       0x33               51
  gs       0x0                0
  fs       0x0                0
  cr2      0x35               53
  err      0x4                4
  oldmask  0x0                0
  trapno   0xe                14
Current time: 1544521139
Please file a bug at http://github.com/tarantool/tarantool/issues

**Comment by kyukhin** [comment]
Could you please provide a reproducer or at least a coredump?

**Comment by kyukhin** [comment]
No answer for months, closing.
