### ISSUE TITLE
ER_WAL_IO: Failed to write to disk

### ISSUE THREAD

**Issue by vmakhaev** [tarantool/tarantool#3899]
Tarantool version:
Tarantool 1.10.2-66-g2972cfcee
Target: Linux-x86_64-RelWithDebInfo

OS version:
docker image progaudi/tarantool:1.10.2

Bug description:
2018-12-20 19:58:48.630 [1] main/10048/main txn.c:292 E> ER_WAL_IO: Failed to write to disk
2018-12-20 19:58:48.781 [1] wal/101/main xlog.c:802 !> SystemError file './data/00000000000001276486.xlog' already exists: File exists

cat 00000000000001276486.xlog
XLOG
0.13
Version: 1.10.2-66-g2972cfcee
Instance: 62d3d7fd-1155-4cb1-9a38-6e623a307faf
VClock: {1: 1276486}
PrevVClock: {1: 1276463}

force_recovery = true

related to https://github.com/tarantool/tarantool/issues/3176

Steps to reproduce:

Optional (but very desirable):
* coredump
* backtrace
* netstat

**Comment by kyukhin** [comment]
Could you pls provide a testcase?

**Comment by kyukhin** [comment]
No answer, closing.

**Comment by vmakhaev** [comment]
I think it happened after database restart. Looks like there is some race condition. This problem is real and not solved. Not sure why you close this issue.

**Comment by vmakhaev** [comment]
Database does not start in some conditions. I would say, this is critical issue.
