### ISSUE TITLE
vinyl treats differently disk and mem tuples in comparators

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#3919]
**Tarantool version:**
At least, from 1.9, I believe.

**Bug description:**
If I insert a double value looking like an integer (2.0, for example), then dump it onto disk and try to read using integer value ((int)2.0 == 2), then it is not found. But in memory it is found. Also, it is found after the tuple hits the cache after, for example, fullscan.

**Steps to reproduce:**
```Lua
ffi = require('ffi')
d = ffi.new('double', 1.0)
d2 = ffi.new('double', 2.0)
box.cfg{}
s = box.schema.create_space('test', {engine = 'vinyl'})
pk = s:create_index('pk')
sk = s:create_index('sk', {parts = {{2, 'number'}}})
s:replace{1, d}
s:replace{2, d2}

-- Select from mem.
sk:select{1} -- Ok, found.
-- Dump d2 to disk.
box.snapshot()
-- Select from disk.
sk:select{2} -- !!! Not found !!!.

-- Do fullscan.
sk:select{}
-- Now sk:select{2} works.
sk:select{2}
```

**Comment by Gerold103** [comment]
@Korablev77 found it.

**Comment by locker** [comment]
Duplicates #3907
