### ISSUE TITLE
Unify package versions in Debian repository

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#392]
Please take a look on http://tarantool.org/dist/master/debian/pool/main/t/tarantool/:

```
tarantool_1.6.3+1+g2d374a4+20140718+1916-1_amd6..> 18-Jul-2014 15:45             1440538
tarantool_1.6.3+1+g2d374a4+20140718+1933-1.debi..> 18-Jul-2014 16:17               14916
tarantool_1.6.3+1+g2d374a4+20140718+1933-1.dsc     18-Jul-2014 16:17                2156
tarantool_1.6.3+1+g2d374a4+20140718+1933-1_i386..> 18-Jul-2014 16:17             1341252
tarantool_1.6.3+1+g2d374a4+20140718+1933.orig.t..> 18-Jul-2014 16:17             2993153
tarantool_1.6.3+20140718+1816-1_amd64.deb          18-Jul-2014 14:44             1440076
tarantool_1.6.3+20140718+1832-1_i386.deb           18-Jul-2014 14:59             1834826
tarantool_1.6.3+20140718+1846-1.debian.tar.xz      18-Jul-2014 15:12               14904
tarantool_1.6.3+20140718+1846-1.dsc                18-Jul-2014 15:12                2079
tarantool_1.6.3+20140718+1846-1_i386.deb           18-Jul-2014 15:12             1339500
tarantool_1.6.3+20140718+1846.orig.tar.gz          18-Jul-2014 15:12             2993606
tarantool_1.6.3+20140718+1903-1.debian.tar.gz      18-Jul-2014 15:29               16399
tarantool_1.6.3+20140718+1903-1.dsc                18-Jul-2014 15:29                1808
tarantool_1.6.3+20140718+1903-1_amd64.deb          18-Jul-2014 15:29             1917344
tarantool_1.6.3+20140718+1903.orig.tar.gz          18-Jul-2014 15:29             2993621
```

Some packages uses githash for naming but some doesn't. It looks inconsistent.

Please do the following things:
+ Investigate which naming scheme is most suited for us (for both **deb and rpm**). I personally more like  `tarantool_1.6.3+1+g2d374a4+20140718+1933~sid` scheme, but please follow the best practices.
   * Name scheme must comply with distro polices
   * Packages with same version for various distributives (e.g. sid and wheezy) must don't have name conflicts (in terms of file names)
   * RPM and DEB should use similar approach to naming as much as it is possible with rpm/deb systems
+ Discuss about a new scheme with me and @unera 
+ Update builds to use the new scheme

**Comment by Sulverus** [comment]
@rtsisyk 
>>Packets should be renamed to 1.6.3.23.gabcde~sid-1_amd64.deb form.

build must be separated with '.' or like git --describe --long?
like 1.6.4-291-g58f2645

**Comment by Sulverus** [comment]
done. awaiting for check
new names will be generated like this: tarantool_1.6.4.311.ge0ff949~jessie-1_amd64
