### ISSUE TITLE
Region trucated before it's content used while index rebuild

### ISSUE THREAD

**Issue by GeorgyKirichenko** [tarantool/tarantool#3920]
vy_run_rebuild_index reads tuples and extract keys to a region near line 2415: key = tuple_extract_key(tuple, cmp_def, NULL); and then truncates region near line 2444: region_truncate(region, mem_used);

After all tries to read the last extracted key to set run max key near line 2453: run->info.max_key = vy_key_dup(key); when key might contain garbage.

**Comment by locker** [comment]
Fixed by 3f57564c3cd541268002cd437b52cfbe26342ab8
