### ISSUE TITLE
can luajit allocate more than 2G FFI object after enabling -DLUAJIT_ENABLE_GC64 in tarantool/third_party/luajit/src/Makefile

### ISSUE THREAD

**Issue by Fedora7** [tarantool/tarantool#3921]
After enabling -DLUAJIT_ENABLE_GC64 in tarantool/third_party/luajit/src/Makefile ( branch tarantool-1.7 based of luajit 2.1 beta 3 ) , the following test still failed when reaching the 2G limit:

ffi2 = require("ffi")
ffi2.cdef[[
    unsigned long compressBound(unsigned long sourceLen);
    int compress2(uint8_t *dest, unsigned long *destLen,
    const uint8_t *source, unsigned long sourceLen, int level);
    int uncompress(uint8_t *dest, unsigned long *destLen,
    const uint8_t *source, unsigned long sourceLen);
]]

test2 = {}
tarantool> for i = 5234567, 9528000 do test2[i]= ffi2.new("uint8_t[?]", 80) end
---
...

tarantool> for i = 9234567, 12528000 do test2[i]= ffi2.new("uint8_t[?]", 80) end
---
...

tarantool> for i = 12234567, 19528000 do test2[i]= ffi2.new("uint8_t[?]", 80) end
---
- error: not enough memory
...
tarantool> box.info
---
- vinyl: []
  version: 2.1.1-164-gf6a31c034
  id: 1

Tarantool version:
2.1

OS version:
Ubuntu 16.04

**Comment by kyukhin** [comment]
Feel free to ask your questions in:

* Telegram channel
  
  * (Russian) https://t.me/tarantoolru
  * (English) https://t.me/tarantool
* Google groups
  
  * (Russian) https://groups.google.com/forum/#!forum/tarantool-ru
  * (English) https://groups.google.com/forum/#!forum/tarantool

**Comment by Totktonada** [comment]
AFAIK, -DLUAJIT_ENABLE_GC64 is experimental LuaJIT feature and should not be considered as production ready.
