### ISSUE TITLE
Prevent tarantool injection & unsolicited code execution

### ISSUE THREAD

**Issue by jobs-git** [tarantool/tarantool#3927]
In SQL, there is what we call SQL injection, and this was mitigated by using `prepared statements`, in tarantool what counter measures can we use so that we can prevent code injections from unsolicited users?

**Comment by Totktonada** [comment]
Tarantool supports placeholders for parameters as for usual `box.execute()` requests as well as for [prepared statements](https://github.com/tarantool/tarantool/issues/2592). Basic example:

```
tarantool> box.cfg{}
tarantool> box.execute([[create table bar(id integer primary key autoincrement, value varchar(100))]])
tarantool> box.execute([[insert into bar values (NULL, ?)]], {'one'})
tarantool> box.execute([[insert into bar values (NULL, ?)]], {'two'})
tarantool> box.execute([[insert into bar values (NULL, ?)]], {'three'})
tarantool> box.execute([[select * from bar]])
---
- metadata:
  - name: ID
    type: integer
  - name: VALUE
    type: string
  rows:
  - [1, 'one']
  - [2, 'two']
  - [3, 'three']
...
```

See more in the [documentation](https://www.tarantool.io/en/doc/latest/reference/reference_lua/box_sql/#lua-function.box.execute).

See also the relevant [discussion](https://github.com/tarantool/doc/issues/1478) with the documentation team.

Feel free to reopen the issue if you have more questions.

**Comment by jobs-git** [comment]
I am glad that there is already an SQL prepared. Is there a native Tarantool prepared statement? Should I reopen one?

**Comment by Totktonada** [comment]
Native requests are quite straightforward: they don't require parsing and generating of bytecode. There is no need to prepare them, because it would not give any performance benefits.

**Comment by jobs-git** [comment]
I was thinking if it was possible to further strengthen tarantool  security. 

Native tarantool database calls might have a potential to do tarantool injection in the future.

Native tarantool prepare might be one solution to this.

**Comment by Totktonada** [comment]
I see no relation. Please, show example of potentialy vulnerable userland code and I will able to respond something more certain (at least how to write it in a safe way).
