### ISSUE TITLE
Length functions for SQL character strings

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#3929]
I have Ubuntu 18.04. I have Tarantool 2.1, pulled from source today.
I have a feature request which could improve compatibility with standard SQL.
Please support the function
"{CHAR_LENGTH | CHARACTER_LENGTH}
(character value expression [USING CHARACTERS])
"
This should return the length in UTF8 characters -- what LENGTH() already returns.
This is not a request to change the behaviour of LENGTH().
This should be illegal if the type of the expression is not CHAR or VARCHAR.
This should return an error if the expression has invalid UTF8, but that is not important
(if we don't error-check other functions, we should not error-check this function).
The clause USING CHARACTERS is optional and does nothing.
CHAR_LENGTH and CHARACTER_LENGTH will be reserved words.

It would be good to support OCTET_LENGTH too, but that is not part of this issue.

**Comment by ImeevMA** [comment]
Hello @pgulutzan. About this function, it was decided that it would be better to implement it as "{CHAR_LENGTH | CHARACTER_LENGTH} (expression of the symbol value)" (without "[USING CHARACTERS]"). I think the expression "[USING <char length units>]" will be added later if we decide to implement all the functions in accordance with ANSI.

**Comment by ImeevMA** [comment]
Hello @pgulutzan. I have a question about this issue. After discussing casts, is it possible to say that the arguments of the requested functions can be of any type except BOOLEAN?

**Comment by pgulutzan** [comment]
When you say "the requested functions", I guess you mean character_length() | octet_length() and their aliases. As discussed in email thread "Check types of arguments of functions" there is an implicit cast (so the length is not the actual length of the stored value e.g. in MessagePack). Implicit cast is okay for everything except BOOLEAN at this moment, but we don't know if it will be okay for VARBINARY. Therefore I don't think it is possible to say that.

**Comment by ImeevMA** [comment]
Thank you, @pgulutzan. Do you think we should wait until VARBINARY is implemented and discuss these functions again?

**Comment by pgulutzan** [comment]
Don't worry about what I think. There was a decision to not wait, and not accept what I suggested above. I am guessing that length() is the same as character_length() and requires a character value expression, that is, data type = 'string'. Therefore length(varbinary-value) will cause an implicit cast(varbinary-value to string). This is a behaviour change, because currently length('Д') = 1 but length(x'D094') = 2.

**Comment by kostja** [comment]
This is confusing. First, we agreed to not allow an implicit cast of VARBINARY to STRING. I also believe that your @pgulutzan interpretation of what length() does is incorrect. I think length() works both for strings and binary objects, without a cast:
https://github.com/tarantool/tarantool/blob/master/src/box/sql/func.c#L139

So, @ImeevMA please simiply add these aliases to LENGTH(), there is nothing else to decide or discuss in this ticket.

**Comment by pgulutzan** [comment]
@ImeevMA: The immediate effect of your most recent commit would, I think, be that both LENGTH(X'...') and CHAR_LENGTH(X'...') will return octet_length with no error. And, if/when implicit casting from VARBINARY to STRING is disallowed, both will cause an error. Is that correct?

**Comment by ImeevMA** [comment]
@pgulutzan tarantool> box.execute("select char_length(X'10')")
---
- metadata:
  - name: char_length(X'10')
    type: integer
  rows:
  - [1]
...
