### ISSUE TITLE
Store regular identifiers in case-normal form

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#3931]
I have Ubuntu 18.04. I have Tarantool 2.1, pulled from source today.

I execute these SQL statements:
DROP TABLE a;
DROP TABLE A;
DROP TABLE Á;
DROP TABLE á;
DROP TABLE д;
DROP TABLE Д;
CREATE TABLE a (s1 INT PRIMARY KEY); /* statement #1 */
CREATE TABLE A (s1 INT PRIMARY KEY); /* statement #2 */
CREATE TABLE Á (s1 INT PRIMARY KEY); /* statement #3 */
CREATE TABLE á (s1 INT PRIMARY KEY); /* statement #4 */
CREATE TABLE д (s1 INT PRIMARY KEY); /* statement #5 */
CREATE TABLE Д (s1 INT PRIMARY KEY); /* statement #6 */

Statement #2 fails with "Error . table A already exists (good).
Statement #4 succeeds (bad).
Statement #6 succeeds (bad).

So we see that identifiers are converted to case-normal form
(which is "upper case" in this context) if the identifier is
ASCII. Accented Latin letters and Cyrillic letters are not
converted.

The standard document says that the conversion should occur
for "a lower case character or a title case character
for which an equivalent upper case sequence U is defined
by Unicode". There is a choice of Unicode definitions for
lower-to-upper character conversions: mapping or folding.
The Unicode FAQ "case mapping" http://unicode.org/faq/casemap_charprop.html
describes the details well. The best-known example is:
with mapping one converts ß to S, with folding one converts
ß to SS. Since the document says "upper case sequence"
not "upper case character", I think it is clear that an
implementor may choose folding rather than mapping, in
other words: the result could be the same as for UPPER().

Do not depend on any tailored collation, use unicode_ci.

**Comment by pgulutzan** [comment]
Regarding a comment in sqlint.h: "Casing is locale-dependent
 * and context-sensitive". The normalization should not be locale-dependent.
Perhaps I have merely misunderstood the comment?

**Comment by kshcherbatov** [comment]
You are right. I've just copied a comment from the original routine ucasemap_utf8ToUpper
https://ssl.icu-project.org/apiref/icu4c/ucasemap_8h.html#a817d31c95e792462407a119b5fdbedc7
but the UCaseMap* object that I pass there has been initialized(ucasemap_open) with locale = NULL
https://ssl.icu-project.org/apiref/icu4c/ucasemap_8h.html#a40df152b19d07dba4cc9d5b3015b27d1
