### ISSUE TITLE
position() function

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#3933]
I have Ubuntu 18.04. I have Tarantool 2.1, pulled from source today.
I try the following statement:
SELECT POSITION('aa' in 'babaac');
Result: syntax error.
This happens because Tarantool does not support the
SQL standard's POSITION function.

Standard syntax: POSITION (string1 IN string2 [USING CHARACTERS])
Tarantool syntax: INSTR (string2, string1)

The suggestion is: support POSITION, remove support for INSTR.

The result should be the position of the first occurrence of
string1 within string2, remembering that counting begins with 1.
If string1 is not found, return 0.
If string1 = blank (that is, '' or X''), return 1.
These rules are already followed by INSTR, so the change
is mostly in syntax.

Both string1 and string2 should really be strings, although
it is probably harmless if someone wants to ask for position
in a number. The strings should be comparable and collation
should be taken into account.

The optional USING CHARACTERS clause does nothing. We allow the clause
but we do not have any choice but CHARACTERS because our
character strings are UTF8.

**Comment by pgulutzan** [comment]
From a comment in a January email:
"MySQL allows POSITION as a synonym for LOCATE.
DB2 supports POSITION.
But Oracle supports INSTR
https://docs.oracle.com/cd/B28359_01/olap.111/b28126/dml_functions_1103.htm#OLADM564"

**Comment by kyukhin** [comment]
Done by 896f396cb5bde898e7c5f1e1c712322e3ee1531e
