### ISSUE TITLE
sql: IN operator and '=' return different results

### ISSUE THREAD

**Issue by Korablev77** [tarantool/tarantool#3934]
```
\set language sql
CREATE TABLE t1(x TEXT primary key);
INSERT INTO t1 VALUES('1');
tarantool> SELECT x FROM t1 WHERE x IN (1.0);
---
- []
...

tarantool> SELECT x FROM t1 WHERE x = 1.0;
---
- - ['1']
...
```
However, comparison rules should be the same for both operators (throw an error like PostgeSQL, return '1' like Oracle or return empty set). Since we decided to become closer to Oracle's behaviour, I suppose both queries should return '1'.

**Comment by kostja** [comment]
Nikita, have we really decided to be closer to Oracle, or it's an interpretation? Please provide a more extended comment, e.g. what the majority does, what the standard says? Oracle is option NN. 3

**Comment by Korablev77** [comment]
I guess the fact that comparison and IN operators must return the same result is not doubtful..? Main idea of this ticket is to fix different behaviour of their application.
What about other vendors (in both cases, obviously):
Oracle: returns 1
PostgreSQL: error (operator does not exist: text = numeric)
MySQL: returns 1
MS Server: returns 1
DB2: error (SQL0420N  Invalid character found in a character string argument of the 
function "DECFLOAT".  SQLSTATE=22018)

AFAIR we decided to ban implicit conversion from CHAR to numeric types (https://github.com/tarantool/tarantool/issues/3809), so it is part of another issue (since it requires to refactor a lot of tests).
