### ISSUE TITLE
Function box.is_in_txn() is absents in version 1.10

### ISSUE THREAD

**Issue by dimtos** [tarantool/tarantool#3940]
Tarantool version: 1.10.2-28-g10f4db86a

OS version: Debian 4.9.110-3+deb9u2

Bug description: can't use box.is_in_txn() in Tarantool v.1.10, because box.is_in_txn=nil

Steps to reproduce: box.begin(); log.info(box.is_in_txn); box.commit()

Optional (but very desirable):
* coredump
* backtrace
* netstat

**Comment by locker** [comment]
Cherry-picked to 1.10 - see commit ceb941796a6f08ccd450b810e2c82a913bf7c7b0
