### ISSUE TITLE
net.box schema contains collation_id (number) instead of collation (string)

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#3941]
How to reproduce (on clean instance, because no box.once is used):

```
box.cfg{listen = 3301}
box.schema.user.grant('guest', 'read,write,execute,create', 'universe')
box.schema.space.create('s')
box.space.s:create_index('pk')
box.space.s:create_index('sk', {type = 'tree', unique = false, parts = {{field = 2, type = 'string', is_nullable = false, collation = 'unicode_ci'}}})
net_box = require('net.box')
c = net_box.connect('localhost:3301')
box.space.s.index.sk.parts[1]
---
- type: string
  is_nullable: false
  collation: unicode_ci
  fieldno: 2
...
c.space.s.index.sk.parts[1]
---
- type: string
  is_nullable: false
  collation_id: 2
  fieldno: 2
...
```

As we see local box provides `collation` field, but net.box provides `collation_id`. There are two reasons why this looks as a problem for me:

* It complicates box/lua/key_def.lua code (merger patchset) a bit (need to handle both formats).
* Lack of some kind of a primary identifier for a collation. This should be its string name I think.

How can be implemented:

net.box can acquire and use info from _collation space.

**Comment by Totktonada** [comment]
If the key_def module created in the scope of #3276 will land before this patch it is necessary to remove `collation_id` parameter support in the module.

**Comment by Totktonada** [comment]
Merger (#3276) will be pushed to 1.10, it depends on key_def module (it is part of merger's patchset). The reason of this issue is to simplify lua/key_def.c code and remove collation_id from it at all. So this issue should be fixed in 1.10 too.

@kyukhin Can you please review the milestone?

**Comment by locker** [comment]
> Merger (#3276) will be pushed to 1.10, it depends on key_def module (it is part of merger's patchset). The reason of this issue is to simplify lua/key_def.c code and remove collation_id from it at all. So this issue should be fixed in 1.10 too.
> 
> @kyukhin Can you please review the milestone?

Pushing this one to 1.10 would be tricky as it upgrades the schema to create _vcollation space. If we had to update the upgrade script both in 1.10 and 2.1 and master, then in master and 2.1 we'd have to handle the case when the space already exists (i.e. it was created by upgrade to a previous version), which is kinda ugly.

Do we really need _vcollation to backport the merger to 1.10? As a matter of fact, do we really need to backport the merger to 1.10?

**Comment by Totktonada** [comment]
Now it seems that we should not backport merger to 1.10, the demand is gone. So this patch can be implemented for master only.

**Comment by locker** [comment]
> Now it seems that we should not backport merger to 1.10, the demand is gone. So this patch can be implemented for master only.

Okay then. Moving back to 2.2.
