### ISSUE TITLE
test: box/push.test.lua flaky hangs

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#3947]
https://travis-ci.org/tarantool/tarantool/jobs/483875315#L2451

```diff
--- box/push.result	Thu Jan 24 13:10:04 2019
+++ var/001_box/push.result	Thu Jan 24 13:13:08 2019
@@ -536,17 +536,3 @@
 ---
 ...
 chan_disconnected:get()
----
-- true
-...
-chan_push:put(true)
----
-- true
-...
-chan_push:get()
----
-- Session is closed
-...
-box.schema.func.drop('do_long_and_push')
----
-...
```

It seems that on_disconnect callback didn't fired up for some reason.

**Comment by avtikhon** [comment]
Also found that the test hangs and on timeout leaves the opened socket with process holding ~780Mb of memory. To reproduce the issue occuring in 1-1.5% of single test loop runs, do:
for r in {1..1000} ; do ./test-run.py --no-output-timeout 3 box/push.test >/dev/null 2>&1 && continue ; echo "Fail reproduced ! check files:" ; ls -al var/001_box ; ps auxT | grep `cat var/001_box/box.pid` ; lsof -p `cat var/001_box/box.pid` ; break ; done
The detected issue test code appeared during fix of
https://github.com/tarantool/tarantool/issues/3859
at
https://github.com/tarantool/tarantool/commit/43af2de2b129dabafe94a61c89688dd4701f8800
