### ISSUE TITLE
Variadic arguments

### ISSUE THREAD

**Issue by olegrok** [tarantool/tarantool#3950]
[Doc](http://www.lua.org/pil/5.2.html):
```
The three dots (...) in the parameter list indicate that the function has a variable number of arguments. When this function is called, all its arguments are collected in a single table, which the function accesses as a hidden parameter named arg. Besides those arguments, the arg table has an extra field, n, with the actual number of arguments collected.
```

Pure Lua:
```
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio
> x = function(...)
>> print(arg, arg.n)
>> end
> x()
table: 0x7fd8d2600660	0
> x(1, 2, 3)
table: 0x7fd8d240ec30	3
```

Tarantool:
```
Tarantool 2.1.1-185-gf583b6c82
type 'help' for interactive help
tarantool> x = function(...)
         > print(arg, arg.n)
         > end
---
...

tarantool> x()
table: 0x010ae60c70	nil
---
...

tarantool> x(1, 2, 3)
table: 0x010ae60c70	nil
---
...
```

Can Tarantool support this feature or is it a bug?

**Comment by Totktonada** [comment]
You referred to Lua 5.0 manual. Using `arg` in vararg functions was deprecated in Lua 5.1 and was removed in Lua 5.2. LuaJIT and then Tarantool does not support it.

However Tarantool [sets][1] _G.arg to table of command line arguments, that is why you got `arg` as a table and `arg.n` as a nil.

Use `select('#', ...)` and `select(N, ...)` to count and get such arguments. Consider that there are some problems with `nil` arguments. I suggest to read the [wiki page][2] on the topic.

[1]: https://github.com/tarantool/tarantool/blob/f1bd33a8a868dbd13707c193cb91681269d95036/src/lua/init.c#L497-L502
[2]: http://lua-users.org/wiki/VarargTheSecondClassCitizen

**Comment by olegrok** [comment]
Ok, thank you.
I think we can close issue.
