### ISSUE TITLE
just wondering: what if TaranTool would join with OpenResty?

### ISSUE THREAD

**Issue by qyloxe** [tarantool/tarantool#3951]
THAT would be a killer app/db/proxy server:

https://github.com/openresty/

Just my $0.02 :)

**Comment by jobs-git** [comment]
its the app developers job if he wants to join openresty w/ tarantool

**Comment by kyukhin** [comment]
Feel free to ask your questions in:

* Telegram channel
  
  * (Russian) https://t.me/tarantoolru
  * (English) https://t.me/tarantool
* Google groups
  
  * (Russian) https://groups.google.com/forum/#!forum/tarantool-ru
  * (English) https://groups.google.com/forum/#!forum/tarantool
