### ISSUE TITLE
tarantoolctl start: bad error message when there is no box.cfg() call in an instance file

### ISSUE THREAD

**Issue by opomuc** [tarantool/tarantool#3953]
```
# cat  /usr/local/etc/tarantool/instances.available/init.lua
local config = require('config')
local yaml = require('yaml')

local cfg = config.parse()

print(yaml.encode(cfg))
```
```
Tarantool 1.10.1-523-g671aada29

k:a opomuc$ tarantoolctl start init.lua
Starting instance init...
--- []
...

/usr/local/bin/tarantoolctl:541: attempt to index a nil value
```

**Comment by olegrok** [comment]
I tried to launch this script in tarantool-1.x:centos7 container and got error:
```
[root@56a86c0d2c8e tmp]# tarantoolctl start test.lua
Starting instance test...
Start failed: /tmp/.rocks/share/tarantool/config.lua:146: bad argument #1 to 'string.startswith' (string expected, got nil)
```

**Comment by Totktonada** [comment]
@opomuc @olegrok I don't know what are you trying to do here. It seems you just try to start an instance w/o box.cfg() call inside. I don't see a reason to support this case. However more meaningful error message from `tarantoolctl start` in the case would helpful.

Re config module errors: I don't know whether you use it correctly. If so, file another issue to this module.

**Comment by opomuc** [comment]
@Totktonada well, an issues with config is a different one and a ticket has been filed already.

I'm not sure if it is reasonable to assume everything must have `box.cfg{}` when called under `tarantoolctl`. If it is so, I must have missed it in the doc, and error message should be understandable

**Comment by opomuc** [comment]
@Totktonada okay, it does seem to be included in the doc

`
An instance file is designed to not differ in any way from a Lua application. It must, however, configure the database, i.e. contain a call to box.cfg{} somewhere in it, because it’s the only way to turn a Tarantool script into a background process, and tarantoolctl is a tool to manage background processes.
`

**Comment by Totktonada** [comment]
Changed the issue header to reflect a work need to be done here.
