### ISSUE TITLE
http.client doesn't honour 'connection: keep-alive'

### ISSUE THREAD

**Issue by ASverdlov** [tarantool/tarantool#3955]
Tarantool version:
Tarantool 1.10.2-1-ge0017ad

OS version:
Darwin MacBook-Pro-2.local 18.2.0 Darwin Kernel Version 18.2.0: Fri Oct  5 19:41:49 PDT 2018; root:xnu-4903.221.2~2/RELEASE_X86_64 x86_64

Bug description:
1) If you set `connection = 'Keep-Alive'` header in `client_object:request()` method, but don't set `keepalive_idle`, `keepalive_interval`, it sends both `Connection: Keep-Alive` *and* `Connection: close` headers.

This results in unspecified behaviour on server-side: server can close the connection or decide to keep it alive.

Steps to reproduce:
A) HTTP Keepalive header is set by user, but the module sends `Connection: close`:
```lua
#!/usr/bin/env tarantool

local http = require('http.client').new()

http:get('google.com', {
    verbose=true,
    headers={['Connection'] = 'Keep-Alive'},
})
```

produces:
```
...
> GET / HTTP/1.1
Host: www.google.com
Accept: */*
Connection: Keep-Alive
Connection: close
...
```

B) Now everything OK (HTTP Keepalive for some reason is inferred from TCP Keepalive)
```lua
#!/usr/bin/env tarantool

local http = require('http.client').new()

http:get('google.com', {
    verbose=true,
    headers={['Connection'] = 'Keep-Alive'},
    keepalive_idle=2, keepalive_interval=1
})
```

produces (**note duplicate header btw**):
```
...
> GET / HTTP/1.1
Host: www.google.com
Accept: */*
Connection: Keep-Alive
Connection: Keep-Alive
Keep-Alive: timeout=2
...
```

As a side note, TCP Keepalive and HTTP Keepalive are features of different protocols and serve different purposes. They should not have been intermixed in this way.

I don't propose breaking TCP Keepalive -> HTTP Keepalive deduction: we should leave it not to break existing applications.

Please just fix "smart" `Connection` header that is added in complete ignorance to what client provided:
1. if user has provided `connection` header options, don't add any on our own.
2. if user hasn't provided `connection` header options, leave current behaviour (that depends on `keepalive_interval`, `keepalive_idle` TCP Keepalive options set) for backward-compatibility.

**Comment by knazarov** [comment]
I suggest that we make keep-alive the default thing within a connection pool. It should be done without requiring the user to write anything except pool.get()

**Comment by kshcherbatov** [comment]
The problem is that the "Connection: Keep-Alive" header is inserted if the keepalive_idle, keepalive_interval parameters have been specified; otherwise, "Connection: close"is set.  Along with this, all values from the headers section are added to the query.
With the same success, you can add a few contradictory headings Keep-Alive: timeout, and even in the same way to add additional "Content-Length"(conflict when real body exists).
```
http:get('google.com', {
    verbose=true,
    headers={['Keep-Alive: timeout'] = 666}
})

> GET / HTTP/1.1
Host: www.google.com
Accept: */*
Keep-Alive: timeout: 666
Connection: close
```
Looks like you are not expected to set this header manually.  But it seems to me that some checks can really be introduced.

**Comment by kshcherbatov** [comment]
As I see, http.c manage {"Accept", "Content-Length", "Connection", "Keep-Alive: timeout"} headers.
The straightforward way is to disallow them to be specified in headers section.

**Comment by SWSAmor** [comment]
The Accept is not working for me with the patch.

**Comment by kshcherbatov** [comment]
> The Accept is not working for me with the patch.

Could we have multiple Accept headers?
Perhaps, we may do not append "Accept" to the exceptions list?

**Comment by SWSAmor** [comment]
No. We need one specific Accept header. We put that in the headers, but the Tarantool put Accept */* too.

**Comment by kshcherbatov** [comment]
> No. We need one specific Accept header. We put that in the headers, but the Tarantool put Accept _/_ too.

Thank you for feedback. I hope I fixed that now.

**Comment by SWSAmor** [comment]
Thank you. Tested. Works perfectly.
