### ISSUE TITLE
Segfault on 1.9.1-0-g06ec3d5

### ISSUE THREAD

**Issue by juise** [tarantool/tarantool#3957]
Tarantool version:
  Tarantool 1.9.1-0-g06ec3d5

OS version:
  CentOS Linux release 7.4.1708 (Core) 
  Derived from Red Hat Enterprise Linux 7.4 (Source)

Bug description:
  After restart 1/2 of the cluster, some xlog files have been corrupted, all restarted nodes segfaulted after ~1m working

Steps to reproduce:
  N/A

Optional (but very desirable):
[tarantool_segmentation_fault_logs.txt](https://github.com/tarantool/tarantool/files/2816763/tarantool_segmentation_fault_logs.txt)
[tarantool_coredump.zip](https://github.com/tarantool/tarantool/files/2817062/tarantool_coredump.zip)

**Comment by kyukhin** [comment]
No feedback for 2 wws. Closing.
