### ISSUE TITLE
http:client cut long header

### ISSUE THREAD

**Issue by norguhtar** [tarantool/tarantool#3959]
Tarantool version: 2.1 

OS version: Debian GNU/Linux 9.7 (stable/jessie)

Bug description: When put string longer than 1008 bytes in headers it cut to 1008 bytes

Steps to reproduce: 

run code from tarantool
```lua
local http = require("http.client").new()

local r=http:get("http://localhost",{headers={Athorization="ujaiJai7aeCo3uJo5Eefoo5ohiech3phah2rei7ahPhahzo2gaishoh2ohceeC2jaephia8thaeNei4Zi8KahJaD3johQuie4ahpooji4tuwohPahgheipu0rahsh1eeTohP4ruy2zoo0ienaek8eijaiweetaisau3ok4xia5feerahlifeeng3ah5Uo0ohd1eish6oGhedohcha8eenahphae0aht0ahloFai9Boa2soh1Oeb6cen2eiDahva4quiashah8eTeih6fuuxo4oaph7MioCah8ahG1eokikiehiPateeQuohru5kies0au9soo8ohkeiwei7DeNo8nainoh2ieyauFuK9Uu7oosaegoo3Taepuangiighie9iphie3ohhaicaefii8Waerueh6ioni9fahchu7Ho0Jiequi1oopaed7oTaiWooDaiNeiWaed0Shuw2ukei3hahzai0xi7doth7siG2bei7oew2miewi1ooPeghughiesh6ohTie7becheibo6wi4joo5ua0uaQuahthait9AeLaeBeiSu5cairai8aeC8tejoochoephei5ciequahnaethiet3liew5ohFohphaiB2yeeph9Ku0thaesh7Quaehiequejeiphoemai6phoNg5ru1sheveiveivoh9cheingaifaivu0ahquoh3ieDae9aisai6ePhaixueC9cae1engazieng4weiquahcoh8jih2beu7he2gae4iZaeyei4doh0quooXahCei4Gooy4ahs6tha6Ne7aifetieth2udai0poo5pos5eef2vingooShei8Chieziu6eipieshae5Ahy5shaengucheighai2wiPho7loo4eixaulahshiGh3aeCheitep8Shie1ThiekaD1Amauch1ChoodeeShohthuo9eivooy3daefea5wohvi9ohg0phovee2OoH8bahzie5xai8Pi8quie2shai5ais1aer3ChaeshuiWe9Uf"}})
```

expect on server header size is 1025. Got 1008 bytes

**Comment by Totktonada** [comment]
I think two things should be done here:

* Increase the maximum header size to 8 KiB.
* Raise an error if a header exceeds this size.

**Comment by norguhtar** [comment]
Header size have limit? Can you tell me where is it? I can fix that

**Comment by Totktonada** [comment]
I don't mean that there is user-controllable limit. It is due to TT_STATIC_BUF_LEN, which is used via tt_vsprintf() in httpc_set_header().

**Comment by norguhtar** [comment]
I see. But just incrase this limit not good solution. May be add other buffer structure for http client?

**Comment by Totktonada** [comment]
Of course. My phrase was just the idea of changes we should do as I think. Nothing about the code.

**Comment by norguhtar** [comment]
I rewrite httpc_set_header. Can you check it? I change add header into curl and add length check in header from lua context

**Comment by Totktonada** [comment]
Please, don't mix different changes into one PR. Send the another one.

**Comment by norguhtar** [comment]
I should split one commit on two? One for fix httpc_set_header and second for rise error?

**Comment by norguhtar** [comment]
I see. It put to other request. Revert it

**Comment by Totktonada** [comment]
> I should split one commit on two? One for fix httpc_set_header and second for rise error?

I don't think so.

> I see. It put to other request. Revert it

Yep. File a separate PR.

**Comment by norguhtar** [comment]
Done. I add new PR.
