### ISSUE TITLE
Introduce hint option for memtx tree index

### ISSUE THREAD

**Issue by kshcherbatov** [tarantool/tarantool#3961]
Rework memtx tree to use 'tuple hints'.
Special functions for retrieve tuple hints for a particular key_def. Hint is an integer that can be used for tuple comparison optimization: if a hint of one tuple is less than a hint of another then the first tuple is definitely less than the second; only if hints are equal tuple_compare must be called for getting comparison result.

Hints are only useful when:
* they are precalculated and stored along with the tuple;
calculation is not cheap (cheaper than tuple_compare btw) but
precalculated hints allow to compare tuples without even fetching
tuple data.
* first part of key_def is 'string', 'unsigned' or 'integer'
* since hint is calculated using only the first part of key_def
(and only first several characters if it is a string) this part
must be different with high probability for every tuple pair.

**Comment by locker** [comment]
Fixed by 9fba29abb4e05babb9b23b4413bd8083f0fba933
