### ISSUE TITLE
http.client segmentation fault

### ISSUE THREAD

**Issue by quitoman** [tarantool/tarantool#3973]
Tarantool version:
Tarantool 1.10.2-129-g8e103fbc3
OS version:
Ubuntu 18.10 x86_64
Bug description:
I'm getting a segmentation fault when I use the http.client module.
Steps to reproduce:
http_client = require('http.client').new()
r = http_client:request('GET','http://tarantool.org')
Optional (but very desirable):
#0  0x4f6a29 in print_backtrace+9
#1  0x413f27 in _ZL12sig_fatal_cbiP9siginfo_tPv+c7
#2  0x7fa4e6f54dd0 in funlockfile+50
#3  0x5175b0 in lj_debug_getinfo+1d0
#4  0x56491c in lj_cf_debug_getinfo+dc
#5  0x50e9c7 in lj_BC_FUNCC+34
#6  0x520254 in lua_pcall+64
#7  0x4e2ab3 in luaT_call+13
#8  0x4dc2a9 in lua_main+59
#9  0x4dc599 in run_script_f+289
#10 0x41340c in _ZL16fiber_cxx_invokePFiP13__va_list_tagES0_+c
#11 0x4f3a40 in fiber_loop+30
#12 0x619d9f in coro_init+3f

**Comment by Totktonada** [comment]
It is likely due to fiber stack size limit. See similar reports: #3569, #3418.

**Comment by quitoman** [comment]
Thank you for your efforts  :)
