### ISSUE TITLE
net.box inconsistent with respect to schema changes

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#398]
I have Ubuntu 12.04 with Tarantool 1.6, pulled from source today.  
I make sure there is no space named 'tester' before I start, by deleting the .xlog and .snap files.  
I execute these requests:
```
box.cfg{listen=3301}
box.schema.user.grant('guest', 'read,write,execute', 'universe')
net_box = require('net.box')
conn = net_box:new('127.0.0.1', 3301)
box.schema.create_space('tester')
box.space.tester:create_index('primary',{})
conn.space.tester
conn.space._space:select({0},{iterator='GE'})
```
The `conn.space.tester` request says there is no space named tester.
The `conn.space._space:select` request says there is a space named tester.

**Comment by rtsisyk** [comment]
`conn:reload_schema()` doesn't work properly:

```
 LISTEN = require('uri').parse(box.cfg.listen)                                                                                                          cn = remote:new(LISTEN.host, LISTEN.service) 
cn:ping()                                                                                                                                                 cn:call('unexists_procedure') 

box.schema.user.revoke('guest','execute','universe')                                                                             box.schema.user.revoke('guest','read,write,execute','universe')                                                            cn:reload_schema() 
```

**Comment by bigbes** [comment]
@rtsisyk: everything works fine for me on your example. Can't reproduce. Reopen if you can.

**Comment by pgulutzan** [comment]
Perhaps I should have explained more clearly when I said "The conn.space.tester request says there is no space named tester." What I see is this:
"
tarantool> conn.space.tester
---
- null
...
"
That is the sort of thing that happens when a space is not found. But the space exists.

**Comment by kostja** [comment]
Peter, for now we implemented connection:flush_schema() which you should use explicitly after a schema change on the remote server. We don't do automatic notifications about schema changes yet. This is gh-802.
