### ISSUE TITLE
Split box.info to app and db parts

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#399]
Currently box.info() contains some information that should be accessible in app server itself without calling `box.cfg{}` (e.g. Tarantool version, build number, compile options, etc.). We need this information in app server because loadable modules currently don't have a way to determine server version on start-up prior to call to box.cfg{}.

**Comment by rtsisyk** [comment]
May I implemented it?

**Comment by kostja** [comment]
Please check my recent commits, I added ffi.C.tarantool_version() and ffi.C.tarantool_uptime().
Please remove build options from box.info to an FFI binding, and leave everything else as is.
I think this is all that needs to be done for this bug for now.
