### ISSUE TITLE
Typo in both language versions of the documentation

### ISSUE THREAD

**Issue by dimtos** [tarantool/tarantool#4006]
Tarantool version:

OS version:

Bug description: typo in documentation - box_schema.space_mt is not correct object, must be box.schema.space_mt

Steps to reproduce: https://tarantool.io/ru/doc/1.10/book/box/box_space/#lua-function.space_object.user_defined

Optional (but very desirable):
* coredump
* backtrace
* netstat

**Comment by kyukhin** [comment]
Fixed.
