### ISSUE TITLE
Rename `net.box` 

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#401]
We decided that Tarantool module names will not be prefixed by category. In other words, `yaml` is `yaml `and isn't `data.yaml`, `socket` is `socket` and isn't `net.socket`, `box.net.pg` is just `pg` and so on.

I remember that initial idea was that Tarantool is a *database* with remote=network *database connectors* to pg, mysql and tarantool itself. This idea grew to **app server** conception, where are `net` is obviously related to network modules like `socket`, `pcap` or even `bgp`, but definitely not to database connectors.

BTW, I see **`test/box/box.net.box.test.lua`** file in the latest master... Java(c)(r)(tm) Enterprise Edition for Serious Business detected. 

Possible solutions:
1. Rename `net.box` to `remote`, `rbox`, `box.remote` or something like that
2. Integrate net.box with box more closely, e.g. `require('net.box').new(XXX)` => `box.connect(XXX)`
Please vote.

**Comment by rtsisyk** [comment]
I suggest `box.connect(uri)`.

**Comment by kostja** [comment]
I think it's not worth the time, and now it's too late in the life cycle.
Won't fix.
