### ISSUE TITLE
REQ not work on https://tarantool.io/ru/try-lts/ or error in the documentation

### ISSUE THREAD

**Issue by tesla1856** [tarantool/tarantool#4014]
Tarantool version: 1.10.0-0-g42612ec04
OS version: https://tarantool.io/ru/try-lts/
Bug description: REQ not work
Steps to reproduce:

```
Tarantool version 1.10.0-0-g42612ec04
Try command 'help' to get help.
tarantool> s=box.schema.space.create("qt");s:create_index("pk");
---
...
tarantool> s:insert{1};
---
- [1]
...
tarantool> s:insert{2};
---
- [2]
...
tarantool> s:insert{3};
---
- [3]
...
tarantool> s:select(2,{iterator="EQ"})
---
- - [2]
...
tarantool> s:select(2,{iterator="REQ"})
---
- - [2]
...
tarantool> s:select(2,{iterator="GE"})
---
- - [2]
  - [3]
...

```
or error in doc: 
- https://tarantool.io/ru/doc/1.10/book/box/data_model/ => "EQ (равно), REQ (неравно)"
- https://tarantool.io/ru/doc/1.10/book/box/box_index/#box-index-iterator-types => "Совпадения находятся таким же образом, что и для box.index.EQ."

**Comment by lenkis** [comment]
Fixed incorrect Russian text. Thanks for giving a shout!
