### ISSUE TITLE
Cleanup SQL types

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#4019]
Tarantool version: 2.1

OS version: any

Bug description:

SQL type system of Tarantool 2.1 should be more or less consistent.

Let's do some cleanup:
1. Remove DATE/TIME/DATETIME from prarser
2. Remove CHAR from parser
3. Remove DECIMAL/NUMERIC/NUM from parser

So, at the end of the day following types should be supported by SQL:
1. TEXT/VARCHAR(N), N is ignored, represented as STRING in space format
2. INTEGER/INT, represented as INTEGER in space format
3. FLOAT/REAL/DOUBLE, represented as NUMBER in space format (subject to change in future)
4. [biggest part of the issue]  Suppoty new type BLOB, represented as BINARY in format.
There's no such a type in formats, so need to introduce new field type and patch whole
Tarantool thoroughly

**Comment by Totktonada** [comment]
See #3650 re BLOBs.

**Comment by Korablev77** [comment]
Last point

> 4\. [biggest part of the issue]  Suppoty new type BLOB, represented as BINARY in format.
>     There's no such a type in formats, so need to introduce new field type and patch whole
>     Tarantool thoroughly

now is blocked by #4023
