### ISSUE TITLE
Strange behavior of box.session.fd

### ISSUE THREAD

**Issue by locker** [tarantool/tarantool#4021]
`box.session.fd(sid)` returns the file descriptor corresponding to the session with the given id. It can be useful for checking if the current connection is closed: `box.session.fd(box.session.id()) >= 0`. The id argument is mandatory, which is inconvenient. We should either use the current session id (i.e. `box.session.id()`) if it is omitted, or drop the argument altogether and always return the file descriptor of the current session (why would someone need to know fd of another session?). Alternatively, we can drop this function altogether, but then we must provide a new function for checking if the current connection has been closed, because presently there's no other way but `box.session.fd()`.

**Comment by kshcherbatov** [comment]
Hm, this method is really strange:
1) it is undocumented https://tarantool.io/ru/doc/1.10/book/box/box_session/#box-session-id
2) for your purpose you should use https://tarantool.io/ru/doc/1.10/book/box/box_session/#box-session-exists 
3) I've dropped box.session.fd and all tests are ok.

So, there are two questions:
1) Should I remove box.session.fd?
2) Should I support box.session.exists() without session_id argument?

**Comment by kshcherbatov** [comment]
I've asked @kostja, he believe that box.session.fd is useful.
So let's support to call box.session.exists and box.session.fd without any arguments - e.g. box.session.peer already support this feature.
