### ISSUE TITLE
Built-in function to get index key from tuple

### ISSUE THREAD

**Issue by sharonovd** [tarantool/tarantool#4025]
Would be very nice to have this onboard, I've seen 3 implementations already in the projects.

Proposed syntax:
space.test.index.primary:extract_key(tuple)

**Comment by kshcherbatov** [comment]
Decided to implement this patch over @Totktonada merger preparatory patch e1cd7086f438c0114ad7f6e1243bec3486f383e6

Therefore, the deletion for the secondary non-unique index will look like this:
```
s = box.schema.space.create('test')
pk = s:create_index('pk')
idx = s:create_index('test', {unique=false,
                     parts = {{2, 'number', path = 'a'},
                              {2, 'number', path = 'b'}}})
s:insert{1, {a = 1, b = 1}}
s:insert{2, {a = 1, b = 2}}
key_def = require('key_def')
pk_def = key_def.new(pk)
for _, tuple in pairs(idx:select({1, nil})) do
    local key = pk_def:extract_key(tuple)
    pk:delete(key)
end
 ```

**Comment by Totktonada** [comment]
We plan to introduce a key_def module with :extract_key(tuple) instance method, so this issue is covered by #3398. Closed as duplicate.
