### ISSUE TITLE
Remove digest.sha_hex() from the code

### ISSUE THREAD

**Issue by lenkis** [tarantool/tarantool#4028]
Support for SHA-0 (digest.sha()) was removed due to OpenSSL upgrade in 1.6.9. But digest.sha_hex() still exists in the API. We cleaned it out of the documentation. Probably it's worth removing sha_hex() from the code to avoid confusion for developers, at least from the current lts/dev versions.

**Comment by Totktonada** [comment]
```
Tarantool 2.1.1-410-g0c7a3e396
type 'help' for interactive help
tarantool> digest = require('digest')
---
...
tarantool> digest.sha('')
---
- error: 'builtin/digest.lua:251: Digest method "sha" is not supported'
...
tarantool> digest.sha_hex('')
---
- error: 'builtin/digest.lua:257: Digest method "sha" is not supported'
...
```

However digest.sha and digest.sha_hex functions are present (see below), so I'll prepare a patch to remove them.

```
tarantool> digest = require('digest')
---
...
tarantool> digest.sha
---
- 'function: 0x41e37d90'
...
tarantool> digest.sha_hex
---
- 'function: 0x41e37df8'
...
```
