### ISSUE TITLE
Non-blocking io.popen

### ISSUE THREAD

**Issue by knazarov** [tarantool/tarantool#4031]
It is sometimes needed to start a subprocess from tarantool and interact with it through stdin/stdout. The most useful case is for writing tests for bindings to some external daemon where you need to start and stop that daemon from test harness.

Current implementation of `io.popen` is blocking, and thus not suitable for tarantool.

**Comment by Totktonada** [comment]
Documentation request: https://github.com/tarantool/doc/issues/1248
