### ISSUE TITLE
sql: make aggregate functions accept arguments of the same type

### ISSUE THREAD

**Issue by Korablev77** [tarantool/tarantool#4032]
Couple of simple examples:

```
SELECT MAX(1, 'STR');
---
- - ['str']
...
CREATE TABLE t (a TEXT PRIMARY KEY);
INSERT INTO t VALUES (1), (2), (3), ('abc');
SELECT SUM(a) FROM t;
---
- - [6]
...

```
In the latter case all arguments must be numeric; in the first case - of the same type.

**Comment by pgulutzan** [comment]
The SQL manual currently says:
"
MAX(expression-1, expression-2, [expression-3 ...])
-- return the largest of the supplied expressions, or, if any expression
is NULL, return NULL
Do not confuse with MAX(expression), which is an aggregate function.
Example: MAX(7, 44, -1) is 44
Example: MAX(1E308, 'a', 0, X'00') is '\0', the nul character
Example: MAX(3, NULL, 2) is NULL
"
I believe that is correct.

**Comment by Korablev77** [comment]
Ok, my bad. Indeed, in the first example it's not an aggregate. But still, result looks confusing: to determine largest of the supplied expressions, they must be comparable. String literal 'str' and integer literal 1 are unlikely to be comparable in any sense (ofc we can implicitly cast int to str and compare two strings '1' and 'str', but I suppose this way is not what we really want).

**Comment by pgulutzan** [comment]
OK, my bad too, because I should have explained that the problem isn't the vocabulary, it is: why do I think the examples in the SQL manual are correct? I do not mean that an integer should be implicitly cast to a char, and I believe it will be wonderful if that is restricted by issue#3809. But when I say "SELECT TYPEOF(MAX(1E308, 'a', 0, X'00'));" I see that the data type is not integer and not char, it is BLOB. And the underlying Tarantool/NoSQL type of BLOB is 'scalar'. And in 'scalar' all those values are legal and comparable. Obviously the standard does not allow that syntax or that combination (I use the word "combination" in the way that the standard document uses it for section ""Result of data type combinations") but this is a Tarantool extension. If you still disagree, then I think this might require some discussion about policy, that is, what to do with 'scalar'.

**Comment by Korablev77** [comment]
There is a huge mess with blob and scalar types. Fortunately, we've realised that and decided to remove blob as a valid type and allow instead scalar type (since we failed to provide decent support of BLOB using only SCALAR; we need independent type integrated into NoSQL as well). And it is in scope of 2.1.2 release. SCALAR is a type-aggregation for all other types (available in SQL: INTEGER, NUMBER and STRING), i.e. its behaviour is the same as in NoSQL. Anyway, some day we will have to introduce that type in SQL to make it consistent with NoSQL. BLOB as a term still exists in SQL internals and in fact it represents strings to be encoded as MP_BIN (which matches definition of BLOB in NoSQL internals). For details, see doc request on this subject: https://github.com/tarantool/doc/issues/735

Ok, back to your example. Since BLOB doesn't mean SCALAR now (in every sense), it should result in error. If you have any questions concerning SQL SCALAR type (mb you will notice some bugs or general misbehaviour) or this particular issue, we can discuss it in dev mailing list.

**Comment by pgulutzan** [comment]
Okay, I replied in dev mailing list, subject line = The rules for the scalar data type in SQL.

**Comment by Gerold103** [comment]
According to the standard, if I correctly understand, `SUM()` should raise an error, of any of the values was NULL. Standard "ISO/IEC JTC 1/SC 32/WG 3 The United States of America (ANSI). Information technology — Database languages — SQL — Part 2: Foundation (SQL/Foundation), 2011, page 611". Am I correct, @pgulutzan ?

**Comment by pgulutzan** [comment]
Hi,

Not exactly an error. The standard document is using a
specialized term "completion condition" defined in Part I:
"
The phrase “a completion condition is raised”,
followed by a colon and the name of a condition,
is used in General Rules and elsewhere to indicate
that application of General Rules is not terminated
and diagnostic information is to be made available;
unless an exception condition is also raised,
the execution of the SQL-statement is successful.
"
So it's not what we usually mean when we say "error".

I mentioned this in
issue#2364 SQL clauses related to groups and aggregates
https://github.com/tarantool/tarantool/issues/2364
which is marked "won't fix".

**Comment by Korablev77** [comment]
I'm closing this issue. In Tarantool NoSQL it is allowed to compare values of different types (bool < numeric < string). Numeric aggregates (`SUM` etc) now throw errors in case of adding numbers with values of incompatible types (master branch):
```
tarantool> SELECT SUM(a) FROM t;
---
- error: 'Type mismatch: can not convert abc to number'
...

```
