### ISSUE TITLE
Please add 1.10 builds for Debian Sid

### ISSUE THREAD

**Issue by rybakit** [tarantool/tarantool#4037]
Tarantool 1.10 packages are not available on Debian Sid (unlike 1.9: https://packages.debian.org/source/sid/tarantool).

**Comment by Totktonada** [comment]
I filed #6155 mainly because I remember that somebody asked it. It seems, it was you.

Are you need Debian Sid or just currect testing (Bullseye) is okay now?

**Comment by rybakit** [comment]
> Are you need Debian Sid

No, I don't need it anymore.
