### ISSUE TITLE
sql: disallow different orders in ORDER BY clause

### ISSUE THREAD

**Issue by Korablev77** [tarantool/tarantool#4038]
Without multi-directional iterators (to be introduced in https://github.com/tarantool/tarantool/issues/3309) in most cases (except those when internal VDBE merge sorter is used) ORDER BY with different specified ordered leads to wrong result. For instance:

```
CREATE TABLE t (id INT PRIMARY KEY, a INT, b INT);
INSERT INTO t VALUES (1, 2, 1), (2, -3, 5), (3, 2, -3), (4, 2, 12);
SELECT * FROM t ORDER BY a ASC, b DESC LIMIT 5;
---
- - [2, -3, 5]
  - [3, 2, -3]
  - [1, 2, 1]
  - [4, 2, 12]
...

```
One can see that results are sorted by 'a' field, but not by 'b'. So lets temporary (util #3309 is resolved) disable this feature.

**Comment by pgulutzan** [comment]
The results in that example look correct to me. What results were expected?

**Comment by Korablev77** [comment]
Oh, sorry, I've slightly modified example (forgot to add LIMIT clause).
