### ISSUE TITLE
Backward compatibility broken

### ISSUE THREAD

**Issue by rosik** [tarantool/tarantool#4039]
Tarantool version: 1.10.2-162-g6d4db455d

Bug description:

Commit https://github.com/tarantool/tarantool/commit/6d4db455d1b6cc9a6c87928c2495423542c6d44e breaks backward compatibility with module stat 0.3.1 

Details: https://github.com/tarantool/stat/issues/20

Steps to reproduce:

```console
$ tarantoolctl rocks install stat
...
stat scm-1 is now installed in /tmp/tmp.VFuXWE5tXR/.rocks (license: BSD)

$ tarantool
Tarantool 1.10.2-162-g6d4db455d
type 'help' for interactive help
tarantool> box.cfg()
2019-03-12 09:43:12.632 [31012] main/101/interactive C> Tarantool 1.10.2-162-g6d4db455d
---
...

tarantool> require('stat').stat()
---
- error: '/tmp/tmp.VFuXWE5tXR/.rocks/share/tarantool/stat/init.lua:141: attempt to
    index local ''v'' (a number value)'
...

tarantool>

```

**Comment by sharonovd** [comment]
Problem is that when user updates from e. g. TT  1.10.2-48 -> 1.10.2-162 he does not expect that he should check (and maybe) update all the rocks he uses.
So this change breaks release policy - no features in patchset bumps.

**Comment by kyukhin** [comment]
This was important for customer. Moreover, this change doesn't break backward compatibility since it introduces new field in report, not alters anything. Please, update corresponding module.

**Comment by sharonovd** [comment]
The module is already updated, but bumping Tarantool LTS patchset should not require module version update!

**Comment by kyukhin** [comment]
Too many complaints. Let's just revert the patch from 1.10 branch.
