### ISSUE TITLE
Crash while inserting big tuples in master-master

### ISSUE THREAD

**Issue by makorne** [tarantool/tarantool#4043]
Tarantool version: Tarantool 1.10.2-0-gc0d8063b6

OS version:  Debian 4.9.144-3.1 (2019-02-19) x86_64 GNU/Linux

Bug description: master-master, tarantool-nginx, docker-compose
Testing, inserting big images(15mb) over wrk. 
After 2-3 images  - crash.

`backend_1   | 2019-03-14 09:26:52.895 [1] main/106/applier/replicator@backend1:310 I> can't read row
backend_1   | 2019-03-14 09:26:52.895 [1] main/106/applier/replicator@backend1:310 coio.cc:331 !> SystemError timed out: Operation timed out
backend_1   | 2019-03-14 09:26:52.895 [1] main/106/applier/replicator@backend1:310 I> will retry every 1.00 second
backend1_1  | 2019-03-14 09:26:52.896 [1] relay/172.24.0.2:43354/101/main recovery.cc:276 E> can't apply row: 
backend1_1  | 2019-03-14 09:26:52.896 [1] relay/172.24.0.2:43354/101/main I> fiber `main' has been cancelled
backend1_1  | 2019-03-14 09:26:52.896 [1] relay/172.24.0.2:43354/101/main I> fiber `main': exiting
backend1_1  | 2019-03-14 09:26:52.896 [1] relay/172.24.0.2:43354/101/main I> fiber `main' has been cancelled
backend1_1  | 2019-03-14 09:26:52.896 [1] relay/172.24.0.2:43354/101/main I> fiber `main': exiting
backend1_1  | 2019-03-14 09:26:52.896 [1] relay/172.24.0.2:43354/101/main C> exiting the relay loop
nginx_1     | 172.24.0.1 - - [14/Mar/2019:09:26:53 +0000] "POST /api/add HTTP/1.1" 499 0 "-" "-"
nginx_1     | 172.24.0.1 - - [14/Mar/2019:09:26:53 +0000] "POST /api/add HTTP/1.1" 499 0 "-" "-"
backend1_1  | 2019-03-14 09:26:53.665 [1] main/105/applier/replicator@backend:3109 txn.c:295 W> too long WAL write: 1 rows at LSN 521: 0.911 sec
backend1_1  | 2019-03-14 09:26:53.725 [1] main/124/main txn.c:295 W> too long WAL write: 1 rows at LSN 522: 0.752 sec
backend1_1  | 2019-03-14 09:26:53.794 [1] relay/172.24.0.2:43354/101/main recovery.cc:276 E> can't apply row: 
backend1_1  | 2019-03-14 09:26:53.794 [1] relay/172.24.0.2:43354/101/main sio.cc:303 !> SystemError writev(2), called on fd 13, aka 172.24.0.3:3109: Broken pipe
backend1_1  | 2019-03-14 09:26:53.795 [1] relay/172.24.0.2:43354/101/main sio.cc:303 !> SystemError writev(2), called on fd 13, aka 172.24.0.3:3109: Broken pipe
backend1_1  | Segmentation fault
backend1_1  |   code: SEGV_MAPERR
backend1_1  |   addr: 0x7f9601c9904c
backend1_1  |   context: 0x7f963c44f580
backend1_1  |   siginfo: 0x7f963c44f6b0
backend1_1  |   rax      0xa                10
backend1_1  |   rbx      0x556f36a73300     93936146658048
backend1_1  |   rcx      0x7f96408c22db     140283304747739
backend1_1  |   rdx      0x0                0
backend1_1  |   rsi      0x7f9601c99020     140282251808800
backend1_1  |   rdi      0x556f36a4f240     93936146510400
backend1_1  |   rsp      0x7f963c44fb20     140283232975648
backend1_1  |   rbp      0x7f963c44fb40     140283232975680
backend1_1  |   r8       0x0                0
backend1_1  |   r9       0x0                0
backend1_1  |   r10      0x0                0
backend1_1  |   r11      0x246              582
backend1_1  |   r12      0x556f36a75638     93936146667064
backend1_1  |   r13      0x556f36a731e0     93936146657760
backend1_1  |   r14      0x10a02            68098
backend1_1  |   r15      0x0                0
backend1_1  |   rip      0x556f34e5f2a5     93936117215909
backend1_1  |   eflags   0x10202            66050
backend1_1  |   cs       0x33               51
backend1_1  |   gs       0x0                0
backend1_1  |   fs       0x0                0
backend1_1  |   cr2      0x7f9601c9904c     140282251808844
backend1_1  |   err      0x4                4
backend1_1  |   oldmask  0x0                0
backend1_1  |   trapno   0xe                14
backend1_1  | Current time: 1552555613
backend1_1  | Please file a bug at http://github.com/tarantool/tarantool/issues
backend1_1  | Attempting backtrace... Note: since the server has already crashed, 
backend1_1  | this may fail as well
backend1_1  | #0  0x556f34d35559 in print_backtrace+9
backend1_1  | #1  0x556f34c4c2ba in _ZL12sig_fatal_cbiP9siginfo_tPv+ca
backend1_1  | #2  0x7f96408b1e17 in sigwaitinfo+8
backend1_1  | #3  0x556f34d02f26 in recovery_delete+86
backend1_1  | #4  0x556f34d053e4 in _ZL10relay_stopP5relay+64
backend1_1  | #5  0x556f34d06750 in _Z15relay_subscribeP7replicaimP6vclockj+100
backend1_1  | #6  0x556f34cf73f3 in _Z21box_process_subscribeP5ev_ioP11xrow_header+583
backend1_1  | #7  0x556f34c4e618 in _ZL25tx_process_join_subscribeP4cmsg+68
backend1_1  | #8  0x556f34d36d24 in cmsg_deliver+14
backend1_1  | #9  0x556f34d378cf in fiber_pool_f+ff
backend1_1  | #10 0x556f34c4bc8c in _ZL16fiber_cxx_invokePFiP13__va_list_tagES0_+c
backend1_1  | #11 0x556f34d322f0 in fiber_loop+30
backend1_1  | #12 0x556f34e6cf6f in coro_init+3f
backend_1   | 2019-03-14 09:26:53.915 [1] main/125/main txn.c:295 W> too long WAL write: 1 rows at LSN 521: 1.115 sec
backend_1   | 2019-03-14 09:26:53.951 [1] relay/172.24.0.3:48104/101/main recovery.cc:276 E> can't apply row: 
backend_1   | 2019-03-14 09:26:53.951 [1] relay/172.24.0.3:48104/101/main I> fiber `main' has been cancelled
backend_1   | 2019-03-14 09:26:53.951 [1] relay/172.24.0.3:48104/101/main I> fiber `main': exiting
backend_1   | 2019-03-14 09:26:53.952 [1] relay/172.24.0.3:48104/101/main I> fiber `main' has been cancelled
backend_1   | 2019-03-14 09:26:53.952 [1] relay/172.24.0.3:48104/101/main I> fiber `main': exiting
backend_1   | 2019-03-14 09:26:53.952 [1] relay/172.24.0.3:48104/101/main C> exiting the relay loop
backend_1   | Segmentation fault
backend_1   |   code: SEGV_MAPERR
backend_1   |   addr: 0x7f234346a04c
backend_1   |   context: 0x7f237ec4f580
backend_1   |   siginfo: 0x7f237ec4f6b0
backend_1   |   rax      0xa                10
backend_1   |   rbx      0x56396f3e61a0     94804679483808
backend_1   |   rcx      0x7f2382dc72db     139790496068315
backend_1   |   rdx      0x0                0
backend_1   |   rsi      0x7f234346a020     139789429284896
backend_1   |   rdi      0x56396f2fe7a0     94804678535072
backend_1   |   rsp      0x7f237ec4fb20     139790427421472
backend_1   |   rbp      0x7f237ec4fb40     139790427421504
backend_1   |   r8       0x0                0
backend_1   |   r9       0x0                0
backend_1   |   r10      0x0                0
backend_1   |   r11      0x246              582
backend_1   |   r12      0x56396f3e84d8     94804679492824
backend_1   |   r13      0x56396f3e6080     94804679483520
backend_1   |   r14      0x10a02            68098
backend_1   |   r15      0x0                0
backend_1   |   rip      0x56396dbc82a5     94804654195365
backend_1   |   eflags   0x10202            66050
backend_1   |   cs       0x33               51
backend_1   |   gs       0x0                0
backend_1   |   fs       0x0                0
backend_1   |   cr2      0x7f234346a04c     139789429284940
backend_1   |   err      0x4                4
backend_1   |   oldmask  0x0                0
backend_1   |   trapno   0xe                14
backend_1   | Current time: 1552555613
backend_1   | Please file a bug at http://github.com/tarantool/tarantool/issues
backend_1   | Attempting backtrace... Note: since the server has already crashed, 
backend_1   | this may fail as well
backend_1   | #0  0x56396da9e559 in print_backtrace+9
backend_1   | #1  0x56396d9b52ba in _ZL12sig_fatal_cbiP9siginfo_tPv+ca
backend_1   | #2  0x7f2382db6e17 in sigwaitinfo+8
backend_1   | #3  0x56396da6bf26 in recovery_delete+86
backend_1   | #4  0x56396da6e3e4 in _ZL10relay_stopP5relay+64
backend_1   | #5  0x56396da6f750 in _Z15relay_subscribeP7replicaimP6vclockj+100
backend_1   | #6  0x56396da603f3 in _Z21box_process_subscribeP5ev_ioP11xrow_header+583
backend_1   | #7  0x56396d9b7618 in _ZL25tx_process_join_subscribeP4cmsg+68
backend_1   | #8  0x56396da9fd24 in cmsg_deliver+14
backend_1   | #9  0x56396daa08cf in fiber_pool_f+ff
backend_1   | #10 0x56396d9b4c8c in _ZL16fiber_cxx_invokePFiP13__va_list_tagES0_+c
backend_1   | #11 0x56396da9b2f0 in fiber_loop+30
backend_1   | #12 0x56396dbd5f6f in coro_init+3f
backend_1 exited with code 139
backend1_1 exited with code 139

`

**Comment by locker** [comment]
Looks like #3910. Please upgrade. If the crash happens again after upgrade, feel free to reopen the issue.
