### ISSUE TITLE
gmake failed caused by 'swim' in FreeBSD

### ISSUE THREAD

**Issue by webching** [tarantool/tarantool#4050]
Tarantool version: 2.1
OS version: FreeBSD 12.0

# gmake 
....
Displaying: 

Scanning dependencies of target swim
[ 21%] Building C object src/lib/swim/CMakeFiles/swim.dir/swim.c.o
In file included from /home/tester/tarantool/src/lib/swim/swim.c:32:
In file included from /home/tester/tarantool/src/lib/swim/swim_io.h:36:
/home/tester/tarantool/src/lib/swim/swim_transport.h:41:21: error: field has incomplete type
      'struct sockaddr_in'
        struct sockaddr_in addr;
                           ^
/home/tester/tarantool/src/lib/swim/swim_transport.h:41:9: note: forward declaration of 'struct sockaddr_in'
        struct sockaddr_in addr;
               ^
/home/tester/tarantool/src/lib/swim/swim_transport.h:56:33: error: declaration of 'struct sockaddr' will not be
      visible outside of this function [-Werror,-Wvisibility]
                    size_t size, const struct sockaddr *addr,
                                              ^
/home/tester/tarantool/src/lib/swim/swim_transport.h:61:14: error: declaration of 'struct sockaddr' will not be
      visible outside of this function [-Werror,-Wvisibility]
                    struct sockaddr *addr, socklen_t *addr_size);
                           ^
/home/tester/tarantool/src/lib/swim/swim_transport.h:71:20: error: declaration of 'struct sockaddr' will not be
      visible outside of this function [-Werror,-Wvisibility]
                    const struct sockaddr *addr, socklen_t addr_len);
                                 ^
In file included from /home/tester/tarantool/src/lib/swim/swim.c:32:
/home/tester/tarantool/src/lib/swim/swim_io.h:201:21: error: field has incomplete type 'struct sockaddr_in'
        struct sockaddr_in dst;
                           ^
/home/tester/tarantool/src/lib/swim/swim_transport.h:41:9: note: forward declaration of 'struct sockaddr_in'
        struct sockaddr_in addr;
               ^
In file included from /home/tester/tarantool/src/lib/swim/swim.c:33:
/home/tester/tarantool/src/lib/swim/swim_proto.h:81:21: error: field has incomplete type 'struct sockaddr_in'
        struct sockaddr_in addr;
                           ^
/home/tester/tarantool/src/lib/swim/swim_transport.h:41:9: note: forward declaration of 'struct sockaddr_in'
        struct sockaddr_in addr;
               ^
In file included from /home/tester/tarantool/src/lib/swim/swim.c:33:
/home/tester/tarantool/src/lib/swim/swim_proto.h:280:21: error: field has incomplete type 'struct sockaddr_in'
        struct sockaddr_in src;
                           ^
/home/tester/tarantool/src/lib/swim/swim_transport.h:41:9: note: forward declaration of 'struct sockaddr_in'
        struct sockaddr_in addr;
               ^
/home/tester/tarantool/src/lib/swim/swim.c:304:9: error: returning 'void' from a function with incompatible
      result type 'struct swim *'
        return container_of(scheduler, struct swim, scheduler);
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/tester/tarantool/src/trivia/util.h:200:41: note: expanded from macro 'container_of'
#define container_of(ptr, type, member) ({ \
                                        ^~~~
8 errors generated.

**Comment by Totktonada** [comment]
Maybe `#include <netinet/in.h>` is forgotten, see 311e8fce90011fd7aad930c02b79804d2d6050f7.

**Comment by avtikhon** [comment]
2.1 is also needed the patch
