### ISSUE TITLE
Migrate to luarocks 3

### ISSUE THREAD

**Issue by knazarov** [tarantool/tarantool#4052]
There are many problems with how current luarocks handles manifests. In some cases for instance it leads to unintelligible errors.

For example:

- tarantoolctl rocks install cluster
- cluster is installed as cluster_0_6_3_1-cluster (yes, with that suffix!)
- cluster rock refuses to load when using require('cluster')

There are internal race conditions of different sorts that bite us on a regular basis. Many of those issues are fixed in luarocks 3.0. So let's rebase on top of them.

**Comment by Totktonada** [comment]
Maybe also worth to revert [changes][1] that are needed to require luarocks at tarantool initialization to simplify this and future updates. AFAIR, this ability was planned to be used with luazip to install bundled rocks, but we decided to proceed in another way (#3641).

[1]: https://github.com/tarantool/luarocks/pull/2

**Comment by knazarov** [comment]
I know nothing about other plans. To be honest, I still plan to keep luarocks bundled in the same binary in tarantool enterprise, for many reasons. The main one being that I want to be able to use luarocks commands when located inside production app bundle.

**Comment by knazarov** [comment]
To clarify: I don't think that refactoring of tarantoolctl will likely happen in some foreseeable future, given other problems.
