### ISSUE TITLE
Traces of BLOB data type

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#4068]
I have Ubuntu 18.04.
I have Tarantool 2.1, pulled from source today.

Recently support for the BLOB data type was removed.
But I still see traces of it.

tarantool>select 1 || 1;
Error . Inconsistent types: expected TEXT or BLOB got INTEGER (0.0 seconds)

tarantool>SELECT TYPEOF(X'41');
OK 1 rows affected (0.0 seconds)
+---------------+
| TYPEOF(X'41') |
+---------------+
| blob          |
+---------------+

**Comment by Korablev77** [comment]
AFAIR we've agreed that values to be encoded with MP_BIN format have type BLOB. So, to force this way of encoding one should use format of literal X'...' I don't consider this is a bug, especially taking into consideration the fact that in 2.2.0 we are going to introduce BLOB as NoSQL type.

**Comment by pgulutzan** [comment]
Okay, I was wrong to suggest this is a problem that needs to be fixed in the code. It will be in the documentation, temporarily. Please mark as "won't fix".
