### ISSUE TITLE
 tarantoolctl cat --show-system interface is badly broken

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#4076]
```sh
$ tarantoolctl cat --show-system 00000000000000000117.snap 
builtin/internal.argparse.lua:35: Bad input for parameter "show-system". Expected boolean, got "00000000000000000117.snap"
$ tarantoolctl cat --show-system true 00000000000000000117.snap 
builtin/internal.argparse.lua:35: Bad input for parameter "show-system". Expected boolean, got "true"
$ tarantoolctl cat --show-system 1 00000000000000000117.snap 
builtin/internal.argparse.lua:35: Bad input for parameter "show-system". Expected boolean, got "1"
$ tarantoolctl cat --show-system=true 00000000000000000117.snap 
builtin/internal.argparse.lua:35: Bad input for parameter "show-system". Expected boolean, got "true"
$ tarantoolctl cat --show-system=1 00000000000000000117.snap 
builtin/internal.argparse.lua:35: Bad input for parameter "show-system". Expected boolean, got "1"
```

I don't find a way to set this option. Tarantool 2.1.1-416-gbe7d940f5.

**Comment by bigbes** [comment]
`tarantoolctl cat 00000000000000000000.* --show-system`

**Comment by Totktonada** [comment]
Thanks!

**Comment by locker** [comment]
I myself have always found this behavior weird:
```
tarantoolctl cat --space=512 00000000000000000000.xlog # ok
tarantoolctl cat --space=512 --show-system 00000000000000000000.xlog # fails
tarantoolctl cat --show-system --space=512 00000000000000000000.xlog # ok
tarantoolctl cat --show-system 00000000000000000000.xlog # fails
tarantoolctl cat 00000000000000000000.xlog --show-system # ok
```

The error message is confusing, too:
```
$ tarantoolctl cat --show-system 00000000000000000000.xlog
builtin/internal.argparse.lua:35: Bad input for parameter "show-system". Expected boolean, got "00000000000000000000.xlog"
$ tarantoolctl cat --show-system true 00000000000000000000.xlog
builtin/internal.argparse.lua:35: Bad input for parameter "show-system". Expected boolean, got "true"
```

I didn't bother to open a ticket, but since Alexander stumbled upon this issue too and opened one, I think we should fix it.

**Comment by Totktonada** [comment]
The previous implementation allows to pass a boolean parameter at end of a parameters list, but doesn't allow to pass it in a middle giving a confusing error message. The new implementation, which closes this issue, still allows to pass a boolean parameter w/o a value at end of the list, but also allows to pass it in a middle (or at the end) with one value: true, 1, false or 0, e. g. `--foo true` or `--foo=true`.

I think we should leave boolean parameters w/o an argument (as it was before), but allow to pass them in a middle of parameters list: I mean, prevent 'eating' of a next parameter. I'll prepare the patch about that.

**Comment by Totktonada** [comment]
After the [discussion][1] with Vlad we decided to mark the issue as resolved and mark my patch as the follow-up for Vlad's one.

[1]: https://lists.tarantool.org/pipermail/tarantool-patches/2019-November/012345.html
