### ISSUE TITLE
box.atomic doesn't respect convention for returning errors from functions

### ISSUE THREAD

**Issue by knazarov** [tarantool/tarantool#4085]
Currently `box.atomic` will only rollback the transaction in case of exceptions. The following code will not:

```lua
box.atomic(function()
    -- ... some box.space operations here ...
    return nil, 'An error occured'
end)
```

Since we recommend our users to return errors as values from functions instead of throwing them, I think we should roll back the transaction in the example above.

**Comment by knazarov** [comment]
Of course, the transaction should still roll back on regular exceptions as well

**Comment by GeorgyKirichenko** [comment]
The main issue is that your approach breaks backward compatibility.
Moreover it is not applicable in some cases (for instance on replace, before replace, box functions) and makes tarantool function interface inconsistent from some point of view.
Let think together more thoughtful about that.

**Comment by Totktonada** [comment]
I'm afraid that this will make the function unusable for libraries, because they obligated to support wide range of tarantool versions.

**Comment by kyukhin** [comment]
No feedback for month. Closing
