### ISSUE TITLE
sql: make CREATE TABLE truly transactional

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#4086]
When #4083 is implemented, it will be possible not to
store DDL operations in artificial list, but do CREATE TABLE
inside a transaction.

**Comment by Gerold103** [comment]
Blocked by #4364 - SQL uses savepoints as transactions inside transactions, for all multirow statements, including forthcoming transactional DDL.

**Comment by Gerold103** [comment]
Blocked by #4365.
