### ISSUE TITLE
Error while closing socket.tcp_server socket

### ISSUE THREAD

**Issue by rtokarev** [tarantool/tarantool#4087]
Tarantool version: 2.1.1-476-gaf74255

OS version: CentOS release 6.4 (Final)

Bug description: tarantool reports error to log after socket created using socket.tcp_server is closed

Steps to reproduce:

```
Tarantool 2.1.1-476-gaf74255
type 'help' for interactive help
tarantool> socket = require('socket')
---
...

tarantool> s = socket.tcp_server("0", "3300", function() end)
started
---
...

tarantool> s:close()
---
- true
...

tarantool> LuajitError: builtin/socket.lua:80: attempt to use closed socket
```

**Comment by artur-barsegyan** [comment]
Reproduce this issue on macOS 10.14.1 (18B75) but after recreating `tcp_server()` on this port immediately after `close()` current instance of `tcp_server()`.

**Comment by artur-barsegyan** [comment]
Reproduce this bug on macOS 10.14.1 (18B75). Tarantool version 1.10.2-175-gb3656d459

As I understood, [in socket.lua impl](https://github.com/tarantool/tarantool/blob/master/src/lua/socket.lua#L1067) throws error in case of closed socket and this case is uncovered. `tcp_server` fiber should manage a fiber with `tcp_server_loop` and cancel it in case of closing.

**Comment by rosik** [comment]
I saw it too

**Comment by sergos** [comment]
Expected behavior is just do not report an error? 
What should happen if one fiber keep reading the socket, while the second one closes it?

**Comment by rtokarev** [comment]
> Expected behavior is just do not report an error?

In case of `socket.tcp_server' - yes, an error shouldn't be reported, because it's normally to close a server socket.

> What should happen if one fiber keep reading the socket, while the second one closes it?

Well, maybe eof is ok in this case, but in the other hand, an error is also ok because it could be handled by a caller.

**Comment by rosik** [comment]
could you fix that second fiber, which keeps reading from closed socket? is that ever possible?

**Comment by theonedemon** [comment]
up? any news?

**Comment by LeonidVas** [comment]
Pushed to 1.10, 2.3+

> up? any news?

Pushed to 1.10, 2.3+
