### ISSUE TITLE
 1.10.3: can't create tuple using :frommap() from map with an empty sequence key field 

### ISSUE THREAD

**Issue by d9k** [tarantool/tarantool#4096]
Tarantool version: 1.10.2.203.g0b7078a93-1, 1.10.3-1-gfc6d6a338

OS version: Debian 9.6

Bug description:

`space:frommap()` fails with an error `"Tuple field 1 type does not match one required by operation: expected integer"` while 1st field is an integer sequence.

There wasn't such error in Tarantool `1.10.2.119.g21f87c30d-1`

Steps to reproduce:

```
> box.space.my_space:format()
---
- [{'name': 'id', 'type': 'integer'},
. . . . .
> box.space.my_space:create_index("primary", {
  parts = { { 1, "integer",
      is_nullable = false
    } },
  sequence = true,
  type = "tree",
  unique = true
})
```

**Comment by d9k** [comment]
Bug appeared between `1.10.2.119.g21f87c30d-1` and `1.10.2.203.g0b7078a93-1` versions

**Comment by kshcherbatov** [comment]
I'm not sure it's a bug. Perhaps the previous behavior(although it was convenient for you) was a bug.
I'll deal with it later.

**Comment by d9k** [comment]
@kshcherbatov, I can't see why it was buggy behavior.
Do you suggest calling `map.id = my_sequence:next()` manually before converting to the tuple from map?

**Comment by kshcherbatov** [comment]
@d9k now tuple is validated to match target space format before it is returned to user. Maybe it worth to introduce exception for nullable fields that have autoincrement.

**Comment by d9k** [comment]
@kshcherbatov, thanks for explanation :smiley: 

> Maybe it worth to introduce exception for nonnullable fields that have autoincrement.

:heavy_plus_sign:  :100:

**Comment by kshcherbatov** [comment]
@sharonovd we may rollback #4045  patch 9e2a905c069e58cdd95d91868025391ecd9404e6 to support this autoincrement if you wish. We are looking a system solution for this problem, but now it looks unnatural.

```
diff --git a/src/box/lua/space.cc b/src/box/lua/space.cc
index 93269b72b..6977a27c1 100644
--- a/src/box/lua/space.cc
+++ b/src/box/lua/space.cc
@@ -515,7 +515,7 @@ lbox_space_frommap(struct lua_State *L)
 
 	lua_replace(L, 1);
 	lua_settop(L, 1);
-	tuple = luaT_tuple_new(L, -1, space->format);
+	tuple = luaT_tuple_new(L, -1, box_tuple_format_default());
 	if (tuple == NULL)
 		return luaT_error(L);
 	luaT_pushtuple(L, tuple);
diff --git a/test/box/tuple.result b/test/box/tuple.result
index 2561ebc35..74e5f9e55 100644
--- a/test/box/tuple.result
+++ b/test/box/tuple.result
@@ -1121,7 +1121,7 @@ s:frommap()
 ...
 s:frommap({})
 ---
-- error: Tuple field 1 required by space format is missing
+- []
 ...
 s:frommap({ddd = 1, aaa = 2, ccc = 3, bbb = 4}, {table = true})
 ---
@@ -1237,17 +1237,7 @@ s2:frommap({a="1", k="11"})
 --
 s2:frommap({a="1", k="11"}):tomap({names_only = true})
 ---
-- i: null
-  f: null
-  c: null
-  g: null
-  b: null
-  j: null
-  k: '11'
-  d: null
-  h: null
-  a: '1'
-  e: null
+- []
 ...
 s2:drop()
 ---
```

**Comment by kshcherbatov** [comment]
Confirmed won't fix
