### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by seet61** [tarantool/tarantool#4098]
Tarantool version:
Tarantool 1.10.2-180-gcc3b5646e

OS version:
Debian GNU/Linux 9.8

Bug description:
Segmentation fault

Comment:
I use tarantool as cache with memtx spaces. Tonight at 00:00 we got a Segmentation fault on two servers at the same time. After that services can't start. When I am purge memtx_dir and restart services it start normally. 

Optional (but very desirable):
* syslog
[syslog.zip](https://github.com/tarantool/tarantool/files/3041899/syslog.zip)

* grafana 
![image](https://user-images.githubusercontent.com/6140289/55531932-a1ca4300-56b4-11e9-83c6-19d6e3b94bac.png)

**Comment by Totktonada** [comment]
Backtrace from the log file:

```
#0  0x4f9c89 in print_backtrace+9
#1  0x40f917 in _ZL12sig_fatal_cbiP9siginfo_tPv+c7
#2  0x7f6f719b30e0 in __restore_rt+0
#3  0x7f6f7076fe72 in vsnprintf+62
#4  0x7f6f7074f2c2 in snprintf+82
#5  0x5a4a12 in request_str+172
#6  0x4b63c4 in _ZL9apply_rowP7xstreamP11xrow_header+1a4
#7  0x4c6986 in xstream_write+6
#8  0x4c6e90 in _ZL17applier_subscribeP7applier+310
#9  0x4c80e8 in _ZL9applier_fP13__va_list_tag+1b8
#10 0x40edac in _ZL16fiber_cxx_invokePFiP13__va_list_tagES0_+c
#11 0x4f6970 in fiber_loop+30
#12 0x63083f in coro_init+3f
#13 (nil) in +3f
```

The relevant code:

```c
 311 static inline void
 312 apply_row(struct xstream *stream, struct xrow_header *row)
 313 {
 314         (void) stream;
 315         struct request request;
 316         xrow_decode_dml_xc(row, &request, dml_request_key_map(row->type));
 317         if (request.type == IPROTO_NOP) {
 318                 if (process_nop(&request) != 0)
 319                         diag_raise();
 320                 return;
 321         }
 322         struct space *space = space_cache_find_xc(request.space_id);
 323         if (process_rw(&request, space, NULL) != 0) {
 324                 say_error("error applying row: %s", request_str(&request));
 325                 diag_raise();
 326         }
 327 }
```

It seems that box_process_rw() call from apply_row() failed and request_str() is called. request_str() is bunch of snprintf() calls. Don't know how it can fail. Don't know also how to reproduce the issue.

I suggest to enable core dumps and if it will occur again share it with us (you can do it privately if it contain some private data).

**Comment by locker** [comment]
A similar crash was fixed by commit 8a1a0a9ffde1fbe662dd4c215416eff31a28cd30 in 1.10.2-185-g8a1a0a9f. May be the same issue.

**Comment by Totktonada** [comment]
Ouch, snprintf returns amount of bytes in a whole result, not a part that was really written to a buffer. Now understood the issue.

**Comment by seet61** [comment]
Updated to version 1.10.3-1-gfc6d6a338. Watch. At night the problem appeared at 00:00:06.

**Comment by seet61** [comment]
There was no problem today, but there was a desynchronization of instances at 01:17, no errors in logs.

**Comment by kyukhin** [comment]
So, there's no crash anymore?

**Comment by seet61** [comment]
After update, no crashes, but everytime desynchronisations between nodes.
