### ISSUE TITLE
Tarantool fiber hangs with errinj

### ISSUE THREAD

**Issue by kshcherbatov** [tarantool/tarantool#4100]
Tarantool version:
2.1.1

Bug description:
Tarantool hangs

Steps to reproduce:
s1 = box.schema.create_space("a")
s2 = box.schema.create_space("b")
pk2 = s2:create_index('pk')
drop_space = function() box.space._space.index.primary:delete(s1.id) end
fiber = require('fiber')
box.error.injection.set("ERRINJ_WAL_DELAY", true)
f2 = fiber.create(drop_space)
s2:insert({1})
--- hangs now :(
--- box.error.injection.set("ERRINJ_WAL_DELAY", false)

**Comment by locker** [comment]
Why do you think it's a bug? AFAICS the error injection works as expected - stalls all writes until it is turned off.

**Comment by kshcherbatov** [comment]
Originally met it in Nikita's review.

```
I’ve found way to make Tarantool hang:

box.sql.execute("create table t(id int primary key check (id > 5))")
drop_ck = function() box.space._ck_constraint:delete({'CK_CONSTRAINT_1_T', box.space.T.id}) end
fiber = require('fiber')
box.error.injection.set("ERRINJ_WAL_DELAY", true)
f2 = fiber.create(drop_ck)
box.sql.execute("INSERT INTO t VALUES(1)")
box.error.injection.set("ERRINJ_WAL_DELAY", false)

Please, find the reason of that and add several tests like this:
insert/update + create/drop CK + delayed wal injection.
```

Ok, let's close it
