### ISSUE TITLE
travis-ci: need to switch add force flag at release either even at all travis-ci test jobs

### ISSUE THREAD

**Issue by avtikhon** [tarantool/tarantool#4101]
Tarantool version:
All

OS version:
All

Bug description:
It is needed to add force flag at Tarantool release either even at all tarvis-ci test jobs, to be able to show all failings tests.

Steps to reproduce:
Run on travis-ci

Optional (but very desirable):
* coredump
* backtrace
* netstat

**Comment by Totktonada** [comment]
Dupe of #4131. Already fixed.
