### ISSUE TITLE
Status of 4kn capability on tarantool vinly?

### ISSUE THREAD

**Issue by jobs-git** [tarantool/tarantool#4105]
What is the status of [4kn](https://en.wikipedia.org/wiki/Advanced_Format) capability in tarantool?

**Comment by kostja** [comment]
Why would you suspect there are any issues?

**Comment by jobs-git** [comment]
It was mentioned that databases are the most affected by 4Kn format. I have not tested yet, and I am afraid to loose data if ever.

**Comment by kyukhin** [comment]
Not a bug.
