### ISSUE TITLE
Crash if vinyl space is dropped while being read from

### ISSUE THREAD

**Issue by locker** [tarantool/tarantool#4109]
**Tarantool version:**

2.2.0-124-gdafd3926
2.1.2-6-g42f8dddda09f and 1.10.3-4-g995376f5 are affected as well.

**Bug description:**

Tarantool crashes if a space is dropped while being read from:
```
tarantool: /home/vlad/src/tarantool/src/lib/small/small/matras.h:345: matras_view_get_no_check: Assertion `id < v->block_count' failed.
```

**Steps to reproduce:**

Run the following script in a clean directory:
```Lua
fiber = require('fiber')

box.cfg{}

-- Create a space and dump it to disk.
box.schema.space.create('test', {engine = 'vinyl'})
box.space.test:create_index('primary')
box.space.test:replace{1}
box.snapshot()

-- Slow down disk reads.
box.error.injection.set('ERRINJ_VY_READ_PAGE_TIMEOUT', 0.1)

-- Schedule an asynchronous read from the space.
fiber.create(function() box.space.test:get(1) end)

-- In the meantime drop it.
box.space.test:drop()
```

**Comment by avtikhon** [comment]
The current issue uses the local test which is not produced in vinyl suite, which can block the parallel testing for vinyl, anyway local test still shows the fail
