### ISSUE TITLE
Valid method to use Lua from SQL

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#4113]
Need to be able to register a Lua function for using in SQL from SQL.

Like this:

```
SQL> REGISTER FUNCTION foo(a INTEGER) INTEGER
SQL> SELECT foo(34);
```

This is somewhat similar to existing `box.internal.sql_create_function`

**Comment by Korablev77** [comment]
Could you please provide details on this feature? Do we want to use the same mechanism as `box.internal.sql_create_function` does now? If so, do need to keep old interface `box.internal.sql_create_function`? What should new interface look like (syntax, available options, etc)?

**Comment by pgulutzan** [comment]
If this is intended to be an SQL statement, I don't understand why one would want to avoid CREATE FUNCTION function_name (parameter_list) RETURNS type_name ... LANGUAGE LUA ...;
