### ISSUE TITLE
Improve documentation of socket.tcp_server function

### ISSUE THREAD

**Issue by RunsFor** [tarantool/tarantool#4117]
Right now, there is [some](https://www.tarantool.io/en/doc/2.1/reference/reference_lua/socket/#lua-function.socket.tcp_server) information about `handler-function` which may actually be a table, which may contain a function under `handler` key.

But it says nothing about an option to specify [`prepare`](https://github.com/tarantool/tarantool/blob/master/src/lua/socket.lua#L1162) function. Better to have it in docs and have an example, when it may be usefull.

**Comment by kyukhin** [comment]
Moved to appropriate repo.
