### ISSUE TITLE
Extend ALTER to support constraint drop

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#4120]
It should be possible to drop any named constraint
using standard SQL syntax:
```
ALTER TABLE DROP CONSTRAINT <name>
```

**Comment by Korablev77** [comment]
Related (or blocked) to https://github.com/tarantool/tarantool/issues/3503

If constraints shared the same namespace, it would worth nothing to implement DROP CONSTRAINT statement without specifying type of constraint (FK, UNIQUE or CHECK).
