### ISSUE TITLE
test-run: implement SQL driver

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#4123]
Implement SQL mode in test-run when a directory with tests is expected to contain .test.sql files. Each such file is a test just like .lua test, and each statement in the file is wrapped into box.execute automatically. .result/reject files work the same way as with Lua test. This will make working on test suite for SQL much easier (syntax highlighting, auto-alignment, etc).

The driver should support DELIMITER option with \set delimiter  statement, and use the binary protocol to send statements or fragments of SQL back and forth.

Note, that we currently do not support multiple statements in the same binary command, and don't support transactions unless all statements are supplied at once. Perhaps we will need to support anonymous SQL/PSM blocks in the grammar to work this around.

For example, imagine  I wanted to execute INSERT INTO t1 (a) VALUES (1); SELECT * FROM t1 in a single transaction using the driver. I would not be able to do it as long as I'm using IPROTO_EXECUTE, because IPROTO_EXECUTE does not support multiple SQL statements. What I need is:
 begin INSERT INTO t1 (a) VALUES (1); SELECT * FROM t1 end
This is a single SQL statement from - it is called anonymous compound statement. We badly need to support them anyway.

**Comment by Totktonada** [comment]
Variants:

1. Wrap into box.execute().
2. Use `\set language sql` console command.
3. Use IPROTO_EXECUTE requests (via binary port).

2nd variant requires to send the `\set language sql` command again after reconnection.

**Comment by Totktonada** [comment]
Extracted compound statements support into #4316.
