### ISSUE TITLE
sql: disallow scalar columns participate in ORDER BY

### ISSUE THREAD

**Issue by Korablev77** [tarantool/tarantool#4124]
Column of type SCALAR can contain values of different types, which may turn out to be incomparable. For instance, we obviously can't compare `true` of type BOOLEAN and 'abc' of type STRING. Hence, result of sorting involving SCALAR may be unpredictable. Suggestion is to disallow ORDER BY to be used on such columns.

**Comment by kostja** [comment]
For one, you don't know what values you are going to get - they all may be of the same data type.
Second, we already support indexes on scalar data type, if I'm not mistaken, so can use the same semantics.

Mainly, why not come up with a test case showing there is a problem?

**Comment by Korablev77** [comment]
All these branchings at runtime depending on fetched field type are slowing down execution of SQL queries.

Here's is an example:

```
create table t1(id int primary key, a scalar);
insert into t1 values(1, 'abc')
insert into t1 values(2, 1)
insert into t1 values(3, 123.432)
select * from t1 order by a
---
- metadata:
  - name: ID
    type: integer
  - name: A
    type: scalar
  rows:
  - [2, 1]
  - [3, 123.432]
  - [1, 'abc']
```
Order of result rows seems to be confusing IMHO. What is more, now I'm working on introducing boolean type, and with boolean in scalar it looks much worse.

**Comment by pgulutzan** [comment]
Order of result rows perhaps is confusing because the SQL documentation about SCALAR isn't public yet, but the NoSQL documentation established this long ago: "When there is a mix of types, the key order is: booleans, then numbers, then strings." https://www.tarantool.io/en/doc/1.10/book/box/data_model/

**Comment by Korablev77** [comment]
Ok, then I guess I may close this issue.
