### ISSUE TITLE
tap: inconsistent work with box.NULL

### ISSUE THREAD

**Issue by olegrok** [tarantool/tarantool#4125]
Tarantool version: 2.1.1-185-gf583b6c82

```lua
tarantool> t = require('tap').test('123')
TAP version 13
---
...

tarantool> t:is_deeply({a = box.NULL}, {})
ok - nil
---
- true
...

tarantool> t:is_deeply({}, {a = box.NULL})
not ok - nil
  ---
  filename: builtin/box/console.lua
  trace:
  - line: -1
    source: =[C]
    filename: eval
    what: C
    namewhat: global
    name: pcall
    src: '[C]'
  - line: 130
    source: '@builtin/box/console.lua'
    filename: builtin/box/console.lua
    what: Lua
    namewhat: method
    name: eval
    src: builtin/box/console.lua
  - line: 395
    source: '@builtin/box/console.lua'
    filename: builtin/box/console.lua
    what: Lua
    namewhat: upvalue
    name: repl
    src: builtin/box/console.lua
  - line: 440
    source: '@builtin/box/console.lua'
    filename: builtin/box/console.lua
    what: Lua
    namewhat: 
    src: builtin/box/console.lua
  line: 440
  expected: key a
  got: nil
  ...
---
- false
...
```

Expect that both variants return `false`

**Comment by Totktonada** [comment]
Was both true before 28a56114399a346c4749a1926ce849fbb83c3fce.

```
Tarantool 2.0.4-125-g28a561143
type 'help' for interactive help
tarantool> t = require('tap').test('123')
TAP version 13
---
...

tarantool> t:is_deeply({a = box.NULL}, {})
ok - nil
---
- true
...

tarantool> t:is_deeply({}, {a = box.NULL})
ok - nil
---
- true
...
```

**Comment by olegrok** [comment]
```diff
diff --git a/src/lua/tap.lua b/src/lua/tap.lua
index 546d15392..d49fe0a9d 100644
--- a/src/lua/tap.lua
+++ b/src/lua/tap.lua
@@ -91,7 +91,6 @@ local function cmpdeeply(got, expected, extra)
 
     if ffi.istype('bool', got) then got = (got == 1) end
     if ffi.istype('bool', expected) then expected = (expected == 1) end
-    if got == nil and expected == nil then return true end
 
     if type(got) ~= type(expected) then
         extra.got = type(got)
@@ -99,6 +98,8 @@ local function cmpdeeply(got, expected, extra)
         return false
     end
 
+    if got == nil and expected == nil then return true end
+
     if type(got) ~= 'table' then
         extra.got = got
         extra.expected = expected
```
This change partially solves problems. But break msgpack.test.lua (encode/decode for nil)

**Comment by kshcherbatov** [comment]
Not sure about 'Expect that both variants return false'
In my opinion, that must consistently return true in such case, like they did it before.

**Comment by olegrok** [comment]
I think that `{a = box.NULL}` is not equal to `{a = nil}`, because first variant contains more keys than second if we iterate over this table.

There is some difference in serialization/deserialization

```
tarantool> json.encode({a = box.NULL})
---
- '{"a":null}'
...

tarantool> json.encode({a = nil})
---
- '[]'
...

tarantool> json.decode('{"a": null}')
---
- {'a': null}
...
```

So, let's ask @Totktonada @sharonovd @knazarov

**Comment by sharonovd** [comment]
Agree with @olegrok , Nulls are reserved values and are not equal to absent keys (as in {a=nil}, which is equivalent of {})

**Comment by kshcherbatov** [comment]
Unfortunately, test coverage caught correct counter-example:
tap:is_deeply(msgpack.decode(msgpack.encode(t)), t) must be true, right?
But for t = box.NULL it is not so.
Apparently, you should leave true in this case

**Comment by olegrok** [comment]
> tap:is_deeply(msgpack.decode(msgpack.encode(t)), t)

It's a good question. I agree that `test:is(nil, box.NULL)` is true (because box.NULL == nil), but deeply comparison may return false... (but as minimum we should document this behaviour)

**Comment by Totktonada** [comment]
@olegrok @sharonovd Are there any (more or less) real cases, where we need to consider {} and {foo=box.NULL} as non-equal?

**Comment by sharonovd** [comment]
@totktonada Generally when it comes to comparing nested json's (e g http responses), and
`{  result = 'Success' }`
and 
`{ result = 'Success', error = None }`

are different json's.

**Comment by Totktonada** [comment]
It seems that we should consider nil == box.NULL by default, because they are equal in Lua. However we can configure a test object to consider them as non-equal over all :is(), :isnt(), :isnil(), :is_deeply() methods.

@sharonovd Okay for your tasks?

**Comment by olegrok** [comment]
Yes, may be to prevent backward compatibility break, we should do it configurable

**Comment by kshcherbatov** [comment]
I've introduced a new 'strict' flag for tap object:
```
    @TarantoolBot document
    Title: tap test new flag 'strict'
    In some scenarios it is convenient to distinguish box.NULL and
    nil in tap:is(), tap:isnt(), tap:is_deeply() tests.
    For example, {result='Success'} and {result='Success', error=None}
    are different HTTP responses. You may set t.strict = true to
    behave such way.
    Example:
    t = require('tap').test('123')
    t.strict = true
    t:is_deeply({a = box.NULL}, {}) -- false
 ```
