### ISSUE TITLE
travis-ci: box/on_shutdown.test.lua test flaky fails under highload

### ISSUE THREAD

**Issue by avtikhon** [tarantool/tarantool#4134]
Tarantool version:
master

OS version image:
packpack/packpack:debian-stretch

Bug description:
The following failed even after the grep_log was changed to wait_log with 30 secs timeout

[079] --- box/misc.result	Wed Apr 10 15:13:37 2019
[079] +++ box/misc.reject	Wed Apr 10 18:12:13 2019
[079] @@ -1406,7 +1406,6 @@
[079]  ...
[079]  test_run:wait_log('test', 'on_shutdown 5', nil, 30, {noreset=true})
[079]  ---
[079] -- on_shutdown 5
[079]  ...
[079]  -- make sure we exited because of os.exit(), not a signal.
[079]  test_run:wait_log('test', 'signal', nil, 10, {noreset=true})
[079] 

Steps to reproduce:
./test-run.py -j 50 box/misc.test.lua box/misc.test.lua box/misc.test.lua box/misc.test.lua box/misc.test.lua box/misc.test.lua box/misc.test.lua box/misc.test.lua box/misc.test.lua box/misc.test.lua box/misc.test.lua box/misc.test.lua box/misc.test.lua box/misc.test.lua box/misc.test.lua box/misc.test.lua box/misc.test.lua box/misc.test.lua box/misc.test.lua box/misc.test.lua box/misc.test.lua box/misc.test.lua box/misc.test.lua box/misc.test.lua box/misc.test.lua box/misc.test.lua box/misc.test.lua box/misc.test.lua box/misc.test.lua box/misc.test.lua box/misc.test.lua box/misc.test.lua box/misc.test.lua box/misc.test.lua box/misc.test.lua box/misc.test.lua box/misc.test.lua box/misc.test.lua box/misc.test.lua box/misc.test.lua box/misc.test.lua box/misc.test.lua box/misc.test.lua

Optional (but very desirable):
* coredump
* backtrace
* netstat

**Comment by sergepetrenko** [comment]
Doesn't reproduce on my side anymore. (Mac OS X 10.14.5)

./test-run.py -j128 box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown. box/on_shutdown.
...
Statistics:
* pass: 128

**Comment by avtikhon** [comment]
Still fails:
https://travis-ci.org/tarantool/tarantool/jobs/546634475

**Comment by Totktonada** [comment]
Note: The test case is now extracted into box/on_shutdown.test.lua.
