### ISSUE TITLE
Add all the missing _v (sysview) spaces

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#4141]
Please ensure that all _ system spaces have a corresponding _v space.
We have _vfunc, _vindex, _vpriv, _vsequence, _vspace, _vuser.
We do not have _vtrigger, _vconstraint, _vcollation, _vfk_constraint.
This is due to a suggestion from Konstantin Osipov.

**Comment by kyukhin** [comment]
Needed for #2244.

**Comment by kyukhin** [comment]
Won't be fixed. See no reason.
