### ISSUE TITLE
Improve documentation about implicit yields on WAL write

### ISSUE THREAD

**Issue by markiz** [tarantool/tarantool#4144]
https://www.tarantool.io/en/doc/1.10/book/box/atomic/#atomic-implicit-yields

Currently, the documentation says:

> Database operations usually do not yield, but it depends on the engine:
> In memtx, reads or writes do not require I/O and do not yield.

It goes on further to mention that "all data change operations are followed by an automatic commit, which yields", at which point this becomes confusing, even if technically correct.

What actually happened to me is that I assumed since "database operations" do not yield, that means that `update` call wouldn't yield. (which it did)

---
Proposal:
Improve the current wording explaining the separation of database operations and WAL even more explicitly, because WAL autocommit is the default mode of operation.

**Comment by kyukhin** [comment]
Done.
