### ISSUE TITLE
sql: extend VDBE memory cell with field_type member

### ISSUE THREAD

**Issue by Korablev77** [tarantool/tarantool#4148]
During execution of bytecode virtual machine uses its own type system to operate on memory cells. Types of this system can be matched with Tarantool's field types (at least now). But when it comes for NULLs, we can't say exact type of initial value:

```
CREATE TABLE t (id INT PRIMARY KEY, a INT);
INSERT INTO t VALUES (1, 1), (2, NULL);
SELECT typeof(a) FROM t;
---
- metadata:
  - name: typeof(a)
    type: string
  rows:
  - ['integer']
  - ['null']
...
```
Problem of determining initial type of value will become even more complicated when we add user-defined types. So, to improve our type system, we have to keep in memory cell not only type of value (in other words - msgpack format type), but also type of space's field (in case value is fetched from tuple).

**Comment by kostja** [comment]
test case:
it isn't what i expected ...tarantool> insert into t2 values (1,null);
---
- row_count: 1
...

tarantool> select typeof(s2) from t2;
---
- metadata:
  - name: typeof(s2)
    type: string
  rows:
  - ['null']
...

**Comment by pgulutzan** [comment]
I hope that the intent is: (a) for a NULL in a column which is defined as INT, the data type is 'integer'; (b) for NULL outside of a column and therefore not subject to column-definition rules as in "select null;", the data type is 'boolean'; (c) for NULL in a column which is defined as SCALAR, the data type is 'boolean'. Is that outside the scope of this issue?

**Comment by kyukhin** [comment]
Done by 931d58a30b3d17b5fbb72a6073327ed0b1bfece2
