### ISSUE TITLE
Disallowing creation of a view that cannot be used

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#4149]
I have Ubuntu 18.04. I have Tarantool 2.2 pulled from source today.

I execute these SQL statements:
```
CREATE TABLE ts (s1 INT PRIMARY KEY);
INSERT INTO ts VALUES (1);
WITH RECURSIVE w AS (
            SELECT s1 FROM ts
            UNION ALL
            SELECT s1+1 FROM w WHERE s1 < 4)
          SELECT * FROM w;
CREATE VIEW v AS WITH RECURSIVE w AS (
            SELECT s1 FROM ts
            UNION ALL
            SELECT s1+1 FROM w WHERE s1 < 4)
          SELECT * FROM w;
SELECT * FROM v;
```

The `WITH` statement works.
The `CREATE VIEW` statement works.
The `SELECT` statement does not work.

That is fine -- we only say that we support
`CREATE VIEW v AS SELECT ...`
not
`CREATE VIEW v AS WITH ... SELECT ...`
But I am suggesting that
`CREATE VIEW v AS WITH ... SELECT ...`
should cause an error message = bad syntax.

**Comment by romanhabibov** [comment]
@pgulutzan, hi!
Now, it works like:
tarantool> CREATE VIEW v AS WITH RECURSIVE w AS ( SELECT s1 FROM ts UNION ALL SELECT s1+1 FROM w WHERE s1 < 4) SELECT * FROM w;
---
- error: 'Failed to create space ''V'': can''t create view as <WITH>'
...

**Comment by romanhabibov** [comment]
@pgulutzan, hi!
Now, it works like:
```
tarantool> CREATE VIEW v AS WITH RECURSIVE w AS ( SELECT s1 FROM ts UNION ALL SELECT s1+1 FROM w WHERE s1 < 4) SELECT * FROM w;
---
- null
- Space 'W' does not exist
...
```
The point of the ticket is to change the error message, do I understand you correctly?
Do you want something like:
```
tarantool> CREATE VIEW v AS WITH RECURSIVE w AS ( SELECT s1 FROM ts UNION ALL SELECT s1+1 FROM w WHERE s1 < 4) SELECT * FROM w;
---
- error: 'Failed to create space ''V'': can''t create view as <WITH>'
...
```

**Comment by pgulutzan** [comment]
Yes you understand correctly, and yes, I think your suggested fix would be very good.
