### ISSUE TITLE
Wrong output on console select

### ISSUE THREAD

**Issue by 0xIAx** [tarantool/tarantool#4151]
Tarantool version:
official docker tarantool/tarantool:1.10.2

OS version:
Ubuntu server 18.04 

Bug description:

Wrong output from console. When I'm working with golang client all work's fine. Using index returns correct data. But console always returns incorrect index values. 

Steps to reproduce:

Create simple space and tree index on first integer field (type = 'tree', unique = false)

 tt = box.schema.space.create('virtualtimetable', { is_local = false, if_not_exists = true })
    tt:format({
        **{ name = 'stopid', type = 'integer' },**
        { name = 'roteid', type = 'integer' },
        { name = 'time1', type = 'integer' },
        { name = 'time2', type = 'integer' },
        { name = 'endstopid', type = 'integer' },
        { name = 'idVehicle1', type = 'integer' },
        { name = 'idVehicle2', type = 'integer' },
        { name = 'instance_id', type = 'integer' },
        { name = 'cardnum1', type = 'integer' },
        { name = 'cardnum2', type = 'integer' },
        { name = 'expire_time', type = 'integer' }
    })
    tt:create_index('primary', { type = 'hash', unique = true, parts = { { 1, 'integer' }, { 2, 'integer' } } })
    **tt:create_index('stopidex', { type = 'tree', unique = false, parts = { 1, 'integer' } })**
    tt:create_index('vehicleidex', { type = 'tree', unique = false, parts = { 6, 'integer' } })
    tt:create_index('timeidex', { type = 'tree', unique = false, parts = { { 11, 'integer' }} })

Add some data and trying to get some records..
But returns another stopid.. for any select param 

unix/:/var/run/tarantool/tarantool.sock> box.space.virtualtimetable.index.stopidex:select(**864691128455145298**)
---
- - [**864691128455145344**, 864704013357026305, 777, 1692, 864691128455135317, 864691128455135409,
    864691128455135457, 12, 7, 2, 1555085329]
  - [**864691128455145344**, 864704013357028353, 1624, 4752, 864691128455145252, 864691128455135261,
    864691128455135311, 12, 8, 4, 1555085329]
  - [**864691128455145344**, 864704017651995651, 329, 4392, 864691128455145252, 864691128455136369,
    864691128455136345, 12, 3, 2, 1555085329]
  - [864691128455145344, 864704017652002819, 119, 432, 864691128455145844, 864691128455136291,
    0, 12, 27, 28, 1555085329]
  - [864691128455145344, 864704017652008963, 132, 531, 864691128455135727, 0, 864691128455136317,
    12, 16, 17, 1555085329]
  - [864691128455145344, 864704017652017155, 12, 822, 864691128455145688, 0, 864691128455140304,
    12, 1, 2, 1555085329]
  - [864691128455145344, 864704017652046851, 192, 1572, 864691128455138452, 0, 0,
    12, 6, 7, 1555085329]
  - [864691128455145344, 864704056306708480, 162, 625, 864691128455136322, 864691128455138319,
    864691128455138299, 12, 10, 3, 1555085329]
  - [864691128455145344, 864704056306714624, 683, 0, 864691128455135727, 864691128455138448,
    0, 12, 1, 0, 1555085329]
  - [864691128455145344, 864704056306722816, 29, 0, 864691128455136039, 864691128455139258,
    0, 12, 1, 0, 1555085329]
  - [864691128455145344, 864704056306732032, 252, 0, 864691128455145252, 0, 0, 12,
    3, 0, 1555085329]
  - [864691128455145344, 864704056306736128, 419, 4588, 864691128455145938, 864691128455140308,
    864691128455138305, 12, 1, 2, 1555085329]
  - [864691128455145344, 864704056306748296, 2472, 0, 864691128455145844, 864691128455139335,
    0, 12, 1, 0, 1555085329]
  - [864691128455145344, 864704056306752512, 596, 2446, 864691128455138452, 864691128455139337,
    864691128455139263, 12, 4, 2, 1555085329]
  - [864691128455145344, 864704056306755584, 1812, 5191, 864691128455138452, 864691128455138415,
    864691128455138373, 12, 2, 1, 1555085329]
  - [864691128455145344, 864704056306756480, 1076, 0, 864691128455138452, 864691128455138298,
    0, 12, 1, 0, 1555085329]
  - [864691128455145344, 864704064896763895, 4217, 0, 864691128455139842, 864691128455136856,
    0, 12, 1, 0, 1555085329]
...

**Comment by locker** [comment]
Lua interpreter uses floating point numbers for literals, and an IEEE floating point can't represent all integers greater than 2^54 - they will lose precision:
```
tarantool> 864691128455145298
---
- 864691128455145344
...
```
Try using LL/ULL suffix. This will force the interpreter to create a cdata storing int64/uint64 instead:
```
tarantool> 864691128455145298ULL
---
- 864691128455145298
...
```
Tarantool handles those well so it should work for you.

**Comment by 0xIAx** [comment]
Thank you!! Really impressed with your super fast reply! :)
