### ISSUE TITLE
Exit with builtin/box/console.lua:276: variable 'string' is not declared

### ISSUE THREAD

**Issue by olegrok** [tarantool/tarantool#4154]
```lua
➜  Projects tarantool
Tarantool 2.1.1-185-gf583b6c82
type 'help' for interactive help
tarantool> string
---
- find: 'function: builtin#84'
  ljust: 'function: 0x0104536f48'
  len: 'function: 0x01044f7fe8'
  gsub: 'function: builtin#88'
  upper: 'function: builtin#82'
  sub: 'function: builtin#78'
  char: 'function: builtin#77'
  rstrip: 'function: 0x01045372c0'
  match: 'function: builtin#85'
  split: 'function: 0x0104536e90'
  center: 'function: 0x0104536fb8'
  strip: 'function: 0x0104537250'
  endswith: 'function: 0x0104537070'
  rep: 'function: builtin#79'
  hex: 'function: 0x01045370b8'
  lower: 'function: builtin#81'
  fromhex: 'function: 0x01045371d0'
  dump: 'function: builtin#83'
  gmatch: 'function: builtin#87'
  reverse: 'function: builtin#80'
  byte: 'function: builtin#76'
  startswith: 'function: 0x0104536ff0'
  rjust: 'function: 0x0104536f80'
  lstrip: 'function: 0x0104537288'
  format: 'function: builtin#89'
...

tarantool> string = nil
---
...

tarantool> string
builtin/box/console.lua:276: variable 'string' is not declared
➜  Projects 
```

Expect something as:
```lua
➜  Projects tarantool
Tarantool 2.1.1-185-gf583b6c82
type 'help' for interactive help
tarantool> table
---
- maxn: 'function: builtin#90'
  copy: 'function: 0x0109a54c40'
  new: 'function: builtin#94'
  clear: 'function: builtin#95'
  move: 'function: 0x0109a20988'
  foreach: 'function: 0x0109a20540'
  sort: 'function: builtin#93'
  remove: 'function: 0x0109a20830'
  foreachi: 'function: 0x0109a20430'
  deepcopy: 'function: 0x0109a533e0'
  getn: 'function: 0x0109a20618'
  concat: 'function: builtin#92'
  insert: 'function: builtin#91'
...

tarantool> table = nil
---
...

tarantool> table
---
- error: '[string "return table"]:1: variable ''table'' is not declared'
...

tarantool> 
```

**Comment by romanhabibov** [comment]
Seems that we should retain it as is. The point of problem is use of builtin Lua functions like string.find() in the src/box/lua/console.lua. In this case, 'string' has nulled and these functions invoke to nil. Same problem appears when we make, for example, 'loadstring = nil'. We shouldn't disallow to use these names of vars, because 'string = require('string')' is legal.

**Comment by olegrok** [comment]
Won't
```lua
string = table.deepcopy(require('string')) 
```
help us?

It seems as dirty hack, however we will isolate user from such oportunity?

**Comment by Totktonada** [comment]
Consider `loadstring` example above. We can find more like that with different functions and different modules (built-in or external ones). Just use luacheck for your code to protect youself from such mistakes.

I think the issue should be closed as 'won't fix'.

**Comment by Totktonada** [comment]
It is possible to handle this in the way like Oleg suggests:

```diff
diff --git a/src/box/lua/console.lua b/src/box/lua/console.lua
index f922f0320..6d7c5b846 100644
--- a/src/box/lua/console.lua
+++ b/src/box/lua/console.lua
@@ -10,6 +10,16 @@ local urilib = require('uri')
 local yaml = require('yaml')
 local net_box = require('net.box')
 
+-- Prevent using global string functions, because a user can
+-- clobber them.
+local string_find = string.find
+local string_format = string.format
+local string_gmatch = string.gmatch
+local string_match = string.match
+local string_rep = string.rep
+local string_sub = string.sub
+local loadstring = loadstring
+
 local YAML_TERM = '\n...\n'
 local PUSH_TAG_HANDLE = '!push!'
```

And then replace all usages within the module, including colon calls. This will not handle all those places (I'm sure there are other usages of built-in modules within built-in modules), but at least fix this particular problem. We'll not leave from local tarantool REPL with a bad terminal state.

@Gerold103 What do you think about this way to fix? The whole patch is 1368f018194297cadebb55c90d21b9420b6f63ce. I'll send it for review if we'll agree on approach.

**Comment by Gerold103** [comment]
@Totktonada I do not think it should be fixed. `string = nil` is an abnormal behaviour. A user just must not do it. It is on the same level of idiocy as `free(space:select()[1])` - it crashes Tarantool, but it is not worth fixing. It is not even a problem so as to fix it. I propose just close as 'wont fix', and do not complicate `console` code even more.

**Comment by Gerold103** [comment]
On the other hand, final decision is on Kirill. I am ok with the approach, if 'ok' word is even appropriate with that problem, and any manager approves that.

**Comment by Totktonada** [comment]
@Gerold103 Thanks!

@kyukhin Please, decide whether we should do anything here.

**Comment by kyukhin** [comment]
Stop then.
