### ISSUE TITLE
Add GitLab CI to speed up testing

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#4156]
We need to run testing on our machines because free Travis CI plan does not offer us enough resources.

I proposed the initial setup in afe0c0251afcabd05bd5b5a953e4c335b56e03f0 (Totktonada/add-gitlab-ci branch). It enables:

- Release and debug testing on GCC.
- Release and debug testing on clang 8 (a way more fresh then we have in our Travis CI testing).

We need to do the following jobs to use this (hopefully fast) testing as the push criteria:

- Run only on shorth-term branches.
- Setup Linux machines and ensure the testing is fast enough.
- Setup OS X machine (ask @knazarov re cloud providers) and jobs (release and debug).

@kyukhin Please, review the plan.

**Comment by kyukhin** [comment]
OK. This sounds like a good start.

**Comment by Totktonada** [comment]
Now I understood the problem better: Travis-CI [offers][1] five concurrent jobs per whole GitHub organization and we should pay attention to duration of our builds to don't throttle modules / connectors builds.

We need to elaborate they way we distribute CI / CD tasks to fit all our needs. I propose the following distribution:

* Use Travis-CI mature infrastructure for critical jobs (basic testing and build+deploy goals).
* Use Travis-CI for basic testing of pull requests from forks.
* Use our fast infrastucture for basic testing of our own short-term branches.
* Use our infrastucture for extra testing goals on long-term (release) branches: static build (#3668), LTO, sanitizers and so on (don't flood Travis-CI).
* Leave short-term branches testing in Travis-CI to backup our infrastructure for some months; then maybe disable.
* Leave basic testing of long-term branches in our infrastructure to test the infrastructure itself, again, for some months.

After some time we can reduce duplication:

* Disable our short-term branches testing in Travis-CI (leave only PRs and CI / CD for long-term branches).
* Disable basic testing of long-term branches in GitLab CI (leave only short-term branches and 'extra' jobs in long-term ones: static build, LTO, ...).

The former will decrease pressure on Travis-CI on the order of magnitude (we have a lot of pushes to short-term branches per day). The latter will decrease pressure on our GitLab CI powered infrastucture for some percents.

Maybe we should run short-term branches testing with higher priority then long-term branches testing or on separate machines.

NB: Plot a testing matrix.

[1]: https://stackoverflow.com/a/34809448

**Comment by avtikhon** [comment]
#4215 Clang and LTO fixes
