### ISSUE TITLE
test: switch on is_parallel flag for vinyl suite

### ISSUE THREAD

**Issue by avtikhon** [tarantool/tarantool#4158]
Tarantool version:
All

OS version:
All

Bug description:
Need to switch on is_parallel flag for vinyl suite to be able to run subtests in parallel using -j"<num>" flag for test_run

Steps to reproduce:

Optional (but very desirable):
* coredump
* backtrace
* netstat

**Comment by Totktonada** [comment]
Please, ensure all related issues are resolved. I found these ones:

https://github.com/tarantool/tarantool/issues/4109
https://github.com/tarantool/tarantool/issues/4152
https://github.com/tarantool/tarantool/issues/4058
https://github.com/tarantool/tarantool/issues/3865
https://github.com/tarantool/tarantool/issues/3728

**Comment by avtikhon** [comment]
#4109 - closed
#4152 - closed
#4058 - opened WIP
#3865 - opened but not reproduced
#3728 - opened need to check 1.10 only

**Comment by Totktonada** [comment]
Alexander says vinyl/ suite passes most of the time (47 of 50 runs), so we can consider this issue as not blocked.
