### ISSUE TITLE
sql: can't recover if check constraint involves function

### ISSUE THREAD

**Issue by Korablev77** [tarantool/tarantool#4176]
```
box.cfg{}
function myfunc(x)
      return x < 10
end
box.internal.sql_create_function("myfunc", "INT", myfunc)
box.execute("CREATE TABLE t6(a  INT CHECK (myfunc(a)) primary key);");
os.exit()
./src/tarantool
box.cfg{}
2019-04-23 21:21:12.176 [77940] main/102/interactive box.cc:303 E> error applying row: {type: 'INSERT', replica_id: 1, lsn: 14, space_id: 357, index_id: 0, tuple: ["CK_CONSTRAINT_1_T6", 514, "myfunc(a)"]}
2019-04-23 21:21:12.177 [77940] main/102/interactive ck_constraint.c:233 E> ER_CREATE_CK_CONSTRAINT: Failed to create check constraint 'CK_CONSTRAINT_1_T6': Function 'MYFUNC' does not exist
2019-04-23 21:21:12.177 [77940] main/102/interactive F> can't initialize storage: Failed to create check constraint 'CK_CONSTRAINT_1_T6': Function 'MYFUNC' does not exist
```
This happens (obviously) due to the fact that functions are not persistent.
Mb it is wort to prohibit non-built-in function participate in check constraints, or raise warning concerning the fact that such check constraints won't be restored after instance reload.

**Comment by kostja** [comment]
Why run check constraints at all during recovery? They should be disbled in recovery and replication mode.

**Comment by kshcherbatov** [comment]
May be solved with #4182

**Comment by kshcherbatov** [comment]
Also we may disable space triggers on initialization (reworked in #3691 checks)

**Comment by kyukhin** [comment]
So, after we'll disable the checks during initialization and implement persistence for Lua functions, the issue should be solved. Let's keep it open until the case provided pass.

**Comment by kshcherbatov** [comment]
```
box.cfg{}
function myfunc(x)
      return x < 10
end
box.schema.func.create('MYFUNC', {param_list = {'integer'}, returns = 'integer', is_deterministic = true})
box.execute("CREATE TABLE t6(a  INT CHECK (myfunc(a)) primary key);");
os.exit()
```
....
```
box.cfg{}
```

**Comment by Korablev77** [comment]
@kshcherbatov 
Ok, but now we don't declare this function as persistent (i.e. skip `box.schema.func.create`) and will get the same error. My suggestion is to disallow non-persistent functions participate in check constraints.

**Comment by kshcherbatov** [comment]
Ugum
