### ISSUE TITLE
Result code is sometimes 0 when there is an error

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#4177]
I have tarantool server 2.1 pulled from source today.
I have tarantool-c.
I have access as guest to a Tarantool server on localhost:3302.

I compile and execute this program, with
gcc -o example example.c -ltarantool

#include <stdio.h>
#include <stdlib.h>

#include <tarantool/tarantool.h>
#include <tarantool/tnt_net.h>

void main() {
   struct tnt_stream *tnt = tnt_net(NULL);
   tnt_set(tnt, TNT_OPT_URI, "localhost:3302");
   if (tnt_connect(tnt) < 0) {
       printf("Connection refused\n");
       exit(-1);
   }
   struct tnt_reply reply;
   struct tnt_stream *empty = tnt_object(NULL);
   tnt_object_add_array(empty, 0);

   tnt_eval(tnt, "box.execute('select 5 order by 1 limit 0001;')", 46, empty);
   tnt_flush(tnt);
   tnt_reply_init(&reply);
   tnt->read_reply(tnt, &reply);
   printf("Reply #1 ...\n");
   printf("  reply.code=%ld\n", reply.code);
   printf("  reply.data size=%ld\n", reply.data_end - reply.data);
   printf("  reply.error size=%ld\n", reply.error_end - reply.error);
   printf("  reply.metadata size=%ld\n", reply.metadata_end - reply.metadata);

   tnt_eval(tnt, "box.execute('select 5 order by 1 limit xxxx;')", 46, empty);
   tnt_flush(tnt);
   tnt_reply_init(&reply);
   tnt->read_reply(tnt, &reply);
   printf("Reply #2 ...\n");
   printf("  reply.code=%ld\n", reply.code);
   printf("  reply.data size=%ld\n", reply.data_end - reply.data);
   printf("  reply.error size=%ld\n", reply.error_end - reply.error);
   printf("  reply.metadata size=%ld\n", reply.metadata_end - reply.metadata);

   tnt_eval(tnt, "box.execute('select 5 order by 1 limit null;')", 46, empty);
   tnt_flush(tnt);
   tnt_reply_init(&reply);
   tnt->read_reply(tnt, &reply);
   printf("Reply #3 ...\n");
   printf("  reply.code=%ld\n", reply.code);
   printf("  reply.data size=%ld\n", reply.data_end - reply.data);
   printf("  reply.error size=%ld\n", reply.error_end - reply.error);
   printf("  reply.metadata size=%ld\n", reply.metadata_end - reply.metadata);
}

The connect to localhost:3302 succeeds. The result looks like this:

pgulutzan@pgulutzan-VirtualBox:~/tarantool_sandbox$ ./example
Reply #1 ...
  reply.code=0
  reply.data size=5
  reply.error size=0
  reply.metadata size=0
Reply #2 ...
  reply.code=176
  reply.data size=0
  reply.error size=28
  reply.metadata size=0
Reply #3 ...
  reply.code=0
  reply.data size=0
  reply.error size=54
  reply.metadata size=0

For Reply #1, which is for a good statement, reply.code is 0 and reply.error size is 0. Fine.
For Reply #2, which is for a bad statement, reply.code != 0 and reply.error size != 0, Fine.
For Reply #3, which is for a bad statement, reply.code == 0 and reply.error size != 0. What?
LIMIT BY xxxx and LIMIT BY null are both errors, I depend on reply.code to see that.

I do not believe the bug is in tarantool-c, because a similar
(though more complex) program used to work, with box.sql.execute.
Tarantool-c has not changed in several months, and
box.sql.execute has changed (replaced with box.execute),
so I believe the problem is in tarantool server.

**Comment by ImeevMA** [comment]
I think that this problem will be closed by one of the patches of issue #4074.

**Comment by pgulutzan** [comment]
I don't think so. Issue#4074 is closed now, but I still have a program that says reply.code == 0. This time I am seeing it for a failure of a check constraint.

**Comment by ImeevMA** [comment]
This will be fixed in issue #4183. Somehow, the patches for #4074 and #3691 overlap, leading to this error. @pgulutzan could you run these tests on [this](https://github.com/tarantool/tarantool/tree/imeevma/gh-4183-clean-up-when-constraint-creation-failed) branch?

**Comment by pgulutzan** [comment]
I used branch imeevma/gh-4183-clean-up-when-constraint-creation-failed.
For the initial test described above, I see that now reply.code != 0.
For the newer test (which also failed) of check constraint, I see that now reply.code != 0.
The bug seems to be fixed.
Therefore I believe that you can close this when the branch becomes master.
Thanks.

Please tell me whether you agree with these statements:
"If error_size > 0 then code must be != 0."
"If code != 0 then error_size must be > 0."

Also please let me know if someone plans to implement
warnings soon, because I am guessing that a warning
might cause a code number > 0 which does not mean error.

**Comment by ImeevMA** [comment]
@pgulutzan Sorry for such late reply. For the first question I cannot say fr sure, since if code == Tarantool error code, than 0 is error code of "ER_UNKNOWN". It can be seen here:

**Comment by pgulutzan** [comment]
Thanks for the reply. It seems bad that we cannot be sure about these questions, but if that's the story then programmers will just have to learn to be careful with their coding accordingly. As for warnings,, I read that there will be a "diagnostics" stack   and it would be a good opportunity to allow for a variety of response conditions, but if not, okay.
