### ISSUE TITLE
fio.copyfile() works not properly

### ISSUE THREAD

**Issue by artur-barsegyan** [tarantool/tarantool#4181]
Tarantool version: 1.10.2-175-gb3656d459
OS version: macOS Mojave 10.14.1 
Bug description: `fio.copyfile()` does not fit to `cp` command behavior - `copyfile()` doesn't overwrite dst file

Steps to reproduce:
```bash
echo "fio = require ('fio'); fio.copyfile('1.txt', '2.txt');" > script.lua

echo 111 > 1.txt
echo 222 > 2.txt

tarantool script.lua

echo 222 >> 2.txt

tarantool script.lua
cat 2.txt
```

**Comment by cyrillos** [comment]
This won't be a problem to add a truncation flag while opening a destination file. But the main problem is that -- we might break backward compatibility. Is there are guarantee that none of customers rely on the current behavior?

**Comment by artur-barsegyan** [comment]
> This won't be a problem to add a truncation flag while opening a destination file. But the main problem is that -- we might break backward compatibility. Is there a guarantee that none of customers rely on the current behavior?

we just can add a option with default value

**Comment by cyrillos** [comment]
sounds ok to me

**Comment by cyrillos** [comment]
I'll take a look. Still the fix might conflict with rework of copyfile function I'm working on. Thus I'll address this particular issue once we resolve the current copyfile rework, ie a bit later.

**Comment by artur-barsegyan** [comment]
@cyrillos 

> ...customers rely on the current behavior
but actually current behavior isn't repeatable. I think we should fix that

**Comment by cyrillos** [comment]
I've sent a patch to gather comments.
