### ISSUE TITLE
Excess error message

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#4187]
I have Ubuntu 18.04. I have Tarantool 2.2, pulled from source today.

I execute these SQL statements:
CREATE TABLE tboolean (s1 BOOLEAN PRIMARY KEY);
INSERT INTO tboolean VALUES (TRUE);
SELECT * FROM tboolean WHERE s1 = x'44';

I see:

tarantool> SELECT * FROM tboolean WHERE s1 = x'44';
2019-04-26 16:50:45.189 [9236] main/102/interactive key_def.h:488 E> ER_KEY_PART_TYPE: Supplied key type of part 0 does not match index part type: expected boolean
---
- error: 'Failed to execute SQL statement: Supplied key type of part 0 does not match
    index part type: expected boolean'
...

Thus I am receiving an extra message in addition to the regular SQL error.

**Comment by Korablev77** [comment]
I guess problem lies not only in duplicated error message, but also in a bit confusing error itself. I've found similar case, but error shouldn't be raised since implicit conversion between integer and float is allowed.
```
CREATE TABLE t1(id INT PRIMARY KEY, a INT UNIQUE);
INSERT INTO t1 VALUES (1, 1);
SELECT a FROM t1 WHERE a IN (1.1, 2.1);

2019-05-01 16:48:17.847 [13161] main/102/interactive key_def.h:488 E> ER_KEY_PART_TYPE: Supplied key type of part 0 does not match index part type: expected integer
---
- error: 'Failed to execute SQL statement: Supplied key type of part 0 does not match
    index part type: expected integer'
...
```
