### ISSUE TITLE
Update error with SQL

### ISSUE THREAD

**Issue by dimtos** [tarantool/tarantool#4189]
Tarantool version: 2.1.2-9-g72394afda

OS version: Linux-x86_64-RelWithDebInfo

Bug description: update in space `user` finishing with error `Type mismatch: can not convert 1 to boolean`. In other names of spaces it's ok.

Steps to reproduce: `box.execute([[update "user" set "login" = 'mylogin' where "id" = 20]])`

Optional (but very desirable): `box.space.user:format()`
`- [{'type': 'unsigned', 'name': 'id', 'title': 'ID', 'is_nullable': false}, {'belongs_to': 'user',
    'title': 'Владелец', 'type': 'unsigned', 'name': '_owner', 'is_nullable': false},
  {'type': 'boolean', 'name': 'enabled', 'is_nullable': false}, {'type': 'string',
    'name': 'email', 'is_nullable': false}, {'type': 'string', 'name': 'login', 'is_nullable': false},
  {'type': 'string', 'name': 'password', 'is_nullable': false}, {'type': 'string',
    'name': 'first_name', 'is_nullable': false}, {'type': 'string', 'name': 'last_name',
    'is_nullable': false}, {'type': 'string', 'name': 'middle_name', 'is_nullable': true},
  {'type': 'array', 'name': '_zone', 'is_nullable': true}, {'type': 'array', 'name': '_loc',
    'is_nullable': false}, {'type': 'unsigned', 'name': 'idvzv', 'title': 'idvzv',
    'is_nullable': true}, {'belongs_to': 'department', 'title': 'Отдел', 'type': 'unsigned',
    'name': 'department', 'is_nullable': true}]`

**Comment by kyukhin** [comment]
Could you pls paste create statement for space `user`?

**Comment by dimtos** [comment]
local s = box.schema.space.create('user')
local seq = box.schema.sequence.create('user')
s:create_index( 'id', { sequence = seq.name } )
s:format(...here fields description...)

**Comment by dimtos** [comment]
If I understand correctly, the update method converts the current value of the boolean field `enabled` to 1 or 0 and tries to save with this value. This causes an obvious error, since this field is boolean.

**Comment by dimtos** [comment]
So, the name of the space does not matter, as I mistakenly assumed.

**Comment by ImeevMA** [comment]
I think it could be reproduced this way:
```
box.cfg{}
format = {}
format[1] = {type = 'boolean', name = 'b'}
format[2] = {type = 'array', name = 'a'}
format[3] = {type = 'integer', name = 'i'}
s = box.schema.space.create('t', {format=format})
s:create_index('ii')
s:insert({true, {1, 2}, 1})
box.execute('update "t" set "i" = 10 where "i" = 1')
```

The error looks a little different, but we can say that this is the same error from the trace:
```
tarantool> box.execute('update "t" set "i" = 10 where "i" = 1')
---
- error: !!binary VHlwZSBtaXNtYXRjaDogY2FuIG5vdCBjb252ZXJ0IJIBAiB0byBhcnJheQ==
...

tarantool> box.error.last().trace
---
- - file: /home/mimeev/Work/dev/src/box/sql/vdbe.c
    line: 2667
...
```
Version:
```
tarantool> box.info.version
---
- 2.2.0-483-g8c84932
...
```

The bottom line is that one of the fields is of type "array".
