### ISSUE TITLE
Introduce VARBINARY field type

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#4201]
This type will be very useful for SQL type system, so let's introduce it to tuple format.
It should be stored as `mp_bin` in msgpack.

**Comment by pgulutzan** [comment]
I suggest that the data type name could be VARBINARY not BLOB.
(1) VARBINARY is a bit closer to the MsgPack name MP_BIN.
(2) L in BLOB stands for Large but it doesn't  have to be large.
(3) Perhaps BLOB is SQLite legacy, that no longer matters.
(4) Some folks will have the idea that LOBs are not stored in the main record.
In SQL the standard requirement is VARBINARY(max-length) but perhaps
max-length can be ignored, as it is for VARCHAR.
I do not mean that VARBINARY should be an alias for BLOB.

**Comment by pgulutzan** [comment]
I hope these minor SQL issues won't be forgotten when adding the rest of SQL support for VARBINARY:
that trim(binary-column) trims x'20' not x'00'.
that x'' is treated as a 'string' data type,
that blob not varbinary is a reserved word,
that typeof(binary-column) says 'scalar'.
