### ISSUE TITLE
Introduce VARBINARY type in SQL frontend

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#4206]
After #4201 is implemented, it'll be possible to introduce native VARBINARY type
in SQL frontend.

**Comment by pgulutzan** [comment]
I hope these minor SQL issues won't be forgotten when adding the rest of SQL support for VARBINARY:

SELECT HEX(TRIM(X'004420')) /*trims the wrong bytes */;
CREATE TABLE VARBINARY (s1 INT PRIMARY KEY) /* not reserved word */;
SELECT TYPEOF(X'') /* returns 'scalar' */;
SELECT UPPER(X'65') /* implicit cast */;

**Comment by Korablev77** [comment]
@pgulutzan @kostja
Should we allow "BLOB" synonym of "VARBINARY" in SQL? I'd rather not do so, but asking just in case.

**Comment by pgulutzan** [comment]
I believe that it should not be a synonym because someday maybe support will be added for a binary large object which is only referenced in the tuple, not stored. But it is okay that BLOB is a reserved word.
