### ISSUE TITLE
luacheck: add .luacheckrc config to the project

### ISSUE THREAD

**Issue by RunsFor** [tarantool/tarantool#4208]
l ran luacheck against latest version of tarantool and got lots of warnings.

```bash
$ luacheck -r src | tail -1
Total: 882 warnings / 0 errors in 40 files
```

I believe it would be useful to define `.luacheckrc`, so the lua code will be consistent throughout the project and more friendly for newcomers.

**Comment by ligurio** [comment]
Duplicate of #4681
