### ISSUE TITLE
Remove yields from Vinyl DDL on commit triggers

### ISSUE THREAD

**Issue by locker** [tarantool/tarantool#4218]
Vinyl DDL on commit triggers may yield due to vylog writes. We need to eliminate that in order to implement transactional DDL (#4083) and parallel applier (#1254).

**Comment by kostja** [comment]
I think we agreed to begin with low hanging fruit in transactional DDL. Please do not re-focus.

**Comment by locker** [comment]
> I think we agreed to begin with low hanging fruit in transactional DDL. Please do not re-focus.

We've agreed to allow non-yielding DDL in a transaction so that one could perform lightweight DDL operations atomically, e.g. creation of a space and indexes for it. The problem is creation of an index even for an empty space requires yield in Vinyl. We need to eliminate those, especially counting that that's fairly easy to do.

> I don't see how this is necessary for parallel applier either.

Please ask @GeorgyKirichenko.

**Comment by kostja** [comment]
From priority POV I'd say a general-purpose alter-via-rebuild and online index create are more necessary than this task. As to ask @GeorgyKirichenko, could you please provide an explanation in the ticket instead.

**Comment by locker** [comment]
> From priority POV I'd say a general-purpose alter-via-rebuild and online index create are more necessary than this task.

We already have alter-via-rebuild. Regarding online index creation - do you mean memtx (#3976)? Yeah, it's a pretty important task, too. But it's not even assigned to me. This issue is primarily about allowing DDL operations that don't entail yields to be executed in transactions (#4083). E.g. making `space.create_index` transactional or allowing to create a space and its indexes transactionally. I thought we agreed that this should be done, too. To achieve that, we need to make vylog non-yielding.

> As to ask @GeorgyKirichenko, could you please provide an explanation in the ticket instead.

I asked him to elaborate.

**Comment by GeorgyKirichenko** [comment]
This is not about DDL but about on_commit triggers. If we want to support asynchronous transactions then we need to have an asynchronously called complection for such transaction. The best way to do this is to fire on_done (commit/rollback) triggers in wal schedule function which does not allow yields.

Additionaly the whole story with yielding while on_commit does not look consistent and safe.
