### ISSUE TITLE
Segmentation fault with crypto

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#4223]
I have Ubuntu 18.04.
I have Tarantool 1.10, pulled from source today.
I execute these requests:

box.cfg{}
crypto=require('crypto')
_16byte_iv=  '1234567890123456'
_24byte_pass='123456789012345678901234'
c = crypto.cipher.aes192.cbc.encrypt.new(_24byte_pass,_16byte_iv)
c:init()
print(c:result())

Result = segmentation fault

This does not occur with Tarantool 2.x.
There might be a slight similarity with issue#1383 (closed).

**Comment by Gerold103** [comment]
https://github.com/tarantool/tarantool/commit/263335802cc6190eb5415d3e05717b5c39b36f44
