### ISSUE TITLE
Expose effective user of a current session via iproto

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#4226]
We need to read this value w/o rights to do call / eval from a connector to support the standard property `ClientUser` in JDBC.

See https://github.com/tarantool/tarantool-java/issues/74 for the discussion.

It is more or less connected with #4205.

**Comment by kostja** [comment]
The request doesn't make sense. There is no effective user of the current session, the user can change any time, since the protocol is asynchronous.

**Comment by Totktonada** [comment]
Okay, we're free to skip this client info property and don't implement it: there are no properties required by the JDBC standard.
