### ISSUE TITLE
An ability to disable CK constraints

### ISSUE THREAD

**Issue by kshcherbatov** [tarantool/tarantool#4244]
It may be useful to disable CK constraints in some scenarios. E.g. on Tarantool start.

**Comment by pgulutzan** [comment]
According to issue#3696 the removal of pragma ignore_check_constraints was deliberate.

**Comment by kshcherbatov** [comment]
According to #3696, it shouldn't be implemented

**Comment by kostja** [comment]
#3696 was a temporary move. Without being able to disable check constraints you can't quickly load large partial dumps. This is a must-have feature - it's only a question of which release it belongs to.
