### ISSUE TITLE
Remove exceptions from C triggers

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#4247]
`lbox_trigger_run`, `vy_deferred_delete_on_replace`, and CHECKs are triggers. Triggers are functions returning void, and run in a cycle in `trigger_run` function inside `try catch`. Because of that the only way of returning an error from a trigger was to throw an exception. But exceptions in C are not ok. They work, but pad out frames having GCC option `-fexceptions` set.
https://gcc.gnu.org/onlinedocs/gcc/Code-Gen-Options.html

**Comment by PersDep** [comment]
https://github.com/tarantool/tarantool/tree/i.kosarev/gh-4247-remove-exceptions-from-triggers

**Comment by PersDep** [comment]
---------------------------------------------------------------------------------------------------------------------------------
