### ISSUE TITLE
Deferred DELETE isn't produced on transaction commit

### ISSUE THREAD

**Issue by locker** [tarantool/tarantool#4248]
**Tarantool version:**

Reproduced using 2.2.0-343-gd07e3ac2. Both 2.1 and 1.10 are affected.

**Bug description:**

Under certain conditions a deferred DELETE statement isn't generated when a transaction is committed. This may result in garbage statements piling up in secondary index runs.

**Steps to reproduce:**

Run the following script in an empty directory.

```Lua
box.cfg{}

s = box.schema.space.create('test', {engine = 'vinyl'})
pk = s:create_index('pk')
sk = s:create_index('sk', {parts = {2, 'unsigned'}})

s:insert{1, 1}

box.begin()
s:replace{1, 2}
s:update(1, {{'=', 2, 3}})
box.commit()

box.snapshot()
os.exit()
```

Now take a look at the written run files:

```
$ tarantoolctl cat */*/*.run
Processing file '512/0/00000000000000000006.run'
---
HEADER:
  lsn: 7
  type: INSERT
BODY:
  tuple: [1, 3]
---
HEADER:
  type: ROWINDEX
BODY:
  row_index: "\0\0\0\0"
...

Processing file '512/1/00000000000000000004.run'
---
HEADER:
  lsn: 5
  type: INSERT
BODY:
  tuple: [1, 1]
---
HEADER:
  lsn: 7
  type: INSERT
BODY:
  tuple: [3, 1]
---
HEADER:
  type: ROWINDEX
BODY:
  row_index: "\0\0\0\0\0\0\0\n"
...
```

Note statement `INSERT{1,1}` in the secondary index run. It isn't present in the primary index hence can't be purged.

**Comment by Korablev77** [comment]
Fix was pushed to master, but forgotten to be pushed to 1.10.

**Comment by kostja** [comment]
Please cherry-pick?

**Comment by Korablev77** [comment]
@kostja already done:https://github.com/tarantool/tarantool/commit/9fdeccbce6752d68b8e46c452e249f1bfb1a687a
