### ISSUE TITLE
SWIM: expose triggers on member change

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#4250]
SWIM as a monitoring module is hard to use without an ability to subscribe on events. An event is a change of a member status, incarnation, payload, URI. An appearance of a new member, drop of a dead one. Possible API, which is just a duplicate of any trigger function:
```Lua
--
-- Subscribe on SWIM events. An event is a change of any attribute
-- of any member, a new member appearance, an existing member
-- drop.
-- @param new_function A function to add to the trigger
--        list.
-- @param old_function Optional argument, by which an existing
--        trigger can be dropped.
-- @return A list of triggers when both args are nil. A new trigger,
--         when @a old_trigger is nil. An old trigger otherwise.
--
swim:subscribe(new_function[, old_function])
```

Trigger function will take 3 arguments: SWIM object, updated member, happened events. The function is allowed to yield. Happened events is an object that can be checked for a concrete event like 'drop', 'new', 'update of anything', 'URI update', 'payload update', 'status update'. An example:
```Lua
local function swim_on_update(s, member, events)
    if events:is_drop() then
        ...
    end
    if events:is_new() then
        ...
    end
    if events:is_update() then
        if events:is_new_uri() then
            ...
        end
        if events:is_new_payload() then
            ...
        end
        if events:is_new_status() then
            ...
        end
    end
end

s = swim.new(...)
s:subscribe(swim_on_update)
```

**Comment by kostja** [comment]
Is it not better to have different triggers for different events?

**Comment by Gerold103** [comment]
It does not seem easier to implement. Also it makes impossible to catch multiple events at once.
