### ISSUE TITLE
box-tap/key_def.test.lua flaky fails

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#4252]
> builtin/fun.lua:958: attempt to call local 'gen_x' (a nil value)

https://travis-ci.org/tarantool/tarantool/jobs/535024408#L3750

I'm able to reproduce it with the following command:

```sh
TEST_RUN_TESTS="$(yes box-tap/key_def.test.lua | head -n 1000)" make test
```

**Comment by Totktonada** [comment]
It reproduces with good probability after the following patch:

```diff
diff --git a/test/box-tap/key_def.test.lua b/test/box-tap/key_def.test.lua
index 4b468a696..2c1e3afda 100755
--- a/test/box-tap/key_def.test.lua
+++ b/test/box-tap/key_def.test.lua
@@ -440,9 +440,13 @@ test:test('merge()', function(test)
     test:is_deeply(key_def_ab:extract_key(tuple_a):totable(), {1, 1, 22},
         'case 1: verify with :extract_key()')
 
-    local key_def_ba = key_def_b:merge(key_def_a)
-    local exp_parts = fun.iter(key_def_b:totable())
-        :chain(fun.iter(key_def_a:totable())):totable()
+    local key_def_ba
+    local exp_parts
+    for i = 1, 100000 do
+        key_def_ba = key_def_b:merge(key_def_a)
+        exp_parts = fun.iter(key_def_b:totable())
+            :chain(fun.iter(key_def_a:totable())):totable()
+    end
     test:is_deeply(key_def_ba:totable(), exp_parts,
         'case 2: verify with :totable()')
     test:is_deeply(key_def_ba:extract_key(tuple_a):totable(), {1, 22, 1},
```

But never reproduces when `jit.off()` is added somewhere at top of the file. So looks like a JIT problem.

**Comment by Totktonada** [comment]
@sergos Agreed to look into this issue.

**Comment by printercu** [comment]
Here is reproducer:

```lua
local fun = require('fun')

local function concat(...)
    return fun.chain(...):totable()
end

local function x()
    for _ = 1, 10000 do
        concat({'a', 'b', 'c'}, {'q', 'w', 'e'})
    end
end

xpcall(function()
    for _ = 1, 100 do
        x()
    end
end, function(err)
    print(debug.traceback(tostring(err)))
    os.exit(1)
end)
```

Loops are not necessary. Sometimes it failed with single `concat` after function definition. 

```
$ tarantool test.lua
builtin/fun.lua:958: attempt to call local 'gen_x' (a nil value)
stack traceback:
  test.lua:18: in function 'gen_x'
  builtin/fun.lua:958: in function 'gen_x'
  builtin/fun.lua:778: in function 'concat'
  test.lua:9: in function 'x'
  test.lua:15: in function <test.lua:13>
  [C]: in function 'xpcall'
  test.lua:13: in main chunk
```

Fails for me at
Tarantool 2.3.0-83-g165f8ee6f
Target: Darwin-x86_64-Debug

Tarantool 1.10.2-1-ge0017ad
Target: Darwin-x86_64-Release

**Comment by avtikhon** [comment]
The issue easy reproduced with the following updated script from above:
`a=0 ; while ../src/tarantool 4252.test.lua ; do a=$(($a+1)) ; echo -ne " $a"\\r ; done`
4252.test:
`local fun = require('fun')

local function concat(...)
        return fun.chain(...):totable()
end

local function x()
        concat({'a', 'b', 'c'}, {'q', 'w', 'e'})
end

xpcall(function()
        for _ = 1, 8 do
                x()
        end
        end, function(err)
        print(debug.traceback(tostring(err)))
        os.exit(1)
end)
`

**Comment by printercu** [comment]
Does it solve only flaky test? Do we need separate ticket for https://github.com/tarantool/tarantool/issues/4252#issuecomment-528334600 ?

**Comment by igormunkin** [comment]
@printercu, yes, we've already discussed it with @Totktonada and I'll create a more precise ticket in a while as it has been mentioned [here](https://lists.tarantool.org/pipermail/tarantool-patches/2020-June/017837.html).
