### ISSUE TITLE
http_client.test time out

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#4254]
http_client.test on the latest master times out in test_errors(). Reason unknown, in any case the test should work when internet connectivity is bad (it is not) or outside Russia (is the case).
Disabling until further investigation.

**Comment by kyukhin** [comment]
@avtikhon could you please try to reproduce it?

**Comment by Totktonada** [comment]
@kostja Can you post `curl --version` output? I guess that the issue can depend on whether libcurl uses asynchronous DNS resolving.

**Comment by Totktonada** [comment]
I don't know a way to emulate dns resolving error locally. I think it worth to remove the test case.

**Comment by kostja** [comment]
curl 7.64.0 (x86_64-pc-linux-gnu) libcurl/7.64.0 OpenSSL/1.1.1b zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh/0.8.6/openssl/zlib nghttp2/1.36.0 librtmp/2.3
Release-Date: 2019-02-06
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL
