### ISSUE TITLE
frommap provides errors in different ways

### ISSUE THREAD

**Issue by printercu** [tarantool/tarantool#4262]
Tarantool version:
1.10.3-19

OS version:
macos

Bug description:
When frommap fails it either throws error or returns `nil, 'error description'`.

Steps to reproduce:
```
tarantool> box.schema.space.create('test', {format = {{'a', 'string'}}})
tarantool> box.space.test:frommap({b = 1})
---
- null
- Unknown field 'b'
...

tarantool> box.space.test:frommap({a = 1})
---
- error: Tuple field 1 type does not match one required by operation: expected string
```

**Comment by locker** [comment]
You forgot braces so the format is treated as type-less, having two fields named 'a' and 'string':

```
tarantool> s = box.schema.space.create('test', {format = {'a', 'string'}})
---
...

tarantool> s:format()
---
- [{'name': 'a', 'type': 'any'}, {'name': 'string', 'type': 'any'}]
...
```

Try this:

```
tarantool> s = box.schema.space.create('test', {format = {{'a', 'string'}}})
---
...

tarantool> s:format()
---
- [{'name': 'a', 'type': 'string'}]
...

tarantool> s:frommap({a = 'test'})
---
- ['test']
...
```

**Comment by printercu** [comment]
Yep, sorry. Updated original comment with new error message: `Tuple field 1 type does not match one required by operation: expected string`.

Problem is not in getting it work. Errors in examples are made intentionally. Problem is that it handles failure in different way: `error(message)` and `return nil, message`.

Because of this it's required to use assert here `space:insert(assert(space:frommap(data)))`. Without assert it gives error `Tuple/Key must be MsgPack array`, with assert - `Unknown field 'b'`.

**Comment by opomuc** [comment]
Please make this ASAP!

**Comment by opomuc** [comment]
Also, I think backport to 1.10 is required

**Comment by RunsFor** [comment]
Moreover, it has different behaviour with option `table` on/off:

```
tarantool> s = box.schema.create_space('test', {format = {{name = 'a', type = 'array'}}})
---
...

tarantool> s:frommap({a = 'wrong type and nothing happen'})
---
- error: 'Tuple field 1 type does not match one required by operation: expected array'
...

tarantool> s:frommap({a = 'wrong type'}, {table = true})
---
- - wrong type and nothing happen
...
```
