### ISSUE TITLE
DDL for temporary and local spaces should not be replicated

### ISSUE THREAD

**Issue by R-omk** [tarantool/tarantool#4263]
Tarantool version:
`2.2.0-343-gd07e3ac2f`

When I perform truncate on  _temporary_ (and _is_local_) spaces, it is performed on all replicas.

```
engine = 'memtx',
is_local = true,
temporary = true,
```

**Comment by GeorgyKirichenko** [comment]
As truncate is used as fast shortcut for "table delete all" it should not be replicated across a cluster. Any other operation such as create/modify/drop should continue their working as before.
