### ISSUE TITLE
Printing a finished fiber stops the program

### ISSUE THREAD

**Issue by mtrempoltsev** [tarantool/tarantool#4265]
Tarantool version:

1.10.3

Bug description:

```
local fiber = require('fiber')

local f = fiber.create(function() end)

print(f)
print('done')
```

Output:

```
the fiber is dead
```

**Comment by GeorgyKirichenko** [comment]
Please use fiber.status(f) or even f:status() before any fiber operation that could raise an error (including this example)

**Comment by kyukhin** [comment]
No feedback for minths, closing.

**Comment by mtrempoltsev** [comment]
What feedback are you waiting for? A simple print causes a fatal error, the reproducer I brought.

Tarantool 2.2

```
LuajitError: the fiber is dead
fatal error, exiting the event loop
```

**Comment by kyukhin** [comment]
@GeorgyKirichenko provided you with clear workaround on how to work with fibers. I guess such thing as `print(f)` should be prohibited in docs.

**Comment by mtrempoltsev** [comment]
Do you really think that getting fiber status should cause a fatal error?

**Comment by Gerold103** [comment]
I would rather agree with Maks. Currently fiber object is too agressive about raising an error on literally anything when it is dead.
