### ISSUE TITLE
Introduce new type for UUID

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#4268]
UUID is widely used for identifiers. It is very useful and many applications use it for PK.
For now Tarantool lacks support of the type and we see, that sometimes
string is used store UUID. And this field is set as PK in a space.

This is awful from both performance and space points of view.

Let's make life simple and introduce dedicated field type.
IMHO, it should be stored just as we are going to do that for decimals,
using `mp_ext` of MsgPack.
See #692 for details.

Blocked until #692 is implemented.

**Comment by locker** [comment]
Duplicates #2916?

**Comment by kostja** [comment]
1) I disagree this should be in 2.3. Why is this important?
2) What type UUID? 0, 1, or 2? Users may want all of them.
