### ISSUE TITLE
[3pt] tests: on FreeBSD failed tests exists

### ISSUE THREAD

**Issue by avtikhon** [tarantool/tarantool#4271]
Tarantool version:
master

OS version:
FreeBSD

Bug description:
Failed tests inline - all tests skipped in testing with *.skipcond files:

Still skipped:
-----------------
| Test | Status | Issue |
|--------------|----------------|-------------|
| app/socket.test.lua | SKIPPED stable |  #5020 |
| app-tap/console.test.lua | SKIPPED stable | #5414 |
| app-tap/gh-1700-abort-recording-on-fiber-switch.test.lua | SKIPPED stable | #4819 |

No need to skip:
----------------------
| Test | Status | Issue |
|--------------|----------------|-------------|
| app/crypto.test.lua                       |      flaky not reproduced | returned back to testing |
| app/digest.test.lua                       |      flaky not reproduced | returned back to testing |
| app-tap/http_client.test.lua          |    flaky not reproduced | returned back to testing |
| replication/misc.test.lua              |      flaky test was renamed | already removed |
| replication/skip_conflict_row.test.lua |  flaky workaround | returned back with #4958 |
| wal_off/snapshot_stress.test.lua  |     flaky not reproduced | returned back to testing |
| box/net_msg_max.test.lua      |          flaky (LuajitError: not enough memory)  | returned back to testing |

Fixed:
--------
| Test | Status | Issue |
|--------------|----------------|-------------|
| box-tap/cfg.test.lua             | Data segment size exceeds process limit + fixed with SUSE build #4594 |
| app-tap/tarantoolctl.test.lua  |  |
| box/net.box.test.lua              |  |
| app-tap/pwd.test.lua             | Data segment size exceeds process limit |
| app-tap/debug.test.lua          | Data segment size exceeds process limit |
| app-tap/minimal.test.lua       | Data segment size exceeds process limit |

Steps to reproduce:

Optional (but very desirable):
* coredump
* backtrace
* netstat

**Comment by avtikhon** [comment]
Seems that issue:
Data segment size exceeds process limit
because of:
https://www.gitmemory.com/issue/LuaJIT/LuaJIT/332/494103183

**Comment by Totktonada** [comment]
Related: #4537.

**Comment by Totktonada** [comment]
Re app-tap/console.test.lua: we perform some test cases, then set on_disconnect() triggers for the gh-1938 case, check them and after that remove the triggers. Due to asynchronous disconnection nature, the on_disconnect trigger is fired for one of previous sessions. This can be verified in this way:

```diff
diff --git a/test/app-tap/console.skipcond b/test/app-tap/console.skipcond
deleted file mode 100644
index 48e17903e..000000000
--- a/test/app-tap/console.skipcond
+++ /dev/null
@@ -1,7 +0,0 @@
-import platform
-
-# Disabled on FreeBSD due to flaky fail #4271.
-if platform.system() == 'FreeBSD':
-    self.skip = 1
-
-# vim: set ft=python:
diff --git a/test/app-tap/console.test.lua b/test/app-tap/console.test.lua
index da5c1e71e..a74902d81 100755
--- a/test/app-tap/console.test.lua
+++ b/test/app-tap/console.test.lua
@@ -210,6 +210,7 @@ test:is(addr.host, 'unix/', 'console.listen uri support')
 test:is(addr.port, CONSOLE_SOCKET, 'console.listen uri support')
 s:close()
 
+fiber.sleep(1)
 --
 -- gh-1938: on_connect/on_disconnect/on_auth triggers
 --
```

After this the test passes. Don't know why it appears only on FreeBSD. Don't sure how to distinguish sessions to count from other ones, maybe like so: 9643fdc77323eb55a34ad8fefa7d4fa37b97ee87.
