### ISSUE TITLE
Tarantool fails to install on Macos X Mojave through Homebrew

### ISSUE THREAD

**Issue by nemat-rakhmatov** [tarantool/tarantool#4274]
Tarantool version: 2.1

OS version: Mojave 14.4.5

Bug description:
The command brew install tarantool --HEAD fails since cmake on Mojave uses -isysroot and clobbers lib search path, which makes compiler never look in standard ld locations.

Steps to reproduce:

brew install tarantool --HEAD

Workaround:

Add the following into projects cmake file:

IF(APPLE)
    LINK_DIRECTORIES(/usr/local/lib)
ENDIF()

**Comment by nemat-rakhmatov** [comment]
Additional info:
https://stackoverflow.com/questions/54068035

**Comment by avtikhon** [comment]
I've tried to install tarantool using brew and didn't met any issue, continue investigation.

**Comment by nemat-rakhmatov** [comment]
Mojave 10.14.5, Xcode 10.2.1, brew 2.1.4

$ cc --version
Apple clang version 11.0.0 (clang-1100.0.20.17)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

**Comment by nemat-rakhmatov** [comment]
Using --keep-tmp and adding above cmake lines into CMakeLists.txt leads to successful build. Without - the build fails

**Comment by nemat-rakhmatov** [comment]
The issue resolved with command:
sudo xcode-select -r

Now tarantool brews normally.
