### ISSUE TITLE
Failed to execute SQL statement: NOT NULL constraint failed

### ISSUE THREAD

**Issue by hogmuzzle** [tarantool/tarantool#4279]
Tarantool version:2.1

OS version:ubuntu 18.04

Bug description:
Error when inserting in sql 
error: 'Failed to execute SQL statement: NOT NULL constraint failed: APPUSER.ORG_ID'
Steps to reproduce:
 box.execute("insert into appuser values ('XKh9ar96g3MF','admin','5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8',NULL,NULL,NULL)")

Optional (but very desirable):

box.schema.space.create("appuser",{engine='vinyl', if_not_exists = true})
box.space.appuser:format({
   {name = 'id', type = 'string'},
   {name = 'user_login', type = 'string'},
   {name = 'user_password', type = 'string'},
   {name = 'org_id', type = 'string'},
   {name = 'courier_id', type = 'string'},
   {name = 'store_id', type = 'string'}
  })
  box.space.appuser:create_index('primary', {
   type = 'tree',
   parts = {'id'},
   if_not_exists = true
  })

**Comment by Korablev77** [comment]
You must specify `is_nullable` field in space format: by default it's false while creating format directly via Lua interface. However, if you create space via SQL CREATE TABLE statement, it's assumed to be true by default -- to turn it off use NOT NULL constraint. So:

```
CREATE TABLE t (id INT PRIMARY KEY, a TEXT);
INSERT INTO t VALUES (1, NULL); -- OK
```

```
box.schema.space.create("t")
box.space.t:create_index('primary', {type = 'tree',parts = {'id'}})
box.space.t:format({ {name = 'id', type = 'string'}, {name = 'a', type = 'string', is_nullable = true}})
box.execute("INSERT INTO \"t\" VALUES ('abc', NULL);") -- Also OK
```

**Comment by kyukhin** [comment]
Solved?
