### ISSUE TITLE
Luarocks can't be built-in using cmake lua_source

### ISSUE THREAD

**Issue by rosik** [tarantool/tarantool#4291]
Today we've found very interesting bug.

### Problem

For tarantool static build we try to embed luarocks in the same manner the box modules are embedded. Surprisingly, luarocks commands stop working with the error 
```
builtin/luarocks.util.lua:718: attempt to concatenate local 'vo' (a nil value)
```

### Origin 

The reason of the problem is in [this](https://github.com/tarantool/luarocks/blob/luarocks-3.1.1-tarantool/src/luarocks/util.lua#L714-L717) piece of code:

```lua
local vo, optional = valid_opts[k]:match("^(.-)(%??)$")
if not (tv == vo or (optional == "?" and tv == nil)) then
   error("invalid type option: "..k.." - got "..tv..", expected "..vo)
end
```
Normally it matches string like `"boolean?"` into `vo="boolean"`, `optional="?"`.
But when embedded, it returns `nil, nil`.

The reason of such behavior is [trigraph](https://en.wikibooks.org/wiki/C_Programming/C_trigraph) `??)`: during embedding cmake renders C source with `static const char[]` and lua module content, which is spoiled by gcc:

```

```text
luarocks/util.lua.c:715:61: warning: trigraph ??) converted to ] [-Wtrigraphs]
 "         local vo, optional = valid_opts[k]:match(\"^(.-)(%??)$\")\n"
                                                             ^
``` 

Thus, the script tries to match `^(.-)(%]$` instead of `^(.-)(%??)$` and fails.

**Comment by rosik** [comment]
I guess it should be fixed in [txt2c](https://github.com/tarantool/tarantool/blob/master/extra/txt2c.c) tool, which converts lua scripts to C static strings.

**Comment by Totktonada** [comment]
I think the fix should be pushed into all currently supported branches.
