### ISSUE TITLE
Add a script for checking coding style

### ISSUE THREAD

**Issue by locker** [tarantool/tarantool#4297]
It's really annoying to point to trailing spaces or bad indentation during review. We should probably add a test that would scan the source code and fail on gross violations of our coding guidelines.

**Comment by Gerold103** [comment]
Fuck yes.

**Comment by Totktonada** [comment]
There are `indent` based recommendations on the following page: https://github.com/tarantool/tarantool/wiki/Code-review-procedure-guidelines---checklist

**Comment by kyukhin** [comment]
I propose to implement new CI job which invokes clang-formatter.
We need to prepare a huge patch which will refactor whole existing codebase (except for third parties) and add `ignore revs file` which will skip it for blame.

**Comment by igormunkin** [comment]
JFYI, I suggest taking a look on the way clang-tidy is integrated in [uJIT](https://github.com/iponweb/luavela) testing machinery: the check is run in scope of the [corresponding `make` target](https://github.com/iponweb/luavela/blob/master/CMakeLists.txt#L273), using the custom [runner](https://github.com/iponweb/luavela/blob/master/scripts/run-clang-format).

**Comment by tsafin** [comment]
> JFYI, I suggest taking a look on the way clang-format is integrated in [uJIT](https://github.com/iponweb/luavela) testing machinery: the check is run in scope of the [corresponding `make` target](https://github.com/iponweb/luavela/blob/master/CMakeLists.txt#L273), using the custom [runner](https://github.com/iponweb/luavela/blob/master/scripts/run-clang-format).

Yup, beyond checking style in precommit job (which will be really easy to integrate with Pull-Request flow, but is doable with mail patches flow as well, as git server side checks) we should also provide to makefile targets:
- check the style for the incoming patch (i.e. for files which are in the git index at the moment). Which should be exactly the same script to be used as precommit;
- and the target to automatically fix style for the files to be changed.

i.e. something like `make smart-clang-format`.  and `make check-clang-format`

**Comment by igormunkin** [comment]
> * and the target to automatically fix style for the files to be changed.

This is the [default behaviour](https://github.com/iponweb/luavela/blob/master/scripts/run-clang-format#L184L187) for `run-clang-format` script: it just fixes all violations in-place (via running [`clang-format -i`](https://github.com/iponweb/luavela/blob/master/scripts/run-clang-format#L232L234)).

**Comment by Totktonada** [comment]
Sources of code style information:

* https://www.tarantool.io/en/doc/latest/dev_guide/c_style_guide/
* https://github.com/tarantool/tarantool/wiki/Code-review-procedure
* Server Engineer Standard Operating Procedures::Code review checklist (internal document)
