### ISSUE TITLE
automatically failover

### ISSUE THREAD

**Issue by lexoff92** [tarantool/tarantool#4298]
Tarantool version: 2.1
OS version: CentOS 7

I have a master-replica cluster configured.
When a master fails, you need to manually switch the master role, according to the documentation https://www.tarantool.io/en/doc/2.1/book/replication/repl_bootstrap/#controlled-failover

Can a Tarantool do it automatically? If so, how to implement it?

**Comment by kyukhin** [comment]
That is duplicate of #3055 and friends.
