### ISSUE TITLE
console.listen() with authorization

### ISSUE THREAD

**Issue by rosik** [tarantool/tarantool#4301]
It would be nice to have secure `console.listen()`, which can be bound on a TCP port. Without authorization it is a security breach.

I'm interested in accessing to tarantool instance before `box.cfg()`.

**Comment by kostja** [comment]
There is a task already in progress to make the binary port available before box.cfg{}. This one looks like a duplicate.

**Comment by rosik** [comment]
Guess you're talking about #3549 and #2625, but I can't see how it's going to work before box.cfg. Where could it get user credentials and permissions?

**Comment by rosik** [comment]
We've discussed it in chat, and here's the summary:

1. It's not a duplicate, no other tickets consider security questions.
2. console connection must be encrypted. It can be done similar to `swim.set_encryption_key`.

**Comment by rosik** [comment]
This issue isn't relevant anymore. Kostja is right, listening iproto before box.cfg is much better, and iproto is already worked around with cartridge remote-control implementation.
