### ISSUE TITLE
Allow to use NOTIFY_SOCKET without box.cfg{}

### ISSUE THREAD

**Issue by knazarov** [tarantool/tarantool#4305]
There's a very convenient mechanism of notifying systemd about the fact that the service has finished initialization. This mechanism is called a notification socket. We handle this currently in tarantool: when we've started an init loop, we call `systemd_snotify("READY=1")` (see main.cc). This causes a unix domain socket datagram to be sent through `NOTIFY_SOCKET`.

Unfortunately there's a problem in main.cc: `systemd_init()` is only called when we call `box.cfg{}`. There is no apparent reason for that, because we can write tarantool apps that don't use box api at all, but still leverage the event loop and async operations.

What I propose is to move the call to `systemd_init()` into `main()` like this:

```diff
diff --git a/src/main.cc b/src/main.cc
index 569ff4b5f..5776aa41d 100644
--- a/src/main.cc
+++ b/src/main.cc
@@ -555,7 +555,6 @@ load_cfg()
                        cfg_getb("log_nonblock"),
                        log_format,
                        background);
-       systemd_init();

        if (background)
                daemonize();
@@ -795,6 +794,7 @@ main(int argc, char **argv)
        cbus_init();
        coll_init();
        crypto_init();
+       systemd_init();
        tarantool_lua_init(tarantool_bin, main_argc, main_argv);

        start_time = ev_monotonic_time();
```

**Comment by knazarov** [comment]
The reason why I'm asking for this is because I use delayed calls to box.cfg. When the service starts, it's not called yet in my case.

**Comment by Totktonada** [comment]
I agree in general that coupling all initialization into one box.cfg() call is not good thing. Here however I afraid that the behaviour will be inconsistent between, say, `tarantoolctl status` and systemd's status. Tarantoolctl now requires you to call box.cfg() in an application.

**Comment by knazarov** [comment]
Why do you think so? This patch doesn't affect `tarantoolctl status` in any way. It just allows you to send startup notifications to systemd without calling box.cfg, which looks like a correct thing to do anyway.

To be clear, the thing that sends this notification is not box.cfg itself: it's the code that's called when your main script finishes, right before entering the event loop. box.cfg just reads environment variable `NOTIFY_SOCKET` and initializes the socket. It's the `systemd_snotify()` that is called from main() that actually does the work.

**Comment by Totktonada** [comment]
> Why do you think so? This patch doesn't affect `tarantoolctl status` in any way.

I mean that systemd will report status as 'started', while `tarantoolctl status` will consider an instance as 'stopped' before box.cfg().

**Comment by knazarov** [comment]
For current users (that call box.cfg during the initialization) it won't change anything. The notification is sent as before.

For users that delay the start of box.cfg, current approach simply doesn't work, because systemd will block until it receives the notification, or timeout and fail after 86400 seconds. So if will block OS startup for example.

As for systemd, take a look at what `tarantoolctl status` actually does: https://github.com/tarantool/tarantool/blob/master/extra/dist/tarantoolctl.in#L754 . It just delegates to `systemctl status`. So they will show essentialy the same.

**Comment by Totktonada** [comment]
If it'll forward to systemd, yep, it will show the same. In any other case it will not. Again, I don't against your patch, but we should at least think how to better support non-box-cfg applications at whole.

I mean, your patch solves one particular problem and that is good. But this particular problem is the part of our past vision how to run applications and more things should be changed to support the new way (possibility to omit box.cfg()).

**Comment by knazarov** [comment]
In other cases, when not running under systemd, this code will do nothing, because it doesn't affect the behavior outside systemd. It is only meaningful as a way to signal to systemd that it can proceed with initialization.

**Comment by Totktonada** [comment]
I understand. That is why I say it is inconsistent: we'll have two different meaning of 'started' state after the change.

**Comment by knazarov** [comment]
What meaning are you talking about?

- For those who don't use systemd, we don't change anything
- For those who use systemd AND call box.cfg {} we don't change anything
- For those who use systemd AND don't call box.cfg{} we change state from not working to working

Currently in the code that message through the socket means that we entered an event loop, and it happens when the main script exits. If it was called during box.cfg{}, I'd understand your argument that it changes what it means to be started, because we move the actual call of notification function. But its relation to box.cfg{} is only in initialization of the socket.

If the question is "should we allow applications that don't call box.cfg{} to work as first class citizens" then of course that's up to you (I mean the core team). Let me know when you decide.

**Comment by Totktonada** [comment]
> should we allow applications that don't call box.cfg{} to work as first class citizens

Yep, it is what I meant. Your patch looks safe (in the sense that it does not break anything), but it raises the question about relation between box.cfg() and an application initialization.

**Comment by knazarov** [comment]
What is the next action then to get this through?

**Comment by Totktonada** [comment]
I guess nothing within scope of this issue. But we possibly should adopt tarantoolctl to work in this way in the future.
