### ISSUE TITLE
Unable to call a function on tarantool-1.10* from tarantool-2* with net.box

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#4307]
Tarantool versions:

* Server: 1.10.3-73-g154d4f526 Linux-x86_64-Debug.
* Client (net.box): 2.2.0-423-gd3b2bcb66 Linux-x86_64-Debug.

OS version: Gentoo Linux.

## server.lua

```lua
#!/usr/bin/env tarantool

box.cfg({listen = 3301})

box.once('init', function()
    box.schema.user.grant('guest', 'read,write,execute,create,alter,drop',
                          'universe')
end)

function echo(...)
    return ...
end
```

## client.lua

```lua
#!/usr/bin/env tarantool

local net_box = require('net.box')
local json = require('json')

local connection = net_box.connect('localhost:3301')
local response = {connection:call('echo', {1, 2, 3})}
print(json.encode(response)) -- [1,2,3]
os.exit()
```

When both server and client are run with 2.2 or 1.10 the client prints `[1,2,3]` as expected. When the server is on 1.10, but the client is on 2.2 the output is `Space '277' does not exist`. 277 is ID of `_vcollation` system space.

Looks as the regression from of #3941.

**Comment by cyrillos** [comment]
@romanhabibov This patch fixes similar problem for me.
