### ISSUE TITLE
Sequences misunderstandings

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#4314]
I have Ubuntu 18.04. I have Tarantool 2.x, pulled from source today.

I execute these requests:
box.space.t:drop()
box.sequence.S:drop()
box.schema.sequence.create('S',{min=0, start=0, max=10})
s=box.schema.space.create('t')
s:create_index('I',{sequence='S'})
box.space.t:insert{box.NULL}
box.space.t:insert{box.NULL}
box.space.t:insert{box.NULL}
box.space._sequence_data:select()
box.sequence.S:next()
box.space._sequence_data:select()
The first "box.space._sequence_data:select()" returns nothing.
The second "box.space._sequence_data:select()" returns [1, 3].
So I can see that "box.space.t:insert" was changing the index value.
I do not understand why "box.space._sequence_data:select()" didn't show that.

I execute these requests:
box.space.t:drop()
box.sequence.S:drop()
box.schema.sequence.create('S',{max=tonumber64('9223372036854775808')})
I get an error message saying "expected integer".
But according to our definition, that number is within the integer range.
For example, insertion of the number in an 'integer' field causes no error:
box.schema.space.create('K')
box.space.K:create_index('I',{parts={1,'integer'}})
box.space.K:insert{tonumber64('9223372036854775808')}
I do not understand why the definition of 'integer' does not apply to sequences.

I execute these requests:
box.space.t:drop()
box.schema.space.create('t')
box.space.t:create_index('primary', {
    parts = {{1, 'unsigned'}},
    sequence = {field = 1}
})
box.space.t:insert{5}
box.space.t:insert{tonumber64('9223372036854775808')}
box.space.t:select({6},{iterator='GT'})
box.space.t:insert{box.NULL}
box.space.t:select()
The first "box.space.t:select" returns 9223372036854775808,
which shows that t has a tuple with a value greater than 1.
The second "box.space.t:select" returns values including 6,
which shows that Tarantool thought the previous maximum was 5.
I do not understand why a large unsigned value was ignored.

**Comment by Korablev77** [comment]
1) AFAIU `_sequence_data` is updated only after recovery (not even after box.snapshot()). I guess this should be documented (now doc says that this field is "non-persistent information" and on the other hand "To see what the previous value was, without changing it, you can select from the _sequence_data system space.").
2) Max allowed sequence value is INT64_MAX == 2^63-1. I guess this should be documented as well (now doc only says that INT64_MAX is default value for `max` property) and not going to change (at least soon).
3) In a consequence of previous point, values >=INT64_MAX are ignored by sequence (when there's a gap between INT64_MAX - 1 and max value from space which is less than INT64_MAX - 1). I guess this should be documented.
@kyukhin Fix me if I'm wrong.

**Comment by kyukhin** [comment]
Sounds reasonable. @pgulutzan does this solve your misunderstandings?

**Comment by pgulutzan** [comment]
Yes, solved. I changed a few lines in the manual.
https://github.com/tarantool/doc/commit/fdce75e1ea2e09db9c27668b6dbcbef4db0da64a
I believe you can close this.
