### ISSUE TITLE
tunnel_filter error

### ISSUE THREAD

**Issue by ldr1003049820** [tarantool/tarantool#4315]
Tarantool version: dpdk 18.08

OS version:centos 

Bug description:use tunner_filter add，when use ordinary network card, error eth_igb_filter_ctrl(): Filter type (6) not supported. and when use mlx5 ,it become net_mlx5: port 2 filter type (6) not supported, cmd_tunnel_filter_parsed error: (Operation not supported). i don't know why, please help me. 

Steps to reproduce:

Optional (but very desirable):
* coredump
* backtrace
* netstat

**Comment by kyukhin** [comment]
Wrong repo, sorry.
