### ISSUE TITLE
Consider linking libcurl statically from a submodule

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#4318]
At the moment two distros have a default libcurl version that contains some sensible problems, which affect tarantool's http_client.

* CentOS 7 has a problem with redirects due to libcurl-7.29 which does not handle redirects properly (it was fixed in 7.31, however may be worked around on our side). #4180.
* Mac OS (brew) installs libcurl-7.51, which segfaults from time to time (was fixed in libcurl master, not released yet; I doubt it can be worked around). #4288.

Before we observe a problem when an our side problem appears only with relatively new version of libcurl: #4179.

So there are the class of problem which can be worked around by controlling a version of libcurl we link against. AFAIK the only way to achieve this is to fix a libcurl version (I would use a submodule) and link it statically to a tarantool executable.

To be clear: I think that static linking of a system libraries is generally bad thing and should be avoided as far as feasible. But I see no other way to control this class of problems.

We should decide about options and dependencies with which we want to build curl: say, whether to use async DNS (built-in or c-ares?) and whether to link with nghttp2 (I don't tested whether our http_client supports http2).

If we'll decide to link with nghttp2 we should link it statically, because there is no guarantee that a target system has it: we have no direct dependency from tarantool to nghttp2. However openssl whould be linked dynamically, because it 1) we have it as a dependency; 2) it is important to allow a user to perform fast security updates.

If we'll link with libcurl statically we should remove it from dependencies in our RPM / Deb packages (and the same in Mac OS brew formulae).

We'll required to track security updates of libcurl and update / backport it as fast as possible.

So, there are cons and pros. We need to decide whether we want to going this way.

**Comment by olegrok** [comment]
Please, check that you have not broken https://github.com/tarantool/tarantool/blob/master/Dockerfile.staticbuild

**Comment by Totktonada** [comment]
@olegrok Thank for the reminder. Of course, we'll verify that it works. We also plan to add testing of the static build to CI soon (#3668).
