### ISSUE TITLE
_ck_constraint code not useful

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#4324]
I have Ubuntu 18.04.
I have Tarantool 2.x, pulled from source today.

I execute these requests:

box.schema.space.create('t')
box.space.t:format({{name = 'f1', type = 'unsigned'},
                    {name = 'f2', type = 'string'},
                    {name = 'f3', type = 'string'}})
box.space.t:create_index('i')
box.space.t:create_check_constraint('c2', [["f2" = UPPER("f3") AND NOT "f2" LIKE '__']])
box.space._ck_constraint:select()

The result looks like this:
tarantool> box.space._ck_constraint:select()
---
- - [514, 'c2', false, 'SQL', '"f2" = UPPER("f3") AND NOT "f2" LIKE ''__''']
...

Now I try to use that expression in another statement:

box.space.t:create_check_constraint('c9', '"f2" = UPPER("f3") AND NOT "f2" LIKE ''__''')

The result looks like this:
tarantool> box.space.t:create_check_constraint('c9', '"f2" = UPPER("f3") AND NOT "f2" LIKE ''__''')
---
- error: '[string "box.space.t:create_check_constraint(''c9'', ''"f..."]:1: '')''
    expected near ''''__'''''
...

So the expression (the "code" field) won't work with create_check_constraint.

So now I say:

tarantool> \set language sql
---
- true
...

tarantool> \set delimiter ;
---
...

tarantool> create table t2 ("f1" int primary key, "f2" text, "f3" text, check ('"f2" = UPPER("f3") AND NOT "f2" LIKE ''__'''));
---
- row_count: 1
...

So the expression will work if I'm using SQL with CREATE TABLE.
But I'm using Lua and create_check_constraint and _ck_constraint so I expect the _ck_constraint code to work with create_check_constraint.

**Comment by kshcherbatov** [comment]
Hi, Peter!
I think you should use \' instead of '' in expression, because ' is a string quote sign here
```
tarantool>  box.space.t:create_check_constraint('c9', '"f2" = UPPER("f3") AND NOT "f2" LIKE \'__\'')                                                           
---
- space_id: 512
  name: c9
  expr: '"f2" = UPPER("f3") AND NOT "f2" LIKE ''__'''
...
```

The error is raised by Lua console, so it is not a bug, but expression definition specific in Lua console

**Comment by pgulutzan** [comment]
@kshcherbatov: I do not understand why you think this is not a bug. But we can wait and see if a real customer encounters the same problem.

**Comment by kshcherbatov** [comment]
@pgulutzan 
I mean it is not a bug of server code. This error is produced by Lua interpreter. it seems to be Lua language restriction.

**Comment by pgulutzan** [comment]
We don't agree, but as I said, we can wait and see if a customer encounters the same problem.
