### ISSUE TITLE
Consider partial core dumps to be enabled by default

### ISSUE THREAD

**Issue by filonenko-mikhail** [tarantool/tarantool#4337]
Tarantool is Database and Application Server in one box.

Appserver development process contains a lot of lua/luajit-ffi/lua-c-extension code.

Coredump is very useful in case when some part of appserver crashed. If the reason is input - data from database is not necessary. If the reason is output - data from database is already in snap/xlog files.

Therefore consider core dumps without data enabled by default.

**Comment by cyrillos** [comment]
[PATCH] box/memtx: Skip tuple memory from coredump by default

**Comment by olegrok** [comment]
@kostja 

Are you sure that milestone is 1.10.4?

Initially this feature (https://github.com/tarantool/tarantool/issues/3509) was merged to 2.2
