### ISSUE TITLE
box.cfg output is not sorted 

### ISSUE THREAD

**Issue by eljashm** [tarantool/tarantool#4361]
Although it should be according to the documentation. 

    tarantool> box.cfg
    ---
    - vinyl_run_count_per_level: 2
     rows_per_wal: 500000
     feedback_host: https://feedback.tarantool.io
     readahead: 16320
     wal_dir: .
     checkpoint_interval: 3600
     ---
     ...

**Comment by kyukhin** [comment]
That is misunderstanding. Documentation states:
```
tarantool> box.cfg -- sorted in the alphabetic order
```

This actually means that output was sorted by hand.
We will update documentation to accent this.
