### ISSUE TITLE
sql: integer overflow during addition of floating point

### ISSUE THREAD

**Issue by Korablev77** [tarantool/tarantool#4369]
```
create table x (s1 scalar primary key);
insert into x values (1e0),(9223372036854775807),(9223372036854775806);
select sum(s1) from x;
---
- error: 'Failed to execute SQL statement: integer overflow'
...
```
The problem is that `1e0` value in fact is stored as integer both if value is inserted via SQL facilities (`mpstream_encode_vdbe_mem()`) and Lua. However, in the latter case one can force floating point representation using `ffi.new('double', 1)`. Meanwhile in SQL there's no an ability to control internal format.

**Comment by ImeevMA** [comment]
@Korablev77 I wasn't able to reproduce the problem using given reproducer. I think it was fixed it commit be389cb "sql: refactor arithmetic operations to support unsigned ints". Do you think that the problem is still exists?

**Comment by Korablev77** [comment]
Of course this particular example doesn't work anymore. This one works:
```
create table x (s1 scalar primary key);
insert into x values (1e0),(9223372036854775807),(9223372036854775808);
select sum(s1) from x;
```

**Comment by ImeevMA** [comment]
@Korablev77 Is this issue still relevant?

**Comment by Korablev77** [comment]
Nope, https://github.com/tarantool/tarantool/commit/0dd8be7605ab99b270ce72c503e5deaa2b448557 fixed the problem. Closed.
