### ISSUE TITLE
Luajit fold machinery needs extra checks for correct transformations

### ISSUE THREAD

**Issue by sergos** [tarantool/tarantool#4376]
Tarantool version:
master (2.2)
OS version:
Ubuntu 18.04
Bug description:
Fold machinery in luajit (src/lj_opt_fold.c) neglects data dependency for an IR. Thus SNEW result can be intermixed with original STR pointer, leading to incorrect result of pointer arithmetics. Details: https://github.com/LuaJIT/LuaJIT/issues/505

A stub solution is to disable the transformation and this tracker is to figure out the correct way to detect the data dependency - apparently, the STRREF should be the only use of the SNEW result.

Steps to reproduce:

test-run.py luajit-tap/fold_bug_LuaJIT_505.test.lua

Optional (but very desirable):
* coredump
* backtrace
* netstat

**Comment by Totktonada** [comment]
Related issue in openresty: https://github.com/openresty/luajit2/issues/47

**Comment by kyukhin** [comment]
Fixed by 587532e66ab447728be8a0a23fd8a3ef4f623661

**Comment by Totktonada** [comment]
Fixed in the LuaJIT submodule in https://github.com/tarantool/luajit/commit/587532e66ab447728be8a0a23fd8a3ef4f623661

The LuaJIT submodule is promoted to this commit in 2.3.0-18-ga634bd7de, 2.2.1-8-gf20e692d5, 2.1.2-148-g4e684f413, 1.10.3-112-g8bc69524a.
