### ISSUE TITLE
travis-ci: wrong global environment setup

### ISSUE THREAD

**Issue by avtikhon** [tarantool/tarantool#4377]
Tarantool version:
All

OS version:
All

Bug description:
Found that travis-ci global environment values schema
had the mistake in definition - fixed with added "global:" tag
and added the missed travis-ci environment value to the docker
call.

Steps to reproduce:
travis-ci any job

Optional (but very desirable):
* coredump
* backtrace
* netstat

**Comment by Totktonada** [comment]
You describes a solution, not a problem. What is a problem? Whether it is still relevant?

**Comment by Totktonada** [comment]
I guess `TEST_RUN_EXTRA_PARAMS` is not necessary now (since we don't use Travis CI anymore). How about dropping the variable at all and close the issue? If we'll need to tweak some test-run option, I would read it from an environment variable of the test-run side.
