### ISSUE TITLE
Interactive transactions over network connections

### ISSUE THREAD

**Issue by zilveer** [tarantool/tarantool#4386]
Hi,
I would like have the ability to run interactive transactions over network with Tarantool.

For example:
Try {
START TRANSACTION
make a bunch of queries 
COMMIT
} Catch(){
ROLLBACK
}

And this without writing stored procedures or running the code itself in the Tarantool server. 

Thanks for your hard work !

Regards

**Comment by Gerold103** [comment]
Perhaps linked with https://github.com/tarantool/tarantool/issues/2016.

**Comment by kyukhin** [comment]
I bet this is a duplicate of #2016

**Comment by zilveer** [comment]
@Gerold103 and @kyukhin so is interactive transactions possible currently?

**Comment by alyapunov** [comment]
> 
> 
> @Gerold103 and @kyukhin so is interactive transactions possible currently?

Not yet. See #2016.
