### ISSUE TITLE
Expose box.error to be used by applications

### ISSUE THREAD

**Issue by knazarov** [tarantool/tarantool#4398]
Currently box.error is mostly useful for tarantool itself, but it will be really useful if we could use it in applications. 

Here's what we have right now as a substitute: https://github.com/tarantool/errors

What we would like box.error to have:
- Ability to create new error types
- Ability to skip error codes if we don't need them
- Transparent marshalling through net.box

Creating new error types and matching against them is important, because we often create distributed apps where it's impossible to have consistent error codes between microservices. It is however often possible to just match against error types.

**Comment by parihaaraka** [comment]
It would be nice to pass any user data (e.g. template id and args to compose a localized message).

**Comment by LeonidVas** [comment]
If I understood correctly, We want to extend the box.error module functionality by adding some stuff from the task description in a lua error module style (https://github.com/tarantool/errors) (in according with open/closed principle).

I propose the following extension for the box.error module API:
- box.error.register_custom_type(type, description) - register new type of custom error (after that object can be created by using the box.error.new() method). Type and description are strings
- box.error.list_custom() - return a list of registered custom errors

Methods for work with error_obj(returned by the box.error.new() method):
- box.error.get_stack(err_obj) - return the stack as a string
- box.error.get_type(err_obj) - return the type as a string
- box.error.to_string(err_obj) - return the error as a string
- box.error.get_location(err_obj) - return the error generating location (line and file name)
 
 Add a possibility of work with object in lua style ( like err_obj: ).
And yes, it's must work through net.box (Transparent marshalling through net.box).

**Comment by olegrok** [comment]
@LeonidVas 

Thanks for your proposal. I think we should discuss several points.

> box.error.register_custom_type(type, description)

So, should we persist our custom error object or it should be registered as triggers on every restart?

> get_stack/get_type

May be simple `error:type()` / `error:stack()` and so on?

> Methods for work with error_obj(returned by the box.error.new() method):

Some methods for box.errors are already implemented: https://github.com/tarantool/tarantool/blob/master/src/lua/error.lua

Also this issue is quite close to https://github.com/tarantool/tarantool/issues/1148 that was discussed before. However I found only this - https://github.com/tarantool/tarantool/blob/kshch/gh-1148-stacked-errors/doc/rfc/1148-stacked-diagnostics.md

May be we should to write the public RFC before and discuss it carefully

**Comment by LeonidVas** [comment]
Thanks for the comments.

>box.error.register_custom_type(type, description)
>So, should we persist our custom error object or it should be registered as triggers on every restart?
I think - it should be registered as triggers on every restart. 

> Some methods for box.errors are already implemented: 
> https://github.com/tarantool/tarantool/blob/master/src/lua/error.lua
I overlooked it. Yes, new API is an error.lua module extension (a getter naming style will be saved).

About RFC. It is a good question and I'll think about it.

**Comment by LeonidVas** [comment]
After a second iteration of the discussion, it was decided to remove the registration step (and the list 
method too). So, API will be close to current. Will be added a possibility to create a custom error (new type of error) with something like a subtype (custom type) wich will be available from API and a backtrace will be added to all errors.

**Comment by knazarov** [comment]
@LeonidVas please post the proposed API here

**Comment by knazarov** [comment]
Also, what about 1.10? Will there be a way to use it there?

**Comment by LeonidVas** [comment]
Now box.error API:
described at https://www.tarantool.io/en/doc/2.2/reference/reference_lua/box_error/

+ from tarantool/src/lua/error.lua

attributes:
	type(string) 
	message(string)
	trace(table with file name and line number)
	errno(number)

methods:
	unpack
	raise
	match - match the error message

	__tostring - return the error.message

I am propose to add a new type - ER_CUSTOM_ERROR - "Custom Error"

To box.error API add:
box.error.new_custom(errtype, errtext) - errtype is custom type

To attributes:
	backtrace(string) - for all errors
	custom_type(string) - if ER_CUSTOM_ERROR - return custom type else some stub

To methods:
	is_custom_type(custom_type) - with custom type - check is custom type == custom_type else (custom_type == nil) is type == ER_CUSTOM_ERROR

As I am understand it must work in version >=2.4.1.

**Comment by knazarov** [comment]
@LeonidVas how will the usage actually look like in the user code?

You see, as error handling is used pretty much on every 10-th line of code, having to use boilerplate is a no-go. Here's how we do it in our `errors.lua`:

```lua
local e_http = errors.new_class('HttpInitializationFailed')

-- like this
local res, err = e_http:pcall(httpd.start, httpd)
if res == nil then
    return nil, err
end

-- or like this
if (vars.boot_opts ~= nil) then
    return nil, e_http:new('Cluster is already initialized: %s', in_depth_error_description)
end
```

And as for traces, the current implementation is very bare in what it outputs when you do `tostring()` on an error. e.g. it only shows error message, which is not informative at all. In addition to that, I suspect that your current backtrace design doesn't take into account what lua's `debug.traceback()` does. See [here](https://github.com/keplerproject/lua-compat-5.3/issues/16) for the implementation.

**Comment by LeonidVas** [comment]
Thanks for your comments.
In my interpretation it's look like:

if (some_condition) then
	return nil, box.error.new_custom("My_custom_type", "Something went wrong")
end

In my mind e_http obj from your example looks like a 'builder' and it can be added to tarantool/src/lua/error.lua module. It's don't change a C part of box.error just a some wrap on lua and I don't mind. Please, can you write view of API extension in your mind.

About backtrace implemantation - I propose to use a char* backtrace() from backtrace.cc . If I understood correctly the debug.traceback() "print" only lua bt, backtrace() - with C bt.
But It's not about API.

**Comment by parihaaraka** [comment]
Why do you limit a user with textual type only? Reserve a map-field to store any data. A user may store type name or/and other values (e.g. for localization purposes) if he wants.
Iproto error response may utilize DATA key for this purpose.

**Comment by LeonidVas** [comment]
Hi. If I understand correctly, you want to have some payload with the custom error. But it is not a type name (type name is just a type name(ASCII)). 
About payload:
In my mind it's just a raw data (byte set) with size. Encode/decode payload - it is an user application troubles.
So, two questions:
- What you are offer is payload?
- How it should look for the user in your mind? (example)

**Comment by R-omk** [comment]
my view example 
```yaml
code: 5879
type: myStringErrorType
message: Optional my message
trace: []
otherRequiredAttr:  ~
data:
  someTag: driver
  myLabel: recoverable
  size: 56

```

__tostring  can  be something like 
myStringErrorType=Optional my message   someTag=driver   myLabel=recoverable   size=56

or other human readable format 



map of scalar type (or any type)   is universal data structure for such purposes.
It can be very similar to how tags are used in opentracing.

**Comment by parihaaraka** [comment]
If a user has `data` node to put there anything he wants - he may put `type` there too. We need to pass payload with _any_ error type. We ought to use errors this way:
```
box.error({
        code = box.error.EX_ENCODED,
        reason = mp.encode({
            code = box.error.EX_BAD_ARGUMENT,
            reason = string.format('unable to do the job X because of bad argument %s value %s', 1, arg),
            mask_id = 'badArgumentOfFunctionX',
            args = {num = 1, value = arg},
            extra = {context = 'gui_anchor1'}
        })
    })
```

**Comment by LeonidVas** [comment]
Hello.
So, I want to share the current status of the feature and a plan.
The current API:

attributes:
- type(string) 
- message(string)
- trace(table with file name and line number)
- errno(number)
- bt(string) - Lua backtrace (after discussion with @Totktonada was decided to exclude a C backtrace)

methods:
- unpack
- raise
- match - match the error message
- is_custom - check is an error a custom error

-  __tostring - return the error.message

Add to the interface payload (getter/setter) is planned.
Possible implementation:
Pack/unpack using msgpack and store in struct error as pointer and size of the data

What was done:
- Lua bt for all type of errors (after transmitting through net.box remote bt will be meld with local bt)
- Custom type errors has been added (An error of special type (CustomType) with custom subtype which may be checked in future)
Example:
err_custom = box.error.new(box.error.CUSTOM_ERROR, "MyCustomType", "Reason")
err_custom.custom_type == "MyCustomType"
- Updated the format of transmission an error through net.box in both cases IPROTO_OK and IPROTO_ERROR
IPROTO_ERROR(the error was thrown in process of the net.box call):
Before:
An error code and the message was transmitted (and it can't be expanded without trick)
Now:
A map is used for transmit an error details (it's needed for transmit bt and custom type)
IPROTO_OK(The error is one of the returned values transmitted through net.box):
Before:
Only an error message was transmitted
Now:
The table with keys like in IPROTO_ERROR case

In both cases new fields can easily be added.

For backward compatibility negotiation phase in connection establishing was added.
Now the error transmission format depends on the client choice at the start of the session (old is default).


All other features(syntactic sugar) must be realized by external lua module like https://github.com/tarantool/errors

**Comment by rybakit** [comment]
> unpack
> raise
> match - match the error message

Could you give some brief examples of what these methods should do and/or how they should be used?

**Comment by LeonidVas** [comment]
> > unpack
> > raise
> > match - match the error message
> 
> Could you give some brief examples of what these methods should do and/or how they should be used?

unpack - "unpack" an error to table
raise - throw an error
match - match the error message using string.match

And, if I understand correctly, you want to propose something)

**Comment by Gerold103** [comment]
> bt(string) - Lua backtrace (after discussion with @Totktonada was decided to exclude a C backtrace)

I don't think it is a good idea to shut down C backtracing forever. This API soon or late will be asked to and will be exposed to C, where a C trace may be useful.

**Comment by LeonidVas** [comment]
Feedback(notes):
From @Gerold103 - C trace may be useful
From @Mons and @knazarov - Adding backtrace to the error is a per server parameter (it can be forced when creating an error)
From @knazarov - Add bt to the message in tostring() output
From @knazarov - boilerplate must be box.error functionality
From @R-omk and @parihaaraka - want to have a custom payload
From @LeonidVas - payload possible implementation: Pack/unpack using msgpack and store in struct error as pointer and size of the data
(for client it's look like err:set_payload(table)/payload_table = err:get_payload())
From @LeonidVas - boilerplate must be an external decorator (opinion is in conflict with @knazarov point of view)

@Totktonada, @kyukhin do you have any comments?

Plans:
Work on the feature is suspended until the first iteration of the review is completed.
Cause: There are some critical points that need to be clarified (negotiation phase and serializer context)

**Comment by LeonidVas** [comment]
@knazarov - Add bt to the message in tostring() output
Forwarded from mailing list:

> AFAIU, Kostya want to see a backtrace in logs when an error is not
> catched anywhere (and maybe in some other cases?). We should ask for
> expected behaviour rather that for certain implementation.
> 
> We have __tostring(), which is used when casting to a string explicitly
> or implicitly via concatenation. I would expect just error message here.
> 
> We have __serialize() for repl. It is logical to have backtrace and
> other fields here.
> 
> Note: __serialize() returns an error message and on the first glance it
> seems that we should keep it here for the old way marshaling over the
> binary protocol. However, no, we'll handle errors in serializers
> explicitly and will not use __serialize().
> 
> What method is in use when an error is written to logs (when not
> catched, when diag_log() is used, when written by log.info() from Lua)?
> I think it should be __serialize(), but it is possible that it is not so
> now.
> 
> Hm. Maybe Kostya is about case like:
> 
> | local res, err = my_func()
> | if res == nil then
> | log.info('My message, reason: ' .. err)
> | return
> | end
> 
> What we'll propose for this case? Something like so?
> 
> | log.info('My message, reason: ' .. yaml.encode(err))
> 
> Need to think

**Comment by Gerold103** [comment]
It was decided how public API should look in the first implementation. To be extended later.

Firstly, we omit payload and implement it later. Because there are some non trivial things how to handle it internally effectively.

Secondly, there won't be any kind of 'box.error.register_type'. At least in the initial implementation.

The only thing changed in the public API will be that you can specify your custom error type name in `box.error.new`.

For example:

```Lua
box.error.new({type = 'VShard.BucketTransferInProgress', reason = 'State is "sending"'})
-- or
box.error.new('VShard.BucketNotFound', 'Last tried uuid %s', uuid)
```

So essentially that makes the most valued feature in the initial patch the error marshaling through MessagePack.

You will be able to access your type using the original `<error_object>.type`. For example:

```Lua
e = box.error.new({type = 'VShard.BucketIsPinned'})
assert(e.type == 'VShard.BucketIsPinned')
```

Still you will be able to get the internal error type using another member. We didn't decide on a name yet. Probably something like `base_type`. That will help in case you defined your own `CustomError` or any other name conflicting with existing built-in names. And still want to do some preprocessing by base types. Such as OutOfMemory vs ClientError vs SwimError vs CustomError, and so on.

```Lua
e = box.error.new({type = 'VShard.BucketIsPinned'})
assert(e.type == 'VShard.BucketIsPinned')
assert(e.base_type == 'CustomError')

e = box.error.new(123)
assert(e.type == 'ClientError')
assert(e.base_type == 'ClientError')

e = box.error.new({type = 'ClientError', message = 'Not real client error'})
assert(e.type == 'ClientError')
-- Here you always see real type.
assert(e.base_type == 'CustomError')
```

Backtrace will be collected for Lua only, and won't be concatenated when the error is rethrown, or repushed to Lua, or anyhow else. For C backtrace will be enabled lated, maybe. For Lua it is optional as a per server option, and as an option in `box.error.new`.

Concatenation is dropped because there is no way to implement it so everyone would like it. For example, concatenate on throw is bad, because throw is a deprecated way of returning errors. We do it via `nil,err` convention.

Concatenation on simple repush of an error object is obviously wrong - the error object will change constantly and unexpectedly. Also this is a perf problem. For example, assume we append stacktrace to every error returned from netbox. In that case we need a full deep traversal of every `call()` result to find error objects here, and append a current trace to them. This is simply wrong, and slow.
