### ISSUE TITLE
Introduce GREATEST, LEAST functions to reduce non-typical MIN/MAX overloading

### ISSUE THREAD

**Issue by kshcherbatov** [tarantool/tarantool#4405]
https://database.guide/max-vs-greatest-in-mysql-whats-the-difference/
https://www.databasestar.com/oracle-greatest/
http://www.postgresqltutorial.com/postgresql-min-function/

**Comment by lenkis** [comment]
Doc ticket: https://github.com/tarantool/doc/issues/862
