### ISSUE TITLE
Extend SQL result set metadata

### ISSUE THREAD

**Issue by nicktorwald** [tarantool/tarantool#4407]
The JDBC spec describes [ResultSetMetaData](https://docs.oracle.com/javase/8/docs/api/java/sql/ResultSetMetaData.html) to be able to examine a set of field properties. In tarantool-java we are interesting in `isAutoIncrement`, `isCaseSensetive`, `isNullable`, `getColumnLabel` (alias), `getColumnName` (table column) properties to be known.

Perfectly, if this sort of properties we can extract from the response METADATA part.
Another possible way is to fetch the data from the system spaces using extra query(-ies). However, it can require again extra info to be used to perform such queries (i.e. table name or table id etc.).

Should we split each property into a separate issue?

**Comment by kostja** [comment]
It's a single issue. It should all be in response METADATA. this is really a server issue - we need to track this information through query execution stages.
