### ISSUE TITLE
Publish SQL pragmas

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#4418]
Pragmas are still not documented and not finalized.

It is an acceptable mechanism to tune SQL behavior and we should keep it. Decide on which pragmas we keep and document these. Remove the rest.
This is critical since currently there is no way to use SQL engine other than memtx without a pragma.

**Comment by pgulutzan** [comment]
PRAGMA is now documented in the version-2.3 manual. Perhaps this can be closed now.
