### ISSUE TITLE
sql: allow to specify engine in CREATE TABLE stmt

### ISSUE THREAD

**Issue by Korablev77** [tarantool/tarantool#4422]
Currently, to create table with `vinyl` engine we have to switch default engine using `pragma sql_default_engine = 'vinyl'`. After that, all tables created in SQL will feature `vinyl` engine. However, there's no mechanism to specify engine per table. Suggestion is to extend syntax of `CREATE TABLE` statement to set engine. For instance, `CREATE TABLE (...) WITH ENGINE = 'vinyl'`

**Comment by kyukhin** [comment]
@Korablev77 could you please propose a syntax and discuss it w/ @pgulutzan

**Comment by Korablev77** [comment]
@kyukhin I've already done that: `CREATE TABLE (...) WITH ENGINE = 'vinyl'` For example, syntax which is used in MySQL is `CREATE TABLE (...) ENGINE = '...'`. However, IMHO `WITH` keyword seems to quite suitable.

**Comment by pgulutzan** [comment]
Yes. I suppose WITH is not truly necessary but it might be helpful to show clearly where the table elements end and the table options begin. i suppose that Tarantool might someday support more table options, so let me suggest that in general they will be  at the end, not comma-delimited, format "keyword=literal", the keyword does not need to be a reserved word, the literal must be a literal not a placeholder or variable or expression. I suppose that ALTER TABLE t engine='vinyl'; will be okay too someday. I suppose that CREATE TABLE t AS SELECT ... WITH engine='vinyl'; will be okay too someday.
