### ISSUE TITLE
box functions are not always follows default msgpack serializer options

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#4434]
Tarantool version: 1.10.3-52-g02b5948bd.

There is ability to configure default msgpack serializer that in used in box function from Lua:

https://github.com/tarantool/tarantool/blob/6277f48ad8a7213d73e280d5046c5b5872f74e25/src/lua/msgpack.h#L47-L52

There is also the [issue](https://github.com/tarantool/doc/issues/859) to document it.

I tried to use `msgpack.cfg({encode_max_depth = 1024})` to solve a customer problem with truncation of data with many nesting levels, but met several problems.

The application contains several before_replace triggers like so:

```lua
function triggers.set_mtime64(data_field)
    return function(_, new)
        if new == nil then return new end 
        local data = new[data_field]
        data.mtime = fiber.time64()
        -- TODO: in 1.10.3 will be `new = new:update({{ '=', 'data.mtime', fiber.time64() }})`
        new = new:update{{'=', data_field, data}}
        return new 
    end 
end
```

(The comment is about #1261.)

`data` contains heavily nested structure and it is truncated to 16 levels of nesting in box.tuple.update(), because it uses msgpackffi:

https://github.com/tarantool/tarantool/blob/6277f48ad8a7213d73e280d5046c5b5872f74e25/src/box/lua/tuple.lua#L229-L240

https://github.com/tarantool/tarantool/blob/6277f48ad8a7213d73e280d5046c5b5872f74e25/src/box/lua/tuple.lua#L71-L93

https://github.com/tarantool/tarantool/blob/6277f48ad8a7213d73e280d5046c5b5872f74e25/src/lua/msgpackffi.lua#L7

I think msgpackffi should follow the default serializer options.

Then I use `:tomap()` to decode a tuple to a table, update it in Lua and use `box.tuple.new()` to encode it back (a before_replace trigger does not allow to return a Lua table as a result). After that I observed that `box.tuple.new(new)` with one argument (new convention) uses tuple_serializer and doesn't use the default serializer (`luaL_msgpack_default`). However, say, `box.tuple.new(1, new)` (old convention) will use the default serializer and will not truncate data (if it encode_max_depth is configured so from Lua):

https://github.com/tarantool/tarantool/blob/6277f48ad8a7213d73e280d5046c5b5872f74e25/src/box/lua/tuple.c#L110-L123

This is the second problem: `box.tuple.new(tuple)` truncates data to 32 levels of nesting. I think `tuple_serializer` should follow the default serializer options.

There is a third problem: when, say, msgpack.cfg({encode_max_depth = 1024}) is set, msgpack.cfg.encode_max_depth will show 32, however the new limit works fine.

I had worked around all that problems in this way:

```diff
 function triggers.set_mtime64(data_field)
     return function(_, new)
         if new == nil then return new end
+        new = new:tomap()
         local data = new[data_field]
         data.mtime = fiber.time64()
         -- TODO: in 1.10.3 will be `new = new:update({{ '=', 'data.mtime', fiber.time64() }})`
-        new = new:update{{'=', data_field, data}}
-        return new
+        return box.tuple.new(1, 2):transform(1, 2, unpack(new))
     end
 end
```

However it would be good to fix them in tarantool.

**Comment by Totktonada** [comment]
BTW, I think it is not good to silently crop data when a nesting level exceeds some threshold. It is better to report an error. See also https://github.com/tarantool/tarantool/issues/4366#issuecomment-512654118

**Comment by Totktonada** [comment]
See also #927.

**Comment by Totktonada** [comment]
Changed `box.tuple.new():transform(1, 0, unpack(new))` to `box.tuple.new(1, 2):transform(1, 2, unpack(new))`, because positioning on 1st field having zero fields seems not being correct. See #4460.

**Comment by Gerold103** [comment]
Not sure about why msgpackffi should use msgpack default serializer. 1) They are different modules, 2) The default serializer is documented to affect box API, but msgpackffi is not box.

**Comment by Gerold103** [comment]
On the other hand it is documented as such only in our source code. In the public doc is it just a configuration, not bound to box.

**Comment by Totktonada** [comment]
> Not sure about why msgpackffi should use msgpack default serializer. 1) They are different modules, 2) The default serializer is documented to affect box API, but msgpackffi is not box.

But when msgpackffi is used to perform an update operation, it should follow at least encode_max_depth option, because `box.tuple.update()` is the part of box.

> On the other hand it is documented as such only in our source code. In the public doc is it just a configuration, not bound to box.

It should be fixed in some way; possible options are:

* Make box.tuple.new() and box.tuple.update() always follow msgpack.cfg options.
* Perform the same, but provide more obvious way to configure box's encoder; detach box's encoder from msgpack one.

Both ways make things consistent. Despite our choose we should document how to configure default box's encoder.

Also I would seriously consider whether we should silently crop user's data. This looks as inappropriate behaviour for a database / an appserver. I would change the action to giving an error by default at least for box's functions (but better for all msgpack/json/yaml encoders/decoders). They only thing where such trimming can be appropriate is logging and it would be better to let a user to enable it explicitly.

**Comment by Gerold103** [comment]
Ok, I have a patch which makes msgpackffi use encode_max_dept of the msgpack serializer. Other options are still ignored, and I guess that should be fixed too.
Talking of crop - perhaps we could add a new option for serializer like 'encode_crop_too_deep' or something like that. It would be 'false' by default and will lead to an error.
