### ISSUE TITLE
sql: old savepoint is not erased in case of name collision 

### ISSUE THREAD

**Issue by Korablev77** [tarantool/tarantool#4443]
Now it is allowed to create several savepoints with the same name:

```
START TRANSACTION;
SAVEPOINT sv1;
SAVEPOINT sv1; -- no error occurs
```
However, they still both exist:

```
SAVEPOINT RELEASE sv1;
SAVEPOINT RELEASE sv1;
```
On the other hand, our doc says that savepoint with the same name should be erased (I don't like word 'released' since release of savepoint (I mean in terms of `SAVEPOINT RELEASE `statement) also removes all created after given savepoints):

> If a savepoint with the same name already exists, it is released before the new savepoint is set.

This is also what should be done in accordance with SQL ANSI:

> 17.5 \<savepoint statement\>
> 
> 1) Let S be the \<savepoint name\>.
> 2) If S identifies an existing savepoint established within the current
>    savepoint level, then that savepoint is destroyed.

**Comment by kyukhin** [comment]
Closed by 03cbc36
