### ISSUE TITLE
Clear a readline state during abnormal termination

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#4466]
Tarantool version: 2.3.0-90-g51d8e4c35.
OS version: Linux.

Before 1bc1fcdad40e17365617531cf0e3aebaefa18e6a tarantool clears a readline state even after an abnormal termination using an atexit() callback. Now it is possible that tarantool left a terminal in a bad state and `reset` command is needed to clear it. I have two examples to show this behaviour (I tested both typing them in the interactive console):

The first one comes from #4154:

```lua
loadstring = nil
```

The second is from #4138:

```lua
box.cfg{log = 'syslog:server=non_exists_hostname:3301'}
```

**Comment by Gerold103** [comment]
Sorry @sergepetrenko, I didn't notice that you were assigned earlier.
