### ISSUE TITLE
Adopt luavela test suites (ARM64)

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#4473]
Luavela went public and it contains lots of tests.

Need to merge them into Tarantool.

Make it carefully, keeping track of issues fixed.

---

The actual list of suites to be borrowed after #4862 is implemented:
* [x] #4064
* [x] #5845
* [x] #5844

Follow-ups for next milestone:

* [x] #5970
* [x] #5870

**Comment by Totktonada** [comment]
See also #4064.

**Comment by ligurio** [comment]
Exact list of testsuites:

- [Lua-Harness](https://fperrad.frama.io/lua-Harness/)
- [Lua testsuite](https://www.lua.org/tests/)
- [LuaJIT suite](https://github.com/tarantool/tarantool/issues/4064?)
- [Lua-TestMore](https://fperrad.frama.io/lua-TestMore/)
- LuaVela unit and functional tests

**Comment by igormunkin** [comment]
@ligurio, thanks, I moved everything to the issue! Just a couple nits to your list:

> Exact list of testsuites:
> 
>   * [Lua-Harness](https://fperrad.frama.io/lua-Harness/)
> 
>   * [Lua testsuite](https://www.lua.org/tests/)
> 
>   * [LuaJIT suite](https://github.com/tarantool/tarantool/issues/4064)
> 
>   * [Lua-TestMore](https://fperrad.frama.io/lua-TestMore/)

AFAICS, this is the same as lua-Harness.

> 
>   * LuaVela unit and functional tests
>

I doubt we need this one: it contains tests for new features in uJIT but ours are tested in scope of [original "Tarantool" suite](https://github.com/tarantool/luajit/tree/tarantool/test).

Besides, there is one more left: [CERN-MAD-tests](https://github.com/luavela/luavela/tree/master/tests/lang/CERN-MAD-tests). I added this to the description.

**Comment by Buristan** [comment]
I consider this issue can be closed as done as far as:
1) All test suites except MAD are on-boarded
2) Both: tarantool and luajit fork CI run these tests

MAD tests should be adopted separately due to Lua implementation used by the project offers some non-standard syntax sugar. Also, we need to update lua-Harness and tune our test runner (in cmake files and <luajit-test-init.lua>).
