### ISSUE TITLE
Add proxy server support to http.client

### ISSUE THREAD

**Issue by msiomkin** [tarantool/tarantool#4477]
There's no way to configure http.client in code to use a proxy server. It makes difficult using Tarantool from large companies' LANs. We faced this issue while working on GPN's project.

What's more the behaviour of http.client may be accidentally affected by system-wide proxy settings in environment variables. This may be undesirable. And again there's no way to prevent it in code (overriding it by application-specific settings or explicitly disabling using a proxy). See https://github.com/tarantool/doc/issues/663

We need to add support of the following curl options to http.client module:

CURLOPT_PROXY
CURLOPT_PROXYPORT
CURLOPT_PROXYUSERPWD
CURLOPT_NOPROXY

PR: https://github.com/tarantool/tarantool/pull/4472

**Comment by kyukhin** [comment]
Done.

**Comment by lenkis** [comment]
Doc ticket: https://github.com/tarantool/doc/issues/896
