### ISSUE TITLE
Consider support of space / index names in the binary protocol

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#4479]
Currently tarantool adds an incremental schema id to responses, allows to set a client's schema id for requests and gives an error for a request with a non actual schema id. This allows connectors to determine the situation when a request was made against an old schema, fetch the new one, map space / index names to ids and then retry the request. This however complicates a connector code, especially if it support asynchronous requests: the many situations need to be handled, say, a schema can be updated during a schema fetch.

For ones who interesting: we had discussed some corner cases in https://github.com/tarantool/tarantool-java/pull/200

It seems logical to eliminate this complexity and allow to send requests with index / space names. We already allow to use field names for update/upsert operations (it is the part of #1261) in the binary protocol and they are part of a schema (AFAIU).

The main point here is that we have many connectors and an ability to make them easier is something valuable: at least it saves developers from stepping into possible mistakes with handling corner cases, performing synchronization and retrying of requests.

Are there any pitfalls in the proposed feature?

**Comment by rybakit** [comment]
What will happen to the schema id once this is implemented?

**Comment by Totktonada** [comment]
In the proposal I assumed that it will be supported anyway.

**Comment by rybakit** [comment]
Apart from the reducing complexity, I think that this feature might be useful for short-living scripts that do not persist information across runs (this is especially true for PHP with its stateless execution model). So they don't waste resources by fetching schema to just make one or two requests and die.

**Comment by CuriousGeorgiy** [comment]
Superseeded by #8146.
