### ISSUE TITLE
Bump luarocks version

### ISSUE THREAD

**Issue by olegrok** [tarantool/tarantool#4481]
Current luarocks version produce such errors:
![image](https://user-images.githubusercontent.com/8830475/64542982-2046a300-d32d-11e9-8f38-4ded44bdfce8.png)

Problem was fixed here https://github.com/tarantool/luarocks/commit/06a657e7a68dd475e2afb5a56012c43f3a906640, also this fix was merged into luarocks upstream https://github.com/luarocks/luarocks/pull/1056

**Comment by Totktonada** [comment]
See https://github.com/luarocks/luarocks/issues/1049 for more detailed description of the problem.

**Comment by Totktonada** [comment]
The is subject for master and 2.2 branches, where luarocks-3.1.1 is used.
