### ISSUE TITLE
I am getting this erroe on  my Mac osx 10.11.6 el capitan: dyld: Symbol not found: _clock_getres   Referenced from: /usr/local/bin/mongo (which was built for Mac OS X 10.12)   Expected in: /usr/lib/libSystem.B.dylib  in /usr/local/bin/mongo. I am trying to get the mongo db shell up and running on my MAC

### ISSUE THREAD

**Issue by githubjack** [tarantool/tarantool#4483]
Tarantool version:

OS version:

Bug description:

Steps to reproduce:

Optional (but very desirable):
* coredump
* backtrace
* netstat

**Comment by githubjack** [comment]
I have been getting this error which has halted all task as I cannot move until this is sorted. Can someone please help.

**Comment by Gerold103** [comment]
This is not mongo. It is tarantool, a different database. You need to go to mongo repository.

**Comment by afsheen-01** [comment]
how do i navigate back to mongo repository? from tarantool?

**Comment by kyukhin** [comment]
I guess there's no way to leave Tarantool for mongo.

**Comment by Mons** [comment]
> how do i navigate back to mongo repository? from tarantool?

Sorry, no way back. Now learn Tarantool.
