### ISSUE TITLE
fio: "open" returns error as cdata

### ISSUE THREAD

**Issue by olegrok** [tarantool/tarantool#4489]
```lua
Tarantool Enterprise For Mac 2.2.1-13-g8bfcb4422
type 'help' for interactive help
tarantool> fio = require('fio')
tarantool> fio.open('test', { 'O_CREAT', 'O_WRONLY', 'O_APPEND' }, tonumber('644', 8))
---
- null
- 'fio: Permission denied'
...

tarantool> r, e = fio.open('test', { 'O_CREAT', 'O_WRONLY', 'O_APPEND' }, tonumber('644', 8))
tarantool> e
---
- 'fio: Permission denied'
...

tarantool> type(e)
---
- cdata                    -- expected string
...

tarantool> e .. 'something'
---
- error: '[string "return e .. ''something''"]:1: attempt to concatenate ''struct error''
    and ''string'''
...
```

Follow-up: https://github.com/tarantool/tarantool/pull/4044

Please, check that all fio functions return error as string

**Comment by Totktonada** [comment]
It is box.error object and you can, say, look into a lua backtrace with e.trace. Sooner or later we should use it for all errors that comes from tarantool I think. See also #4398.

**Comment by olegrok** [comment]
Could we redefine `__concat` for this object?

**Comment by olegrok** [comment]
@Totktonada 

I propose following patch to close this issue

```patch
From 55b2fd6983d415f8924c10ecf1949db1f1ae6e9f Mon Sep 17 00:00:00 2001
From: Oleg Babin
Date: Wed, 11 Sep 2019 18:53:56 +0300
Subject: [PATCH] error: Add __concat method to error object

Usually functions return pair {nil, err} and user expects that err is string.
Let's make the behaviour of error object closer to string
and define __concat metamethod.

Closes tarantool/tarantool#4489
---
 src/lua/error.lua | 8 ++++++++
 1 file changed, 8 insertions(+)

diff --git a/src/lua/error.lua b/src/lua/error.lua
index 28fc0377d..b44fab7b6 100644
--- a/src/lua/error.lua
+++ b/src/lua/error.lua
@@ -150,9 +150,17 @@ local function error_index(err, key)
     return error_methods[key]
 end
 
+local function error_concat(lhs, rhs)
+    if lhs == nil or rhs == nil then
+        error("attempt to concatenate struct error and nil")
+    end
+    return tostring(lhs) .. tostring(rhs)
+end
+
 local error_mt = {
     __index = error_index;
     __tostring = error_message;
+    __concat = error_concat;
 };
 
 ffi.metatype('struct error', error_mt);
-- 
2.22.0

```

That do you think about it?

**Comment by Totktonada** [comment]
I would say that it should not allow more then a string: say, `'' .. box.NULL` gives an error, so `box.error.new(box.error.CFG, 'foo', 'bar') .. box.NULL` should too. At the first glance it looks that we should allow only an error as the first argument and a string, a number or an error as the second one.

I think it is harmless, so I'm okay in general.

**Comment by olegrok** [comment]
https://www.freelists.org/post/tarantool-patches/PATCH-error-Add--concat-method-to-error-object

**Comment by olegrok** [comment]
https://lists.tarantool.org/pipermail/tarantool-patches/2019-November/012341.html

**Comment by Totktonada** [comment]
@kyukhin If it is considered as a bug, then it worth to set 1.10.6 milestone?

**Comment by Totktonada** [comment]
Fixed in:

* [2.4.0-10-g935db1736](https://github.com/tarantool/tarantool/commit/935db173643186e1c5585c1de59a34d1fd0d5cda)
* [2.3.1-10-ga078005de](https://github.com/tarantool/tarantool/commit/a078005dec5eb4a24584188116cdcfe07b82e3ec)
* [2.2.2-12-gae1bf8a4f](https://github.com/tarantool/tarantool/commit/ae1bf8a4f5a1b0f4e92cac841e110492539dc8bf)
* [1.10.5-4-g6606120a7](https://github.com/tarantool/tarantool/commit/6606120a7282bf3ff2c204ca4c8663fabf9af7fb)

**Comment by olegrok** [comment]
I've changed issue title - to clarify that was done in fact
