### ISSUE TITLE
FreeBSD compilation failing due to curl dependencies

### ISSUE THREAD

**Issue by v-izmalkov** [tarantool/tarantool#4490]
Tarantool version:
2.2.1-51-g22a6375fb
OS version:
FreeBSD 12.0-RELEASE
Bug description:
Errors preventing building from source codes. See attached screenshot for details.

Steps to reproduce:
On a fresh installed FreeBSD (used VirtualBox 6 6.0.10 r132072 (Qt5.6.3)) i followed instructions, provided in [user's manual](https://www.tarantool.io/en/doc/2.2/dev_guide/building_from_source/)

1. Installed all dependencies (except py27-msgpack-python - there is no available package with such name - installed py27-msgpack instead, and made sure to use pip-2.7 install requirements.txt later by instructions)
```
pkg install -y sudo git cmake gmake gcc coreutils \
autoconf automake libtool \
readline ncurses libyaml openssl libunwind icu \
python27 py27-pip py27-setuptools py27-daemon \
py27-msgpack py27-yaml py27-argparse py27-six py27-gevent
```
then used 
```
pip install -r \
https://raw.githubusercontent.com/tarantool/test-run/master/requirements.txt \
--user
```
Also installed git and nano.
And added my current user to sudoers.

2. Used git clone:
`git clone --recursive https://github.com/tarantool/tarantool.git -b 2.2 ~/tarantool`
(i have to add, that i have tried branches `2.1` and `master` with the same effect)

3. Used git submodule update from cloned directory
```
cd tarantool
git submodule update --init --recursive
```
4. Prepare

```
make clean
rm CMakeCache.txt
cmake .

```
5. Build

`gmake`

And getting erros (to be seen on screenshot and in provided console logs).
<img width="1081" alt="Снимок экрана 2019-09-11 в 12 35 53" src="https://user-images.githubusercontent.com/54984326/64697227-0631cf80-d4a9-11e9-90f2-16ce87cd4d61.png">

Optional (but very desirable):
* coredump Not Avaliable
* backtrace Not Avaliable
* netstat Not Avaliable
Console logs - [2.txt](https://github.com/tarantool/tarantool/files/3601395/2.txt)

**Comment by avtikhon** [comment]
The additional package helps:
sudo pkg install openssl111-1.1.1d

**Comment by avtikhon** [comment]
Also be noticed that the installation of the openssl may rollback 111 to 102, like here:
```
gmake -f .travis.mk test_freebsd
sudo pkg install -y git cmake gmake gcc coreutils \
	readline ncurses libyaml openssl libunwind icu \
	python27 py27-pip py27-setuptools py27-daemon \
	py27-yaml py27-argparse py27-six py27-gevent \
	gdb bash autoconf automake libtool
Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
All repositories are up to date.
Checking integrity... done (1 conflicting)
  - openssl-1.0.2t,1 conflicts with openssl111-1.1.1d on /usr/local/bin/c_rehash
Checking integrity... done (0 conflicting)
The following 2 package(s) will be affected (of 0 checked):

Installed packages to be REMOVED:
	openssl111-1.1.1d

New packages to be INSTALLED:
	openssl: 1.0.2t,1

Number of packages to be removed: 1
Number of packages to be installed: 1

The operation will free 1 MiB.
[1/2] Deinstalling openssl111-1.1.1d...
[1/2] Deleting files for openssl111-1.1.1d: 100%
[2/2] Installing openssl-1.0.2t,1...
[2/2] Extracting openssl-1.0.2t,1: 100%
Message from openssl-1.0.2t,1:

Edit /usr/local/openssl/openssl.cnf to fit your needs.
cmake . -DCMAKE_BUILD_TYPE=RelWithDebInfo -DENABLE_WERROR=ON 
-- Enabling LTO: FALSE
-- OpenSSL 1.0.2t found
-- 
```
to avoid of it the following patch we'll have for out testing:
```
diff --git a/.travis.mk b/.travis.mk
index a816d17db..15be62194 100644
--- a/.travis.mk
+++ b/.travis.mk
@@ -164,7 +164,7 @@ test_osx: deps_osx test_osx_no_deps
 
 deps_freebsd:
        sudo pkg install -y git cmake gmake gcc coreutils \
-               readline ncurses libyaml openssl libunwind icu \
+               readline ncurses libyaml openssl111 libunwind icu \
                python27 py27-pip py27-setuptools py27-daemon \
                py27-yaml py27-argparse py27-six py27-gevent \
                gdb bash autoconf automake libtool
```

**Comment by v-izmalkov** [comment]
i can confirm, executing 
`sudo pkg install openssl111-1.1.1d `
fixed the issue - i was able to complete the building from source codes on the test FreeBSD environment.
