### ISSUE TITLE
Vinyl: index lookup dramatically degraded after some deletions from space

### ISSUE THREAD

**Issue by andrew-statsenko** [tarantool/tarantool#4501]
Tarantool version:
tarantool-1.10.3.79

OS version:
CentOS7

Bug description:

Index lookup on vinyl spaces dramatically degraded after some deletions from space with warning:

`warning>       main/152710576/main vinyl.c:3739 W> 559/2: select(["93cb92c8-aa5a-4b92-88c5-95a4b838c9f2", "ru"], EQ) => ["93cb92c8-aa5a-4b92-88c5-95a4b838c9f2", "e784a300-00a3-e93c-5a00-31731df402d0", 407672617, 0.75, 1, null, null, 59.7929, 30.5527, 49, "ru", 1568376137, 1, null, 2146] took too long: 323.909 sec
`
Steps to reproduce:
 - create space with secondady indices
 - inset 1-10M tuples into vinyl space
 - delete some (10-30%) keys from space
 - lookup tuple from secondary index

**Comment by sergos** [comment]
Reproduced. Test attached.
The problem can cause another case: if a replica syncing from master and replaying an xlog, then it will intermittently receive UPDATE and DELETE. This will cause the slowdown and during the sync there are no compactions. The slowdown will grow and sync will delay more and more. 
@Korablev77 will look into the issue
[test.lua.zip](https://github.com/tarantool/tarantool/files/4154256/test.lua.zip)

**Comment by sergos** [comment]
After adding to the test yet another step:
```
i2:drop()
i2=space:create_index('user_scene_mtime_id', {type = 'tree',parts = {'user_id', 'scene_id', 'mtime', 'id'}})

for i=1,test_repeat*5 do
    print("benching test after secondary index drop/create: ", clock.bench(test)[1])
end
```

I got the:
```
2020-02-05 23:56:50.240 [7769] main/101/test.lua vinyl.c:3739 W> 512/1: select(["e85c9dc5-16a7-4bfd-8532-f0a94051638c", 1, 1, 123140], GT) => <NULL> took too long: 23.567 sec
benching test after primary index compaction: 	37.562684
benching test after secondary index drop/create: 	1.1999999998125e-05
benching test after secondary index drop/create: 	3.999999989901e-06
benching test after secondary index drop/create: 	3.999999989901e-06
benching test after secondary index drop/create: 	4.0000000183227e-06
benching test after secondary index drop/create: 	3.999999989901e-06
```

**Comment by pnvasanth** [comment]
Hi, we are also having same issue. could you please let me know when can we expect the fix? 
Also is there any workaround for the time being? Thanks.

**Comment by sergos** [comment]
Hi! The fix has no exact ETA unfortunately.
The best workaround so far is to run compaction ```compact(<your primary index here>)``` regularly, or after a number of deletions in the space. To say exact number of deletion is hard, you have to balance depending on your load.

**Comment by naimulhaider** [comment]
@sergos What's the progress on this? I'm facing the same issue. Is there an ETA now?

**Comment by sergos** [comment]
Sorry, focused on other activities so far.
Could you share some on the project you're using Tarantool for? It might help to rise the priority for the bug.

**Comment by naimulhaider** [comment]
I work at Lockwood Publishing, the job of my tarantool cluster is to ingest streams of data (around 1000s of records per second) and stores it in vinyl. There is an indexpiration worker that removes data that's not required anymore (older than 7 days for example), and the problem occurs when indexpiration queries the data after deletes. It seems to take minutes to fetch a single record from Vinyl.

**Comment by sergos** [comment]
Ok, is workaround applicable? Since indexpiration is a once-per-day(?) you can simply accompany it with a compaction of your primary index. Will it work for you?

**Comment by locker** [comment]
The problem is in the "deferred delete" optimization: DELETE statements aren't written to secondary indexes so even if a tuple is present in a secondary index, it may still be deleted; to check this, we have to look it up in the primary index, which slows down secondary index scan. We will disable the optimization by default for now and add an option to enable it. We will also investigate if there are ways to mitigate the problem without disabling the optimization (e.g. trigger compaction when there are too many deferred DELETE statements).
