### ISSUE TITLE
Recursion assertion

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#4504]
I have Ubuntu 18.04. I have tarantool-master, pulled from source today.
I execute these requests:
```
box.schema.func.create('_C',
      {language = 'LUA',
       returns = 'string',
       body = [[
function (i)
   print(i)
   local m = box.space._space:select()
   return 0
end
]],
       param_list = {'integer'},
       exports = {'LUA', 'SQL'},
       is_sandboxed = false,
       is_deterministic = true})
box.execute([[
WITH RECURSIVE x AS
(
 SELECT 0 AS q, 1
 UNION ALL
 SELECT q+1, _c(q) FROM x WHERE q < 1
)
SELECT * FROM x;
]])
```
The result is:
```
0
tarantool: /home/pgulutzan/tarantool-master/src/lib/small/small/region.c:75: region_truncate: Assertion `region_used(region) >= used' failed.
Aborted (core d
```

**Comment by Korablev77** [comment]
Query which results in crash due to the same basic reason:
```
CREATE TABLE ts (s1 INT PRIMARY KEY);
INSERT INTO ts VALUES (1), (2), (3);

WITH RECURSIVE w AS ( SELECT s1 FROM ts UNION ALL SELECT s1+1  FROM w WHERE s1 < 4) SELECT _c(s1) FROM w;
Assertion failed: (region_used(region) >= used), function region_truncate, file /Users/n.pettik/tarantool/src/lib/small/small/region.c, line 75.
Abort trap: 6
```

**Comment by pgulutzan** [comment]
Apparently this is fixed. I need to say returns = 'unsigned' instead of returns = 'string', which is okay. Anyway, there is no assertion in 2.7 or 2.6 or 2.5. There is still an assertion in 2.4. I also tried the code for the _COLUMNS view https://www.tarantool.io/en/doc/latest/reference/reference_sql/sql_plus_lua/#columns-view for which I earlier had to say "Warning: Use this code only with Tarantool version 2.3.2 or later. Use with earlier versions will cause an assertion. See Issue#4504." That is fixed too.
