### ISSUE TITLE
SQL convert INT to "string date"

### ISSUE THREAD

**Issue by zilveer** [tarantool/tarantool#4509]
Tarantool version:
Tarantool 2.2.1-6-g109a304d6

OS version:
Debian 9

Bug description:
Is there anyway upon making a `SELECT` query and convert an `INTEGER` column to string?

For instance I would like to convert the column `created_at` according to this pseudo code:

```
if (created_at == "today")
 return (Hour:min:sec of created_at column) -- 14:37
else
 return (Month (number) / day (number) Hour:min of created_at column) -- 9/17 14:37
```

Steps to reproduce:
See above

Thanks for any feedback.
Regards Zilveer

**Comment by Korablev77** [comment]
There are several ways to do so. If you want to simply convert integer to string, you can use CAST operator: `SELECT CAST(int_column AS STRING);` You can combine it with `CASE-THEN` clause. For instance: `SELECT CASE str_column WHEN 'today' THEN CAST(str_column AS INTEGER) ELSE ...;` If you have to provide any complex manipulations, you can register user-defined Lua function and use it inside query. For example (note that there's no native support of date-time in Tarantool):
```
box.schema.func.create('str_to_date',{language = 'LUA', returns = 'string', body = [[ function (i) local str = tostring(i) return str end]],
param_list = {'integer'}, exports = {'LUA', 'SQL'},is_sandboxed = false, is_deterministic = true})

box.execute("SELECT \"str_to_date\"(str_column) FROM ...;")
```
Btw you can ask any questions in our telegram channel: https://telegram.me/tarantool

**Comment by zilveer** [comment]
@Korablev77 thank you for the feedback.

Is there any native way or a performance way of actually returning created_at as string of "H:m:s" if the timestamp is from today else return "M/d H:m:s".

I can see that I can use Lua for this purpose but is there any other SQL functions for doing it by using CASE ...WHEN ?
I am still new to Tarantool and try to learn all the built in functionalities to make it work for my needs.

BTW I love this damn blazing Database Tarantool !

Thanks for all hard work !
Regards Zilveer

**Comment by zilveer** [comment]
Any help on this would be appreciated

**Comment by Korablev77** [comment]
Unfortunately, there's no such built-in functionality. You can refer to SQL documentation to examine all available pre-defined function: https://www.tarantool.io/en/doc/2.2/reference/reference_sql/sql/#functions
