### ISSUE TITLE
netbox connection converts tuple to table type, but netbox.self is not

### ISSUE THREAD

**Issue by RunsFor** [tarantool/tarantool#4513]
**Tarantool version:**

Tarantool Enterprise For Mac 2.2.1-13-g8bfcb4422

**OS version:**

MacOS Mojave 10.14.6 (18G95)

**Bug description:**

There is a statement in [documentation](https://www.tarantool.io/en/doc/2.2/reference/reference_lua/net_box/#lua-function.net_box.new), that netbox connection, and netbox.self can be interchangable:

> For a local Tarantool server, there is a pre-created always-established connection object named net_box.self. Its purpose is to make polymorphic use of the net_box API easier. Therefore conn = net_box.connect('localhost:3301') can be replaced by conn = net_box.self.

Turns out, its not:

```
localhost:3302> box.space.test:insert({1})
---
- [1]
...
localhost:3302> type(require('net.box').connect('admin:password@localhost:3302'):eval("return box.space.test:get{1}"))
---
- table
...

localhost:3302> type(require('net.box').self:eval("return box.space.test:get{1}"))
---
- cdata
...
```

This may lead to unobvious behaviour when trying to optimise rpc calls in distributed applications, i.e. [`cartridge.rpc`](https://github.com/tarantool/cartridge/blob/master/cartridge/rpc.lua)

**Comment by olegrok** [comment]
I think solution should cover not only `struct tuples` but also another cdata objects. E.g. `box.error` - netbox.self returns cdata, remote connection returns string
