### ISSUE TITLE
build: GCC 9 warning on strncpy()

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#4515]
Tarantool version: 2.3.0-117-g4c2d1eff2.
OS version: Linux.

Ensure that GCC 9 is default one and run:

```sh
cmake . -DCMAKE_BUILD_TYPE=RelWithDebInfo -DENABLE_BACKTRACE=ON -DENABLE_DIST=ON -DENABLE_WERROR=ON && make -j
```

This will give the following warning (that is treated as an error with -DENABLE_WERROR=ON).
```
In file included from /usr/include/string.h:494,
                 from /home/alex/p/tarantool-meta/r/tarantool/src/systemd.c:39:
In function ‘strncpy’,
    inlined from ‘systemd_notify’ at /home/alex/p/tarantool-meta/r/tarantool/src/systemd.c:120:2:
/usr/include/bits/string_fortified.h:106:10: error: ‘__builtin_strncpy’ specified bound 108 equals destination size [-Werror=stringop-truncation]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```

The line that causes the error is the following:

```c
strncpy(sa.sun_path, sd_unix_path, sizeof(sa.sun_path));
```

The line was added in a81aaa6ce7e1b79ca2bc92ca9314b3794bd3334d (1.7.3-674-ga81aaa6ce).

It is used then here:

```c
ssize_t sent = sendto(systemd_fd, message, (size_t) strlen(message),
        flags, (struct sockaddr *) &sa, sizeof(sa));
```

**Comment by Totktonada** [comment]
> In addition, some implementations don't require a null terminator
> when binding a socket (the addrlen argument is used to determine the
> length of sun_path) and when the socket address is retrieved on these
> implementations, there is no null terminator in sun_path.

http://man7.org/linux/man-pages/man7/unix.7.html

So the code itself looks okay and we need to suppress the warning.

**Comment by igormunkin** [comment]
@Totktonada, I suggest taking a look on the way this false positive warnings are suppressed [here](https://github.com/iponweb/luavela/blob/master/src/uj_proto.c#L416).

**Comment by Totktonada** [comment]
OTOH, it is known that we can left a unix path w/o a terminator on Linux. But what about FreeBSD and Mac OS? (See related articles [here](https://www.synack.com/blog/two-bugs-one-func/) and [here](https://www.synack.com/blog/two-bugs-one-func-p2/).)

Related: #4634.
