### ISSUE TITLE
sql query result is tuple with empty fields

### ISSUE THREAD

**Issue by bronya100** [tarantool/tarantool#4517]
Tarantool version:  2.2.1-26-g75b14a3
OS version: Oracle Linux Server release 7.7
Bug description: sql query result is tuple with empty fields
Steps to reproduce:
this request with error
select *, max("minsum") from "promocodes1" where "action_dt" = null 
or the same requests without error with condition on field {is_nullable=true} produces results like this
 [null, null, null, null, null, null, null, null, null, null, null]

**Comment by Korablev77** [comment]
Could you please provide schema for this query? Also note that comparison with null always returns null:
```
tarantool> select 1 = null
---
- metadata:
  - name: 1 = null
    type: boolean
  rows:
  - [null]
...
```
If you are willing to point out whether value is really null or not, you should use IS NULL predicate:
```
tarantool> select 1 is null
---
- metadata:
  - name: 1 is null
    type: boolean
  rows:
  - [false]
...
tarantool> select null is null
---
- metadata:
  - name: null is null
    type: boolean
  rows:
  - [true]
...
```

**Comment by bronya100** [comment]
box.schema.space.create( s, { if_not_exists = true, engine = 'memtx' } )
			box.space[s]:format({
				{name='id', type='unsigned'},
				{name='import_dt', type='unsigned'},
				{name='code', type='string'},
				{name='minsum', type='unsigned'},
				
				{name='status', type='unsigned'},
				{name='action_dt', type='unsigned',is_nullable=true},
				
				{name='order_guid', type='string',is_nullable=true},
				{name='order_id', type='string',is_nullable=true},
				{name='order_type_id', type='unsigned',is_nullable=true},
				{name='order_type', type='string',is_nullable=true},
				
				{name='rest_id', type='string',is_nullable=true},
				{name='table_id', type='string',is_nullable=true},
				{name='station_id', type='string',is_nullable=true},
			})
			box.space[s]:create_index('pk',{type = 'TREE', sequence='g'})
			box.space[s]:create_index('dt',{parts={'import_dt'}, unique = false})
			box.space[s]:create_index('minsum',{parts={'minsum'}, unique = false})
			box.space[s]:create_index('status',{parts={'status'}, unique = false})
			box.space[s]:create_index('order_guid',{parts={'order_guid'}, unique = false})
			box.space[s]:create_index('action_dt',{parts={'action_dt'}, unique = false})

**Comment by pgulutzan** [comment]
This is the result that we expect, if there are no rows where "action_dt" = null is true. When a list of nonaggregate columns and an aggregate function are in the select list, Tarantool has a choice of throwing an error (which is what at least one other DBMS does but Tarantool is not always strict), or returning zero rows (but there is a row for the aggregate function), or returning NULLs both for the nonaggregate columns and the aggregate function (which is what at least one other DBMS does if non-default settings are used).
