### ISSUE TITLE
key_def: allow to create key_def instance using index definition

### ISSUE THREAD

**Issue by olegrok** [tarantool/tarantool#4519]
Currently to create key_def we use: `box.space[space_name].index[index_name].parts`. To get "parts" you should access to space directly.

However sometimes it's needed to compare tuples on remote host. In this case more native is to allow to use index definition (options from create_index function) to create key_def instance.

Information from create_index can be easily distributed between nodes in cluster without physically creation this index

**Comment by Totktonada** [comment]
I don't get your idea. Just to save `.parts` in user's code?

**Comment by olegrok** [comment]
DDL is part of configuration that I can distribute between instanses

`index.parts` is "property" of space's index. And my point is to allow to use configuration to compare tuples (on remote host  primary). But mainly yes, instead of construction key_def by hand

**Comment by olegrok** [comment]
`box.space.test:create_index('test', {parts = {{field = 1, type = 'unsigned'}}})` - to create space

`{{fieldno = 1, type = 'unsigned'}}` - to create key_def instance

It's not consistent I think, let's support field in key_def.new or fieldno in create_index

**Comment by Totktonada** [comment]
`fieldno` is from net.box space object. We should support `field` too.

**Comment by Totktonada** [comment]
Let's consider it as the bug and only add support of `field`. I think it should be done in all supported tarantool versions.

**Comment by Totktonada** [comment]
Now I see: local space object has `fieldno` too. While it receives `field` as input for index parts. Ugh.

**Comment by olegrok** [comment]
There are several methods to create index:

First:
`space:create_index('name', {parts = {{1, 'unsigned'}, {2, 'string', is_nullable=false}}})`

Second:
`space:create_index('name', {parts = {{field=1, type = 'unsigned'}, {field = 2, type = 'string', is_nullable=false}}})`

@Totktonada said that first variant is obsolete and it was introduces event before `is_nullable` option was added. Now it looks too strange and inconsistent to use index definition as array with string keys.

@kyukhin 
Let's deprecate first variant and remove it in next versions.
