### ISSUE TITLE
Misguided error messages in tarantoolctl rocks search

### ISSUE THREAD

**Issue by v-izmalkov** [tarantool/tarantool#4529]
Tarantool version:
Tarantool 2.2.1-3-g878e2a42c
OS version:
Alpine Linux v3.5 (docker run tarantool/tarantool:2.2)
Bug description:
While searching around rocks installation issues, I have tried 
`tarantoolctl search`
to see what it does with no parameters set.
Expected to either have an error or get a full list.
The result is:
```
/opt/tarantool # tarantoolctl rocks search

Error: Enter name and version or use --all. See Tarantool documentation for help.
```
OK now, I have tried the proposed option:
```
/opt/tarantool # tarantoolctl rocks search --all
builtin/internal.argparse.lua:142: unknown options: all
```
This leads to an error. 
I believe there shall be a full available rocks list OR there shall not be the suggestion to use -all flag (i have not found a proper way to use it anyway).
Steps to reproduce:
```
docker run -it tarantool/tarantool:2.2 /bin/sh
tarantoolctl rocks search
tarantoolctl rocks search -all
```
Optional (but very desirable):
* coredump -no
* backtrace -no
* netstat -no

**Comment by v-izmalkov** [comment]
The same command `tarantoolctl rocks search` in Tarantool 1.10.3-107-g17db27170 shows a long list of rocks and versions.

**Comment by olegrok** [comment]
> The same command `tarantoolctl rocks search` in Tarantool 1.10.3-107-g17db27170 shows a long list of rocks and versions.

tarantoolctl rocks 1.x is based on luarocks 2
tarantoolctl rocks 2.2+ is based on luarocks 3

Related PR: https://github.com/tarantool/tarantool/pull/4207

**Comment by v-izmalkov** [comment]
> > The same command `tarantoolctl rocks search` in Tarantool 1.10.3-107-g17db27170 shows a long list of rocks and versions.
> 
> tarantoolctl rocks 1.x is based on luarocks 2
> tarantoolctl rocks 2.2+ is based on luarocks 3
> 
> Related PR: #4207

Understood. 
Still, the issue is there in v.2.2+. This is incorrect to misguide a user.

**Comment by Totktonada** [comment]
I think it worth to just pass this option for `tarantoolctl rocks search` (but maybe not for other commands).
