### ISSUE TITLE
Export libcurl symbols into tarantool/curl.h in case of static bundled curl

### ISSUE THREAD

**Issue by olegrok** [tarantool/tarantool#4559]
Some of our modules (e.g. smtp) needs libcurl, however they continue to use system libcurl because tarantool does not export libcurl symbols and headers.

Let's fix it and allow users to use tarantool's curl in their modules and applications

**Comment by rosik** [comment]
I agree. I think it should be distributed as `tarantool/curl.h` and smtp rock should be able to find it there.

**Comment by Totktonada** [comment]
Nice idea!

**Comment by Totktonada** [comment]
The issue in tarantool/smtp: https://github.com/tarantool/smtp/issues/24

**Comment by Totktonada** [comment]
What remains to do: enable the SMTP protocol, install libcurl headers (for bundled libcurl and static build).
