### ISSUE TITLE
test: create the packpack suse leap 15.[0..2] images and testing with it

### ISSUE THREAD

**Issue by avtikhon** [tarantool/tarantool#4562]
OS version:
suse 15.[0-2]

Blocked by:
- [ ] https://github.com/packpack/packpack/pull/121
- [x] https://github.com/packpack/packpack-docker-images/pull/44

**Comment by avtikhon** [comment]
Waiting sub-task at:
https://github.com/packpack/packpack/pull/113

**Comment by ligurio** [comment]
@avtikhon please add web link to patch and move to review back
