### ISSUE TITLE
Missing foreign key check if autoincrement

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#4565]
I have Ubuntu 18.04.
I have Tarantool 2.3, pulled from source today.
I execute these statements:

CREATE TABLE t1 (s1 INTEGER PRIMARY KEY);
CREATE TABLE t2 (s1 INTEGER PRIMARY KEY AUTOINCREMENT,
                 FOREIGN KEY (s1) REFERENCES t1);
INSERT INTO t2 VALUES (NULL);

Result: no error.
Apparently the foreign key constraint was not checked.

**Comment by kshcherbatov** [comment]
The problem is quite deep: autoincrement(s) are implemented with sequences with are evaluated on the server side (request.c, request_handle_sequence) - lather than this code had been evaluated
```
	struct field_link *link = fk_def->links;
	for (uint32_t i = 0; i < fk_def->field_count; ++i, ++link) {
		int reg = link->child_field + reg_data + 1;
		sqlVdbeAddOp2(v, OP_IsNull, reg, ok_label);
	}
```

Perhaps, it __could__ be solved with fk constraints server integration.

**Comment by kshcherbatov** [comment]
@pgulutzan should fk constraints be evaluated before or after forming a tuple using auto-increment information?

**Comment by pgulutzan** [comment]
@kshcherbatov the short answer is "after". The long answer is ...
I guess the right answer would be what the SQL standard asks.
Of course standard SQL has no autoincrement but probably the rule
for "identity column" is close enough, that is, an autoincrement
column is like a standard column that was defined
with GENERATED BY DEFAULT AS IDENTITY, and NULL means DEFAULT.
In that case the standard order would be:
assign the next value to the identity column,
execute before triggers,
assign values for the rest of the columns,
execute referential actions,
check all constraints (which in theory includes referential constraints),
put the new row in the base table,
execute after triggers.
Of course nobody is worried whether Tarantool does it exactly
that way, but certainly foreign-key checks should happen long after
autoincrement generation.

**Comment by ImeevMA** [comment]
Now, after implementing #6986, the problem seems to be fixed:
```
tarantool> box.execute([[CREATE TABLE t1 (s1 INTEGER PRIMARY KEY);]])
---
- row_count: 1
...

tarantool> box.execute([[CREATE TABLE t2 (s1 INTEGER PRIMARY KEY REFERENCES t1 AUTOINCREMENT);]])
---
- row_count: 1
...

tarantool> box.execute([[INSERT INTO t2 VALUES (NULL);]])
---
- null
- 'Foreign key constraint ''fk_unnamed_T2_S1_1'' failed for field ''1 (S1)'': foreign
  tuple was not found'
...
```

Now it properly works for both field and tuple constraints:
```
tarantool> box.execute([[CREATE TABLE t1 (s1 INTEGER PRIMARY KEY);]])
---
- row_count: 1
...

tarantool> box.execute([[CREATE TABLE t2 (s1 INTEGER PRIMARY KEY REFERENCES t1 AUTOINCREMENT);]])
---
- row_count: 1
...

tarantool> box.execute([[INSERT INTO t1 VALUES (1);]])
---
- row_count: 1
...

tarantool> box.execute([[INSERT INTO t2 VALUES (NULL);]])
---
- autoincrement_ids:
  - 1
  row_count: 1
...
```

```
tarantool> box.execute([[CREATE TABLE t1 (s1 INTEGER PRIMARY KEY);]])
---
- row_count: 1
...

tarantool> box.execute([[CREATE TABLE t2 (s1 INTEGER PRIMARY KEY AUTOINCREMENT, foreign key (s1) REFERENCES t1);]])
---
- row_count: 1
...

tarantool> box.execute([[INSERT INTO t1 VALUES (1);]])
---
- row_count: 1
...

tarantool> box.execute([[INSERT INTO t2 VALUES (NULL);]])
---
- autoincrement_ids:
  - 1
  row_count: 1
...
```
