### ISSUE TITLE
SQL core dump on LIKE statement with arguments

### ISSUE THREAD

**Issue by dezdoz** [tarantool/tarantool#4566]
Tarantool version:
2.3.0-0-gce0f2ef8b ( happens also in versions > 2.2.0 )

OS version: 
Ubuntu 19.04 

Bug description:
Core dump happens on like statement with arguments.

Steps to reproduce:
Through box or binary protocol.
box.execute([[SELECT * FROM "history" WHERE ("message" LIKE ?)]], {'a%'});

Log:
/tarantool/src/box/sql/vdbeaux.c:2240: sqlVdbeReset: Assertion `!p->is_aborted || p->expired == 0' failed.

**Comment by kshcherbatov** [comment]
I bisected the commit that had introduced the bug.

3cc95e537e39fe4aa743c1b089da1957acabf6da is the first bad commit
commit 3cc95e537e39fe4aa743c1b089da1957acabf6da
Author: Mergen Imeev <imeevma@gmail.com>
Date:   Tue May 21 17:34:13 2019 +0300

    sql: remove SQL_SCHEMA errcode
    
    Removing this error code is part of getting rid of the SQL error
    system.

 src/box/sql/sqlInt.h  |  2 --
 src/box/sql/vdbeInt.h |  8 --------
 src/box/sql/prepare.c | 46 +++++++---------------------------------------
 src/box/sql/vdbe.c    |  5 +----
 src/box/sql/vdbeapi.c | 23 +++--------------------
 5 files changed, 11 insertions(+), 73 deletions(-)

**Comment by Korablev77** [comment]
@kshcherbatov Could you suggest fix for that?

**Comment by kshcherbatov** [comment]
In progress =)

**Comment by kshcherbatov** [comment]
Hm, the following change is wrong:
```
@@ -993,21 +992,17 @@ bindText(sql_stmt * pStmt,        /* The statement to bind against */
 {
        Vdbe *p = (Vdbe *) pStmt;
        Mem *pVar;
-       int rc;
-
-       rc = vdbeUnbind(p, i);
-       if (rc == 0) {
-               if (zData != 0) {
-                       pVar = &p->aVar[i - 1];
-                       rc = sqlVdbeMemSetStr(pVar, zData, nData, 1, xDel);
-                       if (rc == 0)
-                               rc = sql_bind_type(p, i, "TEXT");
-                       rc = sqlApiExit(p->db, rc);
-               }
-       } else if (xDel != SQL_STATIC && xDel != SQL_TRANSIENT) {
-               xDel((void *)zData);
+       if (vdbeUnbind(p, i) != 0) {
+               if (xDel != SQL_STATIC && xDel != SQL_TRANSIENT)
+                       xDel((void *)zData);
+               return -1;
        }
-       return rc;
+       if (zData == NULL)
+               return 0;
+       pVar = &p->aVar[i - 1];
+       if (sqlVdbeMemSetStr(pVar, zData, nData, 1, xDel) != 0)
+               return -1;
+       return sql_bind_type(p, i, "TEXT");
 }

```
Going to understand, why it has been refactored at all.

**Comment by kshcherbatov** [comment]
I think that removing sqlLockAndPrepare function was a wrong decision.
