### ISSUE TITLE
test: flaky segfault on vinyl/write_iterator test

### ISSUE THREAD

**Issue by avtikhon** [tarantool/tarantool#4572]
Tarantool version:
Tarantool 2.6.0-142-g535568803
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_BACKTRACE=OFF
Compiler: /usr/bin/cc /usr/bin/c++
C_FLAGS:-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fexceptions -funwind-tables -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type
CXX_FLAGS:-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fexceptions -funwind-tables -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type

OS version:
Debian 9
CentOS 8

Bug description:
- release_lto build
- vinyl/ suite run inline
- commit 2232d45d91743274822cc2bc731502f054637314

https://gitlab.com/tarantool/tarantool/-/jobs/323345221
https://gitlab.com/tarantool/tarantool/-/jobs/771934540#L3039

```
Segmentation fault
  code: SEGV_MAPERR
  addr: (nil)
  context: 0x7f0283aff700
  siginfo: 0x7f0283aff830
  rax      0x0                0
  rbx      0x1                1
  rcx      0x7f0280ab0081     139648725352577
  rdx      0x7f0280ab0087     139648725352583
  rsi      0x7f0280ab0081     139648725352577
  rdi      0x2                2
  rsp      0x7f0283affc90     139648776010896
  rbp      0x7f0283affd30     139648776011056
  r8       0x5614b6aecbd0     94646964243408
  r9       0x5614b6aeca90     94646964243088
  r10      0x7f028097fd50     139648724106576
  r11      0x13               19
  r12      0x243              579
  r13      0x5614b6ae5110     94646964211984
  r14      0x7f0280ab0087     139648725352583
  r15      0x7f0280aeb038     139648725594168
  rip      0x5614b617f2cc     94646954357452
  eflags   0x10246            66118
  cs       0x33               51
  gs       0x0                0
  fs       0x0                0
  cr2      0x0                0
  err      0x4                4
  oldmask  0x0                0
  trapno   0xe                14
Current time: 1571294435
Please file a bug at http://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed, 
this may fail as well
#0  0x5614b6234c19 in print_backtrace+9
#1  0x5614b614bb59 in _ZL12sig_fatal_cbiP9siginfo_tPv+c9
#2  0x7f0284308730 in funlockfile+50
#3  0x5614b617f2cc in vy_deferred_delete_on_replace+26c
#4  0x5614b6242ec2 in trigger_run+32
#5  0x5614b61ee780 in txn_commit_stmt+130
#6  0x5614b61d015b in vy_deferred_delete_batch_process_f+1db
#7  0x5614b6236404 in cmsg_deliver+14
#8  0x5614b6236f3e in fiber_pool_f+8e
#9  0x5614b614b4fc in _ZL16fiber_cxx_invokePFiP13__va_list_tagES0_+c
#10 0x5614b62319e0 in fiber_loop+30
#11 0x5614b63a831f in coro_init+3f
```
Steps to reproduce:

Optional (but very desirable):
* coredump
* backtrace
* netstat

**Comment by Korablev77** [comment]
Also saw failed vinyl/write_iterator.test.lua with different error:
```
[043] vinyl/write_iterator.test.lua                                   [ fail ]
[043] 
[043] Test failed! Result content mismatch:
[043] +++ vinyl/write_iterator.reject	Mon Oct 21 16:16:34 2019
[043] @@ -164,7 +164,7 @@
[043]  ...
[043]  box.snapshot()
[043]  ---
[043] -- ok
[043] +- error: 'Invalid VYLOG file: Slice 7 deleted but not registered'
[043]  ...
[043]  space:insert{12}
[043]  ---
[043] @@ -172,7 +172,7 @@
```

**Comment by avtikhon** [comment]
Not reproduced on 2.4.0-16-gcdf502c

**Comment by Totktonada** [comment]
Reproduce in [Travis-CI](https://travis-ci.org/tarantool/tarantool/jobs/643613314) on 2.2.2-21-g9c58958df.

**Comment by ligurio** [comment]
Passed 100 times out of 100 runs

Tarantool 2.4.0-90-g362d59784

**Comment by avtikhon** [comment]
I've tried to reproduce the issue but failed on:
- native 2232d45d91743274822cc2bc731502f054637314 commit as was on gitlab-ci testing
- latest 2.5.0-2-g098324556 commit on master
- latest 1.10.6-1-g47c009ae7 commit on 1.10
- used debian-stretch as was on gitlab-ci testing
- checked release_lto build as was on gitlab-ci testing
- checked release build
- checked in parallel runs and inline as it was on gitlab-ci testing
- checked the whole suite vinyl/ run and short number of previous tests as it was on gitlab-ci testing

Seems that the issue should be closed, @Korablev77 please approve.

**Comment by avtikhon** [comment]
Seems that issue still exists but very had reproducible:
https://gitlab.com/tarantool/tarantool/-/jobs/584999566
```
 Tarantool 2.5.0-99-gf5dfde5ca
 Target: Linux-x86_64-RelWithDebInfo
 Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_BACKTRACE=OFF
 Compiler: /usr/bin/cc /usr/bin/c++
 C_FLAGS:-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fexceptions -funwind-tables -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -fno-gnu89-inline -Wno-cast-function-type
 CXX_FLAGS:-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fexceptions -funwind-tables -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Wno-cast-function-type
```

**Comment by avtikhon** [comment]
Reproduce for issue mentioned in comment

https://github.com/tarantool/tarantool/issues/4572#issuecomment-544601901
```
cat >vinyl.list.yaml <<EOF
- [vinyl/gh-4957-too-many-upserts.test.lua, null]
- [vinyl/write_iterator.test.lua, null]
EOF
./test-run.py --reproduce vinyl.list.yaml
```

**Comment by Korablev77** [comment]
Still some customers report this crash during DDL+DML load. So I'm reopening issue.

**Comment by kyukhin** [comment]
We need a reproducer.

**Comment by olmiik** [comment]
@kyukhin  Here are a couple of links to reproducer for this issue on latest master o both 1.10 and 2.x
- https://github.com/picodata/tarantool-benchtest/tree/reproduce-vinyl-crash-tnt-issue-4572
- https://github.com/picodata/tarantool-benchtest/tree/reproduce-vinyl-crash-tnt-issue-4572/example/fuzz_vinyl

**Comment by locker** [comment]
Duplicate #6448
