### ISSUE TITLE
Enable debug for libcurl when tarantool is built in debug mode

### ISSUE THREAD

**Issue by igormunkin** [tarantool/tarantool#4575]
As a result of offline discussion with @Totktonada we decided to create a follow-up ticket for subj considering changes to be made within #4490.

**Comment by Totktonada** [comment]
Looks connected with #4444.

**Comment by Totktonada** [comment]
Curious fact: we observed a problem (#6656) on Mac OS on arm64 (and only there!), because libcurl was built in debug mode.

**Comment by ligurio** [comment]
Closed by 3dbf19b61bbe897041f76f544b19148640229422.
