### ISSUE TITLE
support old good "bootstrap by copy" for replication

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#459]
It should be possible to bootstrap replication by copying all data from the master to replica.
Right now this breaks because of cluster id mismatch.

The procedure could be as follows:

- copy the snapshot from master 
- start on the snapshot
- insert a new server id into _cluster **on both masters**
- set current server server id to the newly inserted server id on the new replica
- start replication with box.cfg{replication_source=}

**Comment by rtsisyk** [comment]
I don't understand what should be done for this ticket.

**Comment by kostja** [comment]
Roman, your instruction doesn't work. See gh-806. If it does, please add a test case and close the bug.

**Comment by Sulverus** [comment]
Merged from gh-806. Close?
