### ISSUE TITLE
httpc: dns resolving hangs tarantool

### ISSUE THREAD

**Issue by sergepetrenko** [tarantool/tarantool#4591]
Tarantool version:
1.10.3-121 and up (?)
OS version:
CentOS
Bug description:
Tarantool hangs for the whole time dns resolving takes place.
For example, if resolving feedback.tarantool.io takes 4 seconds,
tarantool will hang for 4 seconds upon making a request to it.

**Comment by sergepetrenko** [comment]
How to reproduce:
Linux:
`tc qdisc add dev wlan0 root handle 1:0 netem delay 5000msec` will add a 5 sec delay on `wlan0` interface (issue `tc qdisc del dev wlan0 root` to reset it)

Mac OS: install Network Link Conditioner and turn it on.

Run tarantool and issue
```lua
box.cfg{feedback_enabled=true, feedback_interval=0}
```
tarantool will hang for 5 seconds (on Linux) or until you turn Network Link Conditioner off (on Mac)
Thanks @Totktonada for the Linux repro

**Comment by Totktonada** [comment]
Closed in [1.10.5-22-g9987838ab](https://github.com/tarantool/tarantool/commit/9987838abda76915e2ec9c78b6be60d616595352), [2.2.2-50-g254e42cea](https://github.com/tarantool/tarantool/commit/254e42cea53e5baeee7d5a3c249d5afe1a26c68b), [2.3.1-54-g488c6ecee](https://github.com/tarantool/tarantool/commit/488c6ecee525448c9f99af93dc5b60e79ae2a0b0), [2.4.0-76-g238370761](https://github.com/tarantool/tarantool/commit/238370761b93116424c47859194cb77cdce6ac33).
