### ISSUE TITLE
`tarantoolctl enter' segmentation fault

### ISSUE THREAD

**Issue by rtokarev** [tarantool/tarantool#4598]
Tarantool version: 1.10.3.69-1

OS version: CentOS 7

Bug description: Sometimes `tarantoolctl enter' is segfaulted.

```
Core was generated by `tarantool /usr/bin/tarantoolctl enter xtaz_167 PATH=/usr/local/sbin:/usr/local/'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f98b1118be7 in ?? ()
(gdb) info threads
  Id   Target Id         Frame
* 1    LWP 43367         0x00007f98b1118be7 in ?? ()
```

**Comment by Gerold103** [comment]
It would be cool to have more details about how to reproduce.

**Comment by rtokarev** [comment]
I don't know how to reproduce it. We have few servers that do `tarantoolctl enter'  every 5 minutes and some times we have such a coredumps.

**Comment by kyukhin** [comment]
Excuse us, but we need to have a reproducer.

**Comment by igormunkin** [comment]
I asked @rtokarev whether it still bothers him, but he failed reproduce the issue using 2.3.2-8-g5e55384 (5e55384). 

If the problem occurs again, please provide all supplementary info (use [bug request template](https://github.com/tarantool/tarantool/issues/new?assignees=&labels=bug&template=bug_report.md) in our repo) and the detailed steps to reproduce the crash.
