### ISSUE TITLE
net.box: self allows to modify source object after transfer

### ISSUE THREAD

**Issue by olegrok** [tarantool/tarantool#4602]
Tarantool version: Tarantool 2.3.0-136-gaf9ef2115

```lua
x = {}
function test() return x end
box.schema.func.create('test')
y = require('net.box').self:call('test')
tarantool> y
---
- []
...

tarantool> y.a = 'b'
---
...

tarantool> y
---
- a: b
...

tarantool> x
---
- a: b
...
```

Expected behaviour: 'y' should be copy of 'x' and 'x' is not changed.

**Comment by rosik** [comment]
related to #4513

**Comment by eljashm** [comment]
I'm not sure whether it's a bug since lua has the same exact behavior - assignment to a table does not create another instance as a copy but instead just another reference to this table. 

The issue needs further discussion.

**Comment by olegrok** [comment]
@eljashm 

I can extend my example:
```lua
box.cfg{listen = 3301}
x = {}
function test() return x end
box.schema.func.create('test')

box.schema.user.passwd('admin', 'test')
conn = require('net.box').connect('admin:test@localhost:3301')
y = conn:call('test')
y == x -- false

z = require('net.box').self:call('test')
z == x -- true
```

According documentation:

>For a local Tarantool server, there is a pre-created always-established connection object named net_box.self. Its purpose is to make polymorphic use of the net_box API easier. Therefore conn = net_box.connect('localhost:3301') can be replaced by conn = net_box.self. However, there is an important difference between the embedded connection and a remote one. With the embedded connection, requests which do not modify data do not yield. When using a remote connection, due to the implicit rules any request can yield, and database state may have changed by the time it regains control.

Then I expect that results will be the same in both cases

**Comment by Totktonada** [comment]
@kyukhin If we don't do #4657, then we shouldn't do this issue too?

**Comment by kyukhin** [comment]
I think so.

**Comment by Totktonada** [comment]
Fixed in together with #4513 in the following commits:

* [2.4.0-83-g0bcf9a59d](https://github.com/tarantool/tarantool/commit/0bcf9a59d700a9d2f33efff987c765a72fd3cb7b)
* [2.3.1-58-gbb2e6d908](https://github.com/tarantool/tarantool/commit/bb2e6d908a3828cfb5cc44929ecae804cb4119ba)
* [2.2.2-54-g40cc8a7a7](https://github.com/tarantool/tarantool/commit/40cc8a7a7408ef5b05a5c6a48f9fbb05d52ea4d2)
* [1.10.5-25-gf1162f233](https://github.com/tarantool/tarantool/commit/f1162f233da069ba7f1f5e0b897875814d00b6c8)

**Comment by olegrok** [comment]
@Totktonada 

https://github.com/tarantool/tarantool/commit/0bcf9a59d700a9d2f33efff987c765a72fd3cb7b#diff-a9dd9be71f8af749f288abb6304a5185R1555 :
`msgpack.decode(msgpack.encode(...))` is applied only for "cdata" type. Simple tables could be modified after call.

**Comment by Totktonada** [comment]
Okay. Thanks!

**Comment by kyukhin** [comment]
I think we should simply document this.
