### ISSUE TITLE
Replication setup error

### ISSUE THREAD

**Issue by rosik** [tarantool/tarantool#4605]
Tarantool version: 2.3.0-187-gc214d086f, **1.10.4-26-gf788396cb**

Bug description:

Instance number 1:

```
box.cfg({listen = 3301}) 
box.schema.user.passwd('admin', '')
```

Instance 2:

```
box.cfg({replication = "admin@localhost:3301"}) 
```

Result:

```
E> ER_MISSING_REQUEST_FIELD: Missing mandatory field 'tuple' in request
```

**Comment by rosik** [comment]
It seems that empty password is the main reason of the error

**Comment by Gerold103** [comment]
Use `admin:@localhost:3301` instead of `admin@localhost:3301`. That way you explicitly say, that there is a password, but an empty one.

**Comment by Gerold103** [comment]
But the strange error is definitely a bug. It should say something like 'no password specified'.

**Comment by rosik** [comment]
Wow, that's surprising. But `netbox.connect("guest@localhost:3301")` works just fine - it uses empty string as a password. Why does it behave differently in box.cfg?

**Comment by kostja** [comment]
Empty string is not the same as an empty password, like in any Unix system. Empty password means there is no login for this user, it is internal. Empty string is a valid password like any other.

**Comment by kostja** [comment]
The reason we treat empty password equal to empty string password for guest user is that we always allow guest login - it is the default session user. So for this user in absence of AUTHENTICATION packet, the assumed password is empty - and hence it should be OK to supply empty or zero-length string password in auth packet, and they are treated the same.
Basically it's to make people life easier. 

If you with to use no password, grant 'super' role to guest. Do not abuse admin user with application logic, this user was created for a DBA

**Comment by rosik** [comment]
Ok, guess I provided bad example. Let's stop talking about "guest" vs "admin", and discuss `netbox.connect` vs `box.cfg({replication})`.

Look:

``` console
> box.cfg({listen = 3301})
> box.schema.user.create('rosik', '')
> box.schema.user.grant('rosik', 'read,write,execute', 'universe')
> require('net.box').connect('rosik@localhost:3301'):call('print', {'It works!'})
It works!
> -- and box.cfg replication doesn't (Missing mandatory field 'tuple' in request)
```

In absence of password netbox tries to authenticate with an empty string. And I like it, it's natural.
Empty password could be meaningful in SSH, which prompts it from the tty, or uses different auth methods. But empty password has no sense in netbox auth request - it will never pass. So netbox tries default empty string, and does make my life easier.

My proposal is to make box.cfg behavior similar - if user didn't provide a password, send authentication packet with an empty string. If it's unset or differs - server will reject it.
