### ISSUE TITLE
Turn on -fcatch-undefined-behavior for clang debug

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#4609]
That flag may help to catch simple bugs such as signed integer overflow, out of array boundaries access, shift operator overflow.

**Comment by Gerold103** [comment]
It is -fsanitize option, actually.

**Comment by Gerold103** [comment]
https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html#available-checks

**Comment by kyukhin** [comment]
Done. Follow up issues submitted: #5075 and #5057
