### ISSUE TITLE
Provide to box.info an information about the ffi sandwich

### ISSUE THREAD

**Issue by Kasen** [tarantool/tarantool#4616]
The reason for dubbing of log warnings about FFI sandwich and JIT disabling into the box.info (as per @Kasen): to take logs from customer is a hard work, whilst making an extra metrics for visualisation is a no-brainer.

**Comment by igormunkin** [comment]
The problem is solved in a different way in scope of tarantool/luajit@4f4fd9e, so this ticket is irrelevant.
