### ISSUE TITLE
Could not compile by downloading the release source

### ISSUE THREAD

**Issue by jobs-git** [tarantool/tarantool#4618]
Tarantool version:
2.2.1
OS version:
CentOS 7
Bug description:
Failed to `cmake .` It ask failed to find submodule
Steps to reproduce:
cmake .
Optional (but very desirable):

**Comment by Totktonada** [comment]
Archives that GitHub automatically creates for releases do not contain submodules. Use tarballs we deploy to download.tarantool.org:

* 1.10: https://download.tarantool.org/tarantool/1.10/src/
* 2.1: https://download.tarantool.org/tarantool/2x/src/
* 2.2: https://download.tarantool.org/tarantool/2.2/src/
* 2.3: https://download.tarantool.org/tarantool/2.3/src/

**Comment by jobs-git** [comment]
I am confused, which one is this https://github.com/tarantool/tarantool/releases/tag/2.2.1

**Comment by Totktonada** [comment]
Use https://download.tarantool.org/tarantool/2.2/src/tarantool-2.2.1.1.tar.gz . Revisions with zero at the end are not deployed now due to #3745.
