### ISSUE TITLE
Select by secondary index with one of params with nil value goes error. 

### ISSUE THREAD

**Issue by seet61** [tarantool/tarantool#4628]
Tarantool version:
Tarantool 1.10.4-30-gc7cab9043

OS version:
debian_version 9.11

Bug description:
Select by secondary index with one of params with nil value goes error. 

Steps to reproduce:
Without nil
```
unix/:/var/run/tarantool/master.control> box.space.FreeMsisdns.index.FreeMsisdns_pht_id_branch_id_switch_id_phs_id_ttl_idx:select({8, 14, 275, 1, 9999999999}, {iterator=box.index.GT, limit=10})
---
- - ['79041011946', 10310457, 8, 17, 401, 1, 9999999999, '']
  - ['79041011978', 10310489, 8, 17, 401, 1, 9999999999, '']
  - ['79041021953', 10320464, 8, 17, 401, 1, 9999999999, '']
  - ['79041021955', 10320466, 8, 17, 401, 1, 9999999999, '']
  - ['79041021987', 10320498, 8, 17, 401, 1, 9999999999, '']
  - ['79041031974', 10330485, 8, 17, 401, 1, 9999999999, '']
  - ['79042061958', 18390874, 8, 17, 401, 1, 9999999999, '']
  - ['79042061979', 18390895, 8, 17, 401, 1, 9999999999, '']
  - ['79042071932', 18400848, 8, 17, 401, 1, 9999999999, '']
  - ['79042071981', 18400897, 8, 17, 401, 1, 9999999999, '']
...
```

With nil
```
unix/:/var/run/tarantool/master.control> box.space.FreeMsisdns.index.FreeMsisdns_pht_id_branch_id_switch_id_phs_id_ttl_idx:select({8, 14, nil, 1, 9999999999}, {iterator=box.index.GT, limit=10})
---
- error: 'Supplied key type of part 2 does not match index part type: expected integer'
...
```

Optional (but very desirable):
* coredump
* backtrace
* netstat

**Comment by seet61** [comment]
`FreeMsisdns_space:format({
    {name='msisdn',type='string'},
    {name='phone_id',type='unsigned'},
    {name='pht_id',type='unsigned'},
    {name='branch_id',type='unsigned'},
    {name='switch_id',type='integer'},
    {name='phs_id',type='unsigned'},
    {name='ttl',type='unsigned'},
    {name='message_id',type='string',is_nullable=true}
})`

**Comment by olegrok** [comment]
It seems that it's a correct behaviour of BTree index

tuples are sorted by index fields and when you add `nil` to some place you break internal structure of BTree.

**Comment by olegrok** [comment]
BTW, what behaviour do you expect to be correct?

**Comment by seet61** [comment]
From documentation:
`Informally, we can state that searches with TREE indexes are generally what users will find is intuitive, provided that there are no nils and no missing parts. Formally, the logic is as follows. A search key has zero or more parts, for example {}, {1,2,3},{1,nil,3}. An index key has one or more parts, for example {1}, {1,2,3},{1,2,3}. A search key may contain nil (but not msgpack.NULL, which is the wrong type).`

I expect that select with nil will work as any value.

**Comment by olegrok** [comment]
> I expect that select with nil will work as any value.

It's a wrong expectation. "select" or "pairs" gives you an iterator then you scan some interval. If you skip (setup it to nil) some field you expect that your iterators starts jump inside this interval. But it's impossible.

If you skip some field you should scan by hand this interval and match all tuples for "condition" after nil in your search key.

Or move this "skipped" value to the end of your scan index in your schema
