### ISSUE TITLE
Extend luarocks functionality

### ISSUE THREAD

**Issue by rosik** [tarantool/tarantool#4629]
Things I'd like to see in tarantoolctl rocks:

* `tarantoolctl rocks doc`: options `--list`, `--home`
* `tarantoolctl rocks install`: option `--only-deps`
* `tarantoolctl rocks remove`: option `--force` (https://github.com/tarantool/tarantool/issues/3632)
* `tarantoolctl rocks list`: options `--outdated`
* `tarantoolctl rocks make`: options `--pack-binary-rock`, `--chdir`
* `tarantoolctl rocks search`: options `--source` `--binary` `--all` (https://github.com/tarantool/tarantool/issues/4529)

Other commands that may be useful:

* `tarantoolctl rocks build`
* `tarantoolctl rocks config`
* `tarantoolctl rocks download`
* `tarantoolctl rocks help`
* `tarantoolctl rocks lint`
* `tarantoolctl rocks new_version`
* `tarantoolctl rocks purge`
* `tarantoolctl rocks upload` - should be implemented in a way compatible to rocks.tarantool.org
* `tarantoolctl rocks write_rockspec`

**Comment by LeonidVas** [comment]
After discussion it was agreed to forward options to the luarocks module without preprocessing and add a black list of unwanted options (like --lua-dir, --lua-version, --local, --global) to luarocks parser.

**Comment by knazarov** [comment]
Please don't break --chdir option that is currently implemented. We depend on it.

**Comment by orchaton** [comment]
We also need --tree option which overrides --local behavior.

It would be great if `tarantoolctl rocks` will support command `test` with understanding `test_dependencies` and `test` sections in a way luarocks does it: https://www.lua.org/wshop18/Muhammad.pdf

It would be nice to support `tarantoolctl rocks make-manifest` to allow updating manifest of personal rocks server as it does `luarocks-admin make-manifest`.

`tarantoolctl rocks` must respect env variable `LUAROCKS_CONFIG` to allow specifying user specific luarocks config file.

It would be nice if `tarantoolctl rocks` will be able to install rocks from any luarocks-like server, so developer can maintain own private server with lua libraries, as luarocks does it.

**Comment by LeonidVas** [comment]
> Please don't break --chdir option that is currently implemented. We depend on it.

Chdir option has been moved to luarocks.

**Comment by LeonidVas** [comment]
> We also need --tree option which overrides --local behavior.
> 
> It would be great if `tarantoolctl rocks` will support command `test` with understanding `test_dependencies` and `test` sections in a way luarocks does it: https://www.lua.org/wshop18/Muhammad.pdf
> 
> It would be nice to support `tarantoolctl rocks make-manifest` to allow updating manifest of personal rocks server as it does `luarocks-admin make-manifest`.
> 
> `tarantoolctl rocks` must respect env variable `LUAROCKS_CONFIG` to allow specifying user specific luarocks config file.
> 
> It would be nice if `tarantoolctl rocks` will be able to install rocks from any luarocks-like server, so developer can maintain own private server with lua libraries, as luarocks does it.

The point of the task is refuse from double parsing of luarocks options (first in tarantoolctl and second in luarocks module), cleanup help and replace a white-list filter (most options are prohibited) to 
a black-list filter (most options allowed). So, if the functionality is work at luarock it must work at tarantoolctl rocks too (most likely).
Black-list:
`+-- The tarantool unsupported arguments list.
+local tarantool_black_list = {
+   ["global"] = true,
+   ["local"] = true,
+   ["lua-version"] = true,
+   ["lua-dir"] = true,
+}`

**Comment by knazarov** [comment]
> > Please don't break --chdir option that is currently implemented. We depend on it.
> 
> Chdir option has been moved to luarocks.

I understand. But we depend on the exact format that is currently implemented in tarantoolctl. Please keep it backwards compatible. Otherwise it will break lots of stuff that is currently written across lots of repositories and user guides
