### ISSUE TITLE
sqlRunParser doesn't set diagnostics in some error cases

### ISSUE THREAD

**Issue by PersDep** [tarantool/tarantool#4633]
```
	if (pEngine == 0) {
		sqlOomFault(db);
		return -1;
	}
```

```
			sqlParser(pEngine, tokenType, pParse->sLastToken,
				      pParse);
			lastTokenParsed = tokenType;
			if (pParse->is_aborted || db->mallocFailed)
				break;
```

We might return error code from sqlRunParser without diagnostics.

**Comment by Gerold103** [comment]
sqlOomFault sets malloc failed and OutOfMemory diagnostics error. So what is a problem?

**Comment by PersDep** [comment]
> First case: sqlOomFault sets mallocFailed and OutOfMemory diagnostics error.
> Second case: if pParse->is_aborted is set, then diag_set is installed already somewhere deeper. If db->mallocFailed is set, then sqlOomFault() was invoked and set OutOfMemory error.
> So what is a problem?

Ok, i see, we are setting diagnostics from sql_parser_destroy if mallocFailed is set. Then I guess it is fine.
