### ISSUE TITLE
"\set output" throws unhandled error in case of empty output type

### ISSUE THREAD

**Issue by olegrok** [tarantool/tarantool#4638]
Tarantool 2.3.0-225-g8d363c439
```lua
tarantool> \set output
---
- error: 'builtin/box/console.lua:117: attempt to index local ''value'' (a nil value)'
...
```
but
```lua
tarantool> \set output something
---
- error: 'Invalid format "something", supported languages: lua and yaml.'
...
```

It seems that we also should return `"error: 'Invalid format "something", supported languages: lua and yaml.'"` for an empty output

**Comment by cyrillos** [comment]
[PATCH] box/console: Handle empty output format

**Comment by cyrillos** [comment]
https://lists.tarantool.org/pipermail/tarantool-patches/2019-December/013194.html
