### ISSUE TITLE
Consider create_index interface unification

### ISSUE THREAD

**Issue by olegrok** [tarantool/tarantool#4652]
Yes, it's a breaking change. But are we sure that it's ok to support all possible variants?

```lua
space:create_index('test', {parts = {1, 'unsigned', 2, 'string'}}) 
```
```lua
space:create_index('test', {parts = {{1, 'unsigned'}, {2, 'string'}}}) 
```

```lua
space:create_index('test', {parts = {{field = 1, type = 'unsigned'}, {field = 2, type = 'string'}}}) 
```

This commands leads to the same result. I think we should support only the last variant.

Inspired by https://github.com/tarantool/tarantool/issues/4519

**Comment by Gerold103** [comment]
Then it is worth dropping some other very deprecated things. Such as old space options format; text console support in netbox; old field type names ('num', 'str'); netbox `:timeout()` API and call/eval 1.6.

**Comment by opomuc** [comment]
you forgot
```
space:create_index('test', {parts = { 'a', 'b' }}) 
```

**Comment by parihaaraka** [comment]
> you forgot
> 
> ```lua
> space:create_index('test', {parts = { 'a', 'b' }}) 
> ```

BTW the only one being used by some people :)

**Comment by Mons** [comment]
See no reason to break backward compatibility
