### ISSUE TITLE
Consider improving testing engine for better usability on test updates

### ISSUE THREAD

**Issue by cyrillos** [tarantool/tarantool#4654]
Currently when one update a test he has to move `reject` file to `result` manually. It would be much more convenient to automatize this action.

This feature is not anyhow urgent so I made a bug just to not forget as @Totktonada asked.

**Comment by Totktonada** [comment]
Maybe we should add one option for updating result files and creating new ones (#4258).

**Comment by ligurio** [comment]
[Tarantool-patches] [PATCH v1] Add option to update file with reference output
https://lists.tarantool.org/pipermail/tarantool-patches/2020-March/015077.html

**Comment by ligurio** [comment]
[Tarantool-patches] [PATCH v2] Add option to update file with reference output
https://lists.tarantool.org/pipermail/tarantool-patches/2020-May/016853.html

**Comment by ligurio** [comment]
Duplicate of #194
