### ISSUE TITLE
sql: raise an error in case space features HASH index

### ISSUE THREAD

**Issue by Korablev77** [tarantool/tarantool#4659]
Until https://github.com/tarantool/tarantool/issues/3752 is resolved, interaction with spaces featuring HASH indexes is unsupported. It may lead to common execution errors as well as assertion or segmentation fault. To prevent such unexpected crashes, it is reasonable to provide check that space has no HASH indexes (like we do with space formats (see `sql_lookup_space()`).
One of examples which results in crash:
```
f = {
            {'1', 'unsigned'},
            {'2', 'string'},
}

s = box.schema.create_space("MY_TABLE", {format = f})
s:create_index('CSS_PK_I', {type = 'hash', parts = {'1'}})
box.execute("SELECT COUNT(*) FROM my_table")
Assertion failed: (part_count > 0), function memtx_hash_index_create_iterator, file tarantool/src/box/memtx_hash.c, line 386.

```

**Comment by kostja** [comment]
Can't you skip hash indexes from consideration is if they didn't exist?

**Comment by pgulutzan** [comment]
This affects the manual because I gave examples of hash indexes in the SQL section. Are there any other index options
https://www.tarantool.io/en/doc/2.3/reference/reference_lua/box_space/#lua-function.space_object.create_index
which are useless or dangerous in SQL?

**Comment by Korablev77** [comment]
@pgulutzan Except for spaces featuring hash indexes, also spaces with map/array types in their formats can turn out to be dangerous:
https://github.com/tarantool/tarantool/issues/4757
https://github.com/tarantool/tarantool/issues/4758

That's all AFAIR.

**Comment by pgulutzan** [comment]
@Korablev77: It's good that you didn't say that other index options are dangerous. I changed the version-2.3 and version-2.4 manuals to remove the hash-index examples, mentioning other options instead. I added that there are limitations when accessing spaces that contain maps or arrays or hash indexes. But disallowing them totally (which you suggested in issue#4757) would be a disaster. Lua spaces including system spaces must be accessible in SQL.

**Comment by Totktonada** [comment]
What about RTREE and BITSET indices?

**Comment by Korablev77** [comment]
@Totktonada @pgulutzan Rtree abd bitset indexes are not tested and likely are unsupported too (see https://github.com/tarantool/tarantool/issues/2230 and https://github.com/tarantool/tarantool/issues/2238). Thanks for pointing that out.
