### ISSUE TITLE
fiber.storage leaks when created from iproto

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#4662]
Tarantool version: all since fiber.storage was invented.

Bug description:
Fiber.storage is a fiber local Lua table. This is like thread local data, but fiber local. That table is created on demand, and is deleted when the fiber gets recycled. But the problem is that it works only for fibers, created from Lua. It does not work for fibers from the pool, used by iproto. That leads to fiber.storage not empty in the beginning of some requests.

Steps to reproduce:
```Lua
fiber = require('fiber')
netbox = require('net.box')
box.cfg{listen = 3313}
box.schema.user.grant('guest', 'execute', 'universe')
storage = nil
i = 0
function ref_object_in_fiber()
    storage = fiber.self().storage
    assert(next(storage) == nil)
    fiber.self().storage.key = i
    i = i + 1
end

c = netbox.connect(box.cfg.listen)
c:call('ref_object_in_fiber')
c:call('ref_object_in_fiber')
```
The second call fails like this:
```
tarantool> c:call('ref_object_in_fiber')
---
- error: '[string "function ref_object_in_fiber()..."]:3: assertion failed!'
...

tarantool> storage
---
- key: 0
...
```
So the storage is not empty in the beginning of a request.

**Comment by olegrok** [comment]
I think it's related to https://github.com/tarantool/tarantool/issues/3462 and https://github.com/tarantool/tarantool/issues/2901

I'm not sure that we clear fiber.storage for fibers that are created from lua

**Comment by Gerold103** [comment]
Related:
```
fiber = require('fiber')
box.cfg{}
function test_storage() fiber.storage.key = 100 end
box.schema.func.create('test_storage')
stor = nil
fiber.create(function()
    box.func.test_storage:call()
end)
2019-12-08 18:55:02.655 [67103] main/115/lua utils.c:1028 E> LuajitError: [string "function test_storage() fiber.storage.key = 1..."]:1: attempt to index field 'storage' (a nil value)
---
- the fiber is dead
...
```
