### ISSUE TITLE
build: brew install tarantool --HEAD fails (1.10, 2.2, master)

### ISSUE THREAD

**Issue by Kasen** [tarantool/tarantool#4664]
Tarantool version:
2.2

OS version:
10.15.1

Bug description:
brew install tarantool --HEAD

==> cmake . -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/tarantool/HEAD-b0800a4_3 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev
==> make
Last 15 lines from /Users/kasen/Library/Logs/Homebrew/tarantool/02.make:
[  6%] Built target eio
[  6%] Building C object CMakeFiles/zstd.dir/third_party/zstd/lib/compress/zstdmt_compress.c.o
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -DCORO_ASM -DLUAJIT_ENABLE_GC64=1 -DLUAJIT_SMART_STRINGS=1 -DNDEBUG -DNVALGRIND -DNVALGRIND=1 -I/tmp/tarantool-20191203-3404-x2eb1f/src -I/tmp/tarantool-20191203-3404-x2eb1f/src/lib -I/tmp/tarantool-20191203-3404-x2eb1f/src/lib/small -I/tmp/tarantool-20191203-3404-x2eb1f/src/lib/small/third_party -I/tmp/tarantool-20191203-3404-x2eb1f/src/lib/core -I/tmp/tarantool-20191203-3404-x2eb1f -I/tmp/tarantool-20191203-3404-x2eb1f/third_party/zstd/lib -I/tmp/tarantool-20191203-3404-x2eb1f/third_party/zstd/lib/common  -Wno-unknown-pragmas -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -msse2 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.15   -Ofast -o CMakeFiles/zstd.dir/third_party/zstd/lib/compress/zstdmt_compress.c.o   -c /tmp/tarantool-20191203-3404-x2eb1f/third_party/zstd/lib/compress/zstdmt_compress.c
[  6%] Building C object CMakeFiles/zstd.dir/third_party/zstd/lib/compress/huf_compress.c.o
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -DCORO_ASM -DLUAJIT_ENABLE_GC64=1 -DLUAJIT_SMART_STRINGS=1 -DNDEBUG -DNVALGRIND -DNVALGRIND=1 -I/tmp/tarantool-20191203-3404-x2eb1f/src -I/tmp/tarantool-20191203-3404-x2eb1f/src/lib -I/tmp/tarantool-20191203-3404-x2eb1f/src/lib/small -I/tmp/tarantool-20191203-3404-x2eb1f/src/lib/small/third_party -I/tmp/tarantool-20191203-3404-x2eb1f/src/lib/core -I/tmp/tarantool-20191203-3404-x2eb1f -I/tmp/tarantool-20191203-3404-x2eb1f/third_party/zstd/lib -I/tmp/tarantool-20191203-3404-x2eb1f/third_party/zstd/lib/common  -Wno-unknown-pragmas -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -msse2 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.15   -Ofast -o CMakeFiles/zstd.dir/third_party/zstd/lib/compress/huf_compress.c.o   -c /tmp/tarantool-20191203-3404-x2eb1f/third_party/zstd/lib/compress/huf_compress.c
[  6%] Building C object CMakeFiles/zstd.dir/third_party/zstd/lib/compress/fse_compress.c.o
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -DCORO_ASM -DLUAJIT_ENABLE_GC64=1 -DLUAJIT_SMART_STRINGS=1 -DNDEBUG -DNVALGRIND -DNVALGRIND=1 -I/tmp/tarantool-20191203-3404-x2eb1f/src -I/tmp/tarantool-20191203-3404-x2eb1f/src/lib -I/tmp/tarantool-20191203-3404-x2eb1f/src/lib/small -I/tmp/tarantool-20191203-3404-x2eb1f/src/lib/small/third_party -I/tmp/tarantool-20191203-3404-x2eb1f/src/lib/core -I/tmp/tarantool-20191203-3404-x2eb1f -I/tmp/tarantool-20191203-3404-x2eb1f/third_party/zstd/lib -I/tmp/tarantool-20191203-3404-x2eb1f/third_party/zstd/lib/common  -Wno-unknown-pragmas -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -msse2 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.15   -Ofast -o CMakeFiles/zstd.dir/third_party/zstd/lib/compress/fse_compress.c.o   -c /tmp/tarantool-20191203-3404-x2eb1f/third_party/zstd/lib/compress/fse_compress.c
[  6%] Built target misc
[  7%] Linking C static library libzstd.a
/usr/local/Cellar/cmake/3.15.5/bin/cmake -P CMakeFiles/zstd.dir/cmake_clean_target.cmake
/usr/local/Cellar/cmake/3.15.5/bin/cmake -E cmake_link_script CMakeFiles/zstd.dir/link.txt --verbose=1
/usr/bin/ar qc libzstd.a  CMakeFiles/zstd.dir/third_party/zstd/lib/common/zstd_common.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/common/entropy_common.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/common/error_private.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/common/pool.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/common/xxhash.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/common/fse_decompress.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/decompress/zstd_decompress.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/decompress/huf_decompress.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/compress/zstd_double_fast.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/compress/zstd_fast.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/compress/zstd_lazy.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/compress/zstd_opt.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/compress/zstd_compress.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/compress/zstd_ldm.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/compress/zstdmt_compress.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/compress/huf_compress.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/compress/fse_compress.c.o
/usr/bin/ranlib libzstd.a
[  7%] Built target zstd
make: *** [all] Error 2

READ THIS: https://docs.brew.sh/Troubleshooting

**Comment by avtikhon** [comment]
Tried to reproduce on the clean image of the OSX 10.15, but build passed:

# system_profiler SPSoftwareDataType
      System Version: macOS 10.15 (19A602)
      Kernel Version: Darwin 19.0.0

# clang -v
Apple clang version 11.0.0 (clang-1100.0.33.12)
Target: x86_64-apple-darwin19.0.0

/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -> MacOSX10.15.sdk

**Comment by avtikhon** [comment]
Issue reproduced, but real log result file is:
/Users/tarantool/Library/Logs/Homebrew/tarantool/02.make
```
cd /tmp/tarantool-20191205-44910-io4lzl/third_party/curl && ./buildconf
buildconf: autoconf not found.
            You need autoconf version 2.57 or newer installed.
make[2]: *** [build/curl/work/stamp/bundled-libcurl-project-configure] Error 1
make[1]: *** [CMakeFiles/bundled-libcurl-project.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```
found that brew tarantool spec is not ready for --HEAD version which consists new curl which needs new dependencies, hot fix is to add them:
brew edit tarantool
```
  depends_on "autoconf" => :build
  depends_on "automake" => :build
  depends_on "libtool" => :build
```

**Comment by Kasen** [comment]
I tried hotfix and it works

**Comment by Totktonada** [comment]
@kyukhin Please, change the milestone to 1.10.5.

**Comment by avtikhon** [comment]
The patch at Homebrew-core repository already exists for a long time - waiting them to push it
https://github.com/Homebrew/homebrew-core/pull/45610

**Comment by opomuc** [comment]
@avtikhon please don't forget about 1.10 as well

**Comment by avtikhon** [comment]
There won't be any specs with previous versions unfortunately:
https://github.com/Homebrew/homebrew-core/pull/45611

**Comment by opomuc** [comment]
> There won't be any specs with previous versions unfortunately:
> [Homebrew/homebrew-core#45611](https://github.com/Homebrew/homebrew-core/pull/45611)

Okay, seems we can't do anything here (for now).

**Comment by Totktonada** [comment]
I see autoconf, automake and libtool in dependencies of the current master of tarantool: https://github.com/avtikhon/homebrew-core/blob/2fe1503805753121be8767d9a6889ce84bc09fed/Formula/tarantool.rb . So the issue is resolved?
