### ISSUE TITLE
Move Tarantool info messages from CRIT to INFO logging level

### ISSUE THREAD

**Issue by opomuc** [tarantool/tarantool#4675]
Having those (and similar IMHO informative) messages in critical log level gives false alarm to anyone reading logs.

```
019-12-09 16:59:05.772 [7611] main/101/interactive C> Tarantool 1.10.4-63-g2de491f6f
2019-12-09 16:59:05.772 [7611] main/101/interactive C> log level 5
2019-12-09 16:59:05.779 [7611] main/101/interactive C> leaving orphan mode
```
```
{"time": "2019-12-09T16:24:17.929+0300", "level": "CRIT", "message": "2.9M rows written", "pid": 426412 , "cord_name": "snapshot", "fiber_id": 101, "fiber_name": "main", "file": "\/tarantool\/src\/box\/memtx_engine.c", "line": 546}
```
Taking into account, that `error` level is lower than `crit`, setting log level to `error` you loose basically everything from Tarantool in the log file

**Comment by printercu** [comment]
Is it worth to change severity levels order to more usual one? https://en.wikipedia.org/wiki/Syslog#Severity_level

**Comment by opomuc** [comment]
Why is it in wishlist?

**Comment by AnastasMIPT** [comment]
> Is it worth to change severity levels order to more usual one? https://en.wikipedia.org/wiki/Syslog#Severity_level

I think it would be better to have a separate issue for this.
