### ISSUE TITLE
Attempt to call field ''new'' when creating a fiber

### ISSUE THREAD

**Issue by racherb** [tarantool/tarantool#4676]
Tarantool version: **1.9.1-26-gdf26a1658**

OS version: Ubuntu 19.04 Disco

Bug description: error: '[string "fi2=fiber.new(fu2)"]:1: attempt to call field ''new'' (a nil value)'

Steps to reproduce:

tarantool> fiber=require('fiber')
...

tarantool> function fu2() fiber.sleep(5) end
...

tarantool> fi2=fiber.new(fu2)

- **error: '[string "fi2=fiber.new(fu2)"]:1: attempt to call field ''new'' (a nil value)'**

**Comment by racherb** [comment]
I updated my tarantool version and this error is not present in version 1.10.

**Comment by olegrok** [comment]
This method was introduced in 1.10.1 - https://github.com/tarantool/tarantool/commit/48cad35eb64c4c84d6daab34a263a37ddc902b79

Close issue
