### ISSUE TITLE
How does tarantool handle http queues?

### ISSUE THREAD

**Issue by jobs-git** [tarantool/tarantool#4679]
Based on [this](https://dzone.com/articles/asynchronous-processing-with-in-memory-databases-o) tarantool is capable of queuing HTTP request in the network buffer.

How does it do this? Does it use epoll? If yes, how is this being implemented if not, how does tarantool do this?

PS: I am looking for a c-solution

**Comment by jobs-git** [comment]
@Totktonada any light on this matter?

**Comment by Totktonada** [comment]
The network thread receives incoming requests, that are encoded according to [tarantool binary protocol](https://www.tarantool.io/en/doc/2.2/dev_guide/internals/box_protocol/) (often called iproto). This thread reads requests into a connection-associated buffer of [readahead](https://www.tarantool.io/en/doc/2.2/reference/configuration/#cfg-networking-readahead) size. Then [net_msg_max](https://www.tarantool.io/en/doc/2.2/reference/configuration/#cfg-networking-net-msg-max) number of worker fibers work on those requests from tx thread. See aa8e343fff1063693c581a90aa6b6c7927ee9e0c and a spec it links for more information.

Reads are made when [libev](http://pod.tst.eu/http://cvs.schmorp.de/libev/ev.pod) (event loop implementation we use) points that data available on a socket. libev uses epoll under hood on Linux. So here you are right, but it is about iproto requests, not HTTP.

There is [nginx upstream](https://github.com/tarantool/nginx_upstream_module/) module that allows to call to tarantool from nginx. It can be used as a layer between HTTP(S) and tarantool binary protocol.

**Comment by jobs-git** [comment]
I see, that clears it, I thought tarantool implements its own socket buffer. That means I can use the network buffer to integrate tarantool in my app. I have two follow up questions though:

1. The socket buffer is just very small, how does tarantool fit 1M req/res or more to the buffer?
2. Which part of the source code handles the request and response batching?

**Comment by Totktonada** [comment]
1. 16KiB per connection by default, can be tuned with `box.cfg{readahead = <number>}`. Optimal size depends on requests size. Let's monitor logs for 'readahead limit reached' messages.
2. src/box/iproto.cc.

**Comment by jobs-git** [comment]
Thank you for your responses. That answers all my questions. Closing this now.
