### ISSUE TITLE
Pragma results are for the wrong options

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#4680]
I have Ubuntu 18.04. I have Tarantool 2.3, pulled from source today.
I execute these SQL statements:
PRAGMA count_changes;
PRAGMA full_column_names;
I see these results:
"
tarantool> pragma count_changes;
---
- metadata:
  - name: defer_foreign_keys
    type: integer
  rows:
  - [1]
...

tarantool> pragma full_column_names;
---
- metadata:
  - name: parser_trace
    type: integer
  rows:
  - [0]
...
"
I do not believe it is correct to return defer_foreign_keys when I ask for count_changes.
I do not believe it is correct to return parser_trace when I ask for full_column_names.
I do believe in the BIble, which says: "Or what man is there of you, whom if his son ask bread, will he give him a stone?"

**Comment by ImeevMA** [comment]
@pgulutzan I think we will fix this issue when we fix #4511.

**Comment by kyukhin** [comment]
@pgulutzan #4511 is closed. Is this issue resolved?

**Comment by pgulutzan** [comment]
@kyukhin: It is resolved because pragma count_changes and pragma full_column_names have been removed.

**Comment by kyukhin** [comment]
Closing then.
