### ISSUE TITLE
lua output: display ULL/LL numbers as strings

### ISSUE THREAD

**Issue by olegrok** [tarantool/tarantool#4682]
Tarantool version: Tarantool Enterprise For Mac 2.2.1-131-gbc6ad173f

```lua
tarantool> \set output lua
true;
tarantool> -1ULL
"18446744073709551615ULL";
tarantool> 1LL
"1LL";
tarantool> 1
1;
```

Expected that LuaJIT extentions will be numbers (not strings)

**Comment by cyrillos** [comment]
After investigating details of what is going on I fear that the serpent module we're using to print output in Lua format won't be able to handle the case. These LL/ULL prefixes are handled by luajit internally and then passed to YAML serializer to process as cdata type. Then YAML serializer fetches the cdata and create `int64` or `uint64` value.

In turn serpent always operate with native Lua type (such as number). Thus even if I drop LL/ULL suffixes the numbers are interpreted as doubles
```
tarantool> \set output lua
true;
tarantool> a=-1LL
;
tarantool> a
-1;
tarantool> a=-1ULL
;
tarantool> a
1.8446744073709552e+19;
```
Which is NOT what users are familiar with. I fear the only option is to drop serpent module and implement own serializer as we have for yaml. Not sure yet, need to investigate more. I think @Totktonada is interested in the issue as well.

**Comment by olegrok** [comment]
> drop serpent module and implement own serializer

I think it's a quite big work... Could we patch "serpent"?

**Comment by cyrillos** [comment]
Hard to say. Need more time to investigate.

**Comment by cyrillos** [comment]
So I decided to start writing own serializer simply because it is interesting thing to do. I think in long term it is better due to specific types we add into (such as cdata).
```
[cyrill@uranus tarantool.git] ./src/tarantool 
Tarantool 2.3.0-275-g06aeb7687
type 'help' for interactive help
tarantool> \set output lua
lua type 1 -> boolean
field type 7
true;
tarantool> -1ULL
lua type 10 -> cdata
field type 1
18446744073709551615;
tarantool> 
```

Since the lua mode for tarantool is still in beta stage I think we can spend more time to implement own serializer and get rid of serpent completely (if only there won't be some really hard issue to resolve).

**Comment by olegrok** [comment]
Cool!

But a small note about your example. We should print `-1ULL` as `18446744073709551615ULL` I think, because simple `18446744073709551615` breaks ability to copy-paste: if you paste `18446744073709551615` again you will get `1.844674407371e+19`

So, you can check cdata type using `ffi.istype('int64_t', -1ULL)` and `ffi.typeof(-1ULL)`

**Comment by cyrillos** [comment]
I fear it is impossible with current code base (ie how we convert data).
```
[cyrill@uranus tarantool.git] ./src/tarantool 
Tarantool 2.3.0-275-g06aeb7687
type 'help' for interactive help
tarantool> -1ULL
---
- 18446744073709551615
...

tarantool> 18446744073709551615
---
- 1.844674407371e+19
...
```

But i'll take a look what i can do. thanks!

**Comment by olegrok** [comment]
@cyrillos 

Also I found an interesting case:
```lua
tarantool> {[-1ULL] = 2, [-1ULL] = 3}
---
- 18446744073709551615: 3
  18446744073709551615: 2
...

tarantool> \set output lua
true;
tarantool> {[-1ULL] = 2, [-1ULL] = 3}
{};
```

**Comment by cyrillos** [comment]
https://lists.tarantool.org/pipermail/tarantool-patches/2020-May/016618.html
