### ISSUE TITLE
Unable to connect with net.box to 2.2 if box.schema.upgrade() has not been called.

### ISSUE THREAD

**Issue by Kasen** [tarantool/tarantool#4691]
Tarantool version:
2.2.1-137

OS version:
CentOS Linux release 7.6.1810
Bug description:
If I start 2.2 as a read-only replica of 1.10, then I can't connect to this node with error:
```
error: Space '277' does not exist
```

Steps to reproduce:
1. Start tarantool 1.10
2. Start the second instance of 1.10
3. Configure replication between these instances. The second instance must be read-only.
4. Restart the second instance with tarantool 2.2
5. Try to connect to the second instance with net.box

**Comment by rosik** [comment]
@kyukhin could you please set a milestone and help with fixing that.

**Comment by Totktonada** [comment]
It is the next incarnation of #4307. We missed the case when a remote instance is run on a new tarantool version, but don't upgraded yet and so lack of `_vcollation` view.

A trivial fix is possible: we can just ignore an error of fetching _vcollation. We may try to strength this way with some kind of verification whether the error is transient or not. Don't sure this way is right, but I don't see any other one for now.
