### ISSUE TITLE
Allow to set format for tuples created by box.tuple.new

### ISSUE THREAD

**Issue by olegrok** [tarantool/tarantool#4693]
Now we can setup tuple format only if put tuple in space.

However for some development purposes it could be useful to setup format without space creation.

Possible syntax: tuple:format({...})

**Comment by Totktonada** [comment]
First, please, describe your use cases.

Second, with the way you proposed we'll create a format each time. If we'll going to implement runtime tuple creation from Lua with a format, then a `format` module (like `key_def` one) should be implemented first with at least `format.new()` function.

**Comment by olegrok** [comment]
My main use case - to test my application logic that manipulates with formatted tuples

**Comment by ImeevMA** [comment]
Can't you use frommap() for you tests?

```
tarantool> s:format()
---
- [{'name': 'i', 'type': 'integer'}, {'name': 'a', 'type': 'integer'}]
...

tarantool> t = s:frommap({i = 1, a = 2})
---
...

tarantool> t
---
- [1, 2]
...

tarantool> type(t)
---
- cdata
...

tarantool> t.i
---
- 1
...

tarantool> t.a
---
- 2
...
```

**Comment by olegrok** [comment]
> Can't you use frommap() for you tests?

frommap requires a space. As I said I don't want to call box.cfg and create any spaces

**Comment by ImeevMA** [comment]
Sorry, did not read properly. However, I think this is quite problematic at the moment. For example, max_id for tuple_format is 2^16-1. I think that if we allow the creation of a format for each tuple, this will not be enough.

**Comment by olegrok** [comment]
> max_id for tuple_format

Sorry, I don't have a complete view how this machinery works.

But I think that's a not good idea to store format for each tuple. I think it should be a local property of the tuple, as the __index metamethod. 
Could it be an "anonymous" format? Anyway when we send tuple via netbox, we convert it to simple table, so it should not be a global system schema property.

**Comment by Gerold103** [comment]
Firstly I agree that we can't create a new format for each tuple. That is insane.
Secondly, why we can't create big number of formats? - because each tuple does not have a format pointer. Tuples have format id. It is a 16bit integer. That limits format count down to UINT16_MAX.
But maybe for userspace formats we could reorganise the tuple storage. We could reserve 1 of 16 bits as a flag saying how the format is stored for this tuple. In case the flag is 0, the rest 15 bits are format id. In case the flag is 1, format is stored by pointer after struct tuple in the same memory block.

**Comment by unera** [comment]
Hi, there

Note: In discussion with @alyapunov and in PRD we decided not to patch `box.tuple.new`, but add a new method `box.tuple.custom`. Please, recheck the document.

we planned the functional for several cases.

### First: Avoid loosing tuple format during Lua-call.

example:

```lua
function my_lua(...)
    return box.space.S,index.I:select(...)
end
```

a remote host wants to restore tuple format

### Second: Avoid loosing tuple format during lua-call while passing cascade of routers.

User -> router1 -> router2 -> lua_call -> return space:select

A user wants to restore tuple format.


### Third: make non-storable tuple lists

For example: A user (Lua-code) wants to return 100 tuples that are result of JOIN, MERGE, etc

example

```lua
local lst1 = space1:select()
local lst2 = space2:select()

local res = {}
for no, t1 in lst do
    table.insert(res, box.tuple.create({t1.id, t1.name, lst2[no].surname}, { FORMAT })
end
```

**Comment by ImeevMA** [comment]
@unera I believe this question has already been answered over three years ago.

**Comment by olegrok** [comment]
@unera this issue also could be interesting in context of https://github.com/tarantool/tuple-merger/issues/16

**Comment by unera** [comment]
> @unera this issue also could be interesting in context of https://github.com/tarantool/tuple-merger/issues/16

hi

there is the fourth goal

we want to simplify connectors and avoid to load schemas and format registry.

in the project, a client could pass iproto requests without schema downloading.
yes, the server could keep format registry, but doesn't have to.
