### ISSUE TITLE
Single rpm/deb repository for different tarantool versions

### ISSUE THREAD

**Issue by printercu** [tarantool/tarantool#4699]
## Issues

1) Current repositories contain packages built from latest commits on each release branch. This is not reliable because every commit is not tested the same way as tagged one (actually these are dev builds). There should be repo with build from tagged commits only (stable builds).
2) Rocks (lua libs) packed into os packages (e.g. http, cartridge, etc.) must be pushed to the large list of repos (OS name x OS version x Tarantool version). Actually they does not depend on anything from this list. It'll be much better to push these packages to as few repos as possible. It'll be great if packages should not be re-published once new OS version is released.
3) Naming of repos is inconsistent: 1_10 for 1.9, 2x for 2.1 (current stable), 2_2 for 2.2.

## Proposal

1) For every pair of (OS name, OS version) use two repos:

- stable channel with builds from tagged commits only
- dev/nightly channel with builds from release branches

There are 2 approaches for naming packages in such repositories:

- use same `tarantool` package name for all branches and versions. This can lead to unintended updates between versions (even major) when user does not pin packages.
- use different package name, e.g. `tarantool1.10, tarantool2.1`. Both deb and rpm packages provides option for virtual packages/capabilities. This allows to "pin" to specific version easily while not complicating defining dependencies from other packages (these packages would still depend on `tarantool` and specific versions would provide `tarantool`).

I suggest using 2nd approach if there is no obvious downsides.

2) As we are deciding to migrate from packagecloud service to self-hosted solution, it should be considered to use same pipeline for publishing tarantool as well deb/rpm-packages for luarocks. https://github.com/tarantool/rocks.tarantool.org can  be extended to handle rpm and deb packages along with luarocks. Different packages can be served either at different paths (`/luarocks/`, `/deb/`) or at different subdomains(`luarocks.`, `deb.`). (luarocks may not work with path prefixes).

3) Let's decide if it's possible to have repositories with rocks which are automatically merged into other ones. This way rocks packages should only be pushed to single `deb` and `rpm` repo and they would be available in repos for all OS and their versions (even new ones).

**Comment by Totktonada** [comment]
> 1. use same `tarantool` package name <...>
> 2. use different package name, e.g. `tarantool1.10, tarantool2.1` <...>
>
> I suggest using 2nd approach if there is no obvious downsides.

There are two points that direct us to going the first way.

* This naming may give a user false expectation that those packages can be installed simultaneously into different locations on a file system (like PostgreeSQL does).
* Inability to smoothly update tarantool, say, from 1.10 to 2.2: one need to delete 1.10 (that will lead to removing of all dependent packages) and then install 2.2.

More broad discussion is available here:

* https://lists.tarantool.org/pipermail/tarantool-patches/2020-January/013609.html
* https://lists.tarantool.org/pipermail/tarantool-patches/2020-January/013676.html
* https://lists.tarantool.org/pipermail/tarantool-patches/2020-January/013736.html

**Comment by Totktonada** [comment]
Closed as won't fix.
