### ISSUE TITLE
Cases when on_shutdown() trigger is not executed

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#4703]
Tarantool version: 2.3.0-235-g5d2105bf1.
OS version: Linux.

Run tarantool interactively, set on_shutdown trigger and send EOF:

```
$ tarantool
Tarantool 2.3.0-235-g5d2105bf1
type 'help' for interactive help
tarantool> box.ctl.on_shutdown(function() local fio = require('fio') fio.open('i_am_died.txt', {'O_CREAT', 'O_TRUNC', 'O_WRONLY'}):close() end)
---
- 'function: 0x4174eb20'
...

tarantool> <hit Ctrl+D>
$ ls -l i_am_died.txt
ls: cannot access 'i_am_died.txt': No such file or directory
```

The trigger is not fired.

Another way to run the case:

```
$ tarantool -i <<< "box.ctl.on_shutdown(function() local fio = require('fio') fio.open('i_am_died.txt', {'O_CREAT', 'O_TRUNC', 'O_WRONLY'}):close() end)"
$ ls -l i_am_died.txt
ls: cannot access 'i_am_died.txt': No such file or directory
```

If we'll call fiber.sleep() at end of the script and kill it by SIGTERM, then, again, the trigger will not be executed:

```
$ tarantool -i <<< "box.ctl.on_shutdown(function() local fio = require('fio') fio.open('i_am_died.txt', {'O_CREAT', 'O_TRUNC', 'O_WRONLY'}):close() end) require('fiber').sleep(100)" & kill %1
[1] 2381
$ 
[1]+  Terminated              tarantool -i <<< "box.ctl.on_shutdown(function() local fio = require('fio') fio.open('i_am_died.txt', {'O_CREAT', 'O_TRUNC', 'O_WRONLY'}):close() end) require('fiber').sleep(100)"
$ ls -l i_am_died.txt
ls: cannot access 'i_am_died.txt': No such file or directory
```

However if we'll send SIGTERM from an inveractive console w/o fiber.sleep(), the trigger will be executed:

```
$ tarantool
Tarantool 2.3.0-235-g5d2105bf1
type 'help' for interactive help
tarantool> box.ctl.on_shutdown(function() local fio = require('fio') fio.open('i_am_died.txt', {'O_CREAT', 'O_TRUNC', 'O_WRONLY'}):close() end)
---
- 'function: 0x416949f0'
...

tarantool> ffi = require('ffi')
---
...

tarantool> ffi.cdef([[ int getpid(void); void kill(int, int); ]])
---
...

tarantool> ffi.C.kill(ffi.C.getpid(), 15)
---
...

tarantool>
$ ls -l i_am_died.txt
---------- 1 alex users 0 Dec 24 15:23 i_am_died.txt
```

The trigger also works if we'll call os.exit():

```
$ tarantool -i <<< "box.ctl.on_shutdown(function() local fio = require('fio') fio.open('i_am_died.txt', {'O_CREAT', 'O_TRUNC', 'O_WRONLY'}):close() end) os.exit()"
$ ls -l i_am_died.txt
---------- 1 alex users 0 Dec 24 15:24 i_am_died.txt
```

Don't sure whether it is a bug or expected behaviour.

**Comment by Gerold103** [comment]
Seems like the SIGTERM cases work, regardless of having `fiber.sleep()`. Could you please check again, maybe it was fixed already? Otherwise it works on Mac only.

**Comment by Gerold103** [comment]
Talking of EOF: https://www.tarantool.io/en/doc/2.2/reference/reference_lua/box_ctl/#lua-function.box.ctl.on_shutdown
Seems like fire on EOF is not documented. But for me it looks strange. EOF is in fact the most normal termination way, and it does not fire `on_shutdown` somewhy. Probably it was just forgotten.
@kyukhin should make a decision.

**Comment by Totktonada** [comment]
I run the third snippet again on Linux on 2.4.0-82-gd8a9f1d9c and the behaviour is the same: the file was not created.

I think we should fire the trigger on EOF, otherwise the behaviour is counter-intuitive.

**Comment by Gerold103** [comment]
I tried the third snippet on Linux (5.0.0-23-generic). It works. Both if I run from console, and if I run as a file in argv[1] to tarantool executable. Please, check again. Maybe your file is not created by some other reason. Try doing `print` in a trigger. Check access rights (you create a file without any rights now). I can't reproduce your problem with `fiber.sleep + SIGTERM` on any system.

**Comment by Gerold103** [comment]
Also try calling fsync.

**Comment by romanhabibov** [comment]
@Totktonada I can't reproduce. The file has created (trigger is executed).

**Comment by Totktonada** [comment]
Added `sync` before `kill %1` and found that it actually works. Okay, it was due to timings on my system.
