### ISSUE TITLE
box: make error "'... field type does not match..." more informative

### ISSUE THREAD

**Issue by ImeevMA** [tarantool/tarantool#4707]
At the moment, the error looks like this:
```
tarantool> s:insert({1.1})
---
- error: 'Tuple field 1 type does not match one required by operation: expected integer'
...
```

This would be more informative if it would give us information about the type of value that was inserted. For example:
```
tarantool> s:insert({1.1})
---
- error: 'Tuple field 1 type does not match one required by operation: expected integer, got double'
...
```

The same about replace(), update() and so on.

**Comment by knazarov** [comment]
Also, if space format is set, show the column name here as well. It is frustrating to figure it out every time.
