### ISSUE TITLE
Provide a user friendly frontend for _session_settings space

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#4711]
After #4511 is finished, we have `_session_settings` virtual space to access and change session settings. It looks like this in Lua:
```Lua
box.space._session_settings:update('sql_recursive_triggers', {{'=', 2, false}})
```
And like this in SQL:
```SQL
UPDATE "_session_settings" SET "value" = false WHERE "name" = 'sql_full_column_names'
```
And clearly this is quite hard to use. I propose to add an API to encapsulate _session_settings update. For example:
```Lua
box.session.setting.<name> = <value>
```
```SQL
SESSION SET <name> = <value>;
```
Or just `SET` in SQL. Or return the session settings back to `PRAGMA`.

**Comment by Totktonada** [comment]
I had quite similar thoughts: https://lists.tarantool.org/pipermail/tarantool-discussions/2019-December/000009.html.

However in my proposal I suggested to access a session setting directly rather then perform msgpack encoding and decoding on each read or change. I don't sure whether an access to a session setting may be a hot spot, but it looks quite similar to `box.cfg.<option>` values, which may be read on each request (say, `box.cfg.read_only`) or used in [metrics](https://github.com/tarantool/metrics/blob/f121cafd241b4b5fe1bb5cbfb8eceb7c46ddc480/metrics/default_metrics/tarantool/system.lua#L9). Maybe after #4205 (read only sessions support) it will matter more.

(Just thoughts around. I had no intention to insist on a certain way to implement it.)

**Comment by Gerold103** [comment]
We still can access them directly, via that new interface. Good thing is that it will encapsulate whatever we choose.

**Comment by pgulutzan** [comment]
This has been discussed before in thread Re: [Tarantool-patches] [PATCH v3 0/5] Replace control pragmas by SET. I thought UPDATE in SQL was good, I didn't notice at the time that others thought a new SQL statement was good.

**Comment by Totktonada** [comment]
@pgulutzan I asked users in Russian and English Telegram channels to like or dislike the proposal. The decision still on Kirill Yukhin, but this way we'll collect a bit more information.

Comments are welcome!

**Comment by Totktonada** [comment]
BTW, we can reflect our usual way to configure things in Lua:

* Read: \<foo\>.cfg.\<bar\> (\<foo\> examples: `box`, `json`, `yaml`, `msgpack`).
* Update: \<foo\>.cfg{\<bar\> = \<value\>}.

In our case \<foo\> is `box.session`.

**Comment by Korablev77** [comment]
Current way of accessing sessions settings looks ok to me. I'd only consider adding shortcut for SQL update as Vlad suggests in this issue.

**Comment by tsafin** [comment]
I'm late here on this party, but I very much dislike proposed syntax of

	SETTING SET configuration_name = value;

It feels not SQL-ish, and I see no much value introducing new statement 
while there is still SET statement available. 

Why we could not simply use something like:
	SET box.session.settings.name = value;
?

* Here is the PostgreSQL way - https://www.postgresql.org/docs/current/config-setting.html#CONFIG-SETTING-SQL-COMMAND-INTERACTION
* Here is MySQL way - https://dev.mysql.com/doc/refman/5.7/en/set-variable.html#set-variable-system-variables (see awkward @@session notation. Which is understandable, but would be not very much natural for us)

**Comment by pgulutzan** [comment]
We don't say SETTING SET configuration = value.
We update box_space._session_settings.
https://www.tarantool.io/en/doc/2.3/reference/reference_lua/box_space/#box-space-session-settings
If you have access to mailing list tarantool-patches@dev.tarantool.org,
you can read the thread
Re: [Tarantool-patches] [PATCH v3 0/5] Replace control pragmas by SET
