### ISSUE TITLE
pass void instead of empty arg list

### ISSUE THREAD

**Issue by cyrillos** [tarantool/tarantool#4718]
For functions which take no arguments better to pass `void` instead of empty arguments list (which cause compilers such as gcc to pass zero as a number of arguments).

**Comment by cyrillos** [comment]
@Totktonada @kyukhin I do not set any milestones here, the reason for this issue just to not forget to clean up these places in the code.

**Comment by Totktonada** [comment]
Relevant: 11dec7dd721222e586d6358b1c8db9a5e9189191.

**Comment by cyrillos** [comment]
https://lists.tarantool.org/pipermail/tarantool-patches/2020-July/018184.html
