### ISSUE TITLE
automatic performance regression testing

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#472]
1. Create a repository for the new project: tarantool/microb
(automatic regression testing micro-benchmarks)

1. Benchmark file format.
A micro-benchmark is a Lua module which has 3 functions: prepare(), run(), cleanup().
All benchmarks are located in artmicro/benchmark/

1. A measurement script. 
A measurement script installs a tarantool package, runs the suite of micro-benchmarks,
and outputs the timing of every benchmark (stores it in a Tarantool database).

1. A Tarantool database with execution history
This database stores results of all benchmarks, and is also an HTTP server that serveres JSON data
with benchmark results to be processed by js-chart.

**Comment by Sulverus** [comment]
Microbench updated and integrated with tarantool buildbot: http://bench.farm.tarantool.org/

**Comment by kostja** [comment]
This is done actually.
