### ISSUE TITLE
fiber: Set diag error on mprotect failure

### ISSUE THREAD

**Issue by cyrillos** [tarantool/tarantool#4722]
@Totktonada reported that on `mprotect` call in fibers the caller is expecting diag error to be set.

Here is a reference to the code example
https://github.com/tarantool/memcached/blob/e593b177c663bbbc71afc7af5eb732e58b6c62a4/memcached/internal/expiration.c#L112-L118

**Comment by cyrillos** [comment]
https://lists.tarantool.org/pipermail/tarantool-patches/2020-January/013551.html

Lets wait for tests being passed.

**Comment by olegrok** [comment]
Related https://github.com/tarantool/tarantool/issues/4720

**Comment by cyrillos** [comment]
Updated version
https://lists.tarantool.org/pipermail/tarantool-patches/2020-January/013632.html

**Comment by Totktonada** [comment]
This issue comes initially from https://github.com/tarantool/memcached/issues/52 , where I observed that fiber_new_ex() does not set an error into the fiber's diagnostics area.
