### ISSUE TITLE
Net.box operations on local spaces are still replicated

### ISSUE THREAD

**Issue by rosik** [tarantool/tarantool#4729]
### Tarantool version

All I guess (checked on 1.10.4, 2.2.2-9)

### Bug description:

Documentation states:

```
Data change operations on replication-local spaces (spaces created with
is_local = true) are written to the WAL but are not replicated.
```

Nevertheless, operations performed over `net.box` are still replicated and may even cause a replication conflict.

### Steps to reproduce:

Set up two replicas (say 3301, 3302) with local space:

```lua
-- 3301
box.cfg({listen = 3301})
box.schema.user.grant('guest', 'super')
box.schema.space.create('test', {is_local = true})
box.space.test:create_index('pk', {parts = {1, 'unsigned'}})
```

```lua
-- 3302
box.cfg({listen = 3302, replication = {3301}})
```

Then do

```lua
require('net.box').connect('localhost:3301').space.test:insert({1})
```

It'll be inserted on both replicas:

```console
tarantool> require('net.box').connect('localhost:3301').space.test:select()
---
- - [1]
...
tarantool> require('net.box').connect('localhost:3302').space.test:select()
---
- - [1]
...
```

P.S. It doesn't happen with netbox call

```console
tarantool> require('net.box').connect('localhost:3301'):call('box.space.test:insert', {{2}})
---
- [2]
...

tarantool> require('net.box').connect('localhost:3301').space.test:select()
---
- - [1]
  - [2]
...

tarantool> require('net.box').connect('localhost:3302').space.test:select()
---
- - [1]
...
```

**Comment by kostja** [comment]
% git diff
diff --git a/src/box/txn.c b/src/box/txn.c
index 963ec8eeb..360b2a0b6 100644
--- a/src/box/txn.c
+++ b/src/box/txn.c
@@ -72,12 +72,11 @@ txn_add_redo(struct txn *txn, struct txn_stmt *stmt, struct request *request)
                /* Initialize members explicitly to save time on memset() */
                row->type = request->type;
                row->replica_id = 0;
-               row->group_id = stmt->space != NULL ?
-                               space_group_id(stmt->space) : 0;
                row->lsn = 0;
                row->sync = 0;
                row->tm = 0;
        }
+       row->group_id = stmt->space != NULL ? space_group_id(stmt->space) : 0;
        row->bodycnt = xrow_encode_dml(request, &txn->region, row->body);
        if (row->bodycnt < 0)
                return -1;
