### ISSUE TITLE
Segfault at applier_subscribe()

### ISSUE THREAD

**Issue by nmoldav** [tarantool/tarantool#4730]
Tarantool version: 2.2.2-11-gb89c62bd7

OS version: Fedora Server 30 - kernel  5.1.19-300.fc30.x86_6

Bug description:  We're running 10 replicas in a mesh configuration.  All replicas are read-write.  They are located in 5 different data centers in different cities, 2 replicas per data center.  As we are testing Tarantool, the only queries run by the application are UPSERTs.  We are not doing any SELECTs yet, except for a few done by Nagios and collectd for monitoring purposes.  

After having some replication issues with 2.1.3 we decided to give 2.2.2 a try.  Today we deleted the databases in all replicas and started afresh with empty spaces.  After starting sending UPSERTs, we began to see segfaults in almost all servers.  The replicas with more traffic segfault more often.  The worst server had 10 crashes in 7 hours.  

We're doing between 2K and 3K UPSERTs per second distributed over 10 spaces.  All spaces have an unsigned integer primary key, and then another unsigned int (timestamp) plus a string value.  All spaces use the vinyl engine.

Steps to reproduce:  we cannot reproduce it with certainty.  The error happens when UPSERT traffic is on.  If we disable the UPSERTs, the error does not happen.  In a couple of servers with very little traffic we have seen no segfaults so far.

[backtrace.txt](https://github.com/tarantool/tarantool/files/4074663/backtrace.txt)
[box.txt](https://github.com/tarantool/tarantool/files/4074664/box.txt)

Some cores (500MB each):
http://demos.e-planning.net/tarantool/core.36039.gz
http://demos.e-planning.net/tarantool/core.10738.gz

**Comment by kyukhin** [comment]
@nmoldav do you have a reproducer? Could you please ping me in Telegram (@kyukhin), so I can try to help you to extract a testcase.

**Comment by nmoldav** [comment]
(gdb) info stack
#0  0x00007f0556da9e75 in raise () from /lib64/libc.so.6
#1  0x00007f0556d94895 in abort () from /lib64/libc.so.6
#2  0x0000000000426adc in sig_fatal_cb (signo=<optimized out>, siginfo=<optimized out>, context=<optimized out>) at /build/usr/src/debug/tarantool-2.2.2.11/src/main.cc:300
#3  <signal handler called>
#4  0x00000000004ee2af in error_raise (e=0x0) at /build/usr/src/debug/tarantool-2.2.2.11/src/lib/core/diag.h:223
#5  diag_raise () at /build/usr/src/debug/tarantool-2.2.2.11/src/lib/core/diag.h:223
#6  0x00000000004eef77 in applier_subscribe (applier=0x20341f0) at /build/usr/src/debug/tarantool-2.2.2.11/src/box/applier.cc:910
#7  0x00000000004f00c8 in applier_f(typedef __va_list_tag __va_list_tag *) (ap=<error reading variable: value has been optimized out>)
    at /build/usr/src/debug/tarantool-2.2.2.11/src/box/applier.cc:959
#8  0x0000000000425f61 in fiber_cxx_invoke(fiber_func, typedef __va_list_tag __va_list_tag *) (f=<optimized out>, ap=<optimized out>)
    at /build/usr/src/debug/tarantool-2.2.2.11/src/lib/core/fiber.h:672
#9  0x000000000052fc00 in fiber_loop (data=<optimized out>) at /build/usr/src/debug/tarantool-2.2.2.11/src/lib/core/fiber.c:694
#10 0x00000000006dada4 in coro_init () at /build/usr/src/debug/tarantool-2.2.2.11/third_party/coro/coro.c:110

Different rows from different segfaults - all type 9 (UPSERT):
(gdb) print *((struct applier_tx_row *) rows->first)
$1 = {next = {next = 0x0}, row = {type = 9, replica_id = 25, group_id = 0, sync = 0, lsn = 5861223, tm = 1579245892.2022591, tsn = 5861223, is_commit = true, bodycnt = 1, 
    schema_version = 0, body = {{iov_base = 0x7f0547c6e04a, iov_len = 99}, {iov_base = 0x0, iov_len = 0}}}}
(gdb) print (*((struct applier_tx_row *) rows->first))->row
$2 = {type = 9, replica_id = 24, group_id = 0, sync = 0, lsn = 7982100, tm = 1579245037.377569, tsn = 7982100, is_commit = true, bodycnt = 1, schema_version = 0, body = {{
      iov_base = 0x7f018aa3a04a, iov_len = 117}, {iov_base = 0x0, iov_len = 0}}}
(gdb) print *((struct applier_tx_row *) rows->first)
$1 = {next = {next = 0x0}, row = {type = 9, replica_id = 25, group_id = 0, sync = 0, lsn = 5562967, tm = 1579243682.6770141, tsn = 5562967, is_commit = true, bodycnt = 1, 
    schema_version = 0, body = {{iov_base = 0x7fa265c6a04a, iov_len = 117}, {iov_base = 0x0, iov_len = 0}}}}
(gdb) print *((struct applier_tx_row *) rows->first)
$1 = {next = {next = 0x0}, row = {type = 9, replica_id = 18, group_id = 0, sync = 0, lsn = 29114693, tm = 1579235805.7342145, tsn = 29114693, is_commit = true, bodycnt = 1, 
    schema_version = 0, body = {{iov_base = 0x7f3abfb8404a, iov_len = 89}, {iov_base = 0x0, iov_len = 0}}}}

**Comment by cyrillos** [comment]
It would be awesome if reporter could test the patch
https://lists.tarantool.org/pipermail/tarantool-patches/2020-January/013664.html

**Comment by cyrillos** [comment]
Updated series
https://lists.tarantool.org/pipermail/tarantool-patches/2020-January/013666.html

**Comment by nmoldav** [comment]
I tried 2.2.2-13 and it crashed again.  
[gdb.txt](https://github.com/tarantool/tarantool/files/4077592/gdb.txt)

This is the core file:
http://demos.e-planning.net/tarantool/core.34073.gz

**Comment by Totktonada** [comment]
Strictly speaking it is not 2.2.2-13, it is 2.2.2-11 with Cyrill's patchset upward.

**Comment by nmoldav** [comment]
I downloaded tarantool-2.2.2.13-1.fc30.x86_64.rpm which Cyrill sent me and when it starts it prints

2020-01-17 16:02:12.991 [43394] main/102/aspu C> Tarantool 2.2.2-13-g58c786516

This is still crashing just like 2.2.2-11

**Comment by Totktonada** [comment]
I'm unable to inspect the core file with the libraries you provided: there are missing ones and gdb reports mismatch for libthread:

```
(gdb) info sharedlibrary
From                To                  Syms Read   Shared Object Library
                                        No          /lib64/libicuuc.so.63
                                        No          /lib64/libreadline.so.8
                                        No          /lib64/libz.so.1
                                        No          /lib64/libssl.so.1.1
                                        No          /lib64/libcrypto.so.1.1
0x00007f8738c90270  0x00007f8738c91039  Yes (*)     root/lib64/libdl.so.2
0x00007f8738c72b30  0x00007f8738c80cd5  Yes (*)     root/lib64/libpthread.so.0
                                        No          /lib64/libgcc_s.so.1
                                        No          /lib64/libunwind-x86_64.so.8
                                        No          /lib64/libunwind.so.8
                                        No          /lib64/libgomp.so.1
                                        No          /lib64/libicui18n.so.63
                                        No          /lib64/libstdc++.so.6
                                        No          /lib64/libm.so.6
0x00007f8738416670  0x00007f873856186f  Yes (*)     root/lib64/libc.so.6
                                        No          /lib64/libicudata.so.63
                                        No          /lib64/libtinfo.so.6
0x00007f8739257110  0x00007f8739276674  Yes (*)     root/lib64/ld-linux-x86-64.so.2
                                        No          /lib64/libnss_files.so.2
                                        No          /lib64/libnss_systemd.so.2
                                        No          /lib64/librt.so.1
(*): Shared library is missing debugging information.
```

```
warning: .dynamic section for "root/lib64/libpthread.so.0" is not at the expected address (wrong library or version mismatch?)
```

I trying to reproduce a right environment in fedora:30 docker container, but no luck at the moment. (You can contact me in Telegram, nickname @Totktonada, if you need help with collecting necessary libraries.)
