### ISSUE TITLE
assert failure in txn_rollback

### ISSUE THREAD

**Issue by cyrillos** [tarantool/tarantool#4744]
Need to write a proper testcase and make sure that preliminary patch I send does a proper fix.

https://lists.tarantool.org/pipermail/tarantool-patches/2020-January/013768.html

**Comment by kyukhin** [comment]
We still need a test case.

**Comment by cyrillos** [comment]
> We still need a test case.

Yes, that's why in next message I asked to drop the former patch. Actually once applier it triggers another assert. I need to address both issues but only once I finish with diag_raise problem.

**Comment by cyrillos** [comment]
It is dup for #4776
