### ISSUE TITLE
sequence:currval()

### ISSUE THREAD

**Issue by parihaaraka** [tarantool/tarantool#4752]
people really need sequence:currval() or read-only workaround
* and actualized man in any case

**Comment by olegrok** [comment]
Seems that ":get" method was removed here - https://github.com/tarantool/tarantool/commit/3ff1f1e36e14381c0ebb5862943d4da281254767#diff-0e3513c6b61a1b1395ec235869120107

@kyukhin 

May be we should simply revert this commit?
