### ISSUE TITLE
SQL SELECT FROM space with map-data in one field generates an error

### ISSUE THREAD

**Issue by dimtos** [tarantool/tarantool#4758]
Tarantool version:
2.3.0-236-g6da9d3953

OS version:
Debian 9

Bug description:
pricing:
- name: id #primary index
  type: unsigned
  is_nullable: false
- name: title
  type: string
  is_nullable: true
- name: type
  type: unsigned
  is_nullable: false
- name: conditions
  type: map
  is_nullable: true
- name: value
  type: scalar
  is_nullable: false
- name: priority
  type: number
  is_nullable: true

box.space.pricing:insert{ nil, 'Any title', 1, { supplier=22 }, 12, 2 }
box.execute([[ SELECT * FROM "pricing" ORDER BY "priority" LIMIT 1 ]])
But!!! If sorting by primary index it's ok.

Steps to reproduce:
see bug description.

Optional (but very desirable):
* coredump
* backtrace
* netstat

**Comment by Korablev77** [comment]
Should be fixed after https://github.com/tarantool/tarantool/issues/4762 and https://github.com/tarantool/tarantool/issues/4763 are resolved.

**Comment by ImeevMA** [comment]
Now it should work fine:
```
tarantool> box.execute([[CREATE TABLE pricing(id UNSIGNED PRIMARY KEY, title STRING, type UNSIGNED, conditions MAP, value SCALAR, priority NUMBER);]])
---
- row_count: 1
...

tarantool> box.execute([[INSERT INTO pricing VALUES(1, 'Any title', 1, {'supplier' : 22}, 12, 2);]])
---
- row_count: 1
...

tarantool> box.execute([[SELECT * FROM pricing ORDER BY priority LIMIT 1;]])
---
- metadata:
  - name: ID
    type: unsigned
  - name: TITLE
    type: string
  - name: TYPE
    type: unsigned
  - name: CONDITIONS
    type: map
  - name: VALUE
    type: scalar
  - name: PRIORITY
    type: number
  rows:
  - [1, 'Any title', 1, {'supplier': 22}, 12, 2]
...
```

Closed by https://github.com/tarantool/tarantool/commit/1364629ecf3c939d16d3f51e221854f4bbf7ba61
