### ISSUE TITLE
box.prepare doesn't correctly parse named placeholders

### ISSUE THREAD

**Issue by rybakit** [tarantool/tarantool#4760]
Tarantool version: 2.3.1-2-g92750c828
OS version: Fedora 30

**Steps to reproduce:**

```lua
box.execute([[ DROP TABLE IF EXISTS prepare_execute; ]])
box.execute([[ CREATE TABLE prepare_execute (id INTEGER PRIMARY KEY, name VARCHAR(50)); ]])
s = box.prepare([[ INSERT INTO prepare_execute VALUES(:id, :name); ]])

s
---
- stmt_id: 1648168926
  execute: 'function: 0x416cbdc0'
  params:
  - name: '?'
    type: ANY
  - name: :id
    type: ANY
  unprepare: 'function: 0x416cbde8'
  param_count: 2
...
```
*Note the unexpected `?` instead of `:name` in the `params` property*.

**Comment by rybakit** [comment]
@Korablev77 I wonder if this issue is somehow related to https://github.com/tarantool/doc/issues/1096?

**Comment by Korablev77** [comment]
No, it is not related at all. Current issue is simply a bug in implementation of :prepare() feature.

**Comment by rybakit** [comment]
@Korablev77 @kyukhin  will the fix be included in 2.3.2?

**Comment by Korablev77** [comment]
@rybakit Yep, I pushed this patch to 2.3: https://github.com/tarantool/tarantool/commit/a06472875474f1de2ee38a66f5168b562fdc3a33

**Comment by rybakit** [comment]
thanks!
