### ISSUE TITLE
sql: introduce type <MAP>

### ISSUE THREAD

**Issue by Korablev77** [tarantool/tarantool#4763]
To finish SQL integration with Tarantool NoSQL, we have to allow users to interact with all existing field types. Otherwise, users are not able to operate on spaces containing at least one of field with type which is unsupported (e.g. see https://github.com/tarantool/tarantool/issues/4758 and https://github.com/tarantool/tarantool/issues/4757). One of those types is MAP, which is not described in ANSI SQL. To access array elements in first implementation iteration it is suggested to consider built-in helpers like:
`map_get('field_name', 'element_index');`
`map_set('field_name', 'element_index', 'new_value');`
`map_create('name', 'value', ...);`
```
CREATE TABLE t (i INT PRIMARY KEY, a ARRAY);
INSERT INTO t VALUES (1, map_create('a', 1, 'b', 2,));
INSERT INTO t VALUES (2, map_create('b', 2, 'a', 'asd', 5, 1));
SELECT * FROM t;
---
- - [1, {'a': 1, 'b': 2}]
  - [2, {'b': 2, 'a': 'asd', 5: 1}]
...
SELECT a FROM t;
---
- - [{'a': 1, 'b': 2}]
  - [{'b': 2, 'a': 'asd', 5: 1}]
SELECT map_get(a, 'a');
- - [1]
  - ['asd']
SELECT map_get(a, 5) FROM t; 
- - [NULL]
  - [1]
```
Alternatively `map_get() `may accept third optional argument indicating default value in case map lacks given key. Note that throwing an error in this case is likely to be unacceptable since map may feature different sets of keys.
```
UPDATE t SET map_set(a, 'a', 'abc') WHERE map_get(a, 'a') = 2;
...
```
`map_get()` and `map_set()` can be replaced with `{ }` indexation operation later.

This interface is quite similar to one suggested for ARRAY type: https://github.com/tarantool/tarantool/issues/4762

For the sake of performance these functions can be implemented as separate VDBE opcodes.

Values of map type shouldn't be implicitly or explicitly comparable with values of other types. To compare map values between each other one can use `map_compare('array_lhs', 'array_rhs')` (or we can simply overload equality operator). As for internal representation maps can be held packed (i.e. encoded with MP_BIN flag) in `struct Mem` with both `SQL_SUBTYPE_MAP` and  `SQL_SUBTYPE_MSGPACK` auxiliary subtypes.

**Comment by pgulutzan** [comment]
map_get('field-name', 'element-index') does the same thing as _decode("field-name", 'element-index'), which is an example in the Tarantool manual for "Calling Lua routines from SQL" https://www.tarantool.io/en/doc/2.3/reference/reference_sql/sql/#calling-lua-routines-from-sql so, if this feature request is accepted, I can add in the manual that _decode will be superseded.

**Comment by Korablev77** [comment]
@pgulutzan Suggestion above is my personal vision of feature, I did not discussed it with other teammates. If @kyukhin is okay with it, manual can be extended with this remark.
