### ISSUE TITLE
Index/constraint is not always found

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#4767]
I have Ubuntu 18.04. I have Tarantool 2.3, pulled from source today.

I execute these requests:

box.execute([[CREATE TABLE t1 (s1 INTEGER PRIMARY KEY);]])
box.execute([[PRAGMA index_list(T1);]])
box.execute([[ALTER TABLE t1 ADD CONSTRAINT "pk_unnamed_T1_1" CHECK (0=0);]])
box.execute([[ALTER TABLE t1 DROP CONSTRAINT "pk_unnamed_T1_1";]])
box.execute([[PRAGMA index_info(T1.pk_unnamed_T1_1);]])

The PRAGMA index_list tells me pk_unnamed_T1_1 exists.
The ALTER TABLE t1 ADD CONSTRAINT tells me pk_unnamed_T1_1 exists.
The ALTER TABLE t1 DROP CONSTRAINT tells me pk_unnamed_T1_1 does not exist.
The PRAGMA index_info tells me pk_unnamed_T1_1 does not exist.

Part of this is documented behaviour, the manual says "Tarantool only looks for names of foreign-key constraints", and the manual says "Tarantool throws an error if the index ... is an automatically created index.". But I am being told the constraint or index does not exist, so at least the error message is wrong.

**Comment by Korablev77** [comment]
@pgulutzan `index_info` does uppercase name. `box.execute([[PRAGMA index_info(T1."pk_unnamed_T1_1");]])` works fine. `DROP CONSTRAINT` now works only for FK constraints, we are working on patch which will allow to drop any type of constraint (coming soon I guess).

**Comment by pgulutzan** [comment]
@Korablev77: I'm not sure I understand what you mean by "does uppercase name", since box.execute([[PRAGMA index_info("t1"."pk_unnamed_T1_1");]]) returns nothing (and shouldn't, because ""s shouldn't cause search of upper(name)). We know that DROP CONSTRAINT works only for FK constraints, I acknowledged that, but the issue is that we're told the constraint does not exist, please look at the error message: "Constraint pk_unnamed_T1_1 does not exist".

**Comment by Korablev77** [comment]
@pgulutzan On current master branch:

```
tarantool> box.execute([[CREATE TABLE t1 (s1 INTEGER PRIMARY KEY);]])
---
- row_count: 1
...

tarantool> box.execute([[PRAGMA index_list(T1);]])
---
- metadata:
  - name: seq
    type: integer
  - name: name
    type: text
  - name: unique
    type: integer
  rows:
  - [0, 'pk_unnamed_T1_1', 1]
...

tarantool> box.execute([[ALTER TABLE t1 ADD CONSTRAINT "pk_unnamed_T1_1" CHECK (0=0);]])
---
- null
- PRIMARY KEY constraint 'pk_unnamed_T1_1' already exists in space 'T1'
...

tarantool> box.execute([[ALTER TABLE t1 DROP CONSTRAINT "pk_unnamed_T1_1";]])
---
- row_count: 1
...

tarantool> box.execute([[PRAGMA index_info(T1.pk_unnamed_T1_1);]])
---
- metadata:
  - name: seqno
    type: integer
  - name: cid
    type: integer
  - name: name
    type: text
  - name: desc
    type: integer
  - name: coll
    type: text
  - name: type
    type: text
  rows: []
...
```
Now it looks absolutely consistent. May I close the issue?

**Comment by pgulutzan** [comment]
@Korablev77: Yes, thank you.
