### ISSUE TITLE
pairs() is broken

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#4770]
Tarantool version:
All versions, having `build: enables LUAJIT_ENABLE_PAIRSMM by default`.

OS version:
Confirmed on Mac, didn't check on others.

Bug description:
`pairs()` returns nothing for `box.space` objects, even though they are just tables.

Steps to reproduce:
```Lua
box.cfg{}
s = box.schema.create_space('test')
keys = {}
for k, v in pairs(s) do keys[k] = true end
keys

keys = {}
s = {key1 = 1, key2 = 2}
for k, v in pairs(s) do keys[k] = true end
keys
```
The first `keys` is empty, although it should not be. The second `keys` is fine, and contains correct keys. Everything worked as intended before this commit, which was added to all versions, unfortunately.
```
commit 1d85144a9b4bbbb026402848efde1ab98bf72633
    build: enables LUAJIT_ENABLE_PAIRSMM by default
    
    Turns on LUAJIT_ENABLE_PAIRSMM flag for tarantool build.
    Now __pairs/__ipairs metamethods are available.
    
    Closes #4650
```
This is critical for VShard, because it used `table.deepcopy`, which uses `pairs` in one of its rebalancer routines.

**Comment by olegrok** [comment]
> The first keys is empty, although it should not be.

I think it's because your space is empty. I suppose that after this patch `pairs(space)` works as `space:pairs()`

```lua
tarantool> box.space.test:replace{1, 2, 3}
---
- [1, 2, 3]
...
tarantool> for k, v in pairs(box.space.test) do print(k, v) end
<iterator state>	[1, 2, 3]
---
...
```

Use `next` as workaround
```lua
tarantool> next(box.space.test)
---
- engine
- memtx
...

tarantool> next(box.space.test, 'engine')
---
- before_replace
- 'function: 0x01081d1898'
...
```

**Comment by Gerold103** [comment]
Well, this is behaviour change. Not compatible with existing code. We have space:pairs() for this. When I use pairs(table), I explicitly want to iterate over the table.

**Comment by Gerold103** [comment]
By this broken logic `table.deepcopy` also should copy the whole space, and I am sure this is not what users expect.

**Comment by olegrok** [comment]
I completely agree with you. I don't know why but space object has "__pairs" metamethod that was not triggered because pure Lua 5.1 doesn't support pairs overriding.

I think the most proper way is to remove this metamethod from space object or use "next" in table.deepcopy.

In fact, table.deepcopy is already broken (https://github.com/tarantool/tarantool/issues/4340)

**Comment by Gerold103** [comment]
In my opinion, we should revert the patch, which caused this break. Because `pairs` uses `next`, according to this page: https://www.lua.org/pil/7.3.html. When I need to workaround `pairs` by calling `next` explicitly, this does not look like API improvement.
And again, this breaks existing code. `table.deepcopy` of a space is not something rare. For example, in VShard it is used to return copy of an internal space object so as users could not change the original object. The same break will appear even if space is just a part of some bigger table.

**Comment by igormunkin** [comment]
@Gerold103, `__pairs` mm is overloaded [here](https://github.com/tarantool/tarantool/blob/master/src/box/lua/schema.lua#L1696) for space objects, but I've found no particular reason for it. Considering the comment regarding Lua 5.2 compatibility nearby, the behaviour you reported is a desired one. However, I totally against the backward compatibility breakage.

I guess we can do follow-up audit to remove all excess overloaded metamethods within Tarantool internals.

**Comment by igormunkin** [comment]
@Gerold103, __pairs mm is overloaded [here](https://github.com/tarantool/tarantool/blob/master/src/box/lua/schema.lua#L1696) for space objects, but I've found no particular reason for it. Considering the comment regarding Lua 5.2 compatibility nearby, the behaviour you reported was a desired one. However, I totally against the backward compatibility breakage.

I guess we can do follow-up audit to remove all excess overloaded metamethods within Tarantool internals.

**Comment by Totktonada** [comment]
My use case, where __pairs metamethod support would be desired: https://github.com/tarantool/graphql.0/blob/05f39946299cb2f35a97be326b992aace0205eaf/graphql/utils.lua#L83-L132

It appears because I didn't want to change graphql-lua code and prefer to work it around on my side.

**Comment by akudiyar** [comment]
Will fixing the space:pairs() behavior (i.e. renaming space#__pairs) solve the issue?

**Comment by Totktonada** [comment]
> Will fixing the space:pairs() behavior (i.e. renaming space#__pairs) solve the issue?

luafun uses getmetatable(<...>).__pairs directly, so it leads to other compatibility problems.

**Comment by igormunkin** [comment]
Related to #4560
