### ISSUE TITLE
Three bytes of death

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#4773]
Tarantool version: 1.10.2-119-g21f87c30d, 2.4.0-19-g6ddccda43.

The following Lua string leads to exit from a console (with zero exit code):

```sh
$ tarantool
Tarantool 2.4.0-19-g6ddccda43
type 'help' for interactive help
tarantool> '\x36\x00\x80'
$ echo $?
0
```

The reason is the following error during encoding to yaml:

```yaml
tarantool> require('yaml').encode('\x36\x00\x80')
---
- null
- expected SCALAR, SEQUENCE-START, MAPPING-START, or ALIAS
...
```

It seems the reason is that lua_isnumber() returns 1 (true) for '\x36\x00\x80' and so libyaml does no analyze the string itself to choose an encoding style:

https://github.com/tarantool/tarantool/blob/e9aa378480336c907304d383ffa5e4dff510171a/third_party/lua-yaml/lyaml.cc#L652-L660

The following patch shows that this guess is right (it is on top of 1.10.2-119-g21f87c30d, but everything is quite similar to current master):

```diff
diff --git a/third_party/lua-yaml/lyaml.cc b/third_party/lua-yaml/lyaml.cc
index c6d118a79..d8ebedfb6 100644
--- a/third_party/lua-yaml/lyaml.cc
+++ b/third_party/lua-yaml/lyaml.cc
@@ -596,11 +596,13 @@ static int dump_node(struct lua_yaml_dumper *dumper)
       return dump_table(dumper, &field);
    case MP_STR:
       str = lua_tolstring(dumper->L, -1, &len);
+#if 0
       if (lua_isnumber(dumper->L, -1)) {
          /* string is convertible to number, quote it to preserve type */
          style = YAML_SINGLE_QUOTED_SCALAR_STYLE;
          break;
       }
+#endif
       style = YAML_ANY_SCALAR_STYLE; // analyze_string(dumper, str, len, &is_binary);
       if (utf8_check_printable(str, len)) {
          if (yaml_is_flow_mode(dumper)) {
```

```yaml
tarantool (patched)> '\x36\x00\x80'
---
- !!binary NgCA
...
```

The following code shows that lua_isnumber() (Lua/C) and tonumber() (Lua) are unable to handle zero bytes in a middle of a string:

https://github.com/tarantool/luajit/blob/c9588f51301844d11a2a9dfa9070e437961c9787/src/lj_strscan.c#L536-L537

`GCstr str` contains length of a string, but `(const uint8_t *)strdata(str)` obviously does not.

See:

```yaml
tarantool> tonumber('\x36\x00\x80')
---
- 6
...
```

```c
/* gcc -shared isnumber.c -o libisnumber.so */

#include <lua.h>
#include <lualib.h>
#include <lauxlib.h>

static int
lbox_isnumber(struct lua_State *L)
{
	lua_pushboolean(L, lua_isnumber(L, 1));
	return 1;
}

LUA_API int
luaopen_isnumber(lua_State *L)
{
	lua_newtable(L);
	static const struct luaL_Reg meta[] = {
		{"isnumber", lbox_isnumber},
		{NULL, NULL}
	};
	luaL_register(L, NULL, meta);
	return 1;
}
```

```yaml
tarantool> package.cpath = './lib?.so;' .. package.cpath
---
...

tarantool> require('isnumber').isnumber('\x36\x00\x80')
---
- true
...
```

The same for PUC-Rio Lua 5.1.5 (it does not support '\x<...>' escape syntax, that is why I use string.char()):

```
$ lua
> print(tonumber(string.char(3*16+6) .. string.char(0) .. string.char(16*8+0)))
6
> package.cpath = './lib?.so;' .. package.cpath
> print(require('isnumber').isnumber(string.char(3*16+6) .. string.char(0) .. string.char(16*8+0)))
true
$ lua -v
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio
```

However @igormunkin shows me that PUC-Rio Lua 5.2.4 is not affected (just in case: it supports '\x<...>' syntax):

```
$ ./lua -e "print(tonumber('\x36\x00'))"
nil
$ ./lua -v
Lua 5.2.4  Copyright (C) 1994-2015 Lua.org, PUC-Rio
```

I see several problems here:

* The console just exists with zero exit code and w/o any diagnostics when yaml is unable to encode a data (the same for `tarantoolctl cat`, see below).
* lua_isnumber() check is not reliable (we should either fix it or don't use it, at least w/o additional check).
* (Need to check.) Do lua-yaml use lua_isnumber() correctly?

----

The problem also affects `tarantoolctl cat` command. Example:

Start tarantool and insert the byte sequence:

```
$ tarantool
tarantool> box.cfg{}
tarantool> box.schema.create_space('s')
tarantool> box.space.s:create_index('pk')
tarantool> _ = box.space.s:insert({1, '\x36\x00\x80'})
tarantool> <Ctrl+D>
```

Try to read a write ahead log:

```
$ tarantoolctl cat 00000000000000000000.xlog
Processing file '00000000000000000000.xlog'
LuajitError: /usr/bin/tarantoolctl:411: attempt to index a nil value
fatal error, exiting the event loop
```

**Comment by igormunkin** [comment]
Fixed in tarantool/luajit in tarantool/luajit@c633004. The submodule was updated in tarantool in 2.4.0-79-g12694d72b (12694d7), 2.3.1-56-g733e0d07a (733e0d0), 2.2.2-52-ga66683f2c (a66683f), 1.10.5-24-g444aa04ff (444aa04).
