### ISSUE TITLE
Consider avoiding addition of created error to Tarantool's diagnostic area

### ISSUE THREAD

**Issue by Korablev77** [tarantool/tarantool#4778]
If error is created via `box.error.new()`, it is automatically added to instance's diagnostic area and ergo replaces `box.error.last`. There's no word about it in docs tho. IMHO this fact complicates workflow with diagnostic area and is not clear from user's point of view. The suggestion is to introduce separate handler to add error to diagnostic area without throwing it (like `box.error.set(e)`). In case this proposal is rejected, please open doc request to clarify the fact that error created with `box.error.new()` gets to diagnostic area.

**Comment by Gerold103** [comment]
I agree, and think you can just do that, because it is not documented. Otherwise it blocks stacked diagnostics.

**Comment by Korablev77** [comment]
Here's an example why it blocks stacked diagnostics. Let's imagine we don't change current `box.error.new()` behaviour. Then:
```
assert(box.error.last() == nil)
e1 = box.error.new(...)
-- e1 reference counter is now 2:  it is once referenced since
-- it has been added to diag area and twice since error is
-- pushed to Lua interface.
--
e2 = box.error.new(...)
-- e2 reference counter is 2, meanwhile e1 is 1
-- (diag_set() calls diag_clear() which in turn decreases
-- reference counter of e1).
e2:set_prev(e1)
e3 = box.error.new(...)
-- At this point diag_clear() is called again. But now it
-- will traverse through the diagnostic stack and decrement
-- reference counter of each error. As a result, e1 reference
-- counter will become 0 and Lua's GC will crash (segfault or whatever)
-- while collecting this object.
--
```

**Comment by Gerold103** [comment]
Wait. Why should diag_clear() traverse all errors? It should decrement counter only of the last error. When last error is destroyed, it decrements next error's counter, and so on, until we faced an error having > 1 counter, or reached end of the list. This was the initial idea, from what I remember.

**Comment by Gerold103** [comment]
My point about blocking was about inability for a user to add its own error into the diag. But I now see that a user can remember `box.error.last()`, create `box.error.new()` and set is prev to the remembered value. So probably it does not block stacked diag.
