### ISSUE TITLE
Positional parameters are not bound if they follow the named ones

### ISSUE THREAD

**Issue by rybakit** [tarantool/tarantool#4782]
Tarantool version: 2.3

Bug description:
Steps to reproduce:

See https://github.com/tarantool/doc/issues/1096 for details.

**Comment by Korablev77** [comment]
Now bind mechanism is following (in pseudocode):
```
binds = [{name1 : val1}, {name2 : val2}, ...] -- array of values to be bound.
places = [pl1, pl2, ...] -- array of placeholders to be substituted.
pos = 0
for i = 0, binds.len do
    pos = i
    b = binds[i]
    if b.name != null then
        pos = -1
        for i = 0, places.len do
            if places[i] == b.name then
                pos = i
                break
            end
        end
        if pos == -1
            raise()
        end
    end
    bind(b.val, pos)
end
```

Let's consider your example:
```
params = {}
params[1] = 'B'
params[2] = {}
params[2][':id'] = 2

box.execute([[ SELECT ?, :id; ]], params)
- ['B', 2]
```
First value to be bound is unnamed ('B') so it is placed at first position; second one is named and is located in the placeholders list at second position.
```
box.execute([[ SELECT :id, ?; ]], params)
- [2, null]
```
Here second parameter to be bound is named and is located in the placeholders list at first position, so it substitutes already bound unnamed value (there's no warning or error if one value replaces already bound one). As a result second placeholder remains uninitialized -> it is null by default.

**Comment by rybakit** [comment]
Thanks for clarifying this!

> so it substitutes already bound unnamed value

This was the source of my confusion, I thought that the positional parameters would *skip* named placeholders and start from the first found `?`.

Also, I checked how it works in PHP, and, to my surprise, it behaves the same: https://3v4l.org/AU5cu, https://3v4l.org/5pA7f.
