### ISSUE TITLE
Stop/notify request fiber as soon as a client has been disconnected

### ISSUE THREAD

**Issue by rtokarev** [tarantool/tarantool#4788]
Currently request fiber doesn't stop when a client that sent request has been disconnected. Such code snippet shortly will result in "net_msg_max limit is reached" warning and will stop the processing of new requests.

```
local net_box = require('net.box')
local fiber = require('fiber')

while true do
        local c = net_box.connect('xtaz:xtaz@0:3301')
        fiber.create(function()
                pcall(c.eval, c, "require('fiber').sleep(10)")
        end)
        print(c:eval('return box.space.test:select()'))
        c:close()
end
os.exit()
```

Such fibers, that wait for some event before answer to a client are useful in pub/sub servers for example. We use them to monitor read/write status of a tarantool and report to a client when it changes.

**Comment by olegrok** [comment]
Could you use `box.session.on_disconnect()` trigger?

**Comment by rtokarev** [comment]
How can I use it to interrupt a fiber that is waiting in ```box.ctl.wait_ro``` for example? I could use ```on_disconnect``` trigger if it's possible to raise an error from it in a waiting fiber.

**Comment by olegrok** [comment]
You can save such fiber into global table where key is session_id. Then in on_disconnect trigger you can find this fiber and cancel him.

```lua
tarantool> f = fiber.new(function() box.ctl.wait_ro() end)
---
...

tarantool> f
---
- status: suspended
  name: lua
  id: 115
...
tarantool> f:cancel()
---
...

tarantool> f
---
- the fiber is dead
...
```

**Comment by rtokarev** [comment]
It seems that this trick is enough for my purposes. Feel free to close the ticket. Thank you very much!

**Comment by Gerold103** [comment]
'net_msg_max' has nothing to do with it, because net_msg object lifetime does not depend on request duration, if this was call or eval. Talking of the long sleeps - avoid big timeouts.

**Comment by rtokarev** [comment]
Why not? If I cancel a fiber processing as soon as a client has been disconnected, it should release ```iproto_msg``` that was created for a request, shouldn't it?

**Comment by Gerold103** [comment]
As I said, `iproto_msg` lifetime does not depend on request duration, if it is a call or eval. It is freed right away, after the message is delivered to the tx thread.

**Comment by rtokarev** [comment]
> It seems that this trick is enough for my purposes. Feel free to close the ticket. Thank you very much!

But it will be great if tarantool does such a cancelation by yourself. This behavior could be triggered by a special hook.

**Comment by Gerold103** [comment]
Yeah, my bad, seems like `iproto_msg` objects are kept the whole request lifetime. So we either need to introduce a setting to auto cancel all session fibers, or close the ticket, since it can be implemented using `on_connect/on_disconnect` triggers.

**Comment by kyukhin** [comment]
I propose to use triggers.
