### ISSUE TITLE
Schema-less netbox

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#4789]
Currently each netbox connection is a huge object which remembers all the spaces, indexes, and collations. For each space it creates `struct tuple_format` object, count of which is very limited. Collation count is huge - even if you don't use them, netbox still downloads 53! collations, including Chines, African, Arabic, etc.
Moreover, **all of this** is downloaded again every time, when schema version is changed on the server anyhow. This slows down connect and reconnect. It adds network hops, and makes netbox consume much more memory.
There are some cases, when schema is not needed at all. For example, when only calls and evals are used. This is the `vshard.router` case, and of any other proxy. Drop of the schema would allow to speed up connect/reconnect, not to re-download the whole schema on every change on the server, not to occupy `struct tuple_format` cells, consume less memory, when proxy makes many connections.

**Comment by tsafin** [comment]
Sorry if it's obvious - but why do we always need to have all 53 collations loaded if there is only single locale used in majority cases (I believe)? Could we whitelist a list of loaded collations somehow? Could we use only relevant to currently selected system locale?

**Comment by olegrok** [comment]
Such collations were added in https://github.com/tarantool/tarantool/issues/4007. And if it significantly slows down netbox we could consider this issue as a bug.

Another proposal is request collations/formats only on demand (I get format/.. of the space if I get at least one tuple from this space).

**Comment by Gerold103** [comment]
We can't download `_space` and `_index` content on demand, because otherwise a first access of `netboxconn.space.<space_name>` will yield. And it will yield again and again on every schema version change. This will break things.
Talking of the `struct tuple_format` - yes, here creation on demand is an option.
Talking of `_collation`. This is tricky. Collation names are used to show `netboxconn.space/index` format and key parts. If we don't download them, all collations will be numbers instead of names. Although I don't see how else they are used.
So the only thing which we can optimized for sure - tuple formats, but this alone won't help much.

**Comment by Totktonada** [comment]
Raw thoughts:

* Add an option to net_box.connect(), which will skip schema load (for ones who only need calls).
* Hide non-used collations?

**Comment by Gerold103** [comment]
Yeah, I was thinking about an option.
Talking of non used collations - this is a problem. We don't know which of them are not used until we download _space and _index. If we would download collations only afterwards, it would add one more network hop to download schema.
We already discussed the collations, in fact. Somewhere. This can't be solved unless we have a stored function, built-in, available for guests, which a netbox connection would call to fetch schema. In that stored function we would filter not needed collations.
But I would just stick to an option for connect.
