### ISSUE TITLE
test: fix replication test suite for packages testing and add it to build spec

### ISSUE THREAD

**Issue by avtikhon** [tarantool/tarantool#4798]
Tarantool version:

OS version:

Bug description:

Steps to reproduce:

Optional (but very desirable):
* coredump
* backtrace
* netstat

**Comment by Totktonada** [comment]
Now we [track](https://github.com/tarantool/tarantool/issues?q=is%3Aopen+is%3Aissue+label%3A%22flaky+test%22) flaky test fails precisely and have a [functionality](https://github.com/tarantool/test-run/pull/217) to restart known flaky fails. Maybe it is the time to enable the test suite back?
