### ISSUE TITLE
If socket is closed while JOIN, replica wont reconnect

### ISSUE THREAD

**Issue by unera** [tarantool/tarantool#480]
and wont do anything

tail of log:

```log

2014-09-02 18:47:19.937 [1950] main/101/slave.lua I> will retry every 1 second
2014-09-02 18:47:23.940 [1950] main/101/slave.lua C> connected to master
2014-09-02 18:47:24.443 [1950] main/101/slave.lua I> authenticated
2014-09-02 18:47:25.367 [1950] main/101/slave.lua !> SystemError unexpected EOF when reading from socket, called on fd 7, aka 127.0.0.1:55917, peer of 127.0.0.1:4587: Broken pipe


```

**Comment by rtsisyk** [comment]
It is possible to fix it since we moved JOIN to a thread.

**Comment by kostja** [comment]
I simply changed the order of operations in box_process_join(), this fixed the problem with unnecessary records in _cluster space. Don't understand the patch in 4867695. 
This doesn't close the bug though, since the complaint is about the replica, not the master.

**Comment by rtsisyk** [comment]
I don't understand what should be done in this ticket.

**Comment by kostja** [comment]
The replication code should be fixed to re-establish a connection and re-try downloading the snapshot if there is an error in JOIN. *Unless* it's a fatal error (and what is a fatal error in JOIN? Seems to be none).
This is what still needs to be done here.

**Comment by rtsisyk** [comment]
The only error then replica can reconnect is SocketError... I made a patch for this ticket in gh-729-multi-master

**Comment by rtsisyk** [comment]
I added a test to check that replica reconnects on socket errors. My test checks only SUBSCRIBE.
Currently there is no way to test bootstrap/JOIN procedure in our test system. It is impossible even in Python. Anyway, replica uses common code both for JOIN/SUBSCRIBE after my replica-refactoring patch, so my test case should be enough.

There is no more to do with this ticket. Please file a feature request to http://github.com/tarantool/test-run if you want to add support for bootstrap tests.

**Comment by kostja** [comment]
gh-729 patch is in
