### ISSUE TITLE
Implement API for H2O-based http server

### ISSUE THREAD

**Issue by karlovnv** [tarantool/tarantool#4802]
Now Tarantool has an internal http-server which has several drawbacks:

- Written in lua and works in the TX-thread
- Doesn't support asynchronous http/2. Using of Http 1.x (sync protocol) leads us to create a lot of connections from single client in order to achieve desired number of requests per second.
- cannot serve a lot of connections (more than 2k)
- does not support server pushes / web sockets

After some investigations we have figured out that [H2O](https://github.com/h2o/h2o) is a good candidate to be a new one http-serve with http/2 support.
It supports: 

- multiplexing and async request processing (using frames) 
- server pushes, web sockets
- TLS
- http/2 prioritization

It will be great to test both:

1. COIO implementation
2. implementation using cpipes and cbus

See [H2O as a library](https://h2o.examp1e.net/faq.html#libh2o)

[Link to discussion](https://github.com/tarantool/tarantool/discussions/5641)

**Comment by filonenko-mikhail** [comment]
web sockets are supported with a little presedanie.

**Comment by hpvd** [comment]
+1

**Comment by alyapunov** [comment]
Perhaps we should provide network-thread-API and allow anybody create their own server development in any possible way?

**Comment by filonenko-mikhail** [comment]
way without a pain

**Comment by rtsisyk** [comment]
> Written in lua and works in the TX-thread

AFAIK, http client was based on libcurl. libcurl should support http 2.0.

**Comment by Totktonada** [comment]
> > Written in lua and works in the TX-thread
> 
> AFAIK, http client was based on libcurl. libcurl should support http 2.0.

This is about the [http.server](https://github.com/tarantool/http) module.
