### ISSUE TITLE
Fuzzing Lua (LuaJit) in Tarantool

### ISSUE THREAD

**Issue by ligurio** [tarantool/tarantool#4823]
LuaJIT is a heart of Tarantool and stability of it closely connected to stability of LuaJIT.
But statistics of issues said that we catch bugs with LuaJIT [1] and sometimes it happens on a production. 

We need to decrease probability of such bugs and introduce more negative testing in tarantool release cycle. In a first step I propose following tools and plan:

1. AFL: I suggest to use AFL at the beginning because it allows to perform fuzzing testing easily without additional development.
2. LibFuzzer: analyze old luajit bugs and find functions in source code where these bugs were fixed. Create focused fuzzers for these functions using LibFuzzer.
3. fault injection in memory allocation using embedded error injection engine (`src/lib/core/errinj.c`) or using external library with `LD_PRELOAD`
4. create Lua grammar fuzzer to check *valid* language constructions
  - http://lua-users.org/wiki/LuaGrammar
  - https://github.com/antlr/grammars-v4/blob/master/lua/Lua.g4
 - WIP fuzzer for Lua https://github.com/google/oss-fuzz/pull/4653 in OSS-Fuzz

### References

1. https://github.com/LuaJIT/LuaJIT/issues/568
1. https://github.com/tarantool/tarantool/issues?q=is%3Aissue+is%3Aopen+label%3Acrash+label%3Aluajit

**Comment by ligurio** [comment]
Trophies: #4824

**Comment by olegrok** [comment]
Could we consider a variant to report founded bugs to upstream repository (https://github.com/LuaJIT/LuaJIT/issues) as well?

I think it improves chances to found solution a bit quickly.

**Comment by ligurio** [comment]
> Could we consider a variant to report founded bugs to upstream repository (https://github.com/LuaJIT/LuaJIT/issues) as well?

Sure, LuaJIT is a third-party and we won't to grow our own patchset.

**Comment by ligurio** [comment]
Lua fuzzer integration to oss-fuzz https://github.com/google/oss-fuzz/pull/4653

**Comment by CuriousGeorgiy** [comment]
@ligurio @igormunkin @sergos, have you considered [this](https://hal.archives-ouvertes.fr/hal-03607939/document) paper?
