### ISSUE TITLE
luajit-gdb: build luajit in RelWithDebInfo mode

### ISSUE THREAD

**Issue by olegrok** [tarantool/tarantool#4827]
Tarantool version: 
Tarantool 2.4.0-70-ged2e143
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_BACKTRACE=ON
Compiler: /usr/bin/cc /usr/bin/c++
C_FLAGS: -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -fno-gnu89-inline -Wno-cast-function-type
CXX_FLAGS: -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Wno-cast-function-type

OS version: centos-7 (`docker run -it --cap-add=SYS_PTRACE --security-opt seccomp=unconfined tarantool/tarantool:2.x-centos7 bash`)

Bug description:

Unable to run luajit-gdb when tarantool build type is RelWithDebInfo - `luajit-gdb.py failed to load: no debugging symbols found for libluajit`

Seems luajit knows nothing about our RelWithDebInfo and we should support it at luajit level.

**Comment by Totktonada** [comment]
https://github.com/tarantool/tarantool/blob/dcaae66e043e6e5b357d7be45a6b078f08a134fc/cmake/luajit.cmake#L171

However I don't know an exact reason. Maybe @mejedi know.

**Comment by mejedi** [comment]
@Totktonada This probably has something to do with packaging, ask @rtsisyk

**Comment by Totktonada** [comment]
@rtsisyk said that he does not remember.

**Comment by igormunkin** [comment]
LuaJIT build system is reimplemented within #4862, so the issue is gone since 2.8.0-82-g07c83aab5 (07c83aa), 2.7.1-73-gd112a4e6e (d112a4e), 2.6.2-70-g1b00de081 (1b00de0), 1.10.9-47-g8eced6926 (8eced69).
```bash
$ ./src/tarantool -v
Tarantool 2.8.0-82-g07c83aab5
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_BACKTRACE=ON
Compiler: /usr/bin/cc /usr/bin/c++
C_FLAGS: -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type
CXX_FLAGS: -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type
$ gdb -batch -n ./src/tarantool -ex 'source ./third_party/luajit/src/luajit-gdb.py'
lj-arch command initialized
lj-tv command initialized
lj-str command initialized
lj-tab command initialized
lj-stack command initialized
lj-state command initialized
lj-gc command initialized
luajit-gdb.py is successfully loaded
```

**Comment by Totktonada** [comment]
What actually fixes the issue? Enabling debug symbols for the RelWithDebInfo build?

**Comment by igormunkin** [comment]
> Enabling debug symbols for the RelWithDebInfo build?

Yes. [Here](https://github.com/tarantool/luajit/blob/tarantool/CMakeLists.txt#L99-L101) it is.

**Comment by Totktonada** [comment]
So, I hope, future generations *will* have an answer why it is enabled now.
