### ISSUE TITLE
Add more tests for LuaJIT

### ISSUE THREAD

**Issue by ligurio** [tarantool/tarantool#4836]
LuaVela [uses](https://www.youtube.com/watch?v=0MmDdTDql5E) following suites in regression testing:

- [Lua-Harness](https://fperrad.frama.io/lua-Harness/)
- [Lua testsuite](https://www.lua.org/tests/)
- [LuaJIT suite](https://github.com/tarantool/tarantool/issues/4064?)
- [Lua-TestMore](https://fperrad.frama.io/lua-TestMore/)
- LuaVela unit and functional tests

Lets consider bringing these tests to regression testing of Tarantool.

**Comment by igormunkin** [comment]
Looks like a dup of #4473.
