### ISSUE TITLE
Introduce a flag in WAL op entry to enable tx required quorum

### ISSUE THREAD

**Issue by sergos** [tarantool/tarantool#4843]
According to [quorum-based synchronous replication](https://github.com/tarantool/tarantool/blob/sergos/quorum-based-synchro/doc/rfc/quorum-based-synchro.md) Tarantool needs to introduce a quorum requirement for transaction that requires synchronous replication.

**Comment by Gerold103** [comment]
Seems like that may be not necessary. Transaction synchronous mode is defined by spaces, participating in the transaction. On replicas the spaces are the same and have the same options. So if master sends a transaction, replica during appliance of the transaction will see if it touches any sync space.

**Comment by kostja** [comment]
Agree with Vlad, this is not a property of the message, it is as property of the space, namely - it's replication group id. We already write replication group ids to WAL (group id 0 and 1 are used, we should begin using group ids > 512 for user-defined groups, i.e. RAFT groups).

**Comment by sergos** [comment]
ok, closing as not relevant.
