### ISSUE TITLE
Implement WAL op entry for quorum confirmation

### ISSUE THREAD

**Issue by sergos** [tarantool/tarantool#4847]
[qsync](https://github.com/tarantool/tarantool/blob/sergos/quorum-based-synchro/doc/rfc/quorum-based-synchro.md) replication needs a special op written in WAL at the moment quorum is achieved. 
The quorum op should have an explicit reference to a txn, so that it will be clear which rollback entries can be dropped.

**Comment by sergos** [comment]
Latest proposal to name the op as "commit"

**Comment by kostja** [comment]
There is no reason to write this data to WAL and RAFT spec in fact never writes AppendEntries *itself* to the commit log. The commit log contains entries + metadata (term, lsn), there is nothing like a special entry. 
If RAFT was running in WAL thread we could easily add "confirm_lsn" to IPROTO_INSERT header, and not write it to the log. There is no need to.
