### ISSUE TITLE
Implement WAL op entry for rollback in case of failed quorum

### ISSUE THREAD

**Issue by sergos** [tarantool/tarantool#4848]
qsync replication needs a special op rollback written in WAL in case a txn failed to collect quorum. 
The rollback op should have an explicit reference to a txn, so that it will be clear which rollback entries have to be played back to restore the state.

**Comment by kostja** [comment]
There is no rollback in RAFT, "rollback" is only possible if there is a leader election, in which case the new term is used for raft log entries.

**Comment by sergos** [comment]
How RAFT log entries are related to Tarantool WAL entries?
Should RAFT have its own log machinery, persistent one AFAIU from the paper?

**Comment by kostja** [comment]
We had a similar discussion with @knazarov. In RAFT, there are no special entry commitIndex is volatile, only term changes are persisted. Whenever a new leader is elected, it computes its commit index by checking responses to AppendEntries RPC.
See for example here: https://web.stanford.edu/~ouster/cgi-bin/papers/raft-atc14
This is why I wrote the remark above.
Tarantool doesn't have to do it this way, so it could indeed persist the commit/rollback index. However, I think adding a new message for it is still an overkill. We could piggy-back commit lsn /rollback lsn in IPROTO HEADER of any log entry, and thus advance the commit index along with writing a new transaction to disk. This plays nicely with AppendEntries philosophy, which piggy-backs the commit index as well. 
For term changes, I think, it's best to have a system tables and persist the current leader, votes and term changes in it. Vlad has already done this in scope of one of persistent read-only work, so he has most of the machiry for this implemented.
