### ISSUE TITLE
Recovery needs rollback in case WAL had a tx without appropriate quorum

### ISSUE THREAD

**Issue by sergos** [tarantool/tarantool#4851]
WAL replay should be updated to support [qsync](https://github.com/tarantool/tarantool/blob/sergos/quorum-based-synchro/doc/rfc/quorum-based-synchro.md) replication. After encounter a txn that requires quorum a list of rollback ops for all subsequent ops should be preserved until corresponding quorum op is met. In case EOF is met the rollback ops list should be kept until rejoin the cluster and either quorum or rollback message arrives. Either, replica can be appointed as a Leader and issue rollback by itself - still, need to keep the rollback ops list.

**Comment by sergepetrenko** [comment]
This is done in scope of #4847, #4848 (recovery processing of CONFIRM and ROLLBACK)
