### ISSUE TITLE
Testing connectors in tarantool development cycle

### ISSUE THREAD

**Issue by ligurio** [tarantool/tarantool#4856]
tarantool has a number connectors written on different languages. we need to test them tarantool development cycle. At least those described in official documentation:
- [ ] java https://github.com/tarantool/tarantool-java
- [ ] python https://github.com/tarantool/tarantool-python#run-tests
- [ ] python https://github.com/igorcoding/asynctnt
- [ ] golang https://github.com/tarantool/go-tarantool
- [ ] golang https://github.com/viciious/go-tarantool
- [ ] php https://github.com/tarantool/tarantool-php#testing

See https://www.tarantool.io/en/doc/1.10/book/getting_started/getting_started_connectors/

(imported from google doc)

**Comment by rybakit** [comment]
@ligurio What do you think about adding an alternative [PHP connector](https://github.com/tarantool-php/client) to the list? It's mentioned in the updated ["Getting Started"](https://www.tarantool.io/en/doc/2.3/getting_started/getting_started_connectors/) manual, in the [User's Guide](https://www.tarantool.io/en/doc/2.2/book/connectors/#php) and in the Cartridge interface. Besides, it's more feature-rich compared to the official connector, for example, it has support for UNIX sockets, SQL (including recently added prepared statements), decimal numbers, etc. Last but not least, it is thoroughly tested with around 400 unit- and integration tests (test coverage is above 80%). And if you need more, there is a [dedicated repository](https://github.com/tarantool-php/queue) that implements PHP bindings for [tarantool/queue](https://github.com/tarantool/queue/) with ~200 integration tests.

**Comment by ligurio** [comment]
Duplicate of #5265.
