### ISSUE TITLE
Ubuntu Focal Fossa 20.04 support

### ISSUE THREAD

**Issue by ObjatieGroba** [tarantool/tarantool#4863]
Tarantool version:
Any

OS version:
Ubuntu Focal Fossa 20.04

Bug description:
No packages in packagecloud

Steps to reproduce:
Open packagecloud

**Comment by Totktonada** [comment]
NB: Update tarantool/msgpuck and tarantool/tarantool-c too.

**Comment by Totktonada** [comment]
Depends on https://github.com/packpack/packpack/issues/120

**Comment by ObjatieGroba** [comment]
libicu63 now not available. Use libicu66 instead

**Comment by ligurio** [comment]
release status - beta, announce - https://lists.ubuntu.com/archives/ubuntu-announce/2020-April/000255.html

**Comment by Totktonada** [comment]
packpack/packpack:ubuntu-focal was pushed in the scope of https://github.com/packpack/packpack/issues/120

**Comment by Totktonada** [comment]
Follow ups:

https://github.com/tarantool/tarantool-c/pull/140
https://github.com/tarantool/msgpuck/pull/12
