### ISSUE TITLE
tests: split box/net.box test into smaller unit tests

### ISSUE THREAD

**Issue by avtikhon** [tarantool/tarantool#4880]

**Comment by avtikhon** [comment]
The following table show the initial commits for each test:
Issue | Test | Commit |   |   |   |  
-- | -- | -- | -- | -- | -- | --
594 | box/net.box_bad_argument_gh-594.test.lua | c27af84f23 |   |   |   |  
946 | box/net.box_call_blocks_gh-946.test.lua | 3bc7f4e6db | 32f1c34899 | 206603ce32 |   |  
3107 | box/net.box_collectgarbage_gh-3107.test.lua | 0f686829a8 |   |   |   |  
2054 | box/net.box_connect_timeout_gh-2054.test.lua | 2cc00539f8 |   |   |   |  
2858 | box/net.box_connect_triggers_gh-2858.test.lua | 40a7b0e2c1 |   |   |   |  
2677 | box/net.box_console_connections_gh-2677.test.lua | d2468dacaf |   |   |   |  
3262 | box/net.box_count_inconsistent_gh-3262.test.lua | 58da206c33 | b793994d95 |   |   | part of 2195 set 3262
3107 | box/net.box_discard_gh-3107.test.lua | 0f686829a8 |   |   |   |  
3859 | box/net.box_disconnect_gh-3859.test.lua | 3bc7f4e6db | 32f1c34899 | 51a9108eb9 | a032ce7cae | part of 946 set to 3859
3107 | box/net.box_fiber-async_gh-3107.test.lua | 0f686829a8 |   |   |   |  
2978 | box/net.box_field_names_gh-2978.test.lua | 97e8c658f8 |   |   |   |  
n/a | box/net.box_get_connection_object.test.lua | 73eac9239a |   |   |   |  
3900 | box/net.box_gibberish_gh-3900.test.lua | 3fb69c15ec |   |   |   |  
983 | box/net.box_huge_data_gh-983.test.lua | dd45d6bc7f |   |   |   |  
1729 | box/net.box_incompatible_index-gh-1729.test.lua | 7665e45a1a | 499634d58b | 386df3d3eb |   |  
841 | box/net.box_incorrect_iterator_gh-841.test.lua | 615cf3849b | 6167a8c24b | 872c1676de | cbb3d9b2c4 | part of 822 set to 841
4091 | box/net.box_index_unique_flag_gh-4091.test.lua | f1f6433b45 |   |   |   |  
3464 | box/net.box_iproto_hangs_gh-3464.test.lua | c6951c928c |   |   |   |  
3256 | box/net.box_is_nullable_gh-3256.test.lua | cc935d244b | aa0964ae14 |   |   |  
3629 | box/net.box_leaks_gh-3629.test.lua | b2b84f47df |   |   |   |  
4040 | box/net.box_log_corrupted_rows_gh-4040.test.lua | f645119f77 |   |   |   |  
3400 | box/net.box_long-poll_input_gh-3400.test.lua | aef973e0ae |   |   |   |  
3107 | box/net.box_methods_gh-3107.test.lua | 0f686829a8 |   |   |   |  
2195 | box/net.box_msgpack_gh-2195.test.lua | 5c59f12260 | 386df3d3eb | 9a590b7de5 | 1aaf637870 |  
1904 | box/net.box_on_schema_reload-gh-1904.test.lua | 950e532c69 | 8a3dae66f6 |   |   |  
1545 | box/net.box_password_gh-1545.test.lua | 076a842011 |   |   |   |  
n/a | box/net.box_permissions.test.lua | a0681659a3 | 43439a0d94 | f003b48926 | f7e53d6d84 |  
2401 | box/net.box_pseudo_objects_gh-2401.test.lua | 300bc7dacc |   |   |   |  
3107 | box/net.box_raw_response_gh-3107.test.lua | 0f686829a8 |   |   |   |  
3958 | box/net.box_readahead_gh-3958.test.lua | 89ccc7a83a |   |   |   |  
3164 | box/net.box_reconnect_after_gh-3164.test.lua | 4b69dfcdcc | 9f75d52de1 | d7cc6462f9 | eb845c45cb |  
n/a | box/net.box_reconnect_after.test.lua | f278d3f0f3 |   |   |   |  
636 | box/net.box_reload_schema_gh-636.test.lua | 4cc9972d31 |   |   |   |  
544 | box/net.box_remote_method_gh-544.test.lua | fcc02b664e | c265f9137c |   |   |  
822 | box/net.box_roll_back_gh-822.test.lua | dc6ec5c59c |   |   |   |  
2666 | box/net.box_schema_change_gh-2666.test.lua | dd29343a5f |   |   |   |  
3107 | box/net.box_schema_change_gh-3107.test.lua | 0f686829a8 |   |   |   |  
2642 | box/net.box_session_type_gh-2642.test.lua | 0bce2472b4 |   |   |   |  
2402 | box/net.box_space_format_gh-2402.test.lua | 905d44b02a |   |   |   |  
1148 | box/net.box_stack_diag_gh-1148.test.lua | 4c46531293 |   |   |   |  
1533 | box/net.box_timeout_gh-1533.test.lua | 7e09ba2d02 |   |   |   |  
3107 | box/net.box_timeout-gh-3107.test.lua | 0f686829a8 |   |   |   |  
970 | box/net.box_upsert_gh-970.test.lua | 1399d9aa18 | 7165381abb |   |   |  
398 | box/net.box_uri_first_arg_gh-398.test.lua | 9f4d7ebac8 | 3b81e95948 |   |   |  
3856 | box/net.box_wait_connected_gh-3856.test.lua | a539fdc2c1 |   |   |   |

**Comment by ligurio** [comment]
Converted numbers of issues in the table to links for convenience.
I propose to check splitted regression tests for a small number of issues. I have chose the most critical issues:  #594, #946,  #3262, #3900, #983, #1729, #3464, #3629, #3400, #970.

**Comment by avtikhon** [comment]
Checked commits and its tests mentioned above:
[x] #594 1.6.3-516-gc27af84f2
    build failed
[x] #946 1.7.7-159-g3bc7f4e6d
    build failed
[x] #970 1.6.6-106-g1399d9aa1
    build failed
[x] #983 c7c00c6170670a670a597aff43dec6f8ff6be34a
    build failed
[x] #1729 1.6.6-65-gc7c00c617
    build failed
[+] #3262 1.10.1-206-gb793994d9
[-] #3400 1.9.1-141-gaef973e0a + 1.9.0-84-gf4d66dae8
    checked initial commit and commit mentioned as the fault, always pass, even with updated test
[+] #3464 1.9.1-28-gc6951c928 + 2.2.0-483-g0529e2f0e
[+] #3629 1.10.1-294-gb2b84f47d
[+] #3900 2.1.1-361-g3fb69c15e

Additionally checked:
[+] #1148 2.4.0-126-g120866780
[+] #3859 2.1.1-136-g43af2de2b
[+] #4040 2.2.0-102-gf510dc6f4
--

**Comment by avtikhon** [comment]
I've tried to use Tarantool packages 1.6.8 version and older, but met a lot of issue with it's installing. Also the main issue that it's not possible to rebuild Tarantool of the old packages in the new OS. The only found available package fot Ubuntu:14.04, but it has issues with installation dependencies, anyway it's version is later than checking patches.

These issues were reported and decided to avoid of checking patches for fixes older than 1.7-1.9 versions.
