### ISSUE TITLE
gitlab-ci: avoid of use local host setup on OSX

### ISSUE THREAD

**Issue by avtikhon** [tarantool/tarantool#4883]
Tarantool version:
All

OS version:
OSX all

Bug description:
Need to avoid of manual setup for OSX hosts of:
1) SSL certs checks disabling
2) ulimit values preparations

**Comment by ligurio** [comment]
@avtikhon 

- split patch for two parts:
  - SSL certs checks disabling
  - ulimit values preparations
- try to fix problem with SSL certificates without disabling SSL in pip

**Comment by ylobankov** [comment]
Not relevant anymore.
