### ISSUE TITLE
Add integration with Coverity

### ISSUE THREAD

**Issue by ligurio** [tarantool/tarantool#4890]
We have registered project on Coverity but analysis happens ad-hoc - https://scan.coverity.com/projects/tarantool-tarantool
It will be useful to add integration of Coverity to development cycle of Tarantool.

Sub-tasks:
- [ ] decide how often we want to check source code in Coverity (pre-commit, on merge, nightly etc)
- [ ] integrate to continuous integration https://scan.coverity.com/travis_ci
- [ ] analyze and fix found warnings and errors

**Comment by ligurio** [comment]
[Travis CI integration](https://scan.coverity.com/travis_ci): "Admin access to at least one project is required to download the Coverity Build Tool."

**Comment by kyukhin** [comment]
Superseded by #5600
