### ISSUE TITLE
need to implement packaging to packagecloud from gitlab to leave travis

### ISSUE THREAD

**Issue by avtikhon** [tarantool/tarantool#4891]
Tarantool version:

OS version:

Bug description:

Steps to reproduce:

Optional (but very desirable):
* coredump
* backtrace
* netstat

**Comment by Totktonada** [comment]
NB: packpack has the [tool for packagecloud](https://github.com/packpack/packpack/blob/51d349a5953eca5f41db367a2940e2f83660d6f8/tools/packagecloud).

**Comment by Totktonada** [comment]
NB: Please, ensure that the new pipeline will able to deploy tarballs and packages for just tagged revisions and close #3745 if everything will look good.

**Comment by avtikhon** [comment]
To push the packages to packagecloud.io exists number of ways:
https://blog.packagecloud.io/eng/2016/03/28/pushing-packages-to-packagecloud/
also in HTTP:
https://packagecloud.io/docs/api#resource_packages_method_create

**Comment by Totktonada** [comment]
We now push all packages to our own S3 based repositories (after #3380) and don't push them to packagecloud.io (however there are still some follow up activities to be done, see #4947). We're left from Travis CI (was tracked in #4410, but was finished in the scope of #5294 in fact).

Deploy jobs (ones that push RPM / Deb packages to our S3 based repositories) now in GitLab CI and they're to be moved to GitHub Actions within the scope of #5662.

I guess there is nothing to track here anymore. Feel free to reopen with details if I missed anything.
