### ISSUE TITLE
move jobs from Travis CI to GitLab CI (at least with code coverage)

### ISSUE THREAD

**Issue by ligurio** [tarantool/tarantool#4893]

**Comment by Totktonada** [comment]
The coverage job was moved from Travis CI to GitHub Actions in the scope of #5294. The follow up activity regarding coveralls.io comments in PRs is tracked in #5644. Other activities regarding moving to GitHub Actions are tracked in the corresponding issues: at least in #5660, #5661, #5662, #5663.

I guess there is nothing to track here anymore, so I'll close the issue. Feel free to reopen with details if I missed something.
