### ISSUE TITLE
Make struct error reference counter uint64/int64

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#4902]
After https://github.com/tarantool/tarantool/commit/ca79e1cfba90cc2cb7ab9de229374366525c0749 it becomes unsafe to use `error.prev`, `box.error.last()`, or strictly speaking any other error method working with an existing error object. Any of them now can throw a Lua error. That should be fixed by making the reference counter uint64/int64. The issue may seem artificial - after all it is not that simple to overflow uint32 counter. But as #1166 and #3224 show, it is real. So rather than complicate user's already not so easy life better make the counter uint64. This is not a memory critical object so as to bother so much about making it as small as possible.

**Comment by Korablev77** [comment]
I'd not consider this problem as a bug. Let's wait for real users who want this "feature" and implement it on demand.
