### ISSUE TITLE
Separate ephemeral space format definition from definition of index parts

### ISSUE THREAD

**Issue by ImeevMA** [tarantool/tarantool#4905]
Currently, we use data obtained from the sql_key_info structure to determine the format of the ephemeral space. But the main goal of this structure is to define parts of the index. This lead to situation, where we have to change definition of index parts without changing sql_key_info.

It’s better to create a way that allows us to define the format and index parts separately. This allows you to define the format or index parts in one place and be sure that these definitions are unchanged at run-time.

**Comment by Korablev77** [comment]
What are the pros/cons in terms of SQL features and performance?

**Comment by ImeevMA** [comment]
Closed by https://github.com/tarantool/tarantool/commit/d61f39a083dbcf26cba8428c139ced036f736e17
