### ISSUE TITLE
Replace MEM_* types by MP_* types and field_types

### ISSUE THREAD

**Issue by ImeevMA** [tarantool/tarantool#4906]
Currently, SQL uses the MEM_ * types instead of the MP_ * types. They are basically functionally identical, but sometimes this is inconvenient. Also, although #4148 has already been implemented, it does not always show the correct field type.

**Comment by Korablev77** [comment]
Note that there's no function to associate each element of MEM_ types with MP_ types, i.e. these sets are not interchangeable (mostly due to auxiliary flags like ones which are responsible for allocation policy etc).

**Comment by Gerold103** [comment]
Well, this is why I said MEM_ **types**, not MEM_ **flags**. Mem types and field types are completely one-to-one interchangeable.
