### ISSUE TITLE
Add payload to error

### ISSUE THREAD

**Issue by LeonidVas** [tarantool/tarantool#4907]
To make the errors more useful for clients, we need add the ability to pass custom payload with them.

**Comment by LeonidVas** [comment]
Some useful information may be in #4398 comments.

**Comment by Totktonada** [comment]
Is it depend on #4610?

**Comment by unera** [comment]
https://github.com/tarantool/tarantool/issues/4907

**Comment by Totktonada** [comment]
It seems, it is going to be handled in #9104. No reason to track it twice, so I'll close this issue as duplicate.
