### ISSUE TITLE
replication broken at  2.3.2 

### ISSUE THREAD

**Issue by exename** [tarantool/tarantool#4928]
Tarantool version:
 2.3.2-1-g9be641bcc
OS version:
master docker on ubuntu 18.04 | replica  Container Linux by CoreOS stable (2247.6.0)
Bug description:
After update to Tarantool 2.3.2-1-g9be641bcc (current tarantool/tarantool:2.3)
replica stop with error
```2020-04-23 17:17:44.576 [1] main C> entering the event loop 2020-04-23 17:19:08.461 [1] main/109/applier/space-db.ns.svc.cl I> can't read row 2020-04-23 17:19:08.461 [1] main/109/applier/space-db.ns.svc.cl applier.cc:664 E> ER_UNSUPPORTED: replication does not support interleaving transactions```

Steps to reproduce:
need upgrade 2.3.1  to 2.3.2 master container with some data and some activity and replica with simple  TARANTOOL_REPLICATION master option 
I test it on other machines without activity on master with snapshot and xlog from prod master, but cant replroduce error, may be replication broked only with active work on master.
Test on prod master with clean replica stable gives error on first three minutes from replica start 
Downgrade  to 2.3.1 resolved issue

**Comment by kyukhin** [comment]
Thanks a lot for you report.

Could you please provide a exact test case or test scenario so we could take a look?
"Some data and some activity" doesn't help much.

**Comment by exename** [comment]
That master instance have local space. we have huge insert rate using transactions to that space.
On 2.3.2 replica stop with error in log  ```ER_UNSUPPORTED: replication does not support interleaving transactions```
With 2.3.1 and older replication works good
