### ISSUE TITLE
How does tarantool handle reply internally as fast as possible?

### ISSUE THREAD

**Issue by jobs-git** [tarantool/tarantool#4939]
Now, from my understanding, tarantool handles transactions by batches.

Suppose there are 100 client applications that sent request to tarantool at the same instance.

So, when those request arrive at tarantool database, it will place those 100 requests in its internal cache/buffer.

There are 3 threads in tarantool, but I presume only 1 thread will query the db. When it returns the result, **how does tarantool guarantee** that it is returning it to the correct request?

I have two assumptions in mind.

1. If tarantool digests the request sequentially then it will just do FIFO, then fill up its `reply buffer` 1 by 1.
2. If tarantool digests the request in async, I would assume its through a `for loop`?

**Comment by Totktonada** [comment]
Each request has it own ID (called `sync`), unique within a connection. Tarantool responds with the same `sync` as the request had. See the [binary protocol documentation](https://www.tarantool.io/en/doc/2.3/dev_guide/internals/box_protocol/).

More about queueing of requests to worker fibers: https://blueprints.launchpad.net/tarantool/+spec/fiber-specialization

If you want to dive into asynchronous processing details I suggest to start from looking into comments in iproto.cc. For example:

https://github.com/tarantool/tarantool/blob/d6d69c9fb16c704c5e89335770308ed0a21b6dd7/src/box/iproto.cc#L378-L411

**Comment by jobs-git** [comment]
I see, so its like a ring buffer within tarantool, is there a motivation why only two? Why not 3 or 5 or so?

**Comment by kostja** [comment]
The ring size is elastic. So there incrementing the number of rings doesn't make any differrence.

**Comment by jobs-git** [comment]
That solves it, thank you!
