### ISSUE TITLE
Add new versions and new OSs prebuilt packages into repository

### ISSUE THREAD

**Issue by no1seman** [tarantool/tarantool#4942]
Tarantool version:
2.x.x
OS version:
Ubuntu 20.04 Focal Fossa && others
Bug description:
1. No any version of Tarantool is unavaible for new Ubuntu 20.04 Focal Fossa
2. Also batch installer **https://tarantool.io/installer.sh** doesn't support 2.4.x and Ubuntu 20.04 Focal Fossa
Steps to reproduce:
Imposible
Optional (but very desirable):
* coredump
* backtrace
* netstat

**Comment by kyukhin** [comment]
Fixed.

**Comment by Totktonada** [comment]
> 2. https://tarantool.io/installer.sh doesn't support 2.4.x and Ubuntu 20.04 Focal Fossa

This part is not done yet. @artembo agreed to fix it on the next week.
