### ISSUE TITLE
infra: squash source tarballs buckets

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#4944]
Let's squash `tarantool.X.Y.src` buckets into one (or place it under `tarantool_repo` bucket), because buckets count is limited.

Change redirects on `try` machine and ensure that old URIs work. At least Gentoo leans on them (other source based distros are likely too):

https://github.com/tarantool/gentoo-overlay/blob/8b8df8cac6e207f95b9c83fdc3976e9b953bf772/dev-db/tarantool/tarantool-9999.ebuild#L11-L25
https://github.com/tarantool/gentoo-overlay/blob/8b8df8cac6e207f95b9c83fdc3976e9b953bf772/dev-db/tarantool/tarantool-9999.ebuild#L43

While we're here it worth to setup redirect from `tarantool.2.1.src` to `tarantool.2x.src` (or where it'll placed after the change) to simplify generation of a proper URL in the ebuild (see the links above).

**Comment by Totktonada** [comment]
@avtikhon Is it done?

**Comment by avtikhon** [comment]
Right, done, as much as possible, left only tarantool.2.3.src bucket with already used path.
