### ISSUE TITLE
tarantool crashes on batch upsert 

### ISSUE THREAD

**Issue by nazaroid** [tarantool/tarantool#4957]
Tarantool version:
2.5.0-0-gfef6505
OS version:
centos 7
Bug description:
I have an application where data ingested through batches (each batch is a transaction) of upsert operations on **vinyl**.
After some time, tnt began to crash on various operations. First, when creating run-files, then on some read operations. After digging into the tnt sources, I came to the conclusion that the reason could be the **BOX_UPDATE_OP_CNT_MAX** restriction. which is triggered after accumulation of upsert operations between merge lsm-segments.

To confirm the theory, I've made a small test - launched 2 batches (2 transactions) of 3000 upsert-s of the same tuples (with idencial key).
On the second batch tnt began to try to make merge (compaction) and crashed with the same error that caused while my application was running.

**Question 1:** How can I take under control batch of upsert operations, to avoid triggering BOX_UPDATE_OP_CNT_MAX?
* The size of the batch is fixed, 
* the size of the restriction we know (BOX_UPDATE_OP_CNT_MAX = 4000). 
Is there any way to control amount of accumulated upserts between merge, to GUARANTEED to avoid triggering BOX_UPDATE_OP_CNT_MAX?

**Question 2:** What to do with the database if more than 4000 upsert has been accumulated before the merge? Reading does not work and merge does not work, an error occurs with any of these operations.

Steps to reproduce:
*  box.begin() 
    upsert 5000 times identical tuples (with same key)
    box.commit() 
    box.snapshot() (or index:compact())
Optional (but very desirable):
* cfg
  vinyl_run_count_per_level: 2
  feedback_host: https://feedback.tarantool.io
  readahead: 16320
  memtx_dir: memtx_dir
  checkpoint_interval: 60
  replication_anon: false
  replication_connect_timeout: 30
  coredump: false
  vinyl_run_size_ratio: 2
  replication_timeout: 1
  wal_dir_rescan_delay: 2
  checkpoint_count: 1
  too_long_threshold: 0.5
  vinyl_bloom_fpr: 0.05
  strip_core: true
  feedback_enabled: true
  wal_max_size: 1048576
  log_level: 6
  slab_alloc_factor: 1.05
  hot_standby: false
  background: false
  vinyl_dir: vinyl_dir
  vinyl_cache: 134217728
  vinyl_read_threads: 1
  replication_sync_lag: 10
  vinyl_timeout: 60
  net_msg_max: 768
  listen: '3301'
  replication_skip_conflict: false
  vinyl_max_tuple_size: 10485760
  memtx_min_tuple_size: 16
  vinyl_write_threads: 4
  force_recovery: true
  memtx_max_tuple_size: 1048576
  log_format: plain
  feedback_interval: 3600
  sql_cache_size: 5242880
  wal_mode: write
  worker_pool_threads: 4
  memtx_memory: 134217728
  read_only: false
  work_dir: /var/lib/tarantool/3301_work_dir
  wal_dir: wal_dir
  vinyl_memory: 134217728
  checkpoint_wal_threshold: 1000000000000000000
  vinyl_page_size: 8192
  replication_sync_timeout: 300
* backtrace
vinyl.compaction.0/102/task D> ClientError at /usr/src/tarantool/src/box/xrow_update.c:166

**Comment by Korablev77** [comment]
Crash was fixed in https://github.com/tarantool/tarantool/commit/3e58445e0d9d93f00e3a7c2ee80d46581b97d778 (1.10)
Upserts have been partially reworked in https://github.com/tarantool/tarantool/commit/5a61c4717e63de24359a02c9f3e603444ab5b637 (2.6)
So now inapplicable upsert shouldn't get stuck - they are simply ignored during merge. We may consider increasing upper bound for BOX_UPDATE_OP_CNT_MAX or remove it at all.

**Comment by alyapunov** [comment]
As I see now everything works fine in 2.6. The limit is only applied if a user creates one huge upsert with more than 4k ops.
<details>
<summary>Here is my test, I tried a coupe of variants of upsert sequence:</summary>

```lua
tarantool> s:replace{1, 0}
---
- [1, 0]
...

tarantool> s:replace{2, 0}
---
- [2, 0]
...

tarantool> for i=1,50000 do s:upsert({1}, {{'+', 2, 1}}) s:upsert({2}, {{'+', 2, 1}}) s:upsert({2}, {{'&', 2, 65535}})  end
---
...

tarantool> box.snapshot()
2020-11-03 16:16:28.065 [24699] main/103/run.lua I> vinyl checkpoint started
2020-11-03 16:16:28.065 [24699] main/105/checkpoint_daemon I> scheduled next checkpoint for Tue Nov  3 17:27:49 2020
2020-11-03 16:16:28.066 [24699] main/107/vinyl.scheduler I> 512/0: dump started
2020-11-03 16:16:28.066 [24699] snapshot/101/main I> saving snapshot `./00000000000000150011.snap.inprogress'
2020-11-03 16:16:28.070 [24699] vinyl.dump.0/102/task I> writing `./512/0/00000000000000000002.run'
2020-11-03 16:16:28.098 [24699] snapshot/101/main I> done
2020-11-03 16:16:28.098 [24699] vinyl.dump.0/102/task I> writing `./512/0/00000000000000000002.index'
2020-11-03 16:16:28.128 [24699] main/107/vinyl.scheduler I> 512/0: dump completed
2020-11-03 16:16:28.128 [24699] main/107/vinyl.scheduler I> dumped 17791558 bytes in 0.1 s, rate 266.1 MB/s
2020-11-03 16:16:28.129 [24699] main/103/run.lua I> vinyl checkpoint completed
---
- ok
...

tarantool> s:select{}
---
- - [1, 50000]
  - [2, 50000]
...
```
</details>

I think we should close the issue.
But is it possible to fix older versions?

**Comment by Korablev77** [comment]
Closed in https://github.com/tarantool/tarantool/commit/23c16207400f6d527e3803de24cb087f1ebfe4c3

@alyapunov Unfortunately, older versions don't seem to be fixable since upsert machinery was introduced only for 2.6 branch. If someone is really affected by this issue, we can increase number of update operations in single upsert.
