### ISSUE TITLE
fio: vague error message when calling pread without arguments

### ISSUE THREAD

**Issue by RunsFor** [tarantool/tarantool#4963]
Following snippet should be self explanatory:

```
tarantool> f = fio.open('out.json', {'O_RDONLY'})
---
...

tarantool> f:pread() -- Argument error should be thrown instead
---
- error: 'builtin/buffer.lua:123: attempt to perform arithmetic on ''char *'' and
    ''nil'''
...
```

**Comment by Lord-KA** [comment]
More on that, [documentation](https://www.tarantool.io/en/doc/latest/reference/reference_lua/fio/#file-handle-pread) on pread misses default value of offset that is implicitly implemented (`lua_tonumber()` returns 0 when no argument on stack). So valid interface is:
`fh:pread([buf,] size, offset = 0)`
