### ISSUE TITLE
Run regression test nightly multiple times to detect flaky tests

### ISSUE THREAD

**Issue by ligurio** [tarantool/tarantool#4974]
> Bug description:

Current state with regression testing: one push changes to a remote GIT branch and CI server triggers regression testing. Some tests failed and one reruns them manually until success or submit new issue when decide it is a new flaky test. Therefore our tests are unreliable and developers lost confidence in tests.

> (possible) Solution;

Due to concurrency we will always have flaky tests and fixing current open issues on flaky tests is not enough to make them reliable in future. There is an idea to run tests multiple times (for example 100 times) on release (aka stable) branches nightly to detect unreliable tests. Multiple runs will increase likelihood of flaky detection and will not affect development activities. Someday we will have 100% on multiple reruns tests and will get reliable regression suite.

- [ ] prepare a automated script to run each regression test many times and print status of every test in a single line with passrate:
```
sql/sql-statN-index-drop.test.lua 0/100
sql/view.test.lua 0/100
sql/gh2483-remote-persistency-check.test.lua 1/100
sql/engine.test.lua   0/100
sql/row-count.test.lua    0/100                         
sql/func-recreate.test.lua 0/100
```
- [ ] integrate script to a [scheduled pipeline](https://gitlab.com/help/ci/pipelines/schedules) and schedule it to run nightly
- [ ] send report about nightly runs to a mail list

**Comment by ligurio** [comment]
```
l=0 ; while ./test-run.py -j16 `for r in {1..64} ; do echo test-name.test.lua; done` 2>/dev/null ; do l=$(($l+1)) ; echo ======== $l ============= ; done
```

`$ (cd test && ./test-run.py -j 100 $(yes app/gh-4787-netbox-empty-errmsg.test.lua | head -n 1000))`

**Comment by ligurio** [comment]
We have tarantool flaky test statistics on https://shame.tarantool.dev/crawler/.
I suppose this ticket can be closed.

**Comment by Totktonada** [comment]
For the history sake, the issue about statistics crawler: https://github.com/tarantool/tarantool-qa/issues/123
