### ISSUE TITLE
degradation in master on FreeBSD after patch set for OpenBSD enabling

### ISSUE THREAD

**Issue by avtikhon** [tarantool/tarantool#5004]
Tarantool version:
 Tarantool 2.5.0-56-g33cc961c7
 Target: FreeBSD-amd64-RelWithDebInfo
 Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_BACKTRACE=OFF
 Compiler: /usr/bin/cc /usr/bin/c++
 C_FLAGS: -Wno-unknown-pragmas -fexceptions -funwind-tables -fno-common -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Werror
 CXX_FLAGS: -Wno-unknown-pragmas -fexceptions -funwind-tables -fno-common -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Werror

OS version:
FreeBSD

Bug description:
https://gitlab.com/tarantool/tarantool/-/jobs/560557067
```
 [001] --- app/socket.result	Wed May 20 10:49:48 2020
 [001] +++ app/socket.reject	Fri May  8 08:20:22 2020
 [001] @@ -836,7 +836,7 @@
 [001]  ...
 [001]  s:recv()
 [001]  ---
 [001] -- Hello, world
 [001] +- 
 [001]  ...
 [001]  sc:sendto('127.0.0.1', s:name().port, 'Hello, world, 2')
 [001]  ---
```

Found that in commit c244c0b254 mistakenly changed FreeBSD blocking checks from tests skip condition files, to fix it need to return that blocks.

Steps to reproduce:

Optional (but very desirable):
* coredump
* backtrace
* netstat

**Comment by ligurio** [comment]
CI: https://gitlab.com/tarantool/tarantool/pipelines/147980757
Patch: https://lists.tarantool.org/pipermail/tarantool-patches/2020-May/016901.html
