### ISSUE TITLE
Add TPC-H benchmark to CI for regular testing

### ISSUE THREAD

**Issue by tsafin** [tarantool/tarantool#5010]
In #2903 we have prepared tools (scripts, data, makefiles) for running TPC-H benchmarking of Tarantool against baseline.

Now we need to integrate it to regular CI testing with collection of results (Q1..Q12 for given commit hash) for visualization in the bench.tarantool.org

- NB! Outliers (Q13, Q17 and Q20) are excluded now, to keep timings of run as reasonabel values. We will return back to them once #4933, #4935 and #4936 will be resolved;
- I'd love to see chart with Q1 .. Q22 as x-axis, and version numbers as y-axis. But I'm ok to see it as we display now for other benchmarks;

**Comment by avtikhon** [comment]
Checked the test in gitlab-ci - benchmark job failed.
https://gitlab.com/tarantool/tarantool/-/jobs/617329039

**Comment by tsafin** [comment]
The problems from https://gitlab.com/tarantool/tarantool/-/jobs/617329039#L90 are due to some unquoted way to pass `$NUMAOPTS` down to `make`

Here is how they were passed https://github.com/tarantool/bench-run/blob/master/benchs/tpch/run.sh#L23

**Comment by tsafin** [comment]
The simplest way to avoid interpretation of of NUMAOPTS value as part of make arguments - is to pass them via environment, i.e. instead of 
```
make bench-tnt NUMAOPTS="$numaopts"
```
use that instead

```
NUMAOPTS="$numaopts" make bench-tnt
```
