### ISSUE TITLE
Assertion with decimal inserted with Lua but updated with SQL

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#5011]
I have Ubuntu 18.04.
I have Tarantool 2.5, pulled from source today.
I execute these requests:
```lua
    box.execute([[CREATE TABLE t (s1 SCALAR PRIMARY KEY);]])
    box.space.T:insert{require('decimal').new(0.0)}
    box.execute([[update t set s1 = s1;]])
```
The result is:
```
tarantool: /home/pgulutzan/tarantool-master/src/box/sql/vdbe.c:382: mem_apply_type: Assertion `mp_typeof(*record->z) == MP_MAP || mp_typeof(*record->z) == MP_ARRAY' failed.
Aborted (core dumped)
```
Nobody expects correct results with decimals in SQL yet.
But I believe an incorrect result would be better than an assertion.

**Comment by pgulutzan** [comment]
A similar assertion will occur with a uuid field.

**Comment by Totktonada** [comment]
> Nobody expects correct results with decimals in SQL yet.
> But I believe an incorrect result would be better than an assertion.

I think that the worst thing a database may do is to give incorrect data to a user. However a proper error message would be better than the assertion fail.

**Comment by sergos** [comment]
Peter, Decimal type has a separate https://github.com/tarantool/tarantool/issues/4415
Can we rename this one into UUID request, since it is already mentioned here?

**Comment by pgulutzan** [comment]
#4415 is about adding support in SQL for a DECIMAL data type. #5011 is about not causing an assertion when any data type is unrecognized. You can of course rename whatever you want to rename, and @kyukhin can of course decide that avoiding assertions is a "wishlist" item, but I was hoping for a workaround that would arrive more quickly, and so is a separate issue.

**Comment by pgulutzan** [comment]
I will illustrate how painless it would be to return an incorrect result instead of asserting.

In src/box/sql/vdbe.c
change
			assert(mp_typeof(*record->z) == MP_MAP ||
			       mp_typeof(*record->z) == MP_ARRAY);
to
			assert(mp_typeof(*record->z) == MP_MAP ||
			       mp_typeof(*record->z) == MP_ARRAY ||
			       mp_typeof(*record->z) == MP_EXT));

In src/box/sql/vdbemem.c
change
		assert(mp_typeof(*mem->z) == MP_MAP ||
		       mp_typeof(*mem->z) == MP_ARRAY);
to
		assert(mp_typeof(*mem->z) == MP_MAP ||
		       mp_typeof(*mem->z) == MP_ARRAY ||
               mp_typeof(*mem->z) == MP_EXT);


In src/box/execute.c: In sql_column_to_messagepack():
change
	default:
to
	case MP_EXT: goto oom;
	default:

Rebuild.
Now
box.execute([[UPDATE t SET s1 = s1;]]
will cause no error, and
box.execute([[SELECT * FROM t;]])
will return an error message.
I admit it's a misleading message,
but I still believe a bad result is better than an assertion.

**Comment by Totktonada** [comment]
> but I still believe a bad result is better than an assertion.

Meaningful error message is the good option.
