### ISSUE TITLE
Assertion fail on msgpack.decode() of wrong mp_error

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#5014]
Tarantool version: 2.5.0-62-gbb7c3d167.

```
tarantool> require('msgpack').decode('\xd4\x03\x00')
tarantool: /var/tmp/portage/dev-db/tarantool-9999/work/tarantool-9999/src/box/mp_error.h:68: error_unpack: Assertion `*data == end' failed.
Aborted
```

**Comment by LeonidVas** [comment]
expected something like this:
```
Tarantool 2.5.0-65-g66024d5
type 'help' for interactive help
tarantool> require('msgpack').decode('\xd4\x02\x00')
---
- error: 'msgpack.decode: invalid MsgPack'
...
```

**Comment by Gerold103** [comment]
It is not only about mp_error. I remember that the same problem exists generally about broken MP_EXT types. I once did a test where I managed to decode a MP_UUID from a buffer < 16 bytes, so clearly not enough for a UUID. But it didn't crash by luck, even though bad memory was read.
I may be wrong, but better check other types too. Both in msgpackffi and in msgpack modules.

**Comment by Gerold103** [comment]
I am fine with closing it.

**Comment by igormunkin** [comment]
Seems to be resolved. Closing then.
