### ISSUE TITLE
http.client silently sends POST instead of GET

### ISSUE THREAD

**Issue by rosik** [tarantool/tarantool#5015]
Tarantool version: 2.5.0-16-g9f2819785

Bug description:

Built-in tarantool HTTP client silently substitutes GET with POST

Steps to reproduce:

```console
tarantool> require('http.client').request('GET', 'http://localhost:8080', "body", {verbose = true})
* Connected to localhost (127.0.0.1) port 8080 (#2)
> POST / HTTP/1.1
```

This snippet requires any listening socket, doesn't mind which one. Even `nc -l 8080` is appropriate.

P.S. The cause of problem is in non-nil body. Without it everything is OK:

```console
tarantool> require('http.client').request('GET', 'http://localhost:8080', nil, {verbose = true})
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET / HTTP/1.1
```

**Comment by Totktonada** [comment]
Looks related to #4173.

It would be good to give an error in the case.

**Comment by rosik** [comment]
Closed as duplicate
