### ISSUE TITLE
Tarantool requires fields that actually does not need

### ISSUE THREAD

**Issue by alyapunov** [tarantool/tarantool#5027]
Tarantool version: 2.5.0
Having nullable field, tarantool does not requre the field to be set, but occasionally requires preceding fields.
<details>
<summary>Example</summary>

```
tarantool> s = box.schema.space.create('test')
---
...

tarantool> i1 = s:create_index('i1', {parts={{1, 'unsigned'}}})
---
...

tarantool> i2 = s:create_index('i2', {parts={{5, 'unsigned', is_nullable=true}}})
---
...

tarantool> s:replace{1}
---
- error: Tuple field 2 required by space format is missing
...

tarantool> s:replace{1, box.NULL}
---
- error: Tuple field 3 required by space format is missing
...

tarantool> s:replace{1, box.NULL, box.NULL}
---
- error: Tuple field 4 required by space format is missing
...

tarantool> s:replace{1, box.NULL, box.NULL, box.NULL}
---
- [1, null, null, null]
...
```
</details>

In this example tarantool does not require field 5 since it's nullable, and that is correct. But if the field 5 is not present I expect tarantool not to require fields 2-4.

**Comment by kyukhin** [comment]
Reproduced on 2.3 and 2.4 as well. 1.10 seems to be OK.

**Comment by PersDep** [comment]
Turns out there is one more closely related issue:
Explicitly specifying nullable array field and creating multikey index based on it leads to fail in `tuple_raw_multikey_count`.
Reproducer:
```
s = box.schema.space.create('test')
s:format({{name='id'}, {name='data', type='array', is_nullable=true}})
s:create_index('i1', {parts={{1, 'unsigned'}}})
s:create_index('i2', {parts={{field=2, path='[*].key', type='string'}}})
s:replace{1, box.NULL}
```
Thus we not only need to fix tuple fields nullability issues but also provide suitable restrictions for multikey index.
