### ISSUE TITLE
Get rid of instance_uuid/replicaset_uuid in favor of unique strings

### ISSUE THREAD

**Issue by Mons** [tarantool/tarantool#5029]
Currently we have an option to set up instance_uuid/replicaset_uuid during start

Within such configurations these identifiers commonly made by hand and created as pure mapping from distinguishable instance name.

Example:
* Cluster on 256 shards with 3 nodes in each replicaset
* Name formed as `<name>_<XXX>_<YY>`, where XXX are numbers from 001 to 256 and YY are 01 to 03. Each instance is of course a member of replicaset `<name>_<XXX>`
* For every of that name there are strict mapping to instance UUID's: `1457A4CE-0<XXX>-00<YY>-0000-000000000000` and Every cluster name has strict mapping to `C1457312-0<XXX>-0000-0000-000000000000`

So, considering that case there is a question: why should we use uuid, when we may just save mapping `vclock-id => instance_name` instead of `vclock-id => uuid` into _cluster?

Common, human friendly names are shorter than 36 bytes of stringified uuid, they are distinguishable by human and it seems, that they could be used in that cases, when they are provided by initial configuration.

It is possible to make some limitations on name/cluster (for ex to 36 bytes) if it is required by some current implementations

**Comment by tsafin** [comment]
Yup, in general, there is no much need for check validity of an instance uuid via `tt_uuid_from_string` unless it's unique string.

From the practical prospective we simply need to use something similar to FQDN names, and they are usually unique (iff DNS is correctly working at this network)

**Comment by Mons** [comment]
It's not worth using DNS, since we may move some node from one host to another
It may change its fqdn while still have it's name (by role in some replicaset)

**Comment by tsafin** [comment]
> It's not worth using DNS, since we may move some node from one host to another

That's why I said "something _similar_ to FQDN" :)

**Comment by R-omk** [comment]
May be related https://github.com/tarantool/tarantool/issues/3805
