### ISSUE TITLE
gitlab-ci: enable skip running of the previous pushes on developers branches

### ISSUE THREAD

**Issue by avtikhon** [tarantool/tarantool#5035]
Tarantool version:
All

OS version:
All

Bug description:
Need to enable ability to skip running of the previous pushes in running gitlab-ci queue on developers branches. As found this feature has 2 special switching check boxes in gitlab-ci CI/CD configuration:
  https://gitlab.com/help/ci/pipelines/settings#auto-cancel-pending-pipelines
To make it workable the whole testing project in gitlab-ci must be either with these options or w/o it.
But in the same project there are release branches testing which must be run for each push and can't be skipped. To resolve this issue found the single solution to split gitlab-ci project in two new with testing on branches which can be skipped and branches that can't be skipped.
  Skip able branches: https://gitlab.com/tarantool/tarantool-core-branches/
  Not skip able branches: https://gitlab.com/tarantool/tarantool/
Created patch for splitting jobs on two projects. This patch can be pushed into release branches only after the new gitlab-ci project https://gitlab.com/tarantool/tarantool-core-branches/ will be completely prepared as https://gitlab.com/tarantool/tarantool/ .

Steps to reproduce:

Optional (but very desirable):
* coredump
* backtrace
* netstat

**Comment by ylobankov** [comment]
Not relevant anymore.
