### ISSUE TITLE
[1pt] gitlab-ci: implement testing rerun based on fragile lists

### ISSUE THREAD

**Issue by avtikhon** [tarantool/tarantool#5050]
Tarantool version:
All

OS version:
All

Bug description:
Need to increase the testing for the developers branches for all the changed components.
To make it possible and to avoid of overload the testing resources, need to do preparation steps:
 - [tarantool/test-run/pull/217] implement the automate rerun process for flaky tests using fragile lists
 - [tarantool/test-run/pull/218] implement artifacts collecting of the flaky tests results files check sums in fragile lists
 
Steps to reproduce:

Optional (but very desirable):
* coredump
* backtrace
* netstat

**Comment by Totktonada** [comment]
Related: https://github.com/tarantool/test-run/issues/189

**Comment by Totktonada** [comment]
Not blocked on test-run anymore.
