### ISSUE TITLE
infra: configuration on test host need to be tunned for UID 995

### ISSUE THREAD

**Issue by avtikhon** [tarantool/tarantool#5051]
Tarantool version:
All

OS version:
Fedora *

Bug description:
https://gitlab.com/tarantool/tarantool/-/jobs/582698844
https://gitlab.com/tarantool/tarantool/-/jobs/582549233

Issue:
```
PACKPACK_EXTRA_DOCKER_RUN_PARAMS='--network=host' ./packpack/packpack
 + docker pull packpack/packpack:fedora-29
 fedora-29: Pulling from packpack/packpack
 Digest: ...
 Status: Image is up to date for packpack/packpack:fedora-29
 docker.io/packpack/packpack:fedora-29
 + docker run ...
 useradd: UID 995 is not unique
 chroot: invalid user
 make: *** [package] Error 125
```

Caused by docker's entrypoint from packpack tool:
```
./build/userwrapper.sh 
useradd: UID 995 is not unique
chroot: invalid user
```

Steps to reproduce:
ssh sh4
su gitlab-runner
cd /home/gitlab-runner/builds/hBm_yoRc/0/tarantool/tarantool
OS=fedora DIST=29 ./packpack/packpack 

useradd: UID 995 is not unique

Optional (but very desirable):
* coredump
* backtrace
* netstat

**Comment by avtikhon** [comment]
To fix the issue the local gitlab-runner UID was changed after discussion in packpack/packpack#127.
Used instructions:
https://www.cyberciti.biz/faq/linux-change-user-group-uid-gid-for-all-owned-files/
Made on the hosts sh[4-8]:
```
gitlab-runner stop
# killed process run by gitlab-runner
# on sh[4,8] additionally stopped VBox driver
service vboxdrv stop
usermod -u 11995 gitlab-runner
find / -user 995 -exec chown -h gitlab-runner {} \;
gitlab-runner start
# on sh[4,8] additionally started VBox driver
service vboxdrv start
```

**Comment by Totktonada** [comment]
AFAIK, it was worked around on the infrastructure side (on machines in CI). Can be closed?

**Comment by avtikhon** [comment]
> AFAIK, it was worked around on the infrastructure side (on machines in CI). Can be closed?

Actually yes.
