### ISSUE TITLE
console tarantool ignores -i flag in case stdin is not a tty.

### ISSUE THREAD

**Issue by OKriw** [tarantool/tarantool#5064]
Tarantool version:
all
OS version:
all
Bug description:
When we executing some_command | tarantool -i. -i flag will be ignored, and command will be pars not by console.
Steps to reproduce:
Will be easy to reproduce after  #4317 will be fixed.

**Comment by Totktonada** [comment]
Reproducer:

```
$ echo 42 | tarantool -i
LuajitError: stdin:1: unexpected symbol near '42'
fatal error, exiting the event loop
```

Expected:

```
$ echo 42 | tarantool -i
Tarantool 2.5.0-130-ge3cf64a6c
type 'help' for interactive help
tarantool> 42
---
- 42
...

tarantool> $ 
```

`-i` should have precedence over `isatty()` as in vanilla luajit.

Not sure what behaviour should be for `tarantool -i -`.
