### ISSUE TITLE
Implement functions for getting a random value in range

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#5075]
In #4609 it was revealed we have a signed integer overflow in `test/unit/histogram.c` in `gen_rand_value()`. It tries to get a random value in a range. Sometimes it happens that the range length exceeds `INT64_MAX`, and `min - max` expression overflows `int64_t`.
Since this is not the only place, where it is necessary to get a random value in a range, would be good to solve this task once for all places, somewhere in `core/random.c` and `.h`. Without undefined behaviour, and preserving the random generator distribution (it is not ok to use things like `rand() % range`).

**Comment by PersDep** [comment]
I propose to use the pseudo random in range implementation **xoshiro256++**. It seems to be fast and doesn’t fail any known statistical test as far as i see. This page contains some info on it: http://prng.di.unimi.it/
Here is my performance comparison of simple **LCG rand()** (x2 cause it is 32-bit), **c++ mt19937_64**, **xoshiro256++** and **tarantool random_bytes(*, 8)**, __10^9 iterations__:
```
rand(): 18403461 18.403461
mt19937_64: 17016626 17.016626
xoshiro256++: 8619140 8.619140
random_bytes(): 2748204500 2748.204500
```

I propose to use **unbiased bitmask with rejection** method to provide number in given boundaries while preserving uniform distribution (https://www.pcg-random.org/posts/bounded-rands.html):
```
static inline uint64_t
random_in_range(uint64_t (*rnd)(void), uint64_t range)
{
	uint64_t mask = UINT64_MAX >> __builtin_clzll(range | 1);
	uint64_t result;
	do {
		result = rnd() & mask;
	} while (result > range);
	return result;
}
```

Let's see its performace comparison with simple random in range:
```
static inline uint64_t
simple_random_in_range(uint64_t (*rnd)(void), uint64_t range)
{
  return rnd() % (range + 1);
}
```
**random_in_range()** & **simple_random_in_range()**, __10^9 iterations each__
There doesn't seem to be the reason to use % (for small ranges) as far as it is not obvious where to draw the line while performance is fine anyway. Sometimes __(closer to powers of 2 from the below)__ it might be even better for **bitmask with rejection**. In the worst cases __(closer to powers of 2 from the above)__ it is about 2 times worse than simple %. Still less than microsecond for one call. Also it is kinda compensated by the 2x speed of xoshiro256++.
```
range 100: 18210485 18.210485 random_in_range
range 100: 16892518 16.892518 simple_random_in_range

range 1000: 12533446 12.533446 random_in_range
range 1000: 16899900 16.899900 simple_random_in_range

range 1025: 33559216 33.559216 random_in_range
range 1025: 16560709 16.560709 simple_random_in_range

range 10000: 27601264 27.601264 random_in_range
range 10000: 16601583 16.601583 simple_random_in_range

range 16385: 32879486 32.879486
range 16385: 16629114 16.629114

range 100000: 18708506 18.708506 random_in_range
range 100000: 17443716 17.443716 simple_random_in_range

range 1000000: 12876102 12.876102 random_in_range
range 1000000: 17009050 17.009050 simple_random_in_range

range 100000000: 20078893 20.078893 random_in_range
range 100000000: 16768971 16.768971 simple_random_in_range
```
