### ISSUE TITLE
suid functions fail

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#508]
I have Ubuntu 12.04 and Tarantool 1.6, pulled from source today.

The description of "suid functions" in https://github.com/tarantool/tarantool/issues/488 appears to be incorrect in two ways:
1. it says that the syntax is `box.schema.func.create('name', { suid = yes })` but that doesn't work; the syntax that works is `box.schema.func.create('name', { setuid = true })`
2. it says that I get to be the function's creator, but if I execute while I'm a different user, I get an error when I try to select, even though the function's creator can do the select.

**HOW TO REPEAT :**

As `user = admin` I said:
```
box.cfg{listen=3301}
box.schema.user.grant('guest', 'execute', 'universe')
function f1 () return box.space._func:get(1)[4] end
function f2 () return box.space._func:get(2)[4] end
box.schema.func.create('f1',{suid=yes})
box.schema.func.create('f2',{setuid=true})
box.space._func:select(0,{iterator='GE'})
```

The result of the select request looks like:
```
tarantool> box.space._func:select(0,{iterator='GE'})
---
- - [1, 1, 'f1', 0]
  - [2, 1, 'f2', 1]
...
```

That shows that `suid = yes` has no effect (field 4 is 0), but `setuid = true` has an effect (field 4 is 1).

Then, on another terminal, I used console.connect so that I would be `user = guest`. I executed these requests:
```
box.cfg{}
console = require('console')
console.connect('localhost',3301)
f1()
f2()
```

The result was an error, both times:
```
localhost:3301> f1()
---
- error: Read access denied for user 'guest' to space '_func'
...

localhost:3301> f2()
---
- error: Read access denied for user 'guest' to space '_func'
...
```

This shows that I wasn't acting as admin.

**Comment by kostja** [comment]
Peter,

this is a strange artifact of console implementation.

Here's what happens: 
when you issue 'console.connect()' and connect to a port, and then invoke f1() or f2(), you actually invoke "eval" binary protocol command, which, in turn, evaluates an arbitrary Lua expresssion you pass to it, in your example, "return f1()" or "return f2()".

setuid user change only works when a function is invoked with CALL binary protocol command, so if you change your client code to:

```
tarantool> c = remote.new('3301')
---
...
tarantool> c:call('f2')
---
- - [0]
...
tarantool> c:call('f1')
---
- error: Read access denied for user 'guest' to space '_func'
```

the code works as expected. 

Actually, it doesn't. There was a bug with that code path too, but I will fix it now, before you get to read this message.
