### ISSUE TITLE
Master needs to send only confirmed data to replica during initial join

### ISSUE THREAD

**Issue by sergepetrenko** [tarantool/tarantool#5097]
During initial join master feeds the replica with all the data from all the spaces via a snapshot-like iterator. Since this data is later used to create replica's snapshot, master has to start sending initial data only when it receives confirmation for the last txn.

**Comment by sergepetrenko** [comment]
During final join either replica must process rollbacks correctly or master shouldn't send unconfirmed data.

**Comment by sergos** [comment]
The unconfirmed data should be either
* confirmed later after quorum is achieved by a leader - even if txns are from the former leader
* rolled back by the leader - again for both leader's or former leader txns

There should be no rollbacks issued by replica itself - they should arrive from master anyways.
I can see a discrepancy in RFC, where I used 'rollback' in part describing snapshot for replica. There it means not a Rollback message, rather replay undo log for all txns in limbo and make xlog rotation. Will it work for the join case?

**Comment by sergos** [comment]
Well, thought twice and I reckon a not sending strategy can be a good save on traffic. And yet, it can be rather easy to implement, if leader can peek into limbo's oldest entry and stop sending before it's LSN.
Any problems with implementation?
