### ISSUE TITLE
gitlab-ci: save results for failed tests in some DB

### ISSUE THREAD

**Issue by avtikhon** [tarantool/tarantool#5117]
Tarantool version:

OS version:

Bug description:
Need to implement ability to save results in any DB at all gitlab-ci jobs to be able to collect its statistics.
Steps to reproduce:

Optional (but very desirable):
* coredump
* backtrace
* netstat

**Comment by ligurio** [comment]
as a first step we can save results to artifacts, luckily gitlab-ci supports junit reports - https://docs.gitlab.com/ee/ci/junit_test_reports.html

**Comment by Totktonada** [comment]
Use GitLab CI artifacts is the interesting idea. It will allow to use an existing reliable infrastructure, but will require some amount of work to implement a crawler. And artifacts may be useful per se.

The issue about artifacts: https://github.com/tarantool/test-run/issues/90.

**Comment by ylobankov** [comment]
Not relevant anymore.
