### ISSUE TITLE
Prevent trace assembling with invalid RENAME to be emitted

### ISSUE THREAD

**Issue by igormunkin** [tarantool/tarantool#5118]
This issue is a follow up for #4252. As a result of that issue only a single flaky test is fixed, but the platform still can produce traces breaking a particular Lua code semantics.

Since the [original problem](https://github.com/LuaJIT/LuaJIT/issues/584) is not fixed yet, I propose to implement a less complex solution to handle such situations: when a `RENAME` IR to be emitted for a destructive x86 op, JIT ought to check whether there is a guarded IR with the same snapno side exit as the one being assembled. If such condition occurs JIT engine just aborts this trace assembling. This idea originates to @sergos [review](https://lists.tarantool.org/pipermail/tarantool-patches/2020-June/017870.html) for #4252.

**Comment by Totktonada** [comment]
Should be fixed in https://github.com/LuaJIT/LuaJIT/commit/33e3f4badfde8cd9c202cedd1f4ed9275bc92e7d, AFAIU.

**Comment by igormunkin** [comment]
To fix the issue LuaJIT/LuaJIT@33e3f4b is backported in scope of tarantool/luajit@3a2e484. The submodule was updated in tarantool in 2.9.0-195-g20c0a12a5 (20c0a12), 2.8.1-143-gd64c82406 (d64c824), 2.7.2-134-g2d1845cf2 (2d1845c), 1.10.10-64-g40d2ed9ae (40d2ed9).
