### ISSUE TITLE
cannot successfully execute two tx's in a row ('Operation is not permitted when there is an active transaction')

### ISSUE THREAD

**Issue by ligurio** [tarantool/tarantool#5120]
### Tarantool version:

`gh-4842-sync-replication`, 958f59dcdea04b9a69066621bcbbc39e6bac592d

### OS version:

CentOS Linux release 8.1.1911 (Core)

### Steps to reproduce:

```lua
test_run:switch('default')
box.cfg{replication_synchro_quorum=NUM_INSTANCES, replication_synchro_timeout=orig_synchro_timeout}
box.begin() box.space.test:insert({1}) box.commit()
box.begin() box.space.test:insert({2}) box.commit()
box.space.sync:truncate()
```

### Expected behaviour

successfully committed both transactions

### Actual behaviour

error  'Operation is not permitted when there is an active transaction ' on second tx

```
test_run:switch('default')
 | ---
 | - true
 | ...
box.cfg{replication_synchro_quorum=NUM_INSTANCES, replication_synchro_timeout=orig_synchro_timeout}
 | ---
 | ...
box.begin() box.space.test:insert({1}) box.commit()
 | ---
 | - error: '[string "box.begin() box.space.test:insert({1}) box.co..."]:1: attempt to
 |     index field ''test'' (a nil value)'
 | ...
box.begin() box.space.test:insert({2}) box.commit()
 | ---
 | - error: 'Operation is not permitted when there is an active transaction '
 | ...
box.space.sync:truncate()
 | ---
 | ...
```

**Comment by Gerold103** [comment]
What is the problem? Your first statement failed after box.begin(), so there is still an open transaction. And you call box.begin() again. This is an error, regardless of whether the space is sync or not. You just tried to start a transaction twice.

**Comment by ligurio** [comment]
Exactly! I'm missed error in output.
