### ISSUE TITLE
Incorrect value for option log_format

### ISSUE THREAD

**Issue by rosik** [tarantool/tarantool#5121]
Follow-up for #689 

Log.cfg can't set json logger at boot

```console
$ tarantool
Tarantool 2.5.0-159-g83462a5cf
type 'help' for interactive help
tarantool> require('log').cfg({format = 'json'})
---
- error: 'builtin/log.lua:456: log.cfg: ''format'' json can''t be used with syslog
    or boot-time logger'
...

tarantool> 
```

Meanwhile, the following is OK:

```console
$ tarantool
Tarantool 2.5.0-159-g83462a5cf
type 'help' for interactive help
tarantool> require('log').cfg()
---
...

tarantool> require('log').cfg({format = 'json'})
---
...
```

I think this check is redundant and can be safely removed.

**Comment by olegrok** [comment]
Such error was introduced in scope of https://github.com/tarantool/tarantool/issues/3946 - when we try to change log format before it was initialized. Seems, we should allow to allow to specify json format in log.cfg, but it should be still prohibited to use before log.cfg/box.cfg.

**Comment by cyrillos** [comment]
Strictly speaking there is a typo in commit 098324556 where we've started to ban json usage on early boot stage.

**Comment by cyrillos** [comment]
https://lists.tarantool.org/pipermail/tarantool-patches/2020-June/018015.html

**Comment by cyrillos** [comment]
https://lists.tarantool.org/pipermail/tarantool-patches/2020-June/018078.html

**Comment by cyrillos** [comment]
https://lists.tarantool.org/pipermail/tarantool-patches/2020-July/018114.html
