### ISSUE TITLE
Fullmesh qsync fails with "XlogError: can't parse row"

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#5138]
```Lua
-- Instance 1
box.cfg{
    listen = 3313,
    replication = {'localhost:3313', 'localhost:3314'},
    replication_timeout = 1,
    replication_synchro_quorum = 2,
    replication_synchro_timeout = 1000000,
}
box.schema.user.grant('guest', 'super')
_ = box.schema.space.create('sync', {is_sync=true})
_ = _:create_index('pk')
```

```Lua
-- Instance 2
box.cfg{
    listen = 3314,
    replication = {'localhost:3313', 'localhost:3314'},
    replication_timeout = 1,
    read_only = true,
}
```

```Lua
-- Instance 1
for i = 1, 1000 do box.space.sync:replace{i} end
```

Result on instance 1:
```
2020-07-05 16:36:46.406 [80634] main/111/applier/localhost:3314 I> can't read row
2020-07-05 16:36:46.406 [80634] main/111/applier/localhost:3314 xlog.c:1796 E> XlogError: can't parse row
```

On instance 2 it is the same. The error originates from instance 2.

**Comment by Gerold103** [comment]
All works fine when no fullmesh.

**Comment by sergos** [comment]
it's reproducible on instance 2 after box.cfg{} w/o instance 1
apparently it's a badly composed rollback message

 p *xrow
(xrow_header) $5 = {
  type = 40
  replica_id = 1
  group_id = 0
  sync = 0
  lsn = 36
  tm = 1594070434.6040962
  tsn = 36
  is_commit = true
  bodycnt = 0
  schema_version = 0
  body = {
    [0] = (iov_base = 0x0000000000000000, iov_len = 0)
    [1] = (iov_base = 0x0000000000000000, iov_len = 0)
  }
}

running 
-> 1792         int rc = xrow_header_decode(xrow,

with it we got the mp_check() fail.

**Comment by sergos** [comment]
nevermind, quorum is Ok. 

Tarantool 2.5.0-204-g0d77595
built on 
```
commit 0d77595acb1ec038282f783a72a92ce24ff50938
Author: Vladislav Shpilevoy <v.shpilevoy@tarantool.org>
Date:   Fri Jul 3 00:55:08 2020 +0200

    [tosquash] replication: add test on local row in the end of sync txn
    
    Currently disabled, because soon should start working without
    any changes when #4928 is fixed.

```
works correct, replica has
```
tarantool> box.space.sync:select{}
[cut...]
  - [997]
  - [998]
  - [999]
  - [1000]
...
```

**Comment by Gerold103** [comment]
With non-fullmesh does not work either. But fails on recovery on the replica.
