### ISSUE TITLE
Fix W631 (line is too long) warnings in test/sql-tap

### ISSUE THREAD

**Issue by ligurio** [tarantool/tarantool#5181]
## Bug description:

there are a bunch of warnings in `test/sql-tap` supressed in `.luacheckrc`.
it would be nice to fix them.

**Total: 6109 warnings / 0 errors in 264 files**

**Comment by Totktonada** [comment]
Revert exclusion:


```diff
$ git diff
diff --git a/.luacheckrc b/.luacheckrc
index 994d29956..8ba86f568 100644
--- a/.luacheckrc
+++ b/.luacheckrc
@@ -31,7 +31,6 @@ exclude_files = {
     -- Third-party source code.
     "src/box/lua/serpent.lua",
     "test-run/**/*.lua",
-    "test/**/*.lua",
     "third_party/**/*.lua",
     ".rocks/**/*.lua",
     ".git/**/*.lua",
```

Message:

> (W631) line is too long (\<...\> > 120)

Count:

```
$ luacheck --codes test/sql-tap/*.test.lua | grep -o '(W631).*$' | wc -l
6108
```

**Comment by igormunkin** [comment]
Look like the resulting changes have no sense and only spoil both git history and test chunks. Closing with wontfix reason.
