### ISSUE TITLE
bug: update error

### ISSUE THREAD

**Issue by bronya100** [tarantool/tarantool#5182]
Tarantool version: 2.2.2-4-g4f8ac5999
OS version: Debian GNU/Linux 9
Bug description: update error

Steps to reproduce:
format = {{'i', 'integer'}}
s = box.schema.space.create('A', {format = format})
_ = s:create_index('i')
box.execute('insert into a values (1), (2);')
format = {{'i', 'integer'}, {'a', 'integer', is_nullable = true}, {'b', 'integer', is_nullable = true}}
s:format(format)

box.execute('update a set "b" = NULL;')
- null
- Field 2 was not found in the tuple

**Comment by olegrok** [comment]
Related - https://github.com/tarantool/tarantool/issues/3378

**Comment by olegrok** [comment]
After #3378 was resolved your code doesn't return error anymore. Probably we could close this issue.

**Comment by ImeevMA** [comment]
Fixed by 2bb373b9f.
