### ISSUE TITLE
Implement LuaJIT platform metrics

### ISSUE THREAD

**Issue by igormunkin** [tarantool/tarantool#5187]
As a result of the research regarding [uJIT pros and cons](https://lists.tarantool.org/pipermail/tarantool-discussions/2020-April/000058.html), LuaJIT platform metrics turned out to be a highly requested feature, so we are going to extend our [LuaJIT fork](https://github.com/tarantool/luajit) API with the following interfaces:

* [x] C API method (similar to [`luaE_metrics`](https://github.com/iponweb/luavela/blob/master/docs/public/ujit-c024.rst#luae-metrics)) returning a structure containing numerous runtime metrics of the state.
* [x] Lua API method (similar to [`ujit.getmetrics`](https://github.com/iponweb/luavela/blob/master/docs/public/ujit-024.rst#ujit-getmetrics)) returning a table with the current values of LuaJIT-specific metrics

Furthermore, in scope of this ticket, an RFC for the feature should be sent to our ml, so we can enrich the metrics to be reported considering users demand.

**Comment by Buristan** [comment]
RFC can be found [here](https://lists.tarantool.org/pipermail/tarantool-patches/2020-July/018775.html).

**Comment by igormunkin** [comment]
Platform metrics are implemented in scope of tarantool/luajit@c441cf5; the interfaces described above are introduced in tarantool/luajit@e4e0a48. The submodule was updated in tarantool in 2.6.0-154-ge5039742e (e503974), 2.5.1-119-g89732d199 (89732d1), 2.4.2-103-g8e218be7b (8e218be), 1.10.7-59-g05bb24ec5 (05bb24e).
