### ISSUE TITLE
Is there a way to connect to tarantool via dbeaver

### ISSUE THREAD

**Issue by enescaglar** [tarantool/tarantool#5189]
Hi,

I am not sure if this is a right place to ask a question. But I wanted to know if there is a way to connect to tarantool via dbeaver? I couldn't find a jdbc driver when I looked for it. If there is a way, can someone point me to a link or describe how to connect?

Thank you.

**Comment by Totktonada** [comment]
Our [tarantool-java](https://github.com/tarantool/tarantool-java/) connector ships some level of JDBC support (it is in alpha status now). There is WIP [JDBC User guide](https://github.com/tarantool/tarantool-java/blob/83125a35a8e87ed309c8c8bbb3f11432bed71f66/JDBC.md). I don't know anything about DBeaver, so I can only point you to mine [experiment](https://github.com/tarantool/tarantool-java/issues/198#issue-452083650) with libreoffice base (we plan to resolve the issue in Q3).

Feel free to ask a question in our [Telegram chat](https://t.me/tarantool). You may highlight me there using @Totktonada nickname.
