### ISSUE TITLE
Convert libyaml to submodule and add support for system libyaml-dev

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#519]
`third_party/lua-yaml` actually consists of two parts:

[libYAML]  - untouched by us: 

```
api.c
dumper.c
emitter.c
HISTORY
LICENSE
LICENSE.LibYAML
loader.c
parser.c
reader.c
README
README.LibYAML
scanner.c
TODO
writer.c
yaml.h
yaml_private.h
```
Lua bindings for [libYAML] - actively patched by me:

```
b64.c
b64.h
lyaml.cc
lyaml.h
```

Please do the following things:

1. Extract all libYAML files to `third_party/libyaml`
2. Create a git mirror of libYAML [hg] repository at GitHub (tarantool/libyaml) using git-hg.
3. Convert `third_party/libyaml ` to a submodule
4. Add support for system libyaml-dev in CMake
This library exists in most popular distributives just because python-yaml and Perl::YAML depends on it.
5. Add libyaml-dev to DEB / RPM dependencies for Tarantool.

[libYAML]: http://pyyaml.org/wiki/LibYAML
[hg]: https://bitbucket.org/xi/libyaml

https://packages.debian.org/wheezy/libyaml-dev/
https://apps.fedoraproject.org/packages/libyaml-devel/
http://svnweb.freebsd.org/ports/head/textproc/libyaml

**Comment by rtsisyk** [comment]
A complaint from Debian's lintian:

```
E: tarantool: embedded-library usr/bin/tarantool: libyaml
N:
N:    The given ELF object appears to have been statically linked to a
N:    library. Doing this is strongly discouraged due to the extra work needed
N:    by the security team to fix all the extra embedded copies or trigger the
N:    package rebuilds, as appropriate.
N:    
N:    If the package uses a modified version of the given library it is highly
N:    recommended to coordinate with the library's maintainer to include the
N:    changes on the system version of the library.
```

**Comment by rtsisyk** [comment]
This patch for 1.6.7 because it blocks Debian packages. The system library is used only if -DENABLE_BUNDLED_LIBYAML is OFF (default value is ON).

**Comment by kostja** [comment]
* Roman Tsisyk <notifications@github.com> [15/12/15 22:52]:
> This patch for 1.6.7 because it blocks Debian packages. The
> system library is used only if -DENABLE_BUNDLED_LIBYAML is OFF
> (default value is ON). All other changes are just moving of
> files and fixes in CMake scripts.

Go ahead and push it. 

-- 
Konstantin Osipov, Moscow, Russia, +7 903 626 22 32
http://tarantool.org - www.twitter.com/kostja_osipov

**Comment by rtsisyk** [comment]
Postreview fixes:

* Fork libyaml to tarantool/
* Add .gitignore to avoid "untracked content" errors http://stackoverflow.com/questions/5126765/how-to-get-rid-of-git-submodules-untracked-status

**Comment by rtsisyk** [comment]
Fixed
