### ISSUE TITLE
Qsync statistics

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#5191]
Would be nice to expose statistics on synchronous replication. Current queue size, average wait time, and more. Need to keep in mind, that it should be something easy to expose in the monitoring tools like grafana, and it should work without changes (or with a few), when we will have multiple limbos.

**Comment by cyrillos** [comment]
This looks like a good dependency on #5289

**Comment by cyrillos** [comment]
When `qsync` stat will be implemented need to update the test case from bug #5446 because grepping output is not reliable source and may be flaky. Instead we should report current quorum value somewhere in `qsync` and use it instead.
