### ISSUE TITLE
Sharding for tarantool 1.6

### ISSUE THREAD

**Issue by vlebedev** [tarantool/tarantool#520]
It would be great to have sharding API like https://github.com/tarantool/shard available for Tarantool 1.6.

**Comment by Sulverus** [comment]
Base sharding api for 1.6 done:
1. All nodes connections
2. Heartbeat table
3. Monitoring and nodes kill
4. After connect node checking
5. Basic oprations implementation

Hot to use it:
1. luarocks: http://rocks.tarantool.org/
2. package is avalable in tarantool rpm/deb repositories:
```bash
sudo yum install tarantool-shard
```
3. Docker images contains tarantool shard package
https://registry.hub.docker.com/u/tarantool/tarantool/dockerfile/

Please review
API - https://github.com/tarantool/shard/blob/master/shard.lua
Exmaple - https://github.com/tarantool/shard/blob/master/demo.lua
Example 2 - https://github.com/tarantool/shard/tree/master/debug

**Comment by kostja** [comment]
I'm closing this ticket, since the core of sharding is complete. We need to add a join of a new node to this scheme, which we'll track separately in shard/ project.
