### ISSUE TITLE
 RAFT library - pick one, implement anew?

### ISSUE THREAD

**Issue by cyrillos** [tarantool/tarantool#5204]
Need to investigate current RAFT implementations library and either choose one or implement by own.

**Comment by olegrok** [comment]
AFAIK etcd has RAFT implementation - https://github.com/etcd-io/etcd/tree/master/raft

But there is one problem it's implemented in Go. But maybe it has a value as source to inspiration

**Comment by cyrillos** [comment]
I already have library simply need time to investigate and a bug to track.

**Comment by cyrillos** [comment]
We already implemented own RAFT code, so bug is outdated.
