### ISSUE TITLE
RAFT testing: any suite available, create anew?

### ISSUE THREAD

**Issue by cyrillos** [tarantool/tarantool#5205]
Need to investigate if there some testing suite already present for RAFT testing or we should implement own one.

**Comment by ligurio** [comment]
There are many Raft implementations can be found on raft.github.io, but many of them lack of testing. Ihaven't found good universal testsuite written on C and I think that it is better to look at existed tests, create a list of good testcases and implement them for Tarantool.

These Raft implementations contains tests:

- Golang https://github.com/etcd-io/etcd/tree/master/raft
- Rust https://github.com/tikv/tikv/tree/master/tests/integrations/raftstore
- C++ https://github.com/baidu/braft/tree/master/test
- Golang https://github.com/hashicorp/raft/tree/master/fuzzy
- C https://github.com/canonical/raft/tree/master/test
- Erlang https://github.com/rabbitmq/ra/tree/master/test
- C++ https://github.com/eBay/NuRaft/tree/master/tests
- Golang https://github.com/lni/dragonboat, [testcases](https://github.com/lni/dragonboat/blob/master/docs/test.md)
- C https://github.com/willemt/raft/tree/master/tests [testcases](https://github.com/willemt/raft#quality-assurance)
- https://colin-scott.github.io/blog/2015/10/07/fuzzing-raft-for-fun-and-profit/

**Comment by kyukhin** [comment]
We're implementing our own suite.
