### ISSUE TITLE
fiber_mprotect doesn't set diagnostics

### ISSUE THREAD

**Issue by PersDep** [tarantool/tarantool#5211]
Version: 1.10

**Comment by Gerold103** [comment]
Why? Here is the complete code:
```C
static inline int
fiber_mprotect(void *addr, size_t len, int prot)
{
	int rc = 0;

	struct errinj *inj = errinj(ERRINJ_FIBER_MPROTECT, ERRINJ_INT);
	if (inj != NULL && inj->iparam == prot) {
		errno = ENOMEM;
		rc = -1;
	}

	if (rc != 0 || mprotect(addr, len, prot) != 0) {
		diag_set(SystemError, "fiber mprotect failed");
		return -1;
	}
	return 0;
}
```

**Comment by PersDep** [comment]
> Why? Here is the complete code:
> 
> ```c
> static inline int
> fiber_mprotect(void *addr, size_t len, int prot)
> {
> 	int rc = 0;
> 
> 	struct errinj *inj = errinj(ERRINJ_FIBER_MPROTECT, ERRINJ_INT);
> 	if (inj != NULL && inj->iparam == prot) {
> 		errno = ENOMEM;
> 		rc = -1;
> 	}
> 
> 	if (rc != 0 || mprotect(addr, len, prot) != 0) {
> 		diag_set(SystemError, "fiber mprotect failed");
> 		return -1;
> 	}
> 	return 0;
> }
> ```
> 
> I see `diag_set()`.

This is about 1.10:
```
#define fiber_mprotect(addr, len, prot)					\
({									\
	int err = mprotect((addr), (len), (prot));			\
	if (err)							\
		say_syserror("mprotect");				\
	err;								\
})
```

**Comment by PersDep** [comment]
1.10 needs https://github.com/tarantool/tarantool/commit/c67522973b32fae955835109d4f86eada8f67ae5 & https://github.com/tarantool/tarantool/commit/8d53fadc0cb15a45ea0cd461d2d5243be51b37e0 from master, but they have to be carefully rebased.

**Comment by PersDep** [comment]
Pushed to 1.10
