### ISSUE TITLE
error  SystemError writev(1)  && not enough memory

### ISSUE THREAD

**Issue by darrenchinesedba** [tarantool/tarantool#5217]
2020-07-29 23:55:09.456 [40889] iproto sio.c:268 !> SystemError writev(1), called on fd 23, aka 127.0.0.1:3303: Broken pipe
2020-07-29 23:55:31.168 [40889] iproto sio.c:268 !> SystemError writev(1), called on fd 184, aka 127.0.0.1:3303: Broken pipe

Tarantool crashes with error "not enough memory"

centos 7
8core CPU ,30G memory
tarantool 2.4.2
![photo_2020-07-30_00-06-46](https://user-images.githubusercontent.com/20239092/88824250-b19a5e80-d1f8-11ea-8ba7-1c9b105922a9.jpg)

**Comment by Totktonada** [comment]
EPIPE ('Broken pipe') means that a reading end of a socket is closed (it typically appears when we try to write into such socket).

Tarantool actually may crash when 'not enough memory' Lua error is thrown, it is tracked by #4671. Usual reason of such error is producing too much long living Lua objects in a user code. We consider implementing of a Lua memory profiler (no issue yet), which will simplify finding of a cause.

**Comment by Totktonada** [comment]
[Profiling Memory in Lua](https://www.lua.org/wshop15/Musa2.pdf) — Pablo Musa (PUC-Rio).
