### ISSUE TITLE
key_def: incorrect validation for part type

### ISSUE THREAD

**Issue by olegrok** [tarantool/tarantool#5222]
Tarantool version: 2.3

```lua
tarantool> key_def.new({{field = 1, type = nil}})
---
- error: type must not be nil
...
tarantool> key_def.new({{field = 1, type = box.NULL}}) -- Expected the same error as for first case
---
- - type: unsigned
    is_nullable: false
    fieldno: 1
...
```

**Comment by Totktonada** [comment]
BTW, [tuple-keydef](https://github.com/tarantool/tuple-keydef) is not affected.

```yaml
# tarantool> keydef = require('tuple.keydef')
# tarantool> keydef.new({{field = 1, type = nil}})
---
- error: type must not be nil
...

# tarantool> keydef.new({{field = 1, type = box.NULL}})
---
- error: Field type is mandatory
...
```

The error is from this code:

https://github.com/tarantool/tarantool/blob/6e45042473fb973c7b1ad87fcf04c9081a4c40fa/src/box/key_def.c#L362-L366

It is called from the `box_key_def_new_v2()` module API function.

It is more like a luck: both modules don't check types of `field`, `type`, `is_nullable`, `collation` and other fields of an input argument. I think they should (but I don't insist on working on it within this particular task).
