### ISSUE TITLE
undefined symbol: curl_version

### ISSUE THREAD

**Issue by rosik** [tarantool/tarantool#5223]
**Tarantool version**: 2.6.0-32-g6e11674dd

**Long story short**: tarantool bundles libcurl, but not entirely, and it's no good.

In the recent update of libcurl (807c7fa584f21ee955b2a14623d70f7510a3650d) its layout has changed: private function `Curl_version_init()` which used to fill-in info structure was eliminated. As a result, no symbols for `libcurl_la-version.o` remained used, so it wasn't included in tarantool binary. And `curl_version` and `curl_version_info` symbols went missing.

According to [libcurl naming conventions](https://github.com/curl/curl/blob/34e5ad21d2cb98475acdbf7a3a6ea973d8c12249/docs/INTERNALS.md#library-symbols) all exported symbols are named as `curl_*`. I think tarantool should respect it and preserve those symbols.

**Steps to reproduce**: 

```lua
ffi = require('ffi')
ffi.cdef('char *curl_version();')
print(ffi.C.curl_version())
```

**Also useful**:

We've noticed the problem while working on static build. Here is a [test](https://github.com/tarantool/tarantool/commit/d7a94e4587159802cc295dd0a4a1e21c6c72b355#diff-250fb463d17f22a6c5abd5a4d757255b) which may help. 

Related to #2971

**Comment by Totktonada** [comment]
It looks as prerequisite for #4559.

I would classify it as a feature.

**Comment by rosik** [comment]
It seems that this issue could be fixed by explicitly listing all 82 public curl symbols in `exports.h`
