### ISSUE TITLE
Synchronized replication dirty reads

### ISSUE THREAD

**Issue by WeCodingNow** [tarantool/tarantool#5229]
Tarantool version: Tarantool 2.5.1-16-gdf35699

OS version: CentOS 7

Bug description:
It is possible to read unconfirmed data from replica during the time period during which a master waits for all necessary receipts of a synchronous transaction from replicas.

![image](https://user-images.githubusercontent.com/9677869/89640455-474c8280-d8b8-11ea-9361-8ccf5848fd7b.png)

Steps to reproduce:
launch tarantool master instance with this init file:
```lua
box.cfg{
    listen = 3300,
    replication_synchro_quorum = 3,
    read_only =  false ,
}

box.once("schema", function()
   box.schema.user.create('replicator', {password = 'password'})
   box.schema.user.grant('replicator', 'replication')

   box.schema.space.create('sync', {is_sync=true})
   box.space.sync:create_index('primary')
end)

require('console').start()
```

launch tarantool replica instance with this init file:
```lua
box.cfg{
    listen = 3301,
    replication = 'replicator:password@localhost:3300',
    
    read_only =  true ,
}

require('console').start()
```

in tarantool master instance console do:
```
box.space.sync:select{1}
```
observe the fact that no tuples are returned

in tarantool replica instance console do:
```
box.space.sync:select{1}
```
observe the fact that no tuples are returned

in tarantool master instance console do:
```
box.space.sync:put{1,1}
```
and, while tarantool master instance is blocked while waiting for confirmation from replicas, in tarantool replica instance console do:
```
box.space.sync:select{1}
```

Observe the fact that a tuple [1,1] is returned from replica even though master will rollback the REPLACE and print "error: Quorum collection for a synchronous transaction is timed out" in console after a few seconds

**Comment by sergos** [comment]
Mmm... Why did you name this a bug, if it was expected? The MVCC feature will fix that, but w/o it enabled you'll see the dirty reads. 
I would rather ask for documentation update where it should be put explicitly.

**Comment by ligurio** [comment]
> I would rather ask for documentation update where it should be put explicitly.

there is a ticket about that -
https://github.com/tarantool/doc/issues/1467

**Comment by sergos** [comment]
By the way, in the master (2.6.0) MVCC is available now (after https://github.com/tarantool/tarantool/commit/7c2a0c187e2dc21c8bf99c42b6cc53db7724c5a3) , can you please check the issue is resolved?

**Comment by ligurio** [comment]
@WeCodingNow Could you please recheck issue on Tarantool with enabled TXM? (`box.cfg{memtx_use_mvcc_engine=true}`)

**Comment by sergos** [comment]
The initial behavior is reproducible:
```
###master
Tarantool 2.11.1-0-g96877bd
type 'help' for interactive help
tarantool> box.ctl.promote()
2023-10-31 15:56:31.520 [91604] main/103/interactive I> RAFT: bump term to 2, follow
2023-10-31 15:56:31.520 [91604] main/115/raft_worker I> RAFT: persisted state {term: 2}
---
...

###replica
tarantool> box.space.sync:select{1}
---
- - [1, 1]
...

###master

tarantool> box.space.sync:put{1,1}
---
- error: Quorum collection for a synchronous transaction is timed out
...

###replica
tarantool> box.space.sync:select{1}
---
- - []
...
``` 

Using the following config
```
###master
box.cfg{             
    listen = 3300,
    memtx_use_mvcc_engine = true,
    txn_isolation = 'read-confirmed',
    replication_synchro_quorum = 3,
    read_only =  false ,
}
box.once("schema", function()
   box.schema.user.create('replicator', {password = 'password'})
   box.schema.user.grant('replicator', 'replication')
   box.schema.space.create('sync', {is_sync=true})
   box.space.sync:create_index('primary')
end)

###repllica
box.cfg{                                    
    listen = 3301,
    replication = 'replicator:password@localhost:3300',
    memtx_use_mvcc_engine = true,
    txn_isolation = 'read-confirmed',
    read_only =  true ,
}

```
Gives the expected behavior
```
###master
tarantool> box.space.sync:put{1,1}

###replica
tarantool> box.space.sync:select{1}
---
- []
...
```
