### ISSUE TITLE
message: Invalid MsgPack - packet body  for 1 master 5 replica

### ISSUE THREAD

**Issue by darrenchinesedba** [tarantool/tarantool#5237]
Tarantool version: 2.4.2

OS version: centos 7.7

1 master  

box.info.uuid
---
- 4f606839-ed44-4e4d-a659-f54b397e4997

box.info.cluster 
---
- uuid: 66e1199b-bd4e-4d3e-9be7-d0be2b8eae6f

box.space._cluster:select()
---
- - [1, '4f606839-ed44-4e4d-a659-f54b397e4997']
  - [2, 'ccaffef4-8da0-4994-b2fe-befcc87d4a5e']
  - [3, 'fb1bac54-21eb-4b99-b4e0-c2e8db20849a']
  - [4, '1a2cd59b-9ad2-4258-92a7-6d968871c8bc']

 box.info.replication
---
- 1:
    id: 1
    uuid: 4f606839-ed44-4e4d-a659-f54b397e4997
    lsn: 9522048
  2:
    id: 2
    uuid: ccaffef4-8da0-4994-b2fe-befcc87d4a5e
    lsn: 0
    upstream:
      status: follow
      idle: 0.58607743494213
      peer: replicator@10.2.19.17:3322
      lag: 6.866455078125e-05
    downstream:
      status: follow
      idle: 0.017467212863266
      vclock: {1: 9522048}
  3:
    id: 3
    uuid: fb1bac54-21eb-4b99-b4e0-c2e8db20849a
    lsn: 0
    downstream:
      status: follow
      idle: 0.017282228916883
      vclock: {1: 9522048}
  4:
    id: 4
    uuid: 1a2cd59b-9ad2-4258-92a7-6d968871c8bc
    lsn: 0
    downstream:
      status: stopped
      message: timed out
      system_message: Connection timed out

what is the reason for   uuid: 1a2cd59b-9ad2-4258-92a7-6d968871c8bc   system_message: Connection timed out

**Comment by darrenchinesedba** [comment]
slave 1

box.info.uuid
---
- ccaffef4-8da0-4994-b2fe-befcc87d4a5e

box.info.cluster
---
- uuid: 66e1199b-bd4e-4d3e-9be7-d0be2b8eae6f

box.space._cluster:select()
---
- - [1, '4f606839-ed44-4e4d-a659-f54b397e4997']
  - [2, 'ccaffef4-8da0-4994-b2fe-befcc87d4a5e']
  - [3, 'fb1bac54-21eb-4b99-b4e0-c2e8db20849a']
  - [4, '1a2cd59b-9ad2-4258-92a7-6d968871c8bc']
box.info.replication
---
- 1:
    id: 1
    uuid: 4f606839-ed44-4e4d-a659-f54b397e4997
    lsn: 9522047
    upstream:
      status: follow
      idle: 0.4372571632266
      peer: replicator@127.0.0.1:3303
      lag: 9.8228454589844e-05
    downstream:
      status: follow
      idle: 0.55629548523575
      vclock: {1: 9522047}
  2:
    id: 2
    uuid: ccaffef4-8da0-4994-b2fe-befcc87d4a5e
    lsn: 0
  3:
    id: 3
    uuid: fb1bac54-21eb-4b99-b4e0-c2e8db20849a
    lsn: 0
  4:
    id: 4
    uuid: 1a2cd59b-9ad2-4258-92a7-6d968871c8bc
    lsn: 0

**Comment by darrenchinesedba** [comment]
slave 2 

box.info.uuid
---
- fb1bac54-21eb-4b99-b4e0-c2e8db20849a

box.info.cluster 
---
- uuid: 66e1199b-bd4e-4d3e-9be7-d0be2b8eae6f

box.space._cluster:select()
---
- - [1, '4f606839-ed44-4e4d-a659-f54b397e4997']
  - [2, 'ccaffef4-8da0-4994-b2fe-befcc87d4a5e']
  - [3, 'fb1bac54-21eb-4b99-b4e0-c2e8db20849a']
  - [4, '1a2cd59b-9ad2-4258-92a7-6d968871c8bc']

box.info.replication
---
- 1:
    id: 1
    uuid: 4f606839-ed44-4e4d-a659-f54b397e4997
    lsn: 9522024
    upstream:
      status: follow
      idle: 0.50331731047481
      peer: replicator@10.2.19.17:3303
      lag: 0.0046825408935547
  2:
    id: 2
    uuid: ccaffef4-8da0-4994-b2fe-befcc87d4a5e
    lsn: 0
    upstream:
      peer: replicator@10.2.19.17:3322
      lag: 4.1422691345215
      status: stopped
      idle: 88600.409119236
      message: Invalid MsgPack - packet body
  3:
    id: 3
    uuid: fb1bac54-21eb-4b99-b4e0-c2e8db20849a
    lsn: 0
  4:
    id: 4
    uuid: 1a2cd59b-9ad2-4258-92a7-6d968871c8bc
    lsn: 0
    downstream:
      status: follow
      idle: 0.64400321245193
      vclock: {4: 3, 1: 9522024}

**Comment by darrenchinesedba** [comment]
slave 3 

box.info.uuid
---
- 1a2cd59b-9ad2-4258-92a7-6d968871c8bc

 box.info.cluster 
---
- uuid: 66e1199b-bd4e-4d3e-9be7-d0be2b8eae6f

box.space._cluster:select()
---
- - [1, '4f606839-ed44-4e4d-a659-f54b397e4997']
  - [2, 'ccaffef4-8da0-4994-b2fe-befcc87d4a5e']
  - [3, 'fb1bac54-21eb-4b99-b4e0-c2e8db20849a']
  - [4, '1a2cd59b-9ad2-4258-92a7-6d968871c8bc']
  - [5, '3b0fd768-605b-4dab-a98f-93a668b4c90b']
  - [6, '7622b1e9-1ab0-45e0-826c-bc8d83af82d0']
  - [7, 'a9717b55-4146-4314-b417-5186d0992a51']

box.info.replication
---
- 1:
    id: 1
    uuid: 4f606839-ed44-4e4d-a659-f54b397e4997
    lsn: 9522050
    upstream:
      peer: replicator@10.2.19.17:3303
      lag: 1.8067572116852
      status: stopped
      idle: 93018.484621109
      message: Invalid MsgPack - packet body
  2:
    id: 2
    uuid: ccaffef4-8da0-4994-b2fe-befcc87d4a5e
    lsn: 0
    upstream:
      peer: replicator@10.2.19.17:3322
      lag: 0.90740966796875
      status: stopped
      idle: 92297.537609717
      message: Invalid MsgPack - packet body
  3:
    id: 3
    uuid: fb1bac54-21eb-4b99-b4e0-c2e8db20849a
    lsn: 0
    upstream:
      status: follow
      idle: 0.28844106849283
      peer: replicator@10.2.19.22:3323
      lag: 0.00010442733764648
  4:
    id: 4
    uuid: 1a2cd59b-9ad2-4258-92a7-6d968871c8bc
    lsn: 4
  6:
    id: 6
    uuid: 7622b1e9-1ab0-45e0-826c-bc8d83af82d0
    lsn: 0
    downstream:
      status: stopped
      message: timed out
      system_message: Connection timed out
  7:
    id: 7
    uuid: a9717b55-4146-4314-b417-5186d0992a51
    lsn: 0
    downstream:
      status: stopped
      message: timed out
      system_message: Connection timed out

**Comment by kyukhin** [comment]
Could you please provide a way we can reproduce this?
