### ISSUE TITLE
Custom aggregate Lua functions in SQL

### ISSUE THREAD

**Issue by msiomkin** [tarantool/tarantool#5240]
Custom Lua routines for SQL functionality (https://www.tarantool.io/en/doc/2.3/reference/reference_sql/sql/#calling-lua-routines-from-sql) can't be considered even a bit production ready without an ability to write aggregate functions. Please do add support for it!

See also: https://github.com/tarantool/tarantool/issues/2579

**Comment by kyukhin** [comment]
I've extended original issues w/ proposal to allow both C and Lua functions to be registered as aggregates and close this issue.
