### ISSUE TITLE
sql: Consider to use index from `like` expression instead of primary

### ISSUE THREAD

**Issue by filonenko-mikhail** [tarantool/tarantool#5249]
Tarantool version:
2.4

Bug description:
In case when sql `where like` expression is used, sql planner wants to make iteration over primary key. 
There is an error `SQL does not support using non-TREE index type` if primary index is hash.

Could you please consider to use iteration index from `like` expression.  

Steps to reproduce:

```lua
local log = require('log')

box.cfg{}

box.schema.space.create('model',
                        {format={{name="first", type="number"},
                            {name="random", type="string"}},
                         if_not_exists=true,
})

box.space.model:create_index('primary',
                            {parts={{
                                  field="first", type="number"
                                    },
                            },
                             type="hash",
                             if_not_exists=true})

box.space.model:create_index('random',
                             {parts={{
                                    field="random", type="string"
                                     },
                             },
                              type="tree",
                              if_not_exists=true
})

local rc, err = box.execute([[
  explain select * from "model" where "random" like ?
]], {'us%'})
assert(err == nil, tostring(err))

rc, err = box.execute([[
  explain query plan select * from "model" where "random" like ?
]], {'us%'})
assert(err == nil, tostring(err))

rc, err = box.execute([[
  select * from "model" where "random" like 'us%'
]])
assert(err == nil, tostring(err))

rc, err = box.execute([[
  select * from "model" indexed by "random" where "random" like ?
]], {'us%'})
assert(err == nil, tostring(err))
```

tarantool 2.4
SQL does not support using non-TREE index type. Please, use INDEXED BY clause to force using proper index.

**Comment by ImeevMA** [comment]
LIKE is currently performed using built-in functions that do not have access to indices. This may be fixed in future releases.

**Comment by Korablev77** [comment]
For the certain types of queries like operator still can use index (in case search condition can be split into two inequalities). See https://github.com/tarantool/tarantool/issues/3889#issuecomment-517333607
My guess that in your particular case index is not used due to presence of value to be bound: such values are not available for query planner, so it can't determine whether like-to-between optimization can be applied or not. Proof:
```
tarantool> box.execute([[
  explain query plan select * from "model" where "random" like 'us%'
]])
---
- metadata:
  - name: selectid
    type: integer
  - name: order
    type: integer
  - name: from
    type: integer
  - name: detail
    type: text
  rows:
  - [0, 0, 0, 'SEARCH TABLE model USING COVERING INDEX random (random>? AND random<?)
      (~16384 rows)']
...
```

**Comment by filonenko-mikhail** [comment]
So, I think we can consider such case from user experience side.
> it can't determine

**Comment by filonenko-mikhail** [comment]
So, I close to descrease infonoise.
