### ISSUE TITLE
Cannot download repomd.xml 2.5

### ISSUE THREAD

**Issue by jobs-git** [tarantool/tarantool#5253]
Tarantool version:
2.5
OS version:
CentOS 8
Bug description:
https://hb.bizmrg.com/tarantool_repo/release/2.5/el/x86_64/repodata/repomd.xml
Steps to reproduce:
https://www.tarantool.io/en/download/os-installation/rhel-centos/

**Comment by Totktonada** [comment]
> baseurl=https://download.tarantool.org/tarantool/release/2.5/el/$release/x86_64/

Aren't you missed to set the `release` shell variable to 7 or 8? It is part of the instruction.

**Comment by jobs-git** [comment]
I did. Darn!
