### ISSUE TITLE
Report crash statistics

### ISSUE THREAD

**Issue by srgkvlv** [tarantool/tarantool#5261]
As a solution team, we need to get data on errors and crashes from Tarantool installations. We need this to track the stability of the product and understand how we can improve it.

Main usage scenarios:
1) Quickly identify bugs and prioritize them. We need to know which component and version of Tarantool and for which OS requires the most prompt fix.
2) Track the quality of the product and quickly understand how it has changed in each new version relative to the previous one.

Functionality:
1. Intercept crashes and errors of Tarantool and store the following information about them: 
- OS version
- Type of the error and/or the signal by which the process was terminated
- Where the event has occurred (component name, line number, memory address, etc.)
- Stacktrace

2. feedback_daemon sends the information to the backend

3. The backend sends a weekly report email with statistics of failures. The report contains:
- Total number (and percentage) of installations with fails and installations without fails broken by Tarantool versions with number of «segmentation fault» and «out of memory» errors for each of version
- Top 10 places in which failures occurred 

Preferred report format example: https://docs.google.com/document/d/1i-3CwZwdc2KsFpduIrJwtG59s_nzNR95ouaeGk-Fni0/edit?usp=sharing

4. Web-page on the backend where the following detailed information available for the selected period:
- Total number (and percentage) of installations without fails and installations with fails for each version of Tarantool
- Number of «segmentation fault» and «out of memory» errors for each version of Tarantool

**Comment by sharonovd** [comment]
#5372 must be implemented along with it (security pre-requisite)
