### ISSUE TITLE
curl: cmake build hides its symbols and not possible to use it

### ISSUE THREAD

**Issue by avtikhon** [tarantool/tarantool#5268]
Tarantool version:
All

OS version:
All

Bug description:

Building using cmake got issue in testing:
```
  [043] box-tap/gh-5223-curl-exports.test.lua                           [ fail ]
  [043] Test failed! Output from reject file box-tap/gh-5223-curl-exports.reject:
  [043]
  [043] Last 15 lines of Tarantool Log file [Instance "app_server"][/build/usr/src/debug/tarantool-2.6.0.54/test/var/043_box-tap/gh-5223-curl-exports.test.lua.tarantool.log]:
  [043] LuajitError: ...tool-2.6.0.54/test/box-tap/gh-5223-curl-exports.test.lua:57: tarantool: undefined symbol: curl_version_info
```
It happened because curl used visibility hiding mode for its symbols
and the test could not use it. To fix it symbols hiding disabled for gcc.

Steps to reproduce:

Optional (but very desirable):
* coredump
* backtrace
* netstat

**Comment by rosik** [comment]
You're not sincere.

> Tarantool version:
All
> OS version:
All

I'm running Ubuntu 20.04.1 LTS:

```text
$ ./test-run.py --builddir /opt/tarantool-build gh-5223-curl-exports.test.lua

Installing the server ...
    Found executable   at /opt/tarantool-build/src/tarantool
    Found tarantoolctl at /opt/tarantool-build/extra/dist/tarantoolctl

Tarantool 2.6.0-61-g5a9b79fa0
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/opt/tarantool-install -DENABLE_BACKTRACE=OFF
Compiler: /usr/bin/cc /usr/bin/c++
C_FLAGS: -fexceptions -funwind-tables -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-gnu-alignof-expression -fno-gnu89-inline -Wn
o-cast-function-type
CXX_FLAGS: -fexceptions -funwind-tables -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Wno-gnu-alignof-expres
sion -Wno-cast-function-type

======================================================================================
WORKR TEST                                            PARAMS          RESULT
---------------------------------------------------------------------------------
[001] box-tap/gh-5223-curl-exports.test.lua                           [ pass ]
---------------------------------------------------------------------------------
Statistics:
* pass: 1
```

**Comment by rosik** [comment]
I've checked recent CI jobs on master (e.g. https://travis-ci.org/github/tarantool/tarantool/jobs/725558549, https://gitlab.com/tarantool/tarantool/-/pipelines/188554706), most of them are green.

Could you provide a better issue description and a reproducer.

**Comment by avtikhon** [comment]
Changes already partly committed and the issue already resolved, closing.

**Comment by Totktonada** [comment]
If you're about [2.6.0-36-g29ec62891](https://github.com/tarantool/tarantool/commit/29ec628918bd7279de08e47becc070420775c2eb), then it is the same commit, where the test was added. And your description shows 2.6.0.54 in a path, it goes afterwards.

There still no information how to reproduce the situation and I guess it was some broken setup (old tarantool with newer tests or something like this). So I'm okay with closing, but the reason is that the issue looks invalid and nothing proves the opposite.
