### ISSUE TITLE
Build fail with openSUSE

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#5269]
I have openSUSE-Leap-15.2.
It is new. Tarantool is the first package that I tried to install on it.

I tried to download Tarantool from source and build.
The instructions are in
https://www.tarantool.io/en/doc/2.5/dev_guide/building_from_source/

I followed the instructions following the words
"For RHEL/CentOS/Fedora, say:"
except that, instead of yum install, I said sudo zypper install.
I installed one more package with zypper install git.

I followed the instructions following the words
"# Python module for parsing YAML (pyYAML), for test suite:"

I tried to follow the instructions following the words
"Finally, use Python pip to bring in Python packages that
may not be up-to-date in the distro repositories."
This failed because "pyconfig.h" was missing, but I decided
to ignore that, since this distro repository is recent.

I followed the instruction after the words
"Use git to download the latest Tarantool source code ...".
including the specification "-b 2.2".
Then I followed the instruction to run cmake
cmake .
Then I ran make (without specifying the C or C++ version):
make
and the error message is
make[2]: *** no rule to make target 'build/curl/dest/lib/libcurl.a',
needed by 'src/tarantool'. Stop.

I am aware of the note on the instruction page about "curl or OpenSSL errors";
when I say "openssl version" the response is "openSSL 1.1.1d 10 Sep 2019".

I write this due to a suggestion from A. Turenko
https://github.com/tarantool/doc/issues/1492#issuecomment-684976658

**Comment by avtikhon** [comment]
> I tried to download Tarantool from source and build.
> The instructions are in
> https://www.tarantool.io/en/doc/2.5/dev_guide/building_from_source/

Ok, seems that instructions must be updated, thanks.

> I followed the instruction after the words
> "Use git to download the latest Tarantool source code ...".
> including the specification "-b 2.2".

Seems that it was the root cause of the issue - branch 2.2 doesn't support openSUSE.

**Comment by Totktonada** [comment]
> Ok, seems that instructions must be updated, thanks.

Filed https://github.com/tarantool/doc/issues/1494

> Seems that it was the root cause of the issue - branch 2.2 doesn't support openSUSE.

Nope, I successfully built 2.2.3-1-g98ecc909a on openSUSE Leap 15.2 from sources.

@pgulutzan Can you, please, attach a full build log? Maybe there is some error above in the build log (or at least difference from my build log).

**Comment by pgulutzan** [comment]
See attached file.

[log.txt](https://github.com/tarantool/tarantool/files/5165045/log.txt)

**Comment by Totktonada** [comment]
Thanks!

I spotted the problem: the libcurl archive file is installed into `build/curl/dest/lib64/libcurl.a`, but it expected to be in `build/curl/dest/lib/libcurl.a` by our CMake files. We can either add --libdir to curl's `./configure <...>` command or adjust the required file name in our CMake files (based of what?).

Still unclear, why it is different inside my docker container (`opensuse/leap:15.2`) and on the Peter's system.

**Comment by pgulutzan** [comment]
@Totktonada since you have spotted the problem, will you turn off the Need Feedback flag? Or do you want me to say something further?

**Comment by Totktonada** [comment]
Thanks for the reminder. It is still unclear when it appears (why the problem exists on one openSUSE Leap 15.2, but does not on another). If you can shed some light, how to better reproduce it: say, base docker or virtualbox image where you're experimenting, it may be helpful. However I guess we can deduce necessary information if we'll deeper look at curl's configure script. Removed 'need feedback' label.

**Comment by Totktonada** [comment]
There are the following lines in the build scripts after #4968:

```cmake
    # The default values for the options below are not always
    # "./lib", "./bin"  and "./include", while curl expects them
    # to be.
    list(APPEND LIBCURL_CMAKE_FLAGS "-DCMAKE_INSTALL_LIBDIR=lib")
    list(APPEND LIBCURL_CMAKE_FLAGS "-DCMAKE_INSTALL_INCLUDEDIR=include")
    list(APPEND LIBCURL_CMAKE_FLAGS "-DCMAKE_INSTALL_BINDIR=bin")
```

Is the issue resolved on the 2.6.0-196-g2b0760192+ versions?

**Comment by pgulutzan** [comment]
I now have openSUSE Tumbleweed on VirtualBox and it is not "new", that is, I was not testing immediately after installing the OS.
I downloaded Tarantool 2.6.1 from source today.
The build succeeded.
So I believe this can be closed.

**Comment by Totktonada** [comment]
Nice, thanks!
