### ISSUE TITLE
Deprecate replication_connect_quorum

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#5272]
The option is useless after bootstrap. All it can do is break a working instance, after it is already booted. People constantly have problems with this option.

The only purpose when it is useful is the cluster bootstrap time, when need to wait for at least specified number of replicas before creating replicaset UUID and registering all of them in `_cluster` on a selected leader. After bootstrap the option is useless. All installations set it to 0 as soon as possible.

Another reason why it should not exist is a conflict with synchronous replication options - there is `replication_synchro_quorum`. 

The option can be renamed to `replication_boot_quorum`, used at boot time like now, and then ignored in all subsequent instance restarts.

**Comment by sergepetrenko** [comment]
To be done in scope of this ticket:
Introduce new `box.cfg` option: `bootstrap_strategy`, which receives 2 possible values `"auto"` -- default, and `"legacy"` -- compatibility with current `replication_connect_quorum` behaviour.

`bootstrap_strategy = "config"` and `bootstrap_strategy = "supervised"` will be done in scope of #7999.
