### ISSUE TITLE
module api: expose everything that is needed for external key_def module

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#5273]
Tarantool version: 2.6.0-52-g71a24b9f2.

We plan to extract built-in key_def module with ability to run on of all supported tarantool release series since 1.10. The module API lacks at least key def creation function, which would support nullability, collation and JSON path (`box_key_def_new()` does not), and I guess many other functionality.

Caution: I really propose to add a new functionality to tarantool 1.10, but since it is only about the module API, risks are lower.

Part of https://github.com/tarantool/vshard-cluster-api/issues/5

**Comment by Gerold103** [comment]
I took a glance at the changes, I am against exposing certain internal things. Ready to discuss.

**Comment by Totktonada** [comment]
Thank you, that's nice to see you interest!

Can you give a list of such things and briefly explain why they should not be exported?

And it seems now the good time to share my observations and thoughts around ABI compatibility. You can find it [here](https://lists.tarantool.org/pipermail/tarantool-discussions/2020-September/000095.html) if you're curious. It is not much polished: just bag of thoughts. Sorry for that.

**Comment by Totktonada** [comment]
From offline discussion with Vlad (sketchy notes):

- Fiber region is fragile.
  - Some box functions may call fiber_gc() and so flush everything on the region (and it is not always related to yield).
    - Examples: box_txn_commit(), box_txn_rollback(), txn_commit_ro_stmt(), sqlVdbeDelete() (called after any SQL request AFAIU).
    - It seems all functions that called fiber_gc() except ones related to txn / recovery / box.cfg / SQL do it within its own fibers, but I cannot prove it formally. Maybe it more or less safe?
    - Raw idea: provide another region with strict guarantees (say, that it never flushed until yield) and switch the module API to the fiber region when (if) it will provide the same guarantees.
  - Vlad mention that there is the idea to move fiber region to cord, so freezing of fiber_region_foo() naming for the module API may be not good idea. Proposed to rename it to box_region_foo().
  - We also looked whether it is possible to don't expose a region to the module API at all. Alexander's objections:
    - It seems meaningful to pass an allocator to module API functions that perform allocations, which cumulative size is not know ahead of time. We have box_tuple_extract_key(), which allocates a buffer on the fiber region, but does not accept a region as an argument. It is bad in two ways: it is not obvious how to release the result, it adds dependency from fiber.c in tuple_extract_key.cc.
    - It sometimes [convenient](https://github.com/tarantool/tarantool/blob/2a01ce91270267dfcf344f83bdeed099806fe5ff/src/lua/pickle.c#L67-L73) to lean on the fact that a fiber / box region will be eventually cleaned up. It may be important, when a called Lua or Lua/C code may raise a Lua error (especially when it is a callback that is not written by us), but using pcall() / cpcall() is not desirable due to performance matters.
  - It seems we should allow to pass a region into a box function (expose `box_region_t *box_region(void)`) as well as allow to truncate this region (expose `box_region_used()` and `box_region_truncate()` at least).
  - It worth to note [why](https://lists.tarantool.org/pipermail/tarantool-discussions/2020-September/000095.html) Alexander against of linking the small library into modules.

- We discussed whether field type in box_key_part_t should be a string or some id.
  - First, enum field_type is in the module API, but some fields were added in the middle, so it is not usable for modules. field_type_MAX also not usable in modules, because its value varies over tarantool versions. The extra mapping to another public enum / id is necessary if we'll going to use numeric IDs: existing enum field type cannot be reused.
  - It also worth to note that enum size is compiler specific thing, so it seems enums should not be used in the module API, because tarantool and a module may be built by different compilers or compiler versions.
  - Numerical IDs would require extra 'convert from/to string' functions in case of key_def external module.
  - Collations already have string identifiers, because numerical IDs may vary across different tarantool instances in the general case. This situation is different from field type, but some consistency in such identifiers looks nice (for Alexander).
  - Considering all said above Alexander think that using of string field types in the module API would be more convenient. Vlad is not quite convinced, but is not strictly against.

I may miss some points, the notes were written after the meeting.

**Comment by Gerold103** [comment]
You missed the thing about error codes and types. We've decided to go for box_error_set() for now, without public API changes in this part.

**Comment by Totktonada** [comment]
Ah, yep, thanks! I have some doubts about this approach in the general case: it seems it would be good if any module (internal or external) would give errors from the same hierarchy. It matters more when a user may treat some errors as transient ones and handle them programmatically. For example a caller of [<popen_handle>:write(<...>)](https://www.tarantool.io/en/doc/latest/reference/reference_lua/popen/#lua-function.popen_handle.write) may want to handle TimedOut error differently from other ones and, say, implement some retrying strategy. However this is not the case for key_def and merger, so I'm okay with ClientError and box_error_set() within the scope of this task.

I just want to note that having two set of error types looks strange for me in the long terms.
