### ISSUE TITLE
I can drop one system space

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#5279]
I have Ubuntu 18.04. I have Tarantool 2.5, pulled from source today.

If I try to drop a memtx system space, I get an error
Can't drop the primary key in a system space
But I can drop a local blackhole system space which has no primary key:
box.execute([[DROP TABLE "_vinyl_deferred_delete";]])
It works. The table is dropped.
I think this is an oversight, since I imagine that the intent was
that it would be illegal to drop any system space.

**Comment by ImeevMA** [comment]
The same is possible in `Lua`:
```
tarantool> box.space._vinyl_deferred_delete:drop()
---
...

tarantool> box.space._vinyl_deferred_delete
---
- null
...

tarantool> 

```
