### ISSUE TITLE
Please add 'subtract' (-) operation for update

### ISSUE THREAD

**Issue by unera** [tarantool/tarantool#528]
uses tarantool 1.5 a user was forced to use add operation with big values.

Now we have numeric that can be
 - double
 - float
 - (u)int{8,16,32}

So old trick wont work properly.

**Comment by alyapunov** [comment]
Arithmetic update rules:
0. There are 6 operations (+, -, *,&, |, ^) that may apply to a numeric tuple field with a numeric second operand. Numeric in terms of msgpack is DOUBLE, FLOAT, INT or UINT.
1. Bit operations (&, |, ^) are only alowed on positive integers.
2. If one of the operands is double - both of the operands are converted to double and result is double
3. Else if one of the operands is float - both of the operands are converted to float and result is float
4. Else - integers. Integer operands are threated as real integer, but if the result of the operation outbound ragne [INT64_MIN, UINT64_MAX] - an error is occured

**Comment by kostja** [comment]
Pushed.
