### ISSUE TITLE
New options 'after', 'after_key', 'after_pk' in select and pairs

### ISSUE THREAD

**Issue by alyapunov** [tarantool/tarantool#5282]
Generalization of #3898.

Implement an option `after` in `select` and `pairs` methods. If it's specifiend it must contain a tuple from which selection must continue. More strictly:
- For tree index (memtx and vinyl) and forward iteration (EQ, GE, GT, ALL) `select` and `pairs` must internally skip all tuples less-or-equal-to tuple given in `after` in terms of that index.
- For tree index (memtx and vinyl) and reverse iteration (REQ, LE,  LT) `select` and `pairs` must internally skip all tuples greater-or-equal-to tuple given in `after` in terms of that index.
- That interanl skipping must be accounted for `offset` option.
- For all other indexes that option must not be allowed.
- In lua that must be table or cdata with C pointer to tuple.
- In IPROTO that must be a msgpack with the tuple.
- Only those fields of the `after` tuple that participate in key definition of the index (and also, if the index is not unique, key definition of the primary index) are actually make sense; all other fields in the tuple are guaranteed to be ignored. 

Implement options `after_key` and `after_pk` in `select` and `pairs` methods. Both are allowed if `after` is not specified. They must work exacly as if `after` option was set to a tuple that has key fields of that index (and key fields of the primary index) equal to `after_key` (and `after_pk`). `after_key` can be omitted if iterator is EQ or REQ and the main key of the selection is full (it makes sense for non-unique secondary; `after_key` could be taken equal to main key in that case).

<details>
<summary>Example of expected behaviour</summary>

```lua
tarantool> s = box.schema.space.create('test')
tarantool> pk = s:create_index('pk', {parts={1, 2}})
tarantool> sk = s:create_index('sk', {parts={2}, unique=false})
tarantool> for i=1,5 do for j=1,3 do s:replace{i, j} end end
---
...
tarantool> sk:select{2}
---
- - [1, 2]
  - [2, 2]
  - [3, 2]
  - [4, 2]
  - [5, 2]
...
tarantool> sk:select({2}, {after={3, 2}})
---
- - [4, 2]
  - [5, 2]
...
tarantool> sk:select({2}, {after={3, 2}, iterator='REQ'})
---
- - [2, 2]
  - [1, 2]
...
tarantool> sk:select({2}, {after_pk={3}})
---
- - [4, 2]
  - [5, 2]
...
tarantool> sk:select({}, {after_key={2}, after_pk={3}})
---
- - [4, 2]
  - [5, 2]
  - [1, 3]
  - [2, 3]
  - [3, 3]
  - [4, 3]
  - [5, 3]
...
```
</details>

**Comment by unera** [comment]
I think that 

- `after_key` - already exists
- `after_tuple` - bad variant for remote clients

So, I suggest the variant

`index:select(key, { after=PK, limit=10, iterator='GE`})`
`index:pairs(key, {after=PK, iterator='GE'})`

So:

1. after always contains primary key
2. if `after` is not null, then iterator will fetch the tuple, extract start index-key from the tuple and continue iterate (`GE` will be replaced by `GT`, etc)
  - if tuple does not exists, it will return empty recordlist (EOF)

**Comment by drewdzzz** [comment]
Will be done in #7639.
