### ISSUE TITLE
Raft: design how to quickly detect tied score during election to restart it faster

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#5285]
If raft election timeout has order of seconds, and in an on-going election nobody is going to win (for example, when all nodes just voted for self immediately), a next election still starts only after the seconds pass. It would be nice to be able to detect the tied score when it happens and restart the election faster.

**Comment by Totktonada** [comment]
> It is not documented nor has a changelog file because this is an
> optimization. Can't be observed except in logs or with a watch.

Agreed regarding documentation.

I doubt regarding a changelog. The scenario looks realistic enough to meet it on production. So the change is the improvement of operating characteristics. It is good to deliver information about such enhancements to our users.
