### ISSUE TITLE
Implement telemetry built-in engine for performance analisys

### ISSUE THREAD

**Issue by cyrillos** [tarantool/tarantool#5289]
Currently we don't have any built-in performance measurement engine so it is hard to estimate if some new functionality or redesign get situation better (of course there is `time` and `perf` tools but they are not enough). Thus we need an internal telemetry engine.

**Comment by cyrillos** [comment]
After being discussed (and implemented a couple of draft code versions) the telemetry in the form of general counters seems to be not needed. So I close the issue.

**Comment by Gerold103** [comment]
I don't remember us deciding that the issue is not needed. We only ended up deciding, that most of the users want kind of request tracing.

**Comment by cyrillos** [comment]
The issue in the form I've been implementing is not needed. We already found that `perf` should suite ours need. The tracing for requests is completely different beast. And I'll open the bug for that if we choose to implement.
