### ISSUE TITLE
[1pt] asan: flaky memory leak in AccessDeniedError

### ISSUE THREAD

**Issue by avtikhon** [tarantool/tarantool#5299]
Tarantool version:
Tarantool 2.6.0-71-ga04778273
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_BACKTRACE=ON
Compiler: /usr/bin/clang-8 /usr/bin/clang++-8
C_FLAGS: -Wno-unknown-pragmas -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -msse2 -fsanitize=address -fsanitize-blacklist=/source/asan/asan.supp -std=c11 -Wall -Wextra -Wno-strict-aliasing -fsanitize=alignment,bool,bounds,builtin,enum,float-cast-overflow,float-divide-by-zero,function,integer-divide-by-zero,return,shift,unreachable,vla-bound -fno-sanitize-recover=alignment,bool,bounds,builtin,enum,float-cast-overflow,float-divide-by-zero,function,integer-divide-by-zero,return,shift,unreachable,vla-bound -Wno-char-subscripts -Wno-gnu-alignof-expression -Werror
CXX_FLAGS: -Wno-unknown-pragmas -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -msse2 -fsanitize=address -fsanitize-blacklist=/source/asan/asan.supp -std=c++11 -Wall -Wextra -Wno-strict-aliasing -fsanitize=alignment,bool,bounds,builtin,enum,float-cast-overflow,float-divide-by-zero,function,integer-divide-by-zero,return,shift,unreachable,vla-bound -fno-sanitize-recover=alignment,bool,bounds,builtin,enum,float-cast-overflow,float-divide-by-zero,function,integer-divide-by-zero,return,shift,unreachable,vla-bound -Wno-char-subscripts -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Werror

OS version:
Debian GNU/Linux buster/sid

Bug description:
In asan/lsan check found common leaks after strdup() function,
    because of its internal allocations in AccessDeniedError class
    for m_object_name, m_object_type, m_access_type buffers:
```    
      Indirect leak of 24 byte(s) in 4 object(s) allocated from:
        #0 0x50b550 in __interceptor_strdup (/tnt/src/tarantool+0x50b550)
        #1 0xd71a98 in AccessDeniedError::AccessDeniedError(char const*, unsigned int, char const*, char const*, char const*, char const*, bool) /tarantool/src/box/error.cc:309:18
        #2 0xd71c5b in BuildAccessDeniedError /tarantool/src/box/error.cc:319:14
        #3 0x567864 in access_check_space /tarantool/src/box/space.c:91:5
        #4 0x55e58b in check_index(unsigned int, unsigned int, space**, index**) /tarantool/src/box/index.cc:172:6
        #5 0x55e58b in box_index_max /tarantool/src/box/index.cc:296
        #6 0x2abfea88  (<unknown module>)
```

To fix the found issues tried to use local memory allocation in stack
for these buffers. In the same situation in a common CustomError class
m_custom_type buffer was locally allocated with 64 size. So the buffers
were changed from strdup() function internal allocation to local setup
with the same size. But this fix didn't pass the review:

https://lists.tarantool.org/pipermail/tarantool-patches/2020-August/019176.html
```
3. It does not look like a good idea. CustomError uses fixed size buffer for
error message, which is considered not as important as error object attributes.
We can't allocate everything inside the error object structure. What will
happen when CustomError gets payload? It definitely won't fit into a fixed buffer.

It is necessary to investigate deeper, why the destructor wasn't called. Any why
ASAN does not consider the AccessDeniedError object leaked itself, because it is
also on the heap.
```

Steps to reproduce:
Login to dev1 test host

Start the docker container:
```
docker run --network=host -v $PWD:/source -w /source -ti registry.gitlab.com/tarantool/tarantool/testing/debian-buster:latest
```
Inside the docker container run:
```
mkdir /tnt ; cd /tnt/ ; rm -rf /tnt/*

CC=clang-8 CXX=clang++-8 cmake /tarantool \
        -DCMAKE_BUILD_TYPE=RelWithDebInfo \
        -DENABLE_WERROR=ON \
        -DENABLE_ASAN=ON \
        -DENABLE_UB_SANITIZER=ON && make -j

cd test
```

Create test 'box/access_leak.test.lua':
```
test_run = require('test_run').new()
box.schema.user.create('test')
box.session.su('guest')
box.schema.user.create('test')
box.schema.func.create('test')
```

And run command:
```
export ASAN=ON ; export LSAN_OPTIONS=suppressions=/source/asan/lsan.supp ; export ASAN_OPTIONS=heap_profile=0:unmap_shadow_on_exit=1:detect_invalid_pointer_pairs=1:symbolize=1:detect_leaks=1:dump_instruction_bytes=1:print_suppressions=0 ; while `! ./test-run.py --builddir /tnt --vardir /tnt/test/var --force box/access_leak.test.lua 2>&1 | tee a.log | grep -A15 box_index_max >/dev/null` ; do date ; done ; cat a.log
```

Optional (but very desirable):
* coredump
* backtrace
* netstat

**Comment by nshy** [comment]
Fixed by PR https://github.com/tarantool/tarantool/pull/10516.
