### ISSUE TITLE
coio_getaddrinfo() crashes inside libeio

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#5312]
Tarantool crashes on Mac when run any tests involving creating and destroying threads for years already, randomly. Sometimes a test fails 100% cases, and stops after something not related is changed on master. That significantly complicates local development, and also signals that there is clearly a bug, probably affecting users, because the crash is almost always the same, about accessing a corrupted pthread_mutex object inside libeio. That may lead to anything, including stored data corruption.
I see that almost all the crashes happen inside coio_getaddrinfo(), and deep inside libeio. coio_getaddrinfo() tries to use internal libeio API, and probably that is the reason. Maybe it is used incorrectly. It is worth trying to rewrite whole coio_task using eio_custom() instead of touching internal libeio API. Also the reason may be that libeio wasn't supposed to be used from multiple threads, and it was incorrectly patched by somebody from our team.

**Comment by Totktonada** [comment]
I would try to update libev (#4909) and libeio first.

**Comment by sergos** [comment]
The problem was because static allocator was used in an incorrect way. As a result the thread local variable following the static buffer of the allocator is overwritten resulting a crash.
Here's a culprit:
```
--- src/lib/core/sio.c:55
        int name_size = 2 * SERVICE_NAME_MAXLEN;
        char *name = static_alloc(name_size);
        int n = snprintf(name, name_size, "fd %d", fd);
        if (fd >= 0) {
                struct sockaddr_storage addr;
                socklen_t addrlen = sizeof(addr);
                int rc = getsockname(fd, (struct sockaddr *) &addr, &addrlen);
                if (rc == 0) {
                        n += snprintf(name + n, name_size - n, ", aka %s",
                                sio_strfaddr((struct sockaddr *)&addr,
                                                                addrlen));
                }

```
By the time of the last ```snprintf``` the ```n``` exceeds the ```name_size``` and result in a buffer overrun. 
The reason of this is than ```snprintf``` doesn't return the number of bytes it prints, rather the original size of the string.
