### ISSUE TITLE
Broken Gentoo build

### ISSUE THREAD

**Issue by ligurio** [tarantool/tarantool#5325]
@Totktonada said that Gentoo build has been broken commit with Jepsen integration to CI.
This patch adds checkout of repository with Jepsen tests on build stage, Gentoo builds software in sandbox without network access and due to this build fails.

**Comment by Totktonada** [comment]
Workaround:

```sh
FEATURES=-network-sandbox emerge -av1 tarantool
```

**Comment by ligurio** [comment]
[Tarantool-patches] [PATCH 1/2] cmake: move jepsen targets under option WITH_JEPSEN
https://lists.tarantool.org/pipermail/tarantool-patches/2020-September/019640.html

**Comment by Totktonada** [comment]
Confirmed, the installing on Gentoo succeeds now.
