### ISSUE TITLE
test: flaky small/obuf.test test

### ISSUE THREAD

**Issue by avtikhon** [tarantool/tarantool#5345]
Tarantool version:
Tarantool 2.6.0-114-g665543369
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_BACKTRACE=ON
Compiler: /usr/bin/cc /usr/bin/c++
C_FLAGS:-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches  -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type
CXX_FLAGS:-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches  -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type

OS version:
Linux (Debian 10, OpenSUSE 15.2, Fedora 28)

Bug description:
https://gitlab.com/tarantool/tarantool/-/jobs/759385208#L2985

[artifacts.zip](https://github.com/tarantool/tarantool/files/5288267/artifacts.zip)

Not possible to use original results file to get checksum due to it has changing path in error message.
```
[181] --- small/obuf.result	Sun Sep 27 08:07:09 2020
[181] +++ small/obuf.reject	Sun Sep 27 08:13:09 2020
[181] @@ -1,2 +1,2 @@
[181] +Test failed: obuf_capacity(&buf) > 0 is false at /build/usr/src/debug/tarantool-2.6.0.114/src/lib/small/test/obuf.c:51, in function 'obuf_basic'
[181]  	*** obuf_basic ***
[181] -	*** obuf_basic: done ***
```

Steps to reproduce:

Optional (but very desirable):
* coredump
* backtrace
* netstat

**Comment by Totktonada** [comment]
Still actual, [got](https://github.com/tarantool/tarantool/runs/1929528509) it in CI on [1.10.9-42-gc85d2d971](https://github.com/tarantool/tarantool/commit/c85d2d97115654f9209dc30d58bb7024fd79a68e).

**Comment by Totktonada** [comment]
See https://github.com/tarantool/small/pull/36
