### ISSUE TITLE
sql: define rules for determining the type of result of bitwise operations

### ISSUE THREAD

**Issue by ImeevMA** [tarantool/tarantool#5364]
Currently result of bitwise operations have type int64. However Tarantool do not have such type.

There is three suggestions for now:
1) Left as it is (type of result - int64).
2) If at least one of operands is negative, the result of type int64. Otherwise, the result of type uint64. This may cause some troubles for understanding, for example `18446744073709551615 | -1 & 1` is `18446744073709551615` though we have -1.
3) Make the result to be of type uint64 (which is type UNSIGNED in Tarantool).

**Comment by ImeevMA** [comment]
@pgulutzan What do you think about this issue?

**Comment by ImeevMA** [comment]
Currently it works this way:
```
select 18446744073709551615 | 4
---
- metadata:
  - name: COLUMN_1
    type: integer
  rows:
  - [-1]
...
```

which isn't look right.

**Comment by pgulutzan** [comment]
I usually oppose increased use of UNSIGNED, for example in my July
conversation with T. Safin I gave what I thought were reasons
https://lists.tarantool.org/pipermail/tarantool-discussions/2020-July/000094.html
and in this case I think there is an additional reason in the manual:
"... the result [of a typical non-comparison operation] has the same data
type as the original operands, except that: promotion to a broader type
may occur to avoid overflow."
INTEGER is a "broader" type than UNSIGNED, so, when both operands are
INTEGERS, the result should be INTEGER or (as in the case of
SELECT 18446744073709551615 + 1, overflow.
(By the way I complained about the error message "integer is overflowed"
when discussing issue#3810 but it was not fixed.)
Of course, we all wish that the result of SELECT 18446744073709551615 | 4
would be 18446744073709551615, but that is in the INTEGER range, so
why not treat the result as a bug?

**Comment by ImeevMA** [comment]
So, do you suggest second rule? This means that the result of a bitwise operation is int64 if at least one of operands is negative. However, I think it is not very easy to determine the type of the result. I mean:
```
18446744073709551615 | -1 == -1
18446744073709551615 | -1 & 1 == 18446744073709551615
```
In the second case we have -1 but still we get 18446744073709551615.

In general both -1 and 18446744073709551615 are of INTEGER type and have the same representation (0xFFFFFFFF). So we should define rules to determine how should we treat this number, as -1 or as 18446744073709551615.

**Comment by pgulutzan** [comment]
I was saying the SQL result of INTEGER | INTEGER should be INTEGER.
You are asking whether I mean that the underlying type should be int64.
Well, no, but perhaps I am asking for something that is impossible.
My assumption is that the representation is cdata and that LuaJIT can be used.
If it gives odd results, then that is okay according to our manual
https://www.tarantool.io/en/doc/latest/reference/reference_lua/other/#lua-function.tonumber64

**Comment by Gerold103** [comment]
Another example, obviously broken.
```
	tarantool> box.execute('SELECT 9223372036854775808 >> 3')
	---
	- metadata:
	  - name: COLUMN_1
	    type: integer
	  rows:
	  - [-1152921504606846976]
	...
```

**Comment by Gerold103** [comment]
Another issue - I can't use the bitwise operations to get a big unsigned value (> INT64_MAX). Example:
```
tarantool> box.execute('select CAST(~1 AS UNSIGNED);')
---
- null
- 'Type mismatch: can not convert -2 to unsigned'
...
```
I wanted to get the same result as would happen in C when I do `~(uint64_t)1`. The result exists, and it is not negative.
