### ISSUE TITLE
Switch to position independent executable compilation

### ISSUE THREAD

**Issue by sharonovd** [tarantool/tarantool#5372]
This is stated as a `must` for #5261 by MRG security team

**Comment by Totktonada** [comment]
Hardened profile is disabled on CentOS 6/7 in the RPM spec in order to provide ability to show a backtrace in `fiber.info()` and at crash. See #1262. However we disable backtraces on CentOS 8 and enable the hardened profile there (it assumes -fPIE AFAIR). See #4611.
