### ISSUE TITLE
Raft: box.ctl.clear_synchro_queue should commit everything. At least when used by Raft

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#5435]
The method is supposed to be called by Raft on a new leader to finish transactions of the old leader. It tries to collect quorum from the other instances, commits all transactions having the quorum, and rolls back the others. But with such behaviour it may rollback transactions having the quorum, making it behave not better than asynchronous replication.

For example, assume there are 5 replicas, election is enabled, quorum is 3. Replica 1 was a leader. It created a transaction, which got the quorum on replicas 1, 2, 3. It writes commit, responds to the client. Then replica 1 dies. Replicas 4 and 5 can't become a new leader, because their vclock < of replica 2 and 3, and they can't get election quorum 3. So assume replica 2 is elected a new leader. Also assume that synchro timeout is small. So small, that when replica 2 becomes a new leader, it tries to clear the synchro queue, but does not manage to collect quorum on the pending transaction, and it rolls it back. This rollback will be replicated to the other replicas (3, 4, 5), and the transaction is gone from everywhere. But it was already responded to the client as success, and the cluster didn't loose a majority of replicas, so it was supposed to keep the transaction at all costs.

The key idea is that if a node was elected a leader, it means it **already** got the quorum, by the definition of the election. It should just immediately proceed to commit of the pending transactions. Not trying to get a quorum again.

**Comment by sergepetrenko** [comment]
The fact that a node is elected a leader means that it has data newer than that of a quorum of instances.
It doesn't mean that all its pending data is present on a quorum of instances. So there are cases when a fresh leader has to rollback pending transactions.
Speaking of your case, maybe we should wait a bit in `box_clear_synchro_queue` after becoming a leader?
We don't wait at all at the moment.

**Comment by sergos** [comment]
Hi!


> On 19 Oct 2020, at 14:27, Serge Petrenko <notifications@github.com> wrote:
> 
> The fact that a node is elected a leader means that it has data newer than that of a quorum of instances.

Also it means the majority of the cluster voted for the leader, i.e. quorum is present.

> It doesn't mean that all its pending data is present on a quorum of instances. So there are cases when a fresh leader has to rollback pending transactions.

It depends on behavior of the replicas: by now AFAIK a replica will disconnect if it can’t apply a transaction? Then there’s no reason to rollback, since no replicas will appear in an inconsistent state in the cluster. Counting the fallen leader we hold the promise: transaction is present on the quorum nodes.

> Speaking of your case, maybe we should wait a bit in box_clear_synchro_queue after becoming a leader?
> We don't wait at all at the moment.

How does it resolves the issue of the case? Transactions from the former leader will be ignored since the new one is defined.

Regards,
Sergos

**Comment by Gerold103** [comment]
> Speaking of your case, maybe we should wait a bit in box_clear_synchro_queue after becoming a leader?

It does not solve the concrete example I gave in the description. Here the transaction had a quorum, was committed, was responded to a client with success, the majority of replicas wasn't lost, and the transaction still was rolled back. Even though all the conditions for not being rolled back were satisfied. Timeouts won't help here, just make the problem harder to reach, probably.

**Comment by Gerold103** [comment]
It seems to me the new leader should wait for the replication of the not committed rows infinitely to collect the quorum. Because any rollback becomes dangerous. It is totally fine to commit something what was rolled back on the leader - we can't protect from it physically. But rollback after commit is unacceptable for sure.

**Comment by sergepetrenko** [comment]
> It seems to me the new leader should wait for the replication of the not committed rows infinitely to collect the quorum. 

Sounds like so.

**Comment by Gerold103** [comment]
Also the new leader should emit 'rollback' for the LSN right after the committed one. Even if on the leader itself there are no transactions to rollback. It is needed to force rollback on followers, who may have newer not committed data, but couldn't win the election somewhy.
Both confirm and rollback should be written always. Confirm - after waiting for quorum, rollback - right after confirm.

**Comment by Gerold103** [comment]
I realized now it should happen not only for Raft. box.ctl.clear_synchro_queue() should do that as well. Because it is going to be used by external election tools, which are likely to be just another Raft implementation. And they also need the new leader to properly collect the quorum.
