### ISSUE TITLE
Raft: send Raft state depending on Tarantool version, not on mode

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#5438]
Currently Raft state is sent to a subscriber when it is connected and the election is enabled. This leads to a bug (or maybe just inconvenience), that if the node was a leader, was turned off, and couldn't deliver the 'off' message to all the followers, some of them would still think the node is a leader until their restart or a new leader election.

If the followers are just voters or also have Raft disabled, they treat the old node as a leader infinitely until a new one is elected somewhere.

The state isn't sent not to break connections with the old versions, which won't understand the Raft messages.

That should be fixed so the state is sent always when possible. When the subscriber has version >= 2.6.0.

**Comment by sergepetrenko** [comment]
There's another problem with current approach:
It's possible that a running instance will never get is_leader notification from an instance it has just voted for.
Imagine you have a candidate, which lacks one vote to become a leader. Then you start a voter, and connect it to the candidate. `box_process_subscribe` involves sending complete raft state, which includes a vote request.
This vote request reaches the follower, and the follower votes for the candidate immediately.
If this vote reaches the candidate earlier than the candidate manages to start the relay thread and set relay->is_raft_enabled, the candidate will not send its state to the voter, leading to voter believing there's no leader until it's restarted.
