### ISSUE TITLE
Raft: turn on sync replication on `_space`, `_schema` system spaces

### ISSUE THREAD

**Issue by cyrillos** [tarantool/tarantool#5448]
Actually I need more comments from @Gerold103 and @Mons about this feature. Where and why should we turn on synchro on these spaces.

**Comment by Gerold103** [comment]
I don't remember us discussing `_space` being synchronous. Why should it be? Raft is not going to use it for anything.

`_cluster` should be synchronous when Raft is enabled. When Raft is disabled, the space is async like it is now.

When Raft mode is set to something except `off`, and a leader is elected, it should make the `_cluster` space synchronous. So to add a new instance or delete one it would be necessary to collect a quorum on that.

**Comment by NeraverinTarantool** [comment]
Maybe we should only write doc, describing that user should enable syc replication for system spaces himself

**Comment by kostja** [comment]
It still makes sense within a single replicaset to provide DDL/DML linearizability.

**Comment by sergepetrenko** [comment]
Duplicate of https://github.com/tarantool/tarantool/issues/9723
