### ISSUE TITLE
Fix luacheck warnings in test/app

### ISSUE THREAD

**Issue by ligurio** [tarantool/tarantool#5454]

**Comment by Totktonada** [comment]
Should we verify code for tarantool console with luacheck? I guess we can do it, but with relaxed restrictions about using `local` and maybe other tricks.

**Comment by ligurio** [comment]
[Tarantool-patches] [PATCH v7 0/3] Fix luacheck warnings in test/app-tap and test/app
https://lists.tarantool.org/pipermail/tarantool-patches/2020-December/021385.html
