### ISSUE TITLE
module: cluster topology provider (MVP)

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#5496]
Implement a service to store a cluster topology. Details TBD.

Proposal - https://github.com/tarantool/tarantool/discussions/5793
Depends on #5681

### Proposed  API (early draft):

`add_instance()`

Description: add a new instance with specified properties to a cluster.

Supported fields:

- uri: (string)
- replicaset uuid: (optional string)
- zone: (optional string)

`set_instance_property()`

Instance modifications.

Supported fields:

- uri: (optional string) Assign URI.
- uuid: (string) Assign replicaset uuid, that instance belongs to.
- zone: (optional string) Assign availability zone, that instance belongs to.

`set_instance_state()`

Update instance state.

Supported fields:

- enabled: (optional boolean) Switch instance to enabled state.
- disabled: (optional boolean) Switch instance to disabled state.
- expelled: (optional boolean) Expelling an instance is permanent and can’t be undone.It’s suitable for situations when the hardware is destroyed,snapshots are lost and there is no hope to bring it back to life. 

`set_replicaset_property()`

Replicaset modifications.

Supported fields:

- uuid: (string) The replicaset UUID.
- roles: ({string,…}) Roles enabled on the replicaset.
- status: (string) Replicaset health.
- master: (ServerInfo) Replicaset leader according to configuration.
- active_master: (ServerInfo) Active leader.
- weight: (number) Vshard replicaset weight.Matters only if vshard-storage role is enabled.
- vshard_group: (string) Name of vshard group the replicaset belongs to.
- all_rw: (boolean) A flag indicating that all servers in the replicaset should be read-write.
- alias: (string) Human-readable replicaset name.

`get_topology()`

Returns a structure with predefined format that contains all objects in topology with every assigned parameters values.

### Topology API used in Cartridge:

1.  Source code: https://github.com/tarantool/cartridge/blob/master/cartridge/topology.lua
2. Get topology  https://www.tarantool.io/en/doc/latest/book/cartridge/cartridge_api/modules/cartridge.lua-api.get-topology/
3. Edit topology https://www.tarantool.io/en/doc/latest/book/cartridge/cartridge_api/modules/cartridge.lua-api.edit-topology/
4. API topology https://www.tarantool.io/en/doc/latest/book/cartridge/cartridge_api/modules/cartridge.lua-api.topology/
5. Topology https://www.tarantool.io/en/doc/latest/book/cartridge/cartridge_api/modules/cartridge.topology/
6. [[Tarantool-patches] [RFC] qsync: provide box.info interface for monitoring](https://lists.tarantool.org/tarantool-patches/20210212080324.274627-1-gorcunov@gmail.com/T/#u)

**Comment by ligurio** [comment]
MVP - https://github.com/ligurio/topology
API documentation - https://ligurio.github.io/topology/

**Comment by ligurio** [comment]
Repository with source code has been moved to Tarantool organization -
https://github.com/tarantool/topology as well as documentation - https://tarantool.github.io/topology/

Right now it is implemented minimal topology version that allows to create a topology in configuration storage using configuration provider and bootstrap vshard with that topology. More features will follow later.
