### ISSUE TITLE
vinyl: errors on instance shutdown after executing a lot of incorrect upserts

### ISSUE THREAD

**Issue by Korablev77** [tarantool/tarantool#5498]
```
box.cfg{}
s = box.schema.create_space('test', {engine = 'vinyl'})
pk = s:create_index('pk')

ups_cnt = 5000

box.begin()
for k = 2, ups_cnt do s:upsert({1}, {{'+', k, 1}}) end
box.commit()
box.snapshot()
os.exit()
2020-11-03 20:00:02.491 [18214] main xrow_update_field.c:89 E> ER_NO_SUCH_FIELD_NO: Field 5000 was not found in the tuple
2020-11-03 20:00:02.491 [18214] main F> fatal error, exiting the event loop
```
Fatal error doesn't seem to be proper behavior after `os.exit()`. I haven't dived into this problem, so in case there's nothing critical just close this issue

**Comment by CuriousGeorgiy** [comment]
The described bug does not show up neither in interactive mode, nor when running the provided code snippet as an initialization script.

**Comment by CuriousGeorgiy** [comment]
Consulted @Korablev77: closing the issue, as it was apparently fixed by prior patches.
