### ISSUE TITLE
tarantoolctl: need to implement ability to stop instances with signal from options

### ISSUE THREAD

**Issue by avtikhon** [tarantool/tarantool#5510]
Tarantool version:

OS version:

Bug description:
Found that some of the instances could not be killed with SIGTERM signal and it really needed SIGKILL signal to be sure that the instance would be terminated. Otherwise some tests may fail, like:
```
  No output during 120 seconds. Will abort after 120 seconds without output. List of workers not reporting the status:
  - 001_engine [engine/json.test.lua, memtx] at var/001_engine/json.result:598
  Test hung! Result content mismatch:
  --- engine/json.result	Fri Nov  6 08:35:45 2020
  +++ var/001_engine/json.result	Mon Nov  9 03:48:40 2020
  @@ -596,248 +596,3 @@
   - ok
   ...
   test_run:cmd("restart server default")
  -engine = test_run:get_cfg('engine')
  ----
  -…
```
Test run uses 'tarantoolctl' tool for commands in format "restart server default", and 'tarantoolctl' had only single way to kill it using SIGTERM signal. To implement ability to use it with SIGKILL was added additional non-mandatory option to stop and restart 'tarantoolctl' commands, like:

  tarantoolctl stop <instance> [--signal=SIGKILL]
  tarantoolctl restart <instance> [--signal=SIGKILL]

This options didn't change the backward compatibility of 'tarantoolctl' tool, but gave the tests ability to stop and restart instances in the following way:

  test_run:cmd("stop server default with signal=KILL")
  test_run:cmd("restart server default with signal=KILL")

It helped to fix the issue with hanging instances in the needed tests.
Steps to reproduce:

Optional (but very desirable):
* coredump
* backtrace
* netstat

**Comment by Totktonada** [comment]
It was for https://github.com/tarantool/test-run/pull/235, which was closed and superseded by another PR. Co I guess I can close this issue.
