### ISSUE TITLE
Add uuid:compare() method

### ISSUE THREAD

**Issue by akudiyar** [tarantool/tarantool#5511]
Tarantool version: 2.4+

There is no built-in way of comparing UUIDs. One can use `uuid:str()` and go with string representations, but it is not a better choice semantically and performance-wise. Btw, there is an internal `tt_uuid_compare` method which may be exposed for this purpose.

Real case: using UUIDs as key parts in indexes requires UUID comparison when performing operations on spaces using tarantool/crud.

**Comment by Totktonada** [comment]
I would consider the [tuple-keydef](https://github.com/tarantool/tuple-keydef) module as the solution, because it supports all field types, which are supported by tarantool indices.

**Comment by Gerold103** [comment]
We can just redefine comparison operators and use <, <=, >, >=, ==, ~=. It is possible. I did it for `struct swim_incarnation`, see swim.lua.
