### ISSUE TITLE
Bank test in multi-table configuration failed on a synchronous cluster

### ISSUE THREAD

**Issue by ligurio** [tarantool/tarantool#5513]
### Tarantool version:

2.7.0-1-g1ad696c09

### OS version:

Ubuntu 18.04 x86_64

### Bug description:

Test simulates a set of bank accounts, one per table, and transfers money
between them at random, ensuring that no account goes negative. Under snapshot
isolation, one can prove that transfers must serialize, and the sum of all 
accounts is conserved. Meanwhile, read transactions select the current balance
of all accounts. Snapshot isolation ensures those reads see a consistent
snapshot, which implies the sum of accounts in any read is constant as well.

The bank test stresses several invariants provided by snapshot isolation. We
construct a set of bank accounts, each with three attributes:

- **type**, which is always “account”. We use this to query for all accounts.
- **key**, an integer which identifies that account.
- **amount**, the amount of money in that account.

Our test begins with a fixed amount (₽100) of money in a single account, and 
proceeds to randomly transfer money between accounts. Transfers proceed by
reading two random accounts by key, and writing back new amounts for those
accounts to reflect some money moving between them. Concurrently, clients read
all accounts to observe the total state of the system.

Total amount of money in test (when test passed plot should draw a single line with Y == 100):
![bank](https://user-images.githubusercontent.com/1151557/98941108-228e2980-24fd-11eb-83fe-33aca609f5a0.png)

### Steps to reproduce:

(setup is not trivial so ask me for assistance)

- Setup a cluster of Linux boxes available via ssh
- Write IP addresses to a plain text file, for example `nodes`
- Install Leiningen, Clojure and Java on a control machine where Jepsen test will started
- Run test with command-line below on control machine:
```
$ lein run test --nodes-file nodes --username ubuntu --version 2.6 --workload bank-multitable-lua
```

NOTE: results are the same with and without enable MVCC (aka TXM), files for both variants attached.

NOTE: The same test successfully passed when test simulates a set of bank accounts, *one per row in a single table* and on a single instance when set of bank accounts is a number of tables.

Source code of test: https://github.com/tarantool/jepsen.tarantool/blob/master/src/tarantool/bank.clj#L74

Lua function to read balance (executed as SQL function):
https://github.com/tarantool/jepsen.tarantool/blob/master/resources/tarantool/jepsen.lua#L131-L155

Operations executed by client:
https://github.com/tarantool/jepsen.tarantool/blob/master/src/tarantool/bank.clj#L100-L128

[bank-test.zip](https://github.com/tarantool/tarantool/files/5530631/bank-test.zip)

**Comment by Totktonada** [comment]
AFAIU from the [code](https://github.com/tarantool/jepsen.tarantool/blob/5fa0fe3599e6d1b119f2d6853a9e70cd1b275847/src/tarantool/bank.clj#L104-L109) the test fetches balances from different tables in separate requests and so in different transactions. Either define a function that fetches all balances in a transaction or wait for interactive transactions support in the protocol (#2016) and use them.

**Comment by Totktonada** [comment]
So I'll take it back to our team with considerable priority.

**Comment by ligurio** [comment]
Discussed with Alexander @Totktonada in private conversation. 
He suspects that the root cause of test fail in non-atomic balance reade,
see https://github.com/tarantool/jepsen.tarantool/blob/master/src/tarantool/bank.clj#L103-L113
and I'm agree, that's a valid remark. We can easily check it if someone implements Lua function that implement sum balances atomically and run it as SQL function.

**Comment by ligurio** [comment]
Fixed:

![image](https://user-images.githubusercontent.com/1151557/119474488-e150bf00-bd54-11eb-9d9c-54a609dd0634.png)
