### ISSUE TITLE
Introduce descending indexes

### ISSUE THREAD

**Issue by Korablev77** [tarantool/tarantool#5529]
It is possible to set sort order in index definition:
`i = s:create_index('test', {type='tree', parts={{1, 'uint', sort_order='desc'}}})`.
However, it affects nothing:
```
s = box.schema.create_space('t')
i = s:create_index('test', {type='tree', parts={{1, 'uint', sort_order='desc'}}})
s:insert({1})
s:insert({3})
s:insert({2})
i:select()
---
- - [1]
  - [2]
  - [3]
```
As one can see, results are still appear in ascending order. So the proposal is to make `sort_order` work as it is supposed to do.

Needed for #2596

**Comment by R-omk** [comment]
related  https://github.com/tarantool/tarantool/issues/3243  https://github.com/tarantool/tarantool/commit/55dec954fc09299f8547f1f93ef573bab18ef132

consider specifying a range (between) and direction for each part of the index key
