### ISSUE TITLE
OOM on a joining/syncing replica

### ISSUE THREAD

**Issue by sergepetrenko** [tarantool/tarantool#5536]
### Tarantool version:
2.4.1+ (probably 2.2.1+, since parallel applier introduction)

### Bug description:
Replica fetches snapshot successfully, then its log is spammed with 
```
too long WAL write: X rows at LSN N: 187.076 sec
```
There may be literally millions of such messages: `25004156 messages suppressed`
And lag may be as high as 480 seconds in some cases.

After some time the connection with master is broken. Master's log shows `relay/<ipaddr>/101/main coio.cc:340 !> SystemError timed out: Connection timed out`.

Replica restarts the connection and the story starts all over again.

During this process replicas memory consumption continues to grow.

After some more retries one of the following happens:
* replica receives `ER_INVALID_MSGPACK` error (hooray, #4040 finally has a reproducer)
   Replication is stopped after this message. This lets replica process all the piled up
   messages in its WAL, its cpu usage drops to zero, but the consumed RAM doesn't decrease.
* replica is killed by OOM

#### The hard way
Give the master enough load so that while the replica is fetching its snapshot, it manages to write roughly the same amount of data to its `.xlog` files.

Now the replica will fetch the snapshot successfully (during this phase no WAL writes are involved, the replica just applies whatever the master sends it, so it doesn't fall back).
When the master finishes sending its snapshot, it already has a pile of transactions in its `.xlog` files, and it immediately starts sending them to the replica. Unlike the first stage, now replica tries to write the transactions to WAL. There is no limit for the speed relay or applier send/receive transactions at, so replica receives the transactions at RPS much higher than master does (the master is simply reading the transactions from the already written WAL, and does it much faster, than could write the transactions to WAL itself).

Replica's WAL is never in time to write all the incoming transactions, so replica has more and more open transactions and cbus messages between tx and WAL, which leads to increasing memory consumption and, eventually, OOM.

#### The easy way
1. Build a debug version of tarantool.
2. Start replica & master.
3. Create some load on master (not necessarily high-RPS).
4. Issue `box.error.injection.set("ERRINJ_WAL_DELAY", true)` on replica
5. Wait some time, issue `box.error.injection.set("ERRINJ_WAL_DELAY", false)` and repeat steps 4-5

I tried it with the following load on master:
```lua
i = 0
whie true
    box.space.test:insert{i}
    if i % 100000 == 0 then
         print("Processed "..i)
    end
    i = i + 1
end
```

And after master has performed roughly 15 000 000 insertions its memory usage was ~500 Mb while replica used up 50+ Gb of RAM. All the symptoms described above were present.

### How to fix
Looks like this issue may be fixed by introducing some kind of a limit for WAL messages in flight, together with some kind of readahead for applier. Similar to how iproto works.

**Comment by sergepetrenko** [comment]
Here's an implementation plan for a bugfix with some background on why we decided to implement it like this.
Agreed on with @Mons and @Gerold103.

What we need to do is to limit the pace at which appliers read and generate new transactions so that when WAL isn't on time to write everything, this doesn't create a huge queue of pending write requests which would eventually lead to an OOM.

We do not want to give up using async txn commit in applier, since it gives us a lot of additional speed and reduces CPU usage on replicas. So waiting for WAL write for each transaction, like it was before parallel applier, isn't an option.

One idea was to put a limit on applier's outgoing transactions, so that it would block once it sees that a lot of stuff is already waiting for a WAL write. This would fix the issue, but there's a better option: the limit should reside in WAL itself. This will also help once async commit is exposed to users (#67).

So what is going to be implemented are 2 new configuration options. The option names are illustratory, we'll come up with better names later.
1. `wal_max_queue_size` - this limits the byte count of what is yet to be written to WAL.
2. `wal_max_queue_len` - this limits the total count of system messages between tx and WAL.

The limits are checked on each wal write request made in tx.
Once the limits are exhausted the following happens:
1. For a "normal" ("synchronous") commit, the fiber executing transaction yields until there is some space available to submit a new write request. There are no changes visible to user. The fiber owning the transaction would block on waiting for a WAL write confirmation anyway. 
2. For an "asynchronous" commit a new option is introduced: `bool block_on_queue`. For now appliers are the only users of asynchronous commit, and they use it with `block_on_queue = true`. This is how it works: while the queue isn't full, everything works like before, appliers simply submit new write requests one by one and never wait for a WAL write. However, once the queue gets filled, a new write request from an applier is blocked until the queue gets some free space for it. This helps to limit applier pace. Exactly what we need. And this also doesn't require any changes in applier itself.
The option `block_on_queue` is intended for #67 implementation. `box.commit{is_async=true}` probably won't be allowed to yield at all, so it will use an async commit with `block_on_queue = false`. In this case once the WAL queue is full, async commit will error, but won't roll the transaction back, allowing the user to either call a synchronous commit or wait until the queue is emptied or do whatever they want.

The queue usage numbers are increased on each new submitted write request and are reduced once a confirmation for a particular WAL write arrives.

**Comment by kostja** [comment]
Another artifact of the bug is that the applier disconnects because WAL batches become too big and the txn thread doesn't acknowledge transactions from master so the master relay disconnect the replica on disconnect. So it's not enough to track memory consumption, it's important to not overwork the WAL thread with too much data to write.

**Comment by sergepetrenko** [comment]
> Another artifact of the bug is that the applier disconnects because WAL batches become too big and the txn thread doesn't acknowledge transactions from master so the master relay disconnect the replica on disconnect. So it's not enough to track memory consumption, it's important to not overwork the WAL thread with too much data to write.

I believe you've hit #5762. I also thought the applier stops sending ACKs when tried to reproduce that. Actually the problem was with relay not reading the acks.

Even if the problem lies in WAL having too big batches, it'll be fixed by this patch. The queue gets emptied only once WAL notifies TX it's written a batch. This happens once per event loop iteration, if I'm correct, so with some tuning you'll get `wal_queue_max_size` or `wal_queue_max_len` small enough to prevent creation of too big WAL batches.
