### ISSUE TITLE
build: build fails on Mac OS 11.0 in Homebrew

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#5543]
Tarantool version: 2.5.2-0-g05730d3.
OS version: Mac OS 11.0.

> -- Performing Test CURL_SUPPORTS_SSL
> -- Performing Test CURL_SUPPORTS_SSL - Failed
> CMake Error at cmake/FindCURL.cmake:130 (message):
>   Curl was built without SSL support

Found by Homebrew CI: https://github.com/Homebrew/homebrew-core/issues/65000 (unroll the big list in the comment).

Filed the issue just to don't forget about this. Let's close it if the problem will be resolved on the homebrew infrastructure side.

**Comment by Totktonada** [comment]
The failure comes from the following check:

https://github.com/tarantool/tarantool/blob/18e2420981d0c141f62ce16020a313300fa56450/cmake/FindCURL.cmake#L108-L134

In fact, any `check_c_source_runs()` fail leads to the 'Curl was built without SSL support' failure. The fail looks so in `CMakeError.txt` or when `--trace-expand` option is passed to cmake:

```
Run Build Command(s):/usr/bin/make cmTC_6cf00/fast && /Applications/Xcode_12.2.app/Contents/Developer/usr/bin/make  -f CMakeFiles/cmTC_6cf00.dir/build.make CMakeFiles/cmTC_6cf00.dir/build
Building C object CMakeFiles/cmTC_6cf00.dir/src.c.o
/Applications/Xcode_12.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -DCURL_SUPPORTS_SSL -D_GNU_SOURCE  -Wno-unknown-pragmas -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -msse2  -isysroot /Applications/Xcode_12.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk -o CMakeFiles/cmTC_6cf00.dir/src.c.o -c /Users/runner/work/tarantool/tarantool/CMakeFiles/CMakeTmp/src.c
make[2]: *** No rule to make target `/usr/lib/libcurl.dylib', needed by `cmTC_6cf00'.  Stop.
make[1]: *** [cmTC_6cf00/fast] Error 2
```

So the `/usr/lib/libcurl.dylib` file just does not exist. The path is [passed](https://github.com/avtikhon/homebrew-core/blob/68a75cf4187e925181b7d9a5fff2d0a1cb3addce/Formula/tarantool.rb#L44) from the brew formula using the `-DCURL_LIBRARY=/usr/lib/libcurl.dylib` cmake option.

----

My guess about the reason of the failure.

Mac OS 11.0 (Big Sur) [introduces](https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11_0_1-release-notes) the following... hm... feature:

> New in macOS Big Sur 11.0.1, the system ships with a built-in dynamic linker cache of all system-provided libraries. As part of this change, copies of dynamic libraries are no longer present on the filesystem. Code that attempts to check for dynamic library presence by looking for a file at a path or enumerating a directory will fail. Instead, check for library presence by attempting to dlopen() the path, which will correctly check for the library in the cache. (62986286)

So, the `/usr/lib/libcurl.dylib` file does not present on the file system, but it seems `check_c_source_runs()` expects that it exists.

----

Proposal.

We can expect that SDK or CLI Developer tools is present on a build system and link against SDK's libcurl. Even if an SDK will not present at the target system, the linker cache will allow a dynamic loader to see the libraries as if they would be in `/usr/lib` (I hope).

Let's try the following patch for the formula:

```diff
diff --git a/Formula/tarantool.rb b/Formula/tarantool.rb
index c2d2b4a010..f6316a653f 100644
--- a/Formula/tarantool.rb
+++ b/Formula/tarantool.rb
@@ -41,10 +41,10 @@ class Tarantool < Formula
     args << "-DREADLINE_ROOT=#{Formula["readline"].opt_prefix}"
     args << "-DENABLE_BUNDLED_LIBCURL=OFF"
     args << "-DCURL_INCLUDE_DIR=#{sdk}/usr/include"
-    args << "-DCURL_LIBRARY=/usr/lib/libcurl.dylib"
+    args << "-DCURL_LIBRARY=#{sdk}/usr/lib/libcurl.tbd"
     args << "-DCURSES_NEED_NCURSES=TRUE"
     args << "-DCURSES_NCURSES_INCLUDE_PATH=#{sdk}/usr/include"
-    args << "-DCURSES_NCURSES_LIBRARY=/usr/lib/libncurses.dylib"
+    args << "-DCURSES_NCURSES_LIBRARY=#{sdk}/usr/lib/libncurses.tbd"
     args << "-DICONV_INCLUDE_DIR=#{sdk}/usr/include"
 
     system "cmake", ".", *args
```

If it'll not work for older Mac OS versions, let's try to do it conditionally.

----

@avtikhon experimenting in https://github.com/Homebrew/homebrew-core/pull/67944

**Comment by carlocab** [comment]
Are you using the latest `FindCURL` module? I'm pretty sure CMake has already figured out how to find libraries on Big Sur even though they're no longer present on the file system.

**Comment by carlocab** [comment]
As for testing, you can use a GitHub runner. Follow the instructions here: https://brew.sh/2020/11/18/homebrew-tap-with-bottles-uploaded-to-github-releases/

**Comment by tsafin** [comment]
> As for testing, you can use a GitHub runner. Follow the instructions here: https://brew.sh/2020/11/18/homebrew-tap-with-bottles-uploaded-to-github-releases/

Thanks for the link - I've missed the moment when this nice workflow helpers for building bottles of tap have been created. Will try to add it to tarantool/homebrew-tap formulas, as bottles are missing there at the moment.

**Comment by carlocab** [comment]
No problem. If you still can't figure out how to get CMake to find `curl` and `ncurses` on Big Sur, you might wish to try depending on Homebrew `curl` and `ncurses`, as those will be easier for CMake to find.

**Comment by tsafin** [comment]
> 
> 
> No problem. If you still can't figure out how to get CMake to find `curl` and `ncurses` on Big Sur, you might wish to try depending on Homebrew `curl` and `ncurses`, as those will be easier for CMake to find.

That's exactly what have been done in tap recipes I mentioned above, but in a longer term guys want to get resolved dependency on system version of libcurl

**Comment by carlocab** [comment]
Yes, that would be helpful. As mentioned, my understanding is that CMake has already fixed this in their latest release, but I haven't really looked into the details of how.

**Comment by Totktonada** [comment]
> Are you using the latest `FindCURL` module? I'm pretty sure CMake has already figured out how to find libraries on Big Sur even though they're no longer present on the file system.

AFAIU, the problem is not in the `FindCURL` module itself, but that we pass a path to a non-exist file via CMake options.

To be honest, I don't like this paths hardcoding, but I didn't look how to better solve it.

**Comment by Totktonada** [comment]
Worked around in https://github.com/Homebrew/homebrew-core/pull/67944.

Maybe we should reconsider the default logic for finding libcurl (now we prefer homebrew's libcurl when `-DENABLE_BUNDLED_LIBCURL=OFF` is passed):

https://github.com/tarantool/tarantool/blob/efc30ccf8393a1aad19d4c17299842899d003caa/cmake/os.cmake#L148-L160

Or provide a cmake option to control this behaviour in a more obvious way:

1. Use bundled libcurl.
2. Link only with system libcurl.
3. Link only with homebrew's libcurl.
4. Prefer system libcurl, fallback to homebrew's one.
5. Prefer homebrew's libcurl, fallback to system's one.

E.g. `-DLIBCURL=BUNDLED|SYSTEM|HOMEBREW|PREFER_SYSTEM|PREFER_HOMEBREW`.

Anyway, the problem that is described in this issue is resolved on Homebrew's formula side, so I'll close the issue.
