### ISSUE TITLE
bitset: writing 1 byte into a region of size 0 (gcc 10)

### ISSUE THREAD

**Issue by artemreyt** [tarantool/tarantool#5564]
Tarantool version:
all

Compiler: `gcc` >= 10

Bug description:
In gcc 10 was added a new flag `-Wstringop-overflow`, which enables when `-O2` in switched on.
Build with CMAKE_BUILD_TYPE != Debug there is a warning displayed:
```
In file included from ***/src/lib/bitset/bitset.h:45,
                 from ***/src/lib/bitset/bitset.c:32:
***/src/lib/bitset/bitset.c: In function ‘tt_bitset_set’:
***/src/lib/bit/bit.h:230:15: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
  230 |  ldata[chunk] |= (1UL << offset);
      |  ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
```

When `-O2` is enabled, then -DNDEBUG is added to compilation, and if to undef this macro there's note for this warning:
```
In file included from ***/src/lib/bitset/bitset.c:32:
***/src/lib/bitset/bitset.h:72:10: note: at offset 0 to object ‘data’ with size 0 declared here
   72 |  uint8_t data[0];
      |          ^~~~
```

**Comment by alyapunov** [comment]
Is there similar problem with struct tuple_chunk?

**Comment by artemreyt** [comment]
Fixed by replacing non-standard zero-length array with ISO C99 flexible-array member in `struct tt_bitset_page` ([here](6011a5182431783749d8f15604710d7d8111b602))

**Comment by Xeverous** [comment]
I know it's late but FYI I got the same weird warning on my own project which uses high-level C++ (no memcpy / byte stuff), it points to random types and totally sane operations like ctor member init list (which can not cause undefined behavior).

[Searching GCC bugzilla](https://gcc.gnu.org/bugzilla/buglist.cgi?bug_status=UNCONFIRMED&bug_status=NEW&bug_status=ASSIGNED&bug_status=SUSPENDED&bug_status=WAITING&bug_status=REOPENED&cf_known_to_fail_type=allwords&cf_known_to_work_type=allwords&f0=OP&f1=OP&f10=OP&f11=OP&f12=product&f13=component&f14=alias&f15=short_desc&f17=content&f18=CP&f19=CP&f2=product&f20=OP&f21=OP&f22=alias&f23=short_desc&f25=content&f26=CP&f27=CP&f28=OP&f29=OP&f3=component&f30=product&f31=component&f32=alias&f33=short_desc&f35=content&f36=CP&f37=CP&f38=OP&f39=OP&f4=alias&f40=alias&f41=short_desc&f43=content&f44=CP&f45=CP&f46=OP&f47=OP&f48=product&f49=component&f5=short_desc&f50=alias&f51=short_desc&f53=content&f54=CP&f55=CP&f56=OP&f57=OP&f58=alias&f59=short_desc&f61=content&f62=CP&f63=CP&f7=content&f8=CP&f9=CP&j1=OR&j11=OR&j21=OR&j29=OR&j39=OR&j47=OR&j57=OR&o12=substring&o13=substring&o14=substring&o15=substring&o16=substring&o17=matches&o2=substring&o22=substring&o23=substring&o24=substring&o25=matches&o3=substring&o30=substring&o31=substring&o32=substring&o33=substring&o34=substring&o35=matches&o4=substring&o40=substring&o41=substring&o42=substring&o43=matches&o48=substring&o49=substring&o5=substring&o50=substring&o51=substring&o52=substring&o53=matches&o58=substring&o59=substring&o6=substring&o60=substring&o61=matches&o7=matches&product=gcc&query_format=advanced&short_desc=byte%20into%20a%20region%20of%20size%200&short_desc_type=allwordssubstr&v12=into&v13=into&v14=into&v15=into&v16=into&v17="into"&v2=byte&v22=a&v23=a&v24=a&v25="a"&v3=byte&v30=region&v31=region&v32=region&v33=region&v34=region&v35="region"&v4=byte&v40=of&v41=of&v42=of&v43="of"&v48=size&v49=size&v5=byte&v50=size&v51=size&v52=size&v53="size"&v58=0&v59=0&v6=byte&v60=0&v61="0"&v7="byte") with this warning gives me 8 results, many on totally bug-free code. Fixes generally include tweaking optimization options.
