### ISSUE TITLE
Attempt to write on a read-only instance should report reason why it is read-only

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#5568]
We have several places in the code, affecting instance read-only state:
1. box.cfg{read_only};
2. box.cfg{replication_connect_quorum} makes instance orphan when the quorum is lost;
3. box.info.election.state - when election mode is configured not to off, any non-leader state makes the instance read-only.

But when a write fails, in the error message it only says ER_READONLY. Would be good to have a concrete reason, why it is read-only.

For raft it may be useful to report the real leader in the error object, if the leader is known. So as the client could go to the real leader. Probably automatically, if the client is a router.

**Comment by unera** [comment]
Stop!
