### ISSUE TITLE
test: flaky replication/quorum.test.lua test needs more time to run

### ISSUE THREAD

**Issue by avtikhon** [tarantool/tarantool#5571]
Tarantool version:
| Tarantool 2.7.0-74-g6ad720d6d6
| Target: Linux-x86_64-Debug
| Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_BACKTRACE=ON
| Compiler: /usr/bin/cc /usr/bin/c++
| C_FLAGS: -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -fprofile-arcs -ftest-coverage -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type -Werror
| CXX_FLAGS: -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -fprofile-arcs -ftest-coverage -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type -Werror

OS version:
Debian 9/CentOS 7 (debug and OOS builds)

Bug description:
Seems that test needs more time to run in debug and OOS builds.

https://gitlab.com/tarantool/tarantool/-/jobs/875750911#L5240

[artifacts.zip](https://github.com/tarantool/tarantool/files/5609702/artifacts.zip)

# results file checksum: d2d9b186850f654c77562ab99abe9067
# results file checksum: 00713be4733924a77afec3c62ceed9ca
```
[049] --- replication/quorum.result	Mon Nov 23 14:32:42 2020
[049] +++ var/rejects/replication/quorum.reject	Thu Nov 26 22:07:09 2020
[049] @@ -428,41 +428,3 @@
[049]  -- If replication_connect_quorum was ignored here, the instance
[049]  -- would exit with an error.
[049]  test_run:cmd('start server replica_quorum with wait=True, wait_load=True, args="1 0.05"')
[049] ----
[049] -- true
[049] -...
```

Steps to reproduce:

Optional (but very desirable):
* coredump
* backtrace
* netstat

**Comment by Totktonada** [comment]
It seems, it should be fixed by a14dad9543360c49c2cf8906a88e09271cad91b6. It was pushed to all alive release branches: 2.7.0-79-ga14dad954, 2.6.1-66-gd44f50efa, 2.5.2-38-ga3492bbe6, 1.10.8-28-g17c5c15cb.
