### ISSUE TITLE
Add more metrics to feedback daemon

### ISSUE THREAD

**Issue by alyapunov** [tarantool/tarantool#5589]
We should add `box.stat().*.rps` and `box.stat.net().*.rps` metrics to feedback daemon.
Also it would be better if we could differentiate requests that came from network from requests that was made in lua.
It would help us to understand what kind and scale of payload is the most wanted by our users.

**Comment by alyapunov** [comment]
Just as @Mons suggested I would refine the task.
1. When I write `box.stat().*.rps` I mean DELETE, SELECT, INSERT etc; that are all events that are printed with `box.stat()`. Just to be safe.
1. We need **rps** of all those events, but it must be calculated as an average over period since the last feedback transmission. For example: the last time (at time _T0_) when a feedback was sent `box.stat().SELECT.total` was _X_. Now (at time _T_), when we are sending feedback again, `box.stat().SELECT.total` is _Y_. We should send _(Y - X) / (T - T0)_ as select rps and store current time and `box.stat().SELECT.total` for the next rps calculation. We should use `box.stat().SELECT.rps` only for the first transmission (after restart of tarantool).
1. Some events (e.g. `box.net.stat().CONNECTIONS`) also has `current` metric. This metric also needs to be collected. It does not require special calculation, the daemon must send current `current` value. Despite only two events have that metric the task should be formulated as: Send all `box.stat().*.current` and `box.stat.net().*.current` numbers that are present in statistics.

**Comment by Mons** [comment]
2. Do not divide by time interval, just send raw `Y - X` delta plus interval.
Then, rps or rpd could be counted on server. Also total could be counted too.
3. Have a note about CONNECTIONS and REQUESTS: despite they both have .current, they also have total, wich means performed requests for REQUESTS and established connections for CONNECTIONS. They also must be sent as (`Y - X`)
