### ISSUE TITLE
Move jobs with building packages to the end of CI pipeline

### ISSUE THREAD

**Issue by ligurio** [tarantool/tarantool#5590]
We have a stage "Test" where is a bunch of jobs not related to testing at all. These jobs creates packages for different Linux distributives. Although it is a bit strange to build packages when testing is not done (next stages of pipeline contains Jepsen tests and optional performance tests) and waste hardware resources for it on **each** commit.

These jobs can be moved to a separate stage at the end of CI pipeline (see logs, no test run there):

- centos 6 https://gitlab.com/tarantool/tarantool/-/jobs/880574166
- debian 8 https://gitlab.com/tarantool/tarantool/-/jobs/880574187
- debian 9 https://gitlab.com/tarantool/tarantool/-/jobs/880574188
- debian 10 https://gitlab.com/tarantool/tarantool/-/jobs/880574189
- ubuntu 14.04 https://gitlab.com/tarantool/tarantool/-/jobs/880574181
- ubuntu 20.04 https://gitlab.com/tarantool/tarantool/-/jobs/880574186
- ubuntu 19.10 https://gitlab.com/tarantool/tarantool/-/jobs/880574185
- ubuntu 18.04 https://gitlab.com/tarantool/tarantool/-/jobs/880574184
- ubuntu 16.04 https://gitlab.com/tarantool/tarantool/-/jobs/880574182

**Comment by Totktonada** [comment]
We have quite specific testing goals, such as testing tarantool that is built with LTO or, say, testing on non-primary platforms. We want to track status of such specific goals, but we surely don't want to skip packages deployment if one of them fails.

I'm not against saving hardware resources if it does not lead to possible waste of human resources and don't affect reliability of the infrastructure. Your proposal is the topic for discussion.

There are also a [large number of flaky tests](https://github.com/tarantool/tarantool/issues?q=is%3Aissue+is%3Aopen+label%3A%22flaky+test%22) and stabilization of our testing is definitely prerequisite of implementing any logic based on the testing result.

Regarding the list. There are other jobs, which build packages: CentOS 7/8, all Fedoras. They have testing inside, but the result is a package (RPM or Deb). I hope, in future we'll run the testing on all Linux distributions, see #1341.

**Comment by ligurio** [comment]
> We have quite specific testing goals, such as testing tarantool that is built with LTO or, say, testing on non-primary platforms.
> We want to track status of such specific goals,
> but we surely don't want to skip packages deployment if one of them fails.

It's not a problem. For jobs that allowed to fail you can use option `allow_failure: true` (see [documentation](https://docs.gitlab.com/ee/ci/yaml/#allow_failure)).

> I'm not against saving hardware resources if it does not lead to possible waste of human resources and
> don't affect reliability of the infrastructure. Your proposal is the topic for discussion.

It's already a waste of human resources because everyone should wait package building tasks before sending patch to mail list otherwise it would be questionable why CI red for these patches. It's also a waste of hardware resources too, because we build packages for *every push to a feature branch* and I don't know serious reasons to do that.

> Regarding the list. There are other jobs, which build packages: CentOS 7/8, all Fedoras. They have testing inside, but the result is a package (RPM or Deb). I hope, in future we'll run the testing on all Linux distributions, see #1341.

Yes, I know. These jobs need to be splitted for testing and packaging firstly.

**Comment by ligurio** [comment]
Duplicate of https://github.com/tarantool/tarantool-qa/issues/142
