### ISSUE TITLE
Make all built-in modules visible by default in the interactive console

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#5596]
Tarantool version: 2.7.0-74-g71377c28e.

It would be convenient to use, say, `fiber.info()` without explicit `fiber = require('fiber')` in the interactive console. The same for all other built-in Lua modules.

I would not place them all into `_G`: it would direct users to omit explicit require calls in modules and applications that may look confusing for a reader. I guess we can run a code from the interactive console in a specific scope, which contains all those variables.

The idea was issued by @Mons, when we forgot a require call at writting a code snippet in the console.

**Comment by kyukhin** [comment]
Looks like a feature for the 3 series.

**Comment by Totktonada** [comment]
Solved in [3.2.0](https://github.com/tarantool/tarantool/releases/tag/3.2.0) in the scope of #9986.

One needs to set `compat.console_session_scope_vars` to `new` in order to use this functionality.
