### ISSUE TITLE
Set box.cfg values using environment variables

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#5602]
It is not always possible or handy to pass parameters inside tarantool instance. For such configurations it may be handy to define instance parameters via environment variables

Definition rules are the following:
* Generic chain for pure tarantool is: default - ENV - box.cfg
* Generic chain for tarantool under tarantoolctl is: default - .tarantoolctl - ENV - box.cfg

Explanation and clarification:
* parameter, explicitly passed inside box.cfg (not by tarantoolctl's wrapper) take precedence over environment and over default
* if no parameter passed into box.cfg, then take a look into appropriate ENV variable.
* for tarantool running under tarantoolctl environment takes precedence over defaults from .tarantoolctl, but not over ones, passed explicitly into box.cfg

As a common prefix for tarantool's environment we take `TT_`
As a suffix we take uppercased version of configuration parameter name

Example:

```bash
TT_LISTEN=3301 tarantool -e 'box.cfg()'
```

shoud act as

```bash
tarantool -e 'box.cfg{ listen=3301 }'
```

Environment variables should be interpreted only during box.cfg phase
Presence of environment variables MUST NOT trigger execution of box.cfg

Rules for type conversions:

* If some argument accepts table, then consider environment variable as comma-separated value
* If env variable could not be parsed into correct value (for example `TT_READAHEAD=abc`), then appropriate error with explanation must be thrown.

Please, as an implementation details, support multiple variants of environment variable name for one config option. We will consider more convenient and handy names for some options as an aliases.

**Comment by okoshovetc** [comment]
It would also be useful to be able to change box.cfg{} params with command line arguments. Would like to see something like this
```bash
tarantool -Clisten=3301 simple_app.lua
```

It would greatly simplify launch of multiple simple applications that only have a couple of spaces/functions

**Comment by orchaton** [comment]
I've found nice setup of ETCD cluster. Maybe tarantool may use it as a reference https://etcd.io/docs/v3.4.0/op-guide/configuration/

**Comment by romanhabibov** [comment]
In the discussion, we decided that all `box.cfg{}`calls (reloads of cfg) except the first one must ignore environment variables.
