### ISSUE TITLE
Dirty reads after restart with synchronous replication and transaction manager

### ISSUE THREAD

**Issue by sergepetrenko** [tarantool/tarantool#5610]
Tarantool version: 2.6+

Follow these steps to reproduce: 
1. Start a single instance and configure it as follows:
```lua
box.cfg{
    replication_synchro_quorum=2,
    replication_synchro_timeout=100,
    memtx_use_mvcc_engine=true
}
```
2. Create a synchronous space
```lua
box.schema.space.create('test', {is_sync=true})
box.space.test:create_index('pk')
```
3. Insert something to the space. Since `replication_synchro_quorum` is `2`, the insertion will stall for 100 seconds.
```lua
require('fiber').new(function() box.space.test:insert{1} end)
```
4. Everything's fine for now: `box.space.test:select{}` returns nothing.
5. Kill the instance before the insertion from step 3 times out.
6. Restart the instance, configure it the same way that we did in step 1
7. The synchronous transaction isn't committed. You may check that by doing something like
```lua
box.space.schema:replace{'smth'}.
```
The replace will stall, since the limbo isn't empty..
8. Still, `box.space.test:select{}` will return `[1]` ?!

**Comment by alyapunov** [comment]
Nice catch, will be fixed in #5973
