### ISSUE TITLE
Cannot run SQL on tarantool: Space [space_name] does not exists

### ISSUE THREAD

**Issue by kokizzu** [tarantool/tarantool#5617]
Tarantool version: docker image:  tarantool/tarantool:2.6.0

OS version: Ubuntu 20.04 64-bit 5.4.0-51-lowlatency 

Bug description: can do select on a space, but can't execute sql
```
box.space.listings:select()
-- output shown
box.execute [[select * from listings]]
---
- null
- Space 'LISTINGS' does not exist
...
```

Steps to reproduce:
1. create a space
2. insert one or more record
3. run queries above using `tarantoolctl connect 3301` or `docker exec -it tarantool_1 console`

Optional (but very desirable):
* coredump
* backtrace
* netstat

**Comment by kokizzu** [comment]
possible duplicate of https://github.com/tarantool/tarantool/issues/5592

**Comment by akudiyar** [comment]
SQL table names are uppercase by the standard. For using lowercase names wrap them in quotes in requests:

`box.execute [[select * from "listings"]]`

**Comment by Totktonada** [comment]
Yep, this is the expected behaviour.
