### ISSUE TITLE
Downstream all aarch64-related patches from vanilla LuaJIT repo

### ISSUE THREAD

**Issue by igormunkin** [tarantool/tarantool#5629]
There are several issues blocking Tarantool from being used on arm64. One of the showstoppers is #2712. As a first step to get closer to arm64 stability is syncing all aarch64-related patches from [vanilla LuaJIT repo](https://github.com/LuaJIT/LuaJIT) according to the procedure developed in scope of #5534.

There is the list of related issues:
* [x] #2712
* [x] #6084
* [x] #6093
* [x] #6065
* [x] #6098
* [x] #6227

**Comment by Buristan** [comment]
This issue was about ARM64-related show stoppers found via Tarantool CI. Further backporting activity will proceed within #6548 and #7230.
