### ISSUE TITLE
Update issue templates

### ISSUE THREAD

**Issue by ligurio** [tarantool/tarantool#5642]
I think we can improve our templates for issues.
- Right now we use common template for all kinds of issues: feature requests, bug reports and questions. It would be good to customize template for each kind of issue.
- Highlight sections in templates to improve readability.
- Set default labels for new issues.

GH allows to use different templates for bug reports, feature requests and template for other issues [1]. 

1. https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/configuring-issue-templates-for-your-repository
2. https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/manually-creating-a-single-issue-template-for-your-repository

**Comment by Totktonada** [comment]
The idea is nice! I propose to send a patch / PR to share your vision of a right way to do so. I think this way we'll earlier start the discussion.

**Comment by Korablev77** [comment]
I'd better remove it at all: I'm tired of seeing the same copy-paste lines in every second issue.

**Comment by ligurio** [comment]
> I'd better remove it at all: I'm tired of seeing the same copy-paste lines in every second issue.

I feel your pain.
Although I think it is not related to templates but to carelessness of issue's authors.

**Comment by ligurio** [comment]
@Totktonada templates are here https://github.com/tarantool/tarantool/compare/ligurio/gh-5642-issue-templates
could provide feedback?

**Comment by Totktonada** [comment]
I left several superficial comments in the [commit](https://github.com/tarantool/tarantool/commit/21fa163bc564f967bb0f4220da15e00c253801d5). There is no way glance on the whole discussion without a pull request: comments will spread across different commits. So I would prefer to have a PR for the discussion.

(Will current comments be attached to a new PR if you'll open the PR prior to force-pushing the branch? Maybe...)

**Comment by ligurio** [comment]
@Totktonada thanks for review! I have updated templates and created a PR - https://github.com/tarantool/tarantool/pull/5690
