### ISSUE TITLE
github-ci: need to implement link integration in history for coverity and coveralls in debug test jobs

### ISSUE THREAD

**Issue by avtikhon** [tarantool/tarantool#5644]
Bug description:
Need to resolve issues mentioned in comment [1].

During implementation of **_coverity_** and **_debug_coverage_** jobs in Github-CI Actions at issue #5600, found 2 issues:
 - result comment from **_coverity_** job in Github-CI Actions run didn't automatically appear in linked PR #5621 
 - previously testing **_debug_** job with coverage in Travis CI automatically wrote a comment with measured code coverage value [2], while **_debug_coverage_** job in Github-CI Actions didn't create the comment in #5621

[1] - https://github.com/tarantool/tarantool/pull/5621#discussion_r543315430
[2] - https://github.com/tarantool/tarantool/pull/5618#issuecomment-743978691

**Comment by Totktonada** [comment]
The comments you linked are about coveralls, not coverity.
