### ISSUE TITLE
Several iproto threads

### ISSUE THREAD

**Issue by alyapunov** [tarantool/tarantool#5645]
There are users that have specific workloads where iproto thread is the bottleneck of throughput: iproto thread's code is 100% loaded while TX thread's core is not.
For such cases it would be nice to have a capability to create several iproto threads. I think we should share listen socket(s) between network thread while every transport socket should be managed by one of network threads exclusively.
Of course there must be an option like `iproto_threads` that haven't to be dynamic.

**Comment by Gerold103** [comment]
Pinning of connections to threads is never a good idea. It will lead to one thread becoming a bottleneck while the others are not fully loaded.

**Comment by Totktonada** [comment]
Looks relevant to #3554. Hopefully even as the move toward #3549.

**Comment by karlovnv** [comment]
see also https://github.com/tarantool/tarantool/issues/4768#issuecomment-583396057

**Comment by mechanik20051988** [comment]
We can't use the same port and address for bind/listen from different Iproto threads because     SO_REUSEPORT (since Linux 3.9) Permits multiple AF_INET or AF_INET6 sockets to be bound to an identical socket address. So we need a single thread manager that accepts connections and spreads them across iproto threads.

**Comment by Gerold103** [comment]
I will duplicate it here in case not everybody noticed above: pinning of connections to threads is never a good idea. It will lead to one thread becoming a bottleneck while the others are not fully loaded. Regardless of how you balance them.

**Comment by Gerold103** [comment]
I recently just did exactly the same task on my other job. I could give some hints if necessary.

**Comment by mechanik20051988** [comment]
During discussion with Mons, we decided to do as follows: in each iproto thread, listens to the same socket, then the thread that caught the connection owns the connection.

**Comment by alyapunov** [comment]
> I will duplicate it here in case not everybody noticed above: pinning of connections to threads is never a good idea. It will lead to one thread becoming a bottleneck while the others are not fully loaded. Regardless of how you balance them.

Are you sure that pinning always leads to the problem? I believe it's possible but I'm sure it will not be our main problem. But still what you propose?
We have obvious requirements:
1. If a user uses only one net thread, the latency must be not greater than that in current tarantool version.
2. We should not overkill now, we want to provide a simple solution for those rare users that have a net thread in 100% cpu: *double the number of threads until none of them in 100% cpu*.
3. Configuration allows further optimizations and improvements (when/if we need them).

I thought a bit about perfectly balanced solution. If we share a connection between threads we'll nevertheless need exclusively read/write from the socket in order to provide correct read order. I think a mutex is needed for each connection (or EPOLLONESHOT with epoll which I guess if worse). If you know a better solution please spill a couple of words.

**Comment by Gerold103** [comment]
I have a perfectly balanced solution without connection pinning, and implemented it twice on my other job for 2 different subsystems: for networking and for general asynchronous task scheduling in a thread pool. It is almost lock-free (lock is taken extremely rare, and there are only 2 of them for the entire scheduler - sockets themselves don't have any), and provides such behaviour that you can be sure a connection is either being handled in one of the worker threads, or is waiting for more events from epoll/iocp/poll/select/kqueue/anything.

Another place you can look for a smarter algorithm - C++ Boost, look for the concept of 'strand' and at asio subsystem. Code there is surprisingly not so hard to read. My solution is inspired by the one from Boost anyway.

I can try to elaborate my algorithm in more details in case anybody cares to actually consider it or at least take into it account when implement the cumbersome solution about pinning sockets to threads. The algorithm mostly revolves around a heavily optimized MPSC queue, and some hard atomic operation usage.

Talking of your comment:

> If a user uses only one net thread, the latency must be not greater than that in current tarantool version. We should not overkill now, we want to provide a simple solution for those rare users that have a net thread in 100% cpu: double the number of threads until none of them in 100% cpu.

You solve one issue and introduce another - unbalanced CPU usage. If user is unlucky or has certain pattern of connects/disconnects, he can end up with some threads consuming notably more CPU. Which will make him add more threads even though not all cores are utilized.

> Configuration allows further optimizations and improvements (when/if we need them).

How is it related to the configuration? Assume you have 2 iproto threads. One of them has a fat client pinned. For example, some routers with heavy discovery. It uses 80-100% CPU with big latency, the other one is somewhere at 10%. Assume you added another thread via the magic config. How will it help with the issue? Assume it gave you this CPU spread: 5, 5, and still 80-100% in the third thread. What next? Restart? Add more threads?

**Comment by kostja** [comment]
You got multiple iproto threads, what next? How is that helping you build an efficient cluster? And if not, what's the point of scaling a single instance?

**Comment by alyapunov** [comment]
> You got multiple iproto threads, what next?
Several listen ports and encription.
> How is that helping you build an efficient cluster?
By no means.
> And if not, what's the point of scaling a single instance?
It's cheap.

**Comment by alyapunov** [comment]
We discussed perfectly balanced solution, here's my very short summary.
1. One instance of scheduler that collects net events. The instance is shared between threads.
2. Events are put to queue that is processed by different threads that makes actual I/O.
3. After processing the I/O the event is sent to scheduler via another queue.

Actually there are a lot of details to care about. I'm not sure I should write complete RFC now. But if everything was made well it would be a solution with very low overhead.

Known pitfalls:
1. When core event engine is level-triggered (as libev) the scheduler should better stop that event on this socket, and start after I/O processing. That's an excess overhead. In one-thread configuration (most common case) that can degrade performance and thus requires workaround.

**Comment by Mons** [comment]
@alyapunov @Gerold103, short decision:

1. For now implementing fair algorithm is not effective from the point of human resource usage.
2. There is no difference, do it now or do it after 3-4 month: the cost of work would be the same.

So, it is efficient to move on with current straight implementation and then return to this question as an optimisation.
