### ISSUE TITLE
Vinyl support Q1'21

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#5653]
Placeholder.

**Comment by Korablev77** [comment]
Would be nice to see what 'vinyl support' is supposed to mean (i.e. which kind of actions are included into this issue).

**Comment by Totktonada** [comment]
Everything to make paid users don't cry.

**Comment by Korablev77** [comment]
Hm, but what about severe crashes reported by casual users?

**Comment by Totktonada** [comment]
Just kidding, sorry for the offtopic.

**Comment by Korablev77** [comment]
Related:
https://github.com/tarantool/tarantool/issues/5054
https://github.com/tarantool/tarantool/issues/5823
