### ISSUE TITLE
Tarantool SQL: consider automatic conversion of concatenation operator like in other databases

### ISSUE THREAD

**Issue by kokizzu** [tarantool/tarantool#5664]
Tarantool version: 2.6.1-134-g19f468bb1

OS version: Linux-x86_64-RelWithDebInfo

Bug description:
not a bug, just inconvenience, concatenation need manual conversion unlike other databases (mysql, postgresql)
```
SELECT CONCAT('test',123) -- mysql
# test123
SELECT 'test' || 123 -- postgres
# test123
```

Steps to reproduce:
```
box.execute [[SELECT 'test' || 123]]
---
- null
- 'Inconsistent types: expected text or varbinary got unsigned'
...
```

**Comment by Korablev77** [comment]
According to ANSI SQL concatenation operator takes strings or binary strings as arguments. In databases like mysql and posgresql there's implicit cast between numeric types and strings, which is extension and is not part of ANSI SQL. Meanwhile we are attempting to make our SQL implementation closer to ANSI, so there's no implicit cast in this case. Still you can use explicit CAST operator to run query from your example:
```
tarantool> box.execute [[SELECT 'test' || CAST(123 as TEXT)]]
---
- metadata:
  - name: COLUMN_1
    type: string
  rows:
  - ['test123']
...
```
I'm afraid we are not going to change this behaviour. Maybe some day we may introduce support of optional non-strict type mode, which turns on implicit casts (but definitely not in the nearest future).

**Comment by kokizzu** [comment]
or at least show which line/position that are causing the error, since this so annoying when the queries are long and have many concatenation
