### ISSUE TITLE
field metadata

### ISSUE THREAD

**Issue by unera** [tarantool/tarantool#567]
I told to Mons yesterday and he and I want the same :)
1. Each space must have 'default schema' record (see below)
2. function 'show -me-my-grants' must show the space's schema, too
3. tuples should use the schema to access its internal data

default space'schema includes
1. name and type (`NUM` or `STR`) for each field that user want be named
2. default_field_type - type for fields that were not listed in previous list

So the following lua code should be accessible:

``` lua

local user = box.space.site_users:get(id)
return { user.id, user.name, user.surname }

```

at the first time tarantool will not use field types, but future will able to.

**Comment by nekufa** [comment]
@kostja looks like this issue was resolved
