### ISSUE TITLE
Extend module API with functions from `box.session` (box_session_xxx)

### ISSUE THREAD

**Issue by olmiik** [tarantool/tarantool#5676]
While developing [tarantool-module](https://github.com/picodata/tarantool-module) we extensively use module API. 

Recently we faced, that most of functions from `box.session` are not included in module API. Would it be possible to change that?

We can extend this commit #2961 to include all functions from `box.session` to module API.

**Comment by NeraverinTarantool** [comment]
Details are sensitive to our customers to not disclose here.
