### ISSUE TITLE
[Upgrade]ER_ACCESS_DENIED: Usage access to universe '' is denied for user 'admin'

### ISSUE THREAD

**Issue by fangguangyang** [tarantool/tarantool#5677]
Tarantool version: 1.8.3

OS version: Centos7.7

Bug description:
```
alter.cc:103 E> ER_ACCESS_DENIED: Usage access to universe '' is denied for user 'admin'
F> can't initialize storage: Usage access to universe '' is denied for user 'admin'
F> can't initialize storage: Usage access to universe '' is denied for user 'admin'
```
step:
I build 2.0.4 and run it with snap file of 1.8.3

 What can I do to upgrade tarantool ver 1.8.3 to 2.x

**Comment by Totktonada** [comment]
1.8.3 was broken in many ways and now there is no simple recipe how to repair its snapshot or make logical dump. You can send me your snapshot (see email in GitHub's profile) and I'll look what I can do.

**Comment by fangguangyang** [comment]
@Totktonada  Thank you for your willingness to help, I had send you one of my snapshot, I hope to get help from the tarantool program, because I have a lot of snapshots in use :joy:

**Comment by fangguangyang** [comment]
[00000000003196820119.zip](https://github.com/tarantool/tarantool/files/5811662/00000000003196820119.zip)
