### ISSUE TITLE
Report all JIT-related allocations as internal.

### ISSUE THREAD

**Issue by Buristan** [tarantool/tarantool#5679]
Memory profiler reports source line as 0 if trace (or other JIT-related stuff) is allocated inside some Lua chunk.

For example, if we have <test.lua> file with the corresponding code:
```lua
local f1, msg1, errno1 = misc.memprof.start("/tmp/tmp_memprofile.bin")
for _ = 1, 100 do
  local _ = {_, _}
end
```

We obtain the following output from the profiler parser.
```
ALLOCATIONS
@test.lua:0, line 3: 57    3192    0
@test.lua:0, line 0: 4     640     0 <- JIT-related allocations
INTERNAL: 2     438     0

REALLOCATIONS

DEALLOCATIONS
INTERNAL: 24    0       1177
        Overrides:
                @test.lua:0, line 3
                INTERNAL
```

It will be prettier to report all JIT-related allocations as internal so as not to confuse users.

**Comment by igormunkin** [comment]
The feature is introduced in scope of tarantool/luajit@196d4ca. The submodule was updated in tarantool in 2.10.0-beta2-79-gc7823c5d1 (c7823c5).
