### ISSUE TITLE
Tarantool supervisor (MVP)

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#5682]
A service that will able to spawn properly configured tarantool instances (see also #5602) and manage them on given machine.

The service should know how to connect to an instance, where it stores snapshots, WALs, vinyl metadata and data, how to check health of an instance, how to read a log (syslog / file). Maybe how to reconfigure the instance, expel it from a cluster.

Within the scope of this issue a resident process (with a private API) + cli is enough. A public supervisor API is part of another issue.

The supervisor should be useful as for production deployments as well as for local development.

It would be good to support usual tarantoolctl layout.

**Comment by LeonidVas** [comment]
Repo moved to organization "tarantool" (https://github.com/tarantool/tvisor)
