### ISSUE TITLE
Adapt or remove disabled tests checking debug line hook trace from PUC-Rio Lua 5.1 test suite in db.lua

### ISSUE THREAD

**Issue by Buristan** [tarantool/tarantool#5693]
This ticket is a logical continuation of gh-4473.

If run  PUC-Rio Lua 5.1 test suite by LuaJIT (HEAD at the moment: [`1672bdc`](https://github.com/tarantool/luajit/commit/1672bdc0ffbee9f32fadb6943909d6af7eb9a7b1)) (not Tarantool) it fails with the following error:
```
../home/burii/builds_workspace/luajit/gh-4473-adopt-luavela-test-suites/src/luajit: db.lua:17: wrong trace!!
stack traceback:
        [C]: in function 'assert'
        db.lua:17: in function '__index'
        db.lua:19: in function 'test'
        db.lua:98: in function 'dofile'
        ...adopt-luavela-test-suites/test/PUC-Lua-5.1-tests/all.lua:82: in main chunk
        [C]: at 0x560fb7692f96
```
caused by this test chunk (assuming that all previous failing test chunks non relating to this error are disabled):
```lua
test([[if
math.sin(1)
then
  a=1
else
  a=2
end
]], {2,4,7})
```

`test()` function is the following:
```lua
function test (s, l, p)
  collectgarbage()   -- avoid gc during trace
  local function f (event, line)
    assert(event == 'line')
    local l = table.remove(l, 1)
    if p then print(l, line) end
    assert(l == line, "wrong trace!!")
  end
  debug.sethook(f,"l"); loadstring(s)(); debug.sethook()
  assert(table.getn(l) == 0)
end
```

LuaJIT interprets a return from calling result of `loadstring()` with a new line number unlike Lua does.

**Comment by igormunkin** [comment]
The issue is resolved in scope of tarantool/luajit@54f14dc. The submodule was updated in tarantool in 2.11.0-entrypoint-136-gb1953b59a (b1953b5), 2.10.0-46-gb33ad44a9 (b33ad44), 1.10.13-23-g519fdb05b (519fdb0).
