### ISSUE TITLE
Adapt or remove disabled tests checking debug count hook from PUC-Rio Lua 5.1 test suite in db.lua

### ISSUE THREAD

**Issue by Buristan** [tarantool/tarantool#5701]
This ticket is a logical continuation of gh-4473.

If run  PUC-Rio Lua 5.1 test suite by LuaJIT (HEAD at the moment: [`1672bdc`](https://github.com/tarantool/luajit/commit/1672bdc0ffbee9f32fadb6943909d6af7eb9a7b1)) (not Tarantool) it fails with the following error:
```
/home/burii/builds_workspace/luajit/gh-4473-adopt-luavela-test-suites/src/luajit: db.lua:329: a
ssertion failed!
stack traceback:
        [C]: in function 'assert'
        db.lua:329: in function 'dofile'
        ...adopt-luavela-test-suites/test/PUC-Lua-5.1-tests/all.lua:82: in main chunk
        [C]: at 0x55718dcf4f96
```
caused by this test chunk (assuming that all previous failing test chunks non relating to this error are disabled):
```lua
debug.sethook(function (e) a=a+1 end, "", 1)
a=0; for i=1,1000 do end; assert(1000 < a and a < 1012)
```

LuaJIT does not check hooks at traces without defined `-DLUAJIT_ENABLE_CHECKHOOK`.
For more information see <src/lj_record.c> or commit 6bce6b118eeb2bb7f36157de158e5cccf0ea68e5 (Add compile-time option LUAJIT_ENABLE_CHECKHOOK. Disabled by default.).

This issue can be resolved at least with these ways:
* Add `jit.off()`/`jit.on()` preamble/postamble.
* Add `-DLUAJIT_ENABLE_CHECKHOOK` flag by default to compile flags.

**Comment by igormunkin** [comment]
The issue is resolved in scope of tarantool/luajit@55ba4db. The submodule was updated in tarantool in 2.8.0-249-g8a09e18ce (8a09e18), 2.7.1-210-g5f4298b6f (5f4298b), 2.6.2-203-g8343a8129 (8343a81), 1.10.9-119-g7a4c7d0b0 (7a4c7d0).
