### ISSUE TITLE
Fix disabled tests checking using math.mod() instead math.fmod()  from PUC-Rio Lua 5.1 test suite in constructs.lua

### ISSUE THREAD

**Issue by Buristan** [tarantool/tarantool#5711]
This ticket is a logical continuation of gh-4473.

If run  PUC-Rio Lua 5.1 test suite by LuaJIT (HEAD at the moment: [`1672bdc`](https://github.com/tarantool/luajit/commit/1672bdc0ffbee9f32fadb6943909d6af7eb9a7b1)) (not Tarantool) it fails with the following error:
```
/home/burii/builds_workspace/luajit/gh-4473-adopt-luavela-test-suites/src/luajit: constructs.lua:205: attempt to call field 'mod' (a nil value)
stack traceback:
        constructs.lua:205: in function 'f'
        constructs.lua:219: in function 'dofile'
        ...adopt-luavela-test-suites/test/PUC-Lua-5.1-tests/all.lua:88: in main chunk
        [C]: at 0x55b124f47f96
```
caused by this test chunk (assuming that all previous failing test chunks non relating to this error are disabled):
```lua
  local res = math.mod(math.floor(i/c), b)+1
```

According to [this section](https://www.lua.org/manual/5.1/manual.html#7.2) in Lua 5.1 Reference Manual, `math.mod()` is renamed to `math.fmod()` if build Lua 5.1 without flag `-DLUA_COMPAT_MOD`.
LuaJIT also has `math.fmod()` instead `math.mod()` builtin.

**Comment by igormunkin** [comment]
The issue is resolved in scope of tarantool/luajit@2a76d74. The submodule was updated in tarantool in 2.8.0-249-g8a09e18ce (8a09e18), 2.7.1-210-g5f4298b6f (5f4298b), 2.6.2-203-g8343a8129 (8343a81), 1.10.9-119-g7a4c7d0b0 (7a4c7d0).
