### ISSUE TITLE
One on commit trigger for a multi-statement transaction

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#5717]
## Problem
There is `box.on_commit()`, which can be called anywhere inside a transaction. But it is not usable when you want to install it from an `on_replace` trigger of a space. Because if you do so, and there is a transaction making several statements on the space, you will install the same `on_commit` trigger multiple times. It is not ok, when the commit trigger wants to do something for the whole transaction, not for each statement.

Example of how it works now:
```Lua
box.cfg{}

count = 0
function on_commit() count = count + 1 end
function on_replace() box.on_commit(on_commit) end

s = box.schema.create_space('test')
_ = s:create_index('pk')

s:on_replace(on_replace)
box.begin() s:replace{1} s:replace{2} box.commit()
```
```
tarantool> count
---
- 2
...
```

## Solutions
It can be workarounded like this:
```Lua
function on_replace()
    pcall(box.on_commit, nil, on_commit)
    box.on_commit(on_commit)
end
```
But it is ugly and slow because removal of an old trigger in Lua has linear complexity on trigger count.

It is possible to use fiber local storage to set a flag saying that the needed triggers were already installed, but it won't work for soon coming IProto transactions, which won't be attached to a fiber.

It can be also workarounded by using the public function `box_txn_id()` via FFI and storing 'transaction local storages' by their IDs in a Lua table, which would be cleared by triggers installed for `on_commit and `on_rollback`. The only problem is that a user needs to use FFI for this.

## Summary
- Either expose `box_txn_id()` to Lua as is;
- Or implement the whole transaction-local storage feature in Lua like I described it above. It shouldn't even involve C in any way.

I raise this feature request here because I need it in vshard in at least 2 places:
- For `_bucket` state change subscription. I want to install a commit trigger for each transaction changing _bucket space and raise a condition or run more special triggers from there;
- I will probably need it for the flawless rebalancing (when bucket is mutable during migration).

**Comment by alyapunov** [comment]
Let's implement `on_commit_statement`/`on_rollback_statement` triggers?
