### ISSUE TITLE
Implement on_shutdown trigger

### ISSUE THREAD

**Issue by EvgenyMekhanik** [tarantool/tarantool#5723]
Tarantool module author should be able to register function that will be called when tarantool is turned off and correctly release all module's resources. Also this function must be called in new tx thread fiber, so, we need a mechanism for asynchronously waiting for the module completion. See https://github.com/tarantool/tarantool/discussions/5641

**Comment by alyapunov** [comment]
After discussions I propose an update of issue description.
Despite the issue originated from thread API discussion (#5641) the idea of on_shutdown is wider and should be implemented as standalone feature.
The goals that have to be achieved:
1. There must be a way to create a on_shutdown trigger that activates on sever shutdown.
1. Trigger must use common tarantool trigger facility.
1. In additional to internal C API (that must be similar to other trigger APIs) there must be a public C API that hides implementation.
1. On_shutdown trigger API should be accessible from lua as well.
1. On_shutdown triggers must be run using personal fibers created for each trigger.
1. Tarantool must fire all on_shutdown triggers in fibers and wait for that fibers' completion before proceeding shutdown.
1. There must be a timeout (3-5 seconds) after which tarantool should stop waiting in any case.
1. A user can create rude and simple shutdown trigger using blocking functions and graceful and optimal shutdown trigger that uses co-functions (for example a module could use `cord_cojoin` for its threads). Both methods must work.

**Comment by alyapunov** [comment]
I would suggest the following plan:
- [ ] Replace function `trigger_add_unique` (it's unused now) with similar `trigger_fund_unique`.
- [ ] Upgrade `fiber_join` to `fiber_join_timeout` function. Implement new `fiber_join` through `fiber_join_timeout`.
- [ ] Implement `trigger_fiber_run` similar to `trigger_fiber` but runs trigger in fibers with (!) given timeout.
- [ ] Implement internal on_shutdown trigger API.
- [ ] Implement public C on_shutdown trigger API.
- [ ] Implement lua on_shutdown trigger API (optional).

About public C public API:
1. There must be only one function in that API: `int on_shutdown(void *ctx, (*new_handler)(void *), (*old_handler)(void *));`. A user should use cooperative functions for waiting (only if they want). Returning from trigger routine notifies tarantool the the trigger has finished.
1. The implementation must internally allocate a structure inherited from `struct trigger` with additional needed fields.

**Comment by Totktonada** [comment]
Documentation request: https://github.com/tarantool/doc/issues/2104
