### ISSUE TITLE
Support LUA_INIT environment variable.

### ISSUE THREAD

**Issue by Buristan** [tarantool/tarantool#5744]
`LUA_INIT` environment  is ignored by Tarantool.

Test example:
```bash
$ LUA_INIT='print "foo" ' luajit  -e "os.exit()"
foo
$ LUA_INIT='print "foo" ' tarantool  -e "os.exit()"
```

It can be used to turn off strict (which is turned on by default, _only_ when built with Debug) when run LuaJIT tests from PUC-Rio Lua 5.1 test suite or Lua-Harness suite (see gh-4473).

**Comment by Mons** [comment]
No. It has a potential to be security hole.
