### ISSUE TITLE
Send feedback at start and on-demand

### ISSUE THREAD

**Issue by artur-barsegyan** [tarantool/tarantool#5750]
**Is your feature request related to a problem? Please describe.**

There are problems with counting "Tarantool starts" and "creation of space and index" events because this data is only received if the user has Tarantool running for more than one hour on the machine.

In order for us to assess the real situation for the product, it is necessary to send feedback from the product immediately after the launch and after the key actions are completed.

**Describe the solution you'd like**

If Tarantool was installed using a script from the Download page, then you need to send feedback immediately and further after the following events are completed:

- creation of the first space
- creating the first index

The usual interval of once an hour should be left.

The rest of Tarantool that were downloaded outside of the Download page does not contain a special meta-file and should be considered as `internal usage` and no feedback sent from them. These are usually CI instances.

As part of this task, you can add the use of the following features to the report:

- synchronous replication
- SQL

**Comment by sharonovd** [comment]
Please extend sent info with uptime, because we will need to filter out test/CI-based launches from our statistics
