### ISSUE TITLE
github-ci: port from gitlab-ci FreeBSD 12 build

### ISSUE THREAD

**Issue by avtikhon** [tarantool/tarantool#5754]
**Is your feature request related to a problem? Please describe.**

Need to port from gitlab-ci FreeBSD 12 build

**Describe the solution you'd like**

FreeBSD 12 build can be implemented using freebsd-vm github action.

**Describe alternatives you've considered**

Any other cloud resource with FreeBSD VM

**Additional context**

**Definition of Done**

Ported FreeBSD 12 build to github actions.

**Comment by ligurio** [comment]
CI systems with FreeBSD support:
- Cirrus CI (https://cirrus-ci.org/guide/FreeBSD/)
- Appveyor ([WIP](https://github.com/appveyor/ci/issues/2844))
- sourcehut (https://man.sr.ht/builds.sr.ht/compatibility.md#openbsd)
- Travis CI (https://erouault.blogspot.com/2016/09/running-freebsd-in-travis-ci.html)

**Comment by Totktonada** [comment]
Workaround for GitHub Actions: https://github.com/vmactions/freebsd-vm.
