### ISSUE TITLE
Support HTTP/2 for http.client

### ISSUE THREAD

**Issue by olegrok** [tarantool/tarantool#5771]
Currently our http client doesn't support HTTP/2:
https://github.com/tarantool/tarantool/blob/90a72ffd1a9b10a8cf52871e7a7c95c9285b8cdc/cmake/BuildLibCURL.cmake#L125

The issue is quite relevant since we plan to support H20 HTTP server.

**Comment by Totktonada** [comment]
NB: It assumes bundling of libnghttp2.
