### ISSUE TITLE
Feature Request: Ctrl+C on incomplete command will only cancel the command not exiting the tarantool client

### ISSUE THREAD

**Issue by kokizzu** [tarantool/tarantool#5776]
**Is your feature request related to a problem? Please describe.**

If we mistakenly type something halfway, and we want to cancel to redo the command, I usually type `Ctrl+C`
which the current behavior is closing the tarantool client (`tarantoolctl connect 3301`), while in other database (MySQL, PostgreSQL) `Ctrl+C` would only clear the currently typed commands/prompt buffer.

PostgreSQL:
```
root@data:~# psql -U x y
psql (12.5 (Ubuntu 12.5-0ubuntu0.20.04.1))
Type "help" for help.

y=> SELEC --> wrongly typed command
y-> ^C --> pressing Ctrl+C
y=> --> going back to prompt instead of exiting

y=>SELCT^C --> pressing Ctrl+C
y=> --> back to prompt instead of exiting
```

MySQL:
```
mysql -f -u root -x -h 127.0.0.1 -P 33061 y
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 27
Server version: 8.0.21 MySQL Community Server - GPL

Copyright (c) 2000, 2020, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> SLECT --> wrongly typed command
    -> 

^C --> Pressing ctrl+C and return/enter
mysql>  --> going back to prompt instead of exiting

```

**Describe the solution you'd like**

I wish that Tarantool client behaves the same (instead of exiting the command line).

**Definition of Done**

Ctrl+C when there's halfway text in the prompt will not exit the tarantool client.

**Comment by Totktonada** [comment]
Thanks for the clear description and examples!

I agree, this annoys me too.

We plan to fix this problem in the scope of #2717. I'll close this feature request as duplicate.
