### ISSUE TITLE
Use copy-on-write read view for long requests

### ISSUE THREAD

**Issue by alyapunov** [tarantool/tarantool#5797]
Tarantool uses special snapshot iterators for snapshot file creation.

Actually snapshot iterators use more general facility - read views for indexes and delayed deletion for tuples. Those read view could be created for any set of HASH or TREE indexes providing a read view of database. By design such a read view can be used in another thread without any synchronization.

We could use those read views for processing long read-only (SQL) requests consistently and cheap.

**Comment by opomuc** [comment]
read-only SQL queries in separate threads is a good idea. 

What happens if during a long query there will be a `write` operation in TX thread?

**Comment by msiomkin** [comment]
@opomuc, it looks like we have only three possible scenarios here:
* lock the table or use one thread mode without yields (the current logic)
* read uncommitted data (that's what NOLOCK hint does in MS SQL)
* read the old data from a snapshot

According to @alyapunov's description I think the third scenario is considered. @alyapunov, am I right?

**Comment by opomuc** [comment]
Actually, I think memtx mvcc can help with it, if I understand it correctly.

**Comment by alyapunov** [comment]
Current mvcc implementation is **not** designed for multithread.
The original idea was to create read view only for read-only requests. That mean that DML will raise an error.
