### ISSUE TITLE
Expose fiber.csw field in Lua

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#5799]
Each fiber counts context switches (yields) in a number with name `csw` (Context SWitch). The field can be obtained from `require('fiber').info()[fid].csw`, but can't be from `require('fiber').self().csw`. This is unfortunate as `.info()` does not have a filter - it puts info about all the fibers in a huge Lua table. Even the fact that you need to build any new Lua table, regardless of its size, to get `csw` is weird. Especially taking into account `csw` is not something private. It is public API.

Besides, `csw` can't be obtained if the fiber is dead. Even if you have fiber object in Lua still available. It returns `:id()`, `:status()`, but can't return `csw`, and is not available via `.info()` anymore.

Knowledge of `csw` can be useful when want to check if yields happened in some function. For instance, to assert it, or perform a manual rollback of a transaction. Or for the monitoring.

I propose to expose `csw` as a member of any fiber object.

**Comment by Mons** [comment]
I think not only csw, but all of the fiber info.

**Comment by iskander232** [comment]
I think we should add 2 functions

1) `info` as a member of `fiber` object  to show information of alive fiber
2) `csw` as a member of `fiber` object to show `csw` of both alive and dead fibers
