### ISSUE TITLE
Possible transaction flaws

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#5801]
I have Ubuntu 20.04. I have Tarantool 2.7 pulled from source today.

The manual now claims that with memtx_use_mvcc_engine
the transactional manager "provides serializable transaction isolation level"
https://www.tarantool.io/en/doc/latest/book/box/atomic/#transactional-manager
I didn't like this wording and ran some tests and saw some flaws.
I use SQL transactions which should mean I don't need to send all at once.
We could call each flaw "Not a bug" if we didn't have a serializable claim.

Start with:

Connection #1
box.cfg{listen=3302, memtx_use_mvcc_engine=true}
box.schema.user.passwd('admin')
box.execute([[CREATE TABLE k1 (s1 INT PRIMARY KEY);]])
box.execute([[CREATE TABLE k2 (s1 INT PRIMARY KEY, s2 INT REFERENCES k1);]])
box.execute([[CREATE TABLE k3 (c INTEGER PRIMARY KEY AUTOINCREMENT);]])
box.execute([[CREATE TABLE k4 (s1 INT PRIMARY KEY);]])

Connection #2
box.cfg{memtx_use_mvcc_engine=true}
net_box = require('net.box')
conn = net_box.connect('admin:admin@127.0.0.1:3302')

Flaw #1
-------

Connection #1:

box.execute([[INSERT INTO k1 VALUES (1);]])
box.execute([[START TRANSACTION;]])
box.execute([[INSERT INTO k2 VALUES (99,1);]])

Connection #2:
conn:execute([[DELETE FROM K1;]])

Connection #1:
box.execute([[COMMIT;]])
-- Suucceeds. So now there is a foreign key referencing a nonexistent row.

Flaw #2
-------

Conection #1:
box.execute([[DELETE FROM k2;]])
box.execute([[DELETE FROM k1;]])

Connection #2:
conn:execute([[SELECT COUNT(*), LUA('require("fiber").sleep(10); return 5'), (SELECT COUNT(*) FROM K1) FROM k1;]])

Connection #1 (do this during the 10 seconds before Connection #2's SELECT finishes)
box.execute([[INSERT INTO k1 VALUES (1);]])

When Connection #2's SELECT finishes, it will show:
 - [0, 5, 1]
In other words, we see COUNT(*) "as of statement start" and we see a
different value ("as of statement start plus 10 seconds".

Flaw #3
-------

Connection 1:
box.execute([[CREATE TABLE j (s1 INT PRIMARY KEY);]])
box.execute([[START TRANSACTION;]])
box.execute([[DROP TABLE j;]])
box.execute([[COMMIT;]])
-- Succeeds

Connection #2:
conn:execute([[CREATE TABLE j (s1 INT PRIMARY KEY);]])
conn:execute([[START TRANSACTION;]])
conn:execute([[DROP TABLE j;]])
conn:execute([[COMMIT;]])
-- Fails. Error: cannot commit - no transaction is active

In general: anything at all on connection #2 causes implicit commit.

But this is possible:

Connection #1:

function foo()
  box.execute([[START TRANSACTION;]])
  box.execute([[INSERT INTO k1 VALUES (10);]])
  box.execute([[COMMIT;]])
  box.execute([[START TRANSACTION;]])
  box.execute([[INSERT INTO k1 VALUES (11);]])
  box.execute([[ROLLBACK;]])
  end

Connection #2:
conn:call('foo')

So perhaps this is a duplicate of issue#3374.

Flaw #4
-------

Alas, I cannot repeat.

After playing for a while with various combinations of
statements on connection #1 and connection #2, I stopped
connection #1 with control-C, restarted ti, and saw
...
2021-02-10 14:54:38.094 [11727] main/103/interactive box.cc:402 E> error applying row: {type: 'INSERT', replica_id: 1, lsn: 74443, space_id: 519, index_id: 0, tuple: [1]}
2021-02-10 14:54:38.267 [11727] main/103/interactive memtx_tree.cc:778 E> ER_TUPLE_FOUND: Duplicate key exists in unique index 'pk_unnamed_K3_1' in space 'K3'
2021-02-10 14:54:38.267 [11727] main/103/interactive F> can't initialize storage: Duplicate key exists in unique index 'pk_unnamed_K3_1' in space 'K3'

I still have the .xlog and .snap if anybody cares.

**Comment by alyapunov** [comment]
It seem that flaw # 1 and # 2 were fixed in a patch set that is on a way to master. I'm sure that flaw # 4 was fixed too, since a lot of crashed were fixed since.
As for flaw # 3 - after streams were implemented we can do transaction via IPROTO (but DDL has some limitations though)
```lua
tarantool> strm = conn:new_stream()
---
...

tarantool> strm:execute([[START TRANSACTION;]])
---
- row_count: 0
...

tarantool> strm:execute([[INSERT INTO k1 VALUES (1);]])
---
- row_count: 1
...

tarantool> box.execute([[SELECT * FROM k1;]])
---
- metadata:
  - name: S1
    type: integer
  rows: []
...

tarantool> strm:execute([[COMMIT;]])
---
- row_count: 0
...

tarantool> box.execute([[SELECT * FROM k1;]])
---
- metadata:
  - name: S1
    type: integer
  rows:
  - [1]
...

```
