### ISSUE TITLE
Delay xlog gc until all replicas  from cluster are connected

### ISSUE THREAD

**Issue by sergepetrenko** [tarantool/tarantool#5806]
There is a problem with how master deletes old xlog files now: it remembers which files are needed by replicas only in runtime.  Once master is restarted, it may delete old xlogs before replicas reconnect leading to XlogGapError and forcing replicas to rejoin.

We may delay GC until all the replicas are connected. Then it'll be known which files to keep.
This issue was also mentioned in #3442, but it's not a duplicate. That ticket is about persistent gc, which is nice, and we may want to implement it separately sooner or later.

**Comment by sharonovd** [comment]
What will happen if there are some old replicas hanging in _cluster? Will it delay xlog gc forever?

**Comment by sergepetrenko** [comment]
Yes, it'll delay gc forever.

Until these replicas are removed from _cluster

**Comment by sergepetrenko** [comment]
If master is running low on disk space, however, it'll delete old xlogs, if any, anyway.
So it shouldn't be a problem
