### ISSUE TITLE
Make memprof raw output more user-friendly

### ISSUE THREAD

**Issue by Buristan** [tarantool/tarantool#5811]
The memory profiler output looks like the following for now:
```
ALLOCATIONS
@true_memleak.lua:6, line 9: 3	144	0
@true_memleak.lua:6, line 8: 2	41	0
```

Line of function definition is confusing for users and looks redundant.
Also, without reading RFC/documentation is unclear what is the rubbish these magic numbers.
@sergos, @igormunkin and I suggest the following format of output:
```
ALLOCATIONS
@true_memleak.lua:9: 3 events	+144 bytes	-0 bytes
@true_memleak.lua:8: 2 events	+41 bytes	-0 bytes
@true_memleak.lua:11: 2 events	+80 bytes	-0 bytes
```
So, functions definition line number should be hidden by default (but information about it should be saved inside the internal structure for future usage in IDE integration or whatever) and shown with additional flag.

**Comment by igormunkin** [comment]
The format is changed in scope of tarantool/luajit@cdf98db. The submodule was updated in tarantool in 2.8.0-170-gcec37a6be (cec37a6).
