### ISSUE TITLE
Add memprof --leak-only option

### ISSUE THREAD

**Issue by Buristan** [tarantool/tarantool#5812]
Profiling real application and finding memory leak becomes complicated task when the memory profiler output does not fit in the screen. `DEALLOCATION` section is aggregated (and become giant due to calls of `collectgarbage()` in the moment) and it's really hard to find memory leak.
It will be nice to add `--leak-only` option deaden the pain of users.

**Comment by igormunkin** [comment]
The feature is implemented in scope of tarantool/luajit@20f79e9. The submodule was updated in tarantool in 2.8.0-232-gef55e4881 (ef55e48).
