### ISSUE TITLE
memprof: group allocations on traces by trace number 

### ISSUE THREAD

**Issue by Buristan** [tarantool/tarantool#5814]
We already know the number of executing trace, where allocation event happens. So we can simplify debugging to users  by reporting not `INTERNAL:`, but `TRACE [n]:` with allocation event. It allows users to compare this output with `jit.dump()` and so on.

**Comment by igormunkin** [comment]
The feature is introduced in scope of tarantool/luajit@7059354. The submodule was updated in tarantool in 2.10.0-beta1-281-ge8765ba5c (e8765ba).
