### ISSUE TITLE
gc_cdatanum is counted improperly

### ISSUE THREAD

**Issue by Buristan** [tarantool/tarantool#5820]
Some kinds of cdata are counted improperly (i.e. are not counted).

How to reproduce:
Assume we have a file named <cdatanum.lua> with the following code:
```lua
local ffi = require "ffi"

local function collected() print"collected" end

collectgarbage()
print("before", misc.getmetrics().gc_cdatanum)
ffi.gc(ffi.cast("void *", 0), collected)
collectgarbage()
collectgarbage()
print("after", misc.getmetrics().gc_cdatanum)
```

Output:
``` bash
$ src/luajit cdatanum.lua
before  0
collected
after   -1
```

**Comment by igormunkin** [comment]
The issue is resolved in scope of tarantool/luajit@82932be. The submodule was updated in tarantool in 2.8.0-103-g3fe840b02 (3fe840b), 2.7.1-94-g755dfe2d5 (755dfe2), 2.6.2-91-g05ad06d14 (05ad06d).
