### ISSUE TITLE
vinyl: can't recovery data in case instance was shutdown during checkpoint

### ISSUE THREAD

**Issue by Korablev77** [tarantool/tarantool#5823]
Imagine following case: user has instance with both memtx and vinyl data. During checkpoint process something goes wrong and server turns out to be emergently turned off (due to electricity problems, admins accident, explosion or whatever). If this happens somewhere between `vinyl->wait_checkpoint ()` and `vinyl->commit_checkpoint()`, then we get instance which can't be bootsrapped even with force_recovery option. More relevant scenario: memtx engine runs `commit_checkpoint()` and fails to rename `*snap.inprogress` file. In this case we end execution with panic().
The reason we can't recover is mismatched vclocks of snapshot and vy_log files:
```
vy_log_begin_recovery(const struct vclock *vclock)
{
 	...
	int cmp = vclock_compare(&vy_log.last_checkpoint, vclock);
	if (cmp > 0) {
		/*
		 * Last vy_log log is newer than the last snapshot.
		 * This can't normally happen, as vy_log is rotated
		 * after snapshot is created. Looks like somebody
		 * deleted snap file, but forgot to delete vy_log.
		 */
		diag_set(ClientError, ER_MISSING_SNAPSHOT);
		return NULL;
	...
```
Since ` vy_log_begin_recovery` is called during initial recovery, errors are not ignored even in force_recovery mode.
vy_log rotation takes place in engine->wait_checkpoint() meanwhile snap rotation (at least renaming) - in commit_checkpoint(). 
To resolve this situation, user has manually remove last vy_log file (and pray that it will work).
A bit synthetic repro:
1. Apply this diff:
```
diff --git a/src/box/engine.c b/src/box/engine.c
index 88ed92861..5170fa791 100644
--- a/src/box/engine.c
+++ b/src/box/engine.c
@@ -30,6 +30,7 @@
  */
 #include "engine.h"
 
+#include "errinj.h"
 #include <stdint.h>
 #include <string.h>
 #include <small/rlist.h>
@@ -147,6 +148,9 @@ engine_commit_checkpoint(const struct vclock *vclock)
                if (engine->vtab->wait_checkpoint(engine, vclock) < 0)
                        return -1;
        }
+       if (errinj(ERRINJ_VINYL_CHECKPOINT_DELAY, ERRINJ_BOOL)->bparam) {
+               exit(-1);
+       }
        engine_foreach(engine) {
                engine->vtab->commit_checkpoint(engine, vclock);

diff --git a/src/lib/core/errinj.h b/src/lib/core/errinj.h
index 814c57c2e..dbfd517a2 100644
--- a/src/lib/core/errinj.h
+++ b/src/lib/core/errinj.h
@@ -149,6 +149,7 @@ struct errinj {
        _(ERRINJ_AUTO_UPGRADE, ERRINJ_BOOL, {.bparam = false})\
        _(ERRINJ_COIO_WRITE_CHUNK, ERRINJ_BOOL, {.bparam = false}) \
        _(ERRINJ_APPLIER_SLOW_ACK, ERRINJ_BOOL, {.bparam = false}) \
+       _(ERRINJ_VINYL_CHECKPOINT_DELAY, ERRINJ_BOOL, {.bparam = false}) \
 
 ENUM0(errinj_id, ERRINJ_LIST);
 extern struct errinj errinjs[];
```
2. Run instance with this script:
```
box.cfg {
    vinyl_memory = 128 * 1024 * 1024,
}

v = box.schema.space.create('test_v', {engine = 'vinyl'})
_ = v:create_index('pk', {run_count_per_level = 100, page_size = 128, range_size = 1024})

m = box.schema.space.create('test_m')
_ = m:create_index('pk')

str = string.rep('!', 100)
for i = 1,1000 do v:insert{i, str} end
for i = 1,1000 do m:insert{i, str} end

errinj = box.error.injection
errinj.set("ERRINJ_VINYL_CHECKPOINT_DELAY", true);
box.snapshot()
```

**Comment by kostja** [comment]
If snapshot rename failed, a previous (memtx) snapshot should be used during recovery/restart. That snapshot's vclock should be passed to vinyl - and vinyl should find a relevant vylog file for it. So the fix is to avoid recoverying vylog beyond memtx's snapshot vclock.

**Comment by alyapunov** [comment]
Just a couple of raw thoughts, I'm not insisting on any:
1. We can create `.vylog.inprogress` in `wait_checkpoint` and rename it to `.vylog` in `commit_checkpoint`. This approach will significantly narrow that time gap when tarantool have to terminate for the problem to be reproduced.
1. We could check emptiness of that last `vlog` file. I think in the case it must be empty. If it's not empty - I'm not sure it's safe to remove it.
1. Maybe we could rename `.vylog` to smth like `.vylog.removed` instead of removing it just for the case if we were wrong.

**Comment by Korablev77** [comment]
1. It's quite interesting idea and looks natural in terms of Tarantool, but I'm afraid its "overkill" for such specific issue - it is simply does not worth the effort.
2. It's not empty. While vylog is rotated, new one contains at least following entries:
CREATE_LSM
CREATE_RUN
INSERT_RANGE
INSERT_SLICE
SNAPSHOT
However, we can open vylog and check that the last entry is SNAPSHOT. In this case it is definitely safe to delete this file.
3. Mb but I'd prefer second option.
To sump up, I suggest following. If we find out that vylog is newer than snap then:
a) In casual recovery mode check that vylog's last entry is SNAPSHOT and in case it is - delete the file;
b) In force recovery mode unconditionally remove vylog and print verbose message in case vylog's last entry is not SNAPSHOT.
