### ISSUE TITLE
infra: add Ubuntu Hirsute (21.04) builds

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#5825]
https://wiki.ubuntu.com/Releases

> Version | Code name | Docs | Release | End of Life
> -- | -- | -- | -- | --
> Ubuntu 21.04 | Hirsute Hippo | Release Notes | April 22, 2021 | January 2022

**Comment by maxtushewski** [comment]
+

**Comment by ylobankov** [comment]
PR to build packages for the aarch64 system: https://github.com/tarantool/tarantool/pull/7135.
