### ISSUE TITLE
triggers: trigger setup misunderstanding

### ISSUE THREAD

**Issue by filonenko-mikhail** [tarantool/tarantool#5826]
The problem is that snippet every time called add new trigger on space

```
box.space[name]:before_replace(triggerfunc)
```

The expected behaiovoiur that every call the old trigger replaced with new. 

This time we probably do not want to change signature (but we definitely want it in tarantool3 milestone).

Consider the warning log when trigger count more than 10 at one space and threshold option in box cfg.

**Comment by olegrok** [comment]
Related to https://github.com/tarantool/tarantool/issues/5717

**Comment by unera** [comment]
We are going to rework trigger system in nextQ, so the issue goes to the wishlist.

**Comment by Totktonada** [comment]
@unera, the ideas here and in your document are very close: offer named triggers. So I think it is OK to close this issue with the upcoming changes.

**Comment by filonenko-mikhail** [comment]
Gently closing
