### ISSUE TITLE
Misterious luajit errors

### ISSUE THREAD

**Issue by rosik** [tarantool/tarantool#5832]
Sometmes Enterprise SDK test fails with a message:

```txt
4: Test command: /__w/sdk/sdk/build.sdk/tarantool-2.7/static-build/tarantool-prefix/src/tarantool-build/src/tarantool "/__w/sdk/sdk/tarantool-2.7/static-build/test/static-build/exports.test.lua"
4: Test timeout computed to be: 10000000
4: LuajitError: builtin/fun.lua:957: attempt to perform arithmetic on local 'i' (a nil value)
4: fatal error, exiting the event loop
4: TAP version 13
4/5 Test #4: check-exports ....................***Failed    0.06 sec
```

https://github.com/luafun/luafun/blob/04c99f9c393e54a604adde4b25b794f48104e0d0/fun.lua#L955-L959

```lua
chain_gen_r1 = function(param, state)
    local i, state_x = state[1], state[2]
    local gen_x, param_x = param[3 * i - 2], param[3 * i - 1]
    return chain_gen_r2(param, state, gen_x(param_x, state[2]))
end
```

The only use of luafun in the test:

```lua
check_symbols = require('fun').chain(
    check_symbols,
    sasl_symbols,
    ldap_symbols,
    lz4_symbols
):totable()

test:plan(#check_symbols)
for _, sym in ipairs(check_symbols) do
    check_symbol(sym)
end
```

The [enterprise test](https://github.com/tarantool/enterprise/blob/master/static-build/test/static-build/exports.test.lua) is slightly modified, but `check_symbols` is completely equal to https://github.com/tarantool/tarantool/blob/master/static-build/test/static-build/exports.test.lua. Other `*_symbols` are similar constant tables.

The test fails only occasionally, and I can't find a reason.

**Comment by rosik** [comment]
May be related to https://github.com/tarantool/tarantool/issues/4252

**Comment by igormunkin** [comment]
Look related to #5118, but your case fails in a different way than #4252, so I'm not marking this as a duplicate now.

**Comment by igormunkin** [comment]
@rosik, #5118 is [resolved](https://github.com/tarantool/tarantool/issues/5118#issuecomment-892725726). Please re-check whether the issue still bothers you.

**Comment by rosik** [comment]
I'm afraid it can't be checked quickly. I don't have a reproducer and don't know a pattern to cause it. I've set up the test loop, but it doesn't fail even for the unfixed version. 1000 retries so far and still no fails.

Here it is: https://github.com/tarantool/sdk/actions/runs/1099055836

**Comment by igormunkin** [comment]
Then closing it. Feel free to reopen if the issue occurs again (hope not).
