### ISSUE TITLE
Adapt lua-Harness test suite

### ISSUE THREAD

**Issue by Buristan** [tarantool/tarantool#5844]
Adapt  [Lua-Harness](https://fperrad.frama.io/lua-Harness/) for LuaJIT self-sufficient testing.

**Comment by igormunkin** [comment]
The suite is introduced in scope of tarantool/luajit@347b8bf and the issue is resolved in scope of tarantool/luajit@d4e12d7. The submodule was updated in tarantool in 2.8.0-133-ga0ade2066 (a0ade20), 2.7.1-122-ge1d9ccfca (e1d9ccf), 2.6.2-119-gb732e8b31 (b732e8b), 1.10.9-77-g4f703e77a (4f703e7).
