### ISSUE TITLE
Adapt PUC-Rio Lua 5.1 test suite

### ISSUE THREAD

**Issue by Buristan** [tarantool/tarantool#5845]
Adapt [Lua test suite](https://www.lua.org/tests/) for self-sufficient LuaJIT testing.

**Comment by sergos** [comment]
Woo-hoo! 👍

Best regards,
Sergos 

Wednesday, 14 April 2021, 23:02 +0300 from ***@***.***  ***@***.***>:

**Comment by igormunkin** [comment]
The suite is introduced in scope of tarantool/luajit@5aed55e and the issue is resolved in scope of tarantool/luajit@3caee9c. The submodule was updated in tarantool in 2.8.0-249-g8a09e18ce (8a09e18), 2.7.1-210-g5f4298b6f (5f4298b), 2.6.2-203-g8343a8129 (8343a81), 1.10.9-119-g7a4c7d0b0 (7a4c7d0).
