### ISSUE TITLE
Check stability of tarantool replicas running inside VMWare vSphere cluster with enabled vMotion

### ISSUE THREAD

**Issue by alexeykoryakin** [tarantool/tarantool#5866]
Need to test tarantool (master and two slave replicas) running heavy insert+update+delete load inside vSphere based cluster. Each replica runs in its own VMW VM on its own ESXi host. Periodically vMotion performs live-migration of VMs from one ESXi host to another one.

**Comment by avtikhon** [comment]
Draft testing made locally to check the test instructions.
[test_instructions.txt](https://github.com/tarantool/tarantool/files/6222781/test_instructions.txt)

**Comment by avtikhon** [comment]
1. начало тестирования
![image](https://user-images.githubusercontent.com/20123850/113382803-18c17180-938b-11eb-8d90-beb6fa9c397a.png)
2. процесс миграции
![image](https://user-images.githubusercontent.com/20123850/113382815-2119ac80-938b-11eb-8d70-e5679827af9d.png)
3. миграция закончилась - на экранах куча сообщений, но реплика показывает, что тестирование шло и продолжает идти без проблем
![image](https://user-images.githubusercontent.com/20123850/113382835-2aa31480-938b-11eb-867a-fbaba42d7be2.png)
4. обратный перенос так же идёт медленно, но уверенно
![image](https://user-images.githubusercontent.com/20123850/113382855-37c00380-938b-11eb-80f0-b41fe65ea9c1.png)
5. обратная миграция прошла так же успешно
![image](https://user-images.githubusercontent.com/20123850/113382874-43abc580-938b-11eb-8753-e359892bcbe5.png)

**Comment by avtikhon** [comment]
The issue with wrong master on continued replica was reproduced and complete instructions how to do it on VMotion were written in internal confluence. Next steps to check TDG/TDG2 with Cartridge using etcd and complete stand of its scheme used by our customers will be continued when the new issues on it will be created.
