### ISSUE TITLE
ffi.new() strangely drastic perf difference

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#5885]
`ffi.new()` gives sky and earth different perf when used for structures depending on whether they are allocated as an array. For instance, `ffi.new('struct tt_uuid[1]')` is ~600 times faster than `ffi.new('struct tt_uuid')`. The same works for other small structs, such as `struct port_c`. Here is the reproducer:
```Lua
local fiber = require('fiber')
local clock = require('clock').monotonic64
local ffi = require('ffi')

local run_count = 100
local iter_count = 100000

-- Make it look like there are many allocations. To simulate fragmentation.
local gc_burden = {}
for i = 1, 10000 do
    gc_burden[i] = ffi.new('int[10]')
end

local function bench_ffi_uuid_object()
    for i = 1, iter_count do
        local reg = ffi.new('struct tt_uuid')
        reg.time_low = i
    end
end

local function bench_ffi_uuid_array()
    for i = 1, iter_count do
        local reg = ffi.new('struct tt_uuid[1]')
        reg[0].time_low = i
    end
end

local times = {}
for i = 1, run_count do
    collectgarbage('collect')
    local t1 = clock()

    ------------------------- PUT THE BENCH CALLS HERE -------------------------
    bench_ffi_uuid_array()
    ----------------------------------------------------------------------------

    local t2 = clock()
    local duration = t2 - t1
    table.insert(times, duration)
end

table.sort(times)
print(string.format('Median value per iteration: %s ns',
                    tonumber(times[#times / 2]) / iter_count))
```
In the loop replace `bench_ffi_uuid_array` with `bench_ffi_uuid_object` to see the difference. I used Release build on Mac. The object allocation costs ~300ns per. The array allocation costs 0.5ns.

Probably there is an explanation why is it so, and it would be good to find it.

I thought this had something to do with `ffi.metatype()` being used for `struct tt_uuid`, but it appears the array elements also have the methods, just like object-allocated uuid. And it does not explain `struct port_c`, which does not have a "metatype".

**Comment by Totktonada** [comment]
Kinda same results on Linux (on Debug tarantool build if that matters).

With `jit.off()`: `bench_ffi_uuid_array` degrades from 0.5ns to 450ns, while `bench_ffi_uuid_object` remains around 300ns.

**Comment by sergepetrenko** [comment]
Related to #4630?
```
tarantool> jit.on()
---
...

tarantool> a = clock.realtime() for i = 1,1000000 do ffi.new("decimal_t") end print(clock.realtime() - a)
0.58546614646912
---
...

tarantool> a = clock.realtime() for i = 1,1000000 do ffi.new("decimal_t[1]") end print(clock.realtime() - a)
0.00062298774719238
---
...


```
Whereas with `jit.off()`:
```
tarantool> jit.off()
---
...

tarantool> a = clock.realtime() for i = 1,1000000 do ffi.new("decimal_t") end print(clock.realtime() - a)
0.58269882202148
---
...

tarantool> a = clock.realtime() for i = 1,1000000 do ffi.new("decimal_t[1]") end print(clock.realtime() - a)
0.7836217880249
---
...


```

**Comment by Gerold103** [comment]
Since we now have this ticket, I also want to piggyback a related issue. Assume, I don't want to use `ffi.new()` because 99.999% of time I need only a single temporary object in the entire thread. On the other hand, I can't make it just global because of #5632. So I tried to invent a "pool" from which I could take an object and put it back. If couldn't put back due to exception or anything else - it is populated again on a next usage:

```Lua
local function ffi_pool_new(c_type)
    local shared_obj = nil

    local function take()
        local res
        res, shared_obj = shared_obj, nil -------> [1] <-------
        if res ~= nil then
            return res
        end
        return ffi.new(c_type)
    end

    local function put(obj)
        shared_obj = obj
    end

    return {
        take = take,
        put = put,
    }
end
```

And I am not really sure it works 100% correct. Can it be that in [1] Lua will invoke GC, which would invoke a `__gc` handler touching the same "pool" object, and leaving it in some invalid state? I need [1] to be atomic regarding GC intervention.

I suspect GC might be invoked in case [1] needed to allocate more memory on the stack. Maybe @Buristan could answer this question? What are the "atomicity"/"GC preemtion" guarantees we have?

This is related to the ticket, because instead of relying on `ffi.new()` to be jitted I could have the "pool" for hot places, such as `box.space.<...>:select()`, which currently uses a global `struct port_c` in an unsafe way.

**Comment by Buristan** [comment]
I agree with @sergepetrenko that the root reason is same as for #4630.
I suppose that this is that case:
> Initialization of nested struct/union types.

According to [this](https://github.com/LuaJIT/LuaJIT/blob/787736990ac3b7d5ceaba2697c7d0f58f77bb782/src/lj_crecord.c#L1040) line of sources, trace is compiled if a structure contains only pointers, numbers or enums.

If I run your code chunk with 
```lua
require("jit.dump").start("-m")
```
I see corresponding JIT-failed message:
```
---- TRACE 3 abort tffi.lua:27 -- NYI: unsupported C type conversion
```
So the performance degradation is the result of absence of compiler optimization. For example, if I run this code locally without any modifications the result is around 0.69 ns for variant with an array. But with `jit.opt.start("-sink")` the result is down to 15.39 ns for the same benchmark.

Meanwhile, as for the second question:
Here are bytecodes for the `take()` function

```bash
$ luajit -bl -e '
local shared_obj = nil

local function take()
    local res
    res, shared_obj = shared_obj, nil -------> [1] <-------
    if res ~= nil then
        return res
    end
    return ffi.new(c_type)
end

take()
'
-- BYTECODE -- 0x40ad2808:4-11
0001    KPRI     0   0
0002    UGET     1   0      ; shared_obj
0003    USETP    0   0      ; shared_obj
0004    MOV      0   1
0005    ISEQP    0   0
0006    JMP      1 => 0008
0007    RET1     0   2
0008 => GGET     1   0      ; "ffi"
0009    TGETS    1   1   1  ; "new"
0010    GGET     2   2      ; "c_type"
0011    CALLT    1   2

-- BYTECODE -- 0x40ad28b8:0-13
0001    KPRI     0   0
0002    FNEW     1   0      ; 0x40ad2808:4
0003    MOV      2   1
0004    CALL     2   1   1
0005    UCLO     0 => 0006
0006 => RET0     0   1
```

GC is invoked only in case when some object is created/resized. `[1]` corresponds to first 4 bytecodes (from `KPRI` to `MOV`). There are no allocations/reallocations during these bytecodes execution, so it is guaranteed that GC can't be invoked there.

All necessary stack resizing might be done at the `FUNCF` bytecode (it will next after `CALL`, but before function's body), but even it does not cause the GC to wake up, because `lj_gc_check()` is not called.

It may be invoked later at comparing (`ISEQP`), in case of ffi metamethod is called and creates some objects. And, obviously, at `ffi.new()` call.

**Comment by sergos** [comment]
Regarding the initial question on array VS struct allocation: the trace referring to the loop in bench_ffi_new_object
```
---- TRACE 2 start pool2.lua:15
0005  UGET     4   1      ; ffi
0006  TGETS    4   4   0  ; "new"
0007  KSTR     6   1      ; "struct tt_uuid"
0008  CALL     4   2   2
0000  . FUNCC               ; ffi.new
---- TRACE 2 abort pool2.lua:16 -- NYI: unsupported C type conversion
```

unlike the same for array:
```
---- TRACE 2 start pool2.lua:22
0005  UGET     4   1      ; ffi
0006  TGETS    4   4   0  ; "new"
0007  KSTR     6   1      ; "struct tt_uuid[1]"
0008  CALL     4   2   2
0000  . FUNCC               ; ffi.new
0009  TGETB    5   4   0
0000  . . FUNCC               ; ffi.meta.__index
0010  TSETS    3   5   2  ; "time_low"
0000  . . FUNCC               ; ffi.meta.__newindex
```

NYI happens at lj_crecord.c:1040, considering only numeric, enums and pointers as valid for initialization. Although for variable length arrays/structs  there is a 'special' case at line 990. I wonder if we can just reuse it for the case of struct?

**Comment by sergos** [comment]
With a trivial change
```
diff --git a/src/lj_crecord.c b/src/lj_crecord.c
index e32ae23e..b5babb53 100644
--- a/src/lj_crecord.c
+++ b/src/lj_crecord.c
@@ -1037,7 +1037,8 @@ static void crec_alloc(jit_State *J, RecordFFData *rd, CTypeID id)
          dc = ctype_rawchild(cts, df);  /* Field type. */
          if (!(ctype_isnum(dc->info) || ctype_isptr(dc->info) ||
                ctype_isenum(dc->info)))
-           lj_trace_err(J, LJ_TRERR_NYICONV);  /* NYI: init aggregates. */
+           goto special;
+           //lj_trace_err(J, LJ_TRERR_NYICONV);  /* NYI: init aggregates. */
          if (J->base[i]) {
            sp = J->base[i];
            sval = &rd->argv[i];
```
I got for both bench_ffi_uuid_object and bench_ffi_uuid_array tests 
```
Median value per iteration: 0.48 ns
```

**Comment by sergos** [comment]
Ticket in LuaJIT https://github.com/LuaJIT/LuaJIT/issues/672 to obtain Mike's feedback.

**Comment by olegrok** [comment]
> Ticket in LuaJIT [LuaJIT/LuaJIT#672](https://github.com/LuaJIT/LuaJIT/issues/672) to obtain Mike's feedback.

Seems we should cherry-pick this patch https://github.com/LuaJIT/LuaJIT/commit/ad65934fa08a65bfb0eb9528731a4394842cc173

**Comment by Buristan** [comment]
The issue is resolved in scope of https://github.com/tarantool/luajit/commit/ba8313c9.
The submodule was updated in tarantool in 2.11.0-entrypoint-169-gd1d3d93ae (d1d3d93), 2.10.0-62-g54d798043 (54d7980), 1.10.13-27-geda8a1c36 (eda8a1c).

The results of the original benchmark on master branch (Release build) on my laptop:

Array:
```
$ src/tarantool /tmp/t.lua
Median value per iteration: 1.20459 ns
```
Struct:
```
$ src/tarantool /tmp/t.lua
Median value per iteration: 0.67138 ns
```

So, as we can see, `ffi.new('struct tt_uuid')` is even faster now.
