### ISSUE TITLE
Build fails on aligned_alloc not defined

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#5888]
```
tarantool/src/box/relay.cc:207:3: error: use of undeclared identifier 'aligned_alloc'
                aligned_alloc(alignof(struct relay), sizeof(struct relay));
```
I get it on the master branch since https://github.com/tarantool/tarantool/commit/2b748d7e1f59f279b436294402d63ff130f02c4f.

**Comment by Gerold103** [comment]
It appears the function is available in C++ since C++17 https://en.cppreference.com/w/cpp/memory/c/aligned_alloc. But available in C earlier, so this stupid patch helped:
```Diff
diff --git a/src/box/relay.cc b/src/box/relay.cc
index 41f949e8e..b8f0a263e 100644
--- a/src/box/relay.cc
+++ b/src/box/relay.cc
@@ -30,6 +30,8 @@
  */
 #include "relay.h"
 
+#include <cstdlib>
+
 #include "trivia/config.h"
 #include "tt_static.h"
 #include "scoped_guard.h"
@@ -202,7 +204,7 @@ relay_new(struct replica *replica)
 	 */
 	assert((sizeof(struct relay) % alignof(struct relay)) == 0);
 	struct relay *relay = (struct relay *)
-		aligned_alloc(alignof(struct relay), sizeof(struct relay));
+		tt_aligned_alloc(alignof(struct relay), sizeof(struct relay));
 	if (relay == NULL) {
 		diag_set(OutOfMemory, sizeof(struct relay), "aligned_alloc",
 			  "struct relay");
diff --git a/src/lib/core/util.c b/src/lib/core/util.c
index f29886105..3fd3f8a45 100644
--- a/src/lib/core/util.c
+++ b/src/lib/core/util.c
@@ -48,6 +48,12 @@
 
 #include "say.h"
 
+void *
+tt_aligned_alloc(size_t alignment, size_t size)
+{
+	return aligned_alloc(alignment, size);
+}
+
 /** Find a string in an array of strings.
  *
  * @param haystack  Array of strings. Either NULL
diff --git a/src/trivia/util.h b/src/trivia/util.h
index 899e1eb7d..42e8279d8 100644
--- a/src/trivia/util.h
+++ b/src/trivia/util.h
@@ -466,6 +466,9 @@ size_t
 strlcpy(char *dst, const char *src, size_t size);
 #endif
 
+void *
+tt_aligned_alloc(size_t alignment, size_t size);
+
 /**
  * Check that @a str is valid utf-8 sequence and can be printed
  * unescaped.
```
Related discussion https://github.com/MRPT/mrpt/issues/803.

**Comment by Gerold103** [comment]
It stopped failing after I upgraded XCode and Command Line Tools though.

**Comment by Gerold103** [comment]
I think it was rather my fault to use an outdated standard library. In case it repeats on any Mac: you need to update XCode via AppStore. Then launch it one time - it will install more shit. Then run `xcode-select --install`. Then run `brew upgrade`. Then restart your terminal. You also need to delete all the CMake cache files, all of them, not just one.

**Comment by tsafin** [comment]
We may use approach similar to FoundationDB using cmake checks for existence at the compile-time https://github.com/mpilman/foundationdb/commit/12106d42bea3f634addb22b12fa22326ffecd0fe

But, actually, if we look into possible way to work-around it, we see that we actually would proxy `aligned_alloc` to `posix_memalign` and it's simply easier to use it directly from any C or C++ context.

**Comment by Totktonada** [comment]
It seems, https://github.com/tarantool/tarantool/pull/5919 should fix the root of the problem.
