### ISSUE TITLE
Segmentation fault with mvcc

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#5892]
I have Ubuntu 20.04
I have Tarantool 2.7, pulled from source today.
I make two empty directories ~/tarantool_sandbox and ~/tarantool_sandbox_2.
I start two shells which I will call Connection #1 and Connection #2.

# On Connection #1
cd ~/tarantool_sandbox
rm *snap
rm *xlog
~/tarantool-2.7/src/tarantool
box.cfg{listen=3302, memtx_use_mvcc_engine=true}
box.schema.user.passwd('admin')
box.execute([[CREATE TABLE u (column1 INT PRIMARY KEY, column2 INT);]])
box.execute([[INSERT INTO u VALUES (1, 20);]])
box.execute([[START TRANSACTION;]])
box.execute([[SELECT * FROM u;]])

# On Connection #2
cd ~/tarantool_sandbox_2
rm *xlog
rm *snap
~/tarantool-2.7/src/tarantool
net_box = require('net.box')
conn = net_box.connect('admin:admin@127.0.0.1:3302')
conn:execute([[UPDATE u SET column2 = 21;]])

# On Connection #1
box.execute([[UPDATE u SET column2 = 22;]])

# Result
tarantool> box.execute([[UPDATE u SET column2 = 22;]]
         > )
Segmentation fault
  code: SEGV_MAPERR
  addr: 0x8
  context: 0x7feafe5fe840
  siginfo: 0x7feafe5fe970
  rax      0x0                0
  rbx      0x41164538         1091978552
  rcx      0x1                1
  rdx      0x7feafe5feea0     140647266774688
  rsi      0x7feafe419038     140647264784440
  rdi      0x7feafe41f280     140647264809600
  rsp      0x7feafe5fee00     140647266774528
  rbp      0x7feafe5fee50     140647266774608
  r8       0x7feafe5fee37     140647266774583
  r9       0x7feafe419040     140647264784448
  r10      0x0                0
  r11      0x7                7
  r12      0x55ae5ce23b66     94207371000678
  r13      0x0                0
  r14      0x41165080         1091981440
  r15      0x55ae5cd3615b     94207370027355
  rip      0x55ae5cc297ce     94207368927182
  eflags   0x10202            66050
  cs       0x33               51
  gs       0x0                0
  fs       0x0                0
  cr2      0x8                8
  err      0x4                4
  oldmask  0x0                0
  trapno   0xe                14
Current time: 1615756687
Please file a bug at http://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed, 
this may fail as well
#0  0x55ae5ce1dece in crash_collect+c6
#1  0x55ae5ce1fec5 in crash_signal_cb+55
#2  0x7feb00f783c0 in funlockfile+60
#3  0x55ae5cc297ce in memtx_tx_story_find_visible_tuple+17c
#4  0x55ae5cc299c4 in memtx_tx_history_add_stmt+1c5
#5  0x55ae5cd4afb9 in memtx_space_replace_all_keys+114
#6  0x55ae5cd4b60e in memtx_space_execute_update+22a
#7  0x55ae5cc2f5b7 in space_execute_dml+15d
#8  0x55ae5cc5b3ff in box_process_rw+10f
#9  0x55ae5cc6088f in box_process1+173
#10 0x55ae5cc60f2f in box_update+c8
#11 0x55ae5ccf16ee in sqlVdbeExec+a0dc
#12 0x55ae5ccf5340 in sqlStep+19f
#13 0x55ae5ccf53eb in sql_step+4a
#14 0x55ae5cdc2517 in sql_execute+b5
#15 0x55ae5cdc2914 in sql_prepare_and_execute+d9
#16 0x55ae5cd3629a in lbox_execute+13f
#17 0x55ae5cec0b4f in lj_BC_FUNCC+34
#18 0x55ae5ce80c98 in lua_pcall+336
#19 0x55ae5ce0270d in luaT_call+2d
#20 0x55ae5cdf91f4 in lua_main+bd
#21 0x55ae5cdf9832 in run_script_f+625
#22 0x55ae5cc1e8a1 in _ZL16fiber_cxx_invokePFiP13__va_list_tagES0_+22
#23 0x55ae5ce27b48 in fiber_loop+86
#24 0xAborted (core dumped)

**Comment by alyapunov** [comment]
Fixed in #6131
