### ISSUE TITLE
Add fiber-friendly ZeroMQ client library to rocks

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#591]
Add a zero-mq client library based on non-blocking I/O to rocks. See also https://github.com/tarantool/tarantool/issues/1091 for server-side support of amqp protocol.

**Comment by Totktonada** [comment]
@bigbes Done in https://github.com/tarantool/tarantool-zmq ?

(Also filed https://github.com/tarantool/rocks/issues/52 )
