### ISSUE TITLE
Build using MacOS SDK 10.15 (Catalina) on macos-10.15 runners

### ISSUE THREAD

**Issue by tsafin** [tarantool/tarantool#5920]
As a follow-up to #5888 we have discovered that there is no way (currently) to diagnose Catalina breakage, because we use BigSur sdk 11.00 even if we are building on Catalina (macos-10.15) runner.

We should enforce sdk 10.15 on macos-10.15, and sdk 11.00 on macos-latest.

**Comment by kyukhin** [comment]
We do not support 10.15 anymore.
