### ISSUE TITLE
String params are cropped on '\0' when passed to an SQL function

### ISSUE THREAD

**Issue by msiomkin** [tarantool/tarantool#5938]
* OS: CentOS Linux release 8.0.1905
* Architecture: Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz

```
[vagrant@localhost pems]$ tarantool --version
Tarantool Enterprise 2.7.1-0-g3ac498c9f-r380
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/__w/sdk/sdk/build.sdk/tarantool-2.7/static-build/tarantool-prefix -DENABLE_BACKTRACE=TRUE
Compiler: /usr/bin/cc /usr/bin/c++
C_FLAGS: -static-libstdc++ -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type
CXX_FLAGS: -static-libstdc++ -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type
```

**Steps to reproduce**

Create a C-function and save it to 'check_str.c':

```C
#include "module.h"
#include <msgpuck.h>

int pm_make_str_result(box_function_ctx_t* ctx, const char* result, uint32_t len)
{
    char* res_buf = (char*)malloc(len * sizeof(char) + 2);
    char* res_end = res_buf;
    res_end = mp_encode_array(res_end, 1);
    res_end = mp_encode_str(res_end, result, len);

    struct tuple* res = box_tuple_new(box_tuple_format_default(),
        res_buf, res_end);

    free(res_buf);

    return box_return_tuple(ctx, res);
}

int pm_check_str(box_function_ctx_t* ctx, const char* args, const char* args_end)
{
    mp_decode_array(&args);

    const char* str;
    uint32_t str_n;
    str = mp_decode_str(&args, &str_n);

    say_info("Param length: %d", str_n);
    say_info("Param value: %.*s", str_n, str);

    return pm_make_str_result(ctx, str, str_n);
}
```

Compile it:

```
[ -d "msgpuck" ] || git clone https://github.com/tarantool/msgpuck.git
cd msgpuck && cmake .
$(MAKE) -C msgpuck
gcc -shared -o cfn.so -fPIC \
    -I$TARANTOOL_INCLUDE \
    -Imsgpuck \
    *.c msgpuck/libmsgpuck.a
```

Launch tarantool and create a test space:

```
box.cfg{}

box.schema.create_space('my_space', { if_not_exists = true })

box.space.my_space:format({{ name = "id", type = "number" }, { name = "value", type = "string" }})

box.space.my_space:create_index("primary", { if_not_exists = true })

box.space.my_space:insert({1, "This is a complete string."})
box.space.my_space:insert({2, "This is a cropped\0 string."})
```

Create the stored function:
```
box.schema.func.drop("cfn.pm_check_str", { if_exists = true })
box.schema.func.create("cfn.pm_check_str", {
    language = "C",
    param_list = { "string" },
    returns = "string",
    exports = { "LUA", "SQL" },
    is_deterministic = true
})
box.schema.role.grant("public", "execute", "function", "cfn.pm_check_str")
```

Now execute a query:

```
box.execute([[select "value", "cfn.pm_check_str"("value") from "my_space"]])
```

**Actual behavior**

```
tarantool> box.execute([[select "value", "cfn.pm_check_str"("value") from "my_space"]])
2021-03-08 03:58:11.735 [7358] main/103/init.lua I> Param length: 26
2021-03-08 03:58:11.735 [7358] main/103/init.lua I> Param value: This is a complete string.
2021-03-08 03:58:11.735 [7358] main/103/init.lua I> Param length: 17
2021-03-08 03:58:11.735 [7358] main/103/init.lua I> Param value: This is a cropped
---
- metadata:
  - name: value
    type: string
  - name: COLUMN_1
    type: string
  rows:
  - ['This is a complete string.', 'This is a complete string.']
  - ["This is a cropped\0 string.", 'This is a cropped']
...
```

**Expected behavior**

```
tarantool> box.execute([[select "value", "cfn.pm_check_str"("value") from "my_space"]])
2021-03-08 03:56:24.841 [7115] main/103/init.lua I> Param length: 26
2021-03-08 03:56:24.841 [7115] main/103/init.lua I> Param value: This is a complete string.
2021-03-08 03:56:24.841 [7115] main/103/init.lua I> Param length: 26
2021-03-08 03:56:24.841 [7115] main/103/init.lua I> Param value: This is a cropped
---
- metadata:
  - name: value
    type: string
  - name: COLUMN_1
    type: string
  rows:
  - ['This is a complete string.', 'This is a complete string.']
  - ["This is a cropped\0 string.", "This is a cropped\0 string."]
...
```

Meanwhile, this works fine:

```
tarantool> sql_res = box.execute([[select "value" from "my_space" where "id" = 2]])
---
...

tarantool> sql_res
---
- metadata:
  - name: value
    type: string
  rows:
  - ["This is a cropped\0 string."]
...

tarantool> box.func["cfn.pm_check_str"]:call({sql_res.rows[1][1]})[1]
2021-03-08 13:02:36.787 [16274] main/103/init.lua I> Param length: 26
2021-03-08 13:02:36.787 [16274] main/103/init.lua I> Param value: This is a cropped
---
- "This is a cropped\0 string."
...
```

And even this works:
```
tarantool> box.execute([[select upper("value") from "my_space" where "id" = 2]])
---
- metadata:
  - name: COLUMN_1
    type: string
  rows:
  - ["THIS IS A CROPPED\0 STRING."]
...
```

P.S. the same cropping happens in custom Lua SQL-functions

**Comment by tsafin** [comment]
Relates to [TNT-99](https://jira.mail.ru/browse/TNT-99)

**Comment by tsafin** [comment]
Current workaround by @ImeevMA is in 9da943c7e6c0d9da95cce83f705869c1f9db5690

**Comment by sergos** [comment]
VARBINARY values are any sequence of zero or more octets (bytes), or NULL. VARBINARY literal values are expressed as X followed by pairs of hexadecimal digits enclosed within single quotes, for example X'0044'. VARBINARY’s NoSQL equivalent is 'varbinary' but **not character string** – the MessagePack storage is MP_BIN (MsgPack binary).

**Comment by msiomkin** [comment]
And what of it?

**Comment by sergos** [comment]
I would recommend to use it instead of STRING. There are recommendations from SQLite itself: https://sqlite.org/nulinstr.html and - at least discussions in support forums - for other DBMS, such as Oracle https://forums.toadworld.com/t/chr-0-null-string-issue/10062/5

To say 'use of CHR(0) in STRING is not forbidden by language standard' is not an indulgence to use it. It simply not well-defined, and so implementation-dependent. If you look for a robust solution - use specifically intended type for the data.

I believe we should follow the opposite way: update Tarantool documentation with explicit mention of undefined behavior in case of CHR(0) in STRING.

**Comment by msiomkin** [comment]
@sergos, C-functions don't support VARBINARY (and many more types/things). STRING - is the only complex type they can return. There's an obvious bug in code: careless and reasonless cropping a string when passing it to MessagePack. Why not fix it right now? There's no reason why we can't support '\0' in strings. There's just a **bug**. Why create artificial restrictions without any necessity?

**Comment by ImeevMA** [comment]
So, in the end, we have two ways to solve the problem: allow \0 in our STRING, or disallow it. Both options will solve our problem. In the second case, we cannot insert \0 into the STRING field.

However, I find it easier to solve this problem with the first option. Also, I believe this should be done for consistency of the code even in the second case, since we have no reason to look at the string when converting from MEM to msgpack. I believe there is a contract that says that if a string is in MEM, it can be put in msgpack and vice versa.

**Comment by tsafin** [comment]
In general I'd suggest to use `varbinary` wherever we need to pass blob (and binary uuid is a blob of 16 bytes length), this would be idiomatic SQL solution. But..

OTOH, there is no point to work with span view of string data (passed as pointer and length) as ASCIIZ, calculating length once again, instead of passing length we have received somehwere (i.e. instead of `mpstream_encode_str(&stream, str);` we could simply call `mpstream_encode_strn(&stream, str, param->n);`).

This will be faster a bit, and (coincidentally) fix our problem for the case whet string is processed as blob.

See no much reason to object this coincidental fix here :)

**Comment by msiomkin** [comment]
Disallowing \0 creates an ungrounded artificial restriction. And it doesn't solve my problem, because  at the current immature stage varbinary is not supported by custom SQL-functions and strings are the only possible workaround. This workaround is documented and it works! Except for this case. I suggest we shouldn't shut off oxygen.

https://www.tarantool.io/en/doc/latest/reference/reference_sql/sql_user_guide/

**Everything** is allowed:

> Byte sequences which are not valid UTF-8 characters are allowed

**Comment by ImeevMA** [comment]
After discussion with @msiomkin we found that:
1) Currently SQL cannot work with functions that returns VARBINARY.
2) We could'n find proper way to convert STRING to VARBINARY. I think it is possible using built-in HEX function, but this is quite complicated way.

However, we found that we could fix issue with returning VARBINARY from functions with this diff:
```
diff --git a/src/box/sql/func.c b/src/box/sql/func.c
index f15d27051..2f194c3ce 100644
--- a/src/box/sql/func.c
+++ b/src/box/sql/func.c
@@ -362,6 +362,12 @@ port_c_get_vdbemem(struct port *base, uint32_t *size)
 		case MP_NIL:
 			sqlVdbeMemSetNull(&val[i]);
 			break;
+		case MP_BIN:
+			str = mp_decode_bin(&data, &len);
+			if (sqlVdbeMemSetStr(&val[i], str, len,
+					     0, SQL_TRANSIENT) != 0)
+				goto error;
+			break;
 		default:
 			diag_set(ClientError, ER_SQL_EXECUTE,
 				 "Unsupported type passed from C");
```

So, if we apply this diff, than we have some way to convert STRING to binary and work with binary. Example below.

Let's compile this functions using method described in the issue:

```
#include "module.h"
#include <msgpuck.h>

int pm_make_str_result(box_function_ctx_t* ctx, const char* result, uint32_t len)
{
    char* res_buf = (char*)malloc(len * sizeof(char) + 2);
    char* res_end = res_buf;
    res_end = mp_encode_array(res_end, 1);
    res_end = mp_encode_str(res_end, result, len);

    struct tuple* res = box_tuple_new(box_tuple_format_default(),
        res_buf, res_end);

    free(res_buf);

    return box_return_tuple(ctx, res);
}

int pm_make_bin_result(box_function_ctx_t* ctx, const char* result, uint32_t len)
{
    char* res_buf = (char*)malloc(len * sizeof(char) + 1024);
    char* res_end = res_buf;
    res_end = mp_encode_array(res_end, 1);
    res_end = mp_encode_bin(res_end, result, len);

    struct tuple* res = box_tuple_new(box_tuple_format_default(),
        res_buf, res_end);

    free(res_buf);

    return box_return_tuple(ctx, res);
}

int pm_check_var(box_function_ctx_t* ctx, const char* args, const char* args_end)
{
    mp_decode_array(&args);

    const char* str;
    uint32_t str_n;
    str = mp_decode_bin(&args, &str_n);

    say_info("Param length: %d", str_n);
    say_info("Param value: %.*s", str_n, str);

    return pm_make_str_result(ctx, str, str_n);
}

int pm_convert(box_function_ctx_t* ctx, const char* args, const char* args_end)
{
    mp_decode_array(&args);

    const char* str;
    uint32_t str_n;
    str = mp_decode_str(&args, &str_n);

    say_info("Param length: %d", str_n);
    say_info("Param value: %.*s", str_n, str);

    return pm_make_bin_result(ctx, str, str_n);
}
```

Than we should create these functions in Lua:

```
box.schema.func.create("cfn.pm_check_var", {
    language = "C",
    param_list = { "varbinary" },
    returns = "string",
    exports = { "LUA", "SQL" },
    is_deterministic = true
})
box.schema.func.create("cfn.pm_convert", {
    language = "C",
    param_list = { "string" },
    returns = "varbinary",
    exports = { "LUA", "SQL" },
    is_deterministic = true
})
```

And then we can convert STRING to BINARY:
```
tarantool> box.execute([[select "cfn.pm_convert"('This is a complete string.')]])
2021-03-25 19:31:29.556 [126829] main/103/interactive I> Param length: 26
2021-03-25 19:31:29.556 [126829] main/103/interactive I> Param value: This is a complete string.
---
- metadata:
  - name: COLUMN_1
    type: varbinary
  rows:
  - ['This is a complete string.']
...

tarantool> box.execute([[select "cfn.pm_convert"('This is a cropped\0 string.')]])
2021-03-25 19:31:52.308 [126829] main/103/interactive I> Param length: 27
2021-03-25 19:31:52.308 [126829] main/103/interactive I> Param value: This is a cropped\0 string.
---
- metadata:
  - name: COLUMN_1
    type: varbinary
  rows:
  - ['This is a cropped\0 string.']
...
```

So, at the end, we can call our length-checking function:
```
box.execute('create table t1(i int primary key autoincrement, v varbinary);')
box.execute([[insert into t1(v) select "cfn.pm_convert"('This is a complete string.')]])
box.execute([[insert into t1(v) select "cfn.pm_convert"('This is a cropped\0 string.')]])
box.execute([[select "cfn.pm_check_var"(v) from t1;]])
```

Result:
```
tarantool> box.execute([[select "cfn.pm_check_var"(v) from t1;]])
2021-03-25 19:36:47.914 [126829] main/103/interactive I> Param length: 26
2021-03-25 19:36:47.914 [126829] main/103/interactive I> Param value: This is a complete string.
2021-03-25 19:36:47.914 [126829] main/103/interactive I> Param length: 27
2021-03-25 19:36:47.914 [126829] main/103/interactive I> Param value: This is a cropped\0 string.
---
- metadata:
  - name: COLUMN_1
    type: string
  rows:
  - ['This is a complete string.']
  - ['This is a cropped\0 string.']
...
```

Hope this will give us some way to solve the issue. What do you think? @Mons @tsafin @kyukhin @sergos

**Comment by msiomkin** [comment]
The latter @ImeevMA's solution suits me fine. But I think we really should apply both patches. The first patch will definitely do no harm (in fact it'll fix a 100% obvious bug).

**Comment by sergos** [comment]
I won't disagree we should resolve the inconsistency and the https://github.com/tarantool/tarantool/commit/9da943c7e6c0d9da95cce83f705869c1f9db5690 is a good one.
Although, the use of textual type may incur even more problems in other places (see https://github.com/tarantool/tarantool/issues/5938#issuecomment-806538370), where `STRING` can be treated in the form of `char *` and to my personal understanding the `VARBINARY` type exists exactly to avoid problems.

I totally support the need of better `VARBINARY` support in Tarantool SQL and a more detailed explanation in the documentation about selection of `STRING` versus `VARBINARY` depending on the expected use.

**Comment by msiomkin** [comment]
> even more problems in other places

I don't see any _serious_ problems.

1. `length` function is not a problem. It's clear there may be artefacts when it's applied to binary content. Let it be.

2. If we count for "lazy" developers, we should _always_ use _only_ null terminated strings in C/C++. Nobody does so.

> Now the “lazy” developer could just copy the data from the buffer
without considering the length and potentially truncate the result at
the first chr(0) - possibly using strcpy() which terminates after
copying the chr(0).

> However, if the developer considers the length of the returned data and
copies that many bytes then chr(0) will also be copied. Using memcpy()
or memmove() for example, copies a given number of bytes regardless of
any chr(0) in their midst.
