### ISSUE TITLE
Public fk_constraints LUA API

### ISSUE THREAD

**Issue by no1seman** [tarantool/tarantool#5943]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when calling box.execute to get fk-constraints that is used under the hood in SQL engine to get spaces relations.

**Describe the solution you'd like**

Wanna get public LUA API for manipulating fk-constraints: getters, setters and also docs with full description.

**Describe alternatives you've considered**

box.execute 

**Additional context**

fk_constraints - is one the ways to describe relations between tables (spaces in Tarantool terminology), but not only SQL uses it, but also: Avro, GraphQL and so on have similar mechanisms to describe relations between entyties. It's quite strange that I can create foreing key in SQL and can't use it for example in GraphQL and vice versa.

**Definition of Done**

Make DDL with SQL and then get the same Avro or GraphQL models with relations between spaces and vice versa without any kind of tricks with box.execute.

**Comment by alyapunov** [comment]
It seems that it's done in #6436.

**Comment by kyukhin** [comment]
> #6436

I guess so.
