### ISSUE TITLE
Remove enum field_type from struct Mem

### ISSUE THREAD

**Issue by ImeevMA** [tarantool/tarantool#5957]
When this field was added, it was used for two purposes:
1) Remove unnecessary double to integer implicit cast.
2) Allow typeof() to determine column type.

Since there is no problem with double to integer conversation and vice versa from the moment field type DOUBLE was added, the only case this field is used is to determine column type. However, in case we resolve #5956, this case may also be deprecated.

**Comment by kostja** [comment]
I think instead of removing enum field_type, you should make it the discriminator of the union, i.e. remove everything else (all other sqlite legacy)

**Comment by ImeevMA** [comment]
@kostja Ok. Let's say we removed MEM_type (which is analogue of MP_type in BOX) from MEM. What should a SELECT return in the code below?
```
CREATE TABLE t0 (n NUMBER PRIMARY KEY);
INSERT INTO t0 VALUES(-1123.12);
SELECT n FROM t0;
```

There is three options (according to field type NUMBER): mem->u.d == -1123.120000, mem->u.i == -4570717687410872812 and mem->u.u == 13876026386298678804.

I think mem is, in a sense, analogous to the field of msgpack in BOX. So, in my opinion, it is quite logical and convenient to use MEM_type instead of field_type everywhere. Second type-defining system only creates unnecessary confusion.

**Comment by ImeevMA** [comment]
Closed by https://github.com/tarantool/tarantool/commit/35e36b921dc92a6e9f304a5edb921537db925762
