### ISSUE TITLE
C functions module reloading is not restoring functions properly

### ISSUE THREAD

**Issue by cyrillos** [tarantool/tarantool#5968]
In the commit 96938fafb restore of old functions is simply broken. I made a test which makes tarantool to crash. Actually the code is highly bounded to my series in #4642 thus need to fix it in the scope to not double efforts.

**Comment by Gerold103** [comment]
You should fix it separately (before 4642 commits) at least to be able to cherry-pick it to 1.10.

**Comment by cyrillos** [comment]
> You should fix it separately (before 4642 commits) at least to be able to cherry-pick it to 1.10.

Sure but my #4642 depends on it as I already mentioned. So I fix it in scope of the #4642 bug but as separate commit.

**Comment by Gerold103** [comment]
It must be pushed to all the supported branches, because it is a bugfix.

**Comment by cyrillos** [comment]
@kyukhin for 2.7 series `gorcunov/gh-5968-func-restore-2.7`, 2.8 already has the fix. For 1.10 series I had to rewrite tests, pushed into `gorcunov/gh-5968-func-restore-1.10`. Lets wait the tests to pass.
