### ISSUE TITLE
Can create many spaces with the same name during a transaction

### ISSUE THREAD

**Issue by artur-barsegyan** [tarantool/tarantool#5981]
**Bug description**

Can create many spaces with the same name during a transaction without any errors. But I couldn't create an index for doubled space. 

After that if I will create an index for space `test` I'll get the error: _"Space 'test' does not exist"_.

* OS: Docker (in MacOS)
* OS Version: MacOS 11.0.1
* Architecture: amd64

Tarantool 2.7.1-0-g3ac498c9f
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_BACKTRACE=ON
Compiler: /usr/bin/cc /usr/bin/c++
C_FLAGS: -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type
CXX_FLAGS: -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type

**Steps to reproduce**

```
tarantool> box.cfg{}
---
...

tarantool> box.begin()
---
...

tarantool> box.schema.create_space('test')
---
- engine: memtx
  before_replace: 'function: 0x01032e1158'
  field_count: 0
  is_sync: false
  ck_constraint: []
  on_replace: 'function: 0x01032e1120'
  temporary: false
  index: []
  is_local: false
  enabled: false
  name: test
  id: 512
- created
...

tarantool> t = box.schema.create_space('test')
---
...

tarantool> t
---
- engine: memtx
  before_replace: 'function: 0x01032e2a88'
  field_count: 0
  is_sync: false
  ck_constraint: []
  on_replace: 'function: 0x01032e2a50'
  temporary: false
  index: []
  is_local: false
  enabled: false
  name: test
  id: 512
...

tarantool> box.space
---
- []
...

tarantool> t:create_index('pk')
---
- error: Space 'test' does not exist
...
```

How to run:

Just type commands in clean Tarantool instance.

**Expected behavior**

In a transaction where I created the space, I should get the error in case creating another space with the same name.

**Comment by olegrok** [comment]
> In a transaction where I created the space, I should get the error in case creating another space with the same name.

Try to commit your transaction - you will get an error.

You violated the rule "don't yield during transaction". So your transaction was marked as "bad" and implicitly rollbacked.

**Comment by kyukhin** [comment]
No response for months.
