### ISSUE TITLE
Update in memtx hides NOT_FOUND error

### ISSUE THREAD

**Issue by alyapunov** [tarantool/tarantool#5982]
I've checked 1.10 and the latest - all versions are affected.

If update founds no tuple by given key it silently does nothing. It seems to be a bug, but I'm not sure.

<details>
<summary>Example</summary>

```lua
tarantool> s = box.schema.space.create('test')
---
...
tarantool> i = s:create_index('test')
---
...
tarantool> s:update({1}, {{'=', 1, 2}})
---
...
```
</details>

**Comment by orchaton** [comment]
@alyapunov 
Same with delete!
Moreover, it is writes transaction down to WAL. I'm not sure is it correct behaviour.
