### ISSUE TITLE
Brew install Apple M1 chip error

### ISSUE THREAD

**Issue by yuriysergeev** [tarantool/tarantool#5983]
**Bug description**
Tarantool doesn't install from 'brew install tarantool' or 'brew install --build-from-source tarantool' on Apple M1
* OS: macOS 
* OS Version: Darwin Kernel Version 20.3.0
* Architecture: arm64

**Steps to reproduce**

Run two ways tarantool installations via homebrew:

1. Type 'brew install tarantool' in console: 
`Installing tarantool --HEAD
==> cmake . -DCMAKE_INSTALL_MANDIR=/opt/homebrew/Cellar/tarantool/HEAD-b88df4d_1/share/doc/tarantool -DCMAKE_INSTALL_S
==> make
Last 15 lines from /Users/ys/Library/Logs/Homebrew/tarantool/02.make:
[  3%] Building C object CMakeFiles/zstd.dir/third_party/zstd/lib/compress/hist.c.o
/opt/homebrew/Library/Homebrew/shims/mac/super/clang -DCORO_ASM -DLUAJIT_ENABLE_GC64 -DLUAJIT_SMART_STRINGS=1 -DNDEBUG -DNVALGRIND -DNVALGRIND=1 -I/tmp/tarantool-20210412-4657-mn4aln/src -I/tmp/tarantool-20210412-4657-mn4aln/src/lib -I/tmp/tarantool-20210412-4657-mn4aln/src/lib/small -I/tmp/tarantool-20210412-4657-mn4aln/src/lib/small/third_party -I/tmp/tarantool-20210412-4657-mn4aln/src/lib/core -I/tmp/tarantool-20210412-4657-mn4aln -I/tmp/tarantool-20210412-4657-mn4aln/third_party/zstd/lib -I/tmp/tarantool-20210412-4657-mn4aln/third_party/zstd/lib/common -I/tmp/tarantool-20210412-4657-mn4aln/third_party/luajit/src -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -DNDEBUG -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=11 -Ofast -MD -MT CMakeFiles/zstd.dir/third_party/zstd/lib/compress/hist.c.o -MF CMakeFiles/zstd.dir/third_party/zstd/lib/compress/hist.c.o.d -o CMakeFiles/zstd.dir/third_party/zstd/lib/compress/hist.c.o -c /tmp/tarantool-20210412-4657-mn4aln/third_party/zstd/lib/compress/hist.c
[  3%] Building C object CMakeFiles/zstd.dir/third_party/zstd/lib/compress/zstd_compress_superblock.c.o
/opt/homebrew/Library/Homebrew/shims/mac/super/clang -DCORO_ASM -DLUAJIT_ENABLE_GC64 -DLUAJIT_SMART_STRINGS=1 -DNDEBUG -DNVALGRIND -DNVALGRIND=1 -I/tmp/tarantool-20210412-4657-mn4aln/src -I/tmp/tarantool-20210412-4657-mn4aln/src/lib -I/tmp/tarantool-20210412-4657-mn4aln/src/lib/small -I/tmp/tarantool-20210412-4657-mn4aln/src/lib/small/third_party -I/tmp/tarantool-20210412-4657-mn4aln/src/lib/core -I/tmp/tarantool-20210412-4657-mn4aln -I/tmp/tarantool-20210412-4657-mn4aln/third_party/zstd/lib -I/tmp/tarantool-20210412-4657-mn4aln/third_party/zstd/lib/common -I/tmp/tarantool-20210412-4657-mn4aln/third_party/luajit/src -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -DNDEBUG -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=11 -Ofast -MD -MT CMakeFiles/zstd.dir/third_party/zstd/lib/compress/zstd_compress_superblock.c.o -MF CMakeFiles/zstd.dir/third_party/zstd/lib/compress/zstd_compress_superblock.c.o.d -o CMakeFiles/zstd.dir/third_party/zstd/lib/compress/zstd_compress_superblock.c.o -c /tmp/tarantool-20210412-4657-mn4aln/third_party/zstd/lib/compress/zstd_compress_superblock.c
[  3%] Building C object CMakeFiles/zstd.dir/third_party/zstd/lib/compress/zstd_compress_sequences.c.o
/opt/homebrew/Library/Homebrew/shims/mac/super/clang -DCORO_ASM -DLUAJIT_ENABLE_GC64 -DLUAJIT_SMART_STRINGS=1 -DNDEBUG -DNVALGRIND -DNVALGRIND=1 -I/tmp/tarantool-20210412-4657-mn4aln/src -I/tmp/tarantool-20210412-4657-mn4aln/src/lib -I/tmp/tarantool-20210412-4657-mn4aln/src/lib/small -I/tmp/tarantool-20210412-4657-mn4aln/src/lib/small/third_party -I/tmp/tarantool-20210412-4657-mn4aln/src/lib/core -I/tmp/tarantool-20210412-4657-mn4aln -I/tmp/tarantool-20210412-4657-mn4aln/third_party/zstd/lib -I/tmp/tarantool-20210412-4657-mn4aln/third_party/zstd/lib/common -I/tmp/tarantool-20210412-4657-mn4aln/third_party/luajit/src -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -DNDEBUG -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=11 -Ofast -MD -MT CMakeFiles/zstd.dir/third_party/zstd/lib/compress/zstd_compress_sequences.c.o -MF CMakeFiles/zstd.dir/third_party/zstd/lib/compress/zstd_compress_sequences.c.o.d -o CMakeFiles/zstd.dir/third_party/zstd/lib/compress/zstd_compress_sequences.c.o -c /tmp/tarantool-20210412-4657-mn4aln/third_party/zstd/lib/compress/zstd_compress_sequences.c
[  3%] Building C object CMakeFiles/zstd.dir/third_party/zstd/lib/compress/zstd_compress_literals.c.o
/opt/homebrew/Library/Homebrew/shims/mac/super/clang -DCORO_ASM -DLUAJIT_ENABLE_GC64 -DLUAJIT_SMART_STRINGS=1 -DNDEBUG -DNVALGRIND -DNVALGRIND=1 -I/tmp/tarantool-20210412-4657-mn4aln/src -I/tmp/tarantool-20210412-4657-mn4aln/src/lib -I/tmp/tarantool-20210412-4657-mn4aln/src/lib/small -I/tmp/tarantool-20210412-4657-mn4aln/src/lib/small/third_party -I/tmp/tarantool-20210412-4657-mn4aln/src/lib/core -I/tmp/tarantool-20210412-4657-mn4aln -I/tmp/tarantool-20210412-4657-mn4aln/third_party/zstd/lib -I/tmp/tarantool-20210412-4657-mn4aln/third_party/zstd/lib/common -I/tmp/tarantool-20210412-4657-mn4aln/third_party/luajit/src -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -DNDEBUG -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=11 -Ofast -MD -MT CMakeFiles/zstd.dir/third_party/zstd/lib/compress/zstd_compress_literals.c.o -MF CMakeFiles/zstd.dir/third_party/zstd/lib/compress/zstd_compress_literals.c.o.d -o CMakeFiles/zstd.dir/third_party/zstd/lib/compress/zstd_compress_literals.c.o -c /tmp/tarantool-20210412-4657-mn4aln/third_party/zstd/lib/compress/zstd_compress_literals.c
[  4%] Linking C static library libzstd.a
/opt/homebrew/Cellar/cmake/3.20.1/bin/cmake -P CMakeFiles/zstd.dir/cmake_clean_target.cmake
/opt/homebrew/Cellar/cmake/3.20.1/bin/cmake -E cmake_link_script CMakeFiles/zstd.dir/link.txt --verbose=1
/usr/bin/ar qc libzstd.a CMakeFiles/zstd.dir/third_party/zstd/lib/common/zstd_common.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/common/entropy_common.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/common/error_private.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/common/pool.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/common/xxhash.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/common/fse_decompress.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/common/debug.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/decompress/zstd_decompress.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/decompress/huf_decompress.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/decompress/zstd_ddict.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/decompress/zstd_decompress_block.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/compress/zstd_double_fast.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/compress/zstd_fast.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/compress/zstd_lazy.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/compress/zstd_opt.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/compress/zstd_compress.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/compress/zstd_ldm.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/compress/zstdmt_compress.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/compress/huf_compress.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/compress/fse_compress.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/compress/hist.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/compress/zstd_compress_superblock.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/compress/zstd_compress_sequences.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/compress/zstd_compress_literals.c.o
/usr/bin/ranlib libzstd.a
[  4%] Built target zstd
make: *** [all] Error 2`

2. Type ' brew install --build-from-source tarantool' in console:
`Downloading https://download.tarantool.org/tarantool/2.6/src/tarantool-2.6.2.0.tar.gz
==> Downloading from https://hb.bizmrg.com/tarantool_repo/sources/2.6/tarantool-2.6.2.0.tar.gz
######################################################################## 100.0%
==> cmake . -DCMAKE_INSTALL_MANDIR=/opt/homebrew/Cellar/tarantool/2.6.2.0_1/share/doc/tarantool -DCMAKE_INSTALL_SYSCONFDIR=/opt/homebrew/etc -DCMAKE_INSTALL_LOCALSTATEDIR=/opt/homebrew/var -DENABLE_DIST=ON -DOPENSSL_ROOT_DIR=/opt/homebrew
==> make
Last 15 lines from /Users/ys/Library/Logs/Homebrew/tarantool/02.make:
[  3%] Building C object CMakeFiles/zstd.dir/third_party/zstd/lib/compress/zstd_ldm.c.o
/opt/homebrew/Library/Homebrew/shims/mac/super/clang -DCORO_ASM -DLUAJIT_ENABLE_GC64=1 -DLUAJIT_SMART_STRINGS=1 -DNDEBUG -DNVALGRIND -DNVALGRIND=1 -I/tmp/tarantool-20210412-8381-16023gd/tarantool-2.6.2.0/src -I/tmp/tarantool-20210412-8381-16023gd/tarantool-2.6.2.0/src/lib -I/tmp/tarantool-20210412-8381-16023gd/tarantool-2.6.2.0/src/lib/small -I/tmp/tarantool-20210412-8381-16023gd/tarantool-2.6.2.0/src/lib/small/third_party -I/tmp/tarantool-20210412-8381-16023gd/tarantool-2.6.2.0/src/lib/core -I/tmp/tarantool-20210412-8381-16023gd/tarantool-2.6.2.0 -I/tmp/tarantool-20210412-8381-16023gd/tarantool-2.6.2.0/third_party/zstd/lib -I/tmp/tarantool-20210412-8381-16023gd/tarantool-2.6.2.0/third_party/zstd/lib/common -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -DNDEBUG -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=11 -Ofast -MD -MT CMakeFiles/zstd.dir/third_party/zstd/lib/compress/zstd_ldm.c.o -MF CMakeFiles/zstd.dir/third_party/zstd/lib/compress/zstd_ldm.c.o.d -o CMakeFiles/zstd.dir/third_party/zstd/lib/compress/zstd_ldm.c.o -c /tmp/tarantool-20210412-8381-16023gd/tarantool-2.6.2.0/third_party/zstd/lib/compress/zstd_ldm.c
[  3%] Building C object CMakeFiles/zstd.dir/third_party/zstd/lib/compress/zstdmt_compress.c.o
/opt/homebrew/Library/Homebrew/shims/mac/super/clang -DCORO_ASM -DLUAJIT_ENABLE_GC64=1 -DLUAJIT_SMART_STRINGS=1 -DNDEBUG -DNVALGRIND -DNVALGRIND=1 -I/tmp/tarantool-20210412-8381-16023gd/tarantool-2.6.2.0/src -I/tmp/tarantool-20210412-8381-16023gd/tarantool-2.6.2.0/src/lib -I/tmp/tarantool-20210412-8381-16023gd/tarantool-2.6.2.0/src/lib/small -I/tmp/tarantool-20210412-8381-16023gd/tarantool-2.6.2.0/src/lib/small/third_party -I/tmp/tarantool-20210412-8381-16023gd/tarantool-2.6.2.0/src/lib/core -I/tmp/tarantool-20210412-8381-16023gd/tarantool-2.6.2.0 -I/tmp/tarantool-20210412-8381-16023gd/tarantool-2.6.2.0/third_party/zstd/lib -I/tmp/tarantool-20210412-8381-16023gd/tarantool-2.6.2.0/third_party/zstd/lib/common -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -DNDEBUG -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=11 -Ofast -MD -MT CMakeFiles/zstd.dir/third_party/zstd/lib/compress/zstdmt_compress.c.o -MF CMakeFiles/zstd.dir/third_party/zstd/lib/compress/zstdmt_compress.c.o.d -o CMakeFiles/zstd.dir/third_party/zstd/lib/compress/zstdmt_compress.c.o -c /tmp/tarantool-20210412-8381-16023gd/tarantool-2.6.2.0/third_party/zstd/lib/compress/zstdmt_compress.c
[  3%] Building C object CMakeFiles/zstd.dir/third_party/zstd/lib/compress/huf_compress.c.o
/opt/homebrew/Library/Homebrew/shims/mac/super/clang -DCORO_ASM -DLUAJIT_ENABLE_GC64=1 -DLUAJIT_SMART_STRINGS=1 -DNDEBUG -DNVALGRIND -DNVALGRIND=1 -I/tmp/tarantool-20210412-8381-16023gd/tarantool-2.6.2.0/src -I/tmp/tarantool-20210412-8381-16023gd/tarantool-2.6.2.0/src/lib -I/tmp/tarantool-20210412-8381-16023gd/tarantool-2.6.2.0/src/lib/small -I/tmp/tarantool-20210412-8381-16023gd/tarantool-2.6.2.0/src/lib/small/third_party -I/tmp/tarantool-20210412-8381-16023gd/tarantool-2.6.2.0/src/lib/core -I/tmp/tarantool-20210412-8381-16023gd/tarantool-2.6.2.0 -I/tmp/tarantool-20210412-8381-16023gd/tarantool-2.6.2.0/third_party/zstd/lib -I/tmp/tarantool-20210412-8381-16023gd/tarantool-2.6.2.0/third_party/zstd/lib/common -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -DNDEBUG -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=11 -Ofast -MD -MT CMakeFiles/zstd.dir/third_party/zstd/lib/compress/huf_compress.c.o -MF CMakeFiles/zstd.dir/third_party/zstd/lib/compress/huf_compress.c.o.d -o CMakeFiles/zstd.dir/third_party/zstd/lib/compress/huf_compress.c.o -c /tmp/tarantool-20210412-8381-16023gd/tarantool-2.6.2.0/third_party/zstd/lib/compress/huf_compress.c
[  3%] Building C object CMakeFiles/zstd.dir/third_party/zstd/lib/compress/fse_compress.c.o
/opt/homebrew/Library/Homebrew/shims/mac/super/clang -DCORO_ASM -DLUAJIT_ENABLE_GC64=1 -DLUAJIT_SMART_STRINGS=1 -DNDEBUG -DNVALGRIND -DNVALGRIND=1 -I/tmp/tarantool-20210412-8381-16023gd/tarantool-2.6.2.0/src -I/tmp/tarantool-20210412-8381-16023gd/tarantool-2.6.2.0/src/lib -I/tmp/tarantool-20210412-8381-16023gd/tarantool-2.6.2.0/src/lib/small -I/tmp/tarantool-20210412-8381-16023gd/tarantool-2.6.2.0/src/lib/small/third_party -I/tmp/tarantool-20210412-8381-16023gd/tarantool-2.6.2.0/src/lib/core -I/tmp/tarantool-20210412-8381-16023gd/tarantool-2.6.2.0 -I/tmp/tarantool-20210412-8381-16023gd/tarantool-2.6.2.0/third_party/zstd/lib -I/tmp/tarantool-20210412-8381-16023gd/tarantool-2.6.2.0/third_party/zstd/lib/common -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -DNDEBUG -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=11 -Ofast -MD -MT CMakeFiles/zstd.dir/third_party/zstd/lib/compress/fse_compress.c.o -MF CMakeFiles/zstd.dir/third_party/zstd/lib/compress/fse_compress.c.o.d -o CMakeFiles/zstd.dir/third_party/zstd/lib/compress/fse_compress.c.o -c /tmp/tarantool-20210412-8381-16023gd/tarantool-2.6.2.0/third_party/zstd/lib/compress/fse_compress.c
[  4%] Linking C static library libzstd.a
/opt/homebrew/Cellar/cmake/3.20.1/bin/cmake -P CMakeFiles/zstd.dir/cmake_clean_target.cmake
/opt/homebrew/Cellar/cmake/3.20.1/bin/cmake -E cmake_link_script CMakeFiles/zstd.dir/link.txt --verbose=1
/usr/bin/ar qc libzstd.a CMakeFiles/zstd.dir/third_party/zstd/lib/common/zstd_common.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/common/entropy_common.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/common/error_private.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/common/pool.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/common/xxhash.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/common/fse_decompress.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/decompress/zstd_decompress.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/decompress/huf_decompress.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/compress/zstd_double_fast.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/compress/zstd_fast.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/compress/zstd_lazy.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/compress/zstd_opt.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/compress/zstd_compress.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/compress/zstd_ldm.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/compress/zstdmt_compress.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/compress/huf_compress.c.o CMakeFiles/zstd.dir/third_party/zstd/lib/compress/fse_compress.c.o
/usr/bin/ranlib libzstd.a
[  4%] Built target zstd
make: *** [all] Error 2`

**Comment by Totktonada** [comment]
Please, share full logs (including /Users/ys/Library/Logs/Homebrew/tarantool/02.make). The cited snippets do not contain an actual error.

I guess 2.6.2 error (the second case) may be related to the problem that was fixed in [2.6.2-97-g9d40779ef](https://github.com/tarantool/tarantool/commit/9d40779ef68a4ff6644c7f5058ddcf624e670906) (after the 2.6.2 release).

Don't know about the first one.

Anyway, there are known problems with LuaJIT on ARM64, so we'll not declare support of ARM64 until at least the following tasks will be resolved:

* https://github.com/tarantool/tarantool/issues/2712
* https://github.com/tarantool/tarantool/issues/5629
* https://github.com/tarantool/tarantool/issues/4473

**Comment by yuriysergeev** [comment]
Sure, all "make" files from the dir in attach:

[01.cmake.txt](https://github.com/tarantool/tarantool/files/6298831/01.cmake.txt)
[02.make.txt](https://github.com/tarantool/tarantool/files/6298832/02.make.txt)

**Comment by Totktonada** [comment]
The error:

```
<inline asm>:30:2: error: unknown directive
        .type coro_startup, %function
        ^
1 error generated.
```

The relevant source:

https://github.com/tarantool/tarantool/blob/aa97a18575a5fba29550e131c4764b81841612b9/third_party/coro/coro.c#L298-L302

It seems, it is our own code upward the original [libcoro](http://cvs.schmorp.de/libcoro/coro.c). It was added in [this commit](https://github.com/tarantool/tarantool/commit/98d994c30dc8e704c56224432a9c934e255e0438).

As I see, this optimization may be turned out on Apple's hardware this way (I didn't test it):

```diff
diff --git a/cmake/BuildLibCORO.cmake b/cmake/BuildLibCORO.cmake
index 3a9c95426..e4466c3c1 100644
--- a/cmake/BuildLibCORO.cmake
+++ b/cmake/BuildLibCORO.cmake
@@ -13,7 +13,9 @@ macro(libcoro_build)
     if (${CMAKE_SYSTEM_PROCESSOR} MATCHES "86" OR ${CMAKE_SYSTEM_PROCESSOR} MATCHES "amd64")
         add_definitions("-DCORO_ASM")
     elseif (${CMAKE_SYSTEM_PROCESSOR} MATCHES "arm" OR ${CMAKE_SYSTEM_PROCESSOR} MATCHES "aarch64")
-        add_definitions("-DCORO_ASM")
+        if (${CMAKE_SYSTEM_NAME} STREQUAL "Linux")
+            add_definitions("-DCORO_ASM")
+        endif()
     else()
         add_definitions("-DCORO_SJLJ")
     endif()
```

It is just workaround, maybe it'll be more reasonable to fix the assembler code (I'm not familiar with the ARM assembler, so I cannot say anything without investigation).

**Comment by Totktonada** [comment]
If we'll attempt to fix the assembly: https://stackoverflow.com/a/20908242/1598057

**Comment by igormunkin** [comment]
@yuriysergeev, Tarantool successfully builds on M1 since 2.9.0-33-g93e2ce52d (93e2ce5). You can use the bleeding Tarantool version via `brew install tarantool --HEAD`. I tried this now on my M1 laptop and get the following as a result:
```
$ brew install tarantool --HEAD
<snipped brew output>
$ tarantool
Tarantool 2.9.0-146-g9a6356808
type 'help' for interactive help
tarantool> jit.os
---
- OSX
...

tarantool> jit.arch
---
- arm64
...

tarantool> _TARANTOOL
---
- 2.9.0-146-g9a6356808
...

```

Hence, I am closing this ticket. However, I am warning you about several known but unresolved issues related to M1:
* #6059
* #6097
* #6098

Stay tuned!
