### ISSUE TITLE
Nested transactions

### ISSUE THREAD

**Issue by unera** [tarantool/tarantool#599]
It would be nice to have nested transactions.

Example You have a function that update user's properties

``` lua
function update_user(id, props)
    box.begin()
    box.space.user:update(id, { something(props) })
    box.space.role:update(id, { someother(props) })
    box.commit()
end
```

And then You want to add something and You have already
a lot of clients that uses `update_user()`, You write a wrapper:

``` lua
function xupdate_user(id, props)
    box.begin()
    box.space.friends:update(id, { something(props) })
    update_user(id, props)
    box.commit()
end
```

So here is You have nested transaction :)

**Comment by jonywtf** [comment]
i need the feature too...
Please implement it!

**Comment by R-omk** [comment]
Also feature:

```lua
handler1 = function()
 -- some
end

handler2 = function()
 -- some
end

box.begin()
  box.begin()
    box.on_commit(handler1)
  box.commit()
  box.on_commit(handler2)
box.commit()
--  invoke handler1 and handler2

```

on_commit invokes all handlers after zero level of nested transaction has been committed

**Comment by kostja** [comment]
We have implemented savepoints. It is now possible to do nested transactions with a bit of syntax sugar. I'm leaving it to the community to come up with a rock.
