### ISSUE TITLE
box: get rid of _schema.max_id

### ISSUE THREAD

**Issue by Korablev77** [tarantool/tarantool#5997]
The only purpose of this thing is to generate increasing space ids in `box.schema.create_space()` - it is neither transactional (max_id is increased before invocation of `on_replace_dd` trigger and in case creation of space fails, its value is not rolled back) nor safe (in case creation of space takes place via direct `box.space._space:replace()` - value of max_id is not changed; so in this case next call of `box.schema.create_space()` may fail due to duplicate space_id).
The suggestion is to replace _schema.max_id with `box.space._space.index[0]:max()[1]` or attached sequence.

**Comment by kostja** [comment]
If you use max() you'll break replication by creating a space with id of a dropped one.
Using an attached sequence should be fine.
