### ISSUE TITLE
create/alter space/index in transaction

### ISSUE THREAD

**Issue by unera** [tarantool/tarantool#600]
I want to create space and its indexes in one transaction (up/down)

for example my project is grown, so I want to upgrade database.
I write two scripts: `up.lua` and `down.lua`.

If `up.lua` raises an error it have to rollback all its works.
`down.lua` have to have the same behaviour

``` console
tarantool> box.begin()

---
...

tarantool> box.schema.create_space('test')

---
- error: Space _space does not support multi-statement transactions
...
```

**Comment by farwayer** [comment]
One more problem is `before_replace`/`on_replace` executes in transaction context. So It is not possible to create space inside handler :disappointed:

**Comment by alyapunov** [comment]
^^ closed by misclick and reopened.

**Comment by CuriousGeorgiy** [comment]
@alyapunov @mkostoevr

The [_Online schema evolution is (almost) free for snapshot databases_](https://www.vldb.org/pvldb/vol16/p140-hu.pdf) paper by Tianzheng Wang et al. may be a good reference.
