### ISSUE TITLE
Incorrect rollback with delete operation in MVCC 

### ISSUE THREAD

**Issue by artur-barsegyan** [tarantool/tarantool#6021]
**Bug description**

Here is a test of that bug:

```lua
box.cfg { memtx_use_mvcc_engine = true }

s = box.schema.create_space('test')
s:create_index('pk', {parts={{1, 'uint'}}})
s:create_index('sec', {parts={{2, 'uint'}}})

fiber = require("fiber")
s:insert({1, 0})

box.begin()
s:delete(1)

fiber.create(function()
    box.begin()
    s:replace({1,1})
    fiber.sleep(1)
    box.commit()
end)

fiber.sleep(1)
box.commit()
```

After that, I get strange errors and tarantool exits with the next messages:

> 2021-04-19 16:04:45.890 [80786] main/103/interactive memtx_tree.cc:863 E> ER_TUPLE_FOUND: Duplicate key exists in unique index "pk" in space "test" with old tuple - [1, 1] and new tuple - [1, 0]
[1]    80786 illegal hardware instruction  src/tarantool

* OS: MacOS
* OS Version: MacOS 11.0.1
* Architecture: amd64

Tarantool 2.5.2-0-g05730d3
Target: Darwin-x86_64-Release
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/tarantool/2.5.2.0 -DENABLE_BACKTRACE=ON
Compiler: /usr/bin/clang /usr/bin/clang++
C_FLAGS: -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-gnu-alignof-expression -Wno-cast-function-type
CXX_FLAGS: -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type

**Comment by Korablev77** [comment]
A bit simplified test:
```
box.cfg { memtx_use_mvcc_engine = true }

s = box.schema.create_space('test')
s:create_index('pk', {parts={{1, 'uint'}}})

txn_proxy = require('txn_proxy')
tx1 = txn_proxy.new()
tx2 = txn_proxy.new()

s:insert({1, 0})

tx2:begin()
tx1:begin()

tx1("s:delete(1)")
tx2("s:replace({1, 3})")

tx2:commit()
tx1:commit()
```
The problem is in tx prepare routines: in case it nullifies del_story of delete statements, it may turn out that during rollback of delete statement its del_story is null and rollback skips mvcc mechanisms...
