### ISSUE TITLE
Lua memory leak at on_commit/on_rollback triggers

### ISSUE THREAD

**Issue by Buristan** [tarantool/tarantool#6025]
If one runs the following Lua chunk (named </tmp/repro.lua>):
```lua
box.cfg{log_level = 0}
box.schema.space.create("test")
box.space.test:create_index('primary', {type = 'tree', parts = {1, 'number'}})
collectgarbage()
local before = collectgarbage("count")
 
for i = 1,1e6 do
    box.begin()
    box.on_commit(function() end) -- New function at every iteration.
    box.space.test:insert{i}
    box.commit()
end
 
collectgarbage()
local after = collectgarbage("count")
 
-- REGISTRY table reallocations, plus alive functions.
print(after - before, "Kbytes")
 
os.exit()
```

The output is the following:
```
$ tarantool /tmp/retro.lua
30290.680664063 Kbytes
```

The reason of the memory leak is unreleased Lua functions, referenced in the _registry_ table by `trg->reg` index. After the transaction is freed and triggers are removed, there is no way to detect the index and remove it from the _registry_ table.

You can inspect the content of the _registry_ table with the following commands via gdb:
```
(gdb) b lj_cf_print
<snipped>
(gdb) r
<snipped>
(gdb) lj-tab ((GG_State *)L)->g.registrytv->gcr.gcptr32
...
0x42c86a18: [10049]: Lua function @ 0x402ccc10, 0 upvalues, "@/tmp/repro.lua":9
0x42c86a20: [10050]: Lua function @ 0x402cc6f0, 0 upvalues, "@/tmp/repro.lua":9
...
```

**Comment by Gerold103** [comment]
The reason is that `trigger_destroy` is not called for these triggers. We must ensure that on commit all the triggers delete themselves, and destroy the rollback triggers manually. Vice versa for on rollback. This way we won't call `trigger_destroy`  for each transaction (it is expensive because uses virtual functions).
