### ISSUE TITLE
Applier synchro-nop filter might use wrong replica id

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#6035]
Here is a change I made:
```Diff
diff --git a/src/box/applier.cc b/src/box/applier.cc
index dc05c91d3..19c9fa169 100644
--- a/src/box/applier.cc
+++ b/src/box/applier.cc
@@ -975,7 +975,7 @@ apply_final_join_tx(struct stailq *rows)
  * The rows are replaced with NOPs to preserve the vclock consistency.
  */
 static void
-applier_synchro_filter_tx(struct stailq *rows)
+applier_synchro_filter_tx(uint32_t replica_id, struct stailq *rows)
 {
 	/*
 	 * XXX: in case raft is disabled, synchronous replication still works
@@ -991,7 +991,7 @@ applier_synchro_filter_tx(struct stailq *rows)
 	 * node, so cannot check for applier->instance_id here.
 	 */
 	row = &stailq_first_entry(rows, struct applier_tx_row, next)->row;
-	if (!txn_limbo_is_replica_outdated(&txn_limbo, row->replica_id))
+	if (!txn_limbo_is_replica_outdated(&txn_limbo, replica_id))
 		return;
 
 	if (stailq_last_entry(rows, struct applier_tx_row, next)->row.wait_sync)
@@ -1082,7 +1082,7 @@ applier_apply_tx(struct applier *applier, struct stailq *rows)
 			}
 		}
 	}
-	applier_synchro_filter_tx(rows);
+	applier_synchro_filter_tx(applier->instance_id, rows);
 	if (unlikely(iproto_type_is_synchro_request(first_row->type))) {
 		/*
 		 * Synchro messages are not transactions, in terms
```
I changed the filter to use ID of the instance who sent the transaction, not the ID of who generated the transaction. This is a functional change. And in theory might lead to NOP-ification of data which should have been applied. But all the tests passed. Which means either it is a serious bug not covered with a test, or it is correct, but we don't know why. Or both options are correct and we don't know why either. All the options are super bad, and this must be investigated.

Here is a test I tried to make it fail:
```Lua
--
-- Instance 1.
--
-- Step 1.
box.cfg{
    listen = 3313,
    replication = {'localhost:3313', 'localhost:3314', 'localhost:3315', 'localhost:3316'},
    replication_connect_quorum = 3,
    replication_synchro_quorum = 2,
    replication_synchro_timeout = 1000,
    replication_sync_timeout = 5,
    read_only = false,
    election_mode = 'candidate',
}

-- Step 5.
box.schema.user.grant('guest', 'super')
box.schema.create_space('async')
_ = box.space.async:create_index('pk')
box.schema.create_space('sync', {is_sync = true})
_ = box.space.sync:create_index('pk')

-- Step 11.
box.cfg{replication_synchro_quorum = 1}
box.ctl.wait_rw()

-- Step 12.
box.cfg{replication_synchro_quorum = 2}
require('fiber').create(function() box.space.sync:replace{1} end)
-- Wait WAL write.
os.exit(0)

-- Step 16.
-- Restart.
box.cfg{
    listen = 3313,
    replication = {'localhost:3313', 'localhost:3314', 'localhost:3315'},
    replication_synchro_quorum = 2,
    replication_synchro_timeout = 1000,
    replication_sync_timeout = 5,
    election_mode = 'manual',
}

-- Step 18.
box.cfg{replication_synchro_quorum = 1}
box.cfg{election_mode = 'candidate'}




--
-- Instance 2.
--
-- Step 2.
box.cfg{
    listen = 3314,
    replication = {'localhost:3313', 'localhost:3314', 'localhost:3315', 'localhost:3316'},
    replication_synchro_quorum = 2,
    replication_synchro_timeout = 1000,
    replication_sync_timeout = 5,
    read_only = true,
    election_mode = 'voter',
}

-- Step 7.
os.exit(0)

-- Step 13.
box.cfg{
    listen = 3314,
    replication = {'localhost:3313', 'localhost:3314', 'localhost:3315'},
    replication_synchro_quorum = 2,
    replication_synchro_timeout = 1000,
    replication_sync_timeout = 5,
    election_mode = 'voter',
}

-- Step 15.
box.cfg{election_mode = 'manual'}
box.ctl.promote()

-- Step 17.
-- Resign.
box.cfg{election_mode = 'voter'}





--
-- Instance 3.
--
-- Step 3.
box.cfg{
    listen = 3315,
    replication = {'localhost:3313', 'localhost:3314', 'localhost:3315', 'localhost:3316'},
    replication_synchro_quorum = 2,
    replication_synchro_timeout = 1000,
    replication_sync_timeout = 5,
    read_only = true,
    election_mode = 'voter',
}

-- Step 8.
os.exit(0)

-- Step 14.
box.cfg{
    listen = 3315,
    replication = {'localhost:3313', 'localhost:3314', 'localhost:3315'},
    replication_synchro_quorum = 2,
    replication_synchro_timeout = 1000,
    replication_sync_timeout = 5,
    election_mode = 'voter',
}




--
-- Instance 4.
--
-- Step 4.
box.cfg{
    listen = 3316,
    replication = {'localhost:3313', 'localhost:3314', 'localhost:3315', 'localhost:3316'},
    replication_connect_quorum = 3,
    replication_synchro_quorum = 2,
    replication_synchro_timeout = 1000,
    replication_sync_timeout = 5,
    read_only = true,
    election_mode = 'voter',
}

-- Step 6.
box.cfg{read_only = false, election_mode = 'manual'}
box.ctl.promote()

-- Step 9.
box.space.async:replace{1}
-- Wait replication to instance 1.

-- Step 10.
os.exit(0)
```
By my idea the Instance 4 should generate a transaction, relay it to Instance 1 only, then Instance 1 makes a synchro transaction without a CONFIRM and dies. Then Instance 2 becomes a leader and emits PROMOTE which should rollback row {1} from the 'sync' space, but keep the old {1} from 'async' space. Then Instance 1 is back and is elected a leader. Its old row sync {1} should be considered outdated and turned into NOPs on the other nodes, while row async {1} must be applied everywhere.

I thought that if the NOP filter would use applier->instance_id, it would nopify the async {1} too. But it didn't nopify not rolled back anything, and I don't know what is worse really.

One of the reasons why sync {1} is not rolledback is that Instance 1 is a leader. So when PROMOTE comes from Instance 2, it is simply ignored by `!raft_is_source_allowed()` in `applier_apply_tx()`, which should not happen obviously.

**Comment by Gerold103** [comment]
It looks like just adding a test, but in fact it appears to be far from trivial. Also it might depend on #6034.

**Comment by sergepetrenko** [comment]
Below is a test that shows that current filtering is correct. It breaks when Vlad's patch is applied (filtering by applier->instance_id instead of row->replica_id).

Actually, this test doesn't work on current master. In order to make it work you have to apply the following patch first.
The patch makes it so tarantool doesn't ignore replication from non-leader source.
This filter was introduced before we had promote, and now promote filtering does the same (even better) job with filtering synchronous transactions. Asynchronous transactions are applied from any source with the patch. Need to investigate whether this is ok.

```diff
--- a/src/box/applier.cc
+++ b/src/box/applier.cc
@@ -1029,19 +1029,7 @@ nopify:;
 static int
 applier_apply_tx(struct applier *applier, struct stailq *rows)
 {
-       /*
-        * Rows received not directly from a leader are ignored. That is a
-        * protection against the case when an old leader keeps sending data
-        * around not knowing yet that it is not a leader anymore.
-        *
-        * XXX: it may be that this can be fine to apply leader transactions by
-        * looking at their replica_id field if it is equal to leader id. That
-        * can be investigated as an 'optimization'. Even though may not give
-        * anything, because won't change total number of rows sent in the
-        * network anyway.
-        */
-       if (!raft_is_source_allowed(box_raft(), applier->instance_id))
-               return 0;
+       (void) applier;
        struct xrow_header *first_row = &stailq_first_entry(rows,
                                        struct applier_tx_row, next)->row;
        struct xrow_header *last_row;
```

Once the patch is applied, try the following test with and without Vlad's patch on top.

Without the patch (filtering by row->replica_id) instance 3 will have [1] in box.space.sync.

With the patch (filtering by applier->instance_id) instance 3 will replace [1] in box.space.sync with NOP.

```lua
--
-- Instance 1.
--

-- Step 1.
box.cfg{listen=3301}
box.schema.user.grant("guest", "replication")

-- Step 4.
box.cfg{replication={3301,3302}, replication_synchro_quorum=2, election_mode='manual'}
box.ctl.promote()
box.schema.space.create("sync", {is_sync=true})
box.space.sync:create_index("pk")
box.space.sync:insert{1}

--
-- Instance 2.
--

-- Step 2.
box.cfg{listen=3302, replication={3301, 3302}, election_mode='voter'}

-- Step 5.
box.space.sync:select{} -- [1].

--
-- Instance 3.
--

-- Step 3.
box.cfg{replication=3301, election_mode='voter'}
-- Wait for connection and break direct replication with 1.
-- Now we have cascade 3301 -> 3302 -> 3303
box.cfg{replication=3302}

-- Step 6.
box.space.sync:select{} -- nothing ?!

```

**Comment by Gerold103** [comment]
It seems such filtering will nopify the perfectly valid sync transactions coming from a replica if it happens before they arrive from the master. Because the replica term might be outdated in a sense that it didn't send us its latest term in its WAL, but it is getting there.

**Comment by Gerold103** [comment]
Need to port to 2.7. Does not work when simply cherry-picked.

**Comment by cyrillos** [comment]
@Gerold103 Vlad, I've pused out `gorcunov/gh-6035-applier-filter-9-27` branch on top of 2.7 which passes tests, though I must confess I didn't revealed yet why the conversion of txn flags have helper, still investigating. Could you please fetch the branch and confirm that it passes tests on your machine as well?

**Comment by cyrillos** [comment]
After been reading code more precise I still don't get how the patch with flags conversion helped to eliminate test problem. There is no concurrent access to these flags from different threads (also I've been reading tarantool disassembled listings since I thought that maybe compiler did some over optimization, but no, everything is fine, the builds I've been testing are debug ones). The only suspicious left is timings - with direct transactions flags update the code runs faster still I don't get how this helps.

**Comment by Gerold103** [comment]
The reason is that https://github.com/tarantool/tarantool/commit/f206d11218ab35a586f9ae107bf5644df43f9511 uses txn flags as bit fields, and it was cherry-picked to 2.7. The flags should have been ported to 2.7 from the beginning. I don't know why that patch was skipped in the first place.

**Comment by cyrillos** [comment]
Merge the `gorcunov/gh-6035-applier-filter-9-27` into 2.7 please, and close the bug then.

**Comment by Gerold103** [comment]
2.7 patch - https://github.com/tarantool/tarantool/commit/fd99c507030949ac4bcc66387e4bde495e29bc4b
