### ISSUE TITLE
Research cost of ARM support in core

### ISSUE THREAD

**Issue by alyapunov** [tarantool/tarantool#6048]
Actually I haven't seen it but they say that tarantool fails to build on ARM, at least on M1.
There could be two types of problems - luajit and core.
We have to investigate core part of the problem and evaluate the cost (in story points) of support of the platform. There's a chance that the cost is about zero - fix it then.
The final aim is to build tarantool on any ARM plafrom and be sure that it works stable and effective there.

**Comment by Totktonada** [comment]
There is known problem around libcoro: #5983.

**Comment by Korablev77** [comment]
@Totktonada 
This PR fixes the problem:
https://github.com/tarantool/tarantool/pull/6058

There's also known build problem with LuaJIT which is fixed in https://github.com/tarantool/tarantool/commit/16212f5d87848654025ba439ef995bb74f00b7f1

Otherwise build is successful.

**Comment by Totktonada** [comment]
Nice! How much it workable? Can you, please, collect statistics of succussful / failing tests and place the overall statistics and the raw data here?

**Comment by Korablev77** [comment]
@igormunkin pointed out that Tarantool is built with jit-off. In this mode only two tests failing are box/push.test.lua:
```
[001] --- box/push.result	Thu Apr 29 19:49:38 2021
[001] +++ var/rejects/box/push.reject	Thu Apr 29 20:31:12 2021
[001] @@ -302,11 +302,12 @@
[001]  ...
[001]  c:call('do_push', {}, {on_push = table.insert, on_push_ctx = messages})
[001]  ---
[001] +- error: 'builtin/box/net_box.lua:584: attempt to index local ''hdr'' (a number value)'
[001]  ...
[001]  ok, err
[001]  ---
[001]  - null
[001] -- '[string "t = setmetatable({100}, {__serialize = functi..."]:1: err in ser'
[001] +- null
[001]  ...
```
My assumption is that it might be connected with jit-off mode - no any reasonable explanation comes into mind.
And sql-tap/atof1.test.lua:
` local y = test:execsql(string.format("SELECT %s=CAST(quote(%s) AS NUMBER)",x, x))
`
`y` sometimes is evaluated as false. I tried to extract it to a separate reproducer but for some reason Tarantool launched from console always gives correct result. Nevertheless it looks to be fixable with a bit more effort.

**Comment by Korablev77** [comment]
Ok, here's a stable reproducer for sql-tap/atof1.test.lua fail:
```
box.cfg{}
--box.execute('set session "sql_vdbe_debug" = true;')
for i = 1, 10000 - 1, 1 do
    local pow = math.random(100)
    local x = math.pow((math.random()-0.5)*2*math.random(), pow)

        local y = box.execute(string.format("SELECT %s=CAST(quote(%s) AS NUMBER)",x, x)) 
        if y['rows'][1][1] == false then  
                require('log').error(y.rows[1][1]) 
                os.exit()
        end
end
```

I suspect that sqlAtoF() raises wrong result for certain specific inputs. Need to dig further.

**Comment by Korablev77** [comment]
I believe that fair eta for both issues is around 8sp.

**Comment by Korablev77** [comment]
Repro for box/push.test.lua:

```
box.cfg{listen = 3301}
netbox = require('net.box')
c = netbox.connect(box.cfg.listen)
ok = nil
err = nil
messages = {}
t = setmetatable({100}, {__serialize = function() error('err in ser') end})
function do_push() ok, err = box.session.push(t) end
box.schema.func.create('do_push')
box.schema.user.grant("guest", "execute", "function", "do_push")
c:call('do_push', {}, {on_push = table.insert, on_push_ctx = messages})

```

**Comment by Korablev77** [comment]
Superseded by https://github.com/tarantool/tarantool/issues/6059
