### ISSUE TITLE
Spelling errors in module.h

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#6061]
I have Ubuntu 20.04.
I have Tarantool 2.9, pulled from source today.

Due to a suggestion from @Totktonada, I list spelling
errors that I see in the generated module.h file.

macroses shuld be macros
strucrs should be structs
indepedent should be independent
othrewise should be otherwise
hadler should be handler
timeoout should be timeout
convertable should be convertible
byffer should be buffer
zerod-based should be zero-based
Absense should be absence
Arrat should be Array
Retrive should be Retrieve
interator should be iterator
scenarious should be scenarios

**Comment by chakkk309** [comment]
Hi, I'm Jackie. I've found these typos in .h file, can I create a pr and submit it to the master branch?
