### ISSUE TITLE
raft: incoming message verification is not complete

### ISSUE THREAD

**Issue by cyrillos** [tarantool/tarantool#6067]
The request in `raft_process_msg` comes from network so it may contain completely arbitrary data. In particular the `raft:state` is defined as enum thus it is signed integer. We need to make sure that state is not over predefined values thus need more precise check. Something like
```
From dccbd18472b4ca3a4317ad9d4fef39b65df64e64 Mon Sep 17 00:00:00 2001
From: Cyrill Gorcunov <gorcunov@gmail.com>
Date: Tue, 11 May 2021 15:53:54 +0300
Subject: [PATCH] raft: more precise verification of request state

The state comes from network so it might be screwed,
make sure that it is known one.

Signed-off-by: Cyrill Gorcunov <gorcunov@gmail.com>
---
 src/lib/raft/raft.c | 6 ++++--
 1 file changed, 4 insertions(+), 2 deletions(-)

diff --git a/src/lib/raft/raft.c b/src/lib/raft/raft.c
index 46a30149f..3ac2661ea 100644
--- a/src/lib/raft/raft.c
+++ b/src/lib/raft/raft.c
@@ -309,7 +309,8 @@ raft_process_msg(struct raft *raft, const struct raft_msg *req, uint32_t source)
 	say_info("RAFT: message %s from %u", raft_msg_to_string(req), source);
 	assert(source > 0);
 	assert(source != raft->self);
-	if (req->term == 0 || req->state == 0 || req->state >= raft_state_MAX) {
+	if (req->term == 0 || req->state == 0 ||
+	    (unsigned)req->state >= raft_state_MAX) {
 		diag_set(RaftError, "Invalid term or state");
 		return -1;
 	}
@@ -405,7 +406,8 @@ raft_process_msg(struct raft *raft, const struct raft_msg *req, uint32_t source)
 			raft_sm_become_leader(raft);
 			break;
 		default:
-			unreachable();
+			panic("RAFT: unexpected state %d", raft->state);
+			break;
 		}
 	}
 	if (req->state != RAFT_STATE_LEADER) {
-- 
2.31.1
```

But it needs a test case first and review if it is a really an issue.

**Comment by cyrillos** [comment]
Seems the modern compilers (gcc and llvm) are not hitting problems here, so just leave it as is.

**Comment by Gerold103** [comment]
Wait. Don't you think we should not rely on the compilers? Also what about the bug I told you about in the mailing list? There is still truncation of the state value if it is > UINT32_MAX.

**Comment by cyrillos** [comment]
> Wait. Don't you think we should not rely on the compilers?

We shouldn't rely on compilers and I posted a fix and explained in a very detailed way why explicit type conversion is a proper way to handle such nuances. You didn't like it and this is perfectly fine because you're the former code author and it is up to you to choose patch(es) which suite your code vision.

> Also what about the bug I told you about in the mailing list? There is still truncation of the state value if it is `> UINT32_MAX`.

I think this problem might be revisited and fixed as a separate issue, it should not be critical because even in worst situation it won't cause application crash or some side effects. The only reason I think of is extended logging maybe for better detection if some remote peer sent wrong data.

**Comment by Gerold103** [comment]
> You didn't like it

It is not about liking or not, such as a not strictly defined code style thing. It is an objective thing - normally you do not cast a number to unsigned type to check if it is negative. You just make `< 0 ` check. The cast is extremely counter-intuitive. Huge over-engineering for such a simple action.

> I think this problem might be revisited and fixed as a separate issue, it should not be critical because even in worst situation it won't cause application crash or some side effects

Why not fix it in scope of this issue? The message verification is incomplete, exactly like the title says. Talking of the side effects - they can happen. If we ever start using upper bits or send a broken message due to any reason and a truncation happens, the instance will incorrectly interpret the state. For instance, treat the sender as a master while it was a follower in fact. This causes issues with NOPification of synchronous data in the limbo.
