### ISSUE TITLE
Build failure on XCode 12.5

### ISSUE THREAD

**Issue by sergos** [tarantool/tarantool#6076]
**Bug description**

After XCode 12.5 upgrade build started to fail in the following way:

```
In file included from /Users/s.ostanevich/workspaces/t.build/src/lib/core/backtrace.cc:42:
In file included from /Users/s.ostanevich/workspaces/t.build/src/lib/core/assoc.h:53:
In file included from /Users/s.ostanevich/workspaces/t.build/src/lib/salad/mhash.h:66:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/math.h:309:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/type_traits:418:
/Users/s.ostanevich/workspaces/t.build/src/lib/small/version:1:1: error: expected unqualified-id
1.0.0-19-gc1b6abd
^
```
The reason is `src/lib/small/VERSION` file is treated as C++ standard library <version> on a filesystem with case-insensitive names. 

To avoid the problems appearance in the future we need to update

a) include paths across the project to avoid the too-high include path with includes as `#include "small/region.h"`
b) the includes themselves to match the a) part

Similar problem appeared at the top of Tarantool repo, where another VERSION file is present. 

* OS: [e.g. Linux/MacOS/FreeBSD/OpenBSD]
MacOS

* OS Version: [e.g. Debian 11, FreeBSD 11]
BigSur 11.2.3, XCode 12.5

* Architecture: [amd64, arm]
AMD64

Place `tarantool --version` output here.
```
$ git describe
2.9.0-26-g75b2ccce8
```

**Steps to reproduce**
`cmake . && make`

**Comment by sharonovd** [comment]
please check that 1.10 can be built as well
