### ISSUE TITLE
Backward compability broken during upgrade 1.10.9 -> 1.10.10

### ISSUE THREAD

**Issue by VifleY** [tarantool/tarantool#6082]
**Bug description**

`box.tuple.encode` signature changed in 1.10.10 

1.10.9
```
function(obj)
```

1.10.10
```
function(tmpbuf, obj)
```

* OS: Linux
* OS Version: Ubuntu 20

**Steps to reproduce**

Run Tarantool 1.10.9 (ex. `docker run -it tarantool/tarantool:1.10.9`)
```
tarantool> tuple = {}
---
...

tarantool> box.tuple.encode(tuple)
---
- 'cdata<char *>: 0x7f1848828030'
- 'cdata<char *>: 0x7f1848828031'
...
```

Run Tarantool 1.10.10 (ex. `docker run -it tarantool/tarantool:1.10.10`)
```
tarantool> tuple = {}
---
...

tarantool> box.tuple.encode(tuple)
---
- error: 'builtin/msgpackffi.lua:56: attempt to call method ''alloc'' (a nil value)'
...
``` 

**Actual behavior**

API changed in bug fix update

**Expected behavior**

API keeps the same signature during minor update

**Comment by Gerold103** [comment]
This is not a public function. It is not documented, and returns data in an internal buffer which you should not ever use. You use a private function - you get potential issues with keeping your code compatible with all versions. Private functions do not have necessity to be compatible with old internal code.
