### ISSUE TITLE
popen: the OS "kill" command kills the process but internally it continues to run

### ISSUE THREAD

**Issue by racherb** [tarantool/tarantool#6083]
**Bug description**

When using the "**popen**" module, a different behavior is observed when using the module's **SIGKILL** signal versus executing the operating system's kill command. 

When `popen_handle:kill()` is executed the system works as expected, however, when killing the process from outside Tarantool (by executing the OS kill command) then the `popen_handle` status is updated indicating the correct state (`status = state: signaled, signame: SIGKILL, sign: 9`) but in reality the process does not stop and continues to run.

When checking the status of the "pid" process through "`ps -fea | grep <pid>`" it does not appear to be running, but in reality it continues to run indefinitely as shown below.

* OS: Linux
* OS Version: Ubuntu 20.04.2 LTS (Focal)
* Architecture: amd64

**Tarantool version**

```Bash
Tarantool 2.5.3-0-gf93e48013
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_BACKTRACE=ON
Compiler: /usr/bin/cc /usr/lib/ccache/g++
C_FLAGS:-g -O2 -fdebug-prefix-map=/build/tarantool-2.5.3.0=. -specs=/usr/share/dpkg/no-pie-compile.specs -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type
CXX_FLAGS:-g -O2 -fdebug-prefix-map=/build/tarantool-2.5.3.0=. -specs=/usr/share/dpkg/no-pie-compile.specs -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type
```

**Steps to reproduce**

Save this code in the file **popen_issue.lua**

```Lua
#!/usr/bin/env tarantool

local popen = require('popen')

local popen_new = popen.new
local popen_opts = popen.opts

local capture = {}

local function submit (what)

    local ph, err = popen_new(
        {what..' >&2'},
        {
            stdin = popen_opts.PIPE,
            stdout = popen_opts.PIPE,
            stderr = popen_opts.PIPE,
            shell = true,
            group_signal = true,
            setsid = true,
        }
    )
    if ph == nil then return nil, err end

    return ph

end

local function read(ph, save_to_file)
    local res, err
        res, err = ph:read({stderr = true}):rstrip()
        if res==nil then
            ph:close()
            return nil, err
        end
        if save and res and res ~= '' then
            local cmd = {'echo "', res, '" >> ', save_to_file}
            os.execute(table.concat(cmd))
        end
    return res
end

popen_issue.submit = submit
popen_issue.read = read

return popen_issue

```

**How to run and Actual behavior**

From the tarantool console run the following:

```Lua
tarantool> cap=require('popen_issue')
tarantool> to_file = os.tmpname()
tarantool> ph=cap.submit('ping localhost')
tarantool> ph
---
- stdout: open
  command: sh -c 'ping localhost >&2'
  stderr: open
  status:
    state: alive
  stdin: open
  opts:
    stdout: pipe
    stdin: pipe
    group_signal: true
    keep_child: false
    close_fds: true
    restore_signals: true
    shell: true
    setsid: true
    stderr: pipe
  pid: 1807189            --Take note here
...
```
Let's start reading the output of the execution:

```Lua
tarantool> cap.read(ph, to_file)
...
  ...
  64 bytes from localhost (127.0.0.1): icmp_seq=149 ttl=64 time=0.033 ms
  64 bytes from localhost (127.0.0.1): icmp_seq=150 ttl=64 time=0.036 ms
  64 bytes from localhost (127.0.0.1): icmp_seq=151 ttl=64 time=0.051 ms
  64 bytes from localhost (127.0.0.1): icmp_seq=152 ttl=64 time=0.029 ms
  64 bytes from localhost (127.0.0.1): icmp_seq=153 ttl=64 time=0.056 ms'
...
```

From the Linux terminal run the following: 

Use here the value of ph.pid returned earlier. In my case the value corresponds to 1807189

```Bash
$ ps -fea | grep 1807189
userx+ 1807189 1286630  0 22:17 ?        00:00:00 sh -c ping localhost >&2
userx+ 1807191 1807189  0 22:17 ?        00:00:00 ping localhost
userx+ 2697081   65215  0 22:26 pts/4    00:00:00 grep --color=auto 1807189
```
Kill the ph.pid process from Linux.

```Bash
$ sudo kill 9 1807189

```
Let's go back to the tarantool console and check the status of the popen handler.

```Lua
tarantool> ph
---
- stdout: open
  command: sh -c 'ping localhost >&2'
  status:
    state: signaled
    signame: SIGTERM
    signo: 15
  stderr: open
  stdin: open
  opts:
    stdout: pipe
    stdin: pipe
    group_signal: true
    keep_child: false
    close_fds: true
    restore_signals: true
    shell: true
    setsid: true
    stderr: pipe
...
```

So far so good. Popen detects that the signal has been sent (**state: signaled**). Let's see what happens when we read the output. 

```
tarantool> cap.read(ph, to_file)
---
  ...
  64 bytes from localhost (127.0.0.1): icmp_seq=962 ttl=64 time=0.028 ms
  64 bytes from localhost (127.0.0.1): icmp_seq=963 ttl=64 time=0.029 ms
  64 bytes from localhost (127.0.0.1): icmp_seq=964 ttl=64 time=0.030 ms
  64 bytes from localhost (127.0.0.1): icmp_seq=965 ttl=64 time=0.039 ms
  64 bytes from localhost (127.0.0.1): icmp_seq=966 ttl=64 time=0.030 ms
---
```

```
tarantool> cap.read(ph, to_file)
---
- '64 bytes from localhost (127.0.0.1): icmp_seq=1155 ttl=64 time=0.053 ms
  64 bytes from localhost (127.0.0.1): icmp_seq=1156 ttl=64 time=0.054 ms'
```
Execute as many times as possible the function `cap.read(ph, to_file)` this function will always fetch new data.

Did it remain in execution? We do a check in the Linux terminal and it seems that it is not running.

**Expected behavior**

It is expected that, when sending the **SIGKILL** signal to the Linux terminal, the behavior will be the same as when sending the signal from `popen_handle:kill()`.

**Another anomaly observed**

The output of the chunk read breaks the integrity of the data as seen below. 
By reviewing the contents of the output file (to_file) you can see how the chunk breaks the file line.

`$ cat /tmp/lua_cwl196`

64 bytes from localhost (127.0.0.1): icmp_seq=1836 ttl=64 time=0.039 ms
64 bytes from localhost (127.0.0.1): icmp_seq=1837 ttl=64 time=0.034 ms
64 bytes from localhost (127.0.0.1): icmp_seq=1838 ttl=64 time=0.031 ms
**64 bytes from localhost (127.0.0.1): icmp_seq=18
39 ttl=64 time=0.031 ms**
64 bytes from localhost (127.0.0.1): icmp_seq=1840 ttl=64 time=0.035 ms
64 bytes from localhost (127.0.0.1): icmp_seq=1841 ttl=64 time=0.043 ms
64 bytes from localhost (127.0.0.1): icmp_seq=1842 ttl=64 time=0.030 ms
64 bytes from localhost (127.0.0.1): icmp_seq=1843 ttl=64 time=0.045 m

**Comment by cyrillos** [comment]
Actually it is expected. The positive signal number means that you're killing parent `sh` process, where child `ping` continue executing. You should kill the whole session instead, ie to use `kill -9 $pid` as far as I can say. Try this way please.

**Comment by cyrillos** [comment]
You will have the same result if you run `sh -c "ping 127.0.0.1` and try to `kill 9 pidof(sh)` because the `sh` process get killed while `ping` process get reparented to `init`.

**Comment by racherb** [comment]
I have tried to reproduce the case again and it is working correctly, even if I kill the parent process through kill 9 <pid>.

**Comment by racherb** [comment]
With your answer I consider the case closed.
