### ISSUE TITLE
Missed setting of CARG1 as lua_State argument in call to lj_tab_setinth() in BC_TSETR fallback

### ISSUE THREAD

**Issue by Buristan** [tarantool/tarantool#6084]
Call to Lua fast function built-ins contained `BC_TSETR` leads to crash, when a new index is integer greater than `t->asize`:
```bash
$ src/tarantool -e 'table.move({}, 1, 1, 3, {})'             
zsh: segmentation fault  src/tarantool -e 'table.move({}, 1, 1, 3, {})
```
The reason is not set `CARG1` as `lua_State` for call to `lj_tab_setinth()` in `BC_TSETR` fallback.
This issue is fixed in the upstream via commit LuaJIT/LuaJIT@ae20998ff5aaacc8e3afd46c64e28a8e039b58a1.
This issue relates only to arm/arm64/ppc architectures.

The mentioned fix need to be backported as a part of #5629 with the test above.

**Comment by igormunkin** [comment]
The issue is resolved in scope of tarantool/luajit@dd75470. The submodule was updated in tarantool in 2.9.0-80-gbef585aa8 (bef585a).
