### ISSUE TITLE
Log and limit iteration in space

### ISSUE THREAD

**Issue by alyapunov** [tarantool/tarantool#6085]
### The problem.
If a space is huge then `space:select{}` (with empty key) will kill the tarantool. Moreover, similar `space:pairs{}` iteration without yielding will also block the server for a time.
Note that not only empty key is dangerous: partial keys, non-unique indexes and GE (LE, GT, LT) iterators could lead to very long iteration.
On the other hand if a space is small there should be no limits to select it all in one line.
### The solution.
Introduce new term - DB micro operation (quantum?) - the operation with DB that costs a limited (O(1) or at most O(ln(N))) amount of time. For example `space:select{key}` consist of one lookup microop and then M microops - iteration over M resulting tuples. And one iteration over `space:pairs{}` is exactly one microop. Another good example is iteration over bitset index: with a complex key the lookup has an O(N) complexity - that is up to N microops to acquire the first tuple.

Implement two limits - (warn limit, error limits) -  on the number of DB micro operations **since the last fiber switch**. Reaching warn limit must generate a warning in log file, and reaching error limit must result a error. Both limits may be set in box.cfg, may be manually overridden by a special function (only until the next fiber switch) and should have finite defaults (I propose 16k and 128k).

**Comment by drewdzzz** [comment]
We decided to use time for limit iteration. The patch is almost ready, but there are still several questions questions:
1. What should be the default limit? I think it's better to use maximum possible value so that the limitation works only with users who explicitly use this feature.
2. Should we limit only select/pairs functions, or also limit DML? All the DML operations yield when WAL is enabled, but when it is disabled, DML operations are unstoppable.

**Comment by unera** [comment]
Will the limit work only if `select{}` contains `nil` in its options?

**Comment by drewdzzz** [comment]
> Will the limit work only if `select{}` contains `nil` in its options?

@unera,  It will work with `select`/`pairs` methods regardless of its arguments.

**Comment by unera** [comment]
It's a pity.

Why we decided to add the limit regardless of `select:limit`?

**Comment by unera** [comment]
I understood


>  What should be the default limit? I think it's better to use maximum possible value so that the limitation works only with users who explicitly use this feature.

1 second

>    Should we limit only select and pairs functions, or also limit DML? DML operations yields when WAL is enabled, but when WAL is disabled or operations are executed in a single large transaction, they don't yield.

Yes we should

**Comment by drewdzzz** [comment]
> > Should we limit only select and pairs functions, or also limit DML? DML operations yields when WAL is enabled, but when WAL is disabled or operations are executed in a single large transaction, they don't yield.
> 
> Yes we should

Should limit select/pairs only, or DML too?

**Comment by Mons** [comment]
> What should be the default limit? I think it's better to use maximum possible value so that the limitation works only with users who explicitly use this feature.

Warn limit may be set to 0.5, as in `too_long_threshold`, but from the user's point of view it's 0.5 second freeze, so I'd better set it to **0.1**
Error limit **1.0** may be considered acceptable.

> Should we limit only select and pairs functions, or also limit DML? DML operations yields when WAL is enabled, but when WAL is disabled or operations are executed in a single large transaction, they don't yield.

Yes, DML for wal_mode=none also should be subjected to limitation.

**Comment by alyapunov** [comment]
So we will have a warn limit 0.1s and error limit 1s.
Note that wal_mode='write' can also be easily frozen using transactions, which postpone wal write.

**Comment by drewdzzz** [comment]
In offline discussion we decided to:
1. Limit `select`, `pairs` and `replace` methods.
2. Use *SIGURG* to stop iteration.

**Comment by drewdzzz** [comment]
We are currently choosing between two approaches: get time with `clock_gettime()` on every 1000 iteration / dml query, or use [itimer](https://www.opennet.ru/man.shtml?topic=setitimer&category=2&russian=0) have a low-resolution clock in our program space.
I ran two benchmarks to find out which approach reduces performance less.

## Cbench
|                                                              |     master                            | clock_gettime()          | Interval timer (10 ms tick)  |
|   ---------------------------------- |   -                                      | ---------------------- |-----------------------|
|Hash replaces                                      |   1825905 (+/- 21290)    |  1835696 (`+0.5 %`)  | 1772406 (` -2.9 %`)  |
|Hash selects                                        |    5443035 (+/- 20337)  |  5380033 (`-1.15 %`) |     5333206  ( `-2%`)  |
|Hash selrepl                                         |    1544353  (+/- 21913)   |  1553313 (`+0.6 %`)  |   1495764 (`-3.14%`)  |
|Hash updates                                       |    1192947   (+/- 17613)  |  12129939 (`+2.2 %`)| 1193405  (`+0.04%`)|
|Hash deletes                                        |  2091779   (+/- 32314)   |  2134894 (`+2 %`)     | 2112681 (`+1%`)|
|Tree replaces                                       |    1253800  (+/- 6739)    |  1263604 (`+0.7 %`)  |  1249164 (`-0.3%`)  |
|Tree selects                                         |    2276908   (+/- 4832)  |  2268585 (`-0.35 %`)|  2273586  (`-0.14%`)  |        
|Tree selrepl                                          |    921922  (+/- 7115)       |   922086  (`+0.017 %`)|   910616 (`-1.22%`) |      
|Tree updates                                       |     776853  (+/- 6844)    |    785628 (`+1.13 %`) |   792585  (`+2%`)  |
|Tree deletes                                        |     1053129  (+/- 5436)   |    1061779 (`+0.8 %`) |  1059897 (`+0.63%`)  |

## Fiber yield rps benchmark
|                    fiber num                          |     master     | clock_gettime()          | Interval timer (10 ms tick)  |
|   ---------------------------------- |   -                 | ---------------------- |-----------------------|
|1                                                            |   3542216    |  3024121  (`-14.6 %`) | 3513613 (`-0.8 %`)     |
|10                                                          |    7437426   |  5573086   (`-25 %`) | 7445122 (`+0.1 %`)     |
|100                                                       |    6944586   | 5025591 (`-27.6 %`)  | 6846051 (`-1.4 %`)    |
|1000                                                     |    1401066    |  1274967     (`-9 %`)  | 1379156 (`-1.56 %`)   |

**Comment by Mons** [comment]
Decided to set the following defaults:
* Warning limit should be set by default to 0.5s.
* Error limit should be set to 1s. 

Documentation should be populated with the information, how to adjust this limits and must be searchable by the error message.

**Comment by Mons** [comment]
Also, this feature must be in effect for all SQL queries.
If someone wants to execute long requests (either SQL or with common select), they should extend global default limit.

**Comment by drewdzzz** [comment]
@Mons 
Should there be commands in SQL that can change the global limit? If they should, what kind of limits should they change (only the global limit, or for the current fiber too, should they only increase the limit, or can they assign it any value)?

**Comment by Totktonada** [comment]
Documentation request: https://github.com/tarantool/doc/issues/3057
