### ISSUE TITLE
Backport commits fixing xpcall on aarch64

### ISSUE THREAD

**Issue by Buristan** [tarantool/tarantool#6093]
On aarch64 architectures the code below leads to crash:
```bash
tarantool -e 'xpcall(assert, nil)'
Segmentation fault (core dumped)
```
In upstream it is ticket LuaJIT/LuaJIT#365.
Commit LuaJIT/LuaJIT@33082a6f4778aa152f6a4a684a7fe79436f1ecb6 fixes the core dump. And additional commit LuaJIT/LuaJIT@d417ded17945b4211608d497d50b509e0274f5e0 fixes an error message thrown by `xpcall()`.

**Comment by igormunkin** [comment]
The changeset is backported in scope of tarantool/luajit@4e4e3fd and tarantool/luajit@af889e4. The submodule was updated in tarantool in 2.9.0-80-gbef585aa8 (bef585a).
