### ISSUE TITLE
run module tests as part of release suite

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#610]
We need to run test suite for all modules published at rocks.tarantool.org before we make a release.

**Comment by Sulverus** [comment]
Done. Awaiting for check.

1. for lua modules(queue, http, expirationd) added travis spec to run tests suites with tarantool.
2. writed tests for expirationd
3. queue-collection moved to tarantool/queue master branch(old code in stable branch)
4. travis ping feature added in tarantool buildbot to test modules after build.

N.B> travis-ping feature enabled only for ubuntu trusty_64 builder(travis-ci works on it)

**Comment by Sulverus** [comment]
travis spec added to stable branch for tarantool/queue
