### ISSUE TITLE
fiber.time() and fiber.time64(): convert to FFI

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#611]
Use ffi or fiber.time() and fiber.time64()

**Comment by rtsisyk** [comment]
I also suggest to rename fiber.time64() to fiber.utime() or something like that

**Comment by kostja** [comment]
* Roman Tsisyk <notifications@github.com> [15/01/15 16:58]:
> I also suggest to rename fiber.time64() to fiber.utime() or
> something like that.

Too late for renames, unfortunately.

-- 
http://tarantool.org - a NoSQL database in a Lua script
