### ISSUE TITLE
Error in comparison too small DOUBLE number with DECIMAL numbers in index.

### ISSUE THREAD

**Issue by ImeevMA** [tarantool/tarantool#6119]
Tarantool 2.9.0-59-gc5e185474

Too small (less than 1e-38) DOUBLE numbers truncated to 0 when compared to DECIMAL during construction of index.

Reproducer:
```
tarantool> s = box.schema.space.create('a', {format = {{'u', 'number'}}})
---
...

tarantool> _ = s:create_index('i')
---
...

tarantool> s:insert({require('decimal').new(0)})
---
- [0]
...

tarantool> s:insert({1e-39})
---
- error: Duplicate key exists in unique index "i" in space "a" with old tuple - [0]
    and new tuple - [1e-39]
...
```

**Comment by sergepetrenko** [comment]
Hi! This behaviour is following the current design, and is not a bug. Our decimals have only 38 decimal digits of precision (fixed point). So everything less than 1e-38 gets truncated to zero when  constructing a decimal.

Speaking of comparators, when comparing with decimals every other number type is cast to decimal prior to comparison.
So this behaviour is expected with current comparators.

If you want to change the way numbers are cast in comparators, that's a separate task, and needs to be discussed separately.

**Comment by ImeevMA** [comment]
I am not sure that we always cast to decimal. Is this documented? This is not typical for our numeric comparators. Also, I believe this is not always true:
```
tarantool> s = box.schema.space.create('a', {format = {{'u', 'number'}}})
---
...

tarantool> _ = s:create_index('i')
---
...

tarantool> s:insert({require('decimal').new("99999999999999999999999999999999999999")})
---
- [99999999999999999999999999999999999999]
...

tarantool> s:insert({1e100})
---
- [1e+100]
...

tarantool> s:select()
---
- - [99999999999999999999999999999999999999]
  - [1e+100]
...
```

Here we see, that these number were properly compared.

**Comment by ImeevMA** [comment]
I also saw something strange:
```
tarantool> s:select({1e50}, {iterator="LE"})
---
- []
...

tarantool> s:select({1e50}, {iterator="GE"})
---
- - [99999999999999999999999999999999999999]
  - [1e+100]
...
```

**Comment by sergepetrenko** [comment]
> Here we see, that these number were properly compared.

Must be due to tuple hints? I'm not sure

**Comment by sergepetrenko** [comment]
> I also saw something strange:
> 
> ```
> tarantool> s:select({1e50}, {iterator="LE"})
> ---
> - []
> ...
> 
> tarantool> s:select({1e50}, {iterator="GE"})
> ---
> - - [99999999999999999999999999999999999999]
>   - [1e+100]
> ...
> ```

Now this is a bug, indeed.

**Comment by ImeevMA** [comment]
However, now this does not look like problem of DECIMAL:
```
tarantool> s = box.schema.space.create('a', {format = {{'u', 'number'}}})
---
...

tarantool> _ = s:create_index('i')
---
...

tarantool> s:insert({-1ULL})
---
- [18446744073709551615]
...

tarantool> s:insert({1e100})
---
- [1e+100]
...

tarantool> s:select()
---
- - [18446744073709551615]
  - [1e+100]
...

tarantool> s:select({1e50}, {iterator="LE"})
---
- []
...

tarantool> s:select({1e50}, {iterator="GE"})
---
- - [18446744073709551615]
  - [1e+100]
...
```
