### ISSUE TITLE
Replication stopped after a transaction with temp space truncation

### ISSUE THREAD

**Issue by sergepetrenko** [tarantool/tarantool#6123]
Tarantool 2.9.0-61-g2b25ca6c7 (master)

Run the following test on 2 instances:

```lua
--
-- Instance 1
--

-- Step 1
box.cfg{listen=3301}
box.schema.user.grant("guest", "replication")
box.schema.space.create("temp", {temporary=true})

-- Step 3
box.begin() box.space._schema:replace{"smth"} box.space.temp:truncate() box.commit()

--
-- Instance 2
--

-- Step 2
box.cfg{replication=3301}
```

After running 3 steps, replication between the instances will break, and the second instance's log will show:
`applier.cc:663 E> ER_UNSUPPORTED: replication does not support interleaving transactions`

**Comment by sergos** [comment]
The documentation says
```
The truncate method cannot be called from within a transaction.
```
https://www.tarantool.io/en/doc/latest/reference/reference_lua/box_space/truncate/
Are we plan to change it?

**Comment by sergepetrenko** [comment]
> The documentation says
> 
> ```
> The truncate method cannot be called from within a transaction.
> ```
> 
> https://www.tarantool.io/en/doc/latest/reference/reference_lua/box_space/truncate/
> Are we plan to change it?

I think this will be changed. We're planning to implement transactional ddl, aren't we?
Besides, even while the doc states that truncate in a transaction is forbidden, it works, as can be seen in my example.
