### ISSUE TITLE
Retry join automatically (for a timeout)

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#6126]
Currently when join fails, the instance is terminated. Even if the error was not critical. For instance, the join-master appeared to be read-only.

It looks like a config error, but actually can happen even without config changes. For instance, if automatic election is used, then a new instance can find the leader, but while it is sending a join request, the leader can resign. The join will fail saying the former leader is read-only.

It should not be hard to retry the join by looking for a new leader. Such not critical errors can be caught in `bootstrap_from_master()`, when box is waiting for applier's state `APPLIER_FETCHED_SNAPSHOT` or `APPLIER_FINAL_JOIN`.

The most complex part would be vinyl, which in `engine_begin_initial_recovery_xc()` can already create some files. It is not clear what to do with them to retry.

Retry itself should re-create the appliers to fetch new ballots, try to find a new join-master, and retry. Retry would need to be done via polling with small sleeps if a leader can not be found. So as this wouldn't be a busy loop.

Another option (more complex but better) would be to subscribe on ballot updates and look for when some of the remote nodes becomes suitable to be a join-master. Hard parts here are:
1. There are no ballot updates now, it needs to be implemented.
2. Need to retry connection establishment to disconnected appliers.

**Comment by Gerold103** [comment]
A very simple test case:
```Lua
--
-- Instance 1
--
box.cfg{
    listen = 4401,
    replication = {4401},
    read_only = false,
}
box.schema.user.grant('guest', 'super')
box.cfg{read_only = true}

-- Now wait a bit and start the second instance.

--
-- Instance 2
--
box.cfg{
    listen = 4402,
    replication = {4401, 4402},
    read_only = true,
}
```
Currently the second instance just terminates immediately. Instead it should wait until the other instances becomes writable. The test is quite artificial, but imagine instead of config `read_only` the first instance is a RAFT candidate trying to be elected. Then the waiting would make sense.

**Comment by sergepetrenko** [comment]
It seems this is a bugfix, rather than a feature. Should be in 2.10 as well: https://github.com/tarantool/tarantool/issues/8681.

Will backport in scope of #8682
