### ISSUE TITLE
replication conflict testing

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#613]
Add test cases for asynchronous replication conflicts:
- delete of a non-existing key
- double update of a key on two nodes
- insert
- auto-increment
- CRDT cases

We need to cover with test what works and what doesn't..

**Comment by Sulverus** [comment]
Done. Need review for 5 cases:
* double update in master and replica - replication status: stopped
* insert different values with same id - replication status: stopped
* auto increment different values - replication status: stopped
* CRDT increment with update - replication is correct
* delete not existing key - replication is correct

**Comment by kostja** [comment]
Pushed.
