### ISSUE TITLE
ER_TUPLE_FOUND message is cropped on large tuples

### ISSUE THREAD

**Issue by rybakit** [tarantool/tarantool#6166]
The extended ER_TUPLE_FOUND message was introduced in https://github.com/tarantool/tarantool/commit/d11fb3061e15faf4e0eb5375fb8056b4e64348ae. However, the change does not take into account that tuples can be large, which can lead to cropping the message in the middle and showing only the old tuple or even half a tuple.

* OS: MacOS
* OS Version: 10.15.7
* Architecture: amd64

Tarantool version: 2.8.1-0-ge2a1ec0c2

**Steps to reproduce**

```
#!/usr/bin/env tarantool

s = box.schema.space.create('foo')
s:create_index('primary', {unique = true, parts = {1, 'NUM', 2, 'STR'}})
s:insert{1, string.rep('_', 500)}
s:insert{1, string.rep('_', 500)}
```

How to run:

Just type `tarantool test.lua`.

**Actual behavior**

The "old" tuple is cropped and the "new tuple" part is not displayed.

**Expected behavior**

Both "old" and "new" tuples are fully displayed. 

_Ideally, it would be great to be able to access the old tuple from the error object, for example through `err.old_tuple`, so you don't have to parse the string to get the key of the conflicting tuple._

**Comment by kyukhin** [comment]
Maybe instead of printing values of arbitrary size we'll simply dump space name + primary key value for tuple caused conflict?

**Comment by rybakit** [comment]
> we'll simply dump space name + primary key value for tuple caused conflict

That would work in my case, too. But it would be really great if the error object could be extended to hold the old tuple. I implemented "ON DUPLICATE KEY UPDATE" MySQL's like behavior by using `insert()` + follow-up `update()` (read the details [here](https://stackoverflow.com/a/68081411/1160901)), but the problem is that the pk is auto incremental and can be omitted during the insert, so the only way to get it is to parse the error message. Do you think it's possible to add the `old_tuple` property to the error object so I can just refer to it without messing with the strings?
