### ISSUE TITLE
select() with key-value dictionary returns everything, it is dangerous

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#6167]
```Lua
box.cfg{}
s = box.schema.create_space('test')
_ = s:create_index('pk')
s:replace{1}
s:select({key = 'value'})
```
Result:
```
tarantool> s:select({key = 'value'})
---
- - [1]
...
```
Expected result: an error about invalid arguments. Otherwise on a huge table that might make tarantool process not responding for a long time and even die due to OOM.

**Comment by R-omk** [comment]
It seems to me it's time to provide the ability to enable something like a '_strict mode_', which, according to best practices, will disable some dangerous features, and if someone clearly needs them, then it is better to explicitly enable them at their own risk.

**Comment by olegrok** [comment]
Such query fails if engine will be changed to vinyl. I can assume that proper fix should unify behavior for both engines.

**Comment by drewdzzz** [comment]
The same problem with **fselect**.

**Comment by drewdzzz** [comment]
@R-omk what features are you talking about?

> It seems to me it's time to provide the ability to enable something like a '_strict mode_', which, according to best practices, will disable some dangerous features, and if someone clearly needs them, then it is better to explicitly enable them at their own risk.

**Comment by drewdzzz** [comment]
Actual behavior of select/get/fselect/pairs with key-value dictionary (possibly combined with array):
**Memtex**:
All of the above functions works only with the array part of given table (that's why given key-value dictionary is recognized as an empty array, so select{key = 'value'} == select{}).
**Vinyl**:
Fails with different errors (_ER_TUPLE_NOT_ARRAY_ or _ER_KEY_PART_TYPE_ )

**Comment by pgulutzan** [comment]
I guess this is a request that the default value of options.limit in space_object:select() should be small and settable by an administrator, vaguely like MariaDB's sql_select_limit
https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_sql_select_limit
If it's applied to SQL as well, then it must affect all statements that have a LIMIT clause, and only affects the final result
(so I can have a subquery that's not affected by the limit).
But in the long run I think what's needed is a grantable privilege for using lots of CPU and storage, regardless of tuple count.

**Comment by drewdzzz** [comment]
Fix for `vinyl` will not reduce its performance.
Fix for `memtx` will reduce its performance by 10% on average (1,1 MRPS at master vs 0,99 MRPS with the patch) with sizes of selected tuples == 1 (decrease will intensify if tuples are bigger). 
We need to choose between usability and performance.

**Comment by Totktonada** [comment]
I would also highlight #6655. It seems, we need more powerful validation here.
