### ISSUE TITLE
getting "attempt to index field 'primary' (a nil value)" in lua procedure while space:truncate() call from admin console

### ISSUE THREAD

**Issue by zlobspb** [tarantool/tarantool#618]
getting "attempt to index field 'primary' (a nil value)" in lua procedure while space:truncate() call from admin console

Tarantool 1.6.3-573-gfabb121

**Comment by rtsisyk** [comment]
I discussed this bug with @kostja. The best fix is to make drop/create index in single transaction to prevent fiber_yield() during wal_write();

**Comment by rtsisyk** [comment]
=> use transaction in space_truncate()

**Comment by bigbes** [comment]
https://gist.github.com/089854ba4788a7a47e96cbe07ca5d2d8

**Comment by rtsisyk** [comment]
A quick idea from @kostja how to fix this problem:
- Add `version` member to the space options in box.space._space
- Truncate the space when version has changed

**Comment by kostja** [comment]
Fixed in 1.7.4-139-g2561456
