### ISSUE TITLE
new release policy: change version format for pre-releases (X.Y.Z-betaN and so on)

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#6183]
The main discussion about the new release policy is [here](https://github.com/tarantool/tarantool/discussions/6182).

The relevant section of the new policy description is the following:

> ## Version naming
>
> Everything spins around the three digit release naming like `3.1.2`. Here the
> release series is `3` (major version). `3.1` identifies a feature set, the
> minor version is increased with new features. `3.1.2` and `3.1.3` may differ by
> fixed bugs.
>
> During early development we publish alpha, beta and release candidates, they
> are marked this way: `3.0.0-alphaN`, `3.0.0-betaN`, `3.0.0-rcN` (`N` is a
> number).
>
> During the support stage we also can publish a release candidate, it'll be
> marked similarly: `3.2.0-rcN`.
>
> Nightly builds are marked this way: `git describe --always --long`-dev.
> Together with the development flow (described below) it gives names like so:
> `3.0.0-alpha1-14-gxxxxxxxxx-dev`, `3.1.2-5-gxxxxxxxxx-dev` and even
> `3.0.0-entrypoint-17-gxxxxxxxxx-dev`.

We should ensure that the version is correctly reported in all places:

* tarantool --version
* _TARANTOOL
* box.info.version
* require('tarantool')
* iproto and console greetings
* C module API

Ensure that it will not break:

* connectors (which may lean on certain data format in the iproto greeting packet);
* replication (the same);
* modules (which may check tarantool version in runtime).

Not sure that it is possible to implement it without any breakage, but at least we should elaborate all such places, update modules/connectors/tarantool itself and provide a good description, what may going wrong and how to fix it (compatibility matrix).

Or, maybe, keep the old version format in critical places (such as iproto greeting) and provide a version in the new format separately.

I don't know, what will be the best solution, we should investigate it.

**Comment by locker** [comment]
> We should ensure that the version is correctly reported in all places:
> 
> - tarantool --version
> - _TARANTOOL
> - box.info.version
> - require('tarantool')
> - **iproto and console greetings**
> - C module API

Why do we need to change the greeting? AFAIK it's only used by connectors and other Tarantool instances to check if a certain feature is available on the server, and it isn't visible to the end-user. Currently, the greeting includes only major.minor.patch, i.e. it doesn't even include git commit sha. I don't think we need to include a release marker (-dev, -rc, etc) into it, because connectors don't need this information. Besides, changing the greeting string is dangerous, since it may break connectors and/or older Tarantool versions, and it'd be really difficult to check that.

As for other places - they all report PACKAGE_VERSION string, which is set in the make file, so changing it should fix them all.

**Comment by locker** [comment]
> Or, maybe, keep the old version format in critical places (such as iproto greeting) and provide a version in the new format separately.

One can already query the version via `eval('box.info.version')`, which should be safe to change to the new format.

**Comment by locker** [comment]
If there actually may be a difference in the feature set between say 3.5.1-alpha1 and 3.5.1-alpha2, which a connector would like to be aware of, we'd better add a separate iproto message for reporting the feature set (#6253) instead of relying on a client correctly parsing the version string with an arbitrary suffix reported in a greeting message.

**Comment by Totktonada** [comment]
I don't mind this plan. I would even say that if we'll publish 3.5.1-alpha2 and support its new features in a connector, it should be okay to break compatibility of the connector with 3.5.1-alpha1. And, it seems, the time to implement a more general features testing mechanism comes now.

**Comment by Totktonada** [comment]
My expectation was that if we'll build a non tagged commit, we'll get a version with the `-dev` suffix from `tarantool --version` (and other sources of the version string). I [marked](https://github.com/tarantool/tarantool/commit/9707a7bdcd24397d080db4e9e3da3676c7220e0c) packages this way. Can we do the same for the version reporting from inside tarantool?

**Comment by Totktonada** [comment]
We need a packpack side support for compiling a version in a certain format into tarantoool that is built from a tarball (including packaging into RPM / Deb files). See the [discussion](https://github.com/tarantool/tarantool/pull/6382#discussion_r694809678) in the PR. I filed the issue about this: https://github.com/packpack/packpack/issues/140.

**Comment by Totktonada** [comment]
I agree that we shouldn't change the three-number version in the protocol greetings: neither in the binary protocol, nor the console text protocol. This change would be breaking for connectors and it is highly undesirable.

Also I'm not so sure now that it worth to change format of the string version in `tarantool --version`, `_TARANTOOL`, `box.info.version`, `require('tarantool').version`, `PACKAGE_VERSION` in `tarantool/module.h` and stderr output on the first line at starting tarantool interactively. Many modules, CI scripts and tools rely on it.

I agree with Vladimir's point regarding reliability of the git hash comparing to just numbers (see the linked pull request). Also now I doubt that we should add the `-dev` suffix right into the version string.

I'll close the issue, because, maybe, the best what I can do is to do nothing. The main problem regarding building packages for pre-releases was resolved in #6184, while `tarantool --version` works correctly without any changes.

I'll update the release policy [discussion](https://github.com/tarantool/tarantool/discussions/6182) soon[^1] to reflect this vision in order to start a discussion about less breaking ways to deliver a user-friendly build information to users. Say, add another line into `tarantool --version` output, which will describe the build for humans: is it release, pre-release, developer build.

I still think that https://github.com/packpack/packpack/issues/140 would be the good build process refactoring, but now I consider it as just refactoring, not a feature that we need to change `tarantool --version`.

[^1]: Current document version is 7, the update will be in the version 8.
