### ISSUE TITLE
new release policy: adjust download.tarantool.org infrastructure

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#6186]
The main discussion about the new release policy is [here](https://github.com/tarantool/tarantool/discussions/6182).

Since we [plan](https://github.com/tarantool/tarantool/issues/6185) to add repositories with a bit different layout (`series-2`, `pre-release`), we should adjust download.tarantool.org redirections and ensure that everything works good.

NB: Don't forget about source tarballs.

**Comment by VitaliyaIoffe** [comment]
Now next paths redirect requests to S3 
```
https://download.tarantool.org/tarantool/pre-release/series-2/<os>/
https://download.tarantool.org/tarantool/pre-release/series-2/<os>/<dists>
https://download.tarantool.org/tarantool/release/series-2/<os>/
https://download.tarantool.org/tarantool/release/series-2/<os>/<dists>
```
Also, wфыe added gpgkey `https://download.tarantool.org/tarantool/series-2/gpgkey`
