### ISSUE TITLE
Tarantool пишет логи в /var/log/boot.log

### ISSUE THREAD

**Issue by kdy999** [tarantool/tarantool#6187]
**Bug description**

Tarantool пишет логи в /var/log/boot.log

* OS: RedHat (CentOS)
* OS Version: 7, 8
* Architecture: [amd64, arm]
* tarantool 2.7.2, 2.8.1

**Steps to reproduce**

Инстансы Taratool пишут свои логи в файл /var/log/boot.log

Судя по документации должно быть так:

https://www.tarantool.io/ru/doc/latest/reference/configuration/:
В настоящий момент настройка syslog:facility не учитывается, но будет использоваться в дальнейшем. Ее значением должно быть одно из ключевых слов syslog, которые сообщают программе syslogd, куда отправлять сообщение. Возможные значения: auth, authpriv, cron, daemon, ftp, kern, lpr, mail, news, security, syslog, user, uucp, local0, local1, local2, local3, local4, local5, local6, local7. 
**По умолчанию: user.**

Однако по исходникам не так (lib/core/say.c):
        if (opts.facility == syslog_facility_MAX)
                log->syslog_facility = SYSLOG_LOCAL7;
        else
                log->syslog_facility = opts.facility;

local7 - это как раз сообщения при загрузке системы (boot.log), по крайней мере, для RHEL-based дистрибутивов.

Обходное решение:
TARANTOOL_LOG=syslog:facility=user

**Comment by kyukhin** [comment]
Let's fix the default in documentation to local7.

**Comment by kdy999** [comment]
Поправить документацию - самая простая, но плохая идея.
Т.к. файл boot.log предназначен для сообщений при загрузке системы и обнуляется каждый раз при перезагрузке, поэтому не участвует в logrotate системных логов.
Однако Tarantool при выставленном **local7** (по умолчанию) пишет в этот файл свои логи очень активно, в результате чего файл быстро распухает до десятков гигабайт. 
Так что правильно будет сделать **user**, a не **local7**.

**Comment by kyukhin** [comment]
local7 таковым является только на [RHEL](https://www.oreilly.com/library/view/linux-security-cookbook/0596003919/ch09s27.html):
```
# Red Hat usurps the local7 facility for boot messages from init scripts
local7.*                        /var/log/boot.log
```

 Менять умолчания испортит апгрейд.
