### ISSUE TITLE
bring back memcache to tarantool 1.6

### ISSUE THREAD

**Issue by s-stupnikov** [tarantool/tarantool#620]
subj
disappearance of memcache protocol support was justified with assumption that "no one using it". Nothing can be further from the truth, because, for example, it's under use in several departments at MRG. Plus, some third-party tools build upon memcache protocol.
Long story short,  disappearance of memcache complicates transition to 1.6, increases developer burden and makes it harder to integrate with third-party tools.

**Comment by kostja** [comment]
Done, check out https://github.com/tarantool/memcached
