### ISSUE TITLE
Reduce number of logs produced during snapshoting

### ISSUE THREAD

**Issue by no1seman** [tarantool/tarantool#6220]
As for now on big instances core produces too much logs related to shapshoting:
...
Jul 15 15:04:58 server1 cartridge.app-r01-s01[34567]: snapshot/101/main C> 15.2M rows written
Jul 15 15:04:58 server1 cartridge.app-r01-s01[34567]: snapshot/101/main C> 15.3M rows written
Jul 15 15:04:58 server1 cartridge.app-r01-s01[34567]: snapshot/101/main C> 15.4M rows written
Jul 15 15:04:58 server1 cartridge.app-r01-s01[34567]: snapshot/101/main C> 15.5M rows written
Jul 15 15:04:58 server1 cartridge.app-r01-s01[34567]: snapshot/101/main C> 15.6M rows written
Jul 15 15:04:58 server1 cartridge.app-r01-s01[34567]: snapshot/101/main C> 15.7M rows written
...

Such logs is about 80% of all instance logs and seems that it's not OK. Need to reduce them because it's quite diffcult to find smth usefull in tons of such logs and also logs occupy to much volume.

**Comment by RunsFor** [comment]
We have about 180M rows on storage, so it is about 1800k messages for each instance on a server each `checkpoint_interval` seconds. There are also similar messages (`rows received`) during replica rebootstrap. It doesn't happen such often, but anyways feels redundant.
