### ISSUE TITLE
Add aarch64 binary packages for Linux distributions

### ISSUE THREAD

**Issue by igormunkin** [tarantool/tarantool#6222]
Since we are going to announce ARM64 support in the upcoming release, we need to prepare CI routines for building aarch64 binary packages for Linux distributions.

**Comment by VitaliyaIoffe** [comment]
Blocked, cause now `update_repo.sh` doesn't support arch!=x86_64. It brings collisions connected with wrong directories and problems with metainformation. 

Suggest changing the approach from `update_repo.sh` to `rws`.

**Comment by ylobankov** [comment]
> Blocked, cause now `update_repo.sh` doesn't support arch!=x86_64. It brings collisions connected with wrong directories and problems with metainformation.
> 
> Suggest changing the approach from `update_repo.sh` to `rws`.

Unblocked by https://github.com/tarantool/tarantool/pull/6641. We fully migrated to RWS and `arm` packages are deployed via it. So closing the issue.
