### ISSUE TITLE
Bump luarocks 

### ISSUE THREAD

**Issue by rosik** [tarantool/tarantool#6223]
It's time to upgrade

See also: https://github.com/tarantool/enterprise/issues/55 (a bug from a customer)

**Comment by Mons** [comment]
Also set `FORCE_CONFIG=false` in `extra/luarocks/hardcoded.lua` to allow loading of project-side `.rocks/config-5.1.lua`

**Comment by DifferentialOrange** [comment]
See also https://github.com/tarantool/cartridge/issues/1834

**Comment by locker** [comment]
Duplicate #6597
