### ISSUE TITLE
Support DUALNUM mode in luajit-gdb

### ISSUE THREAD

**Issue by Buristan** [tarantool/tarantool#6224]
For x86/x64 `LJ_DUALNUM` mode is disabled. But for some other arches (arm or arm64, for example) it is enabled by default.
luajit-gdb displays integers in `LJ_DUALNUM` mode as `nan`-s (`1` for example):

```
(gdb) lj-tv 0x7fb7d66938
number -nan(0x9000000000001)
```

But it is nothing but an integer:
```
p *(TValue *)0x7fb7d66938
$218 = {u64 = 18444773748872577025, n = -nan(0x9000000000001), gcr = {gcptr64 = 18444773748872577025}, it64 = -1970324836974591, {i = 1, it = 4294508544}, ftsz = -1970324836974591, u32 = {lo = 1,
    hi = 4294508544}}
(gdb) p LJ_DUALNUM
$226 = 1
(gdb) p tvisint((TValue *)0x7fb7d66938)
$227 = 1
```

**Comment by igormunkin** [comment]
The issue is resolved in scope of tarantool/luajit@6469d70. The submodule was updated in tarantool in 2.9.0-302-gba5398c7d (ba5398c), 2.8.1-198-g6dd397349 (6dd3973), 2.7.2-191-gb3cb4bbba (b3cb4bb), 1.10.10-71-gfea79e2c2 (fea79e2).
