### ISSUE TITLE
Assertion failed when casting -0.5 to unsigned

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#6225]
I have Ubuntu 20.04. I have Tarantool 2.9, pulled from source today.
I enter this SQL statement:
SELECT CAST(-0.5 AS UNSIGNED);
The result is:
tarantool: /home/pgulutzan/tarantool-master/src/lib/msgpuck/msgpuck.h:1732: mp_sizeof_int: Assertion `num < 0' failed.
Aborted (core dumped)

**Comment by ImeevMA** [comment]
This issue is similar to #6010. I will fix both.
