### ISSUE TITLE
sql: lack of long double on Mac M1 results in test fail

### ISSUE THREAD

**Issue by Korablev77** [tarantool/tarantool#6239]
From #6059:

```
box.cfg{}
--box.execute('set session "sql_vdbe_debug" = true;')
for i = 1, 10000  do
    local pow = math.random(100)
    local x = math.pow((math.random()-0.5)*2*math.random(), pow)
        local y = box.execute(string.format("SELECT %s=CAST(quote(%s) AS NUMBER)",x, x)) 
        if y['rows'][1][1] == false then  
                require('log').error(y.rows[1][1]) 
                os.exit()
        end
end
```

The thing is in `quoteFunc()` and in particular in `sqlVXPrintf`: for precise floating point arithmetics it relies on long double (`LONGDOUBLE_TYPE`) type. However, on Mac M1 `sizeof(long double) == sizeof(double)`: https://developer.apple.com/forums/thread/673482
This leads to false evaluation of `%s=CAST(quote(%s) AS NUMBER)` comparison rarely.

**Comment by ImeevMA** [comment]
There is more than one ways to fix this problem:
1) Make quote() return double in case it receive double. This will be done anyway.
2) Replace `long double` by `double`.
3) Drop sql/printf.c (in this case long double won't be used anywhere).

I plan to do the first and the third.
