### ISSUE TITLE
lua: getting number as argument instead of table on M1

### ISSUE THREAD

**Issue by drewdzzz** [tarantool/tarantool#6248]
From #6059 

**Bug description**

Function `dispatch_response_iproto` from `net_box.lua` gets number instead of table as argument `hdr` resulting in failed `box/push` test on M1 without Lua-JIT.

**Snippet failing the test**
```
box.cfg{listen = 3301}
netbox = require('net.box')
c = netbox.connect(box.cfg.listen)
ok = nil
err = nil
messages = {}
t = setmetatable({100}, {__serialize = function() error('err in ser') end})
function do_push() ok, err = box.session.push(t) end
box.schema.func.create('do_push')
box.schema.user.grant("guest", "execute", "function", "do_push")
c:call('do_push', {}, {on_push = table.insert, on_push_ctx = messages})
```
The thing is if we remove error from `__serialize` then `hdr` will be a table.

**Actual behavior**

`error: 'builtin/box/net_box.lua:584: attempt to index local ''hdr'' (a number value)'`

Test framework shows this error. Tarantool just fails with no error due to attempt to index a number.

**Expected behavior**

```
ok, err
- null
-- '[string "t = setmetatable({100}, {__serialize = functi..."]:1: err in ser'
```

**Comment by igormunkin** [comment]
The issue is resolved in 2.9.0-275-g027775ff2 (027775f). The fix is also backported to 2.8.1-175-g44a7ba72c (44a7ba7), 2.7.2-168-geb9344911 (eb93449), 1.10.10-70-g21b444c83 (21b444c).
