### ISSUE TITLE
Add a few predefined system events for pub/sub:

### ISSUE THREAD

**Issue by unera** [tarantool/tarantool#6260]
event system is designed here: https://github.com/tarantool/tarantool/issues/6257

Predefined system events:

- `tnt_ro` (`true|false`) - box.info.ro state
- `tnt_term` (`integer`) - RAFT term
- `tnt_gfs` (`false|true`) - Graceful shutdown state

[RFC](https://docs.google.com/document/d/1mZDLtbvTHLWKNP5dP5TKZkQoUxi3l4GCPFPrxS9aGfE/edit?usp=sharing)

**Comment by Gerold103** [comment]
We can also define an event signaled on schema version change. It would allow the clients to download a new schema before more requests come.
