### ISSUE TITLE
DDL lock

### ISSUE THREAD

**Issue by locker** [tarantool/tarantool#6264]
Even though both vinyl and memtx now support mvcc (i.e. it is possible to yield inside a transaction), the space cache still doesn't support versioning: we create a new space struct on each DDL operation involving the space and delete the old space struct on completion. As a result, a race between DDL and DML can result in all kinds of bugs, from crashes (#5998, #6140) to missing data (#6263). 

We fix these issues by aborting concurrent DML transactions from a DDL operation (commit for vinyl: d3e12369565151ba8c0632a84adab4bf90eff23f), but this behavior is unexpected from users' point of view, especially if a DDL operation doesn't actually change space format or indexes, but just updates some unrelated space option, like is_sync (#5603). Another problem with this approach is that we don't clean up pointers to a deleted space from all data structures, e.g. [`txn_stmt`](https://github.com/tarantool/tarantool/blob/b1ee4e59b6450812fb68f34144d7ac7d639623bc/src/box/txn.h#L187) will still contain the pointer after a vinyl transaction is aborted and we are lucky that rollback doesn't try to dereference it. This makes the code fragile, although correct. Should we want to try to log rollbacks, we will probably get a crash (by trying to read space name or id), but not necessarily - the code might just work until it crashes production one day.

The right way to resolve this problem would be introducing schema versioning, but all the benefits of having this feature do not justify the tremendous amount of work needed to implement it. So we suggest a compromise solution, which would avoid conflicts in most cases - locking :-)

The idea is to add a per space RW lock for serializing DDL and DML operations. A DML transaction would take the lock for reading before beginning a statement for a space and hold it until commit. A DDL operation would take the lock for writing to update the space cache. This should guarantee that once we update the space cache, no transactions pointing to the old space struct will remain. Apparently, this solution doesn't guarantee progress - a DML transaction might never complete and hence a DDL would get stuck forever waiting for the lock. The suggested solution for this is timeouts :-) If a DML transaction fails to take a lock for T seconds, it aborts itself and returns an error. If a DDL transaction fails to take a lock for T seconds, it rolls back all DML transactions involving the space and proceeds with space cache change. For the most common case, when there's no long lived transactions, this approach will thus result in no conflicts, which is positively a step forward. We will also use the lock to avoid aborting in-flight transactions before building an index or checking format, like [we do now](https://github.com/tarantool/tarantool/blob/b1ee4e59b6450812fb68f34144d7ac7d639623bc/src/box/vinyl.c#L4191). Instead we will install the on-replace trigger that propagates changes to a newly built index under the space lock taken exclusively, thus guaranteeing that all in-flight transactions have been committed by the time we start traversing the space.

**Comment by kostja** [comment]
If  DDL has priority over DML, DML will have to yield where it didn't, so it's going to break applications. If DML has priority over DDL, DDL will starve out.

**Comment by locker** [comment]
The idea was to take the lock in exclusive mode only for space_cache_replace, which doesn't yield. This means that if mvcc is disabled, there will be no behavior changes for memtx users. If mvcc is enabled, a DML operation may indeed yield, but only if there's another explicitly yielding DML operation. That is, if one just enables mvcc for the old code, everything will work just fine, but if one creates a function that yields in a transaction, the old code may start to yield.

Discussed with @alyapunov and @unera. Agreed that even this change may break users. @unera suggested to use one lock for all spaces and take it in `box.begin()`, but even this is potentially dangerous, because currently `box.begin()` doesn't yield, neither for memtx nor for vinyl. Fixing a test (#5603) doesn't justify the potential risk.

Seems there's no other way but to leave the current behavior as is: abort all DML on DDL.

**Comment by kostja** [comment]
@locker you're quite capable of doing versioned data dictionary. the issue is fuzzy testing transactional ddl which @kyukhin promised to do 3 years ago and it's still not done. people were running some fuzzying on vinyl ddl and getting weird errors, tickets will be filed.
