### ISSUE TITLE
Fiber can't be canceled before the first yield

### ISSUE THREAD

**Issue by rosik** [tarantool/tarantool#6276]
**Bug description**

* OS: Linux
* OS Version: Ubutnu 20.04
* Architecture: x86_64

```console
$ tarantool --version
Tarantool 2.9.0-184-gb0cd298a7
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/opt/tarantool-install -DENABLE_BACKTRACE=ON
Compiler: /usr/bin/cc /usr/bin/c++
C_FLAGS: -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type
CXX_FLAGS: -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type
```

**Steps to reproduce**

Run the following shell script:

```bash
tarantool -l fiber -e "f = fiber.new(print, [[Haha, I'm alive]]) f:cancel() print('Fiber canceled')"
```

**Actual behavior**

```console
$ tarantool -l fiber -e "f = fiber.new(print, [[Haha, I'm alive]]) f:cancel() print('Fiber canceled')"
Fiber canceled
Haha, I'm alive
```

**Expected behavior**

Only "Fiber canceled" should be printed.

**Comment by Gumix** [comment]
This is the expected behaviour. The [doc](https://www.tarantool.io/en/doc/latest/reference/reference_lua/fiber/#fibers) says:

> However, [fiber_object.cancel](https://www.tarantool.io/en/doc/latest/reference/reference_lua/fiber/#fiber-object-cancel) is advisory — it works only if the runaway fiber calls [fiber.testcancel()](https://www.tarantool.io/en/doc/latest/reference/reference_lua/fiber/#fiber-testcancel) occasionally.

**Comment by Gumix** [comment]
Filled https://github.com/tarantool/doc/issues/2993 to make the documentation a bit more clear on this.
