### ISSUE TITLE
Wrong result from trim()

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#6278]
I have Ubuntu 20.04. I have Tarantool 2.9, pulled from source today.
I execute this statement:
SELECT TRIM(TRAILING 'xd' FROM 'd');
The result is a blank string.
I expected 'd' because 'xd' does not appear in the FROM string.

**Comment by ImeevMA** [comment]
This is not incorrect behavior. the argument before `FROM` tells us not the substring, but the characters to be discarded.
