### ISSUE TITLE
Export libsmall symbols to prevent version mismatch

### ISSUE THREAD

**Issue by DragonF0rm** [tarantool/tarantool#6286]
I'm writing tarantool module in C and facing some crashes when calling `small_alloc_create` because my system libsmall version (latest release in official RPM repos) does not match one statically linked with tarantool. The reason is that tarantool partially exports libsmall symbols and the wrong function version is being executed when calling one. Can we export libsmall symbols like you've done it with libcurl here #4559?
```
[root@dddev1 m.uymin]# tarantool --version
Tarantool 2.7.2-0-g4d8c068
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_BACKTRACE=ON
Compiler: /opt/rh/devtoolset-8/root/usr/bin/cc /opt/rh/devtoolset-8/root/usr/bin/c++
C_FLAGS:-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type -Werror
CXX_FLAGS:-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type -Werror

[root@dddev1 m.uymin]# which tarantool
/usr/bin/tarantool

[root@dddev1 m.uymin]# nm -gD /usr/bin/tarantool | grep -i small
00000000007fb870 T small_alloc_create
00000000007fbd70 T small_alloc_destroy
00000000007fba70 T small_alloc_setopt
00000000007fcf30 T small_class_create
00000000007fba90 T smalloc
00000000007fbdf0 T small_stats
00000000007f8ff0 T small_test_feature
```

**Comment by Totktonada** [comment]
We want to fix it by hidding the symbols, see #5932 (it'll land to the near release).

Exporting them would not solve the problem entirely, because of several reasons:

1. libsmall has some definitions right in the header files, which could be inlined by the compiler.
2. A new function could be added and if tarantool's small version is older than the system one, we'll call everything from tarantool, but this new function from the system library.

**Comment by Totktonada** [comment]
In fact, direct exporting of a library symbols looks as the problematic way in the general case. See https://github.com/tarantool/smtp/pull/32 and https://github.com/tarantool/smtp/pull/33.

**Comment by Totktonada** [comment]
As for me, it seems that bundling libsmall into the project (the same version as we have in tarantool-1.10 and later) as a static library is the best option for now: it'll work with all recent tarantool versions (even despite symbols clash). See also https://github.com/tarantool/memcached/pull/60.
