### ISSUE TITLE
Trino/Presto Tarantool Connector

### ISSUE THREAD

**Issue by kokizzu** [tarantool/tarantool#6288]
Currently there's no connector for trino/presto for Tarantool (while other databases already have)

https://trino.io/docs/current/connector.html

trino (fork of presto) is currently number 1 distributed query engine (can query and join from multiple datasource/database) for analytics use cases

**Comment by Totktonada** [comment]
Something that looks similar for me: https://loopback.io/doc/en/lb3/Database-connectors.html

**Comment by NeraverinTarantool** [comment]
We do not plan to add such a connector in the coming year. Without clustered SQL, Trino/Presto's ability to work with Tarantool would be very limited.
