### ISSUE TITLE
Dpkg warning that doesn't support architecture 'i386'

### ISSUE THREAD

**Issue by rosik** [tarantool/tarantool#6289]
I've installed tarantool with the installer script:

```
curl -L https://tarantool.io/release/2.8/installer.sh | bash
```

Whenever I run `sudo apt update`, I see the warning:

```
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://download.tarantool.org/tarantool/2.8/ubuntu focal InRelease' doesn't support architecture 'i386'
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://download.tarantool.org/tarantool/modules/ubuntu focal InRelease' doesn't support architecture 'i386'
```

The i386 architecture is installed in my system but treated as foreign:

```console
$ dpkg --print-architecture
amd64
$ dpkg --print-foreign-architectures
i386
```

The warning can be suppressed by modifying apt sources list as follows:

```
deb [arch=amd64] https://download.tarantool.org/tarantool/2.8/ubuntu/ focal main
deb  [arch=amd64] https://download.tarantool.org/tarantool/modules/ubuntu/ focal main
```

Let's update the installer script and the doc accordingly.

* OS: Linux
* OS Version: Ubuntu 20.04
* Architecture: amd64

**Comment by Totktonada** [comment]
Is not it the same as https://github.com/tarantool/doc/issues/2252?

**Comment by rosik** [comment]
Lol. Yes. But it's still not fixed.

Closing as a duplicate.
