### ISSUE TITLE
Strange segfault without backtrace in __serialize.

### ISSUE THREAD

**Issue by EvgenyMekhanik** [tarantool/tarantool#6300]
#! /PATH_TO_TARANTOOL
net_box = require('net.box')

box.cfg{
        listen = "/tmp/1"
}
conn = net_box.connect("/tmp/1")
t = setmetatable({}, {
    __serialize = function()
        return conn.space
end})

require('console').start()

-- Try to serialize 't', causes to segfault
t

**Comment by Totktonada** [comment]
Looks like problem B from #3228.
