### ISSUE TITLE
Cartridge compatibility broken 

### ISSUE THREAD

**Issue by rosik** [tarantool/tarantool#6306]
## Bug description

In 954194a1ca5c2cd1826a8a689663c827313dbbef (https://github.com/tarantool/tarantool/issues/6241) the internals of `netbox.future` object was changed. Now it's a userdata. In previous versions, it used to be a Lua table. The errors module puts there `func_name` and `conn` for the sake of pretty error formatting:

https://github.com/tarantool/errors/blob/21405a7c5d6773fc306e730692b49803743edfe0/errors.lua#L388-L397

https://github.com/tarantool/errors/blob/21405a7c5d6773fc306e730692b49803743edfe0/errors.lua#L444-L451

## Steps to reproduce

```bash
git clone git@github.com:tarantool/errors.git
cd errors
tarantoolctl rocks install luatest
.rocks/bin/luatest
```

```console
$ .rocks/bin/luatest
.............E.

Tests with errors:
------------------

1) unit.netbox.test_errors_netbox_wait_async
/tmp/tmp.AuChC2kkcg/errors/errors.lua:394: attempt to index local 'future' (a userdata value)
stack traceback:
        /tmp/tmp.AuChC2kkcg/errors/test/unit/netbox_test.lua:227: in function 'unit.netbox.test_errors_netbox_wait_async'
        ...
        [C]: in function 'xpcall'

Ran 15 tests in 0.237 seconds, 14 successes, 1 error

Failed tests:

unit.netbox.test_errors_netbox_wait_async
```

```console
$ tarantool --version
Tarantool 2.9.0-247-ged7da7e63
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/opt/tarantool-install -DENABLE_BACKTRACE=ON
Compiler: /usr/bin/cc /usr/bin/c++
C_FLAGS: -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type
CXX_FLAGS: -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type
```

**Comment by locker** [comment]
Ready for review: https://lists.tarantool.org/pipermail/tarantool-patches/2021-August/025346.html

**Comment by rosik** [comment]
Supposing netbox future object remains a userdata (because I don't want to revert the whole patch) the modern `errors` module is doomed. So I'm going to release 2.7.1 anyway.

But, before that we need few enhancements in the tarantool itself and in the errors module:

1. Remove excess yield from future:wait(0) (on review)
1. https://github.com/tarantool/tarantool/issues/6314
1. Stop using net.box internals: https://github.com/tarantool/errors/pull/40 (on review)
