### ISSUE TITLE
Add a filter to the test system to hide line numbers in error() message

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#634]
```
Test failed! Result content mismatch:
--- big/iterator.result	Thu Nov 20 15:48:08 2014
+++ big/iterator.reject	Wed Nov 26 14:55:14 2014
@@ -891,7 +891,7 @@
 -- Test cases for #123: box.index.count does not check arguments properly
 space.index['primary']:pairs(function() end, { iterator = box.index.EQ })
 ---
-- error: 'builtin/msgpackffi.lua:264: can not encode Lua type: ''function'''
+- error: 'builtin/msgpackffi.lua:262: can not encode Lua type: ''function'''
```
Please add a filter to replace `builtin/(.+)\.lua:(\d+`) with `builtin/(.+)\.lua` in all test suites, including app/.

**Comment by kostja** [comment]
I don't think it's a good idea: we can go pretty far on that path, log filtering, etc.
We need more ways to test the server, since so many things are not testable well with the current framework, rather than try to make the current functional framework perfect for everything.

**Comment by kostja** [comment]
mejedi created an stdout filter which is now used almost everywhere, so I think this can be closed.

**Comment by kostja** [comment]
I'm closing this per above comment.

**Comment by rtsisyk** [comment]
OK. I agree.
