### ISSUE TITLE
Backport commit for fix recording of `string.char()` without arguments

### ISSUE THREAD

**Issue by Buristan** [tarantool/tarantool#6371]
Reproducer:

```sh
src/tarantool -e '
for i = 1, 100 do local s = string.char() end
'
tarantool: lj_record.c:137: rec_check_slots: Assertion `itype2irt(tv) == ((IRType)(((tr)>>24) & IRT_TYPE))' failed.
Aborted
'
```

The issue is fixed via commit LuaJIT/LuaJIT@dfa692b7 in the upstream.

**Comment by igormunkin** [comment]
The issue is resolved in scope of tarantool/luajit@f3e4906. The submodule was updated in tarantool in 2.10.0-beta2-68-g87461d5c7 (87461d5), 2.8.3-26-g5c7464403 (5c74644), 1.10.12-24-gb3982d4d0 (b3982d4).
