### ISSUE TITLE
Assertion when inserting a decimal number in a scalar column containing 1.8e308

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#6377]
I have Ubuntu 20.04. I have Tarantool 2.10, pulled from source today.

I say:
CREATE TABLE t (s1 SCALAR PRIMARY KEY);
INSERT INTO t VALUES (1.8e308),(CAST(1.1 AS DECIMAL));
Result:
tarantool: /home/pgulutzan/tarantool-master/src/lib/core/decimal.c:237: decimal_compare: Assertion `decimal_check_status(&res, &decimal_context) != NULL' failed.
Aborted (core dumped)

**Comment by ImeevMA** [comment]
This is not SQL problem:
```
tarantool> s = box.schema.space.create('T', {format={{'S', 'scalar'}}})
---
...

tarantool> i = s:create_index('i')
---
...

tarantool> s:insert({1e400})
---
- [inf]
...

tarantool> s:insert({require('decimal').new(1.1)})
tarantool: /home/mergen/work/dev/src/lib/core/decimal.c:237: decimal_compare: Assertion `decimal_check_status(&res, &decimal_context) != NULL' failed.
Aborted (core dumped)
```

Also, I was able to reproduce it on Tarantool 2.8.0. @sergepetrenko could you look into it?
