### ISSUE TITLE
Tarantool process stuck on futex on restart

### ISSUE THREAD

**Issue by DifferentialOrange** [tarantool/tarantool#6381]
**Bug description**

After restart, Tarantool process is stuck on bootstrap.

* OS: Linux
* OS Version: CentOS 7
* Architecture: amd64

Tarantool Enterprise 1.10.10-0-gaea7ae77a-r406

**Steps to reproduce**

The issue is happened on customer test zone. I do not have a pure reproducer, but similar situations happened several times so I think I'll be able to provide some additional info if needed. 

The timeline is as follows.
1. Tarantool instance is restarted by [supervisor](http://supervisord.org/) due to unknown reasons.
2. After bootstrap, Tarantool instance fails with "not enough memory" while doing vshard bucket discovery. The reason highly likely is our application bug.
3. Tarantool instance is restarted by supervisor after fail.
4. Index bootstrap fails with the following error.
    ![image](https://user-images.githubusercontent.com/20455996/130597421-1b7bbbc6-1a06-40f8-83c6-b0d23e78aee1.png)
5. Tarantool instance is restarted by supervisor after fail.
6. Tarantool tries to bootstrap spaces. 
![image](https://user-images.githubusercontent.com/20455996/130597553-36ce4476-c830-46ec-9012-7b44510ab62a.png)

At the same time (a bit after it), some Tarantool instances from the same cluster running on the same server also catch "not enough memory".

**Actual behavior**

Tarantool instance is considered to be dead by other cluster instances. It is impossible to connect to this instance with `tarantoolctl`. There are no new messages in log. The last ones are shown above.

At the same time, supervisor status of this process is RUNNING.

![ps all](https://user-images.githubusercontent.com/20455996/130598480-edeacf62-28b6-4a6d-aed4-c753731a47ba.png)

**Expected behavior**

If Tarantool is unable to bootstrap, process exits with some error so it is possible for supervisor to restart it and try again.

**Comment by AnastasMIPT** [comment]
The bug did not reproduce.
