### ISSUE TITLE
get SOPHIA_BUILD from git failed

### ISSUE THREAD

**Issue by dedok** [tarantool/tarantool#639]
```
$ cd build && cmake ../ && make
...
[  4%] Generating third_party/sophia
[  4%] Generating third_party/sophia/sophia/libsophia.a
fatal: Not a git repository: ../../.git/modules/sophia
fatal: Not a git repository: ../../.git/modules/sophia
```
SOPHIA v1.2

**Comment by kostja** [comment]
Which command fails? cmake .. works fine if you're building in a clean git tree. Did you make git clean -qfxd first? Did you do git submodule update --init?

I rechecked out-of-source builds with sophia, they work OK.
