### ISSUE TITLE
Authenticate via role

### ISSUE THREAD

**Issue by parihaaraka** [tarantool/tarantool#6424]
Due to the hard limit on the number of users/roles we could serve users distinction within a role by means of `on_auth` trigger. Just pass a password to the trigger when user name is a role.

**Comment by parihaaraka** [comment]
More generalized solution is to pass all auth arguments to on_auth triggers when initial user is not found. Somehow the efficient user (or set of roles) has to be set by the trigger in case of successful authentication.
* It would be nice to have password processing functions being exposed :)

**Comment by parihaaraka** [comment]
[PR](https://github.com/tarantool/tarantool/pull/6673)

**Comment by NeraverinTarantool** [comment]
We do not plan such changes in Tarantool. In our opinion, it is more correct to eliminate restrictions on the number of users and roles.
