### ISSUE TITLE
Drop error_marshaling_enabled session setting

### ISSUE THREAD

**Issue by locker** [tarantool/tarantool#6428]
Before version 2.4.1, Tarantool encoded errors in msgpack as strings. In 2.4.1 a new msgpack extension was introduced for errors. An error encoded in the new format includes an error code and a stack trace.

In order not to break compatibility with old connections which don't support the new msgpack extension, a new session setting was introduced - `error_marshaling_enabled` (see [box.error.new()](https://www.tarantool.io/en/doc/latest/reference/reference_lua/box_error/new/)). This was a bad call, because

1. To enable it, the client has to have the privilege to execute an arbitrary Lua code (EVAL).
2. The option affects not only how errors are encoded by iproto, but also the behavior of the [msgpack](https://www.tarantool.io/en/doc/latest/reference/reference_lua/msgpack/) module.

Now, when we have the [IPROTO_ID](https://github.com/tarantool/tarantool/issues/6253) command for querying server/client features, it's natural to use it to enable the new error format. We can flip the existing `error_marshaling_enabled` session setting from the command, but

1. The user can still flip it back (because it's a session setting), which is pointless and harmful.
2. It will affect the behavior of the msgpack module (see point 2 above), which may result in breaking user code.

The suggestion is to drop the `error_marshaling_enabled` session setting now that we don't really need it for enabling the new error format (thanks to IPROTO_ID). The msgpack module should continue encoding errors in the old format, but there should be an option to enable the new format (per msgpack.encode and maybe global default).

**Comment by locker** [comment]
Special case: tuple creation also encodes given arguments (one of which may be an error) in msgpack. There are two cases:
- Explicit: box.tuple.new
- Implicit: box.space.insert, box.space.replace, etc

Currently, error_marshaling_enabled affects their behavior (although there's a [bug](#6431) somewhere in the encoder which leads to a crash so this is unusable). This looks wrong: using a new connector shouldn't affect how data is stored when inserted into a space. But how can we make them to encode errors in the new error format? A global setting?

Suggestion: use the old error format in those functions for now. File a bug to investigate how we can switch to the new error format.

**Comment by locker** [comment]
There's msgpack.cfg(), which sets default serializer options. We should probably add error_marshaling_enabled there.

**Comment by Totktonada** [comment]
> 1. To enable it, the client has to have the privilege to execute an arbitrary Lua code (EVAL).

It is not fully correct. One can grant a user access to the '_settion_settings' virtual space and work with it as with usual space (AFAIR this space supports only SELECT and UPDATE operations).

NB: It is strange that we don't give a user access to its session setting by default.

**Comment by locker** [comment]
> > 1. To enable it, the client has to have the privilege to execute an arbitrary Lua code (EVAL).
> 
> It is not fully correct. One can grant a user access to the '_settion_settings' virtual space and work with it as with usual space (AFAIR this space supports only SELECT and UPDATE operations).

You're right. Still, this requires granting privileges. I believe new errors should be enabled automatically.

> 
> NB: It is strange that we don't give a user access to its session setting by default.

I think it's a bug, see #6310.
