### ISSUE TITLE
[Eternal] Proofread Tarantool changelogs for 2.10.0-rc1

### ISSUE THREAD

**Issue by NickVolynkin** [tarantool/tarantool#6430]
**Epic: [Release notes](https://github.com/tarantool/doc/issues/2570)**

- [ ] proofread changelogs in https://github.com/tarantool/tarantool/tree/master/changelogs/unreleased
- [ ] proofread changelogs in https://github.com/tarantool/tarantool-ee/tree/master/changelogs/unreleased
- [ ] backport changes to other branches

---

Progress chart in Notion to track changes: https://www.notion.so/tarantool/Proofreading-Tarantool-changelogs-3d540b96fb604b788f44e9a3f9bb6d5b

Updated on Feb 18, 2022: included EE changelogs.

**Comment by patiencedaur** [comment]
Will be repeated every sprint until 2.10.1 is out.
