### ISSUE TITLE
Crash in box.tuple.new(box.error.new(0)) when error_marshaling_enabled

### ISSUE THREAD

**Issue by locker** [tarantool/tarantool#6431]
```
Tarantool 2.10.0-beta1-27-gb0431cf8f47e
type 'help' for interactive help
tarantool> box.tuple.new(box.error.new(0))
---
- ['Unknown error']
...

tarantool> box.session.settings.error_marshaling_enabled = true
---
...

tarantool> box.tuple.new(box.error.new(0))
tarantool: /home/vlad/src/tarantool/src/box/tuple.h:1142: mp_tuple_assert: Assertion `tuple == tuple_end' failed.
Aborted
```

**Comment by locker** [comment]
Another way to reproduce:

```
Tarantool 2.10.0-beta1-33-gfff047cc2244
type 'help' for interactive help
tarantool> box.cfg{log_level = 0}
---
...

tarantool> box.session.settings.error_marshaling_enabled = true
---
...

tarantool> box.space._space:insert{box.error.new(0)}
tarantool: /home/vlad/src/tarantool/src/box/tuple.h:1142: void mp_tuple_assert(const char*, const char*): Assertion `tuple == tuple_end' failed.
Aborted
```

**Comment by locker** [comment]
Related issue - looks like the error extension encoding is completely broken:

```
tarantool> msgpack = require('msgpack')
---
...

tarantool> msgpack.decode(msgpack.encode{box.error.new(0), 1, 2, 3})
---
- ['Unknown error', 1, 2, 3]
- 19
...

tarantool> box.session.settings.error_marshaling_enabled = true
---
...

tarantool> msgpack.decode(msgpack.encode{box.error.new(0), 1, 2, 3})
---
- ['Unknown error', 'Unknown error', 1, 2]
- 121
...
```

Good news - it should be totally safe to drop the error_marshaling_enabled session setting (see #6428), as nobody could possibly use it without crash or invalid result.

**Comment by Totktonada** [comment]
AFAIK there is the only client that [supports](https://github.com/tarantool-php/client/compare/ba7f7c4f84ee5ba87ff9c8b6cc603e8856e18642...7e99aa5d68bf22ae70275de6997b79a4a2c27b41) them: tarantool-php/client. However it is still unclear why someone would enable it.

For debugging? It has very limited support of tracebacks (#4904). For stacked diagnostics? AFAIK we have not so much errors that are reported this way. And those things should 'just work', without all those options.

As @LeonidVas noted, it is barely usable without a payload support (#4907), which was postponed to unclear future.

----

Regarding the crash itself: maybe it is related to partial support in the Lua->msgpack serialization code (see #4908).

**Comment by locker** [comment]
> AFAIK there is the only client that [supports](https://github.com/tarantool-php/client/compare/ba7f7c4f84ee5ba87ff9c8b6cc603e8856e18642...7e99aa5d68bf22ae70275de6997b79a4a2c27b41) them: tarantool-php/client. However it is still unclear why someone would enable it.

And it's enabled only in a test...
