### ISSUE TITLE
Constraints

### ISSUE THREAD

**Issue by unera** [tarantool/tarantool#6436]
We need to have constraints.

- [ ] Relations

Features to do:

- Foreign field to primary
- Foreign field to indexed field
- Foreign composite fields to primary composite key
- Foreign composite fields to composite indexed fields

Foreign checks have to pass
- in update/insert/replace operations
- in delete operation (Add option `cascade`)

- [ ] Field values

Features to do:

- Constraint is stored into `spaces._func`
- More than one constraint per space
- It would be nice to know about all broken constraints in Error message. Example:
  `space:insert{1,2,3}` throws "Constraint errors: foo, bar, baz". It would be nice if a user don't need parsing to know constraint names.

Constraint interface:

- Return value is ignored
- If constraint doesn't pass check, the function raises an exception

**Comment by Totktonada** [comment]
I would like to see decomposition of the task from the development team. Here we have constraints and relations. Moreover, each likely will be splitted into its own phases.

If relations are tracked here, it worth to close #3080.
