### ISSUE TITLE
Get rid of atomics in rmean

### ISSUE THREAD

**Issue by locker** [tarantool/tarantool#6447]
Since commit 91d8e7ae2a43a6b7898c1c08b81d1a6fd9dfd907, rmean uses atomic operations to update and collect statistics:

https://github.com/tarantool/tarantool/blob/5546cde0c78f376ec53bb406f57fa71e90889b80/src/rmean.c#L59-L66

The reason for that is that in IPROTO, rmean stats are updated from an IPROTO thread while read from the TX thread. Using atomics in rmean however can lead to a performance degradation in potentially hot code paths. Since TX already calls IPROTO (via CBUS) to collect stats, we should probably fetch rmean stats this way as well and get rid of atomics:

https://github.com/tarantool/tarantool/blob/5546cde0c78f376ec53bb406f57fa71e90889b80/src/box/iproto.cc#L3023-L3034

**Comment by Gerold103** [comment]
Alongside, please, get rid of this hack by fetching stats via `iproto_do_cfg`. It is `cfg`, like the name says, not for stats. This slipped without a review not so long ago. Would be cool if it could be fixed here.

**Comment by Gumix** [comment]
Probably we can update rmean non-atomically in iproto threads, but read them atomically in the tx thread.
I am not sure, but [C11, §5.1.2.4, 25](https://www.open-std.org/jtc1/sc22/wg14/www/docs/n1548.pdf) says that it is legal:

> The execution of a program contains a data race if it contains two conflicting actions in different threads, **at least one of which is not atomic**, and neither happens before the other. Any such data race results in undefined behavior.

**Comment by Gumix** [comment]
Performance measurement showed that `rmean_collect()` is not on a hot path, so it makes little sense to optimize it.

**server:**
```lua
box.cfg{listen = 31337}
box.schema.user.grant('guest', 'read,write,execute,create,drop', 'universe', nil, {if_not_exists = true})
local s = box.schema.space.create('test')
s:create_index('pk')
s:insert{1}
```

```sh
$ perf record -g taskset 0xf tarantool server.lua
```

**client:**
```lua
local conn = require('net.box').connect('localhost:31337')
for i = 1, 100000 do
    conn.space.test:select{1}
end
os.exit()
```

```sh
$ taskset 0xf00 tarantool client.lua
```

**`perf report`:**
```
Samples: 15K of event 'cpu-clock:pppH', Event count (approx.): 3892000000
  Children      Self  Command    Shared Object       Symbol

+   58.45%     0.00%  iproto     [kernel.kallsyms]   [k] entry_SYSCALL_64_after_hwframe
+   55.85%     0.19%  iproto     [kernel.kallsyms]   [k] do_syscall_64
+   29.95%     1.45%  iproto     libc-2.31.so        [.] writev
+   26.75%     0.10%  iproto     [kernel.kallsyms]   [k] do_writev
+   26.50%     0.08%  iproto     [kernel.kallsyms]   [k] vfs_writev
+   26.19%     0.13%  iproto     [kernel.kallsyms]   [k] do_iter_write
+   25.93%     0.10%  iproto     [kernel.kallsyms]   [k] do_iter_readv_writev
+   25.84%     0.16%  iproto     [kernel.kallsyms]   [k] sock_write_iter
+   25.67%     0.09%  iproto     [kernel.kallsyms]   [k] sock_sendmsg
+   25.39%     0.07%  iproto     [kernel.kallsyms]   [k] tcp_sendmsg
[...]
     0.37%     0.37%  tarantool  tarantool           [.] rmean_collect
     0.32%     0.32%  iproto     tarantool           [.] rmean_collect
```
