### ISSUE TITLE
SQL quote functions and nul characters

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#6467]
I have Ubuntu 20.04.
I have Tarantool 2.10, pulled from source today.
I execute this statement:
SELECT quote(cast(x'440044' AS STRING));
The result is a string with length 3: 'D'.
This conforms with SQLite: https://www.sqlite.org/lang_corefunc.html#quote
but for other functions we fixed so that \0 in an SQL string is not considered to be a string terminator.

**Comment by ImeevMA** [comment]
Fixed by 64d0eca36
