### ISSUE TITLE
logrotate doesn't logrotate fully

### ISSUE THREAD

**Issue by unera** [tarantool/tarantool#648]
to reproduce:

1. rename log to `log.1`
1. call `log.rotate()` in lua - it will create new log file
1. reconnect replica to the host, or stop the host: messages about reconnects and exit messages will be written to `log.1`

**Comment by rtsisyk** [comment]
Will be fixed after moving SUBSCRIBE operation to a thread.

**Comment by rtsisyk** [comment]
The other part of the problem was broken logrotated script, it would not send SIGHUP to tarantool.
Relay is now running in a thread, and logrotated script is fixed.
