### ISSUE TITLE
Support any callable object as an argument to triggers

### ISSUE THREAD

**Issue by Mons** [tarantool/tarantool#6484]
[PM link](https://www.notion.so/tarantool/Support-any-callable-object-as-an-argument-to-triggers-c9138ec77a59431b838046041f5c28ab)

Currently, trigger methods (session, space) accept only pure functions. Sometimes it may be useful to pass the table with a __call metamethod.

I propose to support such objects as trigger arguments.

**Comment by Totktonada** [comment]
I'll also highlight that userdata and cdata objects can have the `__call` metamethod too. Cited [from myself](https://github.com/tarantool/httpng/pull/248#discussion_r719864927):

Example for userdata:

```lua
tarantool> ud = newproxy(true)
tarantool> mt = getmetatable(ud)
tarantool> mt.__call = function(self, ...) return ... end
tarantool> ud(1, 2, 3)
---
- 1
- 2
- 3
...
```

Example for cdata:

```lua
tarantool> ffi = require('ffi')
tarantool> ffi.cdef('struct foo { int x; }')
tarantool> mt = {__call = function(self, ...) return ... end}
tarantool> ffi.metatype('struct foo', mt)
tarantool> cd = ffi.new('struct foo', {x = 42})
tarantool> cd(1, 2, 3)
---
- 1
- 2
- 3
...
```

----

In the scope of this issue we can also expose a function to verify whether an object is callable that will be accessible from Lua code. It would be useful for modules.

There is `luaL_iscallable()`, but

* It is accessible only from Lua/C.
* It does not accept userdata with `__call` (only function, table, cdata AFAIR).

I would also improve the `luaL_iscallable()` function with userdata support within this issue.

Questions:

* Whether such function should verify that the `__call` field on the metatable is also callable?
* If so, whether it should have infinite recursion / cycling protection?

Interesting fact: if I don't do something wrong, it seems, the `__call` metamethod may be a function only:

```lua
tarantool> x = setmetatable({}, {__call = function(self, ...) return ... end})
tarantool> t = setmetatable({}, {__call = x})
tarantool> t(1, 2, 3)
---
- error: '[string "return t(1, 2, 3)"]:1: attempt to call global ''t'' (a table value)'
...
```

So all those recursion / cycling questions seems irrelevant. We should just check that `__call` is a function.

There is issue about reading of a metatable of a cdata object: #3915. Some information from it may be relevant here.

**Comment by Gerold103** [comment]
Why can't you wrap it into a closure?

**Comment by R-omk** [comment]
Related https://github.com/tarantool/tarantool/issues/4115

**Comment by unera** [comment]
> Why can't you wrap it into a closure?

wrapper - is a workaround.
callable object is a wrapper, too.

So if you need a trigger linked to the object (wrapper), you have to wrap it twice.

**Comment by Mons** [comment]
wrapper is not a workaround.
One of the purpouse of callable table — is to make already set up triggers distinguishable.
One may create table with metadata (like name) inside and __call. And then, on reload or in any other case one can distinguish exactly this table from the list.

**Comment by unera** [comment]
> wrapper is not a workaround.

Wrapper is a workaround to use a callable object.

If You have a calable table you can wrap it into a closure. :)

**Comment by Mons** [comment]
I can distinguish between different function, only having a reference to some function.

**Comment by unera** [comment]
> I can distinguish between different function, only having a reference to some function.

I agree with all you wrote.

But You can create a new wrapper for each callable object. So the workaround exists. 

Ok, but we want to use functional, not workaround (don't wrap an object twice).
So the task should be realised, not closed or moved to wishlist :)
