### ISSUE TITLE
Use Knuth–Morris–Pratt algorithm for some SQL built-in functions

### ISSUE THREAD

**Issue by ImeevMA** [tarantool/tarantool#6492]
We can create functions to find one string within another that uses the KMP algorithm and use them in some functions, such as the implementation of the built-in SQL functions POSITION() and REPLACE().

There should be two functions: the first for VARBINARY arguments, the second for STRING arguments. The second function should be able to use collations.

**Comment by Vigor-jpg** [comment]
Hi ! I am the perticipant of GSoC 2022 , and I don't know what should I do about the function for VARBINARY arguments.Is it the same with the function for STRING arguments.Could you please tell me some more details about the demand of this function.

**Comment by ImeevMA** [comment]
Sorry, this issue is already under development. Please find another one :).

**Comment by ImeevMA** [comment]
It appears that this change is not necessary at this time.
