### ISSUE TITLE
API to read event data without making a subscription

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#6493]
[Design document](https://www.notion.so/tarantool/Watch-once-0143eee47a514fdd91a3232a156d81ef)

The ticket #6257 defines subscriptions. The other ticket #6260 defines built-in events available out of the box. One of the features of the subs is that they work without any grants. At least the built-in ones.

It might be useful to have an API to get data by a subscription key without making an actual subscription. It could be used by clients who are not able or don't want to process async events. They might want to poll the data. With the help of such API they wouldn't need to implement stored functions to get stuff like election state, some cfg options, and whatever will be exposed along.

It is possible to emulate it by sending subscribe + unsubscribe requests right after each other, but that means more network data, and more load on the server to create and drop the subscription even though it wasn't really needed.

**Comment by unera** [comment]
We could add a flag to [IPROTO_WATCH](https://www.tarantool.io/ru/doc/latest/dev_guide/internals/iproto/events/#iproto-watch) request.

UNSUBSCRIBE: true

|PLACE| TYPE | VALUE |
|--------|---------|------------|
|header|IPROTO_REQUEST_TYPE|IPROTO_WATCH|
|body|IPROTO_EVENT_KEY|MP_STR|
|body|**IPROTO_WATCH_UNSUBSCRIBE**|MP_BOOL|

If the flag is true, tarantool doesn't add the client to the subscriber's list.

Cases:

- if the subscriber's list has already contained the client, it means that a client should stay there.

So algo:

IPROTO_WATCH[unsubscribe = true] -> return state[IPROTO_EVENT_KEY]

**Comment by locker** [comment]
[Design document](https://www.notion.so/tarantool/Watch-once-0143eee47a514fdd91a3232a156d81ef)
