### ISSUE TITLE
futex stuck after arena overfolw

### ISSUE THREAD

**Issue by no1seman** [tarantool/tarantool#6495]
**Bug description**

Seems that threads are not killed after arena overflow.

* OS: [Linux]
* OS Version: [REDHAT 7.9 x64]
* Architecture: [amd64]

Place `tarantool --version` output here.

Enterprise 2.7.2-110 

**Steps to reproduce**
No
**Actual behavior**
![image](https://user-images.githubusercontent.com/17825302/136179407-cb6e8c72-608f-4c31-ab8f-aa526e70bf27.png)

**Expected behavior**

theards must be killed after disconnect.

**Comment by AnastasMIPT** [comment]
Tried to reproduce in the configuration of two shards, each storage and replica, running instances using supervisord. Inserted a lot of tuples into the space. Tried seterlimit with hard limits, just RAM overflow, memory limit with memtx_memory. In all cases it resulted in the usual allocation errors without crashing the instance.
