### ISSUE TITLE
builtin/box/schema.lua: attempt to index local 'opts' (a number value)

### ISSUE THREAD

**Issue by rybakit** [tarantool/tarantool#6501]
**Bug description**

When I make an IPROTO call with malformed arguments, I get an internal lua error about an unexpected value type:

<img width="551" alt="tarantool_luajit_error" src="https://user-images.githubusercontent.com/533861/136459391-eb63c2c3-ae17-48ea-8d46-86c7cdd36c15.png">

* OS: MacOS
* OS Version: 11.6
* Architecture: amd64

```bash
Tarantool 2.8.2-0-gfc96d10f5
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_BACKTRACE=ON
Compiler: /usr/bin/cc /usr/bin/c++
C_FLAGS: -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type
CXX_FLAGS: -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type
```

**Steps to reproduce**

1. Run a tarantool instance in console 1:

```bash
docker run -p 3301:3301 --rm tarantool/tarantool:2
```

2. Install the PHP connector and make an IPROTO call in console 2:

```bash
docker run -it --rm composer bash
composer require tarantool/client:0.9.0 rybakit/msgpack
```

Then copy-paste the following content and save it as `test.php`:

```php
<?php

namespace Tarantool\Client;

require __DIR__ . '/vendor/autoload.php';

$client = Client::fromDsn('tcp://host.docker.internal:3301');

// valid request
$client->call('box.space._vspace:select', [300], [Schema\IteratorTypes::GT]);

// malformed request (note the missing [])
$client->call('box.space._vspace:select', [300], Schema\IteratorTypes::GT);
```

Then run the saved script:

```bash
php test.php
```

**Actual behavior**

A luajit error occurs about the local lua `opts` variable:

```
Fatal error: Uncaught Tarantool\Client\Exception\RequestFailed: builtin/box/schema.lua:1516: attempt to index local 'opts' (a number value)
```

**Expected behavior**

A more meaningful message about a malformed request/arguments, rather than a lua error about an unexpected value of a local variable.

**Comment by rybakit** [comment]
@Totktonada Nice, at first I was trying to reproduce it without the connector using `net.box.call` and to my surprise it did not cause any errors :)

**Comment by sergos** [comment]
Looks like `check_iterator_type` should reuse the `check_param_table` for opts with appropriate template

**Comment by Totktonada** [comment]
NB: `box.space._vspace:select({300}, box.index.GT)` is now valid.

Changed in:

* 2.10.0-beta2-132-g3a98e0794
* 2.8.3-55-g63f76a198
* 1.10.12-46-gd45e5e797
