### ISSUE TITLE
wiki: duplicate PackPack build guide

### ISSUE THREAD

**Issue by DifferentialOrange** [tarantool/tarantool#6508]
tarantool/tarantool repo wiki contains two pages about building with PackPack: https://github.com/tarantool/tarantool/wiki/Build-RPM-or-Deb-package-using-packpack and https://github.com/tarantool/tarantool/wiki/PackPack . The latter is outdated. It is confusing

**Comment by Totktonada** [comment]
I removed the former and all pages created by me in a free time. I'll not contribute to this wiki anymore except when it is part of my working task, sorry.

**Comment by Totktonada** [comment]
I hope we resolved the problem with my contributions to the wiki. I updated the instruction and merged it into https://github.com/tarantool/tarantool/wiki/PackPack.
