### ISSUE TITLE
tarantoolctl non default path to running applications

### ISSUE THREAD

**Issue by zloidemon** [tarantool/tarantool#652]
If someone developing an application and ofter start/stop without root access in non default path of the system. More well use tarantoolctl like that:

```
$ cd ~/helloworld
$ tarantoolctl start
```

helloworld has to contain *init.lua* with code and tarantool configuration. An application has to start by user which *run tarantoolctl* and chroot that for $HOME/helloworld.

**Comment by Sulverus** [comment]
Awaiting for review

**Comment by zloidemon** [comment]
I think https://github.com/tarantool/tarantool/commit/2f2b585269804e5455c76705aba6d45b407e3d3b is more well for that task.

**Comment by kostja** [comment]
I pushed your changes but changed the semantics a bit so that  ~/.config/default and /etc/default are never merged: either one or the other is chosen. 

Please let me know if You see any trouble with my fix.
