### ISSUE TITLE
netbox opts type is not checked

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#6530]
```Lua
netbox = require('net.box')
box.cfg{listen = 3313}
box.schema.user.grant('guest', 'super')
c = netbox.connect(box.cfg.listen)
function echo(...) return ... end
c:call('echo', {1}, box.NULL)
```
Gives
```
---
- error: 'builtin/box/net_box.lua:920: ''void *'' has no member named ''buffer'''
...
```
The error must be graceful. With a precise reason. Not internal Lua's error.

**Comment by AnastasMIPT** [comment]
I think we should also figure out if we want to check all the options for validity.

On the one hand, checking all options for type and presence can slow down Tarantool.

On the other hand, there are the following cases:

For example, right now, if we pass a Lua string as `buffer` option, Tarantool will crash with a Segmentation fault.

If we pass a Lua string as the limit parameter to a remote select query, then select will return an empty tuple.
