### ISSUE TITLE
Write in log when see `space:select(nil)`

### ISSUE THREAD

**Issue by Buristan** [tarantool/tarantool#6539]
We all hate `space:select(nil)` from large space. We see either crash with OOM, either Tarantool is slow in the uptake with 100% of CPU usage by tx thread. Debugging of killer-request is often too painful and exhausting. The simplest solution which doesn't break back compatibility is to write in the log with `crit` level, when this request is occurring. To simplify debugging we can write Lua stack trace with the log level `warn` or less. When a user sees a core dump with OOM backtrace or 100% CPU usage by Tarantool he will check the logs first to be sure, that there is no `space:select(nil)`.

**Comment by NeraverinTarantool** [comment]
@alyapunov 
After internal discussion, we decided:
- Warn the user about potentially dangerous code
- With logging level - CRIT
- For all cases:
     - `:select()`
     - `:select(nil)`
     - `:select{}`
     - `crud:select()`
     - `crud:select(nil)`
     - `crud:select{}`
- With ratelimit (it's worth raising it higher than 0.5 sec for this particular case)
- Add the option fullscan=true to suppress the message in the log
- Remove examples of the form select () from the documentation everywhere
- 2.10 and 1.10.x

**Comment by kyukhin** [comment]
I've submitted two more issues:
1. [crud part](https://github.com/tarantool/crud/issues/276)
2. [doc part](https://github.com/tarantool/doc/issues/2818)

In scope of this issue we're about to fix core only.
