### ISSUE TITLE
Rework/Update README.md

### ISSUE THREAD

**Issue by R-omk** [tarantool/tarantool#6579]
There have been many changes and innovations in recent years, it may be worth making some changes into the readme file.

**Comment by Totktonada** [comment]
I agree. Also there was the idea between @knazarov and me that we should reflect different installation methods in the  README to ease a new user the road to play with tarantool. Sure, we should also update our key features.

To be honest, there was the [attempt](https://github.com/tarantool/tarantool/pull/4741) — it was hard to agree on certain way to present this information and we agreed that I'll do it in the way I like. So, it is my debt. I promised to do so to @knazarov.

**Comment by Totktonada** [comment]
Please, check it out: https://github.com/tarantool/tarantool/pull/6644.
