### ISSUE TITLE
ecosystem: rockspecs should not use insecure git protocol

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#6587]
We recently was hit by the following problem:

```
$ tarantoolctl rocks install luatest                                                                                                                                                               
Installing http://rocks.tarantool.org/luatest-scm-1.rockspec

Cloning into 'luatest'...
fatal: remote error: 
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.

Error: Failed cloning git repository.
```

The reason is that GitHub is going to disable pulls using insecure git protocol: https://github.blog/2021-09-01-improving-git-protocol-security-github/.

Generally it means that we should replace `url = 'git://github.com/<...>'.git` rockspec directive with `url = 'git+https://github.com/<...>.git'`. (Caution: just `url = 'https://<...>'` means a tarball, not a git repository.)

I resolved the problem manually: updated all problematic rockspecs on rocks.tarantool.org (it is the server, which is used by default by `tarantoolctl rocks [subcommand]`).

However we should update rockspecs in repositories, because it is quite usual to deploy a rockspec from a project repository to rocks.tarantool.org automatically from CI (or manually, but the rockspec is anyway based on one from the repository).

We should also restrict rocks.tarantool.org server to decline rockspecs with insecure github.com repository URLs:

- [ ] https://github.com/tarantool/rocks.tarantool.org/issues/47

----

The list of rocks.tarantool.org rocks with status against this problem is the following (will be updated).

- [x] argon2 (https://github.com/tarantool/argon2/pull/2)
- [x] [argparse](https://github.com/mpeterv/argparse) (unaffected, already `git+https://`)
- [ ] [authman](https://github.com/mailru/tarantool-authman) (https://github.com/mailru/tarantool-authman/pull/20)
- [x] avro-schema (https://github.com/tarantool/avro-schema/pull/143)
- [x] cartridge (unaffected, already `git+https://`)
- [x] cartridge-cli (unaffected, already `git+https://`; the rock is deprecated, it was rewritten in Go)
- [x] cartridge-cli-extensions (unaffected, already `git+https://`)
- [x] cartridge-extensions (unaffected, already `git+https://`)
- [x] cbench (https://github.com/tarantool/cbench/pull/7)
- [x] checks (https://github.com/tarantool/checks/pull/29)
- [x] conf (https://github.com/tarantool/conf/pull/13)
- [x] config (https://github.com/tarantool/config/pull/10)
- [x] connpool (https://github.com/tarantool/connpool/pull/8)
- [x] crud (unaffected, already `git+https://`)
- [x] cron-parser (https://github.com/tarantool/cron-parser/pull/8)
- [x] [date](https://github.com/Tieske/date) (https://github.com/Tieske/date/pull/27)
- [x] ddl (unaffected, already `git+https://`)
- [x] document (https://github.com/tarantool/document/pull/8)
- [x] dump (https://github.com/tarantool/dump/pull/12)
- [x] expirationd (https://github.com/tarantool/expirationd/pull/91)
- [x] frontend-core (unaffected, already `git+https://`)
- [x] errors (unaffected, already `git+https://`)
- [x] gis (https://github.com/tarantool/gis/pull/18)
- [x] gperftools (https://github.com/tarantool/gperftools/pull/6)
- [x] graphite (deprecated, will not receive updates)
- [x] graphql (https://github.com/tarantool/graphql/pull/23)
- [x] graphqlapi (unaffected, already `git+https://`)
- [x] graphqlide (unaffected, already `git+https://`)
- [x] http (https://github.com/tarantool/http/pull/148)
- [x] http-v2-legacy (https://github.com/tarantool/http/pull/149)
- [x] icu-date (https://github.com/tarantool/icu-date/pull/29)
- [x] [jsonpath](https://github.com/tarantool/lua-jsonpath) (https://github.com/tarantool/lua-jsonpath/pull/2)
- [x] kafka (https://github.com/tarantool/kafka/pull/47)
- [x] ldecnumber (https://github.com/tarantool/ldecnumber/pull/5)
- [x] [lpeglabel](https://github.com/sqmedeiros/lpeglabel/) (unaffected, all rockspecs use tarball URLs)
- [x] [lrexlib-pcre](https://github.com/rrthomas/lrexlib/) (https://github.com/rrthomas/lrexlib/pull/41)
- [x] [lrexlib-pcre2](https://github.com/rrthomas/lrexlib/) (https://github.com/rrthomas/lrexlib/pull/41)
- [x] [lua-term](https://github.com/hoelzro/lua-term) (unaffected, the rockspec uses a tarball URL)
- [x] luacheck (unaffected, already `git+https://`)
- [x] [luacov](https://github.com/keplerproject/luacov/) (already `git+https://`, was updated [here](https://github.com/keplerproject/luacov/commit/1721f4aac58fb9919f9526ead4402356bb0680b9))
- [x] [luacov-console](https://github.com/spacewander/luacov-console/) (https://github.com/spacewander/luacov-console/pull/2)
- [x] luacov-reporters (https://github.com/tarantool/luacov-reporters/pull/2)
- [x] [luafilesystem](https://github.com/keplerproject/luafilesystem) (https://github.com/keplerproject/luafilesystem/pull/152)
- [x] luagraphqlparser (https://github.com/tarantool/luagraphqlparser/pull/7)
- [x] luarapidxml (unaffected, already `git+https://`)
- [x] luatest (https://github.com/tarantool/luatest/pull/188)
- [x] lulpeg (https://github.com/tarantool/LuLPeg/pull/6)
- [x] membership (unaffected, already `git+https://`)
- [x] memcached (https://github.com/tarantool/memcached/pull/72)
- [x] metrics (https://github.com/tarantool/metrics/pull/320)
- [x] migrate (https://github.com/tarantool/migrate/pull/18)
- [x] migrations (unaffected, already `git+https://`)
- [x] modulekit (the rockspec is removed from rocks.tarantool.org, see below; but the repository is to be updated; https://github.com/tarantool/modulekit/pull/7 and https://github.com/tarantool/modulekit/pull/8)
- [x] moonwalker (https://github.com/tarantool/moonwalker/commit/36ba736ed9fc7090ca9711d940f2defba7f29f79)
- [x] mqtt (https://github.com/tarantool/mqtt/pull/43)
- [ ] [mrasender](https://github.com/mailru/mrasender) (https://github.com/mailru/mrasender/pull/1)
- [x] mysql (https://github.com/tarantool/mysql/pull/62)
- [x] pg (https://github.com/tarantool/pg/pull/27)
- [x] prometheus (deprecated, will not receive updates)
- [x] queue (https://github.com/tarantool/queue/pull/154)
- [x] shard (deprecated, will not receive updates)
- [x] sharded-queue (unaffected, already `git+https://`)
- [x] smtp (https://github.com/tarantool/smtp/pull/50)
- [x] sqlparser (https://github.com/tarantool/sqlparser/pull/14)
- [x] stat (deprecated, will not receive updates)
- [x] [tarantool-lsp](https://github.com/tarantool/lua-lsp/) (https://github.com/tarantool/lua-lsp/pull/14)
- [x] tarantool-curl (deprecated, will not receive updates)
- [x] template (https://github.com/tarantool/template/pull/8)
- [x] tnt-kafka (the old name of kafka, will not receive updates)
- [x] tracing (https://github.com/tarantool/tracing/commit/9feeae61e3dfa2d295d0c538c85a3686523d72ab)
- [x] tradeparser (https://github.com/tarantool/tradeparser/pull/4)
- [x] tuple-keydef (https://github.com/tarantool/tuple-keydef/pull/22)
- [x] tuple-merger (https://github.com/tarantool/tuple-merger/pull/28)
- [x] vshard (https://github.com/tarantool/vshard/pull/305)
- [x] watchdog (https://github.com/tarantool/watchdog/pull/20)
- [x] websocket (https://github.com/tarantool/websocket/pull/15)
- [x] zookeeper (https://github.com/tarantool/zookeeper/pull/11)

----

Removed the 'modulekit' rockspec from rocks.tarantool.org, because it is too old (corresponds to the old repository layout) and could not be installed anymore. The repository is splitted now to luakit and ckit branches. Since there is no much sense to deploy the template repository, I will not deploy 'luakit' and 'ckit' rocks instead of the 'modulekit' one.

----

[luafun](https://github.com/luafun/luafun/) will be updated here:

- [x] https://github.com/luafun/luafun/pull/61

**Comment by tst2005** [comment]
Hello,
An alternative solution to patch each repository is to change the tool that using them.
Luarocks did it with https://github.com/luarocks/luarocks/commit/9ff512e35455939f02eaec2318e3acc77782fdeb .
Maybe tarantool can also consider this way.

Regards,

**Comment by Totktonada** [comment]
@tst2005 Wow, I didn't aware of that. Filed #6597.

**Comment by Totktonada** [comment]
It is not in the list, but I also proposed the same change to luacov-coveralls: https://github.com/moteus/luacov-coveralls/pull/30.

**Comment by Totktonada** [comment]
Remaining task:

- https://github.com/tarantool/rocks.tarantool.org/issues/47

**Comment by Totktonada** [comment]
Current status:

* All the rockspecs are updated on the rocks server.
* The rockspecs in the repositories are updated too, except:
  - [authman](https://github.com/mailru/tarantool-authman) (https://github.com/mailru/tarantool-authman/pull/20)
  - [mrasender](https://github.com/mailru/mrasender) (https://github.com/mailru/mrasender/pull/1)
  - [luacov-coveralls](https://github.com/moteus/luacov-coveralls) (https://github.com/moteus/luacov-coveralls/pull/30) (it is not listed in this issue, because it is not present on our rocks server)
* The server side task https://github.com/tarantool/rocks.tarantool.org/issues/47 is opened.

I think there is nothing to track here. Closing then.
