### ISSUE TITLE
Master-Master Replication Issue

### ISSUE THREAD

**Issue by victor-oancea-leftclick-io** [tarantool/tarantool#6588]
**Bug description**

main/7370/main box.cc:187 E> ER_READONLY: Can't modify data because this instance is in read-only mode.

I have 2 identical masters, both started with:
`box.cfg{
    work_dir = '/root/tarantool',
    memtx_dir = '/root/tarantool/memtx',
    wal_dir = '/root/tarantool/wal',
    memtx_memory = 13737418240,
    memtx_use_mvcc_engine = true,
    pid_file = "tarantool.pid",
    worker_pool_threads = 16,
    iproto_threads = 8,
    listen = 3301,
    net_msg_max = 76800,
    readahead = 1632000,
    checkpoint_interval = 600,
    checkpoint_count  = 5,
    replication_synchro_quorum = 2,
    replication_synchro_timeout = 10,
    election_mode = 'candidate',
    replication = {
       'replicator:password@ip1:3301',
       'replicator:password@ip2:3301'
    },
    read_only = false,
}`

* OS: Ubuntu
* OS Version: 20.4
* Architecture: amd64

Place `tarantool --version` output here.
`Tarantool 2.8.2-0-gfc96d10f5
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_BACKTRACE=ON
Compiler: /usr/bin/cc /usr/lib/ccache/g++
C_FLAGS:-g -O2 -fdebug-prefix-map=/build/tarantool-2.8.2.0=. -specs=/usr/share/dpkg/no-pie-compile.specs -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type
CXX_FLAGS:-g -O2 -fdebug-prefix-map=/build/tarantool-2.8.2.0=. -specs=/usr/share/dpkg/no-pie-compile.specs -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type
`

**Steps to reproduce**

Just start 2 masters with `tarantool script.lua` -- the strict contains only the box.cfg mentioned above.

Then using any client, try to do an insert, update or delete into a memtx space, concurrently on both masters.

**Comment by sergos** [comment]
Could you provide log during bootstrap?
Apparently, election mode triggers RAFT, which contradicts the master-master.

**Comment by victor-oancea-leftclick-io** [comment]
Yep, my bad. It is using leader election. I'll close this
