### ISSUE TITLE
Implement optional Linearizable Read (raft)

### ISSUE THREAD

**Issue by R-omk** [tarantool/tarantool#6592]
This mode for read request when needs to read the latest committed data, not the old data.

**Comment by R-omk** [comment]
related https://github.com/tarantool/tarantool/issues/6661 

The basic idea behind this is to confirm that the leader is true leader or not by sending a message to the followers. If a majority of responses are healthy, then the leader can safely serve the reads.

**Comment by sergos** [comment]
Implemented in https://github.com/tarantool/tarantool/issues/6707
