### ISSUE TITLE
Add PR label to trigger GitHub workflows

### ISSUE THREAD

**Issue by locker** [tarantool/tarantool#6605]
Running all GitHub workflows every time a developer updates a branch overloads test runners, especially if a developer is paranoid and pushes the branch after every single change because of the fear to lose the code.

I suggest to solve this problem as follows:
1. Shut down the mailing list and switch to PRs for all developers. Ideally, forbid to create branches in the main repository along the way, because those branches make the repo look like a trash dump. Let the developers create their own forks instead.
2. Add a special label for PRs (ready-to-merge, run-tests?). Setting this label on a PR or synchronizing a PR with this label would trigger the workflows. A developer would set this label only after the final approval of his/her PR. GitHub seems to [support](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request) this. We could probably even forbid merging a branch that doesn't have this label set.

**Comment by Totktonada** [comment]
Related: https://github.blog/changelog/2021-11-10-require-pull-requests-without-requiring-reviews/

**Comment by tsafin** [comment]
>     2\. Add a special label for PRs (ready-to-merge, run-tests?). Setting this label on a PR or synchronizing a PR with this label would trigger the workflows.

I'd suggest the opposite mode for label:
- if there is no any special label assigned then GH actions triggered;
- but at the moment when developer wants to silence it a bit, and commit set of commits without any intermediate checks, then he/she would mark PR with label 'no-ci' or such.
