### ISSUE TITLE
Build error (apple/m1)

### ISSUE THREAD

**Issue by dkuk** [tarantool/tarantool#6611]
**Bug description**

* OS: MacOS
* OS Version: Monterey (12.0.1 (21A559))
* Architecture: [arm/ apple m1]

2.10.0-beta1

**Steps to reproduce**
 
brew install --HEAD

does not builds
[02.make.log](https://github.com/tarantool/tarantool/files/7545433/02.make.log)

**Comment by Totktonada** [comment]
Duplicate of #6576.
