### ISSUE TITLE
Setup integration testing with CRUD module

### ISSUE THREAD

**Issue by ligurio** [tarantool/tarantool#6620]
CRUD [1] is one of the popular modules in Tarantool's ecosystem.
It would be nice to trigger tests for CRUD module with latest Tarantool version built from master branch. The same as we did for other modules and connectors, see #6056.

1. https://github.com/tarantool/crud

Pull requests:
* https://github.com/tarantool/crud/pull/335/
* https://github.com/tarantool/tarantool/pull/8056

**Comment by slavakirichenko** [comment]
Before merge this PR, first we need to mergre [335 at trarntool/crud](https://github.com/tarantool/crud/pull/335/)
