### ISSUE TITLE
Roles: incorrect handling of 'read'

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#663]
I have Ubuntu 12.04 and Tarantool 1.6 pulled from source today.
I execute these requests:
```
box.schema.role.create('X1')
box.schema.role.create('X2')
box.schema.role.grant('X1','read','role','X2')
box.schema.role.revoke('X1','read','role','X2')
box.schema.role.info('X1')
```
The result of `box.schema.role.info('X1')` is:
```
tarantool> box.schema.role.info('X1')
---
- - - execute
    - role
    - X2
...
```

I believe this indicates that:

1. For the 'grant', Tarantool interpreted the 'read' as meaning 'execute',
and therefore it succeeded. For the 'revoke', Tarantool did not interpret
the read as meaning 'execute', and therefore it failed. This is inconsistent.
2. It is apparent that the 'revoke' failed, because info() says the grant is
still there. But there was no error message. This is not sufficiently informative.

**Comment by Sulverus** [comment]
Done. Please review.
There is 2 ways:
1. do box.errror for `role.revoke('X1','read','role','X2')`
2. replace it with execute and revoke
I think second way is more user-friendly.
Also box/role.test was updated with this case

**Comment by kostja** [comment]
Pushed.
