### ISSUE TITLE
sql: ROUND() on big precision value behaves strange

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#6650]
This looks strange. I used precision `INT_MAX` and `INT_MAX` without the last digit. I had an impression that the bigger the precision, the more precise the value is. So from some point the result just should be equal the original number.
```
tarantool> box.execute('SELECT ROUND(1.2345678, 2147483647)')
---
- metadata:
  - name: COLUMN_1
    type: double
  rows:
  - [0]
...

tarantool> box.execute('SELECT ROUND(1.2345678, 214748364)')
---
- metadata:
  - name: COLUMN_1
    type: double
  rows:
  - [1.2345678]
...
```
It could be related to coverity reporting that `tt_sprintf("%.*f", n, d)` is incorrect. Firstly, because `d` is `double`, not `float`, so it should be `%lf`. Secondly, because `.*` takes `int`, but `n` is `uint64_t`.

**Update**: it is not related to the format. I tried to fix it and nothing changed.

**Comment by ImeevMA** [comment]
Hi, @Gerold103! I created a patch to fix this issue in ROUND(), however the main issue is with tt_sprintf(). I believe it returns an empty string if the precision is too big, but I'm not sure if that's wrong since 2147483647 is larger than the size of the static buffer that is used in tt_sprintf().
