### ISSUE TITLE
Problems with arrays

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#6668]
I have Ubuntu 20.04.
I have Tarantool 2.10, pulled from source today.
This version has a new feature for arrays, see issue #4762.
There are 6 problems.

1
I execute these requests:
``` lua
box.execute([[DROP TABLE n;]])
box.execute([[CREATE TABLE n (s1 INT PRIMARY KEY, s2 ARRAY, s3 ARRAY) ;]])
box.execute([[INSERT INTO n VALUES (1,[1, 'a', ['abc', 321], 1.5], NULL);]])
box.execute([[SELECT DISTINCT s2 FROM n;]])
```
Result = Segmentation fault.

A segmentation fault also occurs with SELECT COUNT(DISTINCT s2) FROM n;

2
I execute these requests:
``` lua
box.execute([[DROP TABLE n;]])
box.execute([[CREATE TABLE n (s1 INT PRIMARY KEY, s2 ARRAY, s3 ARRAY) ;]])
box.execute([[INSERT INTO n VALUES (1,[1, 'a', ['abc', 321], 1.5], NULL);]])
box.execute([[INSERT INTO n VALUES (2,NULL,LUA('return {1,2}'));]])
box.execute([[INSERT INTO n VALUES (3,[1, 'a', ['abc', 321], 1.5], NULL);]])
box.execute([[SELECT s2 FROM n GROUP BY s2;]])
```
Result = Assertion.
tarantool: /home/pgulutzan/tarantool-master/src/box/sql/mem.c:2367: mem_cmp_scalar: Assertion `0' failed.

3
I execute these requests:
``` lua
box.execute([[DROP TABLE n;]])
box.execute([[CREATE TABLE n (s1 INT PRIMARY KEY, s2 ARRAY) ;]])
box.execute([[INSERT INTO n VALUES (1,[1, 'a', ['abc', 321], 1.5]);]])
box.execute([[INSERT INTO n VALUES (3,[1, 'a', ['abc', 321], 1.5]);]])
box.execute([[SELECT s1,s2 FROM n ORDER BY s2, s1;]])
```
Result:
```
  - [3, [1, 'a', ['abc', 321], 1.5]]
  - [1, [1, 'a', ['abc', 321], 1.5]]
```
I believe this is wrong. The values in s2 are the same, therefore
the second ORDER BY column should have been used, so I think that
the correct result would be:
```
  - [1, [1, 'a', ['abc', 321], 1.5]]
  - [3, [1, 'a', ['abc', 321], 1.5]]
```

4
I execute these requests:
``` lua
box.execute([[DROP TABLE n;]])
box.execute([[CREATE TABLE n (s1 INT PRIMARY KEY, s2 ARRAY, s3 ARRAY);]])
box.execute([[INSERT INTO n VALUES (1,[1, 'a', ['abc', 321], 1.5], NULL);]])
box.execute([[ALTER TABLE n ADD COLUMN s4 INT;]])
```
Result =
Tuple field count 3 does not match space field count 4
Okay, this isn't specifically an ARRAY problem (sorry), but wouldn't it be
less confusing if the message was "ALTER is illegal because rows exist"?

5
I execute this request with Tarantool version 2.8:
``` lua
box.execute([[SELECT CAST("parts" AS VARBINARY) FROM "_vindex" limit 1;]])
```
Result = No error.
I execute this request with Tarantool version 2.10:
``` lua
box.execute([[SELECT CAST("parts" AS VARBINARY) FROM "_vindex" limit 1;]])
```
Result = Error = Type mismatch: can not convert array([[0, "string"]]) to varbinary'
I call this a "regression".

6
These perhaps could be described as limitations, so I am only asking
for a clear statement that the behaviour is deliberate.
a: There is no resemblance between this and the standard-SQL ARRAY data type.
b: Neither LENGTH() nor CARDINALITY() will work.
c: There is no plan to support associative arrays (maps).
d: Array columns cannot be used with any built-in function except CAST().
   That includes the previously-discussed functions LENGTH() and CARDINALITY().
   And CAST from any other type, except ANY, is illegal.
e: CREATE INDEX is is illegal. So is UNIQUE and PRIMARY KEY.
   And INDEXED BY is illegal with an RTREE index made via Lua.
g: Array columns cannot be used with = > >= < <= comparisons, only IS [NOT] NULL works.

Suggested fix: Cancel this feature, revert to the superior behaviour before issue #4762 was implemented.

**Comment by ImeevMA** [comment]
Hi @pgulutzan! I agree that 1, 2 and 3 are bugs. This is essentially the same error - in some cases I forgot to disable comparison for MAP and ARRAY. I'll fix it.

About 4 - please move it another issue. I do not plan to fix it here.

About 5 - ARRAY cannot be cast to anything other than ANY - see https://github.com/tarantool/doc/issues/2461. I don't think this is a regression.

About 6:
a) True. Our ARRAY is the same as ARRAY in BOX, so it is not the one from the standard.
b) True. Since there were different opinions about this feature, I decided to abandon it for now. If you think this is really necessary, please add a issue about adding CARDINALITY().
c) I believe we already have basic MAP support - see https://github.com/tarantool/doc/issues/2462. The syntax for MAP values is in review.
d) CAST() is not a built-in function, it is an operation. However, there are several functions that can work with ARRAY. For example, TYPEOF(), PRINTF(), QUOTE(), LIKELY() and so on. What else do you think should work with ARRAY?
e) ARRAY and MAP values cannot be compared, so there cannot be indexes containing MAP or ARRAY values.
g) True.

About the suggested fix: This won't happen.

**Comment by pgulutzan** [comment]
Re 4: Oops, I see that I already complained about it, it's issue #5917.
Re 5: Oops, I missed that you had already explained in https://github.com/tarantool/doc/issues/2461. I was looking at https://github.com/tarantool/doc/issues/2475. I made a comment there to say what I think can be done for documentation of this feature.
Re 6a) I don't agree that it's the same as in Tarantool box.
Why enclose in []s?
Lua arrays https://www.lua.org/pil/11.1.html look like {1,2} not [1,2]
and Tarantool console shows {}s too for what might someday be default:

tarantool> \set output lua
true;
tarantool> box.execute([[SELECT lua('return {1,2}');]])
{metadata = {{name = "COLUMN_1", type = "any"}}, rows = {{{1, 2}}}};

Also by using []s you're going to make it difficult if someday we want to use them for some other purpose like SQL Server compatibility or for use as an index within an array. It's true that {}s can have special meaning too e.g. for certain ODBC datetime literals, but I think conflict there is less likely.

**Comment by ImeevMA** [comment]
> Why enclose in []s?

This is the design suggested by @unera.

> Also by using []s you're going to make it difficult if someday we want to use them for some other purpose like SQL Server compatibility or for use as an index within an array. It's true that {}s can have special meaning too e.g. for certain ODBC datetime literals, but I think conflict there is less likely.

We will add operator `[]` to select values from MAP and ARRAY. The patch is in review.

**Comment by pgulutzan** [comment]
@unera might be right, I am reconsidering my comment about {}s and realizing that I shouldn't have casually said "for certain ODBC datetime literals", because ODBC drivers (and of course JDBC drivers oo)  might not only eat escape sequences that clearly are for datetimes, they might eat anything enclosed in braces. Of course, this also means that the plan to use braces for maps is bad too, but that's a separate issue.
So you're saying that, with the patch that is in review, [] can be used for both an array literal and an array index?
