### ISSUE TITLE
Roles: do not mix up roles and users

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#668]
If it is accepted that a user is not the same thing as a role, and if it is accepted that a role is not a type of user (except for implementor convenience in the _user space), then requests which specifically say "user" should not work for roles, and requests which specifically say "role" should not work for users. Therefore:
* `box.schema.user.drop|grant|revoke('R' [, ...])` should fail if R is a role
* `box.schema.role.drop|grant|revoke('U' [, ...]) should fail if U is a user

`box.schema.role.info()` depends on what a "current role" is. It could be declared that there is no such thing as a current role. Or it could be declared that every role which has been granted to the current user, including public, is a current role. But in either case, it should not show grants to the current user.

This is not a suggestion to change the name of the `_user` space, or a suggestion that roles should not be stored in the `_user` space.

See also:
* issue #665 Roles: `box.schema.role.exists` does not work.

**Comment by Sulverus** [comment]
Done:
1. Implemented in gh-668 branch
2. reviewed with Kostia
3. Merged

**Comment by pgulutzan** [comment]
I am looking at this detail in the original issue description: "But in either case, it [i.e. box.schema.role.info] should not show grants to the current user." In fact box.schema.role.info does show grants to the current user. For example, as user admin, I did these requests:
box.schema.role.info()
box.schema.create_space('t')
box.schema.user.grant('admin','read','space','t')
box.schema.role.info()
... And I see the grant on space t.
It probably is acceptable to reply "we decided to ignore that" and close this again.

**Comment by kostja** [comment]
Peter, role.info() should not be documented. Instead we came up with _vspace and _vindex tables. role.info() and user.info() are half-done and broken (I can come up with a number of cases when they don't show the necessary information, i.e. when privileges are inherited via a chain of grants/roles).

So, when it comes to role.info() and user.info() the decision is "won't fix", we will perhaps remove them from some future release.
