### ISSUE TITLE
debian: tarantool should NOT have runtime dependecy on binutils

### ISSUE THREAD

**Issue by amdei** [tarantool/tarantool#6699]
**Bug description**

Opposite to #1179 and follow-up to #2155.
Debian-package should NOT have run-time dependency from `binutils` package.
This is due to `binutils` include, among others, linker and assembler, what is in most cases forbidden on production server.
Looks like this dependency is a residual from times, when tarantool did use `libbfd` for stack unwinding.
Now it simply does not required at all.

* OS: Debian
* OS Version: all
* Architecture: all

**Actual behavior**

Debian package ARE depends on `binutils` package.

**Expected behavior**

Debian package DOES NOT have dependency on `binutils` package.

**Comment by Totktonada** [comment]
Nice catch, thanks!
