### ISSUE TITLE
tarantool console doesn't work with unix pipes

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#672]
I would like to use tarantool console in batch mode, to execute remote commands. 
I can't have a script with require('console').connect(arg[1]) and feed stuff into that script - this doesn't work.

This script writes 'need an existing console' when executed in pipe mode.

I was not even able to write a script like that with plain box.net.box && dostring, which should be easier, but I didn't pursue.

**Comment by rtsisyk** [comment]
cat xx | tarantool don't start our console. Instead of processing input line by line, tarantool passes stdin descriptor to Lua to process entire input with loadstring()/dofile() interface.

**Comment by pgulutzan** [comment]
I am assuming that this bug report is about this error message:
"
localhost:3301> console.delimiter('!')
---
- error: 'builtin/console.lua:229: console.delimiter(): need existing console'
...
"

The message is cryptic and the situation is surely common, so I regret that this is called a "feature" request.

**Comment by khmelevskii** [comment]
tarantool test.lua
tarantool: builtin/console.lua:271: console.connect() need existing console

**Comment by kostja** [comment]
@rybakit needs this feature as well, it's OK if it's available in tarantoolctl, not in tarantool itself.

**Comment by rtsisyk** [comment]
`console.connect()` and `console.delimiter()` works only if you use an interactive console and/or `tarantoolctl enter`. `cat lua.xx  | tarantool` works exactly as expected - like original Lua interpreter.
Why do you need delimiters for local files?

**Comment by rybakit** [comment]
My use case was about executing arbitrary lua code for the concrete instance, something like 

```
echo 'print(box.session.id())' | tarantoolctl eval instance
```
As a workaround, I use 
```
echo "box.session.id()" | socat - UNIX-CONNECT:/var/run/tarantool/instance.control
```
but, besides it's not intuitive, it also outputs some garbage, which I need to take care of:

```
Tarantool 1.6.8-102-g094d13b (Lua console)
type 'help' for interactive help
---
- 8
...
```

**Comment by rtsisyk** [comment]
Discussed with @bigbes  and @kostja  =>

```
$ echo 'expression' | tarantoolctl eval instance
---
- result
...
```

* On success result should be printed to stdout as YAML and $? set to 0
* On error (`type(resp) == 'table' and resp.error ~= nil`) result should be printed stderr and return code set to 1

**Comment by kostja** [comment]
Besides eval, it should work the same way for 'connect'
