### ISSUE TITLE
datetime MessagePack decoder does not validate values

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#6723]
```Lua
msgpack = require('msgpack')
mp = '\xd8\x04'
mp = mp..string.rep('\xff', 16)
dt = msgpack.decode(mp)
dt == dt + {day=0}
```
```
tarantool> dt == dt + {day=0}
---
- false
...
```
`dt` is broken. However from its `__tostring` it is not obvious. It becomes obvious when it fails a simple check like `self == self + 0`. It works for normal datetime objects, but not for this broken one. In this MessagePack I simulated like the original `struct datetime` had `0xff` in all its bytes.

**Comment by Gerold103** [comment]
This one is a bit harder to detect. I couldn't get a crash, I only got reading of garbage data. To make it crash I needed to add an obvious assertion in one place.
```Diff
--- a/src/lib/core/mp_datetime.c
+++ b/src/lib/core/mp_datetime.c
@@ -61,6 +61,7 @@ datetime_unpack(const char **data, uint32_t len, struct datetime *date)
 	const char *const svp = *data;
 	memset(date, 0, sizeof(*date));
 
+	assert(len >= 8);
 	int64_t i_epoch = load_u64(*data);
 	date->epoch = i_epoch;
 	*data += sizeof(i_epoch);
```
If you are reading 8 bytes, you need to be sure you have 8 bytes by that pointer. But it crashes when I do this:
```Lua
msgpack = require('msgpack')
mp = '\xd4\x04\xff'
msgpack.decode(mp)
```
```
tarantool> msgpack.decode(mp)
Assertion failed: (len >= 8), function datetime_unpack, file /Users/gerold/Work/Repositories/tarantool/src/lib/core/mp_datetime.c, line 64.
Process 90868 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = hit program assert
    frame #4: 0x00000001002bfdbf tarantool`datetime_unpack(data=0x00000001059ffb68, len=1, date=0x0000000103e4d318) at mp_datetime.c:64:2
   61  		const char *const svp = *data;
   62  		memset(date, 0, sizeof(*date));
   63  	
-> 64  		assert(len >= 8);
   65  		int64_t i_epoch = load_u64(*data);
   66  		date->epoch = i_epoch;
   67  		*data += sizeof(i_epoch);
```

**Comment by alyapunov** [comment]
BTW in decimal we have similar problem, it also should be fixed.
<details>

```
tarantool> msgpack = require('msgpack')
---
...

tarantool> mp = '\xd4\x01\xcf'
---
...

tarantool> msgpack.decode(mp) -- <=== Here we load uint64_t from invalid memory
---
- error: 'msgpack.decode: invalid MsgPack'
...

```
</details>

Since nobody has found those problems, I guess it's not a big problem.

**Comment by tsafin** [comment]
> Let assume we want to check consistency of all data we load from messagepack stream 
> (highly doubted, considering that we have selected the fastest method to encode/decode, 
> not the most compact one, but in any case).

After these instructions:
```
tarantool> msgpack = require 'msgpack'
---
...

tarantool> mp = '\xd8\x04'
---
...

tarantool> mp = mp..string.rep('\xff', 16)
---
...

tarantool> dt = msgpack.decode(mp)
---
...

tarantool> dt == dt + {day=0}
---
- false
...

tarantool> dt
---
- 1969-12-31T23:58:59.-00000001-0001
...
```
we received this strange negative suvsecond, because of a fact that `nsec` is negative, and was not normalized:

```
tarantool> dt.nsec
---
- -1
...

tarantool> dt.epoch
---
- -1
...

tarantool> dt.tzoffset
---
- -1
...

tarantool> dt.tzindex
---
- -1
...
```

It's ok that `epoch`, `tzindex` and `tzoffset` contain values equal to -1. It's not very well for `nsec` though, and before normalization (proceeded inside of interval operation as you showed) thiese negative nanoseconds won't be applied to the second part, thus comparison will always return incorrect results if one of operand i normalized and another one is not.

I'll add brief validation facility, `[tnt_]datetime_validate`, but we should clearly realize that it would regress speed here (upto 2x).

As for assertion with invalid target buffer size then simple patch below fixed it:
```diff
--- a/src/lib/core/mp_datetime.c
+++ b/src/lib/core/mp_datetime.c
@@ -55,7 +55,7 @@ mp_sizeof_datetime(const struct datetime *date)
 struct datetime *
 datetime_unpack(const char **data, uint32_t len, struct datetime *date)
 {
-       if (len <= 0)
+       if (len < sizeof(int64_t))
                return NULL;
 
        const char *const svp = *data;
```

**Comment by Gerold103** [comment]
You don't need to validate it in comparators. You only need validate it when it arrived. In that scope it could be good to update `mp_check()` so as it would properly validate known MP_EXT type. Currently it does not check anything except their sizes.

**Comment by tsafin** [comment]
> You don't need to validate it in comparators. You only need validate it when it arrived. In that scope it could be good to update `mp_check()` so as it would properly validate known MP_EXT type. Currently it does not check anything except their sizes.

At least uuid is being validated via `tt_uuid_validate()`
