### ISSUE TITLE
tarantoolctl reload

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#675]
Add a controlled way to reload Lua modules without instance restart via tarantoolctl

**Comment by rtsisyk** [comment]
What do you want to reload? We have only /etc/tarantool/instances.enabled/myapp.lua file.. 
There is no sense calling dofile() on it.

**Comment by kostja** [comment]
The syntax is 
```
tarantoolctl reload path-to-file
```
Simply does "dofile(path-to-file)" to it in the given instance.
This is a simple feature for tarantoolctl, just a time-saver.

**Comment by Sulverus** [comment]
Awaiting for review

**Comment by kostja** [comment]
Merged.
