### ISSUE TITLE
PROMOTE for the next term sometimes arrives earlier than the term bump

### ISSUE THREAD

**Issue by sergepetrenko** [tarantool/tarantool#6754]
Try running the following test:
<details><summary>bug_test.lua</summary>

```lua
local luatest = require('luatest')
local helpers = require('test.luatest_helpers')
local cluster = require('test.luatest_helpers.cluster')
local g = luatest.group('bug')

g.before_each(function(g)
    g.cluster = cluster:new({})

    g.box_cfg = {
        election_mode = 'off';
        replication = {
            helpers.instance_uri('server_', 1);
            helpers.instance_uri('server_', 2);
        };
    }

    g.server_1 = g.cluster:build_and_add_server(
        {alias = 'server_1', box_cfg = g.box_cfg})
    g.server_2 = g.cluster:build_and_add_server(
        {alias = 'server_2', box_cfg = g.box_cfg})
    g.cluster:start()
end)

g.after_each(function(g)
    g.cluster:stop()
    g.cluster.servers = nil
end)

g.test_interfering_promote_in_wal = function(g)
    local wal_write_count = g.server_1:exec(function()
        box.error.injection.set('ERRINJ_WAL_DELAY', true)
        return box.error.injection.get('ERRINJ_WAL_WRITE_COUNT')
    end)

    g.server_2:exec(function()
        box.ctl.promote()
    end)
    g.server_1:wait_wal_write_count(wal_write_count + 2)

    local ok, err = g.server_1:exec(function()
        local f = require('fiber').new(box.ctl.promote); f:set_joinable(true)
        box.error.injection.set('ERRINJ_WAL_DELAY', false)
        return f:join()
    end)

    luatest.assert(
        not ok and err.code == box.error.INTERFERING_PROMOTE,
        'interfering promote not handled')
end
```

</details>

`./test-run.py $(yes replication-luatest/bug_test.lua | head -n 1000) -j16`

Sooner or later all the workers will hang.

The workers hang for the following reason:
Note, after `server_2` has issues `box.ctl.promote()`, we wait for 2 wal write attempts on `server_1`:
```lua
g.server_1:wait_wal_write_count(wal_write_count + 2)
```
This is because we assume, that `server_1` will first receive the term bump (`IPROTO_RAFT`), and only then the promote request itself.

When the waiting for 2 wal writes times out, this is because PROMOTE arrives first, and applier is blocked on a synchronous WAL write, so it never reads the term bump and never attempts the second write.

A PROMOTE for a specific term arriving on a replica earlier than the term bump itself might be bad: we assume everywhere that txn_limbo's term (bumped by promote) always follows raft term.

In order to fix this we might either write server's full raft state together with a PROMOTE or, maybe, relay raft term updates from WAL instead of relying on asynchronous notifications.

Found by @grafin while working on #6033

**Comment by grafin** [comment]
I think i finally found the cause of the problem. It is not the order of term increment and promote msg. It is that term is being incremented via raft_sm_schedule_new_term() which calls raft_sm_pause_and_dump() where nothing happens because of:
```c
if (raft->is_write_in_progress)
    return;
```
Because of that term increment just doesn't happen at all. The whole event loop architecture around RAFT looks very fragile.

**Comment by Gerold103** [comment]
Well, it happens later, when the current WAL write is done. It will check if the written data != the most actual data and will make another WAL write.

**Comment by grafin** [comment]
My mistake. It was just a coincidence that in gcov that branch was visited same amount of times as there were stuck runs.
@sergepetrenko helped me investigate the order of term bump and promote messages and we agreed that possible solution is to set something like msg_sent flag from relay thread, that can be accessed from tx thread, and when sending term bump wait for it to be actually sent.
