### ISSUE TITLE
sophia engine creates sophia dir with empty 'snapshot' file

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#678]
Sophia engine creates 'sophia' dir with empty snapshot file even if no space with engine=sophia is created.

**Comment by pmwkaa** [comment]
fix on branch sophia-gh-678

**Comment by kostja** [comment]
Dmitry, this fix contradicts what PeterG is asking for in gh-684.
Sophia should never auto-create its directory, it's the job of tarantoolctl. By default sophia_dir should be the same as work_dir, which is the same as CWD.

**Comment by kostja** [comment]
A ticket can be closed only when it's merged.
You should add 'Fixes gh-678' to the changeset comment, then it gets closed automatically when I push the change to the master. Otherwise you need to watch when the patch is merged and then close the ticket.

**Comment by pmwkaa** [comment]
Please don't confuse tarantool and tarantoolctl. If i add check for sophia_dir existance on startup (fail if not exists, on a first sophia index creation), it will break stand alone tarantool and shebang modes for sophia.

We might need a tarantool option for sophia which will change this behaviour (create by default).

**Comment by pmwkaa** [comment]
Please review

**Comment by rtsisyk** [comment]
Fixed.
