### ISSUE TITLE
One byte of death

### ISSUE THREAD

**Issue by ligurio** [tarantool/tarantool#6781]
**Bug description**

* OS: Linux
* OS Version: Ubuntu 20.04 x86_64
* Architecture: amd64

```
Tarantool 2.10.0-beta2-37-g9d43b842b
Target: Linux-x86_64-Debug
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_BACKTRACE=ON
Compiler: /usr/bin/clang /usr/bin/clang++
```

**Steps to reproduce**

In Tarantool's console:

```
box.cfg{listen=3303}
require('net.box').connect('3303'):call('\x8a')
```

**Actual behavior**

Tarantool is dead.

**Expected behavior**

Tarantool is alive.

**Comment by Korablev77** [comment]
Here we go again
https://github.com/tarantool/tarantool/issues/4773
