### ISSUE TITLE
Execution of traces inside a vmevent handler corrupts stitching

### ISSUE THREAD

**Issue by Buristan** [tarantool/tarantool#6782]
Reproducer:

```
$ ./luajit -jdump=-m -e '
-- Make compiler really aggressive.
jit.opt.start("recunroll=1", "callunroll=1", "hotloop=1")
local function f(n)
  return n < 2 and n or f(n - 1) + f(n - 2)
end
-- Compile `bc` functions.
require"jit.bc".dump(loadstring(string.dump(f)))
-- Here we dump info about `f()` traces and run bc functions inside.
print(f(10))

...
luajit: /home/burii/builds_workspace/luajit/t_master/src/lj_trace.c:517: trace_stop: Assertion `(J->exitno)>0 && (MSize)(J->exitno)<J->sizetrace' failed.
Aborted (core dumped)
```

`J->exitno` means the number of an exit from a currently executed trace __and__ also a number of a trace with which we want to stitch after C function execution. If part of a function has been compiled before a vmevent handler was called, its trace is used during the vmevent handler on recording. When recording trace to stitch `J->exitno` is set to the previously executed trace. After running trace in the vmevent handler and exit it by a snapshot `J->exitno` is set to the number of exit instead number of trace to stitch. It's the moment when stitching is broken.

**Comment by MikePall** [comment]
Fixed upstream. https://github.com/LuaJIT/LuaJIT/commit/b5b20191f3a8a2e2d28f1362b11bd26a51083d89
