### ISSUE TITLE
Add workflow for catching missing changelog

### ISSUE THREAD

**Issue by locker** [tarantool/tarantool#6790]
Sometimes developers forget to update the [changelog](https://github.com/tarantool/tarantool/tree/master/changelogs/unreleased) when adding a new feature or fixing a bug. It'd be nice to have a workflow that would fail in this case. Since not all commits require change log entries, we'd need to be able to suppress the check somehow. The suggestion is to use a tag in the commit message, for example:

```
test: fix flaky test

Closes #XXXX

NO_CHANGELOG=test fix
```

**Comment by Totktonada** [comment]
Should it be applied to only to commits that are closing issues?

**Comment by locker** [comment]
> Should it be applied to only to commits that are closing issues?

I'd apply the check to all commits. If a commit is preparatory and doesn't need a change log, the author can add the `NO_CHANGELOG` tag to the commit messsage. BTW, we could do the same to catch missing doc bot request. I don't see anything wrong with most commits having `NO_CHANGELOG NO_DOC` in the log.
