### ISSUE TITLE
Sophia: assertion on update

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#680]
I have Ubuntu 12.04 and Tarantool 1.6 pulled from source today.

I execute these requests:
"
box.cfg{}
box.schema.space.create('tester', {engine='sophia'})
box.space.tester:create_index('primary',{type = 'tree', parts = {2, 'STR'}})
box.space.tester:insert{1,'X'}
box.space.tester:update({'X'}, {{'=', 2, 'Y'}})
"

The result after box.space.tester:update looks like this:

tarantool> box.space.tester:update({'X'}, {{'=', 2, 'Y'}})
/home/pgulutzan/tarantool-master/src/box/engine_sophia.cc:302: virtual void SophiaFactory::commit(txn*): Assertion `sp_get(lc) == __null' failed.
2014-12-28 14:03:23.618 [29801] main/101/spawner I> Exiting: master shutdown
Aborted (core dumped)

**Comment by pmwkaa** [comment]
fixed on branch sophia-snapshot
