### ISSUE TITLE
Sophia: support or produce error on space::alter

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#681]
I have Ubuntu 12.04 and Tarantool 1.6, pulled from source today.

I execute these requests:
"
s = box.schema.space.create('M',{engine='sophia'})
s:create_index('primary',{})
s:insert{5}
s.index.primary:alter({parts={1,'NUM'}})
"

The result of the alter is:
Result: error: sophia/so_ctl.c:335 database '555' is exists

I don't know what this means. With engine='memtx' things look okay.

The rename request causes the same message.

**Comment by kostja** [comment]
Progress?

**Comment by pmwkaa** [comment]
implemented on brach sophia-integration
