### ISSUE TITLE
an option to prevent net.box.connect() from schema fetching

### ISSUE THREAD

**Issue by parihaaraka** [tarantool/tarantool#6812]
subj
1) custom iproto-servers doesn't contain `box` and so on;
2) some users may intend to use `call` and/or `eval` only.

**Comment by Gerold103** [comment]
Duplicate of https://github.com/tarantool/tarantool/issues/4789.

**Comment by parihaaraka** [comment]
> Duplicate of #4789.
yep.. sorry
this 5 min issue looks like abandoned :/
