### ISSUE TITLE
Sophia: assertion on startup

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#683]
I have Ubuntu 12.04 and Tarantool 1.6, pulled from source today.

After starting with box.cfg{} -- using default configuration --
I executed some functions which create millions of random tuples.
After some time, the functions stop with the message
- error: Failed to allocate 124 bytes in slab allocator for tuple
... which is fine, not a bug. However, when I try to start again,
box.cfg{} -- or box.cfg{slab_alloc_arena=2.0} etc. --
fails and the screen looks like this:
"
/home/pgulutzan/tarantool-master/src/tarantool: version 1.6.3-760-g5e9553d
type 'help' for interactive help
tarantool> box.cfg{slab_alloc_arena=3.0}
2014-12-31 16:18:46.993 [2479] main/101/interactive C> version 1.6.3-760-g5e9553d
2014-12-31 16:18:46.993 [2479] main/101/interactive C> log level 5
2014-12-31 16:18:46.995 [2512] main/101/spawner C> initialized
2014-12-31 16:18:46.995 [2479] main/101/interactive I> mapping 3221225472 bytes for a shared arena...
2014-12-31 16:18:46.999 [2479] main/101/interactive I> recovery start
2014-12-31 16:18:46.999 [2479] main/101/interactive I> recovering from `./00000000000000000000.snap'
2014-12-31 16:18:47.043 [2479] main/101/interactive I> recover from `./00000000000000000000.xlog'
/home/pgulutzan/tarantool-master/src/box/engine_sophia.cc:302: virtual void SophiaFactory::commit(txn*): Assertion `sp_get(lc) == __null' failed.
2014-12-31 16:18:47.144 [2512] main/101/spawner I> Exiting: master shutdown
Aborted (core dumped)
"
... which makes me worry that, after an allocation failure, perhaps the database is not recoverable?

The rest of this issue report is a copy of the functions that I was running before the
"failed to allocate" error happened.

box.space.tester:drop()
box.schema.space.create('tester', {engine='sophia'})
box.space.tester:create_index('primary',{type = 'tree', parts = {2, 'STR'}})
console = require('console'); console.delimiter('!')
function string_function()
  local random_number
  local random_string
  random_string = ""
  for x = 1,100,1 do
    random_number = math.random(65, 90)
    random_string = random_string .. string.char(random_number)
    end
  return random_string
  end!
function delete_replace_update()
  local counter, string_value, string_value_2, string_value_3, random_number
  for counter = 1,10000000,1  do
    print(counter)
    string_value = string_function()
    string_table = box.space.tester.index.primary:select({string_value}, {iterator = 'GE', limit = 1})
    if string_table[1] == nil then string_value_2 = box.space.tester:insert{counter, string_value}[2]
    else string_value_2 = string_table[1][2] end
    if string_value_2 == nil then string_value_2 = box.space.tester:insert{counter, string_value}[2] end
    random_number = math.random(1,4)
    string_value_3 = string_function()
    if random_number == 1 then box.space.tester:delete{string_value_2} end
    if random_number == 2 then box.space.tester:replace{counter, string_value_2} end
    if random_number == 3 then box.space.tester:replace{counter, string_value_3} end
    end
  end!
console.delimiter('')!
delete_replace_update()

**Comment by pmwkaa** [comment]
Thank you. This is related to gh-680.

**Comment by pgulutzan** [comment]
Okay, glad to know it might be part of something that's already known. It's potentially serious though, because it happens even if I never never create a sophia space.

**Comment by pmwkaa** [comment]
fixed on branch sophia-snapshot (as part of #680)
