### ISSUE TITLE
Extend signature of http.client.request()

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#6831]
Current API:

```
http.client.request(method: string, url: string) 
http.client.request(method: string, url: string, body: string) 
http.client.request(method: string, url: string, body: string, opts: table) 
```

I propose to add one more case for compatibility with [Python Requests API](http://docs.python-requests.org/en/master/api/#requests.request): 

```
http.client.request(method: string, url: string, opts: table) 
```

`opts` is table, `data` is string, so all cases can be easily recognized.

**Comment by Totktonada** [comment]
The HTTP client now accepts a table as a `body` (#6833). The issue is not relevant anymore.
