### ISSUE TITLE
Stream-oriented interface of http.client.request()

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#6834]
Currently `http.client.request()` returns a Lua table with the following fields:
- `resp.status` - http code
- `resp.reason` - textual reason of responded HTTP Status, e.g. "Not Found" or "OK".
- `resp.headers` - headers (table)
- `resp.body` - raw body of response

Current implementation is not stream-oriented - `body` is fully read once. I want to import > 1 GB file to box.space using `http.client`.

Proposed changes:
- `resp:body()` - read response body, close socket.
- `resp:json()` - read response body, close socket, return decoded JSON.
- `resp:read({ size = size, delimiter = delimiter })` - a wrapper for `socket.read()`. See  request_read() function in `http/server.lua`.
- `resp:close()` - close socket. Once this method has been called the underlying `:body()`, `:json()`, `:read()` methods must not be called again. Should not normally need to be called explicitly.

**Comment by Totktonada** [comment]
There is more detailed #7845 about streaming of a request and a response. I'll close this one as duplicate.
