### ISSUE TITLE
Inconsistency with box.cfg and directories

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#684]
I notice that directory handling is inconsistent.

#1 If directory snap_dir does not exist, then I cannot say
box.cfg{snap_dir='snap_dir'} -- causes a severe error
... SystemError error reading directory 'snap_dir': No such file or directory
... box.cfg fails, no attempt is made to create snap_dir

#2 But if directory sophia_dir does not exist, then I can say
box.cfg{sophia_dir='sophia_dir'} -- causes no error
... initializing an empty data directory
... a new directory is created with the specified name

#3 And if directory work_dir does not exist, then I can say
box.cfg{work_dir='work_dir'} -- causes a non-severe error
... can't chdir to `work_dir': No such file or directory
... Although an error message appears, box.cfg succeeds
... Directory work_dir is not created; default directory is used

Why doesn't the same thing happen in every case?

It looks more user-friendly to create a new directory (#2),
but I suppose there must have been a reason for returning
a severe error (#1), which was coded before #2.
As for #3, where the user is explicitly asking for 'work_dir'
but Tarantool is returning 'default directory' and pretending
that is okay -- that used to be okay according to MySQL,
but not according to the Bible.

**Comment by kostja** [comment]
Dmitry, sophia initialization must fail with an error if the directory does not exist.

**Comment by rtsisyk** [comment]
Fixed.

**Comment by kostja** [comment]
Roman, please fix issue number 3 as well first.
