### ISSUE TITLE
 BETWEEN shortcut

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#685]
A common case is to retrieve all keys with the same prefix. One can use EQ iterator for this.

On the same token, we could have a shortcut for BETWEEN operation, when two keys are given in the range.

Suggested syntax options:

```
index:select({from, to}, { iterator = 'BETWEEN'}  )

index:pairs(key):until(key_end)
```

**Comment by rtsisyk** [comment]
I didn't catch it..

**Comment by rtsisyk** [comment]
OK, I've got it. I need to think about that. May be we can use some luafun feature for that.

**Comment by rtsisyk** [comment]
Raw idea: `index:select({from, to}, { iterator = 'BETWEEN'} )`

**Comment by unera** [comment]
> Raw idea: index:select({from, to}, { iterator = 'BETWEEN'} )

Raw idea: `index:select({from}, { iterator = 'LT|GT|LE|GE', to = {to}})`

**Comment by kostja** [comment]
Sorry, this is definitely won't fix now. 1.7 is frozen and we're focusing on 1.8 which has SQL.

**Comment by Khatskevich** [comment]
I propose to reopen this ticket because it is not only "nice" thing, but it also increases speed.

We do not want to compare each tuple with the key while iterating over the range. Particularly, we have unicode collations and this comparison can be expensive.
