### ISSUE TITLE
box.ctl.demote() and synchro queue owner interaction is inconsistent.

### ISSUE THREAD

**Issue by grafin** [tarantool/tarantool#6860]
**Bug description**

box.ctl.demote() and synchro queue owner interaction is inconsistent.

Running box.ctl.demote() with election_mode = 'off' sets synchro queue owner to NIL.
Running box.ctl.demote() with election_mode = 'manual' leaves synchro queue owner as is.

**Steps to reproduce**

```lua
box.cfg{election_mode = 'manual'}
box.ctl.promote()
box.ctl.demote()
box.cfg{election_mode = 'off'}
box.schema.create_space('test'):create_index('pk')
box.space.test:replace({1})
box.ctl.demote()
box.space.test:replace({1})
```

This leads to not so obvious behaviour:
On leader node with election_mode = 'manual' run box.ctl.demote(), set box.cfg{replication_mode='off'} now this node (assuming no one else took synchro queue from it) is RW (for synchronous transactions too). Further calls to box.ctl.demote() will not do anything, because term was bumped during previous demote and now this node doesn't consider itself leader.

**Actual behavior**

Node is RW, it can't be demoted.

**Expected behavior**

I don't really know.

**Comment by Gerold103** [comment]
The example is outdated, it won't work now due to fencing:
```Lua
box.cfg{election_mode = 'manual'}
box.ctl.promote()
box.ctl.demote()
box.cfg{election_mode = 'off'}
box.schema.create_space('test')
```
```
---
- error: Can't modify data on a read-only instance - synchro queue with term 2 belongs
    to 1 (1c42af5b-492a-43ed-b0d7-fe768ffc14c3) and is frozen due to fencing
...
```

> Running box.ctl.demote() with election_mode = 'off' sets synchro queue owner to NIL.

That is correct. This is done with the intention to allow people to delete all the artifacts of qsync and raft completely without a trace: no owner of the queue and no election leader.

> Running box.ctl.demote() with election_mode = 'manual' leaves synchro queue owner as is.

That is also correct. In non-off mode the queue should always be owned. The instance will be read-only anyway, whether the owner is 0 or not. Because in non-off election mode only the leader is writeable. I.e. if the instance stopped being a leader, then changing the queue owner to 0 on it won't allow any writes.

> Further calls to box.ctl.demote() will not do anything, because term was bumped during previous demote and now this node doesn't consider itself leader.

This is indeed strange. The following script shows the not so intuitive behaviour on 3.0:
```Lua
box.cfg{election_mode = 'manual'}
box.ctl.promote()
box.ctl.demote()
box.cfg{election_mode = 'off'}
```
```
tarantool> box.info.election
---
- leader_idle: 3.3667780000251
  state: follower
  vote: 0
  term: 3
  leader: 0
...

tarantool> box.info.synchro
---
- queue:
    owner: 1
    term: 2
    len: 0
    busy: false
  quorum: 1
...
```
As we can see, all is fine here. Not a leader, the queue is owned and is one term behind. `box.ctl.demote()` won't do anything from this moment. But it can be hacked liked so:
```Lua
box.ctl.promote()
```
```
tarantool> box.info.election
---
- state: follower
  vote: 0
  leader: 0
  term: 4
...

tarantool> box.info.synchro
---
- queue:
    owner: 1
    term: 4
    len: 0
    busy: false
  quorum: 1
...
```
```Lua
box.ctl.demote()
```
```
tarantool> box.info.synchro
---
- queue:
    owner: 0
    term: 5
    len: 0
    busy: false
  quorum: 1
...
```

Apparently, `box.ctl.demote()` in off-mode won't do anything if the queue term is behind the election term. But otherwise it works as expected.

The same happens even if the owner is another replica which might even be down. So the quorum is not required if the limbo is empty already.

It seems we could harmlessly allow the full demote of the queue in off-mode even if its term is < raft term. What do you think - @sergos, @sergepetrenko, @grafin?

The place in the code is
```
int
box_demote(void)
{
    ...
    /* Currently active leader is the only one who can issue a DEMOTE. */
    bool is_leader = txn_limbo_replica_term(&txn_limbo, instance_id) ==
             box_raft()->term && txn_limbo.owner_id == instance_id;
    if (box_election_mode != ELECTION_MODE_OFF)
        is_leader = is_leader && box_raft()->state == RAFT_STATE_LEADER;
    if (!is_leader)
        return 0;
    ...
```
In the off-mode we could allow demote if limbo term `<=` raft term, not strictly `==`. It won't decrease the safety anyway.


<details>
<summary>Example with demote from non-owner instance (click)</summary>

```Lua
--
-- Instance 1
--
-- Step 1
--
box.cfg{
    listen = 3313,
    replication = {3313, 3314},
    election_mode = 'manual'
}
box.schema.user.grant('guest', 'super')
--
-- Step 3
--
box.ctl.demote()
box.cfg{election_mode = 'off'}
--
-- Step 5
--
os.exit(0)


--
-- Instance 2
--
-- Step 2
--
box.cfg{
    listen = 3314,
    replication = {3313, 3314},
    election_mode = 'manual',
    read_only = true
}
--
-- Step 4
--
box.cfg{election_mode = 'off'}
--
-- Step 6
--
box.ctl.promote()
box.ctl.demote()
```
</details>

**Comment by sergepetrenko** [comment]
> It seems we could harmlessly allow the full demote of the queue in off-mode even if its term is < raft term. What do you think

Sounds good to me.

**Comment by Gerold103** [comment]
Frankly, I am not sure anymore. Perhaps we should leave it as is. I made a patch, it is simple, but I forgot that there might be installations which use qsync without our elections. For them allowing a demote to disown the queue regardless of the owner might be disruptive. I will ask again just in case - @sergepetrenko, @grafin, @sergos - are sure we want to allow that?

**Comment by grafin** [comment]
> allowing a demote to disown the queue regardless of the owner might be disruptive. 

I might be not fully understanding the problem here: we are about to relax the term check, not the owner. Of the queue isn't owned by the instance, demoting on it shouldn't do anything.

**Comment by Gerold103** [comment]
> I might be not fully understanding the problem here: we are about to relax the term check, not the owner.

Assume you were owner of the queue in term 3. And your election term is 4. There is no way to tell if there is no other instance which owns the queue in the term 4 (when elections are off). So the term relax is equivalent to not checking the owner at all (again, when elections are off).

**Comment by sergepetrenko** [comment]
> Assume you were owner of the queue in term 3. And your election term is 4. There is no way to tell if there is no other instance which owns the queue in the term 4 (when elections are off). So the term relax is equivalent to not checking the owner at all (again, when elections are off).

Actually it's not the same as not checking the owner.

Not checking the owner means you may "steal" the synchro queue from the current owner. By issuing demote in the most actual term.

But not checking the term is different. Even if you know only of term 3, and somewhere exists a node, who owns a queue in term 4, your demote will happen in term 4. So this will be a split-brain. It won't harm the rest of the cluster (unlike in the first example, where the demote will spread everywhere).

I think this is fine. Term check doesn't guard us from this anyway. For example, the node might have a stale raft term, and in this case the term check will pass just fine but the same situation will happen.

So, I still vote for skipping the term check. What do you think @Gerold103 @grafin ?

**Comment by grafin** [comment]
I think its ok to skip the term check. AND ignore demotes in term where promote has been issued (treat it as a split brain, which it is), I thought that it currently works like that.

**Comment by sergepetrenko** [comment]
> (treat it as a split brain, which it is), I thought that it currently works like that.

This is how it works now: https://github.com/tarantool/tarantool/blob/a6054f01bd5bcf327b29e5c12daaefdce9204244/src/box/txn_limbo.c#L1037-L1043
