### ISSUE TITLE
Segmentation fault on xlog write(?)

### ISSUE THREAD

**Issue by Anei** [tarantool/tarantool#687]
Here's a log: https://gist.github.com/Anei/9bc26f3c41a68936bda1#file-gistfile1-txt
After restart tarantool was unable to read one xlog file: https://gist.github.com/Anei/9bc26f3c41a68936bda1#file-gistfile2-txt

File exists and has correct access rights, there's a huge amount of free disk space. File size is 0:
```
root@avi-cluster85 lib/tarantool/tarantool-ru-12 # ls -la /var/lib/tarantool/tarantool-ru-12/00000000000111279236.xlog
-rw-r--r-- 1 tarantool tarantool 0 Jan 13 20:21 /var/lib/tarantool/tarantool-ru-12/00000000000111279236.xlog
```

After deleting this file tarantool started successfully.

**Comment by alyapunov** [comment]
We've established the cause and fixed this bug.
