### ISSUE TITLE
Configure logger without calling box.cfg{}

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#689]
It would be nice to configure logger (at least level) without calling box.cfg{}.
I need it to properly write test for #411 and #460.

**Comment by rtsisyk** [comment]
In progress

**Comment by cyrillos** [comment]
https://lists.tarantool.org/pipermail/tarantool-patches/2020-May/016995.html

**Comment by Totktonada** [comment]
Implemented in [2.5.0-100-ga94a9b3fd](https://github.com/tarantool/tarantool/commit/a94a9b3fd629b5abbc99a23ba527cd91e5c6ebf5). So, available since 2.5.1 and in all 2.6+ releases.
