### ISSUE TITLE
Respond to SUBSCRIBE request explicitly

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#691]
The master replies to SUBSCRIBE request with a stream of rows. If there are no rows,
the master is silent.
However, subscribe may fail in case of server id or cluster id mismatch.
The replica has no way to know whether a connection is dead or it has failed to subscribe if there is no response.
The server should send OK packet first.

**Comment by rtsisyk** [comment]
This feature already was implemented in 1.6.7. A test case is hard to make.

**Comment by rtsisyk** [comment]
Tested explicitly by replication code.
