### ISSUE TITLE
sophia: fix options settings

### ISSUE THREAD

**Issue by pmwkaa** [tarantool/tarantool#694]
Make it possible to change a single sophia configuration fields.

Right now complete lua table is needed to change any configuration. Set not defined options in lua table with default values.

**Comment by pmwkaa** [comment]
fixed on branch sophia-gh-694

**Comment by kostja** [comment]
@alyapunov, this is your domain, the fix is quite ugly, and we need nested configuration option for memtx, replication, write ahead logging, etc. 

Please either tell Dmitry how to, or come up yourself with a generic fix.

This also needs a proper test case in app/cfg.test.lua.
