### ISSUE TITLE
Bump openssl version in static build

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#6947]
Currently we have 1.1.1f:

https://github.com/tarantool/tarantool/blob/7dc9fe44a5aebc2b44c240221d2a71cd6d97b6b0/static-build/CMakeLists.txt#L15-L16

While 1.1.1n is released now.

Changelog: https://www.openssl.org/news/cl111.txt

Vulnerabilities: https://www.openssl.org/news/vulnerabilities.html

**Comment by locker** [comment]
Backported to 2.8 and 1.10.
