### ISSUE TITLE
SQL ROUND function doesn't work for legit fractional expressions

### ISSUE THREAD

**Issue by msiomkin** [tarantool/tarantool#6988]
**Bug description**

A lot of legitimate fractional expressions are not handled by SQL ROUND function any more. The reasons are:

1. Fractional constants now have 'decimal' type.
2. Implicit typecasts are eliminated for cases when loss of precision may occur.

Possible solution to the problem: we need a decimal overload of SQL ROUND function.

* OS: Linux
* OS Version: Centos 8
* Architecture: amd64

Tarantool 2.10.0-beta2-207-ga5557281c
Target: Linux-x86_64-Release
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_BACKTRACE=ON
Compiler: /usr/lib64/ccache/cc /usr/lib64/ccache/c++
C_FLAGS: -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type
CXX_FLAGS: -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type

**Steps to reproduce**

Run tarantool, box.cfg{}

Run query:
```lua
box.execute([[select round(1.0 / 3)]])
```

**Actual behavior**

```
---
- null
- 'Type mismatch: can not convert decimal(0.33333333333333333333333333333333333333)
  to double'
...
```

**Expected behavior**

```
---
- metadata:
  - name: COLUMN_1
    type: decimal
  rows:
  - [0]
...
```

**Comment by ImeevMA** [comment]
Implicit cast fails since 0.33333333333333333333333333333333333333 cannot be precisely converted to DOUBLE value. I believe this is not a bug. We can go another way - we can add an implementations of ROUND() for INTEGER argument and DECIMAL argument, than there will be no need for this implicit cast. I set this issue as a `feature`.

**Comment by msiomkin** [comment]
The lack of decimal ROUND overload may be perfectly treated as a bug in this context! You should have cared about adding this overload before thoughtlessly breaking implicit type casting.

**Comment by ImeevMA** [comment]
If I remember correctly, DECIMAL was added to SQL after the implicit cast rules were applied. Adding a new function implementation is still a feature, not a bug. I see no problem adding this implementation after someone from the PM says it's necessary. @unera could you look at this?

**Comment by msiomkin** [comment]
An entirely legitimate SQL query doesn't work:

```
select round(1.0 / 3)
```

Surely it's a **bug** first of all! Secondly, even worse, it's a rude breaking of backward compatibility.

Why on earth should I care about the reasons and/or about the history of adding some features?!

**Comment by unera** [comment]
> Surely it's a bug first of all!

Yes, this is a bug

@ImeevMA Could You add `decimal ROUND(decimal, ....)` variant?

**Comment by ImeevMA** [comment]
Yes, I see no problem with this.
