### ISSUE TITLE
SQL SUM and AVG functions don't work for CASE expressions that may return NULL in their branches

### ISSUE THREAD

**Issue by msiomkin** [tarantool/tarantool#6990]
**Bug description**

subj

* OS: Linux
* OS Version: Centos 8
* Architecture: amd64

Tarantool 2.10.0-beta2-207-ga5557281c
Target: Linux-x86_64-Release
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_BACKTRACE=ON
Compiler: /usr/lib64/ccache/cc /usr/lib64/ccache/c++
C_FLAGS: -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type
CXX_FLAGS: -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type

**Steps to reproduce**

Run tarantool, box.cfg{}

Run query:
```lua
box.execute([[select sum(case when 1 = 1 then 1 else null end)]])
```

and

```lua
box.execute([[select avg(case when 1 = 1 then 1 else null end)]])
```

**Actual behavior**

```
---
- null
- 'Failed to execute SQL statement: wrong arguments for function SUM()'
...
```

and

```
---
- null
- 'Failed to execute SQL statement: wrong arguments for function AVG()'
...
```

**Expected behavior**

```
---
- metadata:
  - name: COLUMN_1
    type: integer
  rows:
  - [1]
...
```

**Comment by unera** [comment]
Yes, this is a bug.

Aggregate functions have to skip nulls instead throwing errors.

**Comment by msiomkin** [comment]
ROUND also fails:

```
tarantool> box.execute([[select round(case when 1 = 1 then 1 else null end)]])
---
- null
- 'Failed to execute SQL statement: wrong arguments for function ROUND()'
...
```

**Comment by unera** [comment]
@msiomkin 

> of the first branch

first not-null branch

**Comment by msiomkin** [comment]
Or even better use the 'traditional' approach:

https://docs.microsoft.com/en-us/sql/t-sql/language-elements/case-transact-sql?view=sql-server-ver15#return-types

**Comment by unera** [comment]
CASE should return the highest type of its branch. Do cast nulls-branches to the highest type.

**Comment by ImeevMA** [comment]
See also issue #6989 - it has the same problem and should be fixed in this issue.
