### ISSUE TITLE
Setup integration testing with Tarantool EE

### ISSUE THREAD

**Issue by locker** [tarantool/tarantool#7013]
A commit to the community repository can break Tarantool EE build, which uses the community repo as a submodule. For example, a function used in EE source code can be reworked or even dropped in the community repo. To catch such breakages early and fix Tarantool EE accordingly, we need a workflow that would do the following steps:
1. Checkout [tarantool-ee](https://github.com/tarantool/tarantool-ee).
2. Update the open-source submodule to the new commit.
3. Build tarantool-ee and run tests.

If the workflow fails, the PR author is supposed to fix Tarantool EE.

It may be difficult to fix Tarantool EE so that it works both for the new commit and for the commit before. If we push the open-source commit before the corresponding EE fix, the workflow will start to fail for the community master branch. If we push the EE fix first, we'll get red CI for the EE repo. Suggestion: run this workflow only on PR and not on push to master. This way, we'll always have green CI for master branches both in the community and EE repository, but at the same time we'll get an early signal if EE needs to be fixed.

**Comment by NickVolynkin** [comment]
It seems that we've already done it. Further improvements to integration testing will be made in https://github.com/tarantool/sdk/issues/353.
