### ISSUE TITLE
Tarantool doesn't exit on Ctrl+D

### ISSUE THREAD

**Issue by alyapunov** [tarantool/tarantool#7017]
Normally tarantool stops Ctrl+D. But with (at least) console.listen it doesn't.
```
tarantool -e "require('console').listen(3313) require('console').start()"
```
You have to hit Ctrl+D and then Ctrl+C to stop it.

**Comment by locker** [comment]
We enter the event loop after executing the script if there active libev events (e.g. there's a background fiber running, as it is the case with `console.listen`):

https://github.com/tarantool/tarantool/blob/d627ee2618c9f3e28cd91eab4b3f753379b5ce8c/src/main.cc#L774-L786

That said, the observed behavior, although may seem confusing at the first glance, is actually legit. You can eliminate the need to hit Ctrl-C after exiting the console with Ctrl-D by explicitly calling exit after `console.start`:

```
tarantool -e "require('console').listen(3313) require('console').start() os.exit(0)"
```

**Comment by locker** [comment]
Still, this looks confusing, especially if logging to stdout is disabled:

```
tarantool -e "box.cfg{log_level = 'error'} require('console').start()"
```

When I type Ctrl-D, Tarantool seemingly freezes - console stops to work, typed characters are not echoed. It looks like Tarantool hangs, but it just means that the console has exited, but Tarantool is still running in the background. We could write something to stdout to make things clear, for example, "Exited console. Type Ctrl-C to exit".
