### ISSUE TITLE
Add packages for brand new UBUNTU 22.04 Jammy Jellyfish

### ISSUE THREAD

**Issue by no1seman** [tarantool/tarantool#7062]
Since brand new UBUNTU 22.04 Jammy Jellyfish released seems need to add packages for it into CI and publish debs

**Comment by Totktonada** [comment]
Duplicate of https://github.com/tarantool/tarantool-qa/issues/160.

**Comment by NickVolynkin** [comment]
Duplicate of https://github.com/tarantool/tarantool-qa/issues/160
