### ISSUE TITLE
Export IProto constants

### ISSUE THREAD

**Issue by Korablev77** [tarantool/tarantool#7103]
Justification: in each test related to parsing/forming IProto requests by hand we should copy-paste them in test file over and over again. It would be nice to have them in the one place. They are described in docs; those constants can't be changed over time.

**Comment by Totktonada** [comment]
> They are described in docs; those constants can't be changed over time.

Internal constant names were changed at least two times.[^1]

* `IPROTO_CALL` was changed from 6 to 10. The old iproto request code (6) was renamed to IROTO_CALL_16 (d025d102f47a5247b24027435c8ecf54c09c7201).
* `IPROTO_ERROR` was changed from 0x31 to 0x52 (0x52 was formerly known as `IPROTO_ERROR_STACK`). The old response key was renamed to `IPROTO_ERROR_24` (2b4263d32bd36f7563f5b79b7815903a2c18b2c0).

Maybe there were other renames I don't aware about.

It means that we anyway need some updating process. Maybe version-based (`box.iproto.cfg({constant_version = <...>})`, maybe using [compat](https://github.com/tarantool/tarantool/discussions/6912) (`require('tarantool').compat({iproto_constant_foo = 'old'/'new'})`).

[^1]: I would highlight that it is only about internal constant names. An interpretation of old codes remain the same. The protocol only gains some new codes.

**Comment by locker** [comment]
This has been done in #7894. Automatic generation of the Lua translation table will be done in #8443.
