### ISSUE TITLE
console.test.lua fails in Fedora 19 x64

### ISSUE THREAD

**Issue by Sulverus** [tarantool/tarantool#712]
app/console.test.lua                            2015-02-04 15:44:41.626 [28567] main/101/console.test.lua F> builtin/console.lua:328: failed to create server unix/:/tmp/tarantool-test-console.sock: Address already in use
[ fail ]

Test failed! Result content mismatch:
--- app/console.result	Wed Feb  4 14:51:41 2015
+++ app/console.reject	Wed Feb  4 15:44:41 2015
@@ -27,6 +27,3 @@
 ok - console.listen uri support
 ok - console.listen uri support
 ok - console.listen uri support
-ok - console.listen uri support
-ok - console.listen uri support
-ok - console.listen uri support

Fatal error: Failed to run test app/console.test.lua: wrong test output. Execution aborted.

in tarantool.log:
2015-02-04 15:44:41.625 [28567] main/101/console.test.lua I> started on 127.0.0.1:0
2015-02-04 15:44:41.626 [28567] main/101/console.test.lua I> tcp_server: remove dead UNIX socket: /tmp/tarantool-test-console.sock
2015-02-04 15:44:41.626 [28567] main/101/console.test.lua socket.lua:1027 W> tcp_server: No such file or directory
2015-02-04 15:44:41.626 [28567] main/101/console.test.lua F> builtin/console.lua:328: failed to create server unix/:/tmp/tarantool-test-console.sock: Address already in use
2015-02-04 15:44:41.674 [28568] main/101/spawner I> Exiting: master shutdown

**Comment by kostja** [comment]
Roman, Andrey can quickly set up a virtual host for you.

**Comment by Sulverus** [comment]
It's already up on farm

$cd vmach/test/
$vagrant ssh

**Comment by Sulverus** [comment]
if run it separately it working correctly, test fails only if we run it with others:

app/boolean.test.lua                            [ pass ]
app/cfg.test.lua                                [ pass ]
app/console.test.lua                            2015-02-05 15:32:10.142 [10656] main/101/console.test.lua F> builtin/console.lua:328: failed to create server unix/:/tmp/tarantool-test-console.sock: Address already in use
[ fail ]

**Comment by rtsisyk** [comment]
socket.tcp_server() automatically removes old unix socket only **after one event loop iteration** (see tcp_server_loop function). I don't think that problem with delayed removal of unix socket file is very important for us. I'm adding a workaround to the test and closing this ticket.
