### ISSUE TITLE
app: query parameters parsing is slow under ASAN

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#7155]
Version: 2.11.0-entrypoint-38-g7175f1c85.

Test case: [clusterfuzz-testcase-minimized-uri_fuzzer-4766034870009856.zip](https://github.com/tarantool/tarantool/files/8720697/clusterfuzz-testcase-minimized-uri_fuzzer-4766034870009856.zip).

Build:

```shell
CC=clang-13 CXX=clang++-13 cmake . -DCMAKE_BUILD_TYPE=Debug -DENABLE_BACKTRACE=ON -DENABLE_DIST=ON -DENABLE_FEEDBACK_DAEMON=OFF -DENABLE_BUNDLED_LIBCURL=OFF -DENABLE_ASAN=ON -DENABLE_FUZZER=ON && make -j
```

Test:

```shell
$ ./test/fuzz/uri_fuzzer clusterfuzz-testcase-minimized-uri_fuzzer-4766034870009856 
<...>
Running: clusterfuzz-testcase-minimized-uri_fuzzer-4766034870009856
Executed clusterfuzz-testcase-minimized-uri_fuzzer-4766034870009856 in 25019 ms
<...>
```

Test from Lua:

```lua
tarantool> require('clock').bench(require('uri').parse, require('fio').open('clusterfuzz-testcase-minimized-uri_fuzzer-4766034870009856'):read())[1]
---
- 23.818751496
...
```

The test case has 132k query parameters with 33 unique names. Parsing of the parameters was added to `uri_create()` in 27cef5c80c8c88245591ff5d55d993ddb9602e9d (2.10.0-beta1-336-g27cef5c80). As I see from the parsing code, it intensively (re)allocates buffers. I suspect that allocations are considerably slow under ASAN.

@alyapunov asked me to file an issue on it to fix the query parameters parsing speed.

Originally reported by oss-fuzz in https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=44817 (will be disclosed 2022-05-19). You can find a bit more information here.

**Comment by CuriousGeorgiy** [comment]
I started researching this issue in my spare time, and here are the conclusions I have currently come up with:

The problem is clearly not in the parameter array allocation, since, as you wrote, there are only 33 unique parameters in the query.

I built a flame graph with the parameter array preallocated to 64 elements:
![out](https://user-images.githubusercontent.com/32464072/196237767-9da99dae-c0da-4947-be31-dbc7c651f7d4.svg)

The flame graph shows that most of the time is consumed by `memmove` but its callees are unknown, from which I draw the conclusion that it is called from inside **LuaJIT** (maybe it has something to do with reading the file with the URI string).

**Comment by CuriousGeorgiy** [comment]
@Totktonada could you please verify this from the side of your team?

**Comment by Totktonada** [comment]
@CuriousGeorgiy It is unclear, whether you test it using ASAN or other build, where the relative cost of `realloc()` is likely different. The original problem is reproduced on the uri fuzzer without Lua. I give a reproducer using Lua for convenience, but you can ignore it if it makes the profile harder to read.

Sure, 33 reallocs of the params array and 132k reallocs of values arrays. The second is likely the problem. It is easy to verify:

```diff
diff --git a/src/lib/uri/uri.c b/src/lib/uri/uri.c
index edf9f8b70..6c90be72c 100644
--- a/src/lib/uri/uri.c
+++ b/src/lib/uri/uri.c
@@ -17,6 +17,11 @@ struct uri_param {
 	int value_count;
 	/** Array of values for this parameter. */
 	char **values;
+	/**
+	 * Maximum amount of element in the `values` array (till
+	 * realloc).
+	 */
+	size_t capacity;
 };
 
 /**
@@ -38,9 +43,17 @@ uri_find_param(const struct uri *uri, const char *name)
 static void
 uri_param_add_value(struct uri_param *param, const char *value)
 {
-	size_t size = (param->value_count + 1) * sizeof(char *);
-	param->values = xrealloc(param->values, size);
-	param->values[param->value_count++] = xstrdup(value);
+	if ((size_t)param->value_count + 1 <= param->capacity) {
+		param->values[param->value_count++] = xstrdup(value);
+	} else {
+		size_t new_capacity = param->capacity == 0 ? 16 :
+			param->capacity * 2;
+		size_t new_size = new_capacity * sizeof(char *);
+		param->values = xrealloc(param->values, new_size);
+		param->values[param->value_count++] = xstrdup(value);
+		param->capacity = new_capacity;
+	}
+	assert((size_t)param->value_count <= param->capacity);
 }
 
 /**
@@ -65,6 +78,7 @@ uri_param_create(struct uri_param *param, const char *name)
 	param->name = xstrdup(name);
 	param->values = NULL;
 	param->value_count = 0;
+	param->capacity = 0;
 }
 
 /**
@@ -75,10 +89,11 @@ uri_param_copy(struct uri_param *dst, const struct uri_param *src)
 {
 	dst->name = xstrdup(src->name);
 	dst->value_count = src->value_count;
-	dst->values = (src->value_count == 0 ? NULL :
-		       xmalloc(src->value_count * sizeof(*dst->values)));
+	dst->values = (src->capacity == 0 ? NULL :
+		       xmalloc(src->capacity * sizeof(*dst->values)));
 	for (int i = 0; i < src->value_count; i++)
 		dst->values[i] = xstrdup(src->values[i]);
+	dst->capacity = src->capacity;
 }
 
 void
diff --git a/src/lua/uri.lua b/src/lua/uri.lua
index a26306428..f6e195bfe 100644
--- a/src/lua/uri.lua
+++ b/src/lua/uri.lua
@@ -9,6 +9,7 @@ struct uri_param {
     const char *name;
     int value_count;
     const char **values;
+    size_t capacity;
 };
 
 /**
```

This patch decreases the Lua test execution from 25-31 seconds to 50ms.

There are still a lot of allocations (all those `strdup()`), but, it seems, `realloc()` is the most problematic for ASAN. It deserves refactoring, but it is okay to ignore it within this issue if fuzzers will not reach timeouts.
