### ISSUE TITLE
Get rid of fiber_set_cancellable usage in Tarantool

### ISSUE THREAD

**Issue by Gumix** [tarantool/tarantool#7166]
Currently `fiber_set_cancellable()` is used inside Tarantool as a guard against spurious wakeups.

First of all, the name is misleading — _(non)cancellable_ fiber actually means _(non)wake-able_ fiber.
Secondly, this protection does work only for Lua API's `fiber:wakeup()`, while it's possible to wakeup any fiber using C API's `fiber_wakeup()` or from within the Tarantool.

#6506 is an example of a crash caused by a spurious wakeup, however there are about 20 other similar dangerous places. Some of them can be easily fixed by yielding until a completion flag is set, while others should be carefully redesigned, because they rely strictly on the order in which fibers are woken up, which is quite fragile.

**Comment by unera** [comment]
Hi!

Prodact team resoulution:

Of cource it would be nice to drop the function, but some user's code can be broken, so we think that we should replace the function to No-Operation function, and drop their description from documentation.
