### ISSUE TITLE
Crash Tarantool on stop

### ISSUE THREAD

**Issue by ESologub** [tarantool/tarantool#7174]
При проведении работ по проверке отказоустойчивости базы данных был остановлен один экземпляр. После остановки он упал и сформировал core файл.

* OS: Linux
* OS Version: RedHat 7
* Architecture: amd64

Tarantool 2.8.2-67-g05d77d8
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_BACKTRACE=ON
Compiler: /opt/rh/devtoolset-8/root/usr/bin/cc /opt/rh/devtoolset-8/root/usr/bin/c++
C_FLAGS:-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-funons -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type -Werror  

[dra_routing_db.log](https://github.com/tarantool/tarantool/files/8753630/dra_routing_db.log)
[dra_routing_db.20220418000001.log](https://github.com/tarantool/tarantool/files/8753629/dra_routing_db.20220418000001.log)
есть еще ./core файл, но сюда не загружается

не воспроизводится

**Comment by kyukhin** [comment]
Пожалуйста, выложите артефакт полученный с помощью нашего [инструмента](https://github.com/tarantool/tarantool/blob/master/tools/tarabrt.sh), на любом удобном ресурсе.

**Comment by Korablev77** [comment]
А каким образом стопали инстанс? Есть значения `box.cfg{}` на котором работал инстанс?

**Comment by alyapunov** [comment]
Корка есть, но не в паблике. Надо спрашивать лично.

**Comment by ESologub** [comment]
> Без корки скорее всего сложно будет что-то сказать..

Корку выложил Андрею Жилину из Тарантул.

> выложите артефакт

Пробуем

**Comment by Korablev77** [comment]
Reproduced:
```
box.cfg{log = "log.txt"}
box.error.injection.set("ERRINJ_LOG_ROTATE", true)
box.error.injection.info().ERRINJ_LOG_ROTATE
require('log').rotate()
os.exit()
```

**Comment by Korablev77** [comment]
Closed as a duplicate (#4450).
