### ISSUE TITLE
Crash Tarantool at work

### ISSUE THREAD

**Issue by ESologub** [tarantool/tarantool#7175]
В процессе нагрузочного тестирования упал экземпляр Tarantool

В процессе работы было 2 падения, причины непонятны

* OS: Linux
* OS Version: RedHat 7
* Architecture: x64

Tarantool 2.1.3-9-g85ad850
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_BACKTRACE=ON
Compiler: /opt/rh/devtoolset-8/root/usr/bin/cc /opt/rh/devtoolset-8/root/usr/bin/c++
C_FLAGS:-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -fno-gnu89-inline -Wno-cast-function-type 
CXX_FLAGS:-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -fexceptions -funwind-tables -fno-omit-frame-pointer -fno-stack-protector -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Wno-cast-function-type 

не дублируется

в логе присутствует 2 ошибки: 
Segmentation fault
  code: SEGV_MAPERR

[dra_routing_db1.log](https://github.com/tarantool/tarantool/files/8754026/dra_routing_db1.log)
[dra_routing_db2.log](https://github.com/tarantool/tarantool/files/8754027/dra_routing_db2.log)

**Comment by igormunkin** [comment]
Duplicate of #843.
