### ISSUE TITLE
net.box: connection:_request() hangs indefinitely

### ISSUE THREAD

**Issue by sergepetrenko** [tarantool/tarantool#7177]
I've prepared some testing code:

<details><summary>test.lua</summary>

```lua
local msgpack = require('msgpack')

-- Iproto keys to encode custom call request.
local IPROTO_REQUEST_TYPE = 0x00
local IPROTO_SYNC = 0x01
local IPROTO_TUPLE = 0x21
local IPROTO_FUNCTION_NAME = 0x22

local IPROTO_CALL = 0x0a

local next_request_id = 135 -- next_request_id = 0 reproduces the bug as well.

function encode_call(raw_val)
    next_request_id = next_request_id + 1
    local header = msgpack.encode({
        [IPROTO_REQUEST_TYPE] = IPROTO_CALL,
        [IPROTO_SYNC] = next_request_id,
    })
    local body = msgpack.encode({
        [IPROTO_FUNCTION_NAME] = 'test',
        -- Reserve a slot for raw_val.
        [IPROTO_TUPLE] = {box.NULL},
    })
    -- Replace the nil placeholder with val.
    body = string.sub(body, 1, -2)..raw_val
    local size = msgpack.encode(#header + #body)
    return size..header..body
end
```
</details>

The file exports a `encode_call()` function, which accepts one msgpack-encoded parameter, and encodes an iproto call request to function `test` with this parameter.

Now I run the following:
`tarantool -i test.lua`
And in tarantool console:
```lua
msgpack = require('msgpack')
decimal = require("decimal")
net_box = require('net.box')

function test(val) require('log').info("The function is invoked") return true end

box.cfg{listen=3301}
box.schema.user.grant('guest', 'super')
net_box = require('net.box')
c = net_box:connect(3301)
c:_request(net_box._method.inject, {timeout = 1}, nil, nil, encode_call(msgpack.encode(decimal.new(1))))
```
The last request hangs for a second and then returns a timeout.
Tarantool log has:
```
2022-05-23 15:08:53.810 [52320] main/121/main I> The function is invoked
```

**Comment by locker** [comment]
`c:_request()` uses an internally-generated sync number, which is different from the one you pass:

https://github.com/tarantool/tarantool/blob/934da6ad0a0cb20e27623f65287a36c0d09bced5/src/box/lua/net_box.c#L2114-L2118

If you change `next_request_id` to 4 in your example, everything works fine.

I think the best way to make the inject method usable in this case is to export connection's `next_sync` for internal usage. Then you could set `sync` in your example to `c:_next_sync()` and the request future would wait on this sync number.
