### ISSUE TITLE
Transaction isolation level management 

### ISSUE THREAD

**Issue by antonbashir** [tarantool/tarantool#7202]
**Is your feature request related to a problem? Please describe.**

After upgrading Tarantool from 2.8 to 2.10 I've been receiving errors: "ER_TRANSACTION_CONFLICT: Transaction has been aborted by conflict". The source of errors described in the end of the issue.

**Describe the solution you'd like**

What I propose is an addition of three methods to box API to implement possibility of configuring `txn_isolation` property for `box.begin()`.

**Definition of Done**
Box API has methods for atomic execution with configured transaction level. 

**Additional information**

I want to highlight the problem. Look at the source code below.
In the code I wrote example of methods for using different isolation levels. 
`configured_atomic` for customization of `atomic` options and `immutable/mutable` for predefined levels. 
But when I've set `READ_COMMITTED` level I'm still receiving the error. I checked two cases:

1) Concurrent update for non-indexed field
2) Concurrent update for indexed field

In the first case READ_COMMITTED works as expected - no error. 
But the second case will give `ER_TRANSACTION_CONFLICT: Transaction has been aborted by conflict`. 

```
local fiber = require("fiber")
local log = require("log")

local function atomic_tail(status, ...)
    if not status then
        box.rollback()
        error((...), 2)
    end
    box.commit()
    return ...
end

local configured_atomic = function(default_options)
    local atomic_builder = {}

    if default_options == nil then
        default_options = {}
    end

    atomic_builder.begin_options = default_options

    atomic_builder.read_committed = function(self)
        self.begin_options.txn_isolation = "READ_COMMITTED"
        return self
    end

    atomic_builder.read_confirmed = function(self)
        self.begin_options.txn_isolation = "READ_CONFIRMED"
        return self
    end

    atomic_builder.options = function(self, options)
        self.begin_options = options
        return self
    end

    atomic_builder.run = function(self, fun, ...)
        box.begin(self.begin_options)
        return atomic_tail(pcall(fun, ...))
    end

    return atomic_builder
end

local immutable = function(fun, ...)
    box.begin({ txn_isolation = "READ_CONFIRMED" })
    return atomic_tail(pcall(fun, ...))
end

local mutable = function(fun, ...)
    box.begin({ txn_isolation = "READ_COMMITTED" })
    return atomic_tail(pcall(fun, ...))
end

box.cfg {
    listen = 3301,
    replication_synchro_quorum = 1,
    replication_synchro_timeout = 10,
    replication = { "repository:repository@localhost:3301" },
    election_mode = "candidate",
    read_only = false,
    memtx_use_mvcc_engine = true,
}
box.ctl.promote()

local test = box.schema.create_space("test", {
    if_not_exists = true,
    format = { { "id", type = "number" }, { "indexed", type = "string" }}
})

test:create_index("id", { unique = true, if_not_exists = true, parts = { { 1, "number" } } })
test:create_index("indexed", { unique = false, if_not_exists = true, parts = { { 2, "string" } } })

local id = 0
local nextId = function()
    id = id + 1;
    return id;
end

log.info("READ_COMMITTED:")

local put = function()
    configured_atomic():read_committed():run(function()
        test:put({ nextId(), "queue", "READY", "test" })
    end)
end

local firstUpdate = function()
    return configured_atomic():read_committed():run(function()
        for _, task in test.index.indexed:pairs() do
            test:update(task.id, { { '=', "indexed", "test + test" } })
        end
    end)
end

local secondUpdate = function()
    return configured_atomic():read_committed():run(function()
        for _, task in test.index.indexed:pairs() do
            test:update(task.id, { { '=', "indexed", "test - test" } })
        end
    end)
end

for _ = 1, 10 do
    fiber.create(put)
end

fiber.create(firstUpdate)
fiber.create(secondUpdate)

log.info("Done")

require('console').start()
```

**Comment by R-omk** [comment]
> But we don't have any way to pass box.begin arguments.

I would also note that `atomic` has not been atomic (non yielding)  for a long time since vinyl and mvcc.
Maybe `box.transaction`

Perhaps it is worth introducing a completely new thing, and at the same time fixing all the existing shortcomings.

https://github.com/tarantool/tarantool/issues/4191
https://github.com/tarantool/tarantool/issues/6454

**Comment by alyapunov** [comment]
In offline discussion we decided that it would be nice to make the following: if the first argument of box.atomic is a non-callable table then consider it to be options table, expecting the rest arguments to be the function and its arguments.
