### ISSUE TITLE
Invalid key part count error is not descriptive enough

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#7223]
```yaml
- error: Invalid key part count in an exact match (expected 1, got 0)
```

It is hard to spot what exactly raises the error. There are different ways to make it better:

* Give more details: space name, index name.
* Include a code line number into the message itself.
* Change something about error reporting to not miss details.

Inspired by @Mons. He said that he met it as result of a maintenance script run and was angry.

**Comment by Mons** [comment]
Let's add for now space and index names as a simple solution to not dive into errors refactoring

**Comment by alyapunov** [comment]
Blocked by new error subsystem refactoring.
