### ISSUE TITLE
Display state of connected replicas on a master

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#723]
@rtsisyk's proposal:

```
box.info.replication:
    <instance_id>:
      uuid: 643542af-e73d-4cd8-853b-b50ab0811571 -- the unique identifier of the remote master.
      lag: <seconds> -- max(upstream.lag, downstream.lag)
      idle: <seconds> -- min(upstream.idle, downstream.idle)
      upstream:
         lag: <seconds> -- number of we are behind the remote master.
         idle: <seconds> -- number of seconds after the last incoming message from the remote master.
         status: connect|connecting|auth|disconnected|error
         error: <struct error> -- the last error happened on our instance during applying rows from the remote instance, displayed only when status is "error".
      downstream:
         vclock: {1: 1} -- approximated vclock of the remote master.
         # lag: <seconds> -- number of second the remote master is behind us.
         # idle: <seconds> -- number of second after the last outgoing message to remote master.
         # error: <struct error>  -- the last error happened on the remote master during applying our rows.
```

**Comment by rtsisyk** [comment]
Please merge multi-master first, I can't make review fixes

**Comment by kostja** [comment]
Now, this patch, unfortunately, needs to be re-done. The feature request wasn't specified  well enough.
We need to look around and see what others do too, before coming back to this.

First of all, the user needs to see a single entry for a single node. I.e. if we have both a relay and a remote in a master-master setting, we need to display only 1 entry in replication status table.

Second, in case of multi-source, we need to find a way to index the output A quick index is needed so that we can display state of 1 replica only, without building an entire table. Apparently we need to index it with server ids (short ones). Perhaps we need to enforce human-readable names on nodes, and index the table using these names.

Finally, we need to find a way to merge information from outgoing vclock (remote->vlcock) and incoming vclock (relay->vclock), as well as from outgoing lag and incoming lag into few comprehensible metrics. 
How much is the remote behind and how much are we behind? We have the following data:
- the time when we sent the last row to remote (idle1)
- the time when we received last row from remote (idle2)
- the timestamp of the last row received
- the timestamp of the last row sent.

Can we assume that link speed is uniform, and merge two idle times and two lag times and display the min (idle1, idle2) as idle, and min(lag1, lag2) as lag? I think we need to find a way to do it, since that's what the user is interested in. Making sense of two idle and two lag times is difficult even to us, not to mention users. 

Finally, we need to find a way to merge vclocks. We actually have 3 vclocks to sync: recovery->vclock, remote->vclock, relay->vclock. In a totally synchronous system, all vclocks are identical. So, if they are not, the difference tells us about events which have not reached the other side yet. So, perhaps we need to print a single vclock in the following form:

{ 1: 32 (+3), 2: 33 (-3) }, showing how much the master is ahead or behind the replica.

Last thing, we need to replace socket address with uri from the configuration file. Addresses and ports are useful, but take a lot of display space, and are perhaps useful for debugging, but not at all handy if one just needs to monitor replciation and do health checks.

**Comment by kostja** [comment]
Galera uses node names in configuration:
http://galeracluster.com/documentation-webpages/dbconfiguration.html

Needs to be checked whether or not a node name is mandatory. Without names, the whole thing can become messy pretty easily.

**Comment by kostja** [comment]
Example where you need to check separately master and slave status:
https://code.google.com/p/tungsten-replicator/wiki/Cheat_Sheet
I think it's a bad idea - all the user cares about is divergence of master and slave, we should not be forcing him/her to merge master and slave status to find it out.

**Comment by rtsisyk** [comment]
We need a specification for new version box.info.replication.

**Comment by rtsisyk** [comment]
This feature break compatibility with 1.6.6 and it also depends on patches pushed to 1.7.0. 
Re-scheduled to 1.7.x.

**Comment by rtsisyk** [comment]
Please note that ACKs from replica is not part of this ticket!

**Comment by rtsisyk** [comment]
The first part was merged.  Relays are still not tracked.

**Comment by rtsisyk** [comment]
This ticket is probably a breaking change (it MAY change box.info.replication() format).

**Comment by rtsisyk** [comment]
```
tarantool> { status = "bidirectional" }
—-
- status: bidirectional
...

tarantool> { status = "follow" }
—-
- status: follow
...

tarantool> { status = "relay" }
—-
- status: relay
...
```

**Comment by rtsisyk** [comment]
```
box.info.replication:
    <instance_id>:
      uuid: 643542af-e73d-4cd8-853b-b50ab0811571 -- the unique identifier of the remote master.
      vclock: {1: 1} -- approximated vclock of the remote master.
      status: follow | bidirectional | relay
      upstream:
         lag: <seconds> -- number of we are behind the remote master.
         idle: <seconds> -- number of seconds after the last incoming message from the remote master.
         error: <struct error> -- the last error happened on our instance during applying rows from the remote instance.
      downstream:
         lag: <seconds> -- number of second the remote master is behind us.
         idle: <seconds> -- number of second after the last outgoing message to remote master.
         error: <struct error>  -- the last error happened on the remote master during applying our rows.
```

**Comment by rtsisyk** [comment]
I also think that any error in applier or relay should abort both.

**Comment by rtsisyk** [comment]
It also would be nice to add **hidden**  upstream.socket / downstream.socket for  tests and debugging purpose:

```
box.info.replication[0].upstream.socket
---
- fd: 6
  name:
    host: 1.2.3.4
    family: AF_INET
    type: SOCK_STREAM
    protocol: tcp
    port: 50806
  peer:
    host: 81.200.3.182
    family: AF_INET
    type: SOCK_STREAM
    protocol: tcp
    port: 80  
```

Output is the same as  in `socket` module.

**Comment by rtsisyk** [comment]
Please note that I kept box.info.cluster.uuid and box.space._cluster names without changes, because there is no well-defined  long-term vision how all these cluster stuff will look like in 1.8.x+.
