### ISSUE TITLE
Add HMAC to crypto module

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#725]

**Comment by rtsisyk** [comment]
Code for hmac and aes is already exists in Mail.Ru Private repo.
We can open-source it. Please ask me for details.

**Comment by bigbes** [comment]
https://github.com/wahern/luaossl/blob/master/src/openssl.c#L6291 - for HMAC in OpenSSL
http://dev.kryo.se/iodine/browser/src/base32.c - for BASE32
