### ISSUE TITLE
Allow box.info before box.cfg

### ISSUE THREAD

**Issue by Mons** [tarantool/tarantool#7255]
There is a local variable, that is not exposed:
https://github.com/tarantool/tarantool/blob/a353ec918756c889e2c98f62617050a574a0168e/src/box/lua/load_cfg.lua#L739

Currently, the only way to check is to do
```
type(box.cfg) == 'function'
```

Proposed change:
```
tarantool> box.info
---
- error: "builtin/box/load_cfg.lua:726: Please call box.cfg{} first\nstack traceback:\n\tbuiltin/box/load_cfg.lua:726:
    in function '__index'\n\t[string \"return box.info\"]:1: in main chunk\n\t[C]:
    in function 'pcall'\n\tbuiltin/box/console.lua:404: in function 'eval'\n\tbuiltin/box/console.lua:710:
    in function 'repl'\n\tbuiltin/box/console.lua:759: in function <builtin/box/console.lua:747>"
...

tarantool> box.is_configured
---
- false
...

tarantool> box.cfg{}
...skip...
---
...

tarantool> box.is_configured
---
- true
...
```

**Comment by Mons** [comment]
It is required to avoid hardly-interruptible exceptions of indexing box.
I.e.: box_is_configured should have the meaning: I can freely access box[anything] and will not blow up on `Please call box.cfg{} first`
https://github.com/tarantool/tarantool/blob/master/src/box/lua/load_cfg.lua#L724-L729

**Comment by R-omk** [comment]
> https://github.com/tarantool/tarantool/pull/7407#issuecomment-1186223868

As a further development, one could add a trigger called in different phases of the bootstrap process.

related https://github.com/tarantool/tarantool/issues/3159
