### ISSUE TITLE
RTREE index safety if out of memory

### ISSUE THREAD

**Issue by alyapunov** [tarantool/tarantool#727]
Now if memory allocation fails, rtree index panic.
We should handle OOM more carefully. Ideally any memory fails must be logged and system must rolback to previous correct state (that it'll be hard to implement due to rtree specific features).
I've added a disabled test for this case (test/box/rtree_errinj.test.lua, CR pending now)

**Comment by kostja** [comment]
See gh-625

**Comment by kostja** [comment]
How to fix: 
- put aside a set of blocks which are sufficient to cover insert-on-delete needs
- if out of main index memory, switch to using the reserve, and disable the tree until the reserve is refilled
- to calculate the necessary amount of the set-aside buffer, use a probablistic model, assuming page splits of pages are independent events, and simulation with stress testing.
