### ISSUE TITLE
Wrong error returned via iproto when transaction was active

### ISSUE THREAD

**Issue by Mons** [tarantool/tarantool#7288]
If transaction was open and any error has occurred, then upon return from function error text would be completely lost and instead would be emitted `Transaction is active at return from function`.
Error is relevant either with memtx_use_mvcc_engine or without.

Steps to reproduce:

Run any simple tarantool
```
box.cfg{ listen = '127.0.0.1:3301', memtx_use_mvcc_engine = true }
box.schema.user.grant('guest', 'super', nil, nil, {if_not_exists = true})
```

Then, connect to it with any iproto client, for ex tarantoolctl, and execute transaction, that will fail inside
```
$ tarantoolctl connect 127.0.0.1:3301
connected to 127.0.0.1:3301
127.0.0.1:3301> box.begin() error("something") box.commit()
---
- error: Transaction is active at return from function
...
127.0.0.1:3301> box.begin() box.space[513]:select() box.commit()
---
- error: Transaction is active at return from function
...
```

Error `something` is completely missed. It is neither logged into server log nor returned to client.

### Expected behavior

* If an error has occurred, then exactly this error must be returned to the client
* `Transaction is active at return from function` should be logged into server's log, with possible additional information, like name of a function call, calling peer, etc.
```
2022-06-21 14:37:16.247 [82769] main/129/main C> Transaction is active at return from function 'user_function'
 stack traceback:
	simple.lua:120: in function 'user_function'
	[C]: in function 'pcall'
	builtin/box/console.lua:404: in function <builtin/box/console.lua:379>
	[C]: at 0x0102634b34
```
* And only if there were no errors, open transaction at the ond of the function should raise error by itself , return it to the client AND log a message.

**Comment by nshy** [comment]
In case of remote console `console.eval ` is called on server to evaluate result. This function uses `pcall` and thus catches evaluation error. Next RPC EVAL method is used to make the remote evaluation. If evaluation does not throw error the method additionally checks if transaction is active and raises `Transaction is active at return from function` if it is.

1. I guess we could just use a function different from `console.eval` but just for the case is this function public API and if it is should it catches errors?

2. Another question is what should be the state of transaction in case of errors. Now in case of local API transaction is aborted but active:

```
 tarantool> box.begin() box.space.my:replace{2, 'a'} error('test error') box.commit()
---
- error: '[string "box.begin() box.space.my:replace{2, ''a''} erro..."]:1: test error'
...

 tarantool> 2022-07-05 15:39:58.910 [172023] main/103/interactive txn.c:1545 W> Transaction has been aborted by a fiber yield

---
...

 tarantool> box.space.my:replace{2, 'b'}
---
- error: Transaction has been aborted by a fiber yield
...

 tarantool> box.begin()
---
- error: 'Operation is not permitted when there is an active transaction '
...

 tarantool>
```

and in case of remote console (or some other iproto EVAL) transaction is rolled back:
```
 localhost:3301> box.begin() box.space.my:replace{2, 'a'} error('test error') box.commit()
---
- error: Transaction is active at return from function
...

*localhost:3301> box.space.my:replace{2, 'b'}
---
- [2, 'b']
...

 localhost:3301>
```

**Comment by Mons** [comment]
1. I think we maybe should patch `console.eval` itself to check `box.is_in_txn()` upon return. At least in case it is run within an iproto fiber.

**Comment by locker** [comment]
This is a bug in console. Reverting f003b48926ac89e834d7a7cc934168d973810c20 is bad IMO - because this would mean that we silently allow buggy user code. I think we should roll back the active transaction in case of eval error. If eval code completes successfully, but leaves a transaction open, we should raise an error, as before.
