### ISSUE TITLE
datetime:set({min=0, sec=0, nsec=0}) inconsistency

### ISSUE THREAD

**Issue by no1seman** [tarantool/tarantool#7298]
**Bug description**

datetime:set inconsistent in some cases

* OS: [Linux]
* OS Version: [Ubuntu 20.04]
* Architecture: [amd64]

Place `tarantool --version` output here.
Tarantool 2.10.0-0-g0a5ce0b9c
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_BACKTRACE=ON
Compiler: /usr/bin/cc /usr/lib/ccache/g++
C_FLAGS:-g -O2 -fdebug-prefix-map=/build/tarantool-2.10.0=. -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fexceptions -funwind-tables -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type
CXX_FLAGS:-g -O2 -fdebug-prefix-map=/build/tarantool-2.10.0=. -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fexceptions -funwind-tables -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type
**Steps to reproduce**

```
tarantool> a=dt.parse('2022-05-05T00:00:00')
---
...

tarantool> a:set({min=0, sec=0, nsec=0})
---
- 2022-05-05T12:00:00Z
...

tarantool>
```

**Actual behavior**

```
- 2022-05-05T12:00:00Z
```

**Expected behavior**

Must be:

```
- 2022-05-05T00:00:00Z
```

**Comment by tsafin** [comment]
This is very silly :)

```diff
diff --git a/src/lua/datetime.lua b/src/lua/datetime.lua
index 04e0bc7df..d4deadac7 100644
--- a/src/lua/datetime.lua
+++ b/src/lua/datetime.lua
@@ -1023,7 +1023,7 @@ local function datetime_set(self, obj)
     end
 
     local lsecs = local_secs(self)
-    local h0 = math_floor(lsecs / (24 * 60)) % 24
+    local h0 = math_floor(lsecs / (60 * 60)) % 24
     local m0 = math_floor(lsecs / 60) % 60
     local sec0 = lsecs % 60
 
```
