### ISSUE TITLE
Snapshot daemon random interval

### ISSUE THREAD

**Issue by alyapunov** [tarantool/tarantool#732]
The problem: If many instances of tarantool are started on one server simultaneously with similar configuration (sharding for example) and shapshot daemons are enables in configurations, then all tarantools will start saving snapshots at the same time, stressing system resources.
 The idea is to solve the problem by adding some options to configuration that bring snapshot daemon to start snaphotting in come random manner thus avoiding simultaneous snapshotting with high probability.

**Comment by kostja** [comment]
Affects mail.ru games

**Comment by rtsisyk** [comment]
Reviewed by @kostja  and @alyapunov => review fixes

**Comment by rtsisyk** [comment]
I'm waiting for comments from @alyapunov and @kostja. They wanted to review this patch.

**Comment by viciious** [comment]
A better solution would be to use a global lock using flock or a similar call/pattern. Random offsets are useless in cases when making a snapshot takes a substantial amount of time (>~ snapshot_interval).

**Comment by kostja** [comment]
Viktor, bug database is not a discussion forum. If you have a feature requeste, please feel free to open it. But better yet, join our discussion channel and air your proposal there. As to the case when making a snapshot takes more than snapshot interval, just don't do it: choose your snapshot interval accordingly. 
Alternatively, snapshot daemon code is 200 lines of Lua code. If snapshotting takes so long in your case, better don't use snapshot daemon at all - fire up a separate fiber which does it the way you need.

**Comment by viciious** [comment]
@kostja I wasn't trying to start a discussion there or something, merely pointing. I wasn't aware that you (somewhat naively) view github merely as a bug database and not as a means for prominent Tarantool users to provide feedback on what's practical and what's not. Now that I'm aware of that, I will restrain myself from providing such comments here. Thanks.
