### ISSUE TITLE
console: multiline commands can't be repeated from readline history

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#7320]
Tarantool version: 2.11.0-entrypoint-164-ge797a7483

For example, start tarantool in the interactive mode and enter a multiline command line-by-line:

```lua
tarantool> function foo()
         >     return 42
         > end
```

Now exit from tarantool and start it again. Navigate over the history using the Up/Down arrows:

```lua
tarantool>               -- press Up
tarantool> end           -- press Up
tarantool>     return 42 -- press Up
tarantool> function foo()
```

I expect that if the command was executed as a single statement, it will be interpreted as the signle statement in the readline console.

**Comment by tsafin** [comment]
Worth to mention, that editing of such multi-line commands from readline history properly works during the same console session, it's serialization/deserialization of a command history to a file that breaks lines here.
