### ISSUE TITLE
Teach ASAN to detect leaks in custom Tarantool allocators

### ISSUE THREAD

**Issue by locker** [tarantool/tarantool#7327]
Beside the libc malloc, Tarantool implements and uses other allocators, e.g. runtime region and memory pools, memtx arena. Currently, ASAN ignores such allocations and doesn't report leaks. One way to fix this is simply use malloc instead of our internal allocators if ASAN is enabled. Maybe, ASAN allows to mark alloc/free functions so that it can enable leak detection for custom allocators?

**Comment by locker** [comment]
https://github.com/google/sanitizers/wiki/AddressSanitizerManualPoisoning

**Comment by CuriousGeorgiy** [comment]
@ligurio started working on this: rougly, the idea is to annotate the same places as for valgrind.
