### ISSUE TITLE
net.box: allow making async ping

### ISSUE THREAD

**Issue by Serpentian** [tarantool/tarantool#7362]
Currently conn:ping({is_async = true}) doesn't make async call and always return true instead of the future object. 

The ping on step 4 returns true without even going to the server:
```lua
--
-- Instance 1
--
-- Step 1
--
box.cfg{listen = 3313}

-- Step 3
--
while true do end

--
-- Instance 2
--
-- Step 2
--
net = require('net.box')
c = net.connect(3313)

-- Step 4
--
c:ping({is_async = true})
```

So, it would be nice to return future object from the ping method in case of `is_async` option or at least `false` if a connection related error occurred before the request had been done.

**Comment by Mons** [comment]
It's a breaking change and we have no plans to change the behavior
