### ISSUE TITLE
Add a method which is invoked once per replica set

### ISSUE THREAD

**Issue by anton-barabanov** [tarantool/tarantool#737]
For example, we need it for create a spaces and indexes in cluster with enabled sync replication.

**Comment by kostja** [comment]
Let me clarify. Right now, to avoid double definition of spaces, users, grants, as well as conflicts between master script and a replica script, developers have to add if_not_exists = true clause to all grants, create/drop space, etc. 
Plus, to avoid conflict between masters and replicas they still are better off skipping DDL part
altogether on replicas.

Thus, something which on a single-node master looks as straightforward as:
```
box.schema.space.create('myspace')
box.space.myspace:create_index('pk')
box.schema.user.grant('guest', 'read,write,execute', 'universe')
```
becomes something complicated when you make your startup script restart-aware and replication-aware.

What we could offer our users, is something like run-once hook, in which they can register
their functions. This hook would be guaranteed to execute only once in entire replica set,
and on the first start of the first master.

Something like:
```
box.run_once(create_spaces_and_users)
```

The implementation could use a special key in _schema space to check whether or not
the hook has already executed. 

We could even offer users some form of DDL versioning/schema upgrade with that approach, if we allow many hooks, each getting its own distinct/unique identifier:


So, to add new spaces, users could, in addition to an existing
```
box.run_once(create_spaces_and_users)
```
simply add
```
box.run_once(add_a_few_more_spaces_and_users)
```

and thus get an automatic "upgrade" of schema, which runs only once, guaranteed.
