### ISSUE TITLE
fiber_gc() can be called in prepared statement called from module_func_call()

### ISSUE THREAD

**Issue by darthunix** [tarantool/tarantool#7388]
The problem is inside the [module_func_call()](https://github.com/tarantool/tarantool/blob/15b823f0ee3eb142c36564fa3973993c1ceba5b9/src/box/module_cache.c#L210), where an arbitrary user-defined function is called:
```c
int
module_func_call(struct module_func *mf, struct port *args,
		 struct port *ret)
{
	struct region *region = &fiber()->gc;
	size_t region_svp = region_used(region);

        ....

	struct module *m = mf->module;
	module_ref(m);
	int rc = mf->func(&ctx, data, data + data_sz);
	module_unref(m);

	region_truncate(region, region_svp);

        ....

	return 0;
}
```
At the moment we expect that the `mf->func` never calls `fiber_gc()`. There is a special assertion in the [region_truncate()](https://github.com/tarantool/small/blob/3e5fb2ab3efbf23df211747d9b055910071cb9cd/small/region.c#L75) code for that:
```c
assert(region_used(region) >= used);
```
The problem happens when we create and destroy multiple prepared statements in the `mf->func` (in my case by calling the Lua code inside the Rust function with C ABI).

As you know, when we unprepare an SQL statement it is only [marked](https://github.com/tarantool/tarantool/blob/15b823f0ee3eb142c36564fa3973993c1ceba5b9/src/box/sql_stmt_cache.c#L163) for statement cache GC but not actually returned to the free list. The statements would be [freed](https://github.com/tarantool/tarantool/blob/15b823f0ee3eb142c36564fa3973993c1ceba5b9/src/box/sql_stmt_cache.c#L240) later, when a user inserts a new prepared statement that doesn't fit into Tarantool's statement cache.

The problem here is that `sql_stmt_cache_gc()` calls `fiber_gc()`.
```
sql_stmt_cache_insert
sql_stmt_cache_gc
sql_stmt_cache_delete
sql_cache_entry_delete
sql_stmt_finalize
sqlVdbeDelete
fiber_gc
```
After that we fail an assertion in `module_func_call() -> region_truncate()`.

So, could you clarify for me the reason to call `fiber_gc()` in `sqlVdbeDelete()` as it seems to be the root of the problem.

**Comment by locker** [comment]
Should be fixed in the scope of #5665 - we don't clean up the whole fiber region on transaction commit anymore.
