### ISSUE TITLE
Inconsistent methods in digest library

### ISSUE THREAD

**Issue by bigbes** [tarantool/tarantool#739]
1) There are `digest.crc32()` and `digest.crc32_update()`, but no `digest.sha1_UPDATE()` function.
2) There are `digest.sha1()` and `digest.sha1_hex()`, but no `digest.crc32_hex()`.

Proposal:
Make universal API for `digest` (not consistent) hashing methods:
```
digest.<hashing_method> = {
   __init = function(<object_to_hash>) end, -- init digest object
   update = function(<hash_object>, <object_to_hash>) end, -- update digest value with this sha1 object
   digest = function(<hash_object>) end, -- return value of diges
   digest_hex = function (<hash_object>) end -- return hex value of digest
}
```
And add `_update` and `_hex` methods, where they are lacking

Usage example:
```
a = digest.sha1('hello').update('world')
print(a.digest())
print(a.digest_hex())
print(digest.crc32('hello').digest())
```

**Comment by rtsisyk** [comment]
I propose to add a global function `hex` which will make hexadecimal string from any object (like Python).

**Comment by bigbes** [comment]
It's deprecated, since we have new module named `crypto`
