### ISSUE TITLE
Integration with Coverity is broken, last analyzed build `2.10.0-beta2-106-g17f08c821` (Feb 12, 2022)

### ISSUE THREAD

**Issue by ylobankov** [tarantool/tarantool#7440]
It looks like the integration with Coverity is broken. The last analyzed build was `2.10.0-beta2-106-g17f08c821` (Feb 12, 2022).
<img width="910" alt="Screenshot 2022-07-19 at 17 33 49" src="https://user-images.githubusercontent.com/3645987/179776697-0a537622-2def-4fcb-a197-71595b81156d.png">

**Comment by kyukhin** [comment]
Fixed and explained here https://github.com/tarantool/infra/issues/155#issuecomment-1265376850
