### ISSUE TITLE
log.cfg panic on incorrect syslog config

### ISSUE THREAD

**Issue by nshy** [tarantool/tarantool#7447]
```
Tarantool 2.11.0-entrypoint-210-g111663821
type 'help' for interactive help
 tarantool> log = require('log')
---
...

 tarantool> log.cfg{log='syslog:xxx'}
IllegalParams: bad option 'xxx'
failed to initialize logging subsystem
```
At the same time:
```
Tarantool 2.11.0-entrypoint-210-g111663821
type 'help' for interactive help
 tarantool> box.cfg{log='syslog:xxx'}
---
- error: 'Incorrect value for option ''log'': bad option ''xxx'''
...

 tarantool>
```
I guess we don't need to panic in the the first case as well.

**Comment by olegrok** [comment]
Looks similar to https://github.com/tarantool/tarantool/issues/5130

**Comment by nshy** [comment]
Duplicates #5130

**Comment by nshy** [comment]
Closed as duplicate.

**Comment by locker** [comment]
The PR that fixes this issue does quite a lot of refactoring of the configuration subsystem, which makes it difficult to backport it to 2.10. Since the issue is minor (exit on invalid config instead of raising an error) and it was reported by a developer, let's commit it to 2.11 only.
