### ISSUE TITLE
`net.box` worker fiber death leaves `"error_reconnect"` state but does not reconnect

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#7448]
```Lua
net = require('net.box')
box.cfg{listen = 3313}
box.schema.user.grant('guest', 'super')
c = net.connect(box.cfg.listen, {reconnect_after = 1})
c:ping()
c._fiber:cancel()
```
```
tarantool> c.state
---
- error_reconnect
...
```
Reconnect doesn't happen anymore. A fix, for example, could be either make the state `error` (without `_reconnect` suffix), or make the canceled worker fiber spawn a new one before it dies if reconnect is enabled. I know the test touches internals to get to the fiber, but in reality it happens when a user simply kills everything he sees in `fiber.info()` without even touching individual netbox objects. Or he could get the fiber id in one of netbox triggers and then cancel just it precisely by the id.

Found in https://github.com/tarantool/vshard/issues/341.

**Comment by Serpentian** [comment]
Actually, in previous versions  (e.g. in tarantool 2.6)  the state of connection after explicit fiber kill is `error`:

<details>
<summary> Tarantool 2.6</summary>

```
tarantool> _TARANTOOL
---
- 2.6.0-0-g47aa4e01e
...
tarantool> c
---
- peer_uuid: 98d4e7e7-2602-4ce3-857d-82fcda96eb40
  host: 127.0.0.1
  schema_version: 78
  protocol: Binary
  state: error
  error: fiber is cancelled
  peer_version_id: 132608
  port: '3301'
...
tarantool> c.error:unpack()
---
- base_type: FiberIsCancelled
  type: FiberIsCancelled
  message: fiber is cancelled
  trace:
  - file: ./src/lua/fiber.c
    line: 46
...
```
</details>
