### ISSUE TITLE
Prohibit killing system fibers from the Lua public API

### ISSUE THREAD

**Issue by Serpentian** [tarantool/tarantool#7473]
Some fibers can be considered as system ones (e.g. connection's worker fiber). Consequently, these fibers are not supposed to be explicitly cancelled from the Lua world. If some flag (e.g. `FIBER_IS_SYSTEM`) is set, the fiber should ignore `fiber_obj:cancel()`.

Suggested by @locker

**Comment by locker** [comment]
Tarantool Cartrdige maintains a [list](https://github.com/tarantool/cartridge/blob/d8d48a17e9bf4505941f7f5785fd4b6a9d809918/cartridge/hotreload.lua#L156-L170) of system fibers that shouldn't be cancelled during hot reload. If we marked these fibers as system, we could remove it.

**Comment by Totktonada** [comment]
Whether 'should not be cancelled' is actually a property of a fiber, not a task it serves? Will not it more logical to 'mask interruptions':

```lua
fiber.self():cancellable(false)
-- <..workload..>
fiber.self():cancellable(true)
```

```lua
fiber.self().uncancellable(function()
    -- <..workload..>
end)
```

(The second variant is more safe considering that a Lua error may be thrown. We can offer both APIs.)

We can either ignore the cancellation event or postpone its delivery until the flag will be dropped. The second variant feels more intuitive for me.

A fiber that always serves a task that should not be cancelled (a system fiber in your terms) can just set the flag at start and never drop it.

(It would be also good to see this property in `fiber.info()`.)

**Comment by Serpentian** [comment]
> Will not it more logical to 'mask interruptions'

Do you propose to export to public the ability to set the fiber 'cancellable'? If so, what can prevent the user from setting this flag to `false` and killing it? 

AFAICS, we want to make all system fibers invincible from the user side.

**Comment by Totktonada** [comment]
I don't see how cancellability (conceptually) depends of origin of the code: is it tarantool's code or external one. I'm afraid that if we'll make it just tarantool's property, we'll hide some design flaws (from ourself).

**Comment by locker** [comment]
Cancelling a system fiber may result in an undefined behavior (e.g. crash) - that's why we must prohibit it. Cancelling a user fiber is fine from Tarantool's point of view - it can only break the user application. I don't think we should make this API public.

**Comment by unera** [comment]
> Some fibers can be considered as system ones (e.g. connection's worker fiber). Consequently, these fibers are not supposed to be explicitly cancelled from the Lua world

Why?

For example, Linux:

```txt
    PID TTY      STAT   TIME COMMAND
      1 ?        Ss     0:54 /sbin/init
      2 ?        S      0:03 [kthreadd]
      3 ?        I<     0:00 [rcu_gp]
      4 ?        I<     0:00 [rcu_par_gp]
      9 ?        I<     0:00 [mm_percpu_wq]
     10 ?        S      0:00 [rcu_tasks_rude_]
     11 ?        S      0:00 [rcu_tasks_trace]
     12 ?        S      5:14 [ksoftirqd/0]
     13 ?        I     18:28 [rcu_sched]
```

You can see lots of system processes, but I can kill any of them.

If a user knows what he does, let the user do that!

**Comment by locker** [comment]
> > Some fibers can be considered as system ones (e.g. connection's worker fiber). Consequently, these fibers are not supposed to be explicitly cancelled from the Lua world
> 
> Why?
> 
> For example, Linux:
> 
> ```
>     PID TTY      STAT   TIME COMMAND
>       1 ?        Ss     0:54 /sbin/init
>       2 ?        S      0:03 [kthreadd]
>       3 ?        I<     0:00 [rcu_gp]
>       4 ?        I<     0:00 [rcu_par_gp]
>       9 ?        I<     0:00 [mm_percpu_wq]
>      10 ?        S      0:00 [rcu_tasks_rude_]
>      11 ?        S      0:00 [rcu_tasks_trace]
>      12 ?        S      5:14 [ksoftirqd/0]
>      13 ?        I     18:28 [rcu_sched]
> ```
> 
> You can see lots of system processes, but I can kill any of them.

You can't:

```
vlad@esperanza:~$ pgrep kswapd
128
vlad@esperanza:~$ sudo kill -9 128
vlad@esperanza:~$ pgrep kswapd
128
vlad@esperanza:~$ sudo kill -9 1
vlad@esperanza:~$ sudo kill -9 1
```

> If a user knows what he does, let the user do that!

The user may cancel a system fiber by mistake (like cartridge reload code does). Tarantool will probably crash with a core dump in this case. The user may think it's a bug and file a ticket. We don't want that.
