### ISSUE TITLE
snapshot daemon: keep track of replica state and take it into account for WAL maintenance

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#748]
Keep track of the state of replciation slaves and don't remove logs which are not yet fetched by a registered slave.
On the same token, maintain a view into all existing slaves and their connection status.

**Comment by rtsisyk** [comment]
Depends on replication-status #723

**Comment by rtsisyk** [comment]
I faced with this problem on a customer installation.

**Comment by rtsisyk** [comment]
Fixed by 1.7.4-79-ga0564b890
