### ISSUE TITLE
Unable to insert number without fractional part to "double" field type

### ISSUE THREAD

**Issue by VifleY** [tarantool/tarantool#7483]
**Bug description**

I reproduced on Tarantool 2.10.0
* OS: Linux
* OS Version: Ubuntu 20.04
* Architecture: amd64

Place `tarantool --version` output here.
Tarantool 2.10.0-1-g370040ca1
Target: Linux-x86_64-RelWithDebInfo
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_BACKTRACE=ON
Compiler: /usr/bin/cc /usr/bin/c++
C_FLAGS: -fexceptions -funwind-tables -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type
CXX_FLAGS: -fexceptions -funwind-tables -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type

Reproducer script:

```
#!/usr/bin/env tarantool

box.cfg{}
s = box.schema.space.create('tester')
s:format({{'a',type='double'}})
s:create_index('primary', {unique = true, parts = {{field = 1, type = 'double'}}})
s:insert{1.0}
```

How to run:

Just type `tarantool test.lua`.

**Actual behavior**
```
---
- error: 'Tuple field 1 (a) type does not match one required by operation: expected
    double, got unsigned'
...
```

That seems to me that `1.0` is a valid double value, so I should be able to insert it

As far as I know that happens, because when new tuple is serialized to msgpack, `1.0` is casted as `MP_UNSIGNED` due to the absence of fractional part

Moreover, I would be able to do `s:insert{ffi.new('double', 1)}` and I find that such type casting confusing

**Comment by VifleY** [comment]
I was able to find, that such behavior is actually slightly mentioned in docs, see [Data model](https://www.tarantool.io/en/doc/latest/book/box/data_model/#field-type-details), so that is probably a desired behavior
But that is still very complex and not obvious to user and even unconsistent (as I can actually do `space:insert(1.5)` without explicit cast)

**Comment by Totktonada** [comment]
It is known flaw of marshalling between msgpack and Lua. There is an idea to take the space format into consideration on the marshalling: #5933. I hope sooner or later it'll be fixed this way.

**Comment by alyapunov** [comment]
We need to ensure that we compare correctly big integer numbers with close doubles.
