### ISSUE TITLE
Deprecate `IPROTO_RAFT_ROLLBACK` and `replication_synchro_timeout`

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#7486]
Can't really remember why they were even added. But I do remember that we knew that these are against canonical Raft - it doesn't have any concept of *"commit timeout"*. The only timeouts in it are heartbeats and election timeout.

Synchro txn rollback by timeout has already brought a lot of bugs and problems in the implementation without notable gain. If this was a way to limit transaction queue, then probably should better add a setting like `txn_queue_max_size` or similar. How it works now is that if the leader is unable to get quorum, it would just start committing all txns, wait a bit, and rollback them. The database doesn't progress but clogs WAL and increases chances of split-brain.

The suggestion is to deprecate the very concept of `IPROTO_RAFT_ROLLBACK`. The setting `replication_synchro_timeout` can be turned into `election_timeout`. Synchro transactions should wait for quorum and write `IPROTO_RAFT_CONFIRM` or wait for `PROMOTE`/`DEMOTE` infinitely.

Note, that `PROMOTE` and `DEMOTE` still should include the rollback functionality. An analogue of this thing is present in real Raft and should remain in tnt.

**Comment by sergos** [comment]
The reason was to implement the qsync replication w/o Raft in it. Hence, leader election doesn't interfere with the data consistency - you may reject request on the same leader until the connectivity in replicaset is restored.
If we agree on the fact that this use is no longer supported, then we can proceed with this ticket. Assigning to product team to make a decision.

**Comment by Gerold103** [comment]
Non-automatic leader election still will work - we emit `PROMOTE`/`DEMOTE` regardless of whether election is enabled.

**Comment by sergepetrenko** [comment]
When implementing this we need to make sure that txn_timeout keeps working. Returns an error to the user, but doesn't roll the transaction back.

**Comment by sergepetrenko** [comment]
This changes behavior, so should go only to 3.1
