### ISSUE TITLE
API to push out-of-band messages into an iproto or console connection

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#750]
We need a Lua API to push data into an iproto connection. This is an out-of-band message for publish-subscribe scenarios. With such API and on_replace triggers it's possible to implement asynchronous subscription to data changes without long-polling.

**Comment by AlexMikhalev** [comment]
What is the current status? I would like to use this feature.

**Comment by kostja** [comment]
This feature is on wishlist milestone. This milestone has no release date. Please like this feature to bump its priority.

**Comment by kostja** [comment]
Duplicate of gh-2677
