### ISSUE TITLE
websockets 

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#751]
We need websocket support. There are two ways to do it: 
1) implement websockets purely in http/lua
2) implemet a FFI C API iproto_push_socket(int fd), which would allow an upgrade of HTTP socket into 
iproto socket with websocket headers.

The first approach is more flexible, the second is less resource-intensive.

**Comment by zloidemon** [comment]
Need to link with https://github.com/tarantool/http/issues/8

**Comment by zloidemon** [comment]
I think tarantool/http module have to support extensions/modules to expand functionality, and then write a module which will support websocket.

**Comment by zloidemon** [comment]
We also can porting that code on tarantool https://github.com/openresty/lua-resty-websocket

**Comment by rtsisyk** [comment]
I can implement it.

**Comment by kostja** [comment]
Duplicate of gh-1028
