### ISSUE TITLE
Add extra security compiler options

### ISSUE THREAD

**Issue by kyukhin** [tarantool/tarantool#7536]
We need to add -fstack-protect (-all?) and -fpie at least.
We need it for static build at least and I guess everywhere.

Need to make sure that perf isn't degraded much.

**Comment by Totktonada** [comment]
See also #7535 (we should prevent possible degradation) and #5372 (it tracks PIE enabling, partially fixes in 5e003c5a64094273dd2a9769792b48f08b0a4ccd, and also has some historical context).

**Comment by Gumix** [comment]
There are no observable performance impact from these features. `-fpie` is already enabled by default in GCC in most Linux distros. See below the performance results for different [`-fstack-protector`](https://gcc.gnu.org/onlinedocs/gcc/Instrumentation-Options.html) options.

#### [cbench](https://github.com/tarantool/cbench/) (requests per sec)
| Benchmark  | `-fno-stack-protector` | `-fstack-protector` | `-fstack-protector-strong` | `-fstack-protector-all` |
-- | -- | -- | -- | --
HASH num | 2114384 | 2143144 (1.4 %) | 2020869 (-4.4 %) | 1792831 (-15.2 %)
HASH str | 1867440 | 1858302 (-0.5 %) | 1850158 (-0.9 %) | 1847146 (-1.1 %)
TREE num | 910488 | 947655 (4.1 %) | 1000870 (9.9 %) | 937958 (3.0 %)
TREE str | 911263 | 976426 (7.2 %) | 880388 (-3.4 %) | 921590 (1.1 %)
**Geomean** | 1194447 | 1235272 **(3.4 %)** | 1210907 **(1.4 %)** | 1195418 **(0.1 %)**

#### [tuple.perftest](https://github.com/tarantool/tarantool/blob/master/perf/tuple.cc) (millions calls per sec)
| Benchmark  | `-fno-stack-protector` | `-fstack-protector` | `-fstack-protector-strong` | `-fstack-protector-all` |
| -- | -- | -- | -- | -- |
| bench_tuple_new | 8.90 | 8.45  (-5.1 %) | 8.47  (-4.8 %) | 7.76  (-12.8 %) |
| bench_tuple_delete | 47.94 | 44.98  (-6.2 %) | 48.70  (1.6 %) | 43.70  (-8.8 %) |
| bench_tuple_ref_unref_low | 245.84 | 237.24  (-3.5 %) | 240.56  (-2.1 %) | 240.96  (-2.0 %) |
| bench_tuple_ref_unref_high | 230.15 | 223.39  (-2.9 %) | 217.61  (-5.4 %) | 228.32  (-0.8 %) |
| tuple_access_members | 942.41 | 917.91  (-2.6 %) | 897.32  (-4.8 %) | 942.67  (0.0 %) |
| tuple_access_data | 651.03 | 629.96  (-3.2 %) | 629.48  (-3.3 %) | 650.96  (-0.0 %) |
| tuple_access_data_range | 553.09 | 565.25  (2.2 %) | 505.39  (-8.6 %) | 581.72  (5.2 %) |
| tuple_access_unindexed_field | 102.10 | 103.37  (1.2 %) | 98.57  (-3.5 %) | 98.03  (-4.0 %) |
| tuple_access_indexed_field | 330.40 | 327.67  (-0.8 %) | 326.06  (-1.3 %) | 322.55  (-2.4 %) |
| tuple_tuple_compare | 41.30 | 41.30  (-0.0 %) | 39.51  (-4.4 %) | 36.02  (-12.8 %) |
| tuple_tuple_compare_hint | 37.69 | 35.08  (-6.9 %) | 35.90  (-4.7 %) | 32.75  (-13.1 %) |
| **Geomean** | 140.78 | 137.16  **(-2.6 %)** | 135.43  **(-3.8 %)** | 133.91  **(-4.9 %)** |
