### ISSUE TITLE
JSON doesn't encode NULL and rounding point zero to nearest whole

### ISSUE THREAD

**Issue by zloidemon** [tarantool/tarantool#754]
Tarantool have bug with encode *null* in serialized object which correctly encoded in cjson. Also CJSON and tarantool have same bug with rounding 2.0 to 2 instead response correctly 2.0.

```
Tarantool 1.6.4-464-g2f8d107 (Lua console)                     
type 'help' for interactive help                               

---
...
cjson
---
- null
...
json = require "json"
---
...
json.encode({x = 2.0})
---
- '{"x":2}'
...
json.encode({x = nil})
---
- '[]'
...
json.encode({x = null})
---
- '[]'
...
json.encode({x = json.null})
---
- '[]'
...
json.null
---
- null
...
json.encode({x = json.null})
---
- '[]'
...
json.encode({x = json.null, f = 2.0})
---
- '{"f":2}'
...

```

CJSON version 2.1.0 with Lua 5.1.5 on Ubuntu trusty.

```
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio
> 
> json = require 'cjson'
> = json.encode({x = 2.0})
{"x":2}
> = json.encode({x = nil})
{}
> = json.encode({x = null})
{}
> = json.encode({x = json.null})
{"x":null}
> = json.encode({x = json.null})
{"x":null}
> = json.encode({x = json.null, f = 2.0})
{"f":2,"x":null}
> 
```

**Comment by zloidemon** [comment]
If use:

```
json = require 'json'
json.encode({x=json.NULL})
```

it works, but why it not compatible with cjson?

**Comment by rtsisyk** [comment]
I added .NULL to all serializers (msgpack, json, yaml). According to our code style conventions, all constants are named in upper case manner. Do you feel that we also need .null alias?

**Comment by zloidemon** [comment]
Yes, I suggest that is good way to use json.null. Because people might used to cjson early and have a code which they might to wish port on tarantool.

**Comment by rtsisyk** [comment]
I've added .null.

2 vs 2.0 is not a problem at all.
