### ISSUE TITLE
Concurrent C API `fiber_join()` is unsafe

### ISSUE THREAD

**Issue by Gumix** [tarantool/tarantool#7562]
**Bug description**

If two or more fibers are yielding in `fiber_join()`, one of them will eventually join and recycle the fiber, while the rest will crash on accessing the recycled fiber's struct, or hang, or totally foreign fiber will be joined. There is no simple solution for this. [More info is here](https://github.com/tarantool/tarantool/pull/7513#discussion_r942985411) and in #7537. The same issue in Lua is addressed in #7531, this ticket is about C API.

**Steps to reproduce**

1. Apply this patch:
```diff
diff --git a/test/unit/fiber.cc b/test/unit/fiber.cc
index 09ef30cf1..19e4debac 100644
--- a/test/unit/fiber.cc
+++ b/test/unit/fiber.cc
@@ -129,6 +129,14 @@ waker_f(va_list ap)
    return 0;
 }

+static int
+joiner_f(va_list ap)
+{
+   struct fiber *fiber = (struct fiber *)fiber()->f_arg;
+   fiber_join(fiber);
+   return 0;
+}
+
 static void
 fiber_join_test()
 {
@@ -182,6 +190,18 @@ fiber_join_test()
    fiber_cancel(fiber);
    fiber_join(fiber);

+   /*
+    * Try to join a fiber by 2 concurrent joiners.
+    */
+   struct fiber *joinee = fiber_new_xc("joinee", noop_f);
+   struct fiber *joiner = fiber_new_xc("joiner", joiner_f);
+   joiner->f_arg = joinee;
+   fiber_set_joinable(joinee, true);
+   fiber_wakeup(joinee);
+   fiber_wakeup(joiner);
+   /* This fiber_join will crash. */
+   fiber_join(joinee);
+
    footer();
 }
```
2. Build Tarantool
3. Run `./test-run.py --builddir ../build unit/fiber.test`

**Expected behavior**

By way of example, `man pthread_join` says:
> If multiple threads simultaneously try to join with the same thread, the results are undefined.

**Comment by mkostoevr** [comment]
The crashes and hungs can be fixed, but I see no way to fix the possible join to fiber the user didn't plan to join without changing the user's code considering the current C API: it has no entries that can be used for reference counting, one can pass a fiber pointer wherever he wants to without informing the system about it.

But if we can introduce something like a `fiber_ref` and make the users use it, it would be better to just make the users join a fiber only once.
