### ISSUE TITLE
Password for guest not checked

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#758]
I have Ubuntu 12.04 and Tarantool 1.6 pulled from source today.

I start with a new installation, that is, there are no Tarantool-database files in the default directory.

I start Tarantool and say
box.cfg{listen=3301}
box.schema.user.grant('guest','read,write,execute','universe')
box.schema.user.passwd('guest', 'sesame')
... I do not close or exit.

I start another shell, with a different default directory, I start Tarantool and say
console = require('console')
console.connect('localhost:3301')

Result: success. I have connected without specifying that my password is 'sesame'.

**Comment by kostja** [comment]
* Peter Gulutzan <notifications@github.com> [15/03/15 22:11]:
> I have Ubuntu 12.04 and Tarantool 1.6 pulled from source today.
> 
> I start with a new installation, that is, there are no Tarantool-database files in the default directory.
> 
> I start Tarantool and say
> box.cfg{listen=3301}
> box.schema.user.grant('guest','read,write,execute','universe')
> box.schema.user.passwd('guest', 'sesame')
> ... I do not close or exit.
> 
> I start another shell, with a different default directory, I start Tarantool and say
> console = require('console')
> console.connect('localhost:3301')

> Result: success. I have connected without specifying that my
> password is 'sesame'.

Yes, this is done on purpose, to support installations which don't need
authentication and access control. Guest is a special user. You should always
be able to connect as guest. In other words, you always have a
CONNECT privilege in tarantool. You can't do anything if you are
guest, though, unless you've been granted privileges.
Please document it.

-- 
http://tarantool.org - a NoSQL database in a Lua script

**Comment by pgulutzan** [comment]
I am unable to agree enthusastically with the comment from Konstantin Osipov for two reasons.
One: if I try to connect with 'guest@wrong_password@localhost:3301') I do not succeed, which shows that the guest password is check in other circumstances.
Two: nobody is going to give a password to guest unless they expect that the password for guest will be checked. If it's intended that the password will be unchecked, then passwd should fail.

**Comment by kostja** [comment]
Peter, in Tarantool, authentication is a standalone request, something like CHANGE-USER in MySQL. When you provide a password in URI, the client tries to issue AUTH request right after establishing a connection. In your case, it tries and it fails.  If you need to become guest, do not issue AUTH at all, it's the default user already. We can prohibit setting a password for guest user, so it will always fail.
I don't think it's a good idea to always return 'success' to AUTH request when user == guest, so in this place 'guest' is treaded like any other user.

**Comment by pgulutzan** [comment]
Konstantin Osipov wrote: "We can prohibit setting a password for guest user, so it will always fail."
Good, then nobody will be able to think they've added protection for the guest user when they haven't.
Thank you for your patient consideration.

**Comment by kostja** [comment]
p
