### ISSUE TITLE
Multi-key access to index by :get()

### ISSUE THREAD

**Issue by zloidemon** [tarantool/tarantool#760]
Would you like to added access to index by multi-key for :get(...) method?

```
box.space.test:insert{'xxxxxxxx', 111, 'test'}
---
- ['xxxxxxxx', 111, 'test']
...
box.space.test.index.oid:get{111, 'test'}
---
- error: More than one tuple found by get()
...
box.space.test.index.oid:select{111, 'test'}
---
- - ['xxxxxxxx', 111, 'test']
```

**Comment by pcdinh** [comment]
Is it equivalent to SQL's WHERE expression with multiple AND conditions?

**Comment by zloidemon** [comment]
Not absolutly, i suggest to use :get() which is mean one returned tuple. That is (like SQL's WHERE):

```lua
for _, k in  box.space.test.index.oid:pairs(111, 'test', {iter = EQ}) do
print(k)
end
```

**Comment by kostja** [comment]
The idea of :get() is to always return one tuple. Use :select() if you need more.
