### ISSUE TITLE
Luajit tests fail on WSL with Ubuntu

### ISSUE THREAD

**Issue by elmaxxo** [tarantool/tarantool#7603]
**Bug description**

After cloning the tarantool repository, I can successfully build it, but when I try to run make test, some luajit tests fail.

* OS: [Ubuntu on WSL-I]
* OS Version: [Ubuntu 20.04.3 LTS]
* Architecture: [amd64]

`tarantool --version` output.
```
Tarantool 2.11.0-entrypoint-369-g130b3c2e1
Target: Linux-x86_64-Debug
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/usr/local -DENABLE_BACKTRACE=ON
Compiler: /usr/bin/cc /usr/bin/c++
C_FLAGS: -fexceptions -funwind-tables -fno-common -fopenmp -msse2 -std=c11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-gnu-alignof-expression -fno-gnu89-inline -Wno-cast-function-type -Werror
CXX_FLAGS: -fexceptions -funwind-tables -fno-common -fopenmp -msse2 -std=c++11 -Wall -Wextra -Wno-strict-aliasing -Wno-char-subscripts -Wno-format-truncation -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type -Werror
```
`/usr/bin/cc --version` output.
```
cc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
**Steps to reproduce**

Reproducer script:

```
#!/bin/bash

git clone https://github.com/tarantool/tarantool.git
cd tarantool
git submodule update --init --recursive
mkdir build && cd build
cmake ..
make test
```

How to run:

Just type `./reproduse`.

**Actual behavior**

<details>
<summary>'make test' command dump</summary>

[  0%] Built target txt2c
[  0%] Built target misc
[  0%] Built target decNumber
[  0%] Built target xxhash
[  3%] Built target zstd
[  5%] Built target bundled-ares-project
[  7%] Built target bundled-nghttp2-project
[  7%] Built target ev
[ 10%] Built target cdt
[ 12%] Built target bundled-libunwind-project
[ 12%] Built target bundled-libcurl-project
[ 12%] Built target eio
[ 12%] Built target coro
[ 12%] Built target minilua
[ 14%] Built target buildvm
[ 14%] Built target buildvm_output
[ 25%] Built target core_static
[ 25%] Built target vm_static
[ 25%] Built target libluajit_static
[ 25%] Built target libluajit
[ 27%] Built target yaml
[ 27%] Built target build_bundled_libs
[ 29%] Built target msgpuck
[ 29%] Built target bit
[ 30%] Built target small
[ 30%] Built target salad
[ 30%] Built target uri
[ 32%] Built target tzcode
[ 38%] Built target core
[ 38%] Built target scramble
[ 38%] Built target cpu_feature
[ 38%] Built target crc32
[ 40%] Built target stat
[ 40%] Built target shutdown
[ 40%] Built target http_parser
[ 40%] Built target coll
[ 40%] Built target crypto
[ 40%] Built target swim_ev
[ 40%] Built target swim_udp
[ 40%] Built target swim
[ 40%] Built target mpstream
[ 60%] Built target server
[ 61%] Built target bitset
[ 61%] Built target csv
[ 61%] Built target json
[ 61%] Built target vclock
[ 61%] Built target raft
[ 61%] Built target box_error
[ 63%] Built target xrow
[ 67%] Built target tuple
[ 67%] Built target xlog
[ 67%] Built target lemon
[ 67%] Built target mkkeywordhash
[ 67%] Built target generate_sql_files
[ 67%] Built target bin2c
[ 92%] Built target box
[ 92%] Built target preprocess_exports
[ 92%] Built target symbols
[ 94%] Built target tarantool
Scanning dependencies of target libfficcall
[ 94%] Building C object third_party/luajit/test/tarantool-tests/ffi-ccall/CMakeFiles/libfficcall.dir/libfficcall.c.o
[ 94%] Linking C shared library libfficcall.so
[ 94%] Built target libfficcall
Scanning dependencies of target libsandwich
[ 94%] Building C object third_party/luajit/test/tarantool-tests/gh-4427-ffi-sandwich/CMakeFiles/libsandwich.dir/libsandwich.c.o
[ 94%] Linking C shared library libsandwich.so
[ 94%] Built target libsandwich
Scanning dependencies of target resboth
[ 94%] Building C object third_party/luajit/test/tarantool-tests/gh-5813-resolving-of-c-symbols/both/CMakeFiles/resboth.dir/resboth.c.o
[ 94%] Linking C shared library resboth.so
[ 94%] Built target resboth
Scanning dependencies of target reshash
[ 94%] Building C object third_party/luajit/test/tarantool-tests/gh-5813-resolving-of-c-symbols/hash/CMakeFiles/reshash.dir/reshash.c.o
[ 94%] Linking C shared library reshash.so
[ 94%] Built target reshash
Scanning dependencies of target resgnuhash
[ 94%] Building C object third_party/luajit/test/tarantool-tests/gh-5813-resolving-of-c-symbols/gnuhash/CMakeFiles/resgnuhash.dir/resgnuhash.c.o
[ 94%] Linking C shared library resgnuhash.so
[ 94%] Built target resgnuhash
Scanning dependencies of target resstripped
[ 94%] Building C object third_party/luajit/test/tarantool-tests/gh-5813-resolving-of-c-symbols/stripped/CMakeFiles/resstripped.dir/resstripped.c.o
[ 94%] Linking C shared library resstripped.so
[ 94%] Built target resstripped
Scanning dependencies of target libproxy
[ 94%] Building C object third_party/luajit/test/tarantool-tests/gh-6098-fix-side-exit-patching-on-arm64/CMakeFiles/libproxy.dir/libproxy.c.o
[ 94%] Linking C shared library libproxy.so
[ 94%] Built target libproxy
Scanning dependencies of target libcur_L
[ 94%] Building C object third_party/luajit/test/tarantool-tests/gh-6189-cur_L/CMakeFiles/libcur_L.dir/libcur_L.c.o
[ 94%] Linking C shared library libcur_L.so
[ 94%] Built target libcur_L
Scanning dependencies of target testlightuserdata
[ 94%] Building C object third_party/luajit/test/tarantool-tests/lj-49-bad-lightuserdata/CMakeFiles/testlightuserdata.dir/testlightuserdata.c.o
[ 96%] Linking C shared library testlightuserdata.so
[ 96%] Built target testlightuserdata
Scanning dependencies of target libmixcframe
[ 96%] Building C object third_party/luajit/test/tarantool-tests/lj-601-fix-gc-finderrfunc/CMakeFiles/libmixcframe.dir/mixcframe.c.o
[ 96%] Linking C shared library libmixcframe.so
[ 96%] Built target libmixcframe
Scanning dependencies of target lightuserdata
[ 96%] Building C object third_party/luajit/test/tarantool-tests/lj-727-lightuserdata-itern/CMakeFiles/lightuserdata.dir/lightuserdata.c.o
[ 96%] Linking C shared library lightuserdata.so
[ 96%] Built target lightuserdata
Scanning dependencies of target libflush
[ 96%] Building C object third_party/luajit/test/tarantool-tests/lj-flush-on-trace/CMakeFiles/libflush.dir/libflush.c.o
[ 98%] Linking C shared library libflush.so
[ 98%] Built target libflush
Scanning dependencies of target testgetmetrics
[ 98%] Building C object third_party/luajit/test/tarantool-tests/misclib-getmetrics-capi/CMakeFiles/testgetmetrics.dir/testgetmetrics.c.o
[ 98%] Linking C shared library testgetmetrics.so
[ 98%] Built target testgetmetrics
Scanning dependencies of target testsysprof
[ 98%] Building C object third_party/luajit/test/tarantool-tests/misclib-sysprof-capi/CMakeFiles/testsysprof.dir/testsysprof.c.o
[ 98%] Linking C shared library testsysprof.so
[ 98%] Built target testsysprof
Scanning dependencies of target tarantool-tests
Running Tarantool tests
/home/zubochiestka/test/tarantool/third_party/luajit/test/tarantool-tests/gh-4476-fix-string-find-recording.test.lua ........... ok
/home/zubochiestka/test/tarantool/third_party/luajit/test/tarantool-tests/gh-7264-add-proto-trace-sysprof-default.test.lua ..... ok
/home/zubochiestka/test/tarantool/third_party/luajit/test/tarantool-tests/lj-426-arm64-incorrect-check-closed-uv.test.lua ...... ok
/home/zubochiestka/test/tarantool/third_party/luajit/test/tarantool-tests/lj-695-ffi-vararg-call.test.lua ...................... ok
/home/zubochiestka/test/tarantool/third_party/luajit/test/tarantool-tests/lj-375-ir-bufput-signed-char.test.lua ................ ok
/home/zubochiestka/test/tarantool/third_party/luajit/test/tarantool-tests/gh-6065-jit-library-smoke-tests.test.lua ............. ok
/home/zubochiestka/test/tarantool/third_party/luajit/test/tarantool-tests/lj-494-table-chain-infinite-loop.test.lua ............ ok
/home/zubochiestka/test/tarantool/third_party/luajit/test/tarantool-tests/lj-505-fold-no-strref-for-ptrdiff.test.lua ........... ok
/home/zubochiestka/test/tarantool/third_party/luajit/test/tarantool-tests/lj-357-arm64-hrefk.test.lua .......................... ok
/home/zubochiestka/test/tarantool/third_party/luajit/test/tarantool-tests/gh-4773-tonumber-fail-on-NUL-char.test.lua ........... ok
/home/zubochiestka/test/tarantool/third_party/luajit/test/tarantool-tests/tonumber-negative-non-decimal-base.test.lua .......... ok
/home/zubochiestka/test/tarantool/third_party/luajit/test/tarantool-tests/gh-6098-fix-side-exit-patching-on-arm64.test.lua ..... ok
/home/zubochiestka/test/tarantool/third_party/luajit/test/tarantool-tests/tools-utils-avl.test.lua ............................. ok
/home/zubochiestka/test/tarantool/third_party/luajit/test/tarantool-tests/gh-6189-cur_L.test.lua ............................... ok
/home/zubochiestka/test/tarantool/third_party/luajit/test/tarantool-tests/lj-584-bad-renames-for-sunk-values.test.lua .......... ok
/home/zubochiestka/test/tarantool/third_party/luajit/test/tarantool-tests/lj-430-maxirconst.test.lua ........................... ok
/home/zubochiestka/test/tarantool/third_party/luajit/test/tarantool-tests/arm64-ccall-fp-convention.test.lua ................... ok
/home/zubochiestka/test/tarantool/third_party/luajit/test/tarantool-tests/fix-fold-simplify-conv-sext.test.lua ................. ok
/home/zubochiestka/test/tarantool/third_party/luajit/test/tarantool-tests/lj-864-varg-rec-base-offset.test.lua ................. ok
/home/zubochiestka/test/tarantool/third_party/luajit/test/tarantool-tests/lj-528-tonumber-0.test.lua ........................... ok
/home/zubochiestka/test/tarantool/third_party/luajit/test/tarantool-tests/gh-3196-incorrect-string-length.test.lua ............. ok
/home/zubochiestka/test/tarantool/third_party/luajit/test/tarantool-tests/misclib-getmetrics-lapi.test.lua ..................... ok
/home/zubochiestka/test/tarantool/third_party/luajit/test/tarantool-tests/gh-4199-gc64-fuse.test.lua ........................... ok
/home/zubochiestka/test/tarantool/third_party/luajit/test/tarantool-tests/gh-6084-missed-carg1-in-bctsetr-fallback.test.lua .... ok
/home/zubochiestka/test/tarantool/third_party/luajit/test/tarantool-tests/lj-524-fold-conv-respect-src-irt.test.lua ............ ok
Segmentation fault
  code: SEGV_MAPERR
  addr: 0xffffffffff700124
  context: 0x7f876e5fe3a0
  siginfo: 0x7f876e5fe9b0
  rax      0xffffffffff700124 -9436892
  rbx      0x7ffff74b5000     140737342296064
  rcx      0x7ffff74b5000     140737342296064
  rdx      0x1                1
  rsi      0x7ffff6bb5040     140737332858944
  rdi      0x7f876e5ffb90     140219649096592
  rsp      0x7f876e5feab0     140219649092272
  rbp      0x12               18
  r8       0x0                0
  r9       0x1                1
  r10      0x0                0
  r11      0x0                0
  r12      0x7f877187e060     140219702042720
  r13      0x0                0
  r14      0x7f876e5ffc40     140219649096768
  r15      0x7f877187f740     140219702048576
  rip      0x7f8771bd2e5b     140219705536091
  eflags   0x10286            66182
  cs       0x33               51
  gs       0x2b               43
  fs       0x53               83
  cr2      0x0                0
  err      0x0                0
  oldmask  0x0                0
  trapno   0x0                0
Current time: 1661354971
Please file a bug at http://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed, 
this may fail as well
#1  0x7f8771b1c2d6 in crash_collect+264
#2  0x7f8771b1e832 in crash_signal_cb+100
#3  0x7f8770f31420 in __restore_rt+0
#4  0x7f8771bd2e5b in dump_dyn_symtab+371
#5  0x7f8771bd316e in resolve_symbolnames+674
#6  0x7f8770abf3d5 in dl_iterate_phdr+389
#7  0x7f8771bd342d in lj_symtab_dump+449
#8  0x7f8771bd34e0 in stream_prologue+53
#9  0x7f8771bd43c5 in lj_sysprof_start+173
#10 0x7f8771b93059 in luaM_sysprof_start+37
#11 0x7f8771bbdfe4 in lj_cf_misc_sysprof_start+149
#12 0x7f8771b77637 in lj_BC_FUNCC+70
#13 0x7f8771b824b5 in lua_pcall+849
#14 0x7f8771afebf6 in luaT_call+45
#15 0x7f8771af5e5c in lua_main+189
#16 0x7f8771af635c in run_script_f+1255
#17 0x7f87718c8a07 in fiber_cxx_invoke(int (*)(__va_list_tag*), __va_list_tag*)+34
#18 0x7f8771b27478 in fiber_loop+136
#19 0x7f8771e8f544 in coro_init+88
/home/zubochiestka/test/tarantool/third_party/luajit/test/tarantool-tests/misclib-sysprof-lapi.test.lua ........................ 
No subtests run 
/home/zubochiestka/test/tarantool/third_party/luajit/test/tarantool-tests/lj-671-arm64-assert-after-mremap.test.lua ............ ok
/home/zubochiestka/test/tarantool/third_party/luajit/test/tarantool-tests/lj-672-cdata-allocation-recording.test.lua ........... ok
Segmentation fault
  code: SEGV_MAPERR
  addr: 0xffffffffff700124
  context: 0x7f12489fe390
  siginfo: 0x7f12489fe9a0
  rax      0xffffffffff700124 -9436892
  rbx      0x7fffce9e8000     140736659881984
  rcx      0x7fffce9e8000     140736659881984
  rdx      0x1                1
  rsi      0x7fffce0e8040     140736650444864
  rdi      0x7f12489ffb80     139716504583040
  rsp      0x7f12489feaa0     139716504578720
  rbp      0x12               18
  r8       0x0                0
  r9       0x1                1
  r10      0x0                0
  r11      0x0                0
  r12      0x7f124babe060     139716555694176
  r13      0x0                0
  r14      0x7f12489ffc30     139716504583216
  r15      0x7f124babf740     139716555700032
  rip      0x7f124be0ce5b     139716559162971
  eflags   0x10286            66182
  cs       0x33               51
  gs       0x2b               43
  fs       0x53               83
  cr2      0x0                0
  err      0x0                0
  oldmask  0x0                0
  trapno   0x0                0
Current time: 1661354971
Please file a bug at http://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed, 
this may fail as well
#1  0x7f124bd562d6 in crash_collect+264
#2  0x7f124bd58832 in crash_signal_cb+100
#3  0x7f124b171420 in __restore_rt+0
#4  0x7f124be0ce5b in dump_dyn_symtab+371
#5  0x7f124be0d16e in resolve_symbolnames+674
#6  0x7f124acff3d5 in dl_iterate_phdr+389
#7  0x7f124be0d42d in lj_symtab_dump+449
#8  0x7f124be0b424 in lj_memprof_start+454
#9  0x7f124bdf8968 in lj_cf_misc_memprof_start+427
#10 0x7f124bdb1637 in lj_BC_FUNCC+70
#11 0x7f124bdbc4b5 in lua_pcall+849
#12 0x7f124bd38bf6 in luaT_call+45
#13 0x7f124bd2fe5c in lua_main+189
#14 0x7f124bd3035c in run_script_f+1255
#15 0x7f124bb02a07 in fiber_cxx_invoke(int (*)(__va_list_tag*), __va_list_tag*)+34
#16 0x7f124bd61478 in fiber_loop+136
#17 0x7f124c0c9544 in coro_init+88
/home/zubochiestka/test/tarantool/third_party/luajit/test/tarantool-tests/misclib-memprof-lapi.test.lua ........................ 
No subtests run 
/home/zubochiestka/test/tarantool/third_party/luajit/test/tarantool-tests/fix-slot-check-for-mm-record.test.lua ................ ok
/home/zubochiestka/test/tarantool/third_party/luajit/test/tarantool-tests/fix-gc-setupvalue.test.lua ........................... ok
/home/zubochiestka/test/tarantool/third_party/luajit/test/tarantool-tests/misclib-sysprof-capi.test.lua ........................ ok
/home/zubochiestka/test/tarantool/third_party/luajit/test/tarantool-tests/lj-49-bad-lightuserdata.test.lua ..................... ok
/home/zubochiestka/test/tarantool/third_party/luajit/test/tarantool-tests/gh-6371-string-char-no-arg.test.lua .................. ok
Segmentation fault
  code: SEGV_MAPERR
  addr: 0xffffffffff700124
  context: 0x7ff9369fe390
  siginfo: 0x7ff9369fe9a0
  rax      0xffffffffff700124 -9436892
  rbx      0x7fffc9f21000     140736581472256
  rcx      0x7fffc9f21000     140736581472256
  rdx      0x1                1
  rsi      0x7fffc9621040     140736572035136
  rdi      0x7ff9369ffb80     140708340038528
  rsp      0x7ff9369feaa0     140708340034208
  rbp      0x15               21
  r8       0x0                0
  r9       0x1                1
  r10      0x0                0
  r11      0x0                0
  r12      0x7ff939bae060     140708392132704
  r13      0x0                0
  r14      0x7ff9369ffc30     140708340038704
  r15      0x7ff939baf740     140708392138560
  rip      0x7ff939f08e5b     140708395650651
  eflags   0x10286            66182
  cs       0x33               51
  gs       0x2b               43
  fs       0x53               83
  cr2      0x0                0
  err      0x0                0
  oldmask  0x0                0
  trapno   0x0                0
Current time: 1661354972
Please file a bug at http://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed, 
this may fail as well
#1  0x7ff939e522d6 in crash_collect+264
#2  0x7ff939e54832 in crash_signal_cb+100
#3  0x7ff939261420 in __restore_rt+0
#4  0x7ff939f08e5b in dump_dyn_symtab+371
#5  0x7ff939f0916e in resolve_symbolnames+674
#6  0x7ff938def3d5 in dl_iterate_phdr+389
#7  0x7ff939f0942d in lj_symtab_dump+449
#8  0x7ff939f07424 in lj_memprof_start+454
#9  0x7ff939ef4968 in lj_cf_misc_memprof_start+427
#10 0x7ff939ead637 in lj_BC_FUNCC+70
#11 0x7ff939eb84b5 in lua_pcall+849
#12 0x7ff939e34bf6 in luaT_call+45
#13 0x7ff939e2be5c in lua_main+189
#14 0x7ff939e2c35c in run_script_f+1255
#15 0x7ff939bfea07 in fiber_cxx_invoke(int (*)(__va_list_tag*), __va_list_tag*)+34
#16 0x7ff939e5d478 in fiber_loop+136
#17 0x7ff93a1c5544 in coro_init+88
/home/zubochiestka/test/tarantool/third_party/luajit/test/tarantool-tests/gh-5813-resolving-of-c-symbols.test.lua .............. 
No subtests run 
/home/zubochiestka/test/tarantool/third_party/luajit/test/tarantool-tests/lj-726-profile-flush-close.test.lua .................. 
not ok - profile output was flushed and closed
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests 
/home/zubochiestka/test/tarantool/third_party/luajit/test/tarantool-tests/bc-jit-unpatching.test.lua ........................... ok
/home/zubochiestka/test/tarantool/third_party/luajit/test/tarantool-tests/lj-601-fix-gc-finderrfunc.test.lua ................... ok
/home/zubochiestka/test/tarantool/third_party/luajit/test/tarantool-tests/lj-603-err-snap-restore.test.lua ..................... ok
/home/zubochiestka/test/tarantool/third_party/luajit/test/tarantool-tests/gh-6227-bytecode-allocator-for-comparisons.test.lua .. ok
/home/zubochiestka/test/tarantool/third_party/luajit/test/tarantool-tests/or-232-unsink-64-kptr.test.lua ....................... ok
/home/zubochiestka/test/tarantool/third_party/luajit/test/tarantool-tests/gh-4427-ffi-sandwich.test.lua ........................ ok
/home/zubochiestka/test/tarantool/third_party/luajit/test/tarantool-tests/lj-727-lightuserdata-itern.test.lua .................. ok
/home/zubochiestka/test/tarantool/third_party/luajit/test/tarantool-tests/misclib-getmetrics-capi.test.lua ..................... ok
/home/zubochiestka/test/tarantool/third_party/luajit/test/tarantool-tests/lj-flush-on-trace.test.lua ........................... ok
/home/zubochiestka/test/tarantool/third_party/luajit/test/tarantool-tests/lj-586-debug-non-string-error.test.lua ............... ok
/home/zubochiestka/test/tarantool/third_party/luajit/test/tarantool-tests/lj-512-profiler-hook-finalizers.test.lua ............. 
not ok - profiler sampling
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests 
/home/zubochiestka/test/tarantool/third_party/luajit/test/tarantool-tests/lj-351-print-tostring-number.test.lua ................ ok

Test Summary Report
-------------------
/home/zubochiestka/test/tarantool/third_party/luajit/test/tarantool-tests/misclib-sysprof-lapi.test.lua                      (Wstat: 134 Tests: 0 Failed: 0)
  Non-zero wait status: 134
  Parse errors: No plan found in TAP output
/home/zubochiestka/test/tarantool/third_party/luajit/test/tarantool-tests/misclib-memprof-lapi.test.lua                      (Wstat: 134 Tests: 0 Failed: 0)
  Non-zero wait status: 134
  Parse errors: No plan found in TAP output
/home/zubochiestka/test/tarantool/third_party/luajit/test/tarantool-tests/gh-5813-resolving-of-c-symbols.test.lua            (Wstat: 134 Tests: 0 Failed: 0)
  Non-zero wait status: 134
  Parse errors: No plan found in TAP output
/home/zubochiestka/test/tarantool/third_party/luajit/test/tarantool-tests/lj-726-profile-flush-close.test.lua                (Wstat: 256 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
/home/zubochiestka/test/tarantool/third_party/luajit/test/tarantool-tests/lj-512-profiler-hook-finalizers.test.lua           (Wstat: 256 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
Files=48, Tests=120,  5 wallclock secs ( 0.07 usr  0.27 sys +  4.40 cusr  5.45 csys = 10.19 CPU)
Result: FAIL
make[3]: *** [third_party/luajit/test/tarantool-tests/CMakeFiles/tarantool-tests.dir/build.make:76: tarantool-tests] Error 1
make[2]: *** [CMakeFiles/Makefile2:3026: third_party/luajit/test/tarantool-tests/CMakeFiles/tarantool-tests.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:6965: test/CMakeFiles/test.dir/rule] Error 2
make: *** [Makefile:2461: test] Error 2

</details>

A clear and concise description of what you see.

**Expected behaivor**

All tests are passed.

**Comment by fckxorg** [comment]
The issue doesn't reproduce in WSL2 anymore. Also, as a general comment, I wouldn't recommend anyone use WSL2 as a development environment, as it has a lot of unsupported features and unexpected effects.
