### ISSUE TITLE
Any plans to add graph capabilities?

### ISSUE THREAD

**Issue by colorsocean** [tarantool/tarantool#761]

**Comment by pcdinh** [comment]
Interesting question. What feature do you want to see in particular?

**Comment by colorsocean** [comment]
Background: I used OrientDB in personal and work projects, and liked it graph capabilities and Direct Links/FetchPlan feature.
1) Connect tuples from different spaces with typed 'edges'
Use case: We can select all users and newsgroups that connected with edge 'subscribed' to current user in single database call.
2) Friends n-depth (no comment)

And I think 'Link'/'FetchPlan' is a strong concept.
In Orient I can Store link to 'Thumbnail' object in 'Gallery' object's 'Cover' field, and then query 'Galleries' with plan "cover:1" and fetch Gallery and it's Cover in single call. A good feature for denormalization.

**Comment by colorsocean** [comment]
Only some of such features will help to cover a lot more use cases.

Sorry for my English:)

**Comment by crudbug** [comment]
I was thinking about this same thing. OrientDB provides multi-model data persistence with Document, Object and Graph models. The idea is to treat vertices and edges as documents making relationships as first class citizens with no joining cost at runtime, traversals are O(1) . I haven't played in-depth with Tarantool, but from my understanding it can also provide multi-model data persistence : plugins for graph store.

**Comment by kostja** [comment]
The engine API is here: 
https://github.com/tarantool/tarantool/blob/master/src/box/engine.h

You could take a look at memtx_engine implementation, and play with our in-memory data structures. 

We have never thought about applicability for graph analysis. But we have never thought about many other ways people use Tarantool.

**Comment by kostja** [comment]
Thank you for your feature request, for now we need to maintain focus - and it would be fair to say we do  not plan to do it in the near future. The storage engine API is there, with it, one can easily implement graph features (store pointers to connected objects in tuples, use tuple_format object to track all tuple modifications, use index iterator API for graph iteration).

**Comment by aleclarson** [comment]
@kostja Can this be reconsidered? I would love an officially supported way of having a field in one tuple point to another tuple (which may exist in the same space or another).

**Comment by aleclarson** [comment]
@bigbes explained:
> Tuples are recreated when changed, so the pointer may change frequently. Even if it doesn't, the pointer is guaranteed to change when Tarantool restarts.
