### ISSUE TITLE
Bad permissions for tarantoolctl

### ISSUE THREAD

**Issue by zloidemon** [tarantool/tarantool#762]
Bad permissions for tarantoolctl.

```
%> tarantoolctl
zsh: permission denied: tarantoolctl
```

Fix: https://github.com/tarantool/tarantool/commit/b2da609cee03185edd462fb347fd5edd9ccb8e15

**Comment by zloidemon** [comment]
Please merge.

**Comment by kostja** [comment]
Thanks!
