### ISSUE TITLE
Introduce pagination

### ISSUE THREAD

**Issue by drewdzzz** [tarantool/tarantool#7639]
[PM link](https://www.notion.so/tarantool/After-in-iterators-0105eac5996b41e1ac7fd418de373b56)

Generalization of #5282.

Implement options `after` and `fetch_pos` in `select` and `pairs` methods. If `after` is specifiend it must contain a tuple from which selection must continue or its `position`. More strictly:

- For tree index (memtx and vinyl) and forward iteration (EQ, GE, GT, ALL) `select` and `pairs` must internally skip all tuples less-or-equal-to tuple given in after in terms of that index.
- For tree index (memtx and vinyl) and reverse iteration (REQ, LE, LT) `select` and `pairs` must internally skip all tuples greater-or-equal-to tuple given in after in terms of that index.
- For all other indexes that option must not be allowed (instead of rtree with NEIGHBOR iterator, but it is follow-up).
- Duplicates are not allowed.
- Pagination with `after` option must be more effective that limit-offset approach and it must not depend on the number of previously selected tuples.
- Performance of `select` and `pairs` without introduced options must not degrade.
- In Lua tuple must be table or cdata with C pointer to tuple, `position` must be a string, that was received from special methods - user is not allowed to create `position` by himself.
- In IPROTO tuple must be MP_ARRAY, `position` must be `MP_BIN`.
- Only those fields of the after tuple that participate in key definition of the index (and also, if the index is not unique, key definition of the primary index) are actually make sense; all other fields in the tuple are guaranteed to be ignored.
- If `box.NULL` or empty Lua string are passed to `after` option, it makes no effect (start position).

Option `fetch_pos` must return position descriptor of last selected tuple (or passed position descriptor, if no tuples were found) as the second return value.

Implement method `index:tuple_pos(tuple)` to allow get position by tuple.

Example:
```lua
local tuples, pos = index:select(key, {fetch_pos=true, limit = 10})
process_tuples(tuples)
tuples, pos = index:select(key, {fetch_pos=true, limit=10, after=pos})
process_tuples(tuples)
```

## Sub-tasks
- [x] #7633
- [x] #7634
- [x] #7635
- [x] #7636
- [x] #7637
- [x] #7638

**Comment by R-omk** [comment]
I think you need to describe in more detail how to use reverse select/pairs.

**Comment by R-omk** [comment]
Why is the term "position" used everywhere? The commonly accepted name for this is "cursor"

**Comment by drewdzzz** [comment]
> I think you need to describe in more detail how to use reverse select/pairs.

Could you, please, tell, what exactly is unclear?

**Comment by R-omk** [comment]
> Could you, please, tell, what exactly is unclear?

Show usage examples.

---

For example, in the `crud`  library  explicitly says to use negative values for the option analog of the limit option.
https://github.com/tarantool/crud/blob/master/doc/select.md#reverse-pagination


At the same time, the `pairs` method does not support the reverse pass at all.
https://github.com/tarantool/crud/blob/master/doc/pairs.md#pagination

**Comment by R-omk** [comment]
> Could you, please, tell, what exactly is unclear?

My question about reverse iterator is no longer relevant. I was confused by how it is implemented in the crud. After all, there the query planner chooses the direction itself, but here the iterator is set explicitly.
