### ISSUE TITLE
move signal handling to iproto thread

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#765]
if the main thread has a runaway stored procedure, signal handling in iproto thread can help react to a signal even on a very busy server.

The challenge is that currently iproto_init() is called after box_init(), i.e. it's optional. So we need to move the handlers from one event loop to another in iproto_init(). It could be a matter of simple ev_signal_stop() in tx thread followed by ev_signal_start() in net thread. 

Another challenge is delivering signal messages between threads, since most messages need to be processed in tx thread: snapshot, terminate, even logrotate.

Unclear whether the approach is worth the trouble.

**Comment by mejedi** [comment]
It's sorta recursive. Txn thread may get busy preventing signal handlers in libev from running. Fine, move them to another thread. However the code triggered by the signal MUST run in the txn thread. We need some form of IPC with the txn thread. The busy event loop in the txn thread, which is the problem we were trying to sole in the first place, will render the IPC inoperable.

Sidenote: logrotate doesn't use libev and hence it doesn't suffer from the busy event loop.

**Comment by kostja** [comment]
I agree, this was a stupid idea, perhaps some signals can be handled this way but not all.
