### ISSUE TITLE
Forbid same names for check constraints and foreign keys

### ISSUE THREAD

**Issue by alyapunov** [tarantool/tarantool#7650]
Now a user can create a set of check constraints and foreign keys for each field and entire tuple. By design for each field/tuple the check constraints must have unique names, the same is true for foreign keys. But now it is possible to create a check constraint and a foreign key with the same name.

This approach is good, but introduces difficulties in SQL implementation. On the other hand in real life it is hard to imagine a user that wants to create both check and foreign constraints for a field, especially with the same names. As for entire tuple it seems less obvious, but still it seems that there will be no harm if we forbid same names.

So, let's forbid same names for check constraints and foreign keys.

**Comment by unera** [comment]
Hi. I doubt that we need to unique constraint name.

Mergen wants to do SQL operator:

```sql
ALTER TABLE foo DROP CONSTRAINT $constraint_name
```

I suggested him to construct `$constraint_name` as:
`${space_name}.${constraint_type}.${constraint_name}`

Don't apply the patch until we discuss that.

**Comment by ImeevMA** [comment]
After discussion with @unera we decided to introduce [`ALTER TABLE DROP CONSTRAINT constraint_type`](https://github.com/tarantool/tarantool/issues/9112).
