### ISSUE TITLE
Parallel qsort without OpenMP

### ISSUE THREAD

**Issue by Gumix** [tarantool/tarantool#7689]
Currently OpenMP is used by Tarantool only for parallel qsort:
https://github.com/tarantool/tarantool/blob/c294a929b058490390ddb2f1216b1984461a5f4e/third_party/qsort_arg_mt.c#L218-L219

However `libgomp.a` in some Linux distros (e.g. CentOS) doesn't work with position-independent code, which is [required for security](https://github.com/tarantool/tarantool/issues/7536).
```
/opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/8/libgomp.a(parallel.o): relocation R_X86_64_32 against hidden symbol `gomp_global_icv' can not be used when making a PIE object
/opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/8/libgomp.a(task.o): relocation R_X86_64_32S against `.rodata' can not be used when making a PIE object; recompile with -fPIC
```
https://github.com/tarantool/tarantool/pull/7587#discussion_r967365257

Let's get rid of OpenMP by rewriting qsort to pthread or something like that.

**Comment by CuriousGeorgiy** [comment]
How about using [std::sort](https://en.cppreference.com/w/cpp/algorithm/sort) and setting a parallel [execution policy](https://en.cppreference.com/w/cpp/algorithm/execution_policy_tag_t)?

**Comment by CuriousGeorgiy** [comment]
Good point of reference: https://stackoverflow.com/a/3969847

**Comment by Gumix** [comment]
> How about using [std::sort](https://en.cppreference.com/w/cpp/algorithm/sort) and setting a parallel [execution policy](https://en.cppreference.com/w/cpp/algorithm/execution_policy_tag_t)?

It requires [at least GCC 10](https://godbolt.org/z/r94Mq4zah) (or GCC 9 + TBB), while we still do support GCC 4.8, but most importantly, [parallel STL is actually implemented in GCC via OpenMP](https://gcc.gnu.org/onlinedocs/libstdc++/manual/parallel_mode_using.html).

**Comment by CuriousGeorgiy** [comment]
@nshy you forgot to remove this hack:
https://github.com/tarantool/tarantool/blob/de0731bd316706c4ff509f6302325a1d3c8736bc/cmake/hardening.cmake#L5-L6

**Comment by nshy** [comment]
Thanks for the care! The issue is addressed in PR https://github.com/tarantool/tarantool/pull/8784
