### ISSUE TITLE
Centos 6 x86_64 test failed

### ISSUE THREAD

**Issue by Sulverus** [tarantool/tarantool#770]
There are problem with different floating point representation 

box/call.test.py                                [ fail ]

Test failed! Result content mismatch:
--- box/call.result Wed Mar 25 13:42:41 2015
+++ box/call.reject Wed Mar 25 13:43:03 2015
```
@@ -24,7 +24,7 @@
 - [False]
 - [-1]
 - [1.123]
-- [1e+123]
+- [9.9999999999999998e+122]
 - [None]
 ...
 f1=nil
```

**Comment by Sulverus** [comment]
call.test updated with workaround for centos6

**Comment by kostja** [comment]
Merged.
