### ISSUE TITLE
☂️ Override IPROTO request types

### ISSUE THREAD

**Issue by alyapunov** [tarantool/tarantool#7716]
# Annotation

[Design document](https://www.notion.so/tarantool/box-iproto-override-44935a6ac7e04fb5a2c81ca713ed1bce)

Currently each IPROTO request type has a has a hard-coded handler, unknown request type is an error.

In order to provide compatibility of current tarantool version with future versions we already need to and an ability to manually override  handlers with user-provided handle, both for currently known and unknown request types. In case of known request types there must be a simple way to fallback to default behavior.

For example if we introduce some new IPROTO request type, we would be able to add a compatibility layer that will override handler for that request type in older version. Another example - if we add one more option to IPROTO_REPLACE, we will override its handler that would handle that new option (if present) or fallback to default hander (if the option is not present).

# Decomposition:
- [x] #7894
- [x] #7895
- [x] #7897
- [x] #7898
- [x] #7901
- [x] #7904

**Comment by Totktonada** [comment]
NB: We shouldn't step into the same problem as we have in space triggers with those handlers: it is tricky to write a hot-reload-aware code that would replace its own old space trigger. See #5826 and #7300.

**Comment by CuriousGeorgiy** [comment]
> We shouldn't step into the same problem as we have in space triggers with those handlers: it is tricky to write a hot-reload-aware code that would replace its own old space trigger

@Totktonada, AFAIC, this is not the case, since we will only have one handler set at a time (i.e., we won't maintain a stack of list of handlers).
