### ISSUE TITLE
Box schema downgrade

### ISSUE THREAD

**Issue by alyapunov** [tarantool/tarantool#7718]
[PM link](https://www.notion.so/box-schema-downgrade-from-2-11-b3af37fb5f66487da95429014a8f2ea3)

Now there's a function `box.schema.upgrade` which make changes in DB so it becomes compliant to binary version. Now this function is called automatically at certain cases.

The idea is to improve this mechanism:
- Allow to pass a certain version to `box.schema.upgrade` (the latest by default).
- List all possible versions in `box.schema.upgrade_list`.
- Allow to downgrade at least down to 2.8 using `box.schema.downgrade`.

Note that downgrade, for example, from 2.10 to 2.8 must be run on 2.10 binary.

In some cases downgrade function will need to make snapshot or perhaps immediately stop tarantool process if it's needed.

**Comment by Totktonada** [comment]
I looked at the 2.10 and 2.11 upgrade scripts that we have now:

https://github.com/tarantool/tarantool/blob/302d91cf8e13e1a167424e4f116612113a012d12/src/box/lua/upgrade.lua#L1215-L1242

Those upgrade scripts were introduced in 18eae244c8e0fcd571c02438e4f9006b5bce4e67 and b771a5bfa97ea435817769b18d163bfc12085049.

It's interesting. My question is whether we should revert effects of those upgrades at downgrade. IOW, what is the goal of the downgrade call:

* Work in a replicaset with instances of an older tarantool version and allow to downgrade this particular instance to the older version.
* Imitate older version behavior as much as possible.

The latter doesn't seems meaningful, to be honest. We anyway run the new runtime.

The present upgrades looks really as just bugfixes. It seems that it is not worth to revert them at the downgrade call (if the upgrades allow an older tarantool version to bootstrap from the new snapshot and work correctly, we need to check it).

Any thoughts?

**Comment by Totktonada** [comment]
Also a new upgrade script will be added in PR #7789, but I wouldn't revert it in the downgrade scripts.
