### ISSUE TITLE
Console improving and administration tools

### ISSUE THREAD

**Issue by zloidemon** [tarantool/tarantool#772]
- Rename _tarantoolctl_ to **tctl**. It would more fast access to the system and not miss to run another tarantool when you have to fix system/taranool(instance).
- Rename _enter_ to **login** to access console, and ask login and password of the user. Or added root permissions for _enter_, but **login** will have access all where users will able to use their login/password to access by config from ~/.tarantool or on the fly.
- Auto compilation for **tctl** to bash/zsh. Like **servi<tab> ast<tab> res<tab>** which will auto complete to **service asterisk restart**.
- Show logs in the console. When you logged in tarantool, would be nice to show logs on the fly it its need.
- Related to above, add  support sticky console prompt. If you have a lot logs/data in the console, very good thing to stick **tarantool>** to the last line of terminal, where you can write something but on the time you will see what does an application and write. (You can see **asterisk -rvv**, how it works.)
- Add execute in instance without log in tarantool and support args like -e, -l, and etc. For example:
  - login to tarantool -> tctl -l instance_name
  - execute something -> tctl -l instance_name -e 'function x(e) return space:select{e} end; x(1);'
- Readline tab completion, for example: https://github.com/torch/trepl

**Comment by Sulverus** [comment]
Nice, i think -le flags will be useful.

**Comment by rtsisyk** [comment]
* tctl makes no sense, IMHO.
* tarantoolctl enter uses unix socket. We don't have authorization on console port.
* Auto completion for command line is nice feature 
* -le may be useful
* Autocompletion for admin console is must have

**Comment by Totktonada** [comment]
Most of the problems are solved at this time. Some may be discussed in context of [tt](https://github.com/tarantool/tt).

I think that we can close this issue.

----
  
> - Rename _tarantoolctl_ to **tctl**. It would more fast access to the system and not miss to run another tarantool when you have to fix system/taranool(instance).

Now there is [tt](https://github.com/tarantool/tt) that covers functionality from the `tarantoolctl` and the `cartridge` commands. And it has a short name.

> - Rename _enter_ to **login** to access console, and ask login and password of the user. Or added root permissions for _enter_, but **login** will have access all where users will able to use their login/password to access by config from ~/.tarantool or on the fly.

As said above, it is irrelevant to accessing tarantool using a Unix socket. May be useful when connecting to a remote instance using iproto.

> - Auto compilation for **tctl** to bash/zsh. Like **servi<tab> ast<tab> res<tab>** which will auto complete to **service asterisk restart**.

`tt completion` subcommand generates tab-completion code for various shell environments.

> - Show logs in the console. When you logged in tarantool, would be nice to show logs on the fly it its need.

`tt log` command was added in the recent [v2.4.0](https://github.com/tarantool/tt/releases/tag/v2.4.0) release.

> - Related to above, add  support sticky console prompt. If you have a lot logs/data in the console, very good thing to stick **tarantool>** to the last line of terminal, where you can write something but on the time you will see what does an application and write. (You can see **asterisk -rvv**, how it works.)

Solved for tarantool's built-in console in #7169. I guess that `tt`'s console client is not affected.

> - Add execute in instance without log in tarantool and support args like -e, -l, and etc. For example:
>   - login to tarantool -> tctl -l instance_name
>   - execute something -> tctl -l instance_name -e 'function x(e) return space:select{e} end; x(1);'

Not sure here.

> - Readline tab completion, for example: https://github.com/torch/trepl

Supported in tarantool's built-in console for a long time, see #86. Supported in `tt` from scratch.
