### ISSUE TITLE
Tarantool storage database as an embedded library

### ISSUE THREAD

**Issue by anatol** [tarantool/tarantool#7721]
**Is your feature request related to a problem? Please describe.**

I am working on a Golang-based application that needs to store and process data. Due to various reasons, the storage needs to be an embedded library. In addition to the embedding requirements the database needs to be fast, it needs to have replication support (at minimum master-slave but master-master would be nice as well), and ideally support database features such as multiple tables, rich datatypes, transactions, and indexes. 

**Describe the solution you'd like**

I read about Tarantool and my understanding is that it is an app server with optional durable storage support.

Now I am trying to look at Tarantool from a different angle - what if its storage can be used as an embedded database for other applications? I want to know how difficult to achieve it and whether it is possible at all.

To make the storage embeddable one needs a clean API written in C that allows doing CRUD operations as well as manage storage parameters. Once it has C interface I can look at Golang bindings.

**Describe alternatives you've considered**

I looked at sqlite but it does not have any replication support. Rocksdb has a huge codebase and difficult to make it truly embedded (but so far it is the best option for me). Many other golang embedded databases (pebble, golelveldb, ...) do not have replication and have rudimentary support for transactions/secondary indexes/...

**Definition of Done**

Ability to use the new embedded database from Golang program.

**Comment by kyukhin** [comment]
We have no such plans for now.
