### ISSUE TITLE
Embed tarantool/metrics in core tarantool

### ISSUE THREAD

**Issue by DifferentialOrange** [tarantool/tarantool#7725]
The series of tickets about tarantool/metrics embedding is just a beginning of the discussion started with possible Product Team plans related to Flight Recorder development. Expected features may be reevaluated, estimation is preliminary.

[tarantool/metrics](https://github.com/tarantool/metrics) is a Lua+ffi module to collect and expose [Tarantool](https://tarantool.io/)-based applications metrics.

The ability to collect metrics in a single place and expose them is useful. It seems that it could be even more useful if module would be embedded to core tarantool. It could decrease the inhomogeneity in core tarantool handles and metrics exported with the module, remove the time lag between releasing new observation handles in core and supporting them in tarantool/metrics. Some potential features like exposing metrics in a separate thread are more likely to implement in core tarantool rather then separate module. It could also simplify integrating another Lua modules with `metrics`. At last, integrating `metrics` with FlightRec would be possible.

On the other hand, it is likely to also bring several inconveniences. Providing new versions would be much harder since now new metrics release would be bound to core Tarantool release. (It is partially would be covered by new `tarantool/metrics-extensions` module, see #7727). It is also a drawback that core tarantool would became a much complicated monolith. Moreover, if it is planned to enable metrics by default (as we discussed), it would affect performance.

Integrating `metrics` with existing core features may vary from most simplest (just put a bunch of Lua code to the core) to time-consuming. For example, most default metrics handles is actually about extracting something from core handle call and putting it to a  Lua table. Since now the original values are in our hands, it could be optimized in some way. Global metrics registry may also be reworked to be more efficient. Not only internals could be reworked -- external API is highly likely to get reworked too. For example, it seems expected to expose some configuration to `box.cfg`, especially if we will enable metrics collect by default. On the other hand, we shouldn't remove old handles to support compatibility with applications that uses `metrics` as a module. If it is planned to use `metrics` as a replacement for `box.info` and many other calls, additional handles would be needed.

One may also want to separate `cartridge`-related features from the module.

Embedding [tarantool/checks] is also a prerequirement to embedding `metrics`: it is a rock dependency.

**Definition of Done**

Minimal: any application that uses the module can use `require('metrics')` and another features without any additional rocks installation.

Additional: internal optimization, convenient API for configuration.

**Comment by DifferentialOrange** [comment]
Current task estimation is based on the following solution:
- embedding the module
- porting tests
- prove simple API handles for `box.cfg`.

**Comment by DifferentialOrange** [comment]
### feature: configuration through box.cfg

Let's also discuss `metrics` module configuration. There are three things:
- default metrics configuration,
- global labels configuration
- export configuration.

**default metrics configuration** is the procedure of initializing some default metric collectors and callbacks for their update or the reverse cleanup procedure. Now, until `metrics.enable_default_metrics()` is called, there are no any default metrics in the registry. In non-cartridge apps, it must be called manually on application setup, in cartridge apps it is called as the part of `cartridge.roles.metrics` initialization. If called without arguments, all possible default metrics are enabled (actual metrics depends on available box handles and the presence of `cartridge` module). There are two optional arguments: `include`, `exclude`. Only one of them could be provided in the same time. `include` is the list of metric groups that should be enabled: in result only `include` metrics are enabled instead of all. (Examples of metric groups: space operation metrics, fiber metrics, luajit metrics, vinyl metrics.) `exclude` is the list of metric groups that should not be enabled: in result all minus `exclude` metrics are enabled instead of all.

box.cfg API for configuring this one should be provided since we want to use box.cfg defaults to enable metrics for an instance.

**global labels configuration** is widely used on the metrics database (Prometheus, InfluxDB) side to distinguish instance metrics. Cartridge role sets instance alias and zone on initialization. Now such configuration is performed through `metrics.set_global_labels` handle which accepts `{string = string,..}` table with labels.

It is possible that it also would be useful for flight recorder (I'm not sure for now), so it seems we also need to provide this in box.cfg API.

**export configuration** allows to set some export and health HTTP handles by default. It requires `http` server module to work. I'm not sure we should provide box.cfg API for this one.

Note that all of the above could also be configured through `cartridge.roles.metrics` clusterwide configuration.

**Comment by R-omk** [comment]
Please consider otlp metric, since OpenMetrics has a superset of Prometheus' types.

https://opentelemetry.io/docs/reference/specification/metrics/data-model/

**Comment by R-omk** [comment]
Also OpenTelemetry  is the modern industry standard.

**Comment by DifferentialOrange** [comment]
> Please consider otlp metric, since OpenMetrics has a superset of Prometheus' types.
> 
> https://opentelemetry.io/docs/reference/specification/metrics/data-model/

Thank you for the advice! It seems like a good idea, but we need to study this more thoroughly. But for now it sees like a big rework, and for now we decided not to introduce any drastic changes if we don't need them for minimal viable product, so I think we return to it later, not a part of this ticket.

**Comment by DifferentialOrange** [comment]
### feature: configuration through box.cfg

There was an idea to configure metrics through `metrics` module cfg (similar to `log`), which sounds good. This way, everything related to business logic may be implemented in metrics module itself.

Let's consider `enable_default_metrics` a bit more. (Here and later, when I refer to "default" metrics, I use this word with the same meaning as in `metrics` package -- it's in-built metrics provided with the package. By using "all", I am assume that user never knows the full list of metrics, since if a new category was added, running the code `exclude = {all_metrics_in_v.X}` to disable all metrics won't have the same effect in the new version.) With this handle, you can
- enable all default metrics,
- enable some default metrics,
- enable all default metrics, except for `excluded`,
- disable some default metrics on the runtime.
We're missing one crucial thing: you cannot disable all metrics. In case of the startup, you can simply not run `enable_default_metrics`, but if was run at least once, the only way to disable all metrics is to mess with registry manually. Such asymmetry must me solved in new cfg.

So what's possible now? To enable all metrics, you pass `included = nil` or `included = {}` with  `excluded = nil` or `excluded = {}`.
To enable some metrics, you pass `included = {metrics1, metrics2}` with  `excluded = nil` or `excluded = {}`. To enable "all except for some" metrics, you pass `included = {}` with `excluded = {metrics3, metrics4}`. In the current concept there is no way to tell metrics "do not enable anything" (version-independent). I think we may use a bit of a dynamic language magic here.

### metrics.cfg{}/metrics.enable_default_metrics_v2 proposal

- We use the same approach with included/excluded to support all existing approaches (`exclude` is used in several project, maybe even more often that non-nil `include`).
- `included` is one of the following: `'all'`, a list of metrics (`{metric1, metric2}`) or `'none'`.
- `excluded` is a list of metrics (`{metric1, metric2}`).
- Default for `included` is `'all'`.
- Default for `excluded` is an empty list `{}`.
- We enable everything that is in `included`, excluding everything that is in `excluded` (if presents).

This approach nearly compatible with existing solution and provide us everything new we might need. The only thing that is incompatible in the proposal is that `included = {}` has the same meaning as `included = 'none'`, while the current behavior is `included = {}` has the same meaning as `included = 'all'`. It could easily be workarounded. But, in my opinion, using explicit `{}` (default value is `nil`) to denote `'all'` is confusing (and I'm not sure anyone doing so), so
- Passing explicit `included = {}` will have the same behavior as before (`included = 'all'`), but we may change it in the future.
The last one finishes the proposal: v2 can replace v1 without any changes for all valid arguments.

**Comment by DifferentialOrange** [comment]
## metrics.cfg{} proposal in examples

Each section is a clean start.

### default

```lua
box.cfg{}
```
or
```lua
metrics.cfg{}
```

**Behavior**: enable everything (if something is not supported, it's still enabled but no collectors/callbacks created).

### explicit enable

```lua
box.cfg{metrics = 'all'}
```
or
```lua
metrics.cfg{include = 'all'}
```

**Behavior**: enable everything (if something is not supported, it's still enabled but no collectors/callbacks created).

### disable metrics

```lua
box.cfg{metrics = 'none'}
```
or
```lua
metrics.cfg{include = 'none'}
```

### exclude

```lua
box.cfg{metrics_exclude = {'fiber', 'cpu'}}
```
or
```lua
metrics.cfg{exclude = {'fiber', 'cpu'}}
```

**Behavior**: enable everything, except for `'fiber'`, `'cpu'`.

### labels

```lua
box.cfg{metrics_labels = {alias = 'storage-1'}}
```
or
```lua
metrics.cfg{labels = {alias = 'storage-1'}}
```

**Behavior**: each metric will contain `alias = 'storage-1'` label on export/collect (global labels behavior).

### backward compatibility (questionable)

```lua
box.cfg{metrics = {}}
```
or
```lua
metrics.cfg{include = {}}
```

**Behavior**: enable everything (if something is not supported, it's still enabled but no collectors/callbacks created).

**Comment by Mons** [comment]
I would suggest:

```
box.cfg{ mertics = { include = 'all' }}
```
and make it equivalent
```
metrics.cfg{ include = 'all' }
```

i.e. make the metrics as a module in the box and forward everything that is passed there directly to metrics.
also it would be possible to call it separately, as, log, for example,

**Comment by DifferentialOrange** [comment]
Continuation of https://github.com/tarantool/tarantool/issues/7725#issuecomment-1385243726

## Road to useful collect

`metrics.collect()` was already improved for the https://github.com/tarantool/tarantool/issues/8192. But there are still things we need to do for the flight recorder.

It is planned that `metrics.collect` result could be used to compute aggregates like rps, max, min, average, etc. What we need to improve to make it possible and convenient? Let's start with discussing possible aggregates.

Since the nature of the metric is related to the collector, aggregates corresponds to the collector type.

### Expected aggregates.

**Collector** stores non-decreasing value, so **value per second** aka numerical derivative (for example, requests per second) makes sense for it. On the other hand, computing min or max doesn't make any sense since min is always 0 and max is the last value if there wasn't any resets for a lifetime (and it's quite common).

**Gauge** stores arbitrary value, so **min** and **max** may be useful (but not guaranteed to, it depends on metric). Value per second mostly doesn't make sense.

**Histogram** has sum, count and buckets. For count and sum, separately, you may compute **value per second** since they are counters in nature. (It's often useful for count: when you store the time of HTTP request execution, derivative of count is RPS; sum derivative often is not that useful, but may be.) By using count and sum together, you may compute things like **average** (both overall and with aging). By using buckets, you may compute **quantiles**.

**Summary** has sum, count and quantiles. Sum and count are exactly the same as in histogram, so we have **value per second** and **average** (both overall and with aging). quantiles are already precomputed aggregates, so you may take them as is.

So what we should provide in new `metrics.collect`?

### Map instead of array

Collect result is an array. Since it is a collection of observation, it sounds expected.

To compute any historical aggregate (value per second, min, max) we need at least two observation collections -- for time1 and time2 moments. Let's say we had already chosen a metric in time1 collection. Next we need to get a corresponding metric -- metric with the same name, of the same type with the same set of labels. Moreover, it would be nice to ignore global labels in labels comparison. Even if we ignore the latter one, you'll need to find an item in the array, which is `O(N)` and sounds dissatisfying. How to solve this?

Actually, every collector has a unique identifier built from its name and type, and every observation in the collector has its unique identifier built from its labels (ignoring the global ones). We may simple expose them and return a map instead of array, so you may use the key of the observation from time1 to get corresponding observation in time2.

### Provide collector kind in observation

We may provide additional info in observation, like `kind = 'counter'`. It is a bit unclear how to better deal with composite collectors. I'm thinking about something like `kind = 'summary', subkind = 'count'`.

### Provide links between metrics

To compute an average or a quantile, you need to find a corresponding sum for each count (it's always there). To not search through the whole array/map again, we may provide something like `related_observations = {<table pointer>}` or ``related_observations = { 'obs_key' }`.
