### ISSUE TITLE
GDB tooling: explore non-current fiber

### ISSUE THREAD

**Issue by elhimov** [tarantool/tarantool#7733]
- A way to look into a non-current fiber.
  - List all fibers of given thread (may be called `info fibers` similarly to `info threads`, alternative: `tt-cord`).
  - 'Switch' to another fiber to use `bt`/`frame`/`list` and so on (may be called `fiber N` or `tt-fiber N` similarly to `thread N`).
  - If such 'switch' is hard to implement, provide some analogues for `bt`/`frame`/`list` that works for given fiber.

**Comment by CuriousGeorgiy** [comment]
Might be worth looking at how it is done in [folly](https://github.com/facebook/folly/blob/85465c8ef64be895bd15a0a315f3698fb5dc685f/folly/fibers/scripts/gdb.py#L191-L285).

**Comment by elhimov** [comment]
> Might be worth looking at how this is done in [folly](https://github.com/facebook/folly/blob/85465c8ef64be895bd15a0a315f3698fb5dc685f/folly/fibers/scripts/gdb.py#L191-L285): they use the [boost::context](https://github.com/boostorg/context) fiber implementation which is pretty much the same as libcoro.

Yes, it helped. Thanks a lot.
