### ISSUE TITLE
leave interactive mode by ctrl-c (always)

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#774]
ctrl-c is exit.

**Comment by zloidemon** [comment]
I think is not good idea, more well use like ipython:

```
KeyboardInterrupt
>>>
KeyboardInterrupt
>>>
KeyboardInterrupt
>>>
KeyboardInterrupt
>>> print "123"
123
>>> print "123"
KeyboardInterrupt
>>>
```

ctrl+c is clean line and not close shell. To close shell more good way to use ctrl+d.
If it's possible to good way add that in configuration ~/.tarantool than use that always.

**Comment by kostja** [comment]
Veniamin, ctrl-d works just as well. ctrl-c is SIGINT.
