### ISSUE TITLE
Adopt LuaJIT machinery for unwinding exceptions raised while trace execution

### ISSUE THREAD

**Issue by igormunkin** [tarantool/tarantool#7745]
## Description
While we were arguing about SMARTness and estimations for tarantool/tarantool#5630, Mike Pall have already introduced internal exceptions unwinding on JIT traces within LuaJIT/LuaJIT@a32aead. and In scope of this epic we're going to adopt [this patch](https://github.com/LuaJIT/LuaJIT/commit/a32aeadc6878305658fb3939830e6abaef587e40) and all its follow-ups from [vanilla LuaJIT](https://github.com/LuaJIT/LuaJIT).

## List of the patches to be adopted implementing the epic:
- [x] LuaJIT/LuaJIT@a32aead
- [x] LuaJIT/LuaJIT@d4a554d
- [x] LuaJIT/LuaJIT@b9d5239
- [x] LuaJIT/LuaJIT@66563bd
- [x] LuaJIT/LuaJIT@e957737
- [x] LuaJIT/LuaJIT@27ee3bc
- [x] LuaJIT/LuaJIT@bfcb74e
- [x] LuaJIT/LuaJIT@78350a2
- [x] LuaJIT/LuaJIT@421c4c7
- [x] LuaJIT/LuaJIT@de77205 
- [x] LuaJIT/LuaJIT@be251d9

**Comment by Mons** [comment]
Fow now it is ok, if it will work only on Linux (x64 & arm)
OSX could be postponed
