### ISSUE TITLE
Phantom read after `get`s from different indexes

### ISSUE THREAD

**Issue by CuriousGeorgiy** [tarantool/tarantool#7837]
**Steps to reproduce**

```lua
os.execute('rm -rf *.snap *.xlog *.vylog 512')

local json = require('json')
local log = require('log')
local txn_proxy = require('txn_proxy')

box.cfg{memtx_use_mvcc_engine = true}

box.schema.space.create('s')
box.space.s:create_index('pk', {parts = {{1}, {2}}})
box.space.s:create_index('sk1', {parts = {{3}}})

local tx1 = txn_proxy:new()
local tx2 = txn_proxy:new()
local tx3 = txn_proxy:new()

tx1('box.begin()')
tx2('box.begin()')
tx3('box.begin()')

tx1('box.space.s:replace{0, 1, 2}')

tx2('box.space.s.index[1]:get{2}')
tx2('box.space.s:get{0, 1}')

tx3('box.space.s:insert{0, 2, 2}')

tx1('box.rollback()')

box.space.s:insert{0, 1, 3}

log.info(json.encode(tx2('box.space.s:select({}, {fullscan = true})')))

os.exit()
```

**Actual behavior**

```console
2022-10-23 14:36:33.256 [78495] main/103/repro.lua I> [[[0,1,3]]]
```

**Expected behavior**

```console
2022-10-23 14:36:33.256 [78495] main/103/repro.lua I> [[]]
```

**Comment by locker** [comment]
I don't see any phantom reads here: [0,1,3] is committed and confirmed before tx2 attempts to read it; since this is the first time tx2 attempts to read these keys, it should see it. Vinyl behavior in this test is exactly the same.

**Comment by CuriousGeorgiy** [comment]
@locker thanks for noticing! I made a typo during simplifiying the reproducer: `tx2` is also supposed to read {0, 1} from primary index.

**Comment by CuriousGeorgiy** [comment]
@locker thanks for noticing! I made a typo during simplifiying the reproducer: `tx2` is also supposed to read {0, 1} from primary index.

**Comment by CuriousGeorgiy** [comment]
Actually, this turns out to be a duplicate of #7828 (it's one bug from different angles).

**Comment by CuriousGeorgiy** [comment]
Actually, this turns out to be a duplicate of https://github.com/tarantool/tarantool/issues/7828 (it's one bug from different angles).
