### ISSUE TITLE
recovery test

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#784]
In a loop:
 - write a record or two into a memtx space or two, maybe wrapped into a transaction, maybe not
 - write a record or two into sophia sophia space or a couple of spaces, maybe within a context of transaction, maybe not
 - (maybe) take snapshot
 - crash the server
 - start the server and check that the data is consistent and present in both engines

**Comment by Sulverus** [comment]
Done. Please review

**Comment by rtsisyk** [comment]
Test works for me.

**Comment by Sulverus** [comment]
Reproduced in Tarantool 1.6.4-581-gf89c1ce

**Comment by Sulverus** [comment]
Not reproduced in Tarantool 1.6.5-29-g69198fd in release mode
