### ISSUE TITLE
Stream http.client support

### ISSUE THREAD

**Issue by oleg-jukovec** [tarantool/tarantool#7845]
**Is your feature request related to a problem? Please describe.**

We were unable to communicate [with a third-party API using http.client](https://github.com/tarantool/etcd-client/issues/2#issuecomment-1288860236). It requires not a regular POST-request workflow (open a connection, send a request, receive a response, close the connection), but a kind of a stream HTTP-request (open a connection, send/receive data many times, close the connection).

**Describe the solution you'd like**

The cURL library has options [CURLOPT_WRITEFUNCTION](https://curl.se/libcurl/c/CURLOPT_WRITEFUNCTION.html) and [CURLOPT_READFUNCTION](https://curl.se/libcurl/c/CURLOPT_READFUNCTION.html). With that callbacks you can control both output and input data streams. If there was a way to set up these callbacks. It would help to solve the problem.

I would suggest to extend the [http.client](https://www.tarantool.io/ru/doc/latest/reference/reference_lua/http/) API. We could add a `stream` field for a request options:

```Lua
local response = client:post(url, first_data_chunk or nil, {stream = true}
```

In this case, the response will not have a `body` field, but two methods for `read` and `write` streamed data:
```Lua
response:write(data_chunk)
local data_chunk = response:read()
```
and the `close` method to finish the request:
```Lua
response:close()
```

Also it may have the HTTP-header "Transfer-Encoding: chunked" instread of `Content-Length: ХХ`.

In all other things it could be a response object with the same fields and settings.

**Describe alternatives you've considered**

We could act in a cURL way and add posibility to a user specify write/read function callbacks:

```Lua
local response = client:post(url, first_data_chunk or nil, {
     read_callback = read_callback_function,
     write_callback = write_callback_function,
})
```

**Additional context**

[gRPC -> REST implementation](https://github.com/grpc-ecosystem/grpc-gateway/blob/master/runtime/handler.go#L18-L99) Used headers:
```
Transfer-Encoding: chunked
Content-Type: application/json
```
[See also.](https://hackmd.io/PjlwhbzuQR6x9nCM0MIHUQ?view#Long-response-chunked)

**Definition of Done**

A user can send and receive data via a streamed HTTP-request.

**Comment by oleg-jukovec** [comment]
I would split the task into two parts:

## 1. Support HTTP-header `Transfer-Encoding: chunked`

We need to add support for auto-format the sent data into one chunk and automatically combining the received data from the chunks for the current implementation.

See:

1. https://en.wikipedia.org/wiki/Chunked_transfer_encoding
2. https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Transfer-Encoding

And make sure it works correctly with (`Transfer-Encoding: chunked` + `Content-Type: application/json`):

https://github.com/tarantool/tarantool/issues/6833
https://www.notion.so/tarantool/HTTP-body-531cfa0f4edb4012ba73b4fa14493864

At the same time, do not touch regular-manually created requests/response.body ? Or not?

## 2. Support chunked data send/receive:

```Lua
-- It adds header `Transfer-Encoding: chunked` instead of `Content-Length: ХХ`.
-- The response does not have `body` field and `decode()` method.
local response = client:post(url, first_data_chunk or nil, {chunked = true})
-- The same rules as in the RFC:
-- https://www.notion.so/tarantool/HTTP-body-531cfa0f4edb4012ba73b4fa14493864
response:write(data)
-- Raw-read of a chunk of data.
local chunk = response:read()
-- Decoded read of a chunk of data, the same rules as in the RFC:
-- https://www.notion.so/tarantool/HTTP-body-531cfa0f4edb4012ba73b4fa14493864
local decoded_chunk = response:read_decode()
-- Closes the response.
response:close()
```

**Comment by oleg-jukovec** [comment]
Addition notes after discussion with @Mons @unera @Totktonada @LeonidVas :

1. We need timeouts for read/write. Default is less than a minute, maybe 5-10 second or 30-60 seconds.
2. It would be better to have read() as [socket.read](https://www.tarantool.io/en/doc/latest/reference/reference_lua/socket/#socket-read)
3. We don't need access to the original chunks, as they can be split randomly at the transport level. It is not necessarily than HTTP chunk is a logical complete chunk of data.

As a result, in action it will look like this:

```Lua
local io = httpc:post(url, first_data_chunk or nil, {chunked = true})
local readed
while readed = io:read('\r\n', {timeout = 10}) do
    local decoded = json.decode(readed)
    if condition(decoded) then
        io:write()
    end
    if condition(decoded) then
        io:close()
    end
end
```

**Comment by Mons** [comment]
1. read timeout and write timeout should be different.
2. read process and write process could occur in separate fibers. in the example above there are read starvation by possible long writes. more complex example follows.

```lua
--[[
From the perspective of "client" it's main purpose is to receive response.
So, we left in the "main flow" reading response and put out to separate fiber writer.
If writes may occur slowly, then we can adjust backpressure with length of a channel
]]

local io = httpc:post(url, first_data_chunk or nil, {chunked = true})

local write_chan = fiber.channel()
fiber.new(function()
    while io and write_chan:readable() do
        local data = write_chan:get()
        if data then
            io:write(data, {timeout = 20})
        end
    end
end)

local recvdata
while recvdata = io:read('\r\n', {timeout = 10}) do
    local decoded = json.decode(recvdata)
    if condition(decoded) then
        write_chan:put( data )
    end
    if condition(decoded) then
        io:close()
    end
end
write_chan:close()
```
