### ISSUE TITLE
Segmentation fault code: SEGV_MAPERR while sending sql query to tnt using jdbc

### ISSUE THREAD

**Issue by mountgnom** [tarantool/tarantool#7853]
**Bug description**

```
Segmentation fault
  code: SEGV_MAPERR
  addr: 0x100000000018
  context: 0x7ffffac25880
  siginfo: 0x7ffffac259b0
  rax      0x100000000008     17592186044424
  rbx      0x7f1d6ce473a0     139764357690272
  rcx      0x5                5
  rdx      0x2d               45
  rsi      0x7f1d6ce47000     139764357689344
  rdi      0x7f1d6ce47010     139764357689360
  rsp      0x7ffffac25cd8     140737400429784
  rbp      0x7f1d6ce473a0     139764357690272
  r8       0x5                5
  r9       0x7f1d6ce472e0     139764357690080
  r10      0x1d               29
  r11      0x246              582
  r12      0x7f1d6cd4ebb0     139764356672432
  r13      0x7f1d6ce472e0     139764357690080
  r14      0x7f1d6ce47370     139764357690224
  r15      0x1                1
  rip      0x7f1d6fb72895     139764405053589
  eflags   0x10202            66050
  cs       0x33               51
  gs       0x0                0
  fs       0x0                0
  cr2      0x100000000018     17592186044440
  err      0x4                4
  oldmask  0x0                0
  trapno   0xe                14
Current time: 1666165882
Please file a bug at http://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed, 
this may fail as well
#1  0x55d89e9eb9bf in crash_signal_cb+191
#2  0x7f1d6fb95c8a in sigwaitinfo+8
```

* OS: Linux
* OS Version: CentOS Linux release 7.9.2009 (Core)
* Architecture: amd64

Tarantool version:  2.10.3-4-g13a839e85

**Steps to reproduce**
We run in docker containers  image tarantool/tarantool:2.10 and java-application. Tarantool instance without catridge, only box.cfg and one fiber, which every 20 minutes fill space with about 500 000 rows. Sometimes when we create a JDBC connection and execute query like
`SqlRowSet resolutionsRowSet = jdbcTemplateTarantool.queryForRowSet("SELECT * FROM <spacename> where author = '1'");`
... we receive that error in logs and Tarantool restarts. It would be obvious to receive errors when spase is filling up by fiber, but it happens even when fiber's sleeping. 

app.lua and dockerfile: [project files.zip](https://github.com/tarantool/tarantool/files/9878586/project.files.zip)

logs: [_kipr-tarantool_logs(5).txt](https://github.com/tarantool/tarantool/files/9878603/_kipr-tarantool_logs.5.txt)

**Comment by Totktonada** [comment]
We have no your data, so it is hard to reproduce the problem. There are two possible ways to proceed:

1. Collect a tarball with the core dump and all related libraries. The [tarabrt.sh](https://github.com/tarantool/tarantool/blob/master/tools/tarabrt.sh) tool may help with it.
2. Share a full reproducer: say, a snapshot + a script that leads to the crash. You can share your data privately to me (alexander.turenko@tarantool.org).

Now we have no even a full backtrace, so it is unlikely we'll find the root of the problem.

**Comment by kyukhin** [comment]
No feedback for 3+ wws. Feel free to reopen.

**Comment by mountgnom** [comment]
@kyukhin , sorry for leaving this comment without reply...  just read and forgot about it.  **Problem was solved** after refactoring of lua script which allow to avoid writing and reading with from one table simultaneously. To be honest i still have no idea why it happened, but i haven't seen it since i changed the script. 
 
updated script:  [app.zip](https://github.com/tarantool/tarantool/files/10464687/app.zip)
