### ISSUE TITLE
Unable to check if index uses sequence through net.box

### ISSUE THREAD

**Issue by DifferentialOrange** [tarantool/tarantool#7858]
**Bug description**

net.box connection object does not provide any info about using sequence.

Related to https://github.com/tarantool/crud/issues/328

* OS: Linux
* OS Version: Ubuntu 22.04
* Architecture: amd64

Tarantool 2.10.0-beta2-283-gb56e012bc

**Steps to reproduce**

`init.lua` script:

```lua
local log = require('log')

box.cfg{listen = 3301}

box.schema.user.grant('guest', 'read,write,execute', 'universe')

local sequence_space = box.schema.space.create('space', {
    format = {
        {name = 'id', type = 'unsigned', is_nullable = false},
    },
})

box.schema.sequence.create('id')

sequence_space:create_index('id', {
    parts = { {field = 'id'} },
    unique = true,
    sequence = 'id',
})

log.info("Index with sequence: %s", box.space['space'].index['id'].sequence_id ~= nil)
```

`remote.lua` script:

```lua
local log = require('log')
local net_box = require('net.box')

local conn = net_box.connect(3301)

log.info("Index with sequence: %s", conn.space['space'].index['id'].sequence_id ~= nil)
```

Run `tarantool init.lua` in one console.
Run `tarantool remote.lua` in another console.

**Actual behavior**

Server (`init.lua`) output:
```
Index with sequence: true
```

Client (`remote.lua`) output:
```
Index with sequence: false
```

**Expected behavior**

Server (`init.lua`) output:
```
Index with sequence: true
```

Client (`remote.lua`) output:
```
Index with sequence: true
```

**Comment by locker** [comment]
> @locker , maybe you can help to clarify this one?

Sequence support wasn't implemented in net.box (i.e. sequences created on the server aren't fetched by net.box connection on schema reload). This can and should be fixed. As a workaround, you can check `conn.space._space_sequence:get(space_id).sequence_id`, but this would only work if the caller has access to `_space_sequence` (unfortunately, we don't have `_vspace_sequence` as of now).

**Comment by locker** [comment]
> > As a workaround, you can check `conn.space._space_sequence:get(space_id).sequence_id`, but this would only work if the caller has access to `_space_sequence` (unfortunately, we don't have `_vspace_sequence` as of now).
> 
> As far as I understand, each `get` call is processed over the network in contrary to `conn.space['space'].index['id']` schema checkup with cached info, isn't it?

Yes, but you can register a [trigger](https://www.tarantool.io/en/doc/latest/reference/reference_lua/net_box/#net-box-on-schema-reload) to cache it on schema reload.
