### ISSUE TITLE
Export IPROTO constants and features to Lua

### ISSUE THREAD

**Issue by CuriousGeorgiy** [tarantool/tarantool#7894]
# Namespaces

## `box.iproto`
New namespace for working with the network subsystem of **Tarantool**.

## `box.iproto.feature`
New namespace for working with features of **IPROTO** protocol.

# IPROTO constants

Export **IPROTO** constants from [`src/box/iproto_constants.h`](https://github.com/tarantool/tarantool/blob/master/src/box/iproto_constants.h) in upper case without `IPROTO_` prefix.
```lua
box.iproto.key.REQUEST_TYPE = 0
box.iproto.key.SYNC = 1
box.iproto.REPLICA_ID = 2
-- ...
box.iproto.type.OK = 0
box.iproto.type.SELECT = 1
box.iproto.type.INSERT = 2
-- ...
```

**IPROTO** constants related to flags, metadata, request keys and type, the **RAFT** protocol are located in corresponding subnamespaces without prefixes:
```lua
box.iproto.flag.COMMIT = 1
-- ...
box.iproto.key.SYNC = 1
-- ...
box.iproto.type.SELECT = 1
-- ...
box.iproto.metadata_key.IS_NULLABLE = 3
-- ...
box.iproto.ballot.VCLOCK = 2
-- ...
box.iproto.raft.TERM = 0
-- ...
```

# IPROTO features

Export the server's **IPROTO** protocol version (see also [`IPROTO_CURRENT_VERSION`](https://github.com/tarantool/tarantool/blob/dec0e0221e183fa972efa65bb0fb658112f2196f/src/box/iproto_features.h#L58-L64)).
```lua
box.iproto.protocol_version = 3
```

Export the set of **IPROTO** protocol features the server supports (see also [`src/box/iproto_features.h`](https://github.com/tarantool/tarantool/blob/master/src/box/iproto_features.h) and [`iproto_features_resolve`](https://github.com/tarantool/tarantool/blob/dec0e0221e183fa972efa65bb0fb658112f2196f/src/box/lua/net_box.lua#L93-L105)).
```lua
box.iproto.protocol_features = {
    streams = true,
    transactions = true,
    error_extension = true,
    watchers = true,
} 
```

Export the mapping of **IPROTO** protocol features the server supports from a lowercase feature name without the `IPROTO_FEATURE` prefix to its code.
```lua
box.iproto.feature.streams = 0
box.iproto.feature.transactions = 1
box.iproto.feature.error_extension = 2
box.iproto.feature.watchers = 3
```

**Comment by Korablev77** [comment]
Looks like duplicate https://github.com/tarantool/tarantool/issues/7103

**Comment by CuriousGeorgiy** [comment]
@Korablev77 your issue is more about code health and deduplication, while this one does not touch this problem.
