### ISSUE TITLE
Export `box_schema_version` to public API and Lua

### ISSUE THREAD

**Issue by CuriousGeorgiy** [tarantool/tarantool#7904]
# Problem
`box_schema_version` symbol is currently exposed via `exports` and `box.internal.schema_version`, but it is not part of the public API.

One of the use cases is #7901: **IPROTO** request handlers need to provide the schema version in their replies (see also [`IPROTO_SCHEMA_VERSION`](https://www.tarantool.io/en/doc/latest/dev_guide/internals/iproto/keys/#iproto-schema-version) and example below).

# Solution

## Interface
Export the server's schema version to C and Lua.

### C
```C
uint32_t
box_schema_version(void);
```

### Lua
```lua
box.info.schema_version
-- 81
```

The returned number is the version of the database schema, an unsigned number that goes up when
there is a major change in the schema, i.e., on DDL operations (see also (see also [`IPROTO_SCHEMA_VERSION`](https://www.tarantool.io/en/doc/latest/dev_guide/internals/iproto/keys/#iproto-schema-version)).

## Example
Mimicking an **IPROTO** response (see #7897 for `box.iproto.send`):
```lua
box.iproto.send(sid, {
    request_type = box.iproto.OK,
    sync = 10, 
    schema_version = box.info.schema_version,
}, {
    data = 1,
})
```

**Comment by Totktonada** [comment]
> # Problem
> `box_schema_version` symbol is currently exposed via `exports`, but it is not part of the public API.

It is not a problem that an internal thing is internal. The issue has no user scenario and has no a user problem.

It also has no public API description. There is a function prototype, but there is no word what it should return.

* When exactly the return value is changed (i.e. what is DDL)? Can the meaning of DDL be changed later and how?
* What the function should return in a transaction that changes the database schema?
* What the function should return after a rolled back DDL?
* What the function should return before `box.cfg()`?
* What the function should return during recovery?

It is excerpt of my questions about this API from the past discussions:

* https://github.com/tarantool/tarantool/discussions/6800
* https://github.com/tarantool/tarantool/issues/6544
* https://github.com/tarantool/tarantool/issues/6545

Let's join to existing discussions if your use case is similar to mine one. And, in any case, describe your use case and your problem.

*In fact, it is very common for 'obvious' issues of the 'expose an internal thing' kind. Latest one that I remember is [this](https://github.com/tarantool/tarantool/pull/7407#issuecomment-1183750102) one. It was completely reconsidered during discussion about the user problem.*

**Comment by CuriousGeorgiy** [comment]
Please take look at the appropriate design document: https://www.notion.so/tarantool/box-iproto-override-44935a6ac7e04fb5a2c81ca713ed1bce and leave your comments there.

**Comment by Totktonada** [comment]
> @Totktonada, please take a look at the appropriate [design document](https://www.notion.so/tarantool/box-iproto-override-44935a6ac7e04fb5a2c81ca713ed1bce) and leave comments regarding your concerns there.

It has no answers to the five API questions above. Okay, I linked the comment above to the design document, but it is just for you -- if you don't want to track it, just close.

> In short, the exposure of this function is needed for **IPROTO** request handlers overriding (handlers need to provide the schema version in their replies).

I'll cite the motivating example from the design document:

```lua
box.iproto.send(sid, {
    request_type = box.iproto.OK,
    sync = 10, 
    schema_version = box.schema_version(),
}, {
    data = 1,
})
```

It more or less answers about the use case: the function is needed to imitate the native iproto response. So you can investigate how it works in iproto and decude answers to the API questions. Whether you should? It seems meaningful for me, but it is the question for managers.

> Your questions are not answered by the existing documentation of [`IPROTO_SCHEMA_VERSION`](https://www.tarantool.io/en/doc/latest/dev_guide/internals/iproto/keys/#iproto-schema-version), so I don't see how this case differs anyhow.

Those are the same and both look flawed now (after years of changes in DDL, transactions, yields during recovery and database schema meaning in presence of sharding). Your issue just highlighted the tech debt to me and I remembered the past discussions.

It would be sad to expose the function without taking care to its design, but I'm not the person who will fight here. Let's consider my comments as an opinion about what should be done about the public API.

**Comment by unera** [comment]
> When exactly the return value is changed (i.e. what is DDL)? Can the meaning of DDL be changed later and how?

When the schema is changed :)
New call will return new value.

> What the function should return in a transaction that changes the database schema?
old (previous) value

> What the function should return after a rolled back DDL?
old (previous) value

> What the function should return before box.cfg()?
0

> What the function should return during recovery?
0

**Comment by alyapunov** [comment]
> It is already:

I think that `internal` should not be a part of public API, so no application should rely on it.

**Comment by Totktonada** [comment]
>> When exactly the return value is changed (i.e. what is DDL)?
>
> When the schema is changed :)

I'm sad to see that a person with high influence on design decisions prefers to just kidding around such gray API zones. We have no precise definition of DDL in the documentation, a user needs to guess or try-and-trial.

How, for example, one can deduce that adding a new space trigger is not a DDL, but adding a new function entry is a DDL?

Or, say, more general and more practical question: how one can deduce that changing of a sharding key/sharding function is not a DDL?

Let's continue kidding on me, that definitely increases confidence about your proposals.

>> Can the meaning of DDL be changed later and how?

Any proposal/decision here?

Can I expect that a successful `box.schema.func.create()` always bumps a schema version? Can I expect that a successful `<space_object>:on_replace(<...>)` never bumps the schema version?

What should I expect from adding an `on_commit` or an `on_rollback` trigger? What about `box.once`?

How about space format changes or, say, `field_count` changes? Or an `is_sync` change?

What about adding a new constraint, relation or a sequence? What if a new user or role is added? If a permissions of a user or role is changed? If a password of a user is changed?

All those questions look obvious for a user? I promise, they're not.

----

Regarding other proposals about the behavior: without a justification they look arbitrary.

**Comment by Totktonada** [comment]
@alyapunov I agree that leaving things explicitly unspecified is acceptable way to proceed with this API.

I'm okay to leave further work on schema versioning/reloading out of scope of this issue. Maybe even reconsider the whole approach to something subscription based. Not here, of course.

**Comment by alyapunov** [comment]
I would also mention that any person in this discussion wants to make tarantool better, in different aspects and manners though; and any has different but proven expertise. So we should respect and investigate points of each other.

**Comment by CuriousGeorgiy** [comment]
So, as I emphasized from the beginning:

> Your questions are not addressed by the existing documentation of [IPROTO_SCHEMA_VERSION](https://www.tarantool.io/en/doc/latest/dev_guide/internals/iproto/keys/#iproto-schema-version), so I don't understand what value they can bring to users.

I assumed it’s obvious this thing is meant to be a magic number, the only thing the client having to do with it is tracking its updates and reacting accordingly - we didn’t specify anything more, so why should the user be overthinking it. 

I really don’t understand the purpose of this hit on me (I’m taking it personal, TBH) in scope of this 1SP issue, the sole purpose of which was enabling the opportunity to fill **IPROTO** headers in request handlers.

**Comment by unera** [comment]
> I'm sad to see that a person with high influence on design decisions prefers to just kidding around such gray API zones. We have no precise definition of DDL in the documentation, a user needs to guess or try-and-trial.

The ticket isn't about the behaviour of the `schema_version` variable. 
The behaviour was provided years ago. Too many connectors rely on this behaviour. So I think that we shouldn't do any changes here.

So, your question was similar to rhetorical (for me), that's why I answered so.

**Comment by CuriousGeorgiy** [comment]
To sum up, this ticket is not about the behaviour of schema version number, so it remains unspecified with its monotonic growth being the only requirement held.
