### ISSUE TITLE
System space `_space` strange behavior with custom before_replace trigger

### ISSUE THREAD

**Issue by drewdzzz** [tarantool/tarantool#7909]
This is what happens in `_space`:
```lua
box.cfg{}
box.space._space:before_replace(function(old, new)
    return nil
end)
box.schema.create_space('test')
tarantool> box.schema.create_space('test')
---
- null
- created
```
AFAIU this function is not supposed to return null ever. And what is "created"?

Bug is found by @Gerold103

**Comment by kyukhin** [comment]
Here's mentioning that returning of nil value leads to tuple not inserted https://www.tarantool.io/en/doc/latest/reference/reference_lua/box_space/before_replace/

**Comment by Mons** [comment]
Not a bug.

Function space create contains the following code:
```lua
box.schema.space.create = function(name, options)
    -- snip
    return box.space[id], "created"
end
```

According to the trigger, insert info space _space was overriden with delete.
So, everything is correct
