### ISSUE TITLE
Investigate system spaces for bugs with custom `before_replace` triggers

### ISSUE THREAD

**Issue by drewdzzz** [tarantool/tarantool#7910]
Thanks to the efforts of @Gerold103, we have found several bugs and even crashes when we set `before_replace` triggers on system spaces (#7909, #7846). However, ban triggers like `before_replace` on system spaces is a bad option - advanced users of tarantool uses this feature, so we should make system spaces with such triggers work properly.

**Comment by kyukhin** [comment]
Not much useful information in the issue. If you'll encounter more bugs w.r.t. triggers on sys spaces -- feel free to open new issue.
