### ISSUE TITLE
Recovery: force recovery should try to recover mixed transactions from WAL

### ISSUE THREAD

**Issue by elhimov** [tarantool/tarantool#7932]
Transaction boundaries in WAL were introduced in 2.1.2 (872d6f1), but replication applier started to apply transaction atomically only in 2.2.1(e94ba2e), so within this range it is possible that transactions are mixed in WAL. There was no problem with them until 2.8.1 because recovering process was still working row-by-row, but in 2.8.1 (9311113) it became transactional as well so starting from 2.8.1 tarantool fails to handle mixed transactions from WAL.

Recently this problem arose [here](https://jira.vk.team/browse/TNT-656)

I find it difficult to provide 100% reproducer here, but at least you need:

1. Setup full mesh cluster of master replicas (the more the better) of any version from the range [2.1.2, 2.2.0]
2. Write various multi-component transactions simultaneously on different replicas
3. Upgrade one instance to 2.8.1 or later (w/o snapshots). If mixed transactions have been produced in WAL at step 2, upgraded instance will fail to recover from WAL 

Mixed transactions is obviously the one of unexpected scenarios in modern tarantool, so we should not handle it in normal mode, and we take care of it only in force recovery mode. But current 'force recovery' treats all the rows of the unexpected transaction as unexpected and thus just skips the entire transaction row-by-row. However it seems we have enough information in this case to handle it more data-friendly, so I'd suggest to improve force recovery to avoid data loss, or at least try to avoid

**Comment by sergepetrenko** [comment]
Decided with @sergos this shouldn't go to 2.10, because it's too big of a change.
Still pushing to 2.11 to fix the possible problems with migration from 2.2 to 2.11.
