### ISSUE TITLE
Fiber region memory leaks on invalid input to DML function

### ISSUE THREAD

**Issue by locker** [tarantool/tarantool#7939]
Reproduced with Tarantool 2.11.0-entrypoint-697-gbab289cd88a7. Tarantool 2.10 is affected as well.

Passing data that can't be encoded in MsgPack to a DML function may result in a fiber region memory leak:

```Lua
local fiber = require('fiber')

function print_mem_used()
    print('Mem used: ' .. fiber.info()[fiber.self().id()].memory.used)
end

box.cfg{log_level = 'warn'}
box.schema.create_space('test')
box.space.test:create_index('pk')

print_mem_used()
pcall(box.space.test.insert, box.space.test,
      {2, string.rep('x', 1024 * 1024), require('buffer').ibuf()})
print_mem_used()

os.exit(0)
```

Output:

```
Mem used: 0
Mem used: 2
```

This happens, because [`lbox_encode_tuple_on_gc`](https://github.com/tarantool/tarantool/blob/bab289cd88a7f76bd1334853063066c43591fabe/src/box/lua/misc.cc#L52) doesn't clean up the region on failure.

This is a minor bug, because the leaked memory will be freed on a transaction commit, but it blocks #5665.

**Comment by locker** [comment]
Not critical => may be fixed later, as it only happens on invalid user input. The issue is difficult to fix, because `lbox_encode_tuple_on_gc` throws a Lua error, and using `lua_cpcall` there may affect performance.

**Comment by locker** [comment]
Note, there are probably a few other places that have potential leaks like that. We need to check all usages of `luamp_encode` in the scope of this issue.

**Comment by CuriousGeorgiy** [comment]
I suggest we also track potential memory leaks caused by `mpstream` API used with `luamp_error`.

**Comment by Totktonada** [comment]
> Not critical => may be fixed later, as it only happens on invalid user input. The issue is difficult to fix, because `lbox_encode_tuple_on_gc` throws a Lua error, and using `lua_cpcall` there may affect performance.

There are non-raising `luaT_tuple_encode()` (it writes to a region) and `luaT_tuple_encode_on_lua_ibuf()`. See ab95ddaacaac30339ff3e5609adb08efdc6c9b62 and db766c5262f3dfb81c3076c31cdc83ff6c32ff53.

**Comment by nshy** [comment]
> I suggest we also track potential memory leaks caused by mpstream API used with luamp_error in scope of this issue.

Forked to #8679
