### ISSUE TITLE
Select FFI does not work on M1

### ISSUE THREAD

**Issue by drewdzzz** [tarantool/tarantool#7946]
If we call select on memtx space (or another function that calls `select_ffi` under the hood) on M1, it will throw an error `NYI: cannot call this C function (yet)`, just try this simple script:
```lua
box.cfg{}
s = box.schema.create_space('test')
s:create_index('pk')
s:replace{0, 0}
s:select{}
```
The snippet from `schema.lua` that throws an error:
```lua
nok = builtin.box_select(index.space_id, index.id, iterator, offset, limit,
                         key, key_end, iterator_pos, iterator_pos_end,
                         fetch_pos, port) ~= 0
``` 
The problem is in LuaJIT: https://github.com/LuaJIT/LuaJIT/issues/205
We can fix the issue or simply create a wrapper with reordered arguments for `box_select`.

**Comment by Mons** [comment]
Could you, please, provide reproducer snippet for pure Tarantool, that didn't work on M1?

**Comment by drewdzzz** [comment]
Added a reproducer to the issue description.
