### ISSUE TITLE
Invalid msgpack error is not useful enough

### ISSUE THREAD

**Issue by DifferentialOrange** [tarantool/tarantool#7968]
**Is your feature request related to a problem? Please describe.**

`invalid MsgPack` error response covers a lot of cases, including those not related to MessagePack.

For example, while I was developing MP_ERROR encoding for tarantool/go-tarantool, I have caught this error with the following payload:
```lua
tarantool> bytes = string.char(130, 39, 170, 114, 101, 116, 117, 114, 110, 32, 46, 46, 46, 33, 145, 199, 74, 3, 129, 0, 145, 134, 0, 171, 67, 108, 105, 101, 110, 116, 69, 114, 114, 111, 114, 1, 170, 99, 111, 110, 102, 105, 103, 46, 108, 117, 97, 2, 211, 0, 0, 0, 0, 0, 0, 0, 201, 3, 173, 85, 110, 107, 110, 111, 119, 110, 32, 101, 114, 114, 111, 114, 4, 211, 0, 0, 0, 0, 0, 0, 0, 0, 5, 211, 0, 0, 0, 0, 0, 0, 0, 0)
---
...

tarantool> require('msgpack').decode(bytes)
---
- error: 'msgpack.decode: invalid MsgPack'
...

```

It was rather hard to debug this one, since Python MessagePack decoder considers this one a valid MessagePack. (And it is valid MessagePack.) The tip that really helped me was running this one with 2.10.0-beta2, which crashes on parsing:

```lua
tarantool> bytes = string.char(130, 39, 170, 114, 101, 116, 117, 114, 110, 32, 46, 46, 46, 33, 145, 199, 74, 3, 129, 0, 145, 134, 0, 171, 67, 108, 105, 101, 110, 116, 69, 114, 114, 111, 114, 1, 170, 99, 111, 110, 102, 105, 103, 46, 108, 117, 97, 2, 211, 0, 0, 0, 0, 0, 0, 0, 201, 3, 173, 85, 110, 107, 110, 111, 119, 110, 32, 101, 114, 114, 111, 114, 4, 211, 0, 0, 0, 0, 0, 0, 0, 0, 5, 211, 0, 0, 0, 0, 0, 0, 0, 0)
---
...

tarantool> require('msgpack').decode(bytes)
tarantool: /home/georgymoiseev/Development/sandbox/tarantool/src/box/mp_error.h:70: error_unpack: Assertion `*data == end' failed.
```

The reason why this MessagePack was "invalid" is that MP_ERROR in Tarantool uses uint32 to store numerical fields and this MessagePack data containing int64-encoded numbers (which can be put to uint32 without any loss of precision, like `0xd300000000` = `int64(0)`).

Even disregarding this case, it is hard to understand what exactly went wrong if you had passed invalid MessagePack (like "too less values in array" and so on).

**Describe the solution you'd like**

`Invalid MsgPack` error contain some info on what exactly went wrong on parsing (especially in case in not related to MessagePack spec violation).

**Describe alternatives you've considered**

Alternative to solving such issues is manually sniffing MessagePack data sent between client and server and then dissecting it with various MessagePack parsing tools. (It is unlikely that having a clear error will always help to understand what exactly went wrong without any dissecting, but it at least should cover some of such cases,)

**Definition of Done**

`Invalid MsgPack` error has a message about what exactly had failed.

**Comment by unera** [comment]
The problem is in `src/box/mp_error.cc`

```c++
  360                 case MP_ERROR_CODE:
  361                         if (mp_typeof(**data) != MP_UINT)
  362                                 goto error;
  363                         mp_err.code = mp_decode_uint(data);
  364                         break;

```

I think the code should check MP_INT and MP_UINT.

PS: We can throw an error if the value is negative.
