### ISSUE TITLE
create_check_constraint - if not exist

### ISSUE THREAD

**Issue by Ar4ikcs** [tarantool/tarantool#7979]
Is it possible to add a new argument to the **create_check_constraint** function like **opts** in **box.schema.space.create**?
For example, opts may contain the option **if_not_exists**
It will be useful because when cartridge/tarantool restarts i see errors like this and instance is not work
```
2022-11-28 12:21:55.485 [18763] main/110/lua confapplier.lua:137 E> Instance entering failed state: ConfiguringRoles -> OperationError
ApplyConfigError: Duplicate key exists in unique index "primary" in space "_ck_constraint" with old tuple - [519, "dates", false, "SQL", "\"dateStart\" < \"dateEnd\"", true] and new tuple - [519, "dates", false, "SQL", "\"dateStart\" < \"dateEnd\"", true]
```

**Comment by alyapunov** [comment]
This function is obsolete and will be dropped.

**Comment by drewdzzz** [comment]
The function was removed in https://github.com/tarantool/tarantool/commit/ea31df2d832284e4c12f9cdc83b5360f7aa0d9bf

**Comment by Ar4ikcs** [comment]
Does it mean that tnt will not be able to create a check constraint?
When i create the issue i mean that i use <space_object>.create_check_constraint function. This function throw the error, which i describe above

**Comment by drewdzzz** [comment]
Constraints will be reworked in an upcoming release. They will be part of space - you'll need to alter the space to create a constraint. There is no place for `if_not_exists` flag in such an API.
