### ISSUE TITLE
Add DMG packages for OS X

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#80]
An idea from V. Gvozdikov

DMG is a self-consistent disk images format used by Apple (c)(r)(tm). It is nice to have a Tarantool image for quick installation (click -> download -> install).

**Comment by rtsisyk** [comment]
We still need "one click installer" for OS X on the our web-site.

**Comment by zloidemon** [comment]
I'll able to make it asap, if that isn't high status you can sign task to me.

**Comment by Mons** [comment]
brew is a modern way for osx
