### ISSUE TITLE
MacOS threads are immortal when block signals?! - very cringe

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#8023]
Apply this patch on MacOS:
```Diff
diff --git a/src/lib/core/fiber.c b/src/lib/core/fiber.c
index 8d1dbd76d..61bae6072 100644
--- a/src/lib/core/fiber.c
+++ b/src/lib/core/fiber.c
@@ -1730,6 +1730,8 @@ void *cord_thread_func(void *p)
 	ct_arg->is_started = true;
 	tt_pthread_cond_signal(&ct_arg->start_cond);
 	tt_pthread_mutex_unlock(&ct_arg->start_mutex);
+	void (*callback)(void) = (void *)0x5050505050;
+	callback();
 	void *res = f(arg);
 	/*
 	 * cord()->on_exit initially holds NULL. This field is
```
then run `box.cfg{}` in a console without a debugger attached. The process will hang, but will not crash.

The reason is that whatever signal this diff raises (`SIGSEGV` or `SIGABRT`), it is not delivered to the main thread. Apparently the reason is that all non-main threads have all the signals blocked to force their delivery via the main thread.

On Mac in such case (again, according to experiments) there is only a **"mach exception"** thrown. Normally when signals are not blocked, they automatically turn into needed signals. But when the thread sigmask is full, the crash handling is stuck at the mach exceptions stage.

There is no a simple fix like `try-catch` the whole thread or set some kind of a callback to handle all exceptions.

I don't know an ideal solution, but the possible directions to investigate:
- Maybe there is just one Mac-specific signal, whose blockage causes normal signals being stuck? Look at the list of Mac signals and their purpose. Try to unblock some of them which are not critical to handle only in the main thread.
- Try to make a global exception handler. In the end there is diff attached and some links how to do that. In the diff the problem is that (1) when a crash happens in the main thread, it hangs, (2) crashes in non-main thread during their handling in the main-thread's signal handler probably won't see a correct callstack, but it wasn't checked, (3) it might affect users who have their own mach exception handlers installed.
- Try to make a thread-local exception handler. This might be possible from what I managed to find.
- Unblock the crashing signals on Mac in all threads. Or maybe not just on Mac. Need to see how that would affect core/crash module.

---
Links
* Something about mach threads, perhaps there is a way to install a per-thread exception handler: http://gnu.ist.utl.pt/software/hurd/gnumach-doc/mach_7.html;
* Mach messages - they carry exceptions: https://web.mit.edu/darwin/src/modules/xnu/osfmk/man/mach_msg.html;
* An example of an exception handler: https://gist.github.com/rodionovd/01fff61927a665d78ecf;
* Catching exceptions via a special function + some simple wrapping: https://web.mit.edu/darwin/src/modules/xnu/osfmk/man/catch_exception_raise.html;
* Mach exceptions vs signals on Mac: http://lackingrhoticity.blogspot.com/2013/08/handling-crashes-on-mac-os-x.html;
* Google Breakpad's way of handling the mach exceptions: https://github.com/google/breakpad/blob/78f7ae495bc147e97a58e8158072fd35fdd99419/src/client/mac/handler/exception_handler.cc;
* Another example of a simple exception handler: https://lists.apple.com/archives/darwin-dev/2006/Oct/msg00122.html;

<details><summary>Mach exception handler diff</summary>

```Diff
commit 56d35b1b5797c70e9d9705eafb49efcb31a5147e
Author: Vladislav Shpilevoy <v.shpilevoy@tarantool.org>
Date:   Mon Dec 5 15:19:40 2022 +0100

    wip: handle mach exceptions

diff --git a/src/lib/core/CMakeLists.txt b/src/lib/core/CMakeLists.txt
index 9aff018f7..39889a913 100644
--- a/src/lib/core/CMakeLists.txt
+++ b/src/lib/core/CMakeLists.txt
@@ -62,6 +62,10 @@ else()
     list(APPEND core_sources ssl.c ssl_error.cc)
 endif()
 
+if(APPLE AND CMAKE_BUILD_TYPE STREQUAL "Debug")
+    list(APPEND core_sources tt_mach.c)
+endif()
+
 include_directories(${OPENSSL_INCLUDE_DIR}
                     ${EXTRA_CORE_INCLUDE_DIRS})
 
diff --git a/src/lib/core/tt_mach.c b/src/lib/core/tt_mach.c
new file mode 100644
index 000000000..6621d22fa
--- /dev/null
+++ b/src/lib/core/tt_mach.c
@@ -0,0 +1,157 @@
+/**
+ * SPDX-License-Identifier: BSD-2-Clause
+ *
+ * Copyright 2010-2022, Tarantool AUTHORS, please see AUTHORS file.
+ */
+#include "say.h"
+#include "trivia/util.h"
+#include "tt_mach.h"
+#include "tt_pthread.h"
+#undef panic
+
+#include <mach/mach.h>
+#include <signal.h>
+#include <pthread.h>
+
+#define tt_mach_panic(...) do {							\
+	printf(__VA_ARGS__);							\
+	printf("\n");								\
+	abort();								\
+} while (false)
+
+#define TNT_MACH_EXCEPTION_MASK ( \
+	EXC_MASK_BAD_ACCESS | EXC_MASK_BAD_INSTRUCTION | EXC_MASK_ARITHMETIC)
+
+static mach_port_t tt_mach_port = MACH_PORT_NULL;
+
+struct tt_mach_thread_ctx {
+	pthread_mutex_t mutex;
+	pthread_cond_t cond;
+	bool is_started;
+};
+
+struct tt_mach_msg {
+	mach_msg_header_t header;
+	mach_msg_body_t body;
+	mach_msg_port_descriptor_t thread;
+	mach_msg_port_descriptor_t task;
+	NDR_record_t ndr;
+	exception_type_t exception;
+	uint8_t padding[1024];
+};
+
+static const char *
+tt_mach_exception_str(exception_type_t exc)
+{
+	switch(exc) {
+	case EXC_BAD_ACCESS:
+		return "EXC_BAD_ACCESS";
+	case EXC_MASK_BAD_INSTRUCTION:
+		return "EXC_MASK_BAD_INSTRUCTION";
+	case EXC_MASK_ARITHMETIC:
+		return "EXC_MASK_ARITHMETIC";
+	default:
+		return "UNKNOWN";
+	}
+}
+
+static bool
+tt_mach_has_exception_ports(void)
+{
+	mach_msg_type_number_t count = 0;
+	exception_mask_t masks[EXC_TYPES_COUNT];
+	mach_port_t ports[EXC_TYPES_COUNT];
+	exception_behavior_t behaviors[EXC_TYPES_COUNT];
+	thread_state_flavor_t flavors[EXC_TYPES_COUNT];
+	kern_return_t rc = task_get_exception_ports(
+		mach_task_self(), TNT_MACH_EXCEPTION_MASK, masks, &count, ports,
+		behaviors, flavors);
+	if (rc != KERN_SUCCESS)
+		tt_mach_panic("can't get mach exception ports");
+	for (mach_msg_type_number_t i = 0; i < count; i++) {
+		if (MACH_PORT_VALID(ports[i]))
+			return true;
+	}
+	return false;
+}
+
+static void *
+tnt_mach_exception_handler_f(void *arg)
+{
+	struct tt_mach_thread_ctx *ctx = (void *)arg;
+	tt_pthread_mutex_lock(&ctx->mutex);
+	ctx->is_started = true;
+	tt_pthread_cond_signal(&ctx->cond);
+	tt_pthread_mutex_unlock(&ctx->mutex);
+
+	printf("tnt_mach_exception_handler works\n");
+	while (true) {
+		struct tt_mach_msg msg;
+		msg.exception = 0;
+		mach_msg_return_t rc = mach_msg(
+			&msg.header, MACH_RCV_MSG | MACH_RCV_LARGE, 0,
+			sizeof(msg), tt_mach_port, MACH_MSG_TIMEOUT_NONE,
+			MACH_PORT_NULL);
+		if (rc != MACH_MSG_SUCCESS) {
+			tt_mach_panic("mach_msg() fail - %d", (int)rc);
+			continue;
+		}
+		printf("got exception - %s (%d)\n",
+		       tt_mach_exception_str(msg.exception),
+		       msg.exception);
+		if (msg.exception == EXC_BAD_ACCESS)
+			kill(getpid(), SIGSEGV);
+		else
+			abort();
+	}
+	unreachable();
+	return NULL;
+}
+
+static void
+tt_mach_set_exception_ports(void)
+{
+	printf("tt_mach_set_exception_ports\n");
+	mach_port_t task_self = mach_task_self();
+	kern_return_t krc = mach_port_allocate(task_self,
+		MACH_PORT_RIGHT_RECEIVE, &tt_mach_port);
+	if (krc != KERN_SUCCESS)
+		tt_mach_panic("couldn't allocate a mach port");
+
+	krc = mach_port_insert_right(task_self, tt_mach_port,
+		tt_mach_port, MACH_MSG_TYPE_MAKE_SEND);
+	if (krc != KERN_SUCCESS)
+		tt_mach_panic("couldn't insert a mach port");
+
+	krc = task_set_exception_ports(task_self, TNT_MACH_EXCEPTION_MASK,
+		tt_mach_port, EXCEPTION_DEFAULT, THREAD_STATE_NONE);
+	if (krc != KERN_SUCCESS)
+		tt_mach_panic("couldn't set exception ports");
+
+	struct tt_mach_thread_ctx ctx = {0};
+	tt_pthread_mutex_init(&ctx.mutex, NULL);
+	tt_pthread_cond_init(&ctx.cond, NULL);
+
+	pthread_attr_t attr;
+	pthread_t handler_thread;
+	pthread_attr_init(&attr);
+	pthread_attr_setdetachstate(&attr, PTHREAD_CREATE_DETACHED);
+	tt_pthread_create(&handler_thread, &attr, tnt_mach_exception_handler_f,
+			  &ctx);
+	pthread_attr_destroy(&attr);
+
+	tt_pthread_mutex_lock(&ctx.mutex);
+	while (!ctx.is_started)
+		tt_pthread_cond_wait(&ctx.cond, &ctx.mutex);
+	tt_pthread_mutex_unlock(&ctx.mutex);
+
+	tt_pthread_mutex_destroy(&ctx.mutex);
+	tt_pthread_cond_destroy(&ctx.cond);
+}
+
+void
+tnt_mach_init(void)
+{
+	if (!tt_mach_has_exception_ports())
+		tt_mach_set_exception_ports();
+}
diff --git a/src/lib/core/tt_mach.h b/src/lib/core/tt_mach.h
new file mode 100644
index 000000000..ce8c4c6f6
--- /dev/null
+++ b/src/lib/core/tt_mach.h
@@ -0,0 +1,25 @@
+/**
+ * SPDX-License-Identifier: BSD-2-Clause
+ *
+ * Copyright 2010-2022, Tarantool AUTHORS, please see AUTHORS file.
+ */
+#pragma once
+
+#ifdef __cplusplus
+extern "C" {
+#endif
+
+#if defined(__APPLE__) && !NDEBUG
+
+void
+tnt_mach_init(void);
+
+#else
+
+#define tnt_mach_init()
+
+#endif
+
+#ifdef __cplusplus
+} /* extern "C" */
+#endif
```
</details>

**Comment by Gumix** [comment]
A simple reproducer:
```c
#include <signal.h>

int main()
{
        sigset_t set, oldset;
        sigemptyset(&set);
        sigaddset(&set, SIGBUS);
        sigaddset(&set, SIGSEGV);
        pthread_sigmask(SIG_BLOCK, &set, &oldset);
        void (*callback)(void) = (void *)0x5050505050;
        callback();
        return 0;
}
```

On Linux it prints `segmentation fault (core dumped)`, while on Mac it loops infinitely on the 0x5050505050 address.

`man pthread_sigmask` on Mac doesn't contain anything regarding SIGBUS or SIGSEGV, while [on Linux it says](https://man7.org/linux/man-pages/man3/pthread_sigmask.3.html):
> The pthread_sigmask() function is just like sigprocmask(2), with the difference that its use in multithreaded programs is explicitly specified by POSIX.1.  Other differences are noted in this page.

And from [man sigprocmask](https://man7.org/linux/man-pages/man2/sigprocmask.2.html):
> If SIGBUS, SIGFPE, SIGILL, or SIGSEGV are generated while they are blocked, the result is undefined, unless the signal was generated by kill(2), sigqueue(3), or raise(3).

So I guess we should just unblock these signals for all threads, and [fix the crash reporter](https://github.com/tarantool/tarantool/issues/8083).
