### ISSUE TITLE
Tarantool doesn't build if libundwind.h is unavailable

### ISSUE THREAD

**Issue by locker** [tarantool/tarantool#8025]
Tarantool 2.11.0-entrypoint-764-g1b15fabbcf32

Build fails with:

```
In file included from /home/vlad/src/tarantool/tarantool/src/lib/core/fiber.h:47,
                 from /home/vlad/src/tarantool/tarantool/test/box-tap/check_merge_source.c:4:
/home/vlad/src/tarantool/tarantool/src/lib/core/backtrace.h:14:10: fatal error: libunwind.h: No such file or directory
   14 | #include "libunwind.h"
      |          ^~~~~~~~~~~~~
```

But it should build just fine, because we use a bundled libunwind.

Triggered by commit https://github.com/tarantool/tarantool/commit/19abfd2a39205de270836adda7f3a733476acaa4, but the root cause is that `test/box-tap/check_merge_source.c` is built as a module, but uses internal headers.

**Comment by Totktonada** [comment]
@NickVolynkin Nope, it looks like autotools generated files in the libunwind repository are generated by one autotools version, but autotools version installed on the build host/container is different. It should gone after PR #8019.

**Comment by NickVolynkin** [comment]
@Totktonada yep, it was likely caused by incorrect submodules in a particular commit.
