### ISSUE TITLE
ninja couldn't find a target for building build/libunwind/dest/lib/libunwind-aarch64.a' on AArch64

### ISSUE THREAD

**Issue by ligurio** [tarantool/tarantool#8026]
**Bug description**

It is not possible to build Tarantool on AArch64 using `ninja-build`.

* OS: Linux
* Architecture: AArch64 (graviton)

Version: b2dab5f4270da1d1a0759245c8a1d93cd8616941

**Steps to reproduce**

```
cmake -S . -B .  -G Ninja -DCMAKE_BUILD_TYPE=Debug -DLUAJIT_ENABLE_GC64=ON
...
-- Configuring done
-- Generating done
-- Build files have been written to: /opt/actions-runner/_work/luajit/luajit

cmake --build . --parallel 8
ninja: error: 'build/libunwind/dest/lib/libunwind-aarch64.a', needed by 'src/tarantool', missing and no known rule to make it
make: *** [.test.mk:42: build] Error 1
Error: Process completed with exit code 2.
```

**Actual behavior**

`ninja` couldn't find a target for building `build/libunwind/dest/lib/libunwind-aarch64.a'`

**Expected behavior**

Building finished successfully.

Job "[Tarantool (Linux/aarch64) Debug GC64:ON / luajit-integration](https://github.com/tarantool/luajit/actions/runs/3437429234/jobs/5732216487#logs)"

**Comment by igormunkin** [comment]
Fixed by #8019. Closing.
