### ISSUE TITLE
can't prune old replicas by deleting their server ids

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#806]
When a replica comes and goes, the server id space (_cluster) can become cluttered with abandoned uuids. It should be possible to simply delete these guids from the _cluster table and thus forget about
abandoned replicas. The trouble is with recovery, since, during recovery we look at the previous xlog file, and its vclock contains server ids for the deleted replicas. As long as this server id is not found in the snapshot, recovery fails.

Recovery fails just the same way when changing server id of the master. It tries to open xlog files which are identified with the previous server id and panics. 

See also gh-459.

As part of work on this ticket, we need to create a test case which overpopulates the _cluster table, removes replicas with 0 changes in their vclock, restarts, removes replicas with non-zero vclock, restarts, etc, changes server uuid, restarts.

**Comment by rtsisyk** [comment]
Why can't? I tried and it does work...

**Comment by rtsisyk** [comment]
A add a tests case for lsn = 0.
just replace master with replica in this test to check lsn > 0

**Comment by kostja** [comment]
Actually you can, needs a test case.

**Comment by Sulverus** [comment]
Implemented with new test-run:
1. Create max replicas and join
2. Try to add one more replca
3. Delete all replicas from `box.space_.cluster` and stop it
4. Create 30 replicas again and join
5. Check results

**Comment by Sulverus** [comment]
https://github.com/tarantool/tarantool/commit/8a633b8d3a0eb9d4ab5c4aacfaeebb533c340743

It works, but sometimes i see max replica errors in log(test passed):
```
$grep -R MAX var/*.log
var/replica10.log:2015-10-27 21:07:39.484 [16807] main/105/applier/localhost:5012 vclock.h:286 E> ER_REPLICA_MAX: Replica count limit reached: 32
var/replica10.log:2015-10-27 21:07:39.485 [16807] main/105/applier/localhost:5012 vclock.h:286 E> ER_REPLICA_MAX: Replica count limit reached: 32
var/replica11.log:2015-10-27 21:07:39.487 [16834] main/105/applier/localhost:5012 vclock.h:286 E> ER_REPLICA_MAX: Replica count limit reached: 32
var/replica11.log:2015-10-27 21:07:39.492 [16834] main/105/applier/localhost:5012 vclock.h:286 E> ER_REPLICA_MAX: Replica count limit reached: 32
```

**Comment by rtsisyk** [comment]
Added a new test case.
