### ISSUE TITLE
use inotify to speed up WAL delivery in async replication

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#808]
Right now replication thread uses ev_stat watcher to discover changes in the binary log and relay them to a replica. ev_stat watcher uses second-coarse timer resolution, which means that a replica may be tens of thousands of records behind the master. This is too much. Additionally, 10 times per second the replica thread rescans the WAL directory to find new data. This is ugly. Additionally,  there is a race condition in notification process when changing the current WAL: if the relay is busy reading the current WAL while a new WAL is being created, it will not notice inotify event for the new WAL and yield into sleep. 

To solve these issues, we need:
- a native inotify watcher which resumes a fiber whenever any inotify event occurs, instead of built-in libev ev_stat watcher
- we should never suspend this watcher, even when re-reading the WAL (currently we only activate the watcher while sleeping, which opens a window for race condition).

**Comment by zloidemon** [comment]
If implement it with (7) inotify. Tarantool will lost support all OS instead Linux.

**Comment by AterCattus** [comment]
inotify + kqueue + ReadDirectoryChangesW + fallback on current implementation ?

**Comment by bigbes** [comment]
No place for WinAPI, right now :D

2015-04-23 15:47 GMT+03:00 Aleksey Akulovich <notifications@github.com>:

> ReadDirectoryChangesW




С наилучшими пожеланиями, Евгений.

**Comment by AterCattus** [comment]
I suggested all variants that I know. Ok, inotify + kqueue + fallback.

**Comment by zloidemon** [comment]
Good variants, but who will do all variants for that case?

**Comment by rtsisyk** [comment]
I patched libev to use nanosecond precision in struct stat. It should be enough.
A patch sent to upstream.
