### ISSUE TITLE
replication: add a test that replica doesn't enter read-write mode before catching up with the master

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#809]
Add a test that checks that local recovery (local WALs) is finished before entering into read/write mode.

**Comment by Sulverus** [comment]
Totaly:
1. catch.test.lua (insert on master, delete on replica)
2. error injection in `relay_send()`

N.B.> now it's possible to delete row before catching up with the master

Please review gh-809 branch: https://github.com/tarantool/tarantool/commits/gh-809

**Comment by kostja** [comment]
Pushed into 1.6
