### ISSUE TITLE
Use .dylib instead of .so for package.cpath on OS X

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#810]
This change is required to fix require() on OS X

**Comment by Sulverus** [comment]
Dynamic libraries format is defined in tarantool `init.cc` and in `luajit/src/luaconf.h`
Patch for tarantool is ready to review https://github.com/tarantool/tarantool/commit/269b005b69956b8db189a20a6ee0bfc696534fc6, but `.so` hardcoded in [luajit](https://github.com/tarantool/luajit/blob/bd34ea57147c74b6f516b0efbe77e96754801507/src/luaconf.h):
```c
#define LUA_LCDIR	LUA_LROOT "/" LUA_LMULTILIB LUA_LUADIR
#define LUA_LLPATH	";" LUA_LLDIR "?.lua;" LUA_LLDIR "?/init.lua"
#define LUA_LCPATH1	";" LUA_LCDIR "?.so"
#define LUA_LCPATH2	";" LUA_LCDIR "loadall.so"

#define LUA_PATH_DEFAULT	"./?.lua" LUA_JPATH LUA_LLPATH LUA_RLPATH
#define LUA_CPATH_DEFAULT	"./?.so" LUA_LCPATH1 LUA_RCPATH LUA_LCPATH2
```

We have 2 ways:
1. Patch https://github.com/tarantool/luajit/ 
2. Workaround it in `init.lua` with replace(is it good idea?)
need @rtsisyk review

**Comment by kostja** [comment]
I think we need to patch LuaJIT build system instead.

**Comment by kostja** [comment]
https://github.com/LuaJIT/LuaJIT/issues/76

**Comment by rtsisyk** [comment]
Still broken:
```
- ./?.dylib;/Users/n.zavaritsky/.luarocks/lib/lua/5.1/?.dylib;/Users/n.zavaritsky/.luarocks/lib/lua/?.dylib;/usr/local/lib/tarantool/?.so;/usr/local/Cellar/tarantool/1.6.8-653/lib/tarantool/?.so;/usr/lib/tarantool/?.so;/usr/local/lib/lua/5.1/?.so;/usr/local/Cellar/tarantool/1.6.8-653/lib/lua/5.1/?.so;/usr/lib/lua/5.1/?.so;
```

**Comment by rtsisyk** [comment]
Please review 6ed16af52f5a4c4fed00c63dd754442cbbabf6e9

```
./src/tarantool: version 1.6.8-753-geadfc3a
type 'help' for interactive help
tarantool> package.cpath
---
- ./?.dylib;/Users/roman/.luarocks/lib/lua/5.1/?.dylib;/Users/roman/.luarocks/lib/lua/?.dylib;/usr/local/lib/tarantool/?.dylib;/Users/roman/homebrew/lib/tarantool/?.dylib;/usr/lib/tarantool/?.dylib;/usr/local/lib/lua/5.1/?.dylib;/Users/roman/homebrew/lib/lua/5.1/?.dylib;/usr/lib/lua/5.1/?.dylib;
```

**Comment by mejedi** [comment]
* from now on, `package.cpath` should mention `dylib`-s only, don't put `so`-s there;
 * LuaJIT, when probing for `something.dylib`, will try `something.so` as well.
