### ISSUE TITLE
Increase `XLOG_READ_AHEAD`

### ISSUE THREAD

**Issue by Gumix** [tarantool/tarantool#8108]
`xlog` and `snap` files are compressed, `xlog_cursor_next` reads them from HDD by ~50 KB chunks:

https://github.com/tarantool/tarantool/blob/182034dc979b3125f0ad66227997b58b400b6e2e/src/box/xlog.c#L1898-L1902

https://github.com/tarantool/tarantool/blob/182034dc979b3125f0ad66227997b58b400b6e2e/src/box/xlog.c#L1548

However `XLOG_READ_AHEAD` is only 16 KB, which doesn't make any sense.

https://github.com/tarantool/tarantool/blob/182034dc979b3125f0ad66227997b58b400b6e2e/src/box/xlog.c#L1557-L1558

Here are CPU usage graphs for Tarantool recovery from a 900 MB snapshot (see #5787 "trees with hints") from a HDD with 300 MB/sec read speed (buffered, uncached).

The first run (`# sync; echo 1 > /proc/sys/vm/drop_caches`) took 25 sec:

<img width="796" alt="Screenshot 2022-12-29 at 21 26 43" src="https://user-images.githubusercontent.com/5719536/209994770-d2c641c8-f1f1-458c-b1ba-4ea9ecd20dc2.png">

The second run (with hot page cache) took 12 sec:

<img width="796" alt="Screenshot 2022-12-29 at 21 27 26" src="https://user-images.githubusercontent.com/5719536/209994790-d77c1358-f212-47eb-b6ee-499382ab41dc.png">

The first run is obviously I/O bound, it should be up to 2x faster with a big enough `XLOG_READ_AHEAD`.

**Comment by Gumix** [comment]
Recovery time for different `XLOG_READ_AHEAD` values:

<img width="710" alt="image" src="https://user-images.githubusercontent.com/5719536/210005918-8722445f-0adf-4d30-bc3e-7ee03253bb45.png">

**Comment by alyapunov** [comment]
Let's take 8M!

**Comment by alyapunov** [comment]
There's a problem: the change of the size would affect each replication relay. There could be lots of relays so the total impact to memory consumption could be significant, while usually a relay actually reads small portions of data and does not need such a big read buffer.
After offline discussion we decided to make simple dynamic-size buffer.
