### ISSUE TITLE
Review breaking changes in 2.11 and add compat options for them

### ISSUE THREAD

**Issue by locker** [tarantool/tarantool#8115]
In the scope of #7000, a new module "compat" was introduced. The goal of this new module is to provide a compatibility configuration layer to make Tarantool updates less painful for users. In a nutshell, when a breaking change is about to be introduced, we should add a new compat option for it and set it to 'old', which means the old behavior (i.e. no breaking change actually happens). When the major version is bumped, we should:
 - update all 'old' compat options to 'new', but allow to reset them to 'old' manually;
 - update all 'new' compat options to 'deprecated' and disable/drop the corresponding code.

However, we already have a bunch of unreleased changes that are in fact breaking, e.g. [fiber slices](https://github.com/tarantool/tarantool/blob/master/changelogs/unreleased/gh-6085-log-and-limit-iteration.md). We should review them and add appropriate compat options if necessary. We should also remove the 'breaking change' tags from the changelog.

**Comment by locker** [comment]
Tracked [here](https://www.notion.so/tarantool/d8ef5ccf94614f839f08e3975d28c611?v=5530a11128c54591b8b9a1a7ec5bf2ba).

**Comment by Totktonada** [comment]
All the changes, which are dubious from the compatibility point of view, were reviewed, discussed and all the follow-up activities were made. I'm closing the issue so.
