### ISSUE TITLE
IProto or netbox rejects some connection requests? Isn't that cringe?!

### ISSUE THREAD

**Issue by Gerold103** [tarantool/tarantool#8130]
I have the following test:
```Lua
--
-- Instance 1
--
-- Step 1
--
box.cfg{listen = 3313, net_msg_max = 5000}
box.schema.user.grant('guest', 'super')

--
-- Instance 2
--
-- Step 2
--
net = require('net.box')
conns = {}
for i = 1, 1000 do
    table.insert(conns, net.connect(3313, {wait_connected = false}))
end
bad_conn = nil
for _, c in pairs(conns) do
    c:wait_connected()
    if c.state ~= 'active' then
        bad_conn = c
        error('found bad conn')
    end
end
```
At `1.10.13-18-g588c65383` the second instance establishes all connections flawlessly. But at `2.10.0-344-g9e0da2a40` and at `2.11.0-entrypoint-854-gff7dc37fa` (latest master I had locally) some connections fail. If print any of them, can see this:
```
tarantool> bad_conn
---
- opts:
    wait_connected: false
  state: error
  error: 'connect, called on fd 231, aka 127.0.0.1:59083: Connection reset by peer'
  port: '3313'
...
```
Both client and server logs are empty. From debugger I can see those connections never make it to the server (`close()` breakpoint never hits), could be a netbox problem. But I didn't investigate too deep.

**Comment by locker** [comment]
Can't reproduce on Linux. May be OS X specific problem.

**Comment by Gumix** [comment]
It's interesting that you got `Connection reset by peer` error on the `connect()` call.

On my M1 mac `connect()`s are always successful, but then `read()` result in the following error.
Roughly 20 out of 200 connections fail, always with consecutive ids 50~70:
```
[..] OK
[52] OK
[53] unexpected EOF when reading from socket, called on fd 63, aka [::1]:52053: Broken pipe
[54] unexpected EOF when reading from socket, called on fd 64, aka [::1]:52054: Broken pipe
[..] error
[71] unexpected EOF when reading from socket, called on fd 81, aka [::1]:52071: Broken pipe
[72] unexpected EOF when reading from socket, called on fd 82, aka [::1]:52072: Broken pipe
[73] OK
[..] OK
```
The `unexpected EOF / Broken pipe` is raised, because `ECONNRESET` error is filtered in `sio_read()`:
https://github.com/tarantool/tarantool/blob/243f9ebd6b124998a131d9f249b7a3c5049ccedb/src/lib/core/sio.c#L252-L260

So the actual error is the same as in the bug description, but for me it occurs during `read()` rather than during `connect()`:
```
[..] OK
[48] OK
[49] read(128), called on fd 59, aka [::1]:64984: Connection reset by peer
[50] read(128), called on fd 60, aka [::1]:64985: Connection reset by peer
[..] error
[71] read(128), called on fd 81, aka [::1]:65006: Connection reset by peer
[72] read(128), called on fd 82, aka [::1]:65007: Connection reset by peer
[73] OK
[..] OK
```

I will try to compare 1.10 and 2.10 versions. BTW, there are no errors if `fiber.sleep(0)` is added after `net.connect()`.

**Comment by Gumix** [comment]
I have tried various combinations of 1.10.15 and 3.0.0 on x86 mac:

  | Server 1.10 | Server 3.0
-- | -- | --
Client 1.10 | OK | OK
Client 3.0 | error | error

**Comment by Mons** [comment]
With nonblocking socket it could behave incorrectly, like return succes, when in fact is not connected.
To check it there is a good flow:
1. do `connect`
2. if it's success, call `getpeername` immediately to check, that connect was really succeded
3. if `getpeername` then fails with ENOTCONN, than dummy `read` may be used to fetch real errno.

**Comment by Gerold103** [comment]
The error happened between 2.10.0-beta1 (works fine) and 2.10.0-beta2 (the error appears). Note that 2.10.0-beta2 won't connect to our latest master - it raises an "invalid msgpack" error. To reproduce use the server of the same version.

Comparing netbox code from 1.10 and latest master I couldn't see any obvious differences in how we create a socket and connect it. It was always non-blocking, connect was always async with waiting for `EV_WRITE` on it, `getsockopt()` was always used. Even when netbox was almost entirely in Lua.

Ideally, need to find the exact commit between beta1 and beta2 where the stuff broke.

**Comment by Gerold103** [comment]
I found the "faulty" commit and the reason. The commit is `c13b3a31a9b04d4e3fbf0be88f76285b2cc103a7` (`net.box: rewrite state machine (transport) in C`). But the commit is fine really.

The reason is that netbox got too fast and the connections are filling up the server socket's backlog. We set the backlog via `sio_listen_backlog()` which is `SOMAXCONN` on non-Linux systems. `SOMAXCONN` is 128. And same on Linux.

Why the same 128 backlog works on Linux but not on Mac? - https://medium.com/@michalwski/parallel-tests-mac-os-x-mysterious-econnreset-and-backlog-2b482066e197. Apparently, Mac's implementation is just not very quick or something.

Sadly, increasing the limit in the code to 1024 didn't help - it gets truncated to the value in `sysctl kern.ipc.somaxconn` (which is also 128). But it can be increased: `sudo sysctl -w kern.ipc.somaxconn=32768`. After doing that + setting a big value in `sio_listen_backlog()` I got rid of the error.

Why it fails sometimes on `connect()` and sometimes on `read()`? - the reason is that a connect might get a positive response from the server "speculatively". It might happen if the server is overloaded and just fake-acks a connection without actually doing the internal bookkeeping stuff right away. The actual establishment of the connection then happens on a first interaction attempt, like reading.

This can't be fixed on our side. If the problem appears for someone else, they should increase the backlog manually. We could bump the value in `sio_listen_backlog()`, but we can't change the system-wide limit.

@sergos, need to decide what to do. Close now, or set a higher limit in `sio_listen_backlog()` + tell people to increase their system-wide limit + close.

**Comment by Totktonada** [comment]
@Gerold103 Shouldn't this kind of errors be retried?

**Comment by Gerold103** [comment]
@Totktonada only if you have reconnect enabled (`reconnect_after` option).

**Comment by sergos** [comment]
I would ensure the connect is not successful with some fake `read()`  on a 'non-Linux platform' and report the error with appropriate instruction on `sysctl` to address the problem.

**Comment by Gerold103** [comment]
The connect is not successful, it is known. And the error is `ECONNRESET`, it can be returned due to other reasons too. Most likely due to other reasons really.

**Comment by sergos** [comment]
> might get a positive response from the server "speculatively"
My intention was to address this speculation. 

As for the changes to the SOMAXCONN - it sounds safe in sources, since it is limited with `kern.ipc.somaxconn` anyways. The error message can be augmented with the configuration update as a possible w/a.

**Comment by Gerold103** [comment]
>  it sounds safe in sources, since it is limited with kern.ipc.somaxconn anyways.

You mean set it to 1000 hardcoded or something? I am not sure it is safe tbh .... Recently I did play with it in my pet project on Mac, used INT_MAX but didn't touch `kern` settings. But no connections were being accepted at all. Probably it might be truncated to 0 when too big or something like that.

As for the reading - I realized that if we try to make a mock read, then we 1) might get stuck if the other side isn't sending anything for unknown period of time, 2) we have to read at least one byte, but can't put it back - we would have to carry it with the socket everywhere to use in the first real read attempt. Doesn't sound feasible.

**Comment by Gerold103** [comment]
@sergos and @sergepetrenko can we do something here? Close or add a comment in the code and close? Any other option is either wrong or won't change anything.

**Comment by sergepetrenko** [comment]
> @sergos and @sergepetrenko can we do something here? Close or add a comment in the code and close? Any other option is either wrong or won't change anything.

@Gerold103 Is there any easy way to get and use the systemwide configured `somaxconn` on mac? [This answer](https://stackoverflow.com/a/28026043) suggests using `sysctlbyname`. If this is possible, this would be the best option, I think.
This code snippet works just fine on my mac:
```c
#include <stdio.h>
#include <errno.h>
#include <sys/sysctl.h>

int main(int argc, char **argv)
{
	int somaxconn = 0;
	size_t size = sizeof(somaxconn);
	int rc = sysctlbyname("kern.ipc.somaxconn", &somaxconn, &size, NULL, 0);
	printf("rc is %d, errno is %d\n", rc, errno);
	printf("sysctl somaxconn is %d\n", somaxconn);
	return 0;
} 
```

**Comment by Gerold103** [comment]
@sergepetrenko getting it won't fix the error. There still will be the error until user goes and changes the external limit. Which is the original problem - we had no idea that this was the reason.

**Comment by sergepetrenko** [comment]
@Gerold103, yes, but at least changing the external limit will work then. If we don't change anything and leave 128 hardcoded, the user will have no control over the situation. Even if he knows it should be ameliorated by increasing the external limit.
