### ISSUE TITLE
Provide default field value for space:format

### ISSUE THREAD

**Issue by unera** [tarantool/tarantool#8157]
Hi!

In [this ticket](https://github.com/tarantool/tarantool/issues/6780) #6780 we decided to check the tuple format in triggers (Trying to avoid the other undefined behaviour bugs).

But some people (#8155) used the triggers to provide defaults from one place.

So I think we should do the next step: provide defaults for space format.

Example:

```lua
tarantool> space:format{
    {
          name='id',
          type='unsigned',
    },
    {
          name='count',
          type='unsigned',
          is_nullable=false,
          default=123
    }
}

tarantool> space:insert{1}
---
- - 1
  - 123
...

```

Checkers for `default`

If a user add `default = something` and `type(something)` not equal `type(space.format[fieldno])` the user should get error: incompatible type.

Also.

**Normal situation**: nullable field with default = notnull_value.
User case: A client wants to add a `nullable=false` field, but want to do that step by step: add nullable, fill all nulls, drop nullable flag.

**Comment by Mons** [comment]
> Isn't this a duplicate of #3206 ?

I think it's worth collecting references to all relevant issues

**Comment by msiomkin** [comment]
Don't forget this scenario, please:

https://github.com/tarantool/tarantool/issues/3206#issuecomment-433944423

**Comment by vlalykin** [comment]
> But some people (https://github.com/tarantool/tarantool/issues/8155) used the triggers to provide defaults from one place. So I think we should do the next step: provide defaults for space format.

not just the default values, it could be the result of some calculations and part of complex business logic.
providing default values for space format does not solve the problem

**Comment by unera** [comment]
SQL requires functional variant for `default`.

So it would be nice to have the following syntax

```
{
   type = 'integer',
   name = 'longitude',
   fndefault = 'random_point',
   default = 37
}

```

If a function `fndefault` is defined, then the default value is calculated as `fndefault($default)`

- `fndefault` - is a name of a function in `_func`
- `fndefault` - don't have to be an idempotent function.
- `fndefault` - musn't do `yield` (so, if a user does, we can print log error)

**Comment by alyapunov** [comment]
For simplicity of agile development let's make functional part in #8609.
