### ISSUE TITLE
Tarantool does not start from the root directory

### ISSUE THREAD

**Issue by DifferentialOrange** [tarantool/tarantool#8158]
**Bug description**

If `tarantool` master is installed on the Ubuntu container, after restart `tarantool` binary is broken.

* OS: Ubuntu
* OS Version: 22.04
* Architecture: amd64

`tarantool 2.11.0~entrypoint-877`

**Steps to reproduce**

1. Clone the master
    ```bash
    git checkout master
    git pull origin master
    ```
2. Build the master with packpack
    ```bash
    OS=ubuntu DIST=jammy make -f .pack.mk package
    ```
3. Install the artifact to some clean docker container
    ```bash
    docker run -it -v `pwd`/build:/build ubuntu:22.04
    ```

    ```bash
    cd /build
    apt update
    apt install `pwd`/tarantool_2.11.0~entrypoint.877.dev-1_amd64.deb  -y
    ```
4. Run tarantool (ok)
    ```bash
    tarantool
    Tarantool 2.11.0-entrypoint-877-g457b293cb
    type 'help' for interactive help
    ```
5. Stop the container (Ctrl+C)
6. Restart the container
    ```bash
    docker ps -a
    docker start 2eb062c5c047 
    ```
7. Run tarantool (not ok)
    ```bash
    docker exec -it 2eb062c5c047 /bin/bash
    ```

    ```bash
    tarantool
    PANIC: unprotected error in call to Lua API (builtin/tarantool.lua:78: attempt to perform arithmetic on local 'ind' (a nil value))
    ```

**Actual behavior**

Get `PANIC: unprotected error in call to Lua API (builtin/tarantool.lua:78: attempt to perform arithmetic on local 'ind' (a nil value))` on `tarantool` start.

**Expected behavior**

`tarantool` starts ok.

**Comment by DifferentialOrange** [comment]
Full build log: [build.log](https://github.com/tarantool/tarantool/files/10413606/build.log)

**Comment by Gumix** [comment]
A simple reproducer:
```bash
$ cd /
$ tarantool
PANIC: unprotected error in call to Lua API (builtin/tarantool.lua:78: attempt to perform arithmetic on local 'ind' (a nil value))
```

The bug in [`remove_root_directory`](https://github.com/tarantool/tarantool/blob/457b293cb820bccce7424fa03bd23662be2a6b1a/src/lua/init.lua#L78), which is used for obtaining module names for per-module logging.
