### ISSUE TITLE
lua decorator to make function atomic

### ISSUE THREAD

**Issue by zlobspb** [tarantool/tarantool#818]
This one might be useful:

function box.transaction(func) -- or function box.atomic(func)
    return function(...)
        box.begin()
        local res = func(...)
        box.commit()
        return res
    end
end

Usage example:

function test()
    box.space.test:insert({1,2,3})
    box.space.test:insert({2,3,4})
    box.space.test:insert({3,4,5})
end

test = box.transaction(test)

**Comment by zlobspb** [comment]
@rtsisyk showed me better way for this
```lua
local function atomic_tail(...)
    box.commit()
    return ...
end

local function atomic(func)
    return function(...)
        box.begin()
        return atomic_tail(func(...))
    end
end
```

**Comment by rtsisyk** [comment]
+1 for this feature

**Comment by kostja** [comment]
Ok to push
25 дек. 2015 г. 10:20 PM пользователь "Roman Tsisyk" <
notifications@github.com> написал:

**Comment by rtsisyk** [comment]
@Mons wants a wrapper to execute a function in transaction:

```
box.txn(fun, ...) 
  box.begin()
  local status, reason = pcall(fun, ...)
  if not status then
    box.rollback()
    error(reason, 2)
  end
  box.commit()
  return reason
end
```

**Comment by Mons** [comment]
For now I propose the following:
```lua
do
	local function tail(status, ...)
		if not status then
			box.rollback()
			error((...), 2)
		end
		box.commit()
		return ...
	end

	function box.txn(fun, ...)
		box.begin()
		return tail(pcall(fun, ...))
	end
end
```

**Comment by kostja** [comment]
Name: box.atomic()

**Comment by rtsisyk** [comment]
=> Implement box.atomic() using the code from Mons' [comment above ^^^](https://github.com/tarantool/tarantool/issues/818#issuecomment-298757317).

**Comment by rtsisyk** [comment]
292cd479ba29cb9e28f1972f1917715291a1815e
