### ISSUE TITLE
Optimize select with offset option

### ISSUE THREAD

**Issue by alyapunov** [tarantool/tarantool#8204]
[PM link](https://www.notion.so/tarantool/offset-n-count-key-log-n-4aba908b48674123892474957420c85f)

Now the cost of `select({key}, offset)` in TREE index with N tuples is `O(log(N) + offset)`. That's a big problem for those users who use huge offsets. Actually it seems that it can simply optimized to O(log(N)) with a tiny cost - just store the total size of subtree in every node of bps tree.

On this way we could also optimize cost of `count{key}` to O(count).

**Comment by R-omk** [comment]
It may also optimize  count between A,B , like redis ZCOUNT command.

but I would prefer it to be an index option or even other type of index

**Comment by alyapunov** [comment]
> It may also optimize count between A,B , like redis ZCOUNT command.
> 
> but I would prefer it to be an index option or even other type of index

1. Tarantool doesn't have methods neither for selecting tuples between A and B nor for counting them, while this issue does not introduce new API, just optimization of it. But if we implement the proposal then you will able to get the desired count with `count(A, {iterator='ge'}) - count(B, {iterator='gt'})`.
2. Why would you prefer an option? An option (or new index) is an additional pain for support. On the other hand the counter is veery cheap in terms of memory consumption and rather cheap in terms of calculation. The only problem I see that in case of presence of a read view the copy-on-write will be used more aggressively.

**Comment by R-omk** [comment]
1. if the count function becomes optimized that should work good.

2. I'm just worried about performance due to the presence of an unpopular feature. To avoid the "bottleneck" effect. But if you think that there are few negative effects, then ok.

**Comment by viciious** [comment]
This would be a neat feature indeed!
