### ISSUE TITLE
Disable automatic schema upgrade

### ISSUE THREAD

**Issue by locker** [tarantool/tarantool#8207]
`box.schema.upgrade` is called automatically if
- Instance is rw (obvious), see #2531.
- Replication isn't configured, because schema upgrade in a cluster is a complicated procedure that has to be done manually, see #2886.

Such behavior is confusing and not really useful, because in production, replication is usually configured. Let's drop it.

**Comment by alyapunov** [comment]
@Mons please consider to label it as 'bug' and '2.10' as well.

**Comment by locker** [comment]
[`test/box-luatest/gh_6794_recover_nonmatching_xlogs_test.lua`](https://github.com/tarantool/tarantool/blob/7c12d490621013ecc9d66f5fc892882a19e82ad7/test/box-luatest/gh_6794_recover_nonmatching_xlogs_test.lua#L41) starts to fail after disabling auto-upgrade because of a bug in `luatest.Server.grep_log`. We need to merge https://github.com/tarantool/luatest/pull/286 and bump the luatest and test-run submodules before we can proceed.
