### ISSUE TITLE
datetime module timezone bug (unable to parse tz string)

### ISSUE THREAD

**Issue by avmartugin** [tarantool/tarantool#8238]
datetime module can't parse tz ('Europe/Moscow' for example)

OS: tarantool/tarantool:2.10.4

output:
unix/:/var/run/tarantool/tarantool.sock>  require("datetime").new{ timestamp = os.time(), tz = 'Europe/Moscow' }
error: 'builtin/datetime.lua:479: could not parse ''Europe/Moscow'''

**Comment by foxzi** [comment]
I fix this problem. Docker images have rebuilt.
