### ISSUE TITLE
tarantoolctl reload is doing nothing

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#824]
tarantoolctl reload is doing dofile(), whereas it should send the file to the server via control socket, or at least execute dofile() on the server side.

**Comment by Sulverus** [comment]
Done. Please review:
1. tarantoolctl reads file 
2. send file to the server via control socket
3. run it on the server side using `loadstring`

**Comment by kostja** [comment]
Pushed. Needs a doc entry for tarantoolctl.
