### ISSUE TITLE
Disable JIT engine on macOS platforms by default

### ISSUE THREAD

**Issue by igormunkin** [tarantool/tarantool#8252]
There is a bunch of tickets related to LuaJIT compiler on macOS platforms. To improve customer experience me and @Mons decided to disable JIT engine on Tarantool startup for macOS builds. Either way, JIT will be aboard as a result of the changes and more adventurous users will be able to enable it via `jit.on()` in their code.

The following need to be done in scope of this issue:
* [x] Adopt LuaJIT testing machinery to skip JIT-related tests
* [x] Introduce LuaJIT CI workflow for regular testing routine with disabled compiler
* [ ] Implement the patch disabling JIT machinery in Tarantool on macOS
* [ ] Adopt Tarantool testing suite to skip JIT-related tests
* [ ] Enable M1 regular testing back.

**Comment by kostja** [comment]
It saddens me to say that but I think JIT should be eventually disabled on all platforms. Here's why I think so:
- JIT performance improvements can not be relied upon - the tracing engine can slow things down, not only speed them up, the number of JIT traces to keep in the cache has to be carefully selected, garbage collection can be a performance hog.
- LuaJIT is dead. no amount of maintenance effort will change it. The Lua community has moved on. FFI is slower in interpreter mode than Lua stack API, so you either build your APIs for FFI or for lua State, and it seems lua state has won. 
- so going forward it's best to rewrite all FFI over to use Lua state and replace LuaJIT with Puc-Rio Lua. Not a huge effort if you look at it. And C or Rust API can be used for anything performance critical.

**Comment by kostja** [comment]
Ah, and one more thing. LuaJIT is the primary reason why Tarantool can't run on Elbrus and other exotic machine architectures. Going forward this will be increasingly important.

**Comment by tsafin** [comment]
@kostja 
> LuaJIT is the primary reason why Tarantool can't run on Elbrus and other exotic machine architectures.

This is not entirely correct, please look around https://storage.mcst.ru/pub/src/LuaJIT/ (essentially we see patch, which disables JIT on el2k architecture, but allows to run LuaJIT userbase code on their platform without massive rewriting efforts).

**Comment by igormunkin** [comment]
I just would like to prevent further discussion and warn everybody already involved, that this particular ticket is just a bullet list to prepare the upcoming release for macOS platforms, so it will be closed when all subtasks are completed.

Anyway, feel free to open another one for the fantasies.

---

P.S. @kostja, if you're interested in *my* thoughts on questionable decisions made in the past or *my* vision for the future of LuaJIT in Tarantool, I'd be delighted to share any *in person*.

**Comment by kostja** [comment]
I don't know folks what triggers you so much. I didn't choose luajit for tarantool, @delamonpansie did. And to be fair to @delamonpansie nobody knew then that LuaJIT will end up where it did. And I am making an effort to amend for this mistake with the investment into Rust ecosystem and transition to Rust. And I am still happy to discuss things. I have no other place to discuss them but the bugs database - I have no access to your "kitchen".

**Comment by kostja** [comment]
And I of course don't mean to ditch Lua from Tarantool. Lua is a great language but Lua community has moved on. Every year Tarantool stays on LuaJIT will broaden that gap.

**Comment by igormunkin** [comment]
> And I am still happy to discuss things.

Glad to hear that. The only thing that bothers me is the discussion about vision and strategy in scope of the ticket for operational routine. That's all.
