### ISSUE TITLE
Building with embeded libcurl fails

### ISSUE THREAD

**Issue by grafin** [tarantool/tarantool#8268]
**Bug description**

Currently building with ENABLE_BUNDLED_LIBCURL=ON and BUNDLED_LIBCURL_USE_NGHTTP2=ON fails with following log:

```
/nix/store/r2b9k28c6aghczpqfvh71y9xavm7rr68-binutils-2.39/bin/ld: build/curl/dest/lib/libcurl.a(http2.c.o): in function `client_new':
http2.c:(.text+0x23f2): undefined reference to `nghttp2_option_set_no_rfc9113_leading_and_trailing_ws_validation'
```

After some research, I've found out that nghttp2_option_set_no_rfc9113_leading_and_trailing_ws_validation function was added in [nghttp2 version 1.50.0](https://nghttp2.org/blog/2022/09/21/nghttp2-v1-50-0/) while currently we bundle nghttp2 version 1.48.0, because of that the build fails.

* OS: NixOS
* OS Version: 22.11
* Architecture: amd64

**Actual behavior**

Tarantool isn't built.

**Expected behavior**

Tarantool is built.

**Comment by Totktonada** [comment]
libcurl uses this function under a build-time condition: https://github.com/curl/curl/commit/eafc2b14ac9e40377168b46cab3f1d90c3f32f45. It seems, system's nghttp2 header is in effect in your case.

It is hard to eliminate such problems. I'm thinking on refactoring of bundling of third party libraries and I'm okay to fix this particular problem by just updating the nghttp2 library.
