### ISSUE TITLE
YAML serializer doesn't detect references between table and nested table with `__serialize` meta method

### ISSUE THREAD

**Issue by locker** [tarantool/tarantool#8310]
PR https://github.com/tarantool/tarantool/pull/8245 fixes alias detection in a table returned by the `__serialize` meta method. However, if a table returned by the `__serialize` meta method references fields from an outer table, they aren't identified as aliases:

```
tarantool> t = {}
---
...

tarantool> {a = t, b = setmetatable({}, {__serialize = function() return {t, t} end})}
---
- a: []
  b:
  - &0 []
  - *0
...
```

To fix this issue, we need to add yet another phase to the YAML serializer:
1. Run all `__serialize` methods recursively. **This is the new phase.**
2. Build a reference table.
3. Encode the resulting object in YAML.

While performing the new phase, the YAML serialize also need to maintain the table mapping all objects to their serialization so that we don't call `__serialize` multiple times for different references of the same object.

**Comment by Totktonada** [comment]
If more or less significant refactoring of the YAML serializer is planned, I suggest to look on the scenarios from https://github.com/tarantool/tarantool/issues/3228#issuecomment-875900653 and https://github.com/tarantool/tarantool/issues/6201 and at least consider, whether we're going forward to solve these problems.
