### ISSUE TITLE
Markup tarantool log messages as `tarantool` module

### ISSUE THREAD

**Issue by unera** [tarantool/tarantool#8320]
Hi, there!

In issue #3211 we realised the per-module logging subsystem. Users can now switch log levels for every Lua module, except tarantool system messages.

So It would be nice:

- Markup all tarantool messages as belonging to module `tarantool`
- Be sure that `box.cfg{module_log_level = {tarantool = XXX}}` works fine.

**Comment by Gumix** [comment]
Currently we don't have an API for setting names and levels for non-Lua parts of Tarantool, related task: #2485

**Comment by unera** [comment]
We can fill every not-defined modules as `tarantool`. So, the patch could be easy.
