### ISSUE TITLE
Add support for temporary spaces with temporary metadata

### ISSUE THREAD

**Issue by gmoshkin** [tarantool/tarantool#8323]
For our use case we need to be able to create temporary spaces on read-only replicas.
Currently temporary spaces cannot be created in read-only mode because the fact of
their creation is persisted and replicated, i.e. they have persisting and replicating metadata.

We propose adding a new subtype of temporary spaces: meta-temporary spaces.
They need to be able to be created via both lua and C api and must support in read-only mode:
- Space creation/deletion/alteration
- Index creation/deletion/alteration
- Truncation
- Data modification (insert/delete/update/...)

Their metadata including
- Fact of space creation/deletion/alteration/truncation
- Fact of index creation/deletion/alteration

must neither be persisted nor replicated.

They also don't need to support some of the more advanced features if those features are to complicated to support:
- Privilege granting is not needed
- SQL triggers are not needed
- Check/foreign key constraints aren't needed
- Constructing views with references to meta-temporary spaces isn't needed
- Functional indexes aren't needed 

Here's the lua syntax we propose:
```lua
box.schema.space.create('meta-temp', { temporary = 'meta' }) -- temporary data and metadata
box.schema.space.create('meta-temp', { temporary = true }) -- only temporary data (as before)
box.schema.space.create('meta-temp', { temporary = false }) -- as before
box.schema.space.create('meta-temp', { temporary = 'something else' }) -- error
```

**Comment by R-omk** [comment]
Related https://github.com/tarantool/tarantool/issues/5616

**Comment by olegrok** [comment]
Probably it's similar to ephemeral spaces https://github.com/tarantool/tarantool/issues/3375

**Comment by gmoshkin** [comment]
> Probably it's similar to ephemeral spaces #3375

Partially. We also need to be able to access meta-temporary spaces in sql statements, which would not be possible be they nameless, and accessing them via the current c api would not be possible without them having ids.
