### ISSUE TITLE
ecryptfs doesn't support O_DIRECT

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#834]
open("./00000000000000000001.snap.inprogress", O_WRONLY|O_CREAT|O_EXCL|O_TRUNC|O_DIRECT, 0664) = -1 EINVAL (Invalid argument)
munmap(0x7f298cf6f000, 1056768)         = 0
write(2, "tarantool_box: ", 15tarantool_box: )         = 15
write(2, "Failed to save snapshot: failed "..., 59Failed to save snapshot: failed to open file in write mode.) = 59

**Comment by rtsisyk** [comment]
I hope I fixed this problem a long time ago....

**Comment by rtsisyk** [comment]
Fixed in 1.6.x. I don't see any reasons to backport this fix.
