### ISSUE TITLE
Pagination stops if the `after` tuple was deleted

### ISSUE THREAD

**Issue by olegrok** [tarantool/tarantool#8373]
Imagine I have sharded space (two spaces on two nodes) with following schema:

```
box.schema.space.create('test2')
box.space.test2:create_index('pk')
box.space.test2:create_index('sk', {unique = false, parts = {{2, 'int'}}})
```

Then I have two tuples in my space (one on each storage)

```
{1, 2008}
{2, 2008}
```

Then I try to select first row from `sk` index and get cursor:
```
tarantool> box.space.test2.index.sk:tuple_pos({1, 2008})
---
- ks0H2AE
...

tarantool> msgpack.decode(digest.base64_decode('ks0H2AE')) -- just to check that it's OK
---
- [2008, 1]
- 6
...
```

But when I try to select the second row from another storage I got empty rowset:
```
tarantool> box.space.test2.index.sk:select({2008})
---
- - [2, 2008]
...

-- I expect that {1, 2008} is less {2, 2008} so I get my tuple... But result is empty.
tarantool> box.space.test2.index.sk:select({2008}, {after = 'ks0H2AE', fetch_pos = true}) 
---
- []
- null
...
```

It perfectly works for `after` values that are in space.
```
tarantool> box.space.test2.index.sk:tuple_pos({2, 2008})
---
- ks0H2AI
...

tarantool> box.space.test2.index.sk:select({2008})
---
- - [2, 2008]
  - [3, 2008]
...

tarantool> box.space.test2.index.sk:select({2008}, {after = 'ks0H2AI', fetch_pos = true})
---
- - [3, 2008]
- ks0H2AM
...
```

But that implementation is quite useless in real world...

**Comment by olegrok** [comment]
Case 2:  single space. Still 2 rows {1, 2008} and {2, 2008}.

The first user call select(limit=1, fetch_pos=true) and then the second deletes the first record. As result the second user can't continue iterate a space since next select with after will return empty rowset. It looks like a bug.

**Comment by locker** [comment]
Vinyl isn't affected.
