### ISSUE TITLE
authentication triggers

### ISSUE THREAD

**Issue by igorcoding** [tarantool/tarantool#844]
Add a trigger which is invoked before authenticating to a new user.
Pass user name to the trigger.

Trigger name is 'on_auth'. Store the trigger hook in box.session. box.session.on_auth(lua function).
If the trigger fails with an error, authentication should fail as well.

The trigger is not invoked if user password doesn't match or other authentication error (i.e. it's invoked only on successfull authentication, but before chaning the user, so the trigger has the option of failing authentication if necessary)

**Comment by Sulverus** [comment]
Added session trigger for successful authentication  + test case. Please review https://github.com/tarantool/tarantool/commit/85240dc3ab780b1a3125baf7f45877dfd3d48c85
Usage example:
```lua
my_fun = function() print('hello world') end
box.session.on_auth(my_fun)
```
N.B> Auth trigger is not called if we use guest connection without password

**Comment by Sulverus** [comment]
Feature updated:
trigger can be used with event argument:
```lua
my_fun = function(user_name) print('hello ' .. user_name) end
box.session.on_auth(my_fun)
```

**Comment by kostja** [comment]
Pushed into master.
