### ISSUE TITLE
The number of replicas limited to the number for CPU cores

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#845]
Tarantool uses one system thread (`struct cord`) for each replica connection. The number of cord are not limited in compile or runtime. However, replication relay uses cord_cojoin() which is implemented via coio_call() which uses  libeio thread pool... By default the size of this pool is equal to the number of CPU cores (experimentally investigated).

In other words, `(#CPU + 1)` replica will be blocked by libeio thread pool. Moreover, since we use libeio also for `coio_getaddrinfo()` or `fio`, these features will stop to work too.

Please re-implemented cord_cojoin() to don't use an extra thread and libeio thread pool.

**Comment by kostja** [comment]
Pushed into 1.6.7
