### ISSUE TITLE
iproto output grows infinetly

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#846]
it is possible to simulate a situation when a read request will produce big output (e.g. select for all space). The binary protocol handler stops reading from socket only if its input buffer is full. With the default size of this buffer (~1G) it is possible to sent up to 20M select() requests each of which will produce unlimited amount of result data (say, 1Mb). Even 10k response packet for each request will cause OOM killer for Tarantooll process.

**Comment by kostja** [comment]
Since it's no longer infinite, closing.
