### ISSUE TITLE
Compile error on CentOS

### ISSUE THREAD

**Issue by alyapunov** [tarantool/tarantool#849]
Running the code:
```
git clone https://github.com/tarantool/tarantool
cd ./tarantool
git checkout stable
git submodule update --init --recursive
cmake . > cmake.result 2>&1
make > make.result 2>&1
```
Got error:
```
[ 38%] Building CXX object src/CMakeFiles/core.dir/recovery.cc.o
In file included from /home/a.lyapunov/19M/tarantool/src/recovery.cc:29:
/home/a.lyapunov/19M/tarantool/include/recovery.h:102: error: declaration of ‘int (* recovery_state::row_handler)(void*, const char*, uint32_t)’
/home/a.lyapunov/19M/tarantool/include/recovery.h:46: error: changes meaning of ‘row_handler’ from ‘typedef int row_handler(void*, const char*, uint32_t)’
```
Full logs are attached.
I think building of tarantool should fail during cmake with readable error or shouldn't faile at all.

**Comment by alyapunov** [comment]
Github does not support file attaching?..
Here are logs:
http://pastebin.com/G2WUJHEx
http://pastebin.com/pCzERkJn

**Comment by rtsisyk** [comment]
Please try to fix this error and see what happens.. I remember that gcc 4.3 wasn't able to compile our scoped_guards. If you face with scoped guard problem after fixing `row_handler` please re-assign ticket to me and I will forbid gcc <= 4.6.
