### ISSUE TITLE
Use ljlinenoise instead of readline()

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#854]
Try to use ljlinenoise library http://fperrad.github.io/ljlinenoise/ instead of system readline().

**Comment by kostja** [comment]
I can see that linenoise has 25 open issues and 32 pull requests, and no one seems to be working on them. It's also unclear whether it supports national alphabets and character sets properly (check out stackoverflow comments and google for crash japanese linenoise). On FreeBSD we already use libedit in readline compatibility mode (thanks to @zloidemon for his patch for #747). 
So I think it's a non-issue.
