### ISSUE TITLE
luarocks error messages should be more helpful

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#855]
I have Ubuntu 12.04 and Tarantool 1.6 pulled from source today.
(I also installed a binary today with apt-get install, see below.)

The MySQL example in Appendix D. Plugins no longer works,
MYSQL_INCLUDE_DIR or WITH_MYSQL parameters are ignored.
I am assuming that everything must be done with luarocks due to
issue#324 "Move net.sql, net.pg, net,mysql to rocks".
Fine, I've seen https://github.com/tarantool/rocks.
But "luarocks install" stops me.

#1
luarocks install mysql --local
Result =
"Error: Could not find expected file libmysqlclient_r.a, or libmysqlclient_r.so,
or libmysqlclient_r.so.* for MYSQL -- you may have to install MYSQL in your
system and/or pass MYSQL_DIR or MYSQL_LIBDIR to the luarocks command.
Example: luarocks install mysql MYSQL_DIR=/usr/local"
... Actually I do have a /usr/local/mysql/lib, and if I say
MYSQL_LIBDIR=/usr/local/mysql/lib then it finds libmysqlclient, okay.
But if I say MYSQL_DIR=/usr/local or MYSQL_DIR=/usr/local/mysql
then it finds nothing, so I don't think the message was helpful.

#2 luarocks install mysql MYSQL_LIBDIR=/usr/local/mysql/lib --local
Result =
"Error: Could not find expected file tarantool/tarantool.h for TARANTOOL
-- you may have to install TARANTOOL in your system and/or pass
TARANTOOL_DIR or TARANTOOL_INCDIR to the luarocks command.
Example: luarocks install mysql TARANTOOL_DIR=/usr/local"
... Actually I had done the usual apt-get install tarantool but
there is no subdirectory of /usr/local that contains tarantool.h.
It appears that the file is expected to be in a subdirectory named
"tarantool", which is not where I install things.
Perhaps the error message would have been more helpful if it had
told me where it actually looked.

**Comment by KlonD90** [comment]
Same thing. Luarocks works with only source of Tarantool?

**Comment by rtsisyk** [comment]
From https://github.com/tarantool/mysql/blob/master/README.md :

```
Prerequisites

    Tarantool 1.6.5+ with header files (tarantool && tarantool-dev packages)
    MySQL 5.1 header files (libmysqlclient-dev package)
````
