### ISSUE TITLE
datetime: strange timestamp on time parsing

### ISSUE THREAD

**Issue by olegrok** [tarantool/tarantool#8588]
```
tarantool> dt.parse('01:01:01', {format ='%H:%M:%S'})
---
- 0000-12-31T01:01:01Z
- 8
...

tarantool> dt.parse('01:01:01', {format ='%H:%M:%S'}).timestamp
---
- -62135679539
...
```

Expected result 3661 = 1 hour 1 minute 1 second since Unix epoch.

Or I didn't find any notes in documentation why it behaves so

**Comment by veod32** [comment]
please inform @veod32 if any documentation update is needed

**Comment by Mons** [comment]
While we parsing date with partial information we should interpret absent components as current time
(almost like in native lua, except the hours: hours should be 00, not 12)

**Comment by ligurio** [comment]
Python's `datetime` [^1] (absent components are not a current time/date):

```python
In [12]: from datetime import datetime

In [13]: datetime.strptime('31/01 23:59:59.999999', '%d/%m %H:%M:%S.%f').date()
Out[13]: datetime.date(1900, 1, 31)
```

Lua [^3]  (absent components are not a current time/date):

```lua
-- LuaJIT

tarantool> os.time({month = 9, day = 1, hour = 12, min = 35, sec = 23}) 
---
- error: field 'year' missing in date table
...

-- To produce a date table, we use the format string "*t". For instance, the following code 
tarantool> os.date("*t", os.time({year = 2021, month = 9, day = 1, hour = 12, min = 35, sec = 23}))
---
- sec: 23
  min: 35
  day: 1
  isdst: false
  wday: 4
  yday: 244
  year: 2021
  month: 9
  hour: 12
...

tarantool> os.date("*t", 1)
---
- sec: 1
  min: 0
  day: 1
  isdst: false
  wday: 5
  yday: 1
  year: 1970
  month: 1
  hour: 3
...

tarantool> 

-- Lua 5.4

> for k, v in pairs(os.date("*t", 10)) do print(k, v) end
min     0
sec     10
month   1
isdst   false
year    1970
wday    5
yday    1
hour    3
day     1
> 
```

[^1]: https://docs.python.org/3/library/datetime.html#strftime-strptime-behavior
[^2]: https://pubs.opengroup.org/onlinepubs/007904875/functions/strptime.html
[^3]: https://www.lua.org/pil/22.1.html

**Comment by Mons** [comment]
Ok, got it.

Maybe I referenced another tool or library, or perhaps it was designed wrong.
Nevertheless, the current behavior is mostly weird and unexpected.
There are several approaches to fill the missing parts in datetime, and I can't say which one is better as the default
* use the minimum possible value
* use the default value, which may refer to unix epoch or some other epoch
* use current value for missing parts. It may be useful to address dates, like `'0712T'` to mean "month 07 day 12 this year".

Anyway, I'd like to consider, that the most expected behavior may refer to some other languages.
It's worth either raising an exception for the missing parts to avoid ambiguity or setting them to "zero", where "zero" should mean unix epoch, as the most common epoch used.

Comments are welcome

**Comment by ligurio** [comment]
> use the minimum possible value

It is an approach used by Golang. Personally, I like it.

Go:

func Parse(layout, value [string](https://pkg.go.dev/builtin#string)) ([Time](https://pkg.go.dev/time#Time), [error](https://pkg.go.dev/builtin#error))

> Elements omitted from the layout are assumed to be zero or, when zero is impossible, one, so parsing "3:04pm" returns the time corresponding to Jan 1, year 0, 15:04:00 UTC (note that because the year is 0, this time is before the zero Time). Years must be in the range 0000..9999. The day of the week is checked for syntax but it is otherwise ignored. 

[^1]: https://pkg.go.dev/time#Parse

Go snippet (https://go.dev/play/p/FbfMbziu34X): 

```go
package main

import (
	"fmt"
	"time"
)

func main() {
	fmt.Println("time.Date()", time.Date(2009, time.November, 10, 23, 0, 0, 0, time.UTC))

	fmt.Println("=====================")

	// Missed month => 01.
	// Missed day => 01.
	// Missed hours => 00.
	// Missed minutes => 00.
	// Missed seconds => 00.
	// Missed fractional seconds => 00.
	// Missed timezone => UTC.
	fmt.Println(time.Parse("2006", "2021")) // 2021-01-01 00:00:00 +0000 UTC <nil>

	// Missed year => 0000.
	fmt.Println(time.Parse("15", "19")) // 0000-01-01 19:00:00 +0000 UTC <nil>
}
```

**Comment by ligurio** [comment]
However, `datetime.new()` sets missed fields Unix time (00:00:00 UTC on 1 January 1971, Thursday):

```lua
tarantool> datetime.new()
---
- 1970-01-01T00:00:00Z
...

tarantool> datetime.new():totable()
---
- sec: 0
  min: 0
  yday: 1
  day: 1
  nsec: 0
  isdst: false
  wday: 5
  tzoffset: 0
  month: 1
  year: 1970
  hour: 0
```

So for consistency, I believe `datetime.parse` should set missed fields to Unix time as well.
