### ISSUE TITLE
Update command-line options

### ISSUE THREAD

**Issue by ligurio** [tarantool/tarantool#8612]
Plan:
- [ ] introduce `--script` option (master and release branches)
- [ ] switch regression tests to using `--script`  (master and release branches)
- [ ] introduce `--repl` option (**master branch only**)
- [ ] forbid passing script path without option `--script` (**master branch only**)

Related:
- luatest: "Support --script in Tarantool 3.0.0" https://github.com/tarantool/luatest/pull/305

**Comment by igormunkin** [comment]
It was decided just to stop starting REPL by default (i.e. when running Tarantool binary with no CLI args) without introducing additional keys mentioned in this issues. Closing.

/cc @Mons
