### ISSUE TITLE
Region_alloc memory leaks in box bindings

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#864]
We have some box bindings like that:
```
static int
lbox_insert(lua_State *L)
{
	if (lua_gettop(L) != 2 || !lua_isnumber(L, 1))
		return luaL_error(L, "Usage space:insert(tuple)");

	struct request request;
	struct port_lua port;
	lbox_request_create(&request, L, IPROTO_INSERT, -1, 2);
	port_lua_create(&port, L);
	box_process(&request, (struct port *) &port);
	return lua_gettop(L) - 2;
}
```

box_process uses region_alloc() for processing request, but I don't see RegionGuard at the top of these bindings.

UPDATE: I run git blame and found a commit caused the problem: 1d1b8953ffc18d50692f8a46e7b375356174f46b

**Comment by kostja** [comment]
* Roman Tsisyk <notifications@github.com> [15/06/08 22:59]:

This is not a leak. The memory is freed at txn commit.

-- 
http://tarantool.org - a NoSQL database in a Lua script
