### ISSUE TITLE
Document some parameters for box.schema.user/role.grant

### ISSUE THREAD

**Issue by bigbes** [tarantool/tarantool#868]
```box.schena.user/role.grant(name, privelege, type, name, options)```

where options can be one of:
* grantor - "name" or "id" of user or role
* if_not_exists - True/False

```box.schema.user/role.revoke(name, privilege, type, name, options)```

where options can be one of:
* if_exists - True/False

**Comment by pgulutzan** [comment]
As far as I can tell, {grantor=user-name} is only possible if I am user 'admin'. Is that correct?

**Comment by kostja** [comment]
Yes.

**Comment by pgulutzan** [comment]
done
