### ISSUE TITLE
Confusing cluster/replicaset/instance name mismatch error

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#8692]
3.0.0-entrypoint-259-g13159230c

Start an instance and stop it:

```sh
$ tarantool
tarantool> box.cfg({cluster_name = 'foo'})
<...>
tarantool> Ctrl+D
```

Start it again with another `cluster_name`:

```sh
$ tarantool
tarantool> box.cfg({cluster_name = 'bar'})
<...>
<...> box.cc:4572 E> ER_CLUSTER_NAME_MISMATCH: Cluster name mismatch: expected bar, got foo
<...> F> can't initialize storage: Cluster name mismatch: expected bar, got foo
```

'Expected' and 'got' values are mixed up.

The same for `replicaset_name` and `instance_name`.

**Comment by Gerold103** [comment]
It depends on how you interpret it. The name 'foo' is stored in WAL. When you recover, you expect to find 'bar' in WAL, but you get 'foo' recovered. This is why 'bar' is expected. Because you expect it in the config, but find a wrong name in WAL.

**Comment by Totktonada** [comment]
Wow, I didn't think about it from this side.

However, it means that the message can be read in two ways. Can we phrase it better? Say,

> ER_CLUSTER_NAME_MISMATCH: Cluster name mismatch: configured as bar, but foo is hold in the database

Or somehow else that would make it clear.
