### ISSUE TITLE
Bindings for clock_gettime()/gettimeofday()

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#872]
Please add bindings for high resolution realtime clock (e.g. fiber.now()).
I see such FFI bindings in many customers projects.

Probably for 1.5 too.

**Comment by Sulverus** [comment]
Hires clock: https://github.com/Mons/tnt-luas/blob/master/hires.lua
Ans we need add wrapper in hires.lua to compute time diff like this:
```lua
local function diff (fun, ...)
    local start_time = now()
    fun(...)
    local diff = now() - start_time
    return diff
end
```

After that we can use bindings in microbench

**Comment by kostja** [comment]
Renamed module from 'time' to 'clock'
