### ISSUE TITLE
avg on integer input uses integer division

### ISSUE THREAD

**Issue by vol0n** [tarantool/tarantool#8735]
**Bug description**

If an input column to `avg` has integral type, tarantool uses integer division when dividing sum over count. 
This is a confusing behaviour: I would expect to get precise value of `avg`, not rounded one. Is it a bug or it was supposed to be this way?

* OS: MacOS
* OS Version: 13.2.1
* Architecture: Intel

Tarantool version: 2.10.4

**Comment by ImeevMA** [comment]
This is done on purpose. See [this discussion](https://github.com/orgs/tarantool/discussions/5910#discussioncomment-1045461).
