### ISSUE TITLE
Assertion fails when `box.rollback` or `box.rollback_to_savepoint` are run from `box.on_commit/on_rollback`

### ISSUE THREAD

**Issue by Serpentian** [tarantool/tarantool#8740]
Reproducer:
```
tarantool> box.cfg()
tarantool> box.schema.create_space('test'):create_index('pk')
tarantool> box.begin() box.on_commit(function() box.rollback() end) box.space.test:insert({1}) box.commit()
tarantool: ./src/box/txn.c:1296: box_txn_rollback: Assertion `txn->signature == TXN_SIGNATURE_UNKNOWN' failed.
zsh: IOT instruction (core dumped)  ./tarantool
```

This seems to work, when run on Release version. The transaction changes are indeed not applied. However, according to the code, triggers are launched after `engine_commit`:

https://github.com/tarantool/tarantool/blob/116df1d70cf768b2cc8569074b2f6715ef84860f/src/box/txn.c#L787-L803

It should be investigated, whether we can rollback in transaction triggers or not. We should either disable this and write it to doc in such case, or tidy up our assertions if it works corrrectly.

**Comment by R-omk** [comment]
Related https://github.com/tarantool/tarantool/issues/7331

**Comment by Serpentian** [comment]
It's documented as UB. We can close it
