### ISSUE TITLE
`box.cfg{ auth_type = 'pap-sha256' }` does not work on Mac SDK. 

### ISSUE THREAD

**Issue by iDneprov** [tarantool/tarantool#8755]
**Bug description**

`box.cfg{ auth_type = 'pap-sha256' }` does not work on Mac SDK. 

* OS: MacOS
* OS Version: 13.4 (22F66)
* Architecture: amd64

`tarantool --version` output: 2.11.0-entrypoint-55-ga74aeaf7c-r508

**Steps to reproduce**

Run two tarantool instances iteractively.

1. Download and install [Tarantool SDK 2.11.0 for Mac](https://www.tarantool.io/ru/accounts/customer_zone/packages/enterprise-macos/tarantool-enterprise-bundle-2.11.0-entrypoint-55-ga74aeaf7c-r508-macosx-x86_64.tar.gz)
2. Run `tarantool` cli
3. Input` box.cfg{ auth_type = 'pap-sha256' }`

**Actual behavior**

You will get error message `error: 'Incorrect value for option ''auth_type'': unexpected option'`

**Expected behavior**

`box.cfg.auth_type` will be configured as `'pap-sha256'`

**Comment by locker** [comment]
> `tarantool --version` output: 2.11.0-entrypoint-55-ga74aeaf7c-r508

The PAP-SHA256 auth type first appeared in Tarantool 2.11.0-entrypoint-104-ga00591510ca2.

Anyway, you're using an unreleased version. Please use [2.11.0](https://github.com/tarantool/tarantool/releases/tag/2.11.0).

**Comment by iDneprov** [comment]
> > `tarantool --version` output: 2.11.0-entrypoint-55-ga74aeaf7c-r508
> 
> The PAP-SHA256 auth type first appeared in Tarantool Enterprise 2.11.0-entrypoint-104-ga00591510ca2.
> 
> Anyway, you're using an unreleased version. Please use [2.11.0](https://github.com/tarantool/tarantool-ee/releases/tag/2.11.0).

Please add Tarantool Enterprise 2.11.0-entrypoint-104-ga00591510ca2 SDK form Mac to tarantool.io

**Comment by locker** [comment]
> > > `tarantool --version` output: 2.11.0-entrypoint-55-ga74aeaf7c-r508
> > 
> > 
> > The PAP-SHA256 auth type first appeared in Tarantool Enterprise 2.11.0-entrypoint-104-ga00591510ca2.
> > Anyway, you're using an unreleased version. Please use [2.11.0](https://github.com/tarantool/tarantool-ee/releases/tag/2.11.0).
> 
> Please add Tarantool Enterprise 2.11.0-entrypoint-104-ga00591510ca2 SDK form Mac to tarantool.io

This repository isn't a right place to file a ticket for this. It's about bugs in Tarantool Community Edition. We don't upload packages to tarantool.io, even more so enterprise packages.
