### ISSUE TITLE
Access to internals of `bsdsocket`. Also `non-yeild` read/recv/recvfrom and write/send/sendto

### ISSUE THREAD

**Issue by bigbes** [tarantool/tarantool#878]
* I need some of routines (e.g. `check_socket`, `get_iflags` of internal library of bsdsocket (`bsdsocket.cc`)), cause i can't read into predefined FFI buffer, so i must write this routine myself.
* read/recv/recvfrom and others doesn't yeild from coroutine. I suppose that related to `:writeable()` and `:readable()` - they must yeild until socket is readeable or writeable, but this API seems to be very inconvinient, and, therefore, read/write are syscalls, so there's no reasons them not to be yeild'ed?

**Comment by rtsisyk** [comment]
:read() and :write() are not syscalls. Please take a look in implementation.

**Comment by bigbes** [comment]
* `socket_methods.read` uses `local readchunk` or `local readline`.
* They uses `:sysread`.
* `:sysread` uses `ffi.C.read`
* ...
* PROFIT

**Comment by rtsisyk** [comment]
socket is non-blocking.

**Comment by bigbes** [comment]
ok, i get it, my bad.
