### ISSUE TITLE
Consider enabling Pointer Authentication on AArch64 macOS

### ISSUE THREAD

**Issue by Gumix** [tarantool/tarantool#8824]
The compilation target on AArch64 macOS is currently `arm64`, however there is another option — `arm64e`, which enables the Pointer Authentication.

Pointer Authentication is a security mitigation technique against the return-oriented programming (ROP) and jump-oriented programming (JOP) attacks:
- https://llvm.org/devmtg/2019-10/slides/McCall-Bougacha-arm64e.pdf
- https://github.com/apple/llvm-project/blob/apple/main/clang/docs/PointerAuthentication.rst
- https://developer.apple.com/documentation/security/preparing_your_app_to_work_with_pointer_authentication

Moreover, macOS system libraries are compiled as `arm64e`, using them from `arm64` code can cause issues like #8074.

**Comment by igormunkin** [comment]
[This activity](https://github.com/LuaJIT/LuaJIT/issues/559#issuecomment-1631566427) is also worth mentioning here.

**Comment by Gumix** [comment]
> An `arm64e` application is not allowed to run on an `arm64` system. Trying to run such an application immediately crashes.

> Since all systems running macOS 13 (Ventura) boot in `arm64` mode, we cannot run our `arm64e` applications by default. We need to enable the `arm64e` mode first.

To enable the `arm64e` mode, one need to disable system integrity protection and to hack macOS boot args.

See for details: https://github.com/lelegard/arm-cpusysregs/blob/main/docs/arm64e-on-macos.md#trying-the-arm64e-target-platform

Since this configuration is very unusual, we can close this task for now.
