### ISSUE TITLE
memtier_benchmark

### ISSUE THREAD

**Issue by bigbes** [tarantool/tarantool#884]
Maybe we should accomodate https://github.com/RedisLabs/memtier_benchmark.git to our needs?

**Comment by rtsisyk** [comment]
Wednesday, June 24, 2015 12:00 PM -07:00 from bigbes <notifications@github.com>:
> 
> Maybe we should accomodate  https://github.com/RedisLabs/memtier_benchmark.git to our needs?
> —
> Reply to this email directly or  view it on GitHub .
> 

Let's show that we faster than Redis even in Redis benchmark ;)

-- 
WBR,
   Roman Tsisyk <roman@tarantool.org>
   http://tarantool.org/ - an efficient in-memory data store and a Lua application server
