### ISSUE TITLE
Inconsistent interval boudaries check

### ISSUE THREAD

**Issue by DifferentialOrange** [tarantool/tarantool#8878]
`datetime.interval` allowed range should include boundaries, yet it doesn't.

```lua
tarantool> datetime.interval.new{year=11759221}
---
- error: 'builtin/box/console.lua:415: value 11759221 of year is out of allowed range
    [-11759221, 11759221]'
...
```

Square brackets imply boundaries inclusion, yet the boundaries are excluded.

https://github.com/tarantool/tarantool/blob/ff57f990f359f6d7866c1947174d8ba0e97b1ea6/src/lua/datetime.lua#L297-L301

At the same time, datetime range check

https://github.com/tarantool/tarantool/blob/ff57f990f359f6d7866c1947174d8ba0e97b1ea6/src/lua/datetime.lua#L263

and C interval range check

https://github.com/tarantool/tarantool/blob/ff57f990f359f6d7866c1947174d8ba0e97b1ea6/src/lib/core/datetime.c#L695

include boundaries, as expected.

**Comment by DifferentialOrange** [comment]
Addition and subtraction also respect boundaries

```
tarantool> datetime.interval.new{year = 11759220} + datetime.interval.new{year = 1}
---
- +11759221 years
...

tarantool> datetime.interval.new{year = 11759220} + datetime.interval.new{year = 2}
---
- error: addition moves value 11759222 of year out of allowed range [-11759221, 11759221]
...

tarantool> datetime.interval.new{year = -11759220} - datetime.interval.new{year = 1}
---
- -11759221 years
...

tarantool> datetime.interval.new{year = -11759220} - datetime.interval.new{year = 2}
---
- error: subtraction moves value -11759222 of year out of allowed range [-11759221,
    11759221]
...
```

**Comment by ArtDu** [comment]
More strange behaviour examples:
![image](https://github.com/tarantool/tarantool/assets/22258443/bb06967d-7dbb-4716-a35f-84c724462455)
![image](https://github.com/tarantool/tarantool/assets/22258443/22672d91-7442-4a25-9ae1-1e79c2e7e9ee)

**Comment by DifferentialOrange** [comment]
> More strange behaviour examples: ![image](https://user-images.githubusercontent.com/22258443/253582636-bb06967d-7dbb-4716-a35f-84c724462455.png) ![image](https://user-images.githubusercontent.com/22258443/253582665-22672d91-7442-4a25-9ae1-1e79c2e7e9ee.png)

I had filed a separate issue, follow https://github.com/tarantool/tarantool/issues/8887

**Comment by ArtDu** [comment]
> More strange behaviour examples: ![image](https://user-images.githubusercontent.com/22258443/253582636-bb06967d-7dbb-4716-a35f-84c724462455.png) ![image](https://user-images.githubusercontent.com/22258443/253582665-22672d91-7442-4a25-9ae1-1e79c2e7e9ee.png)

@DifferentialOrange 
So the solution in hasn't fixed the second picture problem. We can pass from the connector more than limit if connector didn't check boundaries. For example upper limit for year field is 11759221, but I can pass int32. Does Tarantool have to control it?

**Comment by DifferentialOrange** [comment]
> > More strange behaviour examples: ![image](https://user-images.githubusercontent.com/22258443/253582636-bb06967d-7dbb-4716-a35f-84c724462455.png) ![image](https://user-images.githubusercontent.com/22258443/253582665-22672d91-7442-4a25-9ae1-1e79c2e7e9ee.png)
> 
> @DifferentialOrange So the solution hasn't fixed the second picture problem. We can pass from the connector more than limit if connector didn't check boundaries. For example upper limit for year field is 11759221, but I can pass int32. Does Tarantool have to control it?

And it wasn't expected to, follow #8887 issue and #8888 patch

**Comment by ArtDu** [comment]
> And it wasn't expected to, follow #8887 issue and #8888 patch

Correct me if I'm wrong, but #8888 fix only int32 limit problem but not problem that you can pass more than field limit value(not int32 limit).

<img width="856" alt="image" src="https://github.com/tarantool/tarantool/assets/22258443/762a19e3-72ac-4bf7-a589-9c64e9e579b8">

**Comment by DifferentialOrange** [comment]
> > And it wasn't expected to, follow #8887 issue and #8888 patch
> 
> Correct me if I'm wrong, but #8888 fix only int32 limit problem but not problem that you can pass more than field limit value(not int32 limit).
> <img alt="image" width="856" src="https://user-images.githubusercontent.com/22258443/255153682-762a19e3-72ac-4bf7-a589-9c64e9e579b8.png">

Yeah, I doesn't do anything with encode validation. File a separate issue if you wish.

**Comment by ArtDu** [comment]
> > > And it wasn't expected to, follow #8887 issue and #8888 patch
> > 
> > 
> > Correct me if I'm wrong, but #8888 fix only int32 limit problem but not problem that you can pass more than field limit value(not int32 limit).
> > <img alt="image" width="856" src="https://user-images.githubusercontent.com/22258443/255153682-762a19e3-72ac-4bf7-a589-9c64e9e579b8.png">
> 
> Yeah, it doesn't do anything with encode validation. File a separate issue if you wish.

I'll create a ticket. I'm just curious suddenly may you have a plan or a ticket to fix it somewhere
