### ISSUE TITLE
New Lua memory limit option after GC64 enabled

### ISSUE THREAD

**Issue by Mons** [tarantool/tarantool#8881]
Since enabling of GC64 Lua memory can go very high, leading to unexpected OOM across the whole server, instead of just pure OutOfMemory exception inside single instance. So, we need to implement explisit option to cap the memory with ability to change it.

Proposal: new option in section lua:
```yaml
lua:
    memory: 2147483648
```

Default value should be set to 2Gb (2147483648)

Like memtx.memory it could not be lowered, but it whould be good to have an ability to raise it dynamically.

**Comment by Totktonada** [comment]
The rough plan is the following.

* Add an allocator function that tracks overall amount of allocated memory and follows a global limit. The place in the code is [here](https://github.com/tarantool/tarantool/blob/36ef3fb432f9c3e10bf9cbf9aa819fd42226187f/src/lua/init.c#L899).
  * We can replace [luaL_newstate](https://pgl.yoyo.org/luai/i/luaL_newstate) with [lua_newstate](https://pgl.yoyo.org/luai/i/lua_newstate) and pass our own allocator (with `realloc` inside).
  * We can acquire a current allocator ([lua_getallocf](https://pgl.yoyo.org/luai/i/lua_getallocf)) and set ([lua_setallocf](https://pgl.yoyo.org/luai/i/lua_setallocf)) one that wraps the previous one with counter + limit check.
* Add an internal Lua function that allows to set the limit value.
* Add configuration option `lua.memory` into [instance_config.lua](https://github.com/tarantool/tarantool/blob/36ef3fb432f9c3e10bf9cbf9aa819fd42226187f/src/box/lua/config/instance_config.lua) and the corrresponding applier function into `src/box/lua/config/applier/lua.lua` -- it should set the limit.
