### ISSUE TITLE
log.debug()/info()/warn()/error() must not fail on formatting errors

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#889]
```
tarantool> log.info('%d', nil)

---
- error: 'builtin/log.lua:26: bad argument #2 to ''format'' (number expected, got
    nil)'
...
```

The application should not crash due to logging problems!
Log functions must print something reasonable instead of failing on string.format().
Please add extra pcall there.

**Comment by kostja** [comment]
* Roman Tsisyk <notifications@github.com> [15/07/01 16:18]:

I did something similar for format() of strings AFAIR.

-- 
http://tarantool.org - a NoSQL database in a Lua script

**Comment by kostja** [comment]
This goes to the master branch.
