### ISSUE TITLE
Rewrite net.box to use ibuf

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#892]
Please remove Lua string concatenations, string.match(), table.concat(), etc. and move to use new `struct ibuf` FFI bindings. This fix should increase performance of net.box significantly.

For details please take a look on socket:read() and socket:write() implementation in 1.6 branch.

**Comment by Sulverus** [comment]
new netbox version https://github.com/tarantool/tarantool/blob/gh-892/src/lua/net_box.lua
net.box.test passed, but in logs we can see something strange:
```
tarantool: /home/adrozdov/tarantool/tarantool/src/lib/small/slab_cache.c:70: slab_assert: Assertion `slab->magic == slab_magic' failed.
```
Need review

**Comment by kostja** [comment]
Pushed.
