### ISSUE TITLE
Tarantool 2.11.0: ER_PROTOCOL: Transaction id must be equal to LSN of the first row in the transaction.

### ISSUE THREAD

**Issue by ochaton** [tarantool/tarantool#8958]
**Bug description**

I caught misterious bug in asynchronous replication Tarantool 2.11.0:
`ER_PROTOCOL: Transaction id must be equal to LSN of the first row in the transaction.`

* OS: MacOS M1, Macos M1 (docker alpine)
* Architecture: arm, amd64?

```
Tarantool 2.11.0-0-g247a9a4
Target: Darwin-arm64-Release
Build options: cmake . -DCMAKE_INSTALL_PREFIX=/opt/homebrew/Cellar/tarantool/2.11.0_1 -DENABLE_BACKTRACE=TRUE
Compiler: /usr/bin/clang /usr/bin/clang++
C_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -fopenmp -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/tmp/tarantool-20230615-7295-5x7z7g/tarantool-2.11.0=. -std=c11 -Wall -Wextra -Wno-gnu-alignof-expression -Wno-cast-function-type
CXX_FLAGS: -fexceptions -funwind-tables -fasynchronous-unwind-tables -fno-common -fopenmp -Wformat -Wformat-security -Werror=format-security -fstack-protector-strong -fPIC -fmacro-prefix-map=/tmp/tarantool-20230615-7295-5x7z7g/tarantool-2.11.0=. -std=c++11 -Wall -Wextra -Wno-invalid-offsetof -Wno-gnu-alignof-expression -Wno-cast-function-type
```

**Steps to reproduce**

It is quite hard to ease reproducer. Complete reproducer with steps is described in this repo/branch:
https://github.com/ochaton/hunting/tree/mmm-er-protocol

In general we setup 3 nodes in full-mesh master-master replication and create 2 spaces `bus` (ordinary space) and `inbox` (local space). We setup `bus:on_replace` trigger which filters tuples inside applier and inserts some tuples into local `inbox` space.

We have background fiber which atomically removes tuples from local space `inbox` and inserts tuples into ordinary `bus`.

**Actual behavior**

After sending single message via this mechanism 3rd node (not participating in logical communication) stops replication from replicaset. But other 2 nodes continue playing with each other.

Bug is reproduced when we mix local spaces with ordinary spaces in full-mesh master-master replication. Bug reproduced only with 3 instances or greater.

**Expected behavior**

Replication should continue running, because we do not violate any constraint in asynchronous replication

@sergepetrenko @sergos Please take a look

**Comment by sergepetrenko** [comment]
Looks like another incarnation of https://github.com/tarantool/tarantool/issues/8746
