### ISSUE TITLE
Start condition for tarantool 1.5 when admin port is already in use

### ISSUE THREAD

**Issue by aubruevich** [tarantool/tarantool#896]
There are issue in tarantool 1.5: when tarantool starts  and admin port is already in use - tarantool starts successfully (and warning with next message in log 
> 2015-07-06 14:37:54.320 [14828] 1/sched evio.cc:336 W> admin port 43880 is already in use, will retry binding after 0.100000 seconds.")

When I tried to connect to admin port, tarantool showed next error message: 
>"error: admin console connection failed". 

It took a lot of time to investigate the problem and find the issue ( Our tarantool had admin port from ip-v4 bind diapason which was already used by other application)

I think it is better:
1. Write message "admin port 43880 is already in use, will retry binding after 0.100000 seconds." in **error** mode. Usually when the one have some issues with application - first step to investigate the problem: searching for error message in log 
2. Don't start instance of tarantool if admin ( primary) ports are already used. (As I know some kind of this start condition implemented in tarantool-1.6). 

***Tarantool version: Tarantool 1.5.4-46-g6416437***

**Comment by kostja** [comment]
Sorry, this is a  known issue of 1.5, this is why in 1.6 we switched to a single-port approach, the default port being 3301, so below the incoming port range. 
We will not fix this issue in 1.5.
