### ISSUE TITLE
Unclear error message for constraint violation

### ISSUE THREAD

**Issue by p7nov** [tarantool/tarantool#9045]
Tarantool 2.11.0 on MacOS (x86)

When trying to violate a tuple constraint when inserting a tuple, an error message is shown:

```
tarantool> INSERT INTO table4 VALUES (12, 13);
---
- null
- Check constraint 'ck_unnamed_TABLE4_1' failed for tuple
...
```

The wording `Check constraint 'ck_unnamed_TABLE4_1' failed for tuple` implies that the tuple should follow.
If we're not gonna provide tuple details, then the message should be `Check constraint 'ck_unnamed_TABLE4_1' failed for a tuple` (with the "a" article).

Even better: provide tuple info in the error message: `Check constraint 'ck_unnamed_TABLE4_1' failed for tuple [a, 1, false]`.

**Comment by alyapunov** [comment]
I think we should not print tuples in error messages. We never do that; some data is confidential while error are often printed to public log etc.
So let's print an additional article in the message! I hope no design doc will be needed.
