### ISSUE TITLE
SQL: no readable error upon primary key uniqueness violation

### ISSUE THREAD

**Issue by p7nov** [tarantool/tarantool#9052]
Tarantool 2.11.0 on MacOS (x86)

When trying to insert a tuple with a primary key that already exists, I get an unreadable error:

Actual behavior:

```
tarantool> INSERT INTO table2 VALUES (1, 'AB', X'A5', -5.5);
         > ;
---
- null
- !!binary RHVwbGljYXRlIGtleSBleGlzdHMgaW4gdW5pcXVlIGluZGV4ICJwa191bm5hbWVkX1RBQkxFMl8xIiBpbiBzcGFjZSAiVEFCTEUyIiB3aXRoIG9sZCB0dXBsZSAtIFsxLCAiQUIiLCAiQUIiLCA1LjVdIGFuZCBuZXcgdHVwbGUgLSBbMSwgIkFCIiwgIqUiLCAtNS41XQ==
... 
```

Expected behavior: a readable error message explaining that the tuple with this primary key already exists.

Reproduced on the [SQL tutorial](https://www.tarantool.io/en/doc/latest/how-to/sql/sql_tutorial/#create-table) steps:
1. [CREATE TABLE](https://www.tarantool.io/en/doc/latest/how-to/sql/sql_tutorial/#create-table)
2. [INSERT](https://www.tarantool.io/en/doc/latest/how-to/sql/sql_tutorial/#insert)

**Comment by Gumix** [comment]
This is already fixed in 3.0:
```yaml
tarantool> INSERT INTO table2 VALUES (1, 'AB', X'A5', -5.5);
---
- null
- "Duplicate key exists in unique index \"pk_unnamed_TABLE2_1\" in space \"TABLE2\"
  with old tuple - [1, \"AB\", \"AB\", 5.5] and new tuple - [1, \"AB\", \"\xA5\",
  -5.5]"
...
```
