### ISSUE TITLE
Introduce roles in config

### ISSUE THREAD

**Issue by ImeevMA** [tarantool/tarantool#9078]
- [x] Introduce base support for roles https://github.com/tarantool/tarantool/pull/9087)
- [x] Implement `dependencies` for roles (https://github.com/tarantool/tarantool/pull/9338).
- [ ] ~Implement a way to account the necessary privileges for roles.~ Postponed.

**Comment by Totktonada** [comment]
The main scope is done. I propose to track the permissions enhancements separately. Closing so.
