### ISSUE TITLE
Allow to use names from space:format{} when creating indices

### ISSUE THREAD

**Issue by Mons** [tarantool/tarantool#908]
```
s:create_index(
  'primary',
  {unique = true,
  parts = {'fieldname1', 'fieldname2' }}
)
```

**Comment by kostja** [comment]
* Mons <notifications@github.com> [15/07/08 18:28]:

> ```
> s:create_index(
>   'primary',
>   {unique = true,
>   parts = {'fieldname1', 'fieldname2' }}
> )
> ```

Cool!

-- 
http://tarantool.org - a NoSQL database in a Lua script

**Comment by Mons** [comment]
Implemented
