### ISSUE TITLE
A replica may timeout while master is scanning xlogs

### ISSUE THREAD

**Issue by sergepetrenko** [tarantool/tarantool#9094]
**Bug description**

If the master has a long enough xlog, it's possible that it reads it for more than `replication_disconnect_timeout` without sending heartbeats. In this case replica will drop the connection by a timeout and retry connecting, entering an infinite reconnect loop.
This issue was already found and fixed before: ee6de025f7ff4a6fd8e60efafcc78bf613f1686d.

But now it manifests itself again. Commit 56571d83172f made relay stop sending heartbeats, when tx is unresponsive, but that shouldn't happen when WALs are scanned. There is no way to check if tx is responsive while WAL is scanned, and after replication_disconnect_timeout of reading WALs heartbeats are stopped.

We shouldn't stop sending heartbeats during WAL scan, probably.

**Comment by ochaton** [comment]
If relay stops sending heartbeats during wal-scans then we again stuck in the infinite applier-connect loop. Relay just won't have enough time to lookup matching transaction for requested vclock and exit with "write() Broken pipe" or just timeout. Maybe we might instead add wall-time checks inside relay, and if it wastes too much time for scanning, then yield and send heartbeat? Change behaviour from "yield every N records" to "yield when time T has come"
