### ISSUE TITLE
Add helpers for setting error payload in C

### ISSUE THREAD

**Issue by locker** [tarantool/tarantool#9109]
[Link to the design document](https://www.notion.so/tarantool/Error-subsystem-improvements-90faa0a4714b4143abaf8bed2c10b2fc?pvs=4#10e4eac8830a40f083eb541c1f0bed39)

To set an error payload one has to use [`error_set_*`](https://github.com/tarantool/tarantool/blob/1d6043fac53bebd539ee5882f6073767eea753bd/src/lib/core/diag.h#L127-L197) methods on an error object, which isn’t handy, for example:

```c
struct error *e = diag_set(ClientError, ER_READONLY);
error_set_str(e, "reason", box_ro_reason());
```

We need to simplify this, especially in the light of #9108, where we’re planning to replace all error message format arguments with payload fields.

The suggestion is to add helpers that could be used as error payload field initializers:

```c
diag_set(ClientError, ER_READ_ONLY,
         ERROR_STR("reason", box_ro_reason()));
diag_set(ClientError, ER_KEY_PART_COUNT,
         ERROR_UINT("expected", 2),
         ERROR_UINT("got", 3));
diag_set(ClientError, ER_ALTER_SPACE,
         ERROR_STR("space", space_name(space)),
         ERROR_STR("reason", "replication group is immutable"));
```

The helpers will be implemented as functions returning an `error_payload_initializer` struct by value that can later be used to create an error payload field:

```c
struct error_payload_initializer {
    const char *name;
    enum error_initializer_type {
        ERROR_PAYLOAD_INITIALIZER_STR,
        ERROR_PAYLOAD_INITIALIZER_INT,
        /* ... */
    } type;
    union {
        const char *sval;
        int64_t ival;
        /* ... */
    };
};

struct error_payload_initializer
ERROR_STR(const char *name, const char *val)
{
    struct error_payload_initializer v = {
        .name = name,
        .type = ERROR_PAYLOAD_INITIALIZER_STR,
        .sval = val,
    };
    return v;
}

void
error_payload_set(struct error_payload *e,
                  struct error_payload_initializer v);
```

The [`ClientError`](https://github.com/tarantool/tarantool/blob/1d6043fac53bebd539ee5882f6073767eea753bd/src/box/error.h#L200) constructor will take a variadic argument list of `error_payload_initializer` objects and initialize the new error payload using it.

**Comment by nshy** [comment]
Let's consider alternative. Creation `ClientError` with payload would look like:

```c
diag_set(ClientError, ER_READ_ONLY, ER_READ_ONLY_REASON, box_ro_reason()));
diag_set(ClientError, ER_KEY_PART_COUNT,
         ER_KEY_PART_COUNT_EXPECTED, 2,
         ER_KEY_PART_COUNT_ACTUAL, 3);
diag_set(ClientError, ER_ALTER_SPACE,
         ER_ALTER_SPACE_SPACE_NAME, space_name(space)),
         ER_ALTER_SPACE_REASON, "replication group is immutable"));
```

It will require a payload fields type specification for every error code. Payload fields are specified by macros which are defined to integral constant. The latter will allow to lookup type information\field name in simple array by index.

pros:
* type verification for payload fields
* easier to read (I guess not so much, but if we use a slower lookup for type information and use field names instead of macros then yes, much easier, see below)

or use such notation for easier to read at some runtime cost:
```c
diag_set(ClientError, ER_READ_ONLY, "reason", box_ro_reason()));
diag_set(ClientError, ER_KEY_PART_COUNT, "expected", 2, "got", 3);
diag_set(ClientError, ER_ALTER_SPACE,
         "space", space_name(space)),
         "reason", "replication group is immutable"));
```

**Comment by nshy** [comment]
A more concise suggestion from @locker (just positional arguments):

```c
diag_set(ClientError, ER_READ_ONLY, box_ro_reason()));
diag_set(ClientError, ER_KEY_PART_COUNT, 2, key->part_count);
diag_set(ClientError, ER_ALTER_SPACE, space_name(space)), "replication group is immutable"));
```

Looks like nothing is changed comparing with current state. Yet under the hood we will use type information for positional arguments to fill payload.

**Comment by nshy** [comment]
@sergepetrenko, is the last version is good?

**Comment by sergepetrenko** [comment]
> A more concise suggestion from @locker (just positional arguments):
> 
> ```c
> diag_set(ClientError, ER_READ_ONLY, box_ro_reason()));
> diag_set(ClientError, ER_KEY_PART_COUNT, 2, key->part_count);
> diag_set(ClientError, ER_ALTER_SPACE, space_name(space)), "replication group is immutable"));
> ```
> 
> Looks like nothing is changed comparing with current state. Yet under the hood we will use type information for positional arguments to fill payload.
> 
> cons:
> 
> * you cannot omit payload field

Sounds good to me.
