### ISSUE TITLE
Add new ClientError codes for DML operations

### ISSUE THREAD

**Issue by locker** [tarantool/tarantool#9111]
[Link to the design document](https://www.notion.so/tarantool/Error-subsystem-improvements-90faa0a4714b4143abaf8bed2c10b2fc?pvs=4#0532e8fbb67a48e58fb0df4535807149)

Users often complain that errors thrown by `space.insert` or `space.select` functions are difficult to analyze because they lack information about the space for which the failed operation was executed. For example, #7223 was filed because an error thrown by some of Tarantool core DML operations looks like this:

```
Invalid key part count in an exact match (expected 1, got 0)
```

To make investigation easier, we’ll introduce a few new [`ClientError`](https://github.com/tarantool/tarantool/blob/1d6043fac53bebd539ee5882f6073767eea753bd/src/box/error.h#L200) codes, one for each DML operation: `ER_SELECT`, `ER_REPLACE`, `ER_INSERT`, `ER_UPDATE`, `ER_UPSERT`, `ER_DELETE`. They will be set by top-level DML operations ([`box_select`](https://github.com/tarantool/tarantool/blob/96706b7b7e860f23ee59913e347f9b5fd306b662/src/box/box.cc#L3244), [`box_process_rw`](https://github.com/tarantool/tarantool/blob/96706b7b7e860f23ee59913e347f9b5fd306b662/src/box/box.cc#L442)) with [`diag_add`](https://github.com/tarantool/tarantool/blob/1d6043fac53bebd539ee5882f6073767eea753bd/src/lib/core/diag.h#L457) so that the original error that caused the failure will be linked as a cause. All the new errors will store information about the space in the payload: `space_id`, `space_name`, `index_id`, `index_name`. They will also store `key`, `tuple`, and `ops`, if applicable.

**Comment by nshy** [comment]
Discussed f2f with @locker and decided instead just add more payloads on top level. Like `"operation"`, may be `"tuple"` etc.

**Comment by locker** [comment]
> Discussed f2f with @locker and decided instead just add more payloads on top level. Like `"operation"`, may be `"tuple"` etc.

Closing this issue then. We'll improve errors raised by DML operations in the scope of #7223. We'll also add Lua trace to all errors raised in C and thrown to Lua in the scope of #9914.
