### ISSUE TITLE
document stored procedures replication

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#912]
We use row-based replication of stored procedures

**Comment by pgulutzan** [comment]
The manual currently says:
"
Tarantool replication is row-based: each data change command is fully deterministic and operates on a single tuple.
...
A stored program invocation is not written to the write-ahead log. Instead, log events for actual data-change requests, performed by the Lua code, are written to the log. This ensures that possible non-determinism of Lua does not cause replication to go out of sync.
"

**Comment by pgulutzan** [comment]
it's mentioned that they are row-based
