### ISSUE TITLE
(internal) Automate changelog cleanup

### ISSUE THREAD

**Issue by p7nov** [tarantool/tarantool#9135]
# Problem

Changelogs of different Tarantool versions often contain duplicate items. For example, if a fix from 3.0 is backported to 2.11.1, the same changelog item appears in both branches. To keep the changelogs linear, we remove released items from a version's changelog right before its release. Example: a fix is applied to both 2.11.1 and 3.0.0, and 2.11.1 is released. Before 3.0.0 release, this fix should be removed from its changelog to avoid confusion.

# More context

PRs with changelog cleanup:
- https://github.com/tarantool/tarantool/pull/8191
- https://github.com/tarantool/tarantool-ee/pull/348
- https://github.com/tarantool/tarantool/pull/9123
- https://github.com/tarantool/tarantool-ee/pull/551

An automation request from @locker: https://github.com/tarantool/tarantool-ee/pull/348#pullrequestreview-1263770936

 > IMO, deleting released changelogs after each release is definitely not something that should be done manually, because one can easily miss an entry or, what is worse, delete the one that shouldn't be deleted. There should be a script for this and a well-documented procedure for developers and maintainers.

# Current solution

There is a script by @Totktonada [compare-release-notes.zip](https://github.com/tarantool/tarantool/files/12597125/compare-release-notes.zip) (see in `tools/`). It parses git logs of two branches and forms a diff that show which commits that affect files in `changelogs/unreleased` appear in both branches. However, the script seems a bit raw and requires debugging and adjustments for each run.

# Proposed solution

We should properly debug, test, and document the script to make it usable by anyone involved in the release process.

# Definition of done

- [ ] The script is finalized (properly debugged and tested)
- [ ] The script is stored in the Tarantool repo (`taranool/tarantool/tools`)
- [ ] Changelog cleanup is performed by the script on request

**Comment by kyukhin** [comment]
This looks done.
