### ISSUE TITLE
memory leak in function 'sqlTreeViewBareExprList'

### ISSUE THREAD

**Issue by JoraGevorgyan** [tarantool/tarantool#9155]
The memory leak is reported by a static analyzer tool developed at [CAST](https://www.linkedin.com/company/cast-center)
The function 'sqlTreeViewPush' in some conditional path allocates a memory assigns it to a copied argument(which loses after function call) and returns the same pointer. So when they [call  that function](https://github.com/tarantool/tarantool/blob/711756d727456bddd39ee52945dd5ae27a1a5684/src/box/sql/treeview.c#L635) and don't use the returned pointer, it causes a memory leak

**Comment by ImeevMA** [comment]
This does not seem to be the case: if `p` is `NULL`, new memory is allocated, assigned to `p` and then returned. Since `p` was `NULL`, no memory is lost. @JoraGevorgyan, could you please give me a hint when something might go wrong?

**Comment by JoraGevorgyan** [comment]
as I can see pView [is passed](https://github.com/tarantool/tarantool/blob/711756d727456bddd39ee52945dd5ae27a1a5684/src/box/sql/treeview.c#L635) as an argument to function sqlTreeViewPush, AND ... in that function an allocated memory address is [stored in p](https://github.com/tarantool/tarantool/blob/711756d727456bddd39ee52945dd5ae27a1a5684/src/box/sql/treeview.c#L52C3-L52C3), but because p is just the copy of pView, it means that after call of sqlTreeViewPush is done, the memory address assigned to p is lost

**Comment by JoraGevorgyan** [comment]
the possible solution I see is to pass the address of pView and work with that like 'sqlTreeViewPush(TreeView ** p ... ) ' and in body instead of 'p = xmalloc' will be '*p = xmalloc' ... 

if I'm not clear feel free to ask

**Comment by ImeevMA** [comment]
I understand. Well, we don't actually assign the value returned by `sqlTreeViewPush()` to anything on line 635, however the `sqlTreeViewBareExprList()` function is only called in two places, and in both we can be sure that `pView` is not NULL. Since it is not NULL, no new memory will be allocated, so there should be no problem here. We could add `assert(pView != NULL)` just before line 635, but I don't think it's necessary. So, I believe this report is a false-positive.

**Comment by JoraGevorgyan** [comment]
actually it's not a false positive, because there's a path, where the memory address may be lost, but I can't understand, if that case is impossible, why do you call there 'xmalloc'? It's your project and you decide what to do with the issue:-)

**Comment by ImeevMA** [comment]
In general, it is possible to obtain `p == NULL`, but this is not possible in cases where the return value is not assigned to anything. So this is a false positive.

**Comment by ImeevMA** [comment]
The reported issue is false-positive.
