### ISSUE TITLE
Support group to start tarantool

### ISSUE THREAD

**Issue by zloidemon** [tarantool/tarantool#918]
If start tarantool by tarantoolctl with custom user, it might shutdown because tarantoolctld doesn't support setup group. It uses username for both.

**Comment by zloidemon** [comment]
Please merge https://github.com/tarantool/tarantool/commit/a337efd821f290b415038c01e1689ffa895db26f

**Comment by Sulverus** [comment]
Implemented with `getpwnam` and `getgrgid` ffi bindings: we get user data and default user group.

**Comment by Sulverus** [comment]
Merged
