### ISSUE TITLE
Consider forbidding DQL/DML/DDL in on_commit triggers

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#9186]
The [documentation](https://www.tarantool.io/en/doc/latest/reference/reference_lua/box_txn_management/on_commit/) states the following.

> The trigger function should not access any database spaces.

The [commit](https://github.com/tarantool/tarantool/commit/a49c8c02a2f6b7620db12988ec7ee0369076d4d4) that introduces the trigger says the following.

> a trigger can not do any database requests (DML, DDL, DQL) - behaviuor is undefined;

However, spaces are available and DML generally works as expected. AFAIU, things can go bad if DML in on_commit fails on a WAL write.

It is easy to overlook the limitation and it is hard to find it using testing of a module/an application.

I propose to make things more clear: forbid DQL/DML/DDL in on_commit triggers (space, sequence, function, user and other database operations), so attempt to use it will always give an error of some kind (panic if it is the only option).

**Comment by R-omk** [comment]
https://github.com/tarantool/tarantool/issues/7331
