### ISSUE TITLE
Create Amazon Machine Image with Tarantool

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#920]
Create Amazon Machine Image [AMI][1] for Tarantool and register it in [Amazon Market Place][2].
You can use [AWS Free Tier for experiments][3] (register account using your @tarantool.org email).

![ami2](https://cloud.githubusercontent.com/assets/1799054/8649831/59987698-2976-11e5-8ff1-862a5bd6a181.png)
![ami](https://cloud.githubusercontent.com/assets/1799054/8649830/5993479a-2976-11e5-9d93-05823505174d.png)

[1]: http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AMIs.html
[2]: https://aws.amazon.com/marketplace
[3]: http://aws.amazon.com/free/

**Comment by kostja** [comment]
We did a docker image, this should be more than sufficient.
