### ISSUE TITLE
sysprof and memprof parsers lack error handling

### ISSUE THREAD

**Issue by mkokryashkin** [tarantool/tarantool#9217]
**Bug description**
* OS: Linux
* OS Version: any
* Architecture: x86_64

Both the sysprof and memprof parsers lack thorough error handling. It results in raw lua errors for all kinds of situations: incorrect file passed, file being corrupted, empty, etc. Below are some examples of the errors mentioned:

```
$ ./build/src/luajit -ts sysprof.bin
$ file sysprof.bin
sysprof.bin: empty
$ ./build/src/luajit -ts sysprof.bin
./build/src/luajit: ./tools/utils/symtab.lua:107: attempt to concatenate local 'magic' (a nil value)
```

```
$  ./build/src/luajit -ts mee
./build/src/luajit: ./tools/utils/bufread.lua:122: fopen, errno: 2
```

**Expected behavior**

Parsers should be refactored so all possible errors are reported in a concise and user-friendly way. Maybe it would be nice to provide some possible solutions along with errors. No raw Lua errors must be thrown.

**Comment by igormunkin** [comment]
Looks like part of #5994.
