### ISSUE TITLE
Copy and paste installation snipplet for CentOS/Fedora/FreeBSD/etc.

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#922]
Please add to http://tarantool.org/download.html a simple (up to 4-5 lines of code) shell code snipplet which will install Tarantool (like it done for Debian/Ubuntu).

See also #919, #80

**Comment by zloidemon** [comment]
FreeBSD
```
pkg update 
pkg install tarantool

or

make -C /usr/ports/databases/tarantool install clean
```

**Comment by rtsisyk** [comment]
Already done
