### ISSUE TITLE
Add facility to build tarantool statically via a cmake option

### ISSUE THREAD

**Issue by ylobankov** [tarantool/tarantool#9242]
**Is your feature request related to a problem? Please describe.**

In order to build tarantool statically with downloading and building required libraries from the cloud, I must provide the `./static-build/` directory as the source directory for `cmake`.

```console
cmake -S static-build -B static-build -DCMAKE_TARANTOOL_ARGS="-DCMAKE_BUILD_TYPE=RelWithDebInfo;-DENABLE_WERROR=ON"
```

However, we have the `-DBUILD_STATIC=ON` option, but it does a little different job. This option forces tarantool to build statically, but all libraries except `openssl` are embedded in the binary from the system. In order to embed `openssl` in the binary as well, we need to provide the `-DOPENSSL_USE_STATIC_LIBS=TRUE` option to `cmake`.

```console
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DENABLE_WERROR=ON -DBUILD_STATIC=ON -DOPENSSL_USE_STATIC_LIBS=TRUE
```

So it would be nice to have an option similar to `-DBUILD_STATIC=ON`, but allowing to build tarantool statically with downloading and building required libraries from the cloud.

**Additional context**

This feature is also needed to have a facility to build source packages via `cpack`.

**Definition of Done**

When I do something like this:

```console
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DENABLE_WERROR=ON -DBUILD_STATIC_FOO_BAR=ON .
make -j $(nproc)
```

I would like to get statically built tarantool with embedded libraries from the cloud.

**Comment by MBHuman** [comment]
# Possible problem in <code>src/lib/small/VERSION</code> file. 

## Workaround

Remove <code>src/lib/small/VERSION</code> file

## Analysis

Got logs with this cmake command:

```
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DENABLE_WERROR=ON -DBUILD_STATIC=ON -DCMAKE_VERBOSE_MAKEFILE=ON ..
```

Error logs:

```
In file included from /Users/user/Documents/github/tarantool/src/lib/small/perf/small.cc:34:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/array:114:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/algorithm:653:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/functional:500:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/__functional/function.h:20:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/__memory/shared_ptr.h:35:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/atomic:582:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/__thread/poll_with_backoff.h:13:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/chrono:833:
/Users/user/Documents/github/tarantool/src/lib/small/version:1:1: error: expected unqualified-id
1.0.0-19-gc1b6abd
^

```

**Comment by MBHuman** [comment]
@ylobankov Watch possible workaround

**Comment by Totktonada** [comment]
Is it related to #6076? See also https://github.com/tarantool/smtp/pull/43.

**Comment by MBHuman** [comment]
<img width="745" alt="Screen Shot 2023-10-17 at 9 51 57 AM" src="https://github.com/tarantool/tarantool/assets/44523394/4069cd44-d270-4ffc-944d-a5e96db3f8ef">

**Same case**

# In brief: when "src/lib/small" is in include paths,
# `#include <version>` from inside Mac OS SDK headers
# attempts to include "src/lib/small/VERSION" as a
# header file that leads to a syntax error.
