### ISSUE TITLE
One click installation to AWS from our web-site

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#925]
The raw idea from Denis A. (in my interpretation):

- Add a new section in http://tarantool.org/download.html called "Amazon Web Services" with button "Install"
-  On the click
  + Open AWS authorization dialog in popup
  + Ask user about public SSH key (if needed)
  + Start new EC2 instance using Tarantool image (see #920) and provided SSH key.
  + Display Tarantool credentials to the user

See also #920

**Comment by kostja** [comment]
This is http://tarantool.io
