### ISSUE TITLE
Grant 'execute' for a space object does not have an effect

### ISSUE THREAD

**Issue by Lord-KA** [tarantool/tarantool#9277]
Now 'execute' permission for space objects can be granted to a user or role with the following command:
```lua
box.schema.user.grant('myuser', 'execute', 'space')
```

It doesn't seem to have any effect nor meaning.

**Comment by locker** [comment]
According to the comment in `schema.lua`, this is a legacy bug, which should have been fixed in 2.0:

https://github.com/tarantool/tarantool/blob/26d508d1887c140fb98edb15977a32dcf1e980b4/src/box/lua/schema.lua#L2938-L2941

@Totktonada Do you think we need a compat option for this change?

**Comment by Totktonada** [comment]
@locker I guess that it is possible that `read,write,execute` on a space works as `read,write` now and it means that there is a positive scenario. So, it seems, that the compat option may be useful to run some existing code.
