### ISSUE TITLE
Wrong trigger actions when connect fails with access error

### ISSUE THREAD

**Issue by pgulutzan** [tarantool/tarantool#929]
I have Ubuntu 12.04 and Tarantool 1.6, pulled from source two days ago.

I have a test where the connect fails because "Execute access denied".
The on_connect trigger's function is invoked,
the on_auth trigger's function is invoked,
the on_disconnect trigger's function is not invoked.

 From other tests I gather that the intended behaviour is:
* on_auth happens after on_connect iff on_connect succeeds
* if failure happens after on_connect succeeds, then on_disconnect is invoked

But if that is true, then this is a bug, because a failure
happens at some point (the connect does not occur),
but on_disconnect is not invoked.

The test looks like this.
Start on an empty directory.
Notice that nobody grants anything to guest1.

#On shell #1
box.cfg{listen=3301}
box.schema.user.create('guest1', {password='TheRainInSpainFallsMainlyInThePlain'})
connect_invocations = 0
auth_invocations = 0
disconnect_invocations = 0
function function_for_connect () connect_invocations = connect_invocations + 1; end
function function_for_auth () auth_invocations = auth_invocations + 1; end
function function_for_disconnect () disconnect_invocations = disconnect_invocations + 1; end
box.session.on_auth(function_for_auth)
box.session.on_connect(function_for_connect)
box.session.on_disconnect(function_for_disconnect)

#On shell #2 (different shell, different directory) (it will fail)
box.cfg{}
console = require('console')
console.connect('guest1:TheRainInSpainFallsMainlyInThePlain@localhost:3301')
box.session.user()

#On shell #1 again
connect_invocations
auth_invocations
disconnect_invocations

This is what shell #1 says:
"
tarantool> connect_invocations
---
- 1
...

tarantool> auth_invocations
---
- 1
...

tarantool> disconnect_invocations
---
- 0
...
" 

By email, Konstantin Osipov suggested this is probably a bug.

**Comment by rtsisyk** [comment]
net.box wasn't explicitly closed if error in `console.connect()`. on_disconnected trigger was only invoked after collectgarbage('collect') which destructed leaked net.box.

It is always better to free socket connections as soon as possible, without waiting for GC.
I extended Andrew's fix to work both for iproto and console connection.
