### ISSUE TITLE
Remove app/module_api.skipcond

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#931]
```
commit 30257c1691dcd4151cc9c205e261e23fc33544cf
Author: Sulverus <sulverus@gmail.com>
Date:   Mon Apr 27 15:14:37 2015 +0300

    module.api skip condition

diff --git a/test/app/module_api.skipcond b/test/app/module_api.skipcond
new file mode 100644
index 0000000..a1bd98d
--- /dev/null
+++ b/test/app/module_api.skipcond
@@ -0,0 +1,5 @@
+import os
+
+# skip test if we are testing tarantool from package
+if os.path.exists('/usr/bin/tarantool'):
+    self.skip=1
```

Please remove this stupid skipcond - module api should work fine on Tarantool from rpm/deb package.

BTW, `os.path.exists('/usr/bin/tarantool')` is incorrect. For example, I have tarantool installed from deb package, but I run tests in my source directory.

**Comment by Sulverus** [comment]
Fixed workaround  for test-run. If we run tests without build - there is no `module_api.so` file. 
Skipcond updated: now test is enabled for any builds and for package testing if `module_api.so` exists
