### ISSUE TITLE
Race conditions between space initialization and space writes make WAL corrupted. Need tarantool instance lifecycle states improved.

### ISSUE THREAD

**Issue by sergepetrenko** [tarantool/tarantool#9330]
### Discussed in https://github.com/orgs/tarantool/discussions/9325

<div type='discussions-op-text'>

<sup>Originally posted by **extde** November  2, 2023</sup>

Got an issue with corrupted WAL log due to race conditions between space initialization and space writes during tarantool instance startup. 
Looks like a bug because WAL is corrupted, restart is not possible.
See details here - https://stackoverflow.com/a/77408135/2412036:

<details><summary>Added by @sergepetrenko: an extract from stackoverflow</summary>

> I got similar error in Tarantool 2.11.1:
> ```
> 2023-11-01 21:44:57 Loading existing configuration file: /etc/tarantool/config.yml
> 2023-11-01 21:44:57 Config:
> 2023-11-01 21:44:57 ---
> 2023-11-01 21:44:57 pid_file: /var/run/tarantool/tarantool.pid
> 2023-11-01 21:44:57 vinyl_dir: /var/lib/tarantool
> 2023-11-01 21:44:57 log_level: 5
> 2023-11-01 21:44:57 memtx_dir: /var/lib/tarantool
> 2023-11-01 21:44:57 log_format: plain
> 2023-11-01 21:44:57 listen: 3301
> 2023-11-01 21:44:57 wal_dir: /var/lib/tarantool
> 2023-11-01 21:44:57 force_recovery: false
> 2023-11-01 21:44:57 ...
> 2023-11-01 21:44:57 
> 2023-11-01 21:44:57 2023-11-01 18:44:57.257 [1] main/103/tarantool-entrypoint.lua I> Tarantool 2.11.1-0-g96877bd35 Linux-x86_64-RelWithDebInfo
> 2023-11-01 21:44:57 2023-11-01 18:44:57.257 [1] main/103/tarantool-entrypoint.lua I> log level 5
> 2023-11-01 21:44:57 2023-11-01 18:44:57.257 [1] main/103/tarantool-entrypoint.lua I> wal/engine cleanup is paused
> 2023-11-01 21:44:57 2023-11-01 18:44:57.257 [1] main/103/tarantool-entrypoint.lua I> mapping 268435456 bytes for memtx tuple arena...
> 2023-11-01 21:44:57 2023-11-01 18:44:57.257 [1] main/103/tarantool-entrypoint.lua I> Actual slab_alloc_factor calculated on the basis of desired slab_alloc_factor = 1.044274
> 2023-11-01 21:44:57 2023-11-01 18:44:57.257 [1] main/103/tarantool-entrypoint.lua I> mapping 134217728 bytes for vinyl tuple arena...
> 2023-11-01 21:44:57 2023-11-01 18:44:57.258 [1] main/103/tarantool-entrypoint.lua/box.upgrade I> Recovering snapshot with schema version 2.11.1
> 2023-11-01 21:44:57 2023-11-01 18:44:57.261 [1] main/103/tarantool-entrypoint.lua I> update replication_synchro_quorum = 1
> 2023-11-01 21:44:57 2023-11-01 18:44:57.261 [1] main/103/tarantool-entrypoint.lua I> instance uuid be685c81-ad95-416e-9972-531c539bb677
> 2023-11-01 21:44:57 2023-11-01 18:44:57.261 [1] main/103/tarantool-entrypoint.lua I> instance vclock {1: 70}
> 2023-11-01 21:44:57 2023-11-01 18:44:57.261 [1] main/103/tarantool-entrypoint.lua I> tx_binary: bound to 0.0.0.0:3301
> 2023-11-01 21:44:57 2023-11-01 18:44:57.261 [1] main/103/tarantool-entrypoint.lua I> recovery start
> 2023-11-01 21:44:57 2023-11-01 18:44:57.261 [1] main/103/tarantool-entrypoint.lua I> recovering from `/var/lib/tarantool/00000000000000000000.snap'
> 2023-11-01 21:44:57 2023-11-01 18:44:57.266 [1] main/103/tarantool-entrypoint.lua I> cluster uuid 3db61092-9f40-44b6-ba2c-1d8cf2c46624
> 2023-11-01 21:44:57 2023-11-01 18:44:57.273 [1] main/103/tarantool-entrypoint.lua I> assigned id 1 to replica be685c81-ad95-416e-9972-531c539bb677
> 2023-11-01 21:44:57 2023-11-01 18:44:57.273 [1] main/103/tarantool-entrypoint.lua I> update replication_synchro_quorum = 1
> 2023-11-01 21:44:57 2023-11-01 18:44:57.273 [1] main/103/tarantool-entrypoint.lua I> recover from `/var/lib/tarantool/00000000000000000000.xlog'
> 2023-11-01 21:44:57 2023-11-01 18:44:57.273 [1] main/103/tarantool-entrypoint.lua I> done `/var/lib/tarantool/00000000000000000000.xlog'
> 2023-11-01 21:44:57 2023-11-01 18:44:57.273 [1] main/103/tarantool-entrypoint.lua I> recover from `/var/lib/tarantool/00000000000000000066.xlog'
> 2023-11-01 21:44:57 2023-11-01 18:44:57.273 [1] main/103/tarantool-entrypoint.lua recovery.cc:161 W> file `/var/lib/tarantool/00000000000000000066.xlog` wasn't correctly closed
> 2023-11-01 21:44:57 2023-11-01 18:44:57.273 [1] main/103/tarantool-entrypoint.lua I> recover from `/var/lib/tarantool/00000000000000000069.xlog'
> 2023-11-01 21:44:57 2023-11-01 18:44:57.273 [1] main/103/tarantool-entrypoint.lua recovery.cc:161 W> file `/var/lib/tarantool/00000000000000000069.xlog` wasn't correctly closed
> 2023-11-01 21:44:57 2023-11-01 18:44:57.274 [1] main/103/tarantool-entrypoint.lua I> ready to accept requests
> 2023-11-01 21:44:57 2023-11-01 18:44:57.274 [1] main/103/tarantool-entrypoint.lua I> leaving orphan mode
> 2023-11-01 21:44:57 2023-11-01 18:44:57.274 [1] main/106/gc I> wal/engine cleanup is resumed
> 2023-11-01 21:44:57 2023-11-01 18:44:57.274 [1] main/103/tarantool-entrypoint.lua/box.load_cfg I> set 'listen' configuration option to 3301
> 2023-11-01 21:44:57 2023-11-01 18:44:57.274 [1] main/107/checkpoint_daemon I> scheduled next checkpoint for Wed Nov  1 20:30:51 2023
> 2023-11-01 21:44:57 2023-11-01 18:44:57.276 [1] main/103/tarantool-entrypoint.lua/socket I> tcp_server: remove dead UNIX socket: /var/run/tarantool/tarantool.sock
> 2023-11-01 21:44:57 2023-11-01 18:44:57.277 [1] main/118/console/unix/:/var/run/tarantool/tarantool.sock/socket I> started
> 2023-11-01 21:44:57 2023-11-01 18:44:57.277 [1] main/103/tarantool-entrypoint.lua space.h:425 E> ER_NO_SUCH_INDEX_ID: No index #0 is defined in space 'productHistory'
> 2023-11-01 21:44:57 2023-11-01 18:44:57.277 [1] main space.h:425 E> ER_NO_SUCH_INDEX_ID: No index #0 is defined in space 'productHistory'
> 2023-11-01 21:44:57 2023-11-01 18:44:57.277 [1] main F> fatal error, exiting the event loop
> ```
> After investigation I found that the issue related to race conditions between space initialization and space writes during Tarantool instance startup.
> So, I have space initialization (create, format, pk create) in one module, which is triggered by box.watch('box.status') when is_ro == false and is_ro_cfg == false and status == 'running'.
> At the same time I run write tests against this newly created space in instance startup script after box.cfg{} and box.ctl.wait_rw().
> Write tests finished without errors, but WAL log becomes corrupted.
> I got an issue on next startup after instance termination.
> 
> Solution:
> 
> Make sure space initialization is finished completely before any attempt to write to it.
> Unfortunately it is not really possible to put DDL into transaction - there are exceptions in transaction management ([see Rule #3](https://www.tarantool.io/en/doc/latest/reference/reference_lua/box_txn_management/))

</details>

[tarantool race conditions example.zip](https://github.com/tarantool/tarantool/files/13237875/tarantool.race.conditions.example.zip)

It would be nice to have clear set of tarantool instance lifecycle states, including ones for spaces initialization, business logic initialization, instance termination, intermediate states (like service overloaded), etc.
It would be nice if this set would be customizable.</div>

**Comment by Gumix** [comment]
I'm unable to reproduce the exact error using provided example.zip, but if I get it right, there are 2 concurrent fibers that perform:

1. data insertions;
2. space drop, space create, index create.

It's possible that fiber №1 successfully inserted some data into the old space (which was recovered from the snap), then fiber №2 recreated the space, but didn't create the index, because it switched to another fiber, then for some reason Tarantool exited ungraceful, that's why the WAL is corrupted. In other words, a simplified reproducer looks like:

#### run1.lua

```lua
os.execute('rm -rf *.snap *.xlog')
box.cfg{}
box.schema.space.create('test')
box.space.test:create_index('id')
for i = 0, 50 do
    box.space.test:replace{i}
end
box.space.test:drop()
box.schema.space.create('test')
error('some error')
```

```
$ tarantool run1.lua
2023-11-10 22:44:54.401 [1] main/103/run1.lua I> Tarantool 2.11.1-0-g96877bd35 Linux-x86_64-Debug
[...]
2023-11-10 22:44:54.442 [1] main/103/run1.lua I> ready to accept requests
2023-11-10 22:44:54.442 [1] main/104/gc I> wal/engine cleanup is resumed
2023-11-10 22:44:54.442 [1] main/105/checkpoint_daemon I> scheduled next checkpoint for Sat Nov 11 00:19:20 2023
2023-11-10 22:44:54.447 [1] main utils.c:610 E> LuajitError: run1.lua:10: some error
2023-11-10 22:44:54.447 [1] main F> fatal error, exiting the event loop
```

#### run2.lua

```lua
box.cfg{}
box.space.test:get{1}
```

```
$ tarantool run2.lua
2023-11-10 22:45:31.621 [2] main/103/run2.lua I> Tarantool 2.11.1-0-g96877bd35 Linux-x86_64-Debug
[...]
2023-11-10 22:45:31.659 [2] main/103/run2.lua I> recover from `./00000000000000000000.xlog'
2023-11-10 22:45:31.660 [2] main/103/run2.lua recovery.cc:161 W> file `./00000000000000000000.xlog` wasn't correctly closed
2023-11-10 22:45:31.660 [2] main/103/run2.lua I> ready to accept requests
2023-11-10 22:45:31.660 [2] main/103/run2.lua I> leaving orphan mode
2023-11-10 22:45:31.660 [2] main/104/gc I> wal/engine cleanup is resumed
2023-11-10 22:45:31.660 [2] main/105/checkpoint_daemon I> scheduled next checkpoint for Fri Nov 10 23:56:04 2023
2023-11-10 22:45:31.662 [2] main schema.lua:1880 E> ER_NO_SUCH_INDEX_ID: No index #0 is defined in space 'test'
2023-11-10 22:45:31.662 [2] main F> fatal error, exiting the event loop
```

@extde, if you believe that there is a Tarantool bug, please provide us with verbose logs for **both** runs for further investigation.
