### ISSUE TITLE
`on_rollback` function parameter is empty for some types of rollbacks

### ISSUE THREAD

**Issue by Gumix** [tarantool/tarantool#9340]
**Bug description**

Currently there are 5 main reasons why a transaction can be aborted:

1. Explicit `box.rollback()`;
2. WAL write failure;
3. A conflict;
4. Fiber yield (without MVCC);
5. Timeout.

However `on_rollback` triggers are invoked with correct arguments only for 1-3, in other cases the trigger-function parameter is empty.

**Steps to reproduce**

```lua
local fiber = require('fiber')
local s = box.schema.space.create('test')
s:create_index('pk')

function on_rollback(iterator)
    print('on_rollback:')
    for num, old_tuple, new_tuple, space_id in iterator() do
        print(string.format('%d. space_id = %d, old_tuple = %s, new_tuple = %s',
                            num, space_id, tostring(old_tuple), tostring(new_tuple)))
    end
end

print('box.begin()')
box.begin()
  s:insert{1}
  s:insert{2}
  box.on_rollback(on_rollback)
  fiber.yield()
  pcall(s.insert, s, {3})
  pcall(s.insert, s, {4})
print('box.commit()')
pcall(box.commit)
print('the end')
```

**Actual behavior**

```
box.begin()
box.commit()
on_rollback:
the end
```

**Expected behavior**

```
box.begin()
box.commit()
on_rollback:
1. space_id = 512, old_tuple = nil, new_tuple = [2]
2. space_id = 512, old_tuple = nil, new_tuple = [1]
the end
```

**Comment by unera** [comment]
Hi,

a user must access all changed tuples in the trigger in all cases.

**Comment by unera** [comment]
If a tuple was passed to on_replace, before_commit, etc have to be passed to on_rollback.
