### ISSUE TITLE
[svace] dereference of NULL at src/box/sql/where.c:1250

### ISSUE THREAD

**Issue by sergepetrenko** [tarantool/tarantool#9343]
Found by svace: [report](https://svacer.tarantool.io/mode/review/project/9ae45b10-738c-4bca-b373-1a40a2646c6c/branch/3d7c9327-519e-45f4-9733-8f8bf5e1b384/snapshot/0cfe02ce-ff94-46a8-afc5-241aef25eafc/filter/eyJ3YXJuQ2xhc3MiOlsiREVSRUZfT0ZfTlVMTC5DT05TVC9DWFgiXX0=/marker/eyJtYXJrZXJJRCI6IjRlZGJhYjE1LTRiNTUtNDE3NS05ZTI3LTZmZmY5MjMxM2Y3ZiIsImZpbGUiOiIvdGFyYW50b29sLXNkay90YXJhbnRvb2wtMy4wL3RhcmFudG9vbC9zcmMvYm94L3NxbC93aGVyZS5jIn0=)

Relevant code: https://github.com/tarantool/tarantool/blob/4f85d27efdf443cccf18ba29a3221f524904cce2/src/box/sql/where.c#L1231-L1251

`pVal` is initialized to `NULL` at line 1231, and never modified until it is dereferenced inside `mem_cmp_scalar` at line 1250.

**Comment by ImeevMA** [comment]
While this is true, this function is only called in where.c:1488. However, this is inside an `if` in which the condition is always false due to statistics being disabled (stat == NULL on line 1343, and then it becomes equal to surrogate_stat, which has a sample_count field == 0).
