### ISSUE TITLE
[svace] dereference of NULL at src/box/sql/build.c:780

### ISSUE THREAD

**Issue by sergepetrenko** [tarantool/tarantool#9344]
Reported by svace: [report](https://svacer.tarantool.io/mode/review/project/9ae45b10-738c-4bca-b373-1a40a2646c6c/branch/3d7c9327-519e-45f4-9733-8f8bf5e1b384/snapshot/0cfe02ce-ff94-46a8-afc5-241aef25eafc/filter/eyJ3YXJuQ2xhc3MiOlsiREVSRUZfQUZURVJfTlVMTC5FWC9DWFgiXX0=/marker/eyJtYXJrZXJJRCI6IjhjYWZkN2NiLWE4ZWEtNDZhZi04YWZjLTcyNDdiMmU5ZWRjMCIsImZpbGUiOiIvdGFyYW50b29sLXNkay90YXJhbnRvb2wtMy4wL3RhcmFudG9vbC9zcmMvYm94L3NxbC9idWlsZC5jIn0=)

https://github.com/tarantool/tarantool/blob/4f85d27efdf443cccf18ba29a3221f524904cce2/src/box/sql/build.c#L769-L780

Judging by lines 769-771 `parser->create_column_def.space` may be `NULL`, but later `sql_ck_unique_name_new` is called on line 780, which dereferences `parser->create_column_def.space`.

**Comment by ImeevMA** [comment]
Duplicate of #8392.

**Comment by sergepetrenko** [comment]
Duplicate of #8392
