### ISSUE TITLE
Required information about listening host/port of running tarantool

### ISSUE THREAD

**Issue by Mons** [tarantool/tarantool#935]
Old tarantool 1.5 looked like
```
497      25238  0.2  0.5 241348  2648 ?        Ssl  Jul16   7:08 tarantool_box: primary@fluor pri: 13013 sec: 13014 adm: 13015 rpl: 13016, ip: 0.0.0.0          
```
So, monitoring utility could connect to running instance and gather statistics information.

With 1.6 we for now have only 
```
497       9456  1.5  0.2 642024  1096 ?        Sl   Jul06 252:09 /opt/mailru/tarantool16/root/usr/bin/tarantool tnt16_master1.lua: running@master1                
```
which is almost useless.

We need at least one way to connect.
1. I propose the following order of output in proctitle: console, tcp4 socket, tcp6 socket, unix socket.
2. I propose the following proctitle:
```
tarantool: <role>@<custom_proc_title>: con:127.0.0.1:3302 ipv4:127.0.0.2:3301 unix:/var/run/tarantool/...
```

**Comment by kostja** [comment]
We need to bind libproctitle to Lua

**Comment by kostja** [comment]
This is done now on the script level, since proc title can be changed from Lua script, so one can export this manually with requier('title').set_custum(string)
