### ISSUE TITLE
rename "GT" iterator on hash index to something else

### ISSUE THREAD

**Issue by funny-falcon** [tarantool/tarantool#938]
"GT" iterator's behaviour is very confusing on hash indices

``` lua
local log = require 'log'

box.cfg { wal_dir='.', snap_dir='.' }
local s = box.schema.space.create('test', {id = 513, if_not_exists=true})
s:create_index('pk', {type='hash', parts = {1, 'num'}, if_not_exists=true})
s:put({1})
s:put({2})
s:put({3})
s:put({100})
s:put({200})
s:put({300})
local rows = s:select(1, {iterator= 'GT'})
print("rows size = ", #rows)
for _, row in ipairs(rows) do
    print(row[1])
end
```

returns to me

```
$ tarantool config.lua
....
rows size =     4
2
3
100
300
```

While it could be understood, perhaps it is better to rename it.

I propose name "CONT" - continue iteration. Other good name is "NEXT" - next bunch of rows.

**Comment by kostja** [comment]
This is legacy from 1.5, we kept it this way since it was this way in 1.5. Scheduling for 1.7, where we are going to introduce consistent read views, so there will be changes in iteration api anyway.

**Comment by kostja** [comment]
Nobody cares -> won't fix. I think SQL makes the entire problem of using iterators from Lua obsolete.
