### ISSUE TITLE
[svacer] unchecked `mp_read_int64()` function result in src/box/lua/net_box.c:1753

### ISSUE THREAD

**Issue by sergepetrenko** [tarantool/tarantool#9395]
Svacer [link](https://svacer.tarantool.io/mode/review/project/9ae45b10-738c-4bca-b373-1a40a2646c6c/branch/3d7c9327-519e-45f4-9733-8f8bf5e1b384/snapshot/d8dd771d-d0f3-4a24-897f-e7573e0a068b/filter/eyJ3YXJuQ2xhc3MiOlsiVU5DSEVDS0VEX0ZVTkNfUkVTLlNUQVQvQ1hYIl19/marker/eyJtYXJrZXJJRCI6ImU2NjFiMWJhLWQ4NGItNDgzZC1hNzA0LWUxMGNlOTMwODk2MSIsImZpbGUiOiIvdGFyYW50b29sLXNkay90YXJhbnRvb2wtMy4wL3RhcmFudG9vbC9zcmMvYm94L2x1YS9uZXRfYm94LmMifQ==)
`mp_read_int64()` result is ignored, even though it can return an error when passed a MP_UINT not fitting into int64_t.
https://github.com/tarantool/tarantool/blob/1f128c51aa6af9825170ac9fbb77eb74857154a1/src/box/lua/net_box.c#L1887-L1894

**Comment by locker** [comment]
This particular issue is just a tip of the iceberg: in general, net.box assumes that responses received from a Tarantool server a well-formed. We'll fix it in the scope of https://github.com/tarantool/tarantool/issues/9416.
