### ISSUE TITLE
Report errors on `tarantoolctl start`

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#940]
Please print critical errors to console (or at least return error code to init script) if `tarantoolctl start` failed to start instance. For example, user starts instance with box.cfg { arena = 5\* 1024 \* 1024 }. Tarantool fails to allocate memory and exits. `/etc/init.d/tarantool start` prints [OK]. User believe that Tarantool started successfully.

**Comment by rtsisyk** [comment]
Requires significant changes in box_init() process.
Probably for 1.7.x, definitely not for 1.6.8.
See also #1213

**Comment by bigbes** [comment]
`box.cfg` panics on all errors (if `box_config_check` can't detect them):
```
-- box.cfg{ arena = 5* 1024 * 1024 }
-- box.cfg{ listen = "11:11"}
```

**Comment by kostja** [comment]
Is this done?

**Comment by rtsisyk** [comment]
It doesn't:
```
tarantool
tarantool: version 1.7.2-137-ge3069be
type 'help' for interactive help
tarantool> box.cfg { slab_alloc_arena = 100500, background = true, logger = 'tarantool.log', pid_file='tarantool.pid' }
roman@desktop:~$ <!-- TERMINAL IS BROKEN
roman@desktop:~$ reset
roman@desktop:~$ cat tarantool.log 
2016-11-22 11:11:41.059 [25639] main/101/interactive C> version 1.7.2-137-ge3069be
2016-11-22 11:11:41.059 [25639] main/101/interactive C> log level 5
2016-11-22 11:11:41.059 [25639] main/101/interactive I> mapping 107911053312000 bytes for tuple arena...
2016-11-22 11:11:41.059 [25639] main/101/interactive F> failed to preallocate 107911053312000 bytes: Cannot allocate memory, check option 'slab_alloc_arena' in box.cfg(..)
2016-11-22 11:11:41.059 [25639] main/101/interactive F> failed to preallocate 107911053312000 bytes: Cannot allocate memory, check option 'slab_alloc_arena' in box.cfg(..)

```

Please note that it is not a problem of tarantooctl, it is problem of daemon itself.
I propose to fix this problem via NOTIFY_SOCKET (#1923) on systemd-enabled systemd and then move this ticket to **wishlist** for all other systems.

**Comment by bigbes** [comment]
What should be done here?

**Comment by bigbes** [comment]
Two ways, both must be implemented:

1. using [`sd_notify`](https://www.freedesktop.org/software/systemd/man/sd_notify.html) for support of systemd systems
    - inside `box_init`, probably
2. using waiting in the parent process
    - If `box.cfg{ background = true }`, then we're running daemonize.
    - Inside daemonize we're waiting for event from child process (using unix socket or pipe or something)

**Comment by rtsisyk** [comment]
Done
