### ISSUE TITLE
Add an alertion on WAL failure

### ISSUE THREAD

**Issue by alyapunov** [tarantool/tarantool#9405]
Now in case of `ER_WAL_IO` tarantool just rollbacks transaction and throws this error to the user.

This error seems to be exceptional and dangerous. I see no general correct behavior, different users may require different actions, there may "send alert SMS" or "change state to RO" or "retire from leader role in replicaset".

So we should provide an broadcasted variable, such as lua `box.wal_error_count` and C `wal_error_count`.

Needed for https://github.com/tarantool/tarantool/issues/9383

**Comment by unera** [comment]
Failover is an external application, so if it has pub/sub mechanism, failover will able to switch master/slave.

**Comment by grafin** [comment]
> Failover is an external application, so if it has pub/sub mechanism, failover will able to switch master/slave.

Not always. RAFT is part of tarantool core (https://github.com/tarantool/tarantool/issues/9399)
