### ISSUE TITLE
Support string/number aliases for STR/NUM

### ISSUE THREAD

**Issue by monolithed** [tarantool/tarantool#942]
I'm honestly a bit confused.

```lua
space:create_index('primary', {
    parts = {
        host, 'string',
        port, 'number'
    }
})
```
It seems more intuitive and consistent with Lua standard types

https://youtu.be/bM0zK0lwEz8?t=18m46s :dancer:

**Comment by rtsisyk** [comment]
This task is related to #1534, moving to 1.7.x.

**Comment by rtsisyk** [comment]
Discussed today: change `str` to `string`, keep `str` until 1.8.
