### ISSUE TITLE
UPDATE by non-primary index

### ISSUE THREAD

**Issue by funny-falcon** [tarantool/tarantool#943]
Documentation on [IProto Protocol](http://tarantool.org/doc/dev_guide/box-protocol.html) states, that UPDATE accepts field 0x11 - `INDEX_ID` .

But in reality this field is ignored (and could be even missed), and key is always assumed to be primary key.

If `INDEX_ID` is not part of a protocol, then documentation should be fixed. If it is "reserved for future usage", then at least it should be checked for equality to primary index.

**Comment by funny-falcon** [comment]
(same for deletion)

**Comment by kostja** [comment]
Thank you for your patch, I pushed it into 1.6.6.
