### ISSUE TITLE
 Function name is too long

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool#944]
32 chars are no more enough for everyone. Please increase this limit to allow proper operation of C procedures (`modulename.functioname` syntax)

**Comment by Gerold103** [comment]
Which limit is needed? And do we need any limit?

**Comment by Gerold103** [comment]
Remove limit.

**Comment by Gerold103** [comment]
1. Добавить опцию 'is_long' к iproto запросу, и если он установлен, то копировать struct request на отдельную память вместо сохранения в ibuf.
Плюсы: очень просто, гибко, можно использовать не только для call. Пользователь лучше знает, какие у него запросы долгие.
Минусы: опцию могут использовать неоправданно часто.

2. Сделать фидбек от tx по событию пропажи надобности в struct request.
Плюсы: гибко, можно применять для любых запросов, нет копирования, когда нет необходимости. Если tx поток завис, то он не пошлет сигнал об освобождении struct request, а значит iproto не начитает лишней фигни, пока tx не отвдуплит. Пригодится для интерактивных транзакций - там приходится копировать, так как разные запросы одной транзакции раскидываются по разным ibuf, и могут даже оттуда удаляться. Тогда интерактивная транзакция могла бы копировать, а потом слать сигнал об освобождении request.

3. Всегда копировать struct request для misc запросов.
Плюсы: очень просто.
Минусы: не решает проблему с interactive iproto tx, можно завалить застрявший tx кучей запросов, копирование делается даже на быстрые запросы, замедляя их.

**Comment by Gerold103** [comment]
Test:
```Lua
box.cfg{listen=3313}
function aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa()
    return 'kek'
end
name = 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
box.schema.func.create(name)
```
