### ISSUE TITLE
Consider eliminating `tarantoolctl` stuff before 3.0.0 release

### ISSUE THREAD

**Issue by ylobankov** [tarantool/tarantool#9443]
As we all know, the `tarantoolctl` script is going to be replaced by using the new [tt](https://github.com/tarantool/tt) utility. Due to this fact, it would be good to eliminate all stuff related to `tarantoolctl` before release 3.0.0.

**Comment by sergos** [comment]
We should follow the deprecation policy.
The task requires update to public documentation.
There's also a lot of questions on how to migrate 2.x to 3.0 - seems like tt is the only way.

**Comment by Totktonada** [comment]
See also https://github.com/tarantool/tarantool-qa/issues/208.
