### ISSUE TITLE
[svacer] possibly wrong arguments order in `sqlMatchSpanName` call

### ISSUE THREAD

**Issue by Astronomax** [tarantool/tarantool#9445]
Svacer [link](https://svacer.tarantool.io/mode/review/project/9ae45b10-738c-4bca-b373-1a40a2646c6c/branch/3d7c9327-519e-45f4-9733-8f8bf5e1b384/snapshot/9aececf2-bf6f-4dca-9f83-364b301fbaa6/filter/eyJ3YXJuQ2xhc3MiOlsiV1JPTkdfQVJHVU1FTlRTX09SREVSL0NYWCJdfQ==/marker/eyJtYXJrZXJJRCI6ImQ2OTMzYjc2LTg2ZmMtNDllYS1hODRkLWIwMjNlYjM5Yjg5NSIsImZpbGUiOiIvdGFyYW50b29sLXNkay90YXJhbnRvb2wtMy4wL3RhcmFudG9vbC9zcmMvYm94L3NxbC9yZXNvbHZlLmMifQ==)

Relevant code:
https://github.com/tarantool/tarantool/blob/e2851883cd4c23d41bd9aec23fad06fd10d39c45/src/box/sql/resolve.c#L191-L192
Review following parameters and their corresponding arguments: old_col(old_tab), old_tab(old_col)
https://github.com/tarantool/tarantool/blob/e2851883cd4c23d41bd9aec23fad06fd10d39c45/src/box/sql/resolve.c#L156-L157

**Comment by ImeevMA** [comment]
True. Example of wrong result:
```
tarantool> box.execute([[CREATE TABLE A1(B1 INT PRIMARY KEY, A2 INT);]])
---
- row_count: 1
...

tarantool> box.execute([[CREATE TABLE A2(B2 INT PRIMARY KEY, A1 INT);]])
---
- row_count: 1
...

tarantool> box.execute([[INSERT INTO A1 VALUES(1, 2);]])
---
- row_count: 1
...

tarantool> box.execute([[INSERT INTO A2 VALUES(1, 3);]])
---
- row_count: 1
...

tarantool> box.execute([[SELECT a1.a2 FROM (SEQSCAN a1 INNER JOIN a2 ON b1=b2) AS j1;]])
---
- metadata:
  - name: a1.a2
    type: integer
  rows:
  - [3]
...

tarantool> box.execute([[SELECT A1.A2 FROM (SEQSCAN A1 INNER JOIN A2 ON B1=B2) AS J1;]])
---
- metadata:
  - name: A1.A2
    type: integer
  rows:
  - [2]
...
```
