### ISSUE TITLE
[svacer] `sym_hdr.sh_entsize` must be tested to be zero before division

### ISSUE THREAD

**Issue by Astronomax** [tarantool/tarantool#9456]
Svacer [link](https://svacer.tarantool.io/mode/review/project/9ae45b10-738c-4bca-b373-1a40a2646c6c/branch/3d7c9327-519e-45f4-9733-8f8bf5e1b384/snapshot/9aececf2-bf6f-4dca-9f83-364b301fbaa6/filter/eyJ3YXJuQ2xhc3MiOlsiRElWSVNJT05fQllfWkVSTy5FWC9DWFgiXX0=/marker/eyJtYXJrZXJJRCI6IjJiOTRlODQ1LTYwNTItNDFkYy05NjM1LTYzODkyMWNjNmJmYSIsImZpbGUiOiIvdGFyYW50b29sLXNkay90YXJhbnRvb2wtMy4wL3RhcmFudG9vbC90aGlyZF9wYXJ0eS9sdWFqaXQvc3JjL2xqX3N5bXRhYi5jIn0=)
Relevant code: [LuaJIT](https://github.com/tarantool/luajit/blob/fef60a1052b8444be61e9a9932ab4875aff0b2ed/src/lj_symtab.c#L200-L213)
As I see at `dump_sht_symtab` we validate many aspects of the input `ELF` file, therefore it would be good to validate this point too.

**Comment by fckxorg** [comment]
From `man 5 elf`:
```
 sh_entsize
              Some sections hold a table of fixed-sized entries, such as
              a symbol table.  For such a section, this member gives the
              size in bytes for each entry.  This member contains zero
              if the section does not hold a table of fixed-size
              entries.
```

The section in question is `SHT_SYMTAB`, and, as one can clearly see above, it is specifically pointed out in the manpage that this section has fixed-size entries, so `sh_entsize` must be non-zero.

One can argue that the ELF file itself can be malformed, but while taking that argument into consideration, we should also remember that the `dump_sht_symtab` function only processes ELF files that are already loaded into our runtime. So considering that this ELF file has already been successfully loaded, it must be valid.

With that in mind, this issue should be considered a false positive.
