### ISSUE TITLE
iproto connection gets stuck after a long polling request

### ISSUE THREAD

**Issue by Mons** [tarantool/tarantool#946]
If there is a long polling statement and a bunch of requests coming after, in the same connection, sooner or later the connection will become stuck and not responding to the original request.

simple perl example, to reproduce:
(EV-Tarantool could be taken from here: https://github.com/Mons/EV-Tarantool)

``` perl
#!/usr/bin/env perl

use strict;
use EV;
use EV::Tarantool;
use Scalar::Util qw(weaken);
use List::Util qw(max);

my $c = EV::Tarantool->new({
    reconnect => 0,
    timeout   => 1,
    host      => '127.0.0.1',
    port      => 33013,
    connected => sub {
        my $c = shift;
        warn "connected @_";
        my $j;
        $c->lua('box.dostring',['box.fiber.sleep(10)'], { timeout => 0 }, sub {
            warn "Reponse";
            undef $j;
            EV::unloop;
        });
        my $lastseq = 0;
        $j = sub {
            $c->lua('box.time',[], sub {
                if (my $res = shift) {
                    $lastseq = max($lastseq,$res->{id});
                } else {
                    warn "last good seq = $lastseq; @_";
                }
                $j or return;
                $j->();
            })
        };$j->();
    },
    disconnected => sub {
        shift;
        warn "@_";
        EV::unloop;
    }
});
$c->connect();

EV::loop;
```

**Comment by rtsisyk** [comment]
See also #1889

**Comment by Gerold103** [comment]
Normal test case:
```Lua
box.cfg{listen=3313, readahead=128}
remote = require('net.box')
fiber = require('fiber')
box.schema.user.grant('guest', 'read,write,execute', 'universe')
cn = remote.connect(box.cfg.listen)
cn:ping()
function long_call(param)
    fiber.sleep(100000)
    return 'ok'
end
function normal_call(param)
    return 'fast_ok'
end

call1_ret = nil
call2_ret = nil
call3_ret = nil
longs = string.rep('a', 8192)
function call1()
    call1_ret = cn:call('long_call', {longs})
end
function call2()
    call2_ret = cn:call('long_call', {longs})
end
function call3()
    call3_ret = cn:call('normal_call')
end
f1 = fiber.create(call1)
f2 = fiber.create(call2)
cn:call('normal_call')
```

**Comment by Gerold103** [comment]
1. Добавить опцию 'is_long' к iproto запросу, и если он установлен, то копировать struct request на отдельную память вместо сохранения в ibuf.
Плюсы: очень просто, гибко, можно использовать не только для call. Пользователь лучше знает, какие у него запросы долгие.
Минусы: опцию могут использовать неоправданно часто.

2. Сделать фидбек от tx по событию пропажи надобности в struct request.
Плюсы: гибко, можно применять для любых запросов, нет копирования, когда нет необходимости. Если tx поток завис, то он не пошлет сигнал об освобождении struct request, а значит iproto не начитает лишней фигни, пока tx не отвдуплит. Пригодится для интерактивных транзакций - там приходится копировать, так как разные запросы одной транзакции раскидываются по разным ibuf, и могут даже оттуда удаляться. Тогда интерактивная транзакция могла бы копировать, а потом слать сигнал об освобождении request.

3. Всегда копировать struct request для misc запросов.
Плюсы: очень просто.
Минусы: не решает проблему с interactive iproto tx, можно завалить застрявший tx кучей запросов, копирование делается даже на быстрые запросы, замедляя их.

**Comment by Gerold103** [comment]
Blocked by #2619.

**Comment by Gerold103** [comment]
Проблемы текущего решения:
1. Частичная запись obuf[0] и продолжение записи из obuf[1] - перемешивание сообщений.
2. iobuf_reset_mt удаляет obuf, в который в данный момент идет запись.

Решения обоих проблем:
1. - Для защиты от частичной записи и перемешивания сообщений можно запоминать недописанный буфер и продолжать запись с него.
   - Длф защиты от iobuf_reset_mt race можно рефать obuf при его отдаче в iproto_msg и анрефать при net_send_msg.
   Минусы: obuf может бесконтрольно расти, если будет рефаться множеством долгих call/eval.

2. - Решение частичной записи - см. 1.
   - Для защиты от iobuf_reset race box_process_call/eval может отправлять в iproto поток специальное сообщение о необходимости блокировки одного obuf от reset. Iproto блокирует этот obuf и отправляет ответ. Tx тред после получения ответа пишет в obuf. Блокировка снимается в net_send_msg. Фактически, блокировка тоже реф, так как один и тот же obuf может блокировать сразу много call/eval.

3. - Решение частичной записи - см. 1.
   - Отдавать в iproto_msg не obuf, а обертку над ним. Эта обертка рефает obuf. Если obuf слишком разросся и рефов не ноль, то под мутексом во всех iproto_obuf, в которые сейчас не идет запись, obuf из iproto подменяется на новый obuf и освобождает реф.
   - В tx треде, прежде чем писать в iproto_obuf, под мутексом устанавливаем, что запись началась, и выбираем, писать в оригинальный obuf или новый, выделенный специально для этого запроса. Это отчасти приближает pub sub, поскольку можно будет сделать новое сообщение, которое этот per request obuf записывает в сокет и делает его reset. Либо можно будет для этого запроса тоже сделать два ротирующихся obuf.

**Comment by rtsisyk** [comment]
4. Use a dedicated buffer for each response

**Comment by Gerold103** [comment]
5. Предполагает переделку iproto.cc и всех мест использования obuf.
Общая идея - один тред владеет одним obuf. Iproto свой obuf пишет в сокет, Tx свой obuf наполняет данными. Когда Iproto закончил запись в сокет, он посылает сообщение ротации в tx. Tx ротацию выполняет и посылает ответ в Iproto. Iproto, получив ответ, пишет дальше в сокет, но уже из другого obuf.
Как выполнять ротацию в tx? Там же явные указатели на obuf везде. Решение - обернуть obuf в специальный объект, например, iproto_buf. Все, кто сейчас пишет в obuf что-либо для iproto, будут теперь работать с iproto_buf. Внутри этого iproto_buf можно ротировать obuf как угодно.
Поскольку ротация будет происходить в Tx треде, это не сломает тех, кто сейчас ссылается на тот же iproto_buf.
```C

/* iproto.cc */

struct iproto_buf {
    struct obuf *obuf;
};

struct iproto_connection {
    /** Wrappers to use in TX thread. */
    struct iproto_buf obuf_wrappers[2];
    struct cmsg rotate_buf_msg;
    ....
};

/* box/call.h/.c */

struct obuf *obuf -> struct iproto_buf *buf;

void
tx_process_rotation(struct cmsg *m)
{
     struct iproto_connection *conn = container_of(m, struct iproto_connection, rotate_buf_msg);
     struct obuf *tmp = conn->obuf_wrappers[0].obuf;
     conn->obuf_wrappers[0].obuf = conn->obuf_wrappers[1].obuf;
     conn->obuf_wrappers[1].obuf = tmp;
}

/* iproto.cc */

void
net_end_rotation(struct cmsg *m)
{
    ev_io_feed_event(EV_WRITE);
}

```

**Comment by Gerold103** [comment]
The previous idea was rejected after implementation because of complexity.
New proposal:
```C
/* tx thread */

/**
 * Output buffer used by tx to write responses from one session,
 * and by iproto to flush data.
 */
struct connection_obuf {
    struct iproto_connection *conn;
    struct obuf *buf;
    bool is_scheduled_to_dump;
    struct rlist in_batch;
    /**
     * Message to send buffer or buffers batch to iproto thread.
     */
    struct cmsg flush_msg;
};

tx_current_obuf(struct iproto_connection *conn) {
    if (conn->current_obuf == NULL)
        conn->current_obuf = get_new_obuf();
    return conn->current_obuf;
}

finish_response(struct iproto_connection *conn) {
    static struct connection_obuf *batch = NULL;
    if (batch == NULL) {
        batch = conn->current_obuf;
        batch->is_scheduled_to_dump = true;
        schedule_batch_dump(batch);
        return;
    }
    if (!conn->current_obuf->is_scheduled_to_dump)
        rlist_add_entry(batch, conn->current_obuf, in_batch);
}

schedule_batch_dump(struct connection_obuf *batch) {
    cmsg_init(batch->flush_msg, {{net_flush_obufs, NULL}});
    cpipe_flush_input(batch->flush_msg);
}

tx_proces_...() {
    /* return empty buffers back to the cache. */
    if (! rlist_empty(msg->empty_buffers))
        return_empty_buffers_to_the_cache(&msg->empty_buffers);
    /* execute request ... */
    buffer = tx_current_obuf();
    write(buffer, response);
    finish_response();
}

/* iproto thread */

struct iproto_connection {
    /**
     * Empty buffers to send back to tx thread with a next
     * client request.
     */
+   struct rlist empty_buffers;

    /**
     * List of tx buffers to flush. There must be list, not single
     * buffer, because (1) any buffer can be flushed partialy and
     * next buffer can not be flushed until the current is not;
     * (2) new buffers can come from tx thread during while the
     * current is partially flushed.
     */
+   struct rlist buffers;
}

net_flush_obufs() {
    rlist_foreach_entry_safe(buffer, batch, in_batch) {
        rlist_add_tail_entry(conn->buffers, buffer, in_batch);
        ev_feed_event(buffer->conn->output, EV_WRITE);
    }
}

iproto_flush(struct iproto_connection *conn) {
    struct connection_obuf *current_buffer =
        rlist_first_entry(conn->buffers, in_batch);
    struct obuf *buf = current_buffer->obuf;
    flush(buf);
    if (obuf_used(buf) == 0) {
        rlist_del_entry(current_buffer, in_batch);
        rlist_add_entry(connection->empty_buffers, current_buffer,
                        in_batch);
    }
}

iproto_enqueue_batch() {
    struct iproto_msg *first_msg;
    /* prepare iproto_msgs to send, remember first ... */
    if (! rlist_empty(conn->empty_buffers)) {
        first_msg->empty_buffers = conn->empty_buffers;
        rlist_create(conn->empty_buffers);
    }
}
```

**Comment by unera** [comment]
Yesterday discussion. [There was my test case here](https://gist.github.com/unera/6047c0fb58d10b2e518799fd4a8d87ad)

**Comment by Gerold103** [comment]
Proposal for a new buffers:
https://gist.github.com/Gerold103/76d81fa8cb5c20631b584bff5b7f68b7

**Comment by Gerold103** [comment]
The buffer above can not be used - too complex.

**Comment by Gerold103** [comment]
There is a problem with a shared_buffer. The current implementation stores in each shared_iov a max_pos to determine, to which position in the memory block a consumer must consume. But max_pos can be concurrently modified by consumer and producer threads. The proposal is to remove max_pos and use each shared_iov completely, with no gaps. It means, that any reserve() can return less memory that requested.
In such a case we can not do a simple mp_encode_uint, because reserve() can return at first 1 byte and other bytes on a second reserve().
To solve this problem we need a msgpack serializer, which can write message pack partially in different memory blocks. It is linked also with lua/msgpack.c mpstream, which writes lua objects to message pack.

**Comment by Gerold103** [comment]
The new plan:
- To fix the problem, we need to send a special messages to discard ibuf;
- To discard ibuf, we need to unlink it with obuf;
- Unlinked obuf must be refactored to be cyclic (shared_buffer);
- To implement shared_buffer we need a msgpack serializer, which can write message pack in not monolite memory blocks.
- To implement a such mpstream we can refactor the existing one in lua/msgpack.h/.c. We need to add a virtual methods encode_uint/nil/array/map... together with virtual alloc/reserve. By this virtual methods, the partial message pack encoder can be implemented.

**Comment by Gerold103** [comment]
Discarded. The new proposal:
Create a shared_buffer_v2. It has iovec *iov. Each iov is owned either by producer or consumer. When can not reserve new block (producer met begin of a producer), yield until memory become available.

**Comment by Gerold103** [comment]
Новое ультра предложение.

Общий вид буффера в псевдокоде ниже. Предлагается не делать внутри
буффера возможность его уменьшать или увеличивать. Буффер - кольцо
iovec объектов, которые создаются в нем по мере продвижения
producer-а. Тогда буфер становится очень простым объектом. Единственная возможность его увеличивать - realloc какого-нибудь iovec, если запросили память больше, чем размеры всех iovec.

Задачу уменьшения и увеличения количества iovec предлагается
переложить на уровень выше. Для этого iproto соединение должно
при обнаружении необходимости увеличения буфера создать новый
буфер и передать его в использование в producer. При этом старый
буфер не будет уничтожен, пока не будет полностью потреблен
consumer-ом. Уменьшение точно так же - создаем новый буфер
поменьше, старый уничтожаем, когда он потреблен.
```C

struct shared_buffer {
	struct slab_cache *slabc;
	/** Currently used iov. */
	struct iovec *iov;
	/** Capacities of iovecs. */
	size_t * const capacity;
	/** Size for a new memory blocks. */
	size_t iovec_size;
	/** Max size for a realloc. */
	size_t iovec_max_size;
	int iov_count;
};

struct buffer_consumer {
	/** Consumer owns iovecs [cur, end). */
	int cur;
	int end;
	/**
	 * Consume() makes iov[cur].iov_base += consumed to
	 * make iov[cur].iov_base point to the beginning of not
	 * consumed memory.
	 * After the iov[cur] is fully consumed, its iov_base must
	 * be restored to initial value. To do it, make
	 * iov[cur].iov_base -= consumed_in_current.
	 */
	size_t consumed_in_current;
};

struct buffer_producer {
	/** Producer owns iovecs [cur, end). */
	int cur;
	int end;
	/**
	 * Producer writes new data to unused part
	 * iov[cur].iov_base. Produced_in_current stores offset to
	 * the unused memory.
	 */
	size_t produced_in_current;
};

/**
 * Savepoint to rollback to it, if an error on a user side occured
 * after reserve.
 */
struct buffer_producer_svp {
	int cur;
	size_t produced_in_current;
};

char *
buffer_producer_reserve(struct buffer_producer *producer, size_t size)
{
	/*
	 * Try to reserve in a current block.
	 * Try to reserve in a next block (it is empty,
	 * if exists).
	 * If not enough blocks or memory in a next block, realloc
	 * a current one, until a fixed limit.
	 * If a limit is reached, then out of memory.
	 */
}

char *
buffer_produce(struct buffer_producer *producer, size_t size)
{
	/* Reserve + propagate produced_in_current. */
}

void
buffer_consume(struct buffer_consumer *consumer, size_t size)
{
	/* Consume, restore iov_base in fully consumed iovecs. */
}

void
buffer_consumer_to_iovs(const struct buffer_consumer *consumer,
			const struct iovec **iov1, int *iov1_count,
			const struct iovec **iov2, int *iov2_count)
{
	/*
	 * It is neccessary to return two **iov, because a
	 * consumer end can be < consumer cur, and there is no
	 * single continuously iovec array owned by the consumer.
	 */
}
```

**Comment by locker** [comment]
What remains to be done:
1. Count references to iproto connections explicitly. Currently, we assume that a connection is idle if it has no data in the input buffer. This won't hold if we discard the input of a call request before completing the call. Hence we need to reference connections explicitly, e.g. by counting messages allocated for each connection. This should be pretty easy to do.
2. Refactor box_process_call() and box_process_eval() so that they are not passed the iproto output buffer explicitly. Why: the output buffer can be rotated while a call is in progress, in which case the call will write its result to a wrong buffer. To avoid that, we can use struct port to store the result of a call and write the result to the output buffer upon call completion, without a yield.
3. Apply the patch by @Gerold103 that makes call request discard input right after pushing call arguments to Lua stack. See 4206ec7228410fbf576a839320e6649d18f3f206.
