### ISSUE TITLE
Uri module doesn't work with IPv6 correctly

### ISSUE THREAD

**Issue by Serpentian** [tarantool/tarantool#9556]
`Uri` module doesn't work correctly with IPv6. According to [RFC 2732](https://www.rfc-editor.org/rfc/rfc2732) uri must be wrapped into `[]` before adding :port. 

1. `Uri` module doesn't parse full address at all:

```
tarantool> uri.parse('http://[FEDC:BA98:7654:3210:FEDC:BA98:7654:3210]:80/index.html')
---
- null
- 'Incorrect URI: expected host:service or /unix.socket'
...

tarantool> u = uri.parse('http://FEDC:BA98:7654:3210:FEDC:BA98:7654:3210:80/index.html')
---
- host: FEDC
  scheme: http
  path: BA98:7654:3210:FEDC:BA98:7654:3210:80/index.html
...

tarantool> uri.format(u)
---
- http://FEDCBA98:7654:3210:FEDC:BA98:7654:3210:80/index.html
...
```

2. `Uri` module doesn't add brackets, when ipv6 is used, in `uri.format`:

```
tarantool> uri.parse('[0:0:0:0:0:0:0:1]:3300')
---
- host: 0:0:0:0:0:0:0:1
  service: '3300'
  ipv6: 0:0:0:0:0:0:0:1
...

tarantool> u = uri.parse('[0:0:0:0:0:0:0:1]:3300')
---
...

tarantool> uri.format(u)
---
- 0:0:0:0:0:0:0:1:3300
...
```

**Comment by Totktonada** [comment]
It likely affects `config`'s code and seems valuable to allow a user to listen on IPv6 sockets.

**Comment by Totktonada** [comment]
The first point is actually that the case-insensitive IPv6 octets parsing was broken by 1376aad9b3fd1fa3c42a220dafeadaa63387f7a2:

* `hex1_4 = ([0-9a-fA-F]{1,4});` is changed to `hex1_4 = ([0-9a-fa-f]{1,4});`
* `ip4_6 = ("[::" [fF][fF][fF][fF] ":" ip4 "]");` was included into the `ip6` rule and `[fF]` becomes `[ff]`.

It seems it was mistakely lowercased together with some surrounding code.

**Comment by Totktonada** [comment]
In fact, not all the IPv6 URI forms from [RFC 3986](https://datatracker.ietf.org/doc/html/rfc3986.html) and [RFC 2373](https://datatracker.ietf.org/doc/html/rfc2373.html) are accepted by our parser. For example, `0:0:0:0:0:0:13.1.68.3` is not accepted.

However, I think that implementing all the variants should be a separate task (if we ever need it).

I propose to fix case-insensitivity in parsing and square brackets in formatting within the scope of this issue.
