### ISSUE TITLE
Cannot build Tarantool on FreeBSD 14.0

### ISSUE THREAD

**Issue by ylobankov** [tarantool/tarantool#9601]
**Bug description**

* OS: FreeBSD
* OS Version: 14.0
* Architecture: x86_64

Tarantool versions where bug was reproduced:
- 3.1.0-entrypoint-32-g00ff0beb9
- 3.0.0-14-g9d74d7ed3
- 2.11.3-entrypoint-35-gcdd512f95
- 2.10.9-entrypoint-66-gd18ac72f4

**Steps to reproduce**

1. `cmake -S . -B . -DCMAKE_BUILD_TYPE=RelWithDebInfo -DENABLE_WERROR=ON -DTEST_BUILD=ON`
2. `cmake --build . --parallel $(nproc)`

**Actual behavior**

```console
...
/usr/include/c++/v1/string_view:220:10: fatal error: '__string/char_traits.h' file not found
#include <__string/char_traits.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
gmake[3]: *** [test/unit/CMakeFiles/rtree_multidim.test.dir/build.make:76: test/unit/CMakeFiles/rtree_multidim.test.dir/rtree_multidim.cc.o] Error 1
...
```

**Expected behavior**

The build is successful.

**Comment by 0x501D** [comment]
Cannot reproduce:

```sh
root@bsd14:~/tarantool # uname -r
14.0-RELEASE
root@bsd14:~/tarantool # git clone https://github.com/tarantool/tarantool.git
root@bsd14:~/tarantool # pkg install libicu
root@bsd14:~/tarantool # pkg install icu
root@bsd14:~/tarantool # cmake -S . -B . -DCMAKE_BUILD_TYPE=RelWithDebInfo -DENABLE_WERROR=ON -DTEST_BUILD=ON
root@bsd14:~/tarantool # cmake --build . --parallel $(nproc)
root@bsd14:~/tarantool # ./src/tarantool --version
Tarantool 3.1.0-entrypoint-32-g9ee99c5ff
```

**Comment by ylobankov** [comment]
> Cannot reproduce (FreeBSD-14.0 amd64 clean install):
> 
> ```shell
> root@bsd14:~/tarantool # uname -r
> 14.0-RELEASE
> root@bsd14:~/tarantool # git clone https://github.com/tarantool/tarantool.git
> root@bsd14:~/tarantool # pkg install libiconv
> root@bsd14:~/tarantool # pkg install icu
> root@bsd14:~/tarantool # cmake -S . -B . -DCMAKE_BUILD_TYPE=RelWithDebInfo -DENABLE_WERROR=ON -DTEST_BUILD=ON
> root@bsd14:~/tarantool # cmake --build . --parallel $(nproc)
> root@bsd14:~/tarantool # ./src/tarantool --version
> Tarantool 3.1.0-entrypoint-32-g9ee99c5ff
> ```

OK, we did upgrade from 13.2 to 14.0. It looks like the problem is somewhere in upgrade procedure.
