### ISSUE TITLE
index:delete() failed

### ISSUE THREAD

**Issue by 0xBF** [tarantool/tarantool#962]
Иногда при нехватке памяти в тарантуле ломается удаление из space'ов. Не проходит ни delete(), ни truncate() с одной и той же ошибкой.

ОС: Debian Wheezy, amd64
Версия: 1.6.5.274.gf84ad58~wheezy-1

Ошибка:
```
some_space.index.primary:delete{1276001}
---
- error: Failed to allocate 16384 bytes in mempool for new slab
```

**Comment by kostja** [comment]
@alyapunov , you fixed it in 1.6.6, and I finished up, but still needs a test case.
