### ISSUE TITLE
Please, add warn logs when iproto.listen URI is not suitable to be connected through in sharding.applier

### ISSUE THREAD

**Issue by ochaton** [tarantool/tarantool#9644]
Subj:
https://github.com/tarantool/tarantool/blob/6ba34da7f840357f2093cf6ee9a0ef2fc0a0f590/src/box/lua/config/instance_config.lua#L169

when `sharding.apply` is executing, it would be nice, if you log.warn parsed URIs from iproto.listen which is declined by config machinery.

It took me 2 hours to investigate what was wrong with config.yaml ;(((

**Comment by Totktonada** [comment]
In a chat discussion Vlad clarifies that he want skipped URIs to be logged as well, not just skipped.

He also said that even just the following error messages in logs would be helpful.

https://github.com/tarantool/tarantool/blob/557567eea41f009bd21aa5b257be349aa1e8a178/src/box/lua/config/instance_config.lua#L169-L186

The problem he searches was in a zero listen port.
