### ISSUE TITLE
Cluster autobootstrap is broken if replication is not identical on all replicas

### ISSUE THREAD

**Issue by bigbes** [tarantool/tarantool#965]
### The problem
Some times (at first start) replicas hangs into read_only (waiting for her uuid to appear in _cluster). And replication hangs up.

How-to:
1. start first tarantool without replication source
2. start second tarantool with `replication_source=first`
3. start third tarantool wirh `replication_source=second`
4. on first tarantool `box.cfg{replication_source=third}`

Replication will hang up.
We need to restart three tarantools to start it up again.

Second scenario - add fourth tarantool into cluster:
1. three point circle replication started
2. start fourth tarantool. `replication_source=third`
3. first tarantool `box.cfg{replication_source=fourth}`

Replication will hang up.
We need to restart three tarantools to start it up again.
### Suggested solution

Implement replication topology discovery and always bounce node join/register commands to the replica set leader. We may need to implement additional message handlers inside relay thread for that:
- bounce the join message to the leader, if relay discovers it's not a leader, and relay the results back to the joined replica

**Comment by rtsisyk** [comment]
The following sequence works for me:

```
tarantool1> box.cfg { listen = 3313 }
tarantool2> box.cfg { listen = 3314, replication_source = 3313 }
tarantool3> box.cfg { listen = 3315, replication_source = 3314 }
tarantool1> box.cfg { replication_source = 3315 }
tarantool1> box.space._schema:insert({'hello'}
```

**Comment by rtsisyk** [comment]
BTW, autobootstrap doesn't work in the following dead loop:

```
tarantool1> box.cfg { listen = 3313, replication_source = 3315 }
tarantool2> box.cfg { listen = 3314, replication_source = 3313 }
tarantool3> box.cfg { listen = 3315, replication_source = 3314 }
```

**Comment by rtsisyk** [comment]
ok, the described scheme above is not supported by autobootstrap. This problem will be fixed by introducing leader election via raft in 1.8 or later versions.

**Comment by rtsisyk** [comment]
Moved to 1.8

**Comment by kostja** [comment]
This should work now. Please add a test case and close the bug.

**Comment by kostja** [comment]
Still repeatable :(

**Comment by rosik** [comment]
@kyukhin @locker Any news on the issue?

**Comment by sergepetrenko** [comment]
Doesn't look like anyone needs this after all these years. Besides, we've got 3 new bootstrap strategies for various use cases: 'supervised', 'config' and 'auto'.

Feel free to reopen if I'm wrong.
