### ISSUE TITLE
upsert qa

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#966]
For all cases of upsert, namely:
- dimension 1: all operation types (+, -, :, =)
- dimension 2: whether an op fails or not
- one or several failing ops per upsert
- post-upsert tuple format validation failure (field count, field types)
- secondary key format validation failure - upsert must be banned in presense of secondary keys (**currently it's not**)
- attempt to modify the primary key in upsert is banned (**currently it is not**): update_read_ops, then check that there are ops on the primary key, ban them before executing update
- update_read_ops failures should prevent upsert from entering the system, not get ignored.

Check that:
- dimension 3: replication works
- dimension 4: recovery from xlog works
- dimension 5: regardless of the storage engine, which is a settable parameter of the test 

A separate test is required for iproto space:
- send upsert packet that has no ops, or ops is not an array, or has no tuple
- check that the server doesn't crash and produces a valid msgpack output

**Comment by alyapunov** [comment]
Now if the key the updating tuple was not found, the operations is totally ignored and thus not checked for errors; and inserting tuple is not tested for compliance with the given key

**Comment by kostja** [comment]
Not seeing a test for an attempt to modify the primary key in upsert.
