### ISSUE TITLE
Support Fedora 22

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#977]
22:10 < avsej> hi everyone. fedora 22 has been released a couple of months ago. 
               could you update repository?
22:10 < avsej> 22 is missing here http://tarantool.org/dist/master/fedora/ 
22:11 < avsej> kostja_osipov, ping
22:12 < kostja_osipov> hi
22:12 < kostja_osipov> ok, thanks

**Comment by Sulverus** [comment]
done. buildbot updated. packages are ready
http://tarantool.org/dist/master/fedora/22/

**Comment by Sulverus** [comment]
+1.6.6 and 1.7 branches
