### ISSUE TITLE
Allow to set trace level in `box.error` and `box.error.new`

### ISSUE THREAD

**Issue by locker** [tarantool/tarantool#9792]
[`box.error`](https://www.tarantool.io/en/doc/latest/reference/reference_lua/box_error/error/) always uses the current level to set the trace:

https://github.com/tarantool/tarantool/blob/567cba8ae7fb1c398d39e7c247466c2c8bd216a1/src/box/lua/error.cc#L193

As a result, the trace becomes useless if `box.error` or `box.error.new` is called from a helper function used to construct errors, as it will always point to the helper function itself. For example,

```lua
-- Helper function that raises an error of type 'MyError' with the given message.
local function my_error(msg)
    box.error{type = 'MyError', message = msg}
end

-- Some function that may raise an error.
local function check_answer(v)
    if v ~= 42 then
        my_error('Bad answer!')
    end
end

local ok, err = pcall(check_answer, 1)
err.trace -- points to my_error, not to my_func, as it should
```

The vanilla function [`error`](https://www.lua.org/pil/8.5.html) has the level argument which can be used to force using a trace from an upper level. We should introduce a similar functionality for `box.error` and `box.error.new`. For example,

```Lua
box.error{type = 'MyError', message = 'Error!', level = 3}
-- or
box.error({type = 'MyError', message = 'Error!'}, 3)
```

**Comment by unera** [comment]
> `box.error{type = 'MyError', message = 'Error!', level = 3}`

I vote the variant :)

**Comment by unera** [comment]
Note: `box.error{..., level = 0}` and `box.error{..., level = nil}` - are the same.

If a user writes a wrapper, he adds its count of wraps to level.

```lua
function my_wrapper1(error) 
   level = error.level or 0
   level = level + 1
   ... -- code

   error.level = level
   return box.error(error)
end

function my_wrapper_on_wrapper1(error)
   level = error.level or 0
   level = level + 1
   ... -- code

   error.level = level
   return my_wrapper1(error)
end
```

So, a user can non-determinated stack of wrappers, so each wrapper could work properly if it adds count of its wraps to `level` (not redefine the value!).

**Comment by Totktonada** [comment]
@unera I want to highlight that in Lua 'this level' is 1. In means that `error('foo')` and `error('foo', 1)` are the same.

```lua
tarantool> function inner(x) error('foo', x) end
tarantool> function outer(x) inner(x) end

tarantool> outer()
---
- error: '[string "function inner(x) error(''foo'', x) end"]:1: foo'
...

tarantool> outer(1)
---
- error: '[string "function inner(x) error(''foo'', x) end"]:1: foo'
...

tarantool> outer(2)
---
- error: '[string "function outer(x) inner(x) end"]:1: foo'
...
```

In the examples above you're using 0 as 'this level' marker, but I think that we should be consistent with Lua here (at least in the Lua API).

**Comment by locker** [comment]
Discussed with @unera. Agreed on the following points:
1. `level` should be passed in the second optional argument to `box.error` and `box.error.new`, **not** as a payload field. Rationale:
   - It's more convenient to catch and re-throw an error with a new level in this case (useful for wrapper functions).
   - Passing the level in a payload field would make it impossible to use `level` as a user-defined payload field.
   - This is consistent with the behavior of the built-in Lua function `error`.
3. `level` should start from 1, **not** from 0, i.e. 1 - the current function (default), 2 - the function calling the current function, and so on; 0 disables trace. This is consistent with the behavior of the built-in Lua function `error`.
4. The `level` argument should be supported in the following cases:
   1. When the first argument is a table, both for `box.error` and `box.error.new`. Then a new error object is constructed with the given level.
   3. When the first argument is an error object, only for `box.error`. Then the stack trace is reset for the given error object according to the given level before throwing it.
