### ISSUE TITLE
Feature `space:format` `default_func` need tuple argument

### ISSUE THREAD

**Issue by a1div0** [tarantool/tarantool#9825]
A simple case is to fill in a default field at the time of recording, but the value of the field depends on other fields of the record:

```lua
box.schema.func.create('default_fingerprint', {
    language = 'Lua',
    body = 'function(_, tuple) return digest.md5(tuple[1] .. tuple[2]) end'
})

box.schema.space.create('test')
box.space.test:create_index('pk')
box.space.test:format({
    {name = 'id', type = 'string'},
    {name = 'value', type = 'string'},
    {name = 'fingerprint', type = 'string', default_func = 'default_fingerprint'}
})
```

**Definition of Done**

An additional argument is passed to the function that generates the default value for the field - the recordable tuple.

**Comment by Gumix** [comment]
Here we have chicken and egg problem — how to fill the fields of the tuple, that is passed as an argument to the function, that fills them. Note that multiple fields can have `default` and/or `default_func`. It's possible to fill them one-by-one, and rebuild the tuple after each field, but it will reduce the performance.

**Comment by a1div0** [comment]
We need some kind of solution. Here in the example there is a non-nullable column `fingerprint` that I would like to fill after the beginning of “replace” or “tt import”, but before checking for null.
Maybe make a trigger?

**Comment by KAPANDR** [comment]
Добавил задачу в бэклог EE 
https://www.notion.so/tarantool/Pass-tuple-as-argument-to-field-s-default_func-8785637fb79f43e4b8ca729e75fc4582
