### ISSUE TITLE
Regenerating C files on every make

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#986]
Generating ../third_party/luafun/fun.lua.c
Generating ../third_party/luajit/src/jit/dis_x64.lua.c
Generating ../third_party/luajit/src/jit/vmdef.lua.c
Generating ../third_party/luajit/src/jit/dump.lua.c
Generating ../third_party/luajit/src/jit/v.lua.c

**Comment by rtsisyk** [comment]
Fixed by @bigbes
