### ISSUE TITLE
Memcached basic operations

### ISSUE THREAD

**Issue by bigbes** [tarantool/tarantool#990]
## Basic Operations
* [x] GET, GETK
* [x] SET, ADD, REPLACE
* [x] DELETE
* [x] INCR, DECR
* [x] PREPEND, APPEND
* [x] TOUCH
* [x] GAT(K) ?

## Administrative operations
* [x] NOOP
* [x] VERSION
* [x] FLUSH
* [x] QUIT

## Tests
* [x] TESTS

**Comment by bigbes** [comment]
GAT(K) operations are (Get and Touch (with Key))

**Comment by bigbes** [comment]
(Get and )Touch - move from update to replace

**Comment by kostja** [comment]
@kostja, @rtsisyk

**Comment by bigbes** [comment]
need: convert tests from perl to python

**Comment by bigbes** [comment]
done on branch `memcached`
