### ISSUE TITLE
`log.info` does not emit file name and line in plain format

### ISSUE THREAD

**Issue by locker** [tarantool/tarantool#9913]
Reproduced with 3.1.0-entrypoint-227-gde80e0264f7d, but it looks like the bug has been there for ages.

Reproducer:

```lua
local log = require('log')
log.cfg{log = 'log.txt'}
log.info('foo')
log.warn('bar')
log.error('buzz')
```

Log:

```
2024-04-05 17:44:33.878 [56006] main/104/test.lua/test I> foo
2024-04-05 17:44:33.878 [56006] main/104/test.lua/test test.lua:4 W> bar
2024-04-05 17:44:33.878 [56006] main/104/test.lua/test test.lua:5 E> buzz
```

Note that the info message lacks the file name and line. This is especially annoying in the scope of PR https://github.com/tarantool/luatest/pull/347, which improved logging in luatest: the PR uses the info log level for logging assertions, which means that they won't include the file name and line.

Interestingly, this bug only affects the plain log format. In the json log format, the file name and line are emitted unconditionally:

```lua
local log = require('log')
log.cfg{log = 'log.txt', format = 'json'}
log.info('foo')
log.warn('bar')
log.error('buzz')
```

Log:

```
{"time": "2024-04-05T17:51:52.305+0300", "level": "INFO", "message": "foo", "pid": 56131 , "cord_name": "main", "fiber_id": 104, "fiber_name": "test.lua", "file": "test.lua", "line": 3, "module": "test"}
{"time": "2024-04-05T17:51:52.305+0300", "level": "WARN", "message": "bar", "pid": 56131 , "cord_name": "main", "fiber_id": 104, "fiber_name": "test.lua", "file": "test.lua", "line": 4, "module": "test"}
{"time": "2024-04-05T17:51:52.305+0300", "level": "ERROR", "message": "buzz", "pid": 56131 , "cord_name": "main", "fiber_id": 104, "fiber_name": "test.lua", "file": "test.lua", "line": 5, "module": "test"}
```

**Comment by Gumix** [comment]
This condition was in `say.c` from the [very beginning](https://github.com/tarantool/tarantool/commit/8cf4386e7998ac6cc00c97cfa15ae2e0c7649f50):

```c
	if (level == S_WARN || level == S_ERROR)
		p += snprintf(buf + p, len - p, " %s:%i", filename, line);
```

OK, let's emit the filename for `S_FATAL`, `S_SYSERROR`, `S_ERROR`, `S_CRIT`, `S_WARN` and `S_INFO`.

What about `S_VERBOSE` and `S_DEBUG`?
