### ISSUE TITLE
Memcached quiet operations

### ISSUE THREAD

**Issue by bigbes** [tarantool/tarantool#992]
* [x] GET(K)Q
* [x] SETQ, ADDQ, REPLACEQ
* [x] DELETEQ
* [x] INCRQ, DECRQ
* [x] QUITQ
* [x] FLUSHQ
* [x] APPENDQ, PREPENDQ
* [x] GATQ, GATKQ

* [x] TESTS

**Comment by kostja** [comment]
@kostja, @rtsisyk

**Comment by bigbes** [comment]
need: convert tests from perl to python

**Comment by bigbes** [comment]
done on branch `memcached`
