### ISSUE TITLE
console: autorequire modules suitable for administration and debugging

### ISSUE THREAD

**Issue by Totktonada** [tarantool/tarantool#9986]
It is convenient to have some built-in modules accessible right after connection to the admin console (using `tt connect`) or after starting a debugging session (using `tarantool -i`).

These are ones from where an admin wants to obtain state information: `compat`, `fiber.info()`, `config:info()`, `config:get()` are such examples. `fun` is often used to filter/transform such information.

There are modules that implement a data type and they're used to write a value of the given type to the database: `uuid`, `datetime`, `decimal`, `varbinary`.

Also, some modules are often used in interactive experimenting: `clock.bench()`, `ffi.cast()` and serializers such as `json`, `yaml`, `msgpack`.

There are function that are useful for debugging: `fio.open(<...>):read()`, `log.info()`, `popen.shell()`.

The proposed list of modules:

* clock
* compat
* config
* datetime
* decimal
* ffi
* fiber
* fio
* fun
* json
* log
* msgpack
* popen
* uuid
* varbinary
* yaml

I propose to don't add these names to globals, but make them accessible only in the interactive console: a code in the Lua files still need to `require` the modules. It is easy to do after implementing console session scoped variables, see #9985.

I propose to autorequire the modules in the interactive console session under the same `console_session_scope_vars` compat option.

**Comment by sergos** [comment]
I feel uneasy because of inconsistency between the console mode and the lua script mode. Namely, things one tried in console doesn't work in a script passed as an argument to the Tarantool.

**Comment by Totktonada** [comment]
@sergos I agree with your point in context of some other differences. For example, #1133 is the great addition that makes the interactive mode quite similar to a Lua file code. As another example, I would like to save locals within a console session to ease copy-paste from Lua files to console. (A usual function in a Lua file has `local`.)

My proposal adds the difference deliberately. Moreover, the goal is to have these shortcuts for the interactive work and have them only in the interactive mode.

Let's look on your doubt more precisely: consider a bad scenario. An application developer wrote some code in a console, debugged it, then copy-pasted it to a Lua file (BTW, I often write code this way).

Let's assume that some of the used modules are not `require`'d.

The copy-pasted code has the following properties:

* `luacheck` warns about a read of an undeclared global.
* The strict mode raises an error on attempt to access an undefined global.
* If the strict ode is disabled, an attempt to use the module (call a function from it) leads to the 'attempt to index nil value' error.

The 'forgot to add `require`' is a typical mistake and it occurs disregarding whether the interactive console allows to omit some of them.

I don't think that we add any UX problem here.

And I'm sure that it makes the interactive debugging/administration more convenient.

**Comment by Totktonada** [comment]
Feedback from @Mons: it would be good to allow to configure the list of default console upvalues.

I propose the following API.

```lua
local console = require('console')

-- A Lua table, filled by the modules as describe above.
console.default_upvalues

-- Refuse the autorequire for a particular module.
console.default_upvalues.fio = nil

-- Add a module to the autorequire list.
console.default_upvalues.mymodule = require('mymodule')
```

The `console.default_upvalues` table is to be copyed into a console session.

**Comment by Mons** [comment]
> I feel uneasy because of inconsistency between the console mode and the lua script mode. Namely, things one tried in console doesn't work in a script passed as an argument to the Tarantool.

There are a lot of runtimes, where imports are omitted and implied for easiness of writing code by hand. And barely someone is annoyed when in the leetcode console they have everything imported, and while copied to the script they require additional imports.
