### ISSUE TITLE
Don't leave box.cfg{}/enter read-write mode before downloading all xlogs from the master

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool#999]
The bootstrap code should be able to detect how much it has fallen behind the master and play the log from the master till that position before binding to the primary port and leaving box.cfg{}.

**Comment by rtsisyk** [comment]
Blocked by #1239 - can't create a proper test case.

**Comment by rtsisyk** [comment]
Already fixed, but there is no test case.

**Comment by rtsisyk** [comment]
replication/status.test.lua after 1dbef1c6780a091a96e9a447399d9f1d4ea4e59d effectively checks this feature for JOIN. SUBSCRIBE is still doesn't wait. Can I close this ticket?

**Comment by kostja** [comment]
The idea of this ticket is that now, when master sends its vclock in response to SUBSCRIBE, box_init_done should not be set to true until applier reached the position of the master in the xlog it received and applied. In other words, the slave should at least fetch stuff that's accumulated on the master since it was off before it enters read-write mode.
